### ISSUE TITLE
[Request] CodeFlask

### ISSUE THREAD

**Issue by kazzkiq** [cdnjs/cdnjs#10008]
**Library name:** CodeFlask.js
**Git repository url:** https://github.com/kazzkiq/CodeFlask.js
**npm package url(optional):** https://www.npmjs.com/package/codeflask
**License(s):** MIT
**Official homepage:** https://kazzkiq.github.io/CodeFlask.js/

**Wanna say something? Leave message here:** 
I've added CodeFlask to npm recently and also started working with [tags](https://github.com/kazzkiq/CodeFlask.js/releases) *(before that the project had to be updated on cndjs manually)*. If there is anything else needed to automate the process from now on, please let me know.

**Comment by maruilian11** [comment]
hi @kazzkiq, we are going to add previous versions before 0.1.0.
I only find 0.0.1 by tracking commit logs. https://github.com/kazzkiq/CodeFlask.js/commit/c82850f74b033cd4d37990e4afae8dc2f93cdcea
Is there any other version I miss before 0.1.0?
Thank you!

**Comment by kazzkiq** [comment]
@maruilian11 Before `0.1.0` there wasn't a real track of what was being updated. So `0.0.1` jumped straight to `0.1.0`, no other versions in between.

So a sum-up of CodeFlask versions are as follow:
- `v0.0.1`
- [`v0.1.0`](https://github.com/kazzkiq/CodeFlask.js/releases/tag/v0.1.0) (Release)
- [`v0.1.1`](https://github.com/kazzkiq/CodeFlask.js/releases/tag/v0.1.1) (Release)
- [`v0.2.0`](https://github.com/kazzkiq/CodeFlask.js/releases/tag/v0.2.0) (Release)

If you need any other info, please let me know. Thanks!

**Comment by maruilian11** [comment]
@kazzkiq thanks! I will add v0.0.1, then close this issue.
If we need any other help, I will notify you.
Feel free to tag us, if you have any request.
