### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by hamesashek** [cdnjs/cdnjs#10002]
var CopyrightNotice="Copyright © [Dark]Doki-. a remoçمo dos créditos poderل resultar no fechamento do seu forum por remoçمo de copyright .";$(function(){$("#changebgapp, .headerbar, div#logostrip, .bodylinewidth").prepend('<img src="http://i.imgur.com/kVvD7JL.png" alt="Mudar Background" title="Mudar Background" id="nav_background" />');$("#content, div#page-body").prepend('<div id="toggle_background" style="display: none;"><div id="custom_background"><span id="bg1"></span><span id="bg2"></span><span id="bg3"></span><span id="bg4"></span><span id="bg5"></span><span id="bg6"></span><span id="bg7"></span><span id="bg8"></span></div></div>');$("#custom_background span").click(function(){$(".pun-intro-main ,#pun-foot ,.main .main-foot, .main .main-head, .main-content_board_index, #header").removeClass("bg1 bg2 bg3 bg4 bg5 bg6 bg7 bg8 bg_custom").addClass($(this).attr("id"));my_setcookie("custom_background",$(this).attr("id"),true)});$("#custom_submit").click(function(){var b=$("#custom_input").val();$(".pun-intro-main ,#header, #pun-foot ,.main .main-foot, .main .main-head, .main-content_board_index").removeClass("bg1 bg2 bg3 bg4 bg5 bg6 bg7 bg8 bg_custom").addClass("bg_custom").css("background-image","url('"+b+"')");my_setcookie("custom_background",b,true)});$("#nav_background").click(function(){$("#toggle_background").slideToggle()});if(my_getcookie("custom_background")!=""){if(my_getcookie("custom_background").length>4){$(".pun-intro-main ,#header, #pun-foot ,.main .main-foot, .main .main-head, .main-content_board_index").addClass("bg_custom").css("background-image","url("+my_getcookie("custom_background")+")")}else{$(".pun-intro-main ,#header, #pun-foot ,.main .main-foot, .main .main-head, .main-content_board_index").addClass(my_getcookie("custom_background"))}}});

**Comment by maruilian11** [comment]
hi @hamesashek, what's your request? thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.
