### ISSUE TITLE
[Request] Add DataTables/Buttons

### ISSUE THREAD

**Issue by jmjpro** [cdnjs/cdnjs#10005]
**Library name:** DataTables/Buttons
**Git repository url:** https://github.com/DataTables/Buttons
**npm package url(optional):** https://www.npmjs.com/package/datatables.net-buttons
**License(s):** MIT
**Official homepage:** https://datatables.net/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by jmjpro** [comment]
Please add DataTables/Buttons

**Comment by maruilian11** [comment]
@PeterDaveHello the author put `buttons.dataTables.min.css` and `dataTables.buttons.min.js` in different git repo, do we need to support multiple repo in auto-update in future? or we just add them as two libs in this kind of case.

**Comment by PeterDaveHello** [comment]
@maruilian11 we will not support that, have you told to the author?

**Comment by maruilian11** [comment]
asked here https://github.com/DataTables/Buttons/issues/110#issuecomment-268954698

**Comment by maruilian11** [comment]
Good news! the author will consider adding minified files in git repo in the new year!
https://github.com/DataTables/Buttons/issues/110#issuecomment-268967317

**Comment by kant2002** [comment]
Looks like @DataTable already done necessary steps to allow you upload package to CDNjs

**Comment by MattIPv4** [comment]
Datatables buttons are available on cdnjs: https://cdnjs.com/libraries/datatables-buttons
