### ISSUE TITLE
[Request] Add firebase

### ISSUE THREAD

**Issue by sayurabh** [cdnjs/cdnjs#10004]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @sayurabh,
do you mean this lib?
https://www.npmjs.com/package/firebase

**Comment by clairetsai818** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Yeah I saw it, but I don't know what's the point do you want me to take a look?

**Comment by extend1994** [comment]
Duplicated and move to #7795
