### ISSUE TITLE
Add param for API limits

### ISSUE THREAD

**Issue by ianberdin** [cdnjs/cdnjs#10017]
Please, add param `limit` for API. Because libs to many and requests will so long...

Like this:

    https://api.cdnjs.com/libraries?search=jquery&fields=name&limit=10

Thank you for good service.

**Comment by PeterDaveHello** [comment]
This feature may need to come with `sortBy` and `page`.

**Comment by happierall** [comment]
I test it, and yes, it's fast :)
Look, cdnjs in 1 component: http://libs.playcode.io.
You can close, but limit will be useful.

**Comment by PeterDaveHello** [comment]
@happierall is this your project? Looks cool, and I think we can implement this feature - limit.

**Comment by PeterDaveHello** [comment]
@happierall is this already a production project? I'll suggest you to force enable https first, then we can push it!

**Comment by PeterDaveHello** [comment]
@PeterDaveHello actually, as you are writing javascript, maybe you can just send a PR to implement the features we mentioned here :)

The source code is at: https://github.com/cdnjs/new-website/blob/master/apiServer.js, wanna give it a try?

**Comment by happierall** [comment]
Yes, production.
HTTPS for what's? It will slow down.

**Comment by PeterDaveHello** [comment]
@happierall that's for security reason, and with http/2.0, I don't think it really slow down, but even faster, and you should note that http://api.cdnjs.com/ will be redirected to use https.

**Comment by happierall** [comment]
About PR - I'm not sure, because, haven't experience with node.js.
Today will add ssl.

вт, 20 дек. 2016 г. в 12:36, Peter Dave Hello <notifications@github.com>:

**Comment by PeterDaveHello** [comment]
@happierall Great! Please also provide the library url via https, btw, is there a public repository on GitHub for this project?

**Comment by happierall** [comment]
SSL added, look: https://playcode.io/libs?tabs=output

вт, 20 дек. 2016 г. в 12:42, Peter Dave Hello <notifications@github.com>:

**Comment by happierall** [comment]
Updated for work only for HTTPS: https://playcode.io/libs?tabs=output
Huh, PlayCode haven't github repository. I'm not sure, that it's needed.

вт, 20 дек. 2016 г. в 13:23, Руслан Янбердин <happierall@gmail.com>:

**Comment by happierall** [comment]
I've added HTTP/2 and it's very cool, thank you for idea.

вт, 20 дек. 2016 г. в 14:14, Руслан Янбердин <happierall@gmail.com>:

**Comment by happierall** [comment]
Tweet for this demo usage cloudflare API:
https://twitter.com/playcode_io/status/811190498169942016

вт, 20 дек. 2016 г. в 15:11, Руслан Янбердин <happierall@gmail.com>:

**Comment by PeterDaveHello** [comment]
@pvnr0082t you can try it

**Comment by happierall** [comment]
Limit? - doesn't work.

пн, 16 янв. 2017 г. в 17:19, Peter Dave Hello <notifications@github.com>:

**Comment by PeterDaveHello** [comment]
@happierall no we didn't implement it yet.

**Comment by happierall** [comment]
Then try what?

**Comment by PeterDaveHello** [comment]
@happierall I didn't tell you to try, you may misunderstand.

**Comment by tholman** [comment]
PR for this here: https://github.com/cdnjs/new-website/pull/192 (using algolias maxPerPage and page params)

**Comment by PeterDaveHello** [comment]
@tholman thanks, I'll take a look!

**Comment by xtuc** [comment]
This behavior was changed recently, please try again. Feel free to open a new issue if needed

**Comment by MattIPv4** [comment]
This has been implemented with the `hitsPerPage` url param. See https://cdnjs.com/api for the full API docs.
