### ISSUE TITLE
[Author] [Request] Zooming

### ISSUE THREAD

**Issue by kingdido999** [cdnjs/cdnjs#10010]
**Library name:** Zooming
**Git repository url:** https://github.com/kingdido999/zooming
**npm package url(optional):** https://www.npmjs.com/package/zooming
**License(s):** MIT
**Official homepage:** http://desmonding.me/zooming/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@dada0423 You can take this.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern @cdnjs/intern2 please help update the title in this case.
