### ISSUE TITLE
[Request] [author] Add vectorious 

### ISSUE THREAD

**Issue by mateogianolio** [cdnjs/cdnjs#10013]
**Library name:** vectorious
**Git repository url:** https://github.com/mateogianolio/vectorious
**npm package url(optional):** https://npmjs.com/package/vectorious
**License(s):** MIT
**Official homepage:** https://github.com/mateogianolio/vectorious
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mateogianolio** [comment]
Fixed: https://github.com/mateogianolio/vectorious/commit/1e830e182f3b81e67c7a8feb8e2234f74066273b

**Comment by PeterDaveHello** [comment]
Thanks @mateogianolio
