### ISSUE TITLE
[Test] Make sure libs are under ajax/libs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10012]
Sometimes contributor put the libraries at the wrong place - `ajax/lib`, then the currently test process will totally miss that library and just let the test pass, I didn't come up with a great solution yet, but maybe we can just make sure there is no other files than `libs` under `ajax`.

**Comment by petrgazarov** [comment]
We can put this in `test/valid-packages-test.js` and catch with `npm test`. What do you think?

**Comment by PeterDaveHello** [comment]
@petrgazarov sure! The part I have done in CI is because if we don't checkout the file into filesystem, `npm test` can't easily detect it and I don't want `npm test` involve git commands, so just write the CI only detection.

**Comment by xtuc** [comment]
The bot will make sure that files land in the ajax/libs directory. Not need to ensure that anymore
