### ISSUE TITLE
[Request] Update to jqplot 1.0.9 

### ISSUE THREAD

**Issue by krheinwald** [cdnjs/cdnjs#10023]
**Library name:** jqplot
**Git repository url:** https://github.com/jqPlot/jqPlot
**npm package url(optional):** 
**License(s):** MIT and GPL version 2.0 licenses
**Official homepage:** http://www.jqplot.com/

**Comment by maruilian11** [comment]
I'll wait for the git tags asking issue few days, then manually add every released version if the git tags won't come up in short period of time.
