### ISSUE TITLE
[Request] Add newsTicker 

### ISSUE THREAD

**Issue by ngtrian** [cdnjs/cdnjs#10020]
**Library name:** JQuery Advanced News Ticker 
**Git repository url:**https://github.com/risq/jquery-advanced-news-ticker
**npm package url(optional):** 
**License(s):**GNU GENERAL PUBLIC LICENSE

**Official homepage:**http://risq.github.io/jquery-advanced-news-ticker/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@sajochiu 
Please add this library.
