### ISSUE TITLE
[Request] angular-tek-progress-bar

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10034]
Library name: angular-tek-progress-bar 
Git repository url: https://github.com/TekVanDo/Angular-Tek-Progress-bar
License(s): MIT
Official homepage: http://tekvando.github.io/Angular-Tek-Progress-bar/

**Comment by x09326** [comment]
@sashberd 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

cc @PeterDaveHello

**Comment by sashberd** [comment]
I understand , in future I will request to add libraries by suggested popularity
