### ISSUE TITLE
[Request] angular-ui/ui-codemirror

### ISSUE THREAD

**Issue by psamit** [cdnjs/cdnjs#10032]
**Library name:** angular-ui/ui-codemirror
**Git repository url:** https://github.com/angular-ui/ui-codemirror
**npm package url(optional):**  https://www.npmjs.com/package/angular-ui-codemirror
**License(s):** MIT
**Official homepage:** https://angular-ui.github.io/ui-codemirror/

**Comment by x09326** [comment]
@lcd78706 
Please add this library.
