### ISSUE TITLE
jsPlumb is not up to date

### ISSUE THREAD

**Issue by DedicatedManager** [cdnjs/cdnjs#10030]
How do I request for jsPlumb to get updated?  

cdnjs is currently showing 2.0.7  
https://cdnjs.com/libraries/jsPlumb

But the git repository is showing 2.2.8
https://github.com/jsplumb/jsPlumb

**Comment by DedicatedManager** [comment]
I'm not the creator, nor am I strongly versed in git, but I believe the needed files are in the dist/js folder.  

I believe when a new version is uploaded, the dist/js folder will be updated to the latest js files.
https://github.com/jsplumb/jsPlumb/tree/master/dist/js

Currently its these two files:
https://github.com/jsplumb/jsPlumb/blob/master/dist/js/jsPlumb-2.2.8-min.js
https://github.com/jsplumb/jsPlumb/blob/master/dist/js/jsPlumb-2.2.8.js

Does your system have a way of looking for the latest files and automatically adding them?

Thanks much!

**Comment by kennynaoh** [comment]
Thanks @DedicatedManager . Yes, we have auto-update mechanism to update the latest release on CDNJS.

**Comment by DedicatedManager** [comment]
@kennynaoh - I looks like you added changes, but I'm not seeing them on the cdnjs page for it.  What I"m seeing still just has 2.0.7 and 1.4.1.    Should it have updated by now?  (I'm fairly new to all this so I'm not fully following/understanding what is happening with your replies above - any explanation would help me collaborate better in the future).

https://cdnjs.com/libraries/jsPlumb

**Comment by PeterDaveHello** [comment]
@DedicatedManager the PR is under review, will be there soon.

**Comment by PeterDaveHello** [comment]
Once we added it, we'll close this issue, sorry for your waiting.
