### ISSUE TITLE
[Request] Add ckan.js

### ISSUE THREAD

**Issue by loleg** [cdnjs/cdnjs#10033]
**Library name:** ckan.js
**Git repository url:** https://github.com/okfn/ckan.js
**npm package url(optional):** https://www.npmjs.com/package/ckan
**License(s):** MIT
**Official homepage:** https://github.com/okfn/ckan.js

**Comment by x09326** [comment]
@loleg 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host this one!

**Comment by x09326** [comment]
@lcd78706 
You can add this library, thanks.

**Comment by loleg** [comment]
Many thanks to @PeterDaveHello @lcd78706 @x09326 ! With tip of the hat to library author @rufuspollock
