### ISSUE TITLE
[Request] angular-simple-logger

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10035]
**Library name: angular-simple-logger
**Git repository url: https://github.com/nmccready/angular-simple-logger 
**License(s): MIT
**Official homepage: http://nmccready.github.io/angular-simple-logger/example/

**Comment by x09326** [comment]
@sashberd 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's host it.

**Comment by sashberd** [comment]
Thanks guys

**Comment by nmccready** [comment]
Also for some stats. https://npm-stat.com/charts.html?package=angular-simple-logger&from=2016-01-26&to=2017-01-26

**Comment by nmccready** [comment]
I'll probably be doing a major merge from a fork soon. Where the version will get bumped to 1.X .

**Comment by sashberd** [comment]
@PeterDaveHello When I click on angular simple logger link after search it is not redirects to it

**Comment by PeterDaveHello** [comment]
@sashberd hmmm ... interesteing, thanks for your report, I'll fix it

**Comment by sashberd** [comment]
@PeterDaveHello Thanks
