### ISSUE TITLE
[Request] Update jquery-easing

### ISSUE THREAD

**Issue by kevindb** [cdnjs/cdnjs#10047]
**Library name:** jquery-easing
**Git repository url:** https://github.com/gdsmith/jquery.easing/
**npm package url(optional):** 
**License(s):** [BSD](https://github.com/gdsmith/jquery.easing/blob/master/LICENSE)
**Official homepage:** http://gsgd.co.uk/sandbox/jquery/easing/

The version 1.3 of the library is already being hosted at https://cdnjs.com/libraries/jquery-easing
There is a new 1.4.1 version available on Github: https://github.com/gdsmith/jquery.easing/blob/1.4.1/jquery.easing.min.js

Thank you

**Comment by PeterDaveHello** [comment]
See #10014 , thanks

**Comment by kevindb** [comment]
#10014 seems to be referencing the old/existing version 1.3. I'm asking to have the version 1.4.1 that's available on Github to be added,

**Comment by PeterDaveHello** [comment]
Once the auto-update config applied, the new version will be fetched automatically. I'll reopen this first until we added v1.4.1

**Comment by clairetsai818** [comment]
@kevindb @PeterDaveHello This library is automatically updated to v1.4.1.
https://cdnjs.com/libraries/jquery-easing/1.4.1

**Comment by PeterDaveHello** [comment]
v1.4.1 added in https://github.com/cdnjs/cdnjs/commit/8c7938a8ad7d44e80f41ccb842a550a04b74752e#diff-e9ebd8c2a7999178d50a816bfda89eb6, closing now.

**Comment by kevindb** [comment]
Thank you, all!
