### ISSUE TITLE
[Request] Add jQuery-Visibly

### ISSUE THREAD

**Issue by mitazake** [cdnjs/cdnjs#10052]
jQuery-Visibly
https://github.com/DanielRivers/jQuery-Visibly.
MIT License
http://danielrivers.com/visibly/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@mitazake 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

cc @PeterDaveHello

**Comment by x09326** [comment]
Close due to no response
