### ISSUE TITLE
[Request] Add angular-http-auth 

### ISSUE THREAD

**Issue by JohnGalt1717** [cdnjs/cdnjs#10056]
**Library name:** angular-http-auth
**Git repository url: https://github.com/witoldsz/angular-http-auth
**npm package url(optional):** 
**License(s): unknown
**Official homepage: https://github.com/witoldsz/angular-http-auth

Almost required for openidconnect/oauth and angular.

**Comment by hare1039** [comment]
@pvnr0082t Can I add this library?

**Comment by pvnr0082t** [comment]
@hare1039 Sure, take it please.
