### ISSUE TITLE
[Request] react-toolbox

### ISSUE THREAD

**Issue by tonyhhyip** [cdnjs/cdnjs#10069]
**Library name: React Toolbox https://github.com/react-toolbox/react-toolbox** 
**Git repository url: https://github.com/react-toolbox/react-toolbox**
**npm package url(optional): https://www.npmjs.com/package/react-toolbox** 
**License(s): MIT**
**Official homepage: http://react-toolbox.com/**
**Wanna say something? Leave message here: Please add this**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by plxel** [comment]
+1!
