### ISSUE TITLE
[Request] Add evaporateJS 

### ISSUE THREAD

**Issue by mhenkel1** [cdnjs/cdnjs#10061]
**Library name:** evaporateJS
**Git repository url:** https://github.com/TTLabs/EvaporateJS
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please add this library, thanks.
