### ISSUE TITLE
[Request] Add pug.js

### ISSUE THREAD

**Issue by RedHatter** [cdnjs/cdnjs#10060]
**Library name:** pug.js 
**Git repository url:** https://github.com/pugjs/pug
**npm package url(optional):** pug
**License(s):** MIT
**Official homepage:** http://pugjs.org
**Wanna say something? Leave message here:** This library was previously name jade (which is already in cdnjs) but with the release of 2.0 was renamed to pug.

**Comment by yukulele** [comment]
👍

**Comment by PeterDaveHello** [comment]
@yukulele @RedHatter do you know what are the files should be hosted on CDN?

**Comment by clairetsai818** [comment]
@PeterDaveHello Should I add a new lib named "pug" or rename the old library?

**Comment by PeterDaveHello** [comment]
@clairetsai818 let's add as a new library, and update description of the old one to let the users know that there is a new one.

**Comment by PeterDaveHello** [comment]
@maruilian11 please help take care of this issue, thanks.

**Comment by yukulele** [comment]
pugjs authors don't want we use pug client side https://github.com/pugjs/pug/issues/2655

**Comment by PeterDaveHello** [comment]
@yukulele hmmm, that's the bad news :(

**Comment by MattIPv4** [comment]
Pug is not built to be run in a browser, closing.
