### ISSUE TITLE
[Request] Add bootstrap-combined.min.css 

### ISSUE THREAD

**Issue by rbkpro** [cdnjs/cdnjs#10070]
**Library name:** bootstrap-combined.min.css
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @rbkpro , is there any detail? This issue will be closed if no response in 7 days.

**Comment by rbkpro** [comment]
@pvnr0082t Well, I tried to find the bootstrap-combined.min.css file, bcz I'm using the Bootstrap V2.
So it seems that the file doesn't exist.
thank u.

**Comment by pvnr0082t** [comment]
@rbkpro So, is there any public repository information or something?

**Comment by rbkpro** [comment]
//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css

**Comment by sashberd** [comment]
@PeterDaveHello What we should do with this one?

**Comment by PeterDaveHello** [comment]
hmmm @rbkpro the url is not a repository, please give us more information about this library, thanks.

**Comment by sufuf3** [comment]
Maybe he did mean this link https://github.com/jdorfman/bootstrap-cdn/blob/master/bootstrap-v204/css/bootstrap-combined.min.css
But there is no git tag.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello  This link is from cdn of bootstrap. Should we host hosting?

**Comment by MattIPv4** [comment]
No progress, closing.
