### ISSUE TITLE
[Request] Add Rtlit

### ISSUE THREAD

**Issue by m1reminder** [cdnjs/cdnjs#10093]
**Library name:** Rtlit
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by m1reminder** [comment]
RTLit Library 
Transform CSS files to RTL.

**Comment by clairetsai818** [comment]
Hi @m1reminder 
Are there any details about this library?

**Comment by clairetsai818** [comment]
@m1reminder Do you mean this?
https://github.com/zohararad/rtlit

**Comment by clairetsai818** [comment]
Hi @m1reminder !
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello
