### ISSUE TITLE
[Request] Add phaser 

### ISSUE THREAD

**Issue by miyaxu** [cdnjs/cdnjs#10092]
**Library name:** phaser
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Any details? Thanks!

**Comment by maruilian11** [comment]
@miyaxu please provide the git repo url or npm package url.
this issue will be closed if there is no any response in next 7 days.

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Still no response from requested. Suggest to close

**Comment by extend1994** [comment]
Close due to no response.
