### ISSUE TITLE
[Request] Add rivescript

### ISSUE THREAD

**Issue by pleabargain** [cdnjs/cdnjs#10090]
**Library name:**rivescript
**Git repository url:**
https://github.com/aichaos/rivescript-js
**npm package url(optional):** https://www.npmjs.com/package/rivescript
**License(s):**
**Official homepage:**
https://www.rivescript.com
**Wanna say something? Leave message here:**
easy to use chatbot builder

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t Can I add this library?

**Comment by pvnr0082t** [comment]
@hare1039 The author doesn't put browserified files on GitHub repo. I think you can try to discuss if it's possible to put `dist` folder on GitHub with author.

**Comment by hare1039** [comment]
@pvnr0082t The `dist` folder doesn't exist in the github repo, but in the npm it do exist after version 1.1.8. Maybe I can use npm auto-update. What do you think?

**Comment by pvnr0082t** [comment]
@hare1039 There is `dist` folder after v1.12.2 not v1.1.8. Okay, go ahead. :+1:
