### ISSUE TITLE
[Request] Main.js For Wordpress

### ISSUE THREAD

**Issue by mucahiddayan** [cdnjs/cdnjs#10099]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message

 here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail here?

**Comment by sashberd** [comment]
@PeterDaveHello Still no details. Suggest to close

**Comment by PeterDaveHello** [comment]
@sashberd nice catch! Next time you found a request without any useful info and without response for more than 2 weeks, please feel free to close it directly, just remember to mention the reason why you close it in the comment in case we don't know what happened, and just for the record, thanks!

**Comment by sashberd** [comment]
@PeterDaveHello I am a new one in organization and I think it is to early for me to delete issues. As you can understand , I am going thought old issues and trying to find those one that could be closed or added quick without problems like no gittag, unsupported files etc. cause we have to much like those. May be we can create labels like "Suggest to close" and you or other team members will run over it once a week and close or not close issues like this?

**Comment by PeterDaveHello** [comment]
@sashberd brilliant idea! I'll create it, but you don't need to be afraid to close issue, as you can see, we always try to confirm with issuer first, if they don't provide useful info and do not respond, what we can do is to close it :)

**Comment by sashberd** [comment]
@PeterDaveHello Greta. Ping me when it will ready

**Comment by PeterDaveHello** [comment]
@sashberd I think it's already done :P

**Comment by sashberd** [comment]
@PeterDaveHello  I saw it! Already in use  😃
