### ISSUE TITLE
chai link typo

### ISSUE THREAD

**Issue by herrjemand** [cdnjs/cdnjs#10091]
When looking for chai on cdnjs, i found that link on the front page had typo:
[https://cdnjs.cloudflare.com/ajax/libs/chai/3.5.0/**hai**.min.js](https://cdnjs.cloudflare.com/ajax/libs/chai/3.5.0/hai.min.js)
![_175](https://cloud.githubusercontent.com/assets/1636116/21487654/75335e84-cc33-11e6-8f1e-ddb2ec2ffdec.png)

Other links are not affected

**Comment by PeterDaveHello** [comment]
Fixed, thanks @herrjemand

**Comment by herrjemand** [comment]
@PeterDaveHello oh nice. What was the issue?

**Comment by PeterDaveHello** [comment]
@herrjemand deployed a testing code in accident :(

**Comment by herrjemand** [comment]
@PeterDaveHello XD

You mean this commit? 
https://github.com/cdnjs/new-website/commit/201aec6ff3748c95eda17087ce9d24321d914c7a

**Comment by PeterDaveHello** [comment]
@herrjemand Nope, this is the correct one.

**Comment by herrjemand** [comment]
@PeterDaveHello that's what I mean.*)

**Comment by herrjemand** [comment]
You got there just before I did XD
