### ISSUE TITLE
[Request] Add AjaxFileUpload 

### ISSUE THREAD

**Issue by saikiranmarripati** [cdnjs/cdnjs#10096]
**Library name:** AjaxFileUpload
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Any details? Thanks!

**Comment by maruilian11** [comment]
@saikiranmarripati please provide the git repo or npm package url.
this issue will be closed if there is no any response in next 7 days. thanks.

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Still no response from requester. Suggest to close
