### ISSUE TITLE
[Request] Add js-xss 

### ISSUE THREAD

**Issue by coffeebite** [cdnjs/cdnjs#10098]
**Library name:** js-xss
**Git repository url:** https://github.com/leizongmin/js-xss
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://jsxss.com
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@sajochiu please help me add this library.
