### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by mucahiddayan** [cdnjs/cdnjs#10100]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

As Kanye West said:

> We're living the future so
> the present is our past.

1. Item 1
2. Item 2
3. Item 3
   * Item 3a
   * Item 3b

* Item 1
* Item 2
  * Item 2a
  * Item 2b

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@mucahiddayan, please provide the details of repository, such git repository url, thanks!

**Comment by extend1994** [comment]
Hello @mucahiddayan Could you please provide further infos?

**Comment by maruilian11** [comment]
Hi @mucahiddayan, we will close this issue temporarily. If you still want to add the lib, we will reopen it. Thanks.
