### ISSUE TITLE
[Request] Add finderJS 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10113]
**Library name:** finderJS
**Git repository url:** https://github.com/mynameistechno/finderjs
**License(s):** MIT

Need to ask for bundled distribution/release.

**Comment by mynameistechno** [comment]
It's on npm FYI https://www.npmjs.com/package/finderjs and there's a release as well https://github.com/mynameistechno/finderjs/releases

**Comment by clairetsai818** [comment]
Could you also upload the pre-built files [here](https://github.com/mynameistechno/finderjs) 'cause we  can only fetch the files here through our auto-update. Thanks!
