### ISSUE TITLE
[Request] Add Sliiide 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10112]
**Library name:** Sliiide
**Git repository url:** https://github.com/ahmedrad/sliiide
**Official homepage:** https://ahmedrad.github.io/sliiide/

License info ned to be confirmed

**Comment by ahmedrad** [comment]
Updated license info on the repo, sorry for the late reply

**Comment by PeterDaveHello** [comment]
Thanks a lot @ahmedrad
