### ISSUE TITLE
[Request] Add CSS-Mint 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10114]
**Library name:** CSS-Mint
**Git repository url:** https://github.com/ArunMichaelDsouza/CSS-Mint
**npm package url(optional):**  https://www.npmjs.com/package/css-mint
**License(s):** MIT
**Official homepage:** https://arunmichaeldsouza.github.io/CSS-Mint/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by vanessa-bell** [comment]
Hi! I'd like to help out with this. It'll be my first time contributing to an open source project.

**Comment by PeterDaveHello** [comment]
@vanessa-bell Cool, feel free to ask for help if you need!  We are happy to help you.

**Comment by dakshshah96** [comment]
Hey @vanessa-bell, happy to help if you still want to contribute!

**Comment by vanessa-bell** [comment]
Sorry, I don't have the bandwidth to contribute right now after all. Thanks for offering to help me out! Maybe I can contribute in another way in the future :)

**Comment by dakshshah96** [comment]
Sure, no problem at all 😄

**Comment by PeterDaveHello** [comment]
@vanessa-bell you can try to add the library via single package.json like #11083, do it on GitHub web gui doesn't need high bandwidth.

**Comment by vanessa-bell** [comment]
Thanks @PeterDaveHello! No reason not to give it a try :)

**Comment by PeterDaveHello** [comment]
@vanessa-bell nice
