### ISSUE TITLE
[Request] Add jquery-toast-plugin 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10118]
**Library name:** jquery-toast-plugin
**Git repository url:** https://github.com/kamranahmedse/jquery-toast-plugin/
**npm package url(optional):** jquery-toast-plugin
**License(s):** MIT
**Official homepage:** http://kamranahmed.info/toast

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by matthewfrost** [comment]
Hi,

I'd like to give this a go as my first contribution to open source development. Total noob to this but I can follow instructions and give it a go

**Comment by PeterDaveHello** [comment]
@matthewfrost Cool, feel free to ask for help, we are happy to help you finish it.

**Comment by matthewfrost** [comment]
@PeterDaveHello If I'm adding a library in the ajax/libs directory does that mean I need to checkout the entire libs directory?

**Comment by pvnr0082t** [comment]
@matthewfrost You can try to use sparsesCheckout by following: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md. You don't need to checkout entire libs.

**Comment by PeterDaveHello** [comment]
Also, it is possible to only add one single package.json on GitHub gui :smile:

**Comment by PeterDaveHello** [comment]
@matthewfrost is there any update here?

**Comment by sashberd** [comment]
[Duplicate](https://cdnjs.com/libraries/jquery-toast-plugin). Suggest to close
