### ISSUE TITLE
[Request] Add filex.init.js 

### ISSUE THREAD

**Issue by dincerkurnaz** [cdnjs/cdnjs#10125]
**Library name:** filex.init.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@dincerkurnaz could you also provide the git repository url or npm package url? Thank you!

This issue will be closed if there is no any response in next 7 days.

**Comment by maruilian11** [comment]
close due to no response.
