### ISSUE TITLE
[Request] Add asciidoctor-js 

### ISSUE THREAD

**Issue by nrayapati** [cdnjs/cdnjs#10129]
**Library name:** asciidoctor-js
**Git repository url:** https://github.com/asciidoctor/asciidoctor.js
**npm package url(optional):** https://www.npmjs.com/package/asciidoctor.js
**License(s):** MIT License
**Official homepage:** http://asciidoctor.org/
**Wanna say something? Leave message here:** This is very useful for all of the JavaScript developers of Asciidoctor. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nrayapati** [comment]
Thanks everyone for working this issue. @sufuf3 @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@nrayapati You're welcome.
