### ISSUE TITLE
[Request] Add tslib

### ISSUE THREAD

**Issue by weblucaseduardo** [cdnjs/cdnjs#10128]
**Library name:** tslib (from microsoft)
**Git repository url:** https://github.com/Microsoft/tslib
**npm package url(optional):** https://www.npmjs.com/package/tslib
**License(s):** Apache License
**Official homepage:** https://github.com/Microsoft/tslib
**Wanna say something? Leave message here:** important library for typescript users

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t

**Comment by weblucaseduardo** [comment]
hi, Is there anything I can do to speed up this?

**Comment by pvnr0082t** [comment]
@weblucaseduardo If you can help us resolve https://github.com/Microsoft/tslib/issues/23 and https://github.com/Microsoft/tslib/issues/24, it will be really good! Thanks. :smile:
