### ISSUE TITLE
[Request] tween.js

### ISSUE THREAD

**Issue by windofwind** [cdnjs/cdnjs#10123]
Library name: tween.js
Git repository url: https://github.com/tweenjs/tween.js/
npm package url(optional): https://npmjs.org/package/tween.js
License(s): MIT
Official homepage: https://github.com/tweenjs/tween.js
Wanna say something? Leave message here:

add 16.4

**Comment by PeterDaveHello** [comment]
16.4 is not released yet

**Comment by PeterDaveHello** [comment]
cc #8678 #8674

**Comment by PeterDaveHello** [comment]
npm still v16.3.5, maybe we could transfer to git auto-update.
