### ISSUE TITLE
[Request] Add primeng files for angular 2 app

### ISSUE THREAD

**Issue by tamatcho** [cdnjs/cdnjs#10134]
**Library name:** primeng
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@tamatcho do you mean this lib? https://github.com/primefaces/primeng

**Comment by tamatcho** [comment]
Thanks for replying, I'm developing an angular 2 app and want to load dependencies from a cdn like cdnjs.cloudflare.com but I did not find primeng there.

**Comment by tamatcho** [comment]
In fact I don't want to have my dependencies local

**Comment by tamatcho** [comment]
Yes I mean this lib primefaces/primeng

**Comment by maruilian11** [comment]
@tamatcho Thanks for your quick reply. As you can see, there are so many lib waiting to be added to cdnjs. It's may take some time to add this lib.
