### ISSUE TITLE
utils-wbc

### ISSUE THREAD

**Issue by front-wbc** [cdnjs/cdnjs#10142]
**Library name: utils-wbc
**Git repository url:https://github.com/front-wbc/utils-js
**npm package url(optional):** 
**License(s):**
**Official homepage:https://github.com/front-wbc/utils-js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Merci de lire le README.md pour avoir plus d'informations

c'est une petite classe JS qui rassembler tous les fonctions utilitaires qui peuvent etre réutilisable au sein de même projet ou sur d'autres projets.

**Comment by maruilian11** [comment]
Hi @front-wbc, 
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by maruilian11** [comment]
close due to no response.
