### ISSUE TITLE
[Request] Add angular-fontselect

### ISSUE THREAD

**Issue by ddtch** [cdnjs/cdnjs#10140]
**Library name:** angular-fontselect
**Git repository url:** https://github.com/Jimdo/angular-fontselect
**npm package url(optional):** https://www.npmjs.com/package/angular-fontselect
**License(s):** The MIT License
**Official homepage:** https://github.com/Jimdo/angular-fontselect
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t Can I add this library?

**Comment by PeterDaveHello** [comment]
@hare1039 I'll assign you some.

**Comment by PeterDaveHello** [comment]
@pvnr0082t I already assigned some others.

**Comment by pvnr0082t** [comment]
Okay. Thanks.

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.
