### ISSUE TITLE
[Request] Add Split.js

### ISSUE THREAD

**Issue by simonmysun** [cdnjs/cdnjs#10154]
**Library name:** Split.js
**Git repository url:** https://github.com/nathancahill/Split.js
**npm package url(optional):** https://www.npmjs.com/package/split.js
**License(s):** https://github.com/nathancahill/Split.js/blob/master/LICENSE.txt
**Official homepage:** http://nathancahill.github.io/Split.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 
Please add this library, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 please pick older issues first.

**Comment by PeterDaveHello** [comment]
@simonmysun :smile:
