### ISSUE TITLE
Card library not updated

### ISSUE THREAD

**Issue by schang933** [cdnjs/cdnjs#10155]
The latest release of [Card](https://github.com/jessepollak/card/releases) is ~~2.1.0~~ 2.1.1, but it seems [cdnjs](https://cdnjs.com/libraries/card) is still on version 1.3.2.

I'm not sure if cdnjs operates on push/pull so I can only bring up the issue.

FYI @jessepollak

**Comment by PeterDaveHello** [comment]
@schang933 thanks for report, fixed.

**Comment by schang933** [comment]
👍  @PeterDaveHello Thanks for the quick response!

**Comment by PeterDaveHello** [comment]
No problem, just give it 5~10 mins to be deployed.
