### ISSUE TITLE
[Request] Add fullcalendar-scheduler 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10156]
**Library name:** fullcalendar-scheduler
**Git repository url:** https://github.com/fullcalendar/fullcalendar-scheduler
**License(s):** Multiple:
https://github.com/fullcalendar/fullcalendar-scheduler/blob/v1.5.0/LICENSE.md
**Official homepage:** https://fullcalendar.io/scheduler/

**Comment by sashberd** [comment]
@PeterDaveHello Waiting for your suggestion [here](https://github.com/fullcalendar/fullcalendar-scheduler/issues/384)
