### ISSUE TITLE
[Request] Please update what-input to version 3.x & 4.x

### ISSUE THREAD

**Issue by jesper-dk** [cdnjs/cdnjs#10168]
**Library name: what-input ** 
**Git repository url: https://github.com/ten1seven/what-input **
**NPM: https://www.npmjs.com/package/what-input **

what-input is a dependency for Zurb Foundation, and others. what-input is already on CDNJS, with version 2.1.1 being the latest hosted. Since then what-input has had stable releases in its 3.x and 4.x branches.

**Comment by kennynaoh** [comment]
LGTM

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's give this kind of issue high priority label.
