### ISSUE TITLE
[intern3] Request a new library

### ISSUE THREAD

**Issue by x09326** [cdnjs/cdnjs#10165]
First request a library for intern 3

- [ ]  DragDrop https://github.com/kbjr/DragDrop #10604
- [x]  Peppermint https://github.com/wilddeer/Peppermint
- [x]  Weld https://github.com/tmpvar/weld
- [x]  xStore https://github.com/florian/xStore #10602
- [x]  rssi https://github.com/mvasilkov/rssi #10601
- [x]  nanoajax https://github.com/yanatan16/nanoajax
- [ ]  mag.js https://github.com/magnumjs/mag.js #10603
- [x]  fermata https://github.com/natevw/fermata
- [x]  clone https://github.com/pvorb/clone
- [x]  FastActive https://github.com/jonathanstark/FastActive

**Comment by PeterDaveHello** [comment]
One another reference: https://github.com/callmenick

**Comment by x112358** [comment]
xStore

**Comment by lcd78706** [comment]
clone

**Comment by sajochiu** [comment]
fermata

**Comment by honestree** [comment]
FastActive

**Comment by hare1039** [comment]
Animating-Hamburger-Icons

**Comment by sajochiu** [comment]
mag.js

**Comment by sufuf3** [comment]
Peppermint

**Comment by NiniHsu** [comment]
rssi

**Comment by lcd78706** [comment]
DragDrop

**Comment by qwe19272375** [comment]
Weld

**Comment by lcd78706** [comment]
nanoajax

**Comment by PeterDaveHello** [comment]
@sufuf3 please help check the checkbox if the lib was added already.

**Comment by sufuf3** [comment]
Done

**Comment by MattIPv4** [comment]
We no longer have interns working on cdnjs, closing.
