### ISSUE TITLE
[Request] Unicode CLDR JSON data

### ISSUE THREAD

**Issue by Mottie** [cdnjs/cdnjs#10160]
This request might be outside of the scope of CDNJS, but I thought it was worth a shot.

[Unicode CLDR](http://cldr.unicode.org/index) data is needed for globalization. The [Globalize library](https://github.com/globalizejs/globalize) uses this data in its internationalization and localization tools. Currently, to get the data, globalize uses [npm](https://www.npmjs.com/package/cldr-data-downloader) to download the [zip files](http://www.unicode.org/Public/cldr/30.0.3/) directly from the unicode server, and then expand and save all 250+ megabytes of files locally.

The main issue is that most of the time you don't need the entire data set to get what you need. The folks at Unicode do not plan on providing the unzipped JSON data through a CDN ([ref](http://unicode.org/pipermail/cldr-users/2014-April/000030.html)); but they do have all of the JSON files saved in their GitHub [unicode-cldr organization](https://github.com/unicode-cldr) across 30+ repositories (only 19 are necessary if you want to provide the "full" data set; which includes the "modern" packages).

So my questions are:
* Would it be possible to provide JSON only data through CDNJS?
* Can you combine the data across 19 repositories into one location, or would it be easier to gather updates directly from the six [zip files](http://www.unicode.org/Public/cldr/30.0.3/) provided by the unicode server?
* Even the combined "popularity" of each GitHub data repo does not meet the needed requirement of 100 stars/watchers to be added to CDNJS, but [Globalize](https://github.com/globalizejs/globalize) does meet it.

**Library name:** Unicode CLDR JSON Data
**Git repository url:** 

[CLDR-JSON](https://github.com/unicode-cldr/cldr-json) has the following list of repositories that contain data which would need to be included (only showing "full" packages):
* https://github.com/unicode-cldr/cldr-core
* https://github.com/unicode-cldr/cldr-dates-full
* https://github.com/unicode-cldr/cldr-cal-buddhist-full
* https://github.com/unicode-cldr/cldr-cal-chinese-full
* https://github.com/unicode-cldr/cldr-cal-coptic-full
* https://github.com/unicode-cldr/cldr-cal-dangi-full
* https://github.com/unicode-cldr/cldr-cal-ethiopic-full
* https://github.com/unicode-cldr/cldr-cal-hebrew-full
* https://github.com/unicode-cldr/cldr-cal-indian-full
* https://github.com/unicode-cldr/cldr-cal-islamic-full
* https://github.com/unicode-cldr/cldr-cal-japanese-full
* https://github.com/unicode-cldr/cldr-cal-persian-full
* https://github.com/unicode-cldr/cldr-cal-roc-full
* https://github.com/unicode-cldr/cldr-localenames-full
* https://github.com/unicode-cldr/cldr-misc-full
* https://github.com/unicode-cldr/cldr-numbers-full
* https://github.com/unicode-cldr/cldr-rbnf
* https://github.com/unicode-cldr/cldr-segments-modern (no "full" package)
* https://github.com/unicode-cldr/cldr-units-full

**License:** [Unicode license](https://github.com/unicode-cldr/cldr-json/blob/master/LICENSE)
**Official homepage:** http://cldr.unicode.org/index

CC: @rxaviers

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs @terinjokes

**Comment by drewfreyling** [comment]
Do we even support .json files on the cdn right now?

**Comment by Mottie** [comment]
Every repo should have a `package.json`.

**Comment by drewfreyling** [comment]
@Mottie they do but the return a 403 Forbidden currently.

**Comment by Mottie** [comment]
Hmm, that I don't know... but I do see a 403 message when I try to read a `package.json` in a root folder 😞

**Comment by PeterDaveHello** [comment]
@drewfreyling we don't, need help from Cloudflare, since we don't run our own origin server right now.

**Comment by pkra** [comment]
> @drewfreyling: Do we even support .json files on the cdn right now?
> @PeterDaveHello: @drewfreyling we don't, need help from Cloudflare, since we don't run our own origin server right now.

Should this be a separate issue?

**Comment by terinjokes** [comment]
@pkra No.

**Comment by pkra** [comment]
> terinjokes added Server - configuration Under Consideration labels

Thanks!

**Comment by terinjokes** [comment]
I plan on adding JSON (and source maps) to the allowed content types.

**Comment by pkra** [comment]
Any news on this, @terinjokes ?

**Comment by zorkow** [comment]
Will we get that soon? The problem for us is, that the generation of MathJax's speech output is partially broken, which very much affects accessibility.

**Comment by pkra** [comment]
@terinjokes any news on this? It would be great to finally have json files supported no cdnjs.

**Comment by PeterDaveHello** [comment]
@MattIPv4 would you please help contact with Cloudflare again by the support ticket to see if there is any possibility that we can have it? Thanks a lot.

**Comment by MattIPv4** [comment]
@PeterDaveHello What needs to be done by them, just adding JSON files to the whitelist?

**Comment by PeterDaveHello** [comment]
@MattIPv4 yes, you're right!

**Comment by MattIPv4** [comment]
@Mottie @pkra @PeterDaveHello This has been resolved as part of #13145 and .json files are now served on the cdnjs.cloudflare.com domain 🎉
