### ISSUE TITLE
[Request] Add dna.js 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10176]
**Library name:** dna.js
**Git repository url:** https://github.com/dnajs/dna.js
**License(s):** MIT
**Official homepage:** http://dnajs.org

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by karan-96** [comment]
@PeterDaveHello Hello. I am a beginner. i would like to work on this issue.

**Comment by PeterDaveHello** [comment]
@karan-96 cool!

**Comment by karan-96** [comment]
@PeterDaveHello  i am checking out ajax/libs using 
$ echo '/ajax/libs/*' >> .git/info/sparse-checkout
and i am following this guide
https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md .
after receiving objects,it is taking a lot of time in checking out files(approx 35 lakh files).
Will it take that much time or am i doing something wrong?
Thank you.

**Comment by PeterDaveHello** [comment]
@karan-96 you don't need to add ` '/ajax/libs/*'` into `.git/info/sparse-checkout`, it'll cause to checkout all the libraries, I think you can use ` '/ajax/libs/jquery` instead, just checkout jquery as reference lib.

**Comment by karan-96** [comment]
@PeterDaveHello 
1.do i need to create a separate branch for pull request or can  i use the master branch of my forked repository
2.when i am creating a pull request it is asking  
# Essential checklist
 * [ ] I'm the author of this library
   * [ ] I would like to add link to the page of this library on CDNJS on website / readme
 * [ ] This lib was not found on cdnjs repo
 * [] No already exist / duplicated issue and PR
 * [ ] The lib has notable popularity
   * [ ] More than 100 [Stars / Watchers / Forks] on [GitHub / Bitbucket]
   * [ ] More than 500 downloads stats per month on npm registry
 * [ ] Project has public repository on famous online hosting platform (or been hosted on npm)

# Auto-update checklist
 * [ ] Has valid tags for each versions (for git auto-update)
 * [ ] Auto-update setup
 * [ ] Auto-update target/source is valid.
 * [ ] Auto-update filemap is correct.

how should i respond to it when i am not sure about most of these.

**Comment by PeterDaveHello** [comment]
@karan-96 

1. You should always create a new branch for the pull request
2. For the checklist items you are not sure, feel free to ask, but I think most of it could be found by yourself, just need to take few more minutes. For example, you are not the author of the library you are going to add, so you will not check `I'm the author of this library `, there popularity on its GitHub page: watch: 13, star: 83, fork: 17, so that you can check `The lib has notable popularity `, and its child item, just something like that.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 please also help @karan-96 finish his PR, thanks.
