### ISSUE TITLE
[Request] Add prelodr 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10179]
**Library name:** prelodr
**Git repository url:** https://github.com/joseluisq/prelodr
**npm package url(optional):**  prelodr
**License(s):** MIT

**Comment by extend1994** [comment]
The library's popularities are listed below.
 * GitHub popularity:
   - Count of watchers: 6
   - Count of stars: 59
   - Count of forks: 16
 * NPM download stats:
   - Downloads in the last day: 7
   - Downloads in the last week: 65 
   - Downloads in the last month: 296
@PeterDaveHello Should we add this library?

**Comment by PeterDaveHello** [comment]
Yes, let's do it.

**Comment by joseluisq** [comment]
Awesome ! :+1:
