### ISSUE TITLE
[Request] Add _supersized_ 

### ISSUE THREAD

**Issue by leandro-gomez** [cdnjs/cdnjs#10178]
**Library name:** supersized
**Git repository url:** https://github.com/buildinternet/supersized
**npm package url(optional):** 
**License(s):** GPL/MIT
**Official homepage:** http://buildinternet.com/project/supersized/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t What should we do if naming that includes version number like `supersized.core.3.2.1.js`?

**Comment by PeterDaveHello** [comment]
@hare1039 manually change them of old versions, contact with author to discuss about the possiblity to remove them

**Comment by MattIPv4** [comment]
Library no longer maintained, closing.
