### ISSUE TITLE
[Request] Add jquery-animateNumber

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10188]
Library name: jquery-animateNumber
Git repository url: https://github.com/aishek/jquery-animateNumber
npm package url(optional): https://github.com/aishek/jquery-animateNumber
License(s): MIT
**Official homepage: https://github.com/aishek/jquery-animateNumber
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @helantao  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
Duplicated with #9990. I'm going to close this issue. Thanks for your contribution. @helantao

**Comment by helantao** [comment]
Why this library is not updated

**Comment by pvnr0082t** [comment]
@helantao This library is still working in progress.

**Comment by helantao** [comment]
@pvnr0082t This is a very good library, there are a lot of users submit requests upload. But why hasn't been

**Comment by pvnr0082t** [comment]
@helantao There are so many popular libraries and we will add them if someone requested. Now it's going to be hosted by CDNJS. You can take a look at #10055. We will make this merge ASAP. Thank you. :+1:
