### ISSUE TITLE
[Request] Add jPut

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10189]
Library name: jPut
Git repository url: https://github.com/shabeer-ali-m/jPut
npm package url(optional): https://github.com/shabeer-ali-m/jPut
License(s): MIT
Official homepage: https://github.com/shabeer-ali-m/jPut
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @helantao  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by helantao** [comment]
Well, there really isn't enough of a star or download, but it doesn't prevent it from being a very good library. Well, it can't be submitted to CDNJS, right?

**Comment by sashberd** [comment]
@PeterDaveHello Once the request of this library was closed #6659 due to low popularity. Today`s, it is still low popularity, thus should we add it or close the request

**Comment by PeterDaveHello** [comment]
@helantao sorry but our signal of a good library is its popularity and the lib seems not under maintenance for a while, feel free to create new issue once it reaches our requirement, thanks.
