### ISSUE TITLE
[Request] Add FrontPress

### ISSUE THREAD

**Issue by teles** [cdnjs/cdnjs#10187]
**Library name:** FrontPress
**Git repository url:** https://github.com/frontpressorg/frontpress
**npm package url(optional):** https://www.npmjs.com/package/frontpress
**License(s):** MIT
**Official homepage:** https://github.com/frontpressorg/frontpress
**Wanna say something? Leave message here:**

Only the [release files](https://github.com/frontpressorg/frontpress/tree/master/release) should be avaliable via cdn. 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @teles ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by teles** [comment]
Thank you @pvnr0082t . Sorry for not reading the readme before opening this issue. 
I'll wait for FrontPress to have notable popularity and then I create a new PR for cdnjs.

**Comment by PeterDaveHello** [comment]
We can host this one :smile:

**Comment by PeterDaveHello** [comment]
@teles would you like to send a pull request to add it?

**Comment by teles** [comment]
For sure, @PeterDaveHello ! Im going to read [the contributions file](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) and then I will send a PR using auto update. 
I hope to do it this weekend.

**Comment by PeterDaveHello** [comment]
@teles Great! Feel free to let us know where can we help you!
