### ISSUE TITLE
[Request] Add vue-select 

### ISSUE THREAD

**Issue by prozacsf84** [cdnjs/cdnjs#10184]
**Library name:** vue-select
**Git repository url:** https://github.com/sagalbot/vue-select
**npm package url(optional):** https://www.npmjs.com/package/vue-select
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please add this library.
