### ISSUE TITLE
[Request] Add jquery-sparkle

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10190]
Library name: jquery-sparkle
Git repository url: https://github.com/maxspeicher/jquery-sparkle
npm package url(optional): https://github.com/maxspeicher/jquery-sparkle
License(s): MIT
Official homepage: https://github.com/maxspeicher/jquery-sparkle
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @helantao  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by helantao** [comment]
Well, there really isn't enough of a star or download, but it doesn't prevent it from being a very good library. Well, it can't be submitted to CDNJS, right?

**Comment by sashberd** [comment]
Still no popularity Suggest to close

**Comment by sufuf3** [comment]
@helantao Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). Also there is no git tag.
Thanks for your great work and contribution.

I'll close this issue. cc @PeterDaveHello 

@sashberd Thanks
