### ISSUE TITLE
[Request] Add tiny-date-picker 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10199]
**Library name:** tiny-date-picker
**Git repository url:** https://github.com/chrisdavies/tiny-date-picker
**npm package url(optional):** tiny-date-picker
**License(s):** MIT
**Official homepage:** https://chrisdavies.github.io/tiny-date-picker/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by ArmenAvetisyan** [comment]
Hi, @PeterDaveHello!

I want to start to contribute to open source projects like this.
Can you help me to add the lib using GitHub GUI?

From what I understand from reading your instructions, I'll need to provide into [ajax/libs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs) new folder named _tiny-date-picker_ plus **package.json** file.

So, will I need to grab this one: [package.json](https://github.com/chrisdavies/tiny-date-picker/blob/master/package.json)?

Thanks

**Comment by PeterDaveHello** [comment]
Hi @ArmenAvetisyan !

Of course, I'll be happy to help you!

You are correct that you'll need to create that folder with `package.json`, you can just grab it from upstream, and then add `filename` and `auto-update` config, so that we can carry on to fetch the files, but please remove sections like `devDependencies`, `bugs`, `main` and `scripts` since we don't use it on CDNJS, you'll also need to remove `version` since there is no any version but a **package.json**!

Hope this would help you! Good luck!

@pvnr0082t and @kennynaoh will also help you if you need :)

**Comment by PeterDaveHello** [comment]
@armenavetisyan sorry that we didn't get any response from you for a while so we'll take this PR/issue, feel free to pick another one when you have time, thanks.
