### ISSUE TITLE
[Request] Add Rellax.js

### ISSUE THREAD

**Issue by p-realinho** [cdnjs/cdnjs#10191]
**Library name:** Rellax
**Git repository url:** https://github.com/dixonandmoe/rellax
**npm package url(optional):** https://www.npmjs.com/package/rellax
**License(s):** MIT
**Official homepage:** https://dixonandmoe.com/rellax/
**Wanna say something? Leave message here:**

@dixonandmoe (Authors)

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
@PeterDaveHello This library has already existed in cdnjs.

**Comment by PeterDaveHello** [comment]
@p-realinho looks like we have the latest version on CDNJS now, is there anything else we can do?

**Comment by maruilian11** [comment]
@p-realinho this issue will be closed if there is no any response in next 7 days. thanks.

**Comment by p-realinho** [comment]
@PeterDaveHello @maruilian11 @clairetsai818 
Sorry, I completely forgot to reply. 
That's all, you can go ahead and close it.
Thank you for your time.
