### ISSUE TITLE
[Request] Add material-datetime-picker 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10207]
**Library name:** material-datetime-picker
**Git repository url:** https://github.com/ripjar/material-datetime-picker
**npm package url(optional):**  https://www.npmjs.com/package/material-datetime-picker
**License(s):** MIT
**Official homepage:** https://ripjar.github.io/material-datetime-picker/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by calandraz** [comment]
I'd like to give this a shot if that's ok!

**Comment by PeterDaveHello** [comment]
@calandraz of course, welcome to join and feel free to ask for help when you need it!

**Comment by calandraz** [comment]
@PeterDaveHello so I got started...was able to figure out sparse-checkout but I am adding a new file so how do I add new files to the repo without cloning the entire repo?

**Comment by PeterDaveHello** [comment]
@calandraz so do you want to just send the pull request on GitHub gui? Or you still want to use command line locally?

**Comment by calandraz** [comment]
Well I was trying to do it locally (for the learning aspect of it)

**Comment by PeterDaveHello** [comment]
@calandraz so the steps are all the same, just don't forget to add `/ajax/libs/material-datetime-picker/` to `.git/info/sparse-checkout`

**Comment by calandraz** [comment]
Oh, ok...I'll give it a try thanks @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
@calandraz any news here?

**Comment by calandraz** [comment]
So sorry, I moved to a new state and started a new job. Last few months
have been very busy. If anyone wants to take my datetime - picker issue, go
for it!

**Comment by PeterDaveHello** [comment]
@calandraz thanks for your updates!

**Comment by gururajbn** [comment]
@PeterDaveHello can i take this issue for first PR?

**Comment by gururajbn** [comment]
@PeterDaveHello created a PR, please review.
