### ISSUE TITLE
[Request] Add simple-hint 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10204]
**Library name:** simple-hint
**Git repository url:** https://github.com/catc/simple-hint/
**License(s):** MIT
**Official homepage:** https://catc.github.io/simple-hint/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by rajpatel507** [comment]
can I work on this one?

I have few query working with Github GUI.
- how can I run npm test if i commit change using github GUI?
- In documentation it mention that i have to commit whole change in one commit but i am not able to find way to do it from github GUI(like adding folder and file into new folder in one commit)?
- how to get multiple build version from new repo(they mostly have latest)?

thanks in advance for help.

**Comment by PeterDaveHello** [comment]
Hi @rajpatel507, sure you can take it, @kennynaoh will help you.

 - you can't run `npm test` online but you can just take a look at the ci test result
 - if you can't upload all the files in a single commit, we can squash the commits for you, no worry
 - by auto-update, we'll grab the other releases, you only need to add the latest one

👍

**Comment by rajpatel507** [comment]
@PeterDaveHello, I have commuted change in my local fork but i am not able to test it with CI as authentication with my github account is not working(it went on continuous loop.) ,
Do anyone have ever encounter with same issue?

**Comment by PeterDaveHello** [comment]
@rajpatel507 just send a pull request and the ci will be triggered automatically!
