### ISSUE TITLE
[Request] Change plottable.js to plottable

### ISSUE THREAD

**Issue by CalvinFernandez** [cdnjs/cdnjs#10208]
Hey cdnjs ppl! Starting with plottable 2.6, can we deprecate the `plottable.js` lib name in favor of simply `plottable` ?

**Comment by PeterDaveHello** [comment]
@CalvinFernandez Any reson for it? Directly change the library name will cause current users' website broken.

**Comment by CalvinFernandez** [comment]
@PeterDaveHello , we're standardizing on the Plottable name. If possible it would be great to keep the existing `plottable.js` namespace up untill 2.6 and then use plottable after. Does that sound reasonable?

**Comment by PeterDaveHello** [comment]
Yes, but I wonder if it worth to add the new named one as a new library? Won't it be easier to just keep its name so that the origin users can easily upgrade? We also have some libraries have this kind of case that still keeps their name on CDNJS, what do you think?

**Comment by CalvinFernandez** [comment]
@PeterDaveHello yea it would definitely be easier, it just sounds more confusing to have both plottable.js and plottable running in parallel when they're the same. If having both plottable.js and plottable is something that you're okay with then I also don't mind

**Comment by PeterDaveHello** [comment]
hmmmm, I actually prefer to use its origin name, but not keep two different one, if they share the same repo and development history, just the name changed.

**Comment by CalvinFernandez** [comment]
I'm not sure I follow: so you're saying you want one name in the repo?

**Comment by PeterDaveHello** [comment]
@CalvinFernandez yes, I think it's easier and better to keep using `plottable.js`

**Comment by sashberd** [comment]
Is this issue solved?
