### ISSUE TITLE
[Request] once

### ISSUE THREAD

**Issue by zaclummys** [cdnjs/cdnjs#10212]
**Library name:** once
**Git repository url:** https://github.com/zaclummys/once
**npm package url(optional):** 
**License(s):** MIT License

**Comment by clairetsai818** [comment]
Hi @zaclummys ,
This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look on our README.md for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by clairetsai818** [comment]
close due to no response
