### ISSUE TITLE
[intern3] Open an issue to discuss with author

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#10211]
Some information we need are not so precise, so you should discuss with the library author.

- [x] artDialog #10159 
- [ ] tslib #10128 
- [x] Sliiide #10112 
- [x] codaslider #10571 
- [x] milojs #10340 
- [x] aquarelle #10310 
- [ ] Unsplash Source JS #9900 
- [x] PlanOut.js #9188
- [x] NicEdit #8653

**Comment by sajochiu** [comment]
NicEdit

**Comment by x112358** [comment]
Sliiide

**Comment by lcd78706** [comment]
reframe.js

**Comment by honestree** [comment]
reframe.js

**Comment by NiniHsu** [comment]
artDialog

**Comment by honestree** [comment]
aquarelle

**Comment by sufuf3** [comment]
codaslider

**Comment by hare1039** [comment]
PlanOut.js

**Comment by lcd78706** [comment]
tslib

**Comment by extend1994** [comment]
Close because all information was confirmed.
