### ISSUE TITLE
[Request] es5-string-binder

### ISSUE THREAD

**Issue by hyunjun19** [cdnjs/cdnjs#10216]
**Library name:** es5-string-binder
**Git repository url:** https://github.com/hyunjun19/es5-string-binder
**npm package url(optional):** https://www.npmjs.com/package/es5-string-binder
**License(s):** MIT
**Official homepage:** https://hyunjun19.github.io/es5-string-binder/
**Wanna say something? Leave message here:** thank u cdnjs

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @hyunjun19 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by PeterDaveHello** [comment]
Close due to no response.
