### ISSUE TITLE
[Request] Add dojo 1.11.3

### ISSUE THREAD

**Issue by beeant0512** [cdnjs/cdnjs#10213]
**Library name:** dojo version 1.11.3
**Git repository url:** https://github.com/dojo/dojo.git
**npm package url(optional):** 
**License(s):** BSD
**Official homepage:** http://dojotoolkit.org/

**Comment by dylans** [comment]
This will be redundant with #10349 when that is addressed.

**Comment by PeterDaveHello** [comment]
Since there are more details in  #10349, so just moved to  #10349, thanks.
