### ISSUE TITLE
[Request] Add Semantic-UI-Calendar 

### ISSUE THREAD

**Issue by ethanpil** [cdnjs/cdnjs#10229]
**Library name:** Semantic-UI-Calendar
**Git repository url:** https://github.com/mdehoog/Semantic-UI-Calendar
**npm package url(optional):** https://www.npmjs.com/package/semantic-ui-calendar
**License(s):** MIT License
**Official homepage:** https://github.com/mdehoog/Semantic-UI-Calendar
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
close due to merged. 71b3c5f5eaee45b7eea83ceafda5ff5de24fb8a1
