### ISSUE TITLE
[Request] Add imagehover.css

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10223]
Library name: https://github.com/ciar4n/imagehover.css/
Git repository url: https://github.com/ciar4n/imagehover.css/
npm package url(optional): https://github.com/ciar4n/imagehover.css/
License(s): MIT
Official homepage: http://imagehover.io/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by helantao** [comment]
This is a very good library, but why has not been uploaded

**Comment by PeterDaveHello** [comment]
@helantao feel free to send a pull request to add this lib.

**Comment by hare1039** [comment]
duplicate with #10046

**Comment by hare1039** [comment]
duplicate with #10046 , @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@hare1039 you should 1) confirm that we already had the latest version, 2) confirm with the issuer he/she is satisfied with it before close it.

**Comment by hare1039** [comment]
@PeterDaveHello Got it.
@helantao Is there anything we should improve?

**Comment by hare1039** [comment]
@helantao This issue will close if no response in next 7 days.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
