### ISSUE TITLE
[Request] Add jsm 

### ISSUE THREAD

**Issue by jitesh-ahuja** [cdnjs/cdnjs#10220]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@jitesh-ahuja 
Could you provide some details like git repo url?

**Comment by sashberd** [comment]
Still no response from issue author. Suggest to close

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
Thanks @sashberd
