### ISSUE TITLE
[Request] moment-business-days

### ISSUE THREAD

**Issue by dushyantbangal** [cdnjs/cdnjs#10228]
**Library name:** moment-business-days
**Git repository url:** https://github.com/kalmecak/moment-business-days
**npm package url(optional):** https://www.npmjs.com/package/moment-business-days
**License(s):** MIT

**Comment by hare1039** [comment]
Hi @dushyantbangal,
It seems this library isn't a client-side library. Would you like to give us more detail about the file you want to host?
Thank you.

**Comment by dushyantbangal** [comment]
I don't really know much about the package. I have used it on server side, wanted to use it in angular js.  Its dependent on `moment.js` which has client as well as server library.

**Comment by hare1039** [comment]
@dushyantbangal Hmm yes, the [moment.js](https://cdnjs.com/libraries/moment.js) did have cilent side, but not `moment-business-days`. Unless the author provide client side js files, we can't host `moment-business-days` as it serve as server side library.
@pvnr0082t Would you please help me with doing a double confirm of this library is a server side library?

**Comment by pvnr0082t** [comment]
>This plugin is for using in NodeJS

@hare1039 It seems like it connot compatible with browser.

**Comment by hare1039** [comment]
@dushyantbangal As CDNJS can only host client side library, We are sorry that we can't host this library. Thank you for interesting in CDNJS.

@pvnr0082t Thank you. Shall we close this issue?

**Comment by pvnr0082t** [comment]
@hare1039 You can ask if the author would like to make it compatible with the browser. Then determine if we can host this lib.

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close sine there is no progress from author on request add git tag and time passed from current request was opened

**Comment by hare1039** [comment]
https://github.com/kalmecak/moment-business-days/issues/23
The author confirm that this library is compatible with the browser after version `1.0.4`
