### ISSUE TITLE
[Request] Add css-loader

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10222]
Library name: https://github.com/raphaelfabeni/css-loader
Git repository url: https://github.com/raphaelfabeni/css-loader
**npm package url(optional):** 
License(s): MIT
Official homepage: http://www.raphaelfabeni.com.br/css-loader/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by helantao** [comment]
This is a very good library, but why has not been uploaded

**Comment by PeterDaveHello** [comment]
@helantao feel free to send a pull request to add this lib.

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.
