### ISSUE TITLE
[Request] Add phaser-ce 

### ISSUE THREAD

**Issue by photonstorm** [cdnjs/cdnjs#10227]
**Library name:** Phaser CE
**Git repository url:** https://github.com/photonstorm/phaser-ce
**npm package url(optional):** https://www.npmjs.com/package/phaser-ce
**License(s):** MIT
**Official homepage:** http://phaser.io
**Wanna say something? Leave message here:**

Phaser has split into two versions: The main one (which you kindly host under cdnjs/phaser) and this new Community Edition (Phaser CE) which it'd be great if you could host as well. Although the CE Github repo is very new (only set-up today) we believe over time it could become as popular as the main Phaser one.

**Comment by PeterDaveHello** [comment]
Maybe just follow the auto-update config from `phaser`?

**Comment by swirly** [comment]
have you a release date planned for phaser ce now you have the response ?

**Comment by PeterDaveHello** [comment]
We'll take care of it soon.

**Comment by sufuf3** [comment]
@PeterDaveHello As readme.md say, 
Phaser 2.6.2 is the last 'official' release, published on npm as `phaser`
Phaser 2.7.0 and all future versions have been given to the community to maintain, published on npm as `phaser-ce`.
ref: https://github.com/photonstorm/phaser-ce#whats-new

Should I update the auto-update of `phaser` or add new library which named `phaser-ce`?

Please give me some suggestions, thank you.

**Comment by photonstorm** [comment]
Add it as a new library (`phaser-ce`) please, because while 2.6.2 is our last official v2 release, we are busy working on v3 now and will see a release shortly. Phaser CE has been picked up by the community and they've been really busy, releasing loads of great versions, and are actively maintaining it, which is why I feel it's a good _separate_ addition to CDNJS.

**Comment by sufuf3** [comment]
@photonstorm Thank you. I'll add a new library as `phaser-ce`
