### ISSUE TITLE
[Request] Add artDialog

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10221]
Library name: https://github.com/aui/artDialog
Git repository url: https://github.com/aui/artDialog
npm package url(optional): https://github.com/aui/artDialog
License(s): LGPL
Official homepage: https://github.com/aui/artDialog
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by helantao** [comment]
This is a very good library, but why has not been uploaded

**Comment by PeterDaveHello** [comment]
@helantao feel free to send a pull request to add this lib.

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by pvnr0082t** [comment]
ping @dada0423

**Comment by pvnr0082t** [comment]
@qwe19272375 Please take over this.
