### ISSUE TITLE
[Request][Author] Add Snowflake

### ISSUE THREAD

**Issue by PenetratingShot** [cdnjs/cdnjs#10235]
**Library name:** Snowflake
**Git repository url:** https://github.com/penetratingshot/snowflake
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://usesnowflake.ml/
**Wanna say something? Leave message here:**
I've been working on this for some time now. It's just an animations library built with Jquery. CSS coming soon. (BTW I'm doing this on a Raspberry Pi cuz my computer broke.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @PenetratingShot 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by sashberd** [comment]
Still no popularity. Suggest to close

**Comment by sufuf3** [comment]
@PenetratingShot Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). Also there is no git tag.
Thanks for your great work and contribution.

I'll close this issue. cc @PeterDaveHello

@sashberd Thanks
