### ISSUE TITLE
[Request] Add angular-aria 

### ISSUE THREAD

**Issue by NewWorldMan** [cdnjs/cdnjs#10246]
**Library name:** angular-aria
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @NewWorldMan  any details?

**Comment by PeterDaveHello** [comment]
Duplicated with #10244
