### ISSUE TITLE
[Request] Add angular-animate 

### ISSUE THREAD

**Issue by NewWorldMan** [cdnjs/cdnjs#10245]
**Library name:** angular-animate
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @NewWorldMan , is there any detail? This issue will be closed if no response in 7 days.

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by dknell** [comment]
FYI - anyone looking for this, it's listed under the angular library. i.e. for angular.js:
https://cdnjs.com/libraries/angular.js
