### ISSUE TITLE
[Request] Strapdown.js

### ISSUE THREAD

**Issue by cryogenx** [cdnjs/cdnjs#10249]
**Library name:** Strapdown.js
**Git repository url:**https://github.com/arturadib/strapdown
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://strapdownjs.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please help solve this issue, thanks.

**Comment by sashberd** [comment]
@sufuf3  @PeterDaveHello Suggest to close since there is no answer from author on request add git tag and time passed from current request was opened
