### ISSUE TITLE
[Request] Angular-gridster

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10240]
**Library name: Angular-gridster
**Git repository url: https://github.com/ManifestWebDesign/angular-gridster/tree/master
**npm package url(optional): 
**License(s): MIT
**Official homepage: http://manifestwebdesign.github.io/angular-gridster/
**Wanna say something? Leave message here: Very nice dashboard library to use in angular

**Comment by sashberd** [comment]
Improved version of above library can be taken from here [https://raw.githubusercontent.com/arkabide/angular-gridster/dynamic-colums/src/angular-gridster.js](url)

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 
Is there is a way to add version from master and version from upgraded fork?

**Comment by PeterDaveHello** [comment]
@sashberd not labeled files from master means under development, not a static/formal release, which is not good. Upgraded forked can be considered, just make sure it has enough popularity, and we can name the library on CDNJS with author namesapce like "PeterDaveHello-jQuery" to recognize it's forked version(if the fork has changed its name, without the name conflict, we don't even need to use namesapce style naming here!).
