### ISSUE TITLE
[Request] Add angular-aria 

### ISSUE THREAD

**Issue by NewWorldMan** [cdnjs/cdnjs#10244]
**Library name:** angular-aria
**Git repository url:** https://github.com/angular/angular.js
**npm package url(optional):** https://www.npmjs.com/package/angular-aria
**License(s):** MIT
**Official homepage:** https://angularjs.org/

**Comment by kennynaoh** [comment]
@NewWorldMan  Any details?

**Comment by NewWorldMan** [comment]
Sorry, I thought I had added it when I made this request. It was for angular-material.

**Comment by kennynaoh** [comment]
What you mean is this? https://cdnjs.com/libraries/angular-material

**Comment by maruilian11** [comment]
@NewWorldMan this issue will be closed if there is no any response. thanks.

**Comment by extend1994** [comment]
Library info updated.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/angular-aria
