### ISSUE TITLE
[Request] Add shadydom 

### ISSUE THREAD

**Issue by noopole** [cdnjs/cdnjs#10243]
**Library name:** shadydom
**Git repository url:** https://github.com/webcomponents/shadydom
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @noopole 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by noopole** [comment]
Sure I'll do.
Actually it's a spilt (in the same time that a new version) from the [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) polyfill that has 1946 stars so may it could inherit them.
Anyway thank you for your answer.

**Comment by PeterDaveHello** [comment]
LGTM, let's host it!
