### ISSUE TITLE
[Request] Add jQuery Teletype Plugin 

### ISSUE THREAD

**Issue by martinzuern** [cdnjs/cdnjs#10255]
**Library name:** jQuery Teletype Plugin
**Git repository url:** https://github.com/stvwhtly/jquery-teletype-plugin
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @martinzuern 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by martinzuern** [comment]
Sure.

**Comment by PeterDaveHello** [comment]
Let's host it!
