### ISSUE TITLE
[Request] Add rainbow linenumber 

### ISSUE THREAD

**Issue by RichyHBM** [cdnjs/cdnjs#10267]
**Library name:** rainbow linenumber
**Git repository url:** https://github.com/Sjeiti/rainbow.linenumbers
**npm package url(optional):** 
**License(s):** Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0
**Official homepage:** https://github.com/Sjeiti/rainbow.linenumbers
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @RichyHBM 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by RichyHBM** [comment]
Sure, sorry I hadn't noticed that!
