### ISSUE TITLE
angular-ui-router

### ISSUE THREAD

**Issue by galdar0809** [cdnjs/cdnjs#10264]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @galdar0809 any details?

**Comment by maruilian11** [comment]
@galdar0809 please provide the git repo url or npm package url.
this issue will be closed if there is no any response in next 7 days.

**Comment by rnemec** [comment]
The latest version available on cdnjs is 1.0.3 while the current release is 1.0.6. Is anybody working on this? Did something break recently?

**Comment by sufuf3** [comment]
@rnemec Thank you for reminding.
it seems that npm package move to https://www.npmjs.com/package/@uirouter/angularjs
I'll update this lib ASAP.

**Comment by sufuf3** [comment]
close and move to #11713
