### ISSUE TITLE
[Request] Add filamentgroup/loadCSS

### ISSUE THREAD

**Issue by bartvanhoutte** [cdnjs/cdnjs#10265]
**Library name:** loadCSS
**Git repository url:** https://github.com/filamentgroup/loadCSS
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/filamentgroup/loadCSS

**Comment by pvnr0082t** [comment]
Duplicated with #7961. I'm going to close this issue. @bartvanhoutte Thanks for your contribution.
