### ISSUE TITLE
[Request] bootstrap-markdown-editor

### ISSUE THREAD

**Issue by seanc** [cdnjs/cdnjs#10268]
**Library name:** bootstrap-markdown-editor
**Git repository url:** https://github.com/inacho/bootstrap-markdown-editor
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://inacho.github.io/bootstrap-markdown-editor/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh
