### ISSUE TITLE
[Request] openWeather

### ISSUE THREAD

**Issue by laisgomes** [cdnjs/cdnjs#10266]
**Library name:openWeather
**Git repository url:https://github.com/michael-lynch/open-weather
**npm package url(optional):** 
**License(s):https://github.com/michael-lynch/open-weather/blob/master/LICENSE.md
**Official homepage:**
**Wanna say something? Leave message here: This is lib have a easy functionality.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh
