### ISSUE TITLE
[Request] Add indexeddbshim 

### ISSUE THREAD

**Issue by houd1ni** [cdnjs/cdnjs#10261]
**Library name:** indexeddbshim
**Git repository url:**  https://github.com/axemclion/IndexedDBShim
**npm package url(optional):**  indexeddbshim
**License(s):** Apache-2.0 
**Official homepage:**  https://github.com/axemclion/IndexedDBShim
**Wanna say something? Leave message here:** Why it still isn't here? Strange. Thank you.

**The lib maps requests to IndexedDB to WebSQL for browsers like safari (with buggy IDB implementation) and those, that doesn't support IDB natively at all.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please add this library.

**Comment by brettz9** [comment]
We have now released version 3.0.0 (a new though breaking version). Would be a great service to have this new version available too, thanks!

**Comment by PeterDaveHello** [comment]
@brettz9 of course, see: 0e9936afc3432afad64d0601af2ff0a68c2af57f
