### ISSUE TITLE
[Request] Add ui-tinymce

### ISSUE THREAD

**Issue by garyfagan1987** [cdnjs/cdnjs#10262]
**Library name:** ui-tinymce
**Git repository url:** https://github.com/angular-ui/ui-tinymce
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please add this library.
