### ISSUE TITLE
[Request] Add "Logdown"

### ISSUE THREAD

**Issue by bennyn** [cdnjs/cdnjs#10272]
**Library name:** Logdown 
**Git repository url:** https://github.com/caiogondim/logdown.js
**npm package url(optional):** https://www.npmjs.com/logdown
**License(s):** MIT
**Official homepage:** http://caiogondim.github.io/logdown.js/
**Wanna say something? Leave message here:** Loving your service!

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@kennynaoh any update?

**Comment by bennyn** [comment]
We (the Logdown team) were asked to maintain a `.min.js` file, which we now do: https://github.com/caiogondim/logdown.js/issues/79 😃

**Comment by maruilian11** [comment]
@bennyn thank you~ But there are lots of libs waiting to be added, It may takes some time to add this one. Sorry for that 😓

**Comment by sashberd** [comment]
@bennyn Hi man,
I am going to work on this request now. 
Question: I saw that only from version 2.0.0 there is a file with name logdown.js, before there is only index.js files.
Should we add versions before 2.0.0?

**Comment by bennyn** [comment]
@sashberd Thanks for getting in touch. Let me add @caiogondim to this discussion. He is the core maintainer of logdown. There is a version 3 now! 😃

**Comment by sashberd** [comment]
Hi @caiogondim , please help us with question above in order to move forward with add your library. Thanks

**Comment by caiogondim** [comment]
Only v2.0+ is ok.
And thanks for adding the library.
