### ISSUE TITLE
[Request] cookie-banner

### ISSUE THREAD

**Issue by rmnblm** [cdnjs/cdnjs#10275]
**Library name:** cookie-banner
**Git repository url:** https://github.com/dobarkod/cookie-banner
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/dobarkod/cookie-banner
**Wanna say something? Leave message here:** With CDNJS, the cookie-banner could also support SSL.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@rmnblm `cookie-banner` had already been hosted. ref: 1a3ef2ba7b79091969278cf7de50f593fb449397. Thanks for your contribution. I'm going to close this issue.

**Comment by PeterDaveHello** [comment]
Duplicated with #9956
