### ISSUE TITLE
[Request] arrgh.js

### ISSUE THREAD

**Issue by telmo-rodrigues** [cdnjs/cdnjs#10273]
**Library name:** arrgh.js
**Git repository url:** https://github.com/SanderRossel/arrgh.js
**npm package url(optional):** https://www.npmjs.com/package/arrgh
**License(s):** MIT License
**Official homepage:** https://sanderrossel.github.io/arrgh.js/
**Wanna say something? Leave message here:**

I'm not the owner of this package. All credits go to @SanderRossel.

**Comment by SanderRossel** [comment]
Awesome! :+1:

**Comment by kennynaoh** [comment]
Hello @Badspeed 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by Badspeed** [comment]
@kennynaoh okay, will do. Thank you

**Comment by sashberd** [comment]
Still no popularity. Suggest to close

**Comment by PeterDaveHello** [comment]
Thanks @sashberd
