### ISSUE TITLE
[Request] Add Clearmin

### ISSUE THREAD

**Issue by mxagustinl** [cdnjs/cdnjs#10270]
**Library name: Clearmin
**Git repository url: https://github.com/paomedia/clearmin
**npm package url(optional):** 
**License(s): GPL 3.0
**Official homepage: http://cm.paomedia.com/
**Wanna say something? Leave message here:
"src" folder

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @mxagustinl 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by sashberd** [comment]
Still no popularity. Suggest to close
