### ISSUE TITLE
[Request] Add page piling 

### ISSUE THREAD

**Issue by tlezotte** [cdnjs/cdnjs#10279]
**Library name:** pagePiling
**Git repository url:** https://github.com/alvarotrigo/pagePiling.js
**npm package url(optional):** 
**License(s):** The MIT License
**Official homepage:** http://alvarotrigo.com/pagePiling
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.

**Comment by qwe19272375** [comment]
This library is already exist in CDNJS.
ref: https://cdnjs.com/libraries/pagePiling.js

**Comment by pvnr0082t** [comment]
@qwe19272375 :+1: 
close due to the library had already been hosted. @tlezotte Thanks for your contribution.

**Comment by PeterDaveHello** [comment]
Should confirm that the "latest" version already been hosted, and better confirm with issuer before closing issue ...
