### ISSUE TITLE
[Request] Add amCharts JavaScript Stock Chart

### ISSUE THREAD

**Issue by martynasma** [cdnjs/cdnjs#10284]
**Library name:** amCharts JavaScript Stock Chart
**Git repository url:** https://github.com/amcharts/amstock3
**npm package url(optional):** 
**License(s):** Commercial, Linkware
**Official homepage:** https://www.amcharts.com/

**Comment by PeterDaveHello** [comment]
Already hosted here https://cdnjs.com/libraries/amstockchart/ ?

**Comment by PeterDaveHello** [comment]
cc #5337

**Comment by PeterDaveHello** [comment]
@martynasma is there any open source license that we can use?

**Comment by martynasma** [comment]
This is a very old version. Wasn't added by amCharts staff.

We don't have an open source license _per se_, just this "use the way you see fit":

https://github.com/amcharts/amstock3/blob/master/licence.txt

**Comment by silvangithub** [comment]
Please update to at least 3.20.20, the one hosted it very old (amstockchart)

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t, no any updates?

**Comment by sashberd** [comment]
@PeterDaveHello @martynasma @silvangithub  
Already hosted under https://cdnjs.com/libraries/amcharts
