### ISSUE TITLE
[Request] Add picomodal 

### ISSUE THREAD

**Issue by fractalf** [cdnjs/cdnjs#10282]
**Library name:** picomodal
**Git repository url:** https://github.com/Nycto/PicoModal
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.
