### ISSUE TITLE
[Request] Add jquery-flexdatalist 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10286]
**Library name:** jquery-flexdatalist
**Git repository url:** https://github.com/sergiodlopes/jquery-flexdatalist
**License(s):** MIT
**Official homepage:** http://projects.sergiodinislopes.pt/flexdatalist/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by Manish-Giri** [comment]
@PeterDaveHello Hi! I'm new here and interested in contributing to this issue!! Pls give me some time to read through all the links you've posted and then I'll contact you again if I have questions.

**Comment by PeterDaveHello** [comment]
@Manish-Giri No worry, welcome to join!

**Comment by sophie-li** [comment]
@Manish-Giri hi there! are you still working on this issue? if not and if you don't mind, i would like to contribute to tis since it'll be my first time :)

**Comment by PeterDaveHello** [comment]
@sophie-li I think you can just take it, @Manish-Giri can take some other issues when he is back.
