### ISSUE TITLE
[Request] Add amCharts JavaScript Maps

### ISSUE THREAD

**Issue by martynasma** [cdnjs/cdnjs#10285]
**Library name:** amCharts JavaScript Maps
**Git repository url:** https://github.com/amcharts/ammap3
**npm package url(optional):** 
**License(s):** Commercial, Linkware
**Official homepage:** https://www.amcharts.com/

**Comment by PeterDaveHello** [comment]
@martynasma is there any open source license that we can use?

**Comment by PeterDaveHello** [comment]
@martynasma is there any open source license that we can use?

**Comment by PeterDaveHello** [comment]
Already hosted here? https://cdnjs.com/libraries/ammaps

**Comment by PeterDaveHello** [comment]
cc #5337

**Comment by martynasma** [comment]
This is a very old version. Wasn't added by amCharts staff.

We don't have an open source license _per se_, just this "use the way you see fit":

https://github.com/amcharts/ammap3/blob/master/licence.txt

**Comment by m1dst** [comment]
We are up to version 3.21.0 (March 08, 2017) which would bring maps up to parity with https://cdnjs.com/libraries/amcharts.

**Comment by extend1994** [comment]
@PeterDaveHello It seems that there was a pull request which adds the auto-update config but it doesn't appear on current `package.json`. Should I wait for a while to add the library?

**Comment by PeterDaveHello** [comment]
@extend1994 any detail like issue/PR number?

**Comment by extend1994** [comment]
@PeterDaveHello Sorry! I misread the library. 😰 It should be `ammaps` but what I saw was `am charts `. Thank you for reply 😃  I will add it ASAP.

**Comment by extend1994** [comment]
@PeterDaveHello I am not sure what should I fill out the `license` field. In the lib repo, it's "custom". Or it should be "Linkware"...?

**Comment by PeterDaveHello** [comment]
@extend1994 We can use an object to save the info with link to the reference, take a quck trace, you will see some cases in the repo, not all of them using SPDX license string.  CC @cdnjs/intern3

**Comment by extend1994** [comment]
@PeterDaveHello Okay, thanks!

**Comment by extend1994** [comment]
@PeterDaveHello There are not minified files (e.g `ammap.css`) in the existed versions on CDNJS (https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ammaps). Should I minify them? Or I just need to leave it like that and also don't need to minify them in latest version? Thank you.

**Comment by PeterDaveHello** [comment]
I can minify them, create an issue for that an assign to me, thanks.

**Comment by extend1994** [comment]
@PeterDaveHello Should I wait for #10958 to be done? Or I can just keep doing this issue? Thank you.

**Comment by PeterDaveHello** [comment]
hmmmm, I need more time to work on it, if there is no dependency or conflict, you can get started first.

**Comment by extend1994** [comment]
Okay, thanks again!

**Comment by PeterDaveHello** [comment]
Or maybe you can try to do it directly :)

**Comment by extend1994** [comment]
@PeterDaveHello Do you mean the minified job?

**Comment by PeterDaveHello** [comment]
@extend1994 Yeah I think so.
