### ISSUE TITLE
[Request] Add bootstrap-modal-bs3patch 

### ISSUE THREAD

**Issue by hdiwan** [cdnjs/cdnjs#10294]
**Library name:** bootstrap-modal-bs3patch
**Url:** https://raw.githubusercontent.com/jschr/bootstrap-modal/master/css/bootstrap-modal-bs3patch.css
**License(s):** Apache 2.0
**Official homepage:** https://github.com/jschr/bootstrap-modal/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
GIT URL https://github.com/jschr/bootstrap-modal

**Comment by sufuf3** [comment]
Close this issue because CDNJS host it https://cdnjs.com/libraries/bootstrap-modal
Thanks @sashberd 
cc @PeterDaveHello
