### ISSUE TITLE
[Request] Add paver 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10298]
**Library name:** paver
**Git repository url:** https://github.com/terrymun/paver
**License(s):** MIT

**Comment by VPashkov** [comment]
Hi! I'd like to take this request.

**Comment by PeterDaveHello** [comment]
Thanks @VPashkov, we'll help you review your PR ASAP!

**Comment by terrymun** [comment]
Author chiming in here, thanks for the PR @VPashkov. I thought Paver didn't meet the selection criteria for CDNjs so I didn't submit it, but thanks for including it @PeterDaveHello.

**Comment by PeterDaveHello** [comment]
@terrymun You're welcome 👍

**Comment by VPashkov** [comment]
@terrymun You're welcome. Great library btw.
