### ISSUE TITLE
[Request] QS

### ISSUE THREAD

**Issue by nire0510** [cdnjs/cdnjs#10290]
**Library name:** QS
**Git repository url:** https://github.com/nire0510/qs
**npm package url(optional):** https://www.npmjs.com/package/qs-parser
**License(s):** MIT
**Official homepage:** http://nire0510.github.io/qs/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@nire0510 this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.
