### ISSUE TITLE
[Request] Add routy.js 

### ISSUE THREAD

**Issue by piecioshka** [cdnjs/cdnjs#10296]
**Library name:** routy.js
**Git repository url:** https://github.com/KanoComputing/routy.js
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/KanoComputing/routy.js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @piecioshka 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by piecioshka** [comment]
Hi @extend1994 
Thanks for details.

If this cute lib has no required popularity I will close this issue.
