### ISSUE TITLE
[Request] Add _libhttps://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.cssrary_name_ 

### ISSUE THREAD

**Issue by monsung** [cdnjs/cdnjs#10308]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
What is this issue about?

**Comment by sufuf3** [comment]
close because CSNJS host https://cdnjs.com/libraries/font-awesome/4.5.0
@sashberd Thanks
cc @PeterDaveHello
