### ISSUE TITLE
[Request] Add Stroke 7 Icon Font Set

### ISSUE THREAD

**Issue by afmp94** [cdnjs/cdnjs#10303]
Stroke 7 Icon Font Set
they don't have github
here is the font: http://www.pixeden.com/icon-fonts/stroke-7-icon-font-set
and documentation http://themes-pixeden.com/font-demos/7-stroke/documentation.html
http://www.pixeden.com/license
http://www.pixeden.com+

i don't know if there is a possibility to add this?

**Comment by dakshshah96** [comment]
@PeterDaveHello Can we really add this? Since it's not hosted either on GitHub or npm.

**Comment by PeterDaveHello** [comment]
There needs to be a proof of popularity, and most of the cases, it needs to be hosted on a public git/npm platform.

**Comment by sufuf3** [comment]
@andrespipexz is this library's link as followings?
npm: https://www.npmjs.com/package/pixeden-stroke-7-icon
GitHub: https://github.com/olimsaidov/pixeden-stroke-7-icon

ref: https://github.com/olimsaidov/pixeden-stroke-7-icon/blob/master/package.json#L17

**Comment by MattIPv4** [comment]
Library appears to no longer be maintained, unsure of source of truth for updating. Closing.
