### ISSUE TITLE
[Request] Add json-export-excel.min.js 

### ISSUE THREAD

**Issue by SayaliGhatge** [cdnjs/cdnjs#10313]
**Library name:** json-export-excel.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi,@SayaliGhatge!
Is https://github.com/dtagdev1/json-export-excel what you want to add?

**Comment by sashberd** [comment]
Still not response from issue author. Moreover, If @extend1994  is right the lib has not enough popularity. Suggest to close

**Comment by sufuf3** [comment]
Closed due to no response in 7 days also the lib has not enough popularity. cc @PeterDaveHello
