### ISSUE TITLE
[Request] Add vue-amap

### ISSUE THREAD

**Issue by AxeMea** [cdnjs/cdnjs#10312]
Library name: vue-amap
Git repository url: https://github.com/ElemeFE/vue-amap
npm package url(optional): https://www.npmjs.com/package/vue-amap
License(s): MIT
Official homepage: https://elemefe.github.io/vue-amap
Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Isn't it good enough to be hosted?

**Comment by PeterDaveHello** [comment]
Close per #10631
