### ISSUE TITLE
[Request] Add react-google-maps 

### ISSUE THREAD

**Issue by sppc42** [cdnjs/cdnjs#10328]
**Library name:** react-google-maps
**Git repository url:** https://github.com/tomchentw/react-google-maps
**npm package url(optional):** 
**License(s):** GPL
**Official homepage:** https://tomchentw.github.io/react-google-maps/
**Wanna say something? Leave message here:** Need it urgentnly

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
Hi @sppc42, Could you please tell us what file should be hosted on cdnjs? Thanks!

**Comment by maruilian11** [comment]
@sppc42 
this issue will be closed if there is no any response in next 7 days.

**Comment by extend1994** [comment]
Close due to no response and the library seems incompatible with browser for now. cc @PeterDaveHello
