### ISSUE TITLE
[Request] Add angular-ads CDN link

### ISSUE THREAD

**Issue by DaniNitro** [cdnjs/cdnjs#10322]
**Library name:** angular-ads
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @DaniNitro,
Could you provide more information (e.g. github / npm links) about this library ? Thank you.

**Comment by PeterDaveHello** [comment]
Close due to no response.
