### ISSUE TITLE
[Request] Add query-string 

### ISSUE THREAD

**Issue by nikocraft** [cdnjs/cdnjs#10334]
**Library name:** query-string
**Library description:** Parse and stringify URL query strings
**Git repository url:** https://github.com/sindresorhus/query-string
**npm package name or url (if there is one):** https://www.npmjs.com/package/query-string
**License (List them all if it's multiple):** MIT
**Official homepage:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @nermion,
Is this library work as a front end library?
Would you like to give us more information about this library?

**Comment by sashberd** [comment]
@MattIPv4 I think this one was merged to masted

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/query-string

**Comment by yairEO** [comment]
i'm not sure this is actually working. this isn't a "compiled" code, and it clearly shows:

```javascript
'use strict';
const strictUriEncode = require('strict-uri-encode');
const decodeComponent = require('decode-uri-component');
const splitOnFirst = require('split-on-first');

const isNullOrUndefined = value => value === null || value === undefined;
...
```

All those require statements cannot possible work when using this file in the `src` of a `<script>` tag. 

I wonder what's going on here..

**Comment by MattIPv4** [comment]
Yeah, this is pulling down the file that's available in the NPM pacakge. It seems that this library doesn't provided a distributable, bundled version of the library in the package.

You'll probably want to reach out to the maintainers of this library to ask them to include a bundled version in their package, so that we can host it.
