### ISSUE TITLE
[Request] Add KaTeX 0.7.0

### ISSUE THREAD

**Issue by mateddy** [cdnjs/cdnjs#10337]
Library name: KaTeX 0.7.0
Git repository url: https://github.com/Khan/KaTeX
License(s): MIT
Official homepage: https://khan.github.io/KaTeX/
Wanna say something? Leave message here: KaTeX 0.6.0 is hosted on cdnjs

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by gagern** [comment]
Please add KaTeX 0.7.1 which has the `dist` folder back again.

**Comment by pvnr0082t** [comment]
@gagern Thank you!
