### ISSUE TITLE
[Request] Update Dojo versions

### ISSUE THREAD

**Issue by dylans** [cdnjs/cdnjs#10349]
**Library name:** Dojo
**Git repository url:** https://github.com/dojo/dojo https://github.com/dojo/dijit https://github.com/dojo/dojox https://github.com/dojo/themes https://github.com/dojo/util
**npm package url(optional):** 
**License(s):** BSD
**Official homepage:** http://dojotoolkit.org/
**Wanna say something? Leave message here:** CDNjs currently only has versions through 1.10.4
 
The most recent CDN builds are at:

http://archive.dojotoolkit.org/cdn/1.12.1-cdn/
http://archive.dojotoolkit.org/cdn/1.11.3-cdn/
http://archive.dojotoolkit.org/cdn/1.10.7-cdn/
http://archive.dojotoolkit.org/cdn/1.9.10-cdn/
http://archive.dojotoolkit.org/cdn/1.8.13-cdn/
http://archive.dojotoolkit.org/cdn/1.7.11-cdn/
http://archive.dojotoolkit.org/cdn/1.6.4-cdn/
http://archive.dojotoolkit.org/cdn/1.5.5-cdn/
http://archive.dojotoolkit.org/cdn/1.4.7-cdn/

These contain builds that are optimized for deployment on a CDN (e.g. the same files that Google's CDN uses). If there's a better approach, please let me know! I've read through the README and CONTRIBUTING guidelines, as well as past PRs/tickets for older versions of Dojo.

Ideally we'd like to get this updated as it's blocking us from being update on JSFiddle.

Also let me know if there's a better approach to automate this in the future. Thanks!

**Comment by dakshshah96** [comment]
@PeterDaveHello We really need to do something about this since the latest version as seen from http://archive.dojotoolkit.org/cdn/ now is **1.4.3** and we're still hosting 1.10.4 stable release.

**Comment by PeterDaveHello** [comment]
@dakshshah96 agree. Wanna help take it?

**Comment by dakshshah96** [comment]
@PeterDaveHello Definitely!

**Comment by dylans** [comment]
To be clear, the latest versions (including backported bug fix releases) were all released on March 5th, 2017:

1.12.2
1.11.4
1.10.8
1.9.11
1.8.14
1.7.12
1.6.5
1.5.6
1.4.8

**Comment by dakshshah96** [comment]
@PeterDaveHello The CDN builds are all hosted at http://archive.dojotoolkit.org/cdn/

How do we manage this?
