### ISSUE TITLE
[Request] Please add loadCSS for a faster web

### ISSUE THREAD

**Issue by jesper-dk** [cdnjs/cdnjs#10341]
**Library name:** loadCSS
**Git repository url:** https://github.com/filamentgroup/loadCSS
**Github releases url:** https://github.com/filamentgroup/loadCSS/releases
**npm package url(optional):** https://www.npmjs.com/package/fg-loadcss
**License(s):** MIT

loadCSS is a polyfll which enables robust asynchronous CSS loading. Async CSS speeds up initial page rendering, by allowing less important CSS to load in the background without holding back first page render.

Chrome natively support this, and it is [being developed for WebKit](https://webkit.org/status/#feature-preload). loadCSS makes the pattern robust on older browsers, which is a necessity for this patterns adoption today.

Note, this library is called loadCSS, but on NPM it is named fg-loadcss

**Comment by pvnr0082t** [comment]
Duplicated with #7961. I'm going to close this issue. @jesper-dk Thanks for your contribution.
