### ISSUE TITLE
[Request] Add milojs 

### ISSUE THREAD

**Issue by andfinally** [cdnjs/cdnjs#10340]
**Library name:** milojs
**Git repository url:** https://github.com/mailonline/milo
**npm package url(optional):** milojs
**License(s):**
**Official homepage:** http://milojs.github.io/milo/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@extend1994 please help add this library, cc #10772
