### ISSUE TITLE
[Request] Add box2d 

### ISSUE THREAD

**Issue by mariacheline** [cdnjs/cdnjs#10354]
**Library name:** box2d
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
Hi @mariacheline , 
Do you mean this lib? https://github.com/erincatto/Box2D
Could you please tell us what files you want to be hosted? 
Thanks!

**Comment by sufuf3** [comment]
Maybe these: 
https://github.com/kripken/box2d.js/
OR
https://github.com/hecht-software/box2dweb

**Comment by extend1994** [comment]
Close due to no response, all the above libraries don't match the library requirement. cc @PeterDaveHello
