### ISSUE TITLE
Update dygraphs to 2.0.0

### ISSUE THREAD

**Issue by danvk** [cdnjs/cdnjs#10358]
A major new version of dygraphs just came out with a different file structure. `ajax/libs/dygraph/package.json` needs to be updated

 I've tried but have had trouble pushing commits to my fork of this repo.

**Comment by maruilian11** [comment]
hi @danvk, `dist/dygraph.js` need to be built by `scripts/build.sh`, our auto-update bot can't do that automatically. We need to find some ways to solve this problem, maybe open an issue in dygraph first.
Do you need the new version in a hurry? If you are we can manually add `2.0.0` first.

@PeterDaveHello Please take a look.

**Comment by danvk** [comment]
Is it possible to get the built files from npm instead of github? That's what I was hoping to do with this PR.

**Comment by maruilian11** [comment]
@danvk Yes, it is. We also provide npm package auto-update config. Sorry for not checking the npm package first. I will send the PR to turn to use the npm one.
