### ISSUE TITLE
[Request] Add Solid

### ISSUE THREAD

**Issue by derekbtw** [cdnjs/cdnjs#10363]
**Library name:** Solid
**Git repository url:** https://github.com/buzzfeed/solid.git
**License(s):** MIT
**Official homepage:** http://solid.buzzfeed.com/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
https://www.npmjs.com/package/bf-solid
