### ISSUE TITLE
[Request] Add jquery-overlap

### ISSUE THREAD

**Issue by leandrobrunner** [cdnjs/cdnjs#10376]
**Library name: jquery-overlap** 
**Git repository url: https://github.com/leandrobrunner/jquery-overlap.git**
**npm package url(optional):** 
**License(s): MIT License (LICENSE)**
**Official homepage: http://leandrobrunner.github.io/jquery-overlap/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @leandrobrunner ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
Hi @leandrobrunner, as you are the author of this lib, if you'd like to send a PR directly, we'll be happy to help you host it, please let us know what do you think, thanks.
