### ISSUE TITLE
[Request] Add angular-elevatezoom-plus 

### ISSUE THREAD

**Issue by AureoleArk** [cdnjs/cdnjs#10384]
**Library name:** angular-elevatezoom-plus
**Git repository url:https://github.com/igorlino/angular-elevatezoom-plus**
**npm package url(optional):https://www.npmjs.com/package/angular-ez-plus** 
**License(s):The MIT License (MIT)**
**Official homepage:https://igorlino.github.io/angular-elevatezoom-plus/#/main**
**Wanna say something? Leave message here:plz**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @AureoleArk 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Check its npm stats ... looks good.

**Comment by PeterDaveHello** [comment]
@sufuf3 check it again before you close it ...

**Comment by extend1994** [comment]
@PeterDaveHello npm states are
>12 downloads in the last day
58 downloads in the last week
195 downloads in the last month

It should not be enough...?

**Comment by PeterDaveHello** [comment]
I think it'll vary, it's the "last" statics.

**Comment by PeterDaveHello** [comment]
@extend1994 I think we can host this one anyway.

**Comment by extend1994** [comment]
OK 👍
