### ISSUE TITLE
[Author] [Request] Rambda 

### ISSUE THREAD

**Issue by selfrefactor** [cdnjs/cdnjs#10381]
**Library name: rambda** 
**Git repository url: https://github.com/selfrefactor/rambda**
**npm package url(optional): https://www.npmjs.com/package/rambda** 
**License(s): no licence**
**Official homepage:**
**Wanna say something?: The file I want to publish on Cdnjs is https://github.com/selfrefactor/rambda/blob/master/webVersion.js
Also if you require licence, I would create one**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @selfrefactor,
Does `webVersion.js` depends on other `.js` in the repository?
And a license will be appreciated.
Thank you.

**Comment by selfrefactor** [comment]
Hi @hare1039 
webVersion.js is bundled and ready to use. It doesn't depend on other packages.

As for licence- I guess MIT should be fine. 

Thank you for the fast response on my request.

**Comment by hare1039** [comment]
Hi @selfrefactor 
From `0.1.0` to `0.3.1`, `webVersion.js` doesn't exist. At this case, what file should we host?

**Comment by selfrefactor** [comment]
webVersion.js came later as idea, so that is why it is not in prior to 0.3.1 versions. There is no file that can substitute webVersion.js for earlier versions.

**Comment by hare1039** [comment]
@selfrefactor So we don't need to host `0.1.0` to `0.3.1`?
@pvnr0082t Can we host only portions of library versions?

**Comment by selfrefactor** [comment]
@hare1039 If I could choose, I would host only the latest version, as there was some bugs in the previous ones.

**Comment by hare1039** [comment]
@selfrefactor Thank you for your suggestion. 
But the cdnjs-bot fetches files according to tags of the source, I don't think we can host only the latest version.

Let me confirm with the seniors here.

**Comment by hare1039** [comment]
@selfrefactor Can you also change the license field in `package.json` to `MIT`? 
The pull request is rejected because license field is inconsistent with GitHub repo.
Thanks.

**Comment by selfrefactor** [comment]
Hi @hare1039 
I just change it to MIT, now it should be fine.
Let me know if this is still an issue.
