### ISSUE TITLE
[Request] Add jquery-toast-plugin

### ISSUE THREAD

**Issue by helantao** [cdnjs/cdnjs#10387]
Library name: jquery-toast-plugin
Git repository url: https://github.com/kamranahmedse/jquery-toast-plugin
**npm package url(optional):** 
**License(s):**
Official homepage: https://github.com/kamranahmedse/jquery-toast-plugin
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Dup with #10118 @sufuf3 @extend1994
