### ISSUE TITLE
bootstrap-rtl is not on latest version

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10389]
Hey guys,
The latest version of bootstrap-rtl is 3.3.4, however, it is not updated on cdnjs, but the folder is exists.
 For you review
https://github.com/morteza/bootstrap-rtl/tree/master/dist/cdnjs

**Comment by PeterDaveHello** [comment]
@extend1994 let's check if the auto-update config is outdated or something wrong.

**Comment by extend1994** [comment]
@PeterDaveHello There is no auto-update config on cdnjs repo. Files on the repo seemed to be added by the author. Should I set up auto-update config which allow cdnjs to include files on https://github.com/morteza/bootstrap-rtl/tree/master/dist/cdnjs (no JavaScript files).

**Comment by PeterDaveHello** [comment]
@extend1994 try what you think is the best, btw, the high priority issue should be solved earlier and faster as the name it is.

**Comment by extend1994** [comment]
@PeterDaveHello If I want to add old missing versions of it, should I open another issue or just do it and cc this issue?

**Comment by PeterDaveHello** [comment]
@extend1994 Let's open a new one.

**Comment by extend1994** [comment]
OK, thanks!
