### ISSUE TITLE
[Request] Add cachet-status 

### ISSUE THREAD

**Issue by johnjrmurray** [cdnjs/cdnjs#10393]
**Library name:** cachet-status
**Git repository url:** https://github.com/gohiring/cachet-status
**npm package url(optional):** 
**License(s):** The MIT License
**Official homepage:** http://www.gohiring.com/cachet-status/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @johnjrmurray ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
close due to no response.
