### ISSUE TITLE
[Request] Add ivan_test

### ISSUE THREAD

**Issue by ivanu6kin** [cdnjs/cdnjs#10400]
**Library name:** **ivan_test**
**Git repository url:** ivan_test
**npm package url(optional):** ivan_test
**License(s):** free
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@ivanu6kin Could you give more precise detail or url? Thank you.

**Comment by pvnr0082t** [comment]
close due to no response.
