### ISSUE TITLE
[Request] Add SyoTimer 

### ISSUE THREAD

**Issue by redeventmedia** [cdnjs/cdnjs#10408]
**Library name:** SyoTimer
**Git repository url: https://github.com/mrfratello/SyoTimer
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @redeventmedia 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by redeventmedia** [comment]
Thanks @extend1994!  I understand now, makes sense.

**Comment by PeterDaveHello** [comment]
Feel free to ask re-open this one or create an new issue if its popularity get higher, thanks @redeventmedia
