### ISSUE TITLE
[Request] Add jquery.cloudinary 

### ISSUE THREAD

**Issue by tzofiaCo** [cdnjs/cdnjs#10411]
**Library name:** jquery.cloudinary
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Hi @tzofiaCo  ,
Do you mean this lib? https://github.com/cloudinary/pkg-cloudinary-jquery
(npm package: https://www.npmjs.com/package/cloudinary-jquery)

Please tell us what files that you want to be hosted?
Thanks!

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
