### ISSUE TITLE
[Request] Bootstrap-Iconpicker

### ISSUE THREAD

**Issue by strategeens** [cdnjs/cdnjs#10424]
**Library name: Bootstrap-Iconpicker
**Git repository url: https://github.com/victor-valencia/bootstrap-iconpicker
**npm package url(optional):** 
**License(s): MIT license.
**Official homepage: http://victor-valencia.github.io/bootstrap-iconpicker/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicate with #8052

**Comment by PeterDaveHello** [comment]
Move to #8052
