### ISSUE TITLE
[Request] Add Mtn.Library 

### ISSUE THREAD

**Issue by israelinux** [cdnjs/cdnjs#10430]
**Library name:** Mtn.Library
**Git repository url:** https://github.com/israelinux/mtnlibraryjs
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/israelinux/mtnlibraryjs
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue, thanks!!

**Comment by dakshshah96** [comment]
@sufuf3 @PeterDaveHello I don't think this library can be added to cdnjs yet. It isn't popular enough.

**Comment by sufuf3** [comment]
@israelinux   this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
