### ISSUE TITLE
[Request] OwlCarousel2

### ISSUE THREAD

**Issue by LuanComputacao** [cdnjs/cdnjs#10437]
**Library name:** OwlCarousel2
**Git repository url:** https://github.com/OwlCarousel2/OwlCarousel2
**npm package url(optional):** https://www.npmjs.com/package/owl.carousel
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer: https://owlcarousel2.github.io/OwlCarousel2/index.html
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@LuanComputacao Are you looking for this [library](https://cdnjs.com/libraries/OwlCarousel2) `https://cdnjs.com/libraries/OwlCarousel2` ?

**Comment by LuanComputacao** [comment]
Oh yeah! Tks!

**Comment by hare1039** [comment]
@PeterDaveHello Shall we close this issue?

**Comment by PeterDaveHello** [comment]
@hare1039 Confirm that we have the latest version, then you can close it.

**Comment by PeterDaveHello** [comment]
@hare1039 please provide the reason why you close it next time.
