### ISSUE TITLE
Update MDBootstrap to 4.3.0

### ISSUE THREAD

**Issue by mattonit** [cdnjs/cdnjs#10432]
Hello,

We just released MDBootstrap 4.3.0. We'd like to add a new version to cdnjs. Could you please update MDB to 4.3.0?

git repo: https://github.com/mdbootstrap/bootstrap-material-design

**Comment by mattonit** [comment]
MDB 4.3.0 is on CDNJS now, but could you add two missing files? They're located in img/svg directory

**Comment by PeterDaveHello** [comment]
@mattonit Thanks for your suggestion

**Comment by extend1994** [comment]
@PeterDaveHello should I add the files under `img/svg` in all versions or can I just update the auto-update config?

**Comment by mattonit** [comment]
img/svg is required since MDB 4.3.0 and will be required in the future

**Comment by PeterDaveHello** [comment]
@mattonit thanks
