### ISSUE TITLE
[Request] Add pug 

### ISSUE THREAD

**Issue by JoeDuncko** [cdnjs/cdnjs#10431]
**Library name:** pug
**Git repository url:https://pugjs.org/**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #10060
