### ISSUE TITLE
[Request] Add tabulator.js 

### ISSUE THREAD

**Issue by kibblewhite** [cdnjs/cdnjs#10440]
**Library name:** tabulator.js
**Git repository url:** http://olifolkerd.github.io/tabulator/
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://olifolkerd.github.io/tabulator/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
GitHub repo: https://github.com/olifolkerd/tabulator

**Comment by PeterDaveHello** [comment]
Duplicated with #10440
