### ISSUE TITLE
[Request] Add Fast XML Parser

### ISSUE THREAD

**Issue by amitguptagwl** [cdnjs/cdnjs#10463]
**Library name:** Fast XML Parser
**Git repository url:** https://github.com/NaturalIntelligence/fast-xml-parser
**npm package url(optional):** https://www.npmjs.com/package/fast-xml-parser
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Hi @amitguptagwl!
This library doesn't have enough popularity which is more than 100 stars on GitHub or 500 downloads per month on npm.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello

**Comment by amitguptagwl** [comment]
Hi,
Sorry I missed the notification. Yes the library is new so there are not many downloads right now. However reached to 478 downloads in 3 weeks. So I'll request sometimes later when it gets the popularity.

Thanks :)

**Comment by clairetsai818** [comment]
@amitguptagwl Oops! Sorry I did't check the currently popularity. I think it's ready to be added now.

**Comment by amitguptagwl** [comment]
Thanks a lot for the consideration

**Comment by amitguptagwl** [comment]
seems merging in progress. plz let me know if I'm required anywhere to complete the process. Thanks again.
