### ISSUE TITLE
[Request] Add formValidation.min.css 

### ISSUE THREAD

**Issue by krishna8723** [cdnjs/cdnjs#10473]
**Library name:** formValidation.min.css
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@krishna8723 Did you mean this library? `https://github.com/formvalidation/formvalidation`

**Comment by hare1039** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
