### ISSUE TITLE
[Request] Add chartsjs-plugin-data-labels 

### ISSUE THREAD

**Issue by mallchel** [cdnjs/cdnjs#10474]
**Library name:** chartsjs-plugin-data-labels
**Git repository url:** https://github.com/garipov/chartsjs-plugin-data-labels
**npm package url(optional):** https://www.npmjs.com/package/chartsjs-plugin-data-labels
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @mallchel   
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello
