### ISSUE TITLE
[Request] Add wz tooltip

### ISSUE THREAD

**Issue by pokamiami** [cdnjs/cdnjs#10483]
Library name: wz tooltip
Git repository url: https://github.com/Akor/wz_tooltip
npm package url(optional):
License(s):
Official homepage:

**Comment by extend1994** [comment]
Hi @pokamiami  
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello
