### ISSUE TITLE
[Request] [author] Add jquery.json2html

### ISSUE THREAD

**Issue by moappi** [cdnjs/cdnjs#10489]
jquery.json2html
https://github.com/moappi/jquery.json2html
**npm package url(optional):** 
MIT License
http://json2html.com
Oops forgot to include the jquery plugin in my original json2html request; since this is how most users access json2html

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Duplicate with #10292

**Comment by PeterDaveHello** [comment]
Let's move to #10292

**Comment by sufuf3** [comment]
@moappi  would you like to send a PR to add it?

**Comment by PeterDaveHello** [comment]
Close duplicated issue ...

**Comment by PeterDaveHello** [comment]
Ping @clairetsai818

**Comment by PeterDaveHello** [comment]
@sufuf3 any updates here?
