### ISSUE TITLE
http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js library doesn't loads

### ISSUE THREAD

**Issue by gokulsiva** [cdnjs/cdnjs#10488]
I used this as <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> and deployed it in a free online server without any issue. But github page is not loading it.

**Comment by PeterDaveHello** [comment]
@gokulsiva you should use `https://`

**Comment by gokulsiva** [comment]
Thanks dave. It works like charm.

**Comment by PeterDaveHello** [comment]
@gokulsiva You're welcome

**Comment by gokulsiva** [comment]
But I have a question other servers parses http:// why didn't it work in github.

**Comment by PeterDaveHello** [comment]
Search: https mixed content
