### ISSUE TITLE
[Request] Add mikanjs

### ISSUE THREAD

**Issue by mametora** [cdnjs/cdnjs#10490]
**Library name:** mikanjs
**Git repository url:** https://github.com/trkbt10/mikan.js.git
**npm package url(optional):** https://www.npmjs.com/package/mikanjs

**Comment by clairetsai818** [comment]
Hi @mametora !
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md)

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello
