### ISSUE TITLE
[Request] Add p5.collide2d

### ISSUE THREAD

**Issue by BlazingFire007** [cdnjs/cdnjs#10493]
**Library name:** p5.collide2d
**Git repository url:** https://github.com/bmoren/p5.collide2D
**npm package url(optional):** 
**License(s):** GNU LGPL 2.1 License
**Official homepage:** https://github.com/bmoren/p5.collide2D
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @BlazingFire007,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

**Comment by hare1039** [comment]
Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response in 7 days. cc @PeterDaveHello
