### ISSUE TITLE
[Request] Add ScrollToFixed 

### ISSUE THREAD

**Issue by divyamayurmohite** [cdnjs/cdnjs#10494]
**Library name:** ScrollToFixed
**Git repository url:** https://github.com/bigspotteddog/ScrollToFixed
**npm package url(optional):** https://www.npmjs.com/package/scrolltofixed
**License(s):** MIT
**Official homepage:** http://bigspotteddog.github.io/ScrollToFixed/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
@divyamayurmohite Do you mean this?
https://github.com/bigspotteddog/ScrollToFixed

**Comment by divyamayurmohite** [comment]
@clairetsai818 
Yes this one https://github.com/bigspotteddog/ScrollToFixed
