### ISSUE TITLE
[Request] Add videojs-ima

### ISSUE THREAD

**Issue by ye0jun** [cdnjs/cdnjs#10491]
**Library name: videojs-ima** 
**Git repository url: https://github.com/googleads/videojs-ima**
**npm package url(optional): https://www.npmjs.com/package/videojs-ima** 
**License(s): Apache-2.0**
**Official homepage: https://github.com/googleads/videojs-ima**
**Wanna say something? Leave message here: PLEASE..**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@PeterDaveHello The lib on npm has latest version v0.5.0 but less versions. The lib on GitHub has more complete versions (v0.1.0~v0.4.0) but not latest. Which source should I take? Thank you.

**Comment by PeterDaveHello** [comment]
I think you can just create an issue to remind its author to tag it on GitHub.
