### ISSUE TITLE
[Request] Add sumoselect 

### ISSUE THREAD

**Issue by LukeMadhanga** [cdnjs/cdnjs#10500]
**Library name:** sumoselect
**Git repository url:** https://github.com/HemantNegi/jquery.sumoselect
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
@LukeMadhanga this issue is duplicate with #8169, let's move there.
cc @PeterDaveHello
