### ISSUE TITLE
[Request] Add string-fn 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10502]
**Library name:** string-fn
**Git repository url:** https://github.com/selfrefactor/string-fn
**npm package url(optional):** https://www.npmjs.com/package/string-fn
**License(s):** ISC

**Comment by dakshshah96** [comment]
@PeterDaveHello This library doesn't meet the minimum popularity requirements.

**Comment by PeterDaveHello** [comment]
@dakshshah96 we promote potential libraries :)
