### ISSUE TITLE
[Request] Add Custom Markup 

### ISSUE THREAD

**Issue by talonbragg** [cdnjs/cdnjs#10519]
**Library name:** **Git repository url: [here](https://github.com/talonbragg/Custom-Markup)**
**npm package url(optional): https://npmjs.org/package/custommarkup** 
**License(s): MIT**
**Official homepage: https://custommarkup.ml**
**Wanna say something? Leave message here:**
Hi thanks, if I  get the cdn please email it to me here pvpgamecrash@gmail.com
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
duplicate #10492, #10377, #10318.

**Comment by PeterDaveHello** [comment]
Move to #10318
