### ISSUE TITLE
[Request] Add CDN FTV

### ISSUE THREAD

**Issue by rsvaz83** [cdnjs/cdnjs#10526]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@rsvaz83 Could you give us more information about this library(e.g. github/npm links)?

**Comment by hare1039** [comment]
@rsvaz83 This issue will be close if no response in 7 days.

**Comment by hare1039** [comment]
Close due to no response.
