### ISSUE TITLE
[Request] Add http://koronanews.ir 

### ISSUE THREAD

**Issue by koronanews** [cdnjs/cdnjs#10539]
**Library name:** http://koronanews.ir
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @koronanews,
The link you gave us looks like a news website not a JavaScript library. Can you point out the files that you want to host?
npm / GitHub links are appreciated. Thanks.

**Comment by hare1039** [comment]
@koronanews If there is no response in next 7 days, this library will be closed.

**Comment by hare1039** [comment]
Close due to no response.
