### ISSUE TITLE
[author][Request] Add typeboost.css 

### ISSUE THREAD

**Issue by englishextra** [cdnjs/cdnjs#10543]
**Library name:** typeboost.css
**Git repository url:** https://github.com/englishextra/typeboost.css
**npm package url(optional):**  https://www.npmjs.com/package/typeboost.css
**License(s):** (MIT)
**Official homepage:** https://englishextra.github.io/libs/typeboost.css/
**Wanna say something? Leave message here:** Good to have it at cdnjs as at: https://www.jsdelivr.com/projects/typeboost.css Thanks

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @englishextra
The library doesn't have enough popularity(100 stars/watchers on GitHub and  npm package downloaded 300 times per month are good examples). You can take a look on our README for more details :)
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by englishextra** [comment]
Thanks for the response.

**Comment by extend1994** [comment]
@PeterDaveHello Should we hold this library?

**Comment by PeterDaveHello** [comment]
@englishextra would you like to send a pull request to add it?

**Comment by englishextra** [comment]
@PeterDaveHello I will

**Comment by PeterDaveHello** [comment]
@englishextra Thanks

**Comment by englishextra** [comment]
@PeterDaveHello @hare1039 and co. —Thanks
