### ISSUE TITLE
[author][Request] Add ngScrollReveal

### ISSUE THREAD

**Issue by kinotto** [cdnjs/cdnjs#10545]
**Library name:** ngScrollReveal
**Git repository url:**https://github.com/kinotto/ngScrollReveal
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @kinotto
The library doesn't have enough popularity(100 stars/watchers on GitHub is a good example). You can take a look on our README for more details :)
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by extend1994** [comment]
@PeterDaveHello Should we hold this library? Or just close it cause no response?

**Comment by kinotto** [comment]
@extend1994  ok i will open a new issue if it reaches that threshold. thanks for the info.

**Comment by PeterDaveHello** [comment]
@kinotto thanks!

**Comment by extend1994** [comment]
Close this issue cause insufficient popularity, cc @PeterDaveHello
