### ISSUE TITLE
[Request] Add angular-auth0 

### ISSUE THREAD

**Issue by rahulchanglani** [cdnjs/cdnjs#10556]
**Library name:** angular-auth0
**Git repository url:** https://github.com/auth0/angular-auth0
**npm package url(optional):** https://www.npmjs.com/package/angular-auth0
**License(s):** [MIT](https://github.com/auth0/angular-auth0/blob/master/LICENSE)
**Official homepage:** 
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @rahulchanglani 
Do you mean this library https://github.com/auth0/angular-auth0 ?

**Comment by rahulchanglani** [comment]
Yes

**Comment by rahulchanglani** [comment]
Yes, [https://github.com/auth0/angular-auth0]
