### ISSUE TITLE
[Request] Add jquery.cookiecuttr 

### ISSUE THREAD

**Issue by chikochavda** [cdnjs/cdnjs#10569]
**Library name:** jquery.cookiecuttr
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@chikochavda Do you mean this library https://github.com/cdwharton/cookieCuttr ?

**Comment by chikochavda** [comment]
Yes this is the one . Thanks :+1:

**Comment by PeterDaveHello** [comment]
Is the library not up-to-date?

**Comment by PeterDaveHello** [comment]
Close due to no response.
