### ISSUE TITLE
[Author] [Request] Add re-tree to cdnjs

### ISSUE THREAD

**Issue by srfrnk** [cdnjs/cdnjs#10561]
**Library name:** re-tree
**Git repository url:** https://github.com/srfrnk/re-tree
**npm package url(optional):** https://www.npmjs.com/package/re-tree
**License(s):** MIT
**Official homepage:** https://github.com/srfrnk/re-tree
**Wanna say something? Leave message here:** You've recently added [ng-device-detector](https://cdnjs.com/libraries/ng-device-detector) to cdnjs, now people ask me to add re-tree as it is a dependency and adding it would help them. see [issue #57](https://github.com/srfrnk/ng-device-detector/issues/57) 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@PeterDaveHello ng-device-detector has enough popularity and has been on CDNJS. As a dependency, can this library be added to CDNJS? Thanks.

**Comment by PeterDaveHello** [comment]
Okay let's do it 👍
