### ISSUE TITLE
[Request] Add prettycron

### ISSUE THREAD

**Issue by maxharlow** [cdnjs/cdnjs#10567]
**Library name:** prettycron
**Git repository url:** https://github.com/azza-bazoo/prettycron
**npm package url(optional):** https://www.npmjs.com/package/prettycron
**License(s):** LGPL-3.0
**Official homepage:** http://azza-bazoo.github.io/prettycron

**Comment by extend1994** [comment]
@PeterDaveHello Could you please help me take a look at the issue :arrow_up: ? I can not be sure of what the author said. Thanks!

**Comment by PeterDaveHello** [comment]
I didn't see a author comment.

**Comment by extend1994** [comment]
Discussions are here: azza-bazoo/prettycron#33

**Comment by PeterDaveHello** [comment]
@extend1994 are they authors?

**Comment by extend1994** [comment]
Sorry!! They are not. I thought they are contributors and didn't check that well. But indeed I can't really understand what they said.

**Comment by PeterDaveHello** [comment]
@extend1994 simply means they don't have permission and npm package is out-dated, even not the same as the version GitHub

**Comment by extend1994** [comment]
Thanks for explanation :+1: So in this case should I wait the author/contributor for the response.

**Comment by PeterDaveHello** [comment]
@extend1994 you can try to add from git repo.

**Comment by extend1994** [comment]
Okay!
