### ISSUE TITLE
[Request] Add cryptoJS

### ISSUE THREAD

**Issue by Juyoung11** [cdnjs/cdnjs#10582]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @Juyoung11,
Do you mean this library https://github.com/sytelus/CryptoJS?

**Comment by sashberd** [comment]
@PeterDaveHello According to hosted crypto-js librari the [API ](https://github.com/brix/crypto-js#api)is [same ](https://github.com/sytelus/CryptoJS/tree/v3.1.2#cryptojs)with current requested library - https://code.google.com/p/crypto-js
It is like looks duplicate, however, it is not exact. For you discretion.
Suggest to close

**Comment by PeterDaveHello** [comment]
We can host it if its popularity is good enough.

**Comment by MattIPv4** [comment]
Appears to be almost identical to https://cdnjs.com/libraries/crypto-js
