### ISSUE TITLE
[Request] Add intl-messageformat 

### ISSUE THREAD

**Issue by manchicken** [cdnjs/cdnjs#10588]
**Library name:** intl-messageformat
**Git repository url:**git@github.com:yahoo/intl-messageformat.git
**npm package url(optional):** https://www.npmjs.com/package/intl-messageformat
**License(s):**Yahoo! BSD
**Official homepage:**https://github.com/yahoo/intl-messageformat
**Wanna say something? Leave message here:**
This is a common internationalization library implementing the FormatIS.io spec.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
duplicate #10544

**Comment by pvnr0082t** [comment]
@hare1039 You can close it.

**Comment by hare1039** [comment]
Close due to duplicate issue
