### ISSUE TITLE
[Request] Add Animating-Hamburger-Icons 

### ISSUE THREAD

**Issue by hare1039** [cdnjs/cdnjs#10598]
**Library name:** Animating-Hamburger-Icons
**Git repository url:** https://github.com/callmenick/Animating-Hamburger-Icons
**License(s):** MIT, [ref](https://github.com/callmenick/Animating-Hamburger-Icons#license)
**Official homepage:** http://callmenick.com/_development/css-hamburger-menu-icons/
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
