### ISSUE TITLE
[Request] Add angular-drop-image 

### ISSUE THREAD

**Issue by anteriovieira** [cdnjs/cdnjs#10593]
**Library name:** angular-drop-image
**Git repository url:** https://github.com/uni-projecao/angular-drop-image
**npm package url(optional):**  https://www.npmjs.com/package/angular-drop-image
**License(s):** MIT
**Official homepage:** angular-drop-image
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @anteriovieira,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs. 

Feel free to show some other references if you have something else want to discuss with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by anteriovieira** [comment]
Thanks!

**Comment by hare1039** [comment]
Close due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@hare1039 isn't this a response? https://github.com/cdnjs/cdnjs/issues/10593#issuecomment-279193334

**Comment by PeterDaveHello** [comment]
The popularity on npm looks close the the requirement.

**Comment by anteriovieira** [comment]
I would be happy if this package could be added : )

**Comment by PeterDaveHello** [comment]
@anteriovieira would you like to send a pull request?

**Comment by anteriovieira** [comment]
Yes, I really would like it.

**Comment by PeterDaveHello** [comment]
@anteriovieira Nice

**Comment by dakshshah96** [comment]
@anteriovieira Do you need some help sending a pull request? Happy to help!

**Comment by anteriovieira** [comment]
Hi @dakshshah96 , 

yes, I will be happy if you can help me.

**Comment by PeterDaveHello** [comment]
@anteriovieira what kind of help you would like to have first?

**Comment by anteriovieira** [comment]
Hi @PeterDaveHello , 

I read the contribution guide and I understood everything, but I do not think it makes more sense to make this package available. I probably will not keep it anymore, then you can close this issues.

Thanks!

**Comment by PeterDaveHello** [comment]
@anteriovieira Thanks, I will take a look at it soon.
