### ISSUE TITLE
[Request] Add folktale 

### ISSUE THREAD

**Issue by danikkks** [cdnjs/cdnjs#10590]
**Library name:** folktale
**Library desctiption:** A standard library for functional programming in JavaScript
**Git repository url:** https://github.com/origamitower/folktale
**npm package name or url**: https://www.npmjs.com/package/folktale
**License (List them all if it's multiple):** MIT
**Official homepage:** folktale.origamitower.com
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @danikkk,
Do you mean this library?
https://github.com/origamitower/folktale
https://www.npmjs.com/package/folktale

**Comment by danikkks** [comment]
@hare1039, yes

**Comment by JesterXL** [comment]
+1

**Comment by ShaunEgan** [comment]
+1
