### ISSUE TITLE
[Request] Add clone 

### ISSUE THREAD

**Issue by lcd78706** [cdnjs/cdnjs#10600]
**Library name:** clone
**Git repository url:** https://github.com/pvorb/clone
**npm package url(optional):** https://www.npmjs.com/package/clone
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**
cc #10165 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mercyg** [comment]
Hi @drewfreyling I have made a pull request for this library please review it
