### ISSUE TITLE
[Request] Add linkifyjs

### ISSUE THREAD

**Issue by leif81** [cdnjs/cdnjs#10606]
**Library name:** linkifyjs
**Git repository url:** https://github.com/SoapBox/linkifyjs
**npm package url(optional):** https://www.npmjs.com/package/linkifyjs
**License(s):** MIT
**Official homepage:** http://soapbox.github.io/linkifyjs/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Need update `1.1.7` -> `2.1.4`

**Comment by leif81** [comment]
I just became aware that the linkifyjs project is broken up into many js files. `linkify.js` by itself is not terribly useful so all these would need to go in cdnjs too. If you download `linkifyjs.zip` from the GitHub releases page you'll notice all the files e.g. `linkify-html.js`, `linkify-string.js`, `linkify-jquery`, etc.
