### ISSUE TITLE
[Request] Add DragDrop 

### ISSUE THREAD

**Issue by lcd78706** [cdnjs/cdnjs#10604]
**Library name:** DragDrop
**Git repository url:** https://github.com/kbjr/DragDrop
**npm package url(optional):** 
**License(s):** MIT and GPL
**Official homepage:**
**Wanna say something? Leave message here:**
cc #10165 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello still low popularity. Suggest to close

**Comment by sufuf3** [comment]
@sashberd Can we use this rule?
https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0#diff-6a3371457528722a734f3c51d9238c13
we'll still use the old popularity requirement as the standard, for the new issues, which are after Aug 1, use the new [standard](https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0#diff-6a3371457528722a734f3c51d9238c13).

What do you think?

Thanks
