### ISSUE TITLE
[Request] Add background-check.js

### ISSUE THREAD

**Issue by x9t9** [cdnjs/cdnjs#10609]
**Library name:**  BackgroundCheck
**Git repository url:** https://github.com/kennethcachia/background-check
**npm package url(optional):**  
**License(s):** MIT ( [ref](https://github.com/kennethcachia/background-check/blob/master/LICENSE) )
**Official homepage:** http://www.kennethcachia.com/background-check/
**Wanna say something? Leave message here:**

 Automatically switch to a darker or a lighter version of an element depending on the brightness of images behind it.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x9t9** [comment]
any updates ?

**Comment by longjasonm** [comment]
+1 here.

**Comment by PeterDaveHello** [comment]
We'll work on it soon, sorry for the delay.

**Comment by PeterDaveHello** [comment]
Ping @sufuf3
