### ISSUE TITLE
[Request] Add Zepto Touch Plugin

### ISSUE THREAD

**Issue by joelnagy** [cdnjs/cdnjs#10612]
**Library name:** Zepto Touch Plugin
**Git repository url:** https://github.com/madrobby/zepto
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://zeptojs.com
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @hare1039

**Comment by hare1039** [comment]
Hi @joelnagy,
Do you mean we need to add all the files in `https://github.com/madrobby/zepto/tree/master/src`?

**Comment by joelnagy** [comment]
All of the Zepto modules would be great.

**Comment by hare1039** [comment]
@PeterDaveHello Is there a way to compose files from npm and GitHub source?

**Comment by PeterDaveHello** [comment]
I'm not sure what do you mean exactly, have examples or details?

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/cdnjs/pull/13695 adds all. of the source files in the package to future cdnjs versions.
