### ISSUE TITLE
[Request] Add mnist.js 

### ISSUE THREAD

**Issue by omcginty44** [cdnjs/cdnjs#10619]
**Library name:**  
**Git repository url:** https://github.com/cazala/mnist
**npm package url(optional):**  https://www.npmjs.com/package/mnist
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello I tried to minify this lib `js` file, but its payload is too large. Do we add this lib without minified file?

**Comment by PeterDaveHello** [comment]
@maruilian11 What do you mean too large?

**Comment by maruilian11** [comment]
I get this message after using `web-minify-helper`:
```
Payload Too Large
```
I tried to use `uglifyjs` command to minify it, but still run out of memory.

**Comment by PeterDaveHello** [comment]
@maruilian11 Tried some other minify tool or increased nodejs memory limit?

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello Still low popularity. Suggest to close
