### ISSUE TITLE
[Request] Add lazyyt 1.3.0

### ISSUE THREAD

**Issue by Rhodium** [cdnjs/cdnjs#10610]
**Library name: lazyYT
**Git repository url: https://github.com/Daugilas/lazyYT
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here: Update lazyyt to 1.3.0, thanks

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@extend1994 @maruilian11 @maruilian11 
This is a form with low popularity from [here ](https://github.com/tylerpearson/lazyYT)
Suggest to close as low popularity and [duplicate](https://github.com/tylerpearson/lazyYT)
