### ISSUE TITLE
[Request] Add js-xlsx-style 

### ISSUE THREAD

**Issue by esteveolm** [cdnjs/cdnjs#10615]
**Library name:** js-xlsx-style
**Git repository url:** https://github.com/protobi/js-xlsx
**npm package url(optional):** xlsx-style
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to add https://github.com/SheetJS/js-xlsx. Provided url is fork from this one

**Comment by sufuf3** [comment]
@sashberd Thanks but CDNJS already host SheetJS/js-xlsx https://cdnjs.com/libraries/xlsx :)
We can host this lib(protobi/js-xlsx) as low priority.
Thanks :)

**Comment by sashberd** [comment]
@sufuf3 Why we need to host fork of library that is already hosted?

**Comment by sufuf3** [comment]
As maintainer [said](https://github.com/cdnjs/cdnjs/issues/9525#issuecomment-343952847) 
> We host anyone meets our requirement, otherwise, there are many libraries have the same gaol.

This is the reason that we still host the lib which has enough popularity. 😃

**Comment by MattIPv4** [comment]
SheetJS version is still maintained, the fork is not. Closing.
