### ISSUE TITLE
[Request] Add WhitestormJS framework

### ISSUE THREAD

**Issue by sasha240100** [cdnjs/cdnjs#10616]
**Library name:** WhitestormJS
**Git repository url:** https://github.com/WhitestormJS/whitestorm.js
**npm package url(optional):**  https://www.npmjs.com/package/whs
**License(s):** MIT
**Official homepage:** https://whsjs.io/

**Comment by sasha240100** [comment]
@extend1994 Hello?! How it goes? When will it be added?

**Comment by hare1039** [comment]
@extend1994 I think we should add this high priority library as soon as possible. Thanks!

**Comment by extend1994** [comment]
Hi @sasha240100 I will add it as soon as possible!
@hare1039  Thanks for reminder.

**Comment by sasha240100** [comment]
@extend1994 Thanks for adding it. Can you please add v2.0.0-beta.x versions? (they should be used)

**Comment by extend1994** [comment]
@sasha240100 I am not sure if I can add the beta version. Ref: https://github.com/cdnjs/cdnjs/pull/10684#pullrequestreview-23147746.
@PeterDaveHello Can I?

**Comment by PeterDaveHello** [comment]
@extend1994 let's use another commit to add it, but please don't bump the version number since it's not a stable version, thanks.

**Comment by PeterDaveHello** [comment]
@extend1994 but if the beta versions can be fetched by auto-update, you need to do nothing about it.

**Comment by extend1994** [comment]
@PeterDaveHello Thank you for response. Yes, the beta versions can be fetched by auto-update. So do I need to revise the PR title and commit message to the latest beta version, or just leave it a stable version and fetch beta versions automatically?

**Comment by PeterDaveHello** [comment]
@extend1994 for PR details, please discuss in the PR.

**Comment by PeterDaveHello** [comment]
@extend1994 Just add the latest stable versions and the versions can't be fetched by auto-update.

**Comment by sasha240100** [comment]
@PeterDaveHello how can I access beta versions after this PR merged?

**Comment by PeterDaveHello** [comment]
you'll see it on the version list
