### ISSUE TITLE
[Request] mazedigital/Web-Ticker

### ISSUE THREAD

**Issue by semul** [cdnjs/cdnjs#10629]
**Library name: mazedigital/Web-Ticker** 
**Git repository url: https://github.com/mazedigital/Web-Ticker**
**npm package url(optional):**  https://www.npmjs.com/package/webticker
**License(s): https://github.com/mazedigital/Web-Ticker/blob/master/license.md**
**Official homepage: https://maze.digital/webticker/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello The library has low popularity.Suggest to close

**Comment by sufuf3** [comment]
@sashberd Can we use this rule?
https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0#diff-6a3371457528722a734f3c51d9238c13
we'll still use the old popularity requirement as the standard, for the new issues, which after Aug 1, use the new [standard](https://github.com/cdnjs/cdnjs/commit/c484b8b1bdfaaf32e742a1687e927afe2de710c0#diff-6a3371457528722a734f3c51d9238c13).

What do you think?

Thanks
