### ISSUE TITLE
[Request] Add _IcoFont_ 

### ISSUE THREAD

**Issue by ManzDev** [cdnjs/cdnjs#10622]
**Library name:** IcoFont
**Git repository url:** ?
**npm package url(optional):** 
**License(s):** http://icofont.com/license/
**Official homepage:** http://icofont.com/
**Wanna say something? Leave message here:** Alternative to Font Awesome. More than free 2015 icons on this open source project.

=====================

**Comment by hare1039** [comment]
Hi @ManzDev,
 I don't think we can host this icons as the license page explains

http://icofont.com/license/
> Not for Sale or Redistribute
> You may not offer the font/icons, modified or unmodified, for redistribution or resale. You can only use IcoFont as an asset to build other personal or commercial end products.

**Comment by ManzDev** [comment]
Oh... I think that you're right.  I had not noticed :/

**Comment by hare1039** [comment]
@PeterDaveHello What should we do next to this kind of issue that a requested library cannot be add?

**Comment by PeterDaveHello** [comment]
I think we should just close it now.
