### ISSUE TITLE
[Request]Add bootstrap_modify_Accordion

### ISSUE THREAD

**Issue by YeisonVelez11** [cdnjs/cdnjs#10635]
**:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @YeisonVelez11,
Can you provide more information about the library you want to add like a link to GitHub or npm?

**Comment by hare1039** [comment]
@YeisonVelez11 
This issue will be close if no response in next 7 days.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
