### ISSUE TITLE
cdnjs

### ISSUE THREAD

**Issue by VladimAnton** [cdnjs/cdnjs#10632]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@VladimAnton Any detail please?

**Comment by maruilian11** [comment]
@VladimAnton This issue will be closed if there is no response in next 7 days. Thanks.

**Comment by PeterDaveHello** [comment]
Directly close empty issue.
