### ISSUE TITLE
Update fancyBox to patch 2.1.6 ?

### ISSUE THREAD

**Issue by shinoamakusa** [cdnjs/cdnjs#10634]
@PeterDaveHello,
Hi, I was wondering if fancyBox could be updated to patched version 2.1.6 (it is basically 2.1.5 with small patch, but the creator did not change version to 2.1.6 and to make all worse on npm it is listed as 3.0.0 where its just 2.1.5 with small patch)? https://github.com/fancyapps/fancyBox/releases

**Comment by PeterDaveHello** [comment]
I don't get it, isn't it v2.1.6 on the url you provide? So I think we should just add v2.1.6?

**Comment by shinoamakusa** [comment]
Yes, I guess just add 2.1.6 and there is also 3.0 version branch which has not been officially released yet but it there at at version 3.0.22 now - https://github.com/fancyapps/fancyBox/tree/3.0

**Comment by PeterDaveHello** [comment]
@shinoamakusa v2.1.6 added

**Comment by PeterDaveHello** [comment]
@shinoamakusa btw the directory/file structure changed

**Comment by shinoamakusa** [comment]
Is it possible to include also 3.0 version branch which has not been officially released yet but it is there at version 3.0.22 now at separate git branch- https://github.com/fancyapps/fancyBox/tree/3.0 - http://fancyapps.com/fancybox/3/ or wait till he merges it with master after release?

**Comment by PeterDaveHello** [comment]
@shinoamakusa of course not, why should we host a version which is under development and not released
