### ISSUE TITLE
[Request] Mr.Node

### ISSUE THREAD

**Issue by talonbragg** [cdnjs/cdnjs#10638]
**Library name: mrnode** 
**Git repository url: https://github.com/talonbragg/Mr.Node.git**
**npm package url(optional): https://npmjs.org/package/mrnode** 
**License(s): MIT**
**Official homepage: https://mrnode.tk**
**Wanna say something? Leave message here:**
Please email the CDN to pvpgamecrash@gmail.com.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by talonbragg** [comment]
Can somebody please look at this?

**Comment by PeterDaveHello** [comment]
You are welcome to add a library via sending pull request, it'll be faster than just opening a request issue, since there are tons of issues, please wait with patience, thanks.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello Still low popularity. Suggest to close

**Comment by PeterDaveHello** [comment]
Thanks for the library suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), feel free to show some other references if you have something else want to discuss with us, thanks.

Thanks for being interested in CDNJS.

Best,
Peter
