### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.js

### ISSUE THREAD

**Issue by jschug** [cdnjs/cdnjs#10643]
js file now returns a mime/type of image/png.

Same for https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js

**Comment by maruilian11** [comment]
Hi @jschug, Could you tell me more details? Does it cause any problem?

**Comment by jschug** [comment]
Hi:

yes, some browsers see the mime type and will not execute it as java script so the page does not work.  I believe was ok the day before as we have been using it for a while.

J

Jonathan Schug
jschug@upenn.edu

**Comment by jschug** [comment]
Any idea why the mime type changed?


Jonathan Schug
jschug@upenn.edu

**Comment by maruilian11** [comment]
@PeterDaveHello please take a look.

**Comment by PeterDaveHello** [comment]
I have no problem:
```
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js
HTTP/1.1 200 OK
Date: Fri, 17 Feb 2017 17:02:58 GMT
Content-Type: application/javascript; charset=utf-8
Connection: keep-alive
Last-Modified: Wed, 22 Jun 2016 20:01:53 GMT
Expires: Wed, 07 Feb 2018 17:02:58 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 332acf611f81466e-TPE
```

@jschug please help provide the response header of the url you have problem with, and also the response your got from these urls, thanks:
https://cdnjs.com/cdn-cgi/trace
https://cdnjs.cloudflare.com/cdn-cgi/trace

**Comment by jschug** [comment]
Interesting.  My browser (Chrome on a Mac - Version 56.0.2924.87 (64-bit)) reported this error (in screen shot below) which triggered the complaint.

Here are the responses from curl which are the expected response.  I cleared the cache in Chrome and the problem is gone.  Thanks for your help - sorry for the false alarm.

J


> curl -I https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular.js
HTTP/1.1 200 OK
Date: Fri, 17 Feb 2017 17:13:05 GMT
Content-Type: application/javascript; charset=utf-8
Connection: keep-alive
Last-Modified: Wed, 22 Jun 2016 20:01:53 GMT
Expires: Wed, 07 Feb 2018 17:13:05 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
Server: cloudflare-nginx
CF-RAY: 332ade3229e80f39-IAD

> curl -I https://cdnjs.com/cdn-cgi/trace
HTTP/1.1 200 OK
Date: Fri, 17 Feb 2017 17:13:22 GMT
Content-Type: text/plain
Connection: keep-alive
Set-Cookie: __cfduid=d71581b9645b214be1a06c909870320b91487351602; expires=Sat, 17-Feb-18 17:13:22 GMT; path=/; domain=.cdnjs.com; HttpOnly
Server: cloudflare-nginx
CF-RAY: 332ade9b0e9f0f09-IAD
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-cache
X-Frame-Options: SAMEORIGIN

> curl -I https://cdnjs.cloudflare.com/cdn-cgi/trace
HTTP/1.1 200 OK
Date: Fri, 17 Feb 2017 17:13:36 GMT
Content-Type: text/plain
Connection: keep-alive
Server: cloudflare-nginx
CF-RAY: 332adef308c7571d-IAD
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Cache-Control: no-cache
X-Frame-Options: SAMEORIGIN

jschug@ngsc-007>


Jonathan Schug
jschug@upenn.edu

**Comment by PeterDaveHello** [comment]
For the urls, I mean the response content, not header, anyway, the problem didn't really exist, no mind.
