### ISSUE TITLE
[Request] Add react-redux-toastr 

### ISSUE THREAD

**Issue by albertotorresfoltyn** [cdnjs/cdnjs#10642]
**Library name:** react-redux-toastr
**Git repository url:** https://github.com/diegoddox/react-redux-toastr
**npm package url(optional):** react-redux-toastr
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello [According ](https://github.com/diegoddox/react-redux-toastr/issues/169#issuecomment-348832457)to author the library cannot be hosted. Suggest to close
