### ISSUE TITLE
[Request] Add nanoajax 

### ISSUE THREAD

**Issue by lcd78706** [cdnjs/cdnjs#10655]
**Library name:** nanoajax
**Git repository url:** https://github.com/yanatan16/nanoajax
**npm package url(optional):** https://www.npmjs.com/package/nanoajax
**License(s):** MIT  [ref](https://github.com/yanatan16/nanoajax/blob/master/LICENSE#L1)
**Official homepage:**

cc #10165 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please add this library, thanks
