### ISSUE TITLE
[Request] Add speakemoji 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10653]
**Library name:** speakemoji
**Git repository url:** https://github.com/rizalrenaldi/speakemoji
**Official homepage:** https://rizalrenaldi.github.io/speakemoji/

**Comment by PeterDaveHello** [comment]
Hello @rizalrenaldi, your speakemoji looks very cool, and we'll like to host it on CDNJS, it can help your users use it in a easier way with free and high performance CDN service, and also help you spread your library! Just wanna know that have you decided to use what kind of license for it (we expected any open source license so that we can host and distribute it)? Thanks!

**Comment by rizalrenaldi** [comment]
Hi @PeterDaveHello, yes I'd love to add speakemoji to cdnjs. But honestly I'm totally clueless about how this things work :) *sorry* I'm not a programmer/coder at all so please bear with me and let me learn how cdnjs works :D

About the license I prefer to use CC ND 4.0 (http://creativecommons.org/licenses/by-nd/4.0/)

**Comment by PeterDaveHello** [comment]
@rizalrenaldi thanks for your reply and being interested in CDNJS, it's totally not a need to say sorry, we're happy to help individual developer like you and me to make their project better, I'm glad that you have idea about the license, not only for CDNJS, to help your library spreading, it'll be great to get started from adding a `package.json` as an ID card of `speakemoji`, most of the famous libraries have that, here is the reference you'll need: https://docs.npmjs.com/files/package.json, you can also take a look at the libraries' package.json on CDNJS, e.g. https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/hyperapp/package.json as reference, once you have it, I think we can move on, what do you think? If you need any kind of help, feel free to ask @maruilian11 and @pvnr0082t would also be happy to help.
