### ISSUE TITLE
[Request] Add rythm.js 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10652]
**Library name:** rythm.js
**Git repository url:** https://github.com/Okazari/Rythm.js
**npm package url(optional):**  https://www.npmjs.com/package/rythm.js
**License(s):** ISC on npm but GPL-3.0, need to be confirmed
**Official homepage:** https://okazari.github.io/Rythm.js/

**Comment by PeterDaveHello** [comment]
Hello @Okazari, we'd like to host this super awesome library on CDNJS, is it possible to provide officially pre-built file in the repository with valid git version tag(s) so that we can directly use it? Thank you!

**Comment by Okazari** [comment]
Hello ! Thanks for your interest. 

I published a tag v1.2.3 on my repository. There is actually no such things as a build in my library (i'll probably add this soon). The only file needed in my package is the "rythm.js" one at the project root.

Tell me if you need more information.

**Comment by PeterDaveHello** [comment]
Thanks @Okazari, will let you know that if there is anything else we need.

**Comment by Okazari** [comment]
FYI i just published a v1.2.4 tag and the pre-built file is now `src/rythm.js`

**Comment by hare1039** [comment]
@PeterDaveHello Which file source is better: npm or GitHub ?

**Comment by PeterDaveHello** [comment]
Then you have the answer

**Comment by Okazari** [comment]
Since in v1.2.5 the `src/rythm.js` file will be using ES6. Do you still need the prebuilt version ? Will you take care of transpiling to ES5/umd ?

**Comment by PeterDaveHello** [comment]
@Okazari yes we'll need it, we don't handle the transpiling, so will also need your help, thanks!

**Comment by Okazari** [comment]
If you can take files from npm. i'll always provide a "prebuilt" version on root as `rythm.js`

PS : I was just missunderstanding "prebuilt"  (was reading it as "before build" instead of "already built", MB)

**Comment by PeterDaveHello** [comment]
@Okazari maybe we just the wrong word, btw, would you consider to provide it inside a dist folder, and provide with minified file and map file? Thanks.

**Comment by Okazari** [comment]
Working on it. 
Atm you can use v1.2.3 with "rythm.js" on root folder. 
I'll tell you when v1.2.5 is ready.
Not sure about the dist folder, since people currently import it from root and it would be a breaking change (Or gonna do a v2.0.0 providing minified file 🤔)

**Comment by PeterDaveHello** [comment]
@hare1039 let's get started to add this lib.

**Comment by hare1039** [comment]
Hi @Okazari,
About the license, would you confirm which license this library is using?
>> GPL3 https://github.com/Okazari/Rythm.js/blob/master/LICENSE
>> ISC    https://github.com/Okazari/Rythm.js/blob/master/package.json#L16
Thanks!

**Comment by Okazari** [comment]
the mistake is in the package.json, the licence is GPL3

**Comment by PeterDaveHello** [comment]
@Okazari Thanks
