### ISSUE TITLE
[Request][author] Add jsPanel

### ISSUE THREAD

**Issue by Flyer53** [cdnjs/cdnjs#10658]
**Library name:** jsPanel
**Git repository url:** https://github.com/Flyer53/jsPanel
**npm package url(optional):** https://www.npmjs.com/package/jspanel
**License(s):** MIT
**Official homepage:** http://jspanel.de/
+ GitHub / Bitbucket popularity (required): 
  + Count of stars: 137
  + Count of watchers: 24
  + Count of forks: 53
+ NPM download stats (optional):
  + Downloads in the last day: 0
  + Downloads in the last week: 93
  + Downloads in the last month: 185

**Wanna say something? Leave message here:**
I'm the author of this library.
CDNJS already hosts **jsPanel3** which is the repo with jsPanel versions 3.x. **jsPanel** is the "original" repo and has the versions 1.x and 2.x.
I plan to add the jsPanel3 versions to the "original" jsPanel repo in order to have every version in one repo. Also the jsPanel version 4 I'm already working on is planned to go to the "original" repo jsPanel.
Thank you very much

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
I think we can directly move jsPanel3 to jsPanel, and just use symbolic link to link it back.

**Comment by Flyer53** [comment]
Sounds good to me :)
I really appreciate your work very much. Thanks a lot!
I have to admit that my knowledge about npm, git and the like is just enough to get my own GitHub repo going ...

**Comment by PeterDaveHello** [comment]
No worries at all @Flyer53

**Comment by Flyer53** [comment]
In case you decide to host jsPanel versions < 3 as well I started to prepare a zip archive with subfolders for each version. Basically to ensure that only the necessary files are included and that js/css files are properly minified (some of the GitHub downloads don't have a minified css). Maybe that saves you some work?

**Comment by Flyer53** [comment]
And here is the zip archive with all jspanel versions 1.x and 2.x
[jspanel-versions-1.x-and-2.x.zip](https://github.com/cdnjs/cdnjs/files/787206/jspanel-versions-1.x-and-2.x.zip)

**Comment by PeterDaveHello** [comment]
Thanks for the info, we'll get started soon.

**Comment by Flyer53** [comment]
My pleasure
Concerning jsPanel versions 1.x I personally think it's sufficient to add only the latest version 1.11.0
Thanks again for your perfect service :)

**Comment by Flyer53** [comment]
@pvnr0082t @PeterDaveHello 
Hey there! Is there a chance that this issue is going to get forward any time soon? Or is there anything missing from my side?
Regards,
Stefan

**Comment by PeterDaveHello** [comment]
Hey @Flyer53 sorry for the late response, I reassigned this to @sufuf3 and we'll get it done ASAP!

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
