### ISSUE TITLE
[Request] Add fermata 

### ISSUE THREAD

**Issue by lcd78706** [cdnjs/cdnjs#10656]
**Library name:** fermata
**Git repository url:** https://github.com/natevw/fermata
**npm package url(optional):**  https://www.npmjs.com/package/fermata
**License(s):** MIT [ref](https://github.com/natevw/fermata/blob/master/README.md#mit-license)
**Official homepage:**

cc #10165 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 
please add this library, thanks.
