### ISSUE TITLE
[Request] Add gibon 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10651]
**Library name:** gibon
**Git repository url:** https://github.com/tunnckoCore/gibon
**npm package url(optional):** https://www.npmjs.com/package/gibon
**License(s):** MIT

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by dakshshah96** [comment]
I'd like to take this one up since it's beginner-friendly if that's fine 😅

**Comment by PeterDaveHello** [comment]
@dakshshah96 Great! Feel free to ask for help if you need!

**Comment by dakshshah96** [comment]
@PeterDaveHello I've created the fork on my profile.

Seems like there are [3 releases](https://github.com/tunnckoCore/gibon/releases) till date so the three folders will be located at `ajax/libs/gibon/0.3.0`, `ajax/libs/gibon/0.3.1` and `ajax/libs/gibon/0.3.2`.

When I took a look at the [Gibon repository](https://github.com/tunnckoCore/gibon) though, I'm confused about which files from that should be added to the folders I mentioned above. Is it only the `gibon/src/index.js` file?

**Comment by PeterDaveHello** [comment]
I think we'll only need to add the files under `dist` folder but exclude the gz file 😄 
I'll let @pvnr0082t @maruilian11 help you on this issue

**Comment by tunnckoCore** [comment]
Hey everyone! Thanks for that! I'm working on new release locally and there would have some changes

Also there are few problems related to the files.

**Comment by pvnr0082t** [comment]
@tunnckoCore Thanks for the information. :+1:
