### ISSUE TITLE
[Bounty] Write readme document of "tools" [$10]

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10660]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42184483)](https://www.bountysource.com/issues/42184483-write-readme-document-of-tools?utm_source=42184483&utm_medium=shield&utm_campaign=ISSUE_BADGE)

https://github.com/cdnjs/cdnjs/tree/master/tools

**Comment by dakshshah96** [comment]
Hey @PeterDaveHello, I'd love to work on improving the CDNJS documentation. What exactly are we looking for here? I can help!

**Comment by PeterDaveHello** [comment]
@dakshshah96 just add a readme about what's inside the `tools` folder and what's their purpose, how to use them. Thanks!

**Comment by dakshshah96** [comment]
@PeterDaveHello If I'm right, there are three tools which users can use?

* fixFormat.js
* createSparseCheckoutConfig.js
* updateDescription.js

**Comment by PeterDaveHello** [comment]
Actually, almost all of them can be used by user, for example, the SPDX license list is a good reference of recognized license, and there are git hooks example in `hooks` to help user run the tests before push the commits.

**Comment by caseyjhol** [comment]
For anybody searching: `node tools/fixFormat.js`

**Comment by joshhazelhurst123** [comment]
Hi, my basic understanding is that these tools are used for creating or updating a library in the CDNJS. The library needs to be go through a series of checks and balances before it can be created or updated on the CDNJS, for example, it needs to meet the criteria for correct version number, licensing field, correct indention etc. Before making any changes to the library or creating a new one. The user can run tests and make sure that it is compliant before pushing the library onto the CDNJS. 
Would you like screenshots in the readme file? Or just a basic readme file. 
I found the common conventions used at at https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

Let me know if I am on the right track here and I can write something up. But based on what I have written here, what do you think?
Thanks,

**Comment by xtuc** [comment]
tools have changed. Documentation still need to be written tho
