### ISSUE TITLE
New maintainers of CDNJS

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10662]
To keep an open source project alive and keep moving forward, the maintainers of the project really matter 💪 , I've started the training program at CDNJS for almost 2 years, to help students 👨‍🎓 👩‍🎓  learn about linux(mostly Ubuntu), free and open source project contribution, version control system, web related techs, etc, and they just do the practice/homework to valid what they learn via contributing back, I can't say that how good or how huge we've done, but I can say that we now have 3 intern teams as:

 - @cdnjs/intern 
 - @cdnjs/intern2 
 - @cdnjs/intern3 (some students are still under training that didn't reach the quality to be added in the team)

Some of them are just started their training about half a year ago, some of them already finished most of the training, just keep improve the pull request quality and some related things as the remaining part of the training, I think it's time to push some of them to reach the requirement to become a maintainer of CDNJS, which can help CDNJS growth more healthier and stronger ⭐️ , also help the ones who joined us to build their own credits and reputation, though I haven't discuss with them in private, but as this is an open source project, I think it'll be fine to have a public note about this decision, even though it's not made yet.

Currently, @maruilian11 and @pvnr0082t are the most possible ones to become one of us, are they both did visible contribution in the past months as below:

![image](https://cloud.githubusercontent.com/assets/3691490/23096336/524717d4-f655-11e6-9288-705dd89ad95f.png)
![image](https://cloud.githubusercontent.com/assets/3691490/23096339/5bcf6b44-f655-11e6-9a92-3c7c2834cc82.png)

(from https://github.com/cdnjs/cdnjs/graphs)

There are also some potential candidates like @Amomo, @kennynaoh, @Piicksarn & @x09326 : 
![image](https://cloud.githubusercontent.com/assets/3691490/23096367/fae89340-f655-11e6-8b20-5ba83973101f.png)

(Sorry that I just post the quantified charts to demonstrate their contribution, may be a little bit too rough)

IMO, to become a maintainer, the key point is not just about how many commits you made or you are going to make, it's more about if you are interested in and willing to contribute, if you'll like to make this project better, and if you'll like to take the responsibility to keep the project going, not like the training homework or practice anymore, you'll need to assign yourself some issues, I think we can simply say that it's from passive to active, that's all.

I'll like to have some contribution checkpoints ☑️  here to specifically point the things out that I wish the one who'll like to become a maintainer will take as the end of the training (as their most contributions are focus on adding library)

 - 🤔 idea 
 - 📏 code / structure 
 - 🌐 website / api
 - 📝 document 
 - 🆘 help the outside contributor finish their contribution 

I think that's all the notes 📓  I want to take right now, so it may not be very complete, please feel free to correct or remind me something, as this is an open source project, I'll like to be more open to let the others know how we get the new maintainers, though I know the interns may wanna just discuss in private, but that's fine, i's not forced to discuss in public.

At the end, just let you know that I'm not a native English speaker and I'm just trying to write my thoughts down to prevent I forget them too soon, sorry for the wrong spelling, wrong grammar and unusual tone. Thank you all 😄 

cc @cdnjs/team-cdnjs

**Comment by drewfreyling** [comment]
Nice work @peterdavehello

**Comment by PeterDaveHello** [comment]
Recently, @sufuf3 and @dakshshah96 are both very active, are both potential maintainer in future 😄
