### ISSUE TITLE
[Request] Add leaflet.groupedlayercontrol

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10674]
**Library name:** leaflet.groupedlayercontrol
**Git repository url:** https://github.com/ismyrnow/Leaflet.groupedlayercontrol
**License (List them all if it's multiple):** MIT

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by smendez93** [comment]
Hello! I submitted a pull request for this: #10709
I'm kind of new at this but hopefully I did it all correctly.

**Comment by PeterDaveHello** [comment]
@smendez93 cool, we'll help you make it correctly!

**Comment by PeterDaveHello** [comment]
@qwe19272375 any reason this was not labeled with `in progress`? (and some of the others)

**Comment by qwe19272375** [comment]
@PeterDaveHello Sorry, waffle.io did not show every issue that has related PR.
I checked every issue with `Library - Request to Add/Update` manually, and the work should have been correctly done this time.
