### ISSUE TITLE
[Request] Add shower 

### ISSUE THREAD

**Issue by luo820802** [cdnjs/cdnjs#10670]
**Library name:** shower
**Git repository url:** https://github.com/shower/shower
**npm package url(optional):** https://www.npmjs.com/package/shower-core
**License(s):** MIT License
**Official homepage:** https://shwr.me/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t
