### ISSUE TITLE
`mediaelement-plugins` not showing latest version

### ISSUE THREAD

**Issue by ron666** [cdnjs/cdnjs#10688]
I upgraded the `mediaelement-plugins` repo to the next version, but I don't see it reflected here.

**Comment by hare1039** [comment]
Hi @ron666,
Our bot update to `1.2.0` 2 hours ago. Anything we can help you more?

**Comment by ron666** [comment]
I have updated my package.json to reflect the next version is there something else I need to do?

**Comment by ron666** [comment]
I checked again and I still see 1.1.0 as the latest version

**Comment by ron666** [comment]
Update: I don't see the `1.2.0` in your search engine, but if I type anything in the address bar with `1.2.0`, I can find them. Did I miss anything in order to make it display on the search engine?
<img width="795" alt="screen shot 2017-02-22 at 6 36 55 am" src="https://cloud.githubusercontent.com/assets/910829/23209921/579d2068-f8c9-11e6-8736-1de962f897c2.png">
<img width="1115" alt="screen shot 2017-02-22 at 6 37 36 am" src="https://cloud.githubusercontent.com/assets/910829/23209943/6bb83cb8-f8c9-11e6-9066-67c93d89b86d.png">

**Comment by ron666** [comment]
Content cached. After forced refresh, I could see the new version. Thanks for your help!
