### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css

### ISSUE THREAD

**Issue by amit116** [cdnjs/cdnjs#10685]
**Library name:** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @amit116,
Our [font-awesome](https://cdnjs.com/libraries/font-awesome) library have latest version. 
What else can we help you?

Note this issue will close if no response in 7 days.

**Comment by hare1039** [comment]
Close due to no response. cc @PeterDaveHello
