### ISSUE TITLE
[Request] Add jquery-form-observe 

### ISSUE THREAD

**Issue by animeshsinghweb** [cdnjs/cdnjs#10681]
**Library name:** jquery-form-observe
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
Just found:
https://code.google.com/archive/p/jquery-form-observe/downloads

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@PeterDaveHello How do we evaluate popularity from google code?

**Comment by PeterDaveHello** [comment]
There is "star" here: https://code.google.com/archive/p/jquery-form-observe/

but Google code is shutdown for a while, this is an archive site, we need some other reliable source.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
