### ISSUE TITLE
[Request] Add Flexicious React DataGrid

### ISSUE THREAD

**Issue by flexicious** [cdnjs/cdnjs#10692]
**Flexicious React DataGrid:** 
**https://github.com/flexicious/react-datagrid** 
**https://www.npmjs.com/package/flexicious-react-datagrid** (if there is one): 
**Commercial** 
**http://www.reactdatagrid.com/** 
**Would like to host the React DataGrid component developed by our company.** 

=====================

**Comment by clairetsai818** [comment]
Hi @flexicious!
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello

**Comment by flexicious** [comment]
Hello, we are at 2K downloads/month now - does this qualify us now?

**Comment by clairetsai818** [comment]
@flexicious Sure! We'll work on this issue soon.

**Comment by clairetsai818** [comment]
close due duplicated issue #10849, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@clairetsai818 we
