### ISSUE TITLE
[Request] Add pageAccelerator

### ISSUE THREAD

**Issue by floogulinc** [cdnjs/cdnjs#10702]
**Library name:** pageAccelerator
**Git repository url:** https://github.com/Easyfood/pageAccelerator
**npm package name or url** (if there is one): page-accelerator
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/Easyfood/pageAccelerator
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by floogulinc** [comment]
Thanks for this.

**Comment by PeterDaveHello** [comment]
@floogulinc you're welcome.
