### ISSUE TITLE
[Request] Add Angular Leaflet

### ISSUE THREAD

**Issue by JoseGoncalves** [cdnjs/cdnjs#10701]
**Library name:** Angular Leaflet
**Git repository url:** https://github.com/angular-ui/ui-leaflet
**npm package name or url** (if there is one): https://www.npmjs.com/package/ui-leaflet 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://angular-ui.github.io/ui-leaflet/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
duplicate #10121

**Comment by JoseGoncalves** [comment]
@hare1039 sorry, missed that.

**Comment by PeterDaveHello** [comment]
@JoseGoncalves no worries
