### ISSUE TITLE
[author][Request] Add Form JS Framework

### ISSUE THREAD

**Issue by the94air** [cdnjs/cdnjs#10710]
Library name: Form JS Framework 
Git repository url: https://github.com/the94air/formjs
License (List them all if it's multiple): MIT License
Official homepage: https://form.js.org
Wanna say something? Leave message here:

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @the94air 
The library doesn't have enough popularity(100 stars/watchers on GitHub is a good example). You can take a look on our [README](https://github.com/cdnjs/cdnjs/blob/master/README.md) for more details :)
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@the94air we'll accept pull request to add it if you'll like to send us, thanks.

**Comment by the94air** [comment]
Ok, I will :+1:

**Comment by PeterDaveHello** [comment]
@the94air thanks

**Comment by PeterDaveHello** [comment]
Let's re-open it first.

**Comment by the94air** [comment]
Dame this is hard :sob: . I really can't send a pull request. here I said it. I apologize for letting you waiting for nothing. I am so Sorry. Any help ??

**Comment by PeterDaveHello** [comment]
@the94air we can help you finish it if you want!

**Comment by the94air** [comment]
Ok, just tell me what you need ?? :+1:

**Comment by PeterDaveHello** [comment]
@the94air glad you'll like to keep going. @pvnr0082t @maruilian11 please help @the94air! Thanks.

**Comment by maruilian11** [comment]
Hi @the94air, Adding a single package.json is the most easy way to add a lib. You can do it by only using GitHub website GUI. see instructions [here](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson). If you meet any problem, we'll help you 😃

**Comment by the94air** [comment]
I am having a problem with the `filename` because I have 2 files 
`formjs.min.css`
`formjs.min.js`
what can I do? Thanks

**Comment by the94air** [comment]
I am having a problem with the `filename` because I have 2 files 
`formjs.min.css`
`formjs.min.js`
what can I do? Thanks

**Comment by PeterDaveHello** [comment]
@the94air just pick one :)

**Comment by the94air** [comment]
There are a problem in the indent that I can't get rid of

**Comment by maruilian11** [comment]
@the94air You can use `fixFormat.js` to fix indent problem. :smiley: 
https://github.com/cdnjs/cdnjs/blob/master/tools/fixFormat.js

If that can't solve it, please provide some error msg, thanks!

**Comment by the94air** [comment]
The indent problem solved but PR changes has passed more than 3 day. Should i make a new PR ? Thanks

**Comment by PeterDaveHello** [comment]
@the94air we'll take a look at it soon, sorry for the delay.

**Comment by the94air** [comment]
Thanks @PeterDaveHello @pvnr0082t @extend1994 @maruilian11 for all the help . I really appreciate it. I hope you all the best.

**Comment by PeterDaveHello** [comment]
@the94air you're welcome!
