### ISSUE TITLE
[Request] Add vue-ls

### ISSUE THREAD

**Issue by RobinCK** [cdnjs/cdnjs#10733]
**Library name**: vue-ls
**Git repository url**: https://github.com/RobinCK/vue-ls
**npm package name or url** (if there is one): https://www.npmjs.com/package/vue-ls
**License (List them all if it's multiple):** MIT 
**Official homepage:** https://robinck.github.io/vue-ls/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by RobinCK** [comment]
Will the package be added?

**Comment by extend1994** [comment]
@RobinCK Yes I will finish the job ASAP!
