### ISSUE TITLE
Update Wiki page - "Extensions, Plugins, Resources"

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10732]
There are some cool stuffs we should add to this page, this page is totally out-dated.

**Comment by xtuc** [comment]
I think we should keep this open to eventually clean the wiki

**Comment by MattIPv4** [comment]
As this repository is now robot-only, I've removed the wiki (all other docs were removed via a PR) -- We can look at adding new versions of the old wiki content here to cdnjs/packages docs if we think it's needed. ([cdnjs-old-wiki.md](https://gist.github.com/MattIPv4/453e365bcc7498157363f832af75a819))
