### ISSUE TITLE
[Request] knockout-select2

### ISSUE THREAD

**Issue by mumair85** [cdnjs/cdnjs#10730]
**Library name:** knockout-select2
**Git repository url:** https://github.com/cruikshj/knockout-select2
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** https://github.com/cruikshj/knockout-select2
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Hi @mumair85 !
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello
