### ISSUE TITLE
Why https://cdnjs.com/libraries/free-jqgrid selects old version?

### ISSUE THREAD

**Issue by OlegKi** [cdnjs/cdnjs#10742]
The new version 4.14.0 of free-jqgrid seems be successfuly deployed yesterday (see https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/free-jqgrid), but https://cdnjs.com/libraries/free-jqgrid select the previous version 4.13.6 instead on the latest 4.14.0.

The button ![Image of free-jqgrid](https://img.shields.io/cdnjs/v/free-jqgrid.svg), which uses the URL https://img.shields.io/cdnjs/v/free-jqgrid.svg, displays the old version too.

Could you fix the problem please?

**Comment by PeterDaveHello** [comment]
@OlegKi I'll take a look.

**Comment by PeterDaveHello** [comment]
@OlegKi There was a mistake about its version update, fixed, thanks.

**Comment by OlegKi** [comment]
@PabloVallejo Thank you very much!
