### ISSUE TITLE
[Request] [Author] ECKit

### ISSUE THREAD

**Issue by elijahcruz12** [cdnjs/cdnjs#10757]
**Library name:** ECkit
**Git repository url:** https://github.com/ECWebServices/ECKit
**License (List them all if it's multiple):** MIT
**Official homepage:** None currently, Will be one soon.
**Wanna say something? Leave message here:** This is currently Mainly CSS, but has some JavaScript, but will become more JavaScript in the future. Also the latest version is listed as a release.

**Comment by extend1994** [comment]
Hi @elijahcruz12  
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by extend1994** [comment]
Close the issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@elijahcruz12 if you'd like to sen us a pull request, we'll be happy to help you add it, thanks.
