### ISSUE TITLE
[Request] Add Nicedit

### ISSUE THREAD

**Issue by MrChriZ** [cdnjs/cdnjs#10753]
**Library name:** 
Nicedit
**Git repository url:** 
https://github.com/danishkhan/NicEdit
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
MIT
**Official homepage:** 
http://nicedit.com/

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicated with #8653.

**Comment by PeterDaveHello** [comment]
@sufuf3 you should add labels as @hare1039 did.

**Comment by PeterDaveHello** [comment]
Let's close duplicated issue, move to #8653.
