### ISSUE TITLE
[Request] Add fancyBox 3

### ISSUE THREAD

**Issue by evromalarkey** [cdnjs/cdnjs#10758]
**Library name:** fancyBox 3
**Git repository url:** https://github.com/fancyapps/fancybox
**npm package name or url** (if there is one): https://github.com/fancyapps/fancybox/blob/master/package.json
**License (List them all if it's multiple):** GPL-3.0
**Official homepage:** http://fancyapps.com/fancybox/3/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Duplicated with #6191

**Comment by evromalarkey** [comment]
that's not the same version, the stable 3.0.32 release is now on fancybox master branch

**Comment by PeterDaveHello** [comment]
Move to #6191
