### ISSUE TITLE
[Request] React Toolbox

### ISSUE THREAD

**Issue by chiester** [cdnjs/cdnjs#10754]
**Library name:** React Toolbox
**Git repository url:** https://github.com/react-toolbox/react-toolbox
**npm package name or url** (if there is one): react-toolbox
**License (List them all if it's multiple):** MIT
**Official homepage:** http://react-toolbox.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicated with #10069.

**Comment by PeterDaveHello** [comment]
Let's move to  #10069
