### ISSUE TITLE
Remove unrelated files from object-fit-images

### ISSUE THREAD

**Issue by bfred-it** [cdnjs/cdnjs#10761]
Of all these files, only the last two are meant to be used in the browser. The rest has `exports` and `export` commands.

<img width="920" alt="screen shot 2017-03-01 at 11 36 01" src="https://cloud.githubusercontent.com/assets/1402241/23446142/98c008ae-fdf5-11e6-9e49-46d5de252393.png">

https://cdnjs.com/libraries/object-fit-images

**Comment by hare1039** [comment]
@PeterDaveHello I think it is impossible to delete files from cdnjs, is it?

**Comment by PeterDaveHello** [comment]
@hare1039 If the files are confirmed useless then we can.

**Comment by bfred-it** [comment]
@hare1039 unlisting it would be enough.

@PeterDaveHello yes:

 - `common-js` is unlikely to be used in the browser;
 - `es-modules` can't be used either, at least until `<script type=module>` becomes widespread

**Comment by PeterDaveHello** [comment]
Thanks @bfred-it, @hare1039 you could be the first member of @cdnjs/intern3 to remove library files on cdnjs 😎
