### ISSUE TITLE
[Request] Add MUI

### ISSUE THREAD

**Issue by qhhsy** [cdnjs/cdnjs#10769]
**Library name:** mui
**Git repository url:** https://github.com/dcloudio/mui.git
**License (List them all if it's multiple):** MIT
**Official homepage:** https://dev.dcloud.net.cn/mui
thanks!!

**Comment by hare1039** [comment]
Hi @phhsy,
Our member is currently working on this, and I think the PR will be soon merged,
so please wait a few more days. Thanks!

duplicate #10514

**Comment by PeterDaveHello** [comment]
@hare1039 let's directly close duplicated issue and move to the earlier one next time.

**Comment by PeterDaveHello** [comment]
Move to #10514
