### ISSUE TITLE
[Request] Add jquery-tokeninput

### ISSUE THREAD

**Issue by fverry** [cdnjs/cdnjs#10774]
**Library name:** jquery-tokeninput
**Git repository url:** https://github.com/loopj/jquery-tokeninput
**License (List them all if it's multiple):** choose GPL or MIT license 
**Official homepage:** http://loopj.com/jquery-tokeninput/

**Comment by extend1994** [comment]
@PeterDaveHello Could you please help me take a look at this lib, I am not sure the format of the tag is suitable or not. Thanks.

**Comment by PeterDaveHello** [comment]
Can only use for v1.7.0+, so you'll need to manually add the old versions (and may need to exclude old but not suitable versions in .gitignore).
