### ISSUE TITLE
[Request] Add unveil2

### ISSUE THREAD

**Issue by stephengroat** [cdnjs/cdnjs#10782]
**Library name:** unveil2
**Git repository url:** https://github.com/nabble/unveil2
**npm package name or url** (if there is one): https://www.npmjs.com/package/unveil2
**License (List them all if it's multiple):** MIT
**Official homepage:** nabble.github.io/unveil2
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @stephengroat 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by stephengroat** [comment]
I completely understand.

I was hoping that there could be an exception since a previous, now
un-maintained version (https://cdnjs.com/libraries/unveil) is listed

**Comment by PeterDaveHello** [comment]
We can wait for a while 😄

**Comment by PeterDaveHello** [comment]
Looks good on npm now.
