### ISSUE TITLE
[Author] [Request] Add Gijgo

### ISSUE THREAD

**Issue by atatanasov** [cdnjs/cdnjs#10799]
**Library name:** Gijgo
**Git repository url:** https://github.com/atatanasov/gijgo/
**npm package name or url** (if there is one): https://www.npmjs.com/package/gijgo
**License (List them all if it's multiple):** MIT License
**Official homepage:** http://gijgo.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@atatanasov this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by atatanasov** [comment]
Sounds good. I will reopen the issue once we reach this popularity.

**Comment by sufuf3** [comment]
@atatanasov sorry about that I didn't notice that you are the author of this library.
Would you like to send a pull request to add it?? Thanks.

**Comment by PeterDaveHello** [comment]
@atatanasov would you like to send us a pull request? I think we can accept this one, thanks.

**Comment by atatanasov** [comment]
done. 
this is the request https://github.com/cdnjs/cdnjs/pull/11076

**Comment by PeterDaveHello** [comment]
#11076 -> #11077

**Comment by PeterDaveHello** [comment]
Moved to #11110

**Comment by sashberd** [comment]
@PeterDaveHello The #11110 was merged
Close this one
