### ISSUE TITLE
Add missing versions of bootstrap-rtl

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#10793]
**Library name:** bootstrap-rtl
**Git repository url:** https://github.com/morteza/bootstrap-rtl
**License (List them all if it's multiple):** [Unlicense](https://github.com/morteza/bootstrap-rtl/blob/master/UNLICENSE)

**Comment by PeterDaveHello** [comment]
@extend1994 let's remove the items you don't need it.
