### ISSUE TITLE
jquery-countdown

### ISSUE THREAD

**Issue by Tzouhalem** [cdnjs/cdnjs#10796]
**Library name:** jquery-countdown
**Git repository url:** https://github.com/kbwood/countdown
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT licence
**Official homepage:** http://keith-wood.name/countdown.html
**Wanna say something? Leave message here:** Hello. There is already an entry for this 'jquery-countdown' but it is an old version (ie: 2.0.2) whereas the latest version is 2.1.0. The original CDNJS entry for 'jquery-countdown' jQuery plugin was NOT done by the author, Keith Wood - Keith did not even know that his plugin was available from the CDNJS - Keith has confirmed that it was OK for the plugin to be available from the CDNJS (wood.keith@optusnet.com.au). Thank you. Sincerely, Ray Beriau (ray@tzweather.org).

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
The library is already [hosted](https://cdnjs.com/libraries/jquery-countdown) on cdnjs
