### ISSUE TITLE
[Request] Add Bootswatch v4 Alpha

### ISSUE THREAD

**Issue by xeoneux** [cdnjs/cdnjs#10806]
**Library name: Bootswatch** 
**Git repository url: https://github.com/thomaspark/bootswatch** 
**npm package name or url: https://www.npmjs.com/package/bootswatch** 
**License: MIT** 
**Official homepage: https://bootswatch.com/4-alpha/**

**Comment by hare1039** [comment]
Hi @xeoneux,
We have the latest version of [bootswatch](https://cdnjs.com/libraries/bootswatch). What else can we help you?

**Comment by xeoneux** [comment]
Hi @hare1039 
The latest alpha builds of the library for Bootstrap v4 in Alpha aren't present.
It would get really convenient to include it directly to cdnjs.
I am not able to create a fork due to the size of the repository and would really appreciate the help.

**Comment by hare1039** [comment]
@PeterDaveHello Could we add alpha versions manually?

**Comment by PeterDaveHello** [comment]
@xeoneux maybe you can ask its author to release alpha versions on npm.
