### ISSUE TITLE
[Request] Add Tez.js

### ISSUE THREAD

**Issue by dalisoft** [cdnjs/cdnjs#10800]
**Library name:** Tez
**Git repository url:** https://github.com/dalisoft/tez
**npm package name or url** (if there is one): tez.js
**License (List them all if it's multiple):** Apache License 2.0
**Official homepage:** https://github.com/dalisoft/tez
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@lcd78706 please take this issue

**Comment by dalisoft** [comment]
@PeterDaveHello @x09326 @lxd78706 any news? One library adding takea too much. Even i have 3 lib on jsdelivr, but there no answer.

**Comment by PeterDaveHello** [comment]
@dalisoft sorry for the delay, as you can see, there are tons of request issues, maybe you can consider to send us a pull request?

**Comment by dalisoft** [comment]
I am dont know how to make PR for files. When i make PR for one file. Then after update, i should again make PR? Jsdelivr has docs for file and auto-update

**Comment by dalisoft** [comment]
I know i has unpkg and jsdelivr. But i am wished see library on all CDN hosting

**Comment by PeterDaveHello** [comment]
@dalisoft auto-update doc: https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

**Comment by PeterDaveHello** [comment]
@dalisoft you can create a branch, commit multiple files, and then create the PR, we also support to add library via single package.json:
doc: https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson
example: https://github.com/cdnjs/cdnjs/pull/10810

**Comment by PeterDaveHello** [comment]
@dalisoft thanks

**Comment by dalisoft** [comment]
Thanks to you +1

**Comment by dalisoft** [comment]
@PeterDaveHello As i see PR is draft, so you can close issue. Or i close (if you can't). Thanks

**Comment by PeterDaveHello** [comment]
no problem
