### ISSUE TITLE
Remove '/ajax/libs/' from url. Make mirror.

### ISSUE THREAD

**Issue by ianberdin** [cdnjs/cdnjs#10804]
Remove '/ajax/libs/' from url. Make mirror.
Shorten -> better

From `cdnjs.cloudflare.com/ajax/libs/vue/2.2.1/vue.min.js`
To `cdnjs.cloudflare.com/vue/2.2.1/vue.min.js`

Much more clean.

**Comment by MattIPv4** [comment]
Cloudflare are looking into the viability of this and should provide a situation update early next week. I will post any updates I receive here.

**Comment by MattIPv4** [comment]
@PeterDaveHello Cloudflare are saying this is possible with a worker.
I've read through their tutorials and this and have reached the following worker js.

```javascript
addEventListener('fetch', event => {
  event.respondWith(fetchAndApply(event.request))
})

function fetchAndApply(request) {
  const requestURL = new URL(request.url)
  if(!requestURL.pathname.startsWith("/ajax/libs")) requestURL.pathname = "/ajax/libs" + requestURL.pathname
  return fetch(requestURL.toString(), request)
}
```

Could you confirm is this is correct before I send it back to them?

**Comment by MattIPv4** [comment]
We are currently working to deploy a Cloudflare worker that should handle redirecting `/*` to `/ajax/libs/*` :)

**Comment by MattIPv4** [comment]
As we are now tracking these issues with Cloudflare through these issues directly, the worker that we are intending to deploy can be found at https://gist.github.com/MattIPv4/1371cac248d763ab93fc5c13056cef96#file-cdnjs-worker-js

**Comment by xtuc** [comment]
Cloudflare isn't planning to run a worker on cdnjs.cloudflare.com or to remove the `/ajax/libs/` urls at this time. @MattIPv4 has a good workaround, you can put on Cloudflare Worker (or any serverless function) to route the requests from `/` back to `cdnjs.cloudflare.com/ajax/libs/...`.
