### ISSUE TITLE
[Request] Add wdt-emoji-bundle

### ISSUE THREAD

**Issue by itdev** [cdnjs/cdnjs#10809]
**Library name:** wdt-emoji-bundle 
**Git repository url:** https://github.com/needim/wdt-emoji-bundle
**npm package name or url** (if there is one): https://www.npmjs.com/package/wdt-emoji-bundle
**License (List them all if it's multiple):** MIT
**Official homepage:** http://ned.im/wdt-emoji-bundle/

**Comment by hare1039** [comment]
Hi @itdev,
This library will be add in a few more days. Please wait for our process. Thanks.

Move to #9911.
