### ISSUE TITLE
[Author] [Request] Add FPO

### ISSUE THREAD

**Issue by getify** [cdnjs/cdnjs#10811]
**Library name:** FPO
**Git repository url:** https://github.com/getify/fpo
**npm package name or url** (if there is one): https://www.npmjs.com/package/fpo
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/getify/fpo

**Comment by getify** [comment]
Ping. :)

**Comment by hare1039** [comment]
@getify We're sorry that we let you waiting for so long.
I suggest you can add this library by yourself. Here's the steps: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

Here is a valid package.json
```
{
  "name": "fpo",
  "filename": "fpo.min.js",
  "description": "FP library for JavaScript. Supports named-argument style methods.",
  "repository": {
    "type": "git",
    "url": "https://github.com/getify/fpo.git"
  },
  "keywords": [
    "fp",
    "functional",
    "programming"
  ],
  "author": "Kyle Simpson <getify@gmail.com>",
  "license": "MIT",
  "npmName": "fpo",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    }
  ]
}
```

And commit with message like:
```
Add fpo w/ npm auto-update via single package.json

close #10811
```

**Comment by getify** [comment]
@hare1039 thanks for the detailed instructions, just submitted #11760
