### ISSUE TITLE
[author] [Request] Add Country-Region Dropdown Menu

### ISSUE THREAD

**Issue by geodatasource** [cdnjs/cdnjs#10825]
**Library name:** Country-Region Dropdown Menu
**Git repository url:** https://github.com/geodatasource/country-region-dropdown-menu
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** https://github.com/geodatasource/country-region-dropdown-menu/blob/master/license.txt
**Official homepage:** http://www.geodatasource.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @geodatasource 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by PeterDaveHello** [comment]
I think we can host this one if @geodatasource you'll like to send us a pull request, thanks.
