### ISSUE TITLE
[Request] Add bulmaswatch

### ISSUE THREAD

**Issue by jenil** [cdnjs/cdnjs#10823]
**Library name:** Bulmaswatch
**Git repository url:** https://github.com/jenil/bulmaswatch
**npm package name or url** (if there is one): bulmaswatch
**License (List them all if it's multiple):** MIT
**Official homepage:** https://jenil.github.io/bulmaswatch

**Comment by clairetsai818** [comment]
Hi @jenil 
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello

**Comment by jenil** [comment]
hey! Bulmaswatch now has 100+ stars, can I reopen this issue or make a new one?

**Comment by PeterDaveHello** [comment]
@jenil and maybe just send us a pull request?
