### ISSUE TITLE
[Request] Add react-dom

### ISSUE THREAD

**Issue by dcu-sharepoint** [cdnjs/cdnjs#10828]
**Library name:** 
**Git repository url:** https://github.com/facebook/react/
**npm package name or url** (if there is one): https://github.com/facebook/react
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Hi @dcu-sharepoint!
We've already have [react](https://cdnjs.com/libraries/react) with the latest version on our CDN, what else can we help you? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by dcu-sharepoint** [comment]
Thank you; I'm getting into react as we speak and what I though I was looking for was ReactDOM which I couldn't. thank you for your quick response and great service.



________________________________

**Comment by clairetsai818** [comment]
Close because this lib was added and updated to the latest version, cc @PeterDaveHello

**Comment by dcu-sharepoint** [comment]
thank you again;
