### ISSUE TITLE
File permission check on CI

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#10831]
The file permission check on CI only run on the latest version. If the file permission is wrong in old versions, CI won't catch that. We should improve CI to check file permission for old versions of lib.

cc #10791 
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t wrong repo

**Comment by pvnr0082t** [comment]
move to https://github.com/cdnjs/cdnjs-drone-ci/issues/5
