### ISSUE TITLE
[Request] Add ie7-js

### ISSUE THREAD

**Issue by garrett-leyenaar** [cdnjs/cdnjs#10838]
Library name: ie7-js 
Git repository url: https://github.com/jkiss/ie7-js 
This used to be on Googlecode but that has since come down for some reason, all Bootstrap installs use this code to bring old IE installs up to date with modern standards

**Comment by clairetsai818** [comment]
Hi @garrett-leyenaar!
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by extend1994** [comment]
Close the issue because of insufficient popularity and no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@clairetsai818 please assign the issues waiting for response to yourself and don't forget to close them if there is no response.
