### ISSUE TITLE
[Request] Add abcjs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#10842]
**Library name:** abcjs
**Git repository url:** https://github.com/paulrosen/abcjs
**License (List them all if it's multiple):**  MIT

The last time the lib been updated is Aug 2014, the filenames contain version number, so we may need to manually add all the versions first.

cc @jackycute

**Comment by extend1994** [comment]
@PeterDaveHello Is adding files under `bin` correct? 
(I think so because you mentioned 
> the filenames contain version number
)

**Comment by PeterDaveHello** [comment]
Yeah I guess so, you can still open an issue to confirm that in the meantime.

**Comment by PeterDaveHello** [comment]
@extend1994 do we have any updates here?

**Comment by extend1994** [comment]
@PeterDaveHello Yes I am still discussing with the author.

**Comment by PeterDaveHello** [comment]
Okay, let's add this one ASAP, thanks.
