### ISSUE TITLE
[Request] Update Inferno libraries

### ISSUE THREAD

**Issue by Havunen** [cdnjs/cdnjs#10840]
Library name: inferno
Git monorepo root https://github.com/infernojs/inferno   (changed)
packages (GIT):
https://github.com/infernojs/inferno/tree/master/packages/inferno-compat
https://github.com/infernojs/inferno/tree/master/packages/inferno-component
https://github.com/infernojs/inferno/tree/master/packages/inferno-create-class
https://github.com/infernojs/inferno/tree/master/packages/inferno-create-element
https://github.com/infernojs/inferno/tree/master/packages/inferno-devtools
https://github.com/infernojs/inferno/tree/master/packages/inferno-hyperscript
https://github.com/infernojs/inferno/tree/master/packages/inferno-mobx
https://github.com/infernojs/inferno/tree/master/packages/inferno-redux
https://github.com/infernojs/inferno/tree/master/packages/inferno-router
https://github.com/infernojs/inferno/tree/master/packages/inferno-server
https://github.com/infernojs/inferno/tree/master/packages/inferno-shared
https://github.com/infernojs/inferno/tree/master/packages/inferno-test-utils
https://github.com/infernojs/inferno/tree/master/packages/inferno-vnode-flags
https://github.com/infernojs/inferno/tree/master/packages/inferno

npm package url(optional):
- [x] https://www.npmjs.com/package/inferno-compat
- [x] https://www.npmjs.com/package/inferno-component
- [x] https://www.npmjs.com/package/inferno-create-class
- [x] https://www.npmjs.com/package/inferno-create-element
- [x] https://www.npmjs.com/package/inferno-devtools
- [x] https://www.npmjs.com/package/inferno-hyperscript
- [x] https://www.npmjs.com/package/inferno-mobx
- [x] https://www.npmjs.com/package/inferno-redux
- [x] https://www.npmjs.com/package/inferno-router
- [x] https://www.npmjs.com/package/inferno-server
- [x] https://www.npmjs.com/package/inferno-shared
- [x] https://www.npmjs.com/package/inferno-test-utils
- [x] https://www.npmjs.com/package/inferno-vnode-flags
- [x] https://www.npmjs.com/package/inferno

License(s): The MIT license
Official homepage: http://infernojs.org/

**Comment by dakshshah96** [comment]
@PeterDaveHello Looks like each package listed here is a separate one. Am I right?

The only one already existing in CDNJS is https://www.npmjs.com/package/inferno

**Comment by PeterDaveHello** [comment]
@dakshshah96 seems so.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please give hands on this issue.
