### ISSUE TITLE
[Request] Add fancyBox3

### ISSUE THREAD

**Issue by Machou** [cdnjs/cdnjs#10851]
**Library name:** fancyBox3
**Git repository url:** https://github.com/fancyapps/fancybox
**License (List them all if it's multiple):** fancyBox is licensed under the GPLv3 license for all open source applications. A commercial license is required for all commercial applications (including sites, themes and apps you plan to sell).
**Official homepage:** http://fancyapps.com/fancybox/3/

**Comment by PeterDaveHello** [comment]
Added in #8357
