### ISSUE TITLE
[Request] OrgChart

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10857]
**Library name:** OrgChart
**Git repository url:** https://github.com/dabeng/OrgChart
**npm package name or url** (if there is one): https://www.npmjs.com/package/orgchart
**License (List them all if it's multiple):** MIT
**Official homepage:** http://dabeng.github.io/OrgChart/
**Wanna say something? Leave message here:** 
This library has 4 different types of codes e.g. es6/web/jquery
For your review and add

**Comment by sashberd** [comment]
@PeterDaveHello 
This library has 3 different types in 3 different GitHub repositories How could we merge them together?
[https://github.com/dabeng/OrgChart](JQUERY)
[http://github.com/dabeng/OrgChart.js](ES6)
[http://github.com/dabeng/OrgChart-Webcomponents](WebComponents)

**Comment by PeterDaveHello** [comment]
Note: I replied in the PR :)
