### ISSUE TITLE
[Request] Add Bootstrap Big Grid

### ISSUE THREAD

**Issue by ejsiddiqui** [cdnjs/cdnjs#10850]
**Bootstrap Big Grid:** 
**https://github.com/BenWhitehead/bootstrap-big-grid** 
**Usage**: bower install --save bootstrap-big-grid:
**License:** Copyright 2013-2014 Ben Whitehead under the Apache 2.0 license:
**Homepage:** http://benwhitehead.github.io/bootstrap-big-grid/
**The default Bootstrap Grid only provides grid dimensions up to 1200px. Using the same mixins and variables provided by Bootstrap, the grid has been extended to support various larger resolution screens, such as HDTVs and the 15" Retina MacBook Pro.** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@ejsiddiqui this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by ejsiddiqui** [comment]
Hi,

You can close the ticket. I thought it would be very useful for every as it fills the holes in a very popular library.

I requested for the general good of the community and have no affiliation with it.

Regards
Ejaz Siddiqui
________________________________

**Comment by sashberd** [comment]
Still low popularity. Suggest to close

**Comment by sufuf3** [comment]
@ejsiddiqui You can open an issue again when the library has more popularity. :)
@sashberd Thanks

Close because this library doesn't have enough popularity. 
cc @PeterDaveHello
