### ISSUE TITLE
lamejs

### ISSUE THREAD

**Issue by nitank** [cdnjs/cdnjs#10867]
**Library name:*lame.min.js* 
**Git repository url:*https://github.com/logbon72/angular-recorder/blob/master/lib/lame.min.js* 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@nitank this repository doesn't reach our popularity requirement and it doesn't looks like the source repository of lame.min.js, do you mean this one? https://github.com/cdnjs/cdnjs/issues/12132

**Comment by MattIPv4** [comment]
No progress, closing.
