### ISSUE TITLE
[Request] Add Photon

### ISSUE THREAD

**Issue by UtkarshDubey1** [cdnjs/cdnjs#10865]
**Photon:** 
**https://github.com/connors/photon:** 
**npm package name or url** (if there is one): 
**MIT:** 
**photonkit.com:** 
**Please Add it its important for electron users:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@PeterDaveHello This library has a lot of stars, but there is no stable version. Should I add it now or wait for the stable version?

**Comment by PeterDaveHello** [comment]
Enough starts to directly add it, thanks.

**Comment by UtkarshDubey1** [comment]
Hey please u can add it directly its useful

**Comment by PeterDaveHello** [comment]
Reassign to @hare1039
