### ISSUE TITLE
[Request] Add owfont 

### ISSUE THREAD

**Issue by karanjamutahi** [cdnjs/cdnjs#10861]
**Library name:owfont - symbol font for Open Weather Map API** 
**Git repository url:https://github.com/websygen/owfont/** 
**npm package name or url** NONE 
**License : SIL OFL 1.1, MIT, CC BY 3.0** 
**Official homepage :http://websygen.github.io/owfont** 
**Pretty Please** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by extend1994** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@sufuf3  please assign the issues waiting for response to yourself and don't forget to close them if there is no response.
