### ISSUE TITLE
[Request] Add d3-hexbin

### ISSUE THREAD

**Issue by steelskysoftware** [cdnjs/cdnjs#10885]
**Library name:** d3-hexbin
**Git repository url:** https://github.com/d3/d3-hexbin
**npm package name or url** (if there is one):  https://www.npmjs.com/package/d3-hexbin
**License (List them all if it's multiple):** BSD-3-Clause
**Official homepage:** https://d3js.org/
**Wanna say something? Leave message here:** Official plugin for d3js

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/d3-hexbin
