### ISSUE TITLE
[Request] Fix jsrsasign

### ISSUE THREAD

**Issue by elad** [cdnjs/cdnjs#10881]
**Library name:** jsrsasign
**Git repository url:** https://github.com/kjur/jsrsasign
**npm package name or url** (if there is one): https://www.npmjs.com/package/jsrsasign
**License (List them all if it's multiple):** MIT
**Official homepage:** http://kjur.github.io/jsrsasign
**Wanna say something? Leave message here:** cdnjs is serving a version of this library that doesn't work with browsers. According to [jsrsasign/184](https://github.com/kjur/jsrsasign/issues/184) the library that should be used for browsers is http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello Should we delete the the files don't work with browser?

**Comment by PeterDaveHello** [comment]
If it's confirmed, yes.
