### ISSUE TITLE
[Request] Add OverlappingMarkerSpiderfier-Leaflet (sister item of current cdnjs repo)

### ISSUE THREAD

**Issue by kingy444** [cdnjs/cdnjs#10893]
**Library name:**  OverlappingMarkerSpiderfier-Leaflet
**Git repository url:** https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet
**npm package name or url** (if there is one): n/a
**License (List them all if it's multiple):**  This software is released under the MIT licence.
**Official homepage:**  https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet
**Wanna say something? Leave message here:**  This repo is a clone of https://github.com/jawj/OverlappingMarkerSpiderfier which is already hosted by you. Both are by the same author, with the -leaflet version adding the functionality to a leafleat mapset rather than a google mapset. The author actually links this repo in the original repo. 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kingy444** [comment]
apologies, im new to this. it appears that the JS that i want uploaded is not listed directly as an item within the repo files, the direct link http://jawj.github.com/OverlappingMarkerSpiderfier-Leaflet/bin/oms.min.js 

it appears files i am after may be located here: 
https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet/tree/gh-pages

I'm going to assume you guys know what your doing here as the original version of this for google maps is already hosted (http://jawj.github.com/OverlappingMarkerSpiderfier-Leaflet)

**Comment by kingy444** [comment]
Is there anything I can do to try and expedite this process. I tried the whole shallow-clone thing in an attempt to submit a pull request but haven't been successful.

It would be great if we can get this into the repository as soon as possible.

**Comment by PeterDaveHello** [comment]
Hi @kingy444 sorry that I didn't see your comment earlier, @jawj sent pull request #11227 here, so I think we don't need to do anything else. If you're interested in help adding new libraries, maybe you can take a look at #9822 #9821 #9820, thanks a lot!
