### ISSUE TITLE
[Request] Add Gmaps Marker Clusterer

### ISSUE THREAD

**Issue by XmlmXmlmX** [cdnjs/cdnjs#10894]
**Library name:** Gmaps Marker Clusterer
**Git repository url:** https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer
**npm package name or url** (if there is one): https://www.npmjs.com/package/gmaps-marker-clusterer
**License (List them all if it's multiple):** Apache 2.0, CC BY-SA 4.0
**Official homepage:** https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/
**Wanna say something? Leave message here:** This project is a fork of the js-marker-clusterer library, the [original repository](https://github.com/googlemaps/js-marker-clusterer) is [no longer maintained](https://github.com/googlemaps/js-marker-clusterer/commit/dc326b9b9234ce964861eb35b416a6be1ca7d7cf). Yes, it doesn't have so many stars/watches. But it is maintained!

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@XmlmXmlmX this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can add this one, just give it a lower priority.
