### ISSUE TITLE
[Request] Add jquery-numerator

### ISSUE THREAD

**Issue by nkkollaw** [cdnjs/cdnjs#10892]
**Library name:** jquery-numerator
**Git repository url:** https://github.com/garethdn/jquery-numerator
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://garethdn.github.io/jquery-numerator/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@nkkollaw this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by nkkollaw** [comment]
Oh, sure.

I'm not the author, I just thought it was a cool lib.

Sorry, I hadn't seen "100 stars on GitHub or 500 downloads per month on npm" in the README.

Thanks! I'll close the issue.

**Comment by PeterDaveHello** [comment]
@nkkollaw if you'll like to send a pull request for us to add it, we'll like to help you do that :)

**Comment by nkkollaw** [comment]
@PeterDaveHello : mh?

**Comment by PeterDaveHello** [comment]
@nkkollaw I mean if you would like to send a pull request, we can try to add it.
