### ISSUE TITLE
[Request] Add moment-timer

### ISSUE THREAD

**Issue by sp4r74cus** [cdnjs/cdnjs#10905]
**Library name:** moment-timer
**Git repository url:** https://github.com/SeverinDK/moment-timer
**npm package name or url** (if there is one): https://www.npmjs.com/package/moment-timer
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/SeverinDK/moment-timer
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @harush 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can add this one, just give it a lower priority.
