### ISSUE TITLE
[Request] Add jQuery.i18n.properties

### ISSUE THREAD

**Issue by marfulee** [cdnjs/cdnjs#10907]
**Library name: jQuery.i18n.properties** 
**Git repository url: https://github.com/jquery-i18n-properties/jquery-i18n-properties.git** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple): MIT** 
**Official homepage: https://github.com/jquery-i18n-properties** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
