### ISSUE TITLE
[Request] Add jQuery.pulsate

### ISSUE THREAD

**Issue by plonknimbuzz** [cdnjs/cdnjs#10915]
**Library name:** jQuery.pulsate
**Git repository url:** https://github.com/Kilian/jQuery.pulsate
**npm package name or url** (if there is one): https://raw.github.com/Kilian/jQuery.pulsate/master/jquery.pulsate.js and https://raw.github.com/Kilian/jQuery.pulsate/master/jquery.pulsate.min.js
**License (List them all if it's multiple):** MIT https://github.com/Kilian/jQuery.pulsate/blob/master/LICENSE
**Official homepage:** https://kilianvalkhof.com/jquerypulsate/
**Wanna say something? Leave message here:** 1. this library is simple but beautiful, 2. this is light library (1.6kb) 3. i dont see any CDN hosting this library 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@plonknimbuzz This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by plonknimbuzz** [comment]
thank you for your reply.
sorry i dont read the readme (about popularity). because i just see SUBMIT request button in cdnjs website.
thanks for your great work

**Comment by PeterDaveHello** [comment]
@plonknimbuzz thanks for understanding, feel free to open a new request once it reached our minimum requirement, and thanks for being interested in CDNJS :)

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can add this one, just give it a lower priority.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
