### ISSUE TITLE
[Request] Add react-datepicker2

### ISSUE THREAD

**Issue by mberneti** [cdnjs/cdnjs#10918]
Library name: react-datepicker2
Git repository url: https://github.com/mberneti/react-datepicker2
npm package url(optional): https://www.npmjs.com/package/react-datepicker2
License(s): MIT
Official homepage: https://mberneti.github.io/react-datepicker2/

**Comment by sufuf3** [comment]
@mberneti this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by mberneti** [comment]
Oky, i'll open a new request, once it reaches your minimum requirement.

**Comment by PeterDaveHello** [comment]
@mberneti thanks a lot!

**Comment by PeterDaveHello** [comment]
@mberneti  if you'll like to send a pull request for us to add it, we'll like to help you do that :) What do you think?

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by sashberd** [comment]
Hi @mberneti 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
