### ISSUE TITLE
[Request] Add appendGrid

### ISSUE THREAD

**Issue by Wowenko** [cdnjs/cdnjs#10919]
**Library name:** appendGrid
**Git repository url:** https://github.com/hkalbertl/jquery.appendGrid
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Dual licensed under the LGPL and MIT licenses.
**Official homepage:** https://appendgrid.apphb.com/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @Wowenko 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: 
Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want!

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
