### ISSUE TITLE
[Request] Add scrollmagic

### ISSUE THREAD

**Issue by IsamarCDavila** [cdnjs/cdnjs#10923]
**Library name:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @IsamarDavilaG,
We have [ScrollMagic](https://cdnjs.com/libraries/ScrollMagic) at latest version. What can we help you more?

**Comment by omasback** [comment]
Can you add the scrollmagic GSAP plugin? and maybe the other plugins while you're at it?

https://github.com/janpaepke/ScrollMagic/tree/master/dev/src/plugins

**Comment by MattIPv4** [comment]
Plugins are available: https://cdnjs.com/libraries/ScrollMagic
