### ISSUE TITLE
[Request] Add angular-file-uploader

### ISSUE THREAD

**Issue by ConnorMcF** [cdnjs/cdnjs#10927]
**Library name:** angular-file-uploader
**Git repository url:** https://github.com/ghostbar/angular-file-uploader
**npm package name or url** (if there is one): N/A
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/ghostbar/angular-file-uploader
**Wanna say something? Leave message here:** N/A

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@ConnorMcF this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by ConnorMcF** [comment]
Oh sorry! Didn't see that part.
