### ISSUE TITLE
[Request] Add node-gol-hashlife

### ISSUE THREAD

**Issue by dloret** [cdnjs/cdnjs#10925]
**Library name:** node-gol-hashlife
**Git repository url:** https://github.com/rharel/node-gol-hashlife
**npm package name or url** (if there is one): https://github.com/rharel/node-gol-hashlife
**License (List them all if it's multiple):** MIT Licence (https://github.com/rharel/node-gol-hashlife/blob/master/LICENSE.txt)
**Official homepage:** none found
**Wanna say something? Leave message here:** File to be hosted:
https://github.com/rharel/node-gol-hashlife/blob/master/dist/gol.min.js

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@dloret this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by dloret** [comment]
Hi, I understand and thank you for your time. You are the one doing great work :)
This can certainly be closed.
