### ISSUE TITLE
vanilla-lazyload more dist files

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#10930]
Hello,
my library https://github.com/verlok/lazyload is currently published on cdnjs under the name `vanilla-lazyload` (same name on npm). I'm about to change the dist files from 3 to 6 (transpiled and non-transpiled, minified and non-minified, + sourcemaps).
Do I need to do anything or cdnjs will automatically manage the change?

**Comment by PeterDaveHello** [comment]
@verlok if the origin auto-update can fetch the new files with same structure, then you need to do nothing, thanks.

**Comment by PeterDaveHello** [comment]
I think we can close it.
