### ISSUE TITLE
[Request] Add Waffle Grid

### ISSUE THREAD

**Issue by arguiot** [cdnjs/cdnjs#10939]
**Library name:** Waffle Grid
**Git repository url:** https://github.com/lucasgruwez/waffle-grid
**npm package name or url** (if there is one): https://www.npmjs.com/package/waffle-grid
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://lucasgruwez.github.io/waffle-grid/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @arguiot This is for #10940, right? Thanks.
