### ISSUE TITLE
[Request] Add old versions of flowplayer

### ISSUE THREAD

**Issue by hare1039** [cdnjs/cdnjs#10944]
**Library name:** flowplayer
**Git repository url:** https://github.com/flowplayer/flowplayer
**npm package name or url** (if there is one): https://www.npmjs.com/package/flowplayer
**License (List them all if it's multiple):** GPL-3.0
**Official homepage:** https://flowplayer.org

Relate PR #10910

**Comment by MattIPv4** [comment]
We have quite a few versions of FlowPlayer available: https://cdnjs.com/libraries/flowplayer

Due to the nature of cdnjs using auto-update for libraries, we cannot go in and manually add older versions if the auto-update config fails to pick them up.
