### ISSUE TITLE
How can I update my package.info?

### ISSUE THREAD

**Issue by ron666** [cdnjs/cdnjs#10949]
I wanna make a minor update on the package.info files for the MediaElement and MediaElement Plugins repos. I tried to use the `Find File`, but I couldn't find them. What can I do to update them?

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/mediaelement/package.json
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/mediaelement-plugins/package.json

**Comment by ron666** [comment]
Thanks. I updated this to point to the organization repository now. Hope the PRs #10950 and #10951 get merged soon.

**Comment by PeterDaveHello** [comment]
@ron666 thanks for the update.
