### ISSUE TITLE
[author] How to re-trigger git auto update or something to that effect?

### ISSUE THREAD

**Issue by zytzagoo** [cdnjs/cdnjs#10953]
See comment here: https://github.com/cdnjs/cdnjs/commit/8753b90de55ce7c1daec2d052e420daa4cd0dd36#commitcomment-21556759

Or will it fix itself at some point?

**Comment by PeterDaveHello** [comment]
Bump it's version is the simplest way to fix it, we have SRI/hash on files, overwrite the file will break its integrity, so I prefer not to do it.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 @cdnjs/intern3 please help assign this kind of issues to me, thanks.

**Comment by zytzagoo** [comment]
thanks. did so.
