### ISSUE TITLE
[Request][Author] Add EqualizeCss

### ISSUE THREAD

**Issue by VladimirHumeniuk** [cdnjs/cdnjs#10954]
**Library name: EqualizeCss** 
**Git repository url: https://github.com/VladimirHumeniuk/equalizecss** 
**npm package name or url: https://www.npmjs.com/package/equalizecss** (if there is one): 
**License (List them all if it's multiple): ISC** 
**Official homepage: https://equalizecss.com/** 
**Wanna say something? Leave message here: Mobilefirst grid based on flexboxes** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@VladimirHumeniuk this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by VladimirHumeniuk** [comment]
@sufuf3 when library has more popularity i will open issue again. Thanks.

**Comment by sufuf3** [comment]
Thank you.

Close because the lib doesn't have enough popularity, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@VladimirHumeniuk if you'd like to send a pull request, I can accept it, what do you think?

**Comment by VladimirHumeniuk** [comment]
@PeterDaveHello  great! will send pull request soon, thanks.
