### ISSUE TITLE
Minify some files of ammaps

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#10958]
Library name: ammaps
url: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ammaps
Related issue: #10285 

Please help minify the files of ammaps on CDNJS, They include the followings.
1. All files under `3.13.0/maps/js`
2. All files under `3.13.0/exporting`
3. All files under `3.13.0/themes`
4. `3.13.0/ammap.css`

**Comment by PeterDaveHello** [comment]
@extend1994 please describe the files should be minified.

**Comment by extend1994** [comment]
@PeterDaveHello Sorry about not specifying them. I rewrote the comment to describe the filed needed to be minified. Thanks!

**Comment by PeterDaveHello** [comment]
@extend1994 nice, should always do so, since we all may forgot something after few days the issues created, and we should make the things need to be done also be clear.

**Comment by extend1994** [comment]
@PeterDaveHello Okay, I will :+1:

**Comment by MattIPv4** [comment]
Files appear to be minified: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ammaps/3.21.9
