### ISSUE TITLE
[author] [Request] Add btn.style

### ISSUE THREAD

**Issue by smyzin** [cdnjs/cdnjs#10960]
**Library name:** btn.style
**Git repository url:** https://github.com/smyzin/btn.style
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://btn.umount.space/
**Wanna say something? Leave message here:** 
I want to add CDN path for users who will use this css-library
=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@smyzin would you like to send a pull request to add it?

**Comment by smyzin** [comment]
@PeterDaveHello Can you explain what do you mean? Actually, I don't quite understand what are you asking for.

**Comment by PeterDaveHello** [comment]
@smyzin I mean if you can submit it by yourself :)
https://help.github.com/articles/about-pull-requests/

**Comment by sashberd** [comment]
Hi @smyzin 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
