### ISSUE TITLE
[Request] Add turretcss

### ISSUE THREAD

**Issue by scottdejonge** [cdnjs/cdnjs#10968]
**Library name:** turretcss
**Git repository url:** https://github.com/turretcss/turretcss
**npm package name or url** (if there is one): turretcss
**License (List them all if it's multiple):** MIT
**Official homepage:** http://turretcss.com/

**Comment by PeterDaveHello** [comment]
I think we have it as https://cdnjs.com/libraries/bigfishtv-turret?

**Comment by scottdejonge** [comment]
Yeah, I pushed a new version today and moved the repo to a new organisation. Should be https://github.com/turretcss/turretcss and version 4.0.0 if that's cool?

**Comment by PeterDaveHello** [comment]
@scottdejonge the new version is online already: https://cdnjs.com/libraries/bigfishtv-turret/4.0.0, I'll update its repo info.
