### ISSUE TITLE
[Request] Add vkbeautify.js

### ISSUE THREAD

**Issue by codebeautify** [cdnjs/cdnjs#10969]
**Library name:** vkbeautify.js
**Git repository url:** https://github.com/vkiryukhin/vkBeautify
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** https://github.com/vkiryukhin/vkBeautify/blob/master/LICENSE
**Official homepage:**  https://github.com/vkiryukhin/vkBeautify
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
