### ISSUE TITLE
[Request][author] Add JudgementJS

### ISSUE THREAD

**Issue by DRasiti** [cdnjs/cdnjs#10966]
**Library name: JudgementJS** 
**Github: https://github.com/DRasiti/JudgementJS** 
**NPM: https://www.npmjs.com/package/judgementjs** 
**License: MIT** 
**Official homepage: https://drasiti.github.io/JudgementJS/**

**Comment by sufuf3** [comment]
@DRasiti this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md).
But you are the author of this library, would you like to send a PR to add it?

**Comment by PeterDaveHello** [comment]
We can accept it if @DRasiti you can send us pull request, thanks.

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello
