### ISSUE TITLE
[Request][Author] Add vue-frame

### ISSUE THREAD

**Issue by juliandavidmr** [cdnjs/cdnjs#10978]
**Library name:** vue-frame.js
**Git repository url:** https://github.com/juliandavidmr/vue-frame
**npm package name or url** (if there is one): https://github.com/juliandavidmr/vue-frame
**License (List them all if it's multiple):** https://github.com/juliandavidmr/vue-frame/blob/master/LICENSE
**Official homepage:** https://github.com/juliandavidmr/vue-frame
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@juliandavidmr  would you like to send a pull request to add it?? Thanks.

**Comment by sufuf3** [comment]
@juliandavidmr this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md).
But you are the author of this library, would you like to send a PR to add it?

**Comment by sufuf3** [comment]
@juliandavidmr We can host this library if you can send us pull request, thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 Is that your mentor teach you to do?

**Comment by sufuf3** [comment]
sorry about that I learn from oldest issues.

**Comment by juliandavidmr** [comment]
@sufuf3 thanks, Later I do PR, I will wait to make a few more changes in my library npm. Thanks for the help.

**Comment by PeterDaveHello** [comment]
@sufuf3 I dont know why can you make decisions without asking or authorization from your mentor as you are an intern student in a not so good situation, one more time, I will remove your identity until we have agreement about how the intern program running.

**Comment by sufuf3** [comment]
Sorry for everything, I will keep in mind.

**Comment by PeterDaveHello** [comment]
@juliandavidmr if you'd like to send a pull request, we'll be happy to host this library, thanks.
