### ISSUE TITLE
[Author][Request] Add js-popup

### ISSUE THREAD

**Issue by exelban** [cdnjs/cdnjs#10972]
**Library name:** js-popup
**Git repository url:** https://github.com/exelban/js-popup
**npm package name or url** (if there is one): https://www.npmjs.com/package/js-popup
**License (List them all if it's multiple):** Apache License 2.0
**Official homepage:** 
**Wanna say something? Leave message here:** 

Release:
https://github.com/exelban/js-popup/releases

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@exelban would you like to send us a pull request? Thanks.

**Comment by sufuf3** [comment]
close because this library doesn't have enough popularity 
And the author closed the PR. #10975 
cc @PeterDaveHello
