### ISSUE TITLE
[Request] Update justgage version to 1.2.7

### ISSUE THREAD

**Issue by topdog69** [cdnjs/cdnjs#10974]
**Library name:** JustGage
**Git repository url:** https://github.com/toorshia/justgage
**npm package name or url** (if there is one): https://npmjs.com/package/justgage
**License (List them all if it's multiple):** https://spdx.org/licenses/MIT.html
**Official homepage:** justgage.com
**Wanna say something? Leave message here:** 
justgage 1.2.2 is currently hosted on cdnjs https://cdnjs.com/libraries/justgage. I would like to use the 1.2.7 version. I have no knowledge of github and the process to request an update baffled me. Apologies for using this method for the request. 
=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
Hey @PeterDaveHello, isn't justgage supposed to update automatically since it already has the correct `package.json` file with npm auto update enabled?

**Comment by PeterDaveHello** [comment]
@dakshshah96 sometimes the upstreams change the file/directory structure, so we need to update the auto-update config.
