### ISSUE TITLE
[Request] Add VivaGraphJS

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#10983]
**Library name:** VivaGraphJS
**Git repository url:** https://github.com/anvaka/VivaGraphJS
**npm package name or url** (if there is one): https://www.npmjs.com/package/vivagraphjs
**License (List them all if it's multiple):** BSD-3-Clause
**Official homepage:** 
**Wanna say something? Leave message here:**

**Comment by mercyg** [comment]
@sufuf3 I have created pull request please review it!
