### ISSUE TITLE
[Request] jQuery Nearest Element plugin

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#10989]
**Library name:** jQuery Nearest Element plugin
**Git repository url:** https://github.com/gilmoreorless/jquery-nearest
**npm package name or url** (if there is one): npm install jquery-nearest
**License (List them all if it's multiple):** MIT
**Official homepage:** https://gilmoreorless.github.io/jquery-nearest/
**Wanna say something? Leave message here:** 

This is very cool Jquery plugin. It has not 100 starts, but it is almost there. However, for you review

**Comment by sashberd** [comment]
@PeterDaveHello 
You wrote me that I can pick the issues and self-assign them 
I do not have such option
Could you check if this is a problem or I am making something wrong

**Comment by PeterDaveHello** [comment]
@sashberd Not a problem at all, just leave a message/comment at the isssue, and send your pull request :)
