### ISSUE TITLE
[Request][Author] Add slim.js

### ISSUE THREAD

**Issue by eavichay** [cdnjs/cdnjs#10985]
**Library name:**  slim.js
**Git repository url:** https://github.com/eavichay/slim.js
**npm package name or url** (if there is one): slim-js
**License (List them all if it's multiple):** MIT
**Official homepage:** slimjs.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@eavichay would you like to send a pull request to add it?? Thanks.

**Comment by eavichay** [comment]
will try. thanks.

**Comment by eavichay** [comment]
Hi,
I can’t clone the repo to my computer in order to create a pull request: the project is too big and git crashes.
Could you assist with that?

Best regards,
Avichay

**Comment by PeterDaveHello** [comment]
@eavichay I thin you can directly make commit on GitHub gui? No need to clone it:)

**Comment by PeterDaveHello** [comment]
@eavichay we also support to add library via single package.json:
doc: https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson
example: https://github.com/cdnjs/cdnjs/pull/10810

**Comment by eavichay** [comment]
just did, not sure I did it right.

**Comment by PeterDaveHello** [comment]
@eavichay I saw #10997 and replied there, please take a look, thanks.

**Comment by eavichay** [comment]
fixed, passed ci

**Comment by PeterDaveHello** [comment]
@eavichay nice!

**Comment by eavichay** [comment]
I could not manage the commits by myself, please provide help.

**Comment by PeterDaveHello** [comment]
@eavichay sure, please give us some time, we'll come back soon!
