### ISSUE TITLE
[Request] Add vue-frame.js

### ISSUE THREAD

**Issue by juliandavidmr** [cdnjs/cdnjs#10986]
**Library name:** vue-frame.js
**Git repository url:** https://github.com/juliandavidmr/vue-frame
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** https://github.com/juliandavidmr/vue-frame/blob/master/LICENSE
**Official homepage:** https://github.com/juliandavidmr/vue-frame
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #10978 
Move to #10978

**Comment by PeterDaveHello** [comment]
Move to #10978
