### ISSUE TITLE
How to become reviewer or collabarator?

### ISSUE THREAD

**Issue by dalisoft** [cdnjs/cdnjs#10999]
Hi @PeterDaveHello 

Can i become like you collarabarator or reviewer for merging PR or issue checker?

Thanks

**Comment by PeterDaveHello** [comment]
Hi @dalisoft,

Thanks for being interested in join us! I'll suggest you start to make some pull requests first, so that you can be familiar with how do we do as routine, and if we found that you have good enough quality on it, we'll be happy to invite you become a reviewer!

Thanks!

**Comment by dalisoft** [comment]
Thanks. I am already made 2 PR, as soon do PR for other projects. My question is answered, so i am close issue

**Comment by PeterDaveHello** [comment]
@dalisoft thanks, I saw your pull requests, we'll review it! Keep coming new PRs!

**Comment by PeterDaveHello** [comment]
@dalisoft btw, maybe you'll be interested in the info in #10662
