### ISSUE TITLE
[Request] Add semanticUiAlert

### ISSUE THREAD

**Issue by lefuturiste** [cdnjs/cdnjs#11003]
**Library name:** semanticUiAlert
**Git repository url:** https://github.com/diw112/semanticUiAlert
**Official homepage:** https://diw112.github.io/semanticUiAlert/

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Hi @lefuturiste!
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello
