### ISSUE TITLE
[Request] Add slick lightbox

### ISSUE THREAD

**Issue by ftcmnc** [cdnjs/cdnjs#11004]
**Library name:** slick lightbox

**Git repository url:** https://github.com/mreq/slick-lightbox

**License (List them all if it's multiple):** MIT License https://github.com/mreq/slick-lightbox/blob/master/LICENSE

**Official homepage:** http://mreq.github.io/slick-lightbox/

**Wanna say something? Leave message here:**  Popular plugin for the already supported package slick-carousel

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
Hi @ftcmnc!
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by ftcmnc** [comment]
Hi @clairetsai818 the lib is 97 stars already, but I will check in a couple of weeks and let you know when they reach 100

**Comment by PeterDaveHello** [comment]
@ftcmnc I think it's good to go with this lib right now :) 
cc @clairetsai818

**Comment by ZippoRays** [comment]
It reached a 100, I just added the final one, good to go I guess

**Comment by PeterDaveHello** [comment]
We'll take care of it 👍

**Comment by PeterDaveHello** [comment]
@qwe19272375 any updates here please?
