### ISSUE TITLE
bowser updates missing

### ISSUE THREAD

**Issue by tim-nz** [cdnjs/cdnjs#11029]
The updates to bowser are [missing on cdnjs](https://cdnjs.com/libraries/bowser). 13 new versions have been released since cdnjs's latest version (1.0.0). The most recent stable version on the [bowser github release page](https://github.com/ded/bowser/releases/) is 1.6.0. Obviously the git autoupdate isn't working as it should, but I have no idea why (because I have no idea how cdnjs works).

I don't know how to update it myself (or even if I can). So if somone could either update it with the new versions or tell me how to do it myself, I'd appreciate it.

**Comment by PeterDaveHello** [comment]
https://github.com/ded/bowser/tree/1.6.1#110-breaking-changes

**Comment by PeterDaveHello** [comment]
Okay I updated it to the latest now.

**Comment by tim-nz** [comment]
Thanks
