### ISSUE TITLE
[Author] mini.css library not updating

### ISSUE THREAD

**Issue by Chalarangelo** [cdnjs/cdnjs#11024]
Hi, I am the author of [mini.css](https://cdnjs.com/libraries/mini.css). I updated my library about a month ago to **v2.1.0** [[link](https://github.com/Chalarangelo/mini.css/releases/tag/v2.1.0)], however your CDN did not update to the latest version (still shows **v2.0.2**). 

I read the guidelines for auto-updating and, as far as I understand it, my setup is fine, provided that I use `npm` for my package, but the library did not update automatically, like it was supposed to. I would like to know how to fix this (if this is a problem on my end) and if this has a chance of happening again with future releases, as I would like to rely on cdnjs as the main means for deploying my library. 

On a side note, if I add more files under my :file_folder: [dist](https://github.com/Chalarangelo/mini.css/tree/master/dist), will they auto-update upon release or do I have to open an issue/do something else?

Thanks in advance!

**Comment by PeterDaveHello** [comment]
Looks like the directory structure changed.

**Comment by PeterDaveHello** [comment]
The new version will be deployed soon, website will be updated about after 10 mins, thanks.
