### ISSUE TITLE
[Request] Add algebra.js

### ISSUE THREAD

**Issue by Charles-Catta** [cdnjs/cdnjs#11028]
**Library name:** algebra.js
**Git repository url:** https://github.com/nicolewhite/algebra.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/algebra.js
**License (List them all if it's multiple):** MIT License
**Official homepage:** http://algebra.js.org/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicate with #7971

**Comment by PeterDaveHello** [comment]
Let's move to #7971
