### ISSUE TITLE
d3.js v4 modules and CDNJS

### ISSUE THREAD

**Issue by kyrylo** [cdnjs/cdnjs#11025]
Currently, we use [the entire d3 v4](https://cdnjs.com/libraries/d3). We don't use a lot of its features, so I would like to use only some of its modules instead, *and* use your CDN (big thanks for it!).

I would like to send a PR, which adds d3.js v4 modules to CDNJS. Before doing that, I would like to know why nobody has ever done that before. My gut feeling tells me there's some other way of doing what I want, so that's why I decided to create this issue before doing the actual work. 

So, the question is, does it make sense to add the modules, should I proceed with that? I apologise if this question was asked before.

**Comment by PeterDaveHello** [comment]
Considering the cache hit rate and cache sharing, maintenance complexity, it might be better to just load it whole in the same time, on the other hand, I'm not sure how would you introduce its modules here since they are not inside its `build/` directory in its npm package, and the file name / directory may change frequently, any ideas?

**Comment by kyrylo** [comment]
> Considering the cache hit rate and cache sharing, maintenance complexity, it might be better to just load it whole in the same time

It's hard for me to state what would be better without benchmarks, but I don't say you're wrong. The decision of modularity was made by the author of d3 and I would expect CDNJS to reflect that, no matter what penalties users could possibly be getting.

> I'm not sure how would you introduce its modules here since they are not inside its build/ directory in its npm package

Are you sure the modules are not inside `build`? Let's take a look at [`d3-array`](https://github.com/d3/d3-array/blob/bc59792b88c53e9db4308b0eec3b5f4c25e61d5f/package.json#L29-L34):

```sh
% npm install d3-array
% ls node_modules/d3-array/build/
d3-array.js      d3-array.min.js
```

I can see the `build` directory there.

---

unkpg.com already supports d3 v4 modules. For example:
https://unpkg.com/d3-array/build/d3-array.min.js

**Comment by PeterDaveHello** [comment]
@kyrylo I mean d3 itself, if you mean the indivudual modules, we may need a list.

**Comment by kyrylo** [comment]
I did mean individual modules. CDNJS already provides d3 v4 itself (as a whole big library):
https://cdnjs.cloudflare.com/ajax/libs/d3/4.7.3/d3.min.js

<details> 
  <summary>The list of d3.js v4 modules (taken from https://github.com/d3/d3/blob/master/API.md)
</summary>

* https://www.npmjs.com/package/d3-array
* https://www.npmjs.com/package/d3-axis
* https://www.npmjs.com/package/d3-brush
* https://www.npmjs.com/package/d3-chord
* https://www.npmjs.com/package/d3-collection
* https://www.npmjs.com/package/d3-color
* https://www.npmjs.com/package/d3-dispatch
* https://www.npmjs.com/package/d3-drag
* https://www.npmjs.com/package/d3-dsv
* https://www.npmjs.com/package/d3-ease
* https://www.npmjs.com/package/d3-force
* https://www.npmjs.com/package/d3-format
* https://www.npmjs.com/package/d3-geo
* https://www.npmjs.com/package/d3-hierarchy
* https://www.npmjs.com/package/d3-interpolate
* https://www.npmjs.com/package/d3-path
* https://www.npmjs.com/package/d3-polygon
* https://www.npmjs.com/package/d3-quadtree
* https://www.npmjs.com/package/d3-queue
* https://www.npmjs.com/package/d3-random
* https://www.npmjs.com/package/d3-request
* https://www.npmjs.com/package/d3-scale
* https://www.npmjs.com/package/d3-selection
* https://www.npmjs.com/package/d3-shape
* https://www.npmjs.com/package/d3-time-format
* https://www.npmjs.com/package/d3-time
* https://www.npmjs.com/package/d3-timer
* https://www.npmjs.com/package/d3-transition
* https://www.npmjs.com/package/d3-voronoi
* https://www.npmjs.com/package/d3-zoom
</details>

Do you have any other concerns?

**Comment by PeterDaveHello** [comment]
@kyrylo it's fine to add them all.

**Comment by kyrylo** [comment]
Should I add them all in one PR, or should they be added in separate PRs?

**Comment by PeterDaveHello** [comment]
@kyrylo in this case, both fine, thanks!

**Comment by PeterDaveHello** [comment]
#11093 merged, libraries imported!
