### ISSUE TITLE
[Request] Add colorPicker

### ISSUE THREAD

**Issue by Multi-Thinker** [cdnjs/cdnjs#11039]
**Library name:** colorPicker
**http://www.eyecon.ro/colorpicker/**

**Comment by maruilian11** [comment]
Hi @Multi-Thinker, dose this lib has git repo or npm package? then we can provide the auto-update service on it. Thanks!

**Comment by Multi-Thinker** [comment]
Hi @maruilian11 I'm sorry this lib doesn't have official git repo or may be i can't find it, can you add this library from the link i provided they allow to download and use?

**Comment by maruilian11** [comment]
Yes, but it may take some time since there are many libs waiting for being added.
If you want to add it quickly, you can try to send a PR. We will help you if you need 👍

**Comment by Multi-Thinker** [comment]
Thanks, I'll send PR request.

**Comment by PeterDaveHello** [comment]
Let's close this issue in PR's commit message 😄

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
