### ISSUE TITLE
[Request] Add Ripple.js

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11046]
**Library name:** Ripple.js
**Git repository url:** https://github.com/jakiestfu/Ripple.js
**License:** MIT
**Official homepage:** https://jakiestfu.github.io/Ripple.js/demo/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by ajay2507** [comment]
@PeterDaveHello  Hi peter, Can I take up this change. I am a beginner so I would like to join.

**Comment by PeterDaveHello** [comment]
@ajay2507 feel free to ask for help if you need!

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please help @ajay2507 when he needs it.

**Comment by ajay2507** [comment]
@PeterDaveHello sure.. Thanks for your response.

**Comment by PeterDaveHello** [comment]
@ajay2507 Nice, don't forget our CONTRIBUTING.md doc please, thanks.

**Comment by ajay2507** [comment]
@PeterDaveHello sure, I will follow the contributing guidelines.

**Comment by ajay2507** [comment]
@PeterDaveHello  I have one doubt might be a silly question, orign should be this one 
git remote add origin git://github.com/cdnjs/cdnjs.git or one which i forked from cdnjs( git://github.com/ajay2507/cdnjs.git ).
As per my understanding Origin be my forked repository(git://github.com/ajay2507/cdnjs.git) right?

**Comment by ajay2507** [comment]
@PeterDaveHello  I have created the pull request, please let me know if anythings goes wrong.
Thanks for your help.

**Comment by PeterDaveHello** [comment]
@ajay2507 Thanks

**Comment by ajay2507** [comment]
@hare1039 @clairetsai818 Build is failing because of 2 space indent. I tried fixing, can you help me out regarding this.

**Comment by PeterDaveHello** [comment]
Sure
