### ISSUE TITLE
[Request] Add bootstrap-timepicker v0.2.3

### ISSUE THREAD

**Issue by Code-ReaQtor** [cdnjs/cdnjs#11043]
Hi,

This is related to issue #8155

[AdminLTE](https://github.com/almasaeed2010/AdminLTE/blob/master/plugins/timepicker/bootstrap-timepicker.min.js) and a few libraries are using bootstrap-timepicker v0.2.3. However, the oldest available version in cdnjs is v0.2.7 which does not work with AdminLTE.

Thanks.

**Comment by PeterDaveHello** [comment]
@Code-ReaQtor thanks for your report, we'll work on this!
