### ISSUE TITLE
Drop empty files from npm auto-update

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11049]
Sometimes there are empty files from upstream, for example, inspire-tree v1.12.3, those files should be dropped by auto-updater

**Comment by PeterDaveHello** [comment]
@extend1994 this would be easy enough for you to get started with code level contribution.

**Comment by extend1994** [comment]
@PeterDaveHello Okay, I will try it sonn. Thanks for the assignment!
