### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by tscanlin** [cdnjs/cdnjs#11055]
my project is setup for npm auto update (according to: https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md). But it appears to be stuck at an old version. Can you tell me why auto update isn't working?

https://cdnjs.com/libraries/tocbot

**Comment by PeterDaveHello** [comment]
@sufuf3 this should be high priority ...

**Comment by PeterDaveHello** [comment]
@tscanlin looks like you removed the source of auto-update - `dist` folder on npm since v2.2.0?

**Comment by tscanlin** [comment]
It looks like its still there:
https://github.com/tscanlin/tocbot/tree/master/dist

**Comment by PeterDaveHello** [comment]
@tscanlin I mean **npm**

**Comment by tscanlin** [comment]
This is now fixed:
https://cdnjs.com/libraries/tocbot
