### ISSUE TITLE
[Request] Update lunr.js v2.0.1

### ISSUE THREAD

**Issue by VonFry** [cdnjs/cdnjs#11050]
Library name: lunr.js
Git repository url: https://github.com/olivernn/lunr.js
npm package name or url (if there is one):
License (List them all if it's multiple):
Official homepage: http://lunrjs.com
Wanna say something? Leave message here:

cdnjs version: v2.0.0
lastest version: v2.0.1
It fixed a bug...

**Comment by PeterDaveHello** [comment]
@VonFry > It fixed a bug... ?

I'm not sure what do you mean here, it looks like the upstream removed the minified file in v2.0.1, I'll add it manually.
