### ISSUE TITLE
[Request] Add isomorphic-fetch

### ISSUE THREAD

**Issue by nathanlampe** [cdnjs/cdnjs#11054]
**Library name:** isomorphic-fetch
**Git repository url:** https://github.com/matthew-andrews/isomorphic-fetch
**npm package name or url** (if there is one): isomorphic-fetch
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
Working on this one 👍

**Comment by PeterDaveHello** [comment]
I just took a look at `fetch-npm-browserify.js`, I don't think it'll work, so actually #11061 didn't add it with success, so reopen this one.

**Comment by PeterDaveHello** [comment]
I think we should confirm that if it works with browser. @dakshshah96 wanna try it?

**Comment by dakshshah96** [comment]
@PeterDaveHello Sure, I'll open an issue with the author and collaborate.

**Comment by dakshshah96** [comment]
@PeterDaveHello We should probably remove the Pull Request that was merged and close this issue? Author says build files won't be available in the repository.

**Comment by PeterDaveHello** [comment]
@dakshshah96 It is still not available on the cdn, maybe try to manually add the release files and close it.
