### ISSUE TITLE
[Request] Add nipplejs

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11056]
**Library name:** nipplejs
**Git repository url:** https://github.com/yoannmoinet/nipplejs
**npm package name or url** (if there is one): nipplejs 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://yoannmoinet.github.io/nipplejs
**Wanna say something? Leave message here:**

**Comment by ajay2507** [comment]
can I make this change?

**Comment by PeterDaveHello** [comment]
@ajay2507 feel free to take it!

**Comment by ajay2507** [comment]
@PeterBot  okay thanks.

**Comment by ajay2507** [comment]
@PeterDaveHello  Submitted pull request

**Comment by ajay2507** [comment]
@PeterDaveHello  Included review comments and created pull request
