### ISSUE TITLE
[Request] Add qrcodejs

### ISSUE THREAD

**Issue by ryh** [cdnjs/cdnjs#11069]
**Library name:** qrcodejs
**Git repository url:** https://github.com/davidshimjs/qrcodejs
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/davidshimjs/qrcodejs
**Wanna say something? Leave message here:** 
This QRCode.js has no dependencies.

**Comment by ryh** [comment]
sorry,  looks like duplicate  of #5164 #9878

**Comment by PeterDaveHello** [comment]
Move to #9878, thanks @ryh

**Comment by ryh** [comment]
Looks @davidshimjs  did update his repo at all, any forker to maintain?
