### ISSUE TITLE
[Request] Add yii2 2.0.11.2

### ISSUE THREAD

**Issue by sheillendra** [cdnjs/cdnjs#11086]
**Library name:** yii2 2.0.11.2
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@sheillendra do you mean this library? https://github.com/yiisoft/yii2
It's a php framework. Do you know how to use it in front-end?

**Comment by sheillendra** [comment]
Yes it'a a php framework, in production we can access to those asset. 
In every version, its file can be found here [https://github.com/yiisoft/yii2/tree/2.0.11.2/framework/assets](https://github.com/yiisoft/yii2/tree/2.0.11.2/framework/assets)

**Comment by sufuf3** [comment]
@sheillendra OK! I get it. Thank you very much.

**Comment by dakshshah96** [comment]
@PeterDaveHello @sufuf3 Does CDNJS host this kind of stuff too? What we'll basically be hosting here are the `assets` for the [yii2 PHP framework](https://github.com/yiisoft/yii2).

**Comment by MattIPv4** [comment]
This appears to be a PHP framework, which doesn't really fit with cdnjs. Closing.
