### ISSUE TITLE
[Request] Add admin-lte 2.3.12

### ISSUE THREAD

**Issue by sheillendra** [cdnjs/cdnjs#11087]
**Library name:** admin-lte 2.3.12
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@sheillendra we already have v.2.3.11, and this version is newest in GitHub and npm.

Could you tell me where do you find the v2.3.12?
Thank you.

**Comment by sheillendra** [comment]
Sorry it turned out 2.3.12 version was not yet stable

**Comment by sufuf3** [comment]
OK! we use auto-update to get the latest release version.
So, when it release v2.3.12, cdnjs will host it by auto-update mechanism.

Maybe this issue could close, what do you think?

**Comment by sheillendra** [comment]
OK, thank you very much.
