### ISSUE TITLE
[Request] Add findAndReplaceDOMText

### ISSUE THREAD

**Issue by alewolf** [cdnjs/cdnjs#11099]
**Library name:** findAndReplaceDOMText
**Git repository url: https://github.com/padolsey/findAndReplaceDOMText** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage: https://github.com/padolsey/findAndReplaceDOMText** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@qwe19272375 please create an issue to try to add the old versions manually by tracking its git commits.
