### ISSUE TITLE
[Request] Add chartjs-plugin-zoom

### ISSUE THREAD

**Issue by Nahiduzzaman** [cdnjs/cdnjs#11090]
**Library name:** chartjs-plugin-zoom
**Git repository url:* https://github.com/chartjs/chartjs-plugin-zoom
**npm package name or url** (if there is one): https://www.npmjs.com/package/chartjs-plugin-zoom
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicate with #9445
close and move to #9445
cc @PeterDaveHello
