### ISSUE TITLE
AngularJS 1.6.x builds are corrupt

### ISSUE THREAD

**Issue by csvan** [cdnjs/cdnjs#11100]
I cannot pinpoint what the exact issue is, but (at least) `ng-style` breaks when using the current cdnjs builds for angular 1.6.x. What happens is that some elements with ng-style simply do not get the `style` attribute modified during runtime.

I have confirmed this by trying angular 1.6.4 from both cdnjs, https://developers.google.com/speed/libraries/#angularjs, and a local version installed via NPM. It is only reproducible with the cdnjs one.

**Comment by sufuf3** [comment]
@PeterDaveHello  Could you take a look about this? I can't figure out how to solve this problem. Thank you.

**Comment by PeterDaveHello** [comment]
Hi @csvan,

Sorry for my very late response, I think I missed this issue by accident.

I've confirmed that all the files are the same as https://code.angularjs.org/1.6.4/angular-1.6.4.zip, so this issue may not be directly related with us, let me know if I missed anything, thanks!

**Comment by MattIPv4** [comment]
No progress, closing.
