### ISSUE TITLE
[Request] Add Flux-Slider

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11101]
**Library name:** Flux-Slider
**Git repository url:** https://github.com/joelambert/Flux-Slider
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.joelambert.co.uk/flux/
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
