### ISSUE TITLE
[Request] Add dagre

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11102]
**Library name:** dagre
**Git repository url:** https://github.com/cpettitt/dagre
**npm package name or url** (if there is one): https://www.npmjs.com/package/dagre
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

**Comment by dakshshah96** [comment]
@PeterDaveHello This project is not being actively developed or maintained according to their [GitHub repo](https://github.com/cpettitt/dagre). Should we still add this to CDNJS?

**Comment by PeterDaveHello** [comment]
Looks like there are many users still using it, so why not?
