### ISSUE TITLE
[Request] Add path-data-polyfill.js

### ISSUE THREAD

**Issue by Azgaar** [cdnjs/cdnjs#11119]
**Library name:** path-data-polyfill.js
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
Hi @Azgaar,

Thanks for your suggestion. I found https://github.com/jarek-foksa/path-data-polyfill.js. Is this what you want to request?

**Comment by qwe19272375** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
