### ISSUE TITLE
Problem with jquery-circle-progress

### ISSUE THREAD

**Issue by kottenator** [cdnjs/cdnjs#11120]
Hi!

I'm the author of [jquery-circle-progress](https://github.com/kottenator/jquery-circle-progress) library.

It's [presented on CDNJS](https://cdnjs.com/libraries/jquery-circle-progress) (though I've not done anything for this to happen).

And there's [a problem with CDNJS](https://github.com/kottenator/jquery-circle-progress/issues/144) now. People who use my library version 1.2.1 from CDNJS (min or full version) - have problems with it, it doesn't work.

I've investigated the problem and figured out the following.

In the original code there's:

```js
(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD - register as an anonymous module
    define(['jquery'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node/CommonJS
    var $ = require('jquery');
    factory($);
    module.exports = $;
  } else {
    // Browser globals
    factory(jQuery);
  }
})(...);
```

But on CDNJS it's modified to:

```js
(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD - register as an anonymous module
    define(['jquery'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // Node/CommonJS
    var jQuery = require('jquery');
    factory(jQuery);
    module.exports = jQuery;
  } else {
    // Browser globals
    factory(jQuery);
  }
})(...);
```

I've intentionally used `var $ = ...` to not override global `jQuery` variable. But in your version, it's `var jQuery = ...` which overrides the global `jQuery` and the library isn't loaded / initialized correctly.

Could you, please, update the 1.2.1 version on CDNJS with the exact original code? (I have both min / max versions in the Git repo).

With regards,
Rost.

**Comment by PeterDaveHello** [comment]
Hi @kottenator,

Thanks for the report, we will not modify the content of the libraries in most of the cases, I'll take a look at this issue, but as SRI(https://www.w3.org/TR/SRI, https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) is already enabled, it's better not to modify the already hosted versions but bump and host a new version.

I'll let you know what's going on here.

**Comment by kottenator** [comment]
Thanks, @PeterDaveHello!

BTW, could you, please, provide me a link to explanation how does CDNJS add / update libraries?

**Comment by PeterDaveHello** [comment]
This is the whole history of this library on CDNJS repo:

* 925aac8e062 Drop .gitkeep Peter Dave Hello 2 months ago
* 0971b44e9ab Add jquery-circle-progress v1.2.1 PeterBot 4 months ago
* 0de8c5fbd30 Fix the package format. Ionică Bizău 6 months ago
* 8a20b3f3ee2 add jquery-circle-progress v1.2.0 PeterBot 8 months ago
* 3018648be42 add jquery-circle-progress v1.1.4 PeterBot 8 months ago
* d1abc00d4a3 add .gitkeep for libs do not have it yet PeterDaveHello 1 year, 4 months ago
* 7ddd672fbcc add jquery-circle-progress with git auto-update Peter Dave Hello 1 year, 8 months ago

Looks like versions after v1.1.4 were added automatically from the git repository, and it came from the earlier commit you made in v1.2.1 tag:

commit 17c4681506b3d6aed46fd65beacc998d84c19422
Author: Rostyslav Bryzgunov <kottenator@gmail.com>
Date:   Sun Jan 8 19:39:56 2017 -0500

    Fix UMD CommonJS export


it's before tag 1.2.1:

commit 3d04b48d2f40057ac5fc35271cbdb7d6ddf538db
Author: Rostyslav Bryzgunov <kottenator@gmail.com>
Date:   Sun Jan 8 20:51:08 2017 -0500

    Update RawGit URL (it was cached)

So ... it's actually not a CDNJS problem

**Comment by PeterDaveHello** [comment]
About auto-update, here is the doc:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

Here is its config:
https://github.com/cdnjs/cdnjs/blob/0971b44e9ab8e3060a9096373792b1708041a813/ajax/libs/jquery-circle-progress/package.json#L17-L28

We fetch it from git tag, use the files under `dist`.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern @cdnjs/intern2 @cdnjs/intern3 try to learn something from this case.

**Comment by kottenator** [comment]
@PeterDaveHello - yes, I recall now, it was my bug that I've fixed. And probably I've moved `v1.2.1` tag _forward_ because I've not released a version to NPM yet, so it was only a Git tag.

And probably, CDNJS has fetched _an older_ `v1.2.1` tag just before I've shifted it.

So what should I do now? NPM / Bower version 1.2.1 points to the current `v1.2.1` tag commit, but not CDNJS.

**Comment by PeterDaveHello** [comment]
So we don't have a problem here, just see if it's fine for you to bump the version if you have some updates after v1.2.1?

**Comment by kottenator** [comment]
If it's the only way to fix the problem - then sure, I'll have to release a new version.

But maybe it's reasonable to update 1.2.1 version on CDNJS too? Because e.g. `bower install jquery-circle-progress@1.2.1` will fetch the _correct_ tagged version, when CDNJS will return an _obsolete_ one.

**Comment by PeterDaveHello** [comment]
@kottenator as I say about SRI, you should understand directly updat e hosted version will cause new problem, I'll think about it, anyway, it's better to have a new version.

**Comment by kottenator** [comment]
@PeterDaveHello - thank you so much!

I'll avoid pushing _unstable_ tags and moving them _afterwards_ in the future! ;)

**Comment by kottenator** [comment]
Could you, please, tell (at least approximately) - when will the re-added version appear on the CDNJS?

**Comment by PeterDaveHello** [comment]
@kottenator we don't expect files change normally, the TTL on the CDN is very very long, and it's directly controlled by Cloudflare, so please, as I said before, if you need a fast and correct method, please bump the version.

**Comment by kottenator** [comment]
OK, clear. Thanks anyway! I understand that it's _partially_ my fault ;)

**Comment by PeterDaveHello** [comment]
@kottenator no worries
