### ISSUE TITLE
Migrate to sha384/512 on SRI hash calculation

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11123]
Issues:
1. We'll need a powerful and individual platform to focus on re-calcuating all the hashes over all the 950k js & css files?
2. Should the origin sha256 hashes be preserved? Is the answer is yes, how do we deal with it? (How to display on the UI? How to save both sha256 and sha384 hashes?)
3. How urgent we **need** it?
4. How's the impact on performance on both hash calculation and website hosting? Especially the calculation time and memory consumption part.

**Comment by MattIPv4** [comment]
Bringing @drewfreyling's comment from #13384:

I'm in favour of just offering up the SHA-512 values since it is:

 - Less bytes in the browser
 - All browsers (currently) must support 256, 384 and 512 (https://w3c.github.io/webappsec-subresource-integrity/#hash-functions)

If at some point we get fragmented browser support than I think providing multiple hashes makes sense.

**Comment by myshov** [comment]
@PeterDaveHello @MattIPv4 
Hello guys
I suggest to prioritize this issue because SHA-256 and SHA-512 are susceptible to length extension attacks. I suggest to use SHA-384 because it has no this flaw https://blog.skullsecurity.org/2012/everything-you-need-to-know-about-hash-length-extension-attacks

**Comment by MattIPv4** [comment]
cc @zackbloom @xtuc

**Comment by MattIPv4** [comment]
We should keep this open as we are still looking at implementing this.

**Comment by PeterDaveHello** [comment]
Feel free to open a new issue for it(or maybe just use the opened pull request for discussion), as I was removed from the organization without any discussion and respect, just like some other members(I know it's not by you and you're not the one who's in charge for that), I'm now closing ancient issues I'm not working on so that I don't need to receive unnecessary notifications, thanks.

**Comment by ExE-Boss** [comment]
Did you know that you can simply unsubscribe from issues you no longer wish to receive notifications for?

<table><td><img src="https://user-images.githubusercontent.com/3889017/75113480-a55d1480-564e-11ea-96c0-b8c07afa6b7e.png"/></table>

It’s what that button in the sidebar is there for.

**Comment by MattIPv4** [comment]
Noting this down: the current SRI generation happens in https://github.com/cdnjs/tools/blob/master/packages/packages.go#L86 & https://github.com/cdnjs/tools/blob/master/openssl/sri.go

**Comment by klausenbusk** [comment]
I have opened a PR: https://github.com/cdnjs/tools/pull/46

**Comment by xtuc** [comment]
Thanks for your PR @klausenbusk! It already lgtm but I want to make sure which SHA-384/512 we should be using
