### ISSUE TITLE
[Request] Add React VR

### ISSUE THREAD

**Issue by dakshshah96** [cdnjs/cdnjs#11128]
**Library name:** React VR
**Git repository url:** https://github.com/facebook/react-vr
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-vr
**License (List them all if it's multiple):** BSD-3-Clause
**Official homepage:** https://facebook.github.io/react-vr/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Close the issue because the main maintainer said 
> React VR isn't the type of library that can just be imported with a <script> tag. It can only be used as part of a larger compiled application, so it doesn't make sense to upload to a service like CDNJS.

Ref: https://github.com/facebook/react-vr/issues/286#issuecomment-317197835
