### ISSUE TITLE
[author] Shouldn't file-uploader be fine-uploader?

### ISSUE THREAD

**Issue by rnicholus** [cdnjs/cdnjs#11124]
...or at least it seems there should be an alias. Is this possible?

I'm the maintainer of the project. https://cdnjs.com/libraries/file-uploader

**Comment by qwe19272375** [comment]
@PeterDaveHello Could you take a look at this? Not sure how to fix it. Thank you.

**Comment by PeterDaveHello** [comment]
We don't have that feature yet. I'll add an alias for its cdn first, further discuss can be moved to #4627

**Comment by MattIPv4** [comment]
@PeterDaveHello Any further progress with regards to this, should it be labelled as server config?

**Comment by xtuc** [comment]
No progress, let's close it for now. Feel free to comment if needed
