### ISSUE TITLE
[Request] Add jquery-sakura.js

### ISSUE THREAD

**Issue by matirasa** [cdnjs/cdnjs#11148]
**Library name:** jquery-sakura.js
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @matirasa,

Thanks for your suggestion, however, you only give us the name of the library, is there any detail about its repository or npm registry? Thanks a lot!

**Comment by sufuf3** [comment]
@matirasa Do you mean you want CDNJS host this library --> https://github.com/timoschaefer/jQuery-Sakura ?

**Comment by PeterDaveHello** [comment]
Close due to no response.
