### ISSUE TITLE
[Request] Add forge

### ISSUE THREAD

**Issue by RedHatter** [cdnjs/cdnjs#11152]
**Library name:** forge
**Git repository url:** https://github.com/digitalbazaar/forge
**npm package name or url** (if there is one): https://nodei.co/npm/node-forge/
**License (List them all if it's multiple):** GPLv2

**Comment by sufuf3** [comment]
duplicate with #6190

**Comment by sufuf3** [comment]
duplicate with #6190, cc @PeterDaveHello
