### ISSUE TITLE
[Request] Add angular-mocks

### ISSUE THREAD

**Issue by emanuelmaha** [cdnjs/cdnjs#11160]
**Library name:** angular-mocks
**Git repository url:** https://github.com/angular/bower-angular-mocks 
**npm package name or url** (if there is one): https://www.npmjs.com/package/angular-mocks
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@emanuelmaha do you mean this library ? --> 
https://github.com/angular/bower-angular-mocks 
https://www.npmjs.com/package/angular-mocks

**Comment by emanuelmaha** [comment]
@sufuf3 Yes, sorry for late response.

**Comment by sufuf3** [comment]
@emanuelmaha It's fine. Thank you for your response.

Note:
npm:
17,219 downloads in the last day
89,236 downloads in the last week
395,082 downloads in the last month
