### ISSUE TITLE
twbs-pagination not synced to the correct version

### ISSUE THREAD

**Issue by WingGithub** [cdnjs/cdnjs#11167]
I think PeterBot failed to get the correct version of twbs-pagination and the minimized version is also out of sync with the version it did get.

**Comment by sufuf3** [comment]
@PeterDaveHello I used md5sum and found CDNJS is different from origin library.

v1.4.1 in CDNJS result as the followings:
```
94afd2412bb77f625d51d65adf9468df  jquery.twbsPagination.js
e99e973079cbf1d458385dd33a065310  jquery.twbsPagination.min.js
```
the origin v1.4.1 of repo as the followings:
```
11a6545a3aaf117e262d5d496ac0b59d  jquery.twbsPagination.js
5b89d9957194b8be58b717120ae5d044  jquery.twbsPagination.min.js
```

Could you please take a look about this? I can't figure out how to solve this problem. Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 auto-update config checked? as a member of @cdnjs/intern3, this is not enough

**Comment by sufuf3** [comment]
I run auto-update and get the file as same with upstream.
```
11a6545a3aaf117e262d5d496ac0b59d  jquery.twbsPagination.js
5b89d9957194b8be58b717120ae5d044  jquery.twbsPagination.min.js
```

but v1.4.1 in CDNJS is different from origin repo, also different from git auto-update get.
```
94afd2412bb77f625d51d65adf9468df  jquery.twbsPagination.js
e99e973079cbf1d458385dd33a065310  jquery.twbsPagination.min.js
```

**Comment by PeterDaveHello** [comment]
Looks like the content on CDNJS belongs https://github.com/esimakin/twbs-pagination/commit/f5c108db354a77c652e03fa95dbb1c3733e51c5b on Sep 28 14:57:42 2016, and correct one https://github.com/esimakin/twbs-pagination/commit/948aeeb85dcd47c47c240e3207ead2e163575fd8  came at Sep 28 18:26:41 2016.

I think there may be a big chance that its author just tagged v1.4.1 without correct content, and then fixed it immediately, however the wrong content already been added on CDNJS. As SRI was enabled for a long time, we can't directly update the content until the next release. As I think it's a mistake from upstream, I'll respectfully suggest you to open an issue to https://github.com/esimakin/twbs-pagination/ and see how can we help, thanks!

**Comment by WingGithub** [comment]
Actually I think the release tag 1.4.1 is pointing to commit 021d98dbb947479982aa9ec162f7a021f99b55b8. Looks like there was something like a 3 way branch around Sep 28 and the commit that got picked up by the bot wasn't the one that had the final release tag. If the bot picking up the commit by github release tag?

**Comment by PeterDaveHello** [comment]
The bot picks commit by GitHub release tag, it's highly possible that it was re-tagged, that's not the first case here.

**Comment by MattIPv4** [comment]
No progress, closing.
