### ISSUE TITLE
[Request] Add js-deflate

### ISSUE THREAD

**Issue by artBoffin** [cdnjs/cdnjs#11173]
Library name: js-deflate
Git repository url: 
https://github.com/dankogai/js-deflate
npm package name or url (if there is one): 
License (List them all if it's multiple): GPL-2
Official homepage: (user homepage) http://www.dan.co.jp/~dankogai/
Wanna say something? Leave message here:

**Comment by MattIPv4** [comment]
Library appears to no longer be maintained, closing.
