### ISSUE TITLE
[Request] Add hammer-time

### ISSUE THREAD

**Issue by manico** [cdnjs/cdnjs#11176]
**Library name:** hammer-time
**Git repository url:** https://github.com/hammerjs/hammer-time
**npm package name or url:** https://www.npmjs.com/package/hammer-timejs
**License (List them all if it's multiple):** MIT
**Official homepage:** http://hammerjs.github.io/
**Wanna say something? Leave message here:** 

Please add this hammer.js related package.
Thank you. :)

**Comment by PeterDaveHello** [comment]
@manico Thanks!

**Comment by clusteratlas** [comment]
+1
