### ISSUE TITLE
[Request] Add styled-components

### ISSUE THREAD

**Issue by jianzhou520** [cdnjs/cdnjs#11178]
**Library name:** styled-components
**Git repository url:** https://github.com/styled-components/styled-components
**npm package name or url** (if there is one): https://www.npmjs.com/package/styled-components
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @jianzhou520 Do you mean lib in this repo https://github.com/styled-components/styled-components?

**Comment by jianzhou520** [comment]
yep!╰(￣▽￣)╭

**Comment by extend1994** [comment]
Thanks!
