### ISSUE TITLE
[Request][author] Add slim-select

### ISSUE THREAD

**Issue by brianvoe** [cdnjs/cdnjs#11189]
**Library name:** slim-select
**Git repository url:** https://github.com/brianvoe/slim-select
**npm package name or url** (if there is one): slim-select
**License (List them all if it's multiple):** MIT
**Official homepage:** http://slimselectjs.com/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @brianvoe , sorry for the late reply, just asking: if you'd be interested in sending us a pull request? It'll be great if you can send us a pull request, so that we can host it faster! There are some references in beginner issues like #11291 may help, please let me know that if you need any help 😄

**Comment by brianvoe** [comment]
Sorry i probably wont continue trying to make my package available via cdn. I make too many updates and response times for new version pull requests would always be behind.

**Comment by PeterDaveHello** [comment]
We'll take care of it, no worries.

**Comment by brianvoe** [comment]
ok thanks

**Comment by brianvoe** [comment]
I dont mind helping out its just the manual pull request process wasnt ideal.

What will the url path be. Was going to add to the docs how to use via cdn.

**Comment by PeterDaveHello** [comment]
@brianvoe we have auto-update mechanism, so no manual updates in future needed unless you changed the file structure.
As we haven't added it yet, no url yet, but should be something like https://cdnjs.com/libraries/slim-select

**Comment by brianvoe** [comment]
Perfect! Thank you!

**Comment by PeterDaveHello** [comment]
@brianvoe will consider to send a pull request with auto-update config?

**Comment by brianvoe** [comment]
If its a one time thing. Absolutely. I tried looking at the readme and it wasnt super clear exactly what i needed to do but ill look over it again.

**Comment by PeterDaveHello** [comment]
@brianvoe take a look at the issue I mention above?

**Comment by PeterDaveHello** [comment]
@brianvoe if you need any help @sufuf3 will also help you, feel free to ask!
