### ISSUE TITLE
[Request] Add angular-throttle-debounce

### ISSUE THREAD

**Issue by dlevacher** [cdnjs/cdnjs#11181]
**Library name:** angular-throttle-debounce
**Git repository url:** https://github.com/tsaikd/angular-throttle-debounce
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 
**bower**: https://libraries.io/bower/angular-throttle-debounce

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
@dlevacher this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by qwe19272375** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
