### ISSUE TITLE
[Request] Add emojionearea

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11182]
**Library name:** emojionearea
**Git repository url:** https://github.com/mervick/emojionearea
**npm package name or url** (if there is one): https://www.npmjs.com/package/emojionearea
**License (List them all if it's multiple):** MIT
**Official homepage:** https://jsfiddle.net/1v03Lqnu/12/
**Wanna say something? Leave message here:** 

Very nice and simple in use JQUERY emoji area plugin

**Comment by PeterDaveHello** [comment]
Thanks for suggestion, move to #10981
