### ISSUE TITLE
[Request] Add RichMarker

### ISSUE THREAD

**Issue by boylove142** [cdnjs/cdnjs#11191]
**Library name:** RichMarker
**Git repository url:** https://github.com/googlemaps/js-rich-marker
**npm package name or url** (if there is one): https://www.npmjs.com/package/js-rich-marker
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
Already requested #8242
