### ISSUE TITLE
[Request] Add facebook ga

### ISSUE THREAD

**Issue by sivashashank** [cdnjs/cdnjs#11194]
**Library name:** galleria-facebook
**Git repository url:** https://github.com/aiaio/galleria-facebook
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** http://www.alexanderinteractive.com/blog/2012/03/display-facebook-photos-on-your-website-with-galleria/
*Facebook plugin galleria** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@sivashashank this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sivashashank** [comment]
Yeah sure
Regards,
Siva Shashank

**Comment by sufuf3** [comment]
@sivashashank Thanks.
close for this library doesn't have enough popularity.
cc @PeterDaveHello
