### ISSUE TITLE
[Request] Add animatescroll.js

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11196]
**Library name:** animatescroll.js
**Git repository url:** https://github.com/ramswaroop/animatescroll.js
**License (List them all if it's multiple):** MIT
**Official homepage:** http://plugins.compzets.com/animatescroll

**Comment by PeterDaveHello** [comment]
@sufuf3 Remove empty item as we discussed before...

**Comment by sufuf3** [comment]
Sorry, I removed them.

**Comment by abhishek71994** [comment]
@PeterDaveHello is this one taken up by someone?

**Comment by PeterDaveHello** [comment]
@abhishek71994 Looks not, feel free to take it.

**Comment by abhishek71994** [comment]
@PeterDaveHello The procedure is the same as that of the addition of moon.js? for I am a beginner.

**Comment by PeterDaveHello** [comment]
@abhishek71994 Should be not very different, feel free to try and ask for help!

**Comment by abhishek71994** [comment]
Sure, thanks.

**Comment by MattIPv4** [comment]
Library appears to no longer be maintained, closing.
