### ISSUE TITLE
[Request] Add 3d.city

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11193]
**Library name:** 3d.city
**Git repository url:** https://github.com/lo-th/3d.city
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** GPL-3.0
**Official homepage:** http://lo-th.github.io/3d.city/index.html
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
