### ISSUE TITLE
Add new Animatelo release v1.0.3

### ISSUE THREAD

**Issue by gibbok** [cdnjs/cdnjs#11195]
Hi, I would like to notify you that a new release [v1.0.3](https://github.com/gibbok/animatelo/releases/tag/1.0.3) of [Animatelo](https://github.com/gibbok/animatelo) is now available.

Please update your [CDN](https://cdnjs.com/libraries/animatelo).

Thanks for your collaboration.

**Comment by sufuf3** [comment]
@gibbok we just add v1.0.3 3 hours ago ref: https://github.com/cdnjs/cdnjs/commit/67a4fce0c85a68bfbe36476ba62554d95d7c5b83

Thank you for your suggestion.

**Comment by qwe19272375** [comment]
@sufuf3 I think this issue can be closed?

**Comment by sufuf3** [comment]
close by the version added by @PeterBot 
cc @PeterDaveHello , @qwe19272375

**Comment by PeterDaveHello** [comment]
I think it was added before this issue was created actually.
