### ISSUE TITLE
[Request] Add jmespath

### ISSUE THREAD

**Issue by Jaygiri** [cdnjs/cdnjs#11209]
**Library name:** jmespath
**Git repository url:** https://github.com/jmespath/jmespath.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/jmespath
**License (List them all if it's multiple):** Apache License, Version 2.0
**Official homepage:** http://jmespath.org/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
I'll be working on this. @hare1039 Please add the `High Priority` label to this since this library is extremely popular.

* 75,165 downloads in the last day
* 443,237 downloads in the last week
* 1,918,841 downloads in the last month

**Comment by hare1039** [comment]
@dakshshah96 Thank you for reminding me!

**Comment by Jaygiri** [comment]
Thank you @dakshshah96 @hare1039 @PeterDaveHello and @clairetsai818

**Comment by PeterDaveHello** [comment]
@Jaygiri You're welcome.

**Comment by dakshshah96** [comment]
@Jaygiri **jmespath** has been added to cdnjs! Check out https://cdnjs.com/libraries/jmespath 😄

**Comment by Jaygiri** [comment]
Thank you @dakshshah96 @hare1039 @PeterDaveHello @clairetsai818 and @qwe19272375 for working on this and making JMESPath available through cdnjs.com. 

Thank you on behalf of all JMESPath users.

**Comment by PeterDaveHello** [comment]
@Jaygiri totally welcome 👍
