### ISSUE TITLE
Use Zopfli for smaller files.

### ISSUE THREAD

**Issue by jdalton** [cdnjs/cdnjs#1120]
I think it would be awesome if cdnjs used Zopfli to deliver smaller files.
See http://josephscott.org/archives/2013/03/zopfli-compression/

**Comment by PeterDaveHello** [comment]
Any updates? @thomasdavis @terinjokes

**Comment by terinjokes** [comment]
@PeterDaveHello It's on my task list here.

**Comment by PeterDaveHello** [comment]
Thanks, I'm just making sure we remember this.

**Comment by Daniel15** [comment]
http://minime.stephan-brumme.com/ is a good example of Zopfli in use:

> Surprisingly, most Content Delivery Networks (CDNs) give you a quite bad level of GZIP compression.

> Google's Zopfli (open source) is currently the best GZIP compressor and produces the smallest files.
It produces files fully compatible to the DEFLATE algorithm (used by GZIP) but in order to find even better compression

As an example, D3 on CDNJS is 53916 bytes, whereas a version compressed with Zopfli with optimum settings is only 51278 bytes (see http://minime.stephan-brumme.com/d3/3.5.8).

**Comment by PeterDaveHello** [comment]
hmmmm ... should as @terinjokes about the plan, as far as I know, Zopfli will spend much time to compress than origin gzip, so it's not good for on the fly compression, but for kinds like cdnjs, we seldom modify the already exist files, it'll be good if there is a pre-compress progress.

**Comment by Daniel15** [comment]
> but for kinds like cdnjs, we seldom modify the already exist files, it'll be good if there is a pre-compress progress

Yeah, I think CDNJS should compress everything beforehand rather than doing it on-the-fly. It's a good way to save CPU cycles too, rather than recompressing the exact same content over and over again.

**Comment by PeterDaveHello** [comment]
Now here comes the Zopfli 
https://datatracker.ietf.org/doc/draft-alakuijala-brotli/
https://plus.google.com/u/0/+IlyaGrigorik/posts/X9ogn4fLtHL

**Comment by rayshan** [comment]
@PeterDaveHello Brotli isn't the same as Zopfli. Zopfli is already universally supported. Brotli provides even better compression, but requires new browsers implementations. Ideally we would want to support both, serve Brotli-encoded files when client sends `br` header and fallback to Zopfli-encoded files.

References:
http://google-opensource.blogspot.com/2015/09/introducing-brotli-new-compression.html
http://caniuse.com/#search=Brotli

**Comment by PeterDaveHello** [comment]
@rayshan yep I didn't say they are the same, just a reference that we may consider to support in future.

**Comment by PeterDaveHello** [comment]
Guys, forgot to update this issue, at the meantime, we use zopfli to compress PNG internally as a start.

41de841 Merge branch 'zopfli' Peter Dave Hello 3 days ago
|\
| 25192ec zopfli png compression for new imgs Peter Dave Hello 3 days ago
| dd300d8 revert some zopflied png imgs to optipng ver Peter Dave Hello 3 days ago
| 2b206d6 zopfli png img recompression (internal, loseless) Peter Dave Hello 9 days ago
| d1d31ac Revert optipng optimization, will use zopfli instead! Peter Dave Hello 10 days ago
|/

**Comment by MattIPv4** [comment]
@PeterDaveHello I'm a bit confused here, is Zopfli something we'd need to implement or for Cf to implement?

**Comment by xtuc** [comment]
It looks like we are using Zopfli now
