### ISSUE TITLE
[Request] Add optimizely

### ISSUE THREAD

**Issue by uzairbukhari** [cdnjs/cdnjs#11205]
**Library name:** optimizely
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @uzairbukhari,
Would you provide more information about this library?
e.g. some urls to npm/GitHub pages?

Thanks!

**Comment by uzairbukhari** [comment]
Yeah sure,

Npm: https://www.npmjs.com/package/optimizely-client-sdk
Github: https://github.com/optimizely/javascript-sdk

I need to use it in a drupal page so I need its cdn, unfortunately they dont have it already,
Thanks

**Comment by hare1039** [comment]
Thanks!
BTW, we members currently stop working on normal library-adding issues
https://github.com/cdnjs/cdnjs/issues/11170

So if you wish to get this library online in few weeks, you may need to send a PR by yourself.

Sorry for the inconvenience.
