### ISSUE TITLE
[Request] Add WebGazer.js

### ISSUE THREAD

**Issue by dakshshah96** [cdnjs/cdnjs#11237]
**Library name:** WebGazer.js
**Git repository url:** https://github.com/brownhci/WebGazer
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** GPL-3.0
**Official homepage:** https://webgazer.cs.brown.edu/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
@pvnr0082t Please add `in progress` label here.

**Comment by PeterDaveHello** [comment]
@dakshshah96 better tag @qwe19272375 to do it

**Comment by sashberd** [comment]
According to PR [discussion](https://github.com/cdnjs/cdnjs/pull/11257#issuecomment-387343201) the request is closed
