### ISSUE TITLE
[Request] Add BWIP.js

### ISSUE THREAD

**Issue by dakshshah96** [cdnjs/cdnjs#11239]
**Library name:** BWIP.js
**Git repository url:** https://github.com/metafloor/bwip-js
**npm package name or url** (if there is one): http://npmjs.com/package/bwip-js
**License (List them all if it's multiple):** MIT
**Official homepage:** http://bwip-js.metafloor.com/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #10215
@qwe19272375 please check if the issue is duplicate with another issue.
cc @PeterDaveHello

**Comment by dakshshah96** [comment]
@sufuf3 Agreed. This issue is a duplicate.
