### ISSUE TITLE
Not correct version of html2canvas on CDNjs

### ISSUE THREAD

**Issue by alundiak** [cdnjs/cdnjs#11232]
I created https://github.com/niklasvh/html2canvas/issues/1115
But not sure whose fault it is in fact.
Any ideas?

cc/ @niklasvh @eKoopmans

**Comment by eKoopmans** [comment]
Hi @alundiak, it's just a problem in the html2canvas header info, I'll comment over there. No problem with CDNJS, you should be able to close this.

**Comment by alundiak** [comment]
I somehow not agree, because I took 2 different beta-4 code files and it behaves diff. U know what I mean.
