### ISSUE TITLE
[Request] Add matrix-js-sdk

### ISSUE THREAD

**Issue by C0deZLee** [cdnjs/cdnjs#11246]
**Library name:** matrix-js-sdk
**Git repository url:** https://github.com/matrix-org/matrix-js-sdk/releases/tag/v0.7.7
**npm package name or url** (if there is one): matrix-js-sdk
**License (List them all if it's multiple):** Apache License 2.0
**Official homepage:** https://matrix.org/
**Wanna say something? Leave message here:** Please!!!!

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
