### ISSUE TITLE
[Request] Add CrackerakiUA/ui-cropper

### ISSUE THREAD

**Issue by smil2k** [cdnjs/cdnjs#11250]
**Library name:** 
**Git repository url:** https://github.com/CrackerakiUA/ui-cropper
**npm package name or url** (if there is one):  (old https://www.npmjs.com/package/ng-img-crop-full-extended)
**License (List them all if it's multiple):** MIT
**Official homepage:** Github
**Wanna say something? Leave message here:** 

This is a clone of 'ng-img-crop'. It has been renamed recently, thus only 75, the previous name was: https://github.com/CrackerakiUA/ngImgCropFullExtended and had well over 100 stars.

**Comment by alexstanbury** [comment]
Hi, please add this library, it's still being developed and is very useful!
