### ISSUE TITLE
[Request] Add JSandbox

### ISSUE THREAD

**Issue by binaek89** [cdnjs/cdnjs#11259]
**Library name:** JSandbox
**Git repository url:** https://github.com/eligrey/jsandbox
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT license
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@binaek89 According to author library is discounted and not in use.

**Comment by extend1994** [comment]
Close it due to insufficient popularity and no response
