### ISSUE TITLE
[Request] Add chai-as-promised

### ISSUE THREAD

**Issue by thisgeek** [cdnjs/cdnjs#11255]
**Library name:** chai-as-promised
**Git repository url:** https://github.com/domenic/chai-as-promised
**npm package name or url** (if there is one): chai-as-promised
**License (List them all if it's multiple):** [WTFPL](https://github.com/domenic/chai-as-promised/blob/master/LICENSE.txt)
**Official homepage:** None; see either the [README](https://github.com/domenic/chai-as-promised/blob/master/README.md) or the [plugin page](http://chaijs.com/plugins/chai-as-promised/)
**Wanna say something? Leave message here:** 

chai-as-promised currently ranks as the most starred project for testing promises with chai that is mentioned on chai's official list of plugins.

**Comment by qwe19272375** [comment]
NOTE: 1003 stars at GitHub repository

**Comment by PeterDaveHello** [comment]
As per https://github.com/domenic/chai-as-promised/issues/199#issuecomment-305964026, we won't host his library, thanks for suggestion.
