### ISSUE TITLE
[Author][Request] Add mobile debug

### ISSUE THREAD

**Issue by iGitScor** [cdnjs/cdnjs#11263]
Library name: mobile-debug
Git repository url: https://github.com/iGitScor/mobile-debug
npm package name or url (if there is one): https://www.npmjs.com/package/mobile-debug
License (List them all if it's multiple): MIT
Official homepage: None (for the moment)
Wanna say something? Leave message here:

Do I have to make a pull request for that ?

Thank you !

=====================

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@iGitScor sorry for the late reply, it'll be great if you can send us a pull request, so that we can host it faster! There are some references in beginner issues like #11291 may help, please let me know that if you need any help 😄 

@sufuf3 why didn't you reply to its content? You are not a robot.

**Comment by sashberd** [comment]
Hi @iGitScor
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by iGitScor** [comment]
Hi, I hosted in a private server for local deployment

No problem to close the demand
