### ISSUE TITLE
[Request] Add Mapbox/polyline

### ISSUE THREAD

**Issue by enicolasToast** [cdnjs/cdnjs#11264]
Library name: @mapbox/polyline
Git repository url: https://github.com/mapbox/polyline
npm package name or url (if there is one): https://www.npmjs.com/package/@mapbox/polyline (old: https://www.npmjs.com/package/polyline)
License (List them all if it's multiple): Not sure on the type, there is one on the github root path
Official homepage: None (for the moment)
Wanna say something? Leave message here:

Thank you !

**Comment by Billy4195** [comment]
I'd like to take this.

**Comment by sufuf3** [comment]
@Billy4195 Sorry about that.
I think this lib need to be discuss.
@enicolasToast Could you tell us which file can be used in web frond-end that we need to add?
Such as `<script src="filename.js"></script>`

Thanks.

**Comment by extend1994** [comment]
`src/polyline.js` is for browser, see [README](https://github.com/mapbox/polyline#polyline)
> Compatible with nodejs (npm install @mapbox/polyline and the browser (copy src/polyline.js)).

**Comment by enicolasToast** [comment]
Sorry @sufuf3, I left the company where I was working on this and have lost context on it :/
