### ISSUE TITLE
[Request] Update PKI.js repository url, homepage, keyword

### ISSUE THREAD

**Issue by kweisamx** [cdnjs/cdnjs#11268]
**Library name:** PKI.js
**Git repository url:**https://github.com/PeculiarVentures/PKI.js 
**npm package name or url** (if there is one): https://www.npmjs.com/package/pkijs
**License (List them all if it's multiple):**MIT 
**Official homepage:** https://pkijs.org/
**Wanna say something? Leave message here:**

**Comment by PeterDaveHello** [comment]
PR not sent yet?
