### ISSUE TITLE
In progress issue labels

### ISSUE THREAD

**Issue by dakshshah96** [cdnjs/cdnjs#11260]
As of writing this, there are 735 open issues on the cdnjs repo with the majority of them being requests to add/update libraries.

## The Problem

* Finding issues to work on is particularly difficult right now as the label `In progress` is not used proactively to label issues which are currently work in progress.
* Due to this, a contributor needs to open up the issue on a new page and check if a PR has already been made and then decide if he can work on that issue or not.

## Proposed solution and advantages

* If one of the maintainers would be kind enough to do so, we can create a system where a label of `In progress` is added as soon as the issue is mentioned in a pull request.
* This has the added advantage of making it faster to discover issues which aren't being worked on.
* Now, all a new contributor needs to do is use the following criterion and find a new issue to work on without opening up the issue on a new page and check manually — `Doesn't have label In progress` and has a label like `Request to add/update library`.  As simple as that.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Should be fixed now for new PRs, see #11176 as example.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please help label old issues that have corresponding PR with `in progress` label manually.

**Comment by dakshshah96** [comment]
@PeterDaveHello Great! 😄

**Comment by dakshshah96** [comment]
@PeterDaveHello So, the `in progress` label will also be removed when the issue is closed?

**Comment by PeterDaveHello** [comment]
@dakshshah96 yep

**Comment by qwe19272375** [comment]
All old issues that have corresponding PR labeled as `in progress`, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@qwe19272375 Well done.

**Comment by dakshshah96** [comment]
Thanks for the effort @qwe19272375 😄

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 @cdnjs/active-contributor please use "Close #issueNumber" format in pull request "**comment**", so that waffle can help auto label the issues, in commit message will not work in this feature.
