### ISSUE TITLE
[Request] Add art-template

### ISSUE THREAD

**Issue by up9cloud** [cdnjs/cdnjs#11276]
**Library name:** art-template
**Git repository url:** https://github.com/aui/art-template
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://aui.github.io/art-template/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
npm package URL: https://www.npmjs.com/package/art-template
