### ISSUE TITLE
[Request] Add graph-viz-d3.js

### ISSUE THREAD

**Issue by jonhoo** [cdnjs/cdnjs#11275]
Library name: graph-viz-d3-js, A Graphviz web D3.js renderer.
Git repository url: https://github.com/mstefaniuk/graph-viz-d3-js
Official homepage: https://github.com/mstefaniuk/graph-viz-d3-js

**Comment by fintelia** [comment]
I'm also interested in having this library added. Anything I can do to help speed up the process?

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.

**Comment by miparnisari** [comment]
Can we add this one instead? https://github.com/magjac/d3-graphviz. Last commit was 19 hours ago
