### ISSUE TITLE
[Request] Add Morphext

### ISSUE THREAD

**Issue by Niko9911** [cdnjs/cdnjs#11283]
**Library name:** Morphext
**Git repository url:** https://github.com/MrSaints/Morphext
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://morphext.fyianlai.com/
**Wanna say something? Leave message here:** I would like if you add this with high priority. I need this JS library to my customer website :+1: Also I'm not creator of this JS!

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicate with #9219

**Comment by PeterDaveHello** [comment]
Move to #9219
