### ISSUE TITLE
[Request] Add material-components-web

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#11282]
**Library name:** material-components-web
**Library description:** Modular and customizable Material Design UI components for the web
**Git repository url:** https://github.com/material-components/material-components-web
**npm package name or url** (if there is one): https://www.npmjs.com/package/material-components-web
**License (List them all if it's multiple):** [Apache 2.0](https://github.com/material-components/material-components-web/blob/master/LICENSE)
**Official homepage:** https://material.io/components/web/

**Comment by Richienb** [comment]
Is there an estimation on when this library will be added?
