### ISSUE TITLE
[Request] Add texthighlighter

### ISSUE THREAD

**Issue by dsaouda** [cdnjs/cdnjs#11298]
**Library name:** texthighlighter
**Git repository url:** https://github.com/mir3z/texthighlighter
**npm package name or url** (if there is one): https://www.npmjs.com/package/texthighlighter
**License (List them all if it's multiple):**  MIT
**Official homepage:** http://mir3z.github.io/texthighlighter/
**Wanna say something? Leave message here:** Highlighting of selected text

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #9234

**Comment by PeterDaveHello** [comment]
@sufuf3 please help add this lib.
