### ISSUE TITLE
[Request] Update multiple-select

### ISSUE THREAD

**Issue by RichardMisencik** [cdnjs/cdnjs#11297]
**Library name:** multiple-select
**Git repository url:** https://github.com/wenzhixin/multiple-select
**npm package name or url (if there is one):** None
**License (List them all if it's multiple):** MIT
**Official homepage:** http://wenzhixin.net.cn/p/multiple-select/docs/
**Wanna say something? Leave message here:** Current cdnjs version: **1.2.0**, Latest available version: **1.2.1** (from Jan 3, 2016)

**Comment by PeterDaveHello** [comment]
@dakshshah96 mind to take this?

**Comment by dakshshah96** [comment]
@PeterDaveHello Sure, no problem!

**Comment by RichardMisencik** [comment]
How much time is this going to take until it is accessible on cdnjs.com?

**Comment by dakshshah96** [comment]
@RichardMisencik Working on it right now. We'll treat this as high priority now so it's up as soon as possible 👍

**Comment by RichardMisencik** [comment]
@dakshshah96 Thanks mate 👍
