### ISSUE TITLE
[Request] Add bootstrap iconpicker

### ISSUE THREAD

**Issue by andersmmg** [cdnjs/cdnjs#11306]
**Library name:** bootstrap iconpicker
**Git repository url:** https://github.com/victor-valencia/bootstrap-iconpicker
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Unknown
**Official homepage:** https://victor-valencia.github.io/bootstrap-iconpicker/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicate with #8052

**Comment by PeterDaveHello** [comment]
Let's move to #8052 👍
