### ISSUE TITLE
[Request] Add Neataptic

### ISSUE THREAD

**Issue by wagenaartje** [cdnjs/cdnjs#11326]
**Library name**: Neataptic
**Git repository url**: https://github.com/wagenaartje/neataptic
**npm package name or url:** https://www.npmjs.com/package/neataptic
**License**: MIT
**Official homepage**: https://wagenaartje.github.io/neataptic/

**Comment by ajay2507** [comment]
@wagenaartje Can I make this change?.

**Comment by wagenaartje** [comment]
@ajay2507, if you would like, yes please.
