### ISSUE TITLE
[Request] Add kotlin-js standard library

### ISSUE THREAD

**Issue by camdenorrb** [cdnjs/cdnjs#11336]
**Library name:** kotlin-js standard library

**Git repository url:**  https://github.com/JetBrains/kotlin/tree/master/libraries/stdlib/js

**npm package name or url** (if there is one): https://www.npmjs.com/package/kotlin

**License (List them all if it's multiple):** 
https://github.com/JetBrains/kotlin/blob/master/license/LICENSE.txt
https://github.com/JetBrains/kotlin/blob/master/license/NOTICE.txt
https://github.com/JetBrains/kotlin/tree/master/license/third_party - third party, multiple licenses

**Official homepage:** https://kotlinlang.org

**Wanna say something? Leave message here:**  Kotlin's usage has been increasing at a very fast rate, as it's usage starts to move towards the Web usage of Kotlin it would be nice to have a CDN for it. Kotlin's Github currently has 13.7k stars and is increasing every day.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
There is a person try to add this. ref: #11288

**Comment by camdenorrb** [comment]
Are y'all still planning on adding this?

**Comment by arocnies** [comment]
Is this still in progress? Hoping it is 😄

**Comment by sufuf3** [comment]
@extend1994 This issue is assigned to you. Would you like to add this lib recently? This is a high priority issue.

**Comment by thecodewarrior** [comment]
Is this not happening or has it just been buried under a torrent of issues? 

I’m not familiar with contributing to cdnjs, but if I’m understanding your CONTRIBUTING.md correctly all that should really be needed is the NPM package.json, and the auto-update script can do the rest? If so I’m sure it’s trivial to grab the package.json directly off NPM, but even so, here’s their [package.json template](https://github.com/JetBrains/kotlin/blob/master/js/npm/templates/kotlin/package.json).

The latest word I can find from their end is [this forum comment](https://discuss.kotlinlang.org/t/cdn-link-for-kotlin-js/2296/2) from two years ago, where they said “We’re not publishing the Kotlin JS library to any CDN at this time.”

They appear to have published to NPM from the start, so I don’t know if they don’t _want_ it on a CDN or whether they just have never gotten around to it. [commit](https://github.com/JetBrains/kotlin/blob/0a0a05d211cc4644d2c1ec38cbee1217c7ce1bbc/node_utils.xml), [NPM](https://www.npmjs.com/package/kotlin/v/0.0.0)

This ambiguity over whether they actively don’t want it on a CDN or whether they simply haven’t done it yet would obviously need to be worked out before we put it on a CDN. I could certainly ask myself, however I would imagine that someone coming from cdnjs in an official capacity would likely get a more in-depth reply, and would be more likely to get a reply in the first place.

While this isn’t critical for me, I’m sure a lot of people would be very happy to have the stdlib on a CDN as opposed to having to host it themselves.

Thank you for your time.
