### ISSUE TITLE
[Request] Add cssesc

### ISSUE THREAD

**Issue by zhanhb** [cdnjs/cdnjs#11340]
**Library name:** cssesc
**Git repository url:** https://github.com/mathiasbynens/cssesc
**npm package name or url** (if there is one): cssesc
**License (List them all if it's multiple):** MIT
**Official homepage:** https://mths.be/cssesc
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by zhanhb** [comment]
By the way, can v0.1.0 be included in cdnjs?

**Comment by PeterDaveHello** [comment]
@zhanhb Sure thing!

**Comment by PeterDaveHello** [comment]
@zhanhb See: e9c48170d554d310fb4540becabd649c93eb1416, it'll be deployed in 10 mins.

**Comment by zhanhb** [comment]
Thanks very much!

**Comment by PeterDaveHello** [comment]
@zhanhb you're welcome.
