### ISSUE TITLE
[Request] Update the auto-update config of react-native-elements

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11349]
**Library name:** react-native-elements
**Git repository url:** https://github.com/dabit3/React-Native-Elements
**License (List them all if it's multiple):** MIT
**Official homepage:** https://react-native-training.github.io/react-native-elements/
cc #10418

**Comment by sufuf3** [comment]
@PeterDaveHello one of the collaborator of this library said he has a problem about minified files and can't commit for something back in time.
ref: https://github.com/react-native-training/react-native-elements/issues/375#issuecomment-306080179
What can we do?

**Comment by PeterDaveHello** [comment]
So have you confirmed it?

**Comment by sufuf3** [comment]
I discussed with the author (react-native-training/react-native-elements#375) for adding the versions>0.12.0 from npm to GitHub, then I can manually add these versions from GitHub to CDNJS.
But there is no response until this library manually added 4 days ago. https://github.com/cdnjs/cdnjs/commit/ad244068d9a54871583dec1e01a3bc116c525b69

Maybe this issue can close. cc @PeterDaveHello
