### ISSUE TITLE
[Request] Add material-kit

### ISSUE THREAD

**Issue by rujing130185** [cdnjs/cdnjs#11358]
**Library name:** material-kit
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@rujing130185 Do you mean that you want to CDNJS host this library --> https://github.com/creativetimofficial/material-kit ?

**Comment by sufuf3** [comment]
Maybe need assets of this library.
**Git repository url**: https://github.com/creativetimofficial/material-kit
**Official homepage**: https://www.creative-tim.com/product/material-kit
