### ISSUE TITLE
[Request] Add pagecss

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11353]
**Library name:** pagecss
**Git repository url:** https://github.com/chilts/pagecss
**License:** MIT
**Official homepage:** https://pagecss.org/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by HenryKobin** [comment]
Hey Peter, I'd love to try this one out. I just finished reading all the CONTRIBUTING docs and the autoupdate.md
Can I follow the directions for "adding a new library by a single package.json" or should i potentially follow the "adding a new library with it's assets"?
I'm guessing we probably need the assets right?
Thanks for your time! :]
cc: @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@HenryKobin both fine, if you add it with single package.json, I'll add the assests later for you, it'll be more simple, if you'd like to learn more, adding with assets would be more interesting and chanllenging

**Comment by HenryKobin** [comment]
@PeterDaveHello okay cool, I'll work on the package.json first, then if all is well I can give the assets a shot.
What i'm thinking is we mainly need the css file, correct? Or would the user maybe also want the examples folder.
I'll start working on this right now. I should have something ready in the next couple of hours for you guys to take a look at. 👍

**Comment by HenryKobin** [comment]
May i make a pull request by adding to the `ajax/libs` folder `/pagecss/package.json`? Then after that adding the rest via `\0.3.0\` <-- files go in this folder? @PeterDaveHello

**Comment by PeterDaveHello** [comment]
You are correct, it's about the css files, all we need here is the `dist` folder which contains all the distribution purpose files, `ajax/libs/pagecss/package.json` is the correct path, and the files go where the version is, for version 3.0.0, it's `3.0.0` as you say 👍

**Comment by HenryKobin** [comment]
@PeterDaveHello do we need the build.js in the root folder of pagecss, as well?
Also, how does this package.json look with auto-update? Thanks again 😄 
`
  {
  "name": "pagecss",
  "version": "0.3.0",
  "author": "Andrew Chilton"
  "description": "Beautiful CSS for single page sites - simple all the way up!",
  "main": "dist/page.css",
  "style": "dist/page.min.css",
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/chilts/pagecss.git",
    "fileMap": [
      {
        "basePath": "/dist",
        "files": [
          "page.css",
          "page.css.map",
          "page.min.css",
          "page.min.css.map"
        ]
      }
    ]
  }

  "scripts": {
    "build": "node build.js",
    "watch": "node watch.js"
  },
  "repository": "chilts/pagecss",
  "dependencies": {
    "node-sass": "^4.5.3"
  },
  "license": "MIT"
}`

**Comment by PeterDaveHello** [comment]
@HenryKobin we don't need the build script, take a look jquery's pacakge.json as example, and just send a pull request, we have a CI system will tell you that some of the sections should be removed :)

**Comment by HenryKobin** [comment]
awesome thanks!!!! @PeterDaveHello

**Comment by HenryKobin** [comment]
@PeterDaveHello  one final question before I make my pull request: Should i remove the `scripts` from the package.json I posted above? Its included in PageCSS's package.json, but i'm only bringing over the files from the `/dist` folder.

**Comment by PeterDaveHello** [comment]
@HenryKobin it should be removed :+1:

**Comment by HenryKobin** [comment]
@PeterDaveHello will it break the package.json if have the `"author: Andrew Chilton"` line added to our package.json? Its not in the original, but i figure its good form to add the author name. I just don't know if that will make it conflict or something when it updates

**Comment by PeterDaveHello** [comment]
@HenryKobin it won't
