### ISSUE TITLE
[Request] Update Bootswatch 3.3.7 to add "solar" theme

### ISSUE THREAD

**Issue by supriyo-biswas** [cdnjs/cdnjs#11359]
**Library name**: bootswatch
**Git repository url**: https://github.com/thomaspark/bootswatch
**License**: MIT
**Official homepage**: https://bootswatch.com/

Recently, a new theme named "Solar" was added to both v4.x and v3.3.7. I'd like to request an update of this library to add this theme, as v3.3.7 is absent on cdnjs.

I'd have sent in the pull request myself, but the process of cloning (even with a sparse checkout) has been very slow, and I can't actually push the new changes since Github refuses the request after transferring ~3.7 GB of data.

**Comment by dakshshah96** [comment]
Hey @supriyo-biswas, I couldn't find the "Solar" theme on bootswatch's npm package. Please check here: https://unpkg.com/bootswatch@3.3.7/

**Comment by supriyo-biswas** [comment]
@dakshshah96 The theme seems to have been added only in the gh-pages branch of that repository. I don't know how this would work with the npm integration, however, maybe these files [[1](https://bootswatch.com/solar/bootstrap.min.css), [2](https://bootswatch.com/solar/bootstrap.css)] could be manually added into the repo?

**Comment by extend1994** [comment]
The issue about this: https://github.com/thomaspark/bootswatch/issues/643

**Comment by sashberd** [comment]
@supriyo-biswas Is this request still relevant? Do you still need solar theme in v3.3.7?

**Comment by supriyo-biswas** [comment]
No.
