### ISSUE TITLE
[Request] Update the auto-update config of oojs-ui

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11350]
**Library name:** oojs-ui
**Git repository url:** https://phabricator.wikimedia.org/diffusion/GOJU
**npm:** https://www.npmjs.com/package/oojs-ui
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.mediawiki.org/wiki/OOjs_UI

**Comment by dakshshah96** [comment]
@PeterDaveHello Why didn't @sufuf3 not get automatically assigned to this issue on making a pull request? A bug or is it normal?

**Comment by PeterDaveHello** [comment]
@dakshshah96 may be bug from waffle, need some time to debug that, will do soon, too many works here lol ...

**Comment by dakshshah96** [comment]
@PeterDaveHello Haha, no problems! 😄
