### ISSUE TITLE
[Request] Add turntable

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11361]
**Library name:** turntable
**Git repository url:** https://github.com/PolarNotion/turntable
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** ISC
**Official homepage:** https://polarnotion.github.io/turntable/
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
