### ISSUE TITLE
[Request] Add old versions of Vue.Draggable

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11360]
**Library name:** Vue.Draggable 
**Git repository url:** https://github.com/SortableJS/Vue.Draggable
**npm package url(optional):** https://www.npmjs.com/package/vuedraggable
**License(s):** MIT
**Official homepage:** https://github.com/SortableJS/Vue.Draggable

Relate PR #11233

**Comment by MattIPv4** [comment]
We no longer support manually adding versioned files, closing.
