### ISSUE TITLE
Shaka v2.1.3

### ISSUE THREAD

**Issue by boredom2** [cdnjs/cdnjs#11374]
The integrated Build for "shaka-player.compiled.js" seems to be wrong. The integrated Version is not 2.1.3, its "2.1.2-17-dirty". Can this be updated, if necessary?

**Comment by sufuf3** [comment]
Hi @boredom2 ,
Do you mean the library `shaka-player` which upstream repo is from https://github.com/google/shaka-player?
Would you tell me how did you find the `v2.1.2-17-dirty`?
I saw the latest version is `2.1.3` from https://github.com/google/shaka-player/releases, even use `npm view shaka-player versions`, and I can't find the `v2.1.2-17-dirty`.

ref: https://cdnjs.com/libraries/shaka-player

**Comment by boredom2** [comment]
Hi,

yes, the compiled Version on CDNJS here:
https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.1.3/shaka-player.compiled.js
Search the Code for "v2." and you will see, that this Version offers v2.1.2-17-gf11a54a-dirty.
This seems not to be a clean final Version of the 2.1.3 Code.

**Comment by PeterDaveHello** [comment]
It's totally the same file as their npm release, please report to https://github.com/google/shaka-player
