### ISSUE TITLE
[Request] Add i18next-xhr-backend

### ISSUE THREAD

**Issue by lutherfatcat** [cdnjs/cdnjs#11379]
**Library name: i18next-xhr-backend
**Git repository url: https://github.com/i18next/i18next-xhr-backend.git
**npm package name or url (if there is one):  i18next-xhr-backend
**License (List them all if it's multiple): MIT License
**Official homepage: https://github.com/i18next/i18next-xhr-backend
**Wanna say something? Leave message here: Please add i18next-xhr-backend, thanks in advance.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #10720

**Comment by PeterDaveHello** [comment]
Let's move to #10720
