### ISSUE TITLE
[Request] Add kiwi.js

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11370]
**Library name:** kiwi.js
**Git repository url:** https://github.com/gamelab/kiwi.js
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.kiwijs.org
**Wanna say something? Leave message here:**

**Comment by cybernet** [comment]
just for a short description, just for people to know what is about

**Kiwi.js** is the worlds easiest to use Open Source **HTML5** game framework for making both mobile and desktop **HTML5** browser games.
Our focus is blazingly fast **WebGL** rendering and complimentary tools to make professional quality serious games. We use **CocoonJS** for publishing **games and App creation**.
