### ISSUE TITLE
[Request] Add boomerang-cache

### ISSUE THREAD

**Issue by chikochavda** [cdnjs/cdnjs#11388]
**Library name:** boomerang-cache
**Git repository url:** https://github.com/giraysam/boomerang-cache
**npm package name or url** (if there is one): https://www.npmjs.com/package/boomerang-cache
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://giraysam.github.io/boomerang-cache/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Hi @chikochavda ,
this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. 
Thanks for your great work and contribution.

**Comment by chikochavda** [comment]
@sufuf3 

Thanks for your response , I understand. Sorry for not reading README.md file. I will try to reopen when it reach CDN requirement.

Thanks anyways.

**Comment by sufuf3** [comment]
Close because this library doesn't have enough popularity. cc @PeterDaveHello
