### ISSUE TITLE
[Request] Add fontselect

### ISSUE THREAD

**Issue by nikssardana** [cdnjs/cdnjs#11382]
**Library name:** fontselect
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @nikssardana , is there any detail? This issue will be closed if no response in 7 days.

**Comment by nikssardana** [comment]
Here is the github link:
https://github.com/tommoor/fontselect-jquery-plugin

I think the library is no longer maintained.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
