### ISSUE TITLE
CDNJS Not Live in Libraries Page

### ISSUE THREAD

**Issue by yoginth** [cdnjs/cdnjs#11386]
When i visit (https://cdnjs.com/libraries/markdown-it-emoji) This pahe, I'm Seeing the Default Application Error Page by **Heroku** So Fix it Soon as Possible.

**Comment by calpa** [comment]
same here

**Comment by sufuf3** [comment]
@yoginth just this page, or all the pages show the error?

I can access this page from Taiwan currently, would you please see if it is working now?
Otherwise, could you take a picture which page error message you saw?

Thanks for reporting.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Move to https://github.com/cdnjs/new-website/issues/184

**Comment by yoginth** [comment]
Thanks for Immediate Response!
