### ISSUE TITLE
[Request] Add cssicon

### ISSUE THREAD

**Issue by fathyar** [cdnjs/cdnjs#11381]
**Library name:** cssicon
**Git repository url:** https://github.com/wentin/cssicon
**npm package name or url** https://www.npmjs.com/package/cssicon 
**License:** [Creative Commons Zero v1.0 Universal](https://github.com/wentin/cssicon/blob/master/LICENSE)
**Official homepage:** http://cssicon.space

**Comment by pvnr0082t** [comment]
@orangtanah The npm package url seems like not officially maintained.

**Comment by sashberd** [comment]
No tags, no npm, no answer from author
@PeterDaveHello Can ve close this request?
