### ISSUE TITLE
[Request] Add arraysweeper

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11390]
**Library name:** arraysweeper
**Git repository url:** https://github.com/arschmitz/arraysweeper
**npm package name or url** :https://www.npmjs.com/package/arraysweeper 
**License:** MIT 

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by emarkchrome** [comment]
Hi @PeterDaveHello, I am new to contributing on GitHub, and I thought this would be a good place to start. I looked at the implementation previous issue #11344 which was similar to this one, and I know what I need to do.

**Comment by lukemccrae** [comment]
Hey @PeterDaveHello, I just submitted a pull request after following the instructions for "adding a new library by a single package.json". I am new to this and would appreciate feedback!

**Comment by PeterDaveHello** [comment]
@lukemccrae looks like you sent the pull request to your own forked repo, let's send it to cdnjs/cdnjs 👍

**Comment by lukemccrae** [comment]
@PeterDaveHello Thanks for the feedback. I've resubmitted the pull request.

**Comment by dakshshah96** [comment]
@PeterDaveHello This library doesn't seem to meet the minimum popularity requirements 😕

**Comment by sufuf3** [comment]
https://github.com/cdnjs/cdnjs/pull/11460#issuecomment-311360441 this is the library's author comment, maybe we can close this issue?

**Comment by PeterDaveHello** [comment]
@lukemccrae sorry for that, maybe you'd like to try #11473?
