### ISSUE TITLE
[Request] Add covervid.min.js

### ISSUE THREAD

**Issue by SuhailPurkar** [cdnjs/cdnjs#11392]
**Library name:** covervid
**Git repository url:** https://github.com/stefanerickson/covervid
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):**  The MIT License (MIT)
**Official homepage:**  http://stefanerickson.github.io/covervid/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicated with #5427

**Comment by PeterDaveHello** [comment]
Let's move to  #5427
