### ISSUE TITLE
[Request] Add magnify

### ISSUE THREAD

**Issue by thdoan** [cdnjs/cdnjs#11394]
Library name: magnify
Git repository url: https://github.com/thdoan/magnify
npm package url (optional): https://www.npmjs.com/package/magnify
License(s): https://github.com/thdoan/magnify/blob/master/LICENSE
Official homepage: https://thdoan.github.io/magnify/
Wanna say something? Leave message here: This is my second request to host my library. My [first attempt](https://github.com/cdnjs/cdnjs/issues/6604) got rejected because it wasn't popular enough. *Fingers crossed!*

**Comment by TimotheeJeannin** [comment]
Would be nice to add this lib !

**Comment by sufuf3** [comment]
duplicated with #6604
And this lib is working on.
close this issue and let's move to #6604
