### ISSUE TITLE
[Request] Add combodate

### ISSUE THREAD

**Issue by oscarDavid** [cdnjs/cdnjs#11397]
**Library name:** combodate
**Git repository url: https://github.com/vitalets/combodate** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage: http://vitalets.github.io/combodate/** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

URL:
https://github.com/vitalets/combodate
http://vitalets.github.io/combodate/

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
