### ISSUE TITLE
[Request] Add Sticky Kit

### ISSUE THREAD

**Issue by surjithctly** [cdnjs/cdnjs#11408]
**Library name:** Sticky Kit
**Git repository url:** https://github.com/leafo/sticky-kit
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** http://leafo.net/sticky-kit/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
duplicated with #7522

**Comment by PeterDaveHello** [comment]
Let's move to  #7522
