### ISSUE TITLE
[Request] Add https://github.com/mreq/slick-lightbox/issues/51

### ISSUE THREAD

**Issue by jonnymaboy** [cdnjs/cdnjs#11407]
**Library name:** https://github.com/mreq/slick-lightbox/issues/51
**Git repository url:** https://github.com/mreq/slick-lightbox
**npm package name or url** (if there is one): https://github.com/mreq/slick-lightbox
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** http://mreq.github.io/slick-lightbox/
**Wanna say something? Leave message here:** A lightbox wrapper for Ken's amazing slick carousel. Credits go to kenwheeler for doing the hard work.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #11004

**Comment by PeterDaveHello** [comment]
Let's move to #11004
