### ISSUE TITLE
[Request] Add openui5

### ISSUE THREAD

**Issue by Soontao** [cdnjs/cdnjs#11415]
Library name: openui5
Git repository url: https://github.com/SAP/openui5/
License (List them all if it's multiple): Apache
Official homepage: http://openui5.org/index.html

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #9244

**Comment by PeterDaveHello** [comment]
Let's move to #9244
