### ISSUE TITLE
[Request] Add react-immutable-pure-component

### ISSUE THREAD

**Issue by Monar** [cdnjs/cdnjs#11411]
**Library name:** react-immutable-pure-component
**Git repository url:** https://github.com/Monar/react-immutable-pure-component
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-immutable-pure-component
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
@Monar I'll be working on this issue. Before I do, can you please let me know if this library can be used directly in the browser by a developer? Because [react-immutable-pure-component.js](https://unpkg.com/react-immutable-pure-component@1.0.0/lib/react-immutable-pure-component.js) doesn't look like that.

**Comment by Monar** [comment]
Yes, its working directly in the browser please check the (example)[https://monar.github.io/react-immutable-pure-component/] here is [index.html code](https://github.com/Monar/react-immutable-pure-component/blob/master/index.html#L15).

Library is created with (rollup)[https://github.com/rollup/rollup] as (UMD)[https://github.com/umdjs/umd].

**Comment by dakshshah96** [comment]
@Monar Great, I understand now! Thanks 😄
