### ISSUE TITLE
[Request] Add jQuery-QueryBuilder

### ISSUE THREAD

**Issue by leroy0211** [cdnjs/cdnjs#11426]
**Library name:** jQuery-QueryBuilder
**Git repository url:** https://github.com/mistic100/jQuery-QueryBuilder
**npm package name or url** (if there is one): jQuery-QueryBuilder
**License (List them all if it's multiple):** MIT
**Official homepage:** http://querybuilder.js.org/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by htkcodes** [comment]
Any updates???
