### ISSUE TITLE
[Request] Add regularjs

### ISSUE THREAD

**Issue by satlxq** [cdnjs/cdnjs#11425]
**Library name:** regularjs
**Git repository url:** https://github.com/regularjs/regular
**npm package name or url** (if there is one): https://www.npmjs.com/package/regularjs
**License (List them all if it's multiple):** MIT
**Official homepage:** https://regularjs.github.io/
**Wanna say something? Leave message here:** regularjs is a mvvm framework like vuejs

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
