### ISSUE TITLE
[Request] Add strapdownjs

### ISSUE THREAD

**Issue by iamCristYe** [cdnjs/cdnjs#11434]
**Library name:** strapdownjs
**Git repository url:** https://github.com/arturadib/strapdown
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://strapdownjs.com/
**Wanna say something? Leave message here:** I really like this MD to HTML converter since it can maintain the md structure in the html file and provides the exclusive responsive HTML support.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
Duplicate with #10249

**Comment by PeterDaveHello** [comment]
Okay let's move to #10249.
