### ISSUE TITLE
[Request] Add xlsx-populate

### ISSUE THREAD

**Issue by saeedbaba** [cdnjs/cdnjs#11431]
**Library name:** xlsx-populate
**Git repository url:https://github.com/dtjohnson/xlsx-populate
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
@saeedbaba this library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our README.md. Would you mind to open an issue again when the library has more popularity?

**Comment by extend1994** [comment]
Close the issue because of insufficient popularity and no response in 7 days. cc @PeterDaveHello

**Comment by extend1994** [comment]
Close the issue because of insufficient popularity and no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host this using a lower priority (like intern practice)
