### ISSUE TITLE
[Request] Add videojs-hotkeys

### ISSUE THREAD

**Issue by timcosta** [cdnjs/cdnjs#11430]
**Library name:** videojs-hotkeys
**Git repository url:** https://github.com/ctd1500/videojs-hotkeys
**npm package name or url** (if there is one): https://www.npmjs.com/package/videojs-hotkeys
**License (List them all if it's multiple):** Apache-2.0
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
Duplicate with #9818

**Comment by PeterDaveHello** [comment]
Let's move to #9818
