### ISSUE TITLE
[Request] Add webpack-cesium

### ISSUE THREAD

**Issue by TJKoury** [cdnjs/cdnjs#11442]
**Library name:** webpack-cesium
**Git repository url:** https://github.com/DigitalArsenal/webpack-cesium.git
**npm package name or url** (if there is one):  https://www.npmjs.com/package/webpack-cesium
**License (List them all if it's multiple):** ISC
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@TJKoury 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by TJKoury** [comment]
@sufuf3 it is a single .is file hosting of a very popular library (cesiumjs.org).  I packaged it specifically for CDN hosting, since the production version requires hosting of several webworkers, images, json documents, and other external files.

**Comment by TJKoury** [comment]
https://www.npmjs.com/package/cesium

**Comment by TJKoury** [comment]
https://groups.google.com/forum/m/#!topic/cesium-dev/szGWBVpQlTM

**Comment by sufuf3** [comment]
@TJKoury Thank you. It looks cool.

**Comment by TJKoury** [comment]
I aim to please.  Let me know if you have any other questions, and no hard feelings if you don't want to host it.

**Comment by PeterDaveHello** [comment]
@TJKoury would you like to send a pull request to add this library on cdnjs?

**Comment by TJKoury** [comment]
Done (as far as I can tell).  Let me know if I got it right.

**Comment by TJKoury** [comment]
@PeterDaveHello We would like to unpublish this library and re-publish with a different name.  We have a new version that works with every es6-compatible build system, not just Webpack.

How best to do this?

**Comment by MattIPv4** [comment]
@TJKoury please create a new issue if you want to add a new library.

**Comment by MattIPv4** [comment]
webpack-cesium is available on cdnjs: https://cdnjs.com/libraries/webpack-cesium
Closing.
