### ISSUE TITLE
[Request] Add tabulator@3.1.1

### ISSUE THREAD

**Issue by freebeer42** [cdnjs/cdnjs#11446]
**Library name:** tabulator
**Git repository url:** https://github.com/olifolkerd/tabulator
**npm package name or url** (if there is one): https://www.npmjs.com/package/jquery.tabulator
**License (List them all if it's multiple):** MIT https://github.com/olifolkerd/tabulator/blob/master/LICENSE
**Official homepage:** http://olifolkerd.github.io/tabulator/
**Wanna say something? Leave message here:** It appears that PeterBot added the latest 2.x version, but 3.x versions have not shown up. Is there something I can do to help the bot do its thing, or would creating a pull request be faster?

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@freebeer42 thanks for your report, looks like they changed its file/directory structure, I'll fix it now.

**Comment by freebeer42** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@freebeer42 thank you, too.
