### ISSUE TITLE
[Request] Add octokat.js

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#11440]
**Library name:** octokat.js
**Git repository url:** https://github.com/philschatz/octokat.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/octokat
**License (List them all if it's multiple):** [MIT](https://github.com/philschatz/octokat.js/blob/master/LICENSE.md)
**Official homepage:** https://github.com/philschatz/octokat.js

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
