### ISSUE TITLE
[Request] Add selectnav.js

### ISSUE THREAD

**Issue by tooncitydl** [cdnjs/cdnjs#11454]
**Library name:** selectnav.js
**Git repository url:** https://github.com/lukaszfiszer/selectnav.js
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** [MIT](https://github.com/lukaszfiszer/selectnav.js/blob/master/LICENCE)
**Official homepage:** http://lukaszfiszer.github.com/selectnav.js/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
