### ISSUE TITLE
[Request] [Author] Add Tempus Dominus for Bootstrap3 and Bootstrap4

### ISSUE THREAD

**Issue by Eonasdan** [cdnjs/cdnjs#11453]
Library name: Tempus Dominus
Git repository url: https://github.com/tempusdominus/bootstrap-3 and https://github.com/tempusdominus/bootstrap-4
npm package name or url (if there is one): https://www.npmjs.com/package/tempusdominus-bootstrap-3 and https://www.npmjs.com/package/tempusdominus-bootstrap-4
License (List them all if it's multiple): MIT
Official homepage: GitHub Repo
Wanna say something? Leave message here:
"Tempus Dominus" is the successor to my [popular datepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) (which is already here).

I realize that this new repo doesn't conform to your repo star/download rules yet, however the goal will be to move people away from the existing picker to this new version.

I'm happy either way, if you can accept the reference of the previous version cool; however if the new repo needs to grow a bit more I understand.

**Comment by extend1994** [comment]
@Eonasdan Thank you for your request!
@PeterDaveHello Do we need to wait for the enough popularity?

**Comment by PeterDaveHello** [comment]
Yeah the popularity seem to fail the requirement, but if @Eonasdan would like to send us a pull request, I'll like to review and merge it :)

**Comment by Eonasdan** [comment]
@PeterDaveHello @extend1994 having a bit of trouble with the pull request. It sounded like from the docs that I could just provide a package.json file bit the build bot is complaining. 'little help?

**Comment by extend1994** [comment]
@Eonasdan That's right, I will help you to pass the CI test in PR page. Let's discuss there :smiley:
