### ISSUE TITLE
Enable Argo

### ISSUE THREAD

**Issue by ricardopolo** [cdnjs/cdnjs#11452]
Please enable Argo Cludflare in the CDN. We need the faster speed  always in CDNJS, so lets use this new Technology! 😄

**Comment by sufuf3** [comment]
(Argo)[https://www.cloudflare.com/argo/] is awesome.
@PeterDaveHello could you take a look this?
I don't know how to deal with this.
Thank you.

**Comment by ricardopolo** [comment]
As far as I know is simply a setting in the CF interface. For us it was so simple. It won involve developer work by your side.

**Comment by PeterDaveHello** [comment]
@ryankirkman is the only one has permission on cdnjs.com to enable it, and @terinjokes is the only one has permission on cdnjs.cloudflare.com

**Comment by ryankirkman** [comment]
Let me take a look for cdnjs.com

**Comment by ricardopolo** [comment]
@terinjokes @ryankirkman can you check this?

I promise you it will only take 3 minutes, its literally a checkbox in the CloudFlare interface.

**Comment by PeterDaveHello** [comment]
Hi @ricardopolo, thanks for the suggestion, I know that it looks great, but not sure if you noticed it also generate additional costs, please give us more time to make the decision, thanks!

**Comment by ryankirkman** [comment]
Hi everyone, Argo costs additional money on top of the sponsorship we currently receive from Cloudflare: https://support.cloudflare.com/hc/en-us/articles/115000224192

I'll ask Cloudflare if they are willing to provide sponsorship for this feature.

**Comment by ricardopolo** [comment]
Yes it costs per GB.
I hope CloudFlare approves its use and conver the cost. It really improves the speed of the CDN. 😄

**Comment by ryankirkman** [comment]
To clarify, we can enable Argo for cdnjs.com.

It would be a separate configuration on Cloudflare's end to enable Argo for the cdnjs.cloudlfare.com domain.

**Comment by ricardopolo** [comment]
@ryankirkman @PeterDaveHello have you talk with the Cloudflare people to enable this? It would improve a lot the cdn

**Comment by PeterDaveHello** [comment]
Sorry, I'm not in charge in this part, I'll ping Ryan again to see if there is any updates.

**Comment by PeterDaveHello** [comment]
@thomasdavis can you also take a look please? Thanks.

**Comment by MattIPv4** [comment]
@ryankirkman Did CF ever respond to you regarding an additional sponsorship for enabling Argo on all of cdnjs?

**Comment by MattIPv4** [comment]
Update on this: Cloudflare are looking into this internally. Will post further updates here as I get them.

**Comment by MattIPv4** [comment]
@ricardopolo @sufuf3 @PeterDaveHello @ryankirkman You will be pleased to know that Argo is enabled for cdnjs.cloudflare.com 🎉

**Comment by ricardopolo** [comment]
💪💪😁😁😁

**Comment by PeterDaveHello** [comment]
@MattIPv4 can we also do that on cdnjs.com?

**Comment by MattIPv4** [comment]
@PeterDaveHello Ah sure, had missed that. Will chase them for it. :)

**Comment by MattIPv4** [comment]
@PeterDaveHello Having just looked, Argo is listed as an active subscription on cdnjs.com so I would assume it is enabled :)

**Comment by PeterDaveHello** [comment]
@ryankirkman can you turn on Argo permission for us on the panel?
