### ISSUE TITLE
[Request] Add kevinchappell/formBuilder

### ISSUE THREAD

**Issue by foaadnami** [cdnjs/cdnjs#11468]
**Library name:** formBuilder
**Git repository url:**  
Two distributables

https://github.com/kevinchappell/formBuilder/blob/master/dist/form-builder.min.js
https://github.com/kevinchappell/formBuilder/blob/master/dist/form-render.min.js

**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:**  https://github.com/kevinchappell/formBuilder
**Wanna say something? Leave message here:** 
Thanks!

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Note: 
If someone wants to add this library via sending a pull request, need to rename the library. Because the `formbuilder` is already in CDNJS https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/formbuilder
