### ISSUE TITLE
[Request] Add hunt

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11473]
**Library name:** hunt
**Git repository url:** https://github.com/jeremenichelli/hunt
**npm package name or url**: huntjs
**License:** MIT 
**Official homepage:** https://jeremenichelli.github.io/hunt

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by irhen** [comment]
Hello there!
I'm sorry for asking, but I didn't quite catch what exactly needs to be done. There're no open issues in the repository. Could you maybe specify the problem/request?

**Comment by PeterDaveHello** [comment]
Hi @irhen, this is the issue, which is asking to add a new library called "hunt" on cdnjs.

cc @cdnjs/intern3 @cdnjs/active-contributor

**Comment by irhen** [comment]
Oh, I see. I'd like to do something like that one day, but not right now. Thank you for your quick response!

**Comment by dakshshah96** [comment]
@irhen Do let any one of us if you'd like to work on this 😄

**Comment by Akshitaag** [comment]
Hello
Can i work on this issue.?I am a beginner

**Comment by PeterDaveHello** [comment]
@Akshitaag sure thing!

**Comment by Akshitaag** [comment]
@PeterDaveHello i have made a pull request..i might have committed errors being a first timer.
Please review.
Thanks

**Comment by PeterDaveHello** [comment]
@Akshitaag no worries

**Comment by Akshitaag** [comment]
@PeterDaveHello would you mind helping me with errors?
https://ci.cdnjs.com/cdnjs/cdnjs/10723
How can i resolve this error?
huntjs is not a valid cdnjs package.json

**Comment by PeterDaveHello** [comment]
@Akshitaag see the PR page, please should fill the form for the information :)
