### ISSUE TITLE
[Request] Add ng-image-gallery

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11475]
**Library name:** ng-image-gallery
**Git repository url:** https://github.com/thatisuday/ng-image-gallery
**npm package name or url**: ng-image-gallery
**License:** Apache-2.0
**Note:** Please note that **gz** files should be excluded in commits and auto-update config

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by dipikaisdbest** [comment]
Hi @PeterDaveHello Could I grab this one. I am a first time contributor and would need support in the process.

**Comment by PeterDaveHello** [comment]
@dipikaisdbest of course! I'll let @extend1994 and @sufuf3 help you!

**Comment by dipikaisdbest** [comment]
@PeterDaveHello @extend1994 @sufuf3 
Thanks. Taking this up and starting.

**Comment by PeterDaveHello** [comment]
@dipikaisdbest nice, feel free to let us know that where can we help. The doc may be a little bit long, take your time, no rush.

**Comment by PeterDaveHello** [comment]
@dipikaisdbest anything we can help here? Not sure how's your progress going :)

**Comment by dipikaisdbest** [comment]
hi @PeterDaveHello  I am not able to make a concrete progress on this as yet. Might need someone's help.

**Comment by sufuf3** [comment]
@dipikaisdbest How can I help you?
Could you descript what situation did you meet?

Here are the tips, hope can help you.

- [**Adding a new library via a single package.json**](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)
  1. Creating a `package.json` under `ajax/libs/<LIBRARY_NAME>`
  2. Edit the `package.json`.
      - Required fields: `name`, `description`, `filename`, `license`, `repository`, `author`, `keywords`, auto-update config
      - Non-Required fields (If there is no field of the upstream): `homepage`
  3. Save the file and send a PR with the commit message as the followings example with git auto-update (if you use npm auto-update, please change from git to npm):
  This will be useful to us to maintain the git log and trace the history.
```
Add <LIBRARY_NAME> w/ git auto-update via single package.json

close <#THIS_ISSUE_NUMBER>, cc <@AUTHOR>
```

- How to setup auto-update config
The auto-update config can automatically add libraries to the latest version easily. [Here](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md) is the document which can help you to know how to setup auto-update config. 
BTW, in `files` field, we'd like to let it be flexible but if there are some files not necessary to host, we will use some pattern to match and exclude them. There are many example configurations in [document](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md), hope this will help you to understand. 

Thanks.

**Comment by matthewjwhitney** [comment]
Is this still open? It doesn't seem that they ever finished it. can I take this one? Thanks.

**Comment by PeterDaveHello** [comment]
@matthewjwhitney sure you can :+1

**Comment by NYCJacob** [comment]
so looks like this is still open,  if no one is working on it I'll do it.  I did one last year.

**Comment by pawgrmr** [comment]
Hi there, is this issue still open? If so can I take this one?
