### ISSUE TITLE
[Request] Add stringbuffer.js

### ISSUE THREAD

**Issue by AndersonLorena** [cdnjs/cdnjs#11492]
**Library name:** stringbuffer.js
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@AndersonLorena Is there any detail information about `stringbuffer.js`?
Such as Git repository url.
Thank you.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
