### ISSUE TITLE
[Request] Add material-design-icons

### ISSUE THREAD

**Issue by tallesairan** [cdnjs/cdnjs#11498]
**Library name:** boostrap-material-design-icons
**Git repository url:** https://github.com/mervick/material-design-icons
**npm package name or url** (if there is one): https://www.npmjs.com/package/bootstrap-material-design-icons
**License (List them all if it's multiple):** MIT License 
**Official homepage:** http://mervick.github.io/material-design-icons/
**Wanna say something? Leave message here:** Material design icons are the official icon set from Google that are designed under the material design guidelines.

In the official package the icons uses a typographic feature called ligatures, which allows rendering of an icon glyph simply by using its textual name.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by tallesairan** [comment]
@mervick

**Comment by PeterDaveHello** [comment]
@tallesairan @mervick would you guys like to send a pull request to add it on @cdnjs?
