### ISSUE TITLE
[Request] Add semver

### ISSUE THREAD

**Issue by DanielSWolf** [cdnjs/cdnjs#11494]
**Library name:** semver
**Git repository url:** https://github.com/npm/node-semver
**npm package name or url (if there is one):** [semver](https://www.npmjs.com/package/semver)
**License (List them all if it's multiple):** [ISC License](https://github.com/npm/node-semver/blob/master/LICENSE)
**Official homepage:**
**Wanna say something? Leave message here:**

=====================

**Comment by sufuf3** [comment]
@DanielSWolf Could the `semver.js` file can use in web front-end with HTML tag?
Or what files should CDNJS host?

Could you tell me how to use this library in web front-end?
Thank you.

**Comment by DanielSWolf** [comment]
@sufuf3 Yes, `semver.js` should work fine in a browser -- apart from the `module.exports` syntax, of course. It defines a number of helpful functions for working with version strings.

**Comment by sufuf3** [comment]
So can I use ` <script type="text/javascript" src="semver.js"></script>` in HTML file?
Because I saw it use in command line via the npm README (https://www.npmjs.com/package/semver#usage). 

Sorry that I am not familiar with JavaScript.
cc @extend1994, @dakshshah96 , @PeterDaveHello

**Comment by DanielSWolf** [comment]
I'm sorry @sufuf3, I misunderstood your question. No, you cannot reference `semver.js` from a `<script>` tag and expect it to work. You'd have to make the following modifications first:

You have to modify `semver.js` like this:

```js
var semVer = (function() {
  var exports = {};
  var module = { exports: exports };

  // At this point, insert the entire original file semver.js.

  return exports;
})();
```

After that, you should be able to reference the file from a `<script>` tag, and access the functions from the `semVer` variable.

I'm writing these instructions from memory, so I can't guarantee that they're 100% correct.

**Comment by sufuf3** [comment]
@PeterDaveHello Could you help take a look?
I think CDNJS couldn't host this library because it can't use `<script>` tag.
Thank you.

**Comment by dakshshah96** [comment]
Hey @DanielSWolf, there wouldn't be any point in hosting this library on a CDN since it cannot be used in production directly.

I'm closing this issue right now. Let me know if you need to know anything else :)

cc @sufuf3
