### ISSUE TITLE
jQuery UI corrupt minified JS file

### ISSUE THREAD

**Issue by RinkAttendant6** [cdnjs/cdnjs#11495]
The file at `https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js` appears to be different than the official one at `https://code.jquery.com/ui/1.12.1/jquery-ui.min.js` (and Google CDN `https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js`).

This is evident by the difference in SRI hashes:

cdnjs:
```html
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"
  integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM="
  crossorigin="anonymous"></script>
```

jQuery CDN:
```html
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
  crossorigin="anonymous"></script>
```

Note that the unminified files appear to be correct, as the hashes match.

**Comment by PeterDaveHello** [comment]
I'm not sure how do they grab the files, we pull jquery-ui from here:
https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

The checksums should prove that it's the official one:

sha384
```
3ed4d1aaf0e1c9c20153ac75c3022a9db0e8f1a75e58858fdc01e69ebbdc71a7e8df913ba08bd6ec73d79f66229af5ae  jquery-ui.min.js
```

sha256
```
28ce75d953678c4942df47a11707a15e3c756021cf89090e3e6aa7ad6b6971c3  jquery-ui.min.js
```

sha1
```
78489e580adaef931e6e5b131dab556c397e4a1a  jquery-ui.min.js
```

md5
```
c15b1008dec3c8967ea657a7bb4baaec  jquery-ui.min.js
```

**Comment by PeterDaveHello** [comment]
Dear Jquery-ui masters: @scottgonzalez @jzaefferer

Would you guys like to help us known more about what's the proper way to fetch jquery-ui and how jquery CDN, Google CDN did it?

Many thanks!

**Comment by RinkAttendant6** [comment]
The files differ by one byte, with the cdnjs one containing an extra byte, to be exact it's a backslash character inside a regex on line 7.

**Comment by PeterDaveHello** [comment]
@RinkAttendant6 thanks! Would this be fixed in future so that we can share the same checksum?

**Comment by scottgonzalez** [comment]
There are many ways to fetch jQuery UI. The jQuery CDN and Google CDN are two of them, both of them receive the file directly from the development team. The one byte difference you see comes from different build systems using different versions of the same minifier. There's no easy way for us to ensure this doesn't happen without a lot of changes to our download builder.

**Comment by PeterDaveHello** [comment]
@scottgonzalez is it possible to make sure they come from the same build so that we can share the same checksum?

**Comment by ajsb85** [comment]
@PeterDaveHello 👌

**Comment by ajsb85** [comment]
@PeterDaveHello Le dije que tu ere recien graduado

**Comment by PeterDaveHello** [comment]
@ajsb85 English please.

**Comment by scottgonzalez** [comment]
To be honest, I'm not interested in prioritizing this because I don't think this is how people should be getting jQuery UI. If cdnjs wants to have the same checksum, they can just get the file from the jQuery CDN instead of jqueryui.com.

**Comment by PeterDaveHello** [comment]
Anyway, the files are good. There is no really integrity issue here. Thanks.
