### ISSUE TITLE
[Request] Add gridder

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11508]
**Library name:** gridder
**Git repository url:** https://github.com/oriongunning/gridder
**npm package name or url** (if there is one): 
**License:** CC-BY-3.0
**Official homepage:** http://oriongunning.github.io/gridder/ (It's http not https)

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by wlisrausr** [comment]
I would love to take this one. What should I add to .git/info/sparse-checkout file to work on this issue? @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@wlisrausr just add the path for the library that you are going to add. cc @sufuf3

**Comment by wlisrausr** [comment]
Could you please assist me on this step by step @sufuf3? I saw a long of process in another PR and it looks scary 😄

**Comment by sufuf3** [comment]
@wlisrausr welcome.
Here are the sparse-checkout steps which run on Unix-like OS or MacOS, if you still feel confused here is the [tutorial](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md)
1. `mkdir ~/cdnjs`  --> create a folder named cdnjs
2. `cd ~/cdnjs`  --> change dir to cdnjs
3. `git init`  --> init git repo
4. `git config core.sparseCheckout true`  --> turn on sparseCheckout
5. `wget https://github.com/cdnjs/cdnjs/raw/master/tools/sparse-checkout.template -O ~/cdnjs/.git/info/sparse-checkout`  --> modify the sparse-checkout file
6. `echo '/ajax/libs/jquery/*' >> ~/cdnjs/.git/info/sparse-checkout` --> insert the path which I like to watch when I checkout
7. `echo '/ajax/libs/gridder/*' >> .git/info/sparse-checkout` --> insert the path 
8. `git remote add origin git://github.com/cdnjs/cdnjs.git`  --> add remote
9. `git pull origin master --depth 10` . --> pull master
10. `npm install`  
11. `npm test`

Oh, I've written a shell script, maybe you could refer to what cmd I used: https://github.com/sufuf3/cdnjs_setenv/blob/master/cdnjs_env.sh

Thank you.
If you have any question, please let me know, I'll do my best to help you send the valid pull request. 😃

**Comment by wlisrausr** [comment]
Whoaah, thanks a lot for these complete steps! After all those steps, I can directly work to add this gridder library right? @sufuf3

**Comment by sufuf3** [comment]
Checkout the new branch and create the `~/cdnjs/ajax/libs/gridder`, then you can directly work to add this gridder library 👍  YES!
this is the adding library tutorial: https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson
😃

**Comment by wlisrausr** [comment]
Sorry @sufuf3, should I change the remote origin in the 8 step into my fork cdnjs repo? Because I can't push directly into cdnjs repository

**Comment by sufuf3** [comment]
@wlisrausr You have to add another remote which is your cdnjs fork. And push the branch into your fork repo.
Here is a tutorial you can refer to https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
Thank you :+1: :)

**Comment by wlisrausr** [comment]
Got it. Just a little bit confuse because usually I just fork the repo, clone it, and directly work on it. I'll make a PR after this. Thanks @sufuf3 😃

**Comment by sufuf3** [comment]
And please create a pull request :)
On this page https://github.com/cdnjs/cdnjs you will see the green button, then just click the button. fill in some info. then you will send the PR successfully.
😃

**Comment by wlisrausr** [comment]
Done. Thanks a lot for your direction @sufuf3. Just let me know if I need to add or change something in my PR 👍
