### ISSUE TITLE
[Request] Add fontIconPicker

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11514]
**Library name:** fontIconPicker
**Git repository url:** https://github.com/micc83/fontIconPicker
**License:** MIT
**Official homepage:** https://codeb.it/fonticonpicker/

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by khursani8** [comment]
Hi @PeterDaveHello  I would like to help adding this library but I got some problem.
After sparseCheckout I don't know what to do next.
Can you guide me one this?

**Comment by PeterDaveHello** [comment]
Hi @khursani8, it's good to see you finished the sparseCheckout process, the brief step is to create a branch and the directory structure for the library, here, for example, the directory should be `ajax/libs/fontIconPicker`, and then you can start to add its `package.json` and the files of the latest version, make commit, and push the branch, create a pull request! Would this help you or you'd like to have more details?

**Comment by VijayGomathi** [comment]
Hi, @PeterDaveHello  I have created a branch locally and did the necessary changes for this request, but I cannot push the branch to remote. I am given the following error message 
"remote: Permission to cdnjs/cdnjs.git denied to VijayGomathi."
What should I do now?
I am a newbie to github and contribution to projects. Please guide me through the process of creating a pull request.
![error_message](https://user-images.githubusercontent.com/31568585/30868960-991475ee-a2fd-11e7-979c-f4059de673ea.PNG)

**Comment by sufuf3** [comment]
@VijayGomathi May I ask some information?
What is your `origin` remote link?
I think you should fork this repo and push to your fork link.
![2017-09-27 12 16 51](https://user-images.githubusercontent.com/8349587/30871417-7682f7cc-a2ac-11e7-806c-ec5e59d7e3db.png)

Then, you can see the Pull Request button in CDNJS's repo.

Thanks for your joining.

**Comment by VijayGomathi** [comment]
@sufuf3 Thanks you. I did not fork. I was using "https://github.com/cdnjs/cdnjs.git"

**Comment by PeterDaveHello** [comment]
@VijayGomathi you'll need to fork it to send a valid pull request, thanks.
