### ISSUE TITLE
[Request] Add videojs-flash.js

### ISSUE THREAD

**Issue by GwynethLlewelyn** [cdnjs/cdnjs#11517]
**Library name:** videojs-flash.js
**Git repository url:** https://github.com/videojs/videojs-flash
**npm package name or url** (if there is one): https://www.npmjs.com/package/videojs-flash
**License (List them all if it's multiple):** Apache License, Version 2.0
**Official homepage:** 
**Wanna say something? Leave message here:** 
Since Flash was dropped from Video.js >= 6.0.0, the videojs-flash project is providing backwards compatibility with Flash (useful for using Video.js with Red5 servers, for instance); several Video.js plugins are already being hosted by cdnjs.com but not this one!

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @GwynethLlewelyn 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you to open the issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by GwynethLlewelyn** [comment]
Oh, good point! :) Sorry about that, it's just that I saw much more obscure Video.js plugins being served by cdnjs, while this one (videojs-flash) was actually part of the original Video.js before version 6.0.0, when it was split from the original. So now we're stuck with having just part of the complete code being served by cdnjs, while the rest of the code was made into a _separate_ plugin... which is _not_ on cdnjs! Complicated. But I suppose that enough people manage to survive without Flash support these days so the decision to dump part of the code made sense...

**Comment by extend1994** [comment]
I found it has enough popularity on npm! Sorry for not not noticing that! Thank you for quick response and library request :smile:

**Comment by GwynethLlewelyn** [comment]
Oh well done @extend1994 ! I forgot to check it on npm as well. And yes — this particular Video.js plugin is mostly available through npm/bower; there are no distributable files on GitHub, at least for now, meaning that one has to compile everything on one's own... which in turn means that most people will be using npm/bower to get it. No wonder that it isn't that popular on GitHub itself! Thanks for taking a look at it again 👍

**Comment by extend1994** [comment]
@GwynethLlewelyn Thanks a lot for a great of information :smile:
