### ISSUE TITLE
[Request] Add urlive

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11515]
**Library name:** urlive
**Git repository url:** https://github.com/markserbol/urlive
**Licens:** MIT
**Official homepage:** http://markserbol.com/urlive/

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by nbkhope** [comment]
I will give this a try.

**Comment by PeterDaveHello** [comment]
@nbkhope :+1:

**Comment by nbkhope** [comment]
@PeterDaveHello according the guides, I have can run the tests using `npm test`, except that because I don't have all the packages locally, many of them will fail. Is there a way to run a specific test for the new package to be added?

**Comment by PeterDaveHello** [comment]
@nbkhope npm test won't test not existing libraries, so no worries on this part.

**Comment by nbkhope** [comment]
@PeterDaveHello Oh, okay. So the problem was that there was a directory for the libraries, including a `package.json`, but no subdirectories inside. I didn't pull up the whole Git repository, so that might have been affected it.

**Comment by PeterDaveHello** [comment]
Not sure if I understand your problem, any details?

**Comment by PeterDaveHello** [comment]
@sufuf3 please help @nbkhope

**Comment by nbkhope** [comment]
@PeterDaveHello I had many directories under `ajax/libs/` but they only contained a `package.json`. Because of that, when I ran `npm test`, it tried looking for files within those library directories, but could not find them. So the `npm test` failed. After I removed all the directories (except the one I'm working on) from `ajax/libs`, the problem was gone.

**Comment by PeterDaveHello** [comment]
@nbkhope nice! The problem may be caused by wrong sparseCheckout config I think

**Comment by nbkhope** [comment]
@PeterDaveHello I followed the guide, but it always pulls 8G and many directories inside ajax/libs. :octocat:
