### ISSUE TITLE
[Request] Add angular-paging

### ISSUE THREAD

**Issue by devshark** [cdnjs/cdnjs#11519]
**Library name:** Angular-Paging
**Git repository url:** https://github.com/brantwills/Angular-Paging
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT License
**Official homepage:** http://brantwills.github.io/Angular-Paging/
**Wanna say something? Leave message here:** 
This is not my project. Just requesting it because this looks helpful. 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
