### ISSUE TITLE
[Request] Add jquery.flot.tickrotor.js

### ISSUE THREAD

**Issue by irfangg** [cdnjs/cdnjs#11518]
**Library name:** jquery.flot.tickrotor.js
**Git repository url:** https://raw.githubusercontent.com/markrcote/flot-tickrotor/master/jquery.flot.tickrotor.js
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** https://github.com/flot/flot
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @irfangg 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you to open the issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by extend1994** [comment]
Close this library request issue due to no response over 7 days and insufficient popularity. cc @PeterDaveHello

**Comment by extend1994** [comment]
Close this library request issue due to no response over 7 days and insufficient popularity. cc @PeterDaveHello
