### ISSUE TITLE
[Request] Add MathBox

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11526]
**Library name:** MathBox
**Git repository url:** 
V1: https://github.com/unconed/MathBox.js
V2: https://gitgud.io/unconed/mathbox or https://github.com/unconed/mathbox
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:**

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
