### ISSUE TITLE
[Request] Add brick

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11524]
**Library name:** brick
**Git repository url:**  https://github.com/mozbrick/brick
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Apache License v2
**Official homepage:** https://mozbrick.github.io/

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello 
I came across this library and I saw that it is based on html files
We are not hosting html files, thus it cannot be hosted?
Am I write?

**Comment by sufuf3** [comment]
We can host *.js or *.css 
eg. https://github.com/mozbrick/brick/tree/1.0.0/dist
https://github.com/mozbrick/brick/blob/2.0.0/dist/brick-tabbar/dist/brick-tabbar.js
What do you think?

**Comment by sashberd** [comment]
@sufuf3 
If you check [here](https://github.com/mozbrick/brick/tree/2.0.0#install) you will see that *.html files are necessary for using this library

**Comment by sufuf3** [comment]
@sashberd Thanks but I think it's still fine.
Because `<link rel="import" href="bower_components/brick/dist/brick.html">` is import this file https://github.com/mozbrick/brick/blob/2.0.0/dist/brick.html
And the code in file also import other file `<link rel="import" href="brick-deck/dist/brick-deck.html">` .
And if we check https://github.com/mozbrick/brick/blob/2.0.0/dist/brick-deck/dist/brick-deck.html#L214, we can see https://github.com/mozbrick/brick/blob/2.0.0/dist/brick-deck/dist/brick-deck.js
And this file we can host.

What do you think?

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 OK
I still doubt about this, but I will create a PR. I suggest to ask author about this

**Comment by sufuf3** [comment]
@sashberd Thank you very much. :)

**Comment by PeterDaveHello** [comment]
@sashberd do you mean this: https://github.com/PeterDaveHello/web-minify-helper/? If so, would you like to open an issue about your OS? :)

**Comment by PeterDaveHello** [comment]
It's fine to host library as @sufuf3 says if the html files are not so necessary, however, the file structure and the html in this library looks a little weird(not sure if I'm wrong), we may need more time to dig about it.

**Comment by sashberd** [comment]
As I  said before the html files here are trigger files, which are loading content into DOM.
The author itself write:
![image](https://user-images.githubusercontent.com/11975561/31858915-fd2503a6-b70b-11e7-9694-bd2c61174ab0.png)
You have to host also html files. If you are hosting only JS it is useless for this lib.
I will ask the author opinion about this issue

**Comment by PeterDaveHello** [comment]
Thanks @sashberd, but I think the users can write their own triggers? It'll be good to ask the author 👍

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, we don't host html files.
