### ISSUE TITLE
[Request] Add teoria

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11533]
**Library name:** teoria
**Git repository url:** https://github.com/saebekassebil/teoria
**npm package name or url** (if there is one): https://www.npmjs.com/package/teoria
**License (List them all if it's multiple):** MIT
**Official homepage:** https://saebekassebil.github.io/teoria

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
