### ISSUE TITLE
[Request] Add preact-router

### ISSUE THREAD

**Issue by kumarabhishek** [cdnjs/cdnjs#11530]
**Library name:** preact-router
**Git repository url:**  https://github.com/developit/preact-router
**npm package name or url** (if there is one): preact-router
**License (List them all if it's multiple):**  MIT
**Official homepage:** https://github.com/developit/preact-router
**Wanna say something? Leave message here:** Kindly make this available as more and more people will need this as preact is gaining popularity due to its performance.

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nbkhope** [comment]
I'll help out.

**Comment by kumarabhishek** [comment]
Yes. I am looking for final minified and bundled ES5 version which can be directly included via <script> tag. This is help in reducing the bundle size of webapp and increase page load performance as it will code from CDN domain.

**Comment by larshp** [comment]
Hi,
It looks like the NPM module has a `/dist/` folder with a ES and a compiled version:

![image](https://user-images.githubusercontent.com/5888506/29749546-0e386a10-8b2f-11e7-8c6a-2048e30b9ebd.png)

Perhaps it can help moving this issue forward?

**Comment by kumarabhishek** [comment]
Yes, you are right @larshp.
