### ISSUE TITLE
[Request] Add blueimp-gallery.min.css

### ISSUE THREAD

**Issue by aijorgenson** [cdnjs/cdnjs#11538]
**Library name:** blueimp-gallery.min.css
**Git repository url:** https://github.com/blueimp/Gallery
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://blueimp.github.io/Gallery/
**Wanna say something? Leave message here:** The JavaScript file is already on CDN.JS, why isn't the stylesheet?

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@aijorgenson Do you mean you want https://cdnjs.cloudflare.com/ajax/libs/blueimp-gallery/2.25.2/css/blueimp-gallery.min.css ?
[Here](https://cdnjs.com/libraries/blueimp-gallery) is the list of blueimp-gallery.
I check the css files are as same with upstream.

If you have any suggestions, please let me know.
Thank you.

**Comment by aijorgenson** [comment]
Don't know how I missed it, thanks!
