### ISSUE TITLE
[Request] Add choices.js

### ISSUE THREAD

**Issue by jshjohnson** [cdnjs/cdnjs#11540]
**Library name:** choices.js
**Git repository url:** https://github.com/jshjohnson/Choices
**npm package name or url** (if there is one): https://www.npmjs.com/package/choices.js
**License (List them all if it's multiple):** MIT
**Official homepage:** http://joshuajohnson.co.uk/Choices
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicate with #8927
in process #11493
