### ISSUE TITLE
[Request] Add react-materialize

### ISSUE THREAD

**Issue by alextrastero** [cdnjs/cdnjs#11546]
**Library name:** react-materialize
**Git repository url:** https://github.com/react-materialize/react-materialize
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-materialize
**License (List them all if it's multiple):** MIT
**Official homepage:** react-materialize.github.io
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Waiting for https://github.com/react-materialize/react-materialize/issues/315
