### ISSUE TITLE
[Request] Add Fixer.io

### ISSUE THREAD

**Issue by JefMari** [cdnjs/cdnjs#11543]
Library name: Fixer.io
Git repository url: https://github.com/hakanensari/fixer-io
License (List them all if it's multiple): MIT
Official homepage: http://fixer.io/

**Comment by sufuf3** [comment]
@JefMari Thank you for your suggestions.
May I ask that is there any js or css file use in web front-end with HTML tag, like `<script type="text/javascript" src="jsfile"></script>` in HTML file?

Could you tell me how to use this library in web front-end, that CDNJS should host?
Thank you.

**Comment by JefMari** [comment]
Hi @sufuf3 Thank you for your response.
Looks like i mistakenly suggest a wrong repository.

I will now close this issue.

Thank you.
