### ISSUE TITLE
[Request] Add iconv-lite

### ISSUE THREAD

**Issue by nbkhope** [cdnjs/cdnjs#11547]
**Library name**: iconv-lite
**Git repository url**: https://github.com/ashtuchkin/iconv-lite
**npm package name or url (if there is one)**: https://www.npmjs.com/package/iconv-lite
**License (List them all if it's multiple)**: MIT
**Official homepage**: https://github.com/ashtuchkin/iconv-lite

**Comment by sufuf3** [comment]
@nbkhope Thank you for your contribution.
May I ask that is there any js or css file use in web front-end with HTML tag, like `<script type="text/javascript" src="jsfile"></script>` in HTML file?

Could you tell me how to use this library in web front-end, that CDNJS should host?
Thank you.

If there is no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by nbkhope** [comment]
@sufuf3 oh nevermind, it is typically used in the backend with Node.js. I will be closing the issue. Thanks for the heads up.
