### ISSUE TITLE
Missing jquery-validation localization for version 1.16.0

### ISSUE THREAD

**Issue by jenshp** [cdnjs/cdnjs#11550]
As per issue #9491, localization was added for jquery-validation. But in version 1.16.0 it is missing, it is present only in previous versions.

**Comment by sufuf3** [comment]
Note: 
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery-validate/1.16.0
need add https://github.com/jquery-validation/jquery-validation/tree/1.16.0/src/localization
