### ISSUE TITLE
[Request] Add pell

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11552]
**Library name:** pell
**Git repository url:** https://github.com/jaredreich/pell
**npm package name or url** (if there is one): https://www.npmjs.com/package/pell
**License (List them all if it's multiple):** MIT
**Official homepage:** https://jaredreich.com/pell

**Comment by sufuf3** [comment]
This library is amazing, 5 days earn 29..+ star.

**Comment by PeterDaveHello** [comment]
@sufuf3 I think we should work on the older issues first?

**Comment by sufuf3** [comment]
Sorry, I'll pay attention next time.
