### ISSUE TITLE
[Request] Update the repository's url, homepage of notie

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11555]
**Library name**: noite
**Git repository url**: https://github.com/jaredreich/notie
**npm**: https://www.npmjs.com/package/notie
**License** (List them all if it's multiple): MIT
**Official homepage**: https://jaredreich.com/notie

Note:
- **Update the repository's url, homepage, author**
https://github.com/jaredreich/notie/blob/master/package.json#L17
https://github.com/jaredreich/notie/blob/master/package.json#L33
https://github.com/jaredreich/notie/blob/master/package.json#L4
- **Add more keywords**
https://github.com/jaredreich/notie/blob/master/package.json#L20-L27

**Comment by PeterDaveHello** [comment]
@sufuf3 I think you can directly fix it instead of creating an issue as it's very simply enough with high priority?

**Comment by sufuf3** [comment]
OK! sorry~
I will pay attention next time.
