### ISSUE TITLE
[author] Push.js not up to date (v0.0.13 => v1.0.4)

### ISSUE THREAD

**Issue by Nickersoft** [cdnjs/cdnjs#11562]
Hi there! My library Push.js is currently still on version 0.0.13 on CDNJS, but the currently published version is 1.0.4. I noticed the main difference between the releases is Push went from outputting the compiled JavaScript to the root of the repo to a dedicated `bin` directory. Is there anything I should modify in my repo to have CDNJS properly auto-update with correct `bin` files, or should I just go about creating a pull request here? Thanks!

**Comment by PeterDaveHello** [comment]
@Nickersoft should all the files under bin be hosted on CDNJS?

**Comment by Nickersoft** [comment]
Yes. Those are really the only files that matter.

**Comment by PeterDaveHello** [comment]
@Nickersoft should be good now, see the commits above please, as you changed the directory structure but didn't update them on cdnjs, the auto-update coudn't fetch the new versions, I updated auto-update config and added v1.0.2~1.0.4 manually, but for version 1.0.0/1.0.1, I didn't see files that we can use there, you can send a pull request to add them.

**Comment by Nickersoft** [comment]
Yeah, version 1.0.0 and 1.0.1 had some issues with them where the output files weren't being included in the package. How it's set up now should be fine. Thanks for your help!
