### ISSUE TITLE
[Request] Add insignia

### ISSUE THREAD

**Issue by dennobaby** [cdnjs/cdnjs#11572]
**Library name:** insignia
**Git repository url:** https://github.com/bevacqua/insignia
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to no longer be maintained, closing.
