### ISSUE TITLE
[Request] Add canvg.js

### ISSUE THREAD

**Issue by wptd** [cdnjs/cdnjs#11576]
**Library name:** canvg.js
**Git repository url: https://github.com/canvg/canvg/blob/master/canvg.js 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicate with #11575

**Comment by extend1994** [comment]
Move to #11575
