### ISSUE TITLE
Name of foundation differs from Repo/NPM package

### ISSUE THREAD

**Issue by XmlmXmlmX** [cdnjs/cdnjs#11585]
When using the cdnjs api I would expect to be able to use the NPM package name or repository name. This doesn't apply to foundation, because the repo is called `foundation-sites`. The NPM package name is `foundation-sites` ([since v5.5.2 previously `zurb-foundation`](https://github.com/zurb/foundation-sites/commit/2a71b1c2f403d2cfb3a0d62168a79a5733b7a7d9)) as well.

https://api.cdnjs.com/libraries/foundation?output=human -> Does work
https://api.cdnjs.com/libraries/foundation-sites?output=human -> Doesn't work

To change the name would be a massive breaking change, but can't we add something like a alias to use the api in a expected way?

The repo url was updated in 2015-11 from `foundation.git` to `foundation-sites.git`: bc88a0b4c256244b9b996a80e6b4d38c8b967176

**Comment by sufuf3** [comment]
@PeterDaveHello Could you take a look about this?
I think this issue similar to #4627
But I don't know how to deal with this, thank you.

**Comment by PeterDaveHello** [comment]
@XmlmXmlmX yes that's what we should work on, your pull requests would be very welcome 😄
Let's move the discussion here: #8904 , thanks.
