### ISSUE TITLE
[Request] Add gzip-js

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11582]
**Library name:** gzip-js
**Git repository url:** https://github.com/beatgammit/gzip-js
**License (List them all if it's multiple):** MIT
**npm package name or url** (if there is one): https://www.npmjs.com/package/gzip-js

**Comment by extend1994** [comment]
@sufuf3 Please help confirm if npm source exists when you add the tag, thanks. Now I add it.
