### ISSUE TITLE
[Request][Author] Add params-url

### ISSUE THREAD

**Issue by bifot** [cdnjs/cdnjs#11580]
**Library name:** params-url
**Git repository url:** https://github.com/bifot/params-url
**npm package name or url** (if there is one): https://www.npmjs.com/package/params-url/
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/bifot/params-url
**Wanna say something? Leave message here:** YO

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Memo: 
493 downloads in the last month from npm

**Comment by sashberd** [comment]
Hi @bifot 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
