### ISSUE TITLE
[Request][Author] Add web-atoms

### ISSUE THREAD

**Issue by neurospeech** [cdnjs/cdnjs#11589]
**Library name:** web-atoms
**Git repository url:** https://github.com/neurospeech/web-atoms.js
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://http://web-atoms.neurospeech.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @neurospeech 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: 
Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want!

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@neurospeech if you'd like to send a pull request to add this, we can help you do that. Let me know would it help or not, thanks.

**Comment by neurospeech** [comment]
@PeterDaveHello hi, I don't understand what I am supposed to do, the issue was closed by @sufuf3.

**Comment by PeterDaveHello** [comment]
@neurospeech would you like to send a pull request to add your library on CDNJS?

**Comment by neurospeech** [comment]
@PeterDaveHello Yes, let me know what I can do.

**Comment by PeterDaveHello** [comment]
Maybe the instructions for beginner would work for you, take a look at https://github.com/cdnjs/cdnjs/issues/11514 for example?

**Comment by neurospeech** [comment]
@PeterDaveHello No problem, I no longer wish to be added in cdnjs, I feel idea of only promoting famous and rich is not really open source and nice. I have decided to go with jsdelivr.
