### ISSUE TITLE
[Request][Author] Add SearchlightJS

### ISSUE THREAD

**Issue by faroukcharkas** [cdnjs/cdnjs#11581]
**Library name:** SearchlightJS
**Git repository url:** https://github.com/faroukcharkas/searchlightjs
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.npmjs.com/package/searchlightjs?notice=8Y_2MdgGbiS4U62YLbJJOIKJLZ-u_9mVC_SQOiki
**Wanna say something? Leave message here:** Thanks in advance...

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since
https://guides.github.com/features/mastering-markdown/ there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @faroukcharkas 
 The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: 
Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want!

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@faroukcharkas  if you'd like to send a pull request to add this, we can help you do that. Let me know would it help or not, thanks.
