### ISSUE TITLE
[Request][author] Update the auto-update config of tween.js

### ISSUE THREAD

**Issue by mikebolt** [cdnjs/cdnjs#11595]
I want the latest versions of tween.js available on cdnjs. What is the process for adding a new version to cdnjs? Currently the latest version available is 16.7.1, but we now have a 16.10.0 version.

https://cdnjs.com/libraries/tween.js

**Comment by sufuf3** [comment]
@mikebolt thank you very much.

We will update versions ASAP.

Memo: Need to change auto-update from git to npm.

**Comment by mikebolt** [comment]
In the meantime can I update cdnjs by making a GitHub release?

**Comment by sufuf3** [comment]
Yes, you can. Just add a git tag. 
If it does not bother you, could you also make an npm release?
This can let the newest version of your GitHub repo synchronize with npm and CDNJS.

Thank you.
