### ISSUE TITLE
[Request][Author] Add w2b.js

### ISSUE THREAD

**Issue by thuanitdn** [cdnjs/cdnjs#11603]
Library name: w2b.js
Git repository url: https://github.com/thuanitdn/w2b.js
npm package name or url (if there is one): none
License (List them all if it's multiple):
Official homepage: https://thuanitdn.github.io/w2b.js
Wanna say something? Leave message here:

=====================

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @thuanitdn 
The library doesn't have enough popularity(100 stars/watchers on GitHub and 500 downloads/month on npm registry are good examples). You can take a look on our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :)
We suggest you to open the issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by thuanitdn** [comment]
@extend1994 I see, thank you for response.

**Comment by sufuf3** [comment]
Close because the library doesn't have enough popularity. cc @PeterDaveHello
