### ISSUE TITLE
[Request] Add leaflet-search

### ISSUE THREAD

**Issue by saviour123** [cdnjs/cdnjs#11611]
**Library name:** leaflet-search
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@saviour123 any details please?

**Comment by saviour123** [comment]
https://github.com/stefanocudini/leaflet-search
Its a leaflet extension to handle search.

**Comment by PeterDaveHello** [comment]
@saviour123 thanks, we'll take a look.

**Comment by saviour123** [comment]
Awesome.
