### ISSUE TITLE
[Request] Add videojs-contrib-quality-levels

### ISSUE THREAD

**Issue by aigarspl** [cdnjs/cdnjs#11627]
**Library name:** videojs-contrib-quality-levels
**Git repository url:** [https://github.com/videojs/videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels)
**npm package name or url** (if there is one): [videojs-contrib-quality-levels](https://www.npmjs.com/package/videojs-contrib-quality-levels)
**License (List them all if it's multiple):** Apache-2.0. Copyright (c) Brightcove, Inc.
**Official homepage:** [https://github.com/videojs/videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels)
**Wanna say something? Leave message here:** :smiley: 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Stephan972** [comment]
Why does it take so long (1 year as of this writing) to add videojs-contrib-quality-levels to cdnjs ?
