### ISSUE TITLE
[Request][Author] Add nexo.js

### ISSUE THREAD

**Issue by warlock** [cdnjs/cdnjs#11629]
Library name: nexo
Git repository url: https://github.com/warlock/nexo
npm package name or url (if there is one): https://www.npmjs.com/package/nexo
License (List them all if it's multiple): MIT
Official homepage: https://nexo.js.gl
Wanna say something? Thank you :smiley:

=================================

Lightweight Javascript Web Components for Frontend

* Render javascript web components with events
* Reactive model system
* DOM event handler
* Internal Event handler
* Cookies set and get
* Easy for work direcly from browser or build a bundle

**Comment by sufuf3** [comment]
Memo:
986 downloads in the last month from npm
