### ISSUE TITLE
DisplayJS with npm autoupdate has not been updated

### ISSUE THREAD

**Issue by arguiot** [cdnjs/cdnjs#11633]
It's been around 26 hours since I updated DisplayJS on npm (on npm it's `display.js`) and it's still not on the CDNJS repo/servers. Here is the CDNJS page of the package 📦 :

https://cdnjs.com/libraries/DisplayJS/

I hope 🤞 it will be fixed 🛠 soon.

**Comment by PeterDaveHello** [comment]
@arguiot thanks for reporting!

**Comment by PeterDaveHello** [comment]
@arguiot I'll manually add the latest version first and see what the problem is.
