### ISSUE TITLE
[Request] Add laravel-echo

### ISSUE THREAD

**Issue by slashsbin** [cdnjs/cdnjs#11638]
**Library name:** laravel-echo
**Git repository url:** https://github.com/laravel/echo
**npm package name or url** (if there is one): laravel-echo
**License (List them all if it's multiple):** MIT
**Official homepage:** https://laravel.com/docs/master/broadcasting#installing-laravel-echo
**Wanna say something? Leave message here:** for laravel fans <3

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by connectkushal** [comment]
@slashsBin Hi. Please change the link of the **Official homepage:** in your comment to https://laravel.com/docs/master/broadcasting#installing-laravel-echo , so that it always points to the latest version.  :)

**Comment by slashsBin** [comment]
@connectkushal done :)
