### ISSUE TITLE
NPM autoupdate doesn't work properly

### ISSUE THREAD

**Issue by arguiot** [cdnjs/cdnjs#11635]
Hello, 2 days ago, I published a release of [DisplayJS](https://github.com/arguiot/DisplayJS/), and I also released on [NPM](https://npmjs.com/package/display.js). This time, NPM autoupdate didn't work and I had to submit an issue like this, and @PeterDaveHello fixed the problem.

Now, (I mean 7hours ago from the time I post this issue), I published another release (both on Github and npm). And CDNJS didn't update it.

I think I figured out the problem. In the `package.json` file, my version is `v1.0.1`, instead of `1.0.1`, as I normally do and it works fine with everything, except CDNJS.

Could you guys fix this issue, because it's pretty annoying to each time submit an issue 😊.

Next time, I'll release `1.0.2` instead of `v1.0.2` if the problem is not fixed.

**Comment by PeterDaveHello** [comment]
@arguiot The problem is located somewhere else, not the version you named it, I just don't have enough time to dig it out yet, I'll make sure the new version added first, about the version naming, with or without the v prefix are both fine, thanks for reporting again!

**Comment by arguiot** [comment]
Thank you 😊. I hope next time the problem will be fixed.

**Comment by PeterDaveHello** [comment]
@arguiot yeah I hope so, we currently have only one developer here - me ... too many things need to be done.

**Comment by PeterDaveHello** [comment]
The npm auto-update was semi-broken because of some out-side reasons, can't be fully fixed unless we rewrite / replace `tarball-extract` dependency in it, and there may be some other trigger that triggered it, anyway, I did some workaround job first, updates coming now.

**Comment by arguiot** [comment]
Ok, so now, DisplayJS `v1.0.1` should be soon on CDNJS?

**Comment by PeterDaveHello** [comment]
@arguiot yes, as this problem also affected the other libraries, after the workaround fixing, there are about 30 versions need to be added, it'll be done in few mins.

**Comment by arguiot** [comment]
@PeterDaveHello Ok 👌. I'm happy to report a problem that will fix 30 libraries

**Comment by PeterDaveHello** [comment]
@arguiot actually I noticed it, just too busy to fix it immediately :)

**Comment by arguiot** [comment]
@PeterDaveHello Cool 😎, but the important thing is that you're fixing it right now isn't it 😂?

**Comment by PeterDaveHello** [comment]
@arguiot yeah I'm fixing it, but I need to move out many other things 😭

**Comment by arguiot** [comment]
@PeterDaveHello Yeah, I understand 😊. I really hope that more developpers will be added as maintainer to CDNJS.
