### ISSUE TITLE
[Request][Author] Add nanocookie

### ISSUE THREAD

**Issue by camel2243** [cdnjs/cdnjs#11634]
**Library name:** nanocookie
**Git repository url:** https://github.com/camel2243/nanocookie
**npm package name or url** (if there is one): https://www.npmjs.com/package/nanocookie
**License (List them all if it's multiple):** ISC
**Official homepage:** https://github.com/camel2243/nanocookie
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@camel2243 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by camel2243** [comment]
@sufuf3 Sorry, my fault.

I read [README.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for request new library rule.

You can close the issue now.
I will read rule for issue next time, thanks.

**Comment by sufuf3** [comment]
It's OK, thank you for your contribution.
close because the library doesn't have enough notable popularity.
cc @PeterDaveHello
