### ISSUE TITLE
[Request] Add jquery.tabletojson.js

### ISSUE THREAD

**Issue by francorrea18** [cdnjs/cdnjs#11645]
**Library name:**  jquery.tabletojson.js
**Git repository url:** https://github.com/lightswitch05/table-to-json
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** http://www.developerdan.com/table-to-json/
**Wanna say something? Leave message here:** 
http://www.developerdan.com/table-to-json/javascripts/jquery.tabletojson.min.js

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by xerc** [comment]
+1
