### ISSUE TITLE
[Request][Author] Add snc

### ISSUE THREAD

**Issue by warlock** [cdnjs/cdnjs#11652]
Library name: snc
Git repository url: https://github.com/warlock/snc
npm package name or url (if there is one): https://www.npmjs.com/package/snc
License (List them all if it's multiple): MIT
Official homepage: https://snc.js.gl
Wanna say something? Thank you :smiley:

=================================

Javascript Asyncronous Iterators Collection

**Comment by PeterDaveHello** [comment]
@warlock would you like to send us the pull request to add it?

**Comment by warlock** [comment]
I'm going to see the procedure. I did not know he was now on the pull. Thanks Peter Dave.

**Comment by PeterDaveHello** [comment]
@warlock let me know if you need help :)
