### ISSUE TITLE
[Request] Add path-to-regexp

### ISSUE THREAD

**Issue by tlycken** [cdnjs/cdnjs#11651]
**Library name:** path-to-regexp
**Git repository:** https://github.com/pillarjs/path-to-regexp (1500+ ⭐️)
**npm package:** https://www.npmjs.com/package/path-to-regexp (13 million ⬇️ in last month)
**License:** MIT

**Comment by sufuf3** [comment]
@tlycken Thank you for your suggestion.
May I ask that can this library use in front-end?
Like `<script src="path-to-regexp.js"></script>`.

Thank you.

**Comment by tlycken** [comment]
Hum. Maybe I was too fast here; it seems it needs to be transpiled first, which I guess makes it a poor candidate for cdnjs. Sorry about the noise!

**Comment by sufuf3** [comment]
@tlycken It's OK.
Thank you. 😃
