### ISSUE TITLE
[Request] Add Chart.PieceLabel.min.js

### ISSUE THREAD

**Issue by Veereshkumar4** [cdnjs/cdnjs#11650]
**Library name:** Chart.PieceLabel.min.js
**Git repository url:https://github.com/emn178/Chart.PieceLabel.js** 
**npm package name or url** (if there is one): https://www.npmjs.com/package/chart.piecelabel.js
**License (List them all if it's multiple):MIT license** 
**Official homepage:https://github.com/emn178/Chart.PieceLabel.js** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Added in https://github.com/cdnjs/cdnjs/commit/39782612a0fe75557eb455e3e775ef503d8df7bd
