### ISSUE TITLE
[Request] Add gitalk

### ISSUE THREAD

**Issue by calpa** [cdnjs/cdnjs#11668]
**Library name:** Gitalk
**Git repository url:** https://github.com/gitalk/gitalk
**npm package name or url** (if there is one): https://www.npmjs.com/package/gitalk
**License (List them all if it's multiple):** MIT
**Official homepage:** https://gitalk.github.io/
**Wanna say something? Leave message here:** 
Useful for blogs, such as mine: https://calpa.me

**Comment by sufuf3** [comment]
@calpa Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by calpa** [comment]
@sufuf3 For now, gitalk has more than 200 stars.

I am not the owner, but @booxood built it.

**Comment by sufuf3** [comment]
@calpa OK
Thank you for your suggestion. 😃

**Comment by PeterDaveHello** [comment]
Let's add it @sufuf3
