### ISSUE TITLE
[Request] Add ET-Line Icons

### ISSUE THREAD

**Issue by sshelzi** [cdnjs/cdnjs#11673]
**Library name:** ET-Line Icons
**Git repository url:** 
- https://github.com/Reklino/elegant-theme-icons/tree/master/fonts
- https://github.com/jeffstahlin/unyson-framework-et-line-icon-font

**npm package name or url** (if there is one): https://www.npmjs.com/package/et-line (below is the same, just on Github)
**bower package name or url:** https://github.com/pprince/etlinefont-bower
**dribble:** https://dribbble.com/shots/1441199-100-FREE-Line-Icons
**License (List them all if it's multiple):** GPL
**Official homepage:** https://www.elegantthemes.com/blog/freebie-of-the-week/free-line-style-icons
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@sshelzi Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
