### ISSUE TITLE
[Request] Add jquery.localize.js

### ISSUE THREAD

**Issue by Skyost** [cdnjs/cdnjs#11677]
**Library name:** jquery.localize.js    
**Git repository url:** https://github.com/coderifous/jquery-localize    
**npm package name or url (if there is one):**   
**License (List them all if it's multiple):**   
* GPL (http://dev.jquery.com/browser/trunk/jquery/GPL-LICENSE.txt)
* MIT (http://dev.jquery.com/browser/trunk/jquery/MIT-LICENSE.txt)

**Official homepage:** https://github.com/coderifous/jquery-localize    
**Wanna say something? Leave message here:**    
Nothing to add, jquery.localize.js is a great and popular library that allows its users to localize their page in an easy way.

**Comment by extend1994** [comment]
Hi @Skyost this issue is duplicated with #9563, I will close this issue and move this to #9563. It seems that we still need to confirm the license info. It will be great if you can help us with this! Thank you for the issue 😄
