### ISSUE TITLE
[Request] Add jquery.carouFredSel-5.1.0.js

### ISSUE THREAD

**Issue by Mark-Heydari** [cdnjs/cdnjs#11686]
**Library name:** jquery.carouFredSel-5.1.0.js
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@Mark-Heydari Thank you for your suggestion.
Would you give more info about jquery.carouFredSel-5.1.0.js?
CDNJS host https://cdnjs.com/libraries/jquery.caroufredsel I don't know is it fine to you.
I try to search, although there are many sources, I'd like to use v5.1.0 from the official provider.

Thank you.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
