### ISSUE TITLE
[Request] Add vue-strap 2

### ISSUE THREAD

**Issue by albertKrafter** [cdnjs/cdnjs#11692]
**Library name:** vue-strap 2.0.2
**Git repository url:** https://github.com/wffranco/vue-strap
**npm package name or url** (if there is one): github:wffranco/vue-strap
**License (List them all if it's multiple):** MIT
**Official homepage:** http://wffranco.github.io/vue-strap/
**Wanna say something? Leave message here:** "yuche/vue-strap", based on Vue.js 1.x, was forked into "wffranco/vue-strap", which is based on Vue.js 2.x.

Thanks!

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Memo:
When adding this lib, the name of lib needs to be changed because we have https://cdnjs.com/libraries/vue-strap.

"yuche/vue-strap", based on Vue.js 1.x, "wffranco/vue-strap", based on Vue.js 2.x.

**Comment by albert2cas** [comment]
May I suggest to just rely on the version?
E. g.:
https://cdnjs.cloudflare.com/ajax/libs/vue-strap/2.0.2/vue-strap.min.js (for wffranco's)

It seems to me that the development of both projects is sufficiently completed and that they wouldn't need a new major version number.

**Comment by mikkellindblom** [comment]
Any news on adding this?

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
