### ISSUE TITLE
[Request] Add tuesday

### ISSUE THREAD

**Issue by NickStees** [cdnjs/cdnjs#11695]
**Library name:** Tuesday
**Git repository url:** https://github.com/ShakrMedia/tuesday
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** https://github.com/shakrmedia/tuesday/blob/master/LICENSE
**Official homepage:** https://shakrmedia.github.io/tuesday/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ralphchung** [comment]
I'll take it. Thanks!
