### ISSUE TITLE
[Request] Add libjass

### ISSUE THREAD

**Issue by DoomTay** [cdnjs/cdnjs#11705]
**Library name:** libjass
**Git repository url:** https://github.com/Arnavion/libjass
**npm package name or url** (if there is one): libjass
**License (List them all if it's multiple):**  Apache-2.0
**Official homepage:** https://arnavion.github.io/libjass/

**Comment by sufuf3** [comment]
@DoomTay Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by DoomTay** [comment]
Whoops. Somehow it completely slipped my mind to double check the stats for this one.

**Comment by sufuf3** [comment]
@DoomTay It's OK
Still, welcome your suggestion and make CDNJS better.
Thank you.

Close because it doesn't have enough notable popularity. cc @PeterDaveHello
