### ISSUE TITLE
[Request] Add better-xlsx

### ISSUE THREAD

**Issue by helloyou2012** [cdnjs/cdnjs#11712]
**Library name:** better-xlsx
**Git repository url:** https://github.com/d-band/better-xlsx
**npm package name or url** (if there is one): https://www.npmjs.com/package/better-xlsx
**License (List them all if it's multiple):** MIT
**Official homepage:** https://d-band.github.io/better-xlsx/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@helloyou2012 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by helloyou2012** [comment]
@sufuf3 sorry, I didn't notice that.

**Comment by sufuf3** [comment]
It's fine.
If this lib has enough notable popularity, welcome open the issue.
We still welcome your suggestion.

Thank you for your great work.

close due to 
Closed due to unpopular. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host this one with a lower priority.

**Comment by helloyou2012** [comment]
@PeterDaveHello this library has more than 200 stars on GitHub 🙂.

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
