### ISSUE TITLE
[Request] Add Feathers

### ISSUE THREAD

**Issue by appdoodle** [cdnjs/cdnjs#11711]
**Library name: Feathers
**Git repository url: https://github.com/feathersjs/feathers
**npm package name or url** (if there is one): https://www.npmjs.com/package/feathers
**License (List them all if it's multiple): MIT
**Official homepage: https://feathersjs.com/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@appdoodle Thank you for your suggestion.
May I ask what files of this library can use in front-end?
Like `<script src="feathers.js"></script>`.

Thank you.
