### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID for cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by jessewgibbs** [cdnjs/cdnjs#11720]
We are getting reports of this error from a few of our customers.  It appears to be happening in both Firefox and Chrome on Windows.  Here's an example of the message that's appearing:
![29384958-d2e1c936-828a-11e7-80f5-e39617513047](https://user-images.githubusercontent.com/1097447/29385148-83ef05d6-828b-11e7-990d-ad909a8e6583.png)

We'll add additional info to this issue as we collect it.

**Comment by PeterDaveHello** [comment]
Can you please show me the cert you got here? As chrome mentions, there may be an issue with your connection privacy.

**Comment by PeterDaveHello** [comment]
I also wonder what's the IP address that you resolved by your side, looks like the domain was spoofed by your system/network admin, may not be related to CDNJS.

**Comment by PeterDaveHello** [comment]
Close due to no response.
