### ISSUE TITLE
[Request] Add map-icons.com

### ISSUE THREAD

**Issue by roshansing** [cdnjs/cdnjs#11733]
**Library name:** map-icons.com
**Library desctiption:** An icon font for use with Google Maps API and Google Places API using SVG markers and icon labels
**Git repository url:** https://github.com/scottdejonge/map-icons
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** https://github.com/scottdejonge/map-icons/blob/master/LICENSE
**Official homepage:** map-icons.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicated with #9539

**Comment by extend1994** [comment]
Let's move to #9539.
