### ISSUE TITLE
[request] Noty 3.1.2

### ISSUE THREAD

**Issue by nejt** [cdnjs/cdnjs#11743]
https://github.com/needim/noty
It is no longer linked to jQuery.

**Comment by PeterDaveHello** [comment]
Ping @extend1994

**Comment by extend1994** [comment]
@PeterDaveHello Noty originally belongs to (jquery-noty)[https://cdnjs.com/libraries/jquery-noty]. Should I rename "jquery-noty" to "noty"? Or I can just add the files, update the description and other updated parts in "jquery-noty"?
Apart from this, v1.0.0 ~ v1.2.1 on GitHub are missing from (jquery-noty)[https://cdnjs.com/libraries/jquery-noty]. Should I add them in same pull request? Thank you.

**Comment by nejt** [comment]
Noty 3.1.2 is no longer dependent upon jquery.  In my opinion, for clarification I would separate it.

**Comment by PeterDaveHello** [comment]
@nejt thanks

**Comment by extend1994** [comment]
@PeterDaveHello So should I separate it as @nejt (thanks 😃) said?

**Comment by PeterDaveHello** [comment]
@extend1994 sure

**Comment by extend1994** [comment]
OK!
