### ISSUE TITLE
[Request] Add bigtext

### ISSUE THREAD

**Issue by twhitson** [cdnjs/cdnjs#11745]
**Library name:** bigtext
**Library desctiption:** jQuery plugin, calculates the font-size and word-spacing needed to match a line of text to a specific width.
**Git repository url:** https://github.com/zachleat/BigText
**npm package name or url** (if there is one): https://www.npmjs.com/package/bigtext
**License (List them all if it's multiple):** MIT
**Official homepage:** https://www.zachleat.com/web/bigtext-makes-text-big/

**Comment by sufuf3** [comment]
duplicated with #11126

**Comment by extend1994** [comment]
Let's move to #11126.
