### ISSUE TITLE
[Request] Add jquery-watch

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11756]
**Library name:** jquery-watch
**Library desctiption:** A jQuery plug-in to notify you of CSS, Attribute or Property changes in an element
**Git repository url:**  https://github.com/RickStrahl/jquery-watch
**npm package name or url** (if there is one):  https://www.npmjs.com/package/jquery-watch
**License (List them all if it's multiple):**  MIT
**Official homepage:** http://samples.west-wind.com/jquery-watch/, https://weblog.west-wind.com/posts/2014/Oct/20/A-jquerywatch-Plugin-for-watching-CSS-styles-and-Attributes
**Wanna say something? Leave message here:** 

+++++++++++++++++++++++++++++++++

Very nice and usefull library
Please add it to waiting for popularity tag

**Comment by sufuf3** [comment]
@sashberd Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thank you.

**Comment by sashberd** [comment]
@sufuf3 Yes I know about nowadays low popularity of this library, but it is so cool coding and it solves very complicated problem in JS. So i decided to try to ad it to cdnjs, but if it still not goes with cdnjs standards feel free to close this issue

**Comment by sufuf3** [comment]
@sashberd Thanks.
The lib got 123 stars in two years, maybe it's not very popular now.
Let's wait for @PeterDaveHello decision.
To close this PR due to the lib have enough notable popularity, or to add this lib.

**Comment by PeterDaveHello** [comment]
@sashberd if you can send a PR to add it, it'll be acceptable.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello 
Will glad to get this PR to myself

**Comment by PeterDaveHello** [comment]
@sashberd assigned to you now. You can also consider to take some already existed PRs to make this project better and better.
