### ISSUE TITLE
[Request][Author] Add welcomer.js

### ISSUE THREAD

**Issue by jonhue** [cdnjs/cdnjs#11757]
**Library name:** Welcomer.js
**Library desctiption:** Slick welcome bars for your pages
**Git repository url:** https://github.com/slooob/welcomer.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/welcomer
**License (List them all if it's multiple):** MIT
**Official homepage:** https://slooob.github.io/welcomer.js/
**Wanna say something? Leave message here:** Hi. :-)

=====================

Notes from cdnjs maintainer:
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by venkatramanareddy** [comment]
Hey, the library doesn't seem to have enough popularity. There are 214 downloads in the last month though, should I be adding the library?

**Comment by jonhue** [comment]
I'd say that's solid, knowing that I released it 2 days ago :)

**Comment by sufuf3** [comment]
@jonhue Mind to wait a little while? Let this library has enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). 

If there is no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
