### ISSUE TITLE
[Request] Add jquery-iframe-auto-height

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#11754]
**Library name:** jquery-iframe-auto-height
**Git repository url:** https://github.com/house9/jquery-iframe-auto-height
**npm package name or url** (if there is one): none
**License (List them all if it's multiple):** [Unlicense](https://github.com/house9/jquery-iframe-auto-height/#license)
**Official homepage:** none

**Comment by PeterDaveHello** [comment]
@extend1994 You should remove the emtpy sections ... they are only for the out side contributors.

**Comment by extend1994** [comment]
Oh...Sorry!! I didn't see the related document clearly. Remove them right now!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
