### ISSUE TITLE
[Request] Add es7-shim

### ISSUE THREAD

**Issue by garyvdm** [cdnjs/cdnjs#11765]
* Library name: es7-shim
 * Library description: ECMAScript 7 compatibility shims for legacy JavaScript engines 
 * Git repository: https://github.com/es-shims/es7-shim
 * NPM package url: https://www.npmjs.com/package/es7-shim
 * License and its reference: MIT (https://github.com/es-shims/es7-shim/blob/master/LICENSE)
 * GitHub / Bitbucket popularity:
   - Count of watchers: 15
   - Count of stars: 147 
   - Count of forks: 27
 * NPM download stats:
   - Downloads in the last day: 1602
   - Downloads in the last week: 4415
   - Downloads in the last month: 18922

**Comment by ljharb** [comment]
As the maintainer of this package, I would strongly suggest not relying on it, and instead using https://npmjs.com/airbnb-browser-shims

**Comment by PeterDaveHello** [comment]
Hi @ljharb, thanks for the suggestion, I'm not familiar with es6/7, would `airbnb-browser-shims` be fine to be hosted on CDN? (Need browserify or webpack?) Thanks.

**Comment by ljharb** [comment]
Yes, you'd need browserify or webpack; as do all packages following modern best practices.

If you want to generate a bundle and host it on CDN JS, that's totally fine.

**Comment by PeterDaveHello** [comment]
@ljharb is it possible to be provided from you? Which can provide better integrity and reliability (and also we usually don't do that as we can't do that on 3k+ libraries in many different ways)

**Comment by ljharb** [comment]
I don't think it's a good idea or a best practice for packages to do that anymore - only to provide node-style CJS modules, and to let the consumer do the bundling.

With regard to es7-shim, ES7/ES2016 only contained one API change - `Array.prototype.includes` - so the list of shims is incorrect, and I don't intend to update that package again. It only includes a browser build for legacy reasons, just like es5-shim and es6-shim.

**Comment by PeterDaveHello** [comment]
@ljharb thanks a lot for the detail explanation. Really appreciate.
