### ISSUE TITLE
Non existing version on vanilla-lazyload

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#11766]
Hi,

I just noticed that there's a version 10.0.0 of [`vanilla-lazyload` on CDNJS](https://cdnjs.com/libraries/vanilla-lazyload), but the [latest available on npm](https://www.npmjs.com/package/vanilla-lazyload) is 9.0.1.

What happened?

**Comment by PeterDaveHello** [comment]
@verlok You tagged the version v10.0.0 in https://github.com/verlok/lazyload two days ago, that's the reason why.

**Comment by verlok** [comment]
Thanks @PeterDaveHello,
but now the tag [doesn't exist anymore](https://github.com/verlok/lazyload/tags). 

Could you please delete version 10.0.0 from cdnjs?

**Comment by PeterDaveHello** [comment]
@verlok That's not a good move, we don't know if anyone already started to use it.

**Comment by verlok** [comment]
I agree with you. So what happens if I create version 10.0.0 now? Will it override the existing one?

**Comment by PeterDaveHello** [comment]
@verlok It won't override, change the published files would be dangerous and would also change the hash.

**Comment by verlok** [comment]
Ok good, I'll pay attention to the version number next time. Thanks

**Comment by PeterDaveHello** [comment]
Thanks @verlok.
