### ISSUE TITLE
[Request] Add BOOTSTRA.386

### ISSUE THREAD

**Issue by NurdTurd** [cdnjs/cdnjs#11775]
**Library name:** BOOTSTRA.386
**Library desctiption:** A vintage 1980s DOS inspired Twitter Bootstrap theme
**Git repository url:** https://github.com/kristopolous/BOOTSTRA.386
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Apache License 2.0
**Official homepage:** http://kristopolous.github.io/BOOTSTRA.386/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Memo: Maybe need to add from zip file.

**Comment by extend1994** [comment]
Waiting https://github.com/kristopolous/BOOTSTRA.386/issues/39

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
