### ISSUE TITLE
[Request] Add Image-Select

### ISSUE THREAD

**Issue by sarvap-praharanayuthan** [cdnjs/cdnjs#11776]
**Library name:** Image-Select
**Library desctiption:** Image Select is an extension of Chosen, a jQuery plugin that makes long, unwieldy select boxes much more user-friendly. It provides image support for Single and Multi select HTML tags. 
**Git repository url:** https://github.com/websemantics/Image-Select
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** http://websemantics.github.io/Image-Select/

**Comment by sufuf3** [comment]
@sarvap-praharanayuthan Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Let's host this one.
