### ISSUE TITLE
[Request] Add DataTables Plugins

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#11784]
**Library name:** DataTables Plugins
**Library desctiption:** Plug-ins for DataTables
**Git repository url:** https://github.com/DataTables/Plugins
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
it is useful plugins for Datatables library.
Datatables library already include in cdnjs, so maybe this plugins also need include in cdnjs.
Thank you very much.

**Comment by sufuf3** [comment]
@ihsinhw May I ask that what files need to add in CDNJS from https://github.com/DataTables/Plugins?
Thank you.

**Comment by ihsinhw** [comment]
this git include datatables 'all' plugins.
maybe it's Directory architecture not well as Features to easy understand.
in root include Sorting, API,  Filtering, Internationalisation translations, Type detection and Pagination.
but in features Directory include 
Alphabet search, dataTables conditional Paging ,Deep linking,lengthLinks, mark.js,page Resize,scroll Resize, search Highlight, search Panel.
if possible maybe all file add to CDNJS is wonderful.
Thank you.

**Comment by sufuf3** [comment]
Thanks for your reply.

**Comment by julmot** [comment]
@sufuf3 I was wondering: How would you solve the problem that this repository consists of many files and versions?

**Comment by sufuf3** [comment]
@julmot We have auto-update config in every lib's `package.json`, such as `git auto-update`(eg. https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/AniJS/package.json#L19-L30) or `npm auto-update` (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/Chart.js/package.json#L11-L19).
Our auto-update mechanism will get the files via detecting the lib release new version from npm or newest git tag.

As you can see in auto-update config, we have `basePath` which we want to get the files under this folder. And `files` is a pattern matcher allowing selection of multiple files(node-glob).

This is our auto-update mechanism which will get the files by our PeterBot. :)

If you have any question about how to add the newest release version via auto-update, here is detail description you could refer to https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md 

Thank you.

**Comment by ihsinhw** [comment]
Thank you for your help @sufuf3

**Comment by MattIPv4** [comment]
Added in https://github.com/cdnjs/cdnjs/commit/da47452c8e4482c560f9934aa9d3e731519a60cb
