### ISSUE TITLE
Waiting for https://cdnjs.cloudflare.com/

### ISSUE THREAD

**Issue by ashucg** [cdnjs/cdnjs#11786]
I have included every external library using CDNJS but I am facing this issue every day since last week. At times I am unable to access https://cdnjs.com/ as the website never finishes loading and same is for the resources hosted at https://cdnjs.cloudflare.com/

My Location & ISP: https://www.whoismyisp.org/ip/122.173.8.130

**Comment by PeterDaveHello** [comment]
@ashucg thanks for reporting, can you please provide the following info:
 - https://cdnjs.com/cdn-cgi/trace
 - https://cdnjs.cloudflare.com/cdn-cgi/trace

I'd like to ask few quick questions to help us understand the issue:

Do you have the same problem on the other Cloudflare hosted sites and the sites using cdnjs like https://www.yelp.com/? Do you have the problem when directly access resource url like: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js?

Actually, cdnjs.cloudflare.com is directly hosting by @Cloudflare, you can also directly submit the issue at https://support.cloudflare.com/ so the engineer who has the access to the backend can directly help you.

Thanks again.

**Comment by ashucg** [comment]
@PeterDaveHello here is the information you asked for:
https://cdnjs.com/cdn-cgi/trace
`fl=58f31
h=cdnjs.com
ip=122.173.183.81
ts=1504771475.393
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
colo=BOM
spdy=h2
http=h2
loc=IN`

https://cdnjs.cloudflare.com/cdn-cgi/trace
`fl=57f5
h=cdnjs.cloudflare.com
ip=122.173.183.81
ts=1504771476.189
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
colo=DEL
spdy=h2
http=h2
loc=IN`

I am not sure about other websites that are hosted on Cloudflare, I will check yelp next time when CNDJS is down but I do face this problem when I try to directly access the resources such as:
https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js

I will also submit this issue at https://support.cloudflare.com/  ASAP

Other than that, please let me know if you require anything else from me.

Thanks!

**Comment by PeterDaveHello** [comment]
@ashucg Thanks for the info you provided, I believe if you can provide the same info when you opening a support ticket on https://support.cloudflare.com/, they can help you faster.

@terinjokes would you like to take a look at this one? Thanks.

**Comment by PeterDaveHello** [comment]
@ashucg btw, do you have any similiar issues on accessing Cloudflare website directly? Like the https://support.cloudflare.com/  or https://cloudflare.com/, thanks.

**Comment by ashucg** [comment]
@PeterDaveHello nope, never had such issues when accessing Cloudflare directly, even when CDNJS was down for me.

**Comment by PeterDaveHello** [comment]
@ashucg thanks for that info, so when you mean CDNJS I think you mean cdnjs.cloudflare.com? As you can open cdnjs but it's just stock on cdnjs.cloudflare.com resource loading

**Comment by ashucg** [comment]
@PeterDaveHello yeah, https://cdnjs.com/ opens but never finishes loading because resources are hosted at https://cdnjs.cloudflare.com/ which doesn't work for me sometimes.

**Comment by PeterDaveHello** [comment]
@ashucg thanks, I got it, that's a little bit weird, do you mind to take a look at https://cloudflare.com/cdn-cgi/trace to see if it's the same as https://cdnjs.cloudflare.com/cdn-cgi/trace ? I think they should be served from the same node.

**Comment by ashucg** [comment]
https://cloudflare.com/cdn-cgi/trace
`fl=57f9
h=cloudflare.com
ip=171.61.219.6
ts=1504776513.116
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
colo=DEL
spdy=h2
http=h2
loc=IN`

https://cdnjs.cloudflare.com/cdn-cgi/trace
`fl=57f11
h=cdnjs.cloudflare.com
ip=171.61.219.6
ts=1504776514.229
visit_scheme=https
uag=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
colo=DEL
spdy=h2
http=h2
loc=IN`

**Comment by PeterDaveHello** [comment]
@ashucg ok, looks the same. Have you ever tried to use a different browser or device to access resource on cdnjs.cloudflare.com?

**Comment by ashucg** [comment]
@PeterDaveHello yeah, I have tried different devices, browsers and even asked someone else to try to access it but still had the same issue

**Comment by PeterDaveHello** [comment]
@ashucg thanks for the info, @terinjokes is our friend in Cloudflare, I'll also write an email to him.

**Comment by terinjokes** [comment]
@ashucg next time there's an issue for you, can you post the output of `mtr` or traceroute to cdnjs.cloudflare.com?

**Comment by ashucg** [comment]
@terinjokes sure, I will do that

**Comment by ashucg** [comment]
@PeterDaveHello It is working fine right now but this problem has been occurring at random times so I can't tell if it really is gone or not. I will let you guys know if I stop facing this issue or else I would do what @terinjokes has mentioned earlier.

**Comment by PeterDaveHello** [comment]
@ashucg got it, thanks.

**Comment by ashucg** [comment]
I am having the same issue right now, I have checked [Yelp](https://www.yelp.com/) which is working fine for me. I am running `tracert` right now, will update you ASAP

**Comment by ashucg** [comment]
![tracert](https://user-images.githubusercontent.com/11291284/30204989-14851e20-94a5-11e7-8fa3-b1b6f575d0ee.png)
@terinjokes  here is the output

**Comment by ashucg** [comment]
![mtr](https://user-images.githubusercontent.com/11291284/30205237-eeb50df8-94a5-11e7-92cd-1a74fa1af8c5.png)
@terinjokes

**Comment by ashucg** [comment]
Hi guys,

I am no longer experiencing that issue. Thanks to both of you for your time and support.

**Comment by PeterDaveHello** [comment]
Thank you @ashucg

**Comment by lolo32** [comment]
I know, it's already closed, but I go the same issue with Firefox now.
If I enable HTTP3 in Firefox about:config, the connecion never end and stay at "Waiting for https://cdnjs.cloudflare.com", even the request to trace cannot resolve. Just worked after disabling this parameter.
