### ISSUE TITLE
[Request] Add sandbox.js

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#11783]
**Library name:** sandbox.js
**Library desctiption:** 
**Git repository url:** https://github.com/bartaz/sandbox.js
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
if possible, plz help add this library to cdnjs, thank you

**Comment by sufuf3** [comment]
@ihsinhw Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by ihsinhw** [comment]
this library include jquery.highlight.js, it is useful tool with jquery datatables library.
plz consider this library to cdnjs.

**Comment by sufuf3** [comment]
@ihsinhw Thanks.
The lib got 147 stars in 8 years, maybe it's not very popular now.
Let's wait for @PeterDaveHello decision.
To close this PR due to the lib have enough notable popularity, or to add this lib.

**Comment by PeterDaveHello** [comment]
It has no version in its repo, and there is no update for 7 years, it's just a sandbox playground as its description says, maybe try to find some similar function library on cdnjs.com or on GitHub and see if we can host it?

**Comment by sufuf3** [comment]
@ihsinhw What do you think about this comment https://github.com/cdnjs/cdnjs/issues/11783#issuecomment-330030221 ?
Thank you.

**Comment by ihsinhw** [comment]
Thank you for @PeterDaveHello  and @sufuf3 , maybe let me consider and find the similar function library.

**Comment by sufuf3** [comment]
@ihsinhw OK, thanks.
Close because the library doesn't have enough notable popularity.
cc @PeterDaveHello
