### ISSUE TITLE
[Request] Add jquery.balloon

### ISSUE THREAD

**Issue by jeronn** [cdnjs/cdnjs#11787]
**Library name:** jquery.balloon
**Library desctiption:** A jQuery plugin to add balloon tips to elements
**Git repository url:** https://github.com/urin/jquery.balloon.js/
**npm package name or url** (if there is one): https://www.npmjs.com/package/jquery-balloon-js
**License (List them all if it's multiple):** MIT license (http://www.opensource.org/licenses/mit-license.php)
**Official homepage:** https://urin.github.io/jquery.balloon.js/
**Wanna say something? Leave message here:** It's available at jsdelivr, would be nicer on cdnjs. Cheers!

**Comment by sufuf3** [comment]
@PeterDaveHello this lib is available at jsdelivr (https://www.jsdelivr.com/package/npm/jquery-balloon-js)
But this library doesn't have enough popularity.
Should we add it or close because this library doesn't have enough popularity?
Thank you.

**Comment by PeterDaveHello** [comment]
Let's host this one, just with a lower priority.
