### ISSUE TITLE
[Request] Add nanogallery2

### ISSUE THREAD

**Issue by Apollodore** [cdnjs/cdnjs#11801]
**Library name:** nanogallery2
**Library desctiption:** 
**Git repository url:** https://github.com/nanostudio-org/nanogallery2
**npm package name or url** (if there is one): https://www.npmjs.com/package/nanogallery2
**License (List them all if it's multiple):** https://github.com/nanostudio-org/nanogallery2#license
**Official homepage:** 
**Wanna say something? Leave message here:** 

It would be great to add [nanogallery2](https://github.com/nanostudio-org/nanogallery2) on cdnjs, the new improved version of @Kris-B fantastic gallery [already on cdnjs](https://cdnjs.com/libraries/nanogallery) but not updated anymore. Thank you for your great work!

**Comment by sufuf3** [comment]
Memo: 
In README of Kris-B/nanoGALLERY
> nanoGALLERY will continue to be maintained for fixing show-stopper bugs, but no new features should be expected.
> nanoGALLERY's successor, is available: nanogallery2

https://github.com/Kris-B/nanoGALLERY#nanogallery---image-gallery-for-jquery

**Comment by Apollodore** [comment]
Thank you very much for your answer, thank you for giving us cdnjs, I hope you will add nanogallery2 to cdnjs soon!

**Comment by Apollodore** [comment]
Hello, would you agree to reconsider adding [nanogallery2](https://github.com/nanostudio-org/nanogallery2)? Thank you in advance for what yo can do, Best regards.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/nanogallery2
