### ISSUE TITLE
[Request] Add lozad

### ISSUE THREAD

**Issue by ApoorvSaxena** [cdnjs/cdnjs#11803]
Library name: lozad
Library description: Highly performant, light ~0.5kb and configurable lazy loader in pure JS with no dependencies
Git repository: https://github.com/ApoorvSaxena/lozad.js
License(s): MIT

GitHub stats:
13 watchers
447 stars
16 forks

**Comment by ApoorvSaxena** [comment]
Updated GitHub stats:
33 watchers
1453 stars
52 forks

**Comment by PeterDaveHello** [comment]
@ApoorvSaxena thanks.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello 
I came across this library and there are no git tag in it
I suppose there is a need to add at least one in order to host it, am I right?

**Comment by sufuf3** [comment]
Let's discuss with the author.
@ApoorvSaxena Could you 
Could you please add [git tags](https://github.com/ApoorvSaxena/lozad.js/tags) for the repo? 

If you have any suggestions, please let me know.
Thank you.

**Comment by ApoorvSaxena** [comment]
@sufuf3 have added [tag](https://github.com/ApoorvSaxena/lozad.js/tags) to the repo

**Comment by sufuf3** [comment]
@ApoorvSaxena Many thanks.
@sashberd I think it's fine to add this lib :smiley:
