### ISSUE TITLE
[Request] Add leaflet.path.transform

### ISSUE THREAD

**Issue by rajkishan16** [cdnjs/cdnjs#11804]
**Library name:** leaflet.path.transform
**Library desctiption:** Drag/rotate/resize handler for leaflet vector features.
**Git repository url:** https://github.com/w8r/Leaflet.Path.Transform
**npm package name or url** (if there is one): https://www.npmjs.com/package/leaflet-path-transform
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** This is a very useful library, and I would love to see it added to cdnjs. Thanks!

**Comment by extend1994** [comment]
Hi @rajkishan16 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
 We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by rajkishan16** [comment]
Hi @extend1994 
Sorry about that. When I added this request, it did have close to 1000 downloads/month on npm registry. But it looks like it has gone down since then. Thanks anyways!

**Comment by extend1994** [comment]
Well, in this case, I think we can observe it for a while. @rajkishan16 Thanks for quick reply!

**Comment by sashberd** [comment]
Hi @rajkishan16 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
