### ISSUE TITLE
[Request] Add promise-polyfill

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#11802]
**Library name:** promise
**Library desctiption:** Lightweight ES6 Promise polyfill for the browser and node. A+ Compliant
**Git repository url:** https://github.com/taylorhakes/promise-polyfill
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
fetch project recommend taylorhakes/promise-polyfill for its small size and Promises/A+ compatibility.
plz help add it to cdnjs, thank you.

**Comment by BenjaminEHowe** [comment]
+many over in #12487
