### ISSUE TITLE
[Request] Add vanilla-tilt.js

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#11812]
**Library name:** vanilla-tilt.js
**Git repository url:** https://github.com/micku7zu/vanilla-tilt.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/vanilla-tilt
**License (List them all if it's multiple):** [MIT](https://github.com/micku7zu/vanilla-tilt.js/blob/master/LICENSE)
**Official homepage:** https://micku7zu.github.io/vanilla-tilt.js/

**Comment by finch185277** [comment]
I want to add this.
