### ISSUE TITLE
[Request] Update parallax

### ISSUE THREAD

**Issue by RRorg** [cdnjs/cdnjs#11815]
I am the new maintainer of the parallax project:

https://github.com/wagerfield/parallax

Since I've removed the compiled JS files from git versioning, the update route needs to be changed to use npm instead. Adding the recent v3.1 version to CDNjs would be great too.

I've tried adding it myself, but the attempt to git-clone this repo blew my MacBook up after the first 100GB so if someone else could do that I would be super-duper-mega thankful 💙

**Comment by sufuf3** [comment]
@RRorg I'll take this ASAP.
Because CDNJS is too huge, this repo need to enable git [sparseCheckout](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md)
Thank you for your suggestion.

Memo: https://cdnjs.com/libraries/parallax

**Comment by extend1994** [comment]
Hi @RRorg for parallax@3.0.0 on npm. After I use the command `npm i parallax@3.0.0`, `dist/` and files () will appear. I remove the files on purpose and then try to use `gulp` to get the files back. I found the files are different. 
* The result of the command `npm i parallax@3.0.0`
```
def3172e62449bb0a5d85df78f8d86b74e634fcf  dist/parallax.js
59fafcbd35fb1857bec0e67e964b54c80596eedd  dist/parallax.min.js
8ee508554005c40de068471260dc5fedf3e7557e  dist/parallax.min.js.map
```
* The result of the command `gulp `
```
9e7bb2fb10eea77a27954e2ec6d8fe20de89f0a8  dist/parallax.js
031ba36d143e2d7d9bde7e41dafc74c02f2aa981  dist/parallax.min.js
a540a247860e4597121e757e45ad7ba8ee6894e2  dist/parallax.min.js.map
```
Could you please tell me which files should I use? Thank you :)

**Comment by PeterDaveHello** [comment]
@extend1994 it make sense to have different hash on your builds, you can also use diff to check its content, but if the dist files already existed, why do you need to build it via gulp?

**Comment by extend1994** [comment]
@PeterDaveHello Because when I use autoupdate.js, it can not get `dist`, I am curious why there is difference between it (https://registry.npmjs.org/parallax-js/-/parallax-js-3.0.0.tgz) and `npm i parallax@3.0.0`. And the only file I can see to might create `dist` is `gulpfile.js`. The first thought is just give it a try. Should I just use the files after I use the command `npm i parallax@3.0.0`? Thank you.

**Comment by PeterDaveHello** [comment]
@extend1994 try to use "ied" or "pnpm"? I don't think we need to use "npm install" as that's not how we fetch it, auto-updater directly extract files from its tarball.

**Comment by extend1994** [comment]
Ok

**Comment by extend1994** [comment]
@PeterDaveHello 
`dist` is still created using "pnpm", but isn't created using "ied". Which one should I use?

**Comment by PeterDaveHello** [comment]
@extend1994 They are both reference, you can also try "ref", anyway, the tarball will be the correct one, I didn't dig every npm client yet.

**Comment by extend1994** [comment]
OK, thank you! 👍

**Comment by RRorg** [comment]
3.1.0 should be the most recent version on npm, which contains pre built files and unified the build process. That was really hacky in the 3.0.0 release :) Am 15.09.2017 1:16 nachm. schrieb LboAnn <notifications@github.com>:OK, thank you! 👍

**Comment by PeterDaveHello** [comment]
Thanks @RRorg !
