### ISSUE TITLE
[Request] Add sticky-sidebar

### ISSUE THREAD

**Issue by 0cool-f** [cdnjs/cdnjs#11825]
**Library name:** sticky-sidebar
**Library desctiption:** Pure JavaScript plugin for making smart and high performance sticky sidebar.
**Git repository url:** https://github.com/abouolia/sticky-sidebar
**npm package name or url** (if there is one): https://www.npmjs.com/package/sticky-sidebar
**License (List them all if it's multiple):** https://github.com/abouolia/sticky-sidebar/blob/master/LICENSE.md
**Official homepage:** https://abouolia.github.io/sticky-sidebar/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
@0cool-f Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by k9t9** [comment]
Seems it now have around 740 stars on github..

**Comment by presto2116** [comment]
Over a 1000 now
