### ISSUE TITLE
[Request] Add jquery-ajax-localstorage-cache

### ISSUE THREAD

**Issue by codyjoliphant** [cdnjs/cdnjs#11822]
**Library name:** jquery-ajax-localstorage-cache
**Library desctiption:** Jalc is a plugin built for jQuery (> 1.5.1) and any object implementing the storage interface, such as localStorage.
**Git repository url:** https://github.com/SaneMethod/jquery-ajax-localstorage-cache
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Apache 2 License
**Official homepage:** https://github.com/SaneMethod/jquery-ajax-localstorage-cache
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by cy91244** [comment]
I will do this.
