### ISSUE TITLE
[Request] Add jquery-handlebars

### ISSUE THREAD

**Issue by dima734** [cdnjs/cdnjs#11829]
**Library name:** jquery-handlebars
**Library desctiption:** allows you to use Handlebars.js with jQuery.
**Git repository url:** https://github.com/71104/jquery-handlebars/
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT. Copyright 2013 Alberto La Rocca.
**Official homepage:** http://71104.github.io/jquery-handlebars/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by qwe19272375** [comment]
Hi @dima734 ,
Thanks for your suggestion. This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [CONTRIBUTE.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library). Would you mind to open an issue again when the library has more popularity?

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
