### ISSUE TITLE
[Request][Author] Add handsontable-pro

### ISSUE THREAD

**Issue by jansiegel** [cdnjs/cdnjs#11824]
**Library name:** handsontable-pro
**Library desctiption:** Spreadsheet-like data grid editor that provides copy/paste functionality compatible with Excel/Google Docs
**Git repository url:** https://github.com/handsontable/handsontable-pro
**npm package name or url** (if there is one): https://www.npmjs.com/package/handsontable-pro
**License (List them all if it's multiple):** https://github.com/handsontable/handsontable-pro/blob/master/LICENSE
**Official homepage:** https://handsontable.com/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
@jansiegel 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by jansiegel** [comment]
@sufuf3 
`handsontable-pro` is a commercial version of [Handsontable](https://github.com/handsontable/handsontable), and open source spreadsheet component. The "community" edition of Handsontable currently has 8566 stars and 50730 monthly downloads on npm.
The "Pro" version was just moved to Github, previously it was hosted on a private server, that's why it doesn't have much traffic yet.

If that's enough to be added to your registry, that'd be great! If not, I'll open a new issue after it reaches your requirements.

**Comment by sufuf3** [comment]
I think this lib is good, Thank you.

**Comment by budnix** [comment]
@sufuf3 Can I ask when this library will be published? I suppose that this issue was partially accepted but for now we are waiting for "notable popularity"?

**Comment by sufuf3** [comment]
@budnix Actually we are working on #11170, also we want to there are more contributors in this repo. 😢 
Because there are many issues need to be worked.
If you'd like this lib to be hosted ASAP, we encourage you to add a library via sending a pull request.

Thank you.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://www.npmjs.com/package/handsontable (pro deprecated)
