### ISSUE TITLE
Upgrade fixFormat tool to run with package name parameters

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11832]
Hi
I faced with problem, if you work on multiple PR's and you have multiple libs in you sparse checkout , today's fixFormat tool will upgrade all libs even if you do not need it. I made some changes in it and now if you run tool with package name e.g. 'tools/fixFormat.js jquery.hoverIntent' it will run only on provided name for library.
If you want to run on several names, just provide them with spaces in command line, setu.

Here the code:

```
   var args = process.argv
    if (args[2]) {
        args = args.slice(2);
        packages = packages.filter((package) => { return args.some(function(argument) { return package.toLowerCase().indexOf(argument.toLowerCase()) > -1 }) });     
    }
   async.each(packages, function (item, callback) {.....
```
TEST:

![image](https://user-images.githubusercontent.com/11975561/30415503-00ecf884-9931-11e7-9268-688a303c80c8.png)

FYR

**Comment by sufuf3** [comment]
@PeterDaveHello Would you please take a look?
I think maybe it's nice to have.

Thanks.

**Comment by sashberd** [comment]
@PeterDaveHello 
Would you like I will do an update for this issue?

**Comment by sashberd** [comment]
@PeterDaveHello What about this?

**Comment by PeterDaveHello** [comment]
This issue is duplicated with #5476, feel free to send a PR, thanks.
