### ISSUE TITLE
[Request] Add jquery.kinetic

### ISSUE THREAD

**Issue by zkelo** [cdnjs/cdnjs#11836]
**Library name:** jquery.kinetic
**Library desctiption:** jQuery.kinetic is a simple plugin which adds smooth drag scrolling with gradual deceleration to containers.
**Git repository url:** https://github.com/davetayls/jquery.kinetic
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** https://davetayls.me

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
