### ISSUE TITLE
How to publish an older semver version?

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#11838]
Hi there,

in `vanilla-lazyload` I reached version 10.3.0 but I recently released un update for version too, tagging 8.2.0 on the related [Github repo](https://github.com/verlok/lazyload).

Of course I can't release it on the master branch since the development went forward, so my questin is:

- will the 8.2.0 be published on cdnjs, even if the tag is not on the master branch?
- if not, how can I publish 8.2.0?

Thanks

**Comment by PeterDaveHello** [comment]
Already added.
https://cdnjs.com/libraries/vanilla-lazyload/8.2.0
https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/vanilla-lazyload

**Comment by PeterDaveHello** [comment]
As the file/directory structure is the same, the bot can fetch it without a problem 😄

**Comment by verlok** [comment]
Nice and sweet

**Comment by PeterDaveHello** [comment]
🤘🏼
