### ISSUE TITLE
[Request] Add folktale

### ISSUE THREAD

**Issue by balmasi** [cdnjs/cdnjs#11839]
**Library name:** folktale
**Library desctiption:** A standard library for functional programming in JavaScript
**Git repository url:** https://github.com/origamitower/folktale
**npm package name or url**: https://www.npmjs.com/package/folktale
**License (List them all if it's multiple):** MIT
**Official homepage:** folktale.origamitower.com
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #10590

**Comment by extend1994** [comment]
Move to #10590
