### ISSUE TITLE
Library prototype is outdated

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11846]
The library https://github.com/sstephenson/prototype is outdated
There is a need to add autoupdate config
FYR

**Comment by sufuf3** [comment]
Actually, CDNJS host the latest version of this lib. https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/prototype https://github.com/sstephenson/prototype/releases

And we'd like to ignore `*_rc` version like https://github.com/cdnjs/cdnjs/blob/master/.gitignore#L57

So maybe this lib is not really outdated?
@sashberd What do you think?

Thank you for suggestion.
