### ISSUE TITLE
Library expect.js is outdated

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#11845]
Library https://github.com/Automattic/expect.js is outdated

There is a need to add auto-update configuration in package json

FYR

**Comment by sufuf3** [comment]
@sashberd Thanks, it's awesome!
Let's do it.
CDNJS: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/expect.js
Library's URL: https://github.com/Automattic/expect.js
