### ISSUE TITLE
[Request] Add ui.router components

### ISSUE THREAD

**Issue by gRoussac** [cdnjs/cdnjs#11841]
**Library name:** ui.router components
**Library desctiption:**  Route to components today using Angular 1.5+ and ui-router 0.2.x+
**Git repository url:** https://github.com/softsimon/ui-router-route-to-components
**npm package name or url** (if there is one): https://www.npmjs.com/package/ui-router-route-to-components
**License (List them all if it's multiple):** https://spdx.org/licenses/MIT.html
**Official homepage:** 
**Wanna say something? Leave message here:** Thanks

=====================

**Comment by sufuf3** [comment]
@gRoussac  Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by gRoussac** [comment]
Hi,

Thanks for your answer. Nevermind it is hosted by jsdelivr https://www.jsdelivr.com/package/npm/ui-router-components

Success !
