### ISSUE TITLE
[Request][Author] Add OrgChart

### ISSUE THREAD

**Issue by dabeng** [cdnjs/cdnjs#11842]
**Library name:** OrgChart
**Library desctiption:** It's a simple and direct organization chart plugin. Anytime you want a tree-like chart, you can turn to OrgChart
**Git repository url:** https://github.com/dabeng/OrgChart
**npm package name or url:** orgchart
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/dabeng/OrgChart

**Comment by sufuf3** [comment]
Duplicated with #10857 (Today, I will help fix #11826)

**Comment by extend1994** [comment]
Move to #10857.
