### ISSUE TITLE
[Request] Add angular-muti-step-form

### ISSUE THREAD

**Issue by RibeiroAna** [cdnjs/cdnjs#11855]
**Library name:** angular-muti-step-form
**Git repository url:** https://github.com/troch/angular-multi-step-form
npm: https://www.npmjs.com/package/angular-multi-step-form

**Comment by sufuf3** [comment]
@RibeiroAna Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by sashberd** [comment]
Hi @RibeiroAna 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by RibeiroAna** [comment]
No problem. I am closing it.
