### ISSUE TITLE
[Request] Add datatables-bulma

### ISSUE THREAD

**Issue by dedo1911** [cdnjs/cdnjs#11850]
**Library name:** datatables-bulma
**Library desctiption:** DataTables styling for the Bulma CSS framework
**Git repository url:** https://github.com/JDilleen/datatables-bulma
**npm package name or url** (if there is one): https://www.npmjs.com/package/datatables-bulma
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/JDilleen/datatables-bulma

**Comment by sufuf3** [comment]
@dedo1911 Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
