### ISSUE TITLE
[Request] Add rgraph

### ISSUE THREAD

**Issue by heyesr** [cdnjs/cdnjs#11857]
**Library name:** RGraph
**Library desctiption:**  A free SVG and canvas based charts library
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:**  http://www.rgraph.net
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@heyesr Thank you for your suggestion.
Could you give us some info about this lib's repository or npm package?
We usually add the lib from upstream. So we need this info.

Thank you.

**Comment by heyesr** [comment]
Hi,

There's no public source code repository. I use SVN to track my changes whilst developing - but there's no public access  I'm afraid. If you need a list of URLs for the libraries I can provide that - eg (these are the minified libraries)

https://www.rgraph.net/libraries/RGraph.common.core.js
https://www.rgraph.net/libraries/RGraph.bar.js
etc

If you need URLs for the unminified source code I can set that up for you.

**Comment by sufuf3** [comment]
@heyesr Thank you.
@PeterDaveHello could we help add this lib?
This lib seems to be added manually.
1. the website traffic statistics: https://www.alexa.com/siteinfo/rgraph.net
2. the versions on the lib: https://www.rgraph.net/download

Thanks.

**Comment by heyesr** [comment]
Here's a list to the minified library files (and if you want the unminified versions just let me know):

https://www.rgraph.net/libraries/RGraph.bar.js
https://www.rgraph.net/libraries/RGraph.bipolar.js
https://www.rgraph.net/libraries/RGraph.common.annotate.js
https://www.rgraph.net/libraries/RGraph.common.context.js
https://www.rgraph.net/libraries/RGraph.common.core.js
https://www.rgraph.net/libraries/RGraph.common.csv.js
https://www.rgraph.net/libraries/RGraph.common.deprecated.js
https://www.rgraph.net/libraries/RGraph.common.dynamic.js
https://www.rgraph.net/libraries/RGraph.common.effects.js
https://www.rgraph.net/libraries/RGraph.common.key.js
https://www.rgraph.net/libraries/RGraph.common.resizing.js
https://www.rgraph.net/libraries/RGraph.common.sheets.js
https://www.rgraph.net/libraries/RGraph.common.tooltips.js
https://www.rgraph.net/libraries/RGraph.common.zoom.js
https://www.rgraph.net/libraries/RGraph.drawing.background.js
https://www.rgraph.net/libraries/RGraph.drawing.circle.js
https://www.rgraph.net/libraries/RGraph.drawing.image.js
https://www.rgraph.net/libraries/RGraph.drawing.marker1.js
https://www.rgraph.net/libraries/RGraph.drawing.marker2.js
https://www.rgraph.net/libraries/RGraph.drawing.marker3.js
https://www.rgraph.net/libraries/RGraph.drawing.poly.js
https://www.rgraph.net/libraries/RGraph.drawing.rect.js
https://www.rgraph.net/libraries/RGraph.drawing.text.js
https://www.rgraph.net/libraries/RGraph.drawing.xaxis.js
https://www.rgraph.net/libraries/RGraph.drawing.yaxis.js
https://www.rgraph.net/libraries/RGraph.fuel.js
https://www.rgraph.net/libraries/RGraph.funnel.js
https://www.rgraph.net/libraries/RGraph.gantt.js
https://www.rgraph.net/libraries/RGraph.gauge.js
https://www.rgraph.net/libraries/RGraph.hbar.js
https://www.rgraph.net/libraries/RGraph.hprogress.js
https://www.rgraph.net/libraries/RGraph.line.js
https://www.rgraph.net/libraries/RGraph.meter.js
https://www.rgraph.net/libraries/RGraph.modaldialog.js
https://www.rgraph.net/libraries/RGraph.odo.js
https://www.rgraph.net/libraries/RGraph.pie.js
https://www.rgraph.net/libraries/RGraph.radar.js
https://www.rgraph.net/libraries/RGraph.rose.js
https://www.rgraph.net/libraries/RGraph.rscatter.js
https://www.rgraph.net/libraries/RGraph.scatter.js
https://www.rgraph.net/libraries/RGraph.semicircularprogress.js
https://www.rgraph.net/libraries/RGraph.svg.bar.js
https://www.rgraph.net/libraries/RGraph.svg.common.ajax.js
https://www.rgraph.net/libraries/RGraph.svg.common.core.js
https://www.rgraph.net/libraries/RGraph.svg.common.csv.js
https://www.rgraph.net/libraries/RGraph.svg.common.fx.js
https://www.rgraph.net/libraries/RGraph.svg.common.key.js
https://www.rgraph.net/libraries/RGraph.svg.common.sheets.js
https://www.rgraph.net/libraries/RGraph.svg.common.tooltips.js
https://www.rgraph.net/libraries/RGraph.svg.funnel.js
https://www.rgraph.net/libraries/RGraph.svg.hbar.js
https://www.rgraph.net/libraries/RGraph.svg.line.js
https://www.rgraph.net/libraries/RGraph.svg.pie.js
https://www.rgraph.net/libraries/RGraph.svg.radar.js
https://www.rgraph.net/libraries/RGraph.svg.rose.js
https://www.rgraph.net/libraries/RGraph.svg.scatter.js
https://www.rgraph.net/libraries/RGraph.svg.semicircularprogress.js
https://www.rgraph.net/libraries/RGraph.svg.waterfall.js
https://www.rgraph.net/libraries/RGraph.thermometer.js
https://www.rgraph.net/libraries/RGraph.vprogress.js
https://www.rgraph.net/libraries/RGraph.waterfall.js
https://www.rgraph.net/libraries/financial-data.js

**Comment by PeterDaveHello** [comment]
So @heyesr are you the author? It makes no sense that an open source project has no open access development history. We also need to confirm its popularity.

**Comment by heyesr** [comment]
I am. Open Source software does not have to have a full development history online. The thing that defines it as Open Source is the license - and RGraphs license is MIT.

In the same vein you host Highcharts if I'm not mistaken - and that uses a Creative Commons non-open source license. I remember that someone from the Mozilla team once told Mozilla contributors to stop using it for that very reason.

It's not massively popular - but that's down to it not being more prominent in Google search results. It used to have the number 1 spot for the search "HTML5 charts" but then I switched to targeting "javascript charts" and since then I've had no luck with search. Hopefully though a change that I made at the start of September will turn things around.

**Comment by PeterDaveHello** [comment]
Thanks @heyesr, I got your point. As we're maintaining more than 3k libraries here, I'll still need to ask for public repository and valid versioning, thank you.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
