### ISSUE TITLE
[Request] Add mobiriseicons

### ISSUE THREAD

**Issue by mayurshirishmohite** [cdnjs/cdnjs#11858]
**Library name:** mobiriseicons
**Library desctiption:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@mayurshirishmohite Thank you for your suggestion.
I know you mean this lib https://mobiriseicons.com/ that CDNJS can host, maybe.
But could you give us some info about this lib's repository or npm package?
We usually add the lib from upstream. So we need these info.

Thank you.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
