### ISSUE TITLE
[Request] Add jQuery bracket

### ISSUE THREAD

**Issue by smileytechguy** [cdnjs/cdnjs#11860]
**Library name:** jQuery bracket
**Library desctiption:** jQuery bracket is a jQuery plugin that lets users create and display single and double elimination brackets for tournament play.
**Git repository url:** https://github.com/teijo/jquery-bracket
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.aropupu.fi/bracket/
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
Duplicated with #8938

**Comment by extend1994** [comment]
Move to #8938
