### ISSUE TITLE
[Request][Author] Add storymap.js

### ISSUE THREAD

**Issue by jakobzhao** [cdnjs/cdnjs#11864]
**Library name:** storymap.js
**Library desctiption:*digital storytelling with web maps* 
**Git repository url:*https://github.com/jakobzhao/storymap* 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@jakobzhao this library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by jakobzhao** [comment]
Thank you so much! I am currently teachings students on digital storytelling with web maps. I guess It would be better if they know more about what is CDN. and you guys did a great job on serving a variety of libraries. Sure, I will do once it reaches 200 stars.

Thanks again.

Best,
Bo

**Comment by PeterDaveHello** [comment]
@jakobzhao if you can tag each version by git tag, and would like to send a pull request to us, I believe 50 stars in this case would be enough 😊

**Comment by sashberd** [comment]
Hi @jakobzhao 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples).Also git tag was not supported by lib author You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
