### ISSUE TITLE
[Request] Update angular-ui-router

### ISSUE THREAD

**Issue by ncoden** [cdnjs/cdnjs#11865]
The currently hosted package [angular-ui-router](https://cdnjs.com/libraries/angular-ui-router) point to the NPM package [angular-ui-router](https://www.npmjs.com/package/angular-ui-router), but it has been renamed to [@uirouter/angularjs](https://www.npmjs.com/package/@uirouter/angularjs) (see the [package.json](https://github.com/angular-ui/ui-router/blob/master/package.json)).

- [angular-ui-router](https://www.npmjs.com/package/angular-ui-router): published by [christopherthielen](https://www.npmjs.com/~christopherthielen), latest version is v1.0.3.
- [@uirouter/angularjs](https://www.npmjs.com/package/@uirouter/angularjs): published by [christopherthielen](https://www.npmjs.com/~christopherthielen), latest version is v1.0.6.

**Comment by ncoden** [comment]
Poke @PeterDaveHello @extend1994 @sufuf3 ;)

**Comment by sufuf3** [comment]
Thank you. We'll update ASAP.

**Comment by sufuf3** [comment]
Duplicated with #11713
move to #11713
work on #11714
