### ISSUE TITLE
[Request] Add riotgear version 2

### ISSUE THREAD

**Issue by elieobeid7** [cdnjs/cdnjs#11879]
https://riotgear2.github.io/

their cdn link points to version one, possibly because they were unable to get jsdeliver to host it, it would be nice if you could host their library. I'm not affiliated with them, in fact I started learning riotjs yesterday, wanted to add charts and saw riotgearv2

**Comment by sufuf3** [comment]
@elieobeid7 Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.
