### ISSUE TITLE
[Request] Add w3.css

### ISSUE THREAD

**Issue by 9thQuadrant** [cdnjs/cdnjs#11872]
**Library name:** w3.css
**Library desctiption: A CSS framework for easier contruction of pages which offers material design in an easier manner** 
**Official homepage: https://www.w3schools.com/w3css/** 

=====================

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@9thQuadrant Is there any repository of this lib?
Thank you.

**Comment by 9thQuadrant** [comment]
I think there is no repository, it is created by w3schools website.
It was just a css file and there is also a w3.js in the same website.

On 26 Sep 2017 2:18 p.m., "Samina Fu" <notifications@github.com> wrote:

@9thQuadrant <https://github.com/9thquadrant> Is there any repository of
this lib?
Thank you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdnjs/cdnjs/issues/11872#issuecomment-332130769>, or mute
the thread

**Comment by sufuf3** [comment]
@PeterDaveHello How can we do for this issue?
I also can't find the repo of this lib.
Thanks.

**Comment by 9thQuadrant** [comment]
I'll add repo and ping you shortly

On 26 Sep 2017 7:24 p.m., "Samina Fu" <notifications@github.com> wrote:

@PeterDaveHello <https://github.com/peterdavehello> How can we do for this
issue?
I also can't find the repo of this lib.
Thanks.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cdnjs/cdnjs/issues/11872#issuecomment-332205518>, or mute
the thread

**Comment by PeterDaveHello** [comment]
Please create the new issue once the repository is created, please also refer to our document for the popularity requirement, thanks a lot.
