### ISSUE TITLE
[Request] Add kindeditor

### ISSUE THREAD

**Issue by hstarorg** [cdnjs/cdnjs#11875]
**Library name:** kindeditor
**Library desctiption:** WYSIWYG HTML editor
**Git repository url:** https://github.com/kindsoft/kindeditor
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):**  LGPL-2.1
**Official homepage: ** http://kindeditor.net/demo.php
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #6153
close and move to #6153 
cc @PeterDaveHello
