### ISSUE TITLE
[Request] Add elementTransitions.js

### ISSUE THREAD

**Issue by Deepak02mb** [cdnjs/cdnjs#11887]
**Library name:** elementTransitions.js
**Library description:** 
**Git repository url:** https://github.com/dan-silver/ElementTransitions
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** https://dan-silver.github.io/ElementTransitions/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Deepak02mb any details please?

**Comment by sashberd** [comment]
@sufuf3 No git tag with this lib, and no place to open issues inside project
FYI

**Comment by sufuf3** [comment]
@sashberd Yes, you're right!
Thank you for reminding.
Would you like to discuss with the author about adding [git tag](https://github.com/dan-silver/ElementTransitions/tags)?
We can help the open source library better and better. :)
Thank you.

**Comment by sashberd** [comment]
@sufuf3 There is no discuss option!?!?! No issues tab at all inside this project

**Comment by sufuf3** [comment]
@sashberd It's a bad news. 😢 
but I think we can manually add v0.2.1 https://github.com/dan-silver/ElementTransitions/tree/0daad5cce56e2ce7b1bff270f565c5affbacee64
What do you think?

Many thanks.

**Comment by PeterDaveHello** [comment]
Maybe just tweet him about that? I prefer not to manually add it, that's the latest option.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
