### ISSUE TITLE
AlaSQL v0.4.2 throws exception when exporting to excel (XLS) multiple times

### ISSUE THREAD

**Issue by sarveshascbe** [cdnjs/cdnjs#11885]
I am using AlaSQL v0.4.2 for exporting a javascript array object to excel.

Used following options :+1: 
alasql.options.cache = false;
alasql.options.logtarget = 'console';

var mystyle = {
				            headers: true,
				            sheetid: 'Counter Correction',
				        };

var excelObj = alasql('SELECT * INTO XLS("XYZ.xls",?) FROM ?', [mystyle, counterCorrectionData]);

counterCorrectionData is my actual array.

After exporting to XLS file once, i tried several times with less than or equal to the attached excel sheet records - approx - 10000 records with 88 columns.

After 3 + re-execution of excel export i do get this error in IE 11, IE 9 and IE 10. "not enough storage is available to complete this operation"

The Headers are the columns in my Javascript object array - counterCorrectionData

Please look into and let me know what is the issue and resolve as soon as possible.

Attached is the generated exported excel file.
[CounterCorrectionRevised.zip](https://github.com/cdnjs/cdnjs/files/1336083/CounterCorrectionRevised.zip)

**Comment by sufuf3** [comment]
@sarveshascbe CDNJS is web public CDN. So we just host the lib as the same with upstream.
would you discuss with upstream https://github.com/agershun/alasql/issues about your question?
Thank you.

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
