### ISSUE TITLE
[Request] Add ui-router

### ISSUE THREAD

**Issue by amitthore** [cdnjs/cdnjs#11880]
**Library name:** angular-ui-router
**Library desctiption:** 
**Git repository url:** 
**npm package name or url** (if there is one): https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/1.0.3/angular-ui-router.js.map
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
i want this file

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
#11714 need to work on this

**Comment by MattIPv4** [comment]
Looks like this was merged & resolved, closing.
