### ISSUE TITLE
[Request] Add cta.js

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#11889]
**Library name:** cta.js
**Git repository url:** https://github.com/chinchang/cta.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/cta
**License:**  MIT
**Official homepage:** https://kushagragour.in/lab/ctajs/

---
### ℹ️  introduction
CDNJS is one of the most famous free and public web front-end CDN services. We'd like to host a new web front-end library on CDNJS so that web developer can easily use this library on our free CDN without any additional download/upload process.

### 📚  How to add a library
There are two ways to send a pull request(PR):
- [ ] 1. [**Adding a new library via a single package.json**](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)
  1. Creating a `package.json` under `ajax/libs/<LIBRARY_NAME>`
  2. Edit the `package.json`.
      - Required fields: `name`, `description`, `filename`, `license`, `repository`, `author`, `keywords`, auto-update config
      - Non-Required fields (If there is no field of the upstream): `homepage`
  3. Save the file and send a PR with the commit message as the followings example with git auto-update (if you use npm auto-update, please change from git to npm):
  This will be useful to us to maintain the git log and trace the history.
```
Add <LIBRARY_NAME> w/ git auto-update via single package.json

close <#THIS_ISSUE_NUMBER>, cc <@AUTHOR>
```

- [ ] 2. [**Adding a new library with its assets**](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)
  1. Creating a <LIBRARY_NAME> folder under `ajax/libs/`
  2. Edit the `package.json` under `ajax/libs/<LIBRARY_NAME>`.
      - Required fields: `name`, `description`, `filename`, `version`, `license`, `repository`, `author`, `keywords`, auto-update config
      - Non-Required fields (If there is no field of the upstream): `homepage`
  3. Create a folder named after the latest release version under `ajax/libs/<LIBRARY_NAME>`.
  4. Add the files from upstream to `ajax/libs/<LIBRARY_NAME>/<VERSION>`. The file with `md5sum` should as same as upstream.
  5. Save the file and send a PR with the commit message as the followings example with git auto-update (if you use npm auto-update, please change from git to npm):
  This will be useful to us to maintain the git log and trace the history.
```
Add <LIBRARY_NAME>@<VERSION> w/ git auto-update

close <#THIS_ISSUE_NUMBER>, cc <@AUTHOR>
```

If you still don't know how to add a library, here is a tutorial in [document](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md), hope this will help you to understand.

### 💻  How to send a pull request
There are two ways to add a library, via GitHub website or locally.
- [ ] 1. **GitHub website**
- [ ] 2. **locally (Use Git command)** 
  - Using **sparseCheckout**
    Because cdnjs's repo is too huge, currently. It's better to use `sparseCheckout` to lets you only check out the files you want so that the whole directory can only occupy 2.2 GB in your computer. Here is a [tutorial](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md) which let you know how to enable sparseCheckout.
  - If you don't know how to create a pull request locally, please take a look at this [tutotial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

### 🤖  How to setup auto-update config
The auto-update config can automatically add libraries to the latest version easily. [Here](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md) is the document which can help you to know how to setup auto-update config. 
BTW, in `files` field, we'd like to let it be flexible but if there are some files not necessary to host, we will use some pattern to match and exclude them. There are many example configurations in [document](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md), hope this will help you to understand. 

### :memo: Note
If you are interested in joining us and help add this library, please feel free to check what way you'd like to **add a library** and  **send a pull request**. And let me know what kind of help you'll need, we'll help you send the valid pull request, thank you. 😃

**Comment by iamstratos** [comment]
I'd like to work on this one :)

**Comment by sufuf3** [comment]
👍
