### ISSUE TITLE
[Request] Add ng-browser-info 

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#11890]
**Library name:** ng-browser-info
**Repository url:** https://github.com/transferwise/ng-browser-info
**npm package url:** none
**License:** [Apache-2.0](https://github.com/transferwise/ng-browser-info/blob/master/LICENSE)
**Official homepage:** http://transferwise.github.io/ng-browser-info/

## Something you might want to know about CDNJS
CDNJS provides a CDN containing front-end libraries to allow all the web developers from around the world to use the libraries on our free CDN without any additional download/upload process.

## How to deal with this issue?
You can choose to add the library via single package.json or with its required assets. As for the working environment, you can choose to work on the GitHub GUI or on your computer (locally).
Working locally will let you learn git (version control) and debug skills. However, it needs more spaces on your computer in comparison with using GitHub. So don't feel any pressure if you want to use the GitHub GUI. If you decide to work locally, it's recommend to pulling cdnjs repository with [sparseCheckout](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md ) because the cdnjs repo is too huge.

The followings are the useful steps to let you add the requested library with the GitHub GUI  in an easier way. :muscle:
### Via single package.json
1. [Fork](https://github.com/cdnjs/cdnjs/fork) the cdnjs repo and do the following steps on your forked repo.
2. Create a new, non-master branch by clicking the "Branch: master" dropdown and enter the name of the library being added.
3. Create the file `<lib_name>/package.json` under `ajax/libs` directory by clicking "Create new file" button. You will see the part of the screen like this image <img width="477" alt="2017-09-01 1 39 56" src="https://user-images.githubusercontent.com/13430892/29956675-18f5eb68-8f1b-11e7-896b-7f595cba0181.png">
Find the package.json (or bower.json if there is no package.json) in source repo (including npm). Please copy its content and modify the content if the content doesn't match the format of package.json in cdnjs. There are 9 fields we may need in total here. Other than these fields, please remove them.
* Necessary ones: `name`, `filename`, `description`, `keywords`, `repository`, `author`, `license` and "npm auto-update" (or "git auto-update")
  * `name`: library name, please use the GitHub repo name if the source is GitHub, please use npm package name if the source is npm.
  * `filename`: Find the main file of this library, you might be able to find it after reading its documentation. If the main file is not minified, please still use `<filename>.min.js` or `<filename>.min.css` structure naming, we'll do the minify job.
  * `author`: There might be more than one author. Please use `authors` instead when there are multiple authors.
  * `license`: There also might be more than one license. Please use `licenses` when there are multiple licenses.
  * npm auto-update or git auto-update: Please follow https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md. There are a few rules to help you choose GitHub or npm to be the source. The simplest rule you can use here is to choose the one with more versions. If the number of versions are the same, please use npm because we prefer it.
* Unnecessary: `homepage` if it's the same as the source repo or just a demo page with no link to its source repo.

  Last, please use [JSONLint](http://jsonlint.com/) to validate your package.json. 
4. Commit new file: 
* The heading of the commit message
  * If the source is git: `Add <lib_name> w/ git auto-update via single package.json`
  * If the source is npm: `Add <lib_name> w/ npm auto-update via single package.json`
* The body of the commit message: `close #<issue_number>, cc @<lib_author>`
5. Submit the pull request in cdnjs repo and fill out the asked information to make sure that everything you can do is good.
[Example 1](https://github.com/extend1994/cdnjs/blob/99b1a5ca8de29b6fa96468d417befa093841bba7/ajax/libs/videojs-ima/package.json), [Example 2](https://github.com/extend1994/cdnjs/blob/91d227960987d08efadc95f7719cb2ab5b9614f7/ajax/libs/gotem/package.json), [Official document](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)

### With library assets
1. The same as the step 1 in the method "via single package.json".
2. The same as the step 2 in the method "via single package.json".
3. Similar to the the method "via single package.json". But here we need the other necessary field: `version` which is the latest stable version. And please create package.json locally and upload it with step 4. Also, don't forget to use [JSONLint](http://jsonlint.com/) to validate your package.json.
4. Every library should be stored under the `ajax/libs` directory. It has its own sub-directory of `ajax/libs` and each version of the library has its own sub-directory of the library directory name, for example: `/ajax/libs/jquery/3.2.1/`. Find the files from the latest stable version this library needs to run on a browser well (which are also the files you list in `files` field of auto-update config in package.json) and upload them according to their versions. Note every file should be the completely the same as every file in the upstream. Make everything is alright with the command `npm test` if you work locally.
5. Commit the files:
* The heading of the commit message: 
  * If the source is git: `Add <lib_name> w/ git auto-update`
  * If the source is npm: `Add <lib_name> w/ npm auto-update`
* The body of the commit message: `close #<issue_number>, cc @<lib_author>`
6. The same as the step 5 in the method "via single package.json".
[Example](https://github.com/cdnjs/cdnjs/pull/10452/files), [Official document](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)

### Work locally
Some useful commands:
1. Pull the repo from cdnjs repo
```
git pull origin master
```

2. Create a non-master branch from master branch.
```
git checkout -b <lib_name>
```

3. Commit the files, with `-v` you can see more detailed information
```
git commit [-v]
```

4. Revise your last commit message
```
git commit --amend [-v]
```

5. Push to GitHub, add `-f` if you want to update your remote branch.
```
git push <remote_name_you_name_for_your_forked_cdnjs_repo> <branch_name> [-f]
```

Feel free to ask some questions if you have any, we will help you as soon as possible. Now don't hesitate to become a contributor of CDNJS :smile:

## References
For more details you can try to refer [our contributing document](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) or [the contributing document from GitHub](https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project)

**Comment by bpadair32** [comment]
I will work on this

**Comment by PeterDaveHello** [comment]
@bpadair32 nice!
