### ISSUE TITLE
[Request] Add sticky

### ISSUE THREAD

**Issue by samir-jorge-araujo** [cdnjs/cdnjs#11900]
**Library name:** Sticky-js
**Library description:** Sticky-js is a library for sticky elements written in vanilla javascript. With this library you can easily set sticky elements on your website. It's also responsive.
**Git repository url:** https://github.com/rgalus/sticky-js
**npm package name or url** (if there is one): https://www.npmjs.com/package/sticky-js
**License (List them all if it's multiple):** MIT
**Official homepage:** https://rgalus.github.io/sticky-js/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nersoh** [comment]
Can I try this one?

**Comment by PeterDaveHello** [comment]
@nersoh sure, please.

**Comment by nersoh** [comment]
Hey, @PeterDaveHello. What is the easiest way to clone the project? I've tried to download it but the download failed after 3.9GB, and thought Git it took hours of downloading and checking files, which made me to cancel.

**Comment by abdulamite** [comment]
@nersoh Do you have sparse checkout set up and enabled?

**Comment by sufuf3** [comment]
@abdulamite Thank you :)
@nersoh  We have a tutorial of sparseCheckout, you can take a look about it --> https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

Thank you for your join! :)

**Comment by nersoh** [comment]
@sufuf3 @abdulamite Thank you guys, I'll check that out 😃
