### ISSUE TITLE
[Request] Build and update brain missing versions manually

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11904]
**Library name:** brain
**Git repository url:** https://github.com/harthur/brain
**npm package name or url**: https://www.npmjs.com/package/brain 

We got only v0.6.3 in the repository, looks like there is no pre-built files in its npm registry and the git repository, which means you need to go through all the versions, clean up and install their dependencies, build the dist files, and even rename the files.

This is a manual work and can be partially or fully automatically by shell scripts, just make sure there is mechanism to catch any error during the build to prevent you mess the whole thing up(very common issue), if you can handle it properly, I believe that the script will make you learned something and help save your time!

**Comment by sufuf3** [comment]
@PeterDaveHello  As https://github.com/BrainJS/brain.js#brainjs mention the brain.js is a continuation of the harthur/brain repository and harthur/brain is not maintained anymore.
Maybe we can close this issue and move to #12281 What do you think?
Thank you.
