### ISSUE TITLE
[Request] Add webvr-polyfill

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11901]
**Library name:** webvr-polyfill
**Library description:** A JavaScript implementation of the WebVR spec. This project lets you use WebVR today, without requiring a special browser build. It also lets you view the same content without requiring a virtual reality viewer.
**Git repository url:** https://github.com/googlevr/webvr-polyfill/
**npm package name or url**: [webvr-polyfill](https://www.npmjs.com/package/webvr-polyfill)
**License:** Apache-2.0 
**Official homepage:** https://googlevr.github.io/webvr-polyfill/

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by andrew-anguiano** [comment]
@PeterDaveHello I'll give this a shot!

**Comment by PeterDaveHello** [comment]
Nice @andrew-anguiano
