### ISSUE TITLE
[Request] Add TiltHoverEffects

### ISSUE THREAD

**Issue by AshwiniBS** [cdnjs/cdnjs#11920]
**Library name:** TiltHoverEffects
**Library description:** Some ideas for hover effects with a fancy tilt effect. Inspired by the effect seen on Kikk 2015 made by Dogstudio.
**Git repository url:** https://github.com/codrops/TiltHoverEffects/
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Duplicated with #11414
close this issue and move to #11414
Thanks.
cc @PeterDaveHello
