### ISSUE TITLE
Add/Update a few fields in package.json

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#11931]
This issue is mainly for Hacktoberfest hackathon on Oct 2 2018 in NCTU, Taiwan.

The text you see is the library name in cdnjs, the link is directing you to find the related info.
## Add/Update license field
- Reference license lists:
  - [spdx license list](https://spdx.org/licenses/)
  - [cdnjs license list](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json)
- [x] [ekko-lightbox](https://github.com/ashleydw/lightbox/blob/master/LICENSE#L1)
- [x] [embedly-jquery](https://github.com/embedly/embedly-jquery/blob/master/LICENSE)
- [x] [equalize.js](https://github.com/tsvensen/equalize.js#legal)
- [x] [intercom.js](https://github.com/diy/intercom.js#license)
- [x] [jo](https://github.com/davebalmer/jo/blob/ec767af487b8653778c36168c7b3a5f478753cc5/LICENSE.mdown) BSD-2-Clause
- [x] [jqPlot](https://github.com/jqPlot/jqPlot/#legal-notices)
- [x] [jquery-form-validator](http://www.formvalidator.net/#license)
- [x] [jquery-mockjax](https://github.com/jakerella/jquery-mockjax#license)
- [ ] [jquery.blockUI](https://github.com/malsup/blockui#copyright-and-license)
- [x] [jquery.collapsible](https://github.com/juven14/Collapsible/blob/master/LICENSE)
- [x] [jquery.form](https://github.com/jquery-form/form#license)
- [x] [jquery.mb.YTPlayer](https://github.com/pupunzi/jquery.mb.YTPlayer/tree/master/licences)
- [x] [machina.js](https://github.com/ifandelse/machina.js/blob/master/LICENSE)
- [ ] [placeholder-shiv](https://github.com/walterdavis/placeholder-shiv/blob/master/LICENSE.txt)
- [x] [jquery.tablesorter](https://github.com/mottie/tablesorter/#licensing)
- [ ] [webkit.js](https://webkit.org/licensing-webkit/) https://github.com/trevorlinton/webkit.js#License
- [ ] [fatcow-icons](http://www.fatcow.com/free-icons) See Terms of Use Creative Commons Attribution 3.0 License -> CC-BY-3.0
- [ ] [log4javascript](http://log4javascript.org/)
- [x] [legojs](https://github.com/ahager/legojs/blob/master/LICENSE.txt)
- [x] [protovis](https://github.com/mbostock/protovis) - See https://mbostock.github.io/protovis/ for BSD-2-Clause 
- [x] [repo.js](https://github.com/darcyclarke/Repo.js.git) - MIT
- [ ] [roundabout](https://github.com/fredleblanc/roundabout/blob/master/jquery.roundabout.js#L11-L40) - BSD-3-Clause
- [x] [skycons](https://github.com/darkskyapp/skycons.git) - CC0-1.0
- [x] [Vague.js](https://github.com/GianlucaGuarini/Vague.js/blob/master/Vague.js#L9-L31) - MIT
- [ ] [bootstrap-validator](https://github.com/nghuuphuoc/bootstrapvalidator/blob/master/LICENSE.txt#L4-L5) - CC-BY-NC-ND-3.0
- [ ] [jquery.bootstrapvalidator](https://github.com/nghuuphuoc/bootstrapvalidator/blob/master/LICENSE.txt#L4-L5) - CC-BY-NC-ND-3.0
- [x] [jshashes](https://github.com/h2non/jshashes/blob/master/LICENSE) - BSD-3-Clause
- [x] [yepnope](https://github.com/SlexAxton/yepnope.js/blob/master/LICENSE.md)
- [x] [ionic](https://github.com/ionic-team/ionic/blob/master/LICENSE#L4)
- [x] [ionicons](https://github.com/ionic-team/ionicons/blob/master/LICENSE)
- [x] [jit](https://github.com/philogb/jit/blob/master/LICENSE)
- [ ] [jquery.pin](https://github.com/webpop/jquery.pin#license) - BSD-2-Clause 
- [x] [Snowstorm](https://github.com/scottschiller/Snowstorm/blob/master/license.txt)
- [ ] [jquery-ui-map](https://github.com/crfroehlich/jquery-ui-map/blob/master/LICENSE)
- [ ] [jquery.pep](https://github.com/briangonzalez/jquery.pep.js#license)

* More complex ones
  - [ ] [mixitup](https://www.kunkalabs.com/mixitup/licenses/) Commercial license & CC-BY-ND-3.0 See https://www.kunkalabs.com/mixitup/licenses/ Do I need to pay for extensions if my project is non-commercial? 
  - [ ] [jQuery.dotdotdot](https://github.com/FrDH/jQuery.dotdotdot#licence)  CC-BY-NC-4.0 and commercial
  - [ ] [emojione](https://github.com/emojione/emojione/blob/master/LICENSE.md)
  - [ ] [jvectormap](https://github.com/bjornd/jvectormap)
  See an example: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery-infinitescroll/package.json#L33-L39

## Add repository info
- [ ] [1140](https://github.com/andytlr/cssgrid)
- [x] [jcalculator](https://github.com/balajmarius/jcalculator)

## Add/Update multiple fields
- [x] [expect.js](https://github.com/Automattic/expect.js): license & repo
- [ ] [jcalculator](https://github.com/balajmarius/jcalculator): homepage & repo
- [ ] [jquery.selectboxit](https://github.com/gfranko/jquery.selectBoxIt.js): author, license & repo
- [ ] [polyglot](https://github.com/tavyy/Polyglot-Language-Switcher): repo, [author](https://github.com/tavyy/Polyglot-Language-Switcher/blob/master/js/jquery.polyglot.language.switcher.js#L8-L9) & [MIT license](https://github.com/tavyy/Polyglot-Language-Switcher/blob/master/js/jquery.polyglot.language.switcher.js#L10)
- [x] [antimoderate](https://github.com/whackashoe/antimoderate): repo &  MIT license update
- [ ] [jquery-ui-bootstrap](https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap): [homepage](https://jquery-ui-bootstrap.github.io/jquery-ui-bootstrap/) & license
- [ ] [qoopido.js](https://github.com/dlueth/qoopido.js): [license](https://github.com/dlueth/qoopido.js/blob/master/package.json#L18-L26) & [homepage](https://www.qoopido.com)
- [ ] [dplayer](https://github.com/MoePlayer/DPlayer): [MIT license](https://github.com/MoePlayer/DPlayer/blob/master/LICENSE) & repo

Please pick one and leave comment below. Thanks!

**Comment by Billy4195** [comment]
Hi~
I want to modify `Add/Update license field --- ionicons `

**Comment by baili0411** [comment]
I'll add repository info for jcalculator

**Comment by ralphchung** [comment]
Hello
I want to modify jit

**Comment by ycchan5566** [comment]
Hello everyone~
I want to modify machina.js

**Comment by finch185277** [comment]
Hello
I want to modify jquery.roundabout.min.js

**Comment by AikoChou** [comment]
modify ionic license

**Comment by yubin551** [comment]
I want to modify  jqPlot

**Comment by Vamshi99** [comment]
I will add repository information for 1140

**Comment by Ryan0413242** [comment]
Hello
I want to modify jquery.form

**Comment by iylim** [comment]
i'll take the boostrap validator

**Comment by SamMauldin** [comment]
I'll take the one for mixitup

**Comment by adriancerejo** [comment]
Taking placeholder-shiv

**Comment by MattIPv4** [comment]
Most of these have now been resolved. Once we've completed the repository migration we can look at automatically generating a new list of libs with missing fields.
