### ISSUE TITLE
[Request] Update cellx auto-update config 

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#11932]
We need a new auto-update config because cellx v1.7.59+ seem to have files we don't need under current basePath.

**Comment by PeterDaveHello** [comment]
Would anyone in @cdnjs/intern4 like to try?

**Comment by finch185277** [comment]
I want to try it.

**Comment by PeterDaveHello** [comment]
@finch185277 👍

**Comment by finch185277** [comment]
@extend1994
what's problem in basePath

**Comment by PeterDaveHello** [comment]
@finch185277 you better take a deeper look first 😉

**Comment by MattIPv4** [comment]
Files look fine for new versions: https://cdnjs.com/libraries/cellx/1.10.4
