### ISSUE TITLE
[Request] Add imgmap

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#11933]
**Library name:** imgmap
**Library description:** 
**Git repository url:** https://github.com/maschek/imgmap
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
this library is useful for image editor online, just like html editor wysiwyg.
hope this library can be add to CDNJS service for use.

**Comment by qwe19272375** [comment]
Hi @ihsinhw ,
Thanks for your suggestion. This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [CONTRIBUTE.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library). Would you mind to open an issue again when the library has more popularity? 😄

**Comment by sufuf3** [comment]
Closed due to no response in 7 days. cc @PeterDaveHello
