### ISSUE TITLE
[Request] Add w3.css (Re-open)

### ISSUE THREAD

**Issue by 9thQuadrant** [cdnjs/cdnjs#11966]
**Library name:** w3.css
**Library desctiption:** Contains no conflict version of materilaize.css with w3.css and w3.css itself
**Git repository url:** https://github.com/9thQuadrant/w3css
**License (List them all if it's multiple):** MIT
**Official homepage:** [https://materializecss.com](url) , [https://w3schools.com/w3css](url)

**Comment by extend1994** [comment]
Hi @9thQuadrant 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:  Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want! This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 
Thank you for your contribution!

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity, cc @PeterDaveHello
