### ISSUE TITLE
[Request] Add file-upload-with-preview

### ISSUE THREAD

**Issue by hcaz** [cdnjs/cdnjs#11968]
**Library name:** file-upload-with-preview
**Library description:** This is a simple frontend utility to help the file-upload process on your website. It is written in pure JavaScript, has no dependencies, and is a small 13.55 kB (gzipped).
**Git repository url:** https://github.com/promosis/file-upload-with-preview
**npm package name or url** (if there is one): file-upload-with-preview
**License (List them all if it's multiple):** MIT
**Official homepage:** https://promosis.github.io/file-upload-with-preview/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @hcaz 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:  Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want! This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 
Thank you for your contribution!

**Comment by extend1994** [comment]
Close this due to no response and insufficient popularity, cc @PeterDaveHello
