### ISSUE TITLE
[Request] Add leaflet-terminator

### ISSUE THREAD

**Issue by Siliconrob** [cdnjs/cdnjs#11962]
**Library name:** leaflet-terminator
**Library description:** Allows a leaflet map to display night/day
**Git repository url:** https://github.com/joergdietrich/Leaflet.Terminator
**npm package name or url** (if there is one): https://www.npmjs.com/package/leaflet-terminator
**License (List them all if it's multiple):** ISC
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @Siliconrob The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: We suggest you open a issue again when the repo has notable popularity. This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. Thank you for your contribution!

**Comment by extend1994** [comment]
Close this due to no response and insufficient popularity, cc @PeterDaveHello
