### ISSUE TITLE
[Request] Add tracing.js

### ISSUE THREAD

**Issue by qwe19272375** [cdnjs/cdnjs#11973]
## Overview
**library**: tracing.js
**git repository url**: https://github.com/ebobby/tracing.js
**npm package url**: 
**license**: [MIT](https://github.com/ebobby/tracing.js/blob/master/COPYING)
**homepage**: 

## How to contribute
* Fork CDNJS and setup your own work environment
* CDNJS is a large repository like around 80GB, maybe you need to set up [sparse-checkout](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md) before pulling
* There are two ways to add a new library
    * [Add a single package.json of the library with valid CDNJS auto-update setup](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)
    * [Adding a new library with its assets]
(https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)

### About package.json
Leave fields with list under and remove others
```
name
filename
version
author
license
description
keywords
homepage (can be omitted if same with GitHub repository)
repository
```
#### Setup CDNJS auto-update
For npm auto-update, use:
```js
"npmName": "<fill in name>",
  "npmFileMap": [
    {
      "basePath": "<base file directory path>",
      "files": [
        "<main sources in directory>"
      ]
    }
  ]
```
For git auto-update, use this `autoupdate` field in package.json:
```js
"autoupdate": {
    "source": "git",
    "target": "git://github.com/<some author>/<library>",
    "fileMap": [
      {
        "basePath": "<base file directory path>",
        "files": [
          "<main sources in directory>"
        ]
      }
    ]
  }
```

## Some tips
- [x] Run `npm test` before push
- [x] Run `tools/fixformat.js` to fix wrong indent in `package.json`
- [x] Make sure the commit message is clear enough
- [x] Make sure to send PR from non-master branch

---

Please feel free to ask if you need any kind of help. 😄 
If you need further information, check [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)

**Comment by tulikavijay** [comment]
Can I take this up?

**Comment by PeterDaveHello** [comment]
@tulikavijay Sure please.
