### ISSUE TITLE
[Request] Add jquery-ajax-unobtrusive (ASP.NET Core)

### ISSUE THREAD

**Issue by vaindil** [cdnjs/cdnjs#11976]
**Library name:** jquery-ajax-unobtrusive
**Library description:** Part of ASP.NET Core, allows use of `data-` attributes for forms
**Git repository url:** https://github.com/aspnet/jquery-ajax-unobtrusive
**npm package name or url (if there is one):** N/A
**License (List them all if it's multiple):** Apache 2.0
**Official homepage:** N/A

This repo specifically doesn't have a ton of activity, but it's part of ASP.NET Core and IMO should be included.

**Comment by sufuf3** [comment]
As [README](https://github.com/aspnet/jquery-ajax-unobtrusive#jquery-unobtrusive-ajax) said, this project is part of [ASP.NET Core](https://github.com/aspnet/home). 
Although, this library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). But ASP.NET Core has over 6000 stars.
I think this lib is fine to be added.
Thanks.

**Comment by GerkinDev** [comment]
The [npm package](https://www.npmjs.com/package/jquery-ajax-unobtrusive) has about 1700 downloads weekly, so it meet the requirements for inclusion in CDNJS. Moreover, even if it has less downloads/stars, most people use the local copy of this script, used on many ASP.NET sites. Offering the ability to use CDN would help many people using currently the local copy.

Cheers, and thank you for that amazing service. I owe you litters of beer.

**Comment by iMusashi** [comment]
jquery-ajax-unobtrusive could be downloaded earlier using Nuget Package Manager to be referenced in client side scripts for MVC Projects. 

With the latest .NET Core 2.1 update, we cannot reference Nuget package directly in client side scripts but have to download them using npm, bower or some other package manager. Bower, unfortunately, is ending their support and hence npm becomes the obvious choice. 

To make the tooling simple for .NET Users and remove the dependency on npm or other package managers (if not required), Microsoft has created a tool 'Library Manager' that is inbuilt in Visual Studio and is delivered in the last update, which allows users to download client side scripts from cdn servers. Library Manager provides three sources by default: cdnjs, unpkg and filesystem.

I am able to find almost all the files using the above sources except jquery-ajax-unobtrusive. It will be great, if these files are added, thanks.

**Comment by xtuc** [comment]
Closing in favor of https://github.com/cdnjs/cdnjs/issues/12790
