### ISSUE TITLE
[Request] Add quasarframework/quasar

### ISSUE THREAD

**Issue by Iworb** [cdnjs/cdnjs#11985]
**Library name:** Quasar framework
**Library description:** frontend framework for vue.js
**Git repository url:** https://github.com/quasarframework/quasar
**License (List them all if it's multiple):** MIT
**Official homepage:** http://quasar-framework.org
**Wanna say something? Leave message here:** Now it supports UMD build, so I hope it will be included in cdnjs to make it available for online editor like jsfiddle, jsbin, etc.

**Comment by sufuf3** [comment]
@Iworb Thank you.
This is a good news.
Could you tell us that which files can be added on CDNJS?
Sorry that I'm not familiar with this lib.
Thanks.

**Comment by Iworb** [comment]
They're not provide any build by default and it's need to `npm run build` to get all variations of builds (UMD, ES6) with styles.

**Comment by Iworb** [comment]
I missed it, but there's `build` [directory](https://github.com/quasarframework/quasar/tree/v0.14/build) with compiled sources. Link

**Comment by Iworb** [comment]
Any news?

**Comment by sufuf3** [comment]
@Iworb Sorry.
CDNJS didn't build the files by it's own.
Would you discuss with the lib's author to produce the web frond-end files, maybe?
It will useful to us let the lib to be added.

Thank you.

**Comment by extend1994** [comment]
Hi there @Iworb @sufuf3 
I think it has distribution on npm. So I will add it.
If you have any other info or suggestion. Please tell me :)
