### ISSUE TITLE
[Request] Add clipboard-polyfill

### ISSUE THREAD

**Issue by Lukas238** [cdnjs/cdnjs#11994]
**Library name:** clipboard-polyfill
**Library description:** Make copying on the web as easy as: ```clipboard.writeText("This text is plain.");```
**Git repository url:** https://github.com/lgarron/clipboard-polyfill
**npm package name or url** (if there is one):  https://www.npmjs.com/package/clipboard-polyfill
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/lgarron/clipboard-polyfill
**Wanna say something? Leave message here:**  

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by jbutz** [comment]
I'll work on adding this, shouldn't be too bad
