### ISSUE TITLE
[Request] Add EventDrops

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#11999]
**Library name:** EventDrops
**Library description:** A time based / event series interactive visualization using d3.js 
**Git repository url:** https://github.com/marmelab/EventDrops
**npm package name or url**: [event-drops](https://www.npmjs.com/package/event-drops)
**License:** MIT
**Official homepage:** https://marmelab.com/EventDrops/

=====================

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by austin665** [comment]
Hi @PeterDaveHello I would love to take this! I am a beginner but will definitely look into this and may ask you more questions. Thanks!

**Comment by PeterDaveHello** [comment]
@austin665 Great 👍

**Comment by VarunWachaspati** [comment]
@PeterDaveHello  Kindly review my PR https://github.com/cdnjs/cdnjs/pull/12000 and let me know if there any issues

**Comment by PeterDaveHello** [comment]
@VarunWachaspati thanks! Please give us more time to review it, will do it ASAP!
(Tons of PRs on the review queue, sorry!)

**Comment by austin665** [comment]
@PeterDaveHello Oops! Does this mean I shouldn't send my PR anymore?

**Comment by PeterDaveHello** [comment]
@austin665 nope, but we can fix this one first.

**Comment by austin665** [comment]
@PeterDaveHello I sent a PR #12002 , please let me know if there are any issues. This is my first PR ever. Cheers :)

**Comment by PeterDaveHello** [comment]
@austin665 cool, thanks for the PR, I'll take a look at it soon, before that, you can take a look at the CI test result and kick off the issues if there are any!

**Comment by austin665** [comment]
@PeterDaveHello Yes, there was one issue and I fixed it. It says all checks are passing now!!!

**Comment by PeterDaveHello** [comment]
@austin665 awesome! I'll review it ASAP!

**Comment by maruilian11** [comment]
@austin665 Sorry, I think Peter didn't notice there are two duplicated PR for this issue. We usually don't review PRs for the same issue. And I decided to close your PR because it has been a little later than the other. Sorry for wasting your time!

**Comment by austin665** [comment]
@maruilian11  Thanks for getting back! I don't mind wasting time on this issue. The problem though is I commented on this thread informing @PeterDaveHello  that I was working on this issue.  But @VarunWachaspati dude sent a random PR. When his PR didn't go through and was sitting idle I sent mine.  The same is repeated in #11974  as well, where there is a PR being sent by @VarunWachaspati while a PR by another user is being reviewed.   

Sorry if this feels like a rant, but is it not usually that once someone calls out that they are picking up the issue others don't work on the same thing. Like it should not be a race when there are tons of other issues that needs attention. Please correct me if I am wrong, I am still learning :)

**Comment by PeterDaveHello** [comment]
hmmm, @austin665 sorry that I may mislead you and myself from the few comments, the first one I mean we should fix the currently existed PR first, existing PRs didn't mean that you can't send another one, but we need to make sure it's inactive/stale.

I saw your second comment says you sent the PR but I missed the previous one context(excuse but I got too many issues waiting for review ... lol), so I just replied that I'll review it.

To define a stale PR, we usually wait response/update for 7~14 days, depends on the priority of the corresponding issue, so in this case, #12000 is not stale at all, I'm sorry for the inconvenience caused, if you don't mind, I'll like to help you pick and finish another PR, what do you think?

Best,
Peter

**Comment by austin665** [comment]
Hey @PeterDaveHello no problem! You don't have to apologize at all :)   Sure, I would be more than happy to pick up an issue 👍  Happy Coding!

**Comment by PeterDaveHello** [comment]
@austin665 nice 👍
