### ISSUE TITLE
[Request] Add web3.js

### ISSUE THREAD

**Issue by BuonOmo** [cdnjs/cdnjs#12006]
**Library name:** web3.js
**Library description:** Ethereum JavaScript API
**Git repository url:** https://github.com/ethereum/web3.js/
**npm package name or url** (if there is one): web3
**License (List them all if it's multiple):** GNU Lesser General Public License v3
**Official homepage:** 
**Wanna say something? Leave message here:** I can absolutely do the PR, after a few upvotes!

**Comment by chovy** [comment]
should add v1-beta too.
