### ISSUE TITLE
[Request][Author] Add Fontisto

### ISSUE THREAD

**Issue by kenangundogan** [cdnjs/cdnjs#12001]
**Library name:** fontisto
**Library desctiption:** the iconic font and css toolkit (Fontisto gives you scalable vector icons that can instantly be customized — size, color, drop shadow, and anything that can be done with the power of CSS.)
**Git repository url:** https://github.com/kenangundogan/fontisto
**npm package name or url:** https://www.npmjs.com/package/fontisto
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.fontisto.com

**Comment by sufuf3** [comment]
@kenangundogan this library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). 
Would you mind to open an issue again when the library has more popularity? 
If there are no response in 7 days, I will close this issue. 
Thanks for your great work and contribution.

**Comment by extend1994** [comment]
Close this issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by kenangundogan** [comment]
The number of github star is 130, but the download rate from package managers is quite high.

npm, yarn, bower and so on.

Is not enough in this phase.

We are working very hard on this project, we continue to add new versions and features every week.
