### ISSUE TITLE
[Request] Add ckplayer.js 6.8

### ISSUE THREAD

**Issue by pxss** [cdnjs/cdnjs#12009]
**Library name:** ckplayer.js
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@pxss Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

PS. this git repo from https://gitee.com/niandeng/ckplayer but there is no git tags.

**Comment by pxss** [comment]
This js may not have been placed on github, but in China, this js is used very much, and this is its official website: www.ckplayer.com

**Comment by sufuf3** [comment]
@pxss Thanks.
Could you help to discuss with the author about adding [git tag](https://gitee.com/niandeng/ckplayer/tags)?
Because CDNJS add new versions via auto-update config when the library release new versions.
This will be very useful for us to update the versions.

Many thanks.

@PeterDaveHello could we host this lib?
Although, the lib has 132 stars, the number of clicks is 31556 (http://cht.0430.com/cn/web71543/).
Could you give us some suggestion?
Thank you.

**Comment by PeterDaveHello** [comment]
We need at least valid git tags and higher popularity.

**Comment by sashberd** [comment]
Hi @pxss 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). Also no git tag was supported by lib author You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
