### ISSUE TITLE
[Request] Add simple-mask-money

### ISSUE THREAD

**Issue by hmaesta** [cdnjs/cdnjs#12011]
**Library name:** simple-mask-money
**Library description:** Mask money with pure javascript
**Git repository url:** https://github.com/codermarcos/simple-mask-money
**npm package name or url**: simple-mask-money
**License:** (?)
**Official homepage:** http://codermarcos.com/simple-mask-money/

**Comment by sufuf3** [comment]
@hmaesta  Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hmaesta** [comment]
You are right.
Sorry for not reading the Readme with attention. 🤐

**Comment by sufuf3** [comment]
No worries.
Thanks for being interested in CDNJS. 😃
