### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by jfinstrom** [cdnjs/cdnjs#12013]
The link 
http:// www . clarketravis . com
supplied on
https://cdnjs.com/libraries/TableExport
tries to install malware
https://www.travismclarke.com/ seems to be the authors correct site

**Comment by austin665** [comment]
Hi @jfinstrom thanks for bringing this up. I found it directing to the wrong website as well. @PeterDaveHello sent a PR with the changed homepage URL, hope that is all we need to do :smiley:

**Comment by clarketm** [comment]
@jfinstrom @jfinstrom – thanks for bringing this to my attention and resolving it in a timely manner. I apologize for any inconveniences.

**Comment by PeterDaveHello** [comment]
#12014 merged, thank you guys.
