### ISSUE TITLE
[Request] Add numbers.js

### ISSUE THREAD

**Issue by qwe19272375** [cdnjs/cdnjs#12020]
## Overview
**library**: numbers.js
**git repository url**: https://github.com/numbers/numbers.js
**npm package url**: https://www.npmjs.com/package/numbers
**license**: [Apache-2.0](https://github.com/numbers/numbers.js/blob/master/LICENSE)

## How to contribute
* Fork CDNJS and setup your own work environment
* CDNJS is a large repository like around 80GB, maybe you need to set up [sparse-checkout](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md) before pulling
* There are two ways to add a new library
    * [Add a single package.json of the library with valid CDNJS auto-update setup](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)
    * [Adding a new library with its assets](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)

### About package.json
Leave fields with list under and remove others
```
name
filename
version
author
license
description
keywords
homepage (can be omitted if same with GitHub repository)
repository
```
#### [Setup CDNJS auto-update](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md)
For npm auto-update, use:
```js
"npmName": "<fill in name>",
  "npmFileMap": [
    {
      "basePath": "<base file directory path>",
      "files": [
        "<main sources in directory>"
      ]
    }
  ]
```
For git auto-update, use this `autoupdate` field in package.json:
```js
"autoupdate": {
    "source": "git",
    "target": "git://github.com/<some author>/<library>",
    "fileMap": [
      {
        "basePath": "<base file directory path>",
        "files": [
          "<main sources in directory>"
        ]
      }
    ]
  }
```

## Some tips
- [x] Run `npm test` before push
- [x] Run `tools/fixformat.js` to fix wrong indent in `package.json`
- [x] Make sure the commit message is clear enough
- [x] Make sure to send PR from non-master branch

---

Please feel free to ask if you need any kind of help. 😄 
If you need further information, check [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets)

**Comment by bing107** [comment]
Hi @qwe19272375, I'd like to take this issue if its still up for grabs.

**Comment by qwe19272375** [comment]
@bing107 The library of this issue has been added into CDNJS by PR #12022 and this issue should be closed. Thank you!
