### ISSUE TITLE
[Request] Add pug

### ISSUE THREAD

**Issue by billp-rwpc** [cdnjs/cdnjs#12029]
**Library name:** pug
**Library description:** 
https://pugjs.org/js/pug.js 
You only list former and superceded known as "Jade" ... now is "Pug"
I am just a user and have no other interest or association to pug or need for it here.
Just FYI that you are not supporting the latest "jade" now named "pug".
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
https://pugjs.org/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@billp-rwpc this issue seems to be duplicated.

**Comment by billp-rwpc** [comment]
Ok ... thanks.

**Comment by PeterDaveHello** [comment]
PS: we can use issue #10060
