### ISSUE TITLE
[BUG] - Wrong ionicons content in hosted version

### ISSUE THREAD

**Issue by 7php** [cdnjs/cdnjs#12034]
ionicons v2.0.1 is hosted here: [https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css](https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css)

But, the content still has the v2.0.0 version.
Please fix.

**Comment by PeterDaveHello** [comment]
It comes from the upstream repository v2.0.1 tag: https://github.com/ionic-team/ionicons/tree/v2.0.1 / https://github.com/ionic-team/ionicons/commit/ecb4b806831005c25b97ed9089fbb1d7dcc0879c, we can't fix it.

**Comment by 7php** [comment]
Ok well noted. I have created an issue with them. FYI: https://github.com/ionic-team/ionicons/issues/507

Thank you for the response.
