### ISSUE TITLE
[Request] Add themify-icon

### ISSUE THREAD

**Issue by pooyaa** [cdnjs/cdnjs#12046]
**Library name:** themify-icon
**Library description:** Themify Icons is a complete set of icons for use in web design and apps, consisting of 320+ pixel-perfect, hand-crafted icons that draw inspiration from Apple iOS 7 - available to the public, 100% FREE! You may use or distribute it for any purpose, whether personal or commercial. This icon set is a must have tool for web designers and developers.

**Git repository url:** https://github.com/lykmapipo/themify-icons
**npm package name or url** (if there is one): https://themify.me/download/7/
**License (List them all if it's multiple):** free
**Official homepage:** http://themify.me/themify-icons
**Wanna say something? Leave message here:** 
please add this font!!! please

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@pooyaa Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by extend1994** [comment]
Close this issue due to no response and insufficient popularity. cc @PeterDaveHello
