### ISSUE TITLE
[Request] Add workbox

### ISSUE THREAD

**Issue by EskilVisa** [cdnjs/cdnjs#12041]
**Library name: workbox
**Library description: service worker utility
**Git repository url: https://github.com/GoogleChrome/workbox
**npm package name or url** (if there is one):  workbox-sw
**License (List them all if it's multiple):  Apache License, Version 2.0
**Official homepage: https://workboxjs.org/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Enalmada** [comment]
This is the new version of sw-toolbox (https://cdnjs.com/libraries/sw-toolbox) and I am kinda shocked it is not already on cdnjs.

**Comment by sufuf3** [comment]
@EskilVisa @Enalmada Thank you very much.
This lib can be added from npm (the files under `build/importScripts`)
But the filename is combine with version.
Maybe we need to manually add this lib without auto-update config when we send the PR, or discuss with the authors about the filename issue.

Thank you.

**Comment by Enalmada** [comment]
My build process (sbt) doesn't involve npm at all but it is a helpful reminder for those that do.
I also noticed that [jsdelivr](https://www.jsdelivr.com/package/npm/workbox-sw) has it up...another alternative for people until it is up on cdnjs.
workbox is still maturing with a new major version out soon so it is probably a perfect time to discuss with the authors about filename issues.   I can certainly weigh in on why getting it up on cdnjs is critical for a non-npm subset of the community.

**Comment by gauntface** [comment]
We will be removing the version from the filename in V3. Until then it'll be a case of sitting tight.

**Comment by sufuf3** [comment]
@gauntface This is a great news.
Thank you for your support.
We will add this lib ASAP after you release v3.x.x version. :)
tThank you all, guys.

**Comment by Enalmada** [comment]
FYI There seems to be a beta available now with the version not in the filename.   Can cdnjs comment if this is acceptable?
https://storage.googleapis.com/workbox-cdn/releases/3.0.0-beta.1/workbox-sw.js

**Comment by gauntface** [comment]
Would be good to add support while we are in beta in case you need any changes.

**Comment by Enalmada** [comment]
@sufuf3 Workbox 3 is ga!

**Comment by sufuf3** [comment]
Cool. Thanks @EskilVisa 
We will work on this lib ASAP.
Many thanks

**Comment by Billy4195** [comment]
I'd like to helping add this library.

**Comment by chrisblakley** [comment]
[Workbox v4 has been released this week](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0). Any chance we could take a look at this again? At first glance the filenames look like they should work with CDNJS now.

**Comment by samuelcolvin** [comment]
Marked as "High Priority" but open for 1.5 years (and counting). Presumably there must be something blocking this?

Would be wonderful if we could get workbox added.

**Comment by MattIPv4** [comment]
Does anyone have any info here on what packages are actually needed? There seem to be a huge number of workbox packages. Are folks expecting for them all to be hosted on cdnjs?
