### ISSUE TITLE
Upgrade appbase.js - to v2.1.0

### ISSUE THREAD

**Issue by siddharthlatest** [cdnjs/cdnjs#12057]
When adding the library https://github.com/cdnjs/cdnjs/issues/8687, a .gitignore was added to prevent usage of 1.0.0 version. Currently, we are at [2.1.0](https://www.npmjs.com/package/appbase-js).

What should be done to update the lib version on cdnjs?

**Comment by PeterDaveHello** [comment]
@siddharthlatest I'll work on it, let me know if v1.0.0 needs to be unlocked/added or not, thanks.

**Comment by siddharthlatest** [comment]
@PeterDaveHello Wow, thanks for the super quick response. v1.0.0 does not need to be added.

**Comment by PeterDaveHello** [comment]
@siddharthlatest Cool, give it a few secs to be deployed on the website.
