### ISSUE TITLE
Update mermaid

### ISSUE THREAD

**Issue by SISheogorath** [cdnjs/cdnjs#12070]
We just noticed that the NPM version of mermaid does no longer include the global (window) scope variable for the mermaidAPI.

In order to fix this with and without the CDN, we would like to update mermaid. Currently, only 7.0.0 is available on CDNJS.

The release handling is a bit confusing since npm shows 7.1.0 as latest release, Github has the latest release label on 7.0.0, tags go to 7.0.5 and there is a commit on the dist directory talking about [7.0.17 (two months ago)](https://github.com/knsv/mermaid/commit/fe0434cb1641bcc80bfbde7757f16439ed039ab6). Hopefully, @knsv can enlight us what is the right release.

Related issues and fixes:
https://github.com/hackmdio/hackmd/issues/600
https://github.com/SISheogorath/hackmd/commit/1273c9ec5319a533cca313166e8899420cc40377

**Comment by PeterDaveHello** [comment]
Done in 12e88ded0fb86f060375f5d39613e151bf913427 & 62b51675593cb56d93891797a208364138c94441, thanks for report, forgot to close this issue in the commit so manually close it now.
