### ISSUE TITLE
[Request] Add gifplayer

### ISSUE THREAD

**Issue by azjezz** [cdnjs/cdnjs#12071]
**Library name:** gifplayer
**Library description:** gifplayer is a jquery plugin that will help you play and stop animated gifs on your website. Something like they do in 9gag or facebook.

The advantage of using this plugin is that you can load a lighter static version of the animated gif, and then load the actual animated gif, when the user wants to see it in motion. Improving the initial load time of your page.

gifplayer has support for video formats such as webm and mp4. Also, you can customize the event that will trigger the animated gif, for example: click, mouseover. Or you can start and stop the animations by calling specific methods.
**Git repository url:** https://github.com/rubentd/gifplayer
**License :** MIT License
**Official homepage:** http://rubentd.com/gifplayer/

**Comment by extend1994** [comment]
Duplicated with #11192. Move to there.
