### ISSUE TITLE
[Request] Add extends-ng-model.min.js

### ISSUE THREAD

**Issue by umeshp7** [cdnjs/cdnjs#12074]
**Library name:** extends-ng-model.min.js
**Library description:** This project builds on top of ngModel to add new features to angular 
**Git repository url:** https://github.com/Plippe/extends-ng-model
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
https://github.com/Plippe/extends-ng-model 
Please add this, and let me know if added via mail

**Comment by extend1994** [comment]
Hi @umeshp7 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: We suggest you open a issue again when the repo has notable popularity. This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 
Thank you for your contribution!

**Comment by extend1994** [comment]
Close this issue due to no response and insufficient popularity, cc @PeterDaveHello
