### ISSUE TITLE
[Request][Author] Add Chronimi

### ISSUE THREAD

**Issue by Cryptix720** [cdnjs/cdnjs#12078]
**Library name:** https://github.com/Cryptix720/Chronimi
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @Cryptix720 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: We suggest you open a issue again when the repo has notable popularity. 

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 

Thank you for your contribution!

**Comment by extend1994** [comment]
Close this issue due to no response and insufficient popularity, cc @PeterDaveHello
