### ISSUE TITLE
Update MDBootstrap to 4.4.3

### ISSUE THREAD

**Issue by cjmaxik** [cdnjs/cdnjs#12084]
MDBootstrap has been updated to 4.4.3 (https://github.com/mdbootstrap/bootstrap-material-design/releases/tag/4.4.3). Please update. Thank you.

**Comment by PeterDaveHello** [comment]
@cjmaxik thanks for report!

**Comment by PeterDaveHello** [comment]
@cjmaxik not really sure why it's not updated, I manually trigger the updater and bot to update MDBootstrap, now v4.4.2 & v4.4.3 are both added in f372394e821 & 4fb5113783f, please just give it few mins to be deployed. Thanks again.

**Comment by PeterDaveHello** [comment]
Done https://cdnjs.com/libraries/mdbootstrap/4.4.3
