### ISSUE TITLE
[Request] Add opencv

### ISSUE THREAD

**Issue by FallenRiteMonk** [cdnjs/cdnjs#12080]
**Library name:** opencv
**Library description:** Open Source Computer Vision Library
**Git repository url:** https://github.com/opencv/opencv
**License (List them all if it's multiple):** BSD
**Official homepage:** https://opencv.org/

**Comment by extend1994** [comment]
Hi @FallenRiteMonk 
Thanks for request. But I am wondering if this is compatible with a browser?

**Comment by FallenRiteMonk** [comment]
I think this should answer your question if i understood it correctly: 
https://docs.opencv.org/3.3.1/d0/d84/tutorial_js_usage.html

**Comment by extend1994** [comment]
@FallenRiteMonk Thanks! That's what I am wondering.
But according to https://docs.opencv.org/3.3.1/d4/da1/tutorial_js_setup.html, `opencv.js` needs to be manually built, but we need a library distribution from the project maintainers. So If it won't bother you too much, you can try to open an issue there to ask them can they make a distribution. Then we can add this library. 😃

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
