### ISSUE TITLE
[Request] Add dbc-code-contracts

### ISSUE THREAD

**Issue by jek-nov** [cdnjs/cdnjs#12092]
**Library name:** dbc-code-contracts
**Library description:** ES6 classes, which offer the several possibilities:
- the Design by Contract (DbC) approach. You may also set the exception throwing policy, if some contract has failed
- working with the DOM-model, there are methods for fetching/appending/updating/removing the HTML-nodes
- deep working with the HTML-attributes, if you plan to create the possible bindings for the MVC/MVP/MVVM pattern implementation
- loading the resources (the HTML/CSS/JavaScript content) asynchronously via the BLOB-urls, which were created on the fly
- other useful stuff, which isn't supported by the web-browsers from the box

**Git repository url:** https://gitlab.com/o.oleg/orbios.dbc.git
**npm package name or url:** [dbc-code-contracts](https://www.npmjs.com/package/dbc-code-contracts)
**License:** MIT
**Official homepage:** https://gitlab.com/o.oleg/orbios.dbc

**Notes**:  The project repository doesn't have the release by default. It must be built, like RunKit service does it via the **postinstall** script.

For e.g., jsdelivr doesn't provide such possibilities, which RunKit does https://github.com/jsdelivr/jsdelivr/issues/18048

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
