### ISSUE TITLE
Invalid Certificate Authority for cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by rbennettemerson** [cdnjs/cdnjs#12099]
We are unable to load files from cdnjs.cloudflare.com on some of our production sites because the certificate authority is invalid.  This issue seems to be somewhat inconsistent as sometimes there is no certificate error.
![image](https://user-images.githubusercontent.com/5197464/32445185-fefb4690-c2d2-11e7-998d-504bb010fcf1.png)
 
Pinging the domain gives me IP 104.19.196.102.

Looks like there was an issue opened for this already but closed due to no response:
@jessewgibbs / #11720

**Comment by sufuf3** [comment]
@rbennettemerson Thank you for your response.
May I ask your ip of production site and location?
I am in Taiwan. And everything looks fine to me.
![2017-11-06 11 43 08](https://user-images.githubusercontent.com/8349587/32449446-384e3192-c2d7-11e7-8438-1b6a4f8a1684.png)

I also got ip 104.19.194.102 from cdnjs.cloudflare.com server.
```bash
nslookup cdnjs.cloudflare.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	cdnjs.cloudflare.com
Address: 104.19.192.102
Name:	cdnjs.cloudflare.com
Address: 104.19.193.102
Name:	cdnjs.cloudflare.com
Address: 104.19.195.102
Name:	cdnjs.cloudflare.com
Address: 104.19.196.102
Name:	cdnjs.cloudflare.com
Address: 104.19.194.102
```

Also I test the site cdnjs.cloudflare.com https://www.ssllabs.com/ssltest/analyze.html?d=cdnjs.cloudflare.com&latest and http://dnsviz.net/d/cdnjs.cloudflare.com/dnssec/, It's looks fine.
Memo: 
There is only a issue of Certificate `#3`: RSA 2048 bits (SHA1withRSA)
Not sure is this problem.

@PeterDaveHello could you please take a look?
Many Thanks.

**Comment by PeterDaveHello** [comment]
@rbennettemerson can you please give me the result of:

 - traceroute to cdnjs.cloudflare.com

and the content of what you got from:
 - https://cdnjs.com/cdn-cgi/trace
 - https://cdnjs.cloudflare.com/cdn-cgi/trace

I doubt if you connect to a server not hosted by Cloudflare but you are under a Man-in-the-middle attack.

**Comment by rbennettemerson** [comment]
The issue seems to have been resolved as of 10:44 a.m. ET.  I checked all of the IPs (104.19.{192-6}.102) at that time and they all had valid certificates. If the certs haven't changed recently for those servers then it may have more to do with the network I'm connecting from.

**Comment by terinjokes** [comment]
@rbennettemerson CDNJS doesn't use certificates issued by Cisco. You likely were connecting to the internet through an transparent proxy or network device that was decrypting and re-encrypting traffic.
