### ISSUE TITLE
Add React 15.6.2

### ISSUE THREAD

**Issue by uncleramsay** [cdnjs/cdnjs#12100]
React 15.6.2 [was released](https://reactjs.org/blog/2017/09/25/react-v15.6.2.html) in September.

15.6.1 and 16.0.0 are available [on your site](https://cdnjs.com/libraries/react), but 15.6.2 is missing. Would it be possible to add it?

Thanks

**Comment by PeterDaveHello** [comment]
@uncleramsay sure thing, thanks for report.

**Comment by uncleramsay** [comment]
Sorry to reopen this - looks like you missed `react-dom` libraries. Could these be added too please?

**Comment by PeterDaveHello** [comment]
@uncleramsay actually you can try to send a pull request
