### ISSUE TITLE
[Request] Add mdi

### ISSUE THREAD

**Issue by 6y6a** [cdnjs/cdnjs#12130]
**Library name:** MaterialDesign
**Library description:** Material Design Icons
**Git repository url:** https://github.com/Templarian/MaterialDesign
**npm package name or url** (if there is one): mdi
**License (List them all if it's multiple):** SIL OPEN FONT LICENSE Version 1.1
**Official homepage:** https://materialdesignicons.com/

**Comment by PeterDaveHello** [comment]
I think we hosted here already https://cdnjs.com/libraries/MaterialDesign-Webfont ?

**Comment by 6y6a** [comment]
Sorry, I just can't find it about 3 days. Cdnjs already hosted it.

**Comment by PeterDaveHello** [comment]
@6y6a no worries
