### ISSUE TITLE
[Request] Add vue-mask

### ISSUE THREAD

**Issue by felzend** [cdnjs/cdnjs#12133]
**Library name:** v-mask
**Library description:** mask plugin for vuejs
**Git repository url:** https://github.com/probil/v-mask
**npm package name or url** (if there is one): v-mask
**License (List them all if it's multiple):** 
**Official homepage:**

**Comment by extend1994** [comment]
Thanks @felzend.
This has been processing in #10446 for #9870.
So I will close this for now.
You can trace it in #10446.
