### ISSUE TITLE
Suggest to remove libraries from cdnjs

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#12144]
@PeterDaveHello During my work with cdnjs I found a lot of libraries that not maintained by their authors. However, there is some libraries that authors themselves removed them from git or wrote predicate or, moreover, retired messages.
E.g. lib [1140](https://cdnjs.com/libraries/1140). The author in [git](https://github.com/andytlr/cssgrid) says that the library is not relevant , it is [retired](http://andytaylor.me/2013/04/09/1140px-css-grid-retired/). If we can check download statistics of such libraries and see that more then e.g. 1 year there are no downloads of library we, for my opinion, can remove it from cdnjs hosting and free space for other new libraries. We faced with dynamic world, the new libraries became and older are died, maybe we can formulate a course of action in this case.
FYD

**Comment by PeterDaveHello** [comment]
We don't have access log from Cloudflare that's why we can't remove time. I can't help unless @ryankirkman and @thomasdavis talk to Cloudflare, I can't find them for a while.

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to create script that will take all libs that were hosted more the an year ago and check their download rates once per month, 3 times (3 months), if download rate of library is **0** remove it from hosting. May be should send a message to requester/author of the library for notice during 3 month period. Moreover, we can create some gmail in order to archive those libraries for the future needs (if someone will ask for them).
However, all this after guys above will answer to you.
What do you think about such solution flow?

**Comment by PeterDaveHello** [comment]
@sashberd we don't have amy download logs, I prefer to discuss with the possibility comes, there are many pending things to be done first. Sorry.

**Comment by sashberd** [comment]
@PeterDaveHello And what about this [page](https://listium.com/@thomasdavis/16783/most-copied-libraries-on-cdnjscom)

**Comment by PeterDaveHello** [comment]
@sashberd I don't think it's about the method/portal issue. If they want to join, they will, you can see their GitHub page for activities.

**Comment by sashberd** [comment]
@PeterDaveHello I am ready to take development of this one on my self, so @ryankirkman and @thomasdavis if you can help me to find a way to view download rates of libraries will glad to help with this feature

**Comment by thomasdavis** [comment]
This information will just be almost impossible to gather. We barely have access to the logs, let alone a long history of the logs. If a library was accessed in February only once, should it be removed? What if it was accessed last year in September, and then in 3 months it is accessed once again yet again.

**Comment by sashberd** [comment]
@thomasdavis I do  not say that the task is not hard, but the trade off is storage and better management. As for the libraries, the task should remove only exact cases e.g. 1140 library, moreover as I said above, we will not remove it forever, but store it on gmail or some another place for a decade for example, and only after remove it. 
We can create some strict logic of this task and develop it. 
There is no need to run over old logs, we can start from now this monitoring

**Comment by xtuc** [comment]
We don't want to remove libraries from cdnjs as some website might still depend on them and we will break them.
