### ISSUE TITLE
[Request] Add chimee

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12148]
**Library name:** chimee
**Library description:** a video player aims to bring wonderful experience on browser 
**Git repository url:** https://github.com/Chimeejs/chimee/tree/master/lib
**npm package name or url** (if there is one): https://www.npmjs.com/package/chimee
**License (List them all if it's multiple):** MIT
**Official homepage:** https://chimee.org/

**Comment by toxic-johann** [comment]
Thanks~~~

**Comment by sufuf3** [comment]
@toxic-johann Thank you for your attention. 😃

**Comment by PeterDaveHello** [comment]
Maybe also https://github.com/Chimeejs/chimee-player ?
