### ISSUE TITLE
Swiper 4.0.6 files missing

### ISSUE THREAD

**Issue by ezetojo** [cdnjs/cdnjs#12181]
Files of Swiper 4.0.6 return 404 Not Found

https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.6/css/swiper.css
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.6/css/swiper.css
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.6/js/swiper.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.6/js/swiper.min.js
https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.0.6/js/swiper.min.js.map

**Comment by PeterDaveHello** [comment]
Thanks for report. This version was added about two hours ago in fa69e8b2251dfeedc7d8f733dcc4852e3753375b, should be reachable already, I can confirm that I can't access the files either, it returns 404 not found.

@terinjokes would you please take a look if there is any problem on the Cloudflare side of pulling updates? Many thanks.

**Comment by terinjokes** [comment]
:eyes:
