### ISSUE TITLE
[Request] Add primer-markdown

### ISSUE THREAD

**Issue by fisker** [cdnjs/cdnjs#12190]
Library name: primer-markdown
Library description: Stylesheets for rendering GitHub Flavored Markdown and syntax highlighted code snippets.
Git repository url: https://github.com/primer/primer/tree/master/modules/primer-markdown
npm package name or url (if there is one): https://www.npmjs.com/package/primer-markdown
License (List them all if it's multiple): MIT
Official homepage:

**Comment by sufuf3** [comment]
Memo: 116,973 downloads in the last month from npm

**Comment by Billy4195** [comment]
I'd like to solve this issue.

**Comment by xtuc** [comment]
PR merged in https://github.com/cdnjs/packages/commit/66972745f0532a96413ffd26e47192b1954827c5
