### ISSUE TITLE
[Request] Add shards-ui

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12194]
**Library name:** shards-ui
**Library description:** Shards is a free and modern Bootstrap 4 UI toolkit.
**Git repository url:** https://github.com/DesignRevision/shards-ui
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://designrevision.com/downloads/shards/

**Comment by MattIPv4** [comment]
Added via https://github.com/cdnjs/packages/pull/11
