### ISSUE TITLE
[Request] Add running-coder/jquery-typeahead

### ISSUE THREAD

**Issue by burakmete** [cdnjs/cdnjs#12214]
**Library name:** running-coder/jquery-typeahead
**Library description:** Javascript Typeahead (autocomplete) plugin with more than 50 options and callbacks.
**Git repository url:** https://github.com/running-coder/jquery-typeahead
**npm package name or url** (if there is one): https://www.npmjs.com/packages/jquery-typeahead
**License (List them all if it's multiple):** MIT
**Official homepage:** http://www.runningcoder.org/jquerytypeahead/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Memo: 24,854 downloads in the last month

**Comment by PeterDaveHello** [comment]
@sufuf3 what downloads?

**Comment by sufuf3** [comment]
npm
Sorry~
