### ISSUE TITLE
[Request] Add Sequence

### ISSUE THREAD

**Issue by torresio** [cdnjs/cdnjs#12211]
**Library name:** Sequence
**Library description:** The responsive CSS animation framework for creating unique sliders, presentations, banners, and other step-based applications.
**Git repository url:** https://github.com/IanLunn/Sequence
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** GPLv3 + Commercial
**Official homepage:** http://sequencejs.com
**Wanna say something? Leave message here:** Next time I'll learn how to submit via pull request, swear.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
