### ISSUE TITLE
[Request] Add vast-client-js

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12210]
**Library name:** vast-client-js
**Git repository url:** https://github.com/dailymotion/vast-client-js
**npm package name or url** (if there is one): https://www.npmjs.com/package/vast-client
**License (List them all if it's multiple):** [MIT](https://github.com/dailymotion/vast-client-js/blob/master/LICENSE)
**Official homepage:** just leave it emtpy(Don't create this files in package.json then it will redirect to its git repo)

**Related library**: videojs-vast-plugin in #12032

**Comment by cy91244** [comment]
I would like to work on this, thanks.
