### ISSUE TITLE
[Request] Add SoundJS missing versions & files

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12230]
**Library name:** SoundJS
**Git repository url:** https://github.com/CreateJS/SoundJS

Need to manually add 
1. missing versions v0.1.0 ~ v0.4.0, v0.5.1, v0.6.1 & v0.6.2 of the lib on Git repo.
2. missing files in v0.4.1 ~ v0.6.0 (e.g. soundjs.flashplugin-0.4.1.min.js and flashplugin-0.5.0.min.js)

**Comment by cy91244** [comment]
I would work on this, thanks.

**Comment by extend1994** [comment]
Solved in https://github.com/cdnjs/cdnjs/commit/4e1b03f5c0afcef61d02dbfc18a17aaefe543c17 & https://github.com/cdnjs/cdnjs/commit/25b15ac6d850cb565490f8ec43f5197fb8330d6d
More commits about SoundJS: https://github.com/cdnjs/cdnjs/commits/master?after=0e1d2d4854cb76561024036ca59289356125c60f+0
