### ISSUE TITLE
[Request] Add angular-utils-pagination

### ISSUE THREAD

**Issue by ernestoacostacuba** [cdnjs/cdnjs#12235]
**Library name:** angular-utils-pagination
**Library description:** Version 0.11.1 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 
<dependency>
  <groupId>org.webjars.bower</groupId>
 <artifactId>angular-utils-pagination</artifactId>
 <version>0.11.1</version>
</dependency>

**Comment by extend1994** [comment]
@ernestoacostacuba Thanks for request, could you please provide further info git repo or npm?

**Comment by extend1994** [comment]
If there is no response in next 7 days, I will close this issue.

**Comment by extend1994** [comment]
Seems https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination &
https://www.npmjs.com/package/angular-utils-pagination

**Comment by MattIPv4** [comment]
This relies on a html template file, which we cannot host on the CDN. Closing.
