### ISSUE TITLE
[Request] Add EaselJS missing versions

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12231]
**Library name:** EaselJS
**Git repository url:** https://github.com/CreateJS/EaselJS

Need to manually add missing versions v0.3.0 ~ v0.6.0 & v0.8.1 ~ v1.0.0 of the lib on Git repo.

**Comment by cy91244** [comment]
I would work on this, thanks.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting pull requests that manually add versioned files for libraries. Instead, please ensure that the library has an up-to-date auto-update config for either NPM or Git in the cdnjs repository.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
