### ISSUE TITLE
Tooltipster versions are outdated

### ISSUE THREAD

**Issue by vaindil** [cdnjs/cdnjs#12238]
The CDN only has [tooltipster](https://github.com/iamceege/tooltipster) versions up to 3.3.0, which was released back in Nov. 2014. The [latest version](https://github.com/iamceege/tooltipster/releases) is 4.2.5 from April of this year. ([CDN page](https://cdnjs.com/libraries/tooltipster))

**Comment by PeterDaveHello** [comment]
@vaindil thanks, would you like to send a pull request for that?

**Comment by vaindil** [comment]
Sure, I can try. I'm not sure if I'll have the updated format for autoUpdate correct, but I'll give it a shot.

**Comment by PeterDaveHello** [comment]
@vaindil nice, thanks!

**Comment by vaindil** [comment]
Alright, I think that's good. #12239

**Comment by xtuc** [comment]
The PR has been closed, closing this too
