### ISSUE TITLE
[Request] Add bootstrap-vue

### ISSUE THREAD

**Issue by lgh06** [cdnjs/cdnjs#12245]
Library name: bootstrap-vue
Library description: Build responsive, mobile-first projects on the web using Vue.js and the world's most popular front-end CSS library — Bootstrap V4.
Git repository url: https://github.com/bootstrap-vue/bootstrap-vue/
npm package name or url (if there is one): bootstrap-vue
License (List them all if it's multiple): MIT
Official homepage: https://bootstrap-vue.js.org/

**Comment by Billy4195** [comment]
I'd like to take this.
