### ISSUE TITLE
[Request] Add tentcss

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12248]
**Library name:** tentcss
**Git repository url:** https://github.com/sitetent/tentcss
**npm package name or url** (if there is one): https://www.npmjs.com/package/tent-css
**License (List them all if it's multiple):** [MIT](https://github.com/sitetent/tentcss/blob/master/LICENSE)
**Official homepage:** https://css.sitetent.com

**Comment by ralphchung** [comment]
I will take this!
