### ISSUE TITLE
[Request] Add upng-js

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12257]
**Library name:** upng-js
**Library description:** Fast and advanced PNG (APNG) decoder and encoder (lossy / lossless)
**Git repository url:** https://github.com/photopea/UPNG.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/upng-js
**License (List them all if it's multiple):** MIT
**Official homepage:**

**Comment by Billy4195** [comment]
I'd like to take this.
