### ISSUE TITLE
[Request] Add imaskjs

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12256]
**Library name:** imaskjs
**Library description:** vanilla javascript input mask 
**Git repository url:** https://github.com/uNmAnNeR/imaskjs
**npm package name or url** (if there is one): https://www.npmjs.com/package/imask
**License (List them all if it's multiple):** MIT
**Official homepage:** https://unmanner.github.io/imaskjs/

**Comment by Billy4195** [comment]
I'd like to take this.
