### ISSUE TITLE
[Request] Add imaskjs

### ISSUE THREAD

**Issue by uNmAnNeR** [cdnjs/cdnjs#12262]
**Library name:** imaskjs
**Library description:** vanilla javascript input mask
**Git repository url:** https://github.com/uNmAnNeR/imaskjs
**npm package name or url** (if there is one): imaskjs
**License (List them all if it's multiple):** MIT
**Official homepage:** https://unmanner.github.io/imaskjs
**Wanna say something? Leave message here:**

**Comment by sufuf3** [comment]
Duplicated with #12256
Let's close this one and move to #12256
cc @PeterDaveHello
