### ISSUE TITLE
[Request] Add brain.js

### ISSUE THREAD

**Issue by lunaroyster** [cdnjs/cdnjs#12281]
**Library name:** brain.js
**Library description:** Neural network library
**Git repository url:** https://github.com/BrainJS/brain.js
**npm package name or url (if there is one):** http://npmjs.com/package/brain.js
**License (List them all if it's multiple):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**
This project is a continuation of the original library (now unmaintained) by harthur/brain, which is [listed on cdnjs](https://cdnjs.com/libraries/brain).

**Comment by robertleeplummerjr** [comment]
nice

**Comment by robertleeplummerjr** [comment]
also, thank you.  Validation on my side.

**Comment by extend1994** [comment]
Thanks @robertleeplummerjr 😄 
We will add it ASAP!
