### ISSUE TITLE
Add auto-update config to protovis library

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#12289]
The protovis library has not auto update configuration in package.json. There are [new versions](https://github.com/mbostock/protovis/tree/v3.3.0) on library GIT.

**Comment by AilurusUmbra** [comment]
Hi, may I take this issue?

**Comment by PeterDaveHello** [comment]
@AilurusUmbra sure thing 👍

**Comment by OderoAjamu** [comment]
I see that this issue is open. Is it okay if I take it?

**Comment by sashberd** [comment]
@OderoAjamu You are welcome

**Comment by MattIPv4** [comment]
We have 3.3.1 which is the latest in the repo, as this library appears to be unmaintained I see very little value in adding auto-update to pull in older versions. Closing.
