### ISSUE TITLE
Add geojson.js

### ISSUE THREAD

**Issue by mvl22** [cdnjs/cdnjs#12287]
Library name: GeoJSON.js
Library description: Turn your geo data into GeoJSON.
Git repository url: https://github.com/caseycesari/geojson.js
npm package name or url (if there is one): geojson ; see: https://www.npmjs.com/package/geojson
License (List them all if it's multiple): MIT
Official homepage: https://github.com/caseycesari/geojson.js

**Comment by cy91244** [comment]
I will take this, thanks.

**Comment by mvl22** [comment]
Thanks!
