### ISSUE TITLE
[Request] Add willowsystems/jSignature

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#12282]
**Library name:** jSignature
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/willowsystems/jSignature
**Wanna say something? Leave message here:** 
looks like useful Signature library, plz add it to CDNJS.
Thank you.

**Comment by extend1994** [comment]
Hi @ihsinhw I think we can add the original one https://github.com/brinley/jSignature, the one your request was forked from, it has releases on GitHub. cdnjs need releases to add library. Is that okay? Thanks.

**Comment by extend1994** [comment]
To whom wants to add this lib:
  cdnjs needs a library to have releases/tags on GitHub. Currently,  https://github.com/willowsystems/jSignature doesn't meet this requirement.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
