### ISSUE TITLE
Update Font Awesome to 5.0

### ISSUE THREAD

**Issue by ExE-Boss** [cdnjs/cdnjs#12307]
[Font Awesome 5](https://fontawesome.com) has now been released, and the free version is still [under an open source license](https://fontawesome.com/license), so cdnjs can redistribute the free version.

**Comment by ExE-Boss** [comment]
Unfortunately, it looks like that the Font Awesome 5 source code is no longer hosted on GitHub, and me being just a normal user of Font Awesome (I’m not even a [contributor to the repository](https://github.com/FortAwesome/Font-Awesome/graphs/contributors)), it’s unlikely that I could change the Font Awesome team’s mind, especially since they chose to make [a paid version as well](https://fontawesome.com/pro).

So this means that the Font Awesome 5 Free version will have to be kept up to date manually, or you could request that they create a separate branch just for listing the version 5 download links in the README file and use that to notify CDNJS about Font Awesome 5 updates.

**Comment by KZeni** [comment]
They are offering their own CDN service at https://fontawesome.com/get-started. That said, FA 5 Free is still open source and I don't see why they wouldn't make that available via CDNJS as well.

**Comment by sufuf3** [comment]
@ExE-Boss @KZeni Thank you.
I opened an issue on this lib's repo FortAwesome/Font-Awesome#11913
Let's waiting for their response.

Many thanks.

**Comment by sufuf3** [comment]
Hi guys,
As The member of the team said https://github.com/FortAwesome/Font-Awesome/issues/11913#issuecomment-351135450 
> The free repo has not been updated yet.

If you guys would like to discuss the version issue with community, you can go there FortAwesome/Font-Awesome#11908 

And maybe we can close this issue and wait for free repo be added.
What do you think?

Many thanks.

**Comment by PeterDaveHello** [comment]
@sufuf3 Ｉprefer to leave this one opened so people can found it.

**Comment by tlygnersjo** [comment]
Are there going to a be a release of Font Awesome 5.0 on cdnjs in a near future?

Would be great if that could be released, i'm working on a project atm that needs a reliable CDN for Font Awesome (5.0).

Thanks in advance!

**Comment by sagudev** [comment]
Font Awesome repo was updated and they released version 5.0.6. They even made [tag for 5.0.6](https://github.com/FortAwesome/Font-Awesome/releases/tag/5.0.6). Will Font Awesome 5.0.6 now come to cdnjs?

**Comment by sufuf3** [comment]
I'll help update this ASAP.
Thanks.

**Comment by arguiot** [comment]
When will fontawesome 5 be on CDNJS @sufuf3 ?

**Comment by sufuf3** [comment]
@arguiot I don't know.
Let's waiting for reply from FortAwesome/Font-Awesome#12323
Then, I can continue to work on it and let reviewer review the PR.
Many thanks.

**Comment by cederberg** [comment]
I think the Font-Awesome repo tags are back in working order now:
https://github.com/FortAwesome/Font-Awesome/releases

**Comment by sufuf3** [comment]
Thank you.
I would update the version and check it soon.

**Comment by hifocus** [comment]
Hi. I read the discussion above, now font-awesome repo have been release normally. 

Please see https://github.com/FortAwesome/Font-Awesome/releases , the latest `5.2.0` version is included. 

And another opensource CDN `jsDelivr` have got the `5.2.0` version in their network already, https://www.jsdelivr.com/package/gh/FortAwesome/Font-Awesome .

So I think font-awesome should be synced anyway.

**Comment by hifocus** [comment]
@arguiot they can be done automattically

**Comment by sagudev** [comment]
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

**Comment by sufuf3** [comment]
Thank you.
I will do this PR this weekend.
Sorry for late.

**Comment by Nosferican** [comment]
Any update?

**Comment by sufuf3** [comment]
Sorry I will do this PR these two days.

**Comment by sufuf3** [comment]
I updated the PR, let's wait for reviewing.
Thanks
