### ISSUE TITLE
[Request] Add vue-svgicon

### ISSUE THREAD

**Issue by Allenice** [cdnjs/cdnjs#12317]
**Library name:** vue-svgicon
**Library description:** A tool to create svg icon components. (vue 2.x). Using inline svg.
**Git repository url:** https://github.com/MMF-FE/vue-svgicon
**npm package name or url** (if there is one): vue-svgicon
**License (List them all if it's multiple):** MIT
**Official homepage:** https://mmf-fe.github.io/vue-svgicon/
**Wanna say something? Leave message here:**  main file: dist/index.js

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by yaxauw** [comment]
I would like to take this issue
