### ISSUE TITLE
[Request] Add BigInteger.js

### ISSUE THREAD

**Issue by peterolson** [cdnjs/cdnjs#12312]
**Library name:** BigInteger.js
**Library description:** an arbitrary-length integer library for Javascript, allowing arithmetic operations on integers of unlimited size, notwithstanding memory and time limitations.
**Git repository url:** https://github.com/peterolson/BigInteger.js
**npm package name or url (if there is one):** https://www.npmjs.com/package/big-integer
**License (List them all if it's multiple):** Unlicense

**Comment by cy91244** [comment]
I will take this.

**Comment by peterolson** [comment]
Thanks!
