### ISSUE TITLE
Add blissfuljs@1.0.5 with new npm auto-update config

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12318]
Need to update auto-update config of the hosted library blissfuljs because it's outdated.
Some front-end files seem to be removed by the maintainer in https://github.com/LeaVerou/bliss/commit/43e76d1a9750c805f04724a44967459981723e7d.
Please take this issue after there is a conclusion in https://github.com/LeaVerou/bliss/issues/215.

---2017/12/15 update---
Conclusion:
1. auto-update should be updated to npm
2. Need to manually add v1.0.5

**Comment by cy91244** [comment]
I would like to work on this.

**Comment by MattIPv4** [comment]
1.0.5 & 1.0.6 are available: https://cdnjs.com/libraries/blissfuljs/1.0.6
