### ISSUE TITLE
[Request] Add unistore

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12323]
**Library name:** unistore
**Library description:** A tiny ~650b centralized state container with component bindings for Preact & React.
**Git repository url:** https://github.com/developit/unistore
**npm package name or url** (if there is one): https://www.npmjs.com/package/unistore
**License (List them all if it's multiple):** MIT
**Official homepage:**

**Comment by cy91244** [comment]
I would like to work on this, thanks.
