### ISSUE TITLE
JSZipUtils.getBinaryContent - throwing 401 unauthorized error in Chrome browser - And working fine in IE

### ISSUE THREAD

**Issue by mmohamedbasith** [cdnjs/cdnjs#12339]
I am using using below lines to zip file in my angular 2 project. The file to be zipped is stored in different domain site .

Angular site url: http://stawwq:5555

JSZipUtils.getBinaryContent("http://extranet:123/doc/file.docx", function (err, data) {
   if(err) {
      throw err; 
   }
   var zip = new JSZip(data);
});
Zipping works fine in IE . But not in chrome. Receives below error
VM120:3 Error: Ajax error for http://extranet:123/doc/file.docx : 401 Unauthorized
    at XMLHttpRequest.xhr.onreadystatechange (vendor.bundle.js:90270) [angular]
    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (polyfills.bundle.js:7605) [angular]
    at Object.onInvokeTask (vendor.bundle.js:32355) [angular]
    at ZoneDelegate.invokeTask (polyfills.bundle.js:6729) [angular]
    at Zone.runTask (polyfills.bundle.js:6529) [<root> => angular]
    at XMLHttpRequest.ZoneTask.invoke (polyfills.bundle.js:6783) [<root>]

I suspect CORS issue .the site which stores the file has below headeers in web.config

      <customHeaders>
        <remove name="X-Powered-By" />
        <add name="X-MS-InvokeApp" value="1; RequireReadOnly" />
        <add name="Access-Control-Allow-Credentials" value="true" />
        <add name="Access-Control-Allow-Origin" value="http://stawwq:5555" />
      </customHeaders>
  

Would require your assistance to resolve this issue

**Comment by mmohamedbasith** [comment]
Web.config

<httpProtocol allowKeepAlive="true">
      <customHeaders>
        <remove name="X-Powered-By" />
        <add name="X-MS-InvokeApp" value="1; RequireReadOnly" />
        <add name="Access-Control-Allow-Credentials" value="true" />
        <add name="Access-Control-Allow-Origin" value="http://staww8580q:5555" />
      </customHeaders>
    </httpProtocol>

**Comment by sufuf3** [comment]
@mmohamedbasith Thanks for issue.
In fact, CDNJS host the lib from upstream.
So if there is the problem of lib, maybe discuss the issue with lib's author is a better way.
What do you think?

Many thanks.

**Comment by sufuf3** [comment]
If there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by extend1994** [comment]
Close it due to no response in 7 days, cc @PeterDaveHello
