### ISSUE TITLE
[Request] Update store.js to v2

### ISSUE THREAD

**Issue by andronocean** [cdnjs/cdnjs#12336]
[store.js](https://github.com/marcuswestin/store.js) is currently at v2.0.12, while the CDN only has it [up to v1.3.20](https://cdnjs.com/libraries/store.js) from back in 2015. Pretty popular project, and I can't find any other trustworthy CDNs that carry it.

**Comment by sufuf3** [comment]
@andronocean Many thanks.
PS. Now, the bathPath is https://github.com/marcuswestin/store.js/tree/master/dist
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/store.js/package.json#L14-L27

**Comment by ralphchung** [comment]
I'll take this!
