### ISSUE TITLE
vanilla-lazyload latest versions not going live

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#12349]
Hi there,
yesterday (some hours ago) I released 10.4.0 and 10.4.1 of vanilla-lazyload on my github repo, but it’s not going live on cdnjs. 
What am I doing wrong?

**Comment by PeterDaveHello** [comment]
@verlok I think it's already hosted?
https://cdnjs.com/libraries/vanilla-lazyload/10.4.0

commit f6848313ebe72be6674544b66a958f4489c777ad
Author: PeterBot <PeterBot@users.noreply.github.com>
Date:   Tue Dec 19 13:41:52 2017 +0800

    Add vanilla-lazyload v10.4.1

commit 6798809775dc8b497d11c3802135a0afd972a74d
Author: PeterBot <PeterBot@users.noreply.github.com>
Date:   Tue Dec 19 06:16:13 2017 +0800

    Add vanilla-lazyload v10.4.0

**Comment by PeterDaveHello** [comment]
@verlok see also https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/vanilla-lazyload
