### ISSUE TITLE
[Request] Add query-string

### ISSUE THREAD

**Issue by htkoca** [cdnjs/cdnjs#12348]
**Library name:** query-string
**Library description:** Parse and stringify URL query strings
**Git repository url:** https://github.com/sindresorhus/query-string
**npm package name or url (if there is one):** https://www.npmjs.com/package/query-string
**License (List them all if it's multiple):** MIT
**Official homepage:**

**Comment by cy91244** [comment]
I would work on this, thanks.

**Comment by htkoca** [comment]
Thanks!

**Comment by sufuf3** [comment]
Duplicated with #10334 
Let's move to #10334

@cy91244 Before adding the library, could you please check is there any duplicated issue or PR?
We choose the earlier issue to cc it, and close the newest one make sure there is no duplicated issue.
This is useful to maintain a huge project.

Many thanks.

**Comment by sufuf3** [comment]
Close this issue because there is a duplicated issue #10334
cc @PeterDaveHello
