### ISSUE TITLE
[Request] Add moveTo

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12341]
**Library name:** moveTo
**Git repository url:** https://github.com/hsnaydd/moveTo
**npm package name or url** (if there is one): https://www.npmjs.com/package/moveto
**License (List them all if it's multiple):** [MIT](https://github.com/hsnaydd/moveTo/blob/master/LICENSE)
**Official homepage:** https://hsnaydd.github.io/moveTo/demo/

**Comment by cy91244** [comment]
I will take this, thanks.
