### ISSUE TITLE
[Request] Update jquery.inputmask git repo url 

### ISSUE THREAD

**Issue by avradul** [cdnjs/cdnjs#12353]
**Library name:** Inputmask
**Library description:** 
**Git repository url:** https://github.com/RobinHerbots/Inputmask
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** Your latest version 3.3.4 http://prntscr.com/hpkyl2
Please update to 4.x http://prntscr.com/hpl4t1
We all need this version for Android fix https://github.com/RobinHerbots/Inputmask/issues/1750

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to change current npm autoupdate config to git repo... WDYT?

**Comment by avradul** [comment]
@RobinHerbots , can you tagged version 4 on npm and git repo?

**Comment by sufuf3** [comment]
Need to update the git repo url https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery.inputmask, because the [origin](https://github.com/RobinHerbots/jquery.inputmask) always redirect to https://github.com/RobinHerbots/Inputmask

@avradul There is no v4.*.* version release via git tag or npm. (We don't add the files rely on branch but git tag.)
Would you discuss this version issue with the author?
Many thanks.

**Comment by RobinHerbots** [comment]
@avradul , @sufuf3 , 

Not yet, ... I will tag when version 4 is release ready

**Comment by avradul** [comment]
@RobinHerbots, when can we expect version 4.x? Approximately?

**Comment by RobinHerbots** [comment]
@avradul , 

I will release a beta version on npm.  (npmtag next)  So just getting the latest will not result in the 4.x version.

**Comment by avradul** [comment]
@sufuf3, can you update now https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery.inputmask?
Git tag has been updated by the author on https://github.com/RobinHerbots/Inputmask

**Comment by avradul** [comment]
@sufuf3, @sashberd 
What about an update jquery.inputmask to 4.0.3?

**Comment by RobinHerbots** [comment]
@avradul , 

Make it version 4.0.4 (which will probable the last 4 version

**Comment by sufuf3** [comment]
I'll help improve this lib this weekend. (Already booked in my schedule.)
If someone can help send this PR of lib before this weekend in free time, please go ahead.
Very SORRY for the late reply.
Thank you.
