### ISSUE TITLE
[Request] Add jquery-rss

### ISSUE THREAD

**Issue by cougrimes** [cdnjs/cdnjs#12354]
**Library name:** jquery-rss
**Library description:** An easy-to-use rss plugin for jquery with templating.
**Git repository url:** https://github.com/sdepold/jquery-rss
**npm package name or url** https://www.npmjs.com/package/jquery-rss
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/sdepold/jquery-rss
**Wanna say something? Leave message here:**

**Comment by cy91244** [comment]
I would work on this, thanks.

**Comment by sdepold** [comment]
Oh cool thanks! I will update the docs :)
