### ISSUE TITLE
[Author] Brython library has wrong latest version (3.3.20 instead of, currently, 3.3.5)

### ISSUE THREAD

**Issue by jonathanverner** [cdnjs/cdnjs#12367]
cc: @PierreQuentel, @extend1994, @x09326

The [Brython](https://cdnjs.com/libraries/brython/) library shows the latest version to be 3.3.20. However the actual files are from [version 3.3.0](https://github.com/brython-dev/brython/releases/tag/3.3.0); version 3.3.20 does not exist at all. Currently the latest is [3.3.5](https://github.com/brython-dev/brython/releases/tag/3.3.5) (which [is](https://cdnjs.com/libraries/brython/3.3.5) on CDNJS, apparently [added](https://github.com/cdnjs/cdnjs/commit/b535c8b0e6d21c88e3485d0fef0287bc21a4b577) by npm-autoupdate). It would be nice if the [3.3.20](https://cdnjs.com/libraries/brython/3.3.20) version could be removed from CDNJS.

**Comment by extend1994** [comment]
@PeterDaveHello Could you help with this issue? Thank you!

**Comment by PeterDaveHello** [comment]
Looks like it's from npm registry, so is it not an official package on npm or something else?

**Comment by PeterDaveHello** [comment]
I think @sufuf3 and @maruilian11 can also take a look and join the discussion here.

**Comment by jonathanverner** [comment]
@PeterDaveHello: the package on npm registry is official (uploaded by @PierreQuentel), though the 3.3.20 was probably uploaded by mistake. But even on npm the 3.3.5 (currently) is marked as latest...

**Comment by sufuf3** [comment]
@jonathanverner Thanks.
@PeterDaveHello @extend1994 I think we just need to update https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/brython/package.json#L4 this field from 3.3.20 to 3.3.5.
What do you think?

Many thanks.

**Comment by jonathanverner** [comment]
@PierreQuentel just released a new version (3.4.0) on npm which fixes this issue. Thanks for looking into this!
