### ISSUE TITLE
[Request] Add react-image-crop

### ISSUE THREAD

**Issue by DominicTobias** [cdnjs/cdnjs#12365]
**Library name:** react-image-crop
**Library description:** A react UI tool for selecting a crop on an image
**Git repository url:** https://github.com/DominicTobias/react-image-crop
**npm package name or url (if there is one):** https://www.npmjs.com/package/react-image-crop
**License (List them all if it's multiple):** ISC
**Official homepage:** none

Thanks!

**Comment by sufuf3** [comment]
Memo: 28,759 downloads in the last month from npm
