### ISSUE TITLE
[Request] Add tailwindcss

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12372]
**Library name:** tailwindcss
**Git repository url:** https://github.com/tailwindcss/tailwindcss
**npm package name or url** (if there is one): https://www.npmjs.com/package/tailwindcss
**License (List them all if it's multiple):** [MIT](https://github.com/tailwindcss/tailwindcss/blob/master/LICENSE)
**Official homepage:** https://tailwindcss.com

Useful info: https://tailwindcss.com/docs/installation

**Comment by finch185277** [comment]
I want to take this.
