### ISSUE TITLE
[Request] Add spotify-web-api-js

### ISSUE THREAD

**Issue by hughrawlinson** [cdnjs/cdnjs#12384]
Hi! It'd be really great to have https://github.com/JMPerez/spotify-web-api-js accessible. Thanks!

**Library name:** spotify-web-api-js
**Library description:** A client-side JS wrapper for the Spotify Web API
**Git repository url:** https://github.com/JMPerez/spotify-web-api-js
**npm package name or url** (if there is one): https://www.npmjs.com/package/spotify-web-api-js
**License (List them all if it's multiple):** [MIT](https://github.com/JMPerez/spotify-web-api-js/blob/master/LICENSE)
**Official homepage:** https://doxdox.org/jmperez/spotify-web-api-js

**Comment by sufuf3** [comment]
Cool! I love spotify.
But do you know which file can be used in web front-end?
I think there is no front-end files, the front-end file need to be built by user via webpack, as the [README said](https://github.com/JMPerez/spotify-web-api-js#when-bundling-the-library)
CDNJS host the file from upstream, and we don't provide this files of the lib by building the files via ourself.
We want the files can be trust from upstream.

Would you mind discussing the web front-end files with the author?
I think this will be a great work.
Many thanks.

**Comment by extend1994** [comment]
https://github.com/JMPerez/spotify-web-api-js/blob/master/src/spotify-web-api.js is for front-end.
