### ISSUE TITLE
[Request] Update for Bootstrap v4.0.0-beta.3

### ISSUE THREAD

**Issue by hakimihamdan88** [cdnjs/cdnjs#12388]
they have newer version of beta https://getbootstrap.com/docs/4.0/getting-started/download/

**Comment by sufuf3** [comment]
@hakimihamdan88 Thank you.

@PeterDaveHello I can use `./auto-update.js run twitter-bootstrap` to get `ajax/libs/twitter-bootstrap/4.0.0-beta.3`.
May need to take a deep look that why bot didn't fetch it.
Maybe this PR is the same with #12346

Should I help add v4.0.0-beta.3?

Thank you.

**Comment by Skyost** [comment]
👍

**Comment by hakimihamdan88** [comment]
still not updating?

**Comment by sufuf3** [comment]
@hakimihamdan88 @PeterDaveHello added it in this commit https://github.com/cdnjs/cdnjs/commit/ca3574bfafb020fdee941a2586683174878e29f2
Would you mind taking a look?

Many thanks.

@PeterDaveHello Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 it's beta version ...
