### ISSUE TITLE
[Request] Update gijgo@1.7.3 (git autoupdate doesn't work)

### ISSUE THREAD

**Issue by atatanasov** [cdnjs/cdnjs#12399]
Git autoupdate doesn't work for the last release of https://github.com/atatanasov/gijgo/releases
This was working pretty good before. We have an issue just with the last release from Dec 31st.

cndjs url: https://cdnjs.com/libraries/gijgo

**Comment by sufuf3** [comment]
@atatanasov Thank you.

@PeterDaveHello I can use `./auto-update.js gijgo` to get `ajax/libs/gijgo/1.7.3`.
May need to take a deep look that why bot didn't fetch it.
Maybe this PR is similar to #12346

Should I help add v1.7.3?

Thank you.

**Comment by atatanasov** [comment]
any news? The auto update for my library still doesn't work.

**Comment by sufuf3** [comment]
@atatanasov @PeterDaveHello add this version in this commit https://github.com/cdnjs/cdnjs/commit/59c8f965c6cb66658193ced8e33faec7a75b44b1
Would you mind taking a look?
Thank you.

@PeterDaveHello Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 See the difference between v1.7.2 and v1.7.3 file structure and you'll see the bot won't add it automatically.

**Comment by sufuf3** [comment]
Got it.
I would remember that.
Thank you.
