### ISSUE TITLE
[Request] Add turndown

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12397]
**Library name:** turndown
**Library description:** An HTML to Markdown converter written in JavaScript
**Git repository url:** https://github.com/domchristie/turndown
**npm package name or url** (if there is one): https://www.npmjs.com/package/turndown
**License (List them all if it's multiple):** MIT
**Official homepage:** https://domchristie.github.io/turndown/

**Comment by finch185277** [comment]
I want to take this.
