### ISSUE TITLE
[Request] Add rrssb

### ISSUE THREAD

**Issue by PascalBru** [cdnjs/cdnjs#12398]
**Library name:** rrssb
**Library description:** Ridiculously Responsive Social Sharing Buttons
**Git repository url:** https://github.com/kni-labs/rrssb
**npm package name or url** (if there is one): https://www.npmjs.com/package/rrssb
**License (List them all if it's multiple):** The MIT License
**Official homepage:** https://rrssb.netlify.com
**Wanna say something? Leave message here:**

**Comment by finch185277** [comment]
I want to take this.

**Comment by dbox** [comment]
🎉
