### ISSUE TITLE
[Request] Add mailgun-js

### ISSUE THREAD

**Issue by jsalmond** [cdnjs/cdnjs#12404]
**Library name:** mailgun-js
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@jsalmond Thanks for request, could you provide further info such as git repo or npm name?

**Comment by extend1994** [comment]
Will close this issue if there is still no response in next 7 days.

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
this one?
https://www.npmjs.com/package/mailgun.js
https://github.com/mailgun/mailgun-js
