### ISSUE TITLE
[Request] Update asmCrypto auto-update config

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12412]
The latest version of the library on cdnjs is [v0.0.12](https://cdnjs.com/libraries/asmCrypto). However, the latest version should be [v0.18.0](https://github.com/asmcrypto/asmcrypto.js/releases).

And it seems better to use npm auto-update from now because js files for front-end are only on npm now.
npm package url: https://www.npmjs.com/package/asmcrypto.js

**Comment by PeterDaveHello** [comment]
@extend1994 nice catch 👍
