### ISSUE TITLE
SRI Hash Size Upgrade

### ISSUE THREAD

**Issue by Area51Brett** [cdnjs/cdnjs#12428]
SHA384 is immune to length extension attacks, SHA256 is not which is why I am suggesting all SRI tags be upgraded to SHA384. Additionally W3 recommends SHA384 as the baseline for subresource integrity. 

 https://www.w3.org/TR/SRI/#hash-collision-attacks

**Comment by PeterDaveHello** [comment]
Thanks for suggestion, let's move to #11123
