### ISSUE TITLE
[Request] Add gitment

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12420]
**Library name:** gitment
**Library description:** A comment system based on GitHub Issues
**Git repository url:** https://github.com/imsun/gitment
**npm package name or url** (if there is one): https://www.npmjs.com/package/gitment
**License (List them all if it's multiple):** MIT
**Official homepage:** https://imsun.github.io/gitment/

PS. Need add the files from npm. https://github.com/imsun/gitment#1-install

**Comment by finch185277** [comment]
I want to take this.
