### ISSUE TITLE
[Request] Add jquery.boxfit.js

### ISSUE THREAD

**Issue by PvFrozty** [cdnjs/cdnjs#12426]
**Library name:** jquery.boxfit.js
**Library description:** 
**Git repository url:** https://github.com/michikono/boxfit
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

**Comment by extend1994** [comment]
Hi @PvFrozty 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:

We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity.
