### ISSUE TITLE
[Request] Add mapbox.js

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#12427]
**Library name:** mapbox.js
**Library description:** Mapbox JavaScript API, a Leaflet Plugin
**Git repository url:** https://github.com/mapbox/mapbox.js/
**npm package name or url** (if there is one): https://www.npmjs.com/package/mapbox.js/
**License (List them all if it's multiple):** [BSD-3-Clause](https://github.com/mapbox/mapbox.js/blob/mb-pages/LICENSE.md)
**Official homepage:** https://www.mapbox.com/mapbox.js/
**Wanna say something? Leave message here:**

**Comment by extend1994** [comment]
The one wants to take this issue please note you will need the pre-built files for web browser from the authors/maintainers.

**Comment by theel0ja** [comment]
Maybe ask them to implement something like this: https://github.com/highlightjs/cdn-release
