### ISSUE TITLE
[Request] Add react-sortable-hoc

### ISSUE THREAD

**Issue by sufuf3** [cdnjs/cdnjs#12424]
**Library name:** react-sortable-hoc
**Library description:** A set of higher-order components to turn any list into an animated, touch-friendly, sortable list.
**Git repository url:** https://github.com/clauderic/react-sortable-hoc
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-sortable-hoc
**License (List them all if it's multiple):** MIT
**Official homepage:** https://clauderic.github.io/react-sortable-hoc/
**Wanna say something? Leave message here:**  Need add this lib from npm because of https://github.com/clauderic/react-sortable-hoc/blob/master/webpack.config.umd.js

**Comment by finch185277** [comment]
I want to take this.
