### ISSUE TITLE
[Request] Bootstrap 4 stable

### ISSUE THREAD

**Issue by sagudev** [cdnjs/cdnjs#12439]
Bootstrap released Bootstrap 4 stable. Please add it. 

https://github.com/twbs/bootstrap/releases/tag/v4.0.0

**Comment by PeterDaveHello** [comment]
@sagudev Added 12 hours ago
 - https://cdnjs.com/libraries/twitter-bootstrap/4.0.0
 - https://github.com/cdnjs/cdnjs/commit/64202d1e1565a4f3675a51f90102bc9d7ab19af4
