### ISSUE TITLE
[Request] Add maptalks

### ISSUE THREAD

**Issue by fuzhenn** [cdnjs/cdnjs#12432]
**Library name**: maptalks
**Library description**: A light and plugable JavaScript library for integrated 2D/3D maps.
**Git repository url**: https://github.com/maptalks/maptalks.js
**npm package name or url (if there is one)**: https://www.npmjs.com/package/maptalks
**License (List them all if it's multiple)**: BSD-3-Clause
**Official homepage**: https://maptalks.org

**Comment by finch185277** [comment]
I want to take this.

**Comment by fuzhenn** [comment]
Thanks!
