### ISSUE TITLE
[Request] Add bootstrap-ie8

### ISSUE THREAD

**Issue by coliff** [cdnjs/cdnjs#12433]
**Library name:** bootstrap-ie8
**Library description:**  An IE8 and IE9 CSS solution for Bootstrap 4 
**Git repository url:**  https://github.com/coliff/bootstrap-ie8.git
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):**  MIT
**Official homepage:**  https://github.com/coliff/bootstrap-ie8
**Wanna say something? Leave message here:** 
Would be happy to see the CSS files from this project hosted.

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @coliff 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by coliff** [comment]
Thanks for the reply - sorry I missed the popularity requirement. I since found that I can use CDNJS for free  so will use that instead. Thanks!
