### ISSUE TITLE
[Request] Add clamp.js

### ISSUE THREAD

**Issue by lahbib** [cdnjs/cdnjs#12437]
**Library name:** clamp.js
**Library description:** Clamps (ie. cuts off) an HTML element's content by adding ellipsis to it if the content inside is too long.
**Git repository url:** https://github.com/josephschmitt/Clamp.js/
**npm package name or url** https://www.npmjs.com/package/clamp-js

**Comment by PeterDaveHello** [comment]
@lahbib any details?

**Comment by lahbib** [comment]
@PeterDaveHello,

Sorry, i've made PR quickly, i will update it..

**Comment by PeterDaveHello** [comment]
no worries :)

**Comment by extend1994** [comment]
The library have been hosted? https://cdnjs.com/libraries/Clamp.js
