### ISSUE TITLE
[Request] Add multi.js

### ISSUE THREAD

**Issue by Behoston** [cdnjs/cdnjs#12445]
**Library name:** multi.js
**Library description:** Better multi select fields 
**Git repository url:** https://github.com/Fabianlindfors/multi.js
**npm package name or url** (if there is one):  https://www.npmjs.com/package/multi.js
**License (List them all if it's multiple):** MIT
**Official homepage:** https://fabianlindfors.se/
**Wanna say something? Leave message here:** Nope

**Comment by extend1994** [comment]
Move to #10550 which is the same request as this. PR #12268 is in progress.
