### ISSUE TITLE
Typo in contributing guidelines

### ISSUE THREAD

**Issue by palkerecsenyi** [cdnjs/cdnjs#12443]
I found a typo in the CONTRIBUTING.md, line 48:

> The new library must have at least one officially public **accessable** repository and open source license.

'Accessible' is misspelt. The line should be:

> The new library must have at least one officially public **accessible** repository and open source license.

Thanks.

**Comment by Billy4195** [comment]
@palkerecsenyi Maybe you can fix it, and open a pull request 👍 
This will be a good start to contribute to this project.

**Comment by palkerecsenyi** [comment]
I have fixed this in pull request #12444

**Comment by PeterDaveHello** [comment]
Thanks @palkerecsenyi, merged!
