### ISSUE TITLE
[Error - 404] iframe-resizer

### ISSUE THREAD

**Issue by htkoca** [cdnjs/cdnjs#12447]
https://cdnjs.com/libraries/iframe-resizer

None of the URLS on the page seem to work? Please advise if I'm doing something incorrectly. I'm just copying the full URL to the browser bar and it throws a 404.

**Comment by PeterDaveHello** [comment]
Still 404? Would you please give us the response headers?

**Comment by holtkamp** [comment]
@PeterDaveHello there seems to be a delay / problem pushing new changes to the CDN? Lot of 404 on new versions, for example, the newest versions don's work:

https://cdnjs.com/libraries/iframe-resizer
https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.15/ie8.polyfils.map
https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.16/ie8.polyfils.map

https://cdnjs.com/libraries/chosen
https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.2/chosen.jquery.min.js
https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.3/chosen.jquery.min.js

https://cdnjs.com/libraries/blueimp-file-upload
https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.19.3/js/jquery.fileupload.min.js
https://cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/9.20.0/js/jquery.fileupload.min.js

https://cdnjs.com/libraries/blueimp-load-image
https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.17.1/load-image.min.js
https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.18.0/load-image.min.js

Also see https://github.com/cdnjs/cdnjs/issues/12452 https://github.com/cdnjs/cdnjs/issues/12455

**Comment by evromalarkey** [comment]
also another problem with https://cdnjs.com/libraries/intl-tel-input/12.1.7

**Comment by PeterDaveHello** [comment]
@evromalarkey thanks for report. @terinjokes would you please take a look?

**Comment by PeterDaveHello** [comment]
@ryankirkman please take a look.

**Comment by holtkamp** [comment]
thanks for the quick reaction. I now noticed this dependency on the CDN serving the files properly kind of breaks our continuous deployment approach. According to various "update" processes (bower, NPM, etc), a new stable version of a library is available. But when trying to actually reference it by pointing to the CDN, the 404 breaks this idea... 😞

**Comment by htkoca** [comment]
@PeterDaveHello Yeah it's still throwing it for me - but I see you're all on it already :)

```
GET Status: HTTP/1.1 404
--
Response Headers
	cache-control: public, max-age=14400
	cf-cache-status: HIT
	cf-ray: 3e3468d70c79717f-ORD
	content-encoding: br
	content-type: text/html; charset=utf-8
	date: Fri, 26 Jan 2018 15:12:16 GMT
	expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
	expires: Fri, 26 Jan 2018 19:12:16 GMT
	server: cloudflare
	status: 404
	strict-transport-security: max-age=15780000; includeSubDomains
	vary: Accept-Encoding
```

**Comment by terinjokes** [comment]
@PeterDaveHello Thanks for the pings. Fixed.

**Comment by holtkamp** [comment]
@terinjokes thanks! Any idea of the cause / chance of occurring again?
