### ISSUE TITLE
[Request] Add parchment

### ISSUE THREAD

**Issue by miestasmia** [cdnjs/cdnjs#12450]
**Library name:** parchment
**Library description:** Parchment is Quill's document model. It is a parallel tree structure to the DOM tree, and provides functionality useful for content editors, like Quill.
**Git repository url:** https://github.com/quilljs/parchment
**npm package name or url** (if there is one): https://www.npmjs.com/package/parchment
**License (List them all if it's multiple):** BSD3-Clause
**Official homepage:** 
**Wanna say something? Leave message here:** While Parchment is generally only used as a dependency of Quill (which cdnjs already hosts), it is often needed to extend quilljs.

**Comment by extend1994** [comment]
354,923 downloads in the last month
