### ISSUE TITLE
Wrong version for LiveScript 1.5.0 (it is 1.4.0 on CDN)

### ISSUE THREAD

**Issue by pepkin88** [cdnjs/cdnjs#12459]
LiveScript seems to have configured an auto-updater, as of https://github.com/cdnjs/cdnjs/pull/3897, but the newest browser build was generated right after the 1.5.0 tagged commit (and was fixed later https://github.com/gkz/LiveScript/commit/87daae63c4e988eb5c5d0ab599654f58af6c8d0a).

Is there a way to trigger a reupload of the newest version? I don't have rights to the LiveScript repository.

These are the correct files: https://github.com/gkz/LiveScript/tree/master/browser

**Comment by extend1994** [comment]
Hi @pepkin88 cdnjs adds versions based on git tags, so on cdnjs.com v1.5.0 seems v1.4.0. Maybe you can open an issue there to ask can they fix the tag. cc @PeterDaveHello

**Comment by pepkin88** [comment]
I created a pull request for this issue, I thought it might me easier to update the library from a PR.

**Comment by pepkin88** [comment]
There's a new version of LiveScript, 1.6.0, correctly loaded onto CDNJS. Although 1.5.0 will remain untouched, using 1.6.0 is preferable. Therefore I'll close this issue.
