### ISSUE TITLE
[Request] Add websockets

### ISSUE THREAD

**Issue by pcgeek86** [cdnjs/cdnjs#12460]
**Library name:** websockets
**Library description:** Simple to use, blazing fast and thoroughly tested WebSocket client and server for Node.js
**Git repository url:** https://github.com/websockets/ws
**npm package name or url** (if there is one): websockets
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @pcgeek86 I think this library can't be directly used in a browser, like `<script src=".js">`?
Its [README.md](https://github.com/websockets/ws#ws-a-nodejs-websocket-library) says 
> Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object.

**Comment by pcgeek86** [comment]
@extend1994 Oh sorry about that. Please disregard. I tested it out in Node, but didn't realize it wasn't going to also work in the browser. I'll close this out. Cheers!

**Comment by extend1994** [comment]
No problem, thanks for request & quick response! 😄
