### ISSUE TITLE
[Request] Add art-template

### ISSUE THREAD

**Issue by jiang539** [cdnjs/cdnjs#12466]
**Library name:** art-template
**Library description: javasript template
**Git repository url: https://github.com/aui/art-template
**npm package name or url** (if there is one): 
**License (List them all if it's multiple): MIT
**Official homepage: http://aui.github.io/art-template/
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by finch185277** [comment]
https://github.com/cdnjs/cdnjs/issues/11276
same?

**Comment by jiang539** [comment]
yes
same

**Comment by jiang539** [comment]
When do I need to wait,
The project is almost over

**Comment by jiang539** [comment]
Thanks for the free service of CDNJS.
It's been more than a year
