### ISSUE TITLE
[Request] Add collect.js

### ISSUE THREAD

**Issue by raniesantos** [cdnjs/cdnjs#12474]
**Library name:** collect.js
**Library description:** Convenient and dependency free wrapper for working with arrays and objects
**Git repository url:** https://github.com/ecrmnn/collect.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/collect.js
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/ecrmnn/collect.js
**Wanna say something? Leave message here:** none

**Comment by finch185277** [comment]
I want to take this.
