### ISSUE TITLE
[Request][Author] Add supermap-cesium

### ISSUE THREAD

**Issue by zouyaoji** [cdnjs/cdnjs#12477]
Library name: supermap-cesium
Git repository url: https://github.com/zouyaoji/supermap-cesium.git
npm package name or url (if there is one): https://www.npmjs.com/package/supermap-cesium
License (List them all if it's multiple): Apache-2.0
Official homepage:
Wanna say something? Leave message here:

=====================

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@zouyaoji Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by zouyaoji** [comment]
@sufuf3 
Hi, supermap-cesium was developed by [SuperMap](https://www.supermapol.com/), a GIS company focused on online hosting and application of GIS data. supermap-cesium, which is built on [Cesium](https://github.com/AnalyticalGraphicsInc/cesium), allows users to upload and visualize a variety of 3D data types, including BIM, point clouds, 3ds max models, and oblique photographic models. Users can take advantage of the application’s measurement tools, including measuring length, area, and height. The application also offers analysis, such as viewshed, line of sight, and skyline.

LIke [this...](http://support.supermap.com.cn:8090/webgl/examples/examples.html#layer) and [this...](http://www.supermapol.com/earth/)

Best regards！
