### ISSUE TITLE
[Request] Add bchaddrjs

### ISSUE THREAD

**Issue by stabwah** [cdnjs/cdnjs#12475]
**Library name:** bchaddrjs
**Library description:** Bitcoin Cash general purpose address translation for Node.js and web browsers. 
**Git repository url:** https://github.com/bitcoincashjs/bchaddrjs
**npm package name or url** (if there is one): bchaddrjs
**License (List them all if it's multiple):** MIT
**Official homepage:** https://bitcoincashjs.github.io/
**Wanna say something? Leave message here:** This is not my project but is a core library for all Bitcoin Cash development in JavaScript

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @stabwah 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: 
We suggest you open a issue again when the repo has notable popularity. 

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 

Thank you for your request!

**Comment by extend1994** [comment]
Close this issue due to no response and insufficient popularity. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We could try this one
