### ISSUE TITLE
[Request] Add taylorhakes/promise-polyfill

### ISSUE THREAD

**Issue by BenjaminEHowe** [cdnjs/cdnjs#12487]
**Library name:** taylorhakes/promise-polyfill
**Library description:** a polyfill for promises in older browsers
**Git repository url:** https://github.com/taylorhakes/promise-polyfill
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** 

... will probably (eventually) send a pull request! :-)

**Comment by bramus** [comment]
Would be handy, as https://github.com/github/fetch (which is supported by cdnjs: https://cdnjs.com/libraries/fetch) recommends adding this one too _(if you want to use promises)_.

**Comment by bramus** [comment]
Also: this one's a duplicate of https://github.com/cdnjs/cdnjs/issues/11802
