### ISSUE TITLE
[Request] Add smart-app-banner

### ISSUE THREAD

**Issue by Skyost** [cdnjs/cdnjs#12488]
**Library name:** smart-app-banner
**Library description:** Lightweight smart app banner with no jquery requirement.
**Git repository url:** https://github.com/kudago/smart-app-banner
**npm package name or url (if there is one):** smart-app-banner
**License (List them all if it's multiple):** MIT License.
**Official homepage:** https://github.com/kudago/smart-app-banner
**Wanna say something? Leave message here:** I'm not the owner of this project but it would be nice if another smart app banner was added to cdnjs because the only one available is abandonned.

**Comment by ralphchung** [comment]
I will take it.
