### ISSUE TITLE
Add Save.js

### ISSUE THREAD

**Issue by santanuthepro** [cdnjs/cdnjs#12496]

**Comment by extend1994** [comment]
Hi @santanuthepro 
Assuming you're requesting https://github.com/santanuthepro/Save.js.
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by extend1994** [comment]
Close due to no response and insufficient information, cc @PeterDaveHello
