### ISSUE TITLE
[Request] Update jquery.pwstrength.bootstrap to 2.2.0

### ISSUE THREAD

**Issue by Z1ni** [cdnjs/cdnjs#12491]
**Library name:** jquery.pwstrength.bootstrap
**Git repository url:** https://github.com/ablanco/jquery.pwstrength.bootstrap
Current hosted version is 2.1.1, but the newest one (at the time of writing) is 2.2.0

**Comment by extend1994** [comment]
Hi @Z1ni cdnjs currently use [its npm registry](https://www.npmjs.com/package/pwstrength-bootstrap) as library source, when the author release v2.2.0 on npm, cdnjs will also update it too. So if are in hurry to get v2.2.0, my suggestion for you is: Open an issue in ablanco/jquery.pwstrength.bootstrap to ask the author can he release v2.2.0 on npm.
Thanks for request.
