### ISSUE TITLE
[author] bootstrap-select has moved to a new location

### ISSUE THREAD

**Issue by caseyjhol** [cdnjs/cdnjs#12520]
I've moved development and all future releases of bootstrap-select to https://github.com/snapappointments/bootstrap-select. I released v1.13.0-beta today. The NPM and Nuget packages have already been updated accordingly, but I'm unsure of the best way to update CDNJS with the latest version (as, presumably, it's checking in silviomoreto/bootstrap-select). Is there a protocol here? Or should I just submit a PR? I'll be adding npm auto-update in the next release.

**Comment by PeterDaveHello** [comment]
@caseyjhol just a PR to update its auto-update config please :) Thank you.
