### ISSUE TITLE
Fast XML Parser latest is not updated

### ISSUE THREAD

**Issue by amitguptagwl** [cdnjs/cdnjs#12525]
I just checked and found that the library version of fast xml parser is a bit old and not being updated on cdnjs. Can you please check?

https://cdnjs.com/libraries/fast-xml-parser

**Comment by PeterDaveHello** [comment]
@amitguptagwl what's the expected latest version?

**Comment by amitguptagwl** [comment]
3.2.0

**Comment by amitguptagwl** [comment]
@PeterDaveHello Have you get the chance to look into?

**Comment by PeterDaveHello** [comment]
@amitguptagwl yes I'm doing, actually they removed the file on npm registry, we'll switch to use git auto-update, however, there are few versions on there GitHub, if you need other missing versions, please open an issue to request upstream to add git tags for the versions, thanks.

**Comment by amitguptagwl** [comment]
I believe it is fine to point latest version. Many thanks to solve the issue.

**Comment by amitguptagwl** [comment]
One of the contributors replaced browserify with webpack (didn't remember the version or date right now). So probably the file contents may have been changed. Regarding the folder structure, there was no change for the browser bundle file.

**Comment by PeterDaveHello** [comment]
@amitguptagwl looks like it's now minified by default? Am I right?

**Comment by amitguptagwl** [comment]
Yes, you're right.

**Comment by PeterDaveHello** [comment]
@amitguptagwl just asking, would you consider to add suffix .min to the minified file, and keep a src file there?

**Comment by amitguptagwl** [comment]
Sure, let me do that. I'll revert you back. Thanks

**Comment by amitguptagwl** [comment]
@PeterDaveHello done.

**Comment by amitguptagwl** [comment]
@PeterDaveHello Have you get the chance to check it?
