### ISSUE TITLE
CORS issue with assets requested by loaded resources (ionicons in this instance)

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#12537]
As seen in the screenshot below, when a loaded resource from CDNJS loads another resource, it appears to in some cases have incorrect CORS present on it which then prevents it from being loaded. In this instance with ionicons it results in no icons being rendered as the font file ionicons relies on had CORS issues.
https://i.dabbitpri.me/tR0X4WneGd.png

**Comment by sufuf3** [comment]
@MattIPv4 Sorry for late reply.
Is this issue still bother you?
Many thanks.

**Comment by MattIPv4** [comment]
I looked into it further and it seems my intial report was slightly incorrect. In this instance ionicons was looking for a file that didn't exist on the cdn, so it was giving a 404. This 4040 however was unclean due to the resource still being blocked by the CORS as seen in the screenshot.

On testing now it seems 404s work as expected.
