### ISSUE TITLE
[Request] Add print.js

### ISSUE THREAD

**Issue by rajagopalx** [cdnjs/cdnjs#12536]
**Library name:** print.js
**Library description:**  A tiny javascript library to help printing from the web.
**Git repository url:**  https://github.com/crabbly/print.js
**npm package url:** https://www.npmjs.com/package/print.js
**License:**  MIT
**Official homepage:**  http://printjs.crabbly.com/

**Comment by sufuf3** [comment]
Duplicated with #10234
Working on  #12208

**Comment by extend1994** [comment]
Move to #10234
