### ISSUE TITLE
[Request] Add jquery.initialize

### ISSUE THREAD

**Issue by dbezborodovrp** [cdnjs/cdnjs#12541]
**Library name:** jquery.initialize
**Library description:** jQuery plugin for dynamically created elements initialization.
**Git repository url:** https://github.com/pie6k/jquery.initialize.git
**npm package name or url** (if there is one): `jquery.initialize` ([npm](https://www.npmjs.com/package/jquery.initialize))
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/pie6k/jquery.initialize
**Owner:** @pie6k

**Comment by dbezborodovrp** [comment]
Has 91 stars on Github and 74 downloads in the last month from [npmjs.com](https://www.npmjs.com/package/jquery.initialize)

**Comment by extend1994** [comment]
Hi @dbezborodovrp 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :slightly_smiling_face: We suggest you open a issue again when the repo has notable popularity. 

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by dbezborodovrp** [comment]
Thank you for your response. I will wait until the above criteria is met.

**Comment by extend1994** [comment]
Thanks @dbezborodovrp :+1: 
Close due to insufficient popularity for now, cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@dbezborodovrp if you'd like to send a PR for it, we could accept it :)
