### ISSUE TITLE
[Request] Add Mainloop.js

### ISSUE THREAD

**Issue by FlorentMasson** [cdnjs/cdnjs#12542]
**Library name:** Mainloop.js
**Library description:** MainLoop.js provides a well-constructed main loop useful for JavaScript games and other animated or time-dependent applications. 
**Git repository url:** https://github.com/IceCreamYou/MainLoop.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/mainloop.js
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/mainloop.js
