### ISSUE TITLE
[Request] Add hyperHTML

### ISSUE THREAD

**Issue by NKjoep** [cdnjs/cdnjs#12546]
**Library name:** hyperHTML

**Library description:** 
A Fast & Light Virtual DOM Alternative available for NodeJS and NativeScript too.

**Git repository url:** 
https://github.com/WebReflection/hyperHTML 

**npm package name or url**: 
https://www.npmjs.com/package/hyperhtml

**License (List them all if it's multiple):** 
ISC License

**Official homepage:**
https://viperhtml.js.org/

**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by James-N-M** [comment]
Can I take this issue

**Comment by PeterDaveHello** [comment]
@James-N-M :+1

**Comment by James-N-M** [comment]
Thank you ! @PeterDaveHello

**Comment by WebReflection** [comment]
@NKjoep not sure why you pinged me here ... the library is used regularly via unpkg.com, not sure why there's so much friction in this CDN ... open since February, oh well ...

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/hyperHtml
