### ISSUE TITLE
AdmLte

### ISSUE THREAD

**Issue by xFirez** [cdnjs/cdnjs#12557]
Please add the latest version of Admlte to the cdn.

**Comment by extend1994** [comment]
@xFirez Please provide further information such as git repo or npm registry, thanks.
If there is no response in next 7 days, I'll close this issue.

**Comment by xFirez** [comment]
https://github.com/almasaeed2010/AdminLTE/releases

**Comment by extend1994** [comment]
@xFirez It has been hosted. https://cdnjs.com/libraries/admin-lte
Close issue because requested lib has been hosted, cc @PeterDaveHello
