### ISSUE TITLE
ECharts 4.0.3 files missing

### ISSUE THREAD

**Issue by jarben** [cdnjs/cdnjs#12558]
Just tried a new version of ECharts 4.0.3 and files seems to be missing, eg:
https://cdnjs.cloudflare.com/ajax/libs/echarts/4.0.3/echarts.min.js

Thoughts? :)

**Comment by PeterDaveHello** [comment]
@jarben thanks for report, seems to be the same as #12552, waiting for @terinjokes to fix it on the Cloudflare side.

**Comment by jarben** [comment]
Thanks @PeterDaveHello , glad it's been looked at!

**Comment by PeterDaveHello** [comment]
Let's move to #12552
