### ISSUE TITLE
Some cdnjs cloudflare servers are blocking requests from a cloud-based browser

### ISSUE THREAD

**Issue by apm** [cdnjs/cdnjs#12555]
I work for Authentic8, Inc, which provides a cloud-based browser called Silo.

https://www.authentic8.com

Since we have a large number of servers in the cloud, we do on occasion have sites that block our traffic (thinking we may be a bot or whatnot), and we do have ways to deal with this.  The cdnjs issue is much more of a problem for us because cdnjs is causing various host sites to hang without an error message.

Specifically this recently came up while attempting to log into jira.com.  About four out of five times the login page hangs while attempting to load https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js.

Attempting to load this resource from my app server with wget, I get a list of five servers, one of which works and the others all time out.

$ wget https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js
--2018-02-26 22:20:32--  https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js
Resolving cdnjs.cloudflare.com (cdnjs.cloudflare.com)... 104.19.195.102, 104.19.192.102, 104.19.193.102, ...
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.19.195.102|:443... failed: Connection timed out.
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.19.192.102|:443... failed: Connection timed out.
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.19.193.102|:443... failed: Connection timed out.
Connecting to cdnjs.cloudflare.com (cdnjs.cloudflare.com)|104.19.196.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/javascript]
Saving to: ‘require.min.js’

Obviously this is an operations question and may not be appropriate in this location, but I couldn't find a better place.  Is this something that I can get help with here, or is there somewhere you can direct me?

Thanks,

-Adam

**Comment by PeterDaveHello** [comment]
@apm as we don't directly operate the CDN servers, would you please send a support ticket here: https://support.cloudflare.com/hc/en-us ? Thanks.

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by apm** [comment]
Thanks @PeterDaveHello, I started there, but the support articles are geared for customers rather than service providers indirectly impacted by cloudflare access restrictions or misconfiguration.  Eventually went through the community vetting process to submit https://community.cloudflare.com/t/4-5-cdnjs-cloudflare-com-hosts-hang-when-accessed-from-cloud-browser/12966, hopefully that gets me somewhere.

**Comment by drewfreyling** [comment]
@apm let us know if you get the issue sorted

**Comment by apm** [comment]
@drewfreyling, you bet.  The cloudflare thread is https://community.cloudflare.com/t/4-5-cdnjs-cloudflare-com-hosts-hang-when-accessed-from-cloud-browser/12966

**Comment by apm** [comment]
I didn't get an update in the cloudflare thread, but today this issue appears to be fixed.

**Comment by drewfreyling** [comment]
Thanks for the update. Closing.
