### ISSUE TITLE
[Error 404] With update 2.7.0 for Gridlex

### ISSUE THREAD

**Issue by devlint** [cdnjs/cdnjs#12552]
Hello

- If you look at https://cdnjs.com/libraries/gridlex, the 2.7.0 is now the last version updated.
- If you look at the last commit for update https://github.com/cdnjs/cdnjs/commit/852b5fd246630f62b06.1ad9ef916b3b25b8e81b5#diff-741fa7ecc4ecafce59cccc64a5a07164 the 4 new files are good, 
- If you go to https://cdnjs.cloudflare.com/ajax/libs/gridlex/2.7.0/gridlex.css you fall on a 404 error.

Can you fix it ?
Thank you

**Comment by PeterDaveHello** [comment]
There may be something wrong, it'll need Cloudflare to help(@terinjokes)

**Comment by sukima** [comment]
[Hack CSS also affected](https://github.com/cdnjs/cdnjs/commit/c3fa11d4494ca430a6f946ea456c1cfd0b56fcc6#commitcomment-27815064)

**Comment by devlint** [comment]
Some news? Thx

**Comment by terinjokes** [comment]
A quick update here. I'm aware that there's some 404s with newer assets. There's some issues with the ingestion of those resources that I'm currently working through.

**Comment by eiginn** [comment]
Issue should be resolved at this point.

**Comment by devlint** [comment]
Thx @terinjokes, it works perfectly!

**Comment by PeterDaveHello** [comment]
Thanks @terinjokes @eiginn
