### ISSUE TITLE
[Fix] Update babel-polyfill

### ISSUE THREAD

**Issue by virgofx** [cdnjs/cdnjs#12563]
The CDNJS `babel-polyfill` library currently refers to the old location below. It's preventing updates that exist in the same package which transitioned to the new organizational structure for the 7.x series. Can the library be updated to point to the new NPM location and then fill the current releases please. The name can still stay the same ... no need to change anything.

Old: https://www.npmjs.com/package/babel-polyfill
New: https://www.npmjs.com/package/@babel/polyfill

Current release: 7.0.0-beta.40  (Not in CDNJS)

**Comment by virgofx** [comment]
Thanks ! 👍

**Comment by PeterDaveHello** [comment]
Thanks for reporting :grinning:

**Comment by holtkamp** [comment]
@PeterDaveHello minor ping on the auto-updating mechanism

Latest release on CDNJS is [`7.2.5`](https://cdnjs.com/libraries/babel-polyfill), while [`7.3.4` has been released on 2019-02-25](https://github.com/babel/babel/releases).
