### ISSUE TITLE
[Request] Add Yotpo-Rich-Snippets

### ISSUE THREAD

**Issue by Paatsu** [cdnjs/cdnjs#12567]
**Library name:** Yotpo-Rich-Snippets
**Library description:** Yotpo Rich Snippet Solutions
**Git repository url:** https://github.com/Tiggerito/Yotpo-Rich-Snippets
**Official homepage:** https://websiteadvantage.com.au/Yotpo-Product-Rating-Review-Rich-Snippets?utm_source=Yotpo-Rich-Snippets-WordPress-Plugin&utm_medium=WordPress-Plugin-Page-Link&utm_campaign=Yotpo-Rich-Snippets-WordPress-Plugin

**Comment by extend1994** [comment]
Hi @Paatsu 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
 We suggest you open a issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by extend1994** [comment]
Close the issue due to no response & insufficient popularity, cc @PeterDaveHello
