### ISSUE TITLE
Prop-Types 15.6.1 Not Working

### ISSUE THREAD

**Issue by virgofx** [cdnjs/cdnjs#12560]
The latest release of `prop-types` 15.6.1 results in Nginx 404 not found.

https://cdnjs.cloudflare.com/ajax/libs/prop-types/15.6.1/prop-types.js

15.6.0 and below works.

**Comment by virgofx** [comment]
Appears nothing was changed on the Facebook release side. Did something go wrong with this release?

**Comment by aweary** [comment]
Looks to be working now @virgofx 🙂

**Comment by virgofx** [comment]
Oh wow ... yes it's working. The link above (and other minified version) we not working as of yesterday and earlier today.

Not sure what happened?

Weird.

If anyone has any other information, that'd be helpful, otherwise, will close for now.

**Comment by PeterDaveHello** [comment]
@virgofx see #12552, should be fixed now, thanks.
