### ISSUE TITLE
[Request] Add OverlayScrollbars

### ISSUE THREAD

**Issue by KoalaBear84** [cdnjs/cdnjs#12562]
**Library name:** OverlayScrollbars
**Library description:** A javascript scrollbar plugin which hides the native scrollbars and provides
custom styleable overlay scrollbars, but keeps the native functionality and feeling.
**Repository url:** https://github.com/KingSora/OverlayScrollbars/
**npm package url:** https://www.npmjs.com/package/overlayscrollbars
**License:** MIT
**Official homepage:** https://kingsora.github.io/OverlayScrollbars/
**Wanna say something? Leave message here:** I would love to have OverlayScrollbars to the cdnjs! I am not the author.

It is a relatively new library which is a high quality one for custom scrollbars on websites with great customization and browser support.

**Comment by Audiodrome** [comment]
@extend1994 Could I help with this one?

**Comment by extend1994** [comment]
@Audiodrome Sure :+1:

**Comment by KoalaBear84** [comment]
Thank you very much!
