### ISSUE TITLE
[Request][Author] Add anim8js

### ISSUE THREAD

**Issue by ClickerMonkey** [cdnjs/cdnjs#12572]
**Library name:** anim8js
**Library description:** An animation library for javascript.
**Git repository url:** https://github.com/anim8js
**npm package name or url** (if there is one): anim8js
**License (List them all if it's multiple):** MIT
**Official homepage:** http://anim8js.github.io/anim8js/
**Wanna say something? Leave message here:** 

I've included the organization's URL, there are several repos in there:
https://github.com/anim8js/anim8js
https://github.com/anim8js/anim8js-dom
https://github.com/anim8js/anim8js-scrollmagic
https://github.com/anim8js/anim8js-pixi
https://github.com/anim8js/anim8js-jquery
https://github.com/anim8js/anim8js-easel
https://github.com/anim8js/anim8js-animate.css

I recognize that these projects are not that widely used yet, but they are used in many production products by companies of all sizes. Part of this request is to make the library as easy to test out as its competition (velocity, greensock, etc). 

Thank you for your time!

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@ClickerMonkey 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Ref: https://npm-stat.com/charts.html?package=anim8js&from=2018-01-01&to=2018-04-05

**Comment by ClickerMonkey** [comment]
Thanks for the feedback. I understand the popularity requirement - it's just a Catch-22 sometimes. You need your library to be more accessible for people to test it out, but you can't because not enough people have looked into it!

Thanks for your time.

**Comment by sashberd** [comment]
@sufuf3 Is this one should be closed?

**Comment by extend1994** [comment]
@PeterDaveHello How can we do in this issue?
