### ISSUE TITLE
Fix repo url for marked

### ISSUE THREAD

**Issue by styfle** [cdnjs/cdnjs#12579]
Recently, `marked` has changed to a [GitHub org](https://github.com/markedjs/marked) as seen on [npm](https://www.npmjs.com/package/marked).

However, [cdnjs](https://cdnjs.com/libraries/marked) still shows the old repo url.

How can this be fixed?

**Comment by PeterDaveHello** [comment]
@styfle thanks for the info! I think you can try to update its package.json in this repository, should be ajax/libs/marked/package.json :)

**Comment by styfle** [comment]
@PeterDaveHello I created https://github.com/cdnjs/cdnjs/pull/12580
Looks like theres a big checklist to go through so I'm not sure if that is all relevant or if that's only for new packages being added.

**Comment by PeterDaveHello** [comment]
Should be good now, thanks.
