### ISSUE TITLE
[Request] Add dom-to-image 

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12574]
**Library name:** dom-to-image 
**Git repository url:** https://github.com/tsayen/dom-to-image
**npm package name or url** (if there is one): https://www.npmjs.com/package/dom-to-image
**License (List them all if it's multiple):** [MIT](https://github.com/tsayen/dom-to-image/blob/master/LICENSE)
**Official homepage:** none

**Comment by finch185277** [comment]
#8589
same?

**Comment by extend1994** [comment]
Thanks @finch185277 That's right.
Close due to the library has been hosted.
