### ISSUE TITLE
[Request] Add uppy

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12585]
**Library name:** uppy
**Git repository url:** https://github.com/transloadit/uppy
**npm package name or url** (if there is one): https://www.npmjs.com/package/uppy
**License (List them all if it's multiple):** [MIT](https://github.com/transloadit/uppy/blob/master/LICENSE)
**Official homepage:** https://uppy.io/

**Comment by finch185277** [comment]
#12391 
same?

**Comment by extend1994** [comment]
Thanks again @finch185277 
Close due to the request had been opened in the other issue.
