### ISSUE TITLE
[Request][author] Add loaderz

### ISSUE THREAD

**Issue by TotomInc** [cdnjs/cdnjs#12586]
**Library name:** loaderz
**Library description:** A very easy-to-use, blazing fast asset-loader using promises. Support older-browsers and preload images, audios and videos.
**Git repository url:** https://github.com/TotomInc/loaderz
**npm package name or url** (if there is one): https://www.npmjs.com/package/loaderz
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/TotomInc/loaderz

**Comment by extend1994** [comment]
Hi @TotomInc 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
We suggest you open the issue again when the repo has notable popularity.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

cc @Billy4195

**Comment by TotomInc** [comment]
I'll reopen the issue once it gets more popular.

**Comment by PeterDaveHello** [comment]
@TotomInc thank you
