### ISSUE TITLE
[Request] Add Adminator HTML5 Admin Template

### ISSUE THREAD

**Issue by goodjack** [cdnjs/cdnjs#12592]
**Library name:** Adminator HTML5 Admin Template
**Library description:** Adminator is a easy to use and well design admin dashboard template for web apps, websites, services and more
**Git repository url:** https://github.com/puikinsh/Adminator-admin-dashboard
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://colorlib.com/polygon/adminator/index.html
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
cdnjs doesn't host html. Closing.
