### ISSUE TITLE
CDNJS pingdom uptime report not accessible to public

### ISSUE THREAD

**Issue by sunnymui** [cdnjs/cdnjs#12599]
The pingdom uptime report accessed via the main cdnjs.com website isn't accessible to the public. I'm talking about the nav menu option at the top of the page labeled 'Uptime'.

The URL linked is [http://stats.pingdom.com/4jg86a2wqei0](http://stats.pingdom.com/4jg86a2wqei0)

The error message given when clicking on the link reads:

### Public Report Not Activated
This public report page has not been activated by the user, i.e. this user has not made any checks public.

There was an older closed issue about this when searching the issues but that was back in 2015.

**Comment by ryankirkman** [comment]
Looking into it

**Comment by MattIPv4** [comment]
Appears to have since been fixed.
