### ISSUE TITLE
[Request] Add Pretty Embed

### ISSUE THREAD

**Issue by kataroek** [cdnjs/cdnjs#12590]
**Library name:** Pretty Embed
**Library description:** Prettier embeds for your YouTubes - with nice options like high-res preview images, advanced customization of embed options, and optional FitVids support. 
**Git repository url:** https://github.com/mike-zarandona/PrettyEmbed.js/
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
