### ISSUE TITLE
Addition of compressed Jquery File

### ISSUE THREAD

**Issue by RuthlessRuler** [cdnjs/cdnjs#12605]
Can you please add a much compressed version of jquery.min.js file of v2.2.4 like the one i have on my repository here: https://github.com/RuthlessRuler/compressed-jquery-font-awesome/blob/master/jquery-2.2.4.min.js.

It would be really nice since jQuery is comparatively large files and the most compressed version will have significant lower file size than previous version which will accelerate page speed.  the deafult version that are served by most CDNs arent well compressed.

Also more options in jQuery like Google ones will be good too.

**Comment by sufuf3** [comment]
@RuthlessRuler Is this good for you?
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
From: https://cdnjs.com/libraries/jquery/2.2.4
If you have any question, please let me know.
Many thanks.

**Comment by RuthlessRuler** [comment]
Definitely!

**Comment by xtuc** [comment]
We apparently not serve with gzip, but the file is minified
