### ISSUE TITLE
[Request] Add jquery.videoBG.js

### ISSUE THREAD

**Issue by stephenstewart-ca** [cdnjs/cdnjs#12606]
jquery.videoBG.js
This jQuery plugin uses HTML5 video as a background for any div.
https://github.com/sydlawrence/jquery.videoBG
Donate a beer.
http://syddev.com/jquery.videoBG/
No current maintainer, but it works all right.

**Comment by MattIPv4** [comment]
Library appears to no longer be maintained, closing.
