### ISSUE TITLE
bump gauge.js to latest version

### ISSUE THREAD

**Issue by ggerber** [cdnjs/cdnjs#12614]
Good day,

Can you bump gauge.js v1.3.5 (https://cdnjs.com/libraries/gauge.js) to the latest version (1.3.6)?

The github repo is here:
https://github.com/bernii/gauge.js

Kind regards,
George

**Comment by PeterDaveHello** [comment]
v1.3.6 is not tagged or released yet: https://github.com/bernii/gauge.js/releases, point me if I'm wrong, thanks :)

**Comment by ggerber** [comment]
hi,
if you look in the package.json file on github, the latest version is 1.3.6

so i think cdnjs has the old version.
kind regards

**Comment by PeterDaveHello** [comment]
@ggerber the author should tag that version, that's the reliable reference, but package.json is not, I'll respectfully suggest you to open an issue to upstream repository to confirm that :)

**Comment by ggerber** [comment]
hi peter,
the author of gauge.js has tagged his project to the latest version 1.3.6.

would you be so kind as to make this version available on cdnjs?

kind regards,
george

**Comment by Billy4195** [comment]
@ggerber the gauge.js v1.3.6 is already available on [cdnjs.com](https://cdnjs.com/libraries/gauge.js). 
Are there any missing files that you need to use??

**Comment by PeterDaveHello** [comment]
@ggerber see 18276d36d6729d220fa4fa81fd219692b5e6872e

**Comment by ggerber** [comment]
Thank you Peter,

The latest version on cdnjs works now.

Kind regards,
George
