### ISSUE TITLE
[author][FIX] jquery-ui-multiselect-widget

### ISSUE THREAD

**Issue by mlh758** [cdnjs/cdnjs#12611]
The library is at: https://cdnjs.com/libraries/jquery-ui-multiselect-widget/3.0.0

I have recently tagged a pre-release for 3.0.0 but there was a change to the folder structure. My css files are now under /css (https://github.com/ehynds/jquery-ui-multiselect-widget/tree/version3/css). These aren't getting picked up by the cdn.

Do I need to merge the branch to master for this to get picked up? I would prefer to keep it separate for a little while if possible although it will be going into master soon-ish anyway and if that's the fix I can push it up.

**Comment by extend1994** [comment]
@PeterDaveHello I noticed you add 3.0.0 6 days ago, not sure how to handle this issue, please take a look at it, thanks.

**Comment by PeterDaveHello** [comment]
@extend1994 OK, thanks.

**Comment by mlh758** [comment]
Any update on this?

**Comment by MattIPv4** [comment]
No subsequent versions have been released, we can't modify versions that are already on the CDN. Closing.
