### ISSUE TITLE
[Request][Author] Add ilib

### ISSUE THREAD

**Issue by ehoogerbeets** [cdnjs/cdnjs#12626]
**Library name:** ilib
**Library description:** A set of i18n classes in pure javascript
**Git repository url:** https://github.com/iLib-js/iLib
**npm package name or url** (if there is one): https://www.npmjs.com/package/ilib
**License (List them all if it's multiple):** apache2
**Official homepage:** https://github.com/iLib-js/iLib/wiki
**Wanna say something? Leave message here:** Not so popular on npm by itself, but it is used on over 60 million LG webOS SmartTVs because it is the main i18n library behind enyo and enact. So if you want to use those frameworks, you need ilib.

**Comment by extend1994** [comment]
Hope this helps: https://github.com/iLib-js/iLib/blob/development/docs/GettingStarted.md#including-ilib

**Comment by sashberd** [comment]
Hi @ehoogerbeets 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
