### ISSUE TITLE
CDNJS Assets with SRI tags are not loaded by MS Edge

### ISSUE THREAD

**Issue by couven92** [cdnjs/cdnjs#12620]
JS Sript and CSS link tags that use the SRI Hash from the CDNJS website are not loaded by the Edge Browser.

Here is an example of the error log when accessesing https://cdnjs.com/

```
 SEC14318: The blocked resource has a hash of 'kb8pRNu1sIwQEWAO/Mqt1S5PZ5xiLd4nBMoSsqdxKPs='.

 SCRIPT5009: '_bsa' is not defined
cdnjs.com (1,8292)

 SEC14318: The blocked resource has a hash of 'IYGI0ovdtvTnw19p8rG6jZjmlX+5x+4rw9uAhk+5OC4='.

 SEC14318: The blocked resource has a hash of 'eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0='.

 SEC14318: The blocked resource has a hash of 'CYVY39mQQ+3yRKbAaPcIrOcRUUVw+L3BFBM1s/lRb0s='.

11 SEC14318: The blocked resource has a hash of ''.

 SCRIPT5009: 'hljs' is not defined
```

causing the CDNJS Homepage to render like this:

![image](https://user-images.githubusercontent.com/8759693/37553458-d57b96f0-29c8-11e8-8f92-a9e0d1691f83.png)

**Comment by PeterDaveHello** [comment]
@couven92 hmmm, interesting, I'm not sure how can we do this and maybe this is something we can't fixed, shold be fixed by

**Comment by couven92** [comment]
@PeterDaveHello Maybe Edge does not support the SHA algorithm you use in your SRI tags?

**Comment by PeterDaveHello** [comment]
@couven92 not sure yet, I don't use Windows for a while, would you please test with other sites that enabled SRI? I'd like to see how can we deal with it, many thanks.

**Comment by couven92** [comment]
Okay, so I ran MS-Edge through the W3C test for Subresource Integrity. Out of 42 tests, MS Edgre fails 16! Comparison: Firefox passes all 42 tests.

Here's a summary of which SRI test cases MS Edge fails: [w3c-test-subresource-integrity-msedge.pdf](https://github.com/cdnjs/cdnjs/files/1821490/w3c-test-subresource-integrity-msedge.pdf)

I am running `Micorosoft Edge 41.16299.248.0` on `Windows 10 Build 16299.rs3_release.170928-1534`

**Comment by couven92** [comment]
I did some more checking, and I realized I had enabled some experimental options in MS Edge on the `about:flags` in the `Standards Preview` section, resetting all flags to default settings in MS Egde and restarting the browser causes CDNJS to render properly again.

**Comment by PeterDaveHello** [comment]
@couven92 Cool!
