### ISSUE TITLE
[Request] Add brain.js

### ISSUE THREAD

**Issue by rafaelcastrocouto** [cdnjs/cdnjs#12622]
**Library name:** brain.js
**Library description:** Neural network library
**Git repository url:** https://github.com/BrainJS/brain.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/brain.js
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://brain.js.org/
**Wanna say something? Leave message here:** Thx for your time!

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by finch185277** [comment]
#12281 
same?

**Comment by rafaelcastrocouto** [comment]
yes sorry ... plz close!

**Comment by finch185277** [comment]
@rafaelcastrocouto 
Thanks.
