### ISSUE TITLE
[Request] Add file-icon-classic.min.css

### ISSUE THREAD

**Issue by kevegabi** [cdnjs/cdnjs#12633]
**Library name:** file-icon-classic.min.css
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Billy4195** [comment]
Hi @kevegabi, thanks for the request. 
Could you provide more info about this library? such as GitHub repo link or npm link?
Please help us to fill the field of the library info such that we can better understand which library you're requesting.

**Comment by sufuf3** [comment]
@kevegabi Do you mean you want to let this lib https://github.com/dmhendricks/file-icon-vectors be added in CDNJS?
Many thanks.

**Comment by PeterDaveHello** [comment]
Closing now due to no response, feel free to reopen it if I missed anything.
