### ISSUE TITLE
Prism 1.13.0 returning 404

### ISSUE THREAD

**Issue by DaleMckeown** [cdnjs/cdnjs#12634]
All the resources for Prism 1.13.0 are returning 404 errors:

Example: https://cdnjs.cloudflare.com/ajax/libs/prism/1.13.0/themes/prism.css

**Comment by nao-pon** [comment]
It same in elfinder too.

> 404 Not Found

- https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.35/js/elfinder.min.js

**Comment by Dogfalo** [comment]
We have the same problem in materialize as well: 
https://cdnjs.com/libraries/materialize/1.0.0-beta

**Comment by PeterDaveHello** [comment]
Cloudflare fixed it :) Thanks for reporting.
