### ISSUE TITLE
[Request] Add startbootstrap-sb-admin

### ISSUE THREAD

**Issue by leonirlopes** [cdnjs/cdnjs#12632]
**Library name:** SB Admin
**Library description:** SB Admin is a free to download Bootstrap admin template. This template uses the defaul Bootstrap 4 styles along with a variety of powerful plugins to create a powerful framework for creating admin panels, web apps, or back-end dashboards.
**Git repository url:** https://github.com/BlackrockDigital/startbootstrap-sb-admin
**npm package name or url** (if there is one): https://www.npmjs.com/package/startbootstrap-sb-admin
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://startbootstrap.com/template-overviews/sb-admin/
**Wanna say something? Leave message here:** A Bootstrap 4 admin theme with powerful plugins to extend the functionality of the Bootstrap framework.

**Comment by Billy4195** [comment]
Hi @leonirlopes, Thanks for the request.
Does the [SB admin 2](https://github.com/BlackrockDigital/startbootstrap-sb-admin-2) is the same as [SB admin](https://github.com/BlackrockDigital/startbootstrap-sb-admin), or what is the difference between them?

**Comment by leonirlopes** [comment]
Similar. It looks like they have UI differences.

**Comment by sufuf3** [comment]
Memo:
https://github.com/BlackrockDigital/startbootstrap-sb-admin is different from https://github.com/BlackrockDigital/startbootstrap-sb-admin-2 which be hosted on CDNJS.
