### ISSUE TITLE
[author] Correct the npmFileMap for jquery-validation-unobtrusive

### ISSUE THREAD

**Issue by jbagga** [cdnjs/cdnjs#12647]
Original PR to add jquery-validation-unobtrusive to cdnjs with npm autoupdate: https://github.com/cdnjs/cdnjs/pull/7332

The files have since moved to a "dist" directory and the `npmFileMap` in the `package.json` needs to be updated for auto update to work correctly.

**Comment by extend1994** [comment]
Close cause the issue had been solved #12648
