### ISSUE TITLE
[Request] Add vue2-leaflet

### ISSUE THREAD

**Issue by KoRiGaN** [cdnjs/cdnjs#12642]
**Library name:** vue2-leaflet
**Library description:** Vue2Leaflet is a JavaScript library for the Vue framework that wraps Leaflet making it easy to create reactive maps.
**Git repository url:** https://github.com/KoRiGaN/Vue2Leaflet
**npm package name or url** (if there is one): https://www.npmjs.com/package/vue2-leaflet
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** https://korigan.github.io/Vue2Leaflet/#
**Wanna say something? Leave message here:**

**Comment by finch185277** [comment]
I want to take this.
