### ISSUE TITLE
[Request] Add rearmed-js

### ISSUE THREAD

**Issue by westonganger** [cdnjs/cdnjs#12645]
**Library name:** rearmed-js
**Library description:** A collection of helpful methods and monkey patches for Arrays, Objects, Numbers, and Strings in Javascript
**Git repository url:** https://github.com/westonganger/rearmed-js
**npm package name or url** (if there is one): rearmed-js
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/westonganger/rearmed-js

**Comment by sashberd** [comment]
Hi @westonganger 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
