### ISSUE TITLE
Update auto-update config of "asciidoctor.js"

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#12653]
The structure changed since v1.5.6-rc.1, the auto-update config needs to be updated.

**Comment by PeterDaveHello** [comment]
Would @cdnjs/intern4 like to try?

**Comment by Mogztter** [comment]
Hello @PeterDaveHello, what needs to be done ?

**Comment by PeterDaveHello** [comment]
hmmm, just need a quick check about the relation of the release inside different folders that also be useful, like `browser`, `nashorn` and `umd`. I haven't take a look but not sure if the one under root could be used in multiple engines and the `browser` one is specified for the browsers,

**Comment by Mogztter** [comment]
`asciidoctor.js` (and `asciidoctor.min.js`) in the root directory are UMD module (for backward compatibility with previous releases).
But now we also provide a dedicated file per environment, so I think the following can be useful:

* `browser/asciidoctor.js`
* `umd/asciidoctor.js` (since the `asciidoctor.js` file at the root will be remove at some point)
* `nashorn/asciidoctor.js` (because as far as I know Nashorn does not provide a package manager)


Does it sound reasonable to you ?

**Comment by Mogztter** [comment]
@PeterDaveHello Could you please give me pointers on how to fix this issue ? Thanks 😊

**Comment by Mogztter** [comment]
Ping @PeterDaveHello

**Comment by Mogztter** [comment]
@PeterDaveHello Sure, I think it's fine but more specifically what needs to be changed ? I mean the current definition is not perfect but looks valid:

```json
{
  "npmName": "asciidoctor.js",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "**/*"
      ]
    }
  ]
```

Do I need to explicitly define a list of files ?

```json
{
  "npmName": "asciidoctor.js",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "asciidoctor.js",
        "asciidoctor.min.js",
        "css/asciidoctor.css",
        "nashorn/asciidoctor.js"
      ]
    }
  ]
```

Thanks

**Comment by PeterDaveHello** [comment]
What about?
```js
      "basePath": "dist",
      "files": [
        "asciidoctor.*",
        "css/asciidoctor.*",
        "nashorn/asciidoctor.*"
      ]
```

Would it be possible to provide minified version of nashorn build BTW?

**Comment by Mogztter** [comment]
> Would it be possible to provide minified version of nashorn build BTW?

Why not

> What about

I will create a pull request with your recommandation

**Comment by PeterDaveHello** [comment]
> Why not
Just asking because haven't see it, good it have it.

Thanks.

**Comment by PeterDaveHello** [comment]
@Mogztter PR merged! Please help provide minified js/css files in the future releases, thanks!
