### ISSUE TITLE
Update filter.js library

### ISSUE THREAD

**Issue by jlapitan** [cdnjs/cdnjs#12655]
request for updated version of https://github.com/jiren/filter.js

**Comment by PeterDaveHello** [comment]
@jlapitan what's the expected version, please?

**Comment by PeterDaveHello** [comment]
I didn't see any new release: https://github.com/jiren/filter.js/releases

**Comment by jlapitan** [comment]
latest version is 2.1

https://github.com/jiren/filter.js/tree/master/dist

**Comment by PeterDaveHello** [comment]
@jlapitan it's in master branch but not released
