### ISSUE TITLE
[Request] Add farbtastic

### ISSUE THREAD

**Issue by rturkek** [cdnjs/cdnjs#12650]
**Library name:** farbtastic
**Library description:** 
**Git repository url:** https://github.com/mattfarina/farbtastic
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:**  https://github.com/mattfarina/farbtastic
**Wanna say something? Leave message here:** 

=====================

**Comment by sashberd** [comment]
Hi @rturkek 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
