### ISSUE TITLE
[Request][Author] Add wof

### ISSUE THREAD

**Issue by muhibbudins** [cdnjs/cdnjs#12663]
**Library name:** wof
**Library description:** Configurable wheel of fortune with specific angle, build with ES6, Webpack and SASS.
**Git repository url:** https://github.com/muhibbudins/wheel-of-fortune
**npm package name or url (if there is one):** wof
**License (List them all if it's multiple):** MIT

**Comment by sufuf3** [comment]
Hi @muhibbudins 
Thanks for the suggestion, however, this library doesn't have enough notable popularity(like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by muhibbudins** [comment]
Hi @sufuf3 ,
Thanks for the feedback, i forgot about it. Maybe i will open new issue if my library gets popular.

Thank you very much

**Comment by sufuf3** [comment]
Thanks for your response.
Feel free open an issue again or reopen this issue when this library have enough notable popularity.
Thank you very much.

Close this issue because this library doesn't have enough notable popularity.
cc @PeterDaveHello
