### ISSUE TITLE
[Request] Add aws-amplify

### ISSUE THREAD

**Issue by mlabieniec** [cdnjs/cdnjs#12677]
**Library name:** 
aws/aws-amplify

**Library description:** 
AWS Amplify provides a declarative and easy-to-use interface across different categories of cloud operations. 

**Git repository url:** 
https://github.com/aws/aws-amplify

Dist file/s for inclusion:
https://github.com/aws/aws-amplify/tree/master/packages/aws-amplify/dist

**npm package name or url** (if there is one): 
https://www.npmjs.com/package/aws-amplify

**License (List them all if it's multiple):** 
Apache-2

**Official homepage:** 
https://aws.github.io/aws-amplify

**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by tommedema** [comment]
This is high prio since Apr 2018 but there's been no movement

**Comment by tommedema** [comment]
@mlabieniec any update on this? will individual packages like Storage get their own standalone compiled versions too?
