### ISSUE TITLE
[Request] Add lottie-web

### ISSUE THREAD

**Issue by bodymovin** [cdnjs/cdnjs#12687]
Library name: lottie.js
Library description: A no depency JS library to render lottie.json files
Git repository url: https://github.com/airbnb/lottie-web
npm package name or url (if there is one): https://www.npmjs.com/package/lottie-web
License (List them all if it's multiple): MIT License
Official homepage: http://airbnb.io/lottie  

Wanna say something? This library replaces the bodymovin cdn files here:
https://cdnjs.com/libraries/bodymovin

**Comment by MattIPv4** [comment]
Available on cdnjs under the old package name: https://cdnjs.com/libraries/bodymovin

**Comment by ljharb** [comment]
@MattIPv4 the old package name is deprecated; this should be reopened, and it should be added under the new package name.

**Comment by MattIPv4** [comment]
We don't currently have any logic in place to redirect users etc. when names get changed. As this still has usage under the old name, I guess the best option would be to add it under the new name and have both auto-update.

**Comment by ljharb** [comment]
Right; it's not a redirection. A new name is a new package, and both packages should exist and match the published versions for them.

**Comment by MattIPv4** [comment]
`bodymovin` is also set to update from `lottie-web`, so these are identical.

**Comment by ljharb** [comment]
That just means two different packages are coincidentally identical :-)
