### ISSUE TITLE
[Request] Add basicScroll

### ISSUE THREAD

**Issue by MonsterDeveloper** [cdnjs/cdnjs#12685]
**Library name:** basicScroll
**Library description:** Standalone parallax scrolling for mobile and desktop with CSS variables.
**Git repository url:** https://github.com/electerious/basicScroll
**npm package name or url** (if there is one): https://www.npmjs.com/package/basicscroll
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://basicscroll.electerious.com
**Wanna say something? Leave message here:** Well, I am not owner of this library but I am using it so I want it to be accelerated via cdnjs.

**Comment by amdad** [comment]
+1
