### ISSUE TITLE
Add WebAssembly(wasm) file support

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#12681]
As far as I know, the server running by @Cloudflare is using a whitelist to control the file type could be served, currently, there is no WebAssembly(wasm) file in the repository, and #12534 would need that type of file to be served over CDN. @terinjokes would you please help us take a look? Many thanks.

cc @cdnjs/team-cdnjs

**Comment by MattIPv4** [comment]
Hi there, I have added this file extension request to #13145 where I am keeping track of them all.
