### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by redmusic27** [cdnjs/cdnjs#12689]
Hello sir, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution. In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think? best regards :)

**Comment by redmusic27** [comment]
Okay sir. I will start to make a logo for you. if it is ready I will be back.

**Comment by redmusic27** [comment]
Hello sir, I have created a 2 type concept logo for you. You can choose one between the two.
If you like it, I'll send you files and pr. 
Is there anything you want ?

Logomark
![cdnjs-mark](https://user-images.githubusercontent.com/37577374/38568561-26799a86-3d13-11e8-818b-dc5bffae0bd2.jpg)
Logotype
![cdnjs-type](https://user-images.githubusercontent.com/37577374/38568661-635ddd0e-3d13-11e8-85bc-94c86265ab93.jpg)

**Comment by PeterDaveHello** [comment]
Thanks @redmusic27 !
@thomasdavis @ryankirkman do you have any comments?

**Comment by redmusic27** [comment]
Left or Right?

**Comment by PeterDaveHello** [comment]
@redmusic27 let's wait for a few days to see if CDNJS creators would have opinion ;)

**Comment by redmusic27** [comment]
Okay Im understand sir

**Comment by PeterDaveHello** [comment]
@redmusic27 Don't need to call me sir, call me Peter would be fine 😊 BTW, I really appreciate your contribution and effort, thank you.

**Comment by MonsterDeveloper** [comment]
@redmusic27 Maybe try to use another font? cdnjs shows us free and open-source CDN. I think it's better to use fonts like Proxima Nova or some monospace. Here's my version with Proxima Nova Black and PT Mono Bold. 
![cdnjs](https://user-images.githubusercontent.com/16190582/38880367-333b911a-426e-11e8-999b-c8594470e532.jpg)

**Comment by PeterDaveHello** [comment]
@MonsterDeveloper thanks for the suggestion!
@redmusic27 what do you think? May I know what's the current font is? (Sorry that I'm new to font ;) )

**Comment by AmNotADev** [comment]
This issue was addressed by a few core members and a new logo was selected for review, which can be found at the [brand repository](https://github.com/cdnjs/brand).

Keep up the great work though!
