### ISSUE TITLE
[Request] Add line-awesome

### ISSUE THREAD

**Issue by thegreatrazz** [cdnjs/cdnjs#12698]
**Library name:** line-awesome
**Library description:** Replace Font Awesome with modern line icons with a single line of code.
**Git repository url:** https://github.com/icons8/line-awesome
**npm package name or url** (if there is one): https://www.npmjs.com/package/line-awesome
**License (List them all if it's multiple):** MIT or [Good Boy License](https://icons8.com/good-boy-license/)
**Official homepage:** https://icons8.com/line-awesome
**Wanna say something? Leave message here:** A more appealing replacement for Font Awesome 4. I think this project should be more visible (and accessible.)

**Comment by finch185277** [comment]
Hi, @thegreatrazz 
Thanks for the suggestion, however, this library doesn't have enough notable popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before opening an issue, I'll respectfully suggest you open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity, cc @PeterDaveHello
