### ISSUE TITLE
[Request] Add react-dates

### ISSUE THREAD

**Issue by arturom** [cdnjs/cdnjs#12693]
**Library name:** react-dates
**Library description:** An easily internationalizable, accessible, mobile-friendly datepicker library for the web. 
**Git repository url:** https://github.com/airbnb/react-dates/
**npm package name or url** (if there is one): https://npmjs.org/package/react-dates
**License (List them all if it's multiple):** MIT
**Official homepage:** http://airbnb.io/react-dates
**Wanna say something? Leave message here:**

**Comment by pferreir** [comment]
Seconded!
