### ISSUE TITLE
[Request] Add playground.js

### ISSUE THREAD

**Issue by greenmancode** [cdnjs/cdnjs#12695]
**Library name:** playground.js
**Library description:** Playground.js is a game oriented javascript framework that gives you access to essentials like mouse, keyboard, sound and well designed architecture. The rest is up to you. Whether you prefer to roll your own physics library or use Box2D - playground will not get in your way.
**Git repository url:** https://github.com/rezoner/playground  
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** The MIT License (MIT)
**Official homepage:** http://playgroundjs.com
**Wanna say something? Leave message here:**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
