### ISSUE TITLE
[Request] SignalR

### ISSUE THREAD

**Issue by mikaelm12** [cdnjs/cdnjs#12694]
**Git repository url:** https://github.com/aspnet/SignalR
**License(s):** https://github.com/aspnet/SignalR/blob/dev/LICENSE.txt

GitHub / Bitbucket popularity:
 - Count of watchers: 255
 - Count of stars: 1,644
 - Count of forks: 276

NPM download stats:
- Downloads in the last week: 2,499

**Comment by sufuf3** [comment]
Memo: Npm package - https://www.npmjs.com/package/@aspnet/signalr

**Comment by chrisdpratt** [comment]
Just pinging this issue because there hasn't been an update in almost a month. How is this progressing? Is there anything anyone can help with to move it along?

**Comment by mikaelm12** [comment]
We're going to re-evaluate this
