### ISSUE TITLE
[Request] Tabler UI Kit

### ISSUE THREAD

**Issue by codecalm** [cdnjs/cdnjs#12701]
**Library name:** tabler
**Library description:** Tabler is free and open-source HTML Dashboard UI Kit built on Bootstrap 4
**Git repository url:** https://github.com/tabler/tabler
**npm package name or url (if there is one):** https://www.npmjs.com/package/tabler-ui
**License (List them all if it's multiple):** MIT License
**Official homepage:** https://tabler.github.io/
**Wanna say something? Leave message here:** Hi! I am owner of this package. If I could help with something, please let me know

**Comment by PeterDaveHello** [comment]
@codecalm what are the files should be hosted?

**Comment by codecalm** [comment]
Hi @PeterDaveHello 
All `/dist` dir :)

**Comment by PeterDaveHello** [comment]
@codecalm we don't serve html files, and the users shouldn't directly use those html examples ... so, the files need to be specified.

**Comment by codecalm** [comment]
@PeterDaveHello okay, I'll change it as son as possible

**Comment by PeterDaveHello** [comment]
@codecalm thanks, you can also try to send a PR here ;)

**Comment by codecalm** [comment]
Hi! We rewrite Tabler. Now from `dist/` directory we serve only js and css files. Develop version is on `dev` branch, soon we will merge it to master.

**Comment by xtuc** [comment]
@codecalm can you send a PR to add it?

**Comment by MattIPv4** [comment]
`dist` contains almost only `html` files. cdnjs cannot host this. Closing.

**Comment by xtuc** [comment]
cdnjs can host html files but only distribute them as text

**Comment by MattIPv4** [comment]
@xtuc is that a recent change to the whitelist?
