### ISSUE TITLE
[Request] Add jquery.dynamiclist.min

### ISSUE THREAD

**Issue by victorgutierrez92** [cdnjs/cdnjs#12709]
**Library name:** jquery.dynamiclist.min
**Library description:** 
**Git repository url: https://github.com/ikelin/jquery.dynamiclist** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

http://ikelin.github.io/jquery.dynamiclist/js/jquery.dynamiclist.min.js
=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@victorgutierrez92 more details please

**Comment by extend1994** [comment]
Hi @victorgutierrez92 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-libraryhttps://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#b-request-a-new-library) for more details :smile: 

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity, cc @PeterDaveHello
