### ISSUE TITLE
[Request] [Author] Add Zora CSS Reset

### ISSUE THREAD

**Issue by IsibisiDev** [cdnjs/cdnjs#12711]
**Library name:** zora-reset.css
**Library description**: Zora Reset is a modern CSS Reset that fixes the most common bugs of various browsers. It is light and does not invade the development space.
**Git repository url**: https://github.com/IsibisiDev/zora-reset.css
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** GNU General Public License v3.0
**Official homepage:** https://github.com/IsibisiDev/zora-reset.css
**Wanna say something? Leave message here:** N/A

**Comment by extend1994** [comment]
Hi @IsibisiDev 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:
Nevertheless, you are welcome to send a pull request to add your library, we will assist you if you want!

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your contribution!

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity, cc @PeterDaveHello
