### ISSUE TITLE
fingerprintjs2 version update request

### ISSUE THREAD

**Issue by Enalmada** [cdnjs/cdnjs#12718]
https://cdnjs.com/libraries/fingerprintjs2 at 1.6.1

https://github.com/Valve/fingerprintjs2/releases at 1.8.0

Thanks for your time!

**Comment by PeterDaveHello** [comment]
@Enalmada thanks for reporting, I think they forgot to update their npm registry, maybe you can open an issue in the upstream repository to remind them. I'll transfer it to use git auto-update and manually fetch the missing versions from GitHub in the meantime.
