### ISSUE TITLE
[Request] Add Primeng Only theme

### ISSUE THREAD

**Issue by wszgrcy** [cdnjs/cdnjs#12724]
Library name: primeng theme
Library description: not whole only theme
Git repository url: https://github.com/primefaces/primeng/tree/master/src/assets/components/themes
npm package name or url (if there is one): none
License (List them all if it's multiple): MIT

**Comment by finch185277** [comment]
#10134 same?
Why only theme?

**Comment by wszgrcy** [comment]
@finch185277  angular2-6 buid need this(or import by local),primeng not primeui

**Comment by MattIPv4** [comment]
primeng (& its themes) available on cdnjs: https://cdnjs.com/libraries/primeng
