### ISSUE TITLE
[Request] Add multi-angular-polyfills

### ISSUE THREAD

**Issue by wszgrcy** [cdnjs/cdnjs#12723]
Library description: the following js are all for polyfills
Library name: Blob.js
Git repository url: https://github.com/eligrey/Blob.js
npm package name or url (if there is one): none
License (List them all if it's multiple): MIT

Library name: Intl.js
Git repository url: https://github.com/andyearnshaw/Intl.js
npm package name or url (if there is one): none
License (List them all if it's multiple): MIT / Unicode license

Library name: typedarray.js
Git repository url: https://github.com/inexorabletash/polyfill/blob/master/typedarray.js
npm package name or url (if there is one): none
License (List them all if it's multiple): MIT 

Library name: html5-formdata
Git repository url: https://github.com/francois2metz/html5-formdata
npm package name or url (if there is one): none
License (List them all if it's multiple): MIT

**Comment by MattIPv4** [comment]
Blob.js doesn't meet auto-update requirements.
js-polyfills is already available: https://cdnjs.com/libraries/js-polyfills
html5-formdata doesn't meet auto-update requirements.
