### ISSUE TITLE
[Request] Add timeonsitetracker.min.js

### ISSUE THREAD

**Issue by saleemkce** [cdnjs/cdnjs#12739]
**Library name:**  timeonsitetracker.min.js
**Library description:** TimeOnSiteTracker.js - Measure your user's Time on site accurately
**Git repository url:** https://github.com/saleemkce/timeonsite
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** [https://saleemkce.github.io/timeonsite/](https://saleemkce.github.io/timeonsite/)
**Wanna say something? Leave message here:**

**Comment by saleemkce** [comment]
@ryankirkman Thanks for this awesome CDN service. We really love it; it's fast and reliable :)

**Comment by extend1994** [comment]
Hi @

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our [issue rule](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library) for more details :smile:

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by extend1994** [comment]
Close due to no response & insufficient popularity, cc @PeterDaveHello
