### ISSUE TITLE
[Request] Add react-helmet

### ISSUE THREAD

**Issue by cyfos** [cdnjs/cdnjs#12734]
**Library name:** react-helmet
**Library description:** This reusable React component will manage all of your changes to the document head.
**Git repository url:** https://github.com/nfl/react-helmet/tree/c102586229549650ddb0f9615a42d351a2c7241b
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-helmet
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** This is the information I've collected.This package is excellent, but it can't be found at cdnjs.com.

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@cyfos any details?

**Comment by cyfos** [comment]
https://www.npmjs.com/search?q=react-helmet

**Comment by PeterDaveHello** [comment]
@cyfos use our issue template please

**Comment by cyfos** [comment]
OK.This package is excellent, but it can't be found at cdnjs.com

**Comment by cyfos** [comment]
This issue has been updated

**Comment by extend1994** [comment]
@PeterDaveHello This has no UMD standalone js yet, should we leave it open?
Ref: https://github.com/nfl/react-helmet/issues/327

**Comment by sashberd** [comment]
@extend1994 @PeterDaveHello  This is [duplicate](https://github.com/cdnjs/cdnjs/issues/6962)

**Comment by extend1994** [comment]
Thanks @sashberd Move to #6962
