### ISSUE TITLE
[Request] Add github-buttons

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#12743]
**Library name:** github-buttons
**Library description:** :octocat: Unofficial github:buttons.
**Git repository url:** https://github.com/ntkme/github-buttons
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** [BSD 2-Clause "Simplified" License](https://github.com/ntkme/github-buttons/blob/master/LICENSE.md)
**Official homepage:** https://buttons.github.io/
**Wanna say something? Leave message here:**

**Comment by richa031** [comment]
please tell me what things need to be done
