### ISSUE TITLE
[Request] Add sql-formater

### ISSUE THREAD

**Issue by ambischof** [cdnjs/cdnjs#12740]
**Library name:** sql-formatter
**Library description:** 
> SQL Formatter is a JavaScript library for pretty-printing SQL queries. It started as a port of a PHP Library, but has since considerably diverged. It supports Standard SQL, Couchbase N1QL, IBM DB2 and Oracle PL/SQL dialects.

**Git repository url:** https://github.com/zeroturnaround/sql-formatter
**npm package name or url** https://www.npmjs.com/package/sql-formatter
**License (List them all if it's multiple):** MIT
**Official homepage:** https://zeroturnaround.github.io/sql-formatter/

NPM weekly downloads as of this issue posting: 1,991

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/sql-formatter
