### ISSUE TITLE
[Request] Add videojs-vimeo

### ISSUE THREAD

**Issue by timluigjes** [cdnjs/cdnjs#12758]
**Library name:** videojs-vimeo
**Library description:** Videojs Vimeo plugin using the official Vimeo Player API. This is heavily inspired by the official VideoJS YouTube project.
**Git repository url:** https://github.com/videojs/videojs-vimeo
**npm package name or url** (if there is one): https://www.npmjs.com/package/videojs-vimeo
**License (List them all if it's multiple):**  MIT

**Comment by extend1994** [comment]
Duplicated with #9524 & move to it.
Thanks for the request.
