### ISSUE TITLE
[Request] Add skeuocard

### ISSUE THREAD

**Issue by anoorally** [cdnjs/cdnjs#12757]
**Library name:** skeuocard
**Library description:** Skeuocard is a re-think of the way we handle credit card input on the web. It progressively enhances credit card input forms so that the card inputs become skeuomorphic, facilitating accurate and fast card entry, and removing barriers to purchase.
**Git repository url:** https://github.com/kenkeiter/skeuocard
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** Skeuocard is licensed under the MIT license
**Official homepage:** http://kenkeiter.com/skeuocard/
**Wanna say something? Leave message here:** It has 3300 stars and I could not find this js hosted anywhere else. It would be appreciated if you could host its JS and CSS :)

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
