### ISSUE TITLE
[Request] Add https://cdn.ckeditor.com/ckeditor5/10.0.0/classic/ckeditor.js

### ISSUE THREAD

**Issue by hzpemu** [cdnjs/cdnjs#12751]
**Library name:** https://cdn.ckeditor.com/ckeditor5/10.0.0/classic/ckeditor.js
**Library description:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@hzpemu I think this one already [exists](https://cdnjs.com/libraries/ckeditor). Am I right?

**Comment by hzpemu** [comment]
just the ver4.9.2 exists,but no ver5 v10  exists.

**Comment by hzpemu** [comment]
the last ver is https://cdn.ckeditor.com/ckeditor5/10.0.1/classic/ckeditor.js

**Comment by sashberd** [comment]
@hzpemu If it is not posted on git repo or on npm, we have nothing to do in order to host it

**Comment by hzpemu** [comment]
your mean you need this ?
https://github.com/ckeditor/ckeditor5-build-classic/blob/master/build/ckeditor.js
https://github.com/ckeditor/ckeditor5-build-classic

**Comment by hzpemu** [comment]
npm install --save @ckeditor/ckeditor5-build-classic

**Comment by sashberd** [comment]
OK
1) This is defferent git from I provided, So I think it is not duplicate. @extend1994 @PeterDaveHello  FYR
2) There is no git tag 0f v5.* in you git repo, same on npm ([see here](https://libraries.io/npm/@ckeditor%2Fckeditor5-build-classic)). Thus, we can host only v10.* via new library request

@extend1994 @PeterDaveHello @sufuf3 should we create new folder with different auto update config for this new version of ckeditor or just update existed one?

**Comment by sashberd** [comment]
@PeterDaveHello FYR

**Comment by xtuc** [comment]
This would be a new package, we don't want to update existing files on the cdn because of breaking changes
