### ISSUE TITLE
[Request] Add berkan52/select2-bootstrap4-theme

### ISSUE THREAD

**Issue by julionc** [cdnjs/cdnjs#12774]
**Library name:** berkan52/select2-bootstrap4-theme
**Library description:** A theme for Select2 v4 and Bootstrap 4
**Git repository url:** https://github.com/berkan52/select2-bootstrap4-theme
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://github.com/berkan52/select2-bootstrap4-theme
**Wanna say something? Leave message here:**

**Comment by julionc** [comment]
cc @berkan52

**Comment by sashberd** [comment]
Hi @julionc 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
