### ISSUE TITLE
[Request] Add nimnjs

### ISSUE THREAD

**Issue by amitguptagwl** [cdnjs/cdnjs#12776]
Library name: nimnjs-node
Library description: JS implementation of [nimn](https://nimndata.github.io/nimnjs-node/) data format. 60% or more compressed than JSON. 40% or more compressed than msgpack
Git repository url: https://github.com/nimndata/nimnjs-node
npm package name or url: https://www.npmjs.com/package/nimnjs
License (List them all if it's multiple): MIT
Library Path: https://github.com/nimndata/nimnjs-node/blob/master/dist/nimn.js

**Comment by amitguptagwl** [comment]
@finch185277 Thanks to tag it "High Priority". I hope it'll be added soon. Please let me know if I need to do any change from my side.

**Comment by PeterDaveHello** [comment]
@amitguptagwl pull requests are welcome 😎

**Comment by amitguptagwl** [comment]
Sure, let me check how to do the change in this repo.

**Comment by finch185277** [comment]
Hi @amitguptagwl ,

The git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) relies on [git tags](https://github.com/nimndata/nimnjs/tags) so that it can recognize the correct version and 
automatically update the repo.
Could you please add git tags for the repo?

If you have any suggestions, please let me know.
Thank you.

**Comment by amitguptagwl** [comment]
For my another library 'fast-xml-parser', I don't add git tags. Are you sure I need to add them. As the repo is npm project, I believe git automatically maintains that.

**Comment by amitguptagwl** [comment]
@finch185277 Can you please update about git tags confusion for npm repos on github?

**Comment by amitguptagwl** [comment]
😊 I'm aware with git tagging and use it in my other projects.

**Comment by amitguptagwl** [comment]
@finch185277 I hope CDNJS would be using npm update to add this library. If I need any other update in my repo, please let me know.
