### ISSUE TITLE
[Request] Add digital-keyboard

### ISSUE THREAD

**Issue by simbawus** [cdnjs/cdnjs#12777]
**Library name:** digital-keyboard
**Library description:** Digital Keyboard 数字键盘
**Git repository url:** https://github.com/simbawus/DigitalKeyboard
**npm package name or url** (if there is one): digital-keyboard
**License (List them all if it's multiple):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:** Welcome Star

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the [README.md](https://github.com/cdnjs/cdnjs#cdnjs-library-repository) and [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
This library is not answer minimum CDNJS popularity

**Comment by simbawus** [comment]
Hello, my library has 202stars at now, can i apply for a cndjs ?

**Comment by PeterDaveHello** [comment]
@simbawus send a pull request please

**Comment by simbawus** [comment]
@PeterDaveHello ok, thanks!
