### ISSUE TITLE
[Request] Add luxon

### ISSUE THREAD

**Issue by jdfarber** [cdnjs/cdnjs#12778]
**Library name:** luxon
**Library description:** successor to Moment.js
**Git repository url:** https://github.com/moment/luxon
**npm package name or url** (if there is one): https://www.npmjs.com/package/luxon
**License (List them all if it's multiple):** MIT
**Official homepage:** https://moment.github.io/luxon/index.html
**Wanna say something? Leave message here:** Thanks so much for this service!

**Comment by sashberd** [comment]
Duplicate #12220 Move there
