### ISSUE TITLE
Entypo is Corrupted

### ISSUE THREAD

**Issue by DerekTBrown** [cdnjs/cdnjs#12772]
Try downloading the `.ttf` files for example.  The fonts are corrupted:

https://cdnjs.com/libraries/entypo

**Comment by PeterDaveHello** [comment]
@DerekTBrown how to verify if it's correct or not?

**Comment by DerekTBrown** [comment]
Simply download the `.ttf` file from the website and try to open in your operating system (or browser's) font browser.

**Comment by PeterDaveHello** [comment]
It was added here more than 4 years ago:
https://github.com/cdnjs/cdnjs/pull/3255

Though I can see that the file can't be opened properly, however, there is no any other report during these years, the maintenance of the [repository](https://github.com/danielbruce/entypo) seems to be stopped, there is even no clear versioning in this library, this would be hard to deal with ...

**Comment by MattIPv4** [comment]
@PeterDaveHello Looking into this, the current font files on the "source" repo appear to be working fine when downloaded, yet the versions we have are definitely broken?

https://github.com/danielbruce/entypo/tree/master/font
vs https://github.com/juliusrickert/cdnjs/tree/master/ajax/libs/entypo/2.0

**Comment by xtuc** [comment]
We won't change the file in the version 2.0. Since the lib isn't auto updating, please send a PR to enable it. See contributing.md files in the repo
