### ISSUE TITLE
[Request] Add fullcalendar's gcal.js

### ISSUE THREAD

**Issue by smileytechguy** [cdnjs/cdnjs#12788]
**Library name:** fullcalendar-gcal.js (?)
**Library description:** A sub-module of full calendar which provides google calendar support
**Git repository url:** https://fullcalendar.io/docs/google-calendar
**npm package name or url** (if there is one): -
**License (List them all if it's multiple):** MIT
**Official homepage:** https://fullcalendar.io/
**Wanna say something? Leave message here:**

**Comment by sashberd** [comment]
@smileytechguy According to provided url the [repo of lib](https://github.com/fullcalendar
) is already hosted on cdnjs (see [here](https://cdnjs.com/libraries/fullcalendar) and [here](https://cdnjs.com/libraries/fullcalendar-scheduler))
Moreover, the file you are looking for is existed in hosted lib (see [here](https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/gcal.js))

So what is the purpose of this issue?

**Comment by smileytechguy** [comment]
Whoops, my bad, forgot that a library had more than the main one.
