### ISSUE TITLE
[Request] Add ccxt 

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12787]
**Library name:** ccxt
**Git repository url:** https://github.com/ccxt/ccxt
**npm package name or url** (if there is one): https://npmjs.com/package/ccxt
**License (List them all if it's multiple):** [MIT](https://github.com/ccxt/ccxt/blob/master/LICENSE.txt)

6,631 stars on 2018/05/23.
28,703 downloads on npm in last month.

**Comment by xtuc** [comment]
PR has been closed
