### ISSUE TITLE
Adding npm and cdn for the project

### ISSUE THREAD

**Issue by madeas** [cdnjs/cdnjs#12799]
Hello.
I need your help. I created a small project https://github.com/madeas/box-shadows.css/blob/1.0.2/box-shadows.min.css and I want to connect it to npm, and then to cdnjs if the project is in demand. But I do not know how. Can someone help or connect the project  to npm/cdnjs and explain how to use it?

**Comment by maksrise** [comment]
To contribute to CDNJS, please refer to [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md).

**Comment by madeas** [comment]
I have read, but I have a problem with js, including with node.js. I do not know them

**Comment by maksrise** [comment]
[b. request a new library](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library): The new library must have at least 200 stars on GitHub or 800 downloads/month on npm registry, one officially public accessible repository and open source license.

**Comment by sashberd** [comment]
Hi @madeas

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
