### ISSUE TITLE
Genericons - genericons.min.css - missing quote makes whole file invalid

### ISSUE THREAD

**Issue by rinart73** [cdnjs/cdnjs#12791]
https://cdnjs.cloudflare.com/ajax/libs/genericons/3.1/genericons.min.css
Take a look at `url(Genericons.woff') format("woff")`. There should be a single quote after `url(`.
This error makes the whole file invalid and negates the sense of using genericons from cdnjs. And using non-minified version is not a solution.

**Comment by sashberd** [comment]
@rinart73 I think this issue should be opened in library issues tab. We just host existed files and we can not change their content
