### ISSUE TITLE
Add htmlson.js

### ISSUE THREAD

**Issue by adalenv** [cdnjs/cdnjs#12798]
Library name: htmlson.js
Git repository url: https://github.com/adalenv/htmlson.js
npm package name or url (if there is one): https://www.npmjs.com/package/htmlson.js
License (List them all if it's multiple): MIT

**Comment by sashberd** [comment]
Hi @adalenv

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by adalenv** [comment]
its ok , thank you anyway 😄
