### ISSUE TITLE
[Request] Add Simple-Grid

### ISSUE THREAD

**Issue by alegorico** [cdnjs/cdnjs#12796]
**Library name:** Simple-Grid
**Git repository url:** https://github.com/zachacole/Simple-Grid
**npm package name or url (if there is one):**   
**License (List them all if it's multiple):** MIT
**Wanna say something? Leave message here:**

issue update:
this lib waiting for some improvements found in other fork
e.g. https://github.com/alegorico/my-simplegrid.git

**Comment by sashberd** [comment]
The [lib](https://github.com/zachacole/Simple-Grid) itself is answer to the minimum popularity cdnjs restrictions, but your issue fork is not. So you can ask to add original, lib or just close this issue

**Comment by alegorico** [comment]
oh right, the fork is an feature improvement, (compiler, bower register, and not much more). 
the lib should be the priority in this case.

**Comment by sashberd** [comment]
Please update info of the issue. Thanks

**Comment by xtuc** [comment]
You can submit  https://github.com/zachacole/Simple-Grid on cdnjs.com. Your fork doesn't meet the popularity requirements

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
