### ISSUE TITLE
Update simple-jekyll-search 

### ISSUE THREAD

**Issue by MoritzBru** [cdnjs/cdnjs#12803]
`simple-jekyll-search` is stuck on version **1.1.8** (https://cdnjs.com/libraries/simple-jekyll-search) from like a year ago.
The current version is **1.7.0** (https://github.com/christian-fei/Simple-Jekyll-Search/releases)

**Comment by LuckyPigeon** [comment]
Does this lib needs to add all of versions or just need to update the latest one?
