### ISSUE TITLE
Add lazyframe

### ISSUE THREAD

**Issue by theel0ja** [cdnjs/cdnjs#12814]
**Library name:** lazyframe
**Library description:** 🛀🏽 Dependency-free library for lazyloading iframes
**Git repository url**: https://github.com/vb/lazyframe
**npm package name or url** (if there is one): https://www.npmjs.com/package/lazyframe
**License (List them all if it's multiple):** [MIT](https://github.com/vb/lazyframe/blob/master/package.json#L24)
**Official homepage:** https://vb.github.io/lazyframe/
**Wanna say something? Leave message here:** I liked the old issue template, but it's now gone (you have to search it from old repos)

**Comment by sashberd** [comment]
Hi @theel0ja 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by oamits** [comment]
+1 to add this.
"If you add it, they will come..."
:smile:
