### ISSUE TITLE
[author][Request] Add datalist-polyfill

### ISSUE THREAD

**Issue by mfranzke** [cdnjs/cdnjs#12813]
**Library name:** datalist-polyfill
**Git repository url:** https://github.com/mfranzke/datalist-polyfill/
**npm package name or url (if there is one):** https://www.npmjs.com/package/datalist-polyfill
**License (List them all if it's multiple):** MIT
**Wanna say something? Leave message here:**
The downloads currently vary a little bit - yarn reported 11k the latest, whereas they are currently down to 6k: https://yarnpkg.com/en/package/datalist-polyfill

**Comment by PeterDaveHello** [comment]
@mfranzke Send a pull request, please.
