### ISSUE TITLE
[Request] modal-video

### ISSUE THREAD

**Issue by andremacola** [cdnjs/cdnjs#12812]
**Library name:** modal-video
**Git repository url:** https://github.com/appleple/modal-video
**npm package name or url:** https://www.npmjs.com/package/modal-video
**License:** MIT

**Comment by sashberd** [comment]
Hi @andremacola 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by andremacola** [comment]
@sashberd oh, I'm sorry for the inconvenience. I did not read the rules.
