### ISSUE TITLE
Highcharts version auto-update check

### ISSUE THREAD

**Issue by lizheming** [cdnjs/cdnjs#12824]
Hello, Highcharts' latest version in [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/highcharts) is 6.0.7, while it has been updated to 6.1.0 at  [April 13](https://github.com/highcharts/highcharts-dist/releases/tag/v6.1.0). Maybe we should check auto-update is available yet?

**Comment by sashberd** [comment]
@PeterDaveHello @extend1994 @sufuf3 
I think the autoupodate target was changed from  

> git://github.com/highslide-software/highcharts-release.git

to 

> git@github.com:highcharts/highcharts-dist.git

Am I right?

**Comment by sashberd** [comment]
@PeterDaveHello @extend1994 @sufuf3 ping

**Comment by sashberd** [comment]
@PeterDaveHello @extend1994 @sufuf3 ping

**Comment by extend1994** [comment]
@sashberd `git://github.com/highcharts/highcharts-dist.git`
But the reason that the bot didn't add them should be the file structure change.
http://github.com/highslide-software/highcharts-release always redirect to https://github.com/highcharts/highcharts-dist

**Comment by sashberd** [comment]
@extend1994 I did not get what do you mean? Should we change autoupdate target to  git@github.com:highcharts/highcharts-dist.git?

**Comment by extend1994** [comment]
Updating is good, but not sure it will help add latter versions.

**Comment by sashberd** [comment]
If there will still a problem with later/new versions we will get an alert like we got it from @lizheming ?
I will send a PR with update ASAP
