### ISSUE TITLE
[author]update Day.js npm auto-update 

### ISSUE THREAD

**Issue by iamkun** [cdnjs/cdnjs#12828]
Hi,

https://cdnjs.com/libraries/dayjs

From dayjs@1.6.0, we changed the structure of our project.

We moved `dayjs.min.js` from `/dist/dayjs.min.js` to `/dayjs.min.js`.

Would you please update the npm auto-update script so that the version on CDNJS won't freeze on 1.5.x.

Seems all we have to do is update this file?

```
  "npmFileMap": [
    {
      "basePath": "/",
      "files": [
        "**/*"
      ]
    }
 ]
```

**Comment by sashberd** [comment]
@iamkun Can you send PR with change above?

**Comment by iamkun** [comment]
Sure. Just not sure how to set `basePath` properly.

If I just set `basePath: /`,  it doesn't matching in all versions (not ok with version 1.5.x in `/dist`).

**Comment by PeterDaveHello** [comment]
@iamkun if you wanna use repo root as the base path, set basePath to empty string

**Comment by iamkun** [comment]
Ok THX

**Comment by iamkun** [comment]
@PeterDaveHello @sashberd 

PR #12829 here, would you please give it a review. Cheers.
