### ISSUE TITLE
[Request] Add filepond

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12837]
**Library name:** filepond
**Git repository url:** https://github.com/pqina/filepond
**npm package name or url** (if there is one): https://www.npmjs.com/package/filepond
**License (List them all if it's multiple):** [MIT](https://github.com/pqina/filepond/blob/master/LICENSE)
**Homepage**: https://pqina.nl/filepond

3,584 stars on 2018/06/17.
It's recommended to use npm auto-update to fetch all versions.

**Comment by TauseefMalik** [comment]
I will work on it (first contribution to open-source)

**Comment by PeterDaveHello** [comment]
@TauseefMalik what kind of help do you need?

**Comment by TauseefMalik** [comment]
I do know how add repo information in json file but I am kinda confused setting up the copy on my machine. I am not aware of sparsed checkouts etc. If you could list down the things to get a working local copy, it would be of great help. PS- I read contributing.md but is there a simpler quick way to get started

**Comment by extend1994** [comment]
@TauseefMalik Sorry for late reply
If you want to set the environment, you can follow the commands in https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md.
When the env is done, you may refer the "https://github.com/cdnjs/cdnjs/issues/12821" and "work locally" part of https://github.com/cdnjs/cdnjs/issues/12821.
Hope this helps.
