### ISSUE TITLE
[Request] Add spritejs

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12844]
**Library name:** spritejs
**Git repository url:** https://github.com/spritejs/spritejs
**npm package name or url** (if there is one): https://www.npmjs.org/package/spritejs
**License (List them all if it's multiple):** [MIT](https://github.com/spritejs/spritejs/blob/master/LICENSE)
**Homepage**: http://spritejs.org/

1,425 stars on 2018/06/25 -> 2,119 on 2018/07/26
It's recommended to use npm auto-update to fetch more versions with dist files.
v1.10.0, v1.7.0, which have dist files, are only on Git repo. Will need to manually add them.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/spritejs
