### ISSUE TITLE
qunit no longer updating

### ISSUE THREAD

**Issue by thezoggy** [cdnjs/cdnjs#12849]
cdnjs last qunit vesion is 2.4.1 which is when the npm package was renamed.
latest is 2.6.1

http://qunitjs.com/
> Prior to version 2.4.1, QUnit was published under the name qunitjs on NPM. If you wish to install an older version of QUnit on Node, you will want to use the qunitjs package. The qunit package prior to 2.4.1 is an alternative CLI that is now published as node-qunit.

looks like package.json just needs to be updated that the npmName should be `qunit` instead of `qunitjs`
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/qunit/package.json#L22

also source is in /src/*

**Comment by PeterDaveHello** [comment]
@thezoggy Pull requests are welcome.

**Comment by thezoggy** [comment]
I had bad experience with the last pull request with cdnjs... figured this time I'd leave it to the pros.
