### ISSUE TITLE
[Update] FontAwesome to 5.1

### ISSUE THREAD

**Issue by shinoamakusa** [cdnjs/cdnjs#12843]
Is it possible to update FontAwesone to latest version 5.1?
https://github.com/FortAwesome/Font-Awesome/releases

**Comment by sashberd** [comment]
I think this one is [here](https://github.com/cdnjs/cdnjs/pull/12517/commits) already in work
@extend1994 @PeterDaveHello Can you review PR above. Thanks

**Comment by th0mk** [comment]
Fontawesome 5.3.1 has been released, any chance you could update to that? Or do I have to make a seperate issue for that?

It would be great if the package could be updated to something >5.0

**Comment by biehlermi** [comment]
I need the new version too...  Please update it soon!

**Comment by sufuf3** [comment]
Sorry. I will do the PR these two days
CC ##12307

**Comment by sufuf3** [comment]
I updated the PR  #12517, let's wait for reviewing.
Thanks

**Comment by MattIPv4** [comment]
Resolved in #12517 - FontAwesome 5 is now live on cdnjs. 🎉
