### ISSUE TITLE
[Request] Add transformation-matrix-js auto-update

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12848]
**Library name:** transformation-matrix-js
**Git repository url:** https://gitlab.com/epistemex/transformation-matrix-js.git
**npm package name or url** (if there is one): transformation-matrix-js
**License (List them all if it's multiple):** MIT

Its repository came alive after https://github.com/cdnjs/cdnjs/commit/14a55df, so we need to re-add auto-update for it.

**Comment by MattIPv4** [comment]
https://gitlab.com/epistemex/transformation-matrix-js is now a 404, closing.
