### ISSUE TITLE
[Author][Request] Add Box-shadows.css

### ISSUE THREAD

**Issue by madeas** [cdnjs/cdnjs#12855]
https://github.com/madeas/box-shadows.css/blob/1.0.4/box-shadows.min.css

Library name: Box-shadows.css
Version: 1.0.4
Git repository: https://github.com/madeas/box-shadows.css
Licence: [MIT](https://github.com/madeas/box-shadows.css/blob/master/LICENSE) 
Official homepage: https://madeas.github.io/box-shadows

225 stars on 01/07/2018

**Comment by PerrySetGo** [comment]
I will take this issue.
