### ISSUE TITLE
jointjs.css 2.1.2 unknown property

### ISSUE THREAD

**Issue by juangascon** [cdnjs/cdnjs#12850]
Hello.
I do not know if this is to be reported here.
I would have proposed a correction by myself with a pull request but I do not find in the repository the .js or the .css in the subject. I wanted to clone the repo and I could not because it fulfilled my hard disk before ending (more than 64GB)
When I use in my webpage the last version (2.1.2) of jointjs.min.js and jointjs.min.css from the CDN (
https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.1.2/joint.min.css
and
https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.1.2/joint.min.js)
I get in the web developers tool of Firefox these messages:
Unknown property ‘user-select’.  Declaration dropped. joint.min.css:8:76
Unknown property ‘user-drag’.  Declaration dropped. joint.min.css:8:402
Error in parsing value for ‘cursor’.  Declaration dropped. joint.min.css:8:653

Though, when I use the same files from the jointjs webpage (
https://raw.githubusercontent.com/clientIO/joint/master/dist/joint.min.css
and
https://raw.githubusercontent.com/clientIO/joint/master/dist/joint.min.js )
there is no warnings.

Best regards.

**Comment by juangascon** [comment]
I have continued to look and this happens also with the saved .css and .js in my PC downloaded from the official webpage. It is quite strange.

**Comment by xtuc** [comment]
Not caused by cdnjs.com, please reach out to the author of the package
