### ISSUE TITLE
Default version on dropdown box is not the latest?

### ISSUE THREAD

**Issue by alvarotrigo** [cdnjs/cdnjs#12865]
When accessing https://cdnjs.com/libraries/fullPage.js in order to get the link for the CDN, the default selected version is 2.9.7 instead of the latest 3.0.1. 

Why is that? 

Some people seem to be using 2.9.7 when intending to use the latest.

**Comment by PeterDaveHello** [comment]
@alvarotrigo thanks for report.

**Comment by alvarotrigo** [comment]
May I ask, what was the issue?
Is it something I could control on my side?

**Comment by PeterDaveHello** [comment]
@alvarotrigo just forgot to update the version when manually add a new version when structure changed.
