### ISSUE TITLE
[Request] Add loading-bar

### ISSUE THREAD

**Issue by diegoaa** [cdnjs/cdnjs#12873]
**Library name:** loading-bar
**Repository url:** https://github.com/loadingio/loading-bar/
**npm package url:** https://www.npmjs.com/package/@loadingio/loading-bar
**License:** MIT
**Official homepage:** https://loading.io/progress/
1002 weekly downloads

**Comment by sashberd** [comment]
Hi @diegoaa 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
