### ISSUE TITLE
[Request] Update Framework7

### ISSUE THREAD

**Issue by nolimits4web** [cdnjs/cdnjs#12877]
Framework7 us already v3.0.0 https://github.com/framework7io/framework7
cdnjs version is still 2.3.1

Also home page is changed a while ago:
http://idangero.us/framework7 -> http://framework7.io

Repository is changed too: 
https://github.com/nolimits4web/Framework7.git -> https://github.com/framework7io/framework7

Also would be good to have `framework7-vue` and `framework7-react` packages in addition as they sit in same repo

**Comment by sashberd** [comment]
@nolimits4web I got your answer, as for vue and react please open separate issue for each one of the libs and provide your answer to my [question](https://github.com/cdnjs/cdnjs/pull/12878) as reference
Thanks
