### ISSUE TITLE
[Request] Update simple-icons [author]

### ISSUE THREAD

**Issue by birjolaxew** [cdnjs/cdnjs#12885]
`simple-icons` changed hands (and git repo) a while ago. It further seems like the CDNJS version claims to be at `3.0.1`, a version that [never existed](https://github.com/simple-icons/simple-icons/commits/develop/package.json) - the currently newest version is `1.6.7`. This is likely why the git autoupdating fails.

**Git repo changed:**  
`https://github.com/danleech/simple-icons.git` -> `https://github.com/simple-icons/simple-icons.git`

**Version should be fixed:**
`3.0.1` -> `1.6.7`

**Source issue:**
simple-icons/simple-icons#891

The homepage remains the same.

**Comment by PeterDaveHello** [comment]
@birjolaxew would you like to send a pull request to reflect that change? 😄

**Comment by birjolaxew** [comment]
@PeterDaveHello Currently pulling the repo with "Receiving objects" at 10% - has been going for an hour or so. I *think* I might've done something wrong despite following the [sparseCheckout guide](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md) :stuck_out_tongue:

**Comment by PeterDaveHello** [comment]
@birjolaxew maybe just edit it on GitHub web gui? so you dont need to clone it
