### ISSUE TITLE
[Request] Add iris-ws.js

### ISSUE THREAD

**Issue by dibyendu** [cdnjs/cdnjs#12884]
Library name: Iris Websocket Client Library
Git repository url: https://github.com/kataras/iris
Javascripy Library url: https://github.com/kataras/iris/tree/master/websocket
Unminified Typescript file: https://github.com/kataras/iris/blob/master/websocket/client.ts
Unminified Javascript file: https://github.com/kataras/iris/blob/master/websocket/client.go
License: https://github.com/kataras/iris/blob/master/websocket/LICENSE (BSD 3-Clause "New" or "Revised" License)

11,017 stars on 2018/07/21

**Comment by sashberd** [comment]
@dibyendu Could you say, which files should be hosted?

**Comment by dibyendu** [comment]
This is a bit tricky, as the Javascript is embedded in a `.go` file (`client.go`) and they serve it  from within the go file itself (on an endpoint called `/iris-ws.js`).

This snippet is taken from a working code:

```go
import (
    "github.com/kataras/iris"
    "github.com/kataras/iris/websocket"
)

func main() {
app := iris.New()
// serve the javascript built'n client-side library,
// see websockets.html script tags, this path is used.
app.Any("/iris-ws.js", func(ctx iris.Context) {
    ctx.Write(websocket.ClientSource) // this can be found in https://github.com/kataras/iris/blob/master/websocket/client.go
})
```

The actual `Typescript` is here: https://github.com/kataras/iris/blob/master/websocket/client.ts and the Javascript is embedded within this file: https://github.com/kataras/iris/blob/c0a1740de7561bc63c390d36145ed4b1ac0b64f9/websocket/client.go#L24

The `client.ts` can be converted to `iris-ws.js` as follows:
```bash
npm install -g typescript
tsc client.ts 
```
I've converted using the online service here: https://goo.gl/vUsU8H

I would request you to add both the `client.ts` and the compiled `iris-ws.js` to the CDN.

**Comment by sashberd** [comment]
@dibyendu CDNJS is not hosting .go and .ts files as I remember

@PeterDaveHello @extend1994 @sufuf3  FYR

**Comment by PeterDaveHello** [comment]
@sashberd yeah, we don't host that kinds of files.

**Comment by dibyendu** [comment]
Yes, i understand. But is it possible to host the compiled `.ts` file (which is a `.js)` file on CDNJS ?

**Comment by PeterDaveHello** [comment]
@dibyendu only @ryankirkman & @terinjokes can answer that, I have no control on the origin server which is owned by Cloudflare.

**Comment by dibyendu** [comment]
Hi, @PeterDaveHello & @sashberd as you can see that I've asked the developer of *Iris* to add the `javascript` file to the repository and that it has now been added under the path: https://github.com/kataras/iris/blob/master/websocket/client.js, does it make this easier for you to add the `client.js` (and probably the `client.min.js`) file to the cdn ?

**Comment by sashberd** [comment]
@dibyendu If the files answer cdnjs policies there is no problem to host them

**Comment by sashberd** [comment]
@dibyendu I see the `client.js` in master, but I do not see it in any git tag versions. Is the new PR will exists in the future releases of this lib? If it is you are welcome to send PR for this lib.
Thanks

**Comment by dibyendu** [comment]
@sashberd the `client.js` is recently added to the repository for a request based on this issue. That  file will continue to exist on all the future releases and tags.
