### ISSUE TITLE
Compute hases of all the libraries (old and new)

### ISSUE THREAD

**Issue by Rafiot** [cdnjs/cdnjs#12881]
Hi all,

I'm looking for a way to generate a database of known javascript libraries, in order to mark them as sane. cdnjs seems to be the obvious starting point as you basically have them all.

I didn't find an obvious way to get all the links for a specific library (not only the latest one) at once using the API, am I missing something?

I could obviously rebuild the URLs, but I'm wondering if there is a lazier approach.

Thank you very much

**Comment by Rafiot** [comment]
Or RTFM -> https://github.com/cdnjs/cdnjs/wiki/Extensions%2C-Plugins%2C-Resources :)

**Comment by PeterDaveHello** [comment]
@Rafiot I suggest you to directly clone the whole repository to your local storage so you can compute their hashes very quickly.

**Comment by Rafiot** [comment]
Oh. I didn't realize the directory contained everything...

**Comment by PeterDaveHello** [comment]
@Rafiot see ajax/libs
