### ISSUE TITLE
angular-ui-select library returns wrong version

### ISSUE THREAD

**Issue by josemv92** [cdnjs/cdnjs#12898]
Some versions of the angular-ui-select library have the files for a different one:

0.19.8 shows 0.19.7 (for example: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angular-ui-select/0.19.8/select.min.js )
0.20.0 shows 0.19.3 (for example: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angular-ui-select/0.20.0/select.min.js ) (looks like 0.20.0 doesn't even exists in the repo https://github.com/angular-ui/ui-select ).

**Comment by sashberd** [comment]
@josemv92 The problem is in origin files that are hosted on Git repo [see here ](https://github.com/angular-ui/ui-select/blob/32829a39e8efe7f94de049c6b529c23fedfc6686/dist/select.css#L4)
Open an issue in angular-ui-select repo and wait for authors answer

**Comment by josemv92** [comment]
Got it. I reviewed in their repo and found someone already reported this [here](https://github.com/angular-ui/ui-select/issues/2052) and looks like it won't get fixed based on the reply.

Thanks @sashberd.

**Comment by PeterDaveHello** [comment]
@josemv92 thank you for your contribution!
