### ISSUE TITLE
[Request] Add between.js

### ISSUE THREAD

**Issue by sasha240100** [cdnjs/cdnjs#12901]
**Library name:** between.js
**Git repository url:** https://github.com/sasha240100/between.js
**npm package url(optional):**  https://www.npmjs.com/package/between.js
**License(s):** MIT
**Official homepage:** https://between.js.org/

275 stars on 2018/08/04.

**Comment by sasha240100** [comment]
@sashberd Hi. Any updates on this? Would be great to know if I can assist somehow

**Comment by sashberd** [comment]
@sasha240100 You can send the PR and reviewers will review it ASAP. There is a problem on cdnjs with manpower, thus it will take a time
