### ISSUE TITLE
[Author][Request] Add pickr-widget

### ISSUE THREAD

**Issue by Simonwep** [cdnjs/cdnjs#12909]
**Library name:** pickr
**Library description:** Zero-dependency easy to use material color-picker. 
**Git repository url:** https://github.com/Simonwep/pickr
**npm package url:** https://www.npmjs.com/package/pickr-widget
**License:** MIT
**Homepage:** https://simonwep.github.io/pickr/ (demo)

Currently (09.08.2018) 1.200 stars and ~1000 downloads per week on npm.
Files needed to add are all under [/dist](https://github.com/Simonwep/pickr/tree/master/dist), would be a css and js file, also two files :)

**Comment by xtuc** [comment]
Why is that a high priority? Please check the contributing.md files in the repo and send a PR

**Comment by Simonwep** [comment]
No need for that anymore, I'll stick to JSDelivr since I used it from the start and most of the users already grab files from there :)
