### ISSUE TITLE
vanilla-lazyload `dist/lazyload.es2015.js`

### ISSUE THREAD

**Issue by verlok** [cdnjs/cdnjs#12911]
Hello,
my library https://github.com/verlok/lazyload is currently [published on cdnjs]((https://cdnjs.com/libraries/vanilla-lazyload)) under the name `vanilla-lazyload`.

I'm opening this because I recently (3 minor versions ago) changed the content of the `dist` folder, which now features [10 files](https://github.com/verlok/lazyload/tree/master/dist), but I'm only seeing [9 files](https://cdnjs.com/libraries/vanilla-lazyload)  on cdnjs. 

The file `lazyload.es2015.js` is missing, probably because of a previous configuration. 
Now this file can be published on CDNJS as it can be referenced directly as ES6 module from modern browsers.

Could you do that please? 
Thanks

**Comment by PeterDaveHello** [comment]
@verlok sure thing, wanna send a pull request for it?

**Comment by verlok** [comment]
@PeterDaveHello I'd like to, but I'm not sure of what to do in the PR, though. I fork the repo, then what?

**Comment by sashberd** [comment]
@verlok Hi
In which version exact this file should be hosted?

**Comment by xtuc** [comment]
Please send a PR that updates `ajax/libs/vanilla-lazyload/package.json` and the next version that the bot will add will fix that
