### ISSUE TITLE
Manually add Zebra_Datepicker old versions from git

### ISSUE THREAD

**Issue by sashberd** [cdnjs/cdnjs#12920]
Add old lib versions < 1.9.2 from [git](https://github.com/stefangabos/Zebra_Datepicker)

**Comment by maixiu** [comment]
I can tackle this one, any direction how I should start ?

**Comment by sashberd** [comment]
@maixiu 
1. Get cdnjs repo
2. Set up sparce checkout file for Zebra_datepicker folder
3. Add manually old version from git and commit them via PR

**Comment by RVMac** [comment]
Hi, I want to contribute. can you guide me on the needed tasks?

**Comment by govardhan27** [comment]
Hello, I would like to contribute if this is still not resolved. Please let me know.
Thanks

**Comment by xtuc** [comment]
No need to add manually versions. Please send a PR to enable autoupdate for `Zebra_Datepicker`. See the contributing.md files in the repo
