### ISSUE TITLE
[Request] Add lightgallery.js

### ISSUE THREAD

**Issue by arifpedia** [cdnjs/cdnjs#12925]
Full featured JavaScript lightbox gallery. No dependencies. **Not a jQuery Plugin**.

![lightgallery](https://raw.githubusercontent.com/sachinchoolur/lightgallery.js/gh-pages/lightgallery.png)

**Repository** : https://github.com/sachinchoolur/lightgallery.js/
**Homepage** : http://sachinchoolur.github.io/lightgallery.js/
**NPM** : https://www.npmjs.com/package/lightgallery.js
**License** : [GPLv3](https://github.com/sachinchoolur/lightgallery.js/blob/master/LICENSE.md)

**Modules**:

1. Thumbnail - [GitHub](https://github.com/sachinchoolur/lg-thumbnail.js)
2. Autoplay - [GitHub](https://github.com/sachinchoolur/lg-autoplay.js)
3. Video - [GitHub](https://github.com/sachinchoolur/lg-video.js)
4. Fullscreen - [GitHub](https://github.com/sachinchoolur/lg-fullscreen.js)
5. Pager - [GitHub](https://github.com/sachinchoolur/lg-pager.js)
6. Zoom - [GitHub](https://github.com/sachinchoolur/lg-zoom.js)
7. Hash - [GitHub](https://github.com/sachinchoolur/lg-hash.js)
8. Share - [GitHub](https://github.com/sachinchoolur/lg-share.js)

**Comment by iddddg** [comment]
附议,非目前仓库里的jquery版本.无依赖

**Comment by yacoob** [comment]
Any chance of this one getting added soon? Its jquery counterpart is already in and is a really good piece of software; lightweight jquery-less version would be perfect. :)

Thanks!
