### ISSUE TITLE
Update Hls.js page to point to current repo

### ISSUE THREAD

**Issue by johnBartos** [cdnjs/cdnjs#12927]
Hi,

Hls.js now belongs to the video-dev org - would you please update our page to reflect this? https://cdnjs.com/libraries/hls.js

Corresponding issue in our repo: https://github.com/video-dev/hls.js/issues/1890

Thanks!

**Comment by sashberd** [comment]
@johnBartos Both git`s are maintained as I see. I have no idea what is the rule in such case
@PeterDaveHello This [repo](https://github.com/dailymotion/hls.js) is forked from video-dev repo and still maintained. I think we cannot change repo property to video-dev, we have to add video-dev repo as separate lib, but we cannot do this with the same name as I know... What is solution IYO?

**Comment by broodjekipburger** [comment]
Can this be updated please?

**Comment by broodjekipburger** [comment]
Please help here.
I don't think both git's are maintained, so I would suggest to just change from the old dailymotion repo to the new maintained video-dev repo as lib source on cdnjs.
Thank you

**Comment by PeterDaveHello** [comment]
@sashberd See: https://web.archive.org/web/20160221174624/https://github.com/dailymotion/hls.js, it's originally dailymotion/hls.js and moved to video-dev/hls.js, so no problem to update it.

@broodjekipburger @johnBartos pull requests are welcome.

**Comment by sashberd** [comment]
@PeterDaveHello Whatever you said, but `old` repo:https://github.com/dailymotion/hls.js: was updated this summer
And `new` repo was also updated not so far https://github.com/video-dev/hls.js

**Comment by broodjekipburger** [comment]
@sashberd I am not sure.. latest version v0.11.0 (https://github.com/video-dev/hls.js/tree/v0.11.0) is on the video-dev git and I can't load it from cdnjs as long as it's pointing to the archived dailymotion repo

**Comment by dighan** [comment]
I confirm we (dailymotion) have moved `hls.js` project from `dailymotion` orga to `video-dev` a year ago (more details [here](https://medium.com/dailymotion/hls-js-from-dailymotion-to-beyond-384c0b2eeaa6)).  The [video-dev community](https://github.com/video-dev/hls.js) is the official owner of the project. Everything related to `hls.js` on `cdnjs.com` should point to `video-dev` rather than `dailymotion`. Could you tell me how to achieve it ?

**Comment by sashberd** [comment]
@dighan @broodjekipburger 
1) Todays autoupdate is via git. Your new repo has more release via npm, thus you should change autoupdate configuration to npm.  This is first commit
2)Also todays autouppdate takes all files from dist folder except demo files. Is it still right?
```
"fileMap": [
      {
        "basePath": "dist",
        "files": [
          "**/!(*-demo.*)"
        ]
      } 
```
3) On npm there are a lot of version with *canary* in name. Do we need to host them?
Usually we do not host such versions, thus you need to add second commit and add all versions with *canary*t o cdnjs .gitigonre file.
If you have any issue with PR create give me to know will glad to help

**Comment by dighan** [comment]
Understood. I'll try to open a PR but I have to admit it's not an easy task, the repo is quite big. [This](https://github.com/cdnjs/cdnjs/wiki/Cloning-specific-folders-of-cdnjs) should help. Thanks for the guidelines.

**Comment by sashberd** [comment]
This is how your sparce-checkout file should look:

> /ajax/libs/hls.js/*
> 
> /build
> /documents
> /test
> /spec
> /tools
> /LICENSE
> /hooks
> /*.yml
> /*.md
> /*.json
> /*.sh
> /*.js
> /.jscsrc
> /.gitignore
> #/ajax/libs/*/package.json // for tools/createSparseCheckoutConfig.js
>

**Comment by PeterDaveHello** [comment]
@dighan you can do it from GitHub web ui

**Comment by dighan** [comment]
Done https://github.com/cdnjs/cdnjs/pull/13085.
