### ISSUE TITLE
[Request] Add JsSipWrap

### ISSUE THREAD

**Issue by fengchunyan** [cdnjs/cdnjs#12921]
**Library name:** JsSipWrap
**Git repository url:http://fengchunyan@www.mihua.biz:8888/ruby/JsSipWrap.git
**npm package name or url** (if there is one): JsSipWrap
**License (List them all if it's multiple):MIT License
**Official homepage:https://sip.emicmh.com:3002

**Comment by sashberd** [comment]
@fengchunyan Are you talking about this lib? https://github.com/versatica/JsSIP. 

I can not access git url you provided

**Comment by fengchunyan** [comment]
hello our url is nothttps://github.com/versatica/JsSIP, our repository has used jssip,,it’sbased onJsSIP. but notJsSIP.


原始邮件
发件人:Alexnotifications@github.com
收件人:cdnjs/cdnjscdnjs@noreply.github.com
抄送:fengchunyanfengchunyan@emicnet.com; Mentionmention@noreply.github.com
发送时间:2018年8月22日(周三) 16:52
主题:Re: [cdnjs/cdnjs] [Request] Add JsSipWrap (#12921)


@fengchunyan Are you talking about this lib? https://github.com/versatica/JsSIP.
I can not access git url you provided

**Comment by fengchunyan** [comment]
our code is based on jssip,but not it.，，This is not in accordance with the rules？？

**Comment by sashberd** [comment]
@fengchunyan Again, I cannot access the url you provided
@PeterDaveHello Can you help?

**Comment by extend1994** [comment]
Close it due to no response, if there is other question please let us know.
