### ISSUE TITLE
angular.js-1.7.3, 1.7.4 is missing

### ISSUE THREAD

**Issue by binki** [cdnjs/cdnjs#12937]
I see 1.7.3 in https://github.com/angular/bower-angular but not at https://cdnjs.com/libraries/angular.js

**Comment by sufuf3** [comment]
@PeterDaveHello would you please take a look at this?
Because I saw you added [v1.7.2](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular.js/1.7.2) by yourself.
Maybe you know how to deal with this.
Thank you.

**Comment by Narretz** [comment]
Just a heads up. 1.7.4 has also been released and should be included.

**Comment by nepa** [comment]
AngularJS 1.7.5 was released on 4th of October 2018 and is now also missing:

https://github.com/angular/angular.js/blob/master/CHANGELOG.md

**Comment by Ermineia** [comment]
This is getting frustrating.  The second most copied library (after jquery) according to cdnjs.com and three versions outdated with two pending pull requests waiting for a review from a maintainer or owner.  Does the project need more maintainers?

**Comment by xtuc** [comment]
New versions were added.
