### ISSUE TITLE
cdnjs not up to date with version on github

### ISSUE THREAD

**Issue by ScotsScripts** [cdnjs/cdnjs#12939]
Just wanted to mention that github unite gallery is at 1.7.45 but version here is only up to 1.7.40

Not sure what else to do to help get it updated, thanks.

**Comment by holtkamp** [comment]
So you mean:

https://github.com/vvvmax/unitegallery/

versus 

https://cdnjs.com/libraries/unitegallery

Last tagged release is `1.7.40` https://github.com/vvvmax/unitegallery/releases

So I guess the author should tag a new version for the CDNJS update mechanism to kick in

**Comment by sashberd** [comment]
@ScotsScripts @holtkamp is right. Please open issue on lib page in order to add new version git tag and autoupdate will host it automatically ASAP
