### ISSUE TITLE
Webhook for library version updates

### ISSUE THREAD

**Issue by tracker1** [cdnjs/cdnjs#12934]
I just wrote/published [asdfgh](https://badge.fury.io/for/js/asdfgh) and was thinking it would be nice if there was a way to get notified when new zxcvbn releases happen... Ideally, I'd love to be able to do some kind of trigger to update my corresponding version to match a release from zxcvbn.

**Comment by xtuc** [comment]
I don't understand why cdnjs would do that. I think npm would be the best way to provide such a feature.
