### ISSUE TITLE
add react-keeper

### ISSUE THREAD

**Issue by allphfa** [cdnjs/cdnjs#12930]
Library name: react-keeper
Git repository url: https://github.com/vifird/react-keeper
npm package url(optional): https://www.npmjs.com/package/react-keeper
License(s): none
Official homepage: none

**Comment by sashberd** [comment]
@AlphaFase Which files should be hosted?

**Comment by sashberd** [comment]
@allphfa Which files should be hosted? If you do not know please open an issue at lib page and ask an author. If in next 7 days there is no answer from you or answer the issue will be closed
