### ISSUE TITLE
react 16.5.0 is missing

### ISSUE THREAD

**Issue by kjperkin** [cdnjs/cdnjs#12946]
react 16.5.0 appears to have been published ~7 days ago. @PeterBot by @PeterDaveHello appears to have committed react-dom 16.5.0 in 7aaed8f6 but it looks like react proper has not been updated.

I checked and I don't see an open issue or PR for this.

**Comment by sanbornhilland** [comment]
Same goes for `16.5.1` now.

**Comment by sufuf3** [comment]
@PeterDaveHello Would you please take a look?
The file struct still the same.
Many thanks.

**Comment by valleywood** [comment]
Any updates on this? (Also missing 16.5.1)

**Comment by extend1994** [comment]
Done in https://github.com/cdnjs/cdnjs/commit/87489f53a07651844cde987f2785d785c0e71966
