### ISSUE TITLE
[request] chessboard.js 

### ISSUE THREAD

**Issue by gonzalezjo** [cdnjs/cdnjs#12943]
**Name**: chessboard.js

**License**: MIT

**Webpage**: http://chessboardjs.com/ 

**Source code**: https://github.com/oakmac/chessboardjs/

**Download**: http://chessboardjs.com/releases/0.3.0/chessboardjs-0.3.0.zip

**Git repository URL**: https://github.com/oakmac/chessboardjs.git

If I'm missing anything, please let me know.

**Comment by sashberd** [comment]
@gonzalezjo There is no git tag in git repo. Could you please open issue to the lib author in order to add git tags?
May be there is npm for this lib?

**Comment by extend1994** [comment]
ping @gonzalezjo 
If there is no response in next 7 days, I will close this issue.

**Comment by gonzalezjo** [comment]
Will open an issue. Thank you for the ping.

**Comment by oakmac** [comment]
FYI - I added a tag for the v0.3.0 release of chessboard.js

https://github.com/oakmac/chessboardjs/tags

https://github.com/oakmac/chessboardjs/issues/161#issuecomment-435402680

**Comment by akiraheid** [comment]
@sashberd Looks like someone forked the repo and [added it to npm](https://www.npmjs.com/package/chessboardjs)
