### ISSUE TITLE
New Package Request: Material Design Components For The Web

### ISSUE THREAD

**Issue by Richienb** [cdnjs/cdnjs#12944]
I'd like to suggest [MDC](https://material.io/develop/web/docs/getting-started/) to be added to the packages of cdnjs. MDC is an open source library by Google which is meant to be the new version of [MDL](https://cdnjs.com/libraries/material-design-lite).

**Comment by sashberd** [comment]
@Richienb Are you talking about this [one](https://github.com/material-components/material-components-web)?

**Comment by Richienb** [comment]
Yes.

**Comment by sashberd** [comment]
[In the work already ](https://github.com/cdnjs/cdnjs/pull/11303)

**Comment by Richienb** [comment]
Yay!
