### ISSUE TITLE
[Request] Add SignalR (ASP.NET Core)

### ISSUE THREAD

**Issue by MartinGreen** [cdnjs/cdnjs#12940]
**Library name:** aspnet/signalr
**Library description:** SignalR real time communications library for ASP.NET Core.
**Git repository url:** https://github.com/aspnet/SignalR#readme
**npm package url:** https://www.npmjs.com/package/@aspnet/signalr
**License:** Apache-2.0
**Homepage:** https://docs.microsoft.com/en-us/aspnet/core/signalr

This is a new version of the SignalR client library for use with the new SignalR for ASP.NET Core server.
This does not replace the old version which is for use with ASP.NET.
Required files are in dist/browser.
Should also add @aspnet/signalr-protocol-msgpack

**Comment by sashberd** [comment]
@MartinGreen Which files should be hosted?

**Comment by MartinGreen** [comment]
From the npm package:
/dist/browser/signalr.js
/dist/browser/signalr.min.js

**Comment by kinosang** [comment]
How's it going?

**Comment by MatthewSteeples** [comment]
Newer bug for the same issue has some progress on it: #13198
