### ISSUE TITLE
[Request] Add ag-grid-community

### ISSUE THREAD

**Issue by seanlandsman** [cdnjs/cdnjs#12952]
Library name: ag-grid-community
Git repository url: https://github.com/ag-grid/ag-grid/tree/master/packages/ag-grid-community
npm package name or url (if there is one): https://www.npmjs.com/package/ag-grid-community
License (List them all if it's multiple): MIT
Homepage: www.ag-grid.com

**Comment by sashberd** [comment]
@seanlandsman Which files should be hosted?

**Comment by seanlandsman** [comment]
Hi

All files under "dist" please - you can (if it helps) use https://cdnjs.com/libraries/ag-grid as a template.

"ag-grid-community" is "ag-grid" renamed.

thanks very much

**Comment by seanlandsman** [comment]
thanks @sashberd

**Comment by sashberd** [comment]
@seanlandsman thanks to @PeterDaveHello
