### ISSUE TITLE
Add latest semantic-ui v2.4.0

### ISSUE THREAD

**Issue by corydeppen** [cdnjs/cdnjs#12953]
[Semantic UI v2.4.0](https://github.com/Semantic-Org/Semantic-UI/releases/tag/2.4.0) was released a few days ago but still doesn't appear on cdnjs. Is this pending review or is there some other reason it doesn't appear on the site?

/cc @jlukic

**Comment by sashberd** [comment]
@corydeppen Autoupdate looks good. 
@PeterDaveHello @extend1994 FYR

**Comment by corydeppen** [comment]
It's been a week since the 2.4.0 release and it's still not available on the CDN. Is there anything preventing it from being made available?

**Comment by jlukic** [comment]
Any issue here? Would like to help fix if I can.

**Comment by brunotourinho** [comment]
We are in version 2.4.2 already, but in cdn.js repo still in 2.3.3. Visual Studio Library Manager uses cdn.js to update my dependencies. Still waiting for the update ASAP
