### ISSUE TITLE
[Request] Upgrade mermaid to 8.0.0-rc8

### ISSUE THREAD

**Issue by jackycute** [cdnjs/cdnjs#12966]
Library name: mermaid
Git repository url: https://github.com/knsv/mermaid
npm package name or url (if there is one): https://www.npmjs.com/package/mermaid
License (List them all if it's multiple): MIT https://github.com/knsv/mermaid/blob/master/LICENSE
Official homepage: https://mermaidjs.github.io
Wanna say something? Please upgrade this lib from 7.1.0 to 8.0.0-rc8 Thank you!

**Comment by sufuf3** [comment]
Hi
Is this for your request?
https://cdnjs.com/libraries/mermaid/8.0.0-rc.8
Thanks

**Comment by extend1994** [comment]
Hi, @jackycute seems https://cdnjs.com/libraries/mermaid/ is what you request for, I will close this issue now for this reason.

If you need anything else, please let us know, thanks!
