### ISSUE TITLE
[Request] Add rxdb

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#12964]
**Library name:** rxdb
**Git repository url:** https://github.com/pubkey/rxdb
**npm package name or url** (if there is one): https://www.npmjs.com/package/rxdb
**License (List them all if it's multiple):** [Apache-2.0](https://github.com/pubkey/rxdb/blob/master/LICENSE.txt)
**Homepage**: https://pubkey.github.io/rxdb/

It's recommended to use npm auto-update to fetch files for a browser.

**Comment by alemuro** [comment]
I made PR few hours ago. I hope it's well implemented :) 
Regards,
