### ISSUE TITLE
Add htmlparser2

### ISSUE THREAD

**Issue by kyleplo** [cdnjs/cdnjs#12960]

**Comment by extend1994** [comment]
@kyleplo Please provide further info, thx.
Will close this issue if there is no response in next 7 days.

**Comment by kyleplo** [comment]
Sorry.
Library name: htmlparser2
Git repository: https://github.com/fb55/htmlparser2
NPM Package: https://www.npmjs.com/package/htmlparser2
Licence: MIT

**Comment by extend1994** [comment]
@kyleplo thanks, but looks like this lib can't be directly used in front-end?, i.e. include the script using `<script src>`. We don't build/browserify file for any library, need pre-built file from the upstream instead. Can you help check this by opening issue there?
