### ISSUE TITLE
[Request] Please add scribbletune (meets cdnjs requirements for lib addition)

### ISSUE THREAD

**Issue by walmik** [cdnjs/cdnjs#12968]
Library name: scribbletune
Git repository url: https://github.com/scribbletune/scribbletune
npm package name or url (if there is one): https://www.npmjs.com/package/scribbletune
License (List them all if it's multiple): MIT
Homepage: https://scribbletune.com/

**Comment by xtuc** [comment]
Why is that a high priority? Please submit a PR to add the package on the cdn, see contributing.md files in the repo

**Comment by walmik** [comment]
Closing this issue as it s already added to CDNjs. Thank you!
