### ISSUE TITLE
[author] npm auto-update seems broken in latest SCION release

### ISSUE THREAD

**Issue by jbeard4** [cdnjs/cdnjs#12971]
Hi,

I successfully added the SCION library to cdnjs npm auto-update, and since then, auto-update has been working perfectly. You can find the original PR here: https://github.com/cdnjs/cdnjs/pull/8782

However, cdnjs npm auto-update has failed to detect and publish the latest version of SCION (5.0.3) published to npm: https://www.npmjs.com/package/scxml

One thing that changed in this release was the repository url. It now points to gitlab instead of github. Is it possible that this broke npm auto-update? If so, what would be the best way to fix this?

Thank you for your help with this.

**Comment by sashberd** [comment]
@jbeard4 I think it was hosted? https://cdnjs.com/libraries/scion/4.3.1

**Comment by jbeard4** [comment]
@sashberd Thank you for your reply. I'm afraid I don't understand - what do you mean "it was hosted"? 
The issue is that the npm auto-update has not updated SCION from 4.3.1 to 5.0.3.

Let me know what you think. Thanks.

**Comment by PeterDaveHello** [comment]
I think you mean v5.x?

**Comment by PeterDaveHello** [comment]
The reason why it's not updated its structure was changed, which needs a manual update, I'll do it soon.

**Comment by sashberd** [comment]
@PeterDaveHello I do not know what is manual update, but the file structure of lib is same same like it was in v 4.3.1. All files are in `dist\` folder. Just FYI

**Comment by PeterDaveHello** [comment]
It was changed since v5, the bot will only add those version with file structure 100% match with the previous version

**Comment by PeterDaveHello** [comment]
@jbeard4 should be good now ;)

**Comment by jbeard4** [comment]
Thank you!
