### ISSUE TITLE
[Request] Add shards-vue

### ISSUE THREAD

**Issue by iamDecode** [cdnjs/cdnjs#13023]
**Library name:** shards-vue
**Library description:** Shards Vue is a Vue.js UI kit based on Shards UI and Bootstrap 4.
**Git repository url:** https://github.com/DesignRevision/shards-vue
**License:** MIT
**Official homepage:** https://designrevision.com/downloads/shards-vue/

Has 204 stars as of 8/10/2018

**Comment by Pielgrin** [comment]
taken
