### ISSUE TITLE
[REQUEST] Add Callbaxx

### ISSUE THREAD

**Issue by ramadis** [cdnjs/cdnjs#13036]
Library Name: Callbaxx
Library Description: 🔥 JS utility library to bring classic callback style programming to synchronous code
Git repository url: https://github.com/scf4/callbaxx
License: MIT

56 Stars on 14/10/2018

**Comment by sashberd** [comment]
Hi @ramadis 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
