### ISSUE TITLE
[Request] Add zeu

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#13038]
**Library name:** zeu
**Git repository url:** https://github.com/shzlw/zeu
**npm package name or url** (if there is one): https://www.npmjs.com/package/zeu
**License (List them all if it's multiple):** [MIT](https://github.com/shzlw/zeu/blob/master/LICENSE)
**Homepage**: https://shzlw.github.io/zeu/docs/introduction.html

1,297 stars on 2018/10/15.
It's recommended to use npm auto-update to fetch more versions.

**Comment by alemuro** [comment]
I made a PR to include this library into cdnjs.
Regards.

**Comment by bigopon** [comment]
@extend1994 Very nice lib 👍

**Comment by xtuc** [comment]
PR has been closed
