### ISSUE TITLE
plotly 1.33.1 js is missing

### ISSUE THREAD

**Issue by pacoFang** [cdnjs/cdnjs#13033]
Library name: plotly.js
Git repository url: https://github.com/plotly/plotly.js
npm package url(optional): https://www.npmjs.com/package/plotly.js
License(s): MIT
Official homepage: https://plot.ly/javascript/

**Comment by sashberd** [comment]
@pacoFang Exists! https://cdnjs.com/libraries/plotly.js/1.33.1
