### ISSUE TITLE
[Request]: Aurelia

### ISSUE THREAD

**Issue by EisenbergEffect** [cdnjs/cdnjs#13053]
Library name: Aurelia
Repository url: https://github.com/aurelia/script
License: MIT
Official homepage: https://aurelia.io
GitHub Stars: 10,000+

Note: The repo URL above is what we use to build our script-tag build. The library itself is split over many repos. The most central library repo is https://github.com/aurelia/framework

Please let us know what information you need from us to get our script-tag builds hosted on CDN.

Thank you in advance!

**Comment by sashberd** [comment]
@EisenbergEffect I think it was hosted: https://github.com/cdnjs/cdnjs/pull/11356

**Comment by EisenbergEffect** [comment]
@sashberd I'm not sure what that is or how it got there. It's definitely not official (or up to date). We have a whole new build and approach to script-taggable builds which was only finalized within the last couple of weeks. @bigopon can provide more info to help configure the cdn.

**Comment by sashberd** [comment]
@EisenbergEffect As I see both libs are maintained, and moreover ,buy you. Do you mean there is another lib with name **aurelia-scripts** that should be hosted as separate lib on cdnjs?

**Comment by EisenbergEffect** [comment]
In either case (and even if it was me and I forgot), the cdn library above should be replaced by the new one or we need to create a different one for our official script tag ready build.

**Comment by EisenbergEffect** [comment]
Reviewing that PR linked above, no one on that thread is a member of the Aurelia Core team.

**Comment by sashberd** [comment]
@EisenbergEffect I think we should host another lib with name aurelia-script because both libs are maintained.
@PeterDaveHello @extend1994 @sufuf3 FYR

**Comment by EisenbergEffect** [comment]
We're thinking to brand this particular incarnation of Aurelia "Aurelia Script" more officially, so I think that should be fine in the end. Let me know if you need anything else from me. Thanks!
