### ISSUE TITLE
Showdown 1.8.7 update is taking a long time to be published

### ISSUE THREAD

**Issue by KirkMunro** [cdnjs/cdnjs#13055]
Earlier this week Showdown.js released version 1.8.7, and I've been checking for it several times daily since the release on cdnjs. It's been two days, which seems much longer than it usually takes for updates to be made available (IIRC I read somewhere on your site that it can take up to 12 hours). Can someone please look into why this update isn't published yet? Thanks!

**Comment by holtkamp** [comment]
Same goes for Flag-Icon-CSS

- https://cdnjs.com/libraries/flag-icon-css (at 3.2.0)
- https://github.com/lipis/flag-icon-css/releases/tag/3.2.1

**Comment by KirkMunro** [comment]
Seems both of these were updated. Closing.
