### ISSUE TITLE
Tinymce plugins fail to load.

### ISSUE THREAD

**Issue by rturkek** [cdnjs/cdnjs#13068]
These libraries are randomly failing for last so many days. Wait times for this file went to 30 seconds sometimes
https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.7.13/plugins/print/plugin.min.js

it randomly happens other tinymce libraries too. I'm loading like 50 libraries from cdnjs but most the time it's tinymce libraries that fail. Problem continues for last week.

**Comment by sashberd** [comment]
@PeterDaveHello FYR

**Comment by gtmadev** [comment]
Not sure if related, but I have been seeing this as well. I may need to switch back to bundling it myself. The CDN has not been reliable for some reason.

**Comment by MattIPv4** [comment]
@gtmadev Hi there, what you were experiencing was likely #13166 which should now be resolved.

@rturkek are you still experiencing the original issue reported with this specific library?

**Comment by gtmadev** [comment]
The issue was intermittent, but began working a short while later. Have not seen the issue again so far. Thanks for the follow up.

**Comment by Jabberrwocky** [comment]
Receiving 404 when trying to retrieve: https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.9.3/plugins/advlist/plugin.min.js

**Comment by gtmadev** [comment]
I was also seeing this again today. Not sure why the library still keeps going away. Later on it appeared again. I haven't tried it in the last couple hours though.

**Comment by MattIPv4** [comment]
Related to #13165 

Please post full request/response headers and the resource URL that fails if it occurs again.
