### ISSUE TITLE
Got 403 Forbidden while trying to download open-iconic from visual studio 2017 with libman

### ISSUE THREAD

**Issue by Dusthorn** [cdnjs/cdnjs#13062]
In Visual Studio 2017 Community Edition I wanted to add open-iconic to my website application via libman. On package restoring I got this error:
Failed to download resource from “https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/webp/account-login-2x.webp”

Here is my libman.json

{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "library": "jquery@3.3.1",
      "files": [
        "jquery.min.js",
        "jquery.js",
        "jquery.min.map"
      ],
      "destination": "wwwroot/lib/jquery/"
    },
    {
      "provider": "unpkg",
      "library": "bootstrap@4.1.3",
      "destination": "wwwroot/lib/bootstrap/"
    },
    {
      "library": "popper.js@1.14.4",
      "destination": "wwwroot/lib/popper.js/"
    },
    {
      **"library": "open-iconic@1.1.1",**
**"destination": "wwwwroot/lib/open-iconic/"**
    }
  ]
}

**Comment by MattIPv4** [comment]
Hi there, I have added this file extension request to #13145 where I am keeping track of them all.
