### ISSUE TITLE
react version  field not updated?

### ISSUE THREAD

**Issue by Lovesueee** [cdnjs/cdnjs#13070]
new version like 16.6.0, has beed added，but `pkg.version`  field is still 16.4.2 (not updated)

openapi: https://api.cdnjs.com/libraries/react

![image](https://user-images.githubusercontent.com/1896831/47479875-0f01be80-d861-11e8-909b-2398ce4707aa.png)

**Comment by Lovesueee** [comment]
why close this issue? It hasn't been resolved yet?

**Comment by sashberd** [comment]
@Lovesueee As @PeterDaveHello we have nothing to do with it. We take all files and their content from upstream. Open issue in author`s git

**Comment by Lovesueee** [comment]
@sashberd OK，thanks
