### ISSUE TITLE
add support for adblock filters list

### ISSUE THREAD

**Issue by KonoromiHimaries** [cdnjs/cdnjs#13072]
like https://www.jsdelivr.com/rawgit

example
![2018-10-26-cdnjs com - the best foss cdn for web related libraries to speed up your website](https://user-images.githubusercontent.com/5884000/47544663-7adb3a00-d8e8-11e8-8a80-1e6ffb1ac72b.png)

related to https://github.com/collinbarrett/FilterLists/issues/598

**Comment by MattIPv4** [comment]
cdnjs is not going to become a raw mirror of GitHub or NPM, we host curated libraries.
