### ISSUE TITLE
[Request] Add chromata

### ISSUE THREAD

**Issue by ralphilius** [cdnjs/cdnjs#13078]
**Library name:** chromata
**Git repository url:** https://github.com/michaelbromley/chromata
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/michaelbromley/chromata
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@ralphilius There is no git tag in this git lib also no npm version
Please open issue for author in lib in order to add git tag

After 7 days we will close this issue if there is no update from author
Thanks
