### ISSUE TITLE
Automatic update not working for froala-editor

### ISSUE THREAD

**Issue by stefanneculai** [cdnjs/cdnjs#13083]
It looks cdnjs is not updating to the latest 2.9.0 version for the Froala Editor package. Do you have any idea why this is happening?

**Comment by sashberd** [comment]
@stefanneculai I ran git autoupdate on my local machine it looks good. Lets wait for a couple of days and the recheck if new version was hosted

**Comment by sashberd** [comment]
@stefanneculai Hosted
