### ISSUE TITLE
[Request] Add hashids

### ISSUE THREAD

**Issue by frobinsonj** [cdnjs/cdnjs#13095]
**Library name**: hashids
**Git repository url**: https://github.com/ivanakimov/hashids.js
**npm package name or url (if there is one)**: https://www.npmjs.com/package/hashids
**License (List them all if it's multiple)**: [MIT](https://github.com/ivanakimov/hashids.js/blob/master/LICENSE)
**Homepage**: https://hashids.org/javascript/

**Comment by tim-nz** [comment]
Any hope for this?

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/hashids
