### ISSUE TITLE
CDN in China

### ISSUE THREAD

**Issue by Showfom** [cdnjs/cdnjs#13091]
Hello,

I've built and launched the cdnjs CDN in China for 3 years, You can simply replace `cdnjs.cloudflare.com` with `cdnjs.loli.net`

Is there any requirement for being official CDN provider for cdnjs project?

**Comment by MattIPv4** [comment]
@PeterDaveHello Is this something for you or for Ryan at a later date?

**Comment by xtuc** [comment]
This is a question for Cloudflare, closing for now.
