### ISSUE TITLE
git auto update is not working for iris-ws

### ISSUE THREAD

**Issue by dibyendu** [cdnjs/cdnjs#13090]
git auto update is not working for iris-ws.

Latest version is 11.0.4 but the one on the cdnjs is 10.7.0

https://github.com/kataras/iris/releases
vs
https://cdnjs.com/libraries/iris-ws

**Comment by sashberd** [comment]
@PeterDaveHello This lib autoupdate is good, tried on my local machine.
I need your help to check why it is not working any more.
@PeterDaveHello FYR

**Comment by xtuc** [comment]
The bot added
```
Add iris-ws v11.1.1
```
