### ISSUE TITLE
[Request] Add vue-load-image

### ISSUE THREAD

**Issue by john015** [cdnjs/cdnjs#13101]
Library name: vue-load-image
Git repository url: https://github.com/john015/vue-load-image
npm package name or url (if there is one): https://www.npmjs.com/package/vue-load-image
License (List them all if it's multiple): MIT
Homepage: https://john015.github.io/vue-load-image/

**Comment by sashberd** [comment]
Hi @john015 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
