### ISSUE TITLE
No auto update for simplebar

### ISSUE THREAD

**Issue by olafcm** [cdnjs/cdnjs#13102]
Stays at v2.6.1 (https://cdnjs.com/libraries/simplebar) but v3.1.0 (https://github.com/Grsmto/simplebar/releases) expected.
The author changed Git tag version formatting from "v2.6.1" (https://github.com/Grsmto/simplebar/releases/tag/v2.6.1) to "simplebar@3.1.0"(https://github.com/Grsmto/simplebar/releases/tag/simplebar%403.1.0). Maybe that is the reason of the issue?
Can this be resolved please?
Thank you

**Comment by Grsmto** [comment]
I was about to post an issue about this. The problem is that SimpleBar is now using a monorepo design.
Could you tell me how I can get CDNJS to support a monorepo?

Thanks.

**Comment by Grsmto** [comment]
Hi @PeterDaveHello thanks for proposing your help.
Basically SimpleBar main package is not on the root of the repository anymore but in a `/packages` sub-folder.
Before:
```
/src
/dist
./package.json
```

After:
```
/packages
  /simplebar
    /package.json
  /simplebar-react
  /simplebar-vue
```

So I guess CDJS by default is checking for the root package.json but now it's not at the same location anymore so I don't know if we can do a PR to CDNJS or something to fix that!

**Comment by PeterDaveHello** [comment]
@Grsmto would you like to treat them like the same project on CDNJS or separate them?

**Comment by Grsmto** [comment]
@PeterDaveHello so I would like the `package/simplebar` to be the same package as the current one.

In the second step it would be great to have the new packages `simplebar-react` and `simplebar-vue` (both on npm) on CDNJS as well!

**Comment by PeterDaveHello** [comment]
@Grsmto feel free to help update its package.json file on CDNJS, it'll handle it.

**Comment by Grsmto** [comment]
@PeterDaveHello ok I see so I should submit a PR with the package.json updated? I just read the `CONTRIBUTING.md`.

**Comment by PeterDaveHello** [comment]
@Grsmto yes, you are correct!

**Comment by Grsmto** [comment]
Sorry for the ping but am I doing something wrong with the sparse checkout or it's just super long to clone anyway?

![screenshot 2018-12-01 at 20 48 13](https://user-images.githubusercontent.com/527559/49333684-791d2a00-f5aa-11e8-89d8-2df76de5466b.jpg)

**Comment by broodjekipburger** [comment]
Is it possible to have this fixed?
Would be very much appreciated to have the latest version of simplebar accessible through cdnjs :-)

**Comment by Grsmto** [comment]
It's on my todo-list.
