### ISSUE TITLE
[Request] Add vue-cesium

### ISSUE THREAD

**Issue by zouyaoji** [cdnjs/cdnjs#13100]
Library name:  vue-cesium
Git repository url: https://github.com/zouyaoji/vue-cesium
npm package url(optional): https://www.npmjs.com/package/vue-cesium
Official homepage: https://zouyaoji.top/vue-cesium/#/
Description: vue component of cesium

**Comment by sashberd** [comment]
Hi @zouyaoji 

The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!

**Comment by zouyaoji** [comment]
I got it ,thank you.

**Comment by zouyaoji** [comment]
Hahaha, the requirements may have been met so far, please evaluate again.

**Comment by zouyaoji** [comment]
@MattIPv4

**Comment by zouyaoji** [comment]
@MattIPv4 
Please evaluate it again. Or do I need to open a new issue?

**Comment by MattIPv4** [comment]
I am working through every issue in the repo oldest to newest, please have patience.

**Comment by MattIPv4** [comment]
@zouyaoji What should we be hosting here, you don't seem to have bundled versions in your package?

**Comment by zouyaoji** [comment]
@MattIPv4  Hello, I have pushed the built package to npm. Do I need to push it on github?

**Comment by MattIPv4** [comment]
npm should be fine, but it looks like the new version hasn't been published yet?

**Comment by zouyaoji** [comment]
Version 2.1.2 is already the latest. See [vue-cesium](https://www.npmjs.com/package/vue-cesium).
![image](https://user-images.githubusercontent.com/24430116/81915410-1fc18300-9605-11ea-9670-b620761b71b1.png)

**Comment by MattIPv4** [comment]
I don't see a bundled version of the library in the package?

**Comment by zouyaoji** [comment]
There should be some, and those installed through npm can be used normally. The entry file for vue-cesium is in the lib folder.
![image](https://user-images.githubusercontent.com/24430116/81916521-81362180-9606-11ea-8eff-73971a9e0230.png)

**Comment by MattIPv4** [comment]
Ah. It looks like `index.umd.js` is bundled. Is there any css that's needed with that file, or is that the only file we need?

**Comment by zouyaoji** [comment]
There are no css files that must be loaded, but there are css files that are loaded on demand, depending on the user using certain features. It may be necessary to introduce the vc-navigation-sm.css or vc-navigation.css file in the lib folder

**Comment by zouyaoji** [comment]
@MattIPv4 

Hello, I upgraded vue-cesium to version 3.0, but the structure of the built package product has changed, causing cdnjs to list the version number, but the specific file cannot be found. Please help with this.

![image](https://user-images.githubusercontent.com/24430116/235355350-4c91115a-1e7a-4b90-8107-e23803f9e9aa.png)

**Comment by MattIPv4** [comment]
Please file an update request issue, specifying what files should be included now: https://github.com/cdnjs/packages/issues/new?assignees=&labels=%F0%9F%93%A6+Update+Request&template=update-request.yml&title=Update%3A+xxx

**Comment by zouyaoji** [comment]
Received, I have submitted an update request, thank you very much.

https://github.com/cdnjs/packages/issues/1531
