### ISSUE TITLE
403 Forbidden Error for Mathjax a11y files

### ISSUE THREAD

**Issue by DawoudSheraz** [cdnjs/cdnjs#13118]
Hi!
   I have been using Mathjax in a project, that is loaded through cdnjs. However, when I turn a11y feature of Mathjax, I receive 403 error for 'invalid_keypress.ogg' files. Here is the [link](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/extensions/a11y/invalid_keypress.ogg) to said file. I wanted to be sure if you serve media files through your CDN or not.
Thanks!

**Comment by MattIPv4** [comment]
Hi there, I have added this file extension request to #13145 where I am keeping track of them all.
