### ISSUE TITLE
Update svg.js

### ISSUE THREAD

**Issue by Fuzzyma** [cdnjs/cdnjs#13112]
**Library name:** svg.js
**Git repository url:** https://github.com/svgdotjs/svg.js
**npm package**: https://www.npmjs.com/package/@svgdotjs/svg.js
**License:** [MIT](https://github.com/svgdotjs/svg.js/blob/master/LICENSE.txt)
**Homepage**: svgjs.com

We do not upload distribution files to github anymore from version 3 on. So you need to use the npm package instead or use the zip from the release page

**Comment by PeterDaveHello** [comment]
@Fuzzyma feel free to send a pull request :)

**Comment by Fuzzyma** [comment]
@PeterDaveHello Thanks for the fast response. What do I need to change so that npm is used instead of github as endpoint?
