### ISSUE TITLE
[Request] Add browserfs

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#13111]
**Library name:** browserfs
**Git repository url:** https://github.com/jvilk/BrowserFS
**npm package name or url** (if there is one): http://npmjs.com/package/browserfs
**License (List them all if it's multiple):** [MIT](https://github.com/jvilk/BrowserFS/blob/master/package.json#L14)
**Homepage**: None

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/BrowserFS
