### ISSUE TITLE
[Request] Add html2pdf

### ISSUE THREAD

**Issue by TheGuywithTheHat** [cdnjs/cdnjs#13114]
**Library name**: html2pdf
**Git repository url**: https://github.com/eKoopmans/html2pdf
**npm package url**: https://www.npmjs.com/package/html2pdf.js
**License**: MIT

**Comment by HuYuee** [comment]
![image](https://user-images.githubusercontent.com/12147318/50392949-86829a00-078d-11e9-84db-84ae31903224.png)
