### ISSUE TITLE
Content Security Policy Error Chrome 70

### ISSUE THREAD

**Issue by lon9man** [cdnjs/cdnjs#13116]
**What i do**
simply open your site in Chrome 70

**What i get**
error message in Javascript console:
`Refused to load the script 'chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/localLib/jquery/jquery-1.12.4.min.js.local' because it violates the following Content Security Policy directive: "default-src 'unsafe-eval' 'self' *.carbonads.com *.getclicky.com fonts.gstatic.com www.google-analytics.com fonts.googleapis.com cdnjs.cloudflare.com 'unsafe-inline' https: data: ". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.`

screenshot:
![screenshot from 2018-12-04 10-31-43](https://user-images.githubusercontent.com/10497794/49429598-89532600-f7b1-11e8-8e29-7f9a9646aa17.png)

**What i expect**
work without error in the latest Chrome builds

**Comment by MattIPv4** [comment]
@lon9man Hi there, it appears that this error is not actually a cdnjs site issue and rather an issue with an extension you have installed on Chrome. Can you try accessing the page in incognito mode (where extensions should be disabled) and let me know the result?

**Comment by lon9man** [comment]
@MattIPv4 Hi, i have checked:
- in incognito it works **correctly**
- with PAUSED AdBlock it works with the same error
- with DISABLED AdBlock-extension it works **correctly**

strange, but AdBlock doesn't trigger the same error on multiple other websites. 
what do you think about possible cause of error with pair **CDN.JS + ADBLOCK**?

**Comment by MattIPv4** [comment]
@lon9man Yeah this appears to be due to the `content-security-policy` header that we set on the site.

**Comment by lon9man** [comment]
@MattIPv4 i understood this.
but in general (for own interest), are there some steps, which AdBlock/.../other_extension can make to remove such error with `content-security-policy` header?

**Comment by MattIPv4** [comment]
@lon9man Well it looks like its swapping the cdnjs jquery with a local copy of jquery which is causing the issues as far as I can tell.

Frankly I do not recommend using AdBlock though, it's a pretty bad extension. uBlock Origin is the way to go for ad blocking extensions.
