### ISSUE TITLE
update nosleep to version 0.9.0 (also missing versions 0.7+)

### ISSUE THREAD

**Issue by richtr** [cdnjs/cdnjs#13119]
The latest version available for [NoSleep.js](https://github.com/richtr/NoSleep.js) on cdnjs is [v0.6.0](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/nosleep).

From `v0.7.0` onwards the [package.json autoupdate `basePath`](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/nosleep/package.json#L25) needs to be changed from empty (`""`) to `"dist"` to point toward the latest `NoSleep.js` and `NoSleep.min.js` build files.

This is the required change in [/ajax/libs/nosleep/package.json](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/nosleep/package.json):

```diff
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/richtr/NoSleep.js.git",
    "fileMap": [
      {
-       "basePath": "",
+       "basePath": "dist",
        "files": [
          "NoSleep*"
        ]
      }
    ]
  }
```

If you need any further information to proceed with this update please let me know.

**Comment by xtuc** [comment]
Please send a PR to update the package.json

**Comment by MattIPv4** [comment]
I see no reason for this being closed. Having it closed means I won't see it to address it as I'm working throgh all the issues, nor will anyone else.
