### ISSUE TITLE
gridLineDashStyle missing grid line at bottom when only one item

### ISSUE THREAD

**Issue by tuanmy** [cdnjs/cdnjs#13122]
gridLineDashStyle missing grid line at bottom when only one item as bellow demo.
Anyone help me ? 
https://jsfiddle.net/nra6d3fj/1/

My expectation look like: http://i.prntscr.com/-mpzxrNwR9GjBJx1mRWmDA.png

**Comment by PeterDaveHello** [comment]
@tuanmy is this related with CDNJS?

**Comment by tuanmy** [comment]
> @tuanmy is this related with CDNJS?

It is not related to CDNJS? I have tried many version 6.0.x and 6.1.x but still don't resolve my issue

**Comment by PeterDaveHello** [comment]
@tuanmy thought it's the library's issue?

**Comment by tuanmy** [comment]
> @tuanmy thought it's the library's issue?

yep, I think so, because 2 or more items, that is okay :(

**Comment by tuanmy** [comment]
I solved my issue
https://stackoverflow.com/questions/53662652/gridlinedashstyle-of-highchart-missing-grid-line-at-bottom-when-only-one-item-as
