### ISSUE TITLE
Sponsor inconsistency

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13138]
Hiya,

On the main cdnjs site (https://cdnjs.com/about), only three sponsors are listed (CF, Algolia, DO).
However, in the readme of this repo (https://github.com/cdnjs/cdnjs/blob/master/README.md) there are four listed (CF, Algolia, DO, Heroku).

Is there a reason heroku is listed here and not on the site, or is it a relic that was left behind?

**Comment by PeterDaveHello** [comment]
Yes, I really want to list Heroku to thank them, but the last time I asked Heroku, they're still not ready for their content here and not really mind to leave that blank, I'll contact them soon again.

**Comment by MattIPv4** [comment]
Closing -- https://github.com/cdnjs/static-website will have all sponsors listed
