### ISSUE TITLE
Moment.js not automatically updated

### ISSUE THREAD

**Issue by holtkamp** [cdnjs/cdnjs#13146]
[Moment.js](https://cdnjs.com/libraries/moment.js) is configured to automatically update with https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/moment.js/package.json

Version [`2.23.0`](https://github.com/moment/moment/releases) has been tagged a day ago, but seems not detected by the CDNJS bot, resulting in a 404 page for:

https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js

The last two versions seem to have been processed by the @PeterBot as we can see here:

https://github.com/cdnjs/cdnjs/search?q=moment.js&type=Commits

**Comment by holtkamp** [comment]
Looking at https://github.com/cdnjs/cdnjs/search?q=moment.js&type=Commits it seems this problem have been resolved manually by a commit by @PeterDaveHello 

https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js

Not sure if this issue can be closed yet? The auto-update mechanism should work automatically, right?

**Comment by s1awa** [comment]
2.24.0 was not added automatically yet

**Comment by PeterDaveHello** [comment]
commit 37001180f91352d60695813bcd73ef2b2b89c58a
Author: Peter Dave Hello <hsu@peterdavehello.org>
Date:   Mon Jan 28 23:49:41 2019 +0800

    Add moment.js v2.24.0

commit af7e4cd999a095787b49ed41a85916ea0f95d834
Author: Peter Dave Hello <hsu@peterdavehello.org>
Date:   Mon Dec 24 18:30:45 2018 +0800

    Add moment.js v2.23.0

**Comment by holtkamp** [comment]
Hey @PeterDaveHello, thanks for working on this. See https://github.com/cdnjs/cdnjs/issues/13146#issuecomment-450157627, is the auto-update mechanism fixed now? It seems you resolved it manually again...
