### ISSUE TITLE
403 Forbidden - whitelist update

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13145]
Originally from https://twitter.com/leonirlopes/status/1070650338749882368

It appears sound files in general (#13118 .ogg) aren't currently permitted through cdnjs and return a 403 Forbidden when access is attempted.

Eg: https://cdnjs.com/libraries/ion-sound
 - https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.mp3
 - https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.ogg
 - https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.aac

# File extension requests
 - [mp3](https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.mp3) #13145
 - [ogg](https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.ogg) #13145 #13118
 - [aac](https://cdnjs.cloudflare.com/ajax/libs/ion-sound/3.0.7/sounds/beer_can_opening.aac) #13145
 - scss #13145
 - [webp](https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/webp/account-login-2x.webp) #13062 
 - json #10160
 - wasm #12681

**Comment by MattIPv4** [comment]
From #13120 - SCSS files to be added

**Comment by MattIPv4** [comment]
From #13118 - OGG again

**Comment by MattIPv4** [comment]
From #13062 - WEBP files

**Comment by MattIPv4** [comment]
From #10160 - JSON files

**Comment by MattIPv4** [comment]
From #12681 - WASM files

**Comment by MattIPv4** [comment]
Update on this, Cloudflare engineering are looking into this for us. I will post further updates as I get them 😄

**Comment by MattIPv4** [comment]
All extensions apart from .wasm are now in the whitelist and being served on cdnjs.cloudflare.com 🎉

**Comment by MattIPv4** [comment]
For clarification on this, we are still waiting for Cloudflare to add (or confirm it has been added) .wasm to the whitelist of extensions that we serve.

**Comment by xtuc** [comment]
also .ts from #13689

**Comment by xtuc** [comment]
I added .wasm (https://cdnjs.cloudflare.com/ajax/libs/hi-sven/1.1.17/index.wasm) and .ts (https://cdnjs.cloudflare.com/ajax/libs/hi-sven/1.1.17/index.ts)

**Comment by Driphter** [comment]
Can you get .html added? (https://cdnjs.cloudflare.com/ajax/libs/ionicons/5.0.0/cheatsheet.html)

**Comment by MattIPv4** [comment]
I disagree with adding html, cdnjs is not a site/docs host.
