### ISSUE TITLE
Twitter account

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13143]
Hiya,

Does anyone know who has the login details for the twitter account?
I believe Thomas does but he appears to have gone awol recently, does anyone else have the details?

**Comment by PeterDaveHello** [comment]
@MattIPv4 no I don't, only @ryankirkman

**Comment by MattIPv4** [comment]
Ah okay, I'll wait and see if he replies here or I'll send off an email to him in a few days. Assuming Thomas doesn't get back to me before.

**Comment by ryankirkman** [comment]
@MattIPv4 and @PeterDaveHello I have added you both as collaborators on the cdnjs account via TweetDeck teams: https://help.twitter.com/en/using-twitter/tweetdeck-teams

Let me know if you received the invite.

**Comment by MattIPv4** [comment]
@ryankirkman Invite received, thank you!

**Comment by MattIPv4** [comment]
@ryankirkman Could you possibly set the account DMs to open so anyone can get in touch should they need to through that method?

**Comment by ryankirkman** [comment]
@MattIPv4 Is this now resolved?

**Comment by MattIPv4** [comment]
@ryankirkman Yes, thank you very much!
