### ISSUE TITLE
[Request] Add bootstrap-sortable

### ISSUE THREAD

**Issue by blade2005** [cdnjs/cdnjs#13141]
**Library name**: bootstrap-sortable
**Git repository url**: https://github.com/drvic10k/bootstrap-sortable
**npm package name or url:** https://www.npmjs.com/package/bootstrap-table
**License**: MIT
**Official homepage**: https://github.com/drvic10k/bootstrap-sortable

**Comment by ole1986** [comment]
The npm package location does not actually match.

**Comment by blade2005** [comment]
Not sure how I missed that but they've got an open issue on this for getting that done. https://github.com/drvic10k/bootstrap-sortable/issues/119

**Comment by ole1986** [comment]
This npm packages iis not available. But luckily package.json can deal with git repos. So I used

`"bootstrap-sortable": "git://github.com/drvic10k/bootstrap-sortable.git#0df36e981d102963dd08ac3db8b247e00286600d"` 

in package.json to fetch it

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
