### ISSUE TITLE
Non-existent version of britecharts

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13147]
Originally reported at https://twitter.com/golodhros/status/1057372403821498368

It seems that cdnjs has a version of britecharts available that the library itself has not even released: https://cdnjs.com/libraries/britecharts

On cdnjs version 3.0.0 is available but on the britecharts repository there is no 3.0.0 release yet: https://github.com/eventbrite/britecharts/releases

**Comment by xtuc** [comment]
Closing for now
