### ISSUE TITLE
Add These fonts.

### ISSUE THREAD

**Issue by CitizenFoffie** [cdnjs/cdnjs#13144]
Kremlin Font (dafont.com)
Propaganda font! https://www.dafont.com/propaganda.font

**Comment by MattIPv4** [comment]
@CitizenFoffie Hi there, we don't directly just host font files. I would suggest contacting the author of the font and asking them to create a css file to wrap the font so it can be easily used on the web. Once the css has been made and published, it can be requested here if it falls under the requirements.

**Comment by CitizenFoffie** [comment]
if you download it you can use this
@font-face {
font-family: propaganda;
src: url("fonts/propaganda.ttf"); font-style: normal;
font-weight: 100;
}
