### ISSUE TITLE
Logging, processing and access

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13152]
Hiya,

Another user suggestion from twitter: https://twitter.com/konklone/status/1073792201618935808

I think is definitely something worth doing; Declaring what logs cdnjs stores, what processing if any is done to the logs and who ultimately has access to them.

**Comment by PeterDaveHello** [comment]
@MattIPv4 we have no logs, only Cloudflare has the logs.

**Comment by MattIPv4** [comment]
@PeterDaveHello Is it worth putting a single line regarding this on the about page for clarity and to answer future enquiries?

**Comment by PeterDaveHello** [comment]
@MattIPv4 I don't really know, as I discussed with Ryan & Thomas very long time about fetching the logs, for furthur analytics, but without no furthur updates for years, so I'm not sure.

**Comment by MattIPv4** [comment]
Ah okay.
@ryankirkman / @thomasdavis any comments or thoughts regarding the above? Do you think a statement on the site about page regarding what we log (nothing, all CF) would be good?

**Comment by xtuc** [comment]
Closing for now. Feel free to re-open the discussion if that's something we would want
