### ISSUE TITLE
plotly.min.js 1.43.1 is broken

### ISSUE THREAD

**Issue by IvanJosipovic** [cdnjs/cdnjs#13168]
The minified version of plotly.js 1.43.1 is broken.
https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.43.1/plotly.min.js

**Comment by IvanJosipovic** [comment]
I get a 404. It does appear to be related to #13166 as it only occurs when I'm on VPN.

![image](https://user-images.githubusercontent.com/9521987/50405527-cdab6380-076a-11e9-9d38-a3ea622a07c2.png)

**Comment by MattIPv4** [comment]
@IvanJosipovic Could you possibly post this on that issue for me so that it is all centralised?
