### ISSUE TITLE
design-system using hard URLs for assets

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13164]
As reported on twitter by a user: https://twitter.com/fuzzfreecom/status/1076087757162852353

It appears that the lightning design system css files are using hard URLs (`/assets/images/...`) to access some of their assets instead of relative paths (`../images/...`).

https://cdnjs.cloudflare.com/ajax/libs/design-system/2.7.5/styles/salesforce-lightning-design-system.css

This is, as would be expected, causing issues as these assets don't load when the css is accessed through cdnjs.

**Comment by xtuc** [comment]
Tracking in https://github.com/salesforce-ux/design-system/issues/595
