### ISSUE TITLE
[Request] Add quicklink

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#13173]
**Library name:** quicklink
**Git repository url:** https://github.com/GoogleChromeLabs/quicklink
**npm package name or url** (if there is one): http://npmjs.com/package/quicklink
**License (List them all if it's multiple):** [Apache-2.0](
https://github.com/GoogleChromeLabs/quicklink/blob/master/LICENSE)
**Homepage**: None

**Comment by chrisblakley** [comment]
I'm also looking to have this library available on CDNJS.

**Comment by xtuc** [comment]
Would you mind sending a PR to add it? see Contributing.md files in the repo.

**Comment by xtuc** [comment]
Also why was that a high priority?

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/quicklink
