### ISSUE TITLE
Missing 404 twitter-bootstrap/3.4.0 

### ISSUE THREAD

**Issue by freemstr** [cdnjs/cdnjs#13177]
These are missing according to vs2017 library manager and verified to be missing in browser:
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.0/css/bootstrap-theme.css.map https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.0/js/npm.js
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.0/css/bootstrap-theme.min.css.map
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.0/css/bootstrap.min.css.map

**Comment by MattIPv4** [comment]
Hi @freemstr this appears to be you experiencing the issue described in #13166 
Please post your situation in there, following the format I recently posted there with all the correct headers so we can continue investigating this.

I will close this issue to keep everything tidy and centralised.
