### ISSUE TITLE
Update datepicker to latest version

### ISSUE THREAD

**Issue by echolet** [cdnjs/cdnjs#13178]
datepicker (https://cdnjs.com/libraries/datepicker) isn't being updated properly: it's stuck at version 0.6.5, while the latest release is 1.03 (https://github.com/fengyuanchen/datepicker)

**Comment by xtuc** [comment]
the bot likely pushed new version since. Please let us know if the issue persists, closing for now

**Comment by MattIPv4** [comment]
Yes, it is still on 0.6.5.
