### ISSUE TITLE
jQuery source map missing

### ISSUE THREAD

**Issue by daservajesus** [cdnjs/cdnjs#13175]
According to the jQuery repository details on CDNJS the listed resources should be available: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.slim.min.map

This file now returns a 404 error.

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.0/jquery.slim.min.map another 404

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.slim.min.map also returns a 404

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.slim.min.map is 404

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.min.map again 404

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.slim.min.js 404

**Comment by PeterDaveHello** [comment]
@daservajesus thanks for reporting, let's move to #13165 or #13166

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.slim.js
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.slim.min.map 

both of those are also 404

**Comment by daservajesus** [comment]
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.2/jquery.min.map = 404

**Comment by MattIPv4** [comment]
@PeterDaveHello Yeah I can access these files so is #13166 
Will close this to keep it all centralised.

@daservajesus If you get the 404 issues again on these files, please post the response headers and the URL requested to #13166 to help with us fixing this issue.
