### ISSUE TITLE
Instructions to start server cdnjs locally

### ISSUE THREAD

**Issue by jayaprabhakar** [cdnjs/cdnjs#13185]
The Readme.md file says "We fully support https, SPDY, http/2.0, and SRI. These will boost and secure your website with zero configuration. ".

However, I don't see the source code or server (nginx, httpd, haproxy or others) config.

Is it possible to point out how to set up my own server?

**Comment by Glennmen** [comment]
@jayaprabhakar I think you are looking for this, it contains the source code for the website and API: https://github.com/cdnjs/new-website

**Comment by jayaprabhakar** [comment]
I am not sure if that is right. I think the new-website's mainSite starts the webserver that serves the html page of cdnjs.com website, and apiServer provides a mapping from the packagename to the complete url like https://cdnjs.cloudflare.com/ajax/libs/...

**Comment by Glennmen** [comment]
@jayaprabhakar You asked how to setup your own server, not sure what server you are referring too then.

**Comment by xtuc** [comment]
Clone this repository and serve it statically through a web server.
