### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by tazotodua** [cdnjs/cdnjs#13182]
1) on this url:
https://cdnjs.com/libraries/animations

the author link should better to be replaced with  

https://web.archive.org/web/20150607104307/http://www.cloud-eight.com/github/animations/

or mark it as abandoned project, because it is same as AnimateCss

2) also, here 
https://cdnjs.com/libraries/animateplus
author url is broken, and is shown like:
_**https://git**+https/github.com/bendc.git_

i've seen similar things on many other pages, where before the url, some prefix is added automatically..

**Comment by MattIPv4** [comment]
Hi @tazotodua 

The issue with animateplus appears to be a bad package.json in the cdnjs repository as it specifies git+ before a https git url. https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/animateplus/package.json#L8

I have made a PR that should fix this issue https://github.com/cdnjs/cdnjs/pull/13184

**Comment by MattIPv4** [comment]
@PeterDaveHello What do you think is best for the first issue reported here? Should we place the web archive link in the package.json or simply remove the author URL all together or even just leave the dead one?

**Comment by PeterDaveHello** [comment]
@MattIPv4 I prefer to remove it.

**Comment by MattIPv4** [comment]
Resolved in https://github.com/cdnjs/cdnjs/pull/13184 and https://github.com/cdnjs/cdnjs/pull/13186

**Comment by PeterDaveHello** [comment]
Let's close it!

**Comment by PeterDaveHello** [comment]
Oops, the git repo is another issue

**Comment by PeterDaveHello** [comment]
@MattIPv4 the url is not wrong, an upgrade of the parser will fix it :)

**Comment by MattIPv4** [comment]
@PeterDaveHello Hm okay, all the other git repo examples I could find in libs didn't use `git+`. Looks like you've updated the parser, thanks :)

**Comment by PeterDaveHello** [comment]
@MattIPv4 we prevent to use it long time before, see reference here please: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
