### ISSUE TITLE
Incorrect unicode handling

### ISSUE THREAD

**Issue by bitwiseman** [cdnjs/cdnjs#13191]
As reported in https://github.com/beautify-web/js-beautify/issues/1608

Compare this: 
https://raw.githubusercontent.com/beautify-web/js-beautify/v1.8.9/js/lib/beautifier.min.js
https://cdn.rawgit.com/beautify-web/js-beautify/v1.8.9/js/lib/beautifier.min.js
https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.8.9/beautifier.min.js

In the regular expression in question:
```js
// githubusercontent
e.identifier=new RegExp("[$@A-Z_a-zªµºÀ-ÖØ-öø-ˁˆ-ˑˠ-ˤˬˮͰ-ʹͶͷͺ-ͽΆ...")
// cdn.rawgit.com
e.identifier=new RegExp("[$@A-Z_a-zªµºÀ-ÖØ-öø-ˁˆ-ˑˠ-ˤˬˮͰ-ʹͶͷͺ-ͽΆ...")
// cdnjs
e.identifier=new RegExp("[$@A-Z_a-zÂªÂµÂºÃ€-Ã–Ã˜-Ã¶Ã¸-ËË...")
```

Not sure what is causing this.

**Comment by MattIPv4** [comment]
Looking at the raw file we have https://raw.githubusercontent.com/cdnjs/cdnjs/master/ajax/libs/js-beautify/1.8.9/beautifier.min.js the regex appears to be correct so this is likely an issue with how the file is being served?

@PeterDaveHello Any ideas about this or do we need Ryan/Cloudflare as it's a server issue?

**Comment by MattIPv4** [comment]
See also https://github.com/cdnjs/cdnjs/issues/13195#issue-396190824 which appears to be the same issue on another file.

**Comment by MattIPv4** [comment]
Possibly related to https://github.com/cdnjs/cdnjs/issues/12756 where charset isn't being set in the Content-type header?

**Comment by MattIPv4** [comment]
Cloudflare are now looking into this, I will post further updates here as I get them.

**Comment by bitwiseman** [comment]
@MattIPv4 
I worked around the issue for my library but replacing the unicode characters with their ascii representations in JavaScript.  So, you won't be able to use my library to test the problem.

**Comment by MattIPv4** [comment]
@bitwiseman 1.8.9 linked above is still the same though? So we can still use that to test?

**Comment by bitwiseman** [comment]
@MattIPv4 
Ah, yes, of course. 😄

**Comment by simon-says** [comment]
@MattIPv4 / @bitwiseman this should now be resolved 👍 - tested on https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.8.9/beautifier.min.js as an example and looks correct.

**Comment by MattIPv4** [comment]
@simon-says Can confirm it looks to be correct now. Thank you for getting this resolved :)
