### ISSUE TITLE
[Request] Add json2csv

### ISSUE THREAD

**Issue by extend1994** [cdnjs/cdnjs#13197]
**Library name:** json2csv
**Git repository url:** https://github.com/zemirco/json2csv
**npm package name or url** (if there is one): https://www.npmjs.com/package/json2csv
**License (List them all if it's multiple):** [MIT](
https://github.com/zemirco/json2csv/blob/master/LICENSE.md)
**Homepage**: http://www.mircozeiss.com/json2csv/

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/json2csv
