### ISSUE TITLE
Incorrect jQueryValidate message arabic translate file

### ISSUE THREAD

**Issue by messaddek** [cdnjs/cdnjs#13195]
Hello,

I encounter an error while using the file : "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/localization/messages_ar.js". The error is in the line 24.

![error jquery-validate-message-arabic](https://user-images.githubusercontent.com/17082665/50728020-03b1f580-1124-11e9-9bde-948dd0910ed1.jpg)

Regards

**Comment by MattIPv4** [comment]
This issue appears to be an extension of a known issue reported in #13191
