### ISSUE TITLE
Access to XMLHttpRequest at 'https://xxxxx' from origin 'http://localhost:8080' has been blocked by CORS policy

### ISSUE THREAD

**Issue by gruaig** [cdnjs/cdnjs#13210]
Hi

2019-01-11 10:03:13.128 16854-16854/? I/chromium: [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://xxxxx' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: http://localhost:8080/ (0)

We use Ionic cordova. 
This happens intermittently across may browsers. We are also using a cordova Android app.  Switching from CF to direct, this issue stops, so its something to do with Cloudflare. We have made no changes in 3 weeks to our infrastructure or application. We believe the problem started two days ago.

**Comment by MattIPv4** [comment]
@simon-says is it possible that the issue we had over new years is recurring again?

**Comment by gruaig** [comment]
I can help you with what ever info you need. I'm online for the next few hours. Thanks

**Comment by MattIPv4** [comment]
@gruaig If you could, full request/response headers for failed ones would be great so we can get the cf ray id etc.

**Comment by gruaig** [comment]
Yeah sure no problem. 
Request URL: https://uk.*******.app/edge/rest/player/maindata
Request Method: POST
Status Code: 400


cf-ray: 4978ff1c1cfb6a3d-LHR
content-length: 0
date: Fri, 11 Jan 2019 17:10:23 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
set-cookie: __cfduid=d73594bc7253216359b93cc9f31df7b261547226623; expires=Sat, 11-Jan-20 17:10:23 GMT; path=/; domain=.******.app; HttpOnly; Secure
set-cookie: __cflb=508133050; Secure; path=/; expires=Sat, 12-Jan-19 16:10:23 GMT; HttpOnly
status: 400

Thank you

**Comment by noxiousmobile** [comment]
I have the same issue going on, Access-Control-Allow-Origin: * missing in my request header. 
Looks like this issue appeared recently :/

**Comment by MattIPv4** [comment]
@gruaig Those headers appear to be for a post request to your own site, not a get request to a cdnjs resource?

**Comment by MattIPv4** [comment]
Just as a general update: I have emailed our contact at Cloudflare directly to alert them to this issue and have also re-opened the original support ticket from this issue when it occurred during the Christmas/new years period.

**Comment by noxiousmobile** [comment]
I have a method missing from my response. I am using a Request method: OPTIONS but I don't see it in my response header which has this response : 
Access-Control-Allow-Methods: GET, POST, DELETE, PUT

**Comment by MattIPv4** [comment]
@noxiousmobile is this an issue you are having with cdnjs? Why would you ever be making an OPTIONS request to our resources?

**Comment by MattIPv4** [comment]
@gruaig any update regarding this? The header dump you gave was not to a cdnjs rssource?

**Comment by noxiousmobile** [comment]
@MattIPv4 my client sents two requests looks like its preflight. So first one is post OPTIONS and seccond one is POST. In the seccond one the header is missing all the access-controll-allow stuff, they are all strip out from the response so i get a CORS error.

**Comment by MattIPv4** [comment]
@noxiousmobile Why are you sending anything but a GET request to cdnjs?

**Comment by gruaig** [comment]
Hi, We haven't changed anything for weeks but now this request returns a 400. Can we please have a update on the problem. We have upgraded to enterprise.

**Comment by simon-says** [comment]
@gruaig this doesn't look like an issue related to cdnjs - I think you contacted me directly on Friday about this. The best thing to do is contact Cloudflare support directly and give the full request & response headers to them.

Note the response you're receiving there is a HTTP 400 - which means the client request was invalid in some way. In any case, the support team can probably help figure out whether that response is correct and if it's coming from Cloudflare or the origin service.

@MattIPv4 I agree this doesn't look CDNJS related so I think you can close this.
