### ISSUE TITLE
Add missing minifed files for CodeMirror library

### ISSUE THREAD

**Issue by Chi-teck** [cdnjs/cdnjs#13226]
For instance, there is no fullscreen.min.css in the following directory.
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/codemirror/5.43.0/addon/display/

**Comment by MattIPv4** [comment]
@Chi-teck Hi there, we pull codemirror from npm and looking at the GitHub repository for codemirror `fullscreen.min.css` is not a file that they have and so we'd obviously also not have it: https://github.com/codemirror/CodeMirror/tree/master/addon/display

If you wish for codemirror to publish this file, please take it up with them :)

**Comment by Chi-teck** [comment]
@MattIPv4 Can you explain how it works right now? CodeMirror itself [does not provide](https://github.com/codemirror/CodeMirror/issues/5752) minified files at all but _cdnjs_ offers them for most files (`fullscreen.min.css` is just an exception).

**Comment by MattIPv4** [comment]
@PeterDaveHello Where exactly are the minfied files coming from? npm doesn't have them, nor does the lib?

**Comment by PeterDaveHello** [comment]
@MattIPv4 we minify files when there is no minified file of it, though we prefer to have it from upstream, to have better integrity and better specific optimization.

**Comment by xtuc** [comment]
As @PeterDaveHello said, that should probably be upstream
