### ISSUE TITLE
Proposal for new additions to the CDN

### ISSUE THREAD

**Issue by BrightSkyz** [cdnjs/cdnjs#13221]
Hello, @MattIPv4 told me to make this issue so I am. I am currently working on a new system for CDNJS to add support for any NPM package to the CDN. This includes full backward compatibility with current URLs to libraries on CDNJS. I wanted to know if you'd like this/like me to make a repository on GitHub with this so that you can implement it.

The way it works is when a package is requested and it doesn't exist, it fetches the package from npmjs and then extracts the files, it will then serve the file if it exists. Also to save space, it will delete the versions of packages not used after 1 day. (this can be changed depending on amount of available space)

**Comment by BrightSkyz** [comment]
I have finished creating it, let me know if you'd like to see it. (I have a live demo/and the source code)

**Comment by PeterDaveHello** [comment]
Thanks for being interested in contributing!

I assume this feature will look like unpkg or jslidevr npm service? By the current structure of this project, we're not likely to do so, if we'll like to do so, it'll be a separated system and has its own origin server.

It'll be great to have that almost real-time updates for the libraries, but if that's the idea I'm not sure if worth it to do so, when there are at least two services are already doing the same thing for a while, the pros and cons I can list here to be compared:

Pros:
- update very fast
- no manual confirmation needed for new version releases
- no need to wait for Cloudflare to do anything want if we host that origin server

Cons:
- new infra needed, and we need to maintain an additional server
- cache hit rate may be lower as a same library can be hosted on both old and new system
- we need to implement whitelist or blacklist in case of malicious packages and abuse
- not predictable of disk usage

Currently, everything is committed into the git repo, and Cloudflare pulls the updates to "their" origin server for cdnjs.cloudflare.com, then serve the assets behind their global CDN. Not like the proposed feature, the files are almost never deleted unless there are some copyrights or law issues.

Let me know what do you think, thanks a lot!

BTW, we still have other issues need help if you'd like to involve :)

**Comment by BrightSkyz** [comment]
I just read over your message. It would be similar to unpkg or jsdelivr. The size of the the cache can be maintained by writing something to say that if a new library (or version of a library) is requested and the cache is at its max, it can purge the specific version of a the library that hasn't been requested.

For example: (Lets say the max size for the cache is 8 MB)
1. foo@1.0.6 is requested (size is 6 MB)
2. foobar@1.0.0 is requested (size is 1 MB)
3. bar@4.5.3 is requested (size is 4 MB)

In the example above, when bar@4.5.3 is requested, foo@1.0.6 is removed from the cache since it is capped at 8 MB.

- As for new infrastructure, I have a dedicated server which you can trial it on to see how it runs.
- About the cache hit rate, using rsync to sync all the servers together would work nicely to keep all the servers in sync with the same cache.
- Really easy to implement that with the way I created the system (you can easily add code to check a json file for a package to see if it needs to be blocked)
- The disk usage would be able to be capped (if the system I described above is implemented)

**Comment by theel0ja** [comment]
Isn't this already implemented with [unpkg.com](https://unpkg.com/)?

**Comment by PeterDaveHello** [comment]
Yeah I think that's already done by unpkg and jsdelivr, and I don't assume we'll do the same thing, there are pros and cons, though the maintenance effort is high, I believe well organized libraries instead of raw contents would be more user friendly.

**Comment by xtuc** [comment]
@BrightSkyz can you please share the demo?

**Comment by BrightSkyz** [comment]
I'll need to dig it up @xtuc, do you have twitter where I can message you?

**Comment by xtuc** [comment]
As discussed, that's no something we will add to cdnjs for now.
