### ISSUE TITLE
elFinder has not been updated, the latest is 2.1.47

### ISSUE THREAD

**Issue by nao-pon** [cdnjs/cdnjs#13227]
@PeterDaveHello

elFinder 2.1.46 is released on January 14, 2019. However, cdn.js keeps the latest 2.1.43.

Thanks.

**Comment by PeterDaveHello** [comment]
@nao-pon i'll take a look, thanks

**Comment by nao-pon** [comment]
@PeterDaveHello I will inform you that we have released elFinder 2.1.47.

Thanks.

**Comment by PeterDaveHello** [comment]
@nao-pon thanks
