### ISSUE TITLE
4.6.3/ol3 [Not Found]

### ISSUE THREAD

**Issue by carrbrpoa** [cdnjs/cdnjs#13234]
NOT FOUND for:
https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.3/ol-debug.js
https://cdnjs.cloudflare.com/ajax/libs/ol3/4.6.3/ol-debug.css

**Comment by MattIPv4** [comment]
Both files are present in our repo: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ol3/4.6.3

cc @PeterDaveHello Anything you can do or is this going to be a server config issue?

**Comment by PeterDaveHello** [comment]
@MattIPv4 not the same issue #13165 ?

**Comment by MattIPv4** [comment]
@PeterDaveHello Actually could be, let me dig through what was said last time. I do recall someone saying the CORS issue was due to files 404-ing.

**Comment by MattIPv4** [comment]
@carrbrpoa It looks as if this is actually part of the #13165 issue, please could you post there with full request/response headers of the failed request.
