### ISSUE TITLE
Intermittent 404 for twitter-bootstrap@3.3.7

### ISSUE THREAD

**Issue by TristanApc** [cdnjs/cdnjs#13236]
CDNJS link: https://cdnjs.com/libraries/twitter-bootstrap/3.3.7

Hi, we're getting some 404 error while fetching twitter-bootstrap 3.3.7.

We know that this url will intermittently fail: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css.map

and maybe there's more files failing.

**Comment by MattIPv4** [comment]
@TristanApc Please post full request/response headers along with the resource URL in #13165 when you experience a failed request.
