### ISSUE TITLE
[Request] react-extras

### ISSUE THREAD

**Issue by Martin-Pitt** [cdnjs/cdnjs#13249]
**Library name**: react-extras
**Description**: "Useful components and utilities for working with React"
**Git repository URL**: https://github.com/sindresorhus/react-extras.git
**npm package name or url** (if there is one): https://www.npmjs.com/package/react-extras
**License**: MIT

---

If you came to this issue and would like to see this added to cdnjs you are welcome to take this on and submit a pull request, see below for details.
I'm just leaving it on the backlog for now as I'm busy and it's low priority for myself, but I think the maintainers would appreciate help 👍 

---

**Please take a read of their [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also their [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

**Comment by MattIPv4** [comment]
I won't send my normal response as you've nailed it yourself. Thanks :)
