### ISSUE TITLE
Framework7 4.0.x release

### ISSUE THREAD

**Issue by nschermer** [cdnjs/cdnjs#13252]
Framework7 now has a 4.0.x release which is not available in cdnjs and a 3.6.x branch for older devices. Probably better to remove the 4.0.0 beta releases from cdnjs.

**Comment by nschermer** [comment]
FYI, if the individual components css/js files are not included in cdnjs, the .bundle files are sufficient. See https://framework7.io/docs/package.html for more information.

This also is true for the older 3 releases since 3.4 where the component files are required for the -lazy files.

**Comment by MattIPv4** [comment]
@PeterDaveHello The lib appears to be configured to auto update: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/framework7/package.json#L34-L45

Looking at the repo, 4.0.1 is available in the repo but auto update hasn't picked it up? https://github.com/framework7io/framework7/blob/master/packages/core/package.json

**Comment by PeterDaveHello** [comment]
Added in 7c920ce00cd8b12899728bf4a78180967a330ea8
