### ISSUE TITLE
jsrender and jsviews not updating

### ISSUE THREAD

**Issue by BorisMoore** [cdnjs/cdnjs#13257]
@PeterDaveHello 
jsviews and jsrender released v1.0.2 three days ago. (https://npmjs.com/package/jsrender and https://npmjs.com/package/jsviews)

They were auto-updated to cdnjs:
-  https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jsrender/1.0.2.  (by PeterBot) 
- https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jsviews/1.0.2.  (by PeterBot)

But they are not showing up on the cdn.

https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jsrender says "Cannot retrieve the latest commit at this time." (and similar for jsviews).

I don't believe there were any significant directory structure changes or suchlike that would explain the problem. v1.0.1 was similar and did autoupdate correctly...

Any help appreciated...

**Comment by MattIPv4** [comment]
@BorisMoore Hey there!

All the files are live on our CDN: https://cdnjs.cloudflare.com/ajax/libs/jsrender/1.0.2/jsrender.min.js should you wish to access them directly to use them.

It does appear however that our front site has not updated at present: https://cdnjs.com/libraries/jsrender
I do apologise for this, I will let @PeterDaveHello look into this.

**Comment by MattIPv4** [comment]
@PeterDaveHello Has the cdnjs.com site stopped updating completely? I and others have noticed that the new bootstrap versions are not listed either but are live on the CDN?

**Comment by PeterDaveHello** [comment]
@MattIPv4 fixing now and should be fixed in the next hour.

**Comment by PeterDaveHello** [comment]
@BorisMoore fixed, thanks for reporting.

**Comment by BorisMoore** [comment]
Excellent. Thanks for fixing this!
