### ISSUE TITLE
Bootstrap update issues

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13258]
There are two key issues with bootstrap updating on cdnjs currently:

1. 4.3.0 has been added to the repository (and mirrored to cdnjs.cloudflare.com) but is not live on the cdnjs.com site?
https://cdnjs.com/libraries/twitter-bootstrap / https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/twitter-bootstrap/4.3.0

2. 4.3.1 and 3.4.1 have both been released on npm two days ago but have still not been updated on the repo.
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/twitter-bootstrap / https://www.npmjs.com/package/bootstrap?activeTab=versions

As reported on Twitter by ChrisMCharles and others on our Discord community.

**Comment by PeterDaveHello** [comment]
@MattIPv4 1. server issue, fixing now
2. the bot hangs, restarted, running now
they should be both fixed in the next hour

**Comment by MattIPv4** [comment]
@PeterDaveHello Awesome, thank you!

**Comment by PeterDaveHello** [comment]
@MattIPv4 First issue fixed, the second one needs more time.

**Comment by MattIPv4** [comment]
@PeterDaveHello Ah okay.

**Comment by PeterDaveHello** [comment]
@MattIPv4 should be fixed now.

**Comment by MattIPv4** [comment]
Looks good, everything is now present on cdnjs.com
