### ISSUE TITLE
Data collection by cdnjs with regards to GDPR?

### ISSUE THREAD

**Issue by ErinPo** [cdnjs/cdnjs#13272]
What data does cdjns collect? IP addresses, userAgent strings, ...? For how long are they stored? Is cdnjs privacy shield certified? Is there some standardized text website owners can add to their privacy policy in order to properly inform their visitors about the data processing taking place as a result of loading resources from CDNJS?

**Comment by PeterDaveHello** [comment]
@ErinPo cdnjs collects nothing, even the access log. cdnjs.cloudflare.com is directly hosted by Cloudflare.

**Comment by MattIPv4** [comment]
Yup, we log nothing and have no access to the logs that Cloudflare have for cdnjs.cloudflare.com

Please refer to Cloudflare's documents and policies for what information they may store :)

**Comment by MattIPv4** [comment]
Just as an update, I have reached out to Cloudflare to check if there is a specific page or section of their policies that cdnjs users should be referring to. I will post further updates here 😄

**Comment by MattIPv4** [comment]
cc @AmNotADev

**Comment by MattIPv4** [comment]
@dknecht Please use this as the issue for tracking policy related progress (privacy policy etc) :)

**Comment by MattIPv4** [comment]
cc https://github.com/cdnjs/cdnjs/issues/3439 https://github.com/cdnjs/new-website/issues/7

**Comment by tasuki** [comment]
Any news on this?

**Comment by MattIPv4** [comment]
@tasuki I suggest reading Cloudflare's policies/documentation, as resources are loaded through them (cdnjs.cloudflare.com).

**Comment by tasuki** [comment]
Would you have a link or a summary handy?

**Comment by MattIPv4** [comment]
GDPR: https://www.cloudflare.com/gdpr/introduction/
Privacy Policy: https://www.cloudflare.com/privacypolicy/

**Comment by xtuc** [comment]
Looks like this is resolved, feel free to post new comments if needed.
