### ISSUE TITLE
CORS issue with twitter-bootstrap

### ISSUE THREAD

**Issue by InnovativeInventor** [cdnjs/cdnjs#13281]
![image](https://user-images.githubusercontent.com/20117409/54254810-a7a48c80-452b-11e9-90dd-8b052bea2c82.png)

**Comment by MattIPv4** [comment]
@InnovativeInventor That [file doesn't exist](https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap-grid.min.js) which is why you are getting a CORS error as the 404 page does not return a CORS header.
