### ISSUE TITLE
Bootstrap-Table not updated to v1.14.1

### ISSUE THREAD

**Issue by olafcm** [cdnjs/cdnjs#13288]
Git auto-update for this popular library seems to have failed.
Latest release is 1.14.1: https://github.com/wenzhixin/bootstrap-table/releases
Not available on cdnjs: https://cdnjs.com/libraries/bootstrap-table/1.14.1
Author has no clue: #4212
Used to work.
Thanks for checking 😊

**Comment by MattIPv4** [comment]
cc @PeterDaveHello

**Comment by olafcm** [comment]
Note: also 1.14.2 release was not picked-up

**Comment by olafcm** [comment]
The library was auto-updated (https://cdnjs.com/libraries/bootstrap-table/1.14.2).
Thanks!
