### ISSUE TITLE
vis 4.21.0 content seems old.

### ISSUE THREAD

**Issue by heignamerican** [cdnjs/cdnjs#13282]
https://cdnjs.cloudflare.com/ajax/libs/vis/4.21.0/vis.js
Actually, the url provides `@version 4.20.1-SNAPSHOT`.

https://github.com/almende/vis/commits/v4.21.0
Maybe, this file was generated at `2017-10-12T12:23:36Z`, but `2017-10-12T12:43:13Z` is newest.

**Comment by PeterDaveHello** [comment]
@heignamerican it's added by our bot, which means it's the latest when it's added, that must came from upstream and is something we can't do anything with it. We generate SRI for every js & css files, it's not a good idea to touch any hosted files.

**Comment by PeterDaveHello** [comment]
@heignamerican it's added by our bot, which means it should be the correct v4.21.0 when it's added, that must come from upstream and is something we can't do anything with it. We generate SRI for every js & css files, it's not a good idea to touch any hosted files.

**Comment by PeterDaveHello** [comment]
So the upstream might regenerates and retag that version after the bot fetched the initially generated one, and this is not a usual pattern, we usually don't touch anything was released as a version, instead, release a new and correct one. I'm not sure what I can help here but explain the reason why it's different.

**Comment by heignamerican** [comment]
I understand. Thank you for the response.

**Comment by PeterDaveHello** [comment]
@heignamerican thanks
