### ISSUE TITLE
[Request] ag-grid 20 and 20.1

### ISSUE THREAD

**Issue by a-teece** [cdnjs/cdnjs#13285]
Is there a reason that the git autoupdate hasn't resulted in these versions being added automatically?

**Comment by MattIPv4** [comment]
@PeterDaveHello Can you look at this?

The cdnjs package.json appears to be correct: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/ag-grid/package.json

The source folder/file structure is the same: https://github.com/ag-grid/ag-grid/tree/master/dist
The source package.json has the correct version number for the new version: https://github.com/ag-grid/ag-grid/blob/master/package.json

**Comment by xtuc** [comment]
The bot added 
```
    Add ag-grid v22.0.0
    Add ag-grid v22.1.0
    Add ag-grid v22.1.1
    Add ag-grid v21.2.2
    Add ag-grid v20.0.0~21.2.1
```
