### ISSUE TITLE
[author] chart.js is not updating

### ISSUE THREAD

**Issue by benmccann** [cdnjs/cdnjs#13290]
We recently released Chart.js 2.8.0: https://www.npmjs.com/package/chart.js

cdn.js is still showing the prior version 2.7.3: https://cdnjs.com/libraries/Chart.js

Perhaps it's the `"files"` reference in https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/Chart.js/package.json? Our package does not include docs anymore.

**Comment by MattIPv4** [comment]
cc @PeterDaveHello

**Comment by xtuc** [comment]
The bot added
```
    Add Chart.js v2.9.3
    Add Chart.js v2.9.0
    Add Chart.js v2.9.1
    Add Chart.js v2.9.2
    Add Chart.js v2.8.0/2.8.0-rc.1
```
