### ISSUE TITLE
Gijgo is not updating

### ISSUE THREAD

**Issue by olafcm** [cdnjs/cdnjs#13295]
Git auto-update for this library seems to have failed.
Latest release is 1.9.13: https://github.com/atatanasov/gijgo/releases
Not available on cdnjs: https://cdnjs.com/libraries/gijgo/1.9.13
Thanks for checking 🙏

**Comment by MattIPv4** [comment]
cc @PeterDaveHello

**Comment by olafcm** [comment]
The library was auto-updated (https://cdnjs.com/libraries/gijgo/1.9.13).
Thanks!
