### ISSUE TITLE
[author] Is it ok to point ajv to ajv-dist package?

### ISSUE THREAD

**Issue by epoberezkin** [cdnjs/cdnjs#13315]
Currently, in order to work with cdnjs ajv includes the bundles into npm package.

It increases the bundle size: https://github.com/epoberezkin/ajv/issues/940

Is it possible to point ajv (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/ajv/package.json) to ajv-dist package on npm https://www.npmjs.com/package/ajv-dist (so I can remove the bundles from ajv package).

**Comment by epoberezkin** [comment]
I understand that could be enough https://github.com/cdnjs/cdnjs/pull/13316 ?

**Comment by xtuc** [comment]
The PR https://github.com/cdnjs/cdnjs/pull/13316 has been closed. closing the issue for now, feel free to continue to comment
