### ISSUE TITLE
[Request] Add material-components-web

### ISSUE THREAD

**Issue by Richienb** [cdnjs/cdnjs#13338]
> I'm creating this request because https://github.com/cdnjs/cdnjs/issues/12944, https://github.com/cdnjs/cdnjs/issues/8289, https://github.com/cdnjs/cdnjs/issues/12435, https://github.com/cdnjs/cdnjs/issues/11282 and https://github.com/cdnjs/cdnjs/pull/11303 have been stale for quite some time despite being `High priority`

Library name: material-components-web
Library description: Modular and customizable Material Design UI components for the web
Git repository url: https://github.com/material-components/material-components-web
npm package name or url (if there is one): https://www.npmjs.com/package/material-components-web
License (List them all if it's multiple): Apache 2.0
Official homepage: https://material.io/components/web/

**Comment by MattIPv4** [comment]
Hi there,

Opening a new issue when there is already an existing issue and PR for the library does not help anyone. You are welcome to chase and help out on the existing issue/PR but creating new ones causes a mess that isn't helpful.
