### ISSUE TITLE
Fortify Issue : https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery.perfect-scrollbar/0.6.13/js/perfect-scrollbar.jquery.min.js  line 2 (Insecure Randomness)

### ISSUE THREAD

**Issue by revathy-umapathy** [cdnjs/cdnjs#13344]
Fortify Issue : https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery.perfect-scrollbar/0.6.13/js/perfect-scrollbar.jquery.min.js  line 2 (Insecure Randomness)

**Comment by MattIPv4** [comment]
Hi there,

Could you possibly explain the issue further?

**Comment by MattIPv4** [comment]
No progress - closing. Please take this up with the library author if further action is required.

**Comment by dmethvin** [comment]
https://community.microfocus.com/t5/Fortify-User-Discussions/HP-Fortify-SCA-erroneous-High-Impact-Insecure-Randomness/td-p/1570662
