### ISSUE TITLE
[Bug] Not updating package es6-tween

### ISSUE THREAD

**Issue by dalisoft** [cdnjs/cdnjs#13359]
Hello @cdnjs and thanks for great service.

My package doesn't updating more than year.

Link to cdnjs: https://cdnjs.com/libraries/es6-tween
Link to NPM: https://www.npmjs.com/package/es6-tween

**Comment by xtuc** [comment]
could you please check that the package configuration in `ajax/libs/NAME/package.json` matches with the contributing.md files. We also recommend to switch to updates using npm, git had some trouble lately.

**Comment by dalisoft** [comment]
As es6-tween not maintained anymore, i will close this issue
