### ISSUE TITLE
mouse left click not follow link on slide image , bugs only on screen laptop via chrome

### ISSUE THREAD

**Issue by AdolfoHerreraB** [cdnjs/cdnjs#13358]
The click on image link on slide  via "mouse left" not working on laptop screen,only works on touch laptop screen  over google chrome.
Only clicking several times on ramdom area is force to follow the link via mouse.
 for all others browsers works fine. 

im usin jquery 1.8.2

**Comment by MattIPv4** [comment]
Hi there @AdolfoHerreraB 

Where are you experiencing this issue?
Is it an issue with the cdnjs website or simply with your usage of the jQuery library?

**Comment by AdolfoHerreraB** [comment]
on principipal slide behind the nav menu.
https://www.24horasqroo.mx/

I'm change touchEnabled=0 directly on the library offline. and now works the mouse left clcik , but i dont  know if its diable the touch on laptop screen , the proofs are with a computer of other person.

**Comment by MattIPv4** [comment]
@AdolfoHerreraB This is not an issue with cdnjs but an issue with the library you are using through cdnjs. Please contact the library author/team directly for support.

**Comment by AdolfoHerreraB** [comment]
its the same
