### ISSUE TITLE
How do you turn run this module without it accessing an external site, 

### ISSUE THREAD

**Issue by sysman64** [cdnjs/cdnjs#13364]
I need to turn off nowrap so that the enter title shows in the month view but when I change the local css it has not effect since it is pulling from an external site.  I see in the fullcalendarview.library.yml file that the link is https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css however I am unsure how to make it look at my server rather than the link

**Comment by MattIPv4** [comment]
@sysman64 You should be able to just load a secondary css file on your webpage with your customisations. This should overwrite the styles defined in the library if they have a high enough power (more specific selector, usage of `!important` etc).

**Comment by sysman64** [comment]
I tried to point the entry in fullcalendarview.library.yml to my customized css, however when I do all of the formatting of the calendar goes away.

**Comment by MattIPv4** [comment]
@sysman64 Why not just have a secondary stylesheet on the page that will change the nowrap property, without changing the library files?

**Comment by MattIPv4** [comment]
No further progress, closing.
