### ISSUE TITLE
[Request] Vuex 3.1.1

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13366]
Hey @PeterDaveHello and others,

Vuex 3.1.1 was released via NPM 11 days ago but @PeterBot has not updated the cdnjs version: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vuex/package.json#L3

I would appreciate this being looked into and resolved for our users who have asked about this. :)

**Comment by GodofHope** [comment]
Hoping you can solve it faster!😉

**Comment by PeterDaveHello** [comment]
This is not a bug.

**Comment by MattIPv4** [comment]
@PeterDaveHello What is the issue here then?

**Comment by MattIPv4** [comment]
Vuex 3.1.1 was released 17 days ago and follows the correct file structure for what is configured in our autoupdate, with the correct files to be picked up by the file map, yet PeterBot hasn't updated it?
