### ISSUE TITLE
update MDBootstrap to 4.8.1 isn't updated

### ISSUE THREAD

**Issue by Martussky** [cdnjs/cdnjs#13369]
MDBootstrap was released 7 days ago and still is not available on cdnjs. Do you have some advice about why it is not showing yet? Do you have a problem with the auto update?

**Comment by mattonit** [comment]
@PeterDaveHello could you please assist us with this issue?

**Comment by PeterDaveHello** [comment]
@mattonit sure thing

**Comment by MattIPv4** [comment]
@PeterDaveHello Again, what is the issue here as 4.8.1 has been released on the git repository that is configured for autoupdate, and the file map still picks up the files correctly?

**Comment by PeterDaveHello** [comment]
@MattIPv4 Again, any version with different file/directory needs a manual review to be added.

**Comment by MattIPv4** [comment]
@PeterDaveHello This doesn't have a new structure from what I can see, that's why I am so confused?

**Comment by PeterDaveHello** [comment]
Any single new file means the new struct.

**Comment by MattIPv4** [comment]
@PeterDaveHello Ah right okay, could we possibly improve PeterBot so this can be automated without the need for manual intervention?

**Comment by PeterDaveHello** [comment]
@MattIPv4 pull requests are always welcome.
