### ISSUE TITLE
Mapbox automated updated from NPM not working, v0.54 not available on CDNJS

### ISSUE THREAD

**Issue by jpritchard-isl** [cdnjs/cdnjs#13372]
Noticed Mapbox-GL has been update to 0.54, but not available on CDNJS yet, appear to have been updated on NPM nearly 1 month ago.

**Comment by MattIPv4** [comment]
@PeterDaveHello There have been quite a few reports lately of libraries not being updated, could you look into this please?

**Comment by MattIPv4** [comment]
@PeterDaveHello You have removed bug from this too, but there are multiple versions published on NPM that PeterBot has not picked up, the file structure in the package remains the same, and the file map still picks the right files?

**Comment by PeterDaveHello** [comment]
Not being picked up is not equal to bug, as I explained, any version with different file/directory needs a manual review to be added.
