### ISSUE TITLE
Make PeterBot more friendly with errors

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13388]
## Idea

It would be lovely to update @PeterBot so that it was more friendly to new users who have received an error from the CI.

Displaying the error the CI has produced in the review would be great and even suggesting how to fix the error in simple English would also be great to improve the usability.

 - Display error in the review
 - Suggest simple fixes for error

## Relevant Scripts

CI Script: https://github.com/cdnjs/cdnjs-drone-ci/blob/master/cdnjs.sh
PR Review Script: https://github.com/PeterDaveHello/Drone-GitHub-status-report-bot/blob/master/main.sh

**Comment by xtuc** [comment]
PeterBot isn't running anymore, but I will keep that in mind for the future bot
