### ISSUE TITLE
SRI SHA 384/512

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13384]
Following a [user suggestion on the community forum](https://cdnjs.discourse.group/t/sri-sha-384-512-support/79), I believe that we should implement SHA-384 and SHA-512 alongside the existing SHA-256 in the SRI values that we provide to users and use.

```
<!-- Current format -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
 
<!-- Suggested format -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo= sha384-vk5WoKIaW/vJyUAd9n/wmopsmNhiy+L2Z+SBxGYnUkunIxVxAv/UtMOhba/xskxh sha512-bnIvzh6FU75ZKxp0GXLH9bewza/OIw6dLVh9ICg0gogclmYGguQJWl8U30WpbsGTqbIiAwxTsbe76DErLq5EDQ==" crossorigin="anonymous"></script>
```

**Comment by MattIPv4** [comment]
Relevant code looks to be https://github.com/cdnjs/cdnjs/blob/master/build/packages.json.js#L205-L237

**Comment by drewfreyling** [comment]
I'm in favour of just offering up the SHA-512 values since it is:

- Less bytes in the browser
- All browsers (currently) must be support 256, 384 and 512 (https://w3c.github.io/webappsec-subresource-integrity/#hash-functions)

If at some point we get fragmented browser support than I think providing multiple hashes makes sense.

**Comment by PeterDaveHello** [comment]
dup https://github.com/cdnjs/cdnjs/issues/11123

**Comment by MattIPv4** [comment]
@PeterDaveHello Completely missed that, I had only searched for 512.

**Comment by PeterDaveHello** [comment]
Let's just move to #11123, BTW, I don't think it's a beginner issue.
