### ISSUE TITLE
Allow PeterBot to automatically rebase PRs

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13389]
## Idea

Currently, if the pull request is based off an old copy of the master branch, the CI/@PeterBot will simply raise an error to the user asking them to update their branch by rebasing against master.

For new users who are simply wanting to contribute by adding a library, this can be very overwhelming due to the huge size of cdnjs @ HEAD.

It would be great if instead of raising this error to the user, @PeterBot automatically rebased the PR, only raising an error if the human intervention is required due to an automatic rebase failing.

 - Rebase PRs instead of giving an error to the user
 - Only produce an error if automatic rebase fails

## Relevant Scripts

CI Script: https://github.com/cdnjs/cdnjs-drone-ci/blob/master/cdnjs.sh
PR Review Script: https://github.com/PeterDaveHello/Drone-GitHub-status-report-bot/blob/master/main.sh

**Comment by xtuc** [comment]
is this still wanted with the future cdnjs/packages?

**Comment by MattIPv4** [comment]
Nope. I’m not sure why it was ever a requirement honestly. I’m happy for PRs in the new repo to be messy, as long as maintainers always squash and merge, which we can enforce with repo settings.
