### ISSUE TITLE
Version mismatch of vue-router

### ISSUE THREAD

**Issue by breeze9527** [cdnjs/cdnjs#13404]
vue-router@3.0.3 and vue-router@3.0.4 have same content,
and version mismatch since vue-router@3.0.4
[source of vue-router@3.0.3](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vue-router/3.0.3/vue-router.min.js)in cdnjs repository
[source of vue-router@3.0.4](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vue-router/3.0.4/vue-router.min.js)in cdnjs repository

**Comment by MattIPv4** [comment]
Can confirm, looks like 3.0.7 contains the 3.0.6 files: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vue-router/3.0.7/vue-router.min.js
The files at source are correctly versioned: https://github.com/vuejs/vue-router/commit/f69b2c158e67cfca39dbf4ba7b0fe2299e89c88a

cc @PeterDaveHello

**Comment by breeze9527** [comment]
Any response?

**Comment by PeterDaveHello** [comment]
See:
https://github.com/vuejs/vue-router/blob/v3.0.4/dist/vue-router.min.js
https://github.com/vuejs/vue-router/blob/v3.0.7/dist/vue-router.min.js
