### ISSUE TITLE
jquery.i18n.parser.min.js seems broken or badly minimized

### ISSUE THREAD

**Issue by ssuess** [cdnjs/cdnjs#13411]
`https://cdnjs.cloudflare.com/ajax/libs/jquery.i18n/1.0.5/jquery.i18n.parser.min.js` seems to be broken. I minimized the source file `https://cdnjs.cloudflare.com/ajax/libs/jquery.i18n/1.0.5/jquery.i18n.parser.js` myself and it works, but the version downloaded from your site did not.

**Comment by MattIPv4** [comment]
cc @PeterDaveHello

**Comment by xtuc** [comment]
Likely a bad version, please use a later one.
