### ISSUE TITLE
react-dom doesn't have 16.9 version

### ISSUE THREAD

**Issue by monkindey** [cdnjs/cdnjs#13424]
https://cdnjs.com/libraries/react-dom

![image](https://user-images.githubusercontent.com/6913898/62855303-7ae7e180-bd24-11e9-95e2-2c3ea0a7761c.png)

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by frehner** [comment]
@MattIPv4 I think `react-dom` is already a part of CDNJS, and also has an auto-update package.json as part of it.

It just looks like it hasn't picked up the latest `16.9` release.  Which is weird, because it looks like it picked up on all the previous releases and even the `16.9.0-alpha` release.

**Comment by MattIPv4** [comment]
Yeah, it may be that the package structure has changed, which will require a manual PR/commit of the changed version.

**Comment by frehner** [comment]
I just downloaded the tarballs from npm, and the file and folder structure between `16.8.6` and `16.9.0` are the same. From what I can tell at least... :D 

![Screen Shot 2019-08-12 at 3 01 44 PM](https://user-images.githubusercontent.com/3054066/62898175-2471a780-bd12-11e9-8cb8-5f7956af88ba.png)

**Comment by MattIPv4** [comment]
@frehner Are all the files within cjs & umd identical also? (If anything changes [excluding contents of files] the bot won't auto-update)

**Comment by frehner** [comment]
It looks like `16.8.6` had three additional files in each folder (so 6 total: 3 in `umd` and 3 in `cjs`) that no longer exist in `16.9.0`. They appear to be named

```
react-dom-unstable-fire.development.js
react-dom-unstable-fire.production.min.js
react-dom-unstable-fire.profiling.min.js
```

So, if I'm understanding that linked issue correctly, then that would be the cause of react-dom not auto-updating?

**Comment by MattIPv4** [comment]
@frehner Yup, file structure has changed which means the bot won't auto-update, so the version will need to be manually added through a pull request.

**Comment by frehner** [comment]
ok sounds good. I'm not a maintainer of react-dom or anything so it looks like I've reached the limit of my usefulness here. :)

Thanks for your help.

**Comment by MattIPv4** [comment]
@frehner You can submit a PR if you wish to endure doing so :)

**Comment by frehner** [comment]
Oh, I don't mind... I think!

By "manually adding" the version, does that mean creating a PR that updates the package.json to `16.9.0` and also adds a folder that includes the contents of the tarball? If so, that's not too bad... haha

**Comment by MattIPv4** [comment]
@frehner Pretty much :) When adding the version contents, you will need to check it follows how the auto-update map works, which I believe will expand everything out into the root directory of the version. You can check a previous version to confirm this.

**Comment by frehner** [comment]
looks like it just makes a `cjs` and `umd` folder and everything inside of those are just copied over. https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/react-dom/16.8.6

PR incoming then. Thanks!

**Comment by frehner** [comment]
@MattIPv4 created #13425 . Hopefully I did it right. :)

**Comment by xtuc** [comment]
The bot added
```
    Add react-dom v16.11.0
    Add react-dom v16.10.2
    Add react-dom v16.10.1
    Add react-dom v16.10.0
    Add react-dom v16.9.0/16.9.0-rc.0
    Add react-dom v16.9.0-alpha.0

```
