### ISSUE TITLE
Update bootbox.js to v5

### ISSUE THREAD

**Issue by tiesont** [cdnjs/cdnjs#13422]
This replaces a [previous request](https://github.com/cdnjs/cdnjs/issues/13280) to update the bootbox.js CDN. I have reverted our directory structure to match the 4.4 layout (which is the currently-hosted cdnjs version). 

I've added (what I hope is) the settings to enable auto-update from the npm package (https://www.npmjs.com/package/bootbox), per [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md).

Please let me know if I've missed something.

Added pull-request to update package.json: https://github.com/cdnjs/cdnjs/pull/13423

**Comment by MattIPv4** [comment]
@tiesont The auto-update config goes in the package.json in the cdjns repo, not your own package.json.

**Comment by tiesont** [comment]
@MattIPv4 Sorry about that. Fixed our package.json and added a pull-request to update our package.json on this repo.

**Comment by tiesont** [comment]
Looks like the update went through. Closing. Thanks!
