### ISSUE TITLE
update ztree.v3 to 3.5.40

### ISSUE THREAD

**Issue by snowchenlei** [cdnjs/cdnjs#13429]
now have ztree 3.5.40.
but download this result is ztree 3.5.0.1.
i hope update ztree to 3.5.40
![image](https://user-images.githubusercontent.com/26211283/63086641-ea5b0c80-bf82-11e9-8244-0711ba9dcdc2.png)

**Comment by MattIPv4** [comment]
cc @PeterDaveHello this looks like a bug to me but unsure. The source file has the correct version which makes me think it may be an issue our end? https://github.com/zTree/zTree_v3/blob/master/js/jquery.ztree.all.min.js

**Comment by snowchenlei** [comment]
> cc @PeterDaveHello this looks like a bug to me but unsure. The source file has the correct version which makes me think it may be an issue our end? https://github.com/zTree/zTree_v3/blob/master/js/jquery.ztree.all.min.js

Maybe it's a bug, and I want to fix it.Thank you

**Comment by LuckyPigeon** [comment]
@snowchenlei  Are you already work on this?

**Comment by snowchenlei** [comment]
@LuckyPigeon Sorry,I've been busy lately.Maybe someone else could help.Let me know if you have solved it。Thank You.

**Comment by LuckyPigeon** [comment]
@snowchenlei I have updated the package.json

**Comment by LuckyPigeon** [comment]
@snowchenlei Looks like my commit has passed ci test, now let's wait for the result.

**Comment by PeterDaveHello** [comment]
Just found the tag v3.5.01 causes git malfunctioning, once checkout to v3.5.01, the updater can't properly checkout to other references.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/autoupdate/commit/b6076a7d0e7cfec1bf9885840c025ab8dcbc7a3d

**Comment by PeterDaveHello** [comment]
This PR will fix it: https://github.com/cdnjs/cdnjs/pull/13451

**Comment by snowchenlei** [comment]
@LuckyPigeon OK,Thank You!

**Comment by xtuc** [comment]
The bot added
```
    Add zTree.v3 v3.5.39/v3.5.40
    Add zTree.v3 v3.5.38
    Add zTree.v3 v3.5.34~3.5.37
    Add zTree.v3 v3.5.33
    Add zTree.v3 v3.5.32
    Add zTree.v3 v3.5.30
    Add zTree.v3 v3.5.31
    Add zTree.v3 v3.5.29
    Add zTree.v3 v3.5.28
    Add zTree.v3 v3.5.27
    Add zTree.v3 v3.5.25
    Add zTree.v3 v3.5.26
    add zTree.v3 v3.5.24
    add zTree.v3 v3.5.23
``
