### ISSUE TITLE
[Request][Author] Add hideseek-mod

### ISSUE THREAD

**Issue by maxwroc** [cdnjs/cdnjs#13435]
**Library name:** hideseek-mod
**Library description:** A simple, mobile-friendly, yet customizable quick/live search jQuery plugin.
**Git repository url:** https://github.com/maxwroc/HideSeek-Mod
**npm package name or url (if there is one):** https://www.npmjs.com/package/hideseek-mod
**License:** Apache-2.0
**Number of downloads on npm:** ![npm downloads count](https://img.shields.io/npm/dm/hideseek-mod.svg?label=npm)

It is a fork and mod of the original hideseek lib. The source project has no updates since 2y and author is not responsive.

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/hideseek-mod
