### ISSUE TITLE
Should there be a branch protection rules?

### ISSUE THREAD

**Issue by tarlepp** [cdnjs/cdnjs#13430]
With this people who are making PRs that aren't up with master branch they could easily just click update button - if/when there isn't any conflicts.

This would help and speed up PR process a lot.

Example here - https://github.com/cdnjs/cdnjs/pull/13423#pullrequestreview-276249978

And with that I mean this setting:

![image](https://user-images.githubusercontent.com/595561/63216939-3b672e00-c146-11e9-9305-9c64a79a5c51.png)

**Comment by MattIPv4** [comment]
@tarlepp This creates a merge commit in the PR history, which we avoid by requiring it be rebased - this ensures that the overall commit history for the repository is kept clean.

I have an issue already open for allowing @PeterBot to automatically rebase when that CI error is raised: https://github.com/cdnjs/cdnjs/issues/13389

**Comment by tarlepp** [comment]
@MattIPv4 oh, didn't see that one - that one would make this "error" to be solved - I'm keeping this still open because there isn't really ready solution (yet) for this.

**Comment by tarlepp** [comment]
although there is also this
```
Allow rebase merging  
Add all commits from the head branch onto the base branch individually.
```

option on settings, never tried that out so cannot be sure if that would make trick.

**Comment by MattIPv4** [comment]
@tarlepp That just affects how the commits are put into master at merge, not how updating the branch prior to merge works.

As we want to keep the commit history clean, this suggestion for the protection rule won't work, so I'll close this and move the discussion to https://github.com/cdnjs/cdnjs/issues/13389 for ideas on how best to implement this in the bot 👍
