### ISSUE TITLE
[author] tween.js distribution has moved from src/Tween.js to dist/tween.umd.js

### ISSUE THREAD

**Issue by mikebolt** [cdnjs/cdnjs#13448]
I have made some recent changes to tween.js. In version 18 Tween.js is now es6 source, and the version that should be included in the browser is dist/tween.umd.js. This file is generated by `npm run build` and it does not currently exist in the github repository. However, it does exist in the npm repository. The reason for this is that I can't get Travis CI to push back to GitHub.

In short, please change the file that cdnjs serves from (old) src/Tween.js to (new) dist/tween.umd.js from the npm repository. Thanks.

**Comment by MattIPv4** [comment]
Fixed: https://cdnjs.com/libraries/tween.js
