### ISSUE TITLE
Where to find the CLDR JSON filed mentioned in #10160

### ISSUE THREAD

**Issue by AnReZa** [cdnjs/cdnjs#13450]
Ticket #10160 mentiones, that the static JSON files required to use Globalize.js have been added to cdnjs. But where can I find them? I can access the JS files via https://cdnjs.cloudflare.com/ajax/libs/cldrjs/0.5.1/cldr.min.js, for example, but where could I find /cldr/main/de/numbers.json? Without those files, Globalize.js doesn't function.

**Comment by MattIPv4** [comment]
Hi there @AnReZa,

It looks like in that issue we sorted out json files being served on the CDN but never actually had all the CLDR packages added.

You are welcome to open pull requests to add each of the required CLDR packages to CDNJS. :)

**Comment by AnReZa** [comment]
Sorry, but I don't have the time to work myself into the CDN. I have no idea how it works in the background.

**Comment by drewfreyling** [comment]
Should we close this then?

**Comment by AnReZa** [comment]
I wouldn't say so. I still think, that they should be in the dictionary. The other option would be, to remove Globalize.js from your selection. The current solution makes no sense, because Globalize.js is on CDNJS, but the mandatory requirements arent't. Without the CLDR files, Globalize doesn't function.

**Comment by MattIPv4** [comment]
I would close this in favour of a new issue to track the update request to the cldrjs to include the needed json files?

**Comment by AnReZa** [comment]
@MattIPv4 Sure, as long as the missing filed will be added eventually. :)

**Comment by MattIPv4** [comment]
@AnReZa As you're most familiar with list, would you like to open that issue :)
