### ISSUE TITLE
Request to add tiny_mce_wiris plugin to cdn

### ISSUE THREAD

**Issue by dmiepub** [cdnjs/cdnjs#13460]
Request to add tiny_mce_wiris plugin to cdn

**Comment by MattIPv4** [comment]
@dmiepub Do you have any links for this? Would it be https://github.com/lorno-leonard/tiny_mce_wiris ?

**Comment by dmiepub** [comment]
Please check this:

http://www.wiris.com/en/plugins3/tinymce/download
http://www.wiris.com/en/solutions/tinymce

**Comment by MattIPv4** [comment]
It looks like none of those are front-end plugins (CSS/JS)?
I also believe we would have a hard time hosting assets distributed by a specific company that aren't released on GitHub etc.

**Comment by MattIPv4** [comment]
Closing, no progress.
