### ISSUE TITLE
jquery waypoints error version

### ISSUE THREAD

**Issue by logan-19** [cdnjs/cdnjs#13480]
Hello!
jquery waypoints error version

https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js

Contains version 4.0.0

**Comment by JakeRowsell89** [comment]
I had thought of submitting a quick PR, it looks like this is also an issue for the scripts hosted on pagecdn:
https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js

**Comment by xtuc** [comment]
this is likely caused by the library's author. I would recommend reaching out to them instead
