### ISSUE TITLE
CDN missing modules from newer versions of preact (10.0.0-x)

### ISSUE THREAD

**Issue by msembinelli** [cdnjs/cdnjs#13485]
For newer versions of the preact package (10.0.0-x), the `hooks` and `compat` modules are missing from the npmFileMap.

These modules are located in `hooks/dist` and `compat/dist`, which I would like to be included on the CDN. They should be added the npmFileMap in the preact package.json.

**Comment by tomByrer** [comment]
Which CDN are you talking about?  jsDelivr is fine:
https://www.jsdelivr.com/package/npm/preact

**Comment by xtuc** [comment]
The bot added
```
    Add preact v10.0.1
    Add preact v10.0.0-rc.3
    Add preact v10.0.0-rc.2
    Add preact v10.0.0-rc.1
    Add preact v10.0.0-rc.0
    Add preact v10.0.0-beta.3
    Add preact v10.0.0-beta.2
    Add preact v10.0.0-beta.1
    Add preact v10.0.0-beta.0
    Add preact v10.0.0-alpha.0~4

```
