### ISSUE TITLE
cdnjs.cloudflare.com is down

### ISSUE THREAD

**Issue by inlics** [cdnjs/cdnjs#13497]
cdnjs.cloudflare.com is down

**Comment by MattIPv4** [comment]
Looks to be fine, are you sure this isn't an error on your end?

**Comment by drewfreyling** [comment]
Fine for me too - please provide an nslookup and traceroute.

**Comment by inlics** [comment]
> Looks to be fine, are you sure this isn't an error on your end?

It just happened between noon on October 1st and morning on October 2nd.

**Comment by MattIPv4** [comment]
There were no other reports of this at all -- I would suspect this was an issue with your connection?

**Comment by MattIPv4** [comment]
No progress, closing.
