### ISSUE TITLE
Enable HTTP/3 

### ISSUE THREAD

**Issue by Achiel** [cdnjs/cdnjs#13511]
With the announcement that Cloudflare supports HTTP/3 now, would CDNJS be interested in enabling it? Usage will be limited as only Chrome Canary is currently the only browser that supports it, but would help in testing compatibility/performance.

Relevant links:
 - https://developers.cloudflare.com/http3/
 - https://blog.cloudflare.com/http3-the-past-present-and-future/

**Comment by MattIPv4** [comment]
@dknecht @simon-says @zackbloom can we make this happen?

**Comment by drewfreyling** [comment]
We might to be on the waitlist like everyone else!

**Comment by dknecht** [comment]
Yes.  Let’s turn it on.

**Comment by Achiel** [comment]
Cloudflare GA'd HTTP/3 support last week, there's no waiting list anymore! To enable, just login to the dashboard and turn it on under the Network tab.

**Comment by MattIPv4** [comment]
We (cdnjs maintainers) don't have access to the cdnjs.cloudflare.com dashboard, the Cloudflare team need to do this.

@dknecht could you confirm here once it's enabled?

**Comment by zackbloom** [comment]
As it's a subdomain of cloudflare.com it likely can't be turned on without it being turned on for the whole domain. I'm currently working on a timeline for when that might be possible, hopefully very soon!

**Comment by zackbloom** [comment]
We've gone through the due diligence on the services which may be affected and are confident HTTP/3 will only help, not harm, so we are prepared to turn it on today. I will report back if and when that happens! 🚀

**Comment by zackbloom** [comment]
Made progress finishing checks, will confirm that everything looks good tomorrow and provide another update.

**Comment by xtuc** [comment]
h3 is now enabled
