### ISSUE TITLE
font-awesome 4.7.0 icons stopped working

### ISSUE THREAD

**Issue by redf150flames** [cdnjs/cdnjs#13510]
Hello,

I got on my site today and noticed several of the FontAwesome icons broken. I am using the `<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">` embed.

If I disable the `font-family: "fontawesome-5-juicer"` style they come back. Not sure if this was recently updated or not?

![image](https://user-images.githubusercontent.com/5415652/66665760-09cd8900-ec04-11e9-9e15-5e1a1583cb0f.png)

![image](https://user-images.githubusercontent.com/5415652/66665774-12be5a80-ec04-11e9-8084-7713a070defb.png)

**Comment by MattIPv4** [comment]
That appears to be some extra styling you're inserting on your site that is causing the font-awesome icons to break. The assets we are serving have not changed, we ever change the contents of the assets we serve.

**Comment by redf150flames** [comment]
You're right @MattIPv4 there was another plugin adding extra styling that I missed. Thanks!
