### ISSUE TITLE
google-code-prettify still referencing googlecode

### ISSUE THREAD

**Issue by mountainash** [cdnjs/cdnjs#13513]
Library: https://cdnjs.com/libraries/prettify has 2 `_run` files that are calling files on the now disabled **googlecode** CDN 
eg:
https://cdnjs.cloudflare.com/ajax/libs/prettify/r298/run_prettify.js
https://cdnjs.cloudflare.com/ajax/libs/prettify/r298/run_prettify.min.js

The run files need to change to pull from `cdnjs.cloudflare.com` instead.

The setup on https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js seems to be localised to the serving host.

Maybe the guys @Amomo or @PeterDaveHello, that worked on #5508 & #5420 want to have a look?

**Comment by MattIPv4** [comment]
We will never update files that are already published. This would require a new, fixed version from the source for this library.
