### ISSUE TITLE
p5.js not updating

### ISSUE THREAD

**Issue by lmccart** [cdnjs/cdnjs#13523]
Hello, it seems that the p5.js library is stuck at 0.9.0 on the CDN, even though we're on 0.10.2 now. The [package.json auto-update file](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/p5.js/package.json) seems to be correct and the [npm package is here](https://www.npmjs.com/package/p5). Do you see any problem? Thank you!

**Comment by MattIPv4** [comment]
Please see #13524

**Comment by lmccart** [comment]
got it, thanks!
