### ISSUE TITLE
Lack of cdnjs activity

### ISSUE THREAD

**Issue by eastling** [cdnjs/cdnjs#13524]
Hello, it seems the last commit is in 17days ago. Why there is no commit recently?
![image](https://user-images.githubusercontent.com/8174685/67255769-50e63480-f4b6-11e9-8cfb-ebd408cab167.png)

**Comment by MattIPv4** [comment]
Long story super short:

 - Founder restricted access heavily so we (core maintainers) cannot do much at all
 - Founder disappeared off the face of the earth and we heard nothing
 - We (core maintainers) raised this internally and asked it be sorted
 - Nothing was sorted, so @PeterDaveHello appears to have disabled our updating automation (I disagree with this action, it harms the existing users of the service)

We have an on-going internal discussion to get this resolved internally but this is the current state of affairs, nothing has really progressed since we (core maintainers) first raised the access issue internally.

**Comment by olafcm** [comment]
Thank you for your update on this issue, @MattIPv4.
Since the auto-update bot is offline, none of the libs we use are updated. Any progress on the issue?
Thanks!

**Comment by MattIPv4** [comment]
No progress since the last update to the above message, which I plan to keep updated with the latest. I'll follow up internally later today about getting auto-updating back working and getting us (core maintainers) proper admin access to all our repos.

**Comment by gruselhaus** [comment]
@MattIPv4 any progress?

**Comment by MattIPv4** [comment]
I've followed up internally about the outstanding issues, haven't heard anything more though.

As a general note, pinging me for updates isn't need, I will keep the post at the top updated with the latest :)

**Comment by jimaek** [comment]
Let me know if the jsDelivr team can help in any way

**Comment by MattIPv4** [comment]
@jimaek with the little access & control that I have, I'm not sure that there is currently much we can do.

Though, if we ever do reach a point where we have the access needed, it may be an idea to consider simply creating a worker on cdnjs.cloudflare.com that maps traffic to jsDelivr, to put an end to this mess.

**Comment by jimaek** [comment]
That's an option of course. But we can also provide developer time for free to help out and ensure there is no impact to any users. Just ping me

**Comment by aditsachde** [comment]
I'm not really sure how any of the internal infrastructure works, but has there been an attempt to contact Cloudflare? The assets are served from a Cloudflare domain, so they might be able to help out with creating a worker and remapping traffic to jsDelivr, without commit access to all the repos or the bot.

**Comment by MattIPv4** [comment]
Yes, I could potentially work with Cloudflare to deploy such a worker, though this would be an absolute last resort thing and not something I really want to do unless we deciede that cdnjs is completely dead, which is not a call that has been made yet.

**Comment by zackbloom** [comment]
I work at Cloudflare on the team which supports CDNJS. We're all very sorry this disruption in the updating of CDNJS happened. We are committed to continuing to serve CDNJS users and sites. Any site using CDNJS will continue to get the files it relies on without interruption.

We have engineers currently working with the CDNJS team to get the updating happening again. Once that is completed we can start thinking about the best long-term model to ensure projects stay updated without another incident like this. We deeply appreciate the patience and help from the CDNJS team, the users of CDNJS, and of course @MattIPv4, as this gets sorted.

**Comment by drewfreyling** [comment]
Thanks @zackbloom and @MattIPv4 - let me know if I can be if assistance with any of the development effort.

**Comment by PeterDaveHello** [comment]
Sorry for the inconvenience caused here, never mean to harm the project or Cloudflare.

It's really a ... hard decision to make to step down and take a rest, on a project I spent so much time and varies of resources on it, actually, I'm a little bit tired, too many things need to be done, resources are really limited, only few contributors get involved into it, instead, so many people take it as granted ... 

Anyway, yes, we're working with Cloudflare right now to see how we can get it sorted, I hope it won't take too long.

**Comment by zackbloom** [comment]
Thank you @PeterDaveHello. We all deeply appreciate all the time and effort you have put into CDNJS over the past few years, it is an amazing thing to go back through the commits and see just how much you have done.

**Comment by mrlife** [comment]
Thank you for providing CDNJS. Any update on the auto-update bot coming online? Not sure whether to keep waiting or shift to another CDN solution.

https://github.com/DataTables/DataTablesSrc/issues/153

**Comment by MattIPv4** [comment]
The old auto-update bot is online and running. You can see that in the commit activity on the repo. We are still working on figuring out the best plan for a rewrite of the auto-update bot.

**Comment by mrlife** [comment]
@MattIPv4 Thanks for letting me know. When will tagged releases start being picked up, e.g. DataTables 1.10.20?

**Comment by MattIPv4** [comment]
Looks like that was published quite a while back - I would guess that the file structure has changed or another issue has occurred with the auto-update of it that means manual intervention will be needed. Please create a separate issue requesting the library is updated here.
