### ISSUE TITLE
bootstrap-colorpicker not updating

### ISSUE THREAD

**Issue by skmedix** [cdnjs/cdnjs#13527]
[cdnjs](https://cdnjs.com/libraries/bootstrap-colorpicker) | [git repo](https://github.com/itsjavi/bootstrap-colorpicker) | [npm](https://www.npmjs.com/package/bootstrap-colorpicker)

**Comment by MattIPv4** [comment]
Please see #13524

**Comment by skmedix** [comment]
This lib is not auto updating for a while, I guess that's because repo url changed

**Comment by xtuc** [comment]
The bot added the following
```
    Add bootstrap-colorpicker v3.0.0-beta.3
    Add bootstrap-colorpicker v3.0.0-beta.2
    Add bootstrap-colorpicker v2.5.3
    Add bootstrap-colorpicker v3.0.0-beta.1
    Add bootstrap-colorpicker v2.5.2
```
