### ISSUE TITLE
Vuetify not up to date

### ISSUE THREAD

**Issue by xevimayo** [cdnjs/cdnjs#13536]
The Vuetify lib is not updated, current version is 2.1.7 and last in cdnjs is 2.1.1 lots of fixes from there.

**Comment by MattIPv4** [comment]
Please see https://github.com/cdnjs/cdnjs/issues/13524

**Comment by xevimayo** [comment]
Thanks @MattIPv4 now I understand the situation! I hope you can fix these situation.

**Comment by MattIPv4** [comment]
The assets are now in the cdnjs repository and are available on the CDN: https://cdnjs.cloudflare.com/ajax/libs/vuetify/2.1.9/vuetify.js

The only remaining issue is that the website is currently not updating to show the latest versions available, this is being tracked in #13612
