### ISSUE TITLE
OverlayScrollbars is not updated

### ISSUE THREAD

**Issue by KoalaBear84** [cdnjs/cdnjs#13605]
See original request to add it #12562

It says "npm autoupdate enabled", and it is already updated a month ago on npmjs.

https://www.npmjs.com/package/overlayscrollbars

Is it broken? Thanks in advance!

**Comment by MattIPv4** [comment]
Please see https://github.com/cdnjs/cdnjs/issues/13524

**Comment by KoalaBear84** [comment]
Thank you very much for the info and thanks for working to fix this again. 👍

I'll close it myself as things will automatically be resolved 'soon' I guess 👍
