### ISSUE TITLE
Transfer update bot management to Cloudflare

### ISSUE THREAD

**Issue by zackbloom** [cdnjs/cdnjs#13610]
CDNJS relies on an automatic update process which pulls in the latest versions of existing projects (in additional to a manual review process for new projects). Historically the bot which enables this process has ran on a server of a key maintainer of the project, @PeterDaveHello. Unfortunately as a part of https://github.com/cdnjs/cdnjs/issues/13524 this service was terminated 29 days ago, preventing projects from getting updated. We very much want to get this immediate lack of updates resolved, but more importantly we want to ensure an issue like this does not occur again.

@xtuc has prepared a new Ansible-based runner for the Autoupdate bot which is provisionally available for review [here](https://github.com/xtuc/cdnjs-bot-ansible). Based on the approval of the community we will make that runtime the canonical bot which updates CDNJS, and take responsibility for its execution.

We (@cdnjs/cloudflare) are committed to CDNJS and its reliability, and are very happy to have the opportunity to contribute!

**Comment by MattIPv4** [comment]
What's the plan as far as CI goes, will @robocdnjs take over that duty too?

**Comment by zackbloom** [comment]
Yes, that's the plan @MattIPv4. I'm currently in the process of categorizing the open PRs and the plan is for the bot to be able to handle an even wider swath of the cases which currently require manual intervention. I'll have more of a write-up on that in a separate issue.

**Comment by MattIPv4** [comment]
Awesome, sounds great.

**Comment by ryankirkman** [comment]
@zackbloom @xtuc This makes sense to me. Let’s go ahead with using the new Ansible based auto update bot.

One request: since the bot will become the canonical update bot, can we move the new repo under the cdnjs organization GitHub account?

This doesn’t need to block turning on the bot, but would be good to co-locate all parts of cdnjs infrastructure under the cdnjs GitHub organization where possible.

**Comment by zackbloom** [comment]
Yes, I think that is a great idea. We will remove access to @PeterBot at this time then.

**Comment by xtuc** [comment]
@ryankirkman yes sure; I created https://github.com/cdnjs/bot-ansible.

**Comment by jackdoyle** [comment]
Just checking in - @zackbloom @ryankirkman any progress? It has been over a week now and GSAP 3 still isn't up on the Cloudflare CDN. We have a lot of customers asking us about this. Kinda embarrassing for us. It'd be great to get a status update when you have a chance. Thanks for all your efforts!

**Comment by zackbloom** [comment]
Thanks for your patience as always @jackdoyle. I need to check with @xtuc, but I am optimistic about reenabling the updating tomorrow.

**Comment by zackbloom** [comment]
Good news! Updates are live as of today. THANK YOU all for your patience.

PS @jackdoyle https://cdnjs.cloudflare.com/ajax/libs/gsap/3.0.0/gsap.min.js

**Comment by jackdoyle** [comment]
@zackbloom Thanks so much! That's excellent news.

**Comment by jackdoyle** [comment]
@zackbloom is there any reason the cdnjs.com site isn't updating with the new version(s)? https://cdnjs.com/libraries/gsap

It still shows 2.1.3 as the latest (but it should be 3.0.1). Help?

**Comment by zackbloom** [comment]
That is another component which is in the process of being moved to more reliable infrastructure. It's tracked in https://github.com/cdnjs/cdnjs/issues/13612
