### ISSUE TITLE
viewerjs 1.4.0 not provided

### ISSUE THREAD

**Issue by Mister-Hope** [cdnjs/cdnjs#13623]
viewerjs 1.4.0 not provided

https://github.com/fengyuanchen/viewerjs/releases/tag/v1.4.0

the newest is still 1.3.7

**Comment by MattIPv4** [comment]
The assets are in the cdnjs repository and are available on the CDN: https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.4.0/viewer.js

The only remaining issue is that the website is currently not updating to show the latest versions available, this is being tracked in #13612
