### ISSUE TITLE
vuex 3.1.2 missing

### ISSUE THREAD

**Issue by Mister-Hope** [cdnjs/cdnjs#13624]
https://github.com/vuejs/vuex/releases/tag/v3.1.2

The newest is still 3.1.1

**Comment by MattIPv4** [comment]
The assets are in the cdnjs repository and are available on the CDN: https://cdnjs.cloudflare.com/ajax/libs/vuex/3.1.2/vuex.js

The only remaining issue is that the website is currently not updating to show the latest versions available, this is being tracked in #13612
