### ISSUE TITLE
Is the autoupdate process broken ?

### ISSUE THREAD

**Issue by dregad** [cdnjs/cdnjs#13627]
Looking at the numerous issues in this tracker complaining that library XYZ's latest version is not available on cdnjs, I'm wondering whether there is a general problem with the autoupdate process.

e.g. #13625, #13624, #13623, #13620, #13609, #13606, and many others. 

I could add [corejs-typeahead](https://cdnjs.com/libraries/corejs-typeahead) to the list - it seems the latest release (1.3.0) was picked up [in the cdnjs repo](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/corejs-typeahead/1.3.0) but it's not showing up on the CDN / website.

Is this being looked at and can we hope to have it fixed in the near future, or should we consider switching to another, more reliable CDN ?

**Comment by MattIPv4** [comment]
Auto-update is working fine, as you've stated yourself. The assets are in the cdnjs repository and are available on the CDN: https://cdnjs.cloudflare.com/ajax/libs/corejs-typeahead/1.3.0/bloodhound.js

The only reminaing issue is that the website is currently not updating to show the latest versions available, this is being tracked in https://github.com/cdnjs/cdnjs/issues/13612

**Comment by dregad** [comment]
@MattIPv4 thanks for the prompt feedback.

Please accept my apologies for the tone of my initial post's last paragraph, that was uncalled for. Sorry about that.

> The assets are in the cdnjs repository and are available on the CDN

Not knowing the internals of cdnjs, I did not realize that updating the website was a separate process, and did not even think of trying to access the resources directly.

Is it possible to get the SRI without the website ?

**Comment by MattIPv4** [comment]
You should be able to use https://www.srihash.org/ for now, until we have the website running again :)
