### ISSUE TITLE
Download the newest version of all the libraries - frameworks oraganized in one-zip file.

### ISSUE THREAD

**Issue by NotMoni** [cdnjs/cdnjs#13622]
I am going to a rural part of the world where there is no electricity for 3 months. Is it possible i can get a zip file with all the js libraries and frameworks you guys host? I want to give the files to the people that live there and teach them the code. Could you guys provide me a zip file.

**Comment by drewfreyling** [comment]
Just clone the repo and all the files will be there for you to zip up.

**Comment by MattIPv4** [comment]
Be warned it's like around 200GB uncompressed.

**Comment by NotMoni** [comment]
I better get downloading.
