### ISSUE TITLE
collect.js 4.18.7 missing

### ISSUE THREAD

**Issue by ecrmnn** [cdnjs/cdnjs#13625]
Hi

https://cdnjs.com/libraries/collect.js havn't updated in three months.

That release is [three months old](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/collect.js/4.16.6).  The newest release (2 days old) [`4.18.7`](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/collect.js/4.18.7) exists in `ajax/libs/` but isn't visible on the site?

**Comment by MattIPv4** [comment]
The assets are in the cdnjs repository and are available on the CDN: https://cdnjs.cloudflare.com/ajax/libs/collect.js/4.18.7/collect.js

The only remaining issue is that the website is currently not updating to show the latest versions available, this is being tracked in #13612
