### ISSUE TITLE
Please update bootstrap to the latest version

### ISSUE THREAD

**Issue by chrisc0** [cdnjs/cdnjs#13635]
Hi,

Can someone please update bootstrap to the latest version?  It's currently two behind.  Thanks.

Chris

**Comment by MattIPv4** [comment]
The latest version (4.4.1) is in the cdnjs repository (https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/twitter-bootstrap/4.4.1) and is available for use on the CDN: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.css

The website is currently not updating to show latest versions, see #13612
