### ISSUE TITLE
Git auto-update: rollbar.js not updating

### ISSUE THREAD

**Issue by waltjones** [cdnjs/cdnjs#13637]
When the updater was reenabled, rollbar.js caught up to its then current version of 2.14.4. Since then, 2.14.5 and 2.14.6 have been tagged at https://github.com/rollbar/rollbar.js but are not showing up at https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/rollbar.js/ and https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/rollbar.js/package.json is still set to 2.14.4.

Any help is appreciated. Thank you!

**Comment by MattIPv4** [comment]
Hi there!

Thank you for making a new library request issue on cdnjs! 📦
Due to the massive number of requests we receive, it may be a while before one of our team get around to processing this request.

**To help us with this, you can create the pull request to add the library yourself!** 📥

**Please take a read of our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) file for a basic outline of how to make a library pull request and also our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) file for more specific details of the cdnjs `package.json` file for each library.**

Thank you very much for your help in keeping cdnjs up to date with libraries. 😄

**Comment by waltjones** [comment]
Hi @MattIPv4 , this isn't a new library. The autoupdater has worked fine for us until it stopped working for everyone a few months ago. Then when it was working again, it did catch up to the current version at that time. But no further versions have been picked up since then.

If there is a known issue with the autoupdater that is causing the current problem, can you link it here?

**Comment by MattIPv4** [comment]
Ah, I had assumed that new files had been added or files removed, which would cause the auto-update to fail and require a manual PR.

However, looking at the files in 2.14.4 & 2.14.6, they're identical, so auto-update should be working correctly.

@xtuc any ideas?

**Comment by waltjones** [comment]
@MattIPv4 I thought the script relied on git version tags to pick up new versions, but https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md says it looks at npmjs.org. Which is accurate?

**Comment by MattIPv4** [comment]
Depends if you have git or npm auto-update configured. In the case of this lib, it is using git auto-update: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/rollbar.js/package.json#L18-L29

**Comment by waltjones** [comment]
Got it. Thank you. That's what I thought, but just wanted to be sure.

**Comment by waltjones** [comment]
@MattIPv4 Is there anything I can do to help? I'd like to be able to tell others at Rollbar something meaningful about this.

**Comment by MattIPv4** [comment]
I'm not sure what the source of the issue is here, I'm not familiar with how the auto-update bot works.

@xtuc might possibly have some ideas as he's worked on the bot?

**Comment by waltjones** [comment]
Can anyone look at the local file system for the presence of .bot_cant_auto_add or a similarly obvious problem?

https://github.com/cdnjs/script/blob/master/commonScript.sh#L162-L165

**Comment by xtuc** [comment]
@waltjones, the new versions doesn't exists on the file system:
```
sven@cdnjs-bot4:/cdnjs-sven/cdnjs$ ls ajax/libs/rollbar.js/{2.14.5,2.14.6}
ls: cannot access 'ajax/libs/rollbar.js/2.14.5': No such file or directory
ls: cannot access 'ajax/libs/rollbar.js/2.14.6': No such file or directory
```

And `find ajax/libs/rollbar.js/ -name .bot_cant_auto_add` doesn't show anything.

I'm not sure what's wrong but it seems to impact multiple packages as well.

**Comment by waltjones** [comment]
@xtuc Thank you for the update.

**Comment by waltjones** [comment]
@xtuc Let me know if I can help review log files. For example, does it get as far as: https://github.com/cdnjs/script/blob/master/commonScript.sh#L80

I'm happy to help look at this.

**Comment by xtuc** [comment]
That would be helpful! I uploaded the logs from a previous runs (between 18th Dec and 29th Dec) here: https://gist.githubusercontent.com/robocdnjs/3955d67542c3c21f1462a15c24359465/raw/438aba98fde6b749582f17f969274c04886039c9/bot.log

**Comment by waltjones** [comment]
@xtuc Thank you for the log file.

I cloned the cdnjs, bot, script, and autoupdate projects, and ran autoupdate.js script and the bot locally. I saw about 50 projects that autoupdate.js considers autoupdate projects but were not caught up to their most recent git tags, but did update correctly when I ran the scripts locally here. I am using the latest master branch for each of the script repos to run these scripts.

Can you let me know the local value for "version" in autoupdate/git_repo_local_cache/rollbar.js/package.json and in the local cdnjs repo: cdnjs/ajax/libs/rollbar.js/package.json. These both updated correctly when I ran them here, but I assume one or both will not be updated in yours.

I'm also curious what value `AUTOUPDATE_CONCURRENT_LIMIT` is set to in the production config.

There are 10 projects that fail git fetch:
6px git repo fetch failed
gist-embed git repo fetch failed
jquery.iframe-transport git repo fetch failed
mogl git repo fetch failed
probtn git repo fetch failed
rainyday.js git repo fetch failed
scrollmonitor git repo fetch failed
snoocore git repo fetch failed
Tipue-Search git repo fetch failed
unslider git repo fetch failed

When these each fail, the script doesn't call `callback()` and the current async worker exits. 
https://github.com/cdnjs/autoupdate/blob/master/updaters/git.js#L51-L55

For me, when the async limit is 4, the script gets as far as mogl before all async workers are exhausted. When the limit is 8, it's gets to snoocore.

I'm sure there are differences in the production config, but here at least, with less than AUTOUPDATE_CONCURRENT_LIMIT = 11, some projects will never get updated.

**Comment by waltjones** [comment]
@xtuc Just following up on this again.

When I ran everything locally, the rollbar.js package.json was found correctly. The git fetch and git commit worked correctly. It looks like the issue is specific to the local state of the production environment of the cdnjs scripts.

Can you let me know the local value for "version" in autoupdate/git_repo_local_cache/rollbar.js/package.json and in the local cdnjs repo: cdnjs/ajax/libs/rollbar.js/package.json. These both updated correctly when I ran them here, but I assume one or both will not be updated in yours.

I am considering whether to switch to manual updates, but this seems like an unfortunate way to go forward since autoupdate had been working correctly for a long time.

**Comment by MattIPv4** [comment]
For some context on the current situation on cdnjs: we're currently working to rewrite the auto-update bot so we have a better understanding of it's internals. Going forward, we won't be supporting manual updates to cdnjs at all as they require far too much manual work from everyone.

**Comment by waltjones** [comment]
@MattIPv4 Thank you, this is helpful to know. I saw a ticket for that work. I'll keep an eye on it.

**Comment by xtuc** [comment]
Even after a change to the bot, 2.14.5 and 2.14.6 are still not showing up

**Comment by MattIPv4** [comment]
Hmmm. Were they in the local uncommitted list? If not, we should do some more digging into what's going on with these.

**Comment by xtuc** [comment]
the package is updated via git, we recommend switching to npm

**Comment by MattIPv4** [comment]
Possibly a similar situation to #13634 where the git auto-update bot just isn't picking up versions.

@xtuc how's progress going on the new git bot?

**Comment by xtuc** [comment]
@MattIPv4 I haven't started to work on the git bot, sorry for the delay

**Comment by xtuc** [comment]
I moved the package to the new bot and new versions were pushed
