### ISSUE TITLE
Wrong Foundation version

### ISSUE THREAD

**Issue by DanielRuf** [cdnjs/cdnjs#13636]
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.0/js/foundation.min.js

This seems to be 6.5.3 which is wrong.

**Comment by MattIPv4** [comment]
Can confirm this appears to be the case...

foundation.js on cdnjs @ 6.6.0: https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.0/js/foundation.js
foundation.js in the source repo @ 6.6.0: https://raw.githubusercontent.com/foundation/foundation-sites/9a73cc9721056c586547b0b83938dc22a1176871/dist/js/foundation.js

An example that they are different: the string `this.isEnabled = true;` exists in the source repo version but not the cdnjs version.

**Comment by MattIPv4** [comment]
cc @xtuc - whilst we can't retroactively fix versions as this will break SRI, we should find the root cause of this so we dont publish any further bad versions.

**Comment by xtuc** [comment]
we should check if that's still the case with the new bot.

**Comment by MattIPv4** [comment]
https://cdnjs.cloudflare.com/ajax/libs/foundation/6.6.3/js/foundation.js -- search for `FOUNDATION_VERSION = '6.6.3'`.

My guess would be that the folks over at Foundation tagged the version before the files were updated and then fixed this after, but we'd already pulled down the bad tag by the time.

**Comment by DanielRuf** [comment]
> My guess would be that the folks over at Foundation tagged the version before the files were updated and then fixed this after, but we'd already pulled down the bad tag by the time.

I'm not sure as we may have done that but in this case it was a draft tag, not a published tag.

**Comment by DanielRuf** [comment]
> My guess would be that the folks over at Foundation tagged the version before the files were updated and then fixed this after, but we'd already pulled down the bad tag by the time.

I'm not sure as we may have done that but in this case it was a draft release / tag, not a published release / tag.
