### ISSUE TITLE
Documentation for sparseCheckout is confusing

### ISSUE THREAD

**Issue by tevko** [cdnjs/cdnjs#13649]
https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

Let's say I'm looking to add a library - do I need to check out all of `/ajax/libs/`?  If I do that, I'm pulling down ~10 GB. I'm sure I'm doing something wrong here, but I can't find any documentation to say otherwise

**Comment by MattIPv4** [comment]
If you're planning to add a new library, you should just add the folder that will be added to cdnjs to the sparse checkout file. Eg. if you're adding `my-lib`, you would add `/ajax/libs/my-lib/*` to the sparse checkout config.

(However, this repo is generally huge to work with. It is normally recommended to simply use the GitHub web UI to add new stuff to this repo until we refactor how our git system works.)

**Comment by tevko** [comment]
Thanks @MattIPv4 !
