### ISSUE TITLE
twitter-bootstrap version not found!

### ISSUE THREAD

**Issue by wangkanai** [cdnjs/cdnjs#13654]
https://cdnjs.com/libraries/twitter-bootstrap

Is the something wrong with twitter-bootstrap?

![image](https://user-images.githubusercontent.com/10666633/71569263-82a3f900-2b00-11ea-8267-a334d613dba4.png)

But i still see it in the search

![image](https://user-images.githubusercontent.com/10666633/71569310-baab3c00-2b00-11ea-9fe0-ba0c40d5d808.png)

So this issue is causing my build to fail this morning.

![image](https://user-images.githubusercontent.com/10666633/71569326-df071880-2b00-11ea-970c-e1bf0e9f651d.png)

**Comment by stepkillah** [comment]
Same issue for few more packages:
```libman.json : error LIB002: The "twitter-bootstrap@4.3.1" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "tether@1.4.7" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "bootstrap-select@1.13.11" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "bootstrap-fileinput@5.0.6" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "select2@4.0.10" library could not be resolved by the "cdnjs" provider 
```

**Comment by echolet** [comment]
Same issue with Foundation related packages:

https://cdnjs.com/libraries/foundation
404 Not Found

**Comment by Dennis-Petrov** [comment]
The same is for https://cdnjs.com/libraries/bootswatch

**Comment by VladMiskaryan** [comment]
Workaround, that working for me, is update libman.json:

```
    {
      "library": "bootstrap@4.3.1",
      "destination": "wwwroot/lib/bootstrap/dist",
      "provider": "unpkg"
    },
    {
      "library": "bootswatch@4.3.1",
      "destination": "wwwroot/lib/bootswatch",
      "provider": "unpkg"
    }
```

**Comment by MattIPv4** [comment]
@xtuc looks like the new package generation script has further issues?

Interestingly, the libraries index page is showing twitter-bootstrap with the [latest version, 4.4.1](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/twitter-bootstrap/package.json):
![image](https://user-images.githubusercontent.com/12371363/71576227-d8b87280-2ae7-11ea-8468-d63b4ffb2012.png)

**Comment by wangkanai** [comment]
I just did i check and find see that the issue is more wider spread.

![image](https://user-images.githubusercontent.com/10666633/71586921-5d3ddc00-2b4e-11ea-86ac-9040ec4ac4d6.png)

Well, i'm not familiar with your code base, So I don't know how to help out. Is there a PR or branch working on this issue?

**Comment by MattIPv4** [comment]
My guess is that this would be affecting any library with more than 10 versions available on cdnjs. We're actively working to get this fixed :)

**Comment by xtuc** [comment]
This issue is now resolved. Sorry for the inconvenience

**Comment by maxd** [comment]
@xtuc The libman (Library Manager, .NET Core JS package manager) is still return error:

```
libman.json : error LIB002: The "admin-lte@2.4.18" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "twitter-bootstrap@3.4.1" library could not be resolved by the "cdnjs" provider
libman.json : error LIB002: The "bootstrap-datepicker@1.9.0" library could not be resolved by the "cdnjs" provider
libman.json : error LIB002: The "datatables@1.10.19" library could not be resolved by the "cdnjs" provider 
libman.json : error LIB002: The "font-awesome@4.7.0" library could not be resolved by the "cdnjs" provider
libman.json : error LIB002: The "select2@4.0.10" library could not be resolved by the "cdnjs" provider
```

**Comment by MattIPv4** [comment]
I think the API cache will need clearing - @xtuc do you have the correct access on the cdnjs.com Cf dash to perform a purge?

**Comment by wangkanai** [comment]
This look like a good results

![image](https://user-images.githubusercontent.com/10666633/71589030-0fc56d00-2b56-11ea-95f5-77070f26e3c8.png)

and build is not passing also

![image](https://user-images.githubusercontent.com/10666633/71589224-aeea6480-2b56-11ea-8ab5-eeb8d57dd067.png)

Thank you very much for such a quick fixed on the last work day of the year there mate.

**Comment by MattIPv4** [comment]
Sweet, glad to hear it's now working for you :)

**Comment by jtriance** [comment]
![jquery tablesorter-notfound](https://user-images.githubusercontent.com/31019401/71589736-c8e66180-2ada-11ea-8dfa-200c935629cd.PNG)
![jquery tablesorter](https://user-images.githubusercontent.com/31019401/71589737-c8e66180-2ada-11ea-9aab-43c0973cdf35.PNG)

Looks like jquery.tablesorter is also not working

**Comment by MattIPv4** [comment]
Working for me. Try force refreshing the page @jtriance?

**Comment by jtriance** [comment]
OK, that worked now I just need to figure out how to fix my build.  Thanks

**Comment by echolet** [comment]
Although https://cdnjs.com/libraries/foundation is no longer a 404, the package files have a reduced menu, e.g. no "copy SRI".

**Comment by MattIPv4** [comment]
I believe SRI calculations aren't running for new library versions. cc @xtuc

**Comment by xtuc** [comment]
I confirm, we are currently refactoring a lots of things and I had to disable SRI calculations in the meantime.

**Comment by justintoth** [comment]
I'm still having this issue when downloading packages within Visual Studio, using libman.json.

> Restore operation started...
> Restoring libraries for project Web
> The "twitter-bootstrap@4.4.1" library could not be resolved by the "cdnjs" provider
> The "bootstrap-datepicker@1.9.0" library could not be resolved by the "cdnjs" provider
> The "bootstrap-calendar@0.2.5" library could not be resolved by the "cdnjs" provider
> The "bootstrap-select@1.13.12" library could not be resolved by the "cdnjs" provider
> The "bootstrap-switch@4.0.0-alpha.1" library could not be resolved by the "cdnjs" provider
> Restore operation completed with errors
> Time Elapsed: 00:00:00.2478784
> ========== Finished ==========

**Comment by justintoth** [comment]
For others using Visual Studio and libman.json, I resolved the issue by running the "libman cache clean" command.

**Comment by Dennis-Petrov** [comment]
@justintoth , thank you. But where libman should be located? Especially in case of build server (only build tools are installed)?

**Comment by maxd** [comment]
@Dennis-Petrov `dotnet tool install -g <tool>` install tool to `$HOME/.dotnet/tools`. This directory is not included to `$PATH` usually. So, you can include it to `$PATH` env. variable to execute in from any directory or execute `libman` directly from this directory:

```
cd $HOME/.dotnet/tools
./libman cache clean
```

**Comment by Dennis-Petrov** [comment]
@maxd  This looks like linux-specific solution. Anyway, manually deleted folder `.librarymanager\cache` from user profile. The error has gone.
