### ISSUE TITLE
react-dom@16.12.0 file 404

### ISSUE THREAD

**Issue by mainhanu** [cdnjs/cdnjs#13653]
https://cdnjs.com/libraries/react-dom/16.12.0

https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.12.0/umd/react-dom-test-utils.development.js

**Comment by xtuc** [comment]
As pointed out by @MattIPv4 yesterday; the autoupdate bot sometimes leaves uncommited versions (and waits for manual intervention). When the website got generated it included these uncommited changes. React version 16.12.0 is one of them.

**Comment by MattIPv4** [comment]
Looks like this has now been resolved as the version presented in https://api.cdnjs.com/libraries/react-dom is 16.11.0 - However, it seems that this is now being affected by the issue described in #13654 so I will close this in favor of that.
