### ISSUE TITLE
Split cdnjs/cdnjs into human & robot repos

### ISSUE THREAD

**Issue by MattIPv4** [cdnjs/cdnjs#13652]
Following on from #13613 where I had begun looking at a plan to create a new "human" repo for cdnjs and leave this repository to become robot only...

The initial plan there had been to preserve as much as possible of the cdnjs "history" into the new repository. This including renaming cdnjs/cdnjs to cdnjs/packages so that PRs & issues were preserved into the new "human" repo as well as using scripts to clean the existing cdnjs commit history of all non-`package.json` files so that the full commit history still existed but with manageable "human" data inside only.

However, both my test scripts for cleaning the commit history are still running after multiple days and are nowhere near completed. With it becoming very apparent that it will not be possible to preserve the commit history in the new "human" repo,  we'll instead have a single commit in the new "human" repo that will contain all the `package.json` files at the point of migration.

With this approach in mind, I no longer see the value in renaming cdnjs/cdnjs to cdnjs/packages and then mirroring back to a new cdnjs/cdnjs repository - if we preserve PRs, they will all become invalid as the repository will be force-pushed to a single commit. Further, by not immediately transferring all the issues over, we can use the new "human" repo as a fresh start for cdnjs.

**Comment by MattIPv4** [comment]
I will continue to work on a migration plan and ensure all the relevant scripts are present in the [`packages-migration`](https://github.com/cdnjs/packages-migration) repository.

With the new migration strategy as discussed above, the actual migration should be pretty straight-forward now. The key task involved in this will be updating how the cdnjs auto-update bot works to function correctly with the split package.json files.

I believe we should use this migration as an opportunity to fully rewrite the auto-update bot so we better understand how it works internally and to potentially address some of the existing issues with it that cause problems for cdnjs maintainers and contributors.

(Evolving) Spec for the Auto-Update Bot:

 - Reads library configs from `ajax/libs/<lib>/package.json` files
 - Supports npm auto-update configs
   - Relies on npm package versioning
   - Package name
   - File map base directory
   - File map glob/list
   - Example: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angular-css/package.json
 - Supports git auto-update configs
   - ❗️Relies on what for versioning?
     - GitHub tags/releases appear to be what is currently used, but we should look at supporting other public git options such as the public version of GitLab.
   - Git target url
   - File map base directory
   - File map glob/list
   - https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/angular-css/package.json
 - Note: Currently there are two different auto-update config formats (npm & git). For now, the bot should just work with these as they are but down the road, we can look at the existing work to condense these into a single auto-update config style: https://github.com/cdnjs/autoupdate/pull/29 & https://github.com/cdnjs/cdnjs/pull/10080

WIP SPEC

**Comment by xtuc** [comment]
> Reads library configs from ajax/libs/<lib>/package.json files

Maybe we could flatten the repo by removing the `ajax/libs/` directories?

> Supports npm auto-update configs

To me this sounds like what unpkg.com does (which does it on the fly)

> File map glob/list

Something I just noticed is that the file map relies on the [node-glob](https://github.com/isaacs/node-glob) which will be work to port to another language.

**Comment by MattIPv4** [comment]
> Maybe we could flatten the repo by removing the ajax/libs/ directories?

I think it’s worth having at least one sub directory so the root of the project is clean. Doesn’t have to be `ajax/libs` though, I just used that as it’s what we already have.

> To me this sounds like what unpkg.com does (which does it on the fly)

unpkg just presents the full npm package as it is in the registry. cdnjs is different in that we allow customisation of the base dir and the file map for which files we should serve.

> Something I just noticed is that the file map relies on the node-glob which will be work to port to another language.

I believe this is just a NodeJS implementation of normal glob logic - I don’t think we’d need to port it, just find a glob library in Go?

> Would we mind if we moved the spec to a Google doc? It's easier for collaboration IMO

Sure thing, I’d like to make it publicly viewable so anyone can see but we can restrict who can comment/write if that works for you?

**Comment by xtuc** [comment]
> I think it’s worth having at least one sub directory so the root of the project is clean. Doesn’t have to be ajax/libs though, I just used that as it’s what we already have.

Agreed.

> I believe this is just a NodeJS implementation of normal glob logic - I don’t think we’d need to port it, just find a glob library in Go?

It's an implementation of the extended glob logic. I just found a Golang library :+1: 

> Sure thing, I’d like to make it publicly viewable so anyone can see but we can restrict who can comment/write if that works for you?

Yes, I can create it. We can publicly share it but only we can collaborate on it. Also we can post it here after, it's just to avoid the back and forth between us.

**Comment by MattIPv4** [comment]
Remaining tasks:

 - Cleanup commit in cdnjs/packages
   - Remove `version` attr
   - Migrate `npmName`/`npmFileMap` to `autoupdate` format
   - Format all JSON files nicely
 - Complete & merge new cdnjs/packages docs (https://github.com/cdnjs/packages/pull/177)
 - After cdnjs/packages docs, mrge new cdnjs/cdnjs docs (https://github.com/cdnjs/cdnjs/pull/13977)

**Comment by MattIPv4** [comment]
New docs are now merged in both repositories, so I am now happy to close this PR as I believe we have completed everything needed to consider the two repositories split. I'll create a follow-up issue in cdnjs/packages regarding the cleanup commit needed there.
