### ISSUE TITLE
[Request][Author] Import loading-attribute-polyfill from npm registry, cc #13520

### ISSUE THREAD

**Issue by mfranzke** [cdnjs/cdnjs#13668]
From adding another polyfill earlier (#12871, commit: 53431addad88e1085c9cffe511ffecf34d5942aa) I've recognized that with an upfollowing commit (bdd4433ab18b3144ac1a4ae9195d55530cf6e6e6) the related files have been initially imported from npm registry.

This commit hasn't been done for my new request with #13520 / PR #13521 - so the polyfills npm repo files and folders haven't been imported to https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/loading-attribute-polyfill so far.

From my understanding, the prerequisites have been fulfilled - the package.json file is valid, it doesn't contain the "version" entry, but all of the other relevant fields.

Could you please support me and check, if there's something else that I need to do and elsewhere just trigger this initial import which seems to have been missed so far?

**Comment by MattIPv4** [comment]
This a more interesting bug @xtuc. There are no previous version in the repo, so the auto-update bot should just handle adding all previous versions.

**Comment by xtuc** [comment]
is this still happening with the new bot?

**Comment by xtuc** [comment]
The old bot has a bug when no previous versions exists. Since the package has been migrated to the new bot does the issue persist?

**Comment by MattIPv4** [comment]
Versions are now present for this lib, closing.
