### ISSUE TITLE
https://cdnjs.com/libraries/Darkmode.js wrong github link

### ISSUE THREAD

**Issue by heydojo** [cdnjs/cdnjs#13666]
https://cdnjs.com/libraries/Darkmode.js has a link to https://github.com/sandoche/darkmode but the project page is actually https://github.com/sandoche/Darkmode.js instead.

I discovered this whilst wanting to check out the project.

**Comment by xtuc** [comment]
Could you please send a PR to address that issue?

**Comment by xtuc** [comment]
Due to the lack of activity I'm closing the issue.
