### ISSUE TITLE
Git auto-update: roundSlider not updating

### ISSUE THREAD

**Issue by soundar24** [cdnjs/cdnjs#13670]
my project is set for **git** [auto update](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/roundSlider/package.json), but the new version is not updated still.

Here I have updated the release for the new version (1.4.0):
https://github.com/soundar24/roundSlider/releases

But still it shows the older version (1.3.3) in cdnjs:
https://cdnjs.com/libraries/roundSlider

Can you please check and let me know the issue?

**Comment by soundar24** [comment]
@MattIPv4 any update on this? this was the blocker for the new release rollout, can you check this with high priority.

**Comment by MattIPv4** [comment]
Not sure what's going on here if I'm honest, this should be updating. @xtuc any ideas?

**Comment by soundar24** [comment]
@MattIPv4 atleast can you do the manual update for this, as of now. since this is really a big blocker for me, because all the demo samples needed the CDN only.

**Comment by MattIPv4** [comment]
Manually adding updates to this repository is not something I'm going to do, I don't have the time and it is a rather painful process due to the size.

**Comment by soundar24** [comment]
@MattIPv4 thanks for the update. so, what can I do now? is it possible to get it resolved in next 4 hours? or do you have any alternate suggestion for me?

**Comment by MattIPv4** [comment]
You are welcome to submit a PR to add the version yourself in this repository, or sit tight and wait for our team to see if we can fix what's going on here, which might take quite a while.

**Comment by xtuc** [comment]
we recommend switching to udpates using npm. Closing for now, feel free to continue to comment

**Comment by MattIPv4** [comment]
I think this should be kept open, so that we have an issue to either track moving this to NPM or to track that git auto-update isn't working for it, so that this can be fixed.

**Comment by xtuc** [comment]
![Screenshot from 2020-06-01 11-07-08](https://user-images.githubusercontent.com/1493671/83398845-0fc4e400-a3f8-11ea-836f-0cf192453994.png)

The new bot pushed the missing versions
