### ISSUE TITLE
On HTTP/3, get "Waiting for https://cdnjs.cloudflare.com"

### ISSUE THREAD

**Issue by paulocoghi** [cdnjs/cdnjs#13677]
On Firefox 72.0.1, Ubuntu 18.04 64bit, when enabling HTTP/3 and trying to access a site that uses CDNJS, like crucial.com, I get `Waiting for https://cdnjs.cloudflare.com` and the loading never finishes, making the site unable to appear (the page remains blank).

As stated [here](https://github.com/cdnjs/cdnjs/issues/11786#issuecomment-581544347), when disabling HTTP/3 on Firefox (inside `about:config`), the issue doesn't occur.

**Comment by MattIPv4** [comment]
@zackbloom / @xtuc do we support http/3? Can we enable it if we don't?

**Comment by paulocoghi** [comment]
@MattIPv4, it seems that Cloudflare is officially [enabling http/3](https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche/) on its services, thus the issue is on their side.

**Comment by MattIPv4** [comment]
Yeah, having tested it, it looks like cdnjs.cloudflare.com is http/3 enabled so this might be some other bug with how they're serving content on that domain. Not really sure and not something I have insight into or control over.

**Comment by xtuc** [comment]
It looks like it sends the Alternative Service header back with h3 option, so I would asusme it has been enabled.

**Comment by MattIPv4** [comment]
Hm, not sure we want to close this yet, I think this might be another issue then, not just that we've got http/3 enabled.

@paulocoghi could you possibly provide a HAR of the request that hangs?

**Comment by paulocoghi** [comment]
@MattIPv4 , sure! I will provide it ASAP!

**Comment by paulocoghi** [comment]
Now it's working. I can't believe this issue is intermittent :confused:

Here is the cdnjs.com's HAR with HTTP/3 enabled:
https://gist.github.com/paulocoghi/8a414562d9d9e3fb901dd526e60e1bae

I will leave HTTP/3 enabled on my browser and, when the issue occurs, I will post a new HAR here.

**Comment by MattIPv4** [comment]
cdnjs.com doesn't have http/3 enabled - I thought this issue was with cdnjs.cloudflare.com?

**Comment by MattIPv4** [comment]
~~I'm going mad, ignore my now deleted comment~~.

Sounds good, a HAR of it failing will be very useful in trying to establish what's going on!

**Comment by xtuc** [comment]
h3 is enabled on cdnjs.cloudflare.com. I strongly suspect that it's a misconfiguratin on your side. Try to upgrade your browser. if the issue persistent please reach out to the Cloudflare support or to sven(at)cloudflare(dot)com.
