### ISSUE TITLE
able to host typescript files

### ISSUE THREAD

**Issue by xtuc** [cdnjs/cdnjs#13689]
@PeterDaveHello are we able to host typescript files?

_Originally posted by @drewfreyling in https://github.com/cdnjs/cdnjs/issues/9346#issuecomment-263045798_

**Comment by MattIPv4** [comment]
Related to https://github.com/cdnjs/new-website/blob/master/webServer/utils/fileType.js which contains the whitelist of all extensions that should be in the Cf whitelist at present.

**Comment by xtuc** [comment]
.ts is now allowed https://cdnjs.cloudflare.com/ajax/libs/hi-sven/1.1.17/index.ts
