### ISSUE TITLE
Odd behaviour with ElFinder

### ISSUE THREAD

**Issue by LeonSebastianCoimbra** [cdnjs/cdnjs#13709]
Hi everybody,

apparently there is an odd behaviour about the build of ElFinder on CDNJS (https://cdnjs.com/libraries/elfinder/): you can see that the latest usable version is the 2.1.50, but you can also see that in the dropdown list of the versions you can also select the 2.1.51, 2.1.52 and 2.1.53....

This is an anomaly, since by default CDNJS should present always the latest version available...

I used libman (microsoft/.net solution to download client side libraries) to download the latest build (2.1.53); to do so, i used the following configuration file (called libman.json):

`

{
  "version": "1.0",
  "defaultProvider": "cdnjs",
  "libraries": [
    {
      "provider": "cdnjs",
      "library": "elfinder@2.1.53",
      "destination": "wwwroot/lib/elfinder2/"
    }
 ]
}
`

Once running the command "libman.exe restore" (from the same directory where the script is), the process starts but then ends claiming:

`

Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Non è stato possibile scaricare la risorsa da "https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.53/sounds /rm.wav" ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
`

It seems to be an authorization problem on some files of the package. Version 2.1.51 and 2.1.52 suffers of the same problem.

Maybe this is the same reason why CDNJS show version 2.1.50 as the latest one downloadable (and with this version it works!!).

I reached the original maintainer of the project (see: https://github.com/Studio-42/elFinder/issues/3117) but he seems to not knowing anything about it...

Can you please look at why the latest 3 builds of elfinder aren't available in CDNJS?

Thanks in advance.

**Comment by MattIPv4** [comment]
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/elfinder/2.1.53

All the files are present.

**Comment by MattIPv4** [comment]
https://cdnjs.cloudflare.com/ajax/libs/elfinder/2.1.53/sounds/rm.wav is not available as .wav is a not a whitelisted extension on the CDN currently.

**Comment by MattIPv4** [comment]
@xtuc any ideas why version hasn't been updated in https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/elfinder/package.json when new versions have been published on cdnjs?

**Comment by MattIPv4** [comment]
Latest version is now shown: https://cdnjs.com/libraries/elfinder
Closing.

**Comment by LeonSebastianCoimbra** [comment]
Confirmed, now it works like a charm!!

Thank you very much.
