### ISSUE TITLE
Please add the select2 4.0.13 library

### ISSUE THREAD

**Issue by pmoerenhout** [cdnjs/cdnjs#13716]
The latest select2 is 4.0.13. See https://github.com/select2/select2

**Comment by MattIPv4** [comment]
@xtuc any ideas why the git auto-update bot hasn't picked this up?

Auto-update config looks to be correct: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/select2/package.json
And 4.0.13 is tagged in the repo: https://github.com/select2/select2/tree/4.0.13/dist

**Comment by pmoerenhout** [comment]
When I check the Github page: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/select2
it says: Cannot retrieve the latest commit at this time.

**Comment by MattIPv4** [comment]
Yeah, that's due to the size of the repo and the incredibly large commit history, GH con't compute it. https://github.com/cdnjs/cdnjs/commit/5dd1bc140fc7b0e0647ff7a587e2c86ad6fd87f6 was the last commit in that directory.

**Comment by olafcm** [comment]
Any progress on this bug?

**Comment by xtuc** [comment]
the updates using git needs to be refactor, we recommend switching to npm if possible

**Comment by kevin-brown** [comment]
Select2 is published on NPM so that should be possible.

Just a heads up that two beta releases have also been published and those have also not been detected.
