### ISSUE TITLE
wasm files are served with the wrong Content-Type

### ISSUE THREAD

**Issue by lovasoa** [cdnjs/cdnjs#13714]
In order for streaming compilation of webassembly modules to work, the files have to be served with the right content-type header.

Currently, they are served with the generic `application/octet-stream` mime type instead of `application/wasm`. 

Reproduction:

```
$ http https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.1.0/dist/sql-wasm.wasm
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Alt-Svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
CF-Cache-Status: DYNAMIC
CF-RAY: 56ec57714c2868b2-CDG
Cache-Control: max-age=30672000
Connection: keep-alive
Content-Length: 1472284
Content-Type: application/octet-stream
Date: Wed, 04 Mar 2020 14:38:33 GMT
ETag: "5e4e6dff-16771c"
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Mon, 22 Feb 2021 14:38:33 GMT
Last-Modified: Thu, 20 Feb 2020 11:31:11 GMT
Served-In-Seconds: 0.001
Server: cloudflare
Strict-Transport-Security: max-age=15780000; includeSubDomains
Timing-Allow-Origin: *
Vary: Accept-Encoding
```

> For this [instantiation] to work, .wasm files should be returned with an application/wasm MIME type by the server.

[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming)

**Comment by MattIPv4** [comment]
cc @xtuc (plus, do we have an update on the content-type issue for package.json files as well?)

**Comment by xtuc** [comment]
fixed 
```
curl -vvv https://cdnjs.cloudflare.com/ajax/libs/hi-sven/1.5.0/index.wasm |& grep content-type                                                                                                                                              
< content-type: application/wasm
```

**Comment by lovasoa** [comment]
Awesome, thanks !

**Comment by ardislu** [comment]
wasm is now served with `application/wasm; charset=utf-8`:
```
curl -vvv https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.1/sql-wasm.wasm |& grep content-type
< content-type: application/wasm; charset=utf-8
```
But `WebAssembly.instantiateStreaming()` requires the MIME type to be `application/wasm` exactly, with no extra parameters. From the [wasm spec](https://webassembly.github.io/spec/web-api/index.html#streaming-modules):
> 3. If mimeType is not `application/wasm`, reject returnValue with a TypeError and abort these substeps.
> Note: extra parameters are not allowed, including the empty `application/wasm;`.

Can the MIME type be reverted to just `application/wasm` like before?

**Comment by tc80** [comment]
Sorry for the delay. This should be fixed now 👍 
```
curl -vvv https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.6.1/sql-wasm.wasm |& grep content-type
< content-type: application/wasm
< x-content-type-options: nosniff
```

**Comment by ardislu** [comment]
Confirmed it's working for me. Thank you!
