### ISSUE TITLE
tsParticles not showing in search

### ISSUE THREAD

**Issue by matteobruni** [cdnjs/cdnjs#13730]
The https://github.com/cdnjs/cdnjs/pull/13705 PR was merged days ago but I still can't find the library in the website.
How long do I have to wait?

**Comment by MattIPv4** [comment]
The current auto-update bot doesn't pick up new libraries added, such as tsParticles.

This will require the new auto-update bot we are working on for the library to be picked up, versioned files added and for it to be indexed in Aloglia for the website.

@xtuc do you want to move this to the new bot?

**Comment by xtuc** [comment]
I moved the package to the new bot. It pushed the last 10 versions.

**Comment by xtuc** [comment]
Launched manually the website update and the package is live https://cdnjs.com/libraries/tsparticles.
