### ISSUE TITLE
Add g2plot

### ISSUE THREAD

**Issue by RaoHai** [cdnjs/cdnjs#13754]
Library name: g2plot
Git repository url: https://github.com/antvis/g2plot
npm package name or url (if there is one): https://www.npmjs.com/package/@antv/g2plot
License (List them all if it's multiple): MIT
Official homepage: https://g2plot.antv.vision

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/g2plot

**Comment by RaoHai** [comment]
👍
