### ISSUE TITLE
cdnjs.cloudflare no longer working

### ISSUE THREAD

**Issue by oxsygen** [cdnjs/cdnjs#13844]
Hi all, anyone has any idea what happen. cdnjs.cloudflare suddenly stop working. 

When you go to https://cdnjs.cloudflare.com/ it shows URL Not Found.

All JS files are not accessible anymore.

**Comment by MattIPv4** [comment]
Hi there @oxsygen,

We're seeing a few reports of this but nothing major. Do you have any other info you can provide about this issue?

Could you possibly share the output from running this command:

```
curl -I https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.min.js
```

The output should look something like:

```
HTTP/2 200 
date: Sun, 19 Apr 2020 10:40:12 GMT
content-type: application/javascript; charset=utf-8
last-modified: Thu, 30 Jan 2020 11:46:11 GMT
etag: W/"5e32c203-16de6"
expires: Fri, 09 Apr 2021 10:40:12 GMT
cache-control: public, max-age=30672000
vary: Accept-Encoding
timing-allow-origin: *
access-control-allow-origin: *
served-in-seconds: 0.004
cf-cache-status: HIT
age: 6894568
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=15780000; includeSubDomains
server: cloudflare
cf-ray: 5866018cbd6369e7-LHR
alt-svc: h3-27=":443"; ma=86400, h3-25=":443"; ma=86400, h3-24=":443"; ma=86400, h3-23=":443"; ma=86400
cf-request-id: 02339f4bf4000069e7b0132200000001
```

Or if can't run that command for any reason, could you head to a page using cdnjs resources (such as cdnjs.com), open the developer tools, head to the network tab, click on one of the cdnjs requests and share a screenshot of the headers shown?

It should look something like this:

![image](https://user-images.githubusercontent.com/12371363/79685743-ddd63480-8232-11ea-806a-941bb459b2de.png)

Thank you!

**Comment by GuskiS** [comment]
@MattIPv4 I'm getting this output:
```
HTTP/2 404 
date: Mon, 27 Apr 2020 08:33:36 GMT
content-length: 400
set-cookie: __cfduid=dc1b22fd42f6d74dcf65d19a3b5cc13f01587976415; expires=Wed, 27-May-20 08:33:35 GMT; path=/; domain=.cdnjs.cloudflare.com; HttpOnly; SameSite=Lax
cf-cache-status: MISS
expires: Mon, 27 Apr 2020 12:33:36 GMT
cache-control: public, max-age=14400
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 58a7331259edb4cc-RIX
cf-request-id: 025c5e3f7a0000b4cc08bf3200000001
```

However, it is working for my colleagues. Tested on Ubuntu 18.04.4 LTS VM and Windows 10.

**Comment by MattIPv4** [comment]
@GuskiS Please could you share the resource URL you're requesting?

**Comment by GuskiS** [comment]
In that post I used your curl command.
The problem is I can't get `https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.5/require.min.js` which is required by JIRA. Can't log in.

**Comment by MattIPv4** [comment]
If possible, could you share a HAR of the failing request? You can do this by having developers tools open in your browser, navigating to the page with the failing resource, then going to the network tab in developers tools and pressing the download icon "Export HAR".

**Comment by GuskiS** [comment]
Here it is: https://gist.github.com/GuskiS/62a978861f4c4495f5e101dcacb2df88
I'm thinking it is failing because of date/time issues on my PC. Could this be related?

**Comment by MattIPv4** [comment]
Hey @GuskiS, thanks for reporting this. We’ve got our team looking at it now to see if they can figure out what’s going on here. I’ll make sure to keep you updated with any progress.

**Comment by GuskiS** [comment]
I got it working. It was issue with my date/time settings.
I recently reinstalled windows and it seems that my WIFI is unable to synchronise clock, however I was able to synch with my mobile network: 
![image](https://user-images.githubusercontent.com/3505777/80361585-deea1000-8889-11ea-8a40-0d9405c11f5e.png)

and that fixed the issue.

What made me think of this is that I wasn't able to make purchases online (it said my date/time settings where wrong). I also remembered that there are issues with SSL certificates if date/time is wrong. So it might something similar to this CDN 🤔 

I'm also going to remove that gist as it might contain some sensitive information.

**Comment by xtuc** [comment]
@GuskiS could you please send me the HAR to sven AT cloudflare.com?

**Comment by pcmaniac23** [comment]
Hi, I am experiencing the same issue. I get 404 when I access the URL: https://cdnjs.cloudflare.com/
Also, when I access (or a website that I try to access uses libraries hosted on cdnjs.cloudflare.com such as: https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.5/ace.js I get a 404 and this breaks the website for me. Interestingly, the website is accessible to other people. This happens to all the PC/Laptops in my house as well. So this doesn't seem to be just an issue on my own computer.

**Comment by MattIPv4** [comment]
@pcmaniac23 [a HAR](https://github.com/cdnjs/cdnjs/issues/13844#issuecomment-619864568) would be really useful if you could, please.

**Comment by pcmaniac23** [comment]
@MattIPv4 
Hi Matt, thanks for your quick attention!

Here's the HAR file of an attempt at trying to access coliru.stacked-crooked.com which has the issue of 404 when the site tries to get ace.js v1.2.5 from cdnjs.cloudflare.com


[coliru.stacked-crooked.com_ace_js_404.har.zip](https://github.com/cdnjs/cdnjs/files/4567632/coliru.stacked-crooked.com_ace_js_404.har.zip)

**Comment by pcmaniac23** [comment]
@MattIPv4 
Hi Matt,

I brought one of the laptops in my house which has this issue to the office today and tried to access the problematic site (Coliru) using the office's network, and the site works correctly. For your reference, here's the HAR file for this successful session:

[coliru.stacked-crooked.com_ace_js_200.har.zip](https://github.com/cdnjs/cdnjs/files/4573633/coliru.stacked-crooked.com_ace_js_200.har.zip)

I suspect this is either a CDN configuration issue, or an ISP related issue?

**Comment by MattIPv4** [comment]
Hey @pcmaniac23,

That's certainly interesting. This does seem to point to a network-specific issue.

Are you using a custom DNS configuration on your home network?
Do you have any form of proxy configured on your home network?
What ISP do you use for your home network, maybe they're doing something funky?

**Comment by xtuc** [comment]
I can confirm that cdnjs was working as intended. Please clear your cache and retry. Make sure that your proxy is correctly configured if you use one.

Feel free to open a new issue if you see an isse
