### ISSUE TITLE
404 vs 200 OK

### ISSUE THREAD

**Issue by rarkins** [cdnjs/cdnjs#13895]
What is the expected API response code when packages aren't found?

e.g. https://api.cdnjs.com/libraries/thislibdoesnotexist returns a 200 OK with `{}` in the body - is that expected?

**Comment by MattIPv4** [comment]
Hey @rarkins,

We're currently in the process of rather slowly rolling out a new API server (https://github.com/cdnjs/api-server).

In the case of a non-existent library, the old API will response with a 200 OK response that contains an empty object for the body. The new API will be somewhat more normal and will return a 404 response, as well as an error message in the JSON body.

Relevant code in the new API server: https://github.com/cdnjs/api-server/blob/master/tests/suite/library.js#L315-L339 & https://github.com/cdnjs/api-server/blob/master/routes/library.js#L87-L100

Hope that helps!

**Comment by rarkins** [comment]
Thanks @MattIPv4  - we must have missed that in the initial testing. I noticed today that html files referencing non-existent libraries were treating it as a registry error instead of user error.

**Comment by rarkins** [comment]
@MattIPv4

**Comment by rarkins** [comment]
@MattIPv4 FYI: I observed a spate of opening and closing of Renovate PRs for cdnjs libraries. Without a forensic log investigation, this *most likely* indicates that the cdnjs API is alternating between "found" and "not found" responses over time. e.g. if Renovate finds an update for a package one hour, but an hour later the API says "that dependency doesn't exist", then the update PR from the previous hour will get closed automatically. I've seen this happening a lot on one of my own repos:

![image](https://user-images.githubusercontent.com/6311784/80205777-83bae200-862b-11ea-9a1b-e2138e9e0c5e.png)

There's still a possibility it's a Renovate bug, but in case you think it could be caused by the "slowly rolling out a new API server" and would like to troubleshoot it, please let me know.

**Comment by MattIPv4** [comment]
@rarkins Yeah, we might've caused this, sorry!

Overnight the new API had some missing libraries and so it would've been responding with a 404 if a request for a missing library made it to the new origin. We've now fixed this, so both the old & new API servers have the same set of data.

On genuinely missing libraries, you'll still see two different responses until the rollout is complete, with the old API giving a 200 OK empty object & the new API giving a 404 not found error object.

**Comment by rarkins** [comment]
@MattIPv4 thanks - good to know. I updated our logic yesterday to treat both 404 as well as empty 200 OK as the same, so no problem there. I don't log at such a detailed level to know which of the two it was causing the problems in the screenshot, however it sounds like it was probably the new API returning 404. I'll keep an eye on it and if it happens again it sounds like one of us still has a bug :)

**Comment by MattIPv4** [comment]
👍 We definitely had some missing data in the new API overnight, other folks noticed it with Libman failing to upate. So I'd guess that's what caused this to.

Happy to keep digging further if it happens again!
