### ISSUE TITLE
jquery and awesome-bootstrap-checkbox

### ISSUE THREAD

**Issue by D5T** [cdnjs/cdnjs#13897]
Getting errors:
```
libman.json: [LIB018] "jquery@3.4.1" does not contain the following: jquery.min.js
Valid files are 
libman.json: [LIB002] The "awesome-bootstrap-checkbox@1.0.2" library could not be resolved by the "cdnjs" provider
```

**Comment by MattIPv4** [comment]
Hi there,

We're currently in the process of rolling out a new API server and it looks like you encountered a couple of the bugs we inadvertently introduced and hopefully have now resolved.

Please try again after waiting a while for the cache to clear and let us know how it goes!

To explain the two issues:

```
libman.json: [LIB018] "jquery@3.4.1" does not contain the following: jquery.min.js
Valid files are 
```

For some odd reason, the API was returning the jquery library but saying it had no files. We've now pushed up a fix so it should be listing the files correctly!

```
libman.json: [LIB002] The "awesome-bootstrap-checkbox@1.0.2" library could not be resolved by the "cdnjs" provider
```

We believe this was a slight hiccup with one of our API origins that was missing some recent library data. We’ve just updated this and it should now be available again.

Hope that helps!

**Comment by MattIPv4** [comment]
No further progress, closing.
