### ISSUE TITLE
Update shepherd.js

### ISSUE THREAD

**Issue by rwwagner90** [cdnjs/cdnjs#13902]
I believe this is the config we need:

```json
{
  "name": "shepherd.js",
  "description": "Guide your users through a tour of your app.",
  "keywords": [
    "site tour",
    "tour",
    "tutorial",
    "shepherd"
  ],
  "authors": [
    "Adam Schwartz <adam.flynn.schwartz@gmail.com>",
    "Zack Bloom <zackbloom@gmail.com>"
  ],
  "maintainers": [
    "Robert Wagner <rwwagner90@gmail.com>",
    "Chuck Carpenter <chuck@shipshape.io>"
  ],
  "license": "MIT",
  "homepage": "https://shepherdjs.dev",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/shipshapecode/shepherd.git"
  },
  "npmName": "shepherd.js",
  "npmFileMap": [
    {
      "basePath": "dist",
      "files": [
        "*.@(js|css|map)"
      ]
    }
  ],
  "filename": "dist/js/shepherd.js"
}
```

**Comment by xtuc** [comment]
Please send a PR and provide more context. Closing for now

**Comment by rwwagner90** [comment]
@xtuc please do not close. I was told to open this by @MattIPv4 and provided what I think is the correct config. What more context do you need? I cannot do a PR because this repo is like 10 gb or more and git cannot handle cloning it.

**Comment by xtuc** [comment]
Ok, sure. we are currently changing the way we add/update packages, such that you don't need to touch the main big repo. Could you please update the configuration in https://github.com/cdnjs/packages?

**Comment by rwwagner90** [comment]
Closed by https://github.com/cdnjs/packages/pull/43
