### ISSUE TITLE
Update p5.js to v1.0.0 (fix bad update)

### ISSUE THREAD

**Issue by jeremydouglass** [cdnjs/cdnjs#13912]
p5.js v1.0.0 was committed by robocdn in eb66850
However, the commit was wrong -- the files are from v0.10.2, not 1.0.0.

I will submit a pull request to fix this.

I am not the author, but I will ask the core devs to comment / review on this issue/PR.

**Comment by lmccart** [comment]
confirming these changes are correct, thank you @jeremydouglass!

**Comment by xtuc** [comment]
@lmccart just to make sure I understand... are these changes correct or incorrect?

we can indeed see `v0.10.2` in `ajax/libs/p5.js/1.0.0/p5.min.js` https://github.com/cdnjs/cdnjs/commit/eb66850e82ddc0b0740a078497b2e9d829eedad4#diff-123a7de895e2164b72ab1504b916a937R1

**Comment by xtuc** [comment]
on npm https://unpkg.com/browse/p5@1.0.0/lib/p5.min.js has v0.10.2 in the header, nothing to do with cdnjs
