### ISSUE TITLE
why package version not show all in cdnjs ?

### ISSUE THREAD

**Issue by winddies** [cdnjs/cdnjs#13945]
![image](https://user-images.githubusercontent.com/25814552/81290211-3e21fe80-909a-11ea-8e2f-065b04c1ba1d.png)
hi, Why not show all npm package  versions ？

Is it because the time of some version is too long ? 
![image](https://user-images.githubusercontent.com/25814552/81290494-c0122780-909a-11ea-9102-8dd006826d62.png)

**Comment by xtuc** [comment]
which package are you looking at?

**Comment by winddies** [comment]
the package of 1.x not show in cdnjs, i want to know the reason.

**Comment by winddies** [comment]
and version before 2.2.1 not show.  I want to know what is the reason, of course, I don’t have to show it all

**Comment by winddies** [comment]
@xtuc

**Comment by xtuc** [comment]
could you please share link to the website?

**Comment by winddies** [comment]
you can see this [pr](https://github.com/cdnjs/cdnjs/pull/13904)

**Comment by MattIPv4** [comment]
As far as I know, the auto-update bot will pull in the 10 most recent versions when a library is added.

**Comment by winddies** [comment]
so, can you help to add other version to library ?

**Comment by winddies** [comment]
@MattIPv4

**Comment by MattIPv4** [comment]
@winddies We no longer support manually adding versions, so unless the bot can add them there isn't anything we can do.

@xtuc could we get the bot to run through some older versions of this lib?

**Comment by MattIPv4** [comment]
No progress, not worth bringing in older versions, closing.
