### ISSUE TITLE
FileSaver.js broken

### ISSUE THREAD

**Issue by jamierocks** [cdnjs/cdnjs#13946]
Hey :)

I was looking to grab [FileSaver.js](https://github.com/eligrey/FileSaver.js) from cdnjs, however I observed that I was getting 404 issues on `https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.2/FileSaver.min.js`.

The issue is also on the main library page - https://cdnjs.com/libraries/FileSaver.js

**Comment by jamierocks** [comment]
Looks like the issue is that is marked do not build, yet the bot still updates it https://github.com/cdnjs/cdnjs/commit/8c80b13287fab6c0dd61cb4c10c937f02302d614

**Comment by MattIPv4** [comment]
@xtuc this seems rather odd. The bot has updated the version for FileSaver.js and has pushed that version to Algolia, but hasn't committed any files for that version. https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/FileSaver.js

**Comment by MattIPv4** [comment]
Ah, looking at the NPM package, it seems the auto-update config we have no longer matches any files, which is why nothing has been committed.

@xtuc I think we should add logic so that if no files match, we just ignore that version and try again next time?

**Comment by xtuc** [comment]
Some versions were created locally by the old bot and lost.
I cleaned and the new bot pushed them
![Screenshot from 2020-05-11 18-59-05](https://user-images.githubusercontent.com/1493671/81594890-84889d80-93b9-11ea-8a66-d128d112572b.png)
