### ISSUE TITLE
404

### ISSUE THREAD

**Issue by debugd** [cdnjs/cdnjs#13959]
These seem to be gone all of a sudden

https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.25.0/moment.min.js.map

https://cdnjs.cloudflare.com/ajax/libs/emojionearea/3.4.1/emojionearea.min.map

**Comment by xtuc** [comment]
what do you mean by "all of a sudden"? the same URL with that version used to return a map? or the previous versions used to?

**Comment by debugd** [comment]
Correct, it did. These URLs stopped working (I’d say within the last few weeks?) we just noticed.

**Comment by MattIPv4** [comment]
We never remove files from cdnjs -- have you changed version of these libraries?

**Comment by debugd** [comment]
Nope. They are no longer displayed on the site either:

https://cdnjs.com/libraries/moment.js/2.25.0

https://cdnjs.com/libraries/emojionearea/3.4.1

**Comment by MattIPv4** [comment]
This is the commit where 2.25.0 was added: https://github.com/cdnjs/cdnjs/commit/39efd18f70f2992403be88c7025dbc4e59c410dc

If you browse the repo at this point you can see 2.25.0 without map files: https://github.com/cdnjs/cdnjs/tree/39efd18f70f2992403be88c7025dbc4e59c410dc/ajax/libs/moment.js/2.25.0/

This is the parent commit (the commit before this): https://github.com/cdnjs/cdnjs/commit/31671e44f1554b577f00635b5881901de940f5a3

If you browse the repo at this point you can see 2.25.0 didn't exist: https://github.com/cdnjs/cdnjs/tree/31671e44f1554b577f00635b5881901de940f5a3/ajax/libs/moment.js/2.25.0/

Therefor, I am confident in saying map files never existed for 2.25.0

**Comment by MattIPv4** [comment]
No progress, closing.

**Comment by DanAtkinson** [comment]
Hi Matt,

Is it possible then to add the missing `.map` files? Is this something I can submit a PR for?

Which is when I first noticed the console warnings re missing .map files issue also occurs on [2.26.0](https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.26.0/moment.min.js) where the .map is referenced at the bottom, but then doesn't actually exist.

Looking at the `moment.js` repo for [`2.26.0`](https://github.com/moment/moment/tree/2.26.0/min), the .map file is referenced and also exists.

Thanks, Dan

**Comment by MattIPv4** [comment]
Sure thing -- you'd just need to update the glob strings in https://github.com/cdnjs/packages/blob/master/packages/m/moment.js.json to include the .map files, then once merged and new versions would include the .map files on cdnjs :)

**Comment by MattIPv4** [comment]
(We can't add .map files for existing versions, as we do not accept PRs to this repository, only configuration updates in cdnjs/packages)

**Comment by DanAtkinson** [comment]
Ah. It kinda sucks that you can't fix the problem for current versions (although absolutely makes sense from a security perspective). The issue with past versions is probably something that you should perhaps look to resolve yourselves then, given that it was the @robocdnjs account that created the (seemingly incorrect) package mapping in the first place.

Still, I'll have a look at the `moment.js.json` file you linked, and compare it to other libraries as the format is not something I'm familiar with and don't want to break something.

Is there an integration tool that I can test it locally against?

**Comment by MattIPv4** [comment]
There isn't really any issue in the past, we just had the package configured to not include map files -- a cdnjs maintainer in the past made that decision.

If you want to test glob strings, I recommend using https://do.co/glob-tool - you can easily import an NPM package's files and then test a glob string against the files :)

**Comment by DanAtkinson** [comment]
Thanks. It's not the glob strings I'm concerned about but the actual processing of a package based on the mapping file itself once I've made the changes.

I've checked the glob itself and have done a [PR](https://github.com/cdnjs/packages/pull/251) to resolve this for future versions.

![image](https://user-images.githubusercontent.com/23440/84518685-fa3d9d00-acc8-11ea-82ab-59b3078104ef.png)
