### ISSUE TITLE
New version of d3plus.js available

### ISSUE THREAD

**Issue by username101111** [cdnjs/cdnjs#13966]
There is a new version of d3plus available that is not yet on cdnjs. Is there a way to make version 2 available. Thanks! Currently 1.5 k stars on github

https://github.com/alexandersimoes/d3plus/tree/2.0

**Comment by xtuc** [comment]
Thanks for raising the issue.

The bot wasn't able to process those versions I manually restarted the bot.

**Comment by MattIPv4** [comment]
It looks like the file map won't match anything from the 2.x releases on NPPM, creating a PR to address that.

**Comment by xtuc** [comment]
@MattIPv4 I was about the mention that, the bot will push empty versions...

**Comment by MattIPv4** [comment]
Ah yes, we should fix that :)

**Comment by username101111** [comment]
Thanks for working on this. I seems that now the relevant page can not be accessed. https://cdnjs.com/libraries/d3plus says "d3plus version not found!" and the link https://cdnjs.cloudflare.com/ajax/libs/d3plus/2.0.0-alpha.25/d3plus.min.js also does not work

**Comment by MattIPv4** [comment]
Ah shoot, looks like the bot committed versions with this bug present.
