### ISSUE TITLE
Confusion with urls between cdnjs.com and cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by zerocarbthirty** [cdnjs/cdnjs#13960]
Hello, I noticed that there are some sites that use cdnjs like this:

https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js

and there is something a bit odd with the SSL certificate on cdnjs.cloudflare.com so I wanted to just rewrite the links to use

https://cdnjs.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js 

but on cdnjs.com that link isn't valid even though it is valid on cdnjs.cloudflare.com

What is considered canonical and why would the paths differ?

**Comment by MattIPv4** [comment]
`cdnjs.com` is the marketing site for cdnjs, designed for human consumption.

`cdnjs.cloudflare.com` is the CDN that contains the library files, this should be considered the canonical hostname for CDN assets.

**Comment by xtuc** [comment]
> SSL certificate on cdnjs.cloudflare.com
Could you please elaborate?

you can use cdnjs.com to restrieve the file https://ajax.cdnjs.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js. However, it's recommended to use the main cdnjs.cloudflare.com domain.

**Comment by MattIPv4** [comment]
No progress, closing. If you continue to see SSL issues with `cdnjs.cloudflare.com`, please create a new issue so that we can investigate further.
