### ISSUE TITLE
[Request] Fix Chart.js capitalization

### ISSUE THREAD

**Issue by benmccann** [cdnjs/cdnjs#13962]
Hi, I'm a maintainer of Chart.js. We had a user that was complaining about the capitalization of https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Chart.js. I don't think it should be capitalized and am not sure where that's coming from. The package name on npm is not capitalized: https://www.npmjs.com/package/chart.js. Can you change it to lowercase?

**Comment by MattIPv4** [comment]
We can't remove or change old versions, so changing the name for future versions would end up with a naming clash between the two cases (can be done, git just gets angry).

@xtuc thoughts?

**Comment by MattIPv4** [comment]
It's worth also noting, that to fix the case, we'd essentially be adding a new library as `chart.js`, so cdnjs would then have both `Chart.js` and `chart.js`, which I think might possibly be more confusing, especially if we disable auto-update for one of them.

**Comment by MattIPv4** [comment]
I do wish we could simply make all libraries lowercase and be done with it, but unfortunately, that bridge has already be burned as previous maintainers have added two different libraries with the same name but different casing.

**Comment by benmccann** [comment]
I'm not sure how auto-update works. I'm assuming you wouldn't auto-update if there's a new semantic version? I don't know if it's worth it, but if we were going to do it, this would be the time because our next release will be Chart.js 3.0.

**Comment by MattIPv4** [comment]
That might be an option then, disable auto-update for `Chart.js`, and then add `chart.js` ready for 3.0. However, auto-updating will backfill, so we'd still have duplicate versions between `Chart.js` and `chart.js` for versions prior to when auto-update is disabled on `Chart.js`.

(auto-update simply listens to the configured NPM package and mirrors all published versions, based on the file map we have setup)

**Comment by MattIPv4** [comment]
And, of course, this adds another git issue for down the road, where we have two dirs named the same thing with different cases.

**Comment by MattIPv4** [comment]
I don't think this is worth the complexity involved and the confusion this change would likely cause in the future with having two copies of the library, as the library itself uses the capitalized name, I think keeping that on cdnjs is fine given the alternative.
