### ISSUE TITLE
nprogress version not found!

### ISSUE THREAD

**Issue by san-kumar** [cdnjs/cdnjs#13973]
If I search nprogress and click the link I get this error: "nprogress version not found!"

The link is: https://cdnjs.com/libraries/nprogress

Can you please check?

![screenshot](https://i.imgur.com/saMfXhY.png)

Thanks.

**Comment by san-kumar** [comment]
By the way, it says version is `1.0.0-1` on there while the latest version for nProgress is 0.2.0 and this works just fine:

https://cdnjs.cloudflare.com/ajax/libs/nprogress/0.2.0/nprogress.min.js

**Comment by MattIPv4** [comment]
Looks like this was due to a bug with the auto-update bot, it updated the version for the library but did not commit any version files.
