### ISSUE TITLE
[Request] Add wikibase-sdk

### ISSUE THREAD

**Issue by maxlath** [cdnjs/cdnjs#13976]
**Library name**: wikibase-sdk
**Git repository url**: https://github.com/maxlath/wikibase-sdk
**npm package name or url (if there is one)**: wikibase-sdk
**License (List them all if it's multiple)**: MIT
**Official homepage**: https://github.com/maxlath/wikibase-sdk#readme

Associated issue: https://github.com/maxlath/wikibase-sdk/issues/30

**Comment by MattIPv4** [comment]
Hi there,

This package contains no bundled version, and only has a version designed to be used in Node.js relying on exports and imports.

Please consider including a bundled version of the library ready for use on the web in your package, so that we can add it to cdnjs.

**Comment by maxlath** [comment]
[bundles are made available on the `dist` branch in the `dist` folder](https://github.com/maxlath/wikibase-sdk/tree/dist/dist), could that work?

**Comment by MattIPv4** [comment]
If we are going to use git as the auto-update source, this is done based on tags in the repository. It seems that the tags are currently for the master branch, which doesn't contain the dist files. https://github.com/maxlath/wikibase-sdk/tree/v7.4.3/

**Comment by maxlath** [comment]
we could add dist tags on the pattern `v${version}-dist`, like [`v7.4.3-dist`](https://github.com/maxlath/wikibase-sdk/releases/tag/v7.4.3-dist)?

**Comment by MattIPv4** [comment]
I don't believe that'd work, as the bot relies on valid semver for tags that it'll treat as versions to use.

**Comment by maxlath** [comment]
I moved the valid semver tag to identify the dist commit from now on (ex: [`v7.4.6`](https://github.com/maxlath/wikibase-sdk/releases/tag/v7.4.6))
