### ISSUE TITLE
[Request Update] SpinKit

### ISSUE THREAD

**Issue by sunshineplan** [cdnjs/cdnjs#13974]
The newest version is 2.0.1, but cdnjs only has version 1.2.5.

https://github.com/tobiasahlin/SpinKit

**Comment by sunshineplan** [comment]
The problem seems still remain after fix.

**Comment by MattIPv4** [comment]
This was an underly issue from the auto-update bot, we've just cleaned this up and the new versions have been pushed. :)

**Comment by sunshineplan** [comment]
Thank you. Now I can see the latest version on the site.
