### ISSUE TITLE
api and package descriptions are broken currently?

### ISSUE THREAD

**Issue by CameronAM** [cdnjs/cdnjs#13985]
As of 2020-12-06 0107Z the API and description pages for a number of packages appears to be down when accessed from Sydney: eg. https://cdnjs.com/libraries/react-dom is reporting "Application Error", as is https://cdnjs.com/api.

This breaks libman package restorations in Studio, at least.

**Comment by MattIPv4** [comment]
Using #13986 to track this issue.
