### ISSUE TITLE
Problem when embedding code

### ISSUE THREAD

**Issue by batata004** [cdnjs/cdnjs#13996]
Hi, 

Sometimes I cant use a CDN do load the external file inside a website, so I embed the CODE itself on the page. Whe have a conditional on our CMS that does this in PHP:

```
if (check_something) {

    echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/vegas/2.5.1/vegas.min.css"></script>';

}
else{

    echo '<script>' . file_get_contents("https://cdnjs.cloudflare.com/ajax/libs/vegas/2.5.1/vegas.min.css") . '</script>';

}
```

The first conditional works fine, however the second does not because in the "https://cdnjs.cloudflare.com/ajax/libs/vegas/2.5.1/vegas.min.css" there is a code like:

`background:url(overlays/02.png)`

If I embed the CDN code on the website, the external resources downloaded from it will point to my own domain, instead of the CDN domain.

So I ask you: is there a flag like `absolutePath` that I could use like `https://cdnjs.cloudflare.com/ajax/libs/vegas/2.5.1/vegas.min.css?absolutePath=` so the relatives paths become absolute ones?

**Comment by MattIPv4** [comment]
Hi there,

We do not provide any such option, cdnjs resources are designed to be included from the CDN origin, not from your own origin.

We also could not provide such a URL parameter as it would invalidate SRI hashes & would modify the contents of the resource, which is not something we ever do under any circumstances.
