### ISSUE TITLE
jquery 3.4.1 core.min.js broken

### ISSUE THREAD

**Issue by fedejousset** [cdnjs/cdnjs#13999]
Hi,

Apologies in advance if this is not the right place for this but I couldn't find anywhere else to report it. A few hours ago we noticed the jquery core.min.js 3.4.1 link is returning a beautiful 404 error:

![image](https://user-images.githubusercontent.com/20836210/88202489-dc0c7a80-cc40-11ea-8a3b-fe4927fcc94d.png)

Link to the specific jquery CDNJS version: https://cdnjs.com/libraries/jquery/3.4.1
Link to the file which is returning the 404: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/core.min.js

I can confirm this was previously working as the project I'm working on has been using this version since October 2019

Thank you!

**Comment by tc80** [comment]
Yep we broke core.min.js, thanks for letting us know. Should be fixed really shortly

**Comment by MattIPv4** [comment]
I'm guessing this a local cache issue from the earlier issue noted in https://github.com/cdnjs/packages/issues/352 -- I can't see the `core.min.js` listed in the jQuery version linked on my end anymore.

**Comment by fedejousset** [comment]
Hello there, is there any update on this? 

As @MattIPv4  mentioned I can't see the core.min.js listed anymore for that version:

![image](https://user-images.githubusercontent.com/20836210/88291443-24cf3c80-ccf0-11ea-8a4a-66c3f8e99067.png)

**Comment by MattIPv4** [comment]
I'm not sure what update you're expecting here -- this file doesn't exist on the CDN, and never has?

**Comment by xtuc** [comment]
The file was listed on the website but didn't actually exits on the cdn, we fixed the website

**Comment by MattIPv4** [comment]
Running `git log -- ajax/libs/jquery/3.4.1/core.min.js` in a full clone of this repo confirms that the file has never existed.
