### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH on cdnjs.cloudflare.com

### ISSUE THREAD

**Issue by lucasRolff** [cdnjs/cdnjs#14006]
In Google Chrome Version 84.0.4147.125 (Official Build) (64-bit) on OS X, when accessing cdnjs.cloudflare.com - e.g. to load https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js - then I get:

```
This site can’t provide a secure connection
cdnjs.cloudflare.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

In Firefox 79.0 (64-bit) I get:

```
Secure Connection Failed

An error occurred during a connection to cdnjs.cloudflare.com. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP
```

ssllabs.com also seems to not like it:

![https://snaps.hcdn.dk/aAeXnUXhW6mbJQC7QYULdTV037J2RKKQoZ3FZLxZkH.png](https://snaps.hcdn.dk/aAeXnUXhW6mbJQC7QYULdTV037J2RKKQoZ3FZLxZkH.png)

The SSL Version/cipher mismatch obviously causes JS libraries to not load, breaking things.

Yes I agree that applications should have a fallback mechanism for all the libraries they use and switch to them automatically in case cdnjs or similar is unavailable.

However, as an end-user, it's often hard to make software people change, and they'll often forget this anyway :)

**Comment by xtuc** [comment]
Please follow https://status.cdnjs.com/incidents/yv1ptjhnp6ky. We are working ont it

**Comment by NqCompiler** [comment]
can you tell us how long it will take at least? I am considering to use a different cdn for the time being if its gonna take more than 1 or 2 hours.
Thanks!

**Comment by xtuc** [comment]
@NqCompiler you can replace cdnjs.cloudflare.com with ajax.cdnjs.com for now. will fix but not recommended

**Comment by xtuc** [comment]
Fixed
