### ISSUE TITLE
twitter-bootstrap 4.5.2 is missing a file

### ISSUE THREAD

**Issue by thoughtrefraction** [cdnjs/cdnjs#14003]
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/scss/_alert.scss
Returns a 404. This blocks the installation on Visual Studio 2019.

**Comment by tc80** [comment]
Strange. Looking into it now. The file extension `.scss` [should not be ignored](https://github.com/cdnjs/api-server/blob/master/utils/files.js)

**Comment by tc80** [comment]
Weird! twitter-bootstrap 4.5.2 has [no scss directory](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/twitter-bootstrap/4.5.2) for some reason.

However, it is on disk:
```
tcaslin@cdnjs-bot-6:/cdnjs-sven/cdnjs/ajax/libs/twitter-bootstrap/4.5.2/scss$ ls
_alert.scss            _buttons.scss       _forms.scss        _media.scss       _popover.scss   _toasts.scss       vendor
_badge.scss            _card.scss          _functions.scss    mixins            _print.scss     _tooltip.scss
bootstrap-grid.scss    _carousel.scss      _grid.scss         _mixins.scss      _progress.scss  _transitions.scss
bootstrap-reboot.scss  _close.scss         _images.scss       _modal.scss       _reboot.scss    _type.scss
bootstrap.scss         _code.scss          _input-group.scss  _navbar.scss      _root.scss      utilities
_breadcrumb.scss       _custom-forms.scss  _jumbotron.scss    _nav.scss         _spinners.scss  _utilities.scss
_button-group.scss     _dropdown.scss      _list-group.scss   _pagination.scss  _tables.scss    _variables.scss
```

**Comment by tc80** [comment]
Yes it is gitignored [here](https://github.com/cdnjs/cdnjs/blob/master/.gitignore#L299).
@MattIPv4 can we remove `.scss` from the `.gitignore` considering it is included in our [allowlist](https://github.com/cdnjs/api-server/blob/master/utils/files.js#L13)?

```
tcaslin@cdnjs-bot-6:/cdnjs-sven/cdnjs/ajax/libs/twitter-bootstrap/4.5.2/scss$ git check-ignore -v _alert.scss 
.gitignore:299:/ajax/libs/*/*/**/*.scss	_alert.scss
```

**Comment by tc80** [comment]
@thoughtrefraction thanks for making an issue! 😄  
To be honest I'm surprised this problem hasn't come up before...

Will be a couple hours before we can get around to fixing this

**Comment by MattIPv4** [comment]
Should I just remove all the extension ignore lines? The CDN will filter anyway before serving, and glob configurations for packages should only pick up the files they need.

**Comment by thoughtrefraction** [comment]
Thanks - first time user of CDNJS. I realized I didn't need the scss files, and like @MattIPv4 said, specified only the files I need. It is an inconsistency as they are in the default file list, though.

**Comment by thoughtrefraction** [comment]
Thanks - first time user of CDNJS. I realized I didn't need the scss files, and like @MattIPv4 said, specified only the files I need. It is an inconsistency as they are in the default file list, though.

**Comment by thoughtrefraction** [comment]
Thanks - first time user of CDNJS. I realized I didn't need the scss files, and like @MattIPv4 said, specified only the files I need. It is an inconsistency as they are in the default file list, though.

**Comment by thoughtrefraction** [comment]
Thanks - first time user of CDNJS. I realized I didn't need the scss files, and like @MattIPv4 said, specified only the files I need. It is an inconsistency as they are in the default file list, though.

**Comment by thoughtrefraction** [comment]
Thanks - first time user of CDNJS. I realized I didn't need the scss files, and like @MattIPv4 said, specified only the files I need. It is an inconsistency as they are in the default file list, though.
