### ISSUE TITLE
[Feature Request] Single request URL for a chain of libraries

### ISSUE THREAD

**Issue by nikhiljohn10** [cdnjs/cdnjs#14002]
#### Single request URL for a chain of libraries.

> The same feature is implemented in Google fonts as it is given below:
> 
> `<link href="https://fonts.googleapis.com/css2?family=Recursive:wght@400;700&family=Roboto:wght@300;400&display=swap" rel="stylesheet">`

This can be a similar format for cdnjs.

`<link href="https://cdnjs.cloudflare.com/ajax/libs/css?load=twitter-bootstrap@4.5.0:bootstrap.min.css;photoswipe@4.1.3:photoswipe.min.css,default-skin/default-skin.min.css;" rel="preload" as="style" onload="this.onload=null;this.rel='stylesheet'">`

`<script src="https://cdnjs.cloudflare.com/ajax/libs/js?load=jquery@3.5.1:jquery.min.js;photoswipe@4.1.3:photoswipe.min.js,photoswipe-ui-default.min.js;" defer type="text/javascript"> `

When this request is received by the server, query is parsed to create a JSON object. Using this object, server will retrieve all the specific libraries requested and concatenate all of them in the same order as it is requested.

The only restriction is the CSS & JS can not be mixed up in same request as it can not be loaded by the same HTML tag. Also, Images cannot be requested in the same way. But map files can be requested in a similar way in future versions if really needed.

### How the feature is useful
This could decrease the request count. When all libraries needed at loaded in a single request, there will not be any blocking requests and it increases the web performance of the website as part of optimization.

**Comment by MattIPv4** [comment]
Hi there,

Thanks for the suggestion, however, this is not something that cdnjs will be implementing. We have a huge focus on security and as such always encourage folks to include their libraries with SRI hashes to verify the contents on each fetch/load.

Providing a dynamic endpoint for loading libraries would not allow for easy SRI integration and so this isn't something we'd like to add and encourage folks to use.
