### ISSUE TITLE
Resource not found raven-js@3.*

### ISSUE THREAD

**Issue by SChetwynd** [cdnjs/cdnjs#14016]
Hi

I have some projects with dependencies on the raven js library, when attempting to use these resouces I get a 404 resource not found error:
https://cdnjs.com/libraries/raven.js/raven-js@3.27.0
https://cdnjs.com/libraries/raven.js/raven-js@3.26.4
https://cdnjs.com/libraries/raven.js/raven-js@3.26.3

Versions before this, which do not have the raven-js@ prefix seem to work.

**Comment by xtuc** [comment]
The files are in the git repo:
- https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/raven.js/raven-js%403.26.3/raven.min.js
- https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/raven.js/raven-js%403.26.4/raven.min.js
- https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/raven.js/raven-js%403.27.0/raven.min.js

there's probably an issue when serving them

**Comment by xtuc** [comment]
This has been fixed, the raven.js URLs are now available
