### ISSUE TITLE
Consider adding a "latest" version access point

### ISSUE THREAD

**Issue by michel4j** [cdnjs/cdnjs#14017]
For example, "https://cdnjs.cloudflare.com/ajax/libs/jquery/latest/jquery.min.js" would point to the latest jquery version available.

**Comment by drewfreyling** [comment]
How would you handle breaking changes in your application when jquery do major version bumps for example?

**Comment by MattIPv4** [comment]
`latest` is not something that we will ever support. It causes potential issues for users not expecting breaking changes in major version bumps, but more importantly, does not work with SRI which is something we strongly encourage everyone to use as part of using the CDN securely. (It also starts to defeat the point of cdnjs as the cache lifetime on `latest` would have to be far less).

**Comment by DearTanker** [comment]
Although this is a commonplace question, why is it always mentioned? I think one reason is that there are many pure image projects such as Twemoji svg. Not only will the latest version not have any impact on the project, but it may also bring a better look and feel, and even greatly reduce the frequency of updating the old project code for the new version of the image. For scripts such as js, the latest version is very likely to cause the old project to fail.

Therefore, it seems to be a lot of work to provide the latest option for different projects.
