### ISSUE TITLE
"resource not found" for library

### ISSUE THREAD

**Issue by viktorcos** [cdnjs/cdnjs#14013]
We have a dependency on this library: https://cdnjs.com/libraries/startbootstrap-sb-admin-2/3.3.7+1 , but the library links returns "resource not found". 

For example: https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.js

Not sure if this is the right place to report this.

**Comment by MattIPv4** [comment]
Looking into it 👍

**Comment by xtuc** [comment]
This has been fixed. https://cdnjs.cloudflare.com/ajax/libs/startbootstrap-sb-admin-2/3.3.7+1/js/sb-admin-2.js is now available
