### ISSUE TITLE
Copyright Is not updated.

### ISSUE THREAD

**Issue by mathananya** [cdnjs/cdnjs#14028]
The copyright year on the <a href=“https://cdnjs.cloudfare.com”>cdnjs</a> website is not updated and is still showing ©2020 instead of ©2021.
![image](https://user-images.githubusercontent.com/40272810/105464377-841a0380-5cb7-11eb-8cd6-5149d8fb8923.png)

**Comment by xtuc** [comment]
Can you please update it https://github.com/cdnjs/origin-worker/blob/master/src/homepage/index.html?

**Comment by mathananya** [comment]
Thanks for the link. Have proposed changes

**Comment by themuddfamily2** [comment]
@mathananya Can I add to this that you're using a copyright symbol instead of `&copy;` - This can cause issues with certain IDEs
