### ISSUE TITLE
Тема: Donation to cdnjs.com Project

### ISSUE THREAD

**Issue by FollowersPromotionCom** [cdnjs/cdnjs#14020]
Hello, FollowersPromotion team here!

We know your project very well and we want to say that cdnjs.com have a really good product!
Because of this we really want to support you with a monthly donation and become your sponsor!
Also if it possible we want to place our logo with link to our site in the cdnjs.com Project Sponsor page, so please let us know how we can send donation to you, we want to do it asap!

Sincerelly, FollowersPromotion team.
https://followerspromotion.com/

**Comment by MattIPv4** [comment]
On the off chance this was legit: https://opencollective.com/cdnjs
