### ISSUE TITLE
Make libraries case insensitive?

### ISSUE THREAD

**Issue by Explosion-Scratch** [cdnjs/cdnjs#14037]
I don't see a reason why libraries should be case sensitive. Currently this is a 404:
```
https://cdnjs.cloudflare.com/ajax/libs/bijou.js/7.4.0/bijou.js
```
But this is not:
```
https://cdnjs.cloudflare.com/ajax/libs/Bijou.js/7.4.0/bijou.js
``` 
(It's the "B" in "bijou.js" 🤦🏼 )

My suggestion is that _libraries_ (not filenames) should be case insensitive.

**Comment by MattIPv4** [comment]
Unfortunately cdnjs cannot be made case insensitive as we have some library names that clash when case sensitivity is removed, this is well documented and discussed in #3650.

**Comment by Explosion-Scratch** [comment]
> Unfortunately cdnjs cannot be made case insensitive as we have some library names that clash when case sensitivity is removed, this is well documented and discussed in #3650.

Oh well 😖
