### ISSUE TITLE
Sponsorship of cdnjs

### ISSUE THREAD

**Issue by highOnBytes** [cdnjs/cdnjs#14034]
Hi,

My name is Damien Mather, I am a software dev (now turned website owner) from Melbourne (Aus). I run a website called SecurityGladiators.com. It is a blog about internet security, online privacy, streaming etc.

We have a lot of great content to help users eg. 
https://securitygladiators.com/cybercrime-facts-stats-during-covid-19/
https://securitygladiators.com/vpn-test-tool/

I am interested in donating to the project on a monthly/yearly basis.

How much of a contribution will it take to get my website name and link on the footer of the home page https://cdnjs.com/  like Sentry?

Regards

Damien.

**Comment by MattIPv4** [comment]
👋 We generally look for sponsors who can offer cdnjs services that we are in need of, rather than pure financial sponsors -- if you think you have a service that would make sense for cdnjs to be using, please let me know: matt@cdnjs.com
