### ISSUE TITLE
Suggestion: Merge with JSDelivr

### ISSUE THREAD

**Issue by catdrout420** [cdnjs/cdnjs#14050]
I dont know what to choose! CDNJS Or JSDelivr.
JSDelivr has more uptime and providers but CDNJS is faster. (mabye)
The internet would benefit more if CDNJS And JSDelivr would merge?

help

**Comment by MattIPv4** [comment]
👋 Hey! I appreciate the idea and it is something that we've definitely thought about before, but we have a different structure to our CDN in terms of how we operate it compared to jsDelivr, so it likely would not make sense for us to merge. cdnjs operates by having a known set of libraries that folks can add to, whereas jsDevlir works by providing a CDN mirror to all NPM packages as well as GitHub repos.
