### ISSUE TITLE
Vue3 is down/404

### ISSUE THREAD

**Issue by Explosion-Scratch** [cdnjs/cdnjs#14056]
This url (copied from cdnjs):
```
https://cdnjs.cloudflare.com/ajax/libs/vue/3.1.2/vue.min.js
```
Returns a 404 (nginx) error. Many of my projects (and many more of others) rely on Vue from a CDN. This should be patched fast!

**Comment by MattIPv4** [comment]
The link you've included here isn't listed as a file for Vue 3.1.2, so that is why it is a 404: https://cdnjs.com/libraries/vue

**Comment by Explosion-Scratch** [comment]
> The link you've included here isn't listed as a file for Vue 3.1.2, so that is why it is a 404: https://cdnjs.com/libraries/vue

Weird, it's the link the copies to the clipboard when clicking on the link copy button

**Comment by MattIPv4** [comment]
It looks like this URL came from the Algolia index, rather than the actual package page or API response -- @xtuc looks like we're still pushing invalid data to Algolia?

**Comment by Explosion-Scratch** [comment]
Yikes! Thanks for being so responsive!

**Comment by Explosion-Scratch** [comment]
I screen recorded this and will attach a video of it in a minute. The link
given by the quick link copy button leads to a 404. The other links given
on the main page seem to work fine though.

>

**Comment by Explosion-Scratch** [comment]
![cdnjs](https://user-images.githubusercontent.com/61319150/123643475-061fd280-d7ea-11eb-9352-ffe7c84bca77.gif)

**Comment by MattIPv4** [comment]
Yeah, I'm aware -- as I noted above, that's powered by the Algolia index rather than the API, and appears to have some invalid data in it.

**Comment by Explosion-Scratch** [comment]
Just found another possibly related glitch:
![image](https://user-images.githubusercontent.com/61319150/123676555-b5b86d00-d809-11eb-9a58-a7fb63489e9b.png)
A lot of the integrities for scripts and styles are wrong. I usually just remove the attribute and it works fine.

**Comment by MattIPv4** [comment]
:nod: Algolia has bad data

**Comment by xtuc** [comment]
I fixed a few things and reprocessed `tailwindcss` and `vue`. Please let us know if you see any more issues.

**Comment by Explosion-Scratch** [comment]
Thank you!
