### ISSUE TITLE
cdnjs sponsorship from G-Core Labs

### ISSUE THREAD

**Issue by gofort** [cdnjs/cdnjs#14063]
Hey guys!
I am from G-Core Labs, we create CDN and we want to give you free CDN for your services. We are leading CDN in CIS, so it can bring added value to cdnjs.
Let's discuss.

**Comment by MattIPv4** [comment]
Hey!

Thanks for the offer, but unfortunately we're not interested in looking to expand our CDN providers for cdnjs right now.

\- Matt.

**Comment by gofort** [comment]
@MattIPv4 what other ways of sponsorship you have? maybe you have some sponsorship packages listed somewhere?

**Comment by MattIPv4** [comment]
We don't have any purpose-built sponsorship packages, but in terms of other ways to support us there is always [GitHub Sponsors](https://github.com/sponsors/MattIPv4), [Patreon](https://www.patreon.com/cdnjs), or [OpenCollective](https://opencollective.com/cdnjs)
