### ISSUE TITLE
CORS: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by bernd-wechner** [cdnjs/cdnjs#14069]
I was looking at a nice little Javascript solution here:

https://stackoverflow.com/a/22638396/4002633

Only this fails when the style sheets are hosted at: cdnjs.cloudflare.com

I catch this error and report it as follows on a site I'm building:

```
Failed to get rules from: https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css
SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
23:31:15.280 copy_with_style.js:46 Failed to get rules from: https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css
SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
23:31:15.280 copy_with_style.js:46 Failed to get rules from: https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css
SecurityError: Failed to read the 'rules' property from 'CSSStyleSheet': Cannot access rules
```

I wonder, is there a way to fix this? At my end? Or is this a cloudflare issue (they are blocking access to the rules)?

**Comment by MattIPv4** [comment]
Could you share how you're including the cdnjs assets? DO you have any CSP rules in place?

**Comment by bernd-wechner** [comment]
I include the sheets with:

```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css"/ >
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css"/ >
```

It's a Django site and is configured with:

```
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    X_FRAME_OPTIONS = 'DENY'
```

The first of which sets the header `X-Content-Type-Options: nosniff` teh second sets ` X-XSS-Protection: 1; mode=block` the last sets `X-Frame-Options: DENY`, the others seem unrelated (redirect http to https, use a secure cookie and a secure CSRF cookie all side issues I expect).

It's served by lighttpd, on which to enable CSP you would:

```
setenv.add-response-header = ("Content-Security-Policy" => "script-src 'self'; object-src 'self'",)
```

It is served  from behind a reverse proxy,both the reverse proxy and the webserver running lighttpd and neither set to add a Content-Security-Policy.

**Comment by MattIPv4** [comment]
I would recommend using the default `link` tags that we provide through the cdnjs website -- these include the `crossorigin` attribute which I believe will fix your issue here, but also `integrity` to ensure that resource you're receiving is the expected one (we strongly recommend this for security), and also our referrer-policy just so you know that we aren't tracking you or your site:

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.10/select2-bootstrap.min.css" integrity="sha512-kq3FES+RuuGoBW3a9R2ELYKRywUEQv0wvPTItv3DSGqjpbNtGWVdvT8qwdKkqvPzT93jp8tSF4+oN4IeTEIlQA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" integrity="sha512-urpIFwfLI9ZDL81s6eJjgBF7LpG+ROXjp1oNwTj4gSlCw00KiV1rWBrfszV3uf5r+v621fsAwqvy1wRJeeWT/A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.css" integrity="sha512-bYPO5jmStZ9WI2602V2zaivdAnbAhtfzmxnEGh9RwtlI00I9s8ulGe4oBa5XxiC6tCITJH/QG70jswBhbLkxPw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```

**Comment by bernd-wechner** [comment]
Thanks that did work. To clarify is this simply telling the browser directly that it's OK? Or does it send something to cloudflare along with the request that sees cloudflare set CORS header in the response?

**Comment by MattIPv4** [comment]
Having the `crossorigin` present tells the browser to use CORS when requesting the asset, which as the asset is on a different origin to your site, allows it to actually load -- it doesn't change the response from us, we always respond with ACAO: *.

**Comment by bernd-wechner** [comment]
Thanks for clarifying!
