### ISSUE TITLE
font-awesome 5.15.4 is missing the .woff2 files

### ISSUE THREAD

**Issue by webwake** [cdnjs/cdnjs#14076]
The .woff2 files from font-awesome are missing in the latest version (5.15.4), they were there in 5.15.3

The following files should be included
- fa-solid-900.woff2
- fa-regular-400.woff2
- fa-brands-400.woff2

See also https://github.com/FortAwesome/Font-Awesome/issues/18146

**Comment by MattIPv4** [comment]
👋 Looks like this was a remnant of a previous bug in our API -- the files are available on the CDN but weren't included in our API data that powers the site. I've just forced a re-update of this version and the API is now reporting these files as present correctly.

**Comment by MattIPv4** [comment]
woff2 files are now showing on the API and the site.
