### ISSUE TITLE
cdnjs copy of d3-voronoi returns a 404

### ISSUE THREAD

**Issue by gene1wood** [cdnjs/cdnjs#14075]
I'm sorry if this isn't the right place to report this, it's the best I could find. Feel free to point me to a better place to report this issue if this isn't the right plac.e

# Steps to reproduce

1. Browse to https://cdnjs.com/
2. Search for "d3-voronoi"
3. In the result from the search of d3-voronoi @ 1.1.3 click the "Copy URL" icon on the right which puts this URL into the clipboard
   https://cdnjs.cloudflare.com/ajax/libs/d3-voronoi/1.1.3/d3-voronoi.min.js
4. Browse to that URL

# Expected results

Getting the javascript file served back.

# Actual results

A "404 Not Found" is served from nginx

# Additional Context

If you browse to that libraries specific page at https://cdnjs.com/libraries/d3-voronoi

It contains a different version of the library that doesn't 404. So it looks like the problem is specifically with the "Copy URL" link in the search results page.

**Comment by MattIPv4** [comment]
Looks like this is an issue with our Algolia data, 1.1.3 doesn't actually exist in cdnjs, the latest version we have is only 1.1.2 -- let me see if I can force things to see the correct version.

**Comment by MattIPv4** [comment]
Did some manual force updates and it looks like Algolia is now correctly showing 1.1.2 as the last version with a valid URL and SRI hash 👍
