### ISSUE TITLE
library could not be resolved by the "cdnjs" provider

### ISSUE THREAD

**Issue by sivamca127** [cdnjs/cdnjs#14078]
Hi Everyone,

 I'm trying build .net core applications but unfortunately we are getting error like blow

[LIB002]: The "jquery@3.3.1" library could not be resolved by the "cdnjs" provider
[LIB002]: The "twitter-bootstrap@3.3.7" library could not be resolved by the "cdnjs" provider
[LIB002]: The "jquery-validation-unobtrusive@3.2.10" library could not be resolved by the "cdnjs" provider
[LIB002]: The "jquery-validate@1.17.0" library could not be resolved by the "cdnjs" provider
[LIB002]: The "toastr.js@2.1.4" library could not be resolved by the "cdnjs" provider
[LIB002]: The "aspnet-signalr@1.0.3" library could not be resolved by the "cdnjs" provider

I've tried following commands

libman cache clean

libman restore

libman install "individual library"

all the above commands are giving same error like " library could not be resolved by the "cdnjs" provider"

But i could see https://cdnjs.com/libraries/jquery and i'm able to ping from my ubuntu machine(This is Azure VM - no restrictions).

PING cdnjs.com (172.67.81.238) 56(84) bytes of data.
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=1 ttl=53 time=5.82 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=2 ttl=53 time=1.84 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=3 ttl=53 time=3.09 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=4 ttl=53 time=1.94 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=5 ttl=53 time=2.01 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=6 ttl=53 time=1.62 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=7 ttl=53 time=1.92 ms
64 bytes from 172.67.81.238 (172.67.81.238): icmp_seq=8 ttl=53 time=1.86 ms
^C
--- cdnjs.com ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7010ms
rtt min/avg/max/mdev = 1.621/2.516/5.821/1.316 ms

Kindly help me on this.

Thanks in advance

**Comment by MattIPv4** [comment]
👋 We don't maintain libman or the cdnjs integration in it -- do you know what underlying API calls it might be making to us that aren't returning the expecting data?

https://api.cdnjs.com/libraries/jquery/3.3.1 for example definitely resolves to the expected data on our end as far as I can tell.

**Comment by mettihew** [comment]
HI , Is your problem solved ?

**Comment by MattIPv4** [comment]
No updates, closing.
