### ISSUE TITLE
Slow response (hgih thread work) of CDNJS on Jquery.min.js

### ISSUE THREAD

**Issue by IIPoliII** [cdnjs/cdnjs#14081]
Hello,

I keep getting suddenly an ultra slow response from CDNJS. 
Sometimes the reply time is slow and sometimes I don't know why but jquery completly stucks my website during 50 secondes...

I am getting really good PageSpeed scores when it doesn't happen but whenever it happens it kills it.

Do you may have an Idea how I could fix it, or if it's an CDNJS side issue?

![image](https://user-images.githubusercontent.com/29628512/140620333-3ab4820f-889c-40bc-a3ff-156ede0b70ae.png)
![image](https://user-images.githubusercontent.com/29628512/140620347-99d0a5b1-0126-4a81-9ad1-a286c418791b.png)

**Comment by MattIPv4** [comment]
👋 I just ran httpstat against this locally and wasn't able to reproduce the issue:

```
httpstat https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
Connected to 104.16.18.94:443 from 192.168.1.12:52162

HTTP/2 200 
date: Sat, 06 Nov 2021 19:31:41 GMT
content-type: application/javascript; charset=utf-8
access-control-allow-origin: *
cache-control: public, max-age=30672000
etag: W/"603e8adc-15d9d"
last-modified: Tue, 02 Mar 2021 18:58:36 GMT
cf-cdnjs-via: cfworker/kv
cross-origin-resource-policy: cross-origin
timing-allow-origin: *
x-content-type-options: nosniff
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
cf-cache-status: HIT
age: 246153
expires: Thu, 27 Oct 2022 19:31:41 GMT
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=l%2BXF5uuf63URJ5mowgIfoLB6gSaYriYtD5JNitkrBg63N9suqINALht%2Fv4ocR9ztIHWUwQmKoxtm%2B7GWBWWsotFIIDlNegyphURDzZ92zeod38O5W4fwSC5KI%2BLt89wRx%2BJsLAbw"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}
strict-transport-security: max-age=15780000
server: cloudflare
cf-ray: 6aa0be5b18b6f437-LHR
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400

Body stored in: /var/folders/zl/v44sgh6d4g798j371mpkcm5r0000gp/T/tmp2o71Hy

  DNS Lookup   TCP Connection   TLS Handshake   Server Processing   Content Transfer
[    11ms    |       4ms      |     20ms      |       13ms        |        3ms       ]
             |                |               |                   |                  |
    namelookup:11ms           |               |                   |                  |
                        connect:15ms          |                   |                  |
                                    pretransfer:35ms              |                  |
                                                      starttransfer:48ms             |
                                                                                 total:51ms 
```

---

@IIPoliII Could you share some headers from the slow cdnjs request? Specifically, `date`, `etag`, `cf-cache-status`, `expires` and `cf-ray`?

**Comment by IIPoliII** [comment]
> @IIPoliII Could you share some headers from the slow cdnjs request? Specifically, `date`, `etag`, `cf-cache-status`, `expires` and `cf-ray`?

Thanks for your your reply!

I can't get it to you now but I can definitely send it tomorrow.

I will try to find a way to reproduce it everytime, but I often had it randomly, like if suddenly the server I got behind cdnjs was connected on a 1kb/s connection.

Is there any rate limit per site maybe on CDNJS?

I'll sta you tuned with the headers and the needed informations asap.

**Comment by MattIPv4** [comment]
@IIPoliII Any update?

**Comment by MattIPv4** [comment]
No progress, closing.
