### ISSUE TITLE
How to fix NET::ERR CERT WEAK SIGNATURE ALGORITHM error while using mathjax with cloudfare cdn? 

### ISSUE THREAD

**Issue by chaitanya71998** [cdnjs/cdnjs#14122]
few of my users getting this error in Chrome browser, unable to use mathjax

### Technical details:
* version 2.7.1, while using Cloudflare cdn
* Client OS: Windows 8
* Browser: Chrome 99.0.4844.74

### Supporting information:
![image](https://user-images.githubusercontent.com/46353549/159130610-a00c5efd-4815-4b24-bc2e-7dd036e4df26.png)

TIA

**Comment by MattIPv4** [comment]
No progress, closing.

**Comment by chaitanya71998** [comment]
> @chaitanya71998 Could you please share the `fl` field from https://cloudflare.com/cdn-cgi/trace?
> 
> Are you using a corporate proxy? using windows?

No @MattIPv4 , I was using cloudfare cdn you can check first converstion image.
guided the user to update to latest windows verison
