### ISSUE TITLE
CORS: Random missing Access-Control-Allow-Origin header on responses

### ISSUE THREAD

**Issue by aliveli186** [cdnjs/cdnjs#14125]
My web page makes periodic requests to a service in 1 second intervals.
I'm getting the following error message from Chrome very often.

`Access to XMLHttpRequest at 'https://node.x.com:2053/' from origin 'https://app.x.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

1-2 failed requests appear and then back to normal.
Looks like not all responses are going through a certain service where headers are appended. Maybe they fail and a premature response if returned?

### Failed Response:
```
Request Method: OPTIONS
Status Code: 502
```
```
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
cf-ray: 6fde367d7834781c-VIE
content-type: text/html; charset=UTF-8
date: Mon, 18 Apr 2022 14:50:26 GMT
expires: Thu, 01 Jan 1970 00:00:01 GMT
referrer-policy: same-origin
server: cloudflare
set-cookie: cf_use_ob=0; path=/; expires=Mon, 18-Apr-22 14:50:56 GMT
x-frame-options: SAMEORIGIN
```

### Succeeded Response:
```
Request Method: OPTIONS
Status Code: 200
```
```
access-control-allow-headers: *
access-control-allow-methods: OPTIONS, GET
access-control-allow-origin: *
access-control-request-method: *
alt-svc: h3=":2053"; ma=86400, h3-29=":2053"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 6fde3683bb79781c-VIE
content-length: 0
date: Mon, 18 Apr 2022 14:50:27 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2FkH04eJWQO99SDh25Mkvw9O3zjcbX2rpsTYwDrqdeOtYeL4BQApwInyHUtdtY9qqm00T3thNLciitrJJr8W9KcBjKw5r44fISulz63IInfEyV9nIxdMoJuZK%2BC6pKBtZxzINkfDiqA%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
x-powered-by: ARR/3.0
```

**Comment by MattIPv4** [comment]
👋 This error doesn't seem to be related to cdnjs in any way.

**Comment by aliveli186** [comment]
> 👋 This error doesn't seem to be related to cdnjs in any way.

There is a similar closed issue opened here:
https://github.com/cdnjs/cdnjs/issues/13165
