### ISSUE TITLE
Problem with library p5.js/1.4.0/p5.js

### ISSUE THREAD

**Issue by Tacyturn** [cdnjs/cdnjs#14161]
Hello, I'm using you repo for creating art with p5.js, but since yesterday, my projects don't load as I have this message in the browser's console on CHrome :
`Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`
Is it possible to do something , please ?
Kind regards

**Comment by MattIPv4** [comment]
👋 I'm not sure this is an issue with cdnjs, but rather how you've chosen to configure CSP on your own website. You don't have cdnjs included in your `script-src` directive, so the browser will be blocking it loading.

**Comment by MattIPv4** [comment]
No progress, closing.
