### ISSUE TITLE
Is there any requirement for uploading a package to cdnjs?

### ISSUE THREAD

**Issue by medmin** [cdnjs/cdnjs#14165]
I understand there are only 4000+ packages hosted by cdnjs. There must be some requirement, such as the number of stars, the weekly downloads on npm, etc.

Would you please give it a clear definition? I would like to know whether/when my package can be uploaded to cdnjs. Thanks.

**Comment by MattIPv4** [comment]
Hi! We look for a general indicator of popularity in libraries when adding them. We have some numbers in our contributing doc, though we tend to be lenient on the exact values: https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#policy-rules-and-guidelines

**Comment by medmin** [comment]
Thank you so much ! That's very helpful.

**Comment by MattIPv4** [comment]
Question answered, closing.
