### ISSUE TITLE
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js'

### ISSUE THREAD

**Issue by CaptainJack007** [cdnjs/cdnjs#14184]
### Discussed in https://github.com/cdnjs/cdnjs/discussions/14183

<div type='discussions-op-text'>

<sup>Originally posted by **CaptainJack007** March  5, 2023</sup>
```
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

i was deploying html website into Heroku, but i got this error...

my footer.hbs file:
```

<script
  src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"
></script>
<script src="/app.js"></script>
```

my head.hbs file:
```

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta http-equiv="con">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="/index.css">
  <title>{{title}}</title>
</head>
```</div>

**Comment by MattIPv4** [comment]
👋 This does not appear to be an issue with cdnjs, but rather an issue with how your site is being hosted/run.

It sounds like you are setting the `Content-Security-Policy` header, with only `script-src 'self'` permitted. To load remote JS scripts, this header needs to include the domains that you wish to load from, so in this case `script-src 'self' cdnjs.cloudflare.com`.
