### ISSUE TITLE
Critical: Cannot redirect the correct latest version with default branch, eg. master, main, etc.

### ISSUE THREAD

**Issue by codenamedpkt** [cdnjs/cdnjs#14182]
Links with issue produced: https://cdnjs.cloudflare.com/ajax/libs/eruda/master/eruda.min.js

Symptoms: Get not found error with HTTP code 404 because it is not redirected to correct branch or version by user specified, eg. master, main, latest, etc.

Expected behavior: Get correct branch by user upon requested and show raw Javascript (Typescript) content.

Error scrnshot: [![Error scrnshot](https://user-images.githubusercontent.com/23336645/222883668-3e200bc6-4f9b-42b5-93d8-fc4132be9859.jpg)](#error-scrnshot "Error Scrnshot")

**Comment by MattIPv4** [comment]
👋 cdnjs does not offer aliases to latest, branches, etc. We only offer exact URLs for immutable versions.

This is discussed in the cdnjs/packages README: https://github.com/cdnjs/packages#latest-version-url-support
