### ISSUE TITLE
Sponsoring your project

### ISSUE THREAD

**Issue by BairesDev-LLC** [cdnjs/cdnjs#14195]
Hello, 

At BairesDev, we began to support open-source projects. 

Browsing the web, we stumbled upon yours and found it very interesting (congratulations on your hard work, by the way)! 

It's aligned with our values so we are interested in sponsoring you. 

Can you please share more details on how we can do this?
 
Thanks!

**Comment by MattIPv4** [comment]
👋 At the top of [this repo](https://github.com/cdnjs/cdnjs), and [cdnjs/packages](https://github.com/cdnjs/packages), you should see a 'Sponsor' button with information on ways to support cdnjs. You can [Sponsor me directly on GitHub](https://github.com/sponsors/MattIPv4), or you can donate to cdnjs via [OpenCollective](https://opencollective.com/cdnjs) or [Patreon](https://patreon.com/cdnjs).

**Comment by MattIPv4** [comment]
Ah -- that section of the site is reserved for companies that are sponsoring us with services that cdnjs directly uses to operate (e.g. Cloudflare provides a lot of the infra behind cdnjs, statuspage provides our status page, uptimerobot provides some of our monitoring). We don't usually take direct financial contributions for folks to be listed there.

**Comment by MattIPv4** [comment]
Closing, no further progress.
