### ISSUE TITLE
amis库缺少必要的文件

### ISSUE THREAD

**Issue by xiahao90** [cdnjs/cdnjs#14193]
我使用amis库的时候，他会在相对路径加载fa-solid-900.woff2文件，而cdnjs中没有放该文件，就导致了404。
![image](https://user-images.githubusercontent.com/11575908/236404645-e6ab0984-f36b-4608-92e1-d0d478da3a57.png)

应该去https://github.com/baidu/amis/releases/tag/v2.9.0 下载 sdk.tar.gz，并将文件解压后全部收录才行。
![image](https://user-images.githubusercontent.com/11575908/236405156-2008f55a-bb1a-4feb-be9b-f9f92495e136.png)

**Comment by MattIPv4** [comment]
👋 Please open an issue in cdnjs/packages requesting a library update if required files are missing.

That being said, it looks like the error here it the library trying to load FontAwesome from within itself. To reduce load on the CDN, we generally configure libraries to not pull in duplicate files that already exist on the CDN elsewhere. FontAwesome is already available on the CDN as a standalone library, and I recommend using that as the source of icons, not a bundled version within another library. I recommend raising an issue with the library itself if they do not allow you to customise where icons are loaded from.
