### ISSUE TITLE
Fonts from "primevue" library not in the cdnjs distribution

### ISSUE THREAD

**Issue by darkvertex** [cdnjs/cdnjs#14197]
The project https://github.com/primefaces/primevue which is on cdnjs at https://cdnjs.com/libraries/primevue appears to be missing fonts:
<img width="437" alt="image" src="https://github.com/cdnjs/cdnjs/assets/941331/2309391d-a63c-41d2-82a3-4f3497efce10">

These are 404s:
https://cdnjs.cloudflare.com/ajax/libs/primevue/3.29.2/resources/themes/soho-dark/fonts/lato-v17-latin-ext_latin-regular.woff2
https://cdnjs.cloudflare.com/ajax/libs/primevue/3.29.2/resources/themes/soho-dark/fonts/lato-v17-latin-ext_latin-regular.woff

Is this a project maintainer issue or a cdnjs issue?

**Comment by darkvertex** [comment]
Another lib from the same people https://cdnjs.com/libraries/primeicons has fonts in it, so why not "primevue"? 🤔

**Comment by MattIPv4** [comment]
You're welcome to open a PR in cdnjs/packages to update that, or file an issue there to request an update to the config :)

**Comment by darkvertex** [comment]
Done! https://github.com/cdnjs/packages/pull/1551

Thank you for pointing out where the CI config files were. I was not aware how cdnjs worked.

Guess I'll close this and followup in the PR.
