### ISSUE TITLE
DevExtreme 23.1.3:  missing *.js files

### ISSUE THREAD

**Issue by CyberGuerro** [cdnjs/cdnjs#14204]
The package DevExtreme 23.1.3 has only style files unlike of version 22.2.6 which contains javascript libraries files.
Without them package seems to be unusable.

**Comment by MattIPv4** [comment]
Looks like the package structure has changed and the JS is no longer present in the dist directory.

Please open an update request issue in cdnjs/pacakges with what files should be included for this new structure.
