### ISSUE TITLE
Loading Files Issue (Egypt)

### ISSUE THREAD

**Issue by FatemaAlkheshin** [cdnjs/cdnjs#14200]
Hello!
actually, since yesterday, cdn files didn't load successfully in Egypt it's need a VPN to load 
ex:
https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css
can you please advise?

**Comment by MattIPv4** [comment]
Hi there, the link you've included there is a JSDelivr CDN link, not a cdnjs one.

If you are having issues loading cdnjs, please include the full request/response, including any headers, so that we can investigate further.

**Comment by MattIPv4** [comment]
No progress, closing.
