### ISSUE TITLE
Some versions of hexo-theme-anzhiyu are missing

### ISSUE THREAD

**Issue by anzhiyu-c** [cdnjs/cdnjs#14212]
- [1.6.6](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.6.6)
- [1.6.5](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.6.5)
- [1.6.4](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.6.4)
- [1.6.1](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.6.1)
- [1.6.0](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.6.0)
- [1.5.4](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.5.4)
- [1.5.3](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.5.3)
- [1.5.2](https://www.npmjs.com/package/hexo-theme-anzhiyu/v/1.5.2)

**Comment by MattIPv4** [comment]
It looks like both 1.5.2 and 1.5.3 are available: https://api.cdnjs.com/libraries/hexo-theme-anzhiyu?fields=versions

This library was only recently added (2 days ago: https://github.com/cdnjs/packages/commit/875b72bf47c8fb4788d350935cd34e6b33c04e4b), so I suspect it is still actively being processed and new versions will be added as they get processed by the automation. You can follow the logs in https://github.com/cdnjs/logs/tree/prod/packages/h/hexo-theme-anzhiyu

**Comment by anzhiyu-c** [comment]
Okay, thank you. I understand. Synchronization should take a certain amount of time. Thank you. I mistakenly thought it was automatic synchronization immediately. I'm sorry.

**Comment by MattIPv4** [comment]
Closing this out as all the requested versions have been processed.
