### ISSUE TITLE
How to set the Video Autoplay?

### ISSUE THREAD

**Issue by moon95light** [cdnjs/cdnjs#14220]
Hello 
I hope you are doing well.
I am using the vidoe cdn min js file to display the video file in my web app.
The code is below.
<video id="my-video" class="video-js" controls preload="auto" width="640" height="264" data-setup="{}"
        class="video-js my-video-dimensions vjs-controls-enabled vjs-workinghover vjs-v8 vjs-has-started vjs-playing vjs-user-inactive">
        <source
            src="https://cdn.audition.tube/audition/uploads/5850fb10-ada9-42c0-89cb-eca3786534eb/5850fb10-ada9-42c0-89cb-eca3786534eb/playlist.m3u8"
            type="application/x-mpegURL" />
    </video>

I wanna set the video autoplay when load this page.
How to fix this problem?
Please let me know the good way and Help me.
Thank you for your time and consideration.

**Comment by MattIPv4** [comment]
👋 While cdnjs hosts the library you are using, we are not the authors of the library and cannot provide support for it. You'll want to reach out in an appropriate support forum for the library you are using itself.

https://cdnjs.com/libraries/video.js has a link to the GitHub repository where you can potentially ask for help: https://github.com/videojs/video.js
