### ISSUE TITLE
Advertising

### ISSUE THREAD

**Issue by avitzd** [cdnjs/cdnjs#14224]
Hey, would love to learn more.

**Comment by MattIPv4** [comment]
👋 At the top of [this repo](https://github.com/cdnjs/cdnjs), and [cdnjs/packages](https://github.com/cdnjs/packages), you should see a 'Sponsor' button with information on ways to support cdnjs. You can [Sponsor me directly on GitHub](https://github.com/sponsors/MattIPv4), or you can donate to cdnjs via [OpenCollective](https://opencollective.com/cdnjs) or [Patreon](https://patreon.com/cdnjs).

Companies that are sponsoring us with services that cdnjs directly uses to operate (e.g. Cloudflare provides a lot of the infra behind cdnjs, statuspage provides our status page, uptimerobot provides some of our monitoring) are listed on <https://cdnjs.com/about>. We don't usually take direct financial contributions for folks to be listed there.

**Comment by MattIPv4** [comment]
Nothing further, closing.
