### ISSUE TITLE
jquery-validate 1.20.1 returns no files

### ISSUE THREAD

**Issue by bytestream** [cdnjs/cdnjs#14254]
https://cdnjs.com/libraries/jquery-validate/1.20.1 returns no files. The files are present in https://github.com/jquery-validation/jquery-validation/tree/1.20.1/dist

I accidentally pushed the tag without the `dist` directory but have since deleted and pushed the correct tag.  Is it possible to refetch the files, or do we need to release a new version?...

**Comment by MattIPv4** [comment]
Hi, sorry for the delated response. I've manually triggered a refetch of this version: https://github.com/cdnjs/logs/commits/prod/packages/j/jquery-validate/1.20.1
