### ISSUE TITLE
Sponsorship Inquiry: Route4Me Interested in Sponsoring cdnjs

### ISSUE THREAD

**Issue by vadimiljin** [cdnjs/cdnjs#14258]
Hi there,

We at Route4Me are interested in sponsoring cdnjs.com and would love to support your work. As part of the sponsorship, we'd like to have our company recognized on your site with a link back to our website. Could you let us know the next steps or who we should talk to about making this happen?

Thanks for your time!

Best,
Vadim Iljin
outreach@route4me.com

**Comment by MattIPv4** [comment]
👋 At the top of [this repo](https://github.com/cdnjs/cdnjs), and [cdnjs/packages](https://github.com/cdnjs/packages), you should see a 'Sponsor' button with information on ways to support cdnjs. You can [Sponsor me directly on GitHub](https://github.com/sponsors/MattIPv4), or you can donate to cdnjs via [OpenCollective](https://opencollective.com/cdnjs) or [Patreon](https://patreon.com/cdnjs).

Companies that are sponsoring us with services that cdnjs directly uses to operate (e.g. Cloudflare provides a lot of the infra behind cdnjs, statuspage provides our status page, uptimerobot provides some of our monitoring) are listed on <https://cdnjs.com/about>. We don't usually take direct financial contributions for folks to be listed there.
