### ISSUE TITLE
Typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dvd101x** [cdnjs/cdnjs#14252]
The contributing document states:

> pull requests are no longer ~~excepted~~ for this repository

I probably means
> pull requests are no longer **accepted** for this repository

https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

**Comment by MattIPv4** [comment]
Documenting this for the future if we need to edit files here, 'cause I always forget how to sparse-checkout and working with this repo is a headache now (even GitHub's UI cannot edit files in it now):

```
git clone --filter=blob:none --no-checkout --depth 1 --sparse git@github.com:cdnjs/cdnjs.git#
# git sparse-checkout add <dir>
git checkout
# Make edits
git status
git switch -c <branch>
git add <files>
git commit -m <message>
git push
```
