### ISSUE TITLE
Update numbering normalization in `google-libphonenumber'    of Argentina according to the latest ENACOM assignments

### ISSUE THREAD

**Issue by ceagabe** [cdnjs/cdnjs#14260]
Hello CDNJS team,

I would like to request an update of the `google-libphonenumber` library on CDNJS to the latest version, which is **3.2.38**. 

The current version available on CDNJS is outdated, and the latest version includes important bug fixes and enhancements that are critical for proper phone number validation and formatting.

Updating this will greatly benefit developers who rely on this CDN for their projects.

Thank you for your attention to this matter!

Best regards,  
ceagabe

**Comment by MattIPv4** [comment]
Dupe https://github.com/cdnjs/packages/issues/1874
