### ISSUE TITLE
Suggestion: dependency naming & hosting.

### ISSUE THREAD

**Issue by rhalff** [cdnjs/cdnjs#1624]
I'm playing with the `packages.json` and see how it also includes the dependencies.
However it seems like those dependencies are more npm? like.

The naming doesn't really refer to the names of the packages on cdnjs, sometimes
they match, sometimes not, and sometimes the dependencies are not present on cdnjs.

If a package is important enough to be hosted I guess it's dependencies are also.

e.g.
```
{
 "name" : "js-sequence-diagrams",
"dependencies" : { "underscore" : "~1.4.x", "raphael" : "~2.1.x" }
}
```

cdnjs/packages.json does contain underscore, but it's name is `underscore.js`
`raphael` is also present and it's name _does_ match with the name used by cdnjs.

If applications want to integrate cdnjs it would be convenient not having to use something like npm to resolve and download the dependencies locally.

Imagine the packages json being the source for what http://jsfiddle.net/ uses for their framework selection box. Automatic resolving of dependencies wouldn't be that hard if the dependencies could be linked to the correct file also hosted on cdnjs.

In the future you could even expand cdnjs to be a new kind of package/assets manager where everything is already hosted in a structured manner instead of downloaded in a structured way.

Anyway, the basic question is: making dependencies linkable to the files hosted on cdnjs.

**Comment by PeterDaveHello** [comment]
That's from upstream, and for npm dependencies, meaningless on cdnjs in fact.
