### ISSUE TITLE
Add Google Analytics on solving far future caching issue, and rapidly update it (under the same URL)

### ISSUE THREAD

**Issue by laukstein** [cdnjs/cdnjs#1670]
Google Universal Analytics www.google-analytics.com/analytics.js
Old Google Analytics www.google-analytics.com/ga.js

**Comment by laukstein** [comment]
@petecooper, any updates forwarding to this issue?
www.google-analytics.com/ga.js is [outdated and discontinued](https://developers.google.com/analytics/devguides/collection/upgrade/#phase-4).
The only relevant JavaScript file: www.google-analytics.com/analytics.js

**Comment by PeterDaveHello** [comment]
cc @thomasdavis @ryankirkman @drewfreyling

**Comment by thomasdavis** [comment]
Don't think we will continue serving GA, doesn't really make sense for our setup and probably best in general to use Google's cdn as it is very widely used.

**Comment by drewfreyling** [comment]
I agree with @thomasdavis

**Comment by laukstein** [comment]
Related issue https://code.google.com/p/analytics-issues/issues/detail?id=861, as you can see unfortunately GA managers doesn't consider to fix their future caching issue.
