### ISSUE TITLE
cdnjs.com unavailable from China

### ISSUE THREAD

**Issue by evanp** [cdnjs/cdnjs#1922]
I had a user complain that functionality was seriously hampered because our JS files were missing; see e14n/pump.io#837 .

I'm not sure if it's a Great Firewall issue or not; this tool shows that the files are available:

http://www.viewdns.info/chinesefirewall/?domain=https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2Ftwitter-bootstrap%2F2.3.2%2Fcss%2Fbootstrap.min.css

But I thought I'd bring it up here.

**Comment by PeterDaveHello** [comment]
Looks fine now.
http://www.greatfirewallofchina.org/index.php?siteurl=https%3A%2F%2Fcdnjs.com
http://www.greatfirewallofchina.org/index.php?siteurl=https%3A%2F%2Fcdnjs.cloudflare.com

http://www.blockedinchina.net/?siteurl=https%3A%2F%2Fcdnjs.com
http://www.blockedinchina.net/?siteurl=https%3A%2F%2Fcdnjs.cloudflare.com

http://www.viewdns.info/chinesefirewall/?domain=https%3A%2F%2Fcdnjs.com
http://www.viewdns.info/chinesefirewall/?domain=https%3A%2F%2Fcdnjs.cloudflare.com
