### ISSUE TITLE
Bower auto update

### ISSUE THREAD

**Issue by zdroid** [cdnjs/cdnjs#2356]
It would be nice if have auto-update for Bower packages, because of NPM is just for JS.

**Comment by zdroid** [comment]
@cdnjs Any news on this? It's a very useful thing to be supported.

**Comment by PeterDaveHello** [comment]
@zdroid I'm so sorry that we don't even implement this feature, I'll try my best to solve other higher priority issues then go back to implement this one, thank you for your patient!
