### ISSUE TITLE
recent ace library update inconsistent

### ISSUE THREAD

**Issue by ubergeek42** [cdnjs/cdnjs#2804]
@petecooper, I think the updated ace library that just went in(commit https://github.com/cdnjs/cdnjs/commit/a90bc1b4cfe5f49c3818b1b0e6d38686ec63f972) should have been taken from the https://github.com/ajaxorg/ace-builds repository rather than directly from the project.  That is how the 1.1.01 version was packaged(see https://github.com/cdnjs/cdnjs/commit/14e06608ccfcbb0fdad3838d8df73732fd8075ad), and why the recent commit comment notes a change in directory structure, when I don't believe there should have been one.

I believe the way it was just added will work if you are using requirejs, but it doesn't seem to really be the recommended way according to the Readme in the ajaxorg/ace repository.  Can you take a look at this and maybe replace 1.1.2 and 1.1.3 with the src-min-noconflict from the acebuilds repository?

Thanks!

**Comment by rmzelle** [comment]
> Also, I noticed that the http://cdnjs.com/libraries/ace/ doesn't show the newer versions? Is that a cache issue as well that will just magically resolve itself at some point?

@petecooper, http://cdnjs.com/libraries/ace/ is still at 1.1.3, while 1.1.8 is available (https://github.com/ajaxorg/ace-builds/releases). What is the process of getting newer versions into cdnjs?

**Comment by PeterDaveHello** [comment]
@rmzelle You can send a PR to do it by your self or open an issue and wait for somebody to do it.

**Comment by rmzelle** [comment]
Thanks! Just noticed your commits https://github.com/cdnjs/cdnjs/commit/2ec1507e0b7adcc67b951a06b32a75f352a28577 and https://github.com/cdnjs/cdnjs/commit/99cbbdcd3a72ea6ed2e4fa8a9493b6f7eef1c203 to update the ace libraries.
