### ISSUE TITLE
Public uptime page not available

### ISSUE THREAD

**Issue by altmind** [cdnjs/cdnjs#2855]
Visiting "Uptime" on http://cdnjs.com/ gives a pingdom page http://stats.pingdom.com/4jg86a2wqei0 : "Public Report Not Activated".

Please activate public report.

**Comment by rclmenezes** [comment]
It still isn't visible. Any chance you could take a look?

**Comment by PeterDaveHello** [comment]
hmmmm ...

**Comment by ryankirkman** [comment]
This is fixed now: http://stats.pingdom.com/4jg86a2wqei0
