### ISSUE TITLE
Move bower-angular-translate-*

### ISSUE THREAD

**Issue by LordSputnik** [cdnjs/cdnjs#2906]
Hi guys,

Thanks for getting the packages hosted.

One request - could you remove the "bower" prefix from the front of the package names?  In the original github repository, this is just used to indicate that the package is compatible with the bower package manager for node.js (see http://bower.io/), so it probably shouldn't be part of the package name here at cdnjs.

Thanks!

**Comment by knalli** [comment]
fyi: all 8 modules of angular-translate are available now without the _bower_-prefix on cdnjs.com. Each of them autoupdates against the dedicated bower-* repositories of us.

I think we can close this here.

**Comment by PeterDaveHello** [comment]
We don't want to break the running sites, so can not move but can add a new with the right name.
