### ISSUE TITLE
Suggestion - Use static gzip

### ISSUE THREAD

**Issue by ceram1** [cdnjs/cdnjs#2978]
I think it would be awesome if cdnjs uses static-gzip.
And as it's pre-compress, static files can be compressed with level 9

**Comment by PeterDaveHello** [comment]
Hey @terinjokes, are we using something like this now? Or we are using on the fly compression? Just forgot this issue.

**Comment by terinjokes** [comment]
We're currently using an optimized on-the-fly compression via CloudFlare. We may do some static tests in the future while looking at #1120.

**Comment by ceram1** [comment]
It seems better.. So I'll close this.

**Comment by PeterDaveHello** [comment]
@terinjokes Thanks.
