### ISSUE TITLE
auto update seems to fail for vis.js

### ISSUE THREAD

**Issue by josdejong** [cdnjs/cdnjs#3015]
I've recently done two updates for vis.js, but they seem not to be picked up correctly by the auto update of cdnjs: v0.7.3 and v0.7.4 are not showing up on the website. For earlier versions the auto update worked fine. 

Any idea what's wrong?

See the package.json: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/vis/package.json

**Comment by josdejong** [comment]
Hi @PeterDaveHello, we've released vis.js v4.0.0 four days ago, but this new release is still missing on cdnjs. Is it still on your list to update, or did it somehow miss the auto update cycle?

**Comment by thomasdavis** [comment]
hey @josdejong, Peter has informed me of this issue and we are looking into it. We might do some manual submissions in the meantime.

Sidenote: Just read the old discussion, we ended up using Json editor in and around jsonresume.org =D

**Comment by josdejong** [comment]
Ok thanks for letting me know!

Great to hear about jsonresume.org. I should really add support for JSON Schema in the JSON Editor, that will be very useful for these kind of applications.

**Comment by josdejong** [comment]
Any chance of adding vis v4.0.0 and v4.1.0 to cdnjs? Is there anything I can help with? (manual PR's again?)

**Comment by PeterDaveHello** [comment]
I think we can just transfer to git auto-update.

**Comment by josdejong** [comment]
Thanks for adding the latest versions to cdnjs.
