### ISSUE TITLE
Add the Timing-Allow-Origin response header

### ISSUE THREAD

**Issue by philbooth** [cdnjs/cdnjs#3117]
The W3C resource timing API specifies a new response header that enables conforming browsers to publish resource timing data cross-origin:

http://www.w3.org/TR/resource-timing/#timing-allow-origin

Any chance of you guys implementing it on cdnjs?

**Comment by maruilian11** [comment]
**Git repository url:** https://github.com/w3c/resource-timing/

sorry, the lib's popularity doesn't fit our request. please read our document  [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md "README.md")

**Comment by philbooth** [comment]
@maruilian11, this issue is not a request for you to host a library, it is request to implement an HTTP header in your server responses.

[Resource Timing](http://www.w3.org/TR/resource-timing/) is a W3C recommendation that helps developers analyse the performance of their websites. Specifically, it allows them to get fine-grained timings of how long each resource (including JS libs) took to load on a page.

But in order to get the timings for cross-origin resources, those resources must be served with a `Timing-Allow-Origin` origin header in the response, as per [this section](http://www.w3.org/TR/resource-timing/#timing-allow-origin) of the spec.

The header is supported by many other major sites and CDNs, as evidenced by the [following `BigQuery`](https://bigquery.cloud.google.com/results/central-weft-572:job_aQn6PmVBSHeaszmB13g3HbrrcWA?pli=1):

```sql
SELECT COUNT(DISTINCT pageid) AS count, req_host
FROM [httparchive:runs.latest_requests]
WHERE respOtherHeaders CONTAINS 'Timing-Allow-Origin'
GROUP BY req_host
ORDER BY count DESC
LIMIT 1000
```

Requests|Domain
--------|------
156331|fonts.gstatic.com	 
142802|fonts.googleapis.com	 
114788|connect.facebook.net	 
113435|ajax.googleapis.com	 
94415|fbstatic-a.akamaihd.net	 
93896|www.facebook.com	 
66429|apis.google.com	 
57993|fbcdn-profile-a.akamaihd.net	 
53945|scontent.xx.fbcdn.net	 
35166|s.ytimg.com	 
28336|www.googletagservices.com	 
8838|cdn.optimizely.com	 
8703|use.typekit.net	 
6742|fbexternal-a.akamaihd.net	 
5802|scontent.cdninstagram.com	 
4868|cdn.jsdelivr.net	 
4414|themes.googleusercontent.com	 
2216|assets.adobedtm.com	 
2166|static.licdn.com
1593|use.typekit.com

Any chance of you guys implementing it?

**Comment by maruilian11** [comment]
I understand, sorry for my mistake.
@PeterDaveHello please take a look.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs @cdnjs/owners

**Comment by philbooth** [comment]
Also, just in case it's not clear from my description or the spec itself: The value for this header can just be set to `*` on all responses, there is no need for anything dynamic to happen per request.

```
Timing-Allow-Origin: *
```

**Comment by drewfreyling** [comment]
+1

**Comment by gitgrimbo** [comment]
Hi, any progress on this?

**Comment by edds** [comment]
Is there any update on this? It would be great if any request to `https://cdnjs.cloudflare.com/*` could have this header added to it.

**Comment by terinjokes** [comment]
There is no update here.

**Comment by edds** [comment]
Is this something you would consider adding? I'd be more than happy to help add it, but I'm not sure where it would be added, if you can give me a pointer I'd happily submit a pull request.

**Comment by terinjokes** [comment]
The change is in-flight already, but I don't have an update.

**Comment by bripkens** [comment]
Any update on this @terinjokes?

**Comment by MattIPv4** [comment]
🙌 Cloudflare will be looking into this next week to establish where this was left at and hopefully get the header added. I will post any further updates here.

**Comment by MattIPv4** [comment]
@philbooth @drewfreyling @gitgrimbo @edds @ArnaudBrousseau @bripkens

I bring you good news, this change has now been deployed and is live on cdnjs.cloudflare.com resources (may only appear on new resources due to cache). 🎉 

Please let me know if you encounter any issues by responding here and mentioning me :)

cc @PeterDaveHello
