### ISSUE TITLE
Remove Last-Modified Header from CDNJS Server Output

### ISSUE THREAD

**Issue by Niresh12495** [cdnjs/cdnjs#3120]
setting Last-Modified header results the browsers send
if_modified_since to nginx to check freshness of the files, which are
actually unnecessary, cost server processing time.
Its unnecessary because those files are never edited again.
so its good to remove it

Test using this
curl -I cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js

**Comment by shekhei** [comment]
any updates?

**Comment by drewfreyling** [comment]
I vote we keep the last mod header!

**Comment by MattIPv4** [comment]
I see no reason that last mod header should be removed. This issue is very old, so I will close it for now. If anyone has any new thoughts, feel free to mention me.
