### ISSUE TITLE
multilingual description in package.json

### ISSUE THREAD

**Issue by Kris-B** [cdnjs/cdnjs#3270]
Hi,

Is it possible to have a multilingual projet description in the package.json?
Actually, my question is about the localized version of **http://cdnjs.com/news**, for example **http://fr.cdnjs.com/**

The description is automatically translated, but I would like to provide my own translation for some languages.
Is this possible?

**Comment by PeterDaveHello** [comment]
Hi @Kris-B, I'm sorry for the late response, actually, we already dropped multilingual support and the news feature, so close this now, thanks for the suggestion and sorry again!
