### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#3317]
I know cdnjs do not serve html currently, and it's reasonable, but I found a cool project - Viewer.js([http://viewerjs.org/getit/) will need it(http://viewerjs.org/instructions/), I want to ask respectfully if is possible to allow some special cases like Viewer.js to serve html file in the policy and mechanism? thanks!

**Comment by francisbrito** [comment]
:+1: Would love loading Custom Elements from cdnjs

**Comment by edrex** [comment]
Just to expand on the previous comment by @PeterDaveHello, Reveal.js speaker notes plugin requires a file notes.html which is missing.

**Comment by PeterDaveHello** [comment]
@terinjokes can we make it on the schedule to support it? Thanks.

**Comment by laike9m** [comment]
I also have a need to serve HTML. For anyone who has tried to do this, does cdn.js refuse to accept PR that contains HTML, or it fails to serve them?

**Comment by PeterDaveHello** [comment]
@laike9m It is not possible to do that, use Cloudflare directly please.

**Comment by laike9m** [comment]
Thanks Peter, could you help clarify "do not serve"?

**Comment by PeterDaveHello** [comment]
@laike9m Sorry that I respond to a wrong issue, will fix it soon.

**Comment by PeterDaveHello** [comment]
@laike9m we don't accept that right now, and, it'll fail to serve that, thanks for asking.
