### ISSUE TITLE
Update jQuery UI

### ISSUE THREAD

**Issue by JGallardo** [cdnjs/cdnjs#3519]
Requested on our [forum](http://www.cdnjs.com/news/53b3e5260adb6f0200c1b5e4/jquery-ui-is-updated-to-1110-plaese-update--a-hrefhttpjqueryuicomhttpjqueryuicoma) that we update [jQuery UI to 1.11.0](http://jqueryui.com/) but in the libs I do not see that we have the library. Just `jquery-ui-bootstrap` and `jquery-ui-map`.

**Comment by PeterDaveHello** [comment]
Manually updated for a while, see https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/jqueryui
