### ISSUE TITLE
Accessing the latest version x.y.z releases by x.y or x

### ISSUE THREAD

**Issue by reezer** [cdnjs/cdnjs#360]
Various CDNs (Google's for example) allow access of the latest bug fix release of a certain series by not specifying the minor version number. This makes sense, because such releases usually don't contain anything that can breakage, but only contain bug, performance or stability fixes (maybe better support for certain browsers).

To give an example. The current:

```
http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery-1.8.0.min.js
```

should also be available as:

```
http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8/jquery-1.8.min.js
```

and once 1.8.1 is released link to:

```
http://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.1/jquery-1.8.1.min.js
```

For comparison see:

```
https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js
https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js
```

(Maybe it would be better to mention this in its own ticket, but specifying the version number twice seems unnecessary.)

**Comment by luigimannoni** [comment]
Completely agree with that, i guess having a /latest/*.js and /latest/*.min.js would be easier to maintain rather than using wildcards

**Comment by AliMD** [comment]
Do you forgot this feature/issue ?!

**Comment by eusonlito** [comment]
:+1:

**Comment by dandv** [comment]
I'd really like for `latest` or `last` to work. Useful also in [examples of how to use libraries](https://github.com/zeroclipboard/zeroclipboard/issues/587).

**Comment by levithomason** [comment]
It is worth referencing [unpkg](https://unpkg.com/#/), a direct CDN to NPM packages.  They have  killer flexibility and redirects for `latest`, and lots more.

**Comment by Kristinita** [comment]
+1

**Comment by dhowe** [comment]
+1

**Comment by temandroid** [comment]
+1

**Comment by MattIPv4** [comment]
Closing, there is no feasible way to implement this whilst we have a focus on asset integrity with SRI.
