### ISSUE TITLE
backbone-forms 0.14.0 incorrectly returning 0.13.0

### ISSUE THREAD

**Issue by coroneos** [cdnjs/cdnjs#3637]
Backbone forms v0.14.0 is incorrectly returning v0.13.0. This can be directly observed by viewing the following: https://cdnjs.cloudflare.com/ajax/libs/backbone-forms/0.14.0/backbone-forms.js

**Comment by drewfreyling** [comment]
I've asked for an update on https://github.com/powmedia/backbone-forms/issues/404

**Comment by PeterDaveHello** [comment]
There is no response and I don't think it's a real problem here.

**Comment by glenpike** [comment]
Please use 0.14.1 - https://github.com/powmedia/backbone-forms/tree/v0.14.1
