### ISSUE TITLE
No more manual pull request for lib updating

### ISSUE THREAD

**Issue by thomasdavis** [cdnjs/cdnjs#3638]
Hey guys,

We are going to try switch the project to be fully automated. This will take a bit of time and will be a bit rocky at the beginning but will save every bodies time.

We currently have two auto update systems, the old one which uses NPM and will remain active until we transfer it. And a new one that uses git tags. The new one is what we will use by default but it doesn't support NPM just yet so we can only add new auto update scripts for git. We can also add the old style NPM ones I will just transfer them at a later date.

``` json
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/jashkenas/underscore.git",
    "basePath": "",
    "files": [
      "underscore-min.js",
      "underscore-min.map",
      "underscore.js"
    ]
  },
```

During this process, I think it's best if only I merge PR's to make sure we don't cause too many problems at once. I still need to write up documentation. So from this point on don't merge any new libraries into cdnjs.  @drewfreyling @PeterDaveHello @ryankirkman

**Comment by JamesMGreene** [comment]
@PeterDaveHello: I see you [manually?] added ZeroClipboard `v2.2.0`. Any info on its failure to auto-update? I'll likely be releasing another version some time this week.

**Comment by PeterDaveHello** [comment]
Yes, because of I'll always audit all the updated results, so you'll see my commit, we don't use a bot to commit it at this time, I don't think we have problem here, maybe you can ping me here when you're going to release the it, then I'll check if everything okay.

**Comment by dlid** [comment]
Hi, I added the tag 0.8 of https://github.com/dlid/jquery-valjs/releases but I can't see it on cdnjs yet. Is there something else I must do for the auto update to work?

**Comment by PeterDaveHello** [comment]
Sorry, I am too busy these days, I'll audit all the updates results before commit it, added in b9b2efcd60704f1d2ddf0e3c3656fb725fa4f47f now.

**Comment by Jakobud** [comment]
I think I am missing something here.... How exactly do we add or update libraries to cdnjs now? Do we not do pull requests anymore?

The readme says "no more manual submissions" but then it says to do pull requests to add or update libraries. Which is it?

Really confused...

**Comment by PeterDaveHello** [comment]
PR for adding a whole new lib or the libs can't not support/be supported by current auto-update, no manual submissions for updating libs. We are working for the new mechanism to update libs already.

**Comment by ethanpil** [comment]
Maybe I'm just being dense... but I am missing something.

If an existing package needs an update, but the github repo doesn't tag by version, would we just simply update the package.json with the new version number? How does the autoupdate know to pull a new version, create directory, etc...

**Comment by PeterDaveHello** [comment]
@ethanpil Depends on its tags, so if no tag, no autoupdate.

**Comment by ethanpil** [comment]
So, how would one trigger an update in this case?

**Comment by PeterDaveHello** [comment]
In what case? if no tag, no auto-update, if there is/are tag(s), will grab the files as config from that tag(s).

**Comment by JamesMGreene** [comment]
@ethanpil: Y U NO TAGS WITH VERSIONZ? (╯°□°)╯︵ ┻━┻ 

Anyway, you'll have to do manual Pull Requests for updates, then.

But seriously, why aren't/can't you tag versions?

**Comment by ethanpil** [comment]
They aren't my repos, I am just adding a few libs that I use often and I see that several of them don't do it...

**Comment by PeterDaveHello** [comment]
hmmm ... maybe you can open issue in their repo first

**Comment by joeyparrish** [comment]
I've noticed that the latest release of my library (shaka-player) hasn't auto-updated.  (google/shaka-player#27)  We've published the new version in npm and package.json has npmName and npmFileMap.

I checked out cdnjs source and ran auto-update.js myself, and I get errors on knockout and flocks.js.  If I remove package.json from those two folders, I get no errors in the log, but my package still does not update.

Finally, if I edit auto-update.js such that the list of packages contains only mine, my package updates just fine.  So it seems that the lack of auto-update for my package has nothing to do with my package.

Is this a known issue?  Should I be manually updating and creating pull requests for now since auto-update isn't working?

**Comment by PeterDaveHello** [comment]
@joeyparrish Sometimes the auto-update will miss libs with unknown reason, we'll try to figure it our, your lib was updated in 4c6e805 now.

**Comment by noahcooper** [comment]
Hey there,

What's the latest on the frequency of autoupdates? I published a new release at https://github.com/noahcooper/luminateExtend/releases, but it hasn't shown up on cdnjs yet.

Thanks!

-Noah

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-npm-auto-update
> many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most 30 hours, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it

**Comment by noahcooper** [comment]
@PeterDaveHello does that apply to both npm autoupdates as well as autoupdates using git tabs?

**Comment by PeterDaveHello** [comment]
Yes, all the auto-updates, if you are really in hurry, you can send a PR.

**Comment by noahcooper** [comment]
No hurry, just wanted to make sure my updates to package.json to add autoupdate worked correctly.

Thanks!

**Comment by PeterDaveHello** [comment]
@noahcooper Okay, I can audit all the updates right now, I'll do it soon when I wake up, thanks!

**Comment by PeterDaveHello** [comment]
@noahcooper, updated in d148e87

**Comment by pzp1997** [comment]
Waiting for Processing.js to get updated to 1.4.15. 1.4.8, the latest version on cdnjs, is over a year old. Should I submit a PR or do you guys want to set up auto-update for it?

**Comment by PeterDaveHello** [comment]
You can submit PR to setup auto-update for it @pzp1997

**Comment by tocker** [comment]
When adding a new library, should the PR include the latest js sources or just `ajax/libs/<new lib>/package.json` with npm autoupdate and let autoupdate pick up the latest sources?

**Comment by PeterDaveHello** [comment]
@tocker should add with the latest release, and we will add a future to let users only add the package.json within a month(I hope), you can also just send a request issue, and we will add it for you, tahnks.
