### ISSUE TITLE
Sortable vs sortable causes issues on case insensitive filesystems

### ISSUE THREAD

**Issue by zpao** [cdnjs/cdnjs#3650]
Simply checking out cdnjs results in a file being modified because you have https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Sortable and https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/sortable. It's not just my fs though, it looks like you own site can't handle this (search for "sortable" and you see the summary for `Sortable` but view the page and it's `sortable`).

**Comment by PeterDaveHello** [comment]
See https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md, will help.

**Comment by gordonwoodhull** [comment]
New link: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

**Comment by PeterDaveHello** [comment]
Thanks @gordonwoodhull

**Comment by NGsolution** [comment]
Sortable

**Comment by xtuc** [comment]
is there anything actionable here? we won't modify existing files because that would be a breaking change.

**Comment by MattIPv4** [comment]
Closing as this isn't actionable, but have pinned for visibility as this will be a forever issue with this repo (and other related cdnjs repos).

**Comment by japui-coder** [comment]
Sortable vs sortable causes issues on case insensitive filesystems
 #3650
