### ISSUE TITLE
moment-timezone missing -with-data versions

### ISSUE THREAD

**Issue by preaction** [cdnjs/cdnjs#3651]
moment-timezone needs the IANA time zone database to function. There are versions of moment-timezone that include the necessary data. These versions appear to get built by the moment-timezone gruntfile, but do not appear in cdnjs. https://github.com/moment/moment-timezone/tree/develop/builds

**Comment by rspilker** [comment]
It is still the case that the search won't show it, but modifying the URL works.

**Comment by PeterDaveHello** [comment]
@rspilker there will only be one main file on search result, the other files are listed here:
https://cdnjs.com/libraries/moment-timezone
