### ISSUE TITLE
Auto update not working for mathjs?

### ISSUE THREAD

**Issue by josdejong** [cdnjs/cdnjs#3764]
The [`mathjs` package](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/mathjs) has configuration for automatic updates on cdnjs. I've released a new version yesterday (v0.27.0), and it's still not updated on cdnjs, whilst the update script seems to run every 15 minutes. Is something wrong with the automatic updates?

**Comment by josdejong** [comment]
@PeterDaveHello I just released math.js v2.0.0, but I see the previous version, v1.7.1 is still missing on cdnjs. This version was released more than two weeks ago. Would be great if you could add both versions to cdnjs. Thanks!

**Comment by PeterDaveHello** [comment]
Hi @josdejong, hanks for your report and sorry about that, I opened a issue here #4487, I'll pick the new version now and tansfer this lib to use a more reliable git auto-update mechanism!

**Comment by josdejong** [comment]
Thanks a lot! Keep up the good work.

**Comment by PeterDaveHello** [comment]
* f8c361e transfer mathjs to use git auto-update Peter Dave Hello 2 minutes ago
