### ISSUE TITLE
Despite hard reset, local checkout shows file changes in other libraries

### ISSUE THREAD

**Issue by terrymun** [cdnjs/cdnjs#3792]
I am experiencing a peculiar problem here: even after cleaning up my cdnjs fork and restarting it from upstream using the following code:

```
git remote add upstream https://github.com/cdnjs/cdnjs
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 
```

I am still getting the following when checking out master (I am the author of Fluidbox and I am updating the files, mostly fixing outdated version numbers in JS files):

```
D	ajax/libs/fluidbox/1.2.2/jquery.fluidbox.css
M	ajax/libs/fluidbox/1.2.2/jquery.fluidbox.js
M	ajax/libs/fluidbox/1.2.2/jquery.fluidbox.min.js
D	ajax/libs/fluidbox/1.2.3/jquery.fluidbox.css
M	ajax/libs/fluidbox/1.2.3/jquery.fluidbox.js
M	ajax/libs/fluidbox/1.2.3/jquery.fluidbox.min.js
D	ajax/libs/fluidbox/1.2.4/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.2.5/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.2.6/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.2.7/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.3.1/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.3.2/jquery.fluidbox.css
D	ajax/libs/fluidbox/1.3.3/jquery.fluidbox.css
M	ajax/libs/sortable/package.json
```

You can see that the last file from /sortable/ has been modified, but I checked the file and it is precisely identical to the one on the original upstream repo (master). May I know how should I work around this issue so that my pull request will not modify other libraries?

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md This will help

**Comment by PeterDaveHello** [comment]
Let's discuss here #3650.
