### ISSUE TITLE
usernames accepting nullbytes.

### ISSUE THREAD

**Issue by tsiddiki** [cdnjs/cdnjs#3910]
During registration to that website,the sign up form accepts null bytes in user names.
So when I registered an account with the username tarsid%00 ,the account was successfully registered.But the profile link was `www.cdnjs.com/profile/tarsid%00` which results an `400 Bad Request`
And the actual profile was created here `www.cdnjs.com/profile/tarsid`
Besides,
If you have an profile with username testuser and then I create a profile with username testuser+
Both the profile will represent same profile page.

**Comment by PeterDaveHello** [comment]
We don't have user feature on the website right now, removed for a while.
