### ISSUE TITLE
Request timeouts

### ISSUE THREAD

**Issue by jaddison** [cdnjs/cdnjs#3997]
Based on https://gitter.im/cdnjs/cdnjs, I'm not the only one experiencing a high number of request timeouts happening for cdnjs-hosted web assets. I've seen in chrome and safari on yosemite. I'm in Victoria, BC - others have noted this in Vancouver.

Another mention from someone in San Francisco: https://twitter.com/nimiw_/status/527608864276217857 (this guy moved off cdnjs to jsdelivr, apparently)

I'm sure it's not cdnjs itself, but Cloudflare - and they don't seem to be responding to it at all. Can anyone pull some strings?

**Comment by drewfreyling** [comment]
Is anybody still having issues here? @cwensley @jaddison

**Comment by cwensley** [comment]
@drewfreyling I've been testing the past few days with sites that have been known to fail every time (until I refresh the page), and they now seem to be working without failure.  Was something changed?

**Comment by PeterDaveHello** [comment]
maybe cloudflare fixed it xD

**Comment by jaddison** [comment]
We switched a while ago when it was apparent that it wasn't on anyone's radar. Glad to hear it's (likely) been fixed, even if it's inadvertently so. Feel free to close this if you think it's dealt with.

**Comment by mikeevstropov** [comment]
Timeout from Thailand Pattaya
``` console
mikeevstropov@aspire5541g ~ $ traceroute cdnjs.cloudflare.com
traceroute to cdnjs.cloudflare.com (104.19.193.102), 30 hops max, 60 byte packets
 1  192.168.1.1 (192.168.1.1)  1.138 ms  1.099 ms  1.167 ms
 2  10.28.80.1 (10.28.80.1)  9.026 ms  9.178 ms  9.163 ms
 3  10.246.251.177 (10.246.251.177)  9.950 ms  15.087 ms  15.075 ms
 4  10.185.202.133 (10.185.202.133)  25.581 ms  25.568 ms  25.625 ms
 5  10.185.107.89 (10.185.107.89)  15.397 ms  15.219 ms  15.179 ms
 6  210-86-142-58.static.asianet.co.th (210.86.142.58)  18.088 ms 210-86-142-48.static.asianet.co.th (210.86.142.48)  9.407 ms 210-86-142-58.static.asianet.co.th (210.86.142.58)  11.746 ms
 7  ppp-171-102-254-97.revip18.asianet.co.th (171.102.254.97)  11.778 ms  14.506 ms  14.481 ms
 8  ppp-171-102-254-228.revip18.asianet.co.th (171.102.254.228)  14.643 ms  14.716 ms  14.598 ms
 9  210-86-143-72.static.asianet.co.th (210.86.143.72)  14.392 ms  17.637 ms  17.367 ms
10  122.155.226.17 (122.155.226.17)  20.884 ms 122.155.226.105 (122.155.226.105)  20.867 ms  13.013 ms
11  61.19.9.222 (61.19.9.222)  61.834 ms  61.779 ms 61.19.9.110 (61.19.9.110)  63.206 ms
12  103.22.203.89 (103.22.203.89)  80.144 ms *  89.271 ms
13  * * *
14  * * *
15  * * *
16  * * *
17  104.19.193.102 (104.19.193.102)  92.277 ms  91.979 ms  92.311 ms
```

**Comment by PeterDaveHello** [comment]
Hi @mikeevstropov , would you please submit your issue here: https://support.cloudflare.com/requests/new, so that Cloudflare engineer can help you to dig the problem, thanks.

**Comment by loommy24** [comment]
It's probably good too if you can provide the output of [cdn-cgi trace](https://cdnjs.cloudflare.com/cdn-cgi/trace), thanks.
