### ISSUE TITLE
Warning with HTTPS certificate

### ISSUE THREAD

**Issue by skibulk** [cdnjs/cdnjs#4068]
I'm using Chrome Version 39.0.2171.65 m. I'm receiving a warning for your HTTPS certificate at this url: https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js

![screenshot 1](https://cloud.githubusercontent.com/assets/6157038/5274516/6dabde30-7a63-11e4-9f8e-bdd3f3ce9a21.jpeg)

**Comment by PeterDaveHello** [comment]
no problem now
