### ISSUE TITLE
Arabic Translation & Layout

### ISSUE THREAD

**Issue by iSeada** [cdnjs/cdnjs#4081]
Hey there,

I would like to share my feedback regarding Arabic section.

The layout is totally broken, that's because of LTR direction, it's supposed to be RTL, Also translation is very bad and seems translated automatically.

I'm ready to contribute to improve Arabic section as much as possible.

**Comment by MattIPv4** [comment]
I'm not sure what this is referring to, I'm not aware of any Arabic section we have anymore. Closing.
