### ISSUE TITLE
need instructions for git auto update 

### ISSUE THREAD

**Issue by ethanpil** [cdnjs/cdnjs#4096]
I see git autoupdate seems to be supported, per #3638  with this syntax:

````
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/jashkenas/underscore.git",
    "basePath": "",
    "files": [
      "underscore-min.js",
      "underscore-min.map",
      "underscore.js"
    ]
  },
````

an you provide some documentation in readme.md?

**Comment by ethanpil** [comment]
Any news on this?

**Comment by PeterDaveHello** [comment]
hmmmm ... sorry that we are still too busy, will do ASAP, you can take a look at #3638  first, there is an example there.

**Comment by ethanpil** [comment]
Thanks for that ref. Based on that I created the following package.json for a new package. I don't see how I can add a new submission.  Can you 1) Check it  and 2) let me know how to submit it?

````
{
  "name": "html-kickstart",
  "filename": "css/kickstart.css",
  "version": "0.94",
  "description": "HTML KickStart",
  "homepage": "http://www.99lime.com/elements/",
  "keywords": [
    "layout",
    "html5",
    "prototyping"
  ],
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/joshuagatcke/HTML-KickStart.git",
    "basePath": "",
    "files": [
      "css/*",
      "js/*"
    ]
  }
}
````

**Comment by PeterDaveHello** [comment]
Looks ok, you mean how to send a PR or what?

**Comment by ethanpil** [comment]
No, I mean what should I put in the PR?

Just create the folder and add package.json and it will pull? Or, does the initial PR need to include the first set of files?

**Comment by PeterDaveHello** [comment]
Should add the fils.

**Comment by PeterDaveHello** [comment]
I added something here:
https://github.com/cdnjs/cdnjs/blob/master/README.md#enabling-gitrecommended-or-npm-auto-update
What do you think?

**Comment by PeterDaveHello** [comment]
Close due to no response.
