### ISSUE TITLE
jquery.swipebox images

### ISSUE THREAD

**Issue by SoftCreatR** [cdnjs/cdnjs#4136]
jquery.swipebox tries to get images from `../img/` (which results in https://cdnjs.cloudflare.com/ajax/libs/jquery.swipebox/img/), but images are placed in `img/` (https://cdnjs.cloudflare.com/ajax/libs/jquery.swipebox/1.2.9/img/)

Could you fix that or do i have to host the CSS + images by myself / overwrite the CSS rules locally to refer to the correct location?

**Comment by Whoknowsit** [comment]
It's not.

	GET https://cdnjs.cloudflare.com/ajax/libs/jquery.swipebox/img/loader.gif 404 (Not Found)
	GET https://cdnjs.cloudflare.com/ajax/libs/jquery.swipebox/img/icons.png 404 (Not Found)
	GET https://cdnjs.cloudflare.com/ajax/libs/jquery.swipebox/img/icons.svg 404 (Not Found)

**Comment by PeterDaveHello** [comment]
Ha, I meant I think it should be fixed, not fixed, sorry, but fixed now! And also add the new versions!

**Comment by Whoknowsit** [comment]
But you forgot to apply the "fix" in the newest version(s) :P
