### ISSUE TITLE
Translations for Chinese Simplified Website is not correct

### ISSUE THREAD

**Issue by leakingtapan** [cdnjs/cdnjs#4158]
The link for http://zh-cn.cdnjs.com/ doesn't show Chinese translations.

**Comment by PeterDaveHello** [comment]
I tried several browsers but didn't see the problem you said, would please provide more details?
[Imgur](http://i.imgur.com/Rl5BlKr.png)

**Comment by leakingtapan** [comment]
This is the screen shot I saw for http://zh-cn.cdnjs.com/

![image](https://cloud.githubusercontent.com/assets/5259480/5606806/b955b828-93f5-11e4-91b6-024fb377050f.png)

After I refreshed several time, I see the screen shot you gave.

If refresh more, I see the error page.

![image](https://cloud.githubusercontent.com/assets/5259480/5606814/7518a19c-93f6-11e4-8fee-12fd2435ff5b.png)

Probably this is not a translations problem I guess.

**Comment by PeterDaveHello** [comment]
Application Error again, ping @thomasdavis for help.

**Comment by PeterDaveHello** [comment]
I got the same problem on zh-TW now.

**Comment by PeterDaveHello** [comment]
I disabled all i18n as they are automatically translated by Google.
@thomasdavis  @ryankirkman maybe we should redirect all the out-dated i18n domain to `cdnjs.com/$1`

**Comment by ryankirkman** [comment]
Sounds reasonable

**Comment by PeterDaveHello** [comment]
Okay, updated the rule to redirect `http(s)://*.cdnjs.com/*` to `https://cdnjs.com/$2`, let's close this, we won't have i18n or l10n so soon, at least for me, as a current main maintainer, this is a minor feature, more and more important feature should be implemented first.

**Comment by PeterDaveHello** [comment]
Reopen since I disabled the rule will cause problem on api.cdnjs.com

**Comment by MattIPv4** [comment]
We no longer have translated versions of the site, closing.
