### ISSUE TITLE
Site: Remove XSS attempts and bad user profiles

### ISSUE THREAD

**Issue by PlNG** [cdnjs/cdnjs#4169]
on [Page 18](https://cdnjs.com/members/18) you have this batch of users.

	</strong></a><br /><img/src=x onerror=alert(1);>
	tarsid
	tarsid%00%0b
	tarsid%00

on [Page 20](https://cdnjs.com/members/20) 

	tareksiddiki%00
	"/><svg/onload=alert(1)>

I don't know if they're causing issues with your profiles.

**Comment by thomasdavis** [comment]
Thanks for finding those and I didn't realize user profiles were down either. Looking into it...

**Comment by PeterDaveHello** [comment]
We don't have member feature any more, at least right now, and it's been for a while, so let's close this, thanks.
