### ISSUE TITLE
Foundation 5.5.0 minified not really minified

### ISSUE THREAD

**Issue by pedzed** [cdnjs/cdnjs#4175]
The minified version of Foundation JS is not minified. The URL is: https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.0/js/foundation.min.js

I checked and [version 5.4.0](https://cdnjs.cloudflare.com/ajax/libs/foundation/5.4.0/js/foundation.min.js) is minified.

**Comment by drewfreyling** [comment]
@PeterDaveHello was your checkin of 218abd03d8058316f07680810b75e13163a3edda by hand or auto update?

**Comment by drewfreyling** [comment]
This isn't a bug on our side @pedzed 
You'll have to raise this with the foundation people as it is unminified in the zip file in http://foundation.zurb.com/cdn/releases/foundation-5.5.0.zip

**Comment by drewfreyling** [comment]
Looks like they are working on a fix -> https://github.com/zurb/foundation/issues/6073

I'll leave this open so if they do fix it we can update it here. Unfortunately we should probably leave it so it is verbatim with what comes down from their site.

**Comment by pedzed** [comment]
> This isn't a bug on our side @pedzed 
> You'll have to raise this with the foundation people as it is unminified in the zip file in http://foundation.zurb.com/cdn/releases/foundation-5.5.0.zip

I didn't think about that. Well, I had to open this issue anyway to get it updated :)

Could you change the label though? This doesn't fit in `bug - high priority`. A new label `bug - low priority` and `bug - medium priority` would be nice. I'd put it in low priority.

**Comment by PeterDaveHello** [comment]
As @drewfreyling said. I'll minify it now.
