### ISSUE TITLE
Add library gumok.js 

### ISSUE THREAD

**Issue by jofpin** [cdnjs/cdnjs#4181]
A simple way to add views of templates. To your client-side developments!

https://github.com/jofpin/gumok

**Comment by PeterDaveHello** [comment]
As you are the author, maybe you can just send a PR? And we prefer to use git auto-update which depends on tags in git repo, so it'll be better to add tag for each version, thanks.

**Comment by jofpin** [comment]
You mean , to add the Path of versions? the .js file will always be there. you explain me better?

**Comment by PeterDaveHello** [comment]
http://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by PeterDaveHello** [comment]
Hi @jofpin, you there? I meant use should use tag feature to tag each version with corresponding commit, okay?

**Comment by PeterDaveHello** [comment]
Close due to no response, and you are welcome to open an issue or PR any time.
