### ISSUE TITLE
Display file sizes again

### ISSUE THREAD

**Issue by jerone** [cdnjs/cdnjs#4187]
Any change that displaying the file sizes is returned to the site? 

All [sizes are logged](https://github.com/cdnjs/cdnjs/pull/3264#event-124979641) and at some point [displayed on the site](https://github.com/cdnjs/cdnjs/pull/3264#issuecomment-44259177). But apparently it is [removed from the site](https://github.com/cdnjs/cdnjs/pull/3264#issuecomment-49494801) around Juli. 

CDNJS is the only site that does this, displaying the sizes is a feature that other sites don't have.

As a site-note, it would be more useful to calculate the file sizes in bytes and let the site display them in kilobytes.

**Comment by PeterDaveHello** [comment]
What do you think @thomasdavis ?

**Comment by rskumar** [comment]
+1 
I just searched cdnjs for D3 library to check its size. It would be nice functionality, where I can check the size of any library and its alternatives and make a decision on that factor (like chart js, which would be heavy but I just need simple lines and circles)

**Comment by jerone** [comment]
It's not fast, but here's a solution I made: https://packagesize.herokuapp.com

**Comment by PeterDaveHello** [comment]
Dear all, if you'll like to have size info in lib's page again, please leave +1 here.
I'll add it back for more then 50 starts :smiling_imp:

**Comment by nlwillia** [comment]
+1

**Comment by kevinSuttle** [comment]
:+1:

**Comment by rayshan** [comment]
:100: 

I constantly check the size of a module before including in a project, so my users aren't bombarded with a huge payload. I bet many developers do this too. Many modules do not include the compiled or minified production builds in their repos, for example, https://github.com/facebook/react. Cdnjs is my go-to as it has a very comprehensive library.

**Comment by rskumar** [comment]
+1

**Comment by thomasdavis** [comment]
+1 - If the library file size goes on the library page
-1 If the file size is displayed on home page

**Comment by rskumar** [comment]
whats homepage and library-page? Did you mean library specific page to that version?

**Comment by thomasdavis** [comment]
Displaying file sizes on these pages -> https://cdnjs.com/libraries/redux

On Fri, Feb 19, 2016 at 3:59 PM, Ravi <notifications@github.com> wrote:

> whats homepage and library-page? Did you mean library specific page to
> that version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/cdnjs/issues/4187#issuecomment-186052068>.
>



-- 
Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by PeterDaveHello** [comment]
@thomasdavis what's the reason why to remove the size info before?

**Comment by drewfreyling** [comment]
i agree with @thomasdavis

**Comment by chrisblakley** [comment]
I'm trying to do some library comparisons between versions, and showing the filesizes would have been immensely helpful for this.

**Comment by jerone** [comment]
In an attempt to clean up my created issues that have not been processed or updated over a year, I'm closing this issue. If this issue is still relevant, please reopen another issue.

**Comment by jerone** [comment]
It appears that the file-size is now also removed from the main [packages.json](https://cdnjs.com/packages.json) in this commit: https://github.com/cdnjs/cdnjs/commit/858762518d72b8e7263c2d17fd27d1e418f94839#diff-a5e1e93b3fda6160a9047e0c3acfd55b 😢
