### ISSUE TITLE
Search functionality doesn't work -- Algolia limit exceeded?

### ISSUE THREAD

**Issue by dpoindexter** [cdnjs/cdnjs#4190]
Opening Dev Tools console gives the following error (along with quite a few JSONP HTTP errors). From the user's perspective, this results in a silent fail -- the search bar just does nothing.

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
algoliasearch.min.js:7 Error: Operations quota exceeded, change plan to get more Operations.
```

**Comment by thomasdavis** [comment]
Good catch Daniel, tagging @redox

**Comment by redox** [comment]
Oh right! I've just converted your account to an unlimited one :) :+1:

**Comment by dpoindexter** [comment]
That was fast! Looks like it's working great.
