### ISSUE TITLE
hammer.js 2.0.4 is serving up html instead of javascript code

### ISSUE THREAD

**Issue by aner-perez** [cdnjs/cdnjs#4196]
Visit https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.js or
https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.4/hammer.min.js and you will get HTML served up instead of Javascript code

**Comment by PeterDaveHello** [comment]
Oops, I'll take a look at it, thanks.

**Comment by drewfreyling** [comment]
This is fixed in 5be4a5a55db79f1789713d316ff75cc419b78a96
