### ISSUE TITLE
Latest version of nanoGALLERY has not been updated on CDNJS

### ISSUE THREAD

**Issue by Kris-B** [cdnjs/cdnjs#4209]
Hi,
I've made a new release (5.3.0) of https://github.com/Kris-B/nanoGALLERY but it hasn't been updated on CDNJS.
Any clue?

**Comment by PeterDaveHello** [comment]
Issue confirmed, I'll check it out, thanks for reporting this.

**Comment by PeterDaveHello** [comment]
Not sure what's the problem, looks okay, and commit in 87835fee626fd408e9620bcf9321952bba2b560e now, I'll preserve the update log in future to trace the auto-update process, thanks.

**Comment by Kris-B** [comment]
@PeterDaveHello many thanks!

**Comment by PeterDaveHello** [comment]
np
