### ISSUE TITLE
Update Nicescroll

### ISSUE THREAD

**Issue by Xarcell** [cdnjs/cdnjs#4218]
Please update Nicescroll to the latest version 3.6.0 which fixes IE Touch Issues.

https://github.com/inuyaksa/jquery.nicescroll

Thanks.

**Comment by glensc** [comment]
any reason why zoomico.png is not included?

**Comment by PeterDaveHello** [comment]
Maybe I just forgot, will add it, thanks!

**Comment by PeterDaveHello** [comment]
@Piicksarn can you help me fix that?
