### ISSUE TITLE
msl-client-browser library not auto updating

### ISSUE THREAD

**Issue by kood1** [cdnjs/cdnjs#4219]
Hello, I created a new tag with the latest update but it looks like it's not auto-updating:

https://github.com/FINRAOS/MSL/releases/tag/v1.0.6
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/msl-client-browser

Thanks.

**Comment by PeterDaveHello** [comment]
Hi @kood1, thanks for reporting this update, I've update our readme to explain the delay of update 
(https://github.com/cdnjs/cdnjs#enabling-npm-auto-update), and just audit and commit this update in de22497, sorry for the inconvenience.

**Comment by kood1** [comment]
No problem, thank you!
