### ISSUE TITLE
Add library KeyderJS

### ISSUE THREAD

**Issue by JacquesMarais** [cdnjs/cdnjs#4245]
Hi. Could you please add the library <a href='https://github.com/GethisOrg/KeyderJS'>KeyderJS</a> to the CDN?

**Comment by PeterDaveHello** [comment]
Yes, of course, I noticed that you are one of the authors of it, would you like to send a PR?

**Comment by JacquesMarais** [comment]
Okay, thank you.

**Comment by JacquesMarais** [comment]
Hi. Sorry, I don't really understand these things. I can't get a pull request made. Is there a guide I could follow maybe please?

**Comment by PeterDaveHello** [comment]
Fork, add a folder for the lib, and its package, its real files, and then push, send PR.
Don't know if this is enough for you?

**Comment by JacquesMarais** [comment]
Thanks, I added it.
