### ISSUE TITLE
API ≠ Site

### ISSUE THREAD

**Issue by chriscoyier** [cdnjs/cdnjs#4258]
Howdy! 

Is [this](http://api.cdnjs.com/libraries?fields=keywords) still the right endpoint for the API?

I'm noticing some differences between the live site and what is in that API. Like this:

![screen shot 2015-01-22 at 14 40 27](https://cloud.githubusercontent.com/assets/69156/5864109/bf63902a-a244-11e4-9f91-0c67fecaf339.png)

Or is there a time delay or something?

**Comment by thomasdavis** [comment]
Hey Chris, checking this out for you now. Every now and then our API server has had problems deploying and falls out of sync...

**Comment by thomasdavis** [comment]
It's fixed now -> http://api.cdnjs.com/libraries/skeleton

Apparently Heroku was having problems running 0.6.x so upped it to 0.10.x (node)

**Comment by chriscoyier** [comment]
perfect
