### ISSUE TITLE
Update FontAwesome to 4.3.0

### ISSUE THREAD

**Issue by SoftCreatR** [cdnjs/cdnjs#4264]
https://github.com/FortAwesome/Font-Awesome/releases/tag/v4.3.0

**Comment by Whoknowsit** [comment]
https://github.com/cdnjs/cdnjs/commit/77ae80aeac2e5257142ec77dec1f6b05b02a0dd5

**Comment by PeterDaveHello** [comment]
Thanks Whoknowsit.
