### ISSUE TITLE
Two plugins with the same name were added as different versions of one plugin.

### ISSUE THREAD

**Issue by mouse0270** [cdnjs/cdnjs#4269]
It appears that someone took my plugin and made it a version of the other. On https://cdnjs.com/libraries/bootstrap-growl you can see version 1.0.0 and 1.0.6. Version 1.0.0 is ifightcrimes plugin and version 1.0.6 is mine, these two plugins work differently and have different documentation and features. I have noticed people are posting issues because they are trying to use my plugin that they got from your site with his documentation.

ifightcrims: https://github.com/ifightcrime/bootstrap-growl
Mouse0270: https://github.com/mouse0270/bootstrap-growl

PS: this will not be a problem after I update my plugin to version 3.0.0. I have noticed this is causing an issue and decided to rename my plugin. So this issue will be prevented in the future.

@PeterDaveHello has asked me to tag @thomasdavis and @drewfreyling in this issue.

**Comment by thomasdavis** [comment]
Ouch, this is an unfortunate problem. hrmm....

**Comment by thomasdavis** [comment]
Due to the nature of the project, we can't retrospectively change the files, otherwise we cause sites to break. I imagine from now on, we will only add ifightcrimes version to cdnjs/bootstrap-growl and then create a new directory for your new version?

**Comment by mouse0270** [comment]
The worst thing about it is the fact that my plugin works differently than his and everyone who uses 1.0.6 tries it with his documentation and fails. They eventually either give up or someone says hey... This is actually mouse0270 plugin you need to check out his documentation. haha.

The bad thing is I know you can't just remove it without breaking peoples sites who are using it and I don't really think that is a good idea.

My best idea would be maybe add a note in the description stating something like:

If using version 1.0.6 please refer to http://bootstrap-growl.remabledesigns.com/1.0.6/ for documentation.

**Comment by PeterDaveHello** [comment]
Sounds reasonable ... maybe we just add dir named like mouse0270-bootstrap-growl or you named it.

**Comment by mouse0270** [comment]
@Packetslave When I release the next version it will be renamed to something like bootstrap notify or bootstrap notification. So their isn't another package with that name, so it would resolve this issue.

**Comment by PeterDaveHello** [comment]
Okay, that's good.

**Comment by MattIPv4** [comment]
No further progress, closing.
