### ISSUE TITLE
nvd3

### ISSUE THREAD

**Issue by joeflateau** [cdnjs/cdnjs#4283]
Novus has discontinued nvd3.

The community fork should be added to cdnjs:
https://github.com/nvd3-community/nvd3/

**Comment by PeterDaveHello** [comment]
Interesting, I found this in origin repo, different with that one you provide, any idea?

For those interested in a fork of NVD3 that is being actively maintained by a community member, please see: https://github.com/liquidpele/nvd3

**Comment by joeflateau** [comment]
@PeterDaveHello yes, and the README on the liquidpele repo refers you to the nvd3-community repo. liquidpele forked the novus repo to a personal repo, then created the nvd3-community organization.

**Comment by PeterDaveHello** [comment]
Looks okay to do this.
