### ISSUE TITLE
knockout-validation did not update

### ISSUE THREAD

**Issue by crissdev** [cdnjs/cdnjs#4316]
The library did not update after releasing 2.0.2 https://cdnjs.com/libraries/knockout-validation. Do I need to submit a PR or something? Thanks.

[npm package](https://www.npmjs.com/package/knockout.validation)
[releases on github](https://github.com/Knockout-Contrib/Knockout-Validation/releases)

**Comment by PeterDaveHello** [comment]
https://cdnjs.cloudflare.com/ajax/libs/knockout-validation/2.0.2/knockout.validation.min.js is available, just the index didn't update yet, let's call @thomasdavis for help, thanks.

**Comment by crissdev** [comment]
The version is now visible. Thanks for your help.

**Comment by PeterDaveHello** [comment]
np
