### ISSUE TITLE
Please improve supporting for dojo

### ISSUE THREAD

**Issue by spance** [cdnjs/cdnjs#4329]
dojo is a high quality and powerful js framework, but now cdnjs only has dojo-core 1.9.3 version.
Please add dojo 1.10.4 full version that is the latest release.

http://dojotoolkit.org/download/

**Comment by spance** [comment]
Thanks for update.
But that is just dojo base (only one file dojo.js), please add the dojo toolkit full version.
http://download.dojotoolkit.org/release-1.10.4/dojo-release-1.10.4.tar.gz  (8.6MB) This archive contains the full Dojo, Dijit, and DojoX projects, compressed and optimized for immediate deployment.

**Comment by PeterDaveHello** [comment]
I'm not sure what files should be included, there is only one line on official page:
`<script src="//ajax.googleapis.com/ajax/libs/dojo/1.10.3/dojo/dojo.js"></script>`
If you think there are some missing files, please send PR to us, thanks.

**Comment by spance** [comment]
```<script src="//ajax.googleapis.com/ajax/libs/dojo/1.10.3/dojo/dojo.js"></script>```
This link is a correct way for reference that is the dojo main file, and dojo will load other packages base on "ajax.googleapis.com/ajax/libs/dojo/1.10.3/".
The full dojo: http://download.dojotoolkit.org/release-1.10.4/dojo-release-1.10.4.tar.gz
So you should decompress that archive to "cdnjs.cloudflare.com/ajax/libs/dojo/1.9.3/"
then the dojo main file is "cdnjs.cloudflare.com/ajax/libs/dojo/1.9.3/dojo/dojo.js".

**Comment by PeterDaveHello** [comment]
There are also many files are not needed in that tarball, so if you know what will be needed, I'll need your help to tell us, or send PR to us.

**Comment by spance** [comment]
That's right, dojo is a very powerful framework, so many files is the dojo internal requirement if you want using dojo GUI and many features.
It really contains many files likes Extjs, YUI... so we only have to push that full files for full supporting dojo like ajax.googleapis.com.

**Comment by PeterDaveHello** [comment]
No, it's not the right way to do this, including all the files will also place the useless files on cdn, like license files, who will check out that files on cdn? I don't think so, we need a right method to do this.

**Comment by PeterDaveHello** [comment]
Manually added in f20be560663c868091f9ef1850043063c384dcde, hope it works.

**Comment by spance** [comment]
That achive don't contains any useless files.(excluding /build-report.txt), and that files is already  compressed and optimized for immediate deployment.
ajax.googleapis.com has the dojo full supporting, such as "ajax.googleapis.com/ajax/libs/dojo/1.10.3/dijit/_base.js" , "ajax.googleapis.com/ajax/libs/dojo/1.10.3/dojox/color/api/ColorModel.js"

**Comment by PeterDaveHello** [comment]
README, LICENSE, package.json build.txt blank.html ... many useless files I think ...
If you know the correct files, please just send a PR, will be more useful, thanks.

**Comment by PeterDaveHello** [comment]
And we don't want to touch the already exist file structure, I'll try to include w other directories in next release, thanks for reporting this.

**Comment by spance** [comment]
this is a large repository, the transferring will be very difficult in my network environment. I'm so sorry for can't create PR.
Thanks for your working. I will test it later.
