### ISSUE TITLE
How long to git autoupdate?

### ISSUE THREAD

**Issue by aurri** [cdnjs/cdnjs#4342]
Curious if there were any issues with the recent [Riot](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/riot) autoupdate. It's been a while since the last [release](https://github.com/muut/riotjs/releases).

How long does it normally take for the new git autoupdate to pick up the new version?

**Comment by PeterDaveHello** [comment]
Same as npm
https://github.com/cdnjs/cdnjs#enabling-npm-auto-update
```
the update result won't be committed until one of our maintainers audit the diff, bacause many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most 30 hours, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it
```
