### ISSUE TITLE
Update AngularJS to 1.3.13.

### ISSUE THREAD

**Issue by avrozenbaum** [cdnjs/cdnjs#4350]
Someone should update AngularJS to 1.3.13. We only have up to 1.3.12 right now.

**Comment by PeterDaveHello** [comment]
https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.13/angular.min.js

**Comment by avrozenbaum** [comment]
It is not listed on cdnjs.

**Comment by PeterDaveHello** [comment]
@thomasdavis will figure it out, but the files already on cdn so you can use it.
