### ISSUE TITLE
Where is Swiper 3.0.1 release?

### ISSUE THREAD

**Issue by kireerik** [cdnjs/cdnjs#4377]
Swiper has some [newer releases](https://github.com/nolimits4web/Swiper/releases), but I can't find it on [cdnjs](https://cdnjs.com/libraries/swiper). It should be auto updated, am I right? What cause this issue?

**Comment by PeterDaveHello** [comment]
Seems they changed the structure.

**Comment by PeterDaveHello** [comment]
Added in 0183640

**Comment by kireerik** [comment]
Thank you for resolving this issue!

**Comment by PeterDaveHello** [comment]
np
