### ISSUE TITLE
Added /latest/ path alias for each plugin

### ISSUE THREAD

**Issue by Jakobud** [cdnjs/cdnjs#4396]
It would be nice to just add an automatically updating `/latest/` alias for each plugin that always points to the latest version. So you could simply do something like this:

`//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/latest/css/bootstrap.min.css`

instead of 

`//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/css/bootstrap.min.css`

**Comment by PeterDaveHello** [comment]
I remember that I had told about this issue, but don't remember if cloudflare's cdn support symbolic link or not.
Mention @terinjokes & @thomasdavis to give their comments, thanks!

**Comment by Jakobud** [comment]
Actually you know what, I think this might be a terrible idea. The whole purpose of a CDN is that a certain version of a resource is cached on a server. If "latest" is cached on a server and then latest changes to a new version then you are now caching the wrong version. The cached latest is no longer pointing to the latest version.

**Comment by terinjokes** [comment]
Google CDN used to support an equivalent of "latest", based on major and minor versions, before they froze the versions and removed the references from the documentation.

I see no reason in reversing that decision here.

**Comment by Jakobud** [comment]
Hense why I closed the issue and said it was a bad idea. Thanks,
