### ISSUE TITLE
Update Foundation

### ISSUE THREAD

**Issue by Vithon** [cdnjs/cdnjs#4406]
Latest release is 5.5.1.
Release 5.5.0 is currently in repo.

http://foundation.zurb.com/develop/download.html
5.5.1: http://foundation.zurb.com/cdn/releases/foundation-5.5.1.zip

Located in tree at `/ajax/libs/foundation{,-essential}/`

**Comment by drewfreyling** [comment]
Please feel free to add a PR for this one.

**Comment by PeterDaveHello** [comment]
See 2bda989 & 6f625fe please.
