### ISSUE TITLE
Auto update jsoneditor to v4.0.0 failed?

### ISSUE THREAD

**Issue by josdejong** [cdnjs/cdnjs#4423]
It seems like the auto update of jsoneditor missed the [v4.0.0 release](https://github.com/josdejong/jsoneditor/tree/v4.0.0) (9 days ago). The `npmFileMap` field in this projects [package.json](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jsoneditor/package.json) file on cdnjs is still up to date and should work ok. 

Can you please update jsoneditor to v4.0.0? Would be great!

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by PeterDaveHello** [comment]
fixed in 56ec9fa & c677f37

**Comment by josdejong** [comment]
Thanks for the quick action (as always :))

@PeterDaveHello  I see you do all updates manually, which must be quite some work. Is that on purpose to keep control, or are you maybe planning on a fully automatic update system?

**Comment by PeterDaveHello** [comment]
Fully automatic update may make the project in mess because projects may change their structure, this time and this case, it didn't, but we got kind of this problem many times before, we still need to spend our time to trace and fix it, so I will audit everything changed by our updated, and then commit.

**Comment by josdejong** [comment]
Yes, that makes sense. Well, at least this makes sure a certain quality is guaranteed. Are you considering setting up some tooling such that people can do the updates themselves (for example like npm)?

**Comment by PeterDaveHello** [comment]
You can always do it, take a look at auto-update.js please.

**Comment by PeterDaveHello** [comment]
And BTW, we may need to manually minify the files, auto-updater can not easily do it perfectly.

**Comment by josdejong** [comment]
Quite some tricky details. Maybe this manual curation is what makes cdnjs stand out from the others.

Thanks for all your work!

**Comment by PeterDaveHello** [comment]
You're welcome.
