### ISSUE TITLE
Actualizar hover.css

### ISSUE THREAD

**Issue by Dinasty0** [cdnjs/cdnjs#4430]
Actualmente se encuentra en la v2 y la actual es la v1

**Comment by PeterDaveHello** [comment]
Would you please use English? Thanks!

**Comment by AndreiTelteu** [comment]
This was updated at #4500 and the new version is found here:
https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.0.2/css/hover.css
You may close this.

**Comment by PeterDaveHello** [comment]
@Dinasty0 ?

**Comment by PeterDaveHello** [comment]
Close due to no response.
