### ISSUE TITLE
Is cdnjs.com down?

### ISSUE THREAD

**Issue by brenoc** [cdnjs/cdnjs#4431]
Hi, I'm trying to access [cdnjs.com](http://cdnjs.com/) and I got:

>**Heroku | No such app**
There is no app configured at that hostname.
Perhaps the app owner has renamed it, or you mistyped the URL.

**Comment by PeterDaveHello** [comment]
Oops ...

**Comment by olso** [comment]
Pls

**Comment by brenoc** [comment]
The site is up, but the API is down #4447
