### ISSUE TITLE
Toastr isn't updating

### ISSUE THREAD

**Issue by drewfreyling** [cdnjs/cdnjs#4434]
I'm hoping https://github.com/CodeSeven/toastr/issues/263 fixes it. If not, I'll manually update it.

**Comment by PeterDaveHello** [comment]
Seems our updater ignored some versions ... it said 
`Need 1.1.5,1.3.0,v1.2.0,v1.2.1,v1.2.2` while updating, but there is no 2.1.1 in the list ...

**Comment by PeterDaveHello** [comment]
It was fixed in 69ee0d9.
