### ISSUE TITLE
NPM Update on react-cookie not working

### ISSUE THREAD

**Issue by eXon** [cdnjs/cdnjs#4451]
The library react-cookie has been updated to 0.1.4 3 days ago but it is still not updated through NPM. It might be because I made a release between the request and the approbation of the lib. 

Is their a way to force the update check on NPM? (the config file is already setup for this)

Thank you!

**Comment by eXon** [comment]
It might be because you need to run `npm run build` to get the dist files. Is their any way to automate that in the package.json?

**Comment by PeterDaveHello** [comment]
We don't support building ilbs in the auto-update process yet, but we'll accept pull requests to enable it if you would like to do.
I noticed that you also put the dist files in the git repo on the release tags, so I think transferring to use git auto-update as #3638 said will be easier.

**Comment by PeterDaveHello** [comment]
fixed in 1b53508 and updated in bc33fad

**Comment by eXon** [comment]
Awesome, the git tags were for bower so I guess it will do the work for cdnjs too :+1: 

Thanks for the quick relpy :)

**Comment by PeterDaveHello** [comment]
np
