### ISSUE TITLE
Minified Version of JS Not Showing on Website - foundation.min.js (v 5.5.1)

### ISSUE THREAD

**Issue by r-clancy** [cdnjs/cdnjs#4452]
Hello,

I see there is a commit for minifying "foundation.min.js", but the version that appears on the site in the un-minified one.

Is this something that should be reflected on the website now, or will the change be coming soon?

Commit: https://github.com/cdnjs/cdnjs/commit/17a7af2b3df80f3bc9c06f1d2c93d58468a4a35c
Webpage: https://cdnjs.com/libraries/foundation
File: https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.1/js/foundation.min.js

Thanks.

**Comment by PeterDaveHello** [comment]
![Imgur](http://i.imgur.com/yyjoI6c.png)

**Comment by rylinaux** [comment]
@PeterDaveHello 
If you open that file, it isn't the minified version.

**Comment by PeterDaveHello** [comment]
Oh yeah, you are right, tag @terinjokes for help, thanks!

**Comment by rylinaux** [comment]
@terinjokes 
Are you able to resolve this issue?

**Comment by drewfreyling** [comment]
@PeterDaveHello any idea why 17a7af2b3df80f3bc9c06f1d2c93d58468a4a35c doesn't actually seem to be applied? That commit seemed to minify it....

**Comment by PeterDaveHello** [comment]
I don't know, that's the reason why I need to mention @terinjokes.

**Comment by cjmaxik** [comment]
5.5.2 too

**Comment by PeterDaveHello** [comment]
hmmmm ... this is totally foundation's problem ...

**Comment by PeterDaveHello** [comment]
poke @terinjokes for v5.5.1 issue, it should be really minified!

**Comment by PeterDaveHello** [comment]
Looks fine now, so close this.
