### ISSUE TITLE
make cdnjs cookie free domain

### ISSUE THREAD

**Issue by pushkeryadav** [cdnjs/cdnjs#4453]
cookies are not required for static contents and cookies less domain load faster, so make cdnjs cookies free to load js  files faster.

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by terinjokes** [comment]
cdnjs.cloudflare.com is a cookieless domain.

```
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/1140/2.0/1140.css
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Wed, 18 Mar 2015 21:28:16 GMT
Content-Type: text/css
Connection: keep-alive
Last-Modified: Mon, 13 Jan 2014 18:19:11 GMT
Expires: Mon, 07 Mar 2016 21:28:16 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
CF-RAY: 1c9406bc7b3a012b-SJC
```

**Comment by pushkeryadav** [comment]
curl is not showing cookie sent by domain.

if you want to see , just simple check in browser, in chrome enter
*chrome://settings/cookies*
*i*n tab and search for cdnjs.com you will see.

[image: Inline image 1]

**Comment by terinjokes** [comment]
I only have cookies for cdnjs.com, I don't have cookies for cdnjs.cloudflare.com.

**Comment by pushkeryadav** [comment]
if you request this jquery for example
http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js

than you will get a cookie name __cfduid for domain .cloudflare.com

so I am requesting a js file which is static so why need cookie.

**Comment by terinjokes** [comment]
https://www.dropbox.com/s/8ndnvuf9ekc8dis/Screenshot%202015-03-19%2022.38.15.png?dl=0

**Comment by PeterDaveHello** [comment]
Close due to no response.
