### ISSUE TITLE
Make library adding process easier [$5]

### ISSUE THREAD

**Issue by IonicaBizau** [cdnjs/cdnjs#4461]
Since this repository has a big size (~7GB, and **still counting**!), `git` commands are soooo slow.

Example:

``` sh
$ time git status
On branch svg.pan-zoom
nothing to commit, working directory clean

real    0m1.966s
user    0m1.448s
sys     0m1.368s
```

So, adding a new library is pretty slow...

Any ideas how to solve this?

**Comment by PeterDaveHello** [comment]
Yeah ... we'll move the real files to another repo in future.

**Comment by IonicaBizau** [comment]
The thing is that this repository will be still big (because of the git history). The good thing is that you can rewrite the git history, the bad thing is that the old commit links will be broken or so.

**Comment by PeterDaveHello** [comment]
Maybe put them out of the repo, I don't have time to figure it out yet.

**Comment by PeterDaveHello** [comment]
But any suggestions are welcome.

**Comment by IonicaBizau** [comment]
I created this tiny command line tool to automatize this process: https://github.com/IonicaBizau/cdnjs-importer

The usage is so simple:

```sh
$ cdnjs-importer <git-url>
```

Hope you enjoy using it! :smile:

**Comment by PeterDaveHello** [comment]
Okay I'll take a look at it, thanks.

**Comment by PeterDaveHello** [comment]
Looks cool, how to set the file set instead of grab all the files into cdnjs? Thanks :dancer:

**Comment by IonicaBizau** [comment]
@PeterDaveHello What's the use case?
Currently the command line script is pretty limited, but you can use it as module:

```js
// Dependencies
var CdnJsImporter = require("cdnjs-importer"),
    Path = require("path");

// Test adding CaiuSS
CdnJsImporter({
    cdnjs: Path.resolve(__dirname, "../../cdnjs"),
    debug: true,
    libs: [{
        git: "git@github.com:IonicaBizau/CaiuSS.git",
        map: [{
            {
                basePath: "/dist",
                files: ["*"]
            }
        }]
    }]
}, function (res) {
    console.log(res);
});
```

Something like this? If you find any limitation, please kindly open issues. :smile:

**Comment by PeterDaveHello** [comment]
Yeah, I meant in command line, seems this is a cool project, ha :+1:

**Comment by IonicaBizau** [comment]
@PeterDaveHello Yep, you can extend the bin script. I'd be happy to accept contributions. :smile:

**Comment by IonicaBizau** [comment]
@PeterDaveHello Can I make a PR with how to to use this little CLI app?

**Comment by PeterDaveHello** [comment]
Sure please.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Thanks! See #4522.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Now we support adding a lib by a single package.json, the key point is to drop version in package.json, and has a valid auto-update config, that's all.

Please take at look at this as an example:
cdnjs/cdnjs#7149

Hope this help you to send a PR to add a new lib! :smile:

**Comment by MattIPv4** [comment]
@PeterDaveHello I feel this is probably one of the big issues with cdnjs currently. Any further thoughts on the best way to split up the repo so that it is usable by anyone wanting to add a new lib?

The ideas @AmNotADev and I had were:
 - Move all package.json files to a new repo
 - This new repo would become cdnjs/cdnjs and would be the main repo for users
 - Rename the current cdnjs/cdnjs to something like cdnjs/libs
 - This would hold all the actual lib files that Cf host

Limitations with this, however, are that asset files could not be manually PR'ed, so everything would need to use git/npm autoupdate package.json configs?

**Comment by xtuc** [comment]
We are not over 200Gb and we need to improve. We will do it, no need to keep this issue
