### ISSUE TITLE
Update README for filename and git auto-update

### ISSUE THREAD

**Issue by Ryuno-Ki** [cdnjs/cdnjs#4463]
I'm currently process of getting a new lib into CDNjs (see #4456). Hereby I noticed, that `filename` in *package.json* isn't documented on the official npm docs, but required by the CI.

@PeterDaveHello pointed me to #3638 as well, so I'd suggest, you update the README in order to save some time on both ends. I assume, with *git auto-update* a [update hook on server](http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#idp17717392) is meant …

**Comment by IonicaBizau** [comment]
:+1:

I managed to find out the `filename` thing when I read the test files (tests were failing).

**Comment by PeterDaveHello** [comment]
I think README told about this:

https://github.com/cdnjs/cdnjs#create-or-update-packagejson
> (see test/schemata/npm-package.json for details or use another package.json to crib from - it's pretty self-explanatory)

Any way, I did something in 42eaf1647587d1f612a0a2889fd6bebbfc6a83be, I think this may help, what do you think guys?

**Comment by Ryuno-Ki** [comment]
@PeterDaveHello I miss the structure, the scripts expect to be there.
Strings, Arrays and so on. Wherefore is it used?
(By comparing and digging into the CI script I could figure it out …)

**Comment by PeterDaveHello** [comment]
Sorry that I didn't get your point, what does `Wherefore is it used?` mean here?

**Comment by Ryuno-Ki** [comment]
At which point, the values are consumed to accomplish which task?

**Comment by IonicaBizau** [comment]
@Ryuno-Ki Look in the [auto-update.js script](https://github.com/cdnjs/cdnjs/blob/master/auto-update.js).

**Comment by PeterDaveHello** [comment]
For filename:
https://github.com/cdnjs/cdnjs#create-or-update-packagejson
For git auto-update:
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update
