### ISSUE TITLE
Is it a requirement to add the old versions?

### ISSUE THREAD

**Issue by IonicaBizau** [cdnjs/cdnjs#4471]
What happens if I don't add the older versions of a library? Will they be automatically fetched or just ignored?

/cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
You don't need to add them, I'll pick them via auto-updater.

**Comment by IonicaBizau** [comment]
Cool! Is that implemented already?

**Comment by PeterDaveHello** [comment]
Yes.

**Comment by IonicaBizau** [comment]
Awesome! :+1: 
I'm working on a tool to simplify adding libraries in cdnjs. /cc #4461

**Comment by PeterDaveHello** [comment]
Oh, sweet!
