### ISSUE TITLE
Algolia indexing needs tweaked on CDNJS.com

### ISSUE THREAD

**Issue by 9mm** [cdnjs/cdnjs#4513]
I just implemented Algolia on my own site, and I love it!

That's unrelated to the problem I saw, however, which is that you have some things coming up as undefined.

![cdnjs_com_-_the_missing_cdn_for_javascript_and_css](https://cloud.githubusercontent.com/assets/1386207/6957464/4585feb2-d8c9-11e4-9e25-e73d5c368021.png)

**Comment by PeterDaveHello** [comment]
Thanks, let's see if this will work : 5aa38e1, if so, I think we should make it support `repository` field.

**Comment by PeterDaveHello** [comment]
Hmmmm ... not work at all ...

**Comment by PeterDaveHello** [comment]
@thomasdavis : Would you please also take a look at this issue? thanks!

**Comment by PeterDaveHello** [comment]
@9mm The problem came from the moved repo, and the node-github api we used can't handle this kind of case, I opened issue here https://github.com/mikedeboer/node-github/issues/257, and updated the repo url in f5603d8, so close this issue, thanks for your report.
