### ISSUE TITLE
bootstrap-table 1.7 is actually the 1.6 files

### ISSUE THREAD

**Issue by D144** [cdnjs/cdnjs#4515]
bootstrap-table latest version is 1.7.0, but the actual files in https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.7.0/ are the 1.6.0 versions

**Comment by PeterDaveHello** [comment]
I think you should open issue here:
https://github.com/wenzhixin/bootstrap-table/
As you can see, that's not our issue.
https://github.com/wenzhixin/bootstrap-table/blob/1.7.0/dist/bootstrap-table.min.js

**Comment by PeterDaveHello** [comment]
Are you still there? I may close this issue due to no response here.

**Comment by PeterDaveHello** [comment]
Close due to no update.
