### ISSUE TITLE
[Request]Add strapdown

### ISSUE THREAD

**Issue by SoftCreatR** [cdnjs/cdnjs#4527]
See https://github.com/arturadib/strapdown

**Comment by PeterDaveHello** [comment]
There is no any identified version number so that I can not add it, maybe you can open an issue ticket there?

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #56](https://github.com/arturadib/strapdown/issues/56)

**Comment by Piicksarn** [comment]
@SoftCreatR, thanks for your suggestion!
However, we could not get versions number so far.
would you please open an issue again when the repo including tags for versions?:smiley:

**Comment by Piicksarn** [comment]
@SoftCreatR, 
the issue closed for no response!
would you please open an issue again when the repo including tags for versions?
thanks!
