### ISSUE TITLE
New version of lodash (3.6.0) is not available

### ISSUE THREAD

**Issue by NameFILIP** [cdnjs/cdnjs#4528]
See https://github.com/lodash/lodash/issues/1107

**Comment by NameFILIP** [comment]
Looks very simple. Do you simply have to clone the repo and run `npm update lodash`? It's not very clear from the readme...

**Comment by PeterDaveHello** [comment]
Nope, usually you won't need to run the updater, so there is no document for it. And we use git auto-update here not npm. I replied the reason why not update lodash but was deleted by the author, seems he'll like to use force push to overwrite the repo, which will cause `git pull` not work, I just use `git fetch` to update the local repo to prevent this problem now.
