### ISSUE TITLE
Semantic UI RTL Version missing.

### ISSUE THREAD

**Issue by abdelouahabb** [cdnjs/cdnjs#4534]
Hi, first thank you for what you are doing,
the build of SUI misses the RTL (right to left) version https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/semantic-ui/1.11.6 and if I try to make the pull request, I need to download all the repo, and I dont have a good connection speed, and sadly GitHub will not allow me to just upload the missing files, and editing them one is not a good solution, so, I made the RTL build and upload it on a separate repo, https://github.com/abdelouahabb/semantic-ui-rtl where it is written `rtl` that means it is the version that contains it, so I wished it will be updated?

**Comment by abdelouahabb** [comment]
ah! wonderful! thank you ^_^

**Comment by PeterDaveHello** [comment]
np

**Comment by abdelouahabb** [comment]
:+1:
