### ISSUE TITLE
Trianglify not auto-updating [author]

### ISSUE THREAD

**Issue by qrohlf** [cdnjs/cdnjs#4538]
Hi!

I released v0.2.0 of [Trianglify](https://github.com/qrohlf/trianglify) a few days ago and the auto-update functionality doesn't seem to be working on CDNJS.

I'm not entirely sure what's going wrong, the only material change to package.json is [this commit](https://github.com/qrohlf/trianglify/commit/4dd5f71e43e6693daaa0cb15ba14a33c6200c5d0), and I believe that is still the correct syntax for cdnjs.

Anyways, any help would be appreciated, as some of my documentation examples are broken until v0.2.0 is available on CDNJS.

**Comment by PeterDaveHello** [comment]
Correct syntax, but wrong path, I'll fix it now.

**Comment by qrohlf** [comment]
15a82fa24167e083a041e2384642c28051c12bdc is problematic because the unminified source needs to be processed with a module bundler like Browserify to function. 

I decided in v0.2.0 to only support minified bundled builds. Just submitted #4543 to remove the unminified source file.

**Comment by PeterDaveHello** [comment]
okay
