### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on materialize

### ISSUE THREAD

**Issue by jimzhan** [cdnjs/cdnjs#4547]
I'm getting these on my Chrome console when using materialize CSS:

``` bash
Font from origin 'http://cdnjs.cloudflare.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by terinjokes** [comment]
@jimzhan can you tell me which font was being fetched? I thought I had all of them.

**Comment by jimzhan** [comment]
@terinjokes They r all materialize's assets (Roboto & Icons) [Materialize](https://cdnjs.com/libraries/materialize)

**Comment by terinjokes** [comment]
@PeterDaveHello The woff2 file is referenced in the CSS, but it doesn't exist in the git repo. Can you check the script?

**Comment by PeterDaveHello** [comment]
@terinjokes Okay, sorry that I didn't notice that.
@jimzhan Would you please tell me which version you are using? I think you should make sure the files appears on https://cdnjs.com/libraries/materialize.

**Comment by PeterDaveHello** [comment]
Added here:
* c48cf74 add angular-busy v4.1.3 Peter Dave Hello 23 seconds ago

@jimzhan Would you please try again later?

**Comment by jimzhan** [comment]
@PeterDaveHello its 0.96.1 materializecss, problem remains the same.

**Comment by PeterDaveHello** [comment]
Please wait for 30 mins and retry.

**Comment by terinjokes** [comment]
It seems fine here now.

**Comment by PeterDaveHello** [comment]
@jimzhan do you still have this problem? Thanks.

**Comment by MattIPv4** [comment]
Very much a dead issue at this point. I will close this. If it happens to still be an issue, let me know.
