### ISSUE TITLE
Add ember-template-compiler.js

### ISSUE THREAD

**Issue by juansev** [cdnjs/cdnjs#4553]
Please add to the CDN the dynamic template compiling tool for EmberJS.
They offer links but they are only HTTP and it would be nice to have both EmberJS core and the utililty in the same CDN in HTTPS

In this page you can find the download, latest stable version is 1.11.1
http://emberjs.com/builds/#/tagged

**Comment by PeterDaveHello** [comment]
Done in 190d6b0
