### ISSUE TITLE
Update Fabric.js to 1.5.0 [author]

### ISSUE THREAD

**Issue by kangax** [cdnjs/cdnjs#4564]
We have released a new version today, but I can't submit a proper PR due to the large size of the repo (I simply don't have extra 4gigs on my machine right now). The minified distribution file is here — https://github.com/kangax/fabric.js/blob/master/dist/fabric.min.js

Thanks!

**Comment by PeterDaveHello** [comment]
Okay, I'll take it later.

**Comment by PeterDaveHello** [comment]
I think it was already updated:
* 8f96bc0 add fabric.js v1.5.0 Peter Dave Hello 14 hours ago

Please confirm it.

**Comment by kangax** [comment]
Yep, all good! Thanks.
