### ISSUE TITLE
Week security configuration.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#4567]
Thanks for report from @celsoazevedo, @terinjokes would you please help us fix it? Thanks!
![img](https://i.imgur.com/j9HLyrv.png)

**Comment by PeterDaveHello** [comment]
cc @thomasdavis @ryankirkman

**Comment by terinjokes** [comment]
I'm already on it.

**Comment by PeterDaveHello** [comment]
Thanks @terinjokes!

**Comment by PeterDaveHello** [comment]
Looks good now.
