### ISSUE TITLE
invalid lodash v3.7.0.

### ISSUE THREAD

**Issue by jdalton** [cdnjs/cdnjs#4568]
I had forgotten the automation was changed to look to bower and tagged a release in that branch before being finished. I noticed the [copy on cdnjs](https://cdnjs.com/libraries/lodash.js) does not have a fix that the official 3.7.0 has.

**Comment by PeterDaveHello** [comment]
Also the lodash-compat?

**Comment by jdalton** [comment]
lodash-compat seemed ok.

**Comment by PeterDaveHello** [comment]
Would you like to send a PR to update it or let me do it?

**Comment by jdalton** [comment]
If you've got it handy I'll defer to you.

**Comment by PeterDaveHello** [comment]
I can do it, but you have to wait for about 1 hour, I'm outside now.

**Comment by PeterDaveHello** [comment]
Hey @jdalton, I re-download from the url on https://lodash.com/, but there is no difference.

**Comment by jdalton** [comment]
Ah fixed!

**Comment by PeterDaveHello** [comment]
Fixed now, but
