### ISSUE TITLE
[author] Validate.js is not auto updating

### ISSUE THREAD

**Issue by ansman** [cdnjs/cdnjs#4570]
I published version 0.7.1 3 days ago and it still hasn't been updated on cdnjs, is something broken perhaps?

**Comment by PeterDaveHello** [comment]
npm auto-update is not reliable sometime, I just transfer this lib to use git auto-update and update it in these two commits:

* 8ca9224 transfer validate.js to use git auto-update Peter Dave Hello 10 minutes ago 
* 9a2162d add validate.js v0.7.1 Peter Dave Hello 12 minutes ag

**Comment by ansman** [comment]
Thanks!
