### ISSUE TITLE
copy doesn't copy the library url to clipboard in firefox

### ISSUE THREAD

**Issue by nitinsurana** [cdnjs/cdnjs#4574]
Steps to reproduce :

1. Open firefox
2. Browse to cdnjs.com
3. Click copy against any library
4. Try to paste, notice the URL can't be pasted because it's not copied to the clipboard.

Works fine in chrome though.

**Comment by nitinsurana** [comment]
It is related to Flash. After installing Flash, "copy" is working fine. May be we can show the user a messgae in case flash is not installed.

**Comment by drewfreyling** [comment]
I'm thinking we can hide the copy button all together when flash is installed. We use zeroclipboard to achieve this function. Maybe we can only show the copy button if we get the `ready` event back from zeroclipboard. Feel free to add a PR for this!

**Comment by PeterDaveHello** [comment]
@nitinsurana would you please confirm that if you still have this problem?
