### ISSUE TITLE
Vue.js' latest version is not auto-updated from npm

### ISSUE THREAD

**Issue by yyx990803** [cdnjs/cdnjs#4580]
As the title says... the latest version (0.11.8) was released 4 days ago but the version on cdnjs is still 0.11.5 from 3 months ago.

**Comment by jcoffland** [comment]
+1

**Comment by PeterDaveHello** [comment]
Sorry about that, I transferred it to use git auto-update now, more reliable updater, I think it'll not be missed any more!

* ed079b5 add vue v0.11.6~0.11.8 Peter Dave Hello 4 minutes ago
* 200f45e transfer vue to use git auto-update Peter Dave Hello 5 minutes ago

**Comment by yyx990803** [comment]
:+1: Thanks!
