### ISSUE TITLE
http://cdnjs.com/packages.json down

### ISSUE THREAD

**Issue by binki** [cdnjs/cdnjs#4590]
ohnobinki@ohnopublishing /tmp $ http_proxy= wget --server-response http://cdnjs.com/packages.json
    --2015-04-27 18:20:53--  http://cdnjs.com/packages.json
    Resolving cdnjs.com... 2400:cb00:2048:1::a29f:f829, 2400:cb00:2048:1::a29f:f729, 162.159.247.41, ...
    Connecting to cdnjs.com|2400:cb00:2048:1::a29f:f829|:80... connected.
    HTTP request sent, awaiting response...
      HTTP/1.1 404 Not Found
      Date: Mon, 27 Apr 2015 18:20:56 GMT
      Content-Type: text/html; charset=utf-8
      Connection: close
      Set-Cookie: __cfduid=dc29158df8cbc8f6f253f08587fc834f71430158856; expires=Tue, 26-Apr-16 18:20:56 GMT; path=/; domain=.cdnjs.com; HttpOnly
      X-Powered-By: Express
      X-Content-Type-Options: nosniff
      Vary: Accept-Encoding
      Via: 1.1 vegur
      CF-Cache-Status: HIT
      Server: cloudflare-nginx
      CF-RAY: 1ddc8b5764130994-ORD
    2015-04-27 18:20:56 ERROR 404: Not Found.

This interface is [documented to exist and available for consumption](https://github.com/cdnjs/cdnjs/wiki/Extensions%2C-Plugins%2C-Resources)]. It has worked for me before.

Please let me know if there is an alternative/preferable way to download package dependency information or even access committed package.json files through something better than github’s raw interface.

**Comment by PeterDaveHello** [comment]
Sorry about that, I'm going to fix it now.

**Comment by PeterDaveHello** [comment]
I made a mistake here : https://github.com/cdnjs/new-website/commit/adb81437946d66aa7ab348ac46da6c2798a916c9 and fixed it in https://github.com/cdnjs/new-website/commit/13d46b8411d098919b63d7152fdbc6c3f2e6e142, please confirm it had been fixed, thanks.

**Comment by binki** [comment]
That fixes it. Thanks!

**Comment by PeterDaveHello** [comment]
np
