### ISSUE TITLE
The cdnjs git repo is unmanageable

### ISSUE THREAD

**Issue by pieroxy** [cdnjs/cdnjs#4591]
I know it's been raised before, but I need to state it right now: CDNJS is a great idea. It's a very, very (as in VERY) poor and unmaintainable implementation.

The GIT repo is 11GB, it is impossible to clone, rebase, fetch, pull, push or anything else in a comfortable way and as such, it is impossible to work with.

This great idea needed an implementation that scale. Git is not it. Not at all. Not by any stretch of the imagination. And unfortunately, it is just the beginning.

My advice would be to FREEZE the repo until some other way is found, implemented, deployed and proved to work for updating a lib AND to add a new lib.

Until then, you're just going forward at a frightening pace to a place I wouldn't like to be in in any of my worst nightmares.

If you choose to continue down that path, good luck.

**Comment by thomasdavis** [comment]
So we are thinking of moving the files out and maintaining the package.jsons only in this repo. But worried that it will be harder to maintain a true sync between the repo and the cdn. Need a bright idea...

**Comment by PeterDaveHello** [comment]
Duplicated with #3941, let's discuss there.
