### ISSUE TITLE
[Help wanted] Documentation on Wikipedia

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#4594]
We need guys who are familiar with Wikipedia to help us finish and submit the page, thanks!
https://en.wikipedia.org/wiki/Draft:Cdnjs

**Comment by legoktm** [comment]
Please read the [conflict of interest](https://en.wikipedia.org/wiki/Wikipedia:Plain_and_simple_conflict_of_interest_guide) guide before contributing to Wikipedia if you're affiliated with cdnjs.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/intern @cdnjs/team-cdnjs

**Comment by maruilian11** [comment]
i think i can do some chores by your indication.

**Comment by Piicksarn** [comment]
@cdnjs/intern.
