### ISSUE TITLE
[author] pivottable v1.4.0

### ISSUE THREAD

**Issue by nicolaskruchten** [cdnjs/cdnjs#4600]
Hello,

I'm sorry if this is not the appropriate forum for this, but I've recently (yesterday) pushed version 1.4.0 of PivotTable.js (https://github.com/nicolaskruchten/pivottable) which is registered under cdnjs as "pivottable" and I'm not sure what the process is now to get that new version to appear under cdnjs... Do I need to do something to make it automatic, or send a pull request or...?

Any help would be appreciated :)

Thanks,
Nicolas

**Comment by PeterDaveHello** [comment]
Thanks for reporting, cc #4487, transfer to use git auto-update now.

**Comment by nicolaskruchten** [comment]
Thanks very much!

**Comment by PeterDaveHello** [comment]
np
