### ISSUE TITLE
Add jQuery 1.11.3 and 2.1.4 (latest)

### ISSUE THREAD

**Issue by Krinkle** [cdnjs/cdnjs#4601]
http://blog.jquery.com/2015/04/28/jquery-1-11-3-and-2-1-4-released-ios-fail-safe-edition/

https://github.com/jquery/jquery/tree/1.11.3/dist
https://github.com/jquery/jquery/tree/2.1.4/dist

https://www.npmjs.com/package/jquery

**Comment by PeterDaveHello** [comment]
Already added in this commit:
* 25b205f add jquery v1.11.3/2.1.4 Peter Dave Hello 26 minutes ago

**Comment by PeterDaveHello** [comment]
Will need about 15 mins.
