### ISSUE TITLE
Overwriding Google Analytics Code

### ISSUE THREAD

**Issue by andrewspear** [cdnjs/cdnjs#4610]
When I install a script from `cdnjs.cloudflare.com`, three cookies are created among the others which our site creates itself:

![cf](https://cloud.githubusercontent.com/assets/1787336/7460744/fbbc4c44-f26a-11e4-8a9c-b42010626e3e.jpg)

If I host the JS file on my own server these three cookies don't appear.  Note that one is called `_ga` (Google Analytics), this `_ga` ID is causing conflicts with the `_ga` ID from our own universal analytics installed on the site (via Google Tag Manager).  Having two `_ga` IDs for a single user causes a massive number of self-referrals and bounces in Google Analytics which ruins a lot of important reports.

Can I suggest that the `cdnjs.cloudflare.com` system be updated so that including a single JS file does not install this cookie so that conflicts are avoided?

Specifically we were using this script: `https://cdnjs.cloudflare.com/ajax/libs/jquery-tools/1.2.7/jquery.tools.min.js`

**Comment by PeterDaveHello** [comment]
cc @thomasdavis @terinjokes @ryankirkman

**Comment by terinjokes** [comment]
@andrewspear cdnjs.cloudflare.com does not have Google Analytics, nor does the server send any cookies when accessing a file.

Have you been to any other CloudFlare property recently? I have Google Analytics restricted everywhere I know about, but possible I've missed one.

**Comment by andrewspear** [comment]
I don't think the issue is related to my local machine, the issue was actually spotted by a colleague in Bangladesh and we could reproduce it in the USA and New Zealand offices.  Using a link to the `cdnjs.cloudflare.com` version of `jquery.tools.min.js` made the cookies appear, a moment later we link to a locally hosted version of the exact same file and they go away.  There are no other CloudFlare services associated with the site, Akamai is the CDN for our domain.

We have solved this issue by simply not using `cdnjs.cloudflare.com` so this is not an urgent change request, but wanted to let you know what we've spotted and why we've had to stop using the service, in case there's something you can address at your end going forward.

**Comment by drewfreyling** [comment]
@andrewspear There are no cookies in the response if you open an incognito window and navigate to https://cdnjs.cloudflare.com/ajax/libs/jquery-tools/1.2.7/jquery.tools.min.js. I think you have your information wrong here.

**Comment by MattIPv4** [comment]
cdnjs resources do not include cookies in responses, as Drew noted. Closing.
