### ISSUE TITLE
[new] bootstrap-slider

### ISSUE THREAD

**Issue by sriharisahu** [cdnjs/cdnjs#4613]
Hi! I would like to add the bootstrap-slider project from https://github.com/seiyria/bootstrap-slider to the cdnjs repo. Requesting the community to let me know if there are any issues if I add this new library.

**Comment by PeterDaveHello** [comment]
Just submit a pull request and we'll audit it :+1:

**Comment by dbeckwith** [comment]
I've added it in https://github.com/cdnjs/cdnjs/pull/4661
