### ISSUE TITLE
[question] Anyone know how to resolve this git case issue when cloning the repo?

### ISSUE THREAD

**Issue by nouveller** [cdnjs/cdnjs#4622]
I'm trying to squash some commits to submit a PR but when I clone my fork of the repo down one file in particular seems to remain "changed" and those changes don't seem to be able to thrown away.

![screen shot 2015-05-08 at 10 55 06](https://cloud.githubusercontent.com/assets/713128/7534402/2db18b7e-f572-11e4-955f-b8011a38c9be.png)

What is this insanity? I've removed my local copy, cloned down again, same result. Stashing doesn't work either.

Any advice would be great.

:bow:

**Comment by nouveller** [comment]
Deleting the offending file gave me this...

![screen shot 2015-05-08 at 11 26 37](https://cloud.githubusercontent.com/assets/713128/7534744/7ce1ff8c-f575-11e4-9d63-bbc7f862f0ad.png)

**Comment by PeterDaveHello** [comment]
Try sparse checkout - https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

**Comment by PeterDaveHello** [comment]
ref: #3650

**Comment by nouveller** [comment]
@PeterDaveHello Thanks for pointing that out, it may be worth mentioning this method in the `README.md`.

**Comment by PeterDaveHello** [comment]
Yeah, will do it, you can also send a PR to add it, it'll be nice!

**Comment by nouveller** [comment]
Sure thing! I think I've got my library PR #4623 ready to go, so I'll do that after that. :smile:
