### ISSUE TITLE
[author] Question about the procedure for renamed libraries

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [cdnjs/cdnjs#4627]
Hi, we recently renamed [jquery-cookie](https://github.com/carhartl/jquery-cookie) to [js-cookie](https://github.com/js-cookie/js-cookie) to remove jquery dependency. We decided not to physically rename the repository and 2 new versions were added in js-cookie releases as a continuation of jquery-cookie development (1.5.0 and 1.5.1, check [here](https://github.com/js-cookie/js-cookie)). To follow semver spec we did added new features for 1.5.0 but maintained backwards compatibility with 1.4.1 (that compatibility will be removed in [v2.0.0](https://github.com/js-cookie/js-cookie/releases/tag/v2.0.0-beta.1) on js-cookie namespace).

Is there any way to setup an automatic redirect to the js-cookie repository without having to create a new one? What would be the correct procedure here?

Thanks.

**Comment by PeterDaveHello** [comment]
Currently, we don't have the procedure to handle this issue, cc @thomasdavis & @ryankirkman.

**Comment by FagnerMartinsBrack** [comment]
@PeterDaveHello Any news on this one?

I believe it's worth creating a new library and then setting up a message in jquery-cookie page saying "this project was moved to js-cookie" or something like that.

What you guys think?

**Comment by PeterDaveHello** [comment]
hmmmmm ... I have no idea ...

**Comment by FagnerMartinsBrack** [comment]
Ok, but is it viable to implement something that might allow us to provide a message in jquery-cookie CDN page? We will add a new project.

**Comment by ryankirkman** [comment]
We can put a message in the package description so it shows up on the
library page.

**Comment by PeterDaveHello** [comment]
Symbolic link will work https://github.com/cdnjs/cdnjs/issues/5287

**Comment by MattIPv4** [comment]
No further progress, closing.

Going forward, I think we'll achieve this normally by simply adding renamed libraries as if they were a new library.
