### ISSUE TITLE
[Request]angular-foundation

### ISSUE THREAD

**Issue by Norm-** [cdnjs/cdnjs#4629]
I think this one is not included.

http://pineconellc.github.io/angular-foundation/

**Comment by PeterDaveHello** [comment]
You can send a PR to include it.

**Comment by maruilian11** [comment]
**git repo ur:l** https://github.com/pineconellc/angular-foundation
@cdnjs/intern guys i need some advice about which files should be added in this case.
Thank you!

**Comment by Amomo** [comment]
We need to build the whole project to get `mm-foundation-custom-0.6.0.js`.
I think we need to tell the author to put these files on its repo.

**Comment by maruilian11** [comment]
@Amomo i don't really understand what does get `mm-foundation-custom-0.6.0.js` mean.
could u open the issue on their repo? thank you.

**Comment by Amomo** [comment]
@maruilian11 Oh! That is this lib's build file.
I have open an issue for request.
https://github.com/pineconellc/angular-foundation/issues/250
