### ISSUE TITLE
[author] ready.js removed from site

### ISSUE THREAD

**Issue by nouveller** [cdnjs/cdnjs#4632]
I had a PR which was merged a few days ago #4623, the files are still in master (https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ready.js) but no longer appear on the website. https://cdnjs.com/libraries/ready.js.

I wonder what's going on?

**Comment by PeterDaveHello** [comment]
I can see it.

**Comment by nouveller** [comment]
Oh, strange. It's just come back. It definitely disappeared for a few hours as I had something monitoring the page. Weird. I'll keep an eye out.
