### ISSUE TITLE
Uncaught ReferenceError: UserApp is not defined

### ISSUE THREAD

**Issue by Mirodil** [cdnjs/cdnjs#4650]
Search library does not working. here is a error from developer console:

```
Uncaught ReferenceError: UserApp is not defined
```

**Comment by thomasdavis** [comment]
Ops fixing now

**Comment by thomasdavis** [comment]
Fixed in commit -> https://github.com/cdnjs/new-website/commit/a16eebbcb4724657f60410d5c8afee4cb5e37b7a

Waiting for deploy

**Comment by Dervisevic** [comment]
@thomasdavis Do you think this is the reason the search doesn't work? (at least for me)

**Comment by thomasdavis** [comment]
Yep. But sorry just realized deploy didn't work. Deploying manually now...

**Comment by MattIPv4** [comment]
Assuming this was resolved way back when (search happens to be working now). Closing.
