### ISSUE TITLE
https://cdnjs.com/ downish?

### ISSUE THREAD

**Issue by binki** [cdnjs/cdnjs#4651]
https://cdnjs.herokuapp.com/libraries/es6-shim works for me but https://cdnjs.com/libraries/es6-shim doesn’t. ![what I see](http://i.imgur.com/Zp6gZcE.png)

Are heroku and cloudflare fighting each other or something?

**Comment by binki** [comment]
More importantly, https://cdnjs.com/packages.json is working fine for me and multiple VPSes of mine in the US, but it also gets this Application Error for a Canadian in Ontario.

**Comment by PeterDaveHello** [comment]
hmmmmm ... I have no problem at this moment, but @thomasdavis said that heroku is not stable at this moment.

**Comment by binki** [comment]
Hmm, I can’t get the errors to show up anymore. But it seems like https://cdnjs.herokuapp.com/ and https://cdnjs.com/ might be operating off of different databases (at https://cdnjs.com/libraries/es6-shim/ I see version 0.31.2 and at https://cdnjs.herokuapp.com/libraries/es6-shim/ I see 0.27.1). If anyone cares to respond, is cdnjs.com being backed by cdnjs.herokuapp.com or is cloudflare’s upstream somewhere else nowadays?
