### ISSUE TITLE
hiw-api package not updated on cdnjs?

### ISSUE THREAD

**Issue by JoshMcCullough** [cdnjs/cdnjs#4664]
Hi, the package I submitted , `hiw-api`, has [two additional releases on GitHub](https://github.com/HealthIndicators/js-api/releases) which do not appear on cdnjs. Can someone take a look at my [`package.json`](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/hiw-api/package.json) and let me know if something is configured incorrectly? I was under the impression that cdnjs would automatically pull new releases from the repo.

Thanks!

**Comment by PeterDaveHello** [comment]
The files in the file map not appear in your repo in each tags.

**Comment by JoshMcCullough** [comment]
Thanks, will submit a PR soon.
