### ISSUE TITLE
It would be nice to classify all libraries into categoties !!!

### ISSUE THREAD

**Issue by agwaeten** [cdnjs/cdnjs#4667]
It would be nice to classify all libraries in your website into categories so that user can filter items easily such as animation,Forms,audio,video,Images ...etc

**Comment by PeterDaveHello** [comment]
In fact, "tag" may be much more useful in this situation, since a lib may have multiple properties, and as we already have keywords, I wonder if we really need a category feature, what do you think about using keywords to create something like tag cloud? cc @cdnjs/team-cdnjs

**Comment by xtuc** [comment]
we already have keywords. we could use the Aglolia index to provide filters. Closing because it's out of scope for now.
