### ISSUE TITLE
XSS available at cdnjs.com library list

### ISSUE THREAD

**Issue by ghost** [cdnjs/cdnjs#4670]
![2015-05-24 12 40 47](https://cloud.githubusercontent.com/assets/781145/7786710/21fdb490-0212-11e5-8383-f45b66f3a596.png)

**Comment by IonicaBizau** [comment]
Whoups! :bomb: :fire: Thanks for catch!

**Comment by PeterDaveHello** [comment]
cc @thomasdavis @ryankirkman @drewfreyling

**Comment by dylmye** [comment]
High Priority yet it's still there?

**Comment by PeterDaveHello** [comment]
The xss in search was fixed in https://github.com/cdnjs/new-website/commit/8c9076edf508df209123c6b8b428ceb9ad7ac30d, sorry for the late reply.
