### ISSUE TITLE
Question about web hooks publishing

### ISSUE THREAD

**Issue by F2X** [cdnjs/cdnjs#4689]
Hi!
I would like to know if there is any plan to create web hooks to allow real-time publishing on cdn?
In fact I'm trying to do continuous integration with Travis, and publish successfully built lib on both Bower, NPM, GitHub releases and your CDN.
For know it's working on all services, but there is a delay between new GitHub release and its deployment via the autoupdate process.
Thanks

**Comment by PeterDaveHello** [comment]
The problem is not web hooking, is about auditing. See readme for detail, thanks.
