### ISSUE TITLE
ember-data.js.map isn't being updated

### ISSUE THREAD

**Issue by gerry3** [cdnjs/cdnjs#4692]
Looks like `ember-data.js.map` isn't being updated with the other `ember-data.js` files.

<https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/1.0.0-beta.18/ember-data.js.map> is actually for 1.0.0-beta.16.1, not 1.0.0-beta.18. Similarly, 1.0.0-beta.17 is also using the map from 1.0.0-beta.16.1.

@PeterDaveHello

**Comment by PeterDaveHello** [comment]
Not our issue, it's from upstream, you can open issue there.
