### ISSUE TITLE
Update repo url of these libs.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#4695]
Repo url of 346 libs (total: 1224 libs) need to be updated if been moved.
Need to be confirmed.

- [x] 6to5/6to5
- [x] Colourity/Fort.js
- [ ] andyet/ICanHaz.js
- [x] appendto/amplify
- [x] jmdobry/angular-data
- [x] angular-ui/angular-ui
- [x] kentcdodds/apiCheck.js
- [x] mrappleton/backbone-fetch-cache
- [x] addyosmani/backbone.paginator
- [x] jmeas/backbone.radio
- [x] vlamanna/BootstrapFormHelpers
- [ ] projectBS/bsJS
- [x] mauriciosantos/buckets
- [x] rxaviers/cldr
- [x] marijnh/CodeMirror
- [x] jashkenas/coffee-script
- [x] piqnt/cutjs
- [x] johan-gorter/domplotter
- [x] DragonBones/SkeletonAnimationLibraryJS
- [x] elasticsearch/elasticsearch-js
- [x] evancz/Elm
- [x] rpflorence/ember-localstorage-adapter
- [x] hassankhan/emojify.js
- [x] DimitarChristoff/Epitome
- [x] Starcounter-Jack/Fast-JSON-Patch
- [x] twitter/flight
- [x] dilvie/h5Validate
- [x] EightMedia/hammer.js
- [x] jamuhl/i18next
- [x] pivotal/jasmine-ajax
- [x] pivotal/jasmine
- [x] bradvin/FooTable
- [x] warpech/jquery-handsontable
- [x] paulirish/infinite-scroll
- [x] appendto/jquery-mockjax
- [x] brandonaaron/jquery-mousewheel
- [x] allmarkedup/jQuery-URL-Parser
- [ ] neteye/jquery-plugins
- [x] fosco-maestro/jquery-allowed-chars-simple-plugin
- [x] kununu/gray
- [x] GBKS/Wookmark-jQuery
- [ ] wjosdejong/jsoneditoronline
- [ ] tybenz/legojs
- [x] johan-gorter/maquette
- [x] brycedorn/jQuery.minitranslate
- [x] barrel/mixitup
- [x] visionmedia/mocha
- [x] daviferreira/medium-editor
- [x] leetreveil/node-musicmetadata
- [x] darul75/ng-slider
- [ ] j-l-n/noti.js
- [x] ojjs/oj.VimeoVideo
- [x] ojjs/oj.YouTubeVideo
- [x] ojjs/oj.markdown
- [x] ojjs/oj.mustache
- [x] ojjs/oj
- [x] openlayers/ol3
- [x] OnsenUI/OnsenUI
- [x] opal/opal-jquery
- [x] opal/opal
- [x] opal/opal
- [x] openlayers/openlayers
- [x] padolsey/operative
- [x] nnajm/orb
- [x] carlsednaoui/ouibounce
- [x] filamentgroup/Overthrow
- [x] OwlFonk/OwlCarousel
- [x] dexteryy/OzJS
- [x] lmccart/p5.js
- [x] schteppe/p2.js
- [x] dharmafly/pablo
- [x] HubSpot/pace
- [x] metafizzy/packery
- [x] wagerfield/parallax
- [x] paperjs/paper.js
- [x] guillaumepotier/Parsley.js
- [x] mtrpcic/pathjs
- [x] paypal/JavaScriptButtons
- [x] dmajda/pegjs
- [x] peers/peerjs
- [x] usablica/persian.js
- [x] photonstorm/phaser
- [x] amsul/pickadate.js
- [x] lojjic/PIE
- [x] scottjehl/picturefill
- [x] lipka/piecon
- [x] nicolaskruchten/pivottable
- [x] piwik/piwik
- [x] GoodBoyDigital/pixi.js
- [x] zurb/pizza
- [x] walterdavis/placeholder-shiv
- [x] jamesallardice/Placeholders.js
- [x] bestiejs/platform.js
- [x] playlyfe/playlyfe-js-sdk
- [x] playlyfe/odysseus
- [x] Fooidge/PleaseJS
- [x] sciactive/pnotify
- [x] simplegeo/polymaps
- [x] Polymer/polymer
- [x] flowersinthesand/portal
- [x] postaljs/postal.js
- [x] pouchdb/pouchdb
- [x] anshulverma/conditional
- [x] leaverou/prefixfree
- [x] DimitarChristoff/primish
- [x] LeaVerou/prism
- [x] probtn/probtn-web
- [x] processing-js/processing-js
- [x] usablica/progress.js
- [x] proj4js/proj4js
- [x] sstephenson/prototype
- [x] mbostock/protovis
- [x] meltingice/psd.js
- [x] pubnub/pubnub-api
- [x] bestiejs/punycode.js
- [x] yui/pure
- [x] allmarkedup/purl
- [x] pusher/pusher-angular
- [x] pusher/pusher-js
- [x] nprapps/pym.js
- [x] kriskowal/q
- [x] dlueth/qoopido.js
- [x] qooxdoo/qooxdoo
- [x] Craga89/qTip2
- [x] mbostock/queue
- [x] tfriedel6/quicksound.js
- [x] quilljs/quill
- [x] jquery/qunit
- [x] soyjavi/QuoJS
- [x] ded/qwery
- [x] mhemesath/r2d3
- [x] Rich-Harris/Ractive
- [x] ractivejs/ractive
- [x] uxder/Radio
- [x] ccampbell/rainbow
- [x] maroslaw/rainyday.js
- [x] ramda/ramda
- [x] davidmerfield/randomColor
- [x] andreruffert/rangeslider.js
- [x] DmitryBaranovskiy/raphael
- [x] twbs/ratchet
- [x] getsentry/raven-js
- [x] akiran/react-foundation-apps
- [x] akiran/react-slick
- [x] yang/reactive-coffee
- [x] joewalnes/reconnecting-websocket
- [x] remotestorage/remotestorage.js
- [x] darcyclarke/Repo.js
- [x] jrburke/require-cs
- [x] guybedford/require-css
- [x] requirejs/domReady
- [x] requirejs/i18n
- [x] jrburke/require-jquery
- [x] requirejs/text
- [x] jrburke/requirejs
- [x] jfparadis/requirejs-handlebars
- [x] millermedeiros/requirejs-plugins
- [x] jfparadis/requirejs-mustache
- [x] jfparadis/requirejs-tpl
- [x] ded/reqwest
- [x] scottjehl/Respond
- [x] viljamis/responsive-nav.js
- [x] mgonto/restangular
- [x] 23/resumable.js
- [x] imulus/retinajs
- [x] hakimel/reveal.js
- [x] shutterstock/rickshaw
- [x] joeyvandijk/rimg
- [x] mikeric/rivets
- [x] bevacqua/rome
- [x] fredhq/roundabout
- [x] Reactive-Extensions/rxjs-dom
- [x] Reactive-Extensions/rxjs-jquery
- [x] Reactive-Extensions/RxJS
- [x] shaz3e/S3-Colors
- [x] forcedotcom/SalesforceCanvasFrameworkSDK
- [x] medialize/sass.js
- [x] quirkey/sammy
- [x] attila/savvior
- [x] OpenNTF/SocialSDK
- [x] flosse/scaleApp
- [x] jbeard4/SCION
- [x] sindresorhus/screenfull.js
- [x] ded/script.js
- [x] madrobby/scriptaculous
- [x] julianlloyd/scrollReveal.js
- [x] the-diamond-dogs-group-oss/scrollpoints
- [x] seajs/seajs
- [x] davidbau/seedrandom
- [x] t0m/select2-bootstrap-css
- [x] ivaynberg/select2
- [x] keithclark/selectivizr
- [x] brianreavis/selectize.js
- [x] Semantic-Org/Semantic-UI
- [x] FaiblUG/setIframeHeight
- [x] bigspaceship/shine.js
- [x] showdownjs/showdown
- [x] spire-io/shred
- [x] aroc/side-comments
- [x] jacomyal/sigma.js
- [x] szimek/signature_pad
- [x] alvaropinot/simple-text-rotator
- [x] HubSpot/signet
- [x] wojodesign/simplecart-js
- [x] jonathan-fielding/SimpleStateManager
- [x] cjohansen/Sinon.JS
- [x] jquery/sizzle
- [x] bitwiseshiftleft/sjcl
- [ ] n33/skel-layers
- [x] n33/skel
- [x] dhg/Skeleton
- [x] soulwire/sketch.js
- [x] Prinzhorn/skrollr
- [x] darkskyapp/skycons
- [x] freqdec/slabText
- [x] kenwheeler/slick
- [x] adchsm/Slidebars
- [x] nathansearles/Slides
- [x] jakiestfu/Snap.js
- [x] sapegin/social-likes
- [x] dougmartin/Stop-Censorship
- [x] sockjs/sockjs-client
- [x] HubSpot/sortable
- [x] scottschiller/SoundManager2
- [x] nudgepad/space
- [x] bgrins/spectrum
- [x] youtube/spfjs
- [x] fgnass/spin.js
- [x] LearnBoost/Socket.IO
- [x] spine/spine
- [x] dhotson/springy
- [x] alexei/sprintf.js
- [x] nihey/sprites
- [x] eriwen/javascript-stacktrace
- [x] hay/stapes
- [x] mrdoob/stats.js
- [x] markdalgleish/stellar.js
- [x] jmesnil/stomp-websocket
- [x] marcuswestin/store.js
- [x] joshaven/string_score
- [x] jprichardson/string.js
- [x] hakimel/stroll.js
- [x] strophe/strophejs
- [x] joequery/Stupid-Table-Plugin
- [x] learnboost/stylus
- [x] subkit/subkit.js
- [x] andrewplummer/Sugar
- [x] HackerWins/summernote
- [x] visionmedia/superagent
- [x] joeldbirch/superfish
- [x] jillix/svg.connectable.js
- [x] wout/svg.js
- [x] jillix/svg.pan-zoom.js
- [x] wordnik/swagger-ui
- [x] paularmstrong/swig
- [x] bradbirdsall/Swipe
- [x] erming/tabcomplete
- [x] jcoglan/sylvester
- [x] tristen/tablesort
- [x] jsoma/tabletop
- [x] typicaljoe/taffydb
- [x] fraywing/textAngular
- [x] tfrce/widget
- [x] then/request
- [x] walmartlabs/thorax
- [x] mrdoob/three.js
- [x] NUKnightLab/TimelineJS
- [x] bgrins/TinyColor
- [x] tommoor/tinycon
- [x] tinymce/tinymce
- [x] Sjeiti/TinySort
- [x] daneden/Toast
- [x] CodeSeven/toastr
- [x] iamceege/tooltipster
- [x] topcoat/icons
- [x] topcoat/topcoat
- [x] mbostock/topojson
- [x] hapticdata/toxiclibsjs
- [x] Treesaver/treesaver
- [x] qrohlf/trianglify
- [x] rails/turbolinks
- [x] CreateJS/TweenJS
- [x] seaofclouds/tweet
- [x] twitter/twemoji
- [x] justjohn/twig.js
- [x] twbs/bootstrap
- [x] remy/twitterlib
- [x] icambron/twix.js
- [x] jonobr1/two.js
- [x] twitter/typeahead.js
- [x] uikit/uikit
- [x] documentcloud/underscore-contrib
- [x] jashkenas/underscore
- [x] epeli/underscore.string
- [x] nathansmith/unsemantic
- [x] luis-almeida/unveil
- [x] jillix/url.js
- [x] tbranyen/use.js
- [x] vdurmont/userinfo-js
- [x] Imaginea/uvCharts
- [x] ansman/validate.js
- [x] dlid/jquery-valjs
- [x] chriso/validator.js
- [ ] jimmybyrum/vault
- [x] trifacta/vega
- [x] israelidanny/veinjs
- [x] vert-x/vert.x
- [x] julianshapiro/velocity
- [x] videojs/video.js
- [x] box/viewer.js
- [x] almende/vis
- [x] ai/visibilityjs
- [x] yyx990803/vue
- [x] katspaugh/wavesurfer.js
- [x] imakewebthings/jquery-waypoints
- [x] gimite/web-socket-js
- [x] google/web-starter-kit
- [x] Polymer/webcomponentsjs
- [x] typekit/webfontloader
- [x] adamfairhead/webicons
- [x] trevorlinton/webkit.js
- [x] aFarkas/webshim
- [x] feross/webtorrent
- [x] gmuteam/webuploader
- [x] cujojs/when
- [x] WhereYat/whereyat-js
- [x] winjs/winjs
- [x] matthieua/WOW
- [x] xing/wysihtml5
- [x] vitalets/x-editable
- [x] xively/xively-js
- [x] SheetJS/js-xls
- [x] SheetJS/js-xlsx
- [x] slevithan/XRegExp
- [x] xui/xui
- [x] yamlcss/yaml
- [x] YASGUI/YASGUI
- [x] YASGUI/YASQE
- [x] YASGUI/YASR
- [x] SlexAxton/yepnope.js
- [x] yui/yui3
- [x] madrobby/zepto
- [x] zeroclipboard/zeroclipboard
- [x] samcollins/css-social-buttons
- [x] zurb/ink
- [x] lowe/zxcvbn

**Comment by IonicaBizau** [comment]
@PeterDaveHello A script can do that, right?

**Comment by PeterDaveHello** [comment]
Yeah of course I think.

**Comment by PeterDaveHello** [comment]
But should make sure they are in the same situation here.

**Comment by PeterDaveHello** [comment]
```bash
#!/bin/bash
for a in `cat ~/list`
do
    has=`curl -sI https://github.com/$a | grep '^Location' | awk -F'/' '{print  $4"/"$5}' | sed 's/\r//g' | awk -F'/' '{print $1"\\\/"$2}'`
    if [ ! -z "$has" ]; then
        echo "$a $has"
        file=`git grep "$a" -- "*/package.json" | awk -F':' '{print $1}' | uniq`
        if [ ! -z "$file" ]; then
            sed -i "s/$(echo "$a" | awk -F'/' '{print $1"\\\/"$2}')/$has/g" "$file"
        fi
    fi
done
```

**Comment by PeterDaveHello** [comment]
Only 64 libs been fixed, should make sure what are the cases remaining ...

**Comment by PeterDaveHello** [comment]
Updated 64 libs here:
43c20c2389fb50c7b1d2c62788e5c84b8fa6e2e1

**Comment by PeterDaveHello** [comment]
hmmmm ... strange, after the first fixing, only got problem on these libs, maybe there is a problem of my network of first round ...
- [ ] andyet/ICanHaz.js
- [ ] projectBS/bsJS
- [ ] neteye/jquery-plugins
- [ ] wjosdejong/jsoneditoronline
- [ ] tybenz/legojs
- [ ] daviferreira/medium-editor
- [ ] visionmedia/mocha
- [ ] j-l-n/noti.js
- [ ] n33/skel-layers
- [ ] jimmybyrum/vault

**Comment by PeterDaveHello** [comment]
Remaining were dead ...

**Comment by PeterDaveHello** [comment]
hmmmm ... I'm sure some of the results were wrong, should open issue on https://github.com/cdnjs/new-website
