### ISSUE TITLE
Version bump/update not reflected

### ISSUE THREAD

**Issue by WebReflection** [cdnjs/cdnjs#4705]
I'm not sure I've done something wrong but 16 days ago I've PR(ed) [this change](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/document-register-element/package.json) in order to have all .js files from the build folder in.

However, even if the auto-update field is there, the version is stuck at `0.3.0` while the library is at `0.4.1` as noticed by a user.

https://github.com/WebReflection/document-register-element/issues/23

Is there anything I can do to trigger a sync/update?

Thank you

**Comment by PeterDaveHello** [comment]
https://www.npmjs.com/package/document-register-element
> webreflection published a month ago
> 0.3.0 is the latest of 17 releases

**Comment by PeterDaveHello** [comment]
You are using npm auto-update but you didn't update the npm package ...
Maybe you can transfer to use git auto-update so that it won't need to wait for your npm package push.

**Comment by WebReflection** [comment]
http://i.imgur.com/fAANVQ5.gif

thanks
