### ISSUE TITLE
Search for "dimple" returns results for "simple"

### ISSUE THREAD

**Issue by bostonaholic** [cdnjs/cdnjs#4715]
When I enter a search term of `dimple` the results return matches on `simple`.

![screen shot 2015-06-05 at 2 46 17 pm](https://cloud.githubusercontent.com/assets/362146/8014932/f404dfc6-0b91-11e5-9f17-376697945a16.png)

**Comment by PeterDaveHello** [comment]
I think it's fuzzy search feature.

**Comment by LucaRosaldi** [comment]
Yes, it is. If there was a library called 'dimple', it would be the first result. It's not an issue.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by bostonaholic** [comment]
Thanks. This was unexpected behavior but now I see how the fuzzy search is working.
