### ISSUE TITLE
Access-Control-Allow-Origin issue

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#4724]
Seems .map file doesn't have Access-Control-Allow-Origin config in header, maybe we could support it?
cc @thomasdavis @ryankirkman @drewfreyling @terinjokes 

```
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.map
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Tue, 09 Jun 2015 14:25:16 GMT
Content-Type: application/octet-stream
Content-Length: 127576
Connection: keep-alive
Last-Modified: Fri, 01 May 2015 18:30:41 GMT
Expires: Sun, 29 May 2016 14:25:15 GMT
Cache-Control: max-age=30672000
Vary: Accept-Encoding
Accept-Ranges: bytes
CF-RAY: 1f3d8135b3a3038e-HKG
```

```
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Tue, 09 Jun 2015 14:25:23 GMT
Content-Type: application/javascript
Connection: keep-alive
Last-Modified: Fri, 01 May 2015 18:31:14 GMT
Expires: Sun, 29 May 2016 14:25:23 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
CF-RAY: 1f3d816b8a841920-HKG
```

**Comment by PeterDaveHello** [comment]
maybe all the content on cdn can have it?

**Comment by PeterDaveHello** [comment]
ping @terinjokes

**Comment by terinjokes** [comment]
The CORS header can be added to content if a good reason is given, and there are no security issues.

What's the reason to include the CORS header on source maps? This isn't required for browsers to load the source map.

**Comment by PeterDaveHello** [comment]
Oh my fault.

**Comment by jowavp** [comment]
@terinjokes
We are creating a plugin for cdnjs on a web based IDE.
In a project we are able to use the resources on cdnjs, but we should also be able to dowload (copy) the resources in the project and use them from there. 
If we debug the script later, we would be very happy with the .map file. :-)

A work around now is that before we debug the app, we switch to the online resources.

kr,
Joachim

**Comment by MattIPv4** [comment]
Appears to be similar to #7609 (file types missing CORS). I will close this and keep posting updates there, in one place.

**Comment by MattIPv4** [comment]
Cloudflare have deployed a fix and this file extension now comes with a CORS header 🎉
