### ISSUE TITLE
Automatically create the minified version

### ISSUE THREAD

**Issue by IonicaBizau** [cdnjs/cdnjs#4753]
If the minified version doesn't exist, is it possible to generate it?

**Comment by PeterDaveHello** [comment]
Almost impossible, how to determinate need to do it or not? Filename? Not reliable at all, there are too many naming styles.

**Comment by IonicaBizau** [comment]
I see, so the one that adds the library should check/add the minified files, right?

**Comment by PeterDaveHello** [comment]
Yes, we point `filename` to the minified file, and npm test will remind committer to minified if the committer forgot to minfied it.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Ok, thanks! :+1:

**Comment by PeterDaveHello** [comment]
np
