### ISSUE TITLE
MediaElement.js is incomplete

### ISSUE THREAD

**Issue by chris-morgan** [cdnjs/cdnjs#4769]
cdnjs’s copy of MediaElement.js (mediaelement) is lacking bigplay.svg and controls.svg, referred to in the CSS file and used by SVG-capable browsers (most). In consequence all the controls on its players are lacking their graphics. This renders the entire thing comparatively unusable.

[jsdelivr has it complete.](http://www.jsdelivr.com/#!mediaelement)

**Comment by PeterDaveHello** [comment]
Thanks, working on it now.
