### ISSUE TITLE
Ignore empty directory or directory without package.json when testing

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#4774]
So that we can use `.gitkeep` to keep the directory structure only but don't totally drop them while using sparse-checkout.
Currently, use sparse-checkout to checkout `.gitkeep` to keep the structure(directories) will cause test failed.

Maybe just add a parameter for test process.

What do you think @thomasdavis @drewfreyling @ryankirkman @IonicaBizau.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Is issue about the cdnjs repo size? What is the context?

**Comment by PeterDaveHello** [comment]
Not really. But we usually use sparse-checkout on a large repo like cdnjs, I want to keep the directories of the libs without checking out them, so that we can still know what libs we have locally.

**Comment by xtuc** [comment]
Tests will be refactored and this won't be an issue anymore
