### ISSUE TITLE
Directory fonts missing in bootswatch 3.3.5

### ISSUE THREAD

**Issue by yohankoehler** [cdnjs/cdnjs#4787]
Hi,
in bootswatch 3.3.5 glyphicons have been replaced with symlinks to bootstrap, also it seems that the fonts directory in bootswatch 3.3.5 from cdnjs is missing, can you please add it, it is necessary to get glyphicons work.

Thank you.

**Comment by PeterDaveHello** [comment]
Would you like to send a PR to fix it?

**Comment by yohankoehler** [comment]
Ok PR done.

**Comment by edm00se** [comment]
In addition to the gratuitous "me too", here's a link to the corresponding PR:
https://github.com/cdnjs/cdnjs/pull/4788
