### ISSUE TITLE
[new] Inclusion of WebcamJS

### ISSUE THREAD

**Issue by Jeni4** [cdnjs/cdnjs#4795]
Is it possible to include WebcamJS developed by @jhuckaby into the main cdnjs repo from my branch at https://github.com/Jeni4/webcamjs/tree/cdnjs-working-copy ?

* I am looking for errors I may have committed when creating the package.json file (https://github.com/Jeni4/webcamjs/blob/cdnjs-working-copy/package.json) and

**Comment by PeterDaveHello** [comment]
What's the reason why to copy from your branch? Or we just copy from origin repo?
`npm test` will tell you what's the error?

**Comment by Jeni4** [comment]
Changed it after reading your comment and created a pull request instead with the library merged into the library by the cdnjs-importer npm based script. #4797
