### ISSUE TITLE
Update SSL-certificate with SHA-2

### ISSUE THREAD

**Issue by back-2-95** [cdnjs/cdnjs#4807]
"With the announcement by Google, Microsoft’s announcement, and the ongoing security concerns about SHA-1, it's strongly recommended that you migrate to SHA-2 where possible and prepare to migrate all systems to SHA-2 in order to for your users to see your sites and services as trusted."

At least on Firefox console shows warnings with cdnjs resources.

**Comment by PeterDaveHello** [comment]
cc @terinjokes @thomasdavis @ryankirkman

**Comment by terinjokes** [comment]
This will happen.

**Comment by szepeviktor** [comment]
@prdonahue promised on 29th Sep.

> We expect this to happen within the next few days.

**Comment by PeterDaveHello** [comment]
@back-2-95 I think we are using ECC-256 now, do you still have this problem? Thanks.

**Comment by back-2-95** [comment]
@PeterDaveHello Hi, I'm moved to new things so this is no longer relevant to me.

Feel free to close this issue if you have moved to new & shiny stuff ;)

**Comment by PeterDaveHello** [comment]
@terinjokes would you please give us your comment? Thanks.

**Comment by terinjokes** [comment]
We've long switched to SHA2 certificates.
