### ISSUE TITLE
Request to add perfBar

### ISSUE THREAD

**Issue by darkpixel** [cdnjs/cdnjs#4814]
http://lafikl.github.io/perfBar/

**Comment by darkpixel** [comment]
Sorry--just saw the 'no more manual requests'.  :)

**Comment by darkpixel** [comment]
I can't use the cdnjs-importer to request perfBar before the sun goes nova:

15:46:16 [aaron@praxis:~/code] $ cdnjs-importer /home/aaron/code/perfBar/ -c cdnjs
info  [15:46.31 - 01.07.2015] Cloning /home/aaron/code/perfBar/ into /tmp/tmp-5092PKceLNDVDkr9
info  [15:46.32 - 01.07.2015] Set the source path: /build
info  [15:46.32 - 01.07.2015] Creating the version directory: cdnjs/ajax/libs/perfbar/0.2.1
info  [15:46.32 - 01.07.2015] Getting the library files.
info  [15:46.32 - 01.07.2015] Writing the package.json file in cdnjs/ajax/libs/perfbar
info  [15:46.32 - 01.07.2015] Copying the library files
info  [15:46.32 - 01.07.2015] Adding the new library files in the git repository.
info  [16:06.31 - 01.07.2015] Committing the changes
info  [16:21.39 - 01.07.2015] Added perfbar@0.2.1
info  [16:21.39 - 01.07.2015] Done.
16:21:39 [aaron@praxis:~/code] 

Notice the timestamps.  The repository is huge.

**Comment by PeterDaveHello** [comment]
Did you try sparse-checkout with shallow clone/pull?
