### ISSUE TITLE
No GZip Compression over HTTP

### ISSUE THREAD

**Issue by logiclabs** [cdnjs/cdnjs#4815]
When retrieving files over HTTP with "Accept-Encoding: gzip", cdnjs does not return a compressed version of the file.  This issue appears to be the same for all HTTP requests with CloudFlare.  Over HTTPS, the compressed version is correctly returned.  

Example, using JQuery:

![image](https://cloud.githubusercontent.com/assets/1760571/8476945/12f0f424-20be-11e5-94fc-3c8c26faa48c.png)

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by PeterDaveHello** [comment]
I don't see problem here.
![Imgur](http://i.imgur.com/3fNADPM.png)

**Comment by logiclabs** [comment]
Apologies.  On further inspection and testing on another computer, it appears to be something running locally that is altering the content. A little worrying.

**Comment by logiclabs** [comment]
Just to follow up, as I expect his may be useful to other developers: This issue was caused by anti-virus software running locally. It appears it was intercepting the compressed content and returning the uncompressed file, and correctly altering the HTTP headers.  Despite me disabling the AV protection while testing the issue, it was still monitoring and modifying the HTTP traffic.  The anti-virus software is ESET NOD32 Antivirus 8.

To ensure you see the unmodified (gzipped) HTTP traffic in the browser, you need to disable HTTP checking (see here):

![image](https://cloud.githubusercontent.com/assets/1760571/8477819/09dd6abe-20c5-11e5-9ae5-949d4f947202.png)

**Comment by PeterDaveHello** [comment]
:+1:
