### ISSUE TITLE
Wrong version Flexslider 2.1

### ISSUE THREAD

**Issue by Vanhoutte** [cdnjs/cdnjs#4823]
Libary: https://cdnjs.com/libraries/flexslider/2.1

Shows version 2.1, however, the file itself indicates it is version 2.0 ("jQuery FlexSlider v2.0")

**Comment by PeterDaveHello** [comment]
https://cdnjs.cloudflare.com/ajax/libs/flexslider/2.1/jquery.flexslider.js shows 2.1
If you meant css file, this is not our problem.
See https://github.com/woothemes/FlexSlider/blob/version/2.1/flexslider.css
