### ISSUE TITLE
Update Sinon.JS from 2013 to 2015 

### ISSUE THREAD

**Issue by Krinkle** [cdnjs/cdnjs#4841]
http://sinonjs.org/Changelog.txt
> 1.7.3 / 2013-06-20
> [..]
> 1.8.0 / 2014-02-02
> [..]
> 1.15.0 / 2015-05-30

Looks like cdnjs is still on 1.7.3 from 2013. Having a more modern version would be useful.

**Comment by fredericksilva** [comment]
:facepunch:
