### ISSUE TITLE
[New] Add DHTML Gannt

### ISSUE THREAD

**Issue by martincarlin87** [cdnjs/cdnjs#4900]
http://docs.dhtmlx.com/gantt/codebase/dhtmlxgantt.js

http://docs.dhtmlx.com/gantt/codebase/dhtmlxgantt.css

**Comment by PeterDaveHello** [comment]
Any info in detail?

**Comment by Piicksarn** [comment]
@martincarlin87, please provide **git repository url** or **npm package url** !
And the issue will be closed after 7 days for no response.

Thank you
Piicksarn

**Comment by Amomo** [comment]
Close due to no response.
