### ISSUE TITLE
[Request] Add Phaser Kinetic Scrolling Plugin

### ISSUE THREAD

**Issue by jdnichollsc** [cdnjs/cdnjs#4938]
This is a plugin for vertical and horizontal scrolling in Phaser Framework

**Comment by Piicksarn** [comment]
@jdnichollsc would you please provide the **`git repository url`** or **`npm package url`**, so that we could add library efficiently.

Thank you!

**Comment by jdnichollsc** [comment]
Yes, see please:
- https://www.npmjs.com/package/phaser-kinetic-scrolling-plugin
- https://github.com/jdnichollsc/Phaser-Kinetic-Scrolling-Plugin

Thanks!

**Comment by maruilian11** [comment]
sorry this lib doesn't have enough popularity(at least 100 watch or star)
please see our document README.md
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
you can oen the issue again when it get enough popularity, thank you!
