### ISSUE TITLE
[Request] Add http://tzdata-javascript.org/tzdata-javascript.js

### ISSUE THREAD

**Issue by yehezkielbs** [cdnjs/cdnjs#4942]

**Comment by Piicksarn** [comment]
@yehezkielbs would you please provide library name with the **`git repository url`** or **`npm package url`**?
So that we could add library efficiently.

Thank you!

**Comment by maruilian11** [comment]
@yehezkielbs could u provide us one url to help us add the lib, the issue will be closed in 10 days due to no responding.
