### ISSUE TITLE
What about auto-update interval? How frequently?

### ISSUE THREAD

**Issue by KhodeN** [cdnjs/cdnjs#4944]
subj.
I'm waiting for requirejs 2.1.19((

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update
> cdnjs automatically updates libraries that are known to be hosted on npm or git repo, e.g., Lodash. npm auto-update relys on each release and git auto-update relys on the tags in git repo. This auto-update script runs every hour, but the update result won't be committed until one of our maintainers audit the updates, because many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so it'll be reasonable to delay for at most 30 hours, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it.

**Comment by KhodeN** [comment]
thx

**Comment by PeterDaveHello** [comment]
np, will add in 30 mins, under auditing right now

**Comment by PeterDaveHello** [comment]
* 7b6b3c7 add require.js v2.1.19 Peter Dave Hello 24 minutes ago
