### ISSUE TITLE
[Request] vminpoly

### ISSUE THREAD

**Issue by s90198123** [cdnjs/cdnjs#4946]
https://github.com/saabi/vminpoly

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #30 ](https://github.com/saabi/vminpoly/issues/30)

**Comment by Piicksarn** [comment]
@s90198123, thanks for your suggestion!
However, we could not get versions number up to now.
would you please open an issue again when the repo including tags for versions?:smiley:
**And this issue will be closed after 7 days for no response.**

Piicksarn

**Comment by Amomo** [comment]
Close due to no response.
