### ISSUE TITLE
[Request] [author] Add SpotJS library

### ISSUE THREAD

**Issue by AndrewShapel** [cdnjs/cdnjs#4951]
SpotJS used for asynchronous load CSS files and cache it in localStorage. This script does not have any dependencies on a libraries. The standard SpotJS file is around 3KB when minified via UglifyJS

SpotJS works in all major browsers which supports localStorage

More info - https://github.com/AndrewShapel/spotjs

**Comment by Piicksarn** [comment]
@AndrewShapel, the library need to have notable popularity.
You could see [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for the detail.
Would you please make a request again when the library is notable popularity? 

Thank you! :)

**Comment by maruilian11** [comment]
@AndrewShapel sorry for closing the issue suddenly, the issue will be closed **in 10 days** due to no response. thank you for your contribution.

**Comment by AndrewShapel** [comment]
@maruilian11 
Hi, no problem. Yes, my library is not very popular and i will make a request again when the library has notable popularity

**Comment by PeterDaveHello** [comment]
Thank you @AndrewShapel
