### ISSUE TITLE
[Request]Pixeden Icon Pack

### ISSUE THREAD

**Issue by drdexter1989** [cdnjs/cdnjs#4971]
I would appreciate if you can upload these libraries

http://www.pixeden.com/icon-fonts/stroke-7-icon-font-set

**Comment by Piicksarn** [comment]
@PeterDaveHello, would you please take a look on this issue?

**Comment by maruilian11** [comment]
@drdexter1989 could u provide us `git repo url` or `npm url` to help us add the lib, the issue will be closed in 10 days due to no responding.
