### ISSUE TITLE
[Request] Polymer 1.0

### ISSUE THREAD

**Issue by M-Porter** [cdnjs/cdnjs#4973]
Polymer 1.0! :kissing_heart: 

https://www.polymer-project.org/

**Comment by Piicksarn** [comment]
@M-Porter would you please provide the `git repository url` or `npm package url`, so that we could add library efficiently. 

Thank you! :)

**Comment by Piicksarn** [comment]
I found it!
https://github.com/Polymer/polymer

**Comment by maruilian11** [comment]
@cdnjs/intern which files should be added? i need your advice.

**Comment by M-Porter** [comment]
Yeah that's a hard one to decide because it actually consists of hundreds of files (if you include all the elements in the catalog they offer). But that's not part of the "core" polymer project.

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by Amomo** [comment]
Oh! I found that they release their library as `html` files.
And, they have explained why they use html file in their CHANGELOG.md.
- Why is there no javascript file? [\#1707](https://github.com/Polymer/polymer/issues/1707)

Do we host these html files? @PeterDaveHello @cdnjs/intern

**Comment by PeterDaveHello** [comment]
we don't serve html files

**Comment by deathmood** [comment]
why not? these *.html files are not entirely like regular html - they more like library - they can't be rendered by it's own. What is the difference between hosting *.html or *.css or *.js? In extension?

**Comment by PeterDaveHello** [comment]
@deathmood sorry, I think the reason may be complex, cc @ryankirkman, @terinjokes

**Comment by PeterDaveHello** [comment]
@deathmood Currently cloudflare who is the only cdn sponsor of cdnjs owns the server, and we don't have the control access, so we need to discuss with cloudflare, so I mention other maintainers to anwser you.

**Comment by ubragg** [comment]
FYI - you might investigate https://github.com/Download/polymer-cdn which does host all the Polymer components on a CDN.
