### ISSUE TITLE
[Request] Add colorbox.css

### ISSUE THREAD

**Issue by cpieroni** [cdnjs/cdnjs#4976]
There is the javascript library but not its CSS.
There are many examples we could add all.
(https://github.com/jackmoore/colorbox)

**Comment by PeterDaveHello** [comment]
You meant the example folders? That make no sense to add example, if users of this like really like to use its example, I think we could open an issue to ask if the author like to make it like its dist files, what do you think?

**Comment by cpieroni** [comment]
I think having only the javascript library of Cndjs is not enough because to
use Colorbox must also have the css library.

Colorbox examples are starting css then you go to rewrite with your css.

I think to put css (at least the examples) on Cndjs is essential, which
 file put is your choice. XD


2015-07-15 14:12 GMT+02:00 Peter Dave Hello <notifications@github.com>:

> You meant the example folders? That make no sense to add example, if users
> of this like really like to use its example, I think we could open an issue
> to ask if the author like to make it like its dist files, what do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/cdnjs/issues/4976#issuecomment-121597780>.
>



-- 

Cristiano Pieroni
*Web front-end developer and Programmer*

Latest from Drop:

*Drop: crescita a doubledigit per le vendite da mobile*
Aumentano di circa il doppio rispetto allo scorso anno, con un incremento
dell'87% rispetto al 2013, il fatturato ed il numero di vendite online
tramite mobile registrati presso gli e-commerce gestiti da Drop, tra cui
Harmont & Blaine, Cesare Paciotti, A.G. Spalding & Bros. e Merrell (*f**onte:
Pambianconews)*

Our website <http://www.drop.it/>



Drop Srl
e-business&love!

C.so Umberto I, 171
62012 Civitanova Marche (MC)
Italy
Tel.+39 0733 77 95 39
<https://mail.google.com/mail/u/0/?ui=2&view=js&name=main,tlist,ptlist&ver=G1qziDYBtIs.it.&am=%21eUOAJ5benWb7RX3bwLoMQJt6h1WPSqu8VyrCGIY2QKZHowL2QSAHW46EHW40ZdUiQQ>
Fax +39 0733 77 45 04
<https://mail.google.com/mail/u/0/?ui=2&view=js&name=main,tlist,ptlist&ver=G1qziDYBtIs.it.&am=%21eUOAJ5benWb7RX3bwLoMQJt6h1WPSqu8VyrCGIY2QKZHowL2QSAHW46EHW40ZdUiQQ>
www.drop.it
info@drop.it

P.IVA: 01383870431
N. REA Macerata: 148143
N. iscrizione registro delle imprese di Macerata: 01383870431

*Stampami solo se necessario!*
INFORMAZIONI STRETTAMENTE CONFIDENZIALI: questa e-mail (e ogni allegato) è
destinata solo ad uso personale e contiene informazioni riservate, coperte
da segreto professionale e non soggette a divulgazione. Se non ne siete i
corretti destinatari, Vi informiamo che non è assolutamente permessa alcuna
divulgazione, copia, distribuzione. Se per errore avete ricevuto questo
messaggio, Vi chiediamo cortesemente di informarci immediatamente e di
eliminare il messaggio. Grazie.

TUTELA DEI DATI PERSONALI: ai sensi dell'art. 13 del D. Lgs. 196/2003, Si
informa che i dati personali, trattati presso la Ns società, sono gestiti
in conformità al D. Lgs. n. 196 del 30 giugno 2003. L'interessato dei dati
personali potrà esercitare tutti i diritti di cui all'art. 7 del
sopraccitato decreto, tra cui i diritti di accesso, rettifica,
aggiornamento, di opposizione al trattamento e di cancellazione inviando un
messaggio e-mail all'indirizzo info@drop.it.

**Comment by PeterDaveHello** [comment]
@cpieroni Would you mind to open an issue in its repo so that we can discuss with its author?

**Comment by maruilian11** [comment]
@cdnjs/intern do you think we should open an issue on this lib repo?
or just close the issue due to no response?

**Comment by Amomo** [comment]
I think we don't need to host an css example on cdnjs.
We could close it due to no response.

**Comment by maruilian11** [comment]
@cpieroni the issue would be closed **in 7 days** due to no response.
