### ISSUE TITLE
[Request] Add JS-EasyCache

### ISSUE THREAD

**Issue by iprodev** [cdnjs/cdnjs#4977]
Please add JS-EasyCache library to your cdn. https://github.com/iprodev/JS-EasyCache

**Comment by Piicksarn** [comment]
@iangilman , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by iangilman** [comment]
@Piicksarn Looks like you meant to tag @iprodev rather than me...

**Comment by Piicksarn** [comment]
@iangilman, I'm sorry about that!!!! :^(
I will be careful next time...!

**Comment by maruilian11** [comment]
@iprodev sorry for closing the issue suddenly, the issue will be closed **in 10 days** due to no response. thank you for your contribution.
