### ISSUE TITLE
[Request] Add country-region-selector

### ISSUE THREAD

**Issue by kodeine** [cdnjs/cdnjs#4984]
Please add the following.

https://github.com/benkeen/country-region-selector

http://benkeen.github.io/country-region-selector/crs.min.js

**Comment by Piicksarn** [comment]
@kodeine, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library is notable popularity? :smiley:

**Comment by maruilian11** [comment]
@kodeine sorry for closing the issue suddenly, the issue will be closed **in 10 days** due to no response. thank you for your contribution.

**Comment by CoreyWycliffe** [comment]
This has more than 100 stars now.
