### ISSUE TITLE
[Request] nouislider v8.0.2

### ISSUE THREAD

**Issue by ugate** [cdnjs/cdnjs#4992]
http://refreshless.com/nouislider
https://github.com/leongersen/noUiSlider/

**Comment by ugate** [comment]
http://refreshless.com/nouislider
https://github.com/leongersen/noUiSlider/

**Comment by Piicksarn** [comment]
@ugate, Thank you!
noUiSlider v8.0.2 had already included in cdnjs:smiley:
https://cdnjs.com/libraries/noUiSlider

**Comment by ugate** [comment]
@Piicksarn It wasn't showing up in the search when I opened the issue. Thank you for adding it!
