### ISSUE TITLE
[Request] materialdesignicons

### ISSUE THREAD

**Issue by ugate** [cdnjs/cdnjs#4993]
https://materialdesignicons.com/
https://github.com/templarian/MaterialDesign/

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #588](https://github.com/Templarian/MaterialDesign/issues/588)

**Comment by ugate** [comment]
@Templarian Is something you can do so we can get releases onto cdnjs?

**Comment by Templarian** [comment]
Yea, just need to know what is required from me? If it just pulls from the Repo by tags you can use the github repo I maintain for the webfont.

https://github.com/Templarian/materialdesign-webfont

Feel free to add it to CDNjs. I also have sponsored CDN from MaxCDN. As long as you can keep it updated I don't mind which CDNs host the webfont.

**Comment by Templarian** [comment]
Make sure you use the repo I linked above. The repo linked in the first is only for collaborators and is where we maintain the source files, not the production ready library.

**Comment by ugate** [comment]
@Piicksarn Do you have everything you need now?

**Comment by maruilian11** [comment]
@cdnjs/intern though the webfont repo doesn't fit our request popularity, i think we can add it.
if you agree, we can tell PeterDaveHello, then add it. what do you think?

**Comment by Amomo** [comment]
@Piicksarn could you keep finish this PR? #5479
