### ISSUE TITLE
[Request] Add howcomplete.js

### ISSUE THREAD

**Issue by hiteshsharma** [cdnjs/cdnjs#5003]
https://github.com/hiteshsharma/howcomplete.js

**Comment by Piicksarn** [comment]
@hiteshsharma, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library is notable popularity? :smiley:

**Comment by maruilian11** [comment]
@hamchapman the issue will be closed in 10 days due to no response. thank you for your contribution.

**Comment by hamchapman** [comment]
I think you meant to mention @hiteshsharma instead of me :D

**Comment by maruilian11** [comment]
@hamchapman I'm sorry...
