### ISSUE TITLE
[Request] Add flexText 

### ISSUE THREAD

**Issue by tatygrassini** [cdnjs/cdnjs#5009]
https://github.com/alexdunphy/flexText

**Comment by Piicksarn** [comment]
@tatygrassini , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library is notable popularity? :smiley:

**Comment by tatygrassini** [comment]
Absolutely, thanks!
