### ISSUE TITLE
[Request] typeplate

### ISSUE THREAD

**Issue by dccfoux** [cdnjs/cdnjs#5010]
Started to use this for my newer projects but can't find a good CDN upload of it anywhere!

**Comment by dccfoux** [comment]
https://github.com/typeplate/starter-kit

**Comment by maruilian11** [comment]
@dccfoux the author said he'll consider adding package.json for each tag in the coming days, so could you please open the issue again when the package.json is added? thank you for your contribution!

**Comment by maruilian11** [comment]
@dccfoux this issue will be closed **in 7 days** due to no response. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Why not wait for the tags? Though I can see it now.

**Comment by grayghostvisuals** [comment]
@PeterDaveHello Thanks for the add. The package has been updated recently–specifically the CSS port –to match the current [package.json](https://github.com/typeplate/starter-kit/blob/master/package.json) although only 3.0.0 displays on CDNJS when it should be 3.0.1 now. Any advice on how to ensure packages for CDNJS update in accordance with the repo?

**Comment by maruilian11** [comment]
@grayghostvisuals v3.0.1 has been added. just wait for few hour after new tag being added :smiley: 
https://cdnjs.com/libraries/typeplate-starter-kit

**Comment by grayghostvisuals** [comment]
Thanks!
