### ISSUE TITLE
[Request] ExtJS 6.0.0 GPL version

### ISSUE THREAD

**Issue by tananaev** [cdnjs/cdnjs#5019]

**Comment by PeterDaveHello** [comment]
is this okay for you @tananaev -> 1663121 ?
I'm not sure.

**Comment by tananaev** [comment]
It works. Thanks.

Sencha maintains their own CDN service, but starting from version 6.0.0 they don't allow to use it in projects. So, the last GPL version they have there is 5.x.x.

I guess we can close this request now.

**Comment by PeterDaveHello** [comment]
nice
