### ISSUE TITLE
[Request] ng-pdfviewer & pdf.js

### ISSUE THREAD

**Issue by wrufeger** [cdnjs/cdnjs#5020]
To display pdf inline using angular the following libraries are required:

https://github.com/akrennmair/ng-pdfviewer
https://mozilla.github.io/pdf.js/

Would be great to include these, cause there´s no CDN available yet (just bower)

Thanks

**Comment by Amomo** [comment]
Mozilla's PDF.js has a distribution library. https://github.com/mozilla/pdfjs-dist

**Comment by PeterDaveHello** [comment]
ping @Amomo
