### ISSUE TITLE
[Request] type.js

### ISSUE THREAD

**Issue by n370** [cdnjs/cdnjs#5035]
https://github.com/nathanford/type.js

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #25 ](https://github.com/nathanford/type.js)

**Comment by PeterDaveHello** [comment]
https://twitter.com/PeterDaveHello/status/714079752923971584

**Comment by sashberd** [comment]
@PeterDaveHello Too much time since the issue was opened and request to add git tag was sent to authors. Suggest to close due to the impossibility of adding for technical reasons

**Comment by n370** [comment]
@sashberd I don't understand the technical reasons. Would you mind detailing here for the record? In my view it would be much more an issue with the community being able to successfully contact @nathanford than something else.

**Comment by sashberd** [comment]
@n370 The issue was opened before more then 2 years and library is not maintained by the author for 3 years. I do not think someone will add git tag or hot on NPM or will answer you here. Thus, a rolling stone gathers no moss, still suggest to close

**Comment by n370** [comment]
Such a pity but totally agreed! Thanks anyways for shaking off the dust.
