### ISSUE TITLE
[Request] Add persianDatepicker 

### ISSUE THREAD

**Issue by behzadi** [cdnjs/cdnjs#5047]
https://github.com/behzadi/persianDatepicker

**Comment by Piicksarn** [comment]
@behzadi, thanks for your suggestion!

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@behzadi this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
