### ISSUE TITLE
cdnjs badge?

### ISSUE THREAD

**Issue by ogewan** [cdnjs/cdnjs#5060]
Is there one? If not could someone make one? Possibly showing the most updated version on the cdn?
I would do it if I knew how and or had the time atm.

**Comment by ogewan** [comment]
for jQuery 3.0.0-alpha1: ![](https://img.shields.io/badge/cdnjs-3.0.0--alpha1-orange.svg)

**Comment by PeterDaveHello** [comment]
Maybe we could discuss with https://github.com/badges/shields/ if they want to host this badge? If so, I can write it.

**Comment by FredyC** [comment]
Hmm, so after year and nothing happened here? Either way it would be nice to have a badge that can point to latest version automatically to avoid hassle when releasing.

@ogewan How you made that badge, please?

**Comment by PeterDaveHello** [comment]
I just update the API to support send the version only, to minimize the output, and send a PR to [badges/shields](http://shields.io) project to integrate CDNJS badge there, see badges/shields#805.

It'll looks like this:
![cdnjs-jquer-version-badge-example](https://cloud.githubusercontent.com/assets/3691490/19231693/fc93b0f8-8f0d-11e6-9954-78bddf2b7a77.png)

![cdnjs-twitter-bootstrap-version-badge-example](https://cloud.githubusercontent.com/assets/3691490/19231730/30c577c6-8f0e-11e6-826b-2ee2b9c5b879.png)

cc @cdnjs/owners @cdnjs/intern @cdnjs/intern2

**Comment by PeterDaveHello** [comment]
badges/shields#805 merged.

See:
[![CDNJS](https://img.shields.io/cdnjs/v/jquery.svg)](https://cdnjs.com/libraries/jquery)

**Comment by FredyC** [comment]
Thanks. Already using it :) https://github.com/stampit-org/stampit#install
