### ISSUE TITLE
[Request] lit _image_upload_ 

### ISSUE THREAD

**Issue by mbiswajit13** [cdnjs/cdnjs#5072]
I want image upload plugin

**Comment by Piicksarn** [comment]
@mbiswajit13, would you please show some detail?

 - **Library name**
 - **Git repository url**
 - **npm package url(optional)**
 - **Official homepage**

**Comment by maruilian11** [comment]
@mbiswajit13 this issue will be closed due to no response **in 10 days**, thank you for your contribution.
