### ISSUE TITLE
[Request] Krona-2.0.js

### ISSUE THREAD

**Issue by deepthoughts** [cdnjs/cdnjs#5074]
Krona.js is currently hosted on sourceforge.net which is down so it would be nice to have Krona-2.0.js library on CDN. 

Here is the link to the source files which contains krona-2.0.js in src directory. 
http://sourceforge.net/projects/krona/

Thank you

**Comment by Piicksarn** [comment]
@PeterDaveHello would you please take a look in this issue?

**Comment by maruilian11** [comment]
**git repo url:** https://github.com/marbl/Krona/tree/v2.6/KronaTools
@deepthoughts sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

**Comment by deepthoughts** [comment]
It is fine since the new version does not require any hosted JS. Thanks for considering the request.
