### ISSUE TITLE
[Request] update 1.5.6 cdnjs version of slick

### ISSUE THREAD

**Issue by david-06studio** [cdnjs/cdnjs#5078]
please update your version 1.5.6 of slick caroussel... he made a hotfix.
https://github.com/kenwheeler/slick/tree/master/slick

**Comment by PeterDaveHello** [comment]
I don't know what's the reason why you open this issue, we have it for almost 2 weeks.
https://cdnjs.com/libraries/slick-carousel/1.5.6
* 110175a add slick-carousel v1.5.6 Peter Dave Hello 12 days ago
