### ISSUE TITLE
jalali-date-picker.js

### ISSUE THREAD

**Issue by imanfakhar** [cdnjs/cdnjs#5085]
$(".jalali-date-picker").find(".jalali-date-year").focusin(function(){var a=$(this).parent("td");$(this).parents(".jalali-date-picker").addClass("focus-date-picker").find(".popover").removeClass().addClass("popover fade in bottom show-years").show().appendTo(a)}),$(".jalali-date-picker").find(".jalali-date-month").focusin(function(){var a=$(this).parent("td");$(this).parents(".jalali-date-picker").addClass("focus-date-picker").find(".popover").removeClass().addClass("popover fade in bottom show-months").show().appendTo(a)}),$(".jalali-date-picker").find(".jalali-date-day").focusin(function(){var a=$(this).parent("td"),b=$(this).parents(".jalali-date-picker").find(".jalali-date-month").val(),d=($(this).parents(".jalali-date-picker").find(".jalali-date-year").val(),$(this).parents(".jalali-date-picker").find(".years").find("li.active"));if(12!=b||d.hasClass("cab"))if(b>6)var e="popover fade in bottom show-days show-30";else var e="popover fade in bottom show-days";else var e="popover fade in bottom show-days show-29";$(this).parents(".jalali-date-picker").addClass("focus-date-picker").find(".popover").removeClass().addClass(e).show().appendTo(a)}),$(".jalali-date-picker ul li").click(function(){{var a=$(this).data("value"),b=$(this).parent("ul").data("for");$(this).attr("id")}$(this).hasClass("divider")?$(this).hasClass("to-next")?$(this).parent("ul").slideUp().next("ul").slideDown():$(this).hasClass("to-prev")&&$(this).parent("ul").slideUp().prev("ul").slideDown():($(this).parents(".picker").find("li").removeClass("active"),$(this).addClass("active").parents(".popover").removeClass().hide().addClass("popover").parents(".jalali-date-picker").find(b).val(a))}),$(".jalali-date-picker input").keyup(function(){{var a=$(this).val(),b=a.length;$(this).attr("maxlength")}if($(this).hasClass("jalali-date-day")&&a>3&&1==b)a="0"+a,$(this).val(a).parent().next().next().find("input").focus(),$(this).parents(".jalali-date-picker").find(".days").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active"):$(this).removeClass("active")});else if($(this).hasClass("jalali-date-day")&&2==b){if(a>31)var a=31;$(this).val(a).parent().next().next().find("input").focus(),$(this).parents(".jalali-date-picker").find(".days").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active").parents(".jalali-date-picker").removeClass("focus-date-picker"):$(this).removeClass("active")})}else if($(this).hasClass("jalali-date-month")&&a>1&&1==b)a="0"+a,$(this).val(a).parent().next().next().find("input").focus(),$(this).parents(".jalali-date-picker").find(".months").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active"):$(this).removeClass("active")});else if($(this).hasClass("jalali-date-month")&&2==b){if(a>12)var a=12;$(this).val(a).parent().next().next().find("input").focus(),$(this).parents(".jalali-date-picker").find(".months").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active").parents(".jalali-date-picker").removeClass("focus-date-picker"):$(this).removeClass("active")})}else $(this).hasClass("jalali-date-year")&&4==b&&($(this).parent().find(".popover").hide(),$(this).parents(".jalali-date-picker").find(".picker.years").find("ul").hide(),$(this).parents(".jalali-date-picker").find(".picker.years").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active").parent("ul").show().parents(".jalali-date-picker").removeClass("focus-date-picker"):$(this).removeClass("active")}))}),$(".jalali-date-picker input.jalali-date-year").focusout(function(){var a=$(this).val(),b=a.length;if(2==b){var a="13"+a;$(this).val(a).parents(".jalali-date-picker").find(".popover").hide(),$(this).parents(".jalali-date-picker").find(".picker.years").find("ul").hide(),$(this).parents(".jalali-date-picker").find(".picker.years").find("li").each(function(){var b=$(this).data("value");b==a?$(this).addClass("active").parent("ul").show().parents(".jalali-date-picker").removeClass("focus-date-picker"):$(this).removeClass("active")})}}),$(".jalali-date-picker").find("input").blur(function(){var a=$(this).parents(".jalali-date-picker"),b=a.find("input");$(this).parents(".jalali-date-picker").removeClass("focus-date-picker"),setTimeout(function(){a.is(":hover")||b.is(":focus")||a.find(".popover").hide()},100)}),$(".jalali-date-picker input").on("keypress",function(a){return $.isNumeric(String.fromCharCode(a.which))?void 0:!1});

**Comment by PeterDaveHello** [comment]
If you wanna add a new lib, please provide us more info, thanks.
