### ISSUE TITLE
API should sort results by popularity

### ISSUE THREAD

**Issue by nt1m** [cdnjs/cdnjs#5107]
When I search for Jquery, jquery appears as one of the last results. The results aren't relevant if you only show the 10 first results. 
If you can't do that, please at least add a popularity field (represented by the number of requests perhaps).

**Comment by nt1m** [comment]
Seems sorted by newest library right now

**Comment by PeterDaveHello** [comment]
Maybe we can add a parameter to choose the order.

**Comment by nt1m** [comment]
seems to be fixed now

**Comment by MattIPv4** [comment]
Appears to be fixed.
