### ISSUE TITLE
[Request] Add Animations

### ISSUE THREAD

**Issue by acbarbosa1964** [cdnjs/cdnjs#5111]
Animations v2.1
https://github.com/joemottershaw/
**npm package url(optional):** 
http://www.cloud-eight.com
, Copyright 2014, Joe Mottershaw, 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
**git repository url** : https://github.com/joemottershaw/animations
[ Consider adding tags for the repo. #9 ](https://github.com/joemottershaw/animations/issues/9)
