### ISSUE TITLE
[Request] Add OverlappingMarkerSpiderfier

### ISSUE THREAD

**Issue by db0company** [cdnjs/cdnjs#5115]
**Library name:** OverlappingMarkerSpiderfier
**Git repository url:** https://github.com/jawj/OverlappingMarkerSpiderfier
**npm package url(optional):** 
**Official homepage:** https://github.com/jawj/OverlappingMarkerSpiderfier
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #96](https://github.com/jawj/OverlappingMarkerSpiderfier/issues/96)

**Comment by PeterDaveHello** [comment]
Close due to no response from upstream, this lib looks like not under maintenance.
