### ISSUE TITLE
ramda not being updated to latest NPM version [author]

### ISSUE THREAD

**Issue by CrossEye** [cdnjs/cdnjs#5129]
I raised a similar issue in #4474, and learned that I simply hadn't been patient enough.  But it's been five days since the NPM release.  Are we doing something wrong that's causing this not to auto-update on some occasions?

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/issues/4487

**Comment by CrossEye** [comment]
Is there something I can/should do to get Ramda's latest version included?  Just a standard PR with the latest repo included?  Something else?

If you're looking for help with open issue #4487, I can attempt to offer a hand.  I'm new to the codebase, but have been taking advantage of this tool without giving back.  I'm willing to help if I can.  But I'd appreciate a pointer as to where to start looking.

**Comment by CrossEye** [comment]
Well, looks like funny timing!  I guess this version was just added.

I'm still willing to try my hand at the code, if you don't have anyone with more experience who has the time to do it.

**Comment by CrossEye** [comment]
And once again @PeterDaveHello, thanks for your help!

**Comment by PeterDaveHello** [comment]
@CrossEye Thank you for your report, I added this by some tricks, not a normal update process, in fact, there is a repo called [cdnjs/autoupdate](https://github.com/cdnjs/autoupdate), I'll add npm auto-update support in it when I have time and remove [auto-update.js](https://github.com/cdnjs/cdnjs/blob/master/auto-update.js), you are welcome to join us, the todo list is opened as issues in https://github.com/cdnjs/autoupdate/issues!
