### ISSUE TITLE
[Request]createjs

### ISSUE THREAD

**Issue by tntk90** [cdnjs/cdnjs#5131]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What's the detail @tntk90 ?

**Comment by maruilian11** [comment]
@tntk90 this issue will be closed due to no response **in 10 days**, thank you for your contribution.
