### ISSUE TITLE
[Request] Add libsodium.js

### ISSUE THREAD

**Issue by freshsun** [cdnjs/cdnjs#5132]
**Library name:** libsodium
**Git repository url:** https://github.com/jedisct1/libsodium.js
**npm package url(optional):** https://github.com/paixaop/node-sodium
**Official homepage:** https://download.libsodium.org/doc/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@freshsun, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by soatok** [comment]
Regardless of whether or not it meets this threshold, libsodium.js is fundamental to modern secure Javascript application development -- whether in NW.js/Electron, browser extensions, or in client-side Javascript.

That is to say, the popularity of this library is *inevitable*, especially given the recent attention towards privacy featured apps and web services.

Please consider an exception for this case.

**Comment by Piicksarn** [comment]
@PeterDaveHello would you please take a look on this request?

**Comment by PeterDaveHello** [comment]
@Piicksarn: ping @cdnjs/intern first.

**Comment by maruilian11** [comment]
i think we can add it since its star is close to 100.

**Comment by freshsun** [comment]
https://download.libsodium.org/doc/bindings_for_other_languages/index.html
libsodium have many language bindings on github, although most of them is under 100 stars

Another 375 stars repo https://github.com/mdp/gibberish-aes shows libsodium as its replacement. And on client side javascript encryption, libsodium seems to be a promising solution now.
