### ISSUE TITLE
[Request] u-semver

### ISSUE THREAD

**Issue by alanrsoares** [cdnjs/cdnjs#5133]
**Library name:** μ-semver
**Git repository url:** https://github.com/alanrsoares/u-semver
**npm package url(optional):** https://www.npmjs.com/package/u-semver
**Official homepage:** https://github.com/alanrsoares/u-semver
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@alanrsoares, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
 but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by alanrsoares** [comment]
Got it. Thanks =)
