### ISSUE TITLE
Javascript toString error

### ISSUE THREAD

**Issue by ollie314** [cdnjs/cdnjs#5138]
Hi,
Another issue in the listing. For instance, looking for angular js. Going on the listing page and get the following result.

```javascript
https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.3/[object Object]
```

No info in console, sorry.

**Comment by PeterDaveHello** [comment]
Hi @ollie314, thanks for your report, I forgot to fully rebuild the artifacts/meta data after https://github.com/cdnjs/cdnjs/commit/dfc98cb8830b2ac2ecd31129ccf11ae53a8d3029, fixing now!

**Comment by PeterDaveHello** [comment]
Fixed!
