### ISSUE TITLE
library-url output error

### ISSUE THREAD

**Issue by ekeitho** [cdnjs/cdnjs#5141]
cdnjs is currently outputting objects items, instead of file names.
https://cdnjs.com/libraries/backbone.js
https://cdnjs.com/libraries/require.js
https://cdnjs.com/libraries/semantic-ui

ie)
https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.1/[object Object]
https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.19/[object Object]
https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.0.7/[object Object]

**Comment by ekeitho** [comment]
seems like this just got fixed, sweet!

**Comment by PeterDaveHello** [comment]
Thanks for your report.
