### ISSUE TITLE
[Request] Update jQuery Countdown 2.0.2

### ISSUE THREAD

**Issue by swcheon** [cdnjs/cdnjs#5143]
Library name: jQuery Countdown
Git repository url: None
npm package url(optional): None
Official homepage: http://keith-wood.name/countdown.html
Wanna say something? Leave message here: New version! 2.0.2. Please update :)
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@PeterDaveHello would you take a look on this issue?

**Comment by swcheon** [comment]
Oh, I didn't know that.
Thanks!! :)

**Comment by maruilian11** [comment]
i think it's here : https://github.com/hilios/jQuery.countdown

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello I think the files were updated. Suggest to close

**Comment by sashberd** [comment]
According to https://github.com/kbwood/countdown/blob/ff5999364f213a7a0ea2ec460ad3001823eea162/jquery.countdown.js#L2
Only main js file was updated to 2.0.2. All other has no chnaged
