### ISSUE TITLE
[Request] Flexisel – Responsive Carousel jQuery Plugin

### ISSUE THREAD

**Issue by sanusi87** [cdnjs/cdnjs#5147]
**Library name:Flexisel – Responsive Carousel jQuery Plugin** 
**Git repository url:https://github.com/9bitStudios/flexisel/**
**npm package url(optional):** 
**Official homepage:http://9bitstudios.github.com/flexisel/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
(https://github.com/9bitStudios/flexisel/issues/52)
