### ISSUE TITLE
[Request] jquery-ajax-native

### ISSUE THREAD

**Issue by DDRBoxman** [cdnjs/cdnjs#5149]
jquery-ajax-native
https://github.com/acigna/jquery-ajax-native
https://www.npmjs.com/package/jquery-ajax-native
https://github.com/acigna/jquery-ajax-native

**Comment by Piicksarn** [comment]
@DDRBoxman, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@DDRBoxman this issue will be closed due to no response **in 10 days**, thank you for your contribution.
