### ISSUE TITLE
[Request] Add FezVrasta/dropdown.js

### ISSUE THREAD

**Issue by mardafirmansyah** [cdnjs/cdnjs#5150]
FezVrasta/dropdown.js
https://github.com/FezVrasta/dropdown.js

Finally a dropdown plugin that transforms select inputs in nice dropdowns and does not drive you crazy.

**Comment by Piicksarn** [comment]
@mardafirmansyah , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@mardafirmansyah this issue will be closed due to no response **in 10 days**, thank you for your contribution.
