### ISSUE TITLE
jScrollPane library path change

### ISSUE THREAD

**Issue by noofaq** [cdnjs/cdnjs#5152]
Path worked for months until recent times:
https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/jquery.jscrollpane.min.js

Path which works now:
https://cdnjs.cloudflare.com/ajax/libs/jScrollPane/2.0.14/script/jquery.jscrollpane.js

It seems that subdirectory "script/" was added - it has broken quite a number of applications where old path was used.

**Comment by PeterDaveHello** [comment]
Seems I missed this issue, sorry about that, looking into it now.

**Comment by noofaq** [comment]
I have fixed this on my side by doing grep/replace on all my sources where I have used exact path to the library. I guess noone else was affected so you can ignore that as it is already a year from the moment I have noticed that change (time is going so fast...)
