### ISSUE TITLE
[Request] Add flowthings

### ISSUE THREAD

**Issue by gmmeyer** [cdnjs/cdnjs#5156]
**Library name:** flowthings browser client
**Git repository url:** https://github.com/flowthings/browser-client
**npm package url(optional):** https://www.npmjs.com/package/flowthings-browser
**Official homepage:** https://flowthings.io
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@gmmeyer, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library has notable popularity? :smiley:

**Comment by maruilian11** [comment]
@gmmeyer thank you for your contribution, the issue will be closed in 10 days due to no response.
