### ISSUE TITLE
[Request] Add moment.js v2.10.6

### ISSUE THREAD

**Issue by ismarslomic** [cdnjs/cdnjs#5162]
**Library name:** moment.js
**Git repository url:** https://github.com/moment/moment
**npm package url(optional):** 
**Official homepage:** http://momentjs.com/
**Wanna say something? Leave message here:** Can you please update moment.js to the latest version (v2.10.6)? Thanks!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ichernev** [comment]
Can we make this auto update? @ismarslomic check the cdnjs docs about auto-update and to a PR (here). I won't have enough time in the next few weeks.

**Comment by PeterDaveHello** [comment]
I think we have npm auto-update already:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/moment.js/package.json#L3-L18
```js
  "npmName": "moment",
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "moment*.js",
        "lang/*"
      ]
    },
    {
      "basePath": "/min/",
      "files": [
        "*.js"
      ]
    }
  ],
```

Though we have problem on npm auto-update: #4487

But we'll spend time on auditing the update:
https://github.com/cdnjs/cdnjs/#enabling-gitrecommended-or-npm-auto-update
> cdnjs automatically updates libraries that are known to be hosted on npm or git repo, e.g., Lodash. npm auto-update relys on each release and git auto-update relys on the tags in git repo. This auto-update script runs every hour, but **the update result won't be committed until one of our maintainers audit the updates**, because many libs will change the naming or directory structure during different versions, and we may need to minify the lib without pre-minified dist files, so **it'll be reasonable to delay for at most 30 hours**, if you think there is a lib didn't been updated, please wait at least 30 hours for the process to audit it.

**Comment by PeterDaveHello** [comment]
And we also have git auto-update, which is more reliable but not so powerful like it doesn't have multi filemap feature as npm auto-update yet.

**Comment by ismarslomic** [comment]
Thanks for quick replies. I just wonder if it is any chance to get the latest version out on cdnjs.com while you are working with fixing this bug, as I would really like to use this version in my web app asap. Thanks a lot again!

**Comment by jbruni** [comment]
@PeterDaveHello  - Moment.jS 2.12.0 is out: http://momentjs.com/ ... I wonder if the auto-update is working, or it still have to be a manual update...

**Comment by PeterDaveHello** [comment]
@jbruni thanks, I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@jbruni The structure changed so the bot would not add it automatically, i will add it now.

**Comment by PeterDaveHello** [comment]
* 7e16ca1 add moment.js v2.12.0
