### ISSUE TITLE
[Request] Add qrcode.js

### ISSUE THREAD

**Issue by steadiest** [cdnjs/cdnjs#5164]
**Library name: qrcode.js
*_Git repository url: https://github.com/davidshimjs/qrcodejs
*_npm package url(optional):** 
**Official homepage: http://davidshimjs.github.io/qrcodejs/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #60 ](https://github.com/davidshimjs/qrcodejs/issues/60)

**Comment by PeterDaveHello** [comment]
Ref: #5171

**Comment by Piicksarn** [comment]
@PeterDaveHello, how about add it as version in brower.json ?

**Comment by PeterDaveHello** [comment]
Yes we can try.

**Comment by PeterDaveHello** [comment]
Move to #9878
