### ISSUE TITLE
[Request] Add NuclearJS

### ISSUE THREAD

**Issue by raulmatei** [cdnjs/cdnjs#5165]
**Library name:** NuclearJS
**Git repository url:** https://github.com/optimizely/nuclear-js
**npm package url(optional):** https://www.npmjs.com/package/nuclear-js
**Official homepage:** https://optimizely.github.io/nuclear-js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@raulmatei Please add lib's name in the title next time, thank you!

**Comment by raulmatei** [comment]
Sorry for that.
