### ISSUE TITLE
[Request] Add socketcluster 

### ISSUE THREAD

**Issue by happilymarrieddad** [cdnjs/cdnjs#5173]
**Library name:**  
socketcluster-client

**Git repository url:** 
https://github.com/SocketCluster/socketcluster-client

**npm package url(optional):** 
https://libraries.io/npm/socketcluster-client-ws

**Official homepage:**
socketcluster.io

**Wanna say something? Leave message here:**
I love socketcluster and I thought it would be nice to be able to use a CDN instead of having to include the file(s) in my public directory. Thanks!!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Thanks for your suggestion！

However, README.md shows that :
`Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.`

Would you please make a request again when the library have notable popularity? :smiley:

**Comment by PeterDaveHello** [comment]
I think [SocketCluster/socketcluster](https://github.com/SocketCluster/socketcluster) enough popularity.

**Comment by Piicksarn** [comment]
@PeterDaveHello, Thanks!

**Comment by happilymarrieddad** [comment]
Hi,
SocketCluster/socketcluster has over 2000 watchers/stars and socketcluster-client is just one part of socketcluster. Is it possible to use the popularity of socketcluster to bring socketcluster client to CDNJS? Thanks!

|   |
|   |  |   |   |   |   |   |
| SocketCluster/socketclustersocketcluster - Highly scalable realtime microframework |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


 


     On Sunday, August 9, 2015 3:52 AM, Piicksarn <notifications@github.com> wrote:
   

 @PeterDaveHello, Thanks!—
