### ISSUE TITLE
[Feature Request] Auto-update

### ISSUE THREAD

**Issue by AliMD** [cdnjs/cdnjs#5176]
Could you please add auto update feature like [this](https://github.com/jsdelivr/jsdelivr#auto-updating)

**Comment by PeterDaveHello** [comment]
Which feature of auto-update you want to have @AliMD ? We have auto-update mechanism for a long time.

**Comment by AliMD** [comment]
I don't see that!
I think we must update new versions manually

**Comment by PeterDaveHello** [comment]
Did you read our readme.md?
