### ISSUE TITLE
[Request] add tape-dom

### ISSUE THREAD

**Issue by gritzko** [cdnjs/cdnjs#5178]
tape-dom
It is a DOM pretty printer for the [tape unit testing lib](https://www.npmjs.com/package/tape)
https://github.com/gritzko/tape-dom
https://www.npmjs.com/package/tape-dom

I mostly want to host tape.css so the library may add the stylesheet programmatically.

**Comment by Piicksarn** [comment]
@gritzko, thanks for your great work！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```

Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@gritzko this issue will be closed due to no response **in 10 days**, thank you for your contribution.

**Comment by gritzko** [comment]
Sorry, I forgot this one.
I simply inlined the CSS. That is a better solution.
Sorry for disturbance.
