### ISSUE TITLE
[Request] comix-ngn [author]

### ISSUE THREAD

**Issue by ogewan** [cdnjs/cdnjs#5179]
Please add [comix-ngn](https://github.com/ogewan/comix-ngn), master branch.

**Comment by PeterDaveHello** [comment]
Would you like to send a PR to add it by yourself @ogewan ? Thanks!

**Comment by ogewan** [comment]
I can't ATM due to computer issues.

**Comment by maruilian11** [comment]
@ogewan due to less of popularity, we suggest you can open the issue again when the repo has enough popularity(at least 100 watch or star). please see our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

**Comment by maruilian11** [comment]
@ogewan this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
