### ISSUE TITLE
[Request] Add ng-showdown

### ISSUE THREAD

**Issue by tomkwok** [cdnjs/cdnjs#5180]
**Library name:** ng-showdown
**Git repository url:** https://github.com/showdownjs/ng-showdown
**npm package url(optional):** 
**Official homepage:** https://github.com/showdownjs/ng-showdown
**Wanna say something? Leave message here:**
ng-showdown doesn't have 100 stars, as it is recently split from the showdown.js core. Now ng-showdown is required for angular integration.
From https://github.com/showdownjs/showdown/releases:
> angular: angular integration was removed from core and now lives in it's own repository.
If you're using angular integration, you should install ng-showdown

**Comment by Piicksarn** [comment]
@PeterDaveHello, I think it could be added in cdnjs!
how do you think? :)

**Comment by PeterDaveHello** [comment]
Sure.
