### ISSUE TITLE
[Request] AFC

### ISSUE THREAD

**Issue by ashok1994** [cdnjs/cdnjs#5183]
**Library name:AFC** 
**Git repository url:https://github.com/ashok1994/afc.git**
**npm package url(optional):** 
**Official homepage:amiyasfoodcourt.in**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Thanks for your suggestion！

However, README.md shows that :
`Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.`

Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@ashok1994 this issue will be closed due to no response **in 10 days**, thank you for your contribution.
