### ISSUE TITLE
[Request] RiotGear 

### ISSUE THREAD

**Issue by tidusvn05** [cdnjs/cdnjs#5184]
**Library name: Riotgear** 
**Git repository url: https://github.com/RiotGear/rg **
**npm package url(optional):** 
**Official homepage: https://riotgear.github.io**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@tidusvn05, thanks for your suggestion！

However, README.md shows that :
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.

Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@tidusvn05 this issue will be closed due to no response **in 10 days**, thank you for your contribution.
