### ISSUE TITLE
[Request] jTabs

### ISSUE THREAD

**Issue by wolf-w** [cdnjs/cdnjs#5186]
**jTabs** 
**https://github.com/wolf-w/jTabs/**
**Sweet material tabs**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@wolf-w hanks for your suggestion！

However, README.md shows that :
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added.

Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@wolf-w this issue will be closed due to no response **in 10 days**, thank you for your contribution.
