### ISSUE TITLE
Select reinitialization drops carret.

### ISSUE THREAD

**Issue by rexopl** [cdnjs/cdnjs#5188]
There is a problem with selects when updating/reinitializing (without page refresh) in version 0.97.
I rebuild selects like this:
$('select').material_select('destroy');
$('select').material_select();

After every rebuild there is one more carret symbol next to updated selects.
This problem started with 0.97 version.

Same problem when updating without destroy:
$('select').material_select();

Attached image:
http://s12.postimg.org/w7h6fsby5/select.jpg

**Comment by PeterDaveHello** [comment]
Is this a problem of cdnjs?

**Comment by rexopl** [comment]
Ooops sorry wrong git :)!
