### ISSUE TITLE
[Request] Add Vue Router

### ISSUE THREAD

**Issue by IamSwap** [cdnjs/cdnjs#5190]
**Library name: Vue Router** 
**Git repository url: https://github.com/vuejs/vue-router**
**npm package url(optional):** 
**Official homepage: https://github.com/vuejs/vue-router**
**Wanna say something? Leave message here:**
Official Vue js addon library

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #73](https://github.com/vuejs/vue-router/issues/73)

**Comment by Amomo** [comment]
vue-router has tags now.
@Piicksarn could you please make a PR for help? Thanks~

**Comment by Piicksarn** [comment]
@Amomo, ok i got it!
