### ISSUE TITLE
[Request] Add piklor

### ISSUE THREAD

**Issue by digitalsurgeon** [cdnjs/cdnjs#5192]
**Library name:** piklor.js 
**Git repository url:** https://github.com/jillix/piklor.js
**npm package url(optional):** 
**Official homepage:** http://jillix.github.io/piklor.js
**Wanna say something? Leave message here:** Its a cool and very pretty color picker.

**Comment by Piicksarn** [comment]
@digitalsurgeon, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library have notable popularity? :smiley:

**Comment by maruilian11** [comment]
@digitalsurgeon this issue will be closed due to no response **in 10 days**, thank you for your contribution.
