### ISSUE TITLE
Enrich these libs' package.json [repository]

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5194]
These libs don't have both `repository` & `repositories`, maybe even don't have some other common fields, should add more info in there package.json to help us maintain these libs.

Example:
https://github.com/cdnjs/cdnjs/commit/1a384ede062c59c3b1663383ef017791dc834975

Lib list:
- [ ] 1140
- [ ] amcharts
- [ ] ammaps
- [ ] amstockchart
- [ ] boexfi - no repo
- [ ] canvasjs - no repo
- [ ] casualjs - no repo
- [x] chaplin
- [ ] chrome-frame - no repo, no longer supported since 2014
- [ ] dd_belatedpng - no repo, only homepage
- [ ] expect.js
- [ ] ext-core - no repo, wrong license
- [ ] extjs - no repo, only sencha cdn
- [ ] fatcow-icons - no repo, but need to update license format
- [x] firebug-lite
- [ ] flipCounter - no repo, homepage is no longer in maintainance
- [ ] foundicons - to be confirmed
- [ ] jcalculator
- [ ] jqplugin - no repo
- [x] jquery.caroufredsel
- [ ] jquery.selectboxit
- [ ] jquery.socialshareprivacy - no repo, only homepage
- [x] jquery.turbolinks
- [x] jvectormap
- [ ] linq.js - to be confirmed http://linqjs.codeplex.com/
- [ ] log4javascript - no repo, only homepage, but license can be updated
- [ ] meyer-reset - no repo, only homepage, but license can be updated
- [x] min
- [x] ng-currency
- [ ] polyglot
- [x] soundplayer-widget
- [ ] tablefilter - to be confirmed
- [ ] twilio.js - only achieve on the web page
- [x] typeahead-addresspicker
- [ ] WebRupee -  no repo

**Comment by PeterDaveHello** [comment]
cc @Piicksarn @maruilian11 @LeaYeh @Amomo 
Please take this issue, add mention #5194 in each PR's comment, thanks.

**Comment by PeterDaveHello** [comment]
ping @cdnjs/intern to work on this issue.

**Comment by maruilian11** [comment]
got it

**Comment by Amomo** [comment]
ok~ :+1:

**Comment by PeterDaveHello** [comment]
@Amomo @LeaYeh Please help mark the libs in this commit as done.
https://github.com/cdnjs/cdnjs/commit/4c5838dd6cf8e7947e1ff10227fad5138e5488be

**Comment by Amomo** [comment]
I have marked them. 😁

**Comment by PeterDaveHello** [comment]
Let's check the remaining projects.

**Comment by Amomo** [comment]
update the list according  #5492 #5501 #5523 #5535

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by Amomo** [comment]
update the list according #5471(simplemodal) #5628(highcharts) #5632(highmaps)

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by PeterDaveHello** [comment]
Ping @LeaYeh
