### ISSUE TITLE
Point filename field to minified file

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5195]
These is the value `filename` field without suffix `.min.` in the libs we hosted, not sure if they are already minified or not, **may even not be correct**, the filename field should point to a minified and production mainfile. for example, see this commit for js-data: 2703d3b.
- [x] browser.js
- [x] svg-morpheus.js
- [x] ace.js
- [x] com.iskitz.ajile.js
- [x] amcharts.js
- [x] ammap.js
- [x] amstock.js
- [x] angular-locale_en-us.js
- [x] audiosynth.js
- [x] aui/js/aui.js
- [x] backbone-react-component.js
- [x] backbone.modal-bundled.js
- [x] basics.css
- [x] benchmark.js
- [x] mindb
- [x] ckeditor.js
- [x] coin-slider.js
- [ ] cookiejar.js
- [x] cookies-monster.js
- [x] rollups/md5.js
- [x] load1.css
- [x] PIE_IE678.js
- [x] diff_match_patch.js
- [x] document-register-element.js
- [x] dojo.js
- [x] dom4.js
- [x] dygraph-combined.js
- [x] echarts.js
- [x] eddy.dom.js
- [x] es-class.js
- [x] ext-all.js
- [x] jquery.fancybox.pack.js
- [x] script/GeoExt.js
- [x] highcharts.js
- [x] highmaps.js
- [x] highstock.js
- [x] hprose-html5.js
- [x] ie8.js
- [x] jquery.serialize-object.compiled.js
- [ ] jquery.ui.map.js
- [x] jquery.carouFredSel.packed.js
- [x] sha.js
- [x] jsxgraphcore.js
- [x] kwargs.js
- [x] leaflet.draw.js
- [x] leaflet.markercluster.js
- [x] leaflet.js
- [ ] maps/svg/production/ic_beenhere_24px.svg
- [x] MathJax.js
- [ ] lang.js
- [x] mori.js
- [x] musicmetadata.js
- [x] OpenLayers.js
- [ ] picker.js
- [x] piwik.js
- [x] proj4.js
- [x] base.js
- [x] query-result.js
- [x] rangy-core.js
- [x] async.js
- [x] restyle.js
- [x] sbt-core-dojo-amd.js
- [x] css/scojs.css
- [x] sea.js
- [x] shaka-player.compiled.js
- [x] spf.js
- [x] system.js
- [x] tagmanager.js
- [ ] font/icomatic.css
- [x] unsemantic-grid-responsive.css
- [x] video.js
- [x] webfontloader.js
- [ ] webkit.js

cc @Piicksarn @maruilian11 @LeaYeh @Amomo 
Please take this issue, add mention this issue ticket in each PR's comment, thanks.

**Comment by sethlivingston** [comment]
@PeterDaveHello The files on CDNJS (as soon as https://github.com/cdnjs/cdnjs/pull/5201 gets approved) will point to the minified versions. Our Bower distribution (stampit-org/bower) also has minified versions. Is this what you are referring to?

**Comment by maruilian11** [comment]
ace.js is not minified.

**Comment by PeterDaveHello** [comment]
`browser.js` belongs to `6to5`

**Comment by PeterDaveHello** [comment]
See: https://cdnjs.com/#q=browser.js

**Comment by maruilian11** [comment]
<code>browser.js, svg-morpheus.js,  amcharts/3.13.0</code> is minified.

**Comment by PeterDaveHello** [comment]
Thanks!

**Comment by Piicksarn** [comment]
OpenLayers.js
sea.js
sbt-core-dojo-amd.js
sha.js
spf.js
system.js
shaka-player.compiled.js
script/GeoExt.js

are minified.

**Comment by PeterDaveHello** [comment]
Thanks @Piicksarn.

List updated.

**Comment by maruilian11** [comment]
ic_beenhere_24px.svg is an icon, is there something wrong?

**Comment by maruilian11** [comment]
minified:
* ammap.js
* amcharts.js
* aui.js
* basics.css
* ckeditor.js
* cookies-monster.js
* md5.js
* load1.css
* PIE_IE678.js
* diff_match_patch.js
* document-register-element.js
* dom4.js
* echarts.js
* eddy.dom.js
* es-class.js
* jquery.fancybox.pack.js
* highcharts.js
* highmaps.js
* highstock.js
* hprose-html5.js
* ie8.js
* jquery.serialize-object.compiled.js
* jquery.carouFredSel.packed.js
* leaflet.draw.js
* leaflet.markercluster.js
* leaflet.js
* MathJax.js
* piwik.js
* base.js
* query-result.js
* rangy-core.js
* restyle.js
* unsemantic-grid-responsive.css
* video.js
* webfontloader.js

**Comment by Piicksarn** [comment]
Wow!!! THANK YOU! maruilian11!:grinning::grinning::grinning:

**Comment by PeterDaveHello** [comment]
Nice job @maruilian11, list updated.

**Comment by PeterDaveHello** [comment]
And where is @LeaYeh @Amomo ?

**Comment by Amomo** [comment]
I am following~
I would finish the PR's checking work first. I am late for reply.
After that I will concerned about these two issues.

**Comment by Amomo** [comment]
I think `amstock.js` is minified.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by Amomo** [comment]
You have merge PR #5206 , so I think `backbone.modal-bundled.js` could be checked.
And, `com.iskitz.ajile.js` is a minified file.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by Amomo** [comment]
`dojo.js`, `ext-all.js`, ` jsxgraphcore.js`, `proj4.js` are minified.
And, I have found `async.js` in "async/", "neo-async/" and "requirejs-async/", but each of these lib has pointed to minified file.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by LeaYeh** [comment]
**already minified**
angular-locale_en-us.js

-----

**point to minified**

audiosynth.js
backbone-react-component.js

**Comment by PeterDaveHello** [comment]
What do you mean @LeaYeh ?
> **point to minified**
> 
> audiosynth.js
> backbone-react-component.js

**Comment by PeterDaveHello** [comment]
ping @LeaYeh

**Comment by Amomo** [comment]
`audiosynth.js`, `backbone-react-component.js`, `benchmark.js` are minified.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by Amomo** [comment]
update the list according #5517(coin-slider) #5518(kwargsjs) #5520(mori) #5521(musicmetadata) #5522(sco.js) #5524(tagmanager)

**Comment by Piicksarn** [comment]
@cdnjs/intern.
