### ISSUE TITLE
[Request] Add At.js

### ISSUE THREAD

**Issue by NamPNQ** [cdnjs/cdnjs#5196]
**Library name:** At.js
**Git repository url:** https://github.com/ichord/At.js
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

**Comment by Piicksarn** [comment]
#5198 Add at.js v1.3.2 with git auto-update, close #5196

**Comment by NamPNQ** [comment]
@Piicksarn Tks for fast :dancer:

**Comment by Amomo** [comment]
@Piicksarn Could you re-send a PR to add this library?
