### ISSUE TITLE
[Request] Add gentelella

### ISSUE THREAD

**Issue by fsiddiqi** [cdnjs/cdnjs#5200]
**Library name: gentelella 
**Git repository url: https://github.com/kimlabs/gentelella
**npm package url(optional):** 
**Official homepage: http://demo.kimlabs.com/gentelella/production/index.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #13](https://github.com/kimlabs/gentelella/issues/13)

**Comment by PeterDaveHello** [comment]
Now it has both npm package and valid git tag, just need to figure out what are the files should be added.

**Comment by PeterDaveHello** [comment]
Seems we can add `build` since v1.3.0
