### ISSUE TITLE
[Request] Add videogular

### ISSUE THREAD

**Issue by Sheldan** [cdnjs/cdnjs#5216]
**Library name:** videogular
**Git repository url:** https://github.com/2fdevs/videogular
**npm package url(optional):** 
**Official homepage:** http://www.videogular.com/
**Wanna say something? Leave message here:**
They also have some plugins to their main library here:
https://github.com/search?q=user%3A2fdevs+bower-
I add this here, as I didn't want to create issues for all of them.

**Comment by 2fdevs** [comment]
Hi @Sheldan, thanks for requesting this :)

In fact our main repository is this: https://github.com/2fdevs/bower-videogular

The other ones are plugin repositories and theme repositories.

**Plugins**
* https://github.com/2fdevs/bower-videogular-controls
* https://github.com/2fdevs/bower-videogular-overlay-play
* https://github.com/2fdevs/bower-videogular-buffering
* https://github.com/2fdevs/bower-videogular-analytics
* https://github.com/2fdevs/bower-videogular-dash
* https://github.com/2fdevs/bower-videogular-poster
* https://github.com/2fdevs/bower-videogular-ima-ads

**Themes**
* https://github.com/2fdevs/bower-videogular-themes-default

**Comment by maruilian11** [comment]
@2fdevs thank you very much!
