### ISSUE TITLE
[Request] SmoothScroll 

### ISSUE THREAD

**Issue by nativeimaging** [cdnjs/cdnjs#5217]
**Library name:** SmoothScroll
**Git repository url:** https://gist.github.com/galambalazs/6477177
**npm package url(optional):** 
**Official homepage:** https://gist.github.com/galambalazs/6477177
**Wanna say something? Leave message here:** The best simple smooth scroller ever

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Would you mind to ask if the author wanna create a repo for this lib?

**Comment by galambalazs** [comment]
Author here. Sure, I'll make a PR.

**Comment by maruilian11** [comment]
**git repo url:**https://github.com/galambalazs/smoothscroll

**Comment by maruilian11** [comment]
update : https://github.com/galambalazs/smoothscroll-for-websites
