### ISSUE TITLE
[Request] angular-gravatar

### ISSUE THREAD

**Issue by Javichino** [cdnjs/cdnjs#5218]
**Library name: angular-gravatar
**Git repository url: https://github.com/wallin/angular-gravatar
**npm package url(optional): angular-gravatar
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it now.

**Comment by maruilian11** [comment]
@Javichino this issue will be closed due to no response **in 10 days**, thank you for your contribution.
