### ISSUE TITLE
[Request] Add jquery.cookiebar.js

### ISSUE THREAD

**Issue by Seenox** [cdnjs/cdnjs#5220]
**Library name: jquery.cookiebar.js

** 
**Git repository url: http://www.primebox.co.uk/files/uploads/jquery.cookiebar.zip**
**npm package url(optional):** 
**Official homepage: http://www.primebox.co.uk/projects/jquery-cookiebar/**
**Wanna say something? Leave message here: The Cookie Bar plugin creates a small bar at the top or bottom of the website with a short message about cookies and accept, decline, and privacy policy buttons.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@Seenox, i could not find the link of git repository url or npm package url on homepage.
Would you please show the git repository url or npm package url?
Thank you!

**Comment by PeterDaveHello** [comment]
Same as @Piicksarn said, or if you can provide some other ways to proof its users popularity will be fine.

**Comment by Seenox** [comment]
@Piicksarn @PeterDaveHello,

Thanks for the reply. I've just sent an email to the developer and asked for it. Will update the thread as soon as I get a reply.

**Comment by PeterDaveHello** [comment]
Any updates here @Seenox ?

**Comment by Seenox** [comment]
@PeterDaveHello I didn't get any reply from the developer regarding this and seems like he's not updating it either. Please feel free to close this. Thanks.

**Comment by PeterDaveHello** [comment]
Thanks @Seenox

**Comment by PeterDaveHello** [comment]
@Seenox I just found another jquery.cookieBar and open an issue for it in #7456, not sure if this can help, just FYI.

**Comment by Seenox** [comment]
@PeterDaveHello I've just checked it and it seems promising. Although it lacks some features the other one has. Thanks for letting me know.

**Comment by PeterDaveHello** [comment]
@Seenox no problem.
