### ISSUE TITLE
[Request] Add ExifReader

### ISSUE THREAD

**Issue by TrevorS** [cdnjs/cdnjs#5223]
**Library name:** ExifReader
**Git repository url:** https://github.com/mattiasw/ExifReader
**npm package url(optional):** N/A
**Official homepage:** https://github.com/mattiasw/ExifReader
**Wanna say something? Leave message here:**

Thanks!

**Comment by Piicksarn** [comment]
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, but as long as reasonable popularity can be demonstrated the library will be added :)

**Comment by maruilian11** [comment]
@TrevorS this issue will be closed due to no response **in 10 days**, thank you for your contribution.

**Comment by TrevorS** [comment]
Sorry about that.  I understand.  Only 67 stars on their repo.  Thanks!
