### ISSUE TITLE
[Request] tcc

### ISSUE THREAD

**Issue by theconanclub** [cdnjs/cdnjs#5224]
**Library name: tcc** 
**Git repository url:n/a**
**npm package url(optional):** 
**Official homepage: theconanclub.com**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @theconanclub , could you give us more detail about the `repository url`?

**Comment by maruilian11** [comment]
@theconanclub this issue will be closed due to no response **in 10 days**, thank you for your contribution.
