### ISSUE TITLE
[Request] Add Freewall 

### ISSUE THREAD

**Issue by tonytlwu** [cdnjs/cdnjs#5226]
**Library name:** Freewall
**Git repository url:** https://github.com/kombai/freewall
**npm package url(optional):** 
**Official homepage:** http://vnjs.net/www/project/freewall/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@tonytlwu :grinning:
Freewall is already in cdnjs!
https://cdnjs.com/libraries/freewall
Thank you!
