### ISSUE TITLE
[Request] Add d3-svg-legend

### ISSUE THREAD

**Issue by curran** [cdnjs/cdnjs#5230]
**Library name:** d3-legend
**Git repository url:** https://github.com/susielu/d3-legend
**npm package url(optional):** https://www.npmjs.com/package/d3-svg-legend
**Official homepage:** http://d3-legend.susielu.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[ Consider adding tags for the repo. #9 ](https://github.com/susielu/d3-legend/issues/9)

**Comment by curran** [comment]
@Piicksarn Thank you for having a look at this.
