### ISSUE TITLE
[Request] Datatable language files

### ISSUE THREAD

**Issue by stopsopa** [cdnjs/cdnjs#5234]
I would be nice to have language files for datatables plugin like here:
http://cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/
now are only base files of this plugin on cdnjs http://cdnjs.com/libraries/datatables

Thx

**Comment by maruilian11** [comment]
@stopsopa sorry, we only provide the files on GItHub, it seems that they they didn't put those language files on GitHub. or you can provide the url (github) for us. thank you.

**Comment by maruilian11** [comment]
@stopsopa this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
https://github.com/DataTables/Plugins
