### ISSUE TITLE
[Request] Add vkBeautify

### ISSUE THREAD

**Issue by christianscharr** [cdnjs/cdnjs#5239]
**Library name: vkBeautify** 
**Git repository url: https://github.com/vkiryukhin/vkBeautify**
**Official homepage: http://www.eslinstructor.net/vkbeautify/**

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #14](https://github.com/vkiryukhin/vkBeautify/issues/14)

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close, since too much time pas since the issue was opened and request to add git tags was sent to author
