### ISSUE TITLE
"Fork me on GitHub" covers "Request a lib" button.

### ISSUE THREAD

**Issue by bardiharborow** [cdnjs/cdnjs#5249]
The "Fork me on GitHub" ribbon thing makes it impossible to click "Request a lib" on package pages (an [example](https://cdnjs.com/libraries/twitter-bootstrap/)).

**Comment by PeterDaveHello** [comment]
hmmmm ... I'll check it.

**Comment by PeterDaveHello** [comment]
This should fix it.
https://github.com/cdnjs/new-website/commit/e5a975cbd4b259ea21c0fcb03e9049e496e45099
