### ISSUE TITLE
[Request] Add _Slip

### ISSUE THREAD

**Issue by agalazis** [cdnjs/cdnjs#5250]
**Library name:*slip* 
**Git repository url:*https://github.com/pornel/slip *
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by agalazis** [comment]
Fixed library name in title

**Comment by Piicksarn** [comment]
**Git repository url :** https://github.com/pornel/slip
@agalazis, thanks for your suggestion！
However, the library misses the package.json.
Would you please make a request again when the library include package.json?:smiley:

Piicksarn
