### ISSUE TITLE
[Request] Add image-picker

### ISSUE THREAD

**Issue by murilobr** [cdnjs/cdnjs#5254]
**Library name: image-picker** 
**Git repository url: https://github.com/rvera/image-picker**
**npm package url(optional):** 
**Official homepage: http://rvera.github.io/image-picker/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @murilobr , cdnjs has `image-picker` already.
Thanks for your request, you could try this library now. :+1:
