### ISSUE TITLE
[Request] angular-route.min.js

### ISSUE THREAD

**Issue by myndfire** [cdnjs/cdnjs#5257]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What's the lib's name?

**Comment by maruilian11** [comment]
@myndfire please provide the official git repo. thanks!
this issue will be closed due to no response **in 10 days**, thank you for your contribution.
