### ISSUE TITLE
[Request] FuckAdBlock

### ISSUE THREAD

**Issue by anonprophet** [cdnjs/cdnjs#5258]
**Library name:** FuckAdBlock
**Git repository url:** https://github.com/sitexw/FuckAdBlock
**npm package url(optional):** 
**Official homepage:** http://sitexw.fr/fuckadblock/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #5137

**Comment by anonprophet** [comment]
@PeterDaveHello this cdn already added?

i cant find it in cdnjs

**Comment by PeterDaveHello** [comment]
Not added, under auditing, but we can discuss in the same issue ticket.
