### ISSUE TITLE
[Request] Add tPlayer_audio

### ISSUE THREAD

**Issue by mmetrodw** [cdnjs/cdnjs#5260]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Would you please make some details of the request ?

**Comment by maruilian11** [comment]
@mmetrodw please provide `Git repository url` or `npm package url`. thank you!
this issue will be closed due to no response **in 10 days**, thank you for your contribution.
