### ISSUE TITLE
[Request] tPlayer

### ISSUE THREAD

**Issue by mmetrodw** [cdnjs/cdnjs#5261]
**Library name:tPlayer** 
**Git repository url:id-fis.ru:**
**npm package url(optional):** 
**Official homepage:id-fis.ru**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@mmetrodw is the request reference to #5260?
and i could not find the link of git repository url  or npm package url on homepage.
would you please show the git repository url or npm package url?

**Comment by maruilian11** [comment]
@mmetrodw this issue will be closed due to no response **in 10 days**, thank you for your contribution.
