### ISSUE TITLE
Validate.js 0.8.0 is actually 0.7.1

### ISSUE THREAD

**Issue by dooman87** [cdnjs/cdnjs#5264]
@ansman 

http://cdnjs.cloudflare.com/ajax/libs/validate.js/0.8.0/validate.js 

The top comment:

```javascript
//     Validate.js 0.7.1

//     (c) 2013-2015 Nicklas Ansman, 2013 Wrapp
//     Validate.js may be freely distributed under the MIT license.
//     For all details and documentation:
//     http://validatejs.org/
```

Could it be caching issue? Or version in comment wrong?

**Comment by ansman** [comment]
The comment is simply wrong, the version object in the code is correct. The minified version has the correct banner.

**Comment by PeterDaveHello** [comment]
That's not our problem, but validate.js's, as @ansman said, the comment is wrong.
