### ISSUE TITLE
[Request] Add startbootstrap-creative

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5270]
**Library name:** startbootstrap-creative
**Git repository url:** https://github.com/IronSummitMedia/startbootstrap-creative

Reference:
https://cdnjs.com/#q=startbootstrap

**Comment by Amomo** [comment]
We have this lib already, right?
https://cdnjs.com/libraries/startbootstrap-creative

**Comment by PeterDaveHello** [comment]
This issue is a test.

**Comment by Amomo** [comment]
Sorry! XDD
