### ISSUE TITLE
Should not point the version number to a non-stable/production version.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5276]
These libraries seems to be a non-stable/production version, need to check if there is updates, should not use a non-stable/production version number in package.json.
- [ ] amazeui-react version: 1.0.0-beta1 : **no stable version**
- [x] bootstrap-rtl version: 3.2.0-rc2  
- [x] css3pie version: 2.0beta1  
- [x] ember-i18n version: 3.0.0-beta.2  
- [ ] github-repo-widget version: e23d85ab8f : **no stable version**
- [x] jquery-infinitescroll version: 2.0b2.120519  
- [ ] jquery-ui-bootstrap version: 0.5pre  
- [ ] jquery-ui-map version: 3.0-rc1  
- [ ] jschannel version: 1.0.0-git-commit1-8c4f7eb : **no stable version**
- [x] json-mask version: 0.1.1-alpha  
- [x] markdown.js version: 0.6.0-beta1  
- [ ] matter-js version: 0.8.0-alpha  : **no stable version**  
- [x] onsen version: 1.2.0-beta  
- [ ] pie version: 1.0beta5  
- [ ] repo.js version: 5c0eae0f1b : **no stable version**
- [ ] skycons version: 1396634940 : **no stable version**
- [x] two.js version: 0.1.0-alpha  
- [x] unsemantic version: 0  
- [ ] web-starter-kit version: 0.2.0-beta  
- [ ] zocial version: 0

cc @Piicksarn @maruilian11 @LeaYeh @Amomo 
Please take this issue, add mention this issue ticket in each PR's comment, thanks.

**Comment by LeaYeh** [comment]
okay.

**Comment by Amomo** [comment]
I found that `css3pie` and `pie` are point to same repository!

**Comment by PeterDaveHello** [comment]
#5287

**Comment by Amomo** [comment]
Hi @PeterDaveHello ,
`jquery-infinitescroll`, `markdown.js`, `onsen`, `json-mask`, `two.js` and `unsemantic`
have pointed to a stable version and been merged so far.

And, I found some libraries haven't release a stable version yet.
- skycons
- amazeui-react
- github-repo-widget
- jschannel
- repo.js

**Comment by Amomo** [comment]
There are still some libraries that I have no idea how to deal with them.
- jquery-ui-bootstrap version: 0.5pre
- ember-i18n version: 3.0.0-beta.2
- web-starter-kit version: 0.2.0-beta
- css3pie version: 2.0beta1
Could you give me some advice? @cdnjs/intern

**Comment by maruilian11** [comment]
@Amomo maybe we can find out their git url and update them:)
**jquery-ui-bootstrapgit repo url:** https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap

**Comment by maruilian11** [comment]
i think `ember-i18n` use git autoupdate could be better https://github.com/jamesarosen/ember-i18n

**Comment by Amomo** [comment]
@maruilian11 Thank you! but I have some more complex thing need to discuss with you.
Could you give me some advice? @cdnjs/intern

The filemap of `ember-i18n` has changed, I can't find required files.

`web-starter-kit` provide user a example JS file to extend their customize version.
I am confused that should we provide CDN for this?
And, official repo doesn't provide css, but scss now. 😱

`css3pie` needs to build to get required files.

**Comment by maruilian11** [comment]
@Amomo i have no idea about `ember-i18n`, can we ask PeterDaveHello?

**Comment by LeaYeh** [comment]
github-repo-widget version: e23d85ab8f
-> this repo has no tags.

**Comment by Piicksarn** [comment]
@cdnjs/intern.
