### ISSUE TITLE
[Request] Add escher

### ISSUE THREAD

**Issue by aebrahim** [cdnjs/cdnjs#5282]
**Library name:** escher
**Git repository url:** https://github.com/zakandrewking/escher/
**npm package url(optional):** 
**Official homepage:** https://escher.github.io/
**Wanna say something? Leave message here:** Files in escher/escher/lib

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@aebrahim , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library has notable popularity? :smiley:

**Comment by aebrahim** [comment]
Oops sorry did not notice that. I'll do it then.
