### ISSUE TITLE
[Request] HTML-KickStart

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/cdnjs#5289]
**Library name:** html-kickstart
**Git repository url:** https://github.com/joshuagatcke/HTML-KickStart

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo. #77](https://github.com/joshuagatcke/HTML-KickStart/issues/77)

**Comment by mercyg** [comment]
@PeterDaveHello @maruilian11 I was going to add this library using cdnjs-importer I got the error that it doesn't have package.json. How do I create the package.json before cloning the library?

**Comment by maruilian11** [comment]
@mercyg Sorry, I'm not familiar with cdnjs-importer, but I will try it in my free time. Could you please use another way to add lib first? Thank you!

**Comment by mercyg** [comment]
@maruilian11 what is the other way to add the library? I have only used the cdnjs-importer :) thanks

**Comment by maruilian11** [comment]
@mercyg OK, I got your point. I just tried cdnjs-importer myself, and looks like there must be a package.json on the repo before cloning it. You can:
1. Send a PR to the lib repo to add a package.json. 
2. Open an issue to ask if the author can create a package.json.

We can't  use cdnjs-import on this lib until it done. 

Other ways to add the library mentioned in [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-pull-request)
I will recommend the simplest way: [adding-a-new-library-by-a-single-packagejson](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson)

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close, since too much time pas since the issue was opened and request to add git tags was sent to author
