### ISSUE TITLE
Not scrolling works when you increase or decrease

### ISSUE THREAD

**Issue by Zizix** [cdnjs/cdnjs#5290]
Not scrolling works when you increase or decrease the page ( Ctrl + +/- ) Google Chrome/ Fix please, this creates problems navigating some of my visitors. Works very well, but this problem prevents me to use it. https://github.com/cdnjs/cdnjs/issues/5217

**Comment by PeterDaveHello** [comment]
Is this problem related to cdnjs?

**Comment by PeterDaveHello** [comment]
Close due to no response.
