### ISSUE TITLE
[Request] Add NuclearJS addons for React

### ISSUE THREAD

**Issue by raulmatei** [cdnjs/cdnjs#5294]
**Library name:** NuclearJS addons for React
**Git repository url:** https://github.com/jordangarcia/nuclear-js-react-addons
**npm package url(optional):** https://www.npmjs.com/package/nuclear-js-react-addons
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@raulmatei, thanks for your suggestion！

However, [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
 but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library has notable popularity? :smiley:

**Comment by maruilian11** [comment]
@raulmatei this issue will be closed due to no response **in 10 days**, thank you for your contribution.
