### ISSUE TITLE
[Request] jQuery slimScroll

### ISSUE THREAD

**Issue by ihsinh** [cdnjs/cdnjs#5297]
**Library name:** jQuery slimScroll
**Git repository url:**https://github.com/rochal/jQuery-slimScroll
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ihsinh** [comment]
sorry, it is already on http://cdnjs.com/libraries/jQuery-slimScroll

**Comment by IonicaBizau** [comment]
:+1:
