### ISSUE TITLE
[Request] Add flipclock

### ISSUE THREAD

**Issue by Stoltze** [cdnjs/cdnjs#5303]
**Library name:Flipclock** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:http://flipclockjs.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
**git repository url :** https://github.com/objectivehtml/FlipClock

@Stoltze would you please provide the **`git repository url `**or **`npm package url`** next time?
So that we could add library efficiently.

Thank you! :)

**Comment by IonicaBizau** [comment]
@Piicksarn If you're adding new libraries to cdnjs, could you please try the [new version of `cdnjs-importer`](https://github.com/cdnjs/cdnjs-importer/pull/13)?

I'm curious how stable is that and if everything works fine I will release the new version. :four_leaf_clover:

**Comment by Piicksarn** [comment]
@IonicaBizau, OK! :smiley:

**Comment by maruilian11** [comment]
@Stoltze this issue will be closed due to no response **in 10 days**, thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Close due to we have it now:
https://cdnjs.com/libraries/flipclock
