### ISSUE TITLE
Migrate the format of autoupdate field

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5311]
We use `npmName` and `npmFileMap` for npm auto-update and `autoupdate` field for others(currently, only git auto-update uses it), should make npm use the new format.

**Comment by PeterDaveHello** [comment]
* [ ] Update npm auto-updater to use the new format.
 * [ ] Convert all the libs with npm auto-update to use the new format.

**Comment by valorkin** [comment]
@PeterDaveHello could it be the reason why https://cdnjs.com/libraries/ng2-bootstrap
is not updating from npm?

**Comment by PeterDaveHello** [comment]
@valorkin nope, see https://github.com/cdnjs/cdnjs/pull/6808#discussion_r51522175

**Comment by xtuc** [comment]
PR is https://github.com/cdnjs/cdnjs/pull/10080. I'm not sure if it's better to do it in this repo and once we moved to the new repo. The new autoupdater supports both formats

**Comment by MattIPv4** [comment]
We have now completed all the prerequisites needed for this migration and have moved all package configuration JSON files to cdnjs/packages -- the only remaining task is to make a cleanup commit there that migrates the auto-update config strucuture for those using the legacy NPM format. This is covered by https://github.com/cdnjs/packages/issues/253
