### ISSUE TITLE
Add extra url in main url

### ISSUE THREAD

**Issue by deepakyds** [cdnjs/cdnjs#5314]
Hello, 
I have an issue with url. When i clicked on menu, it add url after main page url. e.g., i am at home page and when i click on about page it looks like http://127.0.0.1/http://127.0.0.1/wordpress-ydesign/?page_id=8

My site link : http://ydswp.rockdesigning.com/

**Comment by PeterDaveHello** [comment]
Is this an issue of cdnjs?

**Comment by PeterDaveHello** [comment]
Close due to no response.
