### ISSUE TITLE
[Request] Add directorySlider

### ISSUE THREAD

**Issue by jjconti** [cdnjs/cdnjs#5324]
**Library name:** directorySlider
**Git repository url:** https://github.com/justinwhall/directorySlider
**npm package url(optional):** 
**Official homepage:** http://www.justinwhall.com/directory-jquery-slider/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
sorry, the lib's popularity is not fit our request. please read our document  https://github.com/cdnjs/cdnjs/blob/master/README.md

**Comment by Piicksarn** [comment]
@jjconti, thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
And cdnjs need package.json to got the library information.
Would you please make a request again when the library has notable popularity and include package.json? :smiley:

[Consider adding tags for the repo. #4](https://github.com/justinwhall/directorySlider/issues/4)

**Comment by Piicksarn** [comment]
@jjconti, the author's reply shows that the lib does not suit for adding tags, so we can't confirm the versions for the lib. Also, we can not add the lib because of the missing **package.json**.
But anyway, thanks for the suggestion!:thumbsup:
