### ISSUE TITLE
[Request] Upgrade jqModal

### ISSUE THREAD

**Issue by monk-time** [cdnjs/cdnjs#5325]
**Library name:** jqModal
**Git repository url:** https://github.com/briceburg/jqModal
**Official homepage:** http://jquery.iceburg.net/jqModal/
**Wanna say something? Leave message here:** This library is already hosted on cdnjs (https://cdnjs.com/libraries/jqModal, last version from 03/01/2009), but the author changed homepage url and moved to GitHub several years ago. It's still being developed.

**Comment by monk-time** [comment]
Thanks!

There's one more small thing: the link to official homepage is still 404, it should be http://jquery.iceburg.net/jqModal/.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern
