### ISSUE TITLE
[Request] Add bootstrap-table

### ISSUE THREAD

**Issue by dougawa** [cdnjs/cdnjs#5327]
**Library name: bootstrap-table** 
**Git repository url: https://github.com/wenzhixin/bootstrap-table**
**npm package url(optional):** 
**Official homepage: http://wenzhixin.net.cn/p/bootstrap-table/**
**Wanna say something? Leave message here:**
Please upgrade to version 1.8.2. Thank you.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
sorry, but 1.8.1 seems to be the current version, and we have added git auto update in this lib, if there is any update, it will update automatically. thank you.

**Comment by PeterDaveHello** [comment]
There is no v1.8.2
