### ISSUE TITLE
[Request] update amcharts

### ISSUE THREAD

**Issue by accessdev** [cdnjs/cdnjs#5337]
Amcharts
http://www.amcharts.com/javascript-charts/changelog/

3.15.2 is out

**Comment by maruilian11** [comment]
@cdnjs/intern i only find this repo https://github.com/arturgspb/bower-amcharts, but seems not offical.

**Comment by Piicksarn** [comment]
@maruilian11, I think this one is official : https://github.com/bequadrat/amcharts
but i just can not find the version 3.15.2 on git or npm, so i don't update it.

**Comment by maruilian11** [comment]
@accessdev could you please provide the official `git repo url` or `npm package url`? thank you very much!

**Comment by maruilian11** [comment]
@accessdev please **respond in 7 days**, or we'll close this issue. thank you for your contribution.

**Comment by accessdev** [comment]
@maruilian11 here s the response I got from amcharts

---
We currently do not have an official public git repo or an npm package. However, we're working on porting our whole back catalog of JavaScript product versions into a github repo.
When that is up (at some point next week), it will be relatively easy to also produce npm and bower packages.
---

They will notify me when the repo is up so I can inform you . thanks !

**Comment by maruilian11** [comment]
@accessdev ok! thank you!

**Comment by maruilian11** [comment]
@accessdev could you open the issue again when they notify you? thank you for your contribution!

**Comment by maruilian11** [comment]
@accessdev this issue will be closed if there is no any response in next 7 day. thank you!

**Comment by accessdev** [comment]
@maruilian11 here we go ! https://www.amcharts.com/download/ git@github.com:amcharts/amcharts3.git git@github.com:amcharts/amstock3.git git@github.com:amcharts/ammap3.git

**Comment by maruilian11** [comment]
@accessdev thank you!

**Comment by accessdev** [comment]
any ETA ? on this page 3.13.0 is still the latest version available 

http://cdnjs.com/libraries/amcharts

thanks !

**Comment by PeterDaveHello** [comment]
ping @cdnjs/intern

**Comment by PeterDaveHello** [comment]
@cdnjs/intern @cdnjs/intern2 we need to solve this issue ASAP, please join #5747 discussion!
