### ISSUE TITLE
[Request] Add autoNumeric

### ISSUE THREAD

**Issue by alenaifuino** [cdnjs/cdnjs#5338]
**Library name:** autoNumeric
**Git repository url:** https://github.com/BobKnothe/autoNumeric
**npm package url(optional):** 
**Official homepage:** http://www.decorplanit.com/plugin/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@alenaifuino, thanks for your suggestion！
However, the library misses the **`package.json`** in **stable version**.
Would you please make a request again when the library include package.json in stable version?:smiley:

Piicksarn

**Comment by Amomo** [comment]
via e41d7ec65428a64472e48e18c9ec2a7e9c3038b9, cdnjs have `autoNumeric` now, enjoy! 😄
