### ISSUE TITLE
[Request] Add Tagtacular

### ISSUE THREAD

**Issue by burnsbert** [cdnjs/cdnjs#5339]
**Library name:**  tagtacular
**Git repository url:** https://github.com/burnsbert/tagtacular
**npm package url(optional):** 
**Official homepage:** http://gototech.com/tagtacular/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@burnsbert , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library has notable popularity? :smiley:

**Comment by burnsbert** [comment]
Fair enough. Thanks for the quick reply.
