### ISSUE TITLE
[Request] Add jquery.appendGrid

### ISSUE THREAD

**Issue by hkalbertl** [cdnjs/cdnjs#5340]
**Library name:** jquery.appendGrid
**Git repository url:** https://github.com/hkalbertl/jquery.appendGrid
**npm package url(optional):** https://www.npmjs.com/package/jquery.appendgrid
**Official homepage:** https://appendgrid.apphb.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@hkalbertl , thanks for your suggestion！

However, README.md shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Would you please make a request again when the library has notable popularity? :smiley:

**Comment by hkalbertl** [comment]
Oops, sorry that I haven't notice that. I will request again when it has enough stars/watchers :grin:
