### ISSUE TITLE
[Request] Add typed.js

### ISSUE THREAD

**Issue by tatellos** [cdnjs/cdnjs#5347]
**Library name:*Typed.js* 
**Git repository url:*https://github.com/mattboldt/typed.js/*
**npm package url(optional):** 
**Official homepage:*http://www.mattboldt.com/demos/typed-js/*
**Wanna say something? Leave message here:*Would be nice*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@LeaYeh the author has add tags for each version, could send you the PR to add this lib? thank you!

**Comment by maruilian11** [comment]
close fail.

**Comment by PeterDaveHello** [comment]
> close fail.

typo ...

**Comment by maruilian11** [comment]
@PeterDaveHello thank you~
