### ISSUE TITLE
Enhance the version sort in packages.min.js

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5349]
Program:
[build/packages.json.js](https://github.com/cdnjs/cdnjs/blob/master/build/packages.json.js)

Non-stable releases should be earlier then the stable.

For example,
0.13.0 > 0.13.0-rc2 >  0.13.0-rc1 > 0.12.0

Current result is wrong:
![img_20150813_172742](https://cloud.githubusercontent.com/assets/3691490/9246841/01164cb0-41e1-11e5-8199-a7d4a41e267e.jpg)

**Comment by dotnetchris** [comment]
+1
