### ISSUE TITLE
[Request]creative.css 

### ISSUE THREAD

**Issue by nagarjunsanji** [cdnjs/cdnjs#5350]
**Library name: creative.css** 
**Git repository url: https://github.com/nagarjunsanji/blogspot/blob/master/css/lib/creative.css**
**npm package url(optional):** 
**Official homepage: http://nagarjunsanji.blogspot.in/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
sorry, according to our document [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```

we can't add this lib now, please open the issue when the lib repo has notable popularity, package.json, and tags for each version, thank you!

**Comment by maruilian11** [comment]
@nagarjunsanji this issue will be closed due to no response **in 10 days**, thank you for your contribution.
