### ISSUE TITLE
there's a version of mojio-js named "oauth-token"

### ISSUE THREAD

**Issue by slang800** [cdnjs/cdnjs#5372]
Over here: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/mojio-js/oauth-token. Not that I use it or anything, I just noticed while browsing the repo.

Probably caused by this: https://github.com/mojio/mojio-js/releases/tag/oauth-token

**Comment by PeterDaveHello** [comment]
@cdnjs/intern

**Comment by Amomo** [comment]
@PeterDaveHello What could we do for this library? 😯

**Comment by PeterDaveHello** [comment]
You can discuss this issue with your team members.

**Comment by maruilian11** [comment]
@cdnjs/intern though we don't delete files, should we open an issue ask the author about the tag?
(maybe it's a miss or it has different meaning?)
what do you think?

**Comment by PeterDaveHello** [comment]
Seems to be a special case here, I'll consider on remove it.

**Comment by PeterDaveHello** [comment]
Thanks for your report @slang800
