### ISSUE TITLE
[Request] Add  library Unite Gallery 

### ISSUE THREAD

**Issue by profesorfrink** [cdnjs/cdnjs#5373]
**Library name: Unite Gallery** 
**Git repository url: https://github.com/vvvmax/unitegallery/**
**Official homepage: http://unitegallery.net/**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
[Consider adding tags for the repo #18](https://github.com/vvvmax/unitegallery/issues/18)
