### ISSUE TITLE
[Request] ajax.js

### ISSUE THREAD

**Issue by amirleito** [cdnjs/cdnjs#5378]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@amirleito, would you please provide some detail for us to confirm the library?

**Comment by maruilian11** [comment]
@amirleito this issue will be closed due to no response **in 10 days**, thank you for your contribution
