### ISSUE TITLE
[Update] add jquery-countdown git autoupdate

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/cdnjs#5384]
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery-countdown/package.json
this lib do have git repo, but it remain 2.0.1 files in tag 2.0.2, i think we can add git autoupdate after they update them, i'll open issue on their gitHub.

**Comment by swcheon** [comment]
Thank you! @maruilian11

**Comment by maruilian11** [comment]
done.
https://cdnjs.com/libraries/jquery-countdown
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery-countdown/package.json#L24
