### ISSUE TITLE
[Request] commonmarkjs

### ISSUE THREAD

**Issue by duongphuhiep** [cdnjs/cdnjs#5386]
**Library name: commonmarkjs** 
**Git repository url: https://github.com/jgm/commonmark.js**
**npm package url(optional): commonmark** 
**Official homepage: http://commonmark.org**
**the minify version is quite big: > 90 KB, so a CDN is neccessary**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Duplicate of #5385 !
