### ISSUE TITLE
[Request] Add Heir

### ISSUE THREAD

**Issue by shotmonkey** [cdnjs/cdnjs#5387]
Heir
https://github.com/Olical/Heir
From same developer as EventEmitter

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @shotmonkey  , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by maruilian11** [comment]
@shotmonkey this issue will be closed due to no response **in 10 days**, thank you for your contribution
