### ISSUE TITLE
Check if libs moved to GitHub or other platform from Google code

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5420]
Google Code is going to stop service, we should check if the libs on Google Code moved to GitHub or other platform.

For example:

jqplugin 
https://code.google.com/p/jqplugin/
https://cdnjs.com/libraries/jqplugin

See:
http://google-opensource.blogspot.tw/2015/03/farewell-to-google-code.html

**Comment by PeterDaveHello** [comment]
These libs' package.json contains string **code.google** need to be confirmed.
* [ ] casualjs
* [ ] chrome-frame
* [ ] crypto-js
* [ ] dat-gui
* [ ] datejs
* [ ] diff_match_patch
* [ ] galleriffic
* [ ] geo-location-javascript
* [ ] jqplugin
* [ ] jquery-csv
* [ ] jquery-ui-map
* [ ] jquery.fancytree
* [ ] jquery.formset
* [ ] oppia
* [ ] pagedown
* [ ] prettify
* [ ] rangy
* [ ] swfobject
* [ ] webfont

cc @cdnjs/intern

**Comment by Amomo** [comment]
I can take this work~ 🙋

**Comment by Piicksarn** [comment]
@Amomo, i will help you :smiley:

**Comment by maruilian11** [comment]
http://www.chromium.org/developers/how-tos/chrome-frame-getting-started
seems that `chrome-frame` is no longer supported or updated.

**Comment by Amomo** [comment]
THANK U ! @maruilian11 😘😘😘

I get `dat-gui`'s new repo from their site which is write on their Google code
site: http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage
new repo: https://github.com/dataarts/dat.gui

**Comment by PeterDaveHello** [comment]
Hey, let's check the checkbox until we updated the package.json

**Comment by Amomo** [comment]
ok, I will only note url after the project name!

**Comment by maruilian11** [comment]
@PeterDaveHello what about `webfont`?  it has been already on GItHub, too.

**Comment by PeterDaveHello** [comment]
Have you checked its package.json and read my comment in detail @maruilian11 ? I don't think so.

**Comment by Amomo** [comment]
@maruilian11 I think we still need to update the info in package.json.
Like `webfont`, Its homepage in cdnjs's package.json is point to Google Code, but now it has a new url.
https://developers.google.com/fonts/docs/webfont_loader?csw=1

**Comment by Amomo** [comment]
update the list according #5484 #5509 #5510

**Comment by PeterDaveHello** [comment]
:facepunch:

**Comment by Amomo** [comment]
update the list according #5508(prettify) #5512(jquery.formset)

And, jquery.fancytree has corrected by 7f1517b.

**Comment by Piicksarn** [comment]
@cdnjs/intern.
