### ISSUE TITLE
Lack of keywords in lib's package.json

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5422]
There is no `keywords` field in these libs, maybe we can add keywords for them, and **also send feedback to upstream**.

 - [ ] angular-cache
 - [ ] angular-hal
 - [ ] angular-ui-calendar
 - [ ] angular-ui-select
 - [ ] angular-ui-sortable
 - [ ] angular-utf8-base64
 - [ ] antimoderate
 - [ ] Base64
 - [ ] booking-js
 - [ ] bootbox.js
 - [ ] bootstrap-daterangepicker
 - [ ] chaplin
 - [ ] circliful
 - [ ] clappr
 - [ ] depot
 - [ ] device.js
 - [ ] django.js
 - [ ] documentup
 - [ ] dragdealer
 - [ ] dragula
 - [ ] engine.io-client
 - [ ] eve.js
 - [ ] eventable
 - [ ] expect.js
 - [ ] fluidvids.js
 - [ ] formstone
 - [ ] fpsmeter
 - [ ] github-repo-widget
 - [ ] graphiql
 - [ ] grommet-index
 - [ ] gulp
 - [ ] gumshoe
 - [ ] hls.js
 - [ ] instantsearch.js
 - [ ] interpolate.js
 - [ ] jmpress
 - [ ] joyride
 - [ ] jquery-fracs
 - [ ] jquery-mobile-datebox
 - [ ] jquery-overscroll
 - [ ] jquery-scrollpanel
 - [ ] jquery-twinkle
 - [ ] jquery.photocols
 - [ ] jquery.turbolinks
 - [ ] js-data-angular
 - [ ] jstat
 - [ ] knockout-postbox
 - [ ] label.css
 - [ ] Ladda
 - [ ] legojs
 - [ ] linkurious.js
 - [ ] localStorage
 - [ ] lrsjng.jquery-qrcode
 - [ ] midi.js
 - [ ] midnight.js
 - [ ] ng-tasty
 - [ ] oidc-client
 - [ ] outdated-browser
 - [ ] papier
 - [ ] r2d3
 - [ ] ramjet.js
 - [ ] range.js
 - [ ] repo.js
 - [ ] requirejs-plugins
 - [ ] sbt
 - [ ] scaleapp
 - [ ] shaka-player
 - [ ] sigma.js
 - [ ] slidebars
 - [ ] snabbt.js
 - [ ] snackbarjs
 - [ ] social-sharing
 - [x] space
 - [ ] spf
 - [ ] systemjs
 - [ ] templatebinding
 - [ ] terraformer
 - [ ] timezone-js
 - [ ] uswds
 - [ ] vega-lite
 - [ ] vivus
 - [ ] vue-google-maps

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please help @Piicksarn.

**Comment by Amomo** [comment]
:+1:  OK!

**Comment by maruilian11** [comment]
ok

**Comment by Amomo** [comment]
update the list according  #5405 #5471 #5477

**Comment by PeterDaveHello** [comment]
:facepunch:

**Comment by Amomo** [comment]
update the list according #5593

**Comment by Amomo** [comment]
update the list according #5534(ng-table)

**Comment by Piicksarn** [comment]
update the list according to #5718 

  - jquery-maskmoney
  - jquery-smooth-scroll
  - chosen
  - css-spinning-spinners
  - drawer
  - echarts
  - ember-charts
  - ember-computed-reverse
  - es5-shim
  - hopscotch
  - html5-history-api
  - jQuery-viewport-checker
  - jquery-bootpag

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by PeterDaveHello** [comment]
Done in 985ac9e4b78bc237d0a21eae50d447a9fa1fd673, keywords is not required since 985ac9e4b78bc237d0a21eae50d447a9fa1fd673
