### ISSUE TITLE
[Request] Add jQuery AJAX Select

### ISSUE THREAD

**Issue by kevindb** [cdnjs/cdnjs#5431]
**Library name:** jQuery AJAX Select
**Git repository url:** https://github.com/kevindb/jquery-ajax-select

**Comment by Amomo** [comment]
Hi @kevindb , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by kevindb** [comment]
I'm sorry that I didn't RTFM first. Thank you for reviewing my requests.  :-)
