### ISSUE TITLE
[Request] Add d3.chart [author][new]

### ISSUE THREAD

**Issue by iros** [cdnjs/cdnjs#5435]
**Library name:** d3.chart
**Git repository url:** https://github.com/misoproject/d3.chart
**npm package url(optional):** https://www.npmjs.com/package/d3.chart
**Official homepage:** http://misoproject.com/d3-chart/
**Wanna say something? Leave message here:** This is an abstraction layer written to provide a modular pattern around d3.js

**Comment by PeterDaveHello** [comment]
Hi @iros, would you like to send a pull request to add it?

**Comment by iros** [comment]
Just did @PeterDaveHello! Just wanted to have an issue to document it first. See #5436

**Comment by maruilian11** [comment]
the lib has been added by #5436, so i close it.
