### ISSUE TITLE
[Request] Add Simple Line Icons Webfont

### ISSUE THREAD

**Issue by bbirand** [cdnjs/cdnjs#5439]
**Library name:**   Simple Line Icons Webfont
**Git repository url:** http://graphicburger.com/simple-line-icons-webfont/
**npm package url(optional):** 
**Official homepage:** http://graphicburger.com/simple-line-icons-webfont/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@bbirand sorry, you didn't offer a right git repo url. (it should be https://github.com/....)

**Comment by bbirand** [comment]
Sorry, how about this:
https://github.com/thesabbir/simple-line-icons

**Comment by maruilian11** [comment]
sorry for wrong tag
