### ISSUE TITLE
[Request] Add smoothscroll-for-websites

### ISSUE THREAD

**Issue by createdwithlove** [cdnjs/cdnjs#5443]
**Library name:** smoothscroll-for-websites
**Git repository url:** https://github.com/galambalazs/smoothscroll-for-websites
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @createdwithlove  , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by createdwithlove** [comment]
Hi @Amomo, indeed it has not enough stars, but the original git is https://github.com/galambalazs/smoothscroll. It just has moved and didn't gain enough stars in the meantime.
The script is heavily used in a lot themes on themeforest.

**Comment by maruilian11** [comment]
@cdnjs/intern i think @createdwithlove has proved the lib has enough popularity, if you agree, i want open the issue to ask the author if he can add tags for each version and package.json.
what do you think?

**Comment by Piicksarn** [comment]
@maruilian11 :+1:
It's fine to ask author adding tags for the repo:)

**Comment by maruilian11** [comment]
@createdwithlove this issue is duplicated with #5217, we'll still wait for the author adding tags and package.json and try to add this lib on https://cdnjs.com. due to your request issue is later than #5217 we will keep the earlier one and close this issue. thank you for your contribution!
