### ISSUE TITLE
[Request] Add jQuery Markup

### ISSUE THREAD

**Issue by AuspeXeu** [cdnjs/cdnjs#5444]
Library name: jQuery Markup
Git repository url: https://github.com/rse/jquery-markup
npm package url: https://www.npmjs.com/package/jquery-markup
Official homepage: https://plugins.jquery.com/markup/

**Comment by Amomo** [comment]
Hi @AuspeXeu , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by maruilian11** [comment]
@AuspeXeu this issue will be closed due to no response **in 10 days**, thank you for your contribution

**Comment by AuspeXeu** [comment]
@maruilian11 it has been 6 days but okay.

**Comment by maruilian11** [comment]
@AuspeXeu sorry, just a reminding.
