### ISSUE TITLE
Deny all the un-recognized fields in package.json?

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5452]
Maybe we can deny all the fields that we cannot recognize in package.json so that we won't have this problem again?
https://github.com/cdnjs/cdnjs/commit/b435c303c5afe09de042eff3982e5670163c68d5

@cdnjs/intern @cdnjs/team-cdnjs

**Comment by Amomo** [comment]
Sorry for being a bad example 😭
@PeterDaveHello What does "all the fields" mean?
Or, we could list the necessary fields and only use them?

**Comment by PeterDaveHello** [comment]
all the fields that we cannot recognize

**Comment by maruilian11** [comment]
`name`
`version`
`description`
`filename`
`homepage`
`keywords`
`maintainers`
`assets`
`repository`

is there any field recognized i ignore??

**Comment by maruilian11** [comment]
don't we need `main`?

**Comment by PeterDaveHello** [comment]
We don't need main, and you ignored may fields @maruilian11  :smiling_imp:

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by IonicaBizau** [comment]
We should consider this in the next release of cdnjs-importer, too, right? :dizzy:

**Comment by PeterDaveHello** [comment]
yep @IonicaBizau

**Comment by PeterDaveHello** [comment]
cc @petrgazarov
