### ISSUE TITLE
[Request] Validator.js

### ISSUE THREAD

**Issue by danilodeveloper** [cdnjs/cdnjs#5453]
**Library name: Validator.js ** 
**Git repository url: https://github.com/chriso/validator.js **
**npm package url(optional): https://www.npmjs.com/package/validator ** 
**Official homepage: https://github.com/chriso/validator.js **
** Hey dudes, can you update the validator.js library to the last stable version (4.0.5) please? **

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it https://cdnjs.com/libraries/validator.

**Comment by danilodeveloper** [comment]
I know, but take a look at the version, I would like to use the last stable version 4.0.5, cdnjs has only the 3.12.0 version.

**Comment by PeterDaveHello** [comment]
I think you can add a **update** request, by default, we thought you are asking a new lib on cdnjs, anyway, thanks for your report.

@Amomo please take this.

**Comment by danilodeveloper** [comment]
Tks dude! :P
