### ISSUE TITLE
[Request] Add Parallax-JS 

### ISSUE THREAD

**Issue by aelfa** [cdnjs/cdnjs#5457]
Parallax-JS
https://github.com/razorfish/Parallax-JS
http://razorfish.github.com/Parallax-JS

I'm not sure how to add via a pull request, so you might be faster and get it right the first time! 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
There is no any tag or version info so that we can not recognize its version, I'm afraid we can not add this lib until we can confirm its version info.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern

**Comment by aelfa** [comment]
OK - thanks for checking! I'll find another one!

**Comment by PeterDaveHello** [comment]
np
