### ISSUE TITLE
[Security flaw] HTML injection on dynamic list (search)

### ISSUE THREAD

**Issue by Zopieux** [cdnjs/cdnjs#5462]
Steps to reproduce:
- on homepage, [search for `boostrap-select`](https://cdnjs.com/#q=bootstrap-select) using the dynamic search bar

What happens:
- the `bootstrap-select` description begins with `A custom <select> for Bootstrap` wich is rendered with no escaping, so an actual `<select>` element appears and the remaining of the description is dropped! This is an XSS hazard.

What should happend:
- the rendering of this list should be the same as the [full description page](https://cdnjs.com/libraries/bootstrap-select), that is, an escaped HTML text.

**Comment by PeterDaveHello** [comment]
cc @redox

**Comment by redox** [comment]
Yep right, no escaping there but that make total sense. On it!
