### ISSUE TITLE
Testing for PR only

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5469]
I think current test is not good enough, we don't have test on the autoupdate's target/source or the structure consistency between the real files and the autoupdate's filemap.

If we add this test on normal npm test, it'll test on all the libs, it'll be very inefficient, we should have a test to handle the touched lib in PR.

**Comment by petrgazarov** [comment]
I think we can also add `homepage` and `repository.url`, just to be sure they don't contain a typo and are valid urls.

**Comment by petrgazarov** [comment]
What do you think of using `git` to programmatically get the touched libs (diff against master)?

**Comment by PeterDaveHello** [comment]
Actually this issue was fixed via Drone CI with our own testing scripts here: https://github.com/cdnjs/cdnjs-drone-ci, as you can see here: https://ci.cdnjs.com/cdnjs/cdnjs/1724, it'll only checkout the touched libs, so I'm going to close this issue.

About the `npm test` other details, @petrgazarov please feel free to create new issues :) 

BTW: Let's join us on getbadges https://cdnjs-cdnjs.getbadges.io/activity
