### ISSUE TITLE
d3.js 3.5.6 Illegal token on line 1261

### ISSUE THREAD

**Issue by ThreeSevenths** [cdnjs/cdnjs#5473]
Trying to grab d3.js from the cdn and getting some errors in Chrome. It seems to be related to this line:

```
var Îµ = 1e-6, Îµ2 = Îµ * Îµ, Ï€ = Math.PI, Ï„ = 2 * Ï€, Ï„Îµ = Ï„ - Îµ, halfÏ€ = Ï€ / 2, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;
```

**Comment by ThreeSevenths** [comment]
Well, silly me, I didn't check if this is present in the d3 repo, and it is. I believe this is an issue with the content encoding the cdn is serving.

**Comment by PeterDaveHello** [comment]
Do you have an example?

**Comment by maruilian11** [comment]
@ThreeSevenths please respond in 7 days, or we'll close this issue. thank you for your contribution.

**Comment by ThreeSevenths** [comment]
Sorry, I do have an example, but I was able to find this in the original d3 repo, so it's not specifically a bug with cdnjs. I think this should be closed since there really isn't a problem here other than the original sources.

Thanks!
