### ISSUE TITLE
Support fix package.json format on certain lib

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5476]
Feature of [fixFormat.js](https://github.com/cdnjs/cdnjs/blob/master/tools/fixFormat.js).

So that the whole progress will be faster if we already know a certain target.

**Comment by maruilian11** [comment]
got it.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/intern2 @petrgazarov

**Comment by sashberd** [comment]
@PeterDaveHello Is there any documentation to update with the change in fixtool.js that I want to send right now?

**Comment by PeterDaveHello** [comment]
@sashberd nope, only the source code.
