### ISSUE TITLE
kfxray13

### ISSUE THREAD

**Issue by kfxray13** [cdnjs/cdnjs#5496]
**Library name:kfxray13** 
**Git repository url:https://github.com/kfxray13/kfxray13.git**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
Please provide official git repository url, thank you!

**Comment by kfxray13** [comment]
https://github.com/kfxray13/kfxray13.git

On Tue, Aug 25, 2015 at 6:42 AM, Una Ma <notifications@github.com> wrote:

> Please provide official git repository url, thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/cdnjs/issues/5496#issuecomment-134449638>.
>



-- 
http://kfxray13.blogfa.com/
