### ISSUE TITLE
[Request]kfxray13

### ISSUE THREAD

**Issue by kfxray13** [cdnjs/cdnjs#5497]
**Library name:kfxray13** 
**Git repository url:https://github.com/kfxray13/kfxray13.git**
**npm package url(optional):** 
**Official homepage:http://kfxray13.blogfa.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@kfxray13, the git repository above is empty!

**Comment by Piicksarn** [comment]
@kfxray13, the issue will be closed for no respond after 7 days.
