### ISSUE TITLE
[Request] Add np-autocomplete

### ISSUE THREAD

**Issue by raeef-refai** [cdnjs/cdnjs#5499]
**np-autocomplete** 
**https://github.com/ng-pros/np-autocomplete.git**
**http://ng-pros.github.io/np-autocomplete/index.html**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@raeef-refai, thanks for your suggestion！

However, [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```

Would you please make a request again when the library has notable popularity? :smiley:

**Comment by maruilian11** [comment]
@raeef-refai we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution. 
this issue will be closed **in 10 days* due to no response. thank you!

**Comment by raeef-refai** [comment]
Will do, thanks.
