### ISSUE TITLE
Add missing license field in libs' package.json 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5500]
cc #5194, https://github.com/cdnjs/new-website/issues/66

Should be care of the libs with multiple licenses, especially the libs have commercial license. 
 - [ ] 1140
 - [x] across-tabs
 - [ ] animations
 - [ ] boexfi
 - [x] browser-logos
 - [ ] chrome-frame
 - [x] cryptico
 - [x] davis.js
 - [x] DinaKit
 - [x] documentup
 - [x] entypo
 - [x] expect.js
 - [x] flipCounter
 - [x] foundicons
 - [x] galleriffic
 - [x] gsap
 - [ ] jcalculator
 - [x] jquery-hashchange
 - [x] jquery-outside-events
 - [x] jquery-parallax
 - [x] jquery-sparklines
 - [x] jquery-tools
 - [x] jquery.activity-indicator
 - [x] jquery.formalize
 - [x] jquery.lifestream
 - [x] jquery.percentageloader
 - [x] jquery.postcodify
 - [x] jquery.selectboxit
 - [x] jquery.socialshareprivacy
 - [x] jquery.tiptip
 - [x] json2
 - [x] legojs
 - [x] linq.js
 - [x] log4javascript
 - [ ] luminateExtend
 - [x] meyer-reset
 - [ ] mojio-js
 - [x] openajax-hub
 - [x] PKI.js
 - [x] polyglot
 - [x] prettydiff
 - [ ] probtn
 - [x] prototype
 - [x] protovis
 - [x] react-chartjs-2
 - [x] repo.js
 - [x] require-cs
 - [x] require-jquery
 - [x] roundabout
 - [x] salesforce-canvas
 - [x] script.js
 - [x] simplecartjs
 - [x] skel-layers
 - [x] skycons
 - [x] slabText
 - [x] thorax
 - [x] Vague.js
 - [ ] webicons

**Comment by Amomo** [comment]
update the list according #5509 #5484

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by LeaYeh** [comment]
update the list according #5561 #5560 #5559 #5558 #5582 #5583

**Comment by Amomo** [comment]
@LeaYeh you couldn't mark the libraries if its modified PR hasn't been merged! 😫

**Comment by PeterDaveHello** [comment]
@Amomo is correct ...

**Comment by LeaYeh** [comment]
RRRRRRRR
sorry for that.

**Comment by bbrala** [comment]
I will change the license to MIT for jquery.contextMenu because that seems be incistent throughout the files anyway.

**Comment by PeterDaveHello** [comment]
@bbrala I updated it in https://github.com/cdnjs/cdnjs/commit/c8210fe337dfb2b58031220b6ddb847975113c3f

**Comment by Amomo** [comment]
update the list according 
- #5608 backbone-super
- #5622 backbone-tastypie
- #5628 highcharts
- #5633 highstock
- c8210fe jquery-contextmenu

**Comment by LeaYeh** [comment]
update the list according
  - #5724 
  - #5738 
  - #5742 
  - #5758 
  - #5762 
  - #5798 
  - #5811 
  - #5826

**Comment by PeterDaveHello** [comment]
I'll take this ... take too long time on it.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please help me update the list, thanks.

**Comment by LeaYeh** [comment]
updated list by https://github.com/cdnjs/cdnjs/commit/d0935dabf7069a8c693c02e99dcbf1f42bbfdd5f

**Comment by PeterDaveHello** [comment]
Re-assign to @LeaYeh.

**Comment by PeterDaveHello** [comment]
@LeaYeh can we have a schedule on this? Maybe before the end of 2015?

**Comment by PeterDaveHello** [comment]
@LeaYeh can we have a schedule on this?

**Comment by LeaYeh** [comment]
updated list because these repo already had licence info
- arbor
- bitcoinjs-lib
- bonsai
- bootstrap-social
- chaplin

**Comment by clairetsai818** [comment]
1140

**Comment by clairetsai818** [comment]
tv4

**Comment by clairetsai818** [comment]
libil

**Comment by sufuf3** [comment]
dragdealer

**Comment by sufuf3** [comment]
jquery-textext

**Comment by qwe19272375** [comment]
datejs

**Comment by lcd78706** [comment]
dragdealer

**Comment by lcd78706** [comment]
require-css

**Comment by kiwi89** [comment]
jquery-te

**Comment by lcd78706** [comment]
html5shiv

**Comment by lcd78706** [comment]
mycolorway-simple-hotkeys

**Comment by jj528s35** [comment]
ng-clip

**Comment by honestree** [comment]
add license of hiw-api

**Comment by clairetsai818** [comment]
placeholders

**Comment by clairetsai818** [comment]
s3colors

**Comment by clairetsai818** [comment]
klass

**Comment by NiniHsu** [comment]
shred

**Comment by NiniHsu** [comment]
joopl

**Comment by jj528s35** [comment]
stylus

**Comment by nolsherry** [comment]
slidesjs

**Comment by clairetsai818** [comment]
humane-js

**Comment by clairetsai818** [comment]
requirejs-async

**Comment by clairetsai818** [comment]
easyXDM

**Comment by clairetsai818** [comment]
radio

**Comment by clairetsai818** [comment]
s3colors

**Comment by lcd78706** [comment]
treesaver

**Comment by lcd78706** [comment]
swfobject

**Comment by NiniHsu** [comment]
dd_belatedpng

**Comment by NiniHsu** [comment]
diff_match_patch

**Comment by hare1039** [comment]
ext-core

**Comment by clairetsai818** [comment]
jquery.formalize

**Comment by lcd78706** [comment]
r2d3

**Comment by lcd78706** [comment]
jqueryui-touch-punch

**Comment by clairetsai818** [comment]
jquery-outside-events

**Comment by honestree** [comment]
adding license of polymaps

**Comment by lcd78706** [comment]
money.js

**Comment by clairetsai818** [comment]
dragdealer

**Comment by clairetsai818** [comment]
jquery-hashchange

**Comment by clairetsai818** [comment]
jquery-replace-text

**Comment by clairetsai818** [comment]
jquery-throttle-debounce

**Comment by clairetsai818** [comment]
jquery.atmosphere

**Comment by clairetsai818** [comment]
jquery-bbq

**Comment by lcd78706** [comment]
helium-css

**Comment by NiniHsu** [comment]
jquery-gamequery

**Comment by NiniHsu** [comment]
jquery-history

**Comment by clairetsai818** [comment]
jquery.fileDownload

**Comment by lcd78706** [comment]
jeditable.js

**Comment by clairetsai818** [comment]
jquery.finderselect

**Comment by clairetsai818** [comment]
jquery.spritely

**Comment by clairetsai818** [comment]
jschannel

**Comment by lcd78706** [comment]
foonav

**Comment by qwe19272375** [comment]
path.js

**Comment by qwe19272375** [comment]
kiwi

**Comment by NiniHsu** [comment]
jquery-resize

**Comment by coderbounty-cowboy** [comment]
May want to consider putting a bounty on this issue at www.coderbounty.com

**Comment by hare1039** [comment]
LAB.js

**Comment by honestree** [comment]
add-license of reactive-coffee

**Comment by sashberd** [comment]
@PeterDaveHello Hi man
I made some work on referenced above libraries, here result.
Can I make one PR for all changes that I made or I should do one by one 😨 
[license-update.txt](https://github.com/cdnjs/cdnjs/files/1299495/license-update.txt)
