### ISSUE TITLE
[Request] Add dimple

### ISSUE THREAD

**Issue by ianguerin** [cdnjs/cdnjs#5503]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@ianguerin, would you please provide **git repository url** or **npm package url**?

Thank you
Piicksarn

**Comment by ianguerin** [comment]
@Piicksarn Yep. Sorry!

http://dimplejs.org/dist/dimple.v2.1.6.min.js

**Comment by ianguerin** [comment]
@Piicksarn 
Yep! Sorry!
https://github.com/PMSI-AlignAlytics/dimple

**Comment by maruilian11** [comment]
@cdnjs/intern i think in this case, we just need to add `dimple.latest.js` and `dimple.latest.min.js`

**Comment by Amomo** [comment]
agree. :+1:
