### ISSUE TITLE
[Request] Add ngsecurity

### ISSUE THREAD

**Issue by patrickporto** [cdnjs/cdnjs#5504]
**Library name:** ngsecurity
**Git repository url:** https://github.com/concretesolutions/ng-security
**npm package url(optional):** https://www.npmjs.com/package/ngsecurity
**Official homepage:** https://github.com/concretesolutions/ng-security

**Comment by maruilian11** [comment]
@patrickporto sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
