### ISSUE TITLE
add jQuery-contextMenu git autoupdate

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/cdnjs#5505]
https://github.com/swisnl/jQuery-contextMenu

**Comment by bbrala** [comment]
Hi,

Im the author of this plugin and i updated the plugin to have a dist folder with minified assets. This might make the update progress a bit easier for you guys?

https://github.com/swisnl/jQuery-contextMenu/tree/master/dist

**Comment by PeterDaveHello** [comment]
Thanks a lot @bbrala

**Comment by bbrala** [comment]
New release is up with dist folder. Not sure if you need to change anything.

**Comment by PeterDaveHello** [comment]
I'll check it later.
