### ISSUE TITLE
[Request] Add autoNumeric

### ISSUE THREAD

**Issue by th3uiguy** [cdnjs/cdnjs#5515]
**Library name:** autoNumeric
**Git repository url:** https://github.com/BobKnothe/autoNumeric
**npm package url(optional):** 
**Official homepage:** http://www.decorplanit.com/plugin/
**Wanna say something? Leave message here:** autoNumeric is a jQuery plugin that automatically formats currency and numbers as you type on form inputs.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Duplicate with #5338
