### ISSUE TITLE
[Request] Bootstrap-Confirmation

### ISSUE THREAD

**Issue by chaodongyue** [cdnjs/cdnjs#5519]
**Library name:** Bootstrap-Confirmation
**Git repository url:**https://github.com/mistic100/Bootstrap-Confirmation
**npm package url(optional):** http://badge.fury.io/bo/bootstrap-confirmation2
**Official homepage:**http://mistic100.github.io/Bootstrap-Confirmation/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@chaodongyue sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by chaodongyue** [comment]
@maruilian11 sorry my english is pull,but i very like this lib

**Comment by PeterDaveHello** [comment]
Another problem, this lib is a forked of a forked lib, make confuse people and conflict with their name, we need to discuss the policy about this situation.
