### ISSUE TITLE
Use git auto-update on highcharts

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5525]
Not sure if this repo - https://github.com/highslide-software/highcharts-release fits highcharts

https://cdnjs.com/libraries/highcharts

**Comment by PeterDaveHello** [comment]
highmaps:
https://github.com/highslide-software/highmaps-release

highstock:
https://github.com/highslide-software/highstock-release

**Comment by Amomo** [comment]
We have add git auto-update config in these library.
