### ISSUE TITLE
[Request] Add PykCharts.js

### ISSUE THREAD

**Issue by samsch** [cdnjs/cdnjs#5526]
**Library name:** PykCharts.js
**Git repository url:**https://github.com/pykih/PykCharts.js
**npm package url(optional):** 
**Official homepage:** http://pykcharts.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @samsch , could please add tag (if it is your project) or ask the author to add tags that we can add auto update config.

**Comment by PeterDaveHello** [comment]
Obviously @samsch is not the author, https://github.com/pykih/PykCharts.js/graphs/contributors
I think you can help us ask the tags as @Piicksarn and @maruilian11 did.

**Comment by LeaYeh** [comment]
@PeterDaveHello samsch have asked author for tags as [issue](https://github.com/pykih/PykCharts.js/issues/15)

**Comment by PeterDaveHello** [comment]
Nice.

**Comment by maruilian11** [comment]
@pykih could you please consider adding tags for each version? thank you very much!

**Comment by maruilian11** [comment]
@PeterDaveHello seems no response for a month. how can we do for this issue?

**Comment by PeterDaveHello** [comment]
Maybe write an email first?

https://github.com/pykih/PykCharts.js#support

**Comment by maruilian11** [comment]
@PeterDaveHello sent.

**Comment by maruilian11** [comment]
@PeterDaveHello  there is still no any response.

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Suggest to close due to passed to much time since the request was opened and request to add git tags was sent to author.

**Comment by samsch** [comment]
The repo for PykCharts.js is gone now.
