### ISSUE TITLE
git auto update for marked

### ISSUE THREAD

**Issue by smarts** [cdnjs/cdnjs#5527]
I wan to open a pull request to update [marked](//github.com/chjj/marked), but right now cdnjs is several versions behind the current version. For example, let's say the version in cdnjs is 5, and the latest version is 9. If I add autoupdate *and* change the package version to 6, will auto-update pull in version 6 and then continue on to pull 7, 8, and 9 into cdnjs? That's what I would like to happen. Or would I need to manually pull in all the versions that are not in cdnjs and then configure auto update?

**Comment by maruilian11** [comment]
@smarts yes, it will autoupdate to 9 if they all be tagged. the package.json will update to the latest one, so welcome to send the pull request.

**Comment by smarts** [comment]
@PeterDaveHello volunteered to do this.
