### ISSUE TITLE
[Request] jqueryrotate

### ISSUE THREAD

**Issue by jonny5v** [cdnjs/cdnjs#5528]
**Library name: Jquery Rotate** 
**Git repository url: https://github.com/wilq32/jqueryrotate**
**npm package url(optional):** 
**Official homepage: http://jqueryrotate.com/**
**Wanna say something? Leave message here:**
Please!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @jonny5v , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by maruilian11** [comment]
@jonny5v we suggest you open a issue again when the repo has notable popularity.·
this issue will be closed **in 7 days** due to no response. thank you for your contribution.
