### ISSUE TITLE
[Request] elevator.js

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5529]
Repo: https://github.com/tholman/elevator.js

**Comment by maruilian11** [comment]
@PeterDaveHello seem that the author doesn't want to add package.json or tags yet. do we need to close this issue?

**Comment by PeterDaveHello** [comment]
Any reference?

**Comment by maruilian11** [comment]
@PeterDaveHello https://github.com/tholman/elevator.js/issues/97

**Comment by PeterDaveHello** [comment]
Okay, thanks.
