### ISSUE TITLE
[Request] Add typed-js

### ISSUE THREAD

**Issue by joshhopkins** [cdnjs/cdnjs#5530]
typed-js
https://github.com/mattboldt/typed.js/
http://www.mattboldt.com/demos/typed-js/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
hmmmm ... seems it's version/tag didn't been updated for a long time.

**Comment by maruilian11** [comment]
sorry, it is duplicated with #5347. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
add ` Duplicate` tag before we close it next time. cc @cdnjs/intern

**Comment by Amomo** [comment]
ok.
