### ISSUE TITLE
Size issue in CI

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5538]
Got error due to repo size, see: https://circleci.com/gh/cdnjs/cdnjs/3938
Should use a smart sparse-checkout mechanism in it.

**Comment by PeterDaveHello** [comment]
hmmmm .... it's good now, see: https://circleci.com/gh/cdnjs/cdnjs/3941, strange, I didn't do anything ...

**Comment by PeterDaveHello** [comment]
but we still need a smart sparse-checkout mechanism in it.

**Comment by Amomo** [comment]
`No space left on device`
I have met this problem many times!
However, If I re-send my commit, it might pass (or get "No space left on device" again).

**Comment by PeterDaveHello** [comment]
Keep getting this problem, cc @cdnjs/team-cdnjs @cdnjs/intern
((https://circleci.com/gh/cdnjs/cdnjs/4047

**Comment by PeterDaveHello** [comment]
Asked for help.
Wondering if circleci can support sparse-checkout.

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by xtuc** [comment]
CI is going to be rewriten and will avoid that issue
