### ISSUE TITLE
Un-recognized license(s) field by SPDX license identifier

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5544]
Here are the libs with license(s) field but can not been recognized by SPDX license identifier([1](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json), [2](https://spdx.org/licenses/)), we need to confirm their license(s) and try to use use a clean and clear SPDX license identifier recognized identifier in package.json.

cc #5543 @cdnjs/intern 

Library name / current license(s) field:
- [x] ScrollMagic  :  GPL-3.0+
- [x] UAParser.js  :  GPLv2
- [x] WebRupee  :  Apache License, Version 2.0
- [x] balance-text  :  Apache License, Version 2.0
- [x] bootstrap-rtl  :  Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
- [x] chainvas  :  none
- [x] crafty  :  MIT
- [x] d3-geo-projection  :  BSD
- [x] datatables-colvis  :  MIT
- [x] datatables-fixedheader  :  MIT
- [x] datatables-tabletools  :  MIT
- [x] django.js  :  LGPL 3
- [x] dojo  :  AFLv2.1
- [x] dojo  :  BSD
- [ ] ekko-lightbox  :  MIT
- [ ] embedly-jquery  :  BSD-3-Clause
- [ ] emojione  :  (CC-BY-SA-4.0 and MIT)
- [ ] equalize.js  :  GPLv2
- [ ] evil.js  :  Public Domain
- [ ] extjs  :  GNU General Public License Version 3
- [ ] extjs  :  Open Source License Exception for Applications
- [ ] extjs  :  Open Source License Exception for Development
- [ ] froala-editor  :  CC
- [ ] froala-editor  :  Single Website
- [ ] froala-editor  :  Developer
- [ ] froala-editor  :  Business
- [ ] froala-editor  :  OEM
- [ ] geoext  :  BSD
- [x] highmaps  :  Creative Commons Attribution-NonCommercial 3.0 License.
- [x] ice  :  GPLv2
- [ ] intercom.js  :  Apache
- [x] ixjs  :  Apache License, Version 2.0
- [x] jQuery-slimScroll  :  GPL & MIT
- [x] jQuery.dotdotdot  :  MIT
- [ ] jo  :  Redistribution
- [ ] jqPlot  :  GPL
- [ ] jquery-form-validator  :  Dual licensed under the MIT or GPL Version 2 licenses
- [ ] jquery-mockjax  :  GPLv2
- [x] jquery-smart-web-app-banner  :  Apache License, 2.0
- [ ] jquery.blockUI  :  GPL
- [ ] jquery.collapsible  :  BSD
- [ ] jquery.form  :  GPL
- [ ] jquery.mb.YTPlayer  :  GPL
- [ ] jquery.tablesorter  :  GPL
- [x] jsoneditor  :  Apache License 2.0
- [x] jsonld  :  BSD
- [x] l20n  :  Apache 2.0
- [ ] machina.js  :  GPL
- [ ] mixitup  :  Creative Commons Attribution-NoDerivs 3.0 Unported
- [x] mobilizejs  :  Creative Commons
- [x] msl-client-browser  :  Apache 2.0
- [x] noti.js  :  GNU GPL v2
- [ ] placeholder-shiv  :  BSD
- [x] plupload  :  GPLv2
- [x] plupload  :  Single Website
- [x] plupload  :  OEM
- [x] plupload  :  Custom Licensing
- [x] postal.js  :  GPL
- [ ] qoopido.js  :  GPL
- [x] qtip2  :  GPL
- [x] remoteStorage  :  AGPL
- [x] rxjs-dom  :  Apache License, Version 2.0
- [x] rxjs-jquery  :  Apache License, Version 2.0
- [x] rxjs  :  Apache License, Version 2.0
- [x] sbt  :  Apache 2.0
- [x] showdown  :  BSD
- [x] speakingurl  :  BSD
- [x] spectrum-i18n  :  MIT
- [x] tagmanager  :  MPL
- [x] ui-selectableScroll  :  GPLv3
- [ ] webkit.js  :  BSD
- [x] yamlcss  :  CC

**Comment by Amomo** [comment]
update the list according

- #5690 datatables-colvis : change to MIT
- #5632 highmaps

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by Amomo** [comment]
update the list

- WebRupee
- balance-text
- dojo
- ice
- ixjs
- jquery-smart-web-app-banner
- jsoneditor
- l20n
- msl-client-browser
- noti.js
- rxjs-dom
- rxjs-jquery
- rxjs
- sbt
- ui-selectableScroll

were updated via 1ecf99ca2a9dc4f39952057c717b80ca0e105c5e

**Comment by PeterDaveHello** [comment]
Nice.

**Comment by Amomo** [comment]
jsonld was updated via 8c4e724cb6d80fa7b61dffdb14680e134ddddb9f

**Comment by Amomo** [comment]
- postal.js 

was updated via 62f4bffa216ff0c88abc8fe318c9803a03566579
