### ISSUE TITLE
[Request] Add elemental

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5545]
repo: https://github.com/elementalui/elemental
website: http://elemental-ui.com/

No dist file in the repo yet.

**Comment by Amomo** [comment]
https://github.com/elementalui/elemental/issues/49

**Comment by Amomo** [comment]
The author has replied that
```
There is a repo elemental-dist which has precompiled sources.
```
https://github.com/elementalui/elemental-dist
