### ISSUE TITLE
[Request] jassor slider cdn

### ISSUE THREAD

**Issue by ranaimagine** [cdnjs/cdnjs#5563]
**Library name: jassor slider** 
**Git repository url:**
**npm package url(optional):** 
**Official homepage:http://www.jssor.com**
**jQuery Image Slider/Slideshow/Carousel/Gallery Bootstrap+html+javascript TOUCH SWIPE & Responsive**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@ranaimagine could you please provide the official git repo url? thank you very much!

**Comment by maruilian11** [comment]
@ranaimagine this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
https://github.com/jssor/slider
