### ISSUE TITLE
SALESFORCE LIGHTING DESIGN SYSTEM

### ISSUE THREAD

**Issue by mailtoharshit** [cdnjs/cdnjs#5565]
**Library name:*SALESFORCE LIGHTING DESIGN SYSTEM* 
**Git repository url:*http://www.lightningdesignsystem.com/resources/downloads#role=regular&status=all&#38;status=all*
**npm package url(optional):** 
**Official homepage:*http://www.lightningdesignsystem.com*
**Wanna say something? Leave message here:**
Powerful lighting design system UI framework by Salesforce to make business applications

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@mailtoharshit could you please provide us the offical git repo url? thank you very much!

**Comment by maruilian11** [comment]
we are trying to add this lib in https://github.com/cdnjs/cdnjs/issues/6573
thank you!
