### ISSUE TITLE
[Request] audiojs

### ISSUE THREAD

**Issue by 365studiosdesign** [cdnjs/cdnjs#5566]
**Library name:audio.js** 
**Git repository url:https://github.com/kolber/audiojs**
**npm package url(optional):** 
**Official homepage:http://kolber.github.io/audiojs/**
**Wanna say something? Leave message here:Thank you for providing the ASBOLUTE BEST cdn service available!**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@kolber could you please add tags so that we can add this lib with **git auto-update**.

**Comment by Zetaphor** [comment]
I have added tags to kolber/audiojs and will continue to do so with new updates

**Comment by maruilian11** [comment]
audiojs has been added!
https://github.com/cdnjs/cdnjs/pull/7230
