### ISSUE TITLE
What is the reason status is 0 when cdnjs resources are loaded via XMLHttpRequest 

### ISSUE THREAD

**Issue by hugovart** [cdnjs/cdnjs#5572]
It has to be related to CORS settings more specifically Access-Control-Allow-Origin header, but I could not solve the mystery. I have set up a couple of cdnjs libraries as a dependency in my project. The scripts are loaded via `XMLHttpRequest`.

For about %0.2 of cdnjs requests fails with status `0`.

What could be the reason?

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by MattIPv4** [comment]
No further progress, closing.
