### ISSUE TITLE
autoNumeric

### ISSUE THREAD

**Issue by BobKnothe** [cdnjs/cdnjs#5573]
autoNumeric.js
https://github.com/BobKnothe/autoNumeric
https://www.npmjs.com/package/autonumeric
The MIT License (http://www.opensource.org/licenses/mit-license.php)
http://www.decorplanit.com/plugin/
**I have had a few users request that I add my script - please let me know if I need to take any actions - thanks**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @BobKnothe, I think the git tags of version 1.9.31~1.9.39 were missing, so I can only add to v1.9.30, would you please add the missing tags for version 1.9.31~1.9.39? Thanks!

**Comment by BobKnothe** [comment]
Thanks - out office for a couple days

 
Robert (Bob) Knothe
