### ISSUE TITLE
[Request] Add lodash-fp 

### ISSUE THREAD

**Issue by Nieralyte** [cdnjs/cdnjs#5576]
**Library name:** lodash-fp
**Git repository url:** http://github.com/lodash/lodash-fp
**npm package url:** http://npmjs.com/package/lodash-fp
**License(s):** MIT
**Official homepage:** http://lodash.com/#formats

**Comment by jdalton** [comment]
Cross post with https://github.com/jsdelivr/jsdelivr/issues/6637.
