### ISSUE TITLE
[Request] Add Ajaxis

### ISSUE THREAD

**Issue by amranidev** [cdnjs/cdnjs#5577]
**Library name:*Ajaxis* 
**Git repository url:*https://github.com/amranidev/AjaxisMaterialize*
**npm package url(optional):** 
**License(s):*MIT*
**Official homepage:*https://github.com/amranidev/ajaxis*
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@amranidev sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

**Comment by maruilian11** [comment]
@amranidev this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
