### ISSUE TITLE
[Request] Add wimbarelds/TimeCircles

### ISSUE THREAD

**Issue by jesstokes** [cdnjs/cdnjs#5586]
wimbarelds/TimeCircles
https://github.com/wimbarelds/TimeCircles.git
http://git.wimbarelds.nl/TimeCircles/readme.php
The MIT License (MIT): https://github.com/wimbarelds/TimeCircles/blob/master/MIT.txt

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
as TimeCircles was added, close this issue.
