### ISSUE TITLE
Force pushes to this repository

### ISSUE THREAD

**Issue by valhallasw** [cdnjs/cdnjs#5587]
Hello,

On our webserver, we git pull from this repository regularly to update. However, it has happened multiple times in the recent past the pull failed because of a merge conflict. Typically, this is caused by an earlier merge, which was triggered by a force push to the cdnjs repository.

The most recent example is a merge commit between 5f6783e and 166920a:
```
valhallasw@tools-web-static-01:/srv/cdnjs$ git log --graph 0aaf115 --pretty=format:'%h %ad %s (%an)' | head -n 15
*   0aaf115 Sat Aug 29 16:11:57 2015 +0000 Merge branch 'master' of https://github.com/cdnjs/cdnjs (valhallasw)
|\
| * 166920a Sun Aug 30 00:08:16 2015 +0800 add angular-formly v6.24.21~6.24.23 (Peter Dave Hello)
| * ab8ad8c Sun Aug 30 00:08:03 2015 +0800 add vega v2.2.1 (Peter Dave Hello)
| * 6a811d5 Sun Aug 30 00:07:54 2015 +0800 add localforage v1.2.10 (Peter Dave Hello)
| * fc9852f Sun Aug 30 00:07:40 2015 +0800 add core-js v1.1.3 (Peter Dave Hello)
* |   5f6783e Sat Aug 29 18:30:35 2015 +1000 Merge pull request #5533 from maruilian11/angular-bacon (Drew Freyling)
|\ \
| |/
|/|
| * 21d005f Fri Aug 28 20:43:32 2015 +0800 add angular-bacon v2.0.0 with git auto-update (maruilian11)
* | 3d3b6c2 Sat Aug 29 13:01:28 2015 +0800 add angular-i18n v1.4.5 (Peter Dave Hello)
```

Note that both commits are in the repository according to github -- but only the latter is on branch master. This suggests 5f6783e was first pushed to the repository, then 166920a was force-pushed over it. Angular-bacon was added later with PR #5540 (rather than the original #5533).

And earlier example is 1e392ab being overwritten by fc918b8:
```
valhallasw@tools-web-static-01:/srv/cdnjs$ git log --graph 57994c --pretty=format:'%h %ad %s (%an)' | head -n 15
*   57994ce Sat Jul 25 15:42:37 2015 +0000 Merge branch 'master' of https://github.com/cdnjs/cdnjs (valhallasw)
|\
| * fc918b8 Thu Jul 23 17:22:38 2015 +0800 add flux v2.0.3 with git autoupdate, close #5080 (maruilian11)
| * 8bb9656 Sat Jul 25 23:38:03 2015 +0800 bump dependency - async to ~1.4 (Peter Dave Hello)
| * ad1c885 Sat Jul 25 23:12:49 2015 +0800 add old versions of angular-highlightjs (Peter Dave Hello)
| * 7e2e310 Sat Jul 25 22:27:18 2015 +0800 add angular-highlightjs@0.4.1 with git auto-update (pc035860)
* |   1e392ab Sat Jul 25 23:07:42 2015 +0800 Merge pull request #5110 from pc035860/angular-highlightjs (Peter Dave Hello)
|\ \
| |/
|/|
| * 735e9bb Sat Jul 25 22:27:18 2015 +0800 add angular-highlightjs@0.4.1 with git auto-update (pc035860)
* | ec74781 Sat Jul 25 22:43:28 2015 +0800 add amazeui-react with git auto-update (Peter Dave Hello)
```

Both examples involve a pull request, so I'm not sure if this is a bug in github or just a manual git push.

**Comment by PeterDaveHello** [comment]
Hi @valhallasw, sorry about that, sometimes we use force push to override the wrong things.

**Comment by valhallasw** [comment]
I see. It's advised against (exactly because it causes these kinds of issues for people tracking the repository). If you feel the alternative (git revert) is too cumbersome, could you add a note in the readme so people are aware of it?

Thanks, and of course thank you for all the work you put into cdnjs!

**Comment by PeterDaveHello** [comment]
I am sorry about that, would you like to try `--force` with pull? Thanks.

**Comment by PeterDaveHello** [comment]
See this:
https://stackoverflow.com/questions/1125968/force-git-to-overwrite-local-files-on-pull
