### ISSUE TITLE
[Request] Add wNumb - JavaScript Number & Money formatting

### ISSUE THREAD

**Issue by alanbuchanan** [cdnjs/cdnjs#5589]
**Library name:** wNumb - JavaScript Number & Money formatting
**Git repository url:** https://github.com/leongersen/wnumb

**License(s):** WTFPL
**Official homepage:** http://refreshless.com/wnumb/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @alanbuchanan  , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by maruilian11** [comment]
@alanbuchanan this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
