### ISSUE TITLE
[Request] bootstrap-show-password

### ISSUE THREAD

**Issue by etondolittle** [cdnjs/cdnjs#5590]
**Library name:** bootstrap-show-password
**Git repository url:** https://github.com/wenzhixin/bootstrap-show-password
**npm package url(optional):** https://www.npmjs.com/package/bootstrap-show-password
**License(s):** MIT ??
**Official homepage:** https://github.com/wenzhixin/bootstrap-show-password
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@etondolittle sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@etondolittle this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
I think the watcher + fork + star is pretty enough.

**Comment by PeterDaveHello** [comment]
@LeaYeh please take this.
