### ISSUE TITLE
[Request] add font hack & codeface

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5598]
These two fonts looks great!
https://github.com/chrissimpkins/Hack
https://github.com/chrissimpkins/codeface

@chrissimpkins Would you please help us add it on cdnjs? I'm not sure what files we need actually, thanks!

**Comment by chrissimpkins** [comment]
Happy to Peter.  I am assuming that you would like to host the webfonts.  Are you ok with all of the webfont files?  It will be svg, eot, ttf, woff, and woff2 font builds along with the CSS sheet so that users can import the font.

**Comment by PeterDaveHello** [comment]
Yes, and it'll be good if we can apply the auto-update mechanism on it!

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs#enabling-gitrecommended-or-npm-auto-update

**Comment by PeterDaveHello** [comment]
And we'll need a package.json like this:

```js
{
  "name": "jquery",
  "filename": "svg/hack-regular-webfont.svg",
  "version": "0.0.0",
  "description": "A typeface designed for source code",
  "homepage": "http://sourcefoundry.org/hack/",
  "keywords": [
   "hack",
   "font",
   "code",
   "typeface",
   "web"
  ],
  "repository":
  {
    "type": "git",
    "url": "https://github.com/jquery/jquery.git"
  },
}
```

**Comment by PeterDaveHello** [comment]
If you would like to send a PR on cdnjs as a contributor, I'll respectfully suggest you to use [sparse-checkout] (https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md), so that you won't face the disk space usage issue and performance issue.

**Comment by chrissimpkins** [comment]
I am pushing a Hack typeface bug fix this week and will submit the PR to you over the weekend.  Thanks much for the information and for the invitation to host the files on cdnjs.

Codeface is a repository of multiple typefaces from multiple designers/developers.  The ones in the repository are targeted to the desktop.  You would have to contact the typeface designers directly about the availability of web fonts for these faces.  The web fonts (if available) are not hosted on Codeface.

**Comment by chrissimpkins** [comment]
Also, is there a standard format for font naming on cdnjs?

**Comment by PeterDaveHello** [comment]
Nope, you can name it Hack-font or font-hack I think?

**Comment by chrissimpkins** [comment]
OK will be in touch about the package.json files to confirm that they are correct before I submit the PR.

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by chrissimpkins** [comment]
Peter, is there another typeface that I can use as a template for this?  I am trying to figure out how you need me to include the CSS files and each of the individual web font binaries in this package.json file.   Do I define `filename` in your example above with an array of the files using relative paths from the top level of my Github repository or use the autoupdate `files` array from the information about git autoupdates at the link that you posted above?

**Comment by PeterDaveHello** [comment]
filename only point to the mainfile, in this case, i think its the minified css, `files` is used to grab the files, by matching their filename. If there is a dist folder for distribution files, it'll be very easy to include all the files under that folder by `**/*`. Is that help? https://cdnjs.com/libraries/font-awesome can be an example.
