### ISSUE TITLE
[Request] jquery.dirtyforms

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5599]
https://github.com/snikch/jquery.dirtyforms

**Comment by Amomo** [comment]
jquery.dirtyforms has some **plugins**, and it has a dist repo of itself.

I would like to add jquery.dirtyforms and these libraries to cdnjs in the latest stable version v1.2.3.
[jquery.dirtyforms.dist](https://github.com/NightOwl888/jquery.dirtyforms.dist)
[jquery.dirtyforms.helpers.alwaysdirty.dist](https://github.com/NightOwl888/jquery.dirtyforms.helpers.alwaysdirty.dist)
[jquery.dirtyforms.helpers.ckeditor.dist](https://github.com/NightOwl888/jquery.dirtyforms.helpers.ckeditor.dist)
[jquery.dirtyforms.helpers.tinymce.dist](https://github.com/NightOwl888/jquery.dirtyforms.helpers.tinymce.dist)

**Comment by Amomo** [comment]
jquery.dirtyforms and plugins were added via #5693 #5694 #5695 #5696

**Comment by PeterDaveHello** [comment]
What about the others?

**Comment by Amomo** [comment]
I think we could add them when jquery.dirtyforms release v2.0.0.
Um...I guess I should keep this issue open.

**Comment by PeterDaveHello** [comment]
Why not just now?

**Comment by Amomo** [comment]
sounds great~ 😁

**Comment by Amomo** [comment]
plugins were added
