### ISSUE TITLE
[Request] Add gridifier

### ISSUE THREAD

**Issue by macsupport** [cdnjs/cdnjs#5602]
**Library name:** gridifier
**Git repository url:**https://github.com/nix23/gridifier
**npm package url(optional):** 
**License(s):** Non-commercial license(GPLv3), Commercial license $49.99
**Official homepage:**http://gridifier.io/
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@macsupport sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution

**Comment by maruilian11** [comment]
@macsupport this issue will be closed **in 7 days** due to no response. thank you.
