### ISSUE TITLE
[Request] Add ShareCoffee

### ISSUE THREAD

**Issue by BryantAvey** [cdnjs/cdnjs#5604]
ShareCoffee
git: git clone https://github.com/ShareCoffee/ShareCoffee.git
http://sharecoffee.github.io/

Would love to see the ShareCoffee lib added to cdnjs.  It's a set of common angular and SPservice jquery and other js scripts that work specifically with SharePoint CSR and save a lot of work doing SharePoint 2013 coding.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@BryantAvey sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@BryantAvey this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
