### ISSUE TITLE
[Request] Add app-loading

### ISSUE THREAD

**Issue by egoist** [cdnjs/cdnjs#5609]
**Library name:** app-loading
**Git repository url:** https://github.com/aprilorange/app-loading
**npm package url(optional):** https://www.npmjs.com/package/app-loading
**License(s):** MIT
**Official homepage:** https://aprilorange.github.io/app-loading

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Amomo Please take this.

**Comment by Amomo** [comment]
Hi @aprilorange , from our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md),
```
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example,
but as long as reasonable popularity can be demonstrated the library will be added.
```
Currently, we won't add this library.
Could you make a request again when the library has more popularity?
Thanks for your request. :-)

**Comment by PeterDaveHello** [comment]
If @aprilorange would like to send a PR with auto-update config, I would like to accept this PR, @Amomo you can help @aprilorange to do that, I think 88 stars is very close to 100 starts, and also there are minified files, package.json, which what we need.

**Comment by Amomo** [comment]
Ok, I will.

@aprilorange Could you make a pull request to add this library with auto-update?
You can follow our README.md ["Adding a new or updating an existing library"](https://github.com/cdnjs/cdnjs/blob/master/README.md#adding-a-new-or-updating-an-existing-library) to make it.

And, I will help you checking the PR.
Please feel free to tag me, if there’s anything I can do to help.
