### ISSUE TITLE
[Request] jquery-ajaxchimp

### ISSUE THREAD

**Issue by projoomexperts** [cdnjs/cdnjs#5611]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
repo: https://github.com/scdoshi/jquery-ajaxchimp
