### ISSUE TITLE
[Request] Add jshashtable-3.0.js

### ISSUE THREAD

**Issue by sungiant** [cdnjs/cdnjs#5613]
**Library name: jshashtable**
**Git repository url:https://github.com/timdown/jshashtable**
**License(s):Apache License**
**Official homepage:http://www.timdown.co.uk/jshashtable/**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@sungiant sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@sungiant this issue will be closed if there is no any response in next 7 day. thank you !
