### ISSUE TITLE
[Request] Add Gijgo.com

### ISSUE THREAD

**Issue by atatanasov** [cdnjs/cdnjs#5614]
**Library name:** Gijgo
**Git repository url:** N/A
**npm package url(optional):** https://www.npmjs.com/package/jquery-grid
**License(s):** MIT
**Official homepage:** http://gijgo.com/
**Wanna say something? Leave message here:**
I can upload my js lib to github if this is the only option.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello i wonder if the lib's popularity is enough?

**Comment by PeterDaveHello** [comment]
nope

**Comment by maruilian11** [comment]
@atatanasov sorry, but this lib doesn't have enough popularity
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@atatanasov this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by Amomo** [comment]
Closing due to no response.
