### ISSUE TITLE
[Request] Add SweetAlert2 

### ISSUE THREAD

**Issue by angelxmoreno** [cdnjs/cdnjs#5617]
**Library name:**
sweetalert2

**Git repository url:**
https://github.com/limonte/sweetalert2

**License(s):**
MIT

**Official homepage:**
https://limonte.github.io/sweetalert2/

**Wanna say something? Leave message here:**
you guys rock

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
hmmmm ... it's a fork of t4t5/sweetalert and doesn't have enough popularity, I wonder how we add it and if we should add it now.

**Comment by angelxmoreno** [comment]
It replaces  t4t5/sweetalert if that matters

**Comment by PeterDaveHello** [comment]
We already have sweetalert here: https://cdnjs.com/libraries/sweetalert

**Comment by angelxmoreno** [comment]
Oh I know, I meant it replaces sweetalert. sweetalert2 is fully backwards compatible. It adds features sweetalert does not have like adding html to the modals.

**Comment by PeterDaveHello** [comment]
Yeah, I'll discuss with other cdnjs maintainers, thanks!

ping @cdnjs/team-cdnjs @cdnjs/intern for comments, thanks.

**Comment by angelxmoreno** [comment]
:+1:

**Comment by Piicksarn** [comment]
@cdnjs/intern.

**Comment by maruilian11** [comment]
i think we can add it.

**Comment by drewfreyling** [comment]
I'm not sure if it "replaces" sweetalert as it looks like sweetalert is still being maintained. However they have different names so I have no issue with this.

**Comment by PeterDaveHello** [comment]
Added by #7261

**Comment by limonte** [comment]
> https://limonte.github.io/sweetalert2/

this link is outdated, here's the correct one https://sweetalert2.github.io/
