### ISSUE TITLE
[Request] Add SessionLibrary

### ISSUE THREAD

**Issue by yeisoncruz-igniweb** [cdnjs/cdnjs#5619]
**SessionLibrary:** 

<b>Session library without html5</b>
```javascript
/**
 * Implements cookie-less JavaScript session variables
 * v1.0
 *
 * By Craig Buckler, Optimalworks.net
 *
 * As featured on SitePoint.com
 * Please use as you wish at your own risk.
*
 * Usage:
 *
 * // store a session value/object
 * Session.set(name, object);
 *
 * // retreive a session value/object
 * Session.get(name);
 *
 * // clear all session data
 * Session.clear();
 *
 * // dump session data
 * Session.dump();
 */

 if (JSON && JSON.stringify && JSON.parse) var Session = Session || (function() {

	// window object
	var win = window.top || window;

	// session store
	var store = (win.name ? JSON.parse(win.name) : {});

	// save store on page unload
	function Save() {
		win.name = JSON.stringify(store);
	};

	// page unload event
	if (window.addEventListener) window.addEventListener("unload", Save, false);
	else if (window.attachEvent) window.attachEvent("onunload", Save);
	else window.onunload = Save;

	// public methods
	return {

		// set a session variable
		set: function(name, value) {
			store[name] = value;
		},

		// get a session value
		get: function(name) {
			return (store[name] ? store[name] : undefined);
		},

		// clear session
		clear: function() { store = {}; },

		// dump session data
		dump: function() { return JSON.stringify(store); }

	};

 })();
```

recomended by yeisoncruz16@gmail.com
=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@yeisoncruz-igniweb could you provide the `git repo url` or `npm package url`? thank you!

**Comment by PeterDaveHello** [comment]
Please follow our template to submit a lib request, BTW, this issue will be closed if there is no any response in next 10 days, please let me know if there is any other possibility to add this lib, we may miss something sometimes.

**Comment by yeisoncruz-igniweb** [comment]
I just to read your template to submit a lib request, but I has not repo url or package, is a little util lib for session. But if the request has not the necessary, feel free to close it.

**Comment by PeterDaveHello** [comment]
@yeisoncruz-igniweb sorry that we don't host lib in this way, but you can create a public git repo or npm package for it.

**Comment by yeisoncruz-igniweb** [comment]
https://github.com/yeisoncruz16/SessionLibrary

**Comment by maruilian11** [comment]
@yeisoncruz-igniweb could you please also add tags for each version and package.json?
thank you very much!

**Comment by maruilian11** [comment]
@yeisoncruz-igniweb this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
