### ISSUE TITLE
[Request] Add InView

### ISSUE THREAD

**Issue by vinaykrsharma** [cdnjs/cdnjs#5620]
**Library name:** jquery.inview
**Git repository url:** [https://github.com/zuk/jquery.inview](https://github.com/zuk/jquery.inview)
**npm package url(optional):** 
**License(s):** [https://github.com/zuk/jquery.inview/blob/master/LICENSE](https://github.com/zuk/jquery.inview/blob/master/LICENSE)
**Official homepage:** [https://remysharp.com/2009/01/26/element-in-view-event-plugin](https://remysharp.com/2009/01/26/element-in-view-event-plugin)
**Wanna say something? Leave message here:**  Remy Sharp's jQuery plugin adds a bindable 'inview' event for detecting when an element is scrolled into view.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@vinaykrsharma please add the tags so that we can add your lib with **git auto-update**. thank you.

**Comment by PeterDaveHello** [comment]
Let's take this as v1.0.0 and add it.
https://github.com/zuk/jquery.inview/commit/72eced0835275d00a5184b6d44c960a7dcbdb9b1#diff-0a08a7565aba4405282251491979bb6b
