### ISSUE TITLE
[Request] Add jsonpipe

### ISSUE THREAD

**Issue by fbm-static** [cdnjs/cdnjs#5621]
**Library name:**  jsonpipe
**Git repository url:** https://github.com/eBay/jsonpipe
**npm package url(optional):** https://www.npmjs.com/package/jsonpipe
**License(s):** MIT
**Official homepage:** https://github.com/eBay/jsonpipe
**Wanna say something? Leave message here:** What's good? What's good.

=====================
Notes from cdnjs maintainer:
You are welcoming to add a library via sending pull request,
it'll be faster then just opening an request issue,
and please forget to read the guidelines for contributin', thanks!!

**Comment by maruilian11** [comment]
@fbm-static sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by PeterDaveHello** [comment]
This issue will be closed if there is no any response in next 10 days, please let me know if there is any other possibility to add this lib, we may miss something sometimes.
