### ISSUE TITLE
[Request] Add require-text v2.0.14

### ISSUE THREAD

**Issue by maximegris** [cdnjs/cdnjs#5623]
**Library name: require-text
**Git repository url: https://github.com/requirejs/text
**npm package url(optional):** 
**License(s): Dual-licensed -- new BSD or MIT.
**Official homepage: http://requirejs.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
any reason to close this?
