### ISSUE TITLE
[Request] Add PDF.js

### ISSUE THREAD

**Issue by lony** [cdnjs/cdnjs#5627]
**Library name:** PDF.js
**Git repository url:** https://github.com/mozilla/pdf.js
**npm package url(optional):** 
**License(s):** Apache License 2004
**Official homepage:** https://mozilla.github.io/pdf.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #5020, thanks!
