### ISSUE TITLE
[Request] Add dimple.js 

### ISSUE THREAD

**Issue by jun9** [cdnjs/cdnjs#5630]
**Library name:** dimple.js
**Git repository url:** https://github.com/PMSI-AlignAlytics/dimple
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://dimplejs.org
**Wanna say something? Leave message here:**
Thanks!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
it's duplicated with #5503 , we will add this lib asap. thank you for your contribution!
