### ISSUE TITLE
[Request] Add _library_name_ lodash.min.js

### ISSUE THREAD

**Issue by koenam** [cdnjs/cdnjs#5654]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@koenam,
do you request for the link below? we need more detail for adding library!
https://cdnjs.com/libraries/lodash.js

**Comment by maruilian11** [comment]
@koenam this issue will be closed **in 7 days** due to no response. thank you for your contribution.
