### ISSUE TITLE
LightGallery outdated on cdnjs

### ISSUE THREAD

**Issue by evromalarkey** [cdnjs/cdnjs#5655]
https://cdnjs.com/libraries/lightgallery has old version 1.1.6, but there is already 1.2.0 - https://github.com/sachinchoolur/lightGallery/releases

**Comment by PeterDaveHello** [comment]
v1.2.0 added https://github.com/cdnjs/cdnjs/commit/9d0d04cec324b6e130009731e6844f9c65349c79

**Comment by evromalarkey** [comment]
thanks!
