### ISSUE TITLE
[Request] Add html5shiv

### ISSUE THREAD

**Issue by ukundo** [cdnjs/cdnjs#5660]
**Library name:** html5shiv
**Git repository url:**https://github.com/aFarkas/html5shiv
**npm package url(optional):** 
**License(s):**mit or gpl2
**Official homepage:**
**Wanna say something? Leave message here:** the newest available.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ukundo** [comment]
update available

**Comment by PeterDaveHello** [comment]
* ff79372 add html5shiv v3.7.0 Peter Dave Hello 23 minutes ago
* 961d1b2 add git auto-update config for html5shiv Peter Dave Hello 71 minutes ago

**Comment by ukundo** [comment]
thanks.

**Comment by PeterDaveHello** [comment]
np
