### ISSUE TITLE
[Request] Add angular-base64

### ISSUE THREAD

**Issue by timbaileyjones** [cdnjs/cdnjs#5663]
**Library name:** angular-base64
**Git repository url:** https://github.com/ninjatronic/angular-base64
**npm package url(optional):** 
**License(s):** BSD - via http://code.google.com/p/stringencoders/source/browse/#svn/trunk/javascript
**Official homepage:** https://github.com/ninjatronic/angular-base64

**Comment by PeterDaveHello** [comment]
Seems http://code.google.com/p/stringencoders/source/browse/#svn/trunk/javascript didn't show a valid license.

**Comment by maruilian11** [comment]
@timbaileyjones could you please show us the lib has valid license so that we can add it? thank you!
this issue will be closed if there is no any response in next 7 day.

**Comment by PeterDaveHello** [comment]
@maruilian11 there is no clear valid license request in our document ... I think you can just help us confirm that with its author.

**Comment by timbaileyjones** [comment]
I agree... Upon retracing my steps, this gets much more complicated than I anticipated.

On this page https://github.com/ninjatronic/angular-base64/blob/master/LICENSE, the last line says: "Released under the same license as the original code".  So I went looking for the "original code".  Line 5 of the same LICENSE file points to this page: http://code.google.com/p/stringencoders/source/browse/#svn/trunk/javascript.

Obviously the post-# part doesn't refer to a file, but I think it is clear that we are to seek out the license for the stringencoders project at http://code.google.com/p/stringencoders.  That google URL does a "301 Redirect" to a Github repo of the same name (stringencoders) at https://github.com/client9/stringencoders.

Several files in that repo (COPYING, INSTALL) clearly name the BSD "new" license, and give this URL to the license text. http://www.opensource.org/licenses/bsd-license.php.   Retrieving that php page shows a slighltly different name: "The BSD 2-clause license".

Searching ALL the files in the stringencoders repo shows that the JS files say "dual-licensed MIT and GPL", while the python file says MIT, and the C/H files under ./src named the 'new' BSD license (the 2-clause license).  Even more strange, the apr_base64.[ch] files say "Apache 2.0", but they are just the unit tests, not the C implemention.

So, the angular-base64 project is strictly about Javascript, and there is exactly ONE Javascript file that contains the base64 functionality in the stringencoders repo.  The obvious thing to do is to use the license that is in that file.  https://github.com/client9/stringencoders/blob/master/javascript/base64.js

That file has 25 lines worth of a copyright notice and license, but there is not a license NAME anywhere in that file.  i.e. it does NOT say GPL, MIT, Eclipse, Apache, etc.

Is it required that we be able to assign a short name to this license in order to get it into CDNJS?

**Comment by PeterDaveHello** [comment]
I think we can confirm with its author first, or just don't add that field.

**Comment by ninjatronic** [comment]
Author of `angular-base64` here. The code is a copy of the code in the [base64.js](https://github.com/client9/stringencoders/blob/master/javascript/base64.js) file in the `stringencoders` project linked. When I took the code it was originally hosted on Google Code in it's own project (ie not lumped in with the other languages) so the license that applied at that point in time is the one at the top of the javascript file. You can see that it has been copied verbatim into the angular javascript file [here](https://github.com/ninjatronic/angular-base64/blob/master/angular-base64.js#L10).

As far as I am aware it is a standard MIT license in all but name. Hope that helps.

**Comment by PeterDaveHello** [comment]
@ninjatronic What about clarify its license in readme or somewhere if its MIT license? Or let's confirm with author of base64.js ?

**Comment by ninjatronic** [comment]
For total clarity your best bet is probably to check with [Nick](https://github.com/client9). I've never actually contacted the guy eh, just pasta'd his code into the angular lib!

**Comment by PeterDaveHello** [comment]
Ping @client9
