### ISSUE TITLE
[Request] Add rateYo 

### ISSUE THREAD

**Issue by radicalbiscuit** [cdnjs/cdnjs#5666]
**Library name:** rateYo
**Git repository url:** [https://github.com/prrashi/rateYo](https://github.com/prrashi/rateYo)
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** [http://prrashi.github.io/rateYo/](http://prrashi.github.io/rateYo/)
**Wanna say something? Leave message here:** The package is simple, lightweight, and configurable. Extra stars (pun most certainly intended) for using SVG. The author appears to be responsive. I foresee its prominence in the rating star library world, the vastness of which I have no knowledge.

**Comment by PeterDaveHello** [comment]
Looks good to have.

**Comment by PeterDaveHello** [comment]
@Piicksarn please add this lib, thanks.

**Comment by prrashi** [comment]
Hey!, Thank you guys, for your activity on this library. @PeterDaveHello @radicalbiscuit
