### ISSUE TITLE
[Request] Add Animate Plus 

### ISSUE THREAD

**Issue by donaldallen** [cdnjs/cdnjs#5670]
**Library name:** Animate Plus
**Git repository url:** https://github.com/bendc/animateplus
**npm package url(optional):** https://www.npmjs.com/package/animateplus
**License(s):** MIT
**Official homepage:** https://github.com/bendc/animateplus
**Wanna say something? Leave message here:** Created by Benjamin De Cock of Stripe.

**Comment by PeterDaveHello** [comment]
@maruilian11 please take this
