### ISSUE TITLE
[Request] Add glide js

### ISSUE THREAD

**Issue by danyuk1982** [cdnjs/cdnjs#5671]
**Library name:** Glide JS
**Git repository url:** https://github.com/jedrzejchalubek/Glide.js
**npm package url(optional):** 
**License(s):** MIT License.
**Official homepage:** http://glide.jedrzejchalubek.com/
**Wanna say something? Leave message here:**
Great jQuery slider, please add

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by danyuk1982** [comment]
No idea what that means! I just clicked the "Request a Lib" link here: https://cdnjs.com/ and filled in the form?

**Comment by PeterDaveHello** [comment]
You sent the request ticket and now you have it: https://cdnjs.com/libraries/Glide.js.

**Comment by danyuk1982** [comment]
Oh, ok - great! Thank you :)

**Comment by PeterDaveHello** [comment]
np
