### ISSUE TITLE
Construct a latest folder when libray uses npm auto update

### ISSUE THREAD

**Issue by ColinEberhardt** [cdnjs/cdnjs#5674]
I've noticed that for manually maintained libraries a number of authors are maintaining a `latest` folder which makes it easier to maintain a URL on their website that links to the latest version of their library.

If a library is configured to use npm auto update, a `latest` folder is not created or maintained. 

I'd like to propose that the npm update script creates and maintains a `latest` folder for all libraries that opt in to this feature.

NOTE: This is related to https://github.com/cdnjs/cdnjs/issues/360 but is subset of the functionality described and should be relatively easy to implement using the existing infrastructure.

**Comment by PeterDaveHello** [comment]
I think we've told about this issue for many times ant in the meantime we will not do it, it'll have cache issue and other issues, like breaking changes between versions. cc @cdnjs/team-cdnjs

**Comment by ryankirkman** [comment]
Unfortunately, a `/latest/` directory is not something we will be support.

This is following the same best practices as Google's CDN. You can read more here: https://github.com/cdnjs/cdnjs/issues/4396#issuecomment-83192678
