### ISSUE TITLE
fontAwesom

### ISSUE THREAD

**Issue by akkyjumbade** [cdnjs/cdnjs#5678]

**Comment by PeterDaveHello** [comment]
What is this for?

**Comment by maruilian11** [comment]
@akkyjumbade please provide the lib's `git repo url` or `npm package url` so that we can add the lib. this issue will be closed **in 7 days** due to no response, thank you!

**Comment by download13** [comment]
https://www.npmjs.com/package/font-awesome
https://github.com/FortAwesome/Font-Awesome

**Comment by PeterDaveHello** [comment]
We have it for a long time:
https://cdnjs.com/libraries/font-awesome

**Comment by download13** [comment]
I just realized I've been using that. Not sure why it didn't occur to me before posting here.

**Comment by maruilian11** [comment]
@download13 is there still anything we can do for you?

**Comment by download13** [comment]
No, I'm good. Thanks for the quick responses!

**Comment by maruilian11** [comment]
ok! have a good day~

**Comment by PeterDaveHello** [comment]
@akkyjumbade updates?
