### ISSUE TITLE
[Request] Add jQuery Selectric

### ISSUE THREAD

**Issue by lcdsantos** [cdnjs/cdnjs#5679]
**Library name:** jQuery Selectric
**Git repository url:** https://github.com/lcdsantos/jQuery-Selectric.git
**npm package url(optional):** https://www.npmjs.com/package/selectric
**License(s):** MIT
**Official homepage:** http://lcdsantos.github.io/jQuery-Selectric/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @lcdsantos, I found there is `dist` folder before, would you like to add it again? It'll help us add it and also auto-update it in future, thanks!

**Comment by maruilian11** [comment]
@lcdsantos this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
This lib has enough popularity, just ping @
