### ISSUE TITLE
[Request] Add jQuery DrawSVG

### ISSUE THREAD

**Issue by lcdsantos** [cdnjs/cdnjs#5680]
**Library name:** jQuery DrawSVG
**Git repository url:** https://github.com/lcdsantos/jquery-drawsvg.git
**npm package url(optional):** https://www.npmjs.com/package/drawsvg
**License(s):** MIT
**Official homepage:** http://lcdsantos.github.io/jquery-drawsvg/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Would you like to send a PR by yourself? Since you are the author of this lib :smiley:

**Comment by maruilian11** [comment]
@lcdsantos sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by lcdsantos** [comment]
Ah, ok... Closing this for now.
