### ISSUE TITLE
[Request] Add braintree framebus

### ISSUE THREAD

**Issue by pconerly** [cdnjs/cdnjs#5682]
**Library name:** Braintree frambus
**Git repository url:** https://github.com/braintree/framebus
**npm package url(optional):** https://www.npmjs.com/package/framebus
**License(s):** https://github.com/braintree/framebus/blob/master/LICENSE
**Official homepage:** https://github.com/braintree/framebus
**Wanna say something? Leave message here:**
I'm testing how to use framebus on a simple webpage (i.e. I haven't set up `node_modules` or `webpack` yet) and it would be a tiny bit easier if this was on cdnjs!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@pconerly sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by pconerly** [comment]
Thanks, I will.
