### ISSUE TITLE
[Request] Add Marker Clusterer

### ISSUE THREAD

**Issue by vladrusu** [cdnjs/cdnjs#5683]
**Library name:** Marker Clusterer
**Git repository url:** https://github.com/googlemaps/js-marker-clusterer
**npm package url(optional):** 
**License(s):** Apache 2.0
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems not act on github for a long time, what can we do for this issue?

**Comment by PeterDaveHello** [comment]
Is there any pre-built file in repository we can use?

**Comment by maruilian11** [comment]
@PeterDaveHello this lib only has one version (v1.0.0), maybe we just add this version first without waiting for the tag?
files here
https://github.com/googlemaps/js-marker-clusterer/tree/gh-pages/src

**Comment by PeterDaveHello** [comment]
Yes, it'll be good.
