### ISSUE TITLE
Move on node.js v4.2.2

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5685]
nodejs 4.0 released few days ago:
https://nodejs.org/en/blog/release/v4.0.0/
https://github.com/nodejs/node/releases/

Now migrated/merged with io.js and has new engine, features and may also have performance increase(I haven't test it), see:
 * [NodeJS 4.0.0 is 8% faster – we tested it!](https://raygun.io/blog/2015/09/nodejs-and-io-js-are-now-one/)
 * [What you need to know about Node.js 4.0.0](http://apmblog.dynatrace.com/2015/09/05/all-you-need-to-know-about-node-js-4-0/)

Ping @cdnjs/intern start to **test and report** if we have any problem with nodejs, thanks.

cc @cdnjs/team-cdnjs @cdnjs/atom-devs

**Comment by Amomo** [comment]
I have updated node.js to v4.0 in my environment.
Don't see any error. :+1:

**Comment by PeterDaveHello** [comment]
BTW, you can try: nvm to switch between versions: https://github.com/creationix/nvm, so that once we got a problem, we can easily confirm if it caused by a specify version.

**Comment by maruilian11** [comment]
ok.

**Comment by PeterDaveHello** [comment]
FYI, I'll migrate to v4.0.0 if we didn't see any error for 7 days.

**Comment by PeterDaveHello** [comment]
Where is @Piicksarn and @LeaYeh ?

**Comment by Piicksarn** [comment]
Done, too!

**Comment by Piicksarn** [comment]
@LeaYeh

**Comment by PeterDaveHello** [comment]
Switched to v4.1.1

**Comment by Amomo** [comment]
Done :-D

**Comment by PeterDaveHello** [comment]
@Amomo Nice!

**Comment by IonicaBizau** [comment]
:tada: :sparkles:

**Comment by LeaYeh** [comment]
done

**Comment by PeterDaveHello** [comment]
v4.2.0 with longbterm support just released, so let's move on to the first lts version!

**Comment by ryankirkman** [comment]
Sounds good.

**Comment by PeterDaveHello** [comment]
v4.2.1 released https://nodejs.org/en/blog/release/v4.2.1/, I think we can just follow LTS release without any doubts.

**Comment by Amomo** [comment]
ok, update to v4.2.1 now~

**Comment by maruilian11** [comment]
just updated.

**Comment by IonicaBizau** [comment]
Cool! :rocket: :tada:

**Comment by PeterDaveHello** [comment]
v4.2.1 tested without problem here. @cdnjs/intern please do some simple test after every upgrade and report.

**Comment by LeaYeh** [comment]
done.

**Comment by PeterDaveHello** [comment]
Node v4.2.2 (LTS) released few hours ago:
https://nodejs.org/en/blog/release/v4.2.2/

Note that we are not going to move on v5, just latest LTS version!

**Comment by Amomo** [comment]
update to v4.2.2 now~

**Comment by maruilian11** [comment]
updated.

**Comment by LeaYeh** [comment]
updated.

**Comment by PeterDaveHello** [comment]
@Piicksarn ?
