### ISSUE TITLE
The library search api does not return assets

### ISSUE THREAD

**Issue by getsetbro** [cdnjs/cdnjs#5688]
When I hit the api for the assets of 'twitter-bootstrap' (http://api.cdnjs.com/libraries?search=twitter-bootstrap&fields=assets) here is the results:
https://gist.github.com/getsetbro/0b4d707150a6c9962149

I was expecting to get these:
https://cdnjs.com/libraries/twitter-bootstrap

**Comment by iamstolis** [comment]
This issue breaks support for CDNJS libraries in NetBeans IDE :-(.

**Comment by PeterDaveHello** [comment]
cc @redox Not sure it is related with https://github.com/cdnjs/new-website/commit/ca21f39e54bc281ebac8b3d921035dc515a8d3b2

**Comment by PeterDaveHello** [comment]
hmmm ... yes, now revert it.

**Comment by PeterDaveHello** [comment]
@getsetbro @iamstolis I revert that change, thanks for your reporting!

**Comment by redox** [comment]
Oh, I forgot to handle the "fields" query parameter; let me check that.

**Comment by redox** [comment]
Hey @PeterDaveHello, I've just pushed a revised version of the search, now handling the optional `fields`. I'm so sorry, totally miss that one.

**Comment by getsetbro** [comment]
I'd like to get all assets of all libraries with:
http://api.cdnjs.com/libraries?fields=assets
or
http://api.cdnjs.com/libraries?search=*&fields=assets

**Comment by PeterDaveHello** [comment]
New version deployed, let's give it a try!

**Comment by PeterDaveHello** [comment]
Will close after confirmed.

**Comment by getsetbro** [comment]
Why would this search return to me the "sco.js" library:
$.get('http://api.cdnjs.com/libraries?search=twitter-boo&fields=assets')

**Comment by getsetbro** [comment]
Why would searching for "twitter" return hogan.js?
<img width="570" alt="screen shot 2015-09-14 at 8 55 38 am" src="https://cloud.githubusercontent.com/assets/442793/9851465/650ce4b8-5abe-11e5-9957-8c0164771ba3.png">

**Comment by redox** [comment]
@getsetbro because the search is currently using all attributes (and "twitter" is mentioned in the `homepage` attribute). We can restrict it to the name + description (or just name) if you guys think it's better. What are the most frequent usages of that API?

**Comment by getsetbro** [comment]
This isn't an answer to that question but it would be useful to be able to get only the one library that you want such as:
http://api.cdnjs.com/libraries?<b><i>library=twitter-bootstrap</i></b>&fields=homepage,version,assets

If that means restricting search to the just the name then okay.

**Comment by getsetbro** [comment]
Something else useful is if the assets > files were the full link to the file instead of just the ending.

**Comment by PeterDaveHello** [comment]
@getsetbro not sure if you want this?
http://api.cdnjs.com/libraries/twitter-bootstrap / http://api.cdnjs.com/libraries/twitter-bootstrap?output=human

![default](https://cloud.githubusercontent.com/assets/3691490/9865115/901ec790-5b84-11e5-906c-df082f0e8101.png)

**Comment by PeterDaveHello** [comment]
hmmmm ... I got problem with http://api.cdnjs.com/libraries?search=twitter-bootstrap&fields=assets
![default](https://cloud.githubusercontent.com/assets/3691490/9865126/b209fcee-5b84-11e5-8f99-68a7a34f5053.png)

**Comment by PeterDaveHello** [comment]
Strange, I got no problem locally, hmmmm ...

**Comment by PeterDaveHello** [comment]
hmmm ... it's back now, @redox I think I may revert it again ...

**Comment by redox** [comment]
Not sure I'm following guys, do you still experience an issue?

**Comment by PeterDaveHello** [comment]
This [problem](https://github.com/cdnjs/cdnjs/issues/5688#issuecomment-140241573) appeared with latest master branch, I tested with older revision and has no problem, so it's fallback, but didn't revert yet, any idea about hat error?
