### ISSUE TITLE
[Request] Add jquery-cookiebar

### ISSUE THREAD

**Issue by alberto-bottarini** [cdnjs/cdnjs#5689]
**Library name:** jquery-cookiebar 
**Git repository url:** https://github.com/delboy1978uk/jquery.cookiebar
**License(s):** CC0 1.0 Universal
**Official homepage:** http://www.primebox.co.uk/projects/cookie-bar/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@alberto-bottarini sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@alberto-bottarini this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
