### ISSUE TITLE
[Request] Add usertiming.js

### ISSUE THREAD

**Issue by nicjansma** [cdnjs/cdnjs#5692]
**Library name:** usertiming.js
**Git repository url:** https://github.com/nicjansma/usertiming.js
**npm package url(optional):** https://www.npmjs.com/package/usertiming
**License(s):** MIT
**Official homepage:** https://github.com/nicjansma/usertiming.js

Thanks!

**Comment by PeterDaveHello** [comment]
Would you like to send a PR by yourself @nicjansma ?

**Comment by nicjansma** [comment]
Sure! https://github.com/cdnjs/cdnjs/pull/5698
