### ISSUE TITLE
[Request] Broadway.js

### ISSUE THREAD

**Issue by TakeshiTseng** [cdnjs/cdnjs#5706]
**Library name:Broadway.js** 
**Git repository url:https://github.com/mbebenita/Broadway.git**
**npm package url(optional):** 
**License(s):BSD**
**Official homepage:http://mbebenita.github.io/Broadway/**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Tag added, thanks @soliton4

**Comment by PeterDaveHello** [comment]
@LeaYeh please take this.

**Comment by LeaYeh** [comment]
hey @cdnjs/intern , could you give me some suggestions?
in [this case](https://github.com/mbebenita/Broadway/tree/0.1.0) i want to add all `js` and `css` files in [player folder](https://github.com/mbebenita/Broadway/tree/0.1.0/Player) but, 

1. i dont know how to handle [decoder folder](https://github.com/mbebenita/Broadway/tree/0.1.0/Decoder)

2. and which is main file that i need to point to `filename` field?

**Comment by soliton4** [comment]
the decoder folder is only used for development
the player folder is pretty much the relase

**Comment by LeaYeh** [comment]
@soliton4 thank for your help !

**Comment by LeaYeh** [comment]
@soliton4 could this project without `Player/*.mp4` and `Player/*.html` ?
i ask because cdnjs doesnt support `.mp4` and `.html`

**Comment by soliton4** [comment]
broadway.js is not made specifically to project. but you can use it with a projector of course.
it is intended to work with other mp4 as well so feel free to project your own mp4 file.

**Comment by PeterDaveHello** [comment]
@soliton4 thanks.
