### ISSUE TITLE
[request] Oimo

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [cdnjs/cdnjs#5709]
Oimo
https://github.com/lo-th/Oimo.js/
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Comment by PeterDaveHello** [comment]
@theboyWhoCriedWoolf what are the files should be hosted on CDN? Thanks.

**Comment by sufuf3** [comment]
**Library name:** Oimo.js
**Git repository url:** https://github.com/lo-th/Oimo.js
**npm package name or url** (if there is one): https://www.npmjs.com/package/oimo
**License (List them all if it's multiple):** MIT
**Official homepage:** http://lo-th.github.io/Oimo.js/index.html#basic
![image](https://cloud.githubusercontent.com/assets/8349587/24577286/7d59b10c-16fd-11e7-8874-6b497d2a3ef8.png)

![image](https://cloud.githubusercontent.com/assets/8349587/24577277/66707a48-16fd-11e7-9ce5-176eb080187c.png)
