### ISSUE TITLE
[Request] [new] Add jQuery Raty FA

### ISSUE THREAD

**Issue by fauzana** [cdnjs/cdnjs#5711]
**Library name:** jQuery Raty FA
**Git repository url:** https://github.com/Jacob87/raty-fa
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://jacob87.github.io/raty-fa/

**Comment by maruilian11** [comment]
@fauzana sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
