### ISSUE TITLE
[Issue] Font links in weather-icons do not point to CDN hosted fonts

### ISSUE THREAD

**Issue by clintoncampbell** [cdnjs/cdnjs#5714]
The font URL's in the fontawesome-inspired weather-icons.css do not point to the CDN hosted fonts, meaning that the app must either host the fonts themselves with the directory structure specified in the CSS or override the fontface declaration in the CSS.

**Comment by PeterDaveHello** [comment]
Can you give me a link?

**Comment by clintoncampbell** [comment]
Whoops, here you go: http://cdnjs.com/libraries/weather-icons. Ideally this would work like fontawesome, where including the CSS from the CDN also leveraged the fonts from the CDN. Otherwise, it gets a bit confusing (though can be made to work).

**Comment by PeterDaveHello** [comment]
I meant the version and file you are using, I just took a look at https://cdnjs.cloudflare.com/ajax/libs/weather-icons/2.0.7/css/weather-icons-wind.css and seems the url of fonts are relative urls, so I didn't get your problem yet.

**Comment by clintoncampbell** [comment]
Hmm, this may have been an issue on my end. I did quite a bit of testing with it yesterday before I overrode the fontface. Not sure what I changed, but my test code on codepen is now correctly fetching the fonts after taking out the override. Apologies for the false issue, and thank you for quick response!

**Comment by PeterDaveHello** [comment]
np
