### ISSUE TITLE
[Request] Add Angular-auto-validate

### ISSUE THREAD

**Issue by wsyski** [cdnjs/cdnjs#5715]
**Library name:Angular-auto-validate
*_Git repository url: https://github.com/jonsamwell/angular-auto-validate
*_npm package url(optional):https://www.npmjs.com/package/angular-auto-validate
*_License(s):The MIT License (MIT)
*_Official homepage:http://jonsamwell.github.io/angular-auto-validate
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
unfortunately, we don't host json file for now, but this lib uses json to store i18n strings, @cdnjs/owners can we support json files?

**Comment by ryankirkman** [comment]
I think json should be fine. Let's verify first.

**Comment by PeterDaveHello** [comment]
cc @terinjokes

**Comment by PeterDaveHello** [comment]
ping

**Comment by PeterDaveHello** [comment]
ping @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
@terite is it possible to let json be available on our CDN? Thanks.

**Comment by MattIPv4** [comment]
Working on getting JSON on the whitelist in #13145

**Comment by MattIPv4** [comment]
The request from .json files has been resolved as part of #13145 and .json files are now served on the cdnjs.cloudflare.com domain 🎉

**Comment by MattIPv4** [comment]
@PeterDaveHello Do you still wish to be assigned?
