### ISSUE TITLE
[Request] Add jquery-waypoints

### ISSUE THREAD

**Issue by giovannipds** [cdnjs/cdnjs#5722]
**Library name:** jquery-waypoints
**Git repository url:** https://github.com/imakewebthings/jquery-waypoints.git
**npm package url(optional):** https://www.npmjs.com/package/waypoints
**License(s):** MIT
**Official homepage:** http://imakewebthings.com/waypoints/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it.
https://cdnjs.com/libraries/waypoints

**Comment by giovannipds** [comment]
Hello @PeterDaveHello. Weird! Yesterday I searched and was showing just the "noframework" version, lol. My mistake. Thanks for the answer.
