### ISSUE TITLE
[Request] Add ieBetter.js

### ISSUE THREAD

**Issue by htfy96** [cdnjs/cdnjs#5737]
**Library name:**  ieBetter.js
**Git repository url:** https://github.com/zhangxinxu/ieBetter.js
**License(s):** MIT License
**Official homepage:** http://www.zhangxinxu.com/wordpress/2013/12/iebetter-js-make-ie6-ie8-like-modern-browser-ie9-chrome/ (Chinese)

This is a script which makes IE6-IE8 behave like a modern browser. Compared with the existing script `ie8`, it provides better support for IE6~7.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @htfy96, 
The lib is lack of package.json for confirmed information.
We had already open an issue to the author.
Thanks for your suggestion! :smiley:

**Comment by PeterDaveHello** [comment]
@Piicksarn I don't think you should wait for that, you can just create one and then submit a PR to upstream.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i see!
