### ISSUE TITLE
[Request] Add angular-truncate

### ISSUE THREAD

**Issue by MSTWNTD1** [cdnjs/cdnjs#5743]
Library name: Angular Trucante
Git repository url: https://github.com/sparkalow/angular-truncate

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by BernardoSilva** [comment]
Adding angular-truncate in here: https://github.com/cdnjs/cdnjs/pull/6084

Hope it helps.

**Comment by maruilian11** [comment]
@sparkalow  could you please add tags for this lib so that we can add your lib with **git auto-update**. thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems not act on github for a long time, what can we do for this issue?

**Comment by PeterDaveHello** [comment]
Maybe just take this commit as v0.1.2
https://github.com/sparkalow/angular-truncate/commit/fb45ef9fb7c78b81cba2e960af8736c8e54d2da9
