### ISSUE TITLE
[Request] Add ISO 3166-2

### ISSUE THREAD

**Issue by seb-at-nzrs** [cdnjs/cdnjs#5744]
**Library name:** ISO 3166-2
**Git repository url:** https://github.com/olahol/iso-3166-2.js
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** https://github.com/olahol/iso-3166-2.js
**Wanna say something? Leave message here:** Useful library for converting ISO-3166 Alpha2 and Alpha3 representation to countries.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@seb-at-nzrs sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@seb-at-nzrs this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
