### ISSUE TITLE
[Request] Add jss 

### ISSUE THREAD

**Issue by kof** [cdnjs/cdnjs#5745]
**Library name:** jss
**Git repository url:** https://github.com/jsstyles/jss
**npm package url(optional):** https://www.npmjs.com/package/jss
**License(s):** MIT
**Official homepage:** https://www.npmjs.com/package/jss
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kof** [comment]
thanks

**Comment by Amomo** [comment]
@kof You're welcome! 😃
