### ISSUE TITLE
requiredFiles field

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/cdnjs#5753]
today i was going to add git auto-update config in existed lib, there is a new `example.css` in the new version but without `example.min.css`, so i add requiredFiles field of `example.min.css` under the package.json. but when i run npm test, it said `example.min.css` should be exist.
but we usually add git auto-update config in existed lib without adding the new version files, is there any recommendation？ thanks!

**Comment by PeterDaveHello** [comment]
In this case, add the new version first.

**Comment by maruilian11** [comment]
@PeterDaveHello #5747 is the case. should i close it and send a new PR?

**Comment by PeterDaveHello** [comment]
Use rebase to fix and update your PR.

**Comment by maruilian11** [comment]
ok.
