### ISSUE TITLE
[Request] details-shim

### ISSUE THREAD

**Issue by matbech** [cdnjs/cdnjs#5756]
**Library name: details-shim**
**Git repository url: https://github.com/tyleruebele/details-shim**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://tyleruebele.com/weblog/details-shim**
**Wanna say something? Leave message here: Stand alone HTML5 details shim. Requires no dependencies like jquery**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@matbech sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@matbech this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
