### ISSUE TITLE
[Request] Layer

### ISSUE THREAD

**Issue by cuiqg** [cdnjs/cdnjs#5757]
**Library name:** Layer
**Git repository url:** https://github.com/sentsin/layer.git
**npm package url(optional):** in git
**License(s):** GNU
**Official homepage:** http://layer.layui.com 
**Wanna say something? Leave message here:**
layer是一款近年来口碑非常不错的web弹层组件，她具备全方位的解决方案，致力于服务各个水平段的开发人员，您的页面会轻松地拥有丰富友好的操作体验。

在与同类组件的比较中，layer总是能轻易获胜。她尽可能地在以更少的代码展现更强健的功能，且格外注重性能的提升、易用和实用性，正因如此，越来越多的开发者将媚眼投上了layer。layer兼容了包括IE6在内的所有主流浏览器。 她数量可观的接口，使得您可以自定义太多您需要的风格，每一种弹层模式各具特色，皆广受欢迎。当然，这种“王婆卖瓜”的陈述听起来总是有点难受，因此你需要进一步了解她是否真的如你所愿。

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @cuiqg,

cdnjs relies on the `tags in git repository` to update libraries.
Tags are necessary for us to add a new library.

Would you mind to suggest the author adding tags in GitHub repository?
Thank you!

**Comment by maruilian11** [comment]
@cuiqg this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern I think you can do the tag suggestion work, can't you?

**Comment by maruilian11** [comment]
@PeterDaveHello suggest cdnjs/intern?

**Comment by LeaYeh** [comment]
i already sent mail to author, let's wait for his reply :)

**Comment by PeterDaveHello** [comment]
Thanks.

**Comment by LeaYeh** [comment]
author dosen't reply yet :(

**Comment by PeterDaveHello** [comment]
If there is no response for more then 3 weeks, let's close this issue then.
