### ISSUE TITLE
[Request] Add Bootstrap Notify

### ISSUE THREAD

**Issue by suriya** [cdnjs/cdnjs#5759]
**Library name:** Bootstrap Notify
**Git repository url:** https://github.com/mouse0270/bootstrap-notify
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://bootstrap-notify.remabledesigns.com/
**Wanna say something? Leave message here:**
Thank you so much!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@PeterDaveHello I find the PR #6727 already existed. What should I do?

**Comment by PeterDaveHello** [comment]
Okay so close this, this lib was added in 793fa68.
