### ISSUE TITLE
[Request] Jets.js

### ISSUE THREAD

**Issue by NeXTs** [cdnjs/cdnjs#5760]
**Library name:Jets.js
**Git repository url:https://github.com/NeXTs/Jets.js
**npm package url(optional):https://www.npmjs.com/package/jets
**License(s):MIT
**Official homepage:http://nexts.github.io/Jets.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by NeXTs** [comment]
@Amomo Thanks! :+1:

**Comment by Amomo** [comment]
@NeXTs You're welcome! 😄
