### ISSUE TITLE
[Request] Add Dimple.js Library to cdjns

### ISSUE THREAD

**Issue by jfhucka** [cdnjs/cdnjs#5761]
Hello,
I have all the info below. It would be really great if we can get https access to the opensource dimple library.

Library name: http://dimplejs.org/dist/dimple.v2.1.6.min.js
Git repository url: https://github.com/PMSI-AlignAlytics/dimple
License(s): https://github.com/PMSI-AlignAlytics/dimple/blob/master/MIT-LICENSE.txt
Official homepage: http://dimplejs.org/index.html

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@jfhucka, we have already added the dimple.js! :smile: 
#5748
Thank you!
