### ISSUE TITLE
Auto update not working for gist-embed

### ISSUE THREAD

**Issue by blairvanderhoof** [cdnjs/cdnjs#5763]
I added tag 2.3 today https://github.com/blairvanderhoof/gist-embed, not seeing https://cdnjs.cloudflare.com/ajax/libs/gist-embed/2.3/gist-embed.min.js still.

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/commit/a13b4af8f03497de97f7be2e56ad3743860e52b8
https://github.com/cdnjs/cdnjs#enabling-npmrecommended-or-git-auto-update
