### ISSUE TITLE
add old versions of dimple

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5768]
There was no `dimple.latest.js` unteil dimple v2.1.2, before that, there was version num in the filename, which will not be accepted to be hosted on cdn, in this case, there are many different versions' dist files in the `dist` folder, so that we can not include all the files in auto-update, so the work to add the old versions should be done by human begin, the jobs used to be done by me before, it's time for the member of intern team to do this, the files are here:
https://github.com/PMSI-AlignAlytics/dimple/tree/2.1.6/dist

I think we can rename them to `dimple.latest.min.js` and `dimple.latest.js`, in the old versions, and please be very careful when do these works which can not automatically handled by the program.

**Comment by PeterDaveHello** [comment]
Assigned to @Piicksarn, and all the member in @cdnjs/intern should help to review/audit that PR to close this issue.

**Comment by maruilian11** [comment]
ok.

**Comment by LeaYeh** [comment]
ok, got that
