### ISSUE TITLE
website doesn't link to new files

### ISSUE THREAD

**Issue by richard-vd** [cdnjs/cdnjs#5770]
The 146 files that were added by PR #5329 five days ago were almost instantly available through the CDN, but yet still can't be found through the front page.

For example this file works from the CDN:
https://cdnjs.cloudflare.com/ajax/libs/extjs/6.0.0/packages/charts/classic/charts.js

However it is not listed here:
https://cdnjs.com/libraries/extjs/6.0.0

**Comment by PeterDaveHello** [comment]
Sorry that, I'll do a force rebuild later, usually not to do that.

**Comment by PeterDaveHello** [comment]
Started to fully rebuild, it'll spend a long time, please wait :smile:

**Comment by PeterDaveHello** [comment]
I think we can see those files now @richard-vd

**Comment by richard-vd** [comment]
It's okay now, thanks!
