### ISSUE TITLE
auto-update on Polyglot-Language-Switcher

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5771]
lib: https://cdnjs.com/libraries/polyglot
repo: https://github.com/ixtendo/Polyglot-Language-Switcher/

**Comment by PeterDaveHello** [comment]
And should also add repo info in package.json

**Comment by maruilian11** [comment]
@PeterDaveHello This repo is not maintained anymore, the author open a [new repo](https://github.com/ixtendo/Polyglot-Language-Switcher-2) for it.
https://github.com/ixtendo/Polyglot-Language-Switcher#this-plugin-is-not-maintained-anymore

I decide to add old verions from old repo and add new repo info for this lib.
