### ISSUE TITLE
Add star/fork/watcher info in packages.min.json

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5772]
Program: https://github.com/cdnjs/cdnjs/blob/master/build/packages.json.js
Output:    https://github.com/cdnjs/new-website/blob/master/public/packages.min.json

So that the libraries list can be listed by their popularity, and we can also show the popularity in lib page.

Related issue:
https://github.com/cdnjs/new-website/issues/60

**Comment by NYCJacob** [comment]
would this require calling the github api within the packages.json.js file or is the data already within the rss feed object?

**Comment by PeterDaveHello** [comment]
It'll need to call GitHub API, we already implemented the feature in https://github.com/cdnjs/new-website/blob/master/reindex.js and the result is in https://github.com/cdnjs/new-website/blob/master/GitHub.repos.meta.json, this issue is out dated and should be closed now 😄
