### ISSUE TITLE
[Request] BoomQueries

### ISSUE THREAD

**Issue by zslabs** [cdnjs/cdnjs#5773]
**Library name: BoomQueries** 
**Git repository url: https://github.com/BoomTownROI/boomqueries**
**npm package url(optional): https://www.npmjs.com/package/boomqueries** 
**License(s): MIT**
**Official homepage: http://boomtownroi.github.io/boomqueries/**
**Wanna say something? Leave message here: Would love to have this available as part of your CDN!**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@zslabs sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@zslabs  this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
