### ISSUE TITLE
[Request] jquery-lang

### ISSUE THREAD

**Issue by grcasanova** [cdnjs/cdnjs#5774]
**Library name:** 
Jquery Lang Js
**Git repository url:**
https://github.com/irrelon/jquery-lang-js
**npm package url(optional):** 
**License(s):**
 MIT License (MIT)
 Copyright (c) 2014 Irrelon Software Limited
**Official homepage:**
 http://www.irrelon.com
**Wanna say something? Leave message here:**
Thanks

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We can add this.

**Comment by grcasanova** [comment]
Please let me know once you add it

**Comment by PeterDaveHello** [comment]
@grcasanova of course, we'll close this issue after added it.

**Comment by maruilian11** [comment]
@grcasanova the lib has been added, please take a look :smile:

**Comment by grcasanova** [comment]
thank you :)
