### ISSUE TITLE
[Request] Add axios

### ISSUE THREAD

**Issue by bahrieinn** [cdnjs/cdnjs#5778]
**Library name:** Axios
**Git repository url:** https://github.com/mzabriskie/axios
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/mzabriskie/axios
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mzabriskie** [comment]
@PeterDaveHello @bahrieinn thanks for this! Wondering how long before it shows up here https://cdnjs.com/libraries/axios

**Comment by PeterDaveHello** [comment]
@mzabriskie sorry that we have some issues about our website, but you already can access the files via our cdn by this schema:
https://cdnjs.cloudflare.com/ajax/libs/axios/version/filename

for example:
https://cdnjs.cloudflare.com/ajax/libs/axios/0.1.0/axios.amd.js

thanks!

**Comment by mzabriskie** [comment]
@PeterDaveHello would be great if that link worked so that people can browse available versions. This is the link that comes up in search results on https://cdnjs.com

Also one more question: how long does it take for new versions to be available on the cdn?

Thanks!

**Comment by PeterDaveHello** [comment]
You meant the time between *pushed on GitHub* and *available on cdn* or the time between *release a new version* and *available on cdn*?

**Comment by mzabriskie** [comment]
@PeterDaveHello if I release a new version, how long until it's on the CDN? I tagged `axios@0.7.0` on Github six hours ago, and ran `npm publish` but it still shows `axios@0.6.0` on cdnjs.com search results for axios.

**Comment by PeterDaveHello** [comment]
I think this part can help you, there will be a delay:
https://github.com/cdnjs/cdnjs#enabling-npmrecommended-or-git-auto-update

**Comment by PeterDaveHello** [comment]
@mzabriskie New version added.
