### ISSUE TITLE
Gossip

### ISSUE THREAD

**Issue by neranjan44** [cdnjs/cdnjs#5779]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What is this for?

**Comment by maruilian11** [comment]
@neranjan44 this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
