### ISSUE TITLE
[Request] rpage

### ISSUE THREAD

**Issue by PatSpiegel** [cdnjs/cdnjs#5781]
**Library name:** rpage
**Git repository url:** https://github.com/auxiliary/rpage
**npm package url(optional):** 
**License(s):** GNU GENERAL PUBLIC LICENSE
**Official homepage:** http://auxiliary.github.io/rpage/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PatSpiegel sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
