### ISSUE TITLE
[Request] bencentra/jq-signature

### ISSUE THREAD

**Issue by ais-one** [cdnjs/cdnjs#5783]
Library name: jq-signature
Git repository url: https://github.com/bencentra/jq-signature
npm package url(optional):
License(s): MIT
Official homepage: http://bencentra.github.io/jq-signature/
Wanna say something? Leave message here:

Although it is not popular, the usage for this is quite simple and straight forward.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@ais-one sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@ais-one this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by ais-one** [comment]
Hi noted, will highlight again when repo is more visible. I will close this.
