### ISSUE TITLE
[Request] Add Hyperlapse.js

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5787]
**Library name:** Hyperlapse.js
**Git repository url:** https://github.com/TeehanLax/Hyperlapse.js/
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://hyperlapse.tllabs.io/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems to not act on github for a long time.

**Comment by PeterDaveHello** [comment]
Is it possible to manually add a version for this lib?

**Comment by maruilian11** [comment]
@PeterDaveHello but they didn't mention the version number, can we add the version as v1.0.0?

**Comment by PeterDaveHello** [comment]
Hmmmm ... good catch, maybe you can write an email to him?
If still no response, maybe just use its commit hash as a version ... like 21b0459 , since it has more than 2 thousand stars, it'll be good to add this.

**Comment by maruilian11** [comment]
ok.

**Comment by maruilian11** [comment]
@PeterDaveHello there seems to be no response for a while.

**Comment by PeterDaveHello** [comment]
Close first.
