### ISSUE TITLE
[Request] Shuffle

### ISSUE THREAD

**Issue by leonirlopes** [cdnjs/cdnjs#5788]
**Library name:** Shuffle
**Git repository url:** https://github.com/Vestride/Shuffle
**npm package url(optional):** shufflejs
**License(s):** MIT
**Official homepage:** http://vestride.github.io/Shuffle/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Vestride** [comment]
Thanks @leonirlopes!
