### ISSUE TITLE
[Request] Add sigma.js plugins

### ISSUE THREAD

**Issue by storrgie** [cdnjs/cdnjs#5789]
**Library name:** Sigma.js Plugins 
**Git repository url:** https://github.com/jacomyal/sigma.js/tree/master/plugins
**License(s):** https://github.com/jacomyal/sigma.js/blob/master/LICENSE.txt
**Official homepage:** http://sigmajs.org/

**Comment by maruilian11** [comment]
already on cdnjs
https://cdnjs.com/libraries/sigma.js
