### ISSUE TITLE
[Request] JQuery libraries

### ISSUE THREAD

**Issue by Xarex** [cdnjs/cdnjs#5790]
I see that cdnjs only has one JQuery library, the latest of 3 alpha.

I need older ones to work with some code I am using.  I'd prefer to use cdnjs over Google libraries, but the JQuery libraries on cdnjs are limited.

**Comment by PeterDaveHello** [comment]
which version? I think we have it all.

**Comment by Xarex** [comment]
Hey Peter, looking for 1.4.4/jquery.min.js

**Comment by PeterDaveHello** [comment]
@Xarex This one? https://cdnjs.com/libraries/jquery/1.4.4

**Comment by Xarex** [comment]
Not only are you fast... that was instant, but you know, you are right! I didn't realize there was a dropdown! That is awesome. Thank you :D

**Comment by PeterDaveHello** [comment]
@Xarex np

**Comment by PeterDaveHello** [comment]
@Xarex So I think we can close this issue now?

**Comment by Xarex** [comment]
You have solved my problem so definitely!
