### ISSUE TITLE
angular-ui-grid missing font files

### ISSUE THREAD

**Issue by reupen** [cdnjs/cdnjs#5794]
angular-ui-grid (https://cdnjs.com/libraries/angular-ui-grid) is missing the following files:

* ui-grid.eot
* ui-grid.svg
* ui-grid.ttf
* ui-grid.woff

They are referenced in ui-grid.css and included in the normal distribution of ui-grid:
https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release/3.0.6

**Comment by maruilian11** [comment]
thank you for your reminding, i will add them asap!
