### ISSUE TITLE
[Request] Angular-br-filters

### ISSUE THREAD

**Issue by rafaelbernard** [cdnjs/cdnjs#5797]
**Library name:** Angular-br-filters
**Git repository url:** https://github.com/the-darc/angular-br-filters
**npm package url(optional):** 
**License(s):** The MIT License (MIT)
**Official homepage:** http://the-darc.github.io/angular-br-filters/
**Wanna say something? Leave message here:**
Very useful, stable and needed.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@rafaelbernard Thanks for your suggestion, @LeaYeh please take a look.

**Comment by LeaYeh** [comment]
@PeterDaveHello but this repo doesn't have enough popularity, should we add it? 
or wait for the library has more popularity?

**Comment by PeterDaveHello** [comment]
I didn't say add it but said take a look, so you can decide.

**Comment by LeaYeh** [comment]
Hi @rafaelbernard  ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our README.md for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by rafaelbernard** [comment]
Hi, @LeaYeh. Totally understand your criteria. Thanks for your time. I will spread to word so it can be more popular and open another issue. See ya.
:-)

**Comment by PeterDaveHello** [comment]
So I think  we can close this one now?

**Comment by LeaYeh** [comment]
@rafaelbernard think you :)
@PeterDaveHello yes, i think we can close it
