### ISSUE TITLE
canvas 2 svg

### ISSUE THREAD

**Issue by FernandoBenavides** [cdnjs/cdnjs#5808]
**Library name: canvas2svg
**Git repository url: https://github.com/gliffy/canvas2svg
**npm package url(optional):** 
**License(s):MIT
**Official homepage: http://gliffy.github.io/canvas2svg/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@FernandoBenavides sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@FernandoBenavides this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
