### ISSUE TITLE
[Request] Add angulartics-google-analytics

### ISSUE THREAD

**Issue by sorenh** [cdnjs/cdnjs#5812]
**Library name:** angulartics-google-analytics 
**Git repository url:** https://github.com/angulartics/angulartics-google-analytics
**npm package url(optional):** https://www.npmjs.com/package/angulartics-google-analytics
**License(s):** MIT
**Official homepage:** https://github.com/angulartics/angulartics-google-analytics
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@sorenh sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by sorenh** [comment]
Does it matter that it used to be part of angulartics core, but with the last release, it was split up? Without these plug-ins available alongside angulartics itself, angulartics is pretty useless.

**Comment by maruilian11** [comment]
@PeterDaveHello @cdnjs/intern please take a look.

**Comment by PeterDaveHello** [comment]
yeah we can add it

**Comment by sorenh** [comment]
Sweet! Thanks a lot. cdnjs is super useful!
