### ISSUE TITLE
[Request] Add Google Swiffy runtime

### ISSUE THREAD

**Issue by jhiswin** [cdnjs/cdnjs#5814]
**Library name:**
Google Swiffy runtime

https://www.gstatic.com/swiffy/v7.3.2/runtime.js
https://www.gstatic.com/swiffy/stable/runtime.js

**License(s):**
Proprietary, but free to use/distribute

**Official homepage:**
https://developers.google.com/swiffy/

**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@jhiswin could you please provide `git repository url` or `npm package url`? thank you.

**Comment by maruilian11** [comment]
@jhiswin this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
