### ISSUE TITLE
[Request] angular-read-more

### ISSUE THREAD

**Issue by ismarslomic** [cdnjs/cdnjs#5815]
**Library name:** angular-read-more
**Git repository url:** https://github.com/ismarslomic/angular-read-more
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**  https://github.com/ismarslomic/angular-read-more
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@ismarslomic  sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@ismarslomic this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by ismarslomic** [comment]
Just close it

**Comment by PeterDaveHello** [comment]
Hi @ismarslomic, 

I think you can send a PR in future, and maybe you can consider to provide npm package to help increase the popularity, thanks!
