### ISSUE TITLE
npm auto-updater hangs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5819]
on lib - [turf](https://www.npmjs.com/package/turf) which has 104 releases, the updater will hang, not sure if from 0 to 104 releases is too much for it.

**Comment by PeterDaveHello** [comment]
and seems caused by the error:

`error downloading 0.0.xxx of turf it didnt exist: [object Object]error `

xxx are 76, 78, 83, 77 and 82, pass them it won't hang.

**Comment by PeterDaveHello** [comment]
geojs v0.2.5 has same problem

**Comment by PeterDaveHello** [comment]
okay, seems we should pass the 404 not found versions!

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  - 
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers in Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers in Delhi</a>

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  -
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a> 
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.dteller.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.dteller.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.dteller.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.dteller.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by PeterDaveHello** [comment]
Fixed for a long time ... lol
