### ISSUE TITLE
[Request] skrollr.min.js

### ISSUE THREAD

**Issue by mohsinrahman** [cdnjs/cdnjs#5821]
**Library name:** skrollr.min.js 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
I think you want this?
https://cdnjs.com/libraries/skrollr

**Comment by maruilian11** [comment]
@mohsinrahman this issue will be closed if there is no any response in next 7 day. thank you.
