### ISSUE TITLE
[Request] Together.js

### ISSUE THREAD

**Issue by robintel** [cdnjs/cdnjs#5824]
**Library name: together.js** 
**Git repository url: https://github.com/mozilla/togetherjs**
**npm package url(optional):** 
**License(s): free, open source**
**Official homepage: https://togetherjs.com/**
**Wanna say something? Leave message here: Yes, please add this library! You are doing a great job!**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What files should we include them?

**Comment by maruilian11** [comment]
@robintel this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by robintel** [comment]
Sorry, I missed this comment.

The file to be included should be https://togetherjs.com/togetherjs-min.js .

**Comment by PeterDaveHello** [comment]
Is there a corresponding file on GitHub repo?

**Comment by PeterDaveHello** [comment]
ping

**Comment by maruilian11** [comment]
ping @robintel

**Comment by maruilian11** [comment]
@robintel this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
@ianb @aarondruck, would you guys like to give us comment about this? Thanks a lot!
