### ISSUE TITLE
[Request] Add video.js

### ISSUE THREAD

**Issue by qtvhao** [cdnjs/cdnjs#5827]
**Library name video.js
**Git repository url: https://github.com/videojs/video.js.git
**npm package url(optional):** 
**License(s):**
**Official homepage:**http://www.videojs.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it: https://cdnjs.com/libraries/video.js
