### ISSUE TITLE
[Request] Add _scrollgress 

### ISSUE THREAD

**Issue by bbelhadi** [cdnjs/cdnjs#5830]
**Library name: scrollgress
**Git repository url: https://github.com/michael-lynch/scrollgress
**npm package url(optional):** 
**License(s):**
**Official homepage:**https://plugins.jquery.com/scrollgress/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@bbelhadi sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
