### ISSUE TITLE
[Request] Add Angular Trustpass

### ISSUE THREAD

**Issue by romelgomez** [cdnjs/cdnjs#5832]
**Library name:** Angular Trustpass
**Git repository url:** https://github.com/Trustroots/trustpass
**License(s):** MIT
**Official homepage:** http://trustroots.github.io/trustpass/

**Comment by maruilian11** [comment]
@romelgomez sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by romelgomez** [comment]
ok
