### ISSUE TITLE
[Request] Browserify

### ISSUE THREAD

**Issue by wargun02** [cdnjs/cdnjs#5833]
Library name: Browserify
Git repository url: https://github.com/substack/node-browserify.git
npm package url: https://www.npmjs.com/package/browserify
License(s): MIT
Official homepage: http://browserify.org/
Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
hmmmm ... which file should we include?

**Comment by wargun02** [comment]
Oh pardon me, I got so excited with Browserify that I'd forgotten that it requires bundling all custom modules to be included as one .js. It has a pretty complicated build process though, so, just drop this...

**Comment by PeterDaveHello** [comment]
np
