### ISSUE TITLE
[Request] Add d3-transform [author][new]

### ISSUE THREAD

**Issue by trinary** [cdnjs/cdnjs#5836]
Library name: d3-transform 
Git repository url: https://github.com/trinary/d3-transform
npm package url(optional): https://www.npmjs.com/package/d3-transform
License(s): MIT
Official homepage: https://github.com/trinary/d3-transform
Wanna say something? Leave message here: Had a request for a CDN link from a user here: https://github.com/trinary/d3-transform/issues/13
Just added a minified version, but the library is tiny already.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@trinary Would you likebto send a PR to add this lib?

**Comment by trinary** [comment]
Sure, I wasn't sure if you had some automated way to pull things in, just clicked through from the site. I'll send along a PR later. Thanks!

**Comment by PeterDaveHello** [comment]
@trinary Hmmmm ... we have cdnjs-importer, see.readme for detail :)
