### ISSUE TITLE
[Request] Add Kule Lazy 3

### ISSUE THREAD

**Issue by keicheng** [cdnjs/cdnjs#5837]
**Library name: Kule Lazy** 
**Git repository url: https://github.com/keicheng/kule.lazy**
**npm package url(optional):** 
**License(s): Free**
**Official homepage: http://www.kule.tw**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@keicheng sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by keicheng** [comment]
Hi, my star already 100+, please help me to handle kule.lazy. Thanks!

**Comment by PeterDaveHello** [comment]
@keicheng would you like to send a PR to add your lib?

**Comment by keicheng** [comment]
Sorry, I don`t know what is PR

**Comment by keicheng** [comment]
yes, i want!

**Comment by PeterDaveHello** [comment]
Okay, I'm waiting for you.

**Comment by Amomo** [comment]
As [kule.lazy](https://cdnjs.com/libraries/kule.lazy) has been added, close this issue.

**Comment by PeterDaveHello** [comment]
@Amomo Should refer to the commit instead of the webpage

**Comment by Amomo** [comment]
Oh I see~ I edited it.
