### ISSUE TITLE
[Request] Add angular2

### ISSUE THREAD

**Issue by jimthedev** [cdnjs/cdnjs#5838]
**Library name:**  Angular2
**Git repository url:** https://github.com/angular/angular
**npm package url(optional):** https://www.npmjs.com/package/angular2
**License(s):** Apache-2.0 license
**Official homepage:** http://www.angular.io 
**Wanna say something? Leave message here:** Angular2 is in alpha, but all of the files needed are bundled files are released in the npm package. The bundles are not available on github.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@jimthedev Don't we have it? https://cdnjs.com/libraries/angular.js/2.0.0-alpha.34

**Comment by jimthedev** [comment]
Weird. You do but that is an old version. .38 is out. I'll have to take
another look. It is confusing because now the angular 2 team doesn't call
it angular.js but instead just call it angular. The 1.x branch still goes
by angular.js

**Comment by PeterDaveHello** [comment]
@jimthedev Yeah and i will update it later.

**Comment by PeterDaveHello** [comment]
I added it here https://github.com/cdnjs/cdnjs/commit/37e70edb757e26d4f53c820c1c2a37dff331323e, now you can use it via url like this: https://cdnjs.cloudflare.com/ajax/libs/angular.js/2.0.0-alpha.38/angular2.min.js

@cdnjs/team-cdnjs what do you think about the name issue? I am not really care of change or not due to the conflicts names in cdnjs, we'll change the libs' name because different libs use the same name, or the inconsistent libs' names in libs' package.json/website/GitHub, the name is not 100% same as official name is reasonable and not wired, also in jsDelivr.

**Comment by ryankirkman** [comment]
@PeterDaveHello That naming scheme looks fine for now.

If this becomes a problem we can make a separate `angular2` folder, but if we can I still think it makes sense to keep the next versions of angular under the same folder.

**Comment by drewfreyling** [comment]
Agreed.

**Comment by jimthedev** [comment]
Great, thanks!

**Comment by jimthedev** [comment]
@PeterDaveHello Sorry. They re-released as .39 due to some major bugs. Can you re-release on cdnjs?

Not sure how this works, is there a way to set up some auto update rule?

**Comment by PeterDaveHello** [comment]
@jimthedev currently, no, we can not do auto-update on it. I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@jimthedev btw, will you or other users need the files without `angular2` prefix?
Sorry that I'm not so familiar with angular2, not sure what files are needed for browser, thanks.
https://code.angularjs.org/2.0.0-alpha.39/

**Comment by jimthedev** [comment]
Ideally, yes they'd be included but the angular2 parts are the most
important bundles so if it is a pain for the others you can leave them out.

**Comment by PeterDaveHello** [comment]
So all the files may be used in the browser site?

**Comment by jimthedev** [comment]
Correct.

**Comment by PeterDaveHello** [comment]
though without those files, v2.0.0-alpha.39 been added 3 hours ago, https://github.com/cdnjs/cdnjs/commit/fa0aa66263bf4085c62980d5d57337711ba730e5, I think we can close this issue now?

**Comment by jimthedev** [comment]
Thanks!
