### ISSUE TITLE
[Request] Add Owl Carousel 2

### ISSUE THREAD

**Issue by rahmanroman** [cdnjs/cdnjs#5840]
**Library name:** Owl Carousel 2
**Git repository url:** https://github.com/smashingboxes/OwlCarousel2
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://www.owlcarousel.owlgraphic.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@PeterDaveHello this repo has no stable version, is that ok?

**Comment by PeterDaveHello** [comment]
Depends on its popularity.

**Comment by PeterDaveHello** [comment]
So let's add it.
