### ISSUE TITLE
Deprecate the duplicated lib but with different structure

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5842]
Some libs are duplicated, but can not be migrated/merged(https://github.com/cdnjs/cdnjs/issues/5287) easily due to its different structure, like:

https://cdnjs.com/libraries/spectrum
https://cdnjs.com/libraries/spectrum-i18n

https://cdnjs.com/libraries/angular.js
https://cdnjs.com/libraries/angular-i18n

So should add deprecated property to the lib, and also point to the duplicated but under maintained lib on the website.

**Comment by PeterDaveHello** [comment]
I think we could use something like this (use spectrum-i18n as an example), in package.json:
```js
  "deprecated": {
     "status": "true",
     "replacementLib": "spectrum"
  }
```

So users can easily know `spectrum-i18n` was deprecated and should now take a look at the lib named `spectrum` on cdnjs instead of `spectrum-i18n`.

I need comments, cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  - 
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers in Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers in Delhi</a>

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  -
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a> 
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.dteller.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.dteller.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.dteller.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.dteller.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by MattIPv4** [comment]
This seems like a really niche issue with no progress, closing.
