### ISSUE TITLE
[Request] particles.js

### ISSUE THREAD

**Issue by spartanier7777** [cdnjs/cdnjs#5847]
**Library name: particles.js** 
**Git repository url: https://github.com/VincentGarreau/particles.js/**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage:http://vincentgarreau.com/particles.js/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Amomo please take this.
