### ISSUE TITLE
[Request] jQuery Nestable

### ISSUE THREAD

**Issue by skibulk** [cdnjs/cdnjs#5848]
**Library name:** jQuery Nestable
**Git repository url:** https://github.com/dbushell/Nestable
**npm package url(optional):** 
**License(s):** Copyright © 2012 David Bushell | BSD & MIT license
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Piicksarn please take it.

**Comment by Piicksarn** [comment]
[ Create package.json #173 ](https://github.com/dbushell/Nestable/pull/173)

**Comment by PeterDaveHello** [comment]
@Piicksarn if there is no rapid response, just create a package.json for it in cdnjs, thanks.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i got it.

**Comment by PeterDaveHello** [comment]
Ping @Piicksarn

**Comment by Piicksarn** [comment]
The lib would be added as the tags used. :smiley_cat:
