### ISSUE TITLE
responsive-nav.js is serving css instead of js

### ISSUE THREAD

**Issue by andrewjohnstrong** [cdnjs/cdnjs#5851]
![screen shot 2015-10-08 at 1 04 49 pm](https://cloud.githubusercontent.com/assets/654760/10355931/31e191d0-6dbd-11e5-8494-16c28ba25ccd.png)

**Comment by PeterDaveHello** [comment]
@andrewjohnstrong sorry, we use the `filename` field in package.json to make sure some files been minified, now we have `requiredFiles` field to make sure this, the main file should be the same type as the lib, maruilian11 please take this.

**Comment by andrewjohnstrong** [comment]
Thanks!
