### ISSUE TITLE
test more continuous integration online service

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5854]
circleCI recently became not stable/reliable, travis-ci is still unusable for such a huge repo, we need some alternative platform to perform the test.

Comments are welcome!

cc @cdnjs/intern @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
List some choices with free plan for open source project here
 - [ ] https://drone.io/
 - [ ] https://semaphoreci.com/

**Comment by IonicaBizau** [comment]
@PeterDaveHello Couldn't we fix the root issue: to find a solution not having such a huge repository?

**Comment by PeterDaveHello** [comment]
@IonicaBizau yes we can, and still have not found a good solution.

**Comment by IonicaBizau** [comment]
@PeterDaveHello What if we would keep in the repository only the `package.json` files and the other files will be git-ignored and downloaded by some script?

**Comment by PeterDaveHello** [comment]
If we want to totally removed the files from git, the `script` should be very clear about its policy and mechanism, I think we haven't found it.

No matter what method we will use in future, I hope they'll be 100% opened, not only the mechanism and policy, but also the real things it did, everybody can easily see the inside, audit and trace it.

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  - 
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers in Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers in Delhi</a>

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  -
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a> 
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>

**Comment by IonicaBizau** [comment]
@akashseo963 Stop the spam–reported you already. :boom:

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.dteller.in/packers-and-movers-gurgaon/" title="Packers and Movers in Gurgaon">Packers and Movers in Gurgaon</a>
<a href="http://www.dteller.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.dteller.in/packers-and-movers-hyderabad/" title="Packers and Movers in Hyderabad">Packers and Movers in Hyderabad</a>
<a href="http://www.dteller.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>

**Comment by PeterDaveHello** [comment]
@IonicaBizau Thanks.

**Comment by LeaYeh** [comment]
@PeterDaveHello , i found nearly pull requests ware almost fail in online test, is it because we use new ci server?
if that is true then what should we do to make sure local test is correct？

**Comment by PeterDaveHello** [comment]
@LeaYeh no ...  bacause it failed ... so we need to find other choice ...

**Comment by PeterDaveHello** [comment]
@LeaYeh create a clean environment for the test will work.

**Comment by LeaYeh** [comment]
@PeterDaveHello what do you mean "create a clean environment" ? reclone all repo again?

**Comment by PeterDaveHello** [comment]
@LeaYeh Only cdnjs repo.

**Comment by maruilian11** [comment]
so if we stop using sparse checkout, the problem will be solved?

**Comment by PeterDaveHello** [comment]
@maruilian11 of course not ...

**Comment by maruilian11** [comment]
@PeterDaveHello do we need to keep sending PR?

**Comment by PeterDaveHello** [comment]
@maruilian11 That's not a problem about send or not ...

**Comment by PeterDaveHello** [comment]
We now have self hosting https://ci.cdnjs.com/cdnjs/cdnjs by Drone CI
