### ISSUE TITLE
[Request] Add Angular.Less

### ISSUE THREAD

**Issue by w3core** [cdnjs/cdnjs#5855]
**Library name:** angular.less
**Git repository url:** https://github.com/AngularLess/angular.less
**npm package url(optional):** https://www.npmjs.com/package/angular.less
**License(s):** BSD License
**Official homepage:** https://angularless.github.io/
**Bower package name:** angular.less
**Bower package url:** http://bower.io/search/?q=angular.less
**Libraries.io url:** https://libraries.io/npm/angular.less
**Wanna say something? Leave message here:**
This directive allows you to add Less and PrefixFree on the fly support for your Angular application.
Working example is here: https://angularless.github.io/

**Comment by maruilian11** [comment]
@w3core sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
Hi @w3core 
This issue will be closed if there is no any response in next 7 day. Thank you for your contribution. :-)

**Comment by PeterDaveHello** [comment]
Hey don't steal my assign :smile:

**Comment by Piicksarn** [comment]
Closed due to no response.
