### ISSUE TITLE
[Request] Add min.css 

### ISSUE THREAD

**Issue by w3core** [cdnjs/cdnjs#5856]
**Library name:** min.css
**Git repository url:** https://github.com/w3core/min.css
**npm package url(optional):** https://www.npmjs.com/package/min.css
**License(s):** BSD License
**Official homepage:** https://rawgit.com/w3core/min.css/master/demo.html
**Online version:** https://rawgit.com/w3core/min.css/master/demo.html
**Wanna say something? Leave message here:**
min.css is a tiny, ultrafast and efficient JavaScript library for minifying CSS files that really makes your website faster.

**Comment by maruilian11** [comment]
@w3core sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
@w3core  this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)

**Comment by Amomo** [comment]
Close due to no response.
