### ISSUE TITLE
countdownjs

### ISSUE THREAD

**Issue by weishiji** [cdnjs/cdnjs#5857]
**Library name:** Countdown
**Git repository url:**https://github.com/mckamey/countdownjs
**npm package url(optional):** 
**License(s):*MIT*
**Official homepage:**http://countdownjs.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mckamey** [comment]
Please make the id for this "countdownjs" so that it matches the other CDN instances:

https://github.com/mckamey/countdownjs/issues/2
