### ISSUE TITLE
[Request] Add Paradeiser [author]

### ISSUE THREAD

**Issue by lucidlemon** [cdnjs/cdnjs#5859]
**Library name:** Paradeiser
**Git repository url:** https://github.com/lucidlemon/paradeiser
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://lucidlemon.github.io/paradeiser/
**Wanna say something? Leave message here:** Paradeiser is an easy to use menu for mobile views, it is very easy to include and is pretty lightweight as well. It is sort of an alternative to the Hamburger menu.

**Comment by PeterDaveHello** [comment]
@lucidlemon would you like to send a PR to add this lib?

**Comment by maruilian11** [comment]
@lucidlemon this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
@maruilian11 please use PR to close valid issue though there is no response.

**Comment by maruilian11** [comment]
@PeterDaveHello got it.

**Comment by lucidlemon** [comment]
thanks a lot guys. i'm not that familiar with git and didn't know how to do that and got no answer on gitter. thanks for your work!

**Comment by maruilian11** [comment]
:+1:
