### ISSUE TITLE
[Request] Add Kule Lazy 3

### ISSUE THREAD

**Issue by keicheng** [cdnjs/cdnjs#5860]
**Library name: Kule Lazy** 
**Git repository url:keicheng/kule.lazy**
**npm package url(optional):** 
**License(s):Free**
**Official homepage:http://www.kule.tw**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #5837.

**Comment by keicheng** [comment]
Sorry, it`s duplicated
