### ISSUE TITLE
[Request] auto-update on ckeditor

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#5865]
**Library name:** ckeditor
**Release repo:** https://github.com/ckeditor/ckeditor-releases

cc #5863

**Comment by cwingrav** [comment]
Thanks! But it needs the config.js file as well for 4.5.x releases.

**Comment by PeterDaveHello** [comment]
@cwingrav I'll add them back soon.

**Comment by PeterDaveHello** [comment]
@cwingrav https://github.com/cdnjs/cdnjs/commit/15f8158e6477faf65be89bb05bbc18ec7339647f added.

**Comment by cwingrav** [comment]
Just tested. Works. Great work!
