### ISSUE TITLE
[Request] Add vue-strap

### ISSUE THREAD

**Issue by yuche** [cdnjs/cdnjs#5867]
**Library name:** vue-strap
**Git repository url:** https://github.com/yuche/vue-strap
**npm package url(optional):** https://www.npmjs.com/package/vue-strap
**License(s):** MIT
**Official homepage:** http://yuche.github.io/vue-strap/
**Wanna say something? Leave message here:**
Bootstrap components built with Vue.js.

**Comment by mpociot** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
npm package outdated, reported here:
https://github.com/yuche/vue-strap/issues/10
