### ISSUE TITLE
[Request] Update angular-ui-bootstrap to  0.14.0

### ISSUE THREAD

**Issue by ali-habibzadeh** [cdnjs/cdnjs#5868]
**Library name:*angular-ui-bootstrap* 
**Git repository url:*https://github.com/angular-ui/bootstrap*
**npm package url(optional):** 
**License(s):*MIT*
**Official homepage:*https://angular-ui.github.io/bootstrap/*
**Wanna say something? Leave message here:*Ver 0.14.0*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ali-habibzadeh** [comment]
Thank you for adding this.

**Comment by PeterDaveHello** [comment]
updated https://cdnjs.com/libraries/angular-ui-bootstrap to v0.14.1
