### ISSUE TITLE
[Request] Add aja.js

### ISSUE THREAD

**Issue by pyoio** [cdnjs/cdnjs#5872]
**Library name:** Aja.js
**Git repository url:** https://github.com/krampstudio/aja.js
**npm package url(optional):** aja
**License(s):** MIT
**Official homepage:** http://krampstudio.com/aja.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Aja.js has been added by dc44fa32ba00d40c13a765680f0bb902a12793c9
