### ISSUE TITLE
[Request] Add SignalR

### ISSUE THREAD

**Issue by CreativeColon** [cdnjs/cdnjs#5878]
**Library name:** SignalR
**Git repository url:** https://github.com/SignalR/SignalR
**License(s):** Apache 2.0 License
**Official homepage:** http://signalr.net

I actually wanted to add SignalR to cdnjs myself and make a PR, but cloning this repo is taking forever with all those files. Can someone please add SignalR to this repo that would be great :)

**Comment by maruilian11** [comment]
@cdnjs/intern i'm not sure what files need to be added. some advice? thanks~

**Comment by Amomo** [comment]
I guess there will be a "jquery.signalR.js" and "jquery.signalR.min.js" after building the library.
Because many "samples/ ** / *.html " can see including the file "jquery.signalR.js"
But, I have no idea to build the library...

**Comment by CreativeColon** [comment]
Exactly **jquery.signalR.js** and **jquery.signalR.min.js** are the files that needs to be hosted. I'm actually thinking about turning SignalR into a nodejs package coz that would be easy and it also complies with cdnjs contribution guidelines.... ;)

**Comment by CreativeColon** [comment]
Resolved with #6128
