### ISSUE TITLE
[Request] angular-boostrap-toggle

### ISSUE THREAD

**Issue by ziscloud** [cdnjs/cdnjs#5886]
**Library name:** angular-boostrap-toggle
**Git repository url:** https://github.com/ziscloud/angular-bootstrap-toggle
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://ziscloud.github.io/angular-bootstrap-toggle
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@ziscloud , thanks for your suggestion！

However, [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) shows that :
```>
Libraries must have notable popularity: 100 stars or watchers on GitHub is a good example, 
but as long as reasonable popularity can be demonstrated the library will be added.
```

Would you please make a request again when the library has notable popularity? :smiley:

**Comment by maruilian11** [comment]
@ziscloud this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by ziscloud** [comment]
what a pity, I will raise the request once I got the popularity.
