### ISSUE TITLE
SHA1 certificate being used - causes warnings

### ISSUE THREAD

**Issue by clach04** [cdnjs/cdnjs#5899]
Firefox dev console displays warnings when using any library over https from cdnjs:

    This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.

See https://developer.mozilla.org/en-US/docs/Web/Security/Weak_Signature_Algorithm

**Comment by PeterDaveHello** [comment]
Duplicated with #4807 and thanks for your report.
