### ISSUE TITLE
[Request] jquery.alphanum.js

### ISSUE THREAD

**Issue by erkanisik1** [cdnjs/cdnjs#5901]
**Library name:jquery.alphanum.js 
**Git repository url:https://github.com/KevinSheedy/jquery.alphanum
**npm package url(optional):** 
**License(s):MIT License
**Official homepage:https://github.com/KevinSheedy/jquery.alphanum
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@erkanisik1 sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
@erkanisik1 this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)

**Comment by Amomo** [comment]
Closed due to no response.

**Comment by PeterDaveHello** [comment]
I think this lib looks okay to be added.
