### ISSUE TITLE
[Request] Add Jarty

### ISSUE THREAD

**Issue by zubapita** [cdnjs/cdnjs#5902]
**Library name:Jarty
**Git repository url:https://github.com/kotas/jarty
**npm package url(optional):** 
**License(s):The MIT License
**Official homepage:http://jarty.kotas.jp/
**Wanna say something? Leave message here:Jarty is vary covinience and robust. please add to CDN.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@zubapita sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
@zubapita  this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)

**Comment by Amomo** [comment]
Close due to no response.
