### ISSUE TITLE
[author] jquery.lazy not updating?!

### ISSUE THREAD

**Issue by eisbehr-** [cdnjs/cdnjs#5905]
Hello,

I'll updated the project yesterday and it is allready available on all other auto-updated sites. Only cdnjs is currently missing. Is something wrong on my site or what could i do?

Thanks in advance!

Daniel

**Comment by maruilian11** [comment]
hi @eisbehr- we just add [v0.6.1](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/jquery.lazy/0.6.1) few hours ago, it would be on cdnjs soon :smiley:

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/jquery.lazy/0.6.1
