### ISSUE TITLE
[Request] Add ractive-touch

### ISSUE THREAD

**Issue by avendiart** [cdnjs/cdnjs#5908]
**Library name:** ractive-touch
**Git repository url:** https://github.com/rstacruz/ractive-touch
**npm package url(optional):** https://www.npmjs.com/package/ractive-touch
**License(s):** MIT
**Official homepage:** http://ricostacruz.com/ractive-touch/

**Comment by maruilian11** [comment]
@avendiart sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by maruilian11** [comment]
@avendiart this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by Amomo** [comment]
Close due to no response.
