### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by danielsun174** [cdnjs/cdnjs#5918]
**Skinnytip** 
**https://github.com/elliottb/skinnytip**
**npm package url(optional):** 
**License(s):**
**http://www.ebrueggeman.com/skinnytip**
****

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@danielsun174  sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by danielsun174** [comment]
Okay I haven't seen the point at the README.md
Thank you for the fast answer. closing issue..
