### ISSUE TITLE
[Request] Add superscrollorama

### ISSUE THREAD

**Issue by rraulinio** [cdnjs/cdnjs#5924]
**Library name: superscrollorama** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@rraulinio please provide the `git repo url` or `npm package url` of the lib.

**Comment by maruilian11** [comment]
@rraulinio this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
https://github.com/johnpolacek/superscrollorama ?

**Comment by rraulinio** [comment]
Yep, this.

On Sat, Oct 17, 2015 at 9:05 AM, Peter Dave Hello <notifications@github.com>
wrote:

> https://github.com/johnpolacek/superscrollorama ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cdnjs/cdnjs/issues/5924#issuecomment-148888102>.
>



-- 
[image: --]
Raul Mircea Crivineanu
[image: http://]sefulgalaxiei.me

**Comment by maruilian11** [comment]
@PeterDaveHello this lib seems not going to add new version, do we need to add git auto-update, too?
https://github.com/johnpolacek/superscrollorama#superscrollorama-has-been-replaced-by-scrollmagic

**Comment by rraulinio** [comment]
Not really

**Comment by PeterDaveHello** [comment]
we can add both, and with auto-update.

**Comment by maruilian11** [comment]
ok.

**Comment by rraulinio** [comment]
Ok
