### ISSUE TITLE
[Request] Add bootstrap-rating

### ISSUE THREAD

**Issue by favstay** [cdnjs/cdnjs#5926]
**Library name:Bootstrap Rating** 
**Git repository url:https://github.com/dreyescat/bootstrap-rating**
**npm package url(optional):** 
**License(s):MIT **
**Official homepage:http://dreyescat.github.io/bootstrap-rating/**
**Wanna say something? Leave message here:Thanks for greate cdn server**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Looks okay to add this lib, assign to @Amomo
