### ISSUE TITLE
[Request] LoadGo

### ISSUE THREAD

**Issue by franverona** [cdnjs/cdnjs#5927]
**Library name:** LoadGo
**Git repository url:** https://github.com/franverona/loadgo
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://franverona.com/loadgo/
**Wanna say something? Leave message here:** LoadGo is a JQuery plugin for using your logo as a progress bar.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by franverona** [comment]
Thanks team! :D :+1:

**Comment by maruilian11** [comment]
:smile:
