### ISSUE TITLE
[Request] SignalR

### ISSUE THREAD

**Issue by ch3tanp** [cdnjs/cdnjs#5934]
**Library name:SignalR** 
**Git repository url: https://github.com/SignalR/SignalR**
**npm package url(optional):** 
**License(s):http://www.apache.org/licenses/LICENSE-2.0**
**Official homepage:http://signalr.net/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
#5878
