### ISSUE TITLE
[Request] Add Angular Timer

### ISSUE THREAD

**Issue by donnes** [cdnjs/cdnjs#5935]
**Library name:** Angular Timer
**Git repository url:** https://github.com/siddii/angular-timer/
**npm package url(optional):** https://www.npmjs.com/package/angular-timer
**License(s):** https://github.com/siddii/angular-timer/blob/master/LICENSE.txt
**Official homepage:** http://siddii.github.io/angular-timer/index.html#
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by polomarcus** [comment]
Thanks for the integration, guys

Hey @siddii, angular-timer can be found on https://cdnjs.com/libraries/angular-timer :+1:

**Comment by PeterDaveHello** [comment]
:+1:
