### ISSUE TITLE
Mustang-Modal

### ISSUE THREAD

**Issue by ysfzun** [cdnjs/cdnjs#5937]
**Library name:*Mustang-Modal* 
**Git repository url:*https://github.com/ysfzun/Mustang-Modal*
**npm package url(optional):** 
**nuget package url:*https://www.nuget.org/packages/mustang-modal/* 
**License(s):*https://github.com/ysfzun/Mustang-Modal/blob/master/LICENSE.md*
**Official homepage:**
**Wanna say something? Leave message here:*No html no cry. Many currently used modals use html codes prepared actually for the web page. Mustang-modal, allows you to create new modals interacted with javascript codes without the need of any html. It is simple, easy to use and it has many a lot of features.*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@ysfzun sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
Hi @ysfzun 
This issue will be closed if there is no any response in next 7 day. Thank you for your contribution. :-)

**Comment by ysfzun** [comment]
Hi @Amomo and @maruilian11,
Thanks for the feedback. Not yet I have 4 stars :)  Done, I'm closing this issue.

Have a nice day.
