### ISSUE TITLE
[Request] Add Owl Carousel 2

### ISSUE THREAD

**Issue by RedCreepster** [cdnjs/cdnjs#5953]
**Library name:** Owl Carousel 2
**Git repository url:** https://github.com/smashingboxes/OwlCarousel2
**npm package url(optional):** https://github.com/smashingboxes/OwlCarousel2
**License(s):** MIT
**Official homepage:** http://www.owlcarousel.owlgraphic.com/

**Comment by PeterDaveHello** [comment]
Duplicated with #5840
