### ISSUE TITLE
[Request] caption.js

### ISSUE THREAD

**Issue by efarrell** [cdnjs/cdnjs#5959]
**Library name:** caption.js
**Git repository url:** https://github.com/ericmagnuson/captionjs
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://captionjs.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
Hi @efarrell  ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our README.md for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)
