### ISSUE TITLE
[Request] vkbeautify

### ISSUE THREAD

**Issue by RustyDev** [cdnjs/cdnjs#5960]
**Library name:** vkbeautify
**Git repository url:** https://github.com/vkiryukhin/vkBeautify
**npm package url(optional):** 
**License(s):** MIT, GPL
**Official homepage:** http://www.eslinstructor.net/vkbeautify/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @RustyDev ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
@RustyDev this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by Amomo** [comment]
closed due to no response.
