### ISSUE TITLE
[Request] jquery-ui-bootstrap

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#5962]
**Library name:** jquery-ui-bootstrap
**Git repository url:**https://github.com/jquery-ui-bootstrap/jquery-ui-bootstrap
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
plz help to update, thks.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
@cdnjs/intern Hi everyone,
jquery-ui-bootstrap needs to be updated to v1.0.0. (we have v0.5.0)
But there are too many files, I am not sure which files should we host...😰

And, there are some files duplicate with other libraries **cdnjs already host**.
```
[jquery-ui-bootstrap] v1.0.0

assets/css/bootstrap.min.css = [twitter-bootstrap]  <v0.5.0 has>
assets/fonts/glyphicons-halflings-regular.+(eot|svg|ttf|woff)

assets/css/font-awesome.min.css = [font-awesome]  <v0.5.0 has>
assets/css/font/fontawesome-webfont.+(eot|svg|ttf|woff)

assets/js/google-code-prettify/* = [google-code-prettify]
assets/js/vendor/holder.js = [holder]
assets/js/vendor/html5shiv.js = [html5shiv]
assets/js/vendor/jquery-1.9.1.min.js = [jquery]
assets/js/vendor/jquery-migrate-1.2.1.min.js = [jquery-migrate]
assets/js/vendor/jquery-ui-1.10.3.custom.min.js = [jquery-ui]
assets/js/vendor/less-1.4.2.min.js = [less.js]
assets/js/vendor/respond.min.js = [respond.js]

third-party/jqGrid/* = [jqgrid]
```
Some libraries cdnjs don't host them, but I think they aren't belong to jquery-ui-bootstrap.
```
third-party/gmap3
third-party/jQuery-UI-Date-Range-Picker  <v0.5.0 has>
third-party/jQuery-UI-FileInput  <v0.5.0 has>
third-party/wijmo  <v0.5.0 has>
```

Should we keep all these files in jquery-ui-bootstrap v1.0.0?

Or, should we follow v0.5.0 structure...
keep `twitter-bootstrap`, `font-awesome`, `jQuery-UI-Date-Range-Picker`, `jQuery-UI-FileInput` and `wijmo` in v1.0.0, but don't add other duplicate libraries?

Or any different way?
Could you give me some suggestions? Thank you very much!

**Comment by maruilian11** [comment]
i think just follow v0.5.0, we usually add lib created by author own, don't we?

**Comment by dakshshah96** [comment]
I'm happy to help with this issue. The latest release of jQuery UI Bootstrap is v1.0 alpha. Should we put that up on cdnjs? @PeterDaveHello @maruilian11 @pvnr0082t

**Comment by maruilian11** [comment]
@dakshshah96 Yes, we need 1.0.0. Thanks for helping!

**Comment by MattIPv4** [comment]
Library no longer maintained, closing.
