### ISSUE TITLE
[Request] fabricjs

### ISSUE THREAD

**Issue by awehring** [cdnjs/cdnjs#5964]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @awehring please provide the `git repo url` or `npm package url` of the lib.

**Comment by awehring** [comment]
Sorry, was a handling error from my side.

**Comment by Amomo** [comment]
We have fabricjs already~ :-)
https://cdnjs.com/libraries/fabric.js
