### ISSUE TITLE
[Request] Add InversifyJS

### ISSUE THREAD

**Issue by remojansen** [cdnjs/cdnjs#5967]
**Name: InversifyJS** 
**Git Repo: https://github.com/inversify/InversifyJS.git**
**npm: https://www.npmjs.com/package/inversify** 
**License: MIT** 
**Website: http://inversify.io** 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @remojansen ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
@remojansen this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by remojansen** [comment]
Hi @maruilian11 and @Amomo I will create a new issue once I earn 100 starts thanks for your help
