### ISSUE TITLE
[Request] Add select2-bootstrap-theme

### ISSUE THREAD

**Issue by jonashaag** [cdnjs/cdnjs#5984]
**Library name:** select2-bootstrap-theme
**Git repository url:** https://github.com/select2/select2-bootstrap-theme
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/select2/select2-bootstrap-theme

**Comment by Piicksarn** [comment]
@jonashaag, the library would be considered after the stable version released!
Thank you for the suggestion! :smiley: 

Piicksarn

**Comment by PeterDaveHello** [comment]
@Piicksarn can you talk to the author and confirm that is there will be a stable soon?

**Comment by chipco** [comment]
I used this in 2 projects already and I had no problems with it. Also it's the only option that worked out of the box with bootstrap 3.3.5 and select 4.0.0.
