### ISSUE TITLE
[Request] Add Lity

### ISSUE THREAD

**Issue by user00265** [cdnjs/cdnjs#5986]
**Library name:** Lity
**Git repository url:** https://github.com/jsor/lity
**npm package url(optional):** https://www.npmjs.com/package/lity
**License(s):** MIT
**Official homepage:** http://sorgalla.com/lity/
**Wanna say something? Leave message here:**

**Comment by Amomo** [comment]
Hi @user00265  ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by PeterDaveHello** [comment]
This lib has good structure and also been hosted on npm, I think we can add it.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i got it! :+1:

**Comment by PeterDaveHello** [comment]
Ping @Piicksarn
