### ISSUE TITLE
[Request] Add jssor slider

### ISSUE THREAD

**Issue by leim** [cdnjs/cdnjs#5989]
**Library name:** jssor slider
**Git repository url:** https://github.com/jssor/slider
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://www.jssor.com/
**Wanna say something? Leave message here:**
I think this is a wonderful slider library and userful.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @leim this issue is duplicated with #5563 
**jssor** is going to be added, please wait for PR #5999
