### ISSUE TITLE
eol-style issues

### ISSUE THREAD

**Issue by glensc** [cdnjs/cdnjs#5990]
what's statement and guidelines for mixed LF from files?

```
[master (root-commit) 822b660] import libraries from cdnjs.com. refs 153a823
warning: CRLF will be replaced by LF in cdn/ajax/libs/jquery.colorbox/1.3.34/i18n/jquery.colorbox-ru.js.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in cdn/ajax/libs/jquery.colorbox/1.4.37/i18n/jquery.colorbox-fa.js.
```
- should add `.gitattributes` to project root to configure them for all users?
- should bug upstream to using proper line endings?
- whoever makes pull request should ensure proper line endings?

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by PeterDaveHello** [comment]
In most cases, use upstreams' origin, if there is a problem, we can file an issue to upstream,

**Comment by MattIPv4** [comment]
Closing, no further progress.
