### ISSUE TITLE
bghorizoncont

### ISSUE THREAD

**Issue by dearza** [cdnjs/cdnjs#5991]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @deanius please provide the `git repo url` or `npm package url` of the lib.

**Comment by maruilian11** [comment]
@deanius this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by Piicksarn** [comment]
Closed due to no response!
