### ISSUE TITLE
[Request] Add EasyAutocomplete

### ISSUE THREAD

**Issue by mcalsada** [cdnjs/cdnjs#5992]
**Library name:** EasyAutocomplete
**Git repository url:** https://github.com/pawelczak/EasyAutocomplete
**npm package url(optional):** https://www.npmjs.com/package/easy-autocomplete
**License(s):** MIT
**Official homepage:** http://http://easyautocomplete.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @mcalsada ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
@mcalsada this issue will be closed if there is no any response in next 7 day. thank you for your contribution.

**Comment by Piicksarn** [comment]
Closed due to no response.
