### ISSUE TITLE
[Request] Add ueditor

### ISSUE THREAD

**Issue by leim** [cdnjs/cdnjs#6002]
**Library name:** ueditor
**Git repository url:** https://github.com/fex-team/ueditor
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://ueditor.baidu.com/website/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
https://github.com/fex-team/ueditor/issues/2352
I have asked the author if they could put the compiled files on the repo.
Seems no answer till now :(

**Comment by PeterDaveHello** [comment]
If there is no response for more then a month, I think we just close the issue for the meantime.

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close
