### ISSUE TITLE
[Request] Add eventproxy

### ISSUE THREAD

**Issue by leim** [cdnjs/cdnjs#6003]
**Library name:** eventproxy
**Git repository url:** https://github.com/JacksonTian/eventproxy
**npm package url(optional):** https://www.npmjs.com/package/eventproxy
**License(s):** MIT
**Official homepage:** http://html5ify.com/eventproxy/
**Wanna say something? Leave message here:**
An implementation of task/event based asynchronous pattern.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by JacksonTian** [comment]
thanks.

**Comment by PeterDaveHello** [comment]
np
