### ISSUE TITLE
[Request] Add angular-ui-router-styles

### ISSUE THREAD

**Issue by jejepage** [cdnjs/cdnjs#6017]
**Library name:** angular-ui-router-styles
**Git repository url:** https://github.com/manuelmazzuola/angular-ui-router-styles
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/manuelmazzuola/angular-ui-router-styles
**Wanna say something? Leave message here:**
I am using this library and it would be awesome to include it from CDN. Thank you!

**Comment by LeaYeh** [comment]
Hi @jejepage  ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our README.md for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by LeaYeh** [comment]
@jejepage due to no response so i close it.
