### ISSUE TITLE
datatables includes copy of jquery

### ISSUE THREAD

**Issue by glensc** [cdnjs/cdnjs#6018]
https://cdnjs.com/libraries/datatables/1.10.9

i.e:
https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.9/js/jquery.js

imho this is wrong.

ps: i don't ask to fix existing versions, but would be nice to solve it for future versions

**Comment by PeterDaveHello** [comment]
hmmmm ... the auto-update config:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/datatables/package.json#L32

**Comment by PeterDaveHello** [comment]
@cdnjs/intern please try a better config, thanks.

**Comment by LeaYeh** [comment]
got it, i will be careful in future versions.

**Comment by glensc** [comment]
can the existing `package.json` be fixed? or that would trigger autoupdate without the mentioned file?

**Comment by PeterDaveHello** [comment]
@LeaYeh I meant please fix it :smile: 
Yes, it's in package.json, or if you want, you can also send a PR :+1:
