### ISSUE TITLE
[Request] Add ally.js

### ISSUE THREAD

**Issue by rodneyrehm** [cdnjs/cdnjs#6020]
**Library name:** ally.js
**Git repository url:** https://github.com/medialize/ally.js
**npm package url(optional):** https://www.npmjs.com/package/ally.js
**License(s):** MIT
**Official homepage:** https://github.com/medialize/ally.js
**Wanna say something? Leave message here:**
Please pull the library from npm, the git repository does not contain built artifacts.
I would like to access the "beta" dist tag if possible, (what `npm install ally.js@beta` gives you)

**Comment by Amomo** [comment]
Hi @rodneyrehm ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
We suggest you open an issue again when the library has more popularity.

Thanks for your contribution. :-)

**Comment by ryankirkman** [comment]
@Amomo This is fine. Please add this library to cdnjs :)

**Comment by rodneyrehm** [comment]
Thank you very much! I've added `npmName` and (a very limited) `npmFileMap` and pushed version `1.0.0-beta.3` to npm.

**Comment by PeterDaveHello** [comment]
@Amomo so please add this.

**Comment by rodneyrehm** [comment]
Do I have to push an official release (dist-tag latest) to npm before this can proceed? Currently the beta channel holds `ally.js@1.0.0-beta.6`, but I can publish that officially any time now. I just wanted to minimize the latency between the thing being on npm and the website going live (because it's depending on cdnjs)…

**Comment by PeterDaveHello** [comment]
@rodneyrehm it'll be great if you can have a stable version first, and I can also take this issue for you.

**Comment by rodneyrehm** [comment]
Ok, having triple checked everything I could, version `1.0.0` is now available on [npm](https://www.npmjs.com/package/ally.js).

Now I'll wait for cdnjs to serve the files to publish the website :)

For future reference, is the update from npm to cdnjs automatic or do I need to bump this issue each time? If it's automatic, what's the latency?

and *thank you*!

**Comment by PeterDaveHello** [comment]
ping @Amomo

**Comment by rodneyrehm** [comment]
ping @PeterDaveHello @Amomo - could we get this done today? Did I do something wrong in package.json?

**Comment by PeterDaveHello** [comment]
@rodneyrehm there is no `dist` folder under ally.js@1.0.0, may I know what's the reason why? We will need it for auto-update.

**Comment by PeterDaveHello** [comment]
As you are the author @rodneyrehm, I think you can also try to send a PR, it'll be faster.

**Comment by rodneyrehm** [comment]
> there is no dist folder under ally.js@1.0.0, may I know what's the reason why? We will need it for auto-update.

Is cdnjs using the package.json from the repository, or the one in npm? The one actually published to npm is adjusted accordingly and contains:

```
"npmFileMap": [
  {
    "basePath": "./",
    "files": [
      "ally.min.js",
      "ally.min.js.map"
    ]
  }
],
```

> I think you can also try to send a PR, it'll be faster.

sure! I'll fix the repository's package.json to reflect the state that is published to npm and then work through the steps in your [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md)

**Comment by rodneyrehm** [comment]
package.json has been aligned and 1.0.1 is published to npm

**Comment by rodneyrehm** [comment]
@PeterDaveHello I've sent the PR. Boy, adding a library this way is quite a piece of work…
