### ISSUE TITLE
[Request] error-shelter

### ISSUE THREAD

**Issue by crobinson42** [cdnjs/cdnjs#6023]
error-shelter
Git repository url: https://github.com/crobinson42/error-shelter
npm package url(optional): https://www.npmjs.com/package/error-shelter
License(s): MIT

This is a new module and a very useful small library for use with error tracking and debugging apps. 

I'm currently building an official site for it and will be spreading the word for more use. I use it in a very simple manner, if there is an Error thrown or console.error(..) on the page, it's caught and stowed away, if the page is able to continue executing JS it will make a $.post request to my backend logging endpoint with the full Error, stack, message, etc.. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@crobinson42 sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
@crobinson42  this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)
