### ISSUE TITLE
[Request] [new] [author] Add Trix

### ISSUE THREAD

**Issue by javan** [cdnjs/cdnjs#6024]
**Library name: Trix** 
**Git repository url: https://github.com/basecamp/trix**
**npm package url: https://www.npmjs.com/package/trix** 
**License: MIT**
**Official homepage: http://trix-editor.org/**
Relevant assets: https://github.com/basecamp/trix/tree/master/dist :heart:

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/trix

We have it.
