### ISSUE TITLE
[Request] Add _WEBmoji

### ISSUE THREAD

**Issue by Buttersword123** [cdnjs/cdnjs#6026]
**Library name:WEBmoji** 
**Git repository url:https://github.com/buttersword123/WEBmoji**
**npm package url(optional):** 
**License(s):MIT**
**Official homepage:WEBmoji.net**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @Buttersword123 ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
We suggest you open an issue again when the library has more popularity.

Thanks for your contribution. :-)

**Comment by LeaYeh** [comment]
due to no response so i close it.
