### ISSUE TITLE
[Request] Add Cookiesplease

### ISSUE THREAD

**Issue by Wehmeyer** [cdnjs/cdnjs#6029]
Cookiesplease
https://github.com/zessx/cookiesplease
MIT License
http://smarchal.com/cookiesplease/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @Wehmeyer ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
We suggest you open an issue again when the library has more popularity.

Thanks for your contribution. :-)

**Comment by LeaYeh** [comment]
due to no response so i close it.
