### ISSUE TITLE
[Request] Add CSSgram

### ISSUE THREAD

**Issue by una** [cdnjs/cdnjs#6032]
**Library name: CSSgram** 
**Git repository url: https://github.com/una/CSSgram**
**Direct CSS link: https://raw.githubusercontent.com/una/CSSgram/master/source/css/cssgram.min.css**
**npm package url(optional): https://www.npmjs.com/package/cssgram ** 
**License(s): MIT**
**Official homepage: http://una.im/CSSgram**
**Thank you!**

**Comment by maruilian11** [comment]
sorry for not applying first, lib has been added in be6e8e1.
