### ISSUE TITLE
[Request] Add triggerScrolling.js

### ISSUE THREAD

**Issue by christianfortes** [cdnjs/cdnjs#6043]
**Library name:** triggerScrolling.js
**Git repository url:** https://github.com/christianfortes/triggerScroll
**npm package url(optional):** http://npmjs.com/package/triggerscrolling
**License(s):** MIT
**Official homepage:** http://christianfortes.github.io/triggerScrolling
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@christianfortes  sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
@christianfortes this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)

**Comment by Amomo** [comment]
closed due to no response.
