### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by charizard1636** [cdnjs/cdnjs#6047]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@charizard1636 jquery? relly? I thought we have it!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/jquery

**Comment by Amomo** [comment]
@charizard1636 we have jquery!

This issue will be closed if there is no any response in next 7 day.
Thank you for your contribution.

**Comment by Amomo** [comment]
closed due to no response.
