### ISSUE TITLE
[Request] Rewire

### ISSUE THREAD

**Issue by iamthawmus** [cdnjs/cdnjs#6049]
**Rewire:** 
**https://github.com/jhnns/rewire**
**https://www.npmjs.com/package/rewire** 
**MIT**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
@PeterDaveHello @cdnjs/intern 
It seems that rewire is a node module, I think we don't host this kind of library, right?

**Comment by PeterDaveHello** [comment]
If it can not run in modern browser of course we shouldn't add it. Node module didn't mean it can't.

**Comment by PeterDaveHello** [comment]
@iamthawmus @jhnns would you please give us your comments? Thanks.

**Comment by jhnns** [comment]
I don't think that rewire makes sense to be hostet on a CDN. It was designed for unit tests. It can be used in the browser, but requires preprocessing in this case.

**Comment by PeterDaveHello** [comment]
@jhnns so would you like this lib been hosted on CDNJS? If not, I may close this issue.

**Comment by maruilian11** [comment]
thank you!
