### ISSUE TITLE
[Request] Add angular touch

### ISSUE THREAD

**Issue by 0101adm** [cdnjs/cdnjs#6051]
**Library name:** angular touch
**Git repository url:** https://github.com/angular/bower-angular-touch
**npm package url(optional):** 
**License(s):** google
**Official homepage:** https://docs.angularjs.org/api/ngTouch
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@0101adm sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by 0101adm** [comment]
see issue https://github.com/cdnjs/cdnjs/issues/6052

**Comment by PeterDaveHello** [comment]
Same situation, this is a repo for dist, it's npm pkg has very high popularity, @cdnjs/intern you should not decide it's popularity by only one signal.
