### ISSUE TITLE
[Request] Add angular messages

### ISSUE THREAD

**Issue by 0101adm** [cdnjs/cdnjs#6052]
**Library name:** angular message
**Git repository url:** https://github.com/angular/bower-angular-messages
**npm package url(optional):** 
**License(s):** google
**Official homepage:** https://docs.angularjs.org/api/ngMessages/directive/ngMessages
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@0101adm sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by 0101adm** [comment]
i would agree if you look at the stars.  this is only a repo for bower/npm and if you see the commits (1600+), you'll see it has a lot of activity.

ngMessages is a regularly used directive for angular.

**Comment by maruilian11** [comment]
@PeterDaveHello i think we can add this lib?

**Comment by PeterDaveHello** [comment]
So I think you should leave its npm package name next time so that we can easily got the point, let's add it.

**Comment by 0101adm** [comment]
:thumbsup
