### ISSUE TITLE
[Request] angular morris chart

### ISSUE THREAD

**Issue by hkg25** [cdnjs/cdnjs#6059]
**Library name:angular morris chart** 
**Git repository url:https://github.com/stewones/angular-morris-chart**
**npm package url(optional):** 
**License(s):angular-morris-chart is open-sourced software licensed under MIT.**
**Official homepage:https://angular-morris-chart.stpa.co/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@hkg25 sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Looks very close, maybe we could just add it.
