### ISSUE TITLE
[Request] angular-dygraphs

### ISSUE THREAD

**Issue by hkg25** [cdnjs/cdnjs#6060]
**Library name:angular sygraphs** 
**Git repository url:https://github.com/cdjackson/angular-dygraphs**
**npm package url(optional):** 
**License(s):software licensed under MIT.**
**Official homepage:http://cdjackson.github.io/angular-dygraphs/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@hkg25 sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Piicksarn** [comment]
@hkg25,
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
