### ISSUE TITLE
css missing for jquery-ui 1.8/1.9 packages

### ISSUE THREAD

**Issue by glensc** [cdnjs/cdnjs#6064]
unfortunately the css files are not included...
https://cdnjs.com/libraries/jqueryui/1.8.24 - latest from 1.8.\* series
https://cdnjs.com/libraries/jqueryui/1.9.2 - latest from 1.9.\* series

see: https://github.com/cdnjs/cdnjs/pull/448#issuecomment-151831573

**Comment by PeterDaveHello** [comment]
@Amomo please fix it, thanks.

**Comment by Amomo** [comment]
Hi @PeterDaveHello 
I found that you have add the themes of jqueryui v1.9.0/1.9.1/1.9.2 via 659e16c9c4fb7422e2403c279651170bfbae369a , and themes for v1.8.x via ade3fc5dde7b7f9257aa90c648ed4874172acc4a ,but we can't see them on website!
Could you give me some help? thx~

**Comment by PeterDaveHello** [comment]
This page contains link to theme: https://jqueryui.com/download/

**Comment by Amomo** [comment]
sorry, I mean cdnjs's website. 
https://cdnjs.com/libraries/jqueryui/1.9.2

**Comment by PeterDaveHello** [comment]
File list didn't been updated yet.

**Comment by PeterDaveHello** [comment]
Updated.

**Comment by Amomo** [comment]
Strange. Still can't see the themes of jqueryui at v1.9.2.

**Comment by PeterDaveHello** [comment]
`Ctrl` + `F5`

**Comment by MattIPv4** [comment]
Appears to be resolved, closing.
