### ISSUE TITLE
[Request] Add CSSgram

### ISSUE THREAD

**Issue by anirvan** [cdnjs/cdnjs#6066]
**Library name:** CSSgram
**Git repository url:** https://github.com/una/CSSgram
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://una.im/CSSgram/

**Comment by paleite** [comment]
+1

**Comment by maruilian11** [comment]
@una could you please add tags for each version so that we can add your lib with **git auto update**.
thank you very much!

**Comment by una** [comment]
Lol @ https://github.com/cdnjs/cdnjs/issues/6032

**Comment by una** [comment]
:stuck_out_tongue: and done

**Comment by PeterDaveHello** [comment]
Duplicated with #6032
