### ISSUE TITLE
[Request] Mapstraction 

### ISSUE THREAD

**Issue by fallingrock** [cdnjs/cdnjs#6069]
**Library name: Mapstraction** 
**Git repository url:https://github.com/mapstraction/mxn/**
**npm package url(optional):** 
**License(s): BSD**
**Official homepage:http://mapstraction.com/**
**Wanna say something? Leave message here: Ignore this ... project appears to be abandoned.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
No need to add it anymore?
