### ISSUE TITLE
[Request] awsAccordion 

### ISSUE THREAD

**Issue by hassaan39** [cdnjs/cdnjs#6071]
**Library name: awsAccordion** 
**Git repository url: http://www.jqueryscript.net/demo/jQuery-Plugin-for-Responsive-Accordion-Generator-awsAccordion/jquery.accordion.js**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Please provide its CDN.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We need it's repository and license info @hassaan39

**Comment by PeterDaveHello** [comment]
Close due to no response.
