### ISSUE TITLE
[Request] Javascript-Load-Image

### ISSUE THREAD

**Issue by silbermm** [cdnjs/cdnjs#6076]
**Library name:** Javascript-Load-Image 
**Git repository url:** https://github.com/blueimp/JavaScript-Load-Image
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://blueimp.github.io/JavaScript-Load-Image/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Added in #6480
