### ISSUE TITLE
[Request] Add zxcvbn

### ISSUE THREAD

**Issue by vanduynslagerp** [cdnjs/cdnjs#6085]
**Library name:** zxcvbn
**Git repository url:** https://github.com/dropbox/zxcvbn
**npm package url(optional):**
**License(s):** MIT
**Official homepage:** http://tech.dropbox.com/?p=165
**Wanna say something? Leave message here:**
The last version on cdnjs is 2.0.2 and is not updated since then. The last version of zxcvbn released on GitHub is 4.0.1 (https://github.com/dropbox/zxcvbn/releases/tag/4.0.1)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
already included in cdnjs :smile: 
https://cdnjs.com/libraries/zxcvbn
