### ISSUE TITLE
wmsui

### ISSUE THREAD

**Issue by JagannathLenka** [cdnjs/cdnjs#6086]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@JagannathLenka, would you please make some detail? 
Thank you!

**Comment by Piicksarn** [comment]
This issue will be closed if there is no any response in next 7 day.
Thank you!

**Comment by Piicksarn** [comment]
Closed due to no response.
