### ISSUE TITLE
[Request] SHB-js

### ISSUE THREAD

**Issue by onlineth** [cdnjs/cdnjs#6090]
**Library name:** SHB-js
**Git repository url:** https://github.com/dr-dimitru/SHB-js
**npm package url(optional):** 
**License(s):** The MIT License (MIT)
**Official homepage:** http://ostr.io/code/html-social-like-share-buttons-no-javascript.html
**Wanna say something? Leave message here:**
https://github.com/dr-dimitru/SHB-js.git

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @onlineth ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
due to no response so i close it.
