### ISSUE TITLE
pagedown require upgrade

### ISSUE THREAD

**Issue by bhuvangu** [cdnjs/cdnjs#6091]
https://cdnjs.com/libraries/pagedown require upgrade

**Comment by PeterDaveHello** [comment]
@bhuvangu Thanks for report. @LeaYeh please take a look.

**Comment by x09326** [comment]
What should I do here?
Do I ask the author to add the version tag and add the git auto-update?

**Comment by PeterDaveHello** [comment]
@x09326 see how can you upgrade the lib, maybe something like add auto-update config.

**Comment by xtuc** [comment]
Enable autoupdate for the package, see contributing.md files
