### ISSUE TITLE
[Request] Add Stackicons

### ISSUE THREAD

**Issue by jdextraze** [cdnjs/cdnjs#6092]
**Library name:** Stackicons
**Git repository url:** https://github.com/parkerbennett/stackicons
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://stackicons.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
i already open an [issue](https://github.com/parkerbennett/stackicons/issues/15) to ask for tag

**Comment by PeterDaveHello** [comment]
@LeaYeh so please add a `wait for response` label for this issue.

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems not act on github for a long time, what can we do for this issue?

**Comment by PeterDaveHello** [comment]
Use this as v1.0
[Pushing Version 1.0](https://github.com/parkerbennett/stackicons/commit/285ed85e668495d6a57f5da9aee2f40425dc690f)
