### ISSUE TITLE
[Request] Add peity

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6095]
**Library name:** peity
**Git repository url:** https://github.com/benpickles/peity
**npm package url(optional):**  peity
**License(s):** MIT
**Official homepage:** http://benpickles.github.io/peity

**Comment by PeterDaveHello** [comment]
I think I provided the npm info, @maruilian11 you should use it as higher priority as the source of auto-update, @Piicksarn and you should check it next time.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i see.

**Comment by PeterDaveHello** [comment]
Use commit to close next time ...
