### ISSUE TITLE
[Request] Add jQuery.Gantt

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6099]
**Library name:** jQuery.Gantt
**Git repository url:** https://github.com/mbielanczuk/jQuery.Gantt
**License(s):** MIT
**Official homepage:** http://mbielanczuk.com/2011/06/jquery-gantt-chart/

**Comment by maruilian11** [comment]
wait for a new release.
https://github.com/cdnjs/cdnjs/pull/7005#issuecomment-187043627
https://github.com/mbielanczuk/jQuery.Gantt/issues/53

**Comment by usmonster** [comment]
Should probably instead follow taitems/jQuery.Gantt#162.
