### ISSUE TITLE
[Request] modernizr 3.2.0

### ISSUE THREAD

**Issue by tshortt** [cdnjs/cdnjs#6100]
**Library name:** Modernizr
**Git repository url:** https://github.com/Modernizr/Modernizr
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://modernizr.com
**Wanna say something? Leave message here:** Current version of modernizr is 3.2.0, but it appears that cdnjs.com only hosts up to version 2.8.3. 
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Seems there is no pre-built file anymore, @Modernizr would you please give us advice? Thanks.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/intern @cdnjs/team-cdnjs

**Comment by terinjokes** [comment]
cc @paulirish

**Comment by amwmedia** [comment]
We are encountering the same issue, any update?

**Comment by PeterDaveHello** [comment]
@amwmedia, nope, and I wonder what do you mean "We" here? Thanks.

**Comment by amwmedia** [comment]
my dev team at work. sorry, that was a little unclear ;-)

**Comment by PeterDaveHello** [comment]
@amwmedia no problem

**Comment by PeterDaveHello** [comment]
hmmmm ... still no update yet.

**Comment by chrisblakley** [comment]
Also looking forward to some kind of solution here.

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close due to passed to much time from request and request to author for clear lib situation  was sent
