### ISSUE TITLE
[Request] BitGoJS

### ISSUE THREAD

**Issue by masonicGIT** [cdnjs/cdnjs#6109]
**Library name:** BitGoJS 
**Git repository url:** https://github.com/bitgo/bitgojs
**npm package url(optional):** npm install bitgo 
**License(s):** Apache License
**Official homepage:** www.bitgo.com
**Wanna say something? Leave message here:**  Please let us know what the ETA would look like :-)
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@masonicGIT seems like the author doesn't want this lib been hosted on cdnjs, would you like to join the discussion here: https://github.com/BitGo/BitGoJS/issues/28#issuecomment-223828150

**Comment by PeterDaveHello** [comment]
Close this first until its officially dist build was provided, see the issue link above.
