### ISSUE TITLE
[Request] Lemonade Grid

### ISSUE THREAD

**Issue by dope** [cdnjs/cdnjs#6112]
**Library name:** Lemonade Grid
**Git repository url:** http://github.com/dope/lemonade
**npm package url(optional):** https://www.npmjs.com/package/lemonade-grid
**License(s):** MIT
**Official homepage:** http://lemonade.im

**Comment by PeterDaveHello** [comment]
@dope I saw you are the author, would you like to send a PR to add this lib?
