### ISSUE TITLE
[Request] Sir Trevor

### ISSUE THREAD

**Issue by maxharlow** [cdnjs/cdnjs#6113]
**Library name:** Sir Trevor
**Git repository url:** https://github.com/madebymany/sir-trevor-js.git
**npm package url(optional):** https://www.npmjs.com/package/sir-trevor
**License(s):** MIT
**Official homepage:** http://madebymany.github.io/sir-trevor-js/

**Comment by x09326** [comment]
@PeterDaveHello This lib in npm is version 0.5.0, but in github is version 0.6.0-beta9.
Which should I download ?

**Comment by PeterDaveHello** [comment]
@x09326 The latest stable version.
