### ISSUE TITLE
[Request] Add is.js

### ISSUE THREAD

**Issue by friedemannsommer** [cdnjs/cdnjs#6114]
is.js
https://github.com/arasatasaygin/is.js
MIT License (MIT)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/is_js
