### ISSUE TITLE
[Request] numble

### ISSUE THREAD

**Issue by dubl0dude** [cdnjs/cdnjs#6116]
jasonyost/numble
https://github.com/jasonyost/numble
MIT
http://jasonyost.github.io/numble/

**Comment by Piicksarn** [comment]
@dubl0dude,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
