### ISSUE TITLE
[Request] leaflet-icon-pulse

### ISSUE THREAD

**Issue by ironsideshu** [cdnjs/cdnjs#6118]
**Library name: leaflet-icon-pulse** 
**Git repository url: https://github.com/mapshakers/leaflet-icon-pulse.git**
**npm package url(optional):** 
**License(s): MIT-LICENSE.**
**Official homepage: https://github.com/mapshakers/leaflet-icon-pulse**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @ironsideshu ,

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our README.md for detail.

We suggest you open an issue again when the library has more popularity.
Thanks for your contribution. :-)

**Comment by Piicksarn** [comment]
@ironsideshu, this issue will be closed if there is no any response in next 7 day.

**Comment by LeaYeh** [comment]
because no respond i close this issue
