### ISSUE TITLE
[Request] Add iLightBox

### ISSUE THREAD

**Issue by Greg-J** [cdnjs/cdnjs#6120]
**Library name:** iLightBox
**Git repository url:** https://github.com/sachinchoolur/lightGallery
**npm package url(optional):** 
**License(s):** Apache v2.0
**Official homepage:** http://www.ilightbox.net/
**Wanna say something? Leave message here:** This is an amazing lightbox. Definitely the most full-featured one I've seen.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
lightGallery or iLightBox?

**Comment by PeterDaveHello** [comment]
If you meant https://github.com/sachinchoolur/lightGallery, we have it https://cdnjs.com/libraries/lightgallery
