### ISSUE TITLE
UTF-8 Chars in JS file

### ISSUE THREAD

**Issue by iamJoeTaylor** [cdnjs/cdnjs#6125]
https://cdnjs.cloudflare.com/ajax/libs/field-kit/2.0.4/field-kit.js VS http://square.github.io/field-kit/javascript/field-kit.js

Search for `¥`

The good file is encoded for `UTF-8` the "bad" (CDNJS) is encoded for `Western (Windows-1252)`

<img width="548" alt="screen shot 2015-11-04 at 4 46 46 pm" src="https://github-cloud.s3.amazonaws.com/assets%2F967026%2F10956848%2Fccf436e4-8313-11e5-88cf-71243741b55c.png">

**Comment by PeterDaveHello** [comment]
The encoded is the same in the file, the problem may comes from the server side.

```
$ curl -I https://square.github.io/field-kit/javascript/field-kit.js
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: application/javascript; charset=utf-8
Last-Modified: Wed, 28 Oct 2015 23:21:28 GMT
Access-Control-Allow-Origin: *
Expires: Thu, 05 Nov 2015 01:05:34 GMT
Cache-Control: max-age=600
X-GitHub-Request-Id: 17EB2D22:09B4:9BBF34B:563AA906
Content-Length: 245001
Accept-Ranges: bytes
Date: Thu, 05 Nov 2015 00:55:35 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-bma7034-BMA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1446684934.518991,VS0,VE585
Vary: Accept-Encoding
X-Fastly-Request-ID: d63fd228790c17a56b61b173ab7bf228876a920b
```

```
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/field-kit/2.0.4/field-kit.js
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Thu, 05 Nov 2015 00:56:18 GMT
Content-Type: application/javascript
Connection: keep-alive
Last-Modified: Thu, 29 Oct 2015 04:49:46 GMT
Expires: Tue, 25 Oct 2016 00:56:18 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
CF-RAY: 2404991cf768336d-HKG
```

**Comment by PeterDaveHello** [comment]
@terinjokes do you have any suggestions?

cc @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
But I wonder if it's good to send the encoding from httpd, we can not confirm and declare that all the text based file on cdnjs is utf-8.

**Comment by PeterDaveHello** [comment]
@iamJoeTaylor do you have the problem even when you set a tag like `<meta charset="UTF-8">` in your webpage? I meant not open directly from browser.

**Comment by iamJoeTaylor** [comment]
Adding `<meta http-equiv="content-type" content="text/html; charset=utf-8">` or `charset="utf-8"` attribute to the `script` tag. I can also move away from UTF8.

**Comment by PeterDaveHello** [comment]
So I think we can close this issue now?

**Comment by iamJoeTaylor** [comment]
I think so.

**Comment by terinjokes** [comment]
Reopening because I'm fixing this on the server.

**Comment by PeterDaveHello** [comment]
@terinjokes What about the other files? Or the server will detect their charset and then set it?

**Comment by terinjokes** [comment]
@PeterDaveHello That's the goal.

**Comment by PeterDaveHello** [comment]
@terinjokes so you are going to reach the goal this time? Or just in future? I think that's a hard work, and think it's not really a server side responsibility. Any way, thanks!

**Comment by terinjokes** [comment]
Delivering the correct content-type is certainly a server responsibility

**Comment by terinjokes** [comment]
The change is out, things should eventually fall from cache.

**Comment by iamJoeTaylor** [comment]
@terinjokes :+1: Thank you

**Comment by PeterDaveHello** [comment]
@terinjokes :+1:

**Comment by PeterDaveHello** [comment]
$ curl -I https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.0.20/browser.js
HTTP/1.1 200 OK
Server: cloudflare-nginx
Date: Fri, 13 Nov 2015 10:03:00 GMT
Content-Type: application/javascript
Content-Length: 4
Connection: keep-alive
Last-Modified: Tue, 03 Nov 2015 15:35:25 GMT
Expires: Wed, 02 Nov 2016 10:03:00 GMT
Cache-Control: public, max-age=30672000
Access-Control-Allow-Origin: *
CF-Cache-Status: HIT
Accept-Ranges: bytes
CF-RAY: 2449a4f0558d340f-HKG

**Comment by PeterDaveHello** [comment]
@terinjokes would you please take a look at the case above? Thanks.

**Comment by terinjokes** [comment]
I'm looking at it.

**Comment by PeterDaveHello** [comment]
@terinjokes Thanks.

**Comment by Calixte** [comment]
I think this issue should be reopened. The content types are missing the utf-8 encoding again.
See also https://github.com/cdnjs/cdnjs/issues/12756

```
$ curl -sI https://cdnjs.cloudflare.com/ajax/libs/field-kit/2.0.4/field-kit.js | grep Content
Content-Type: application/javascript
$ curl -sI https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.24.0/babel.min.js | grep Content
Content-Type: application/javascript
```
