### ISSUE TITLE
[Request] Add responsimple

### ISSUE THREAD

**Issue by jonmircha** [cdnjs/cdnjs#6126]
**Library name:**Responsimple
**Git repository url:**https://github.com/jonmircha/responsimple
**npm package url(optional):**https://www.npmjs.com/package/responsimple
**License(s):**MIT
**Official homepage:**http://jonmircha.github.io/responsimple/
**Wanna say something? Leave message here:**A simple, flexible & responsive CSS grid system

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@jonmircha this lib need some notable popularity to be added.

**Comment by jonmircha** [comment]
ok, thanks I'll wait :)

**Comment by PeterDaveHello** [comment]
Thanks.
