### ISSUE TITLE
[Request] Add iframeTracker-jquery

### ISSUE THREAD

**Issue by Vashkatsi** [cdnjs/cdnjs#6133]
**Library name:** iframeTracker-jquery
**Git repository url:** https://github.com/vincepare/iframeTracker-jquery
**npm package url(optional):** 
**License(s):** Apache License Version 2.0
**Official homepage:** https://github.com/vincepare/iframeTracker-jquery
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Looks fine to add this lib.
