### ISSUE TITLE
[Request] Ionic Framework 2.0

### ISSUE THREAD

**Issue by wcustodio** [cdnjs/cdnjs#6134]
**Library name:** Ionic Framework 2.0
**Git repository url:** https://github.com/driftyco/ionic-code/tree/gh-pages/2.0.0
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://ionicframework.com/docs/v2/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @wcustodio ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
because no respond, i close this issue
