### ISSUE TITLE
[Request] Add leaflet-plugins

### ISSUE THREAD

**Issue by 1337** [cdnjs/cdnjs#6137]
**Library name:** leaflet-plugins
**Git repository url:** https://github.com/shramov/leaflet-plugins/
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/shramov/leaflet-plugins/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by brunob** [comment]
Thx @Amomo + @1337 

could you give ma advise to mention it in our readme file ?

**Comment by Amomo** [comment]
Hi @brunob 

After #6149 get merged, we will host leaflet-plugins on cdnjs.
I think you can list the url to this library on our website.
It will look like... https://cdnjs.com/libraries/[leaflet-plugins]

**Comment by brunob** [comment]
Thx for the info @Amomo i'll put a reference to this in the README file after your merge.

**Comment by brunob** [comment]
@Amomo any news about this ?

**Comment by PeterDaveHello** [comment]
@brunob sorry for the delay, I'll take this.

**Comment by brunob** [comment]
No hurry, and thx for that @PeterDaveHello :)

**Comment by PeterDaveHello** [comment]
@brunob np, will add this tomorror, should off to sleep now :)

**Comment by PeterDaveHello** [comment]
@brunob would you please help me confirm the files need to be hosted on cdnjs?

**Comment by PeterDaveHello** [comment]
Should I add the whole `layer`, `css` and `control` folder?

**Comment by brunob** [comment]
Eexactly @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@brunob Is it possible to add a `dist` folder in the repo for distribution files? Thanks.

**Comment by brunob** [comment]
@PeterDaveHello is it obligatory needed ? I would prefer to not change the repo files layout... :\

**Comment by PeterDaveHello** [comment]
@brunob Not that needed, but it will be better.

**Comment by brunob** [comment]
(y) thx @PeterDaveHello
