### ISSUE TITLE
[Request] Watermark

### ISSUE THREAD

**Issue by baivong** [cdnjs/cdnjs#6141]
**Library name:** Watermark
**Git repository url:** https://github.com/baivong/watermark
**npm package url(optional):** https://www.npmjs.com/package/watermark
**License(s):** MIT
**Official homepage:** http://baivong.github.io/watermark/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @baivong ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
