### ISSUE TITLE
[Request] Add cellx

### ISSUE THREAD

**Issue by Riim** [cdnjs/cdnjs#6145]
**Library name: cellx** 
**Git repository url: https://github.com/Riim/cellx**
**npm package url(optional): https://www.npmjs.com/package/cellx** 
**License(s): MIT**
**Official homepage: https://github.com/Riim/cellx**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @Riim ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Riim** [comment]
Ok, thank.

**Comment by PeterDaveHello** [comment]
Looks good now, let's add this.

**Comment by PeterDaveHello** [comment]
@kennynaoh please help add this lib ASAP, thanks!
