### ISSUE TITLE
[Request] Add NLP_compromise

### ISSUE THREAD

**Issue by spencermountain** [cdnjs/cdnjs#6148]
**Library name: nlp_compromise** 
**Git repository url:  https://github.com/spencermountain/nlp_compromise**
**npm package url(optional): https://www.npmjs.com/package/nlp_compromise** 
**License(s): MIT**
**Official homepage:**
**Wanna say something? Leave message here:  Hey, Ive been using rawgit for a while, and looking for something more stable. let me know if this is the right place. thanks!**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by spencermountain** [comment]
hi @Piicksarn i'm just refactoring the publish workflow for this, and wanted to know if this library is a good candidate for cdnjs. This week would be a great time to begin working with this. Let me know if it would be a good fit. cheers

**Comment by spencermountain** [comment]
thanks! this helps a lot. I'll do my best to make sure this project stays a good steward for this cool and generous service. thanks!

**Comment by PeterDaveHello** [comment]
@spencermountain Great.

**Comment by PeterDaveHello** [comment]
@spencermountain is it possible to add cdnjs info in readme? Thanks.
