### ISSUE TITLE
[Request] Add ReactiveX RxJS 5.*.*

### ISSUE THREAD

**Issue by blesh** [cdnjs/cdnjs#6151]
**Library name:** RxJS 5.0.0
**Git repository url:** https://github.com/ReactiveX/RxJS
**npm package url(optional):** https://www.npmjs.com/package/@reactivex/rxjs
**License(s):** Apache 2
**Official homepage:** https://github.com/ReactiveX/RxJS
**Wanna say something? Leave message here:** I'm just the leading the effort for this project. We want to get the alpha library up on CDNs so people can start using it and playing with it, particularly as we close in on a beta release. There might be a *little* confusion because this is a rewrite of the great stuff going on at http://github.com/Reactive-Extensions/RxJS, and is the inevitable successor library (provided we survive beta! haha)

cc/ @mattpodwysocki (of Reactive-Extensions/RxJS)

To get the CDN-able files, you need to get the package via `npm install @reactivex/rxjs` and there are files under `dist/global` that are useful as global installs.

Thank you for your service and your time! I wouldn't be able to prototype things in JSBin without you.

**Comment by blesh** [comment]
I did see that I can submit a PR, but since this is a special case (two repos that are related), I wanted to get guidance from this project's maintainers to make sure I'm "doing it right".

Thanks again!

**Comment by PeterDaveHello** [comment]
We don't support two repo/npm pkg as upstream, if rxjs v4.x is not still going to updating, we can change the auto-update source. cc @cdnjs/team-cdnjs

**Comment by blesh** [comment]
That's fine. In the interim, can you do something to add @reactivex/rxjs? It'll likely be months before it's out of beta.

**Comment by PeterDaveHello** [comment]
So, I need to confirm a few things, the first one is that rxjs v4.x v5.x located at different repo? They are still the same lib but just different version?

 - https://github.com/Reactive-Extensions/RxJS
 - https://github.com/ReactiveX/RxJS

**Comment by blesh** [comment]
That's correct.

v 4 is at Reactive-Extensions
v 5 is at ReactiveX

**Comment by PeterDaveHello** [comment]
@blesh Thanks, so will v4 still be updated?

**Comment by blesh** [comment]
I assume that v4 is already set up properly. I wouldn't change whatever is set up for that. This is more about v5

**Comment by PeterDaveHello** [comment]
Yep but once we changed the auto-update target, we can not receive the new releases from v4.

**Comment by blesh** [comment]
Oh... don't do that, then.  Can you make a new target for now?

**Comment by PeterDaveHello** [comment]
@blesh What about add a lib called rxjs5?

**Comment by PeterDaveHello** [comment]
@blesh or something like rxjs_v5

**Comment by blesh** [comment]
Actually... it looks like npmcdn now supports namespaced packages. So this works:

https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.8/dist/global/Rx.min.js

I'll just use that for now. 

Thank you for all of your help!

**Comment by PeterDaveHello** [comment]
@blesh I think we can still trying to put this on cdnjs :)

**Comment by blesh** [comment]
Oh, okay... awesome, thanks @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
So I think we have leave this issue opened until we add it?

**Comment by blesh** [comment]
Sounds fair.

**Comment by PeterDaveHello** [comment]
@blesh I wonder if your colleagues will like to give us advice about this issue?

**Comment by blesh** [comment]
That's @mattpodwysocki's department. But if I had to speak for him, I'd say, don't change anything about how you're handling RxJS 4.

Really RxJS 4 and RxJS 5 are going to be parallel efforts for some time. So we can't really switch one off and switch the other one. They need to live together.

**Comment by PeterDaveHello** [comment]
So what about just add a `rxjs5` or something? Maybe you and @mattpodwysocki will have some different idea about the naming.

**Comment by blesh** [comment]
Or just `rx` maybe? That's the "street slang" for it anyhow.

**Comment by xsilen** [comment]
just RxJS please, do the same like between angular1 and angular2

**Comment by PeterDaveHello** [comment]
@xsilen angular is another case, there is no way to deal with the auto-update with angular.

**Comment by PeterDaveHello** [comment]
@blesh sorry for the late update, since I'm going to make the npm auto-update support scoped npm package, would you please help me confirm what should we do on rxjs auto-update: 

> To get the CDN-able files, you need to get the package via npm install @reactivex/rxjs and there are files under dist/global that are useful as global installs.

Thanks.

**Comment by blesh** [comment]
Yes, that's still the case.

**Comment by PeterDaveHello** [comment]
Adding it, @blesh maybe you can help us confirm it later, thanks :smile:

**Comment by PeterDaveHello** [comment]
@blesh Added here:
https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.0-beta.9/Rx.min.js
https://cdnjs.com/libraries/rxjs/5.0.0-beta.9

Thanks for your help, and please feel free to ping me if there is any problem.

**Comment by blesh** [comment]
awesome, thanks @PeterDaveHello!
