### ISSUE TITLE
[Request] Add Kindeditor

### ISSUE THREAD

**Issue by netroby** [cdnjs/cdnjs#6153]
**Library name:** Kindeditor
**Git repository url:** https://github.com/kindsoft/kindeditor
**npm package url(optional):** 
**License(s):** LGPL
**Official homepage:** http://kindeditor.org/
**Wanna say something? Leave message here:**
A very tiny and useful JS WISIWIG editor, provided well code format 
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by huaiping** [comment]
Could you please take a look at this? @maruilian11 @PeterDaveHello 
all js and css files in lang, plugins and themes are provided by running grunt.
https://github.com/huaiping/static/tree/master/libs/KindEditor

**Comment by PeterDaveHello** [comment]
We'll take care of it soon, thanks for the reply @huaiping
