### ISSUE TITLE
[Request] owfont 

### ISSUE THREAD

**Issue by ketus** [cdnjs/cdnjs#6160]
**Library name: owfont 
**Git repository url: https://github.com/websygen/owfont
**npm package url(optional):** 
**License(s):**
**Official homepage: http://websygen.github.io/owfont/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@ketus ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity.
Thanks for your contribution. :-)

Piicksarn

**Comment by ketus** [comment]
Oh tank You, good to know :)
