### ISSUE TITLE
[Request] Add eCSSential

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6161]
**Library name:** eCSSential
**Git repository url:** https://github.com/scottjehl/eCSSential
**License(s):** GPL, MIT

**Comment by LeaYeh** [comment]
i already open an [issue](https://github.com/scottjehl/eCSSential/issues/9) to ask author.

**Comment by PeterDaveHello** [comment]
Let's add a label for it next time.

**Comment by maruilian11** [comment]
@scottjehl could you please consider addong tags for each version ? thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems to still act on github, but he didn't make a response.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern can you guys write an email to ask the author? Thanks.

**Comment by scottjehl** [comment]
Hi there. That project is no longer maintained, and we've updated the readme to clarify that. Thanks.

**Comment by PeterDaveHello** [comment]
Okay, thanks @scottjehl
