### ISSUE TITLE
[Request] Add angular-clipboard

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6166]
**Library name:** angular-clipboard
**Git repository url:** https://github.com/omichelsen/angular-clipboard
**npm package url(optional):** angular-clipboard
**License(s):** MIT

Popularity on npm download stats looks fine.

**Comment by LeaYeh** [comment]
@PeterDaveHello but its start is not enough.

**Comment by PeterDaveHello** [comment]
hey no mind, we sometimes add libs with potential or some other important reasons :)
