### ISSUE TITLE
[Request] Add angular-relative-date

### ISSUE THREAD

**Issue by elvis-macak** [cdnjs/cdnjs#6174]
**Library name:** angular-relative-date
**Git repository url:** https://github.com/wildlyinaccurate/angular-relative-date
**npm package url(optional):** 
**License(s):**  MIT
**Official homepage:** https://github.com/wildlyinaccurate/angular-relative-date
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@elvis-macak sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by elvis-macak** [comment]
still thanks
