### ISSUE TITLE
[Request] date dropper

### ISSUE THREAD

**Issue by michaelgearon** [cdnjs/cdnjs#6175]
**Library name:** datedropper 
**Git repository url:** https://github.com/felicegattuso/datedropper/
**npm package url(optional):** 
**License(s):** MIT License CC BY 4.0
**Official homepage:** http://felicegattuso.com/projects/datedropper/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
https://github.com/cdnjs/cdnjs/issues/8125
