### ISSUE TITLE
[Request] Add captionator.js

### ISSUE THREAD

**Issue by akaleeroy** [cdnjs/cdnjs#6176]
**Library name:** captionator.js
**Git repository url:** https://github.com/cgiffard/Captionator
**npm package url(optional):** 
**License(s):** Copyright (c) 2012, Christopher Giffard All rights reserved.
**Official homepage:** [Captionator.js](http://captionatorjs.com/)
**Wanna say something? Leave message here:**

I wanna be able to use .srt subtitles without fussing about converting to .vtt or whatever. Being able to grab this lib from CDNJS would be cool.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@akaleeroy sorry for my late reply, i already open an [issue](https://github.com/cgiffard/Captionator/issues/48) to ask the author, your issue is processing.

**Comment by cgiffard** [comment]
Left a comment on the other issue. :)

**Comment by PeterDaveHello** [comment]
Ping @LeaYeh

**Comment by PeterDaveHello** [comment]
I'll let @pvnr0082t take this.
