### ISSUE TITLE
[Request] Add redux-router

### ISSUE THREAD

**Issue by Morfent** [cdnjs/cdnjs#6179]
**Library name: redux-router** 
**Git repository url: https://github.com/rackt/redux-router**
**npm package url(optional): https://www.npmjs.com/package/redux-router** 
**License(s): MIT**
**Official homepage: none (documentation is in progress according to the repo's README)**
**Wanna say something? Leave message here: react-router and redux are fantastic; this makes the two packages much easier to work with together**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Morfent what are the files should be hosted on CDN? Thanks.

**Comment by Morfent** [comment]
Sorry, I switched to using Webpack to deal with dependencies a while ago, but I'll still try to get this up. The repository has no builds included, but I'll make a pull request to add them and notify you if or when it gets accepted.

**Comment by Morfent** [comment]
Pullreq: https://github.com/acdlite/redux-router/pull/258

**Comment by PeterDaveHello** [comment]
Thanks @Morfent, please feel free to ping me once we could add this.

**Comment by Morfent** [comment]
I believe it can be added now.

**Comment by PeterDaveHello** [comment]
@Morfent We'll take a look at it, thanks.
