### ISSUE TITLE
[Request] Add _angular-resource 

### ISSUE THREAD

**Issue by fjmesa** [cdnjs/cdnjs#6180]
**Library name: packaged angular-resource** 
**Git repository url: https://github.com/angular/bower-angular-resource**
**npm package url(optional): npm install angular-resource** 
**License(s): The MIT License**
**Official homepage:**
=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@fjmesa,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
