### ISSUE TITLE
[Request] Add _angular-cookies 

### ISSUE THREAD

**Issue by fjmesa** [cdnjs/cdnjs#6181]
**Library name: packaged angular-cookies** 
**Git repository url: https://github.com/angular/bower-angular-cookies**
**npm package url(optional): npm install angular-cookies** 
**License(s): The MIT License**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @fjmesa 

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our README.md for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by Piicksarn** [comment]
@fjmesa, this issue will be closed if there is no any response in next 7 day.

**Comment by Amomo** [comment]
closed due to no response.
