### ISSUE TITLE
[Request] Add _angular-dynamic-locale

### ISSUE THREAD

**Issue by fjmesa** [cdnjs/cdnjs#6183]
**Library name: angular-dynamic-locale** 
**Git repository url: https://github.com/lgalfaso/angular-dynamic-locale**
**npm package url(optional): npm install angular-dynamic-locale** 
**Official homepage: https://github.com/lgalfaso/angular-dynamic-locale**
=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello i asked author if they can move `.min.js` and `.min.js.map` to dist, but they only move them in v0.1.29(the latest version). so, should i still set npm auto-update basepath to dist?

**Comment by PeterDaveHello** [comment]
@maruilian11 if v0.1.29 is the latest version, yes
