### ISSUE TITLE
[Request] Add _angular-cache-buster 

### ISSUE THREAD

**Issue by fjmesa** [cdnjs/cdnjs#6184]
**Library name: angular-cache-buster** 
**Git repository url: https://github.com/saintmac/angular-cache-buster**
=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@fjmesa,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
**`This issue will be closed if there is no any response in next 7 day.`**
Thanks!
Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
