### ISSUE TITLE
Plupload isn't updated to v2.1.8

### ISSUE THREAD

**Issue by dimadin** [cdnjs/cdnjs#6188]
Latest version on cdnjs is 2.1.7
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/plupload
while version 2.1.8 is released in July
https://github.com/moxiecode/plupload/releases

**Comment by PeterDaveHello** [comment]
@dimadin thanks for report.

**Comment by PeterDaveHello** [comment]
Added it 9 days ago
* ca0f433 add plupload v2.1.8
