### ISSUE TITLE
[Request] Add Forge

### ISSUE THREAD

**Issue by GabrielJones646** [cdnjs/cdnjs#6190]
**Library name:** Forge
**Git repository url:**https://github.com/digitalbazaar/forge
**npm package url(optional):** 
**License(s):**GPL2
**Official homepage:**http://digitalbazaar.com/2010/07/20/javascript-tls-1/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by davidlehn** [comment]
0.7.0 was released which includes a `dist/forge.min.js` file.

**Comment by maruilian11** [comment]
@davidlehn many thanks! I will send the PR to add it later.

**Comment by PeterDaveHello** [comment]
Move to #11152
