### ISSUE TITLE
[Request] Add fancyBox v3

### ISSUE THREAD

**Issue by avradul** [cdnjs/cdnjs#6191]
**Library name:** fancyBox v3 Beta
**Git repository url:** http://fancyapps.com/fancybox/beta/jquery.fancybox-v3beta.zip
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://fancyapps.com/fancybox/beta/

**Comment by maruilian11** [comment]
@avradul could you please provide **git repo url** or **npm package url**? thank you

**Comment by maruilian11** [comment]
@avradul this issue will be closed if there is no any response in next 7 days. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Should be https://github.com/fancyapps/fancyBox ?

**Comment by maruilian11** [comment]
@avradul if you means https://cdnjs.com/libraries/fancybox, i already had it.
we currently only add stable version, so we can't add v3 Beta.
thank you for your suggestion, this issue will be closed if there is no any response in next 7 days.

**Comment by avradul** [comment]
> we currently only add stable version
Its not true.
What about
bootstrap alpha https://cdnjs.com/libraries/twitter-bootstrap/4.0.0-alpha.2,
angular alpha and beta https://cdnjs.com/libraries/angular.js
?

**Comment by PeterDaveHello** [comment]
@avradul These two examples are the libs I said the most popular libs'

**Comment by PeterDaveHello** [comment]
If we could apply auto-update on this lib, beta versions are also acceptable.

**Comment by maruilian11** [comment]
but we already set auto-update for this lib.

**Comment by PeterDaveHello** [comment]
@maruilian11 
> but we already set auto-update for this lib.

Where?

**Comment by maruilian11** [comment]
hmmm... sorry, i thought it has.
i will send the PR to add auto-update config later.

**Comment by fancyapps** [comment]
Hello! It would be nice if you could add stable v3.

I think you can close this issue, there is no need to add that beta (it was never published on github, too).

**Comment by PeterDaveHello** [comment]
@fancyapps Thanks.
