### ISSUE TITLE
[Request] zoomE

### ISSUE THREAD

**Issue by shinoamakusa** [cdnjs/cdnjs#6193]
Zoome - jQuery Image Zoom Effect Plugin
http://codecanyon.net/item/zoome-jquery-image-zoom-effect-plugin/2973067

The plugin is no longer updated. I am still using this small little beast for image zoom effect on few of my projects. I was wondering would it possible to add it to cdnjs libraries if I provide the files ( which I had bought officially)

Thank you,
Oleg aka Shino Amakusa

**Comment by PeterDaveHello** [comment]
Hi @shinoamakusa, I'm afraid that we can not host this, it will make same license problems.
