### ISSUE TITLE
[Request] Add jquery-postmessage

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6202]
**Library name:** jquery-postmessage
**Git repository url:** https://github.com/cowboy/jquery-postmessage

**Comment by LeaYeh** [comment]
i already open an [issue](https://github.com/cowboy/jquery-postmessage/issues/18) to ask author add tags.

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close due to time passed from issue was opened and request to add git tag was sent to author
