### ISSUE TITLE
[Request] Add other versions of jquery.imgareaselect

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6207]
jquery.imgareaselect
https://cdnjs.com/libraries/imgareaselect
https://github.com/odyniec/imgareaselect

**Comment by x09326** [comment]
@PeterDaveHello So I need to add other versions and modify the autoupdate, right?

**Comment by PeterDaveHello** [comment]
Looks like you only need to add auto-update config in this case.

**Comment by x09326** [comment]
@PeterDaveHello I found the structure of [lib](https://github.com/odyniec/imgareaselect) which is different from ours. #1546  What should I do?

**Comment by PeterDaveHello** [comment]
No mind, #1546 was a long time ago PR, and we didn't have auto-update then, so just add an auto-update config, I'll handle the remaining updates works and filename change.

**Comment by x09326** [comment]
So I just need to add auto-update config follow the structure of our libs, right?
