### ISSUE TITLE
[Request] AwesomeTableJs

### ISSUE THREAD

**Issue by farshadjahanmanesh** [cdnjs/cdnjs#6208]
**Library name:AwesomeTableJs** 
**Git repository url:https://github.com/farshadjahanmanesh/awesomeTableJs**
**npm package url(optional):** 
**License(s):by me**
**Official homepage:awesometableJs.aorb.ir**
**Wanna say something? Leave message here:create table from JSON , generate search box,sorting,filtering,pagination tags automatically**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @farshadjahanmanesh, thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!

**Comment by PeterDaveHello** [comment]
This issue will be closed if there is no any response for 7 days.

**Comment by Piicksarn** [comment]
Closed due to no response.
