### ISSUE TITLE
[Request] Add tinyColorPicker

### ISSUE THREAD

**Issue by 9dev** [cdnjs/cdnjs#6210]
**Library name:** tinyColorPicker
**Git repository url:** https://github.com/PitPik/tinyColorPicker
**npm package url(optional):** -
**License(s):** MIT
**Official homepage:** http://www.dematte.at/tinyColorPicker/
**Wanna say something? Leave message here:** There are not a lot of good jQuery color pickers out there. This one is really good piece of work. Lightweight, fast, cross-browser, pluggable and still in development. It surely deserves to be added.

**Comment by maruilian11** [comment]
@9dev sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by Amomo** [comment]
closed due to no response.

**Comment by PitPik** [comment]
Hi @maruilian11, hi @9dev,
who wants to reopen this ticket? ;o)
I'll promise that I will still put effort into this library!

**Comment by maruilian11** [comment]
@PitPik this lib is ok to add, i'll add it asap.

**Comment by maruilian11** [comment]
hi @PitPik, could you please add git tags for each released version so that we can add it with **git auto-update**, thank you!

**Comment by PitPik** [comment]
Hey @maruilian11,
thanks! Git tagging is done (v1.0.1)

**Comment by maruilian11** [comment]
hi @PitPik ,
tinyColorPicker has been added, you'll see on cdnjs few hours later :smiley:

**Comment by PitPik** [comment]
Hi @maruilian11,
thanks, great :smiley:

**Comment by PitPik** [comment]
Hi @maruilian11,
I just realized that you added https://cdnjs.cloudflare.com/ajax/libs/tinyColorPicker/1.0.3/jqColorPicker.js, jqColorPicker.js.map and jqColorPicker.min.js.
The last 2 (jqColorPicker.js.map and jqColorPicker.min.js) make sense, but jqColorPicker.js without colors.js doesn't ( jqColorPicker.js has colors.js as dependency).
So, https://raw.githubusercontent.com/PitPik/tinyColorPicker/master/colors.js is missing.

Does that make sense to you ;o)?
Thanks a lot.

**Comment by maruilian11** [comment]
@PitPik thank you! i will send a PR for it.
