### ISSUE TITLE
babel-core returns 0 byte file

### ISSUE THREAD

**Issue by Daniel15** [cdnjs/cdnjs#6215]
https://cdnjs.cloudflare.com/ajax/libs/babel-core/6.0.20/browser.js

**Comment by PeterDaveHello** [comment]
We grab it from official npm package:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/babel-core/package.json#L74-L82
```js
  "npmName": "babel-core",
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "browser*.js"
      ]
    }
  ],
```

**Comment by Daniel15** [comment]
You should be using `babel-browser` package, not `babel-core`.

**Comment by PeterDaveHello** [comment]
I'll take a look at it but I believe that was not wrong before, unless its doc still says babel-core:
https://babeljs.io/docs/setup/#babel_in_browser
![temp](https://cloud.githubusercontent.com/assets/3691490/11199128/b52044b2-8d05-11e5-9442-65eb7e31d11c.png)

And I don't think that is the same issue, about changing to another package and empty content.

**Comment by Daniel15** [comment]
Ahh, looks like that doc page is out of date. This one says babel-browser: https://babeljs.io/docs/usage/browser/

It may have changed as part of Babel v6. cc @sebmck

**Comment by PeterDaveHello** [comment]
https://github.com/babel/babel.github.io/pull/573

**Comment by PeterDaveHello** [comment]
Seems I am correct, that's two issues, `babel-browser` only started from v6.1.2
 ~ $ curl https://registry.npmjs.com/babel-browser | [jq](https://stedolan.github.io/jq/) .time
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15242  100 15242    0     0   9311      0  0:00:01  0:00:01 --:--:--  9316
```js
{
  "modified": "2015-11-12T22:18:43.910Z",
  "created": "2015-11-05T11:10:49.292Z",
  "6.1.2": "2015-11-05T11:10:49.292Z",
  "6.1.3": "2015-11-05T11:31:44.195Z",
  "6.1.4": "2015-11-11T10:49:50.786Z",
  "6.1.5": "2015-11-12T06:49:19.568Z",
  "6.1.6": "2015-11-12T07:34:25.668Z",
  "6.1.7": "2015-11-12T07:37:43.304Z",
  "6.1.8": "2015-11-12T07:41:54.961Z",
  "6.1.9": "2015-11-12T07:47:31.585Z",
  "6.1.10": "2015-11-12T07:53:17.885Z",
  "6.1.11": "2015-11-12T07:58:43.467Z",
  "6.1.12": "2015-11-12T08:48:21.912Z",
  "6.1.13": "2015-11-12T19:58:06.403Z",
  "6.1.14": "2015-11-12T20:01:44.294Z",
  "6.1.15": "2015-11-12T20:17:26.190Z",
  "6.1.16": "2015-11-12T21:33:39.033Z",
  "6.1.17": "2015-11-12T21:43:46.613Z",
  "6.1.18": "2015-11-12T21:46:49.325Z",
  "6.1.19": "2015-11-12T22:18:43.910Z"
}
```

**Comment by PeterDaveHello** [comment]
Issue create for the empty files:
https://phabricator.babeljs.io/T6639

**Comment by PeterDaveHello** [comment]
Please try the new versions first.

* 51c5e30 add babel-core v6.1.2~6.1.19
https://cdnjs.com/libraries/babel-core/6.1.19

**Comment by Daniel15** [comment]
Thanks, seems to be working :D

**Comment by PeterDaveHello** [comment]
@Daniel15 and let's leave this issue opened untill the 6.0.x version working.

**Comment by PeterDaveHello** [comment]
As @loganfsmyth replied:

https://phabricator.babeljs.io/T6639
> This is by design. The browser build of Babel has been deprecated in favor of people bundling it themselves with browserify if you need it because Babel 6 no longer includes any plugins by default and users will need to bundle the plugins themselves anyway.
