### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by juliusnarh** [cdnjs/cdnjs#6219]
jquery.min.js
http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
**npm package url(optional):** 
**License(s):**
cdnjs.cloudflare.com
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@juliusnarh What is this for?

**Comment by PeterDaveHello** [comment]
Close duo to no response.
