### ISSUE TITLE
[Request] Add Coffeequate

### ISSUE THREAD

**Issue by therealgregvernon** [cdnjs/cdnjs#6221]
**Library name:** Coffeequate
**Git repository url:** https://github.com/MatthewJA/Coffeequate
**npm package url(optional):** coffeequate
**License(s):** MIT
**Official homepage:** http://coffeequate.readthedocs.org/en/latest
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @therealgregvernon , thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.
