### ISSUE TITLE
[Request] Add REM-unit-polyfill

### ISSUE THREAD

**Issue by flgarrid** [cdnjs/cdnjs#6222]
**Library name:** REM-unit-polyfill
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail?

**Comment by PeterDaveHello** [comment]
https://github.com/chuckcarpenter/REM-unit-polyfill
