### ISSUE TITLE
[Request] AnimatedHeader

### ISSUE THREAD

**Issue by RobertBaldini** [cdnjs/cdnjs#6223]
AnimatedHeader
**Repo:** https://github.com/codrops/AnimatedHeader
**Home page:** http://tympanus.net/codrops/2013/06/06/on-scroll-animated-header/

**Comment by Piicksarn** [comment]
@RobertBaldini,
The lib would be added as the tags used.
Thanks for your suggestion!  :)))

Piicksarn

**Comment by maruilian11** [comment]
@botelho could you please consider adding tags for each version? thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello seems no response for a month. how can we do for this issue?

**Comment by PeterDaveHello** [comment]
Maybe just manually add as v0.0.1
