### ISSUE TITLE
[Request] jqZoom

### ISSUE THREAD

**Issue by ihsinh** [cdnjs/cdnjs#6226]
**Library name:** jqZoom
**Git repository url:** nop, but I found it from  http://www.myjqueryplugins.com/jquery-plugin/jqzoom
**npm package url(optional):** 
**License(s):** 
**Official homepage:**
**Wanna say something? Leave message here:**Looks like the library no Git repository and no Official homepage and unknow License, but it is good useful tool in image zoom function. is the library still could be added ?

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@ihsinh It will be hard

**Comment by PeterDaveHello** [comment]
@ihsinh please open issue again once it has clear repo and license info, thanks!
