### ISSUE TITLE
[Request] Add CSSgram

### ISSUE THREAD

**Issue by dyaa** [cdnjs/cdnjs#6227]
**Library name:** CSSgram
**Git repository url:** https://github.com/una/CSSgram
**npm package url(optional):** https://www.npmjs.com/package/cssgram
**License(s):** MIT
**Official homepage:** http://una.im/CSSgram/

**Comment by PeterDaveHello** [comment]
What files should be included here?

**Comment by dyaa** [comment]
I Should be those files here https://github.com/una/CSSgram/tree/master/source/css 
Specially
- cssgram.css
- cssgram.min.css

**Comment by PeterDaveHello** [comment]
@dyaa thanks, will take a look at it later.

**Comment by PeterDaveHello** [comment]
@dyaa : can we only host cssgram.css & cssgram.min.css? Do they include all the features? Or we need to host all the files under that folder?

**Comment by dyaa** [comment]
You Can just host the cssgram.css & cssgram.min.css they include all of the features .

**Comment by PeterDaveHello** [comment]
Oh good.

**Comment by PeterDaveHello** [comment]
@maruilian11 please add it.

**Comment by maruilian11** [comment]
@PeterDaveHello got it.

**Comment by dyaa** [comment]
@maruilian11 any updates !

**Comment by maruilian11** [comment]
@dyaa sorry, i need to add other earily requesting libs.
but if you need i can add this one asap :smiley:
