### ISSUE TITLE
[Request] /ajax/libs/cookieconsent2/cookieconsent.js

### ISSUE THREAD

**Issue by clickweb4u** [cdnjs/cdnjs#6229]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What is this for? Please give us more details, thanks.

**Comment by Amomo** [comment]
Hi @clickweb4u 
Could you provide more details about your request? Or this issue would be closed in next 7 day.

**Comment by clickweb4u** [comment]
NEVER MIND I DONT UNDERSTUND HOW TO PUT ONLINE MY APLICATION

**Comment by clickweb4u** [comment]
SO I HOSTED ON GOOGLE DRIVE

**Comment by PeterDaveHello** [comment]
So I think we can close this.
