### ISSUE TITLE
[Request] Add juicy-cookie

### ISSUE THREAD

**Issue by ellisthedev** [cdnjs/cdnjs#6235]
**Library name:** Juicy Cookie
**Git repository url:** https://github.com/iambumblehead/juicy-cookie
**npm package url(optional):** https://www.npmjs.com/package/juicy-cookie
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @ellisthedev 

This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
We suggest you open an issue again when the library has more popularity.

Thanks for your contribution. :-)

**Comment by Amomo** [comment]
@ellisthedev this issue will be closed if there is no any response in next 7 day.
Thank you for your contribution. :-)

**Comment by glensc** [comment]
@Amomo and what should he respond with if you clearly said you won't add the library as it doesn't have enough popularity? convince your otherwise? faking some popularity?

**Comment by PeterDaveHello** [comment]
@glensc I think @Amomo just wants to make sure @ellisthedev received this message, and we only closed the issues if there is no response, in fact, I know some libs just started and didn't have popularity on GitHub but in fact have popularity on Facebook, so the author just posted a message to Facebook page and invited some users to give the lib a star, then we quickly confirmed that this is a lib need to be hosted on cdn, then added.

We all are contributors and we are all busy, sometimes we missed the GitHub notifications, the ping message just prevent to close a wrong issue or drop a wrong lib which should not be dropped, that's the point.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by ellisthedev** [comment]
Just saw this, my notifications are 99.99% Laravel related stuff; sorry.

Why does a library have to have a certain star count to be added? I use CDNJS for _everything_ I use on our project and this is one that is not there. It would be nice to keep it all on CDNJS for our users; but if I have to load it from our servers I guess I will.

Kind of depressing. :(

**Comment by PeterDaveHello** [comment]
@ellisthedev I'm sorry, it's impossible to add all the libs on cdn, there are too many, there must be a limit.

**Comment by ellisthedev** [comment]
How is the CDN setup? Seems like one could capitalize on setting up a CDN that aggregates library's that are installable via NPM or Bower so it's all automated. Only task would be to have people submit a build script and worry about disk space.

Like, Homebrew for CDN hosting. Hmmmm. :)

**Comment by PeterDaveHello** [comment]
I have to say it again, if host all the libs, the overhead is too high. The purpose of cdn is to relieve, decrease the loading of the network, and also speed it up. I'm sorry.
