### ISSUE TITLE
Merge CONTRIBUTING-WIP.md into CONTRIBUTING.md

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6236]
[CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md)
[CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md)

it's time to merge(maybe also need to update) these two files :+1: 

Ping me if there is any ambiguous policies or anything.

**Comment by MattIPv4** [comment]
cc @AmNotADev

**Comment by MattIPv4** [comment]
I did not GitHub...

**Comment by MattIPv4** [comment]
I think this one probably can actually be closed, the docs in this repo will be replaced by new ones in the packages-migration repo.

**Comment by xtuc** [comment]
I was concerned about the time the migration could take, maybe we want to fix this before migrating the docs over?

**Comment by MattIPv4** [comment]
It seems like this would just create more work as the docs would need adjusting to be used in the current setup, and then further changes need to be made to them to reflect the new post-migration setup.

IMO, the docs in this repo have been as they are for a long time, a few more weeks/months like this before we do the migration would be fine?

**Comment by PeterDaveHello** [comment]
It's no need to migrate and rewrite the doc before the new model of how the library update would work, the effort won't worth it. This one should be closed.

**Comment by xtuc** [comment]
The new model of libray update will be similar enough I suppose, but I agree with @MattIPv4 that a couple weeks more  as is would be fine
