### ISSUE TITLE
[Request] pdfjs-dist

### ISSUE THREAD

**Issue by ziahamza** [cdnjs/cdnjs#6237]
pdfjs-dist
https://github.com/mozilla/pdfjs-dist
https://www.npmjs.com/package/pdfjs-dist
Apache-2.0
https://mozilla.github.io/pdf.js/
Its the library published by mozilla to use their pdf viewer on any webpage. Its available on bower and npm

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
cc  #5020
