### ISSUE TITLE
[Request] Add Typescript_1.6.2

### ISSUE THREAD

**Issue by park-brian** [cdnjs/cdnjs#6238]
**Typescript** 
**Git repository url: https://github.com/microsoft/typescript**
**npm package url(optional):** 
**License(s): Apache License Version 2.0**
**Official homepage: http://www.typescriptlang.org**
**Wanna say something? Leave message here:**

The file can be located at: 
https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/typescript.js

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
I wonder what are the files should be included, cc @cdnjs/team-cdnjs .

**Comment by park-brian** [comment]
Hi, the path to the file is here: https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.js

Currently the version at https://cdnjs.com/libraries/typescript is 1.0.0 and the official stable version is 1.6.2. If you could update the library that would be great.

Thank you!

**Comment by PeterDaveHello** [comment]
@Piicksarn please add this lib, thanks.

**Comment by Amomo** [comment]
Some issue with #6102, I will take this.

**Comment by PeterDaveHello** [comment]
Close duplicated issue.
