### ISSUE TITLE
[Request] alertify.js

### ISSUE THREAD

**Issue by SaphuA** [cdnjs/cdnjs#6243]
**Library name:** alertify.js
**Git repository url:** https://github.com/alertifyjs/alertify.js
**npm package url(optional):** https://www.npmjs.com/package/alertify.js
**License(s):** MIT
**Official homepage:** https://alertifyjs.org/
**Wanna say something? Leave message here:**
There's already a different package on CDNJS called alertify.js, but this is no longer maintained (http://fabien-d.github.io/alertify.js/).

**Comment by PeterDaveHello** [comment]
@maruilian11 be care of the naming.

**Comment by maruilian11** [comment]
@PeterDaveHello got it!
