### ISSUE TITLE
[Request] material-design-color-palette

### ISSUE THREAD

**Issue by elwadi** [cdnjs/cdnjs#6249]
**Library name:**  material-design-color-palette
**Git repository url:** https://github.com/zavoloklom/material-design-color-palette
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @elwadi, we need the lib to have higher notable popularity so that there is a real need to be hosted on cdn, would you please send this request again in future?

**Comment by Amomo** [comment]
This issue will be closed if there is no any response in next 7 day.

**Comment by PeterDaveHello** [comment]
Close due to no response.
