### ISSUE TITLE
[Request] Tipue-Search

### ISSUE THREAD

**Issue by kdeldycke** [cdnjs/cdnjs#6250]
**Library name:** Tipue-Search
**Git repository url:** https://github.com/Tipue/Tipue-Search
**npm package url(optional):**
**License(s):** MIT
**Official homepage:** http://www.tipue.com/search/
**Wanna say something?** Leave message here:
I made a poor attempt at proper packaging Tipue-Search for easier integration into cdnjs at https://github.com/Tipue/Tipue-Search/pull/27 but not certain I'm on the right track... :(

**Comment by PeterDaveHello** [comment]
@kdeldycke I will take a look at it.

**Comment by PeterDaveHello** [comment]
@maruilian11 please take a look.

**Comment by maruilian11** [comment]
@kdeldycke i think adding package.json is great, but you still can keep `Tipue-Search.jquery.json`.
there are many libs own both `.json`s

**Comment by kdeldycke** [comment]
Thanks @PeterDaveHello ! :)

**Comment by PeterDaveHello** [comment]
No probs.
