### ISSUE TITLE
[Request] bootstrap-notify

### ISSUE THREAD

**Issue by KimKJDesigns** [cdnjs/cdnjs#6251]
bootstrap-notify
https://github.com/mouse0270/bootstrap-notify.git
https://github.com/mouse0270/bootstrap-notify
The MIT License (MIT) Copyright (c) 2015 Robert McIntosh
http://bootstrap-notify.remabledesigns.com/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mouse0270** [comment]
I am working on version 4.0beta right not. I will look into updating the tags over the week though. I'll comment here once I have done so. Sorry, I thought it was all the way updated.

Please keep in mind there is already I library assigned with the name Bootstrap Notify which isn't mine. I am not sure how you handle such conflicts.

**Comment by PeterDaveHello** [comment]
@mouse0270 thanks for reply, we can use mouse0270-bootstrap-notify to avoid the conflicts!

**Comment by mouse0270** [comment]
Is there anything I have to do to keep this updated after it gets added?

**Comment by PeterDaveHello** [comment]
@mouse0270 you can reply on this issue ticket :if you won't mind to ping us :)

**Comment by PeterDaveHello** [comment]
Added #6727
