### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.js

### ISSUE THREAD

**Issue by ramabreddy** [cdnjs/cdnjs#6252]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What is this for?

**Comment by Piicksarn** [comment]
@ramabreddy  :smiley: 
**`This issue will be closed if there is no any response in next 7 day.`**

Thanks
Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
