### ISSUE TITLE
[Request] foundation-sites

### ISSUE THREAD

**Issue by cjmaxik** [cdnjs/cdnjs#6253]
**Library name:** Foundation for Sites (v6.0)
**Git repository url:** https://github.com/zurb/foundation-sites
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://foundation.zurb.com/
**Wanna say something? Leave message here:**

**Comment by PeterDaveHello** [comment]
@cjmaxik cool, i will take a look at it.

**Comment by PeterDaveHello** [comment]
I think foundation-sites is the new name of foundation and we have foundation here: https://cdnjs.com/libraries/foundation

but I have a problem with the new version here https://github.com/zurb/foundation-sites/issues/7049, so will add it later.

**Comment by PeterDaveHello** [comment]
v6.0.1 added:
https://github.com/cdnjs/cdnjs/commit/50062b2bf19ecb8b37417c68d6ad21976c4ab9f2
https://github.com/cdnjs/cdnjs/commit/ae7b9e734e1e7afd15d8198fd714ae3328e2cdea
