### ISSUE TITLE
[Request] JS-Interpreter

### ISSUE THREAD

**Issue by binarez** [cdnjs/cdnjs#6254]
**Library name:** JS-Interpreter
**Git repository url:** https://github.com/NeilFraser/JS-Interpreter
**npm package url(optional):** 
**License(s):** Apache License
**Official homepage:** https://neil.fraser.name/software/JS-Interpreter/
**Wanna say something? Leave message here:**
Thanks!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello can we use this [npm ](https://www.npmjs.com/package/js-interpreter)that is fork of requested library?

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
