### ISSUE TITLE
jatec 

### ISSUE THREAD

**Issue by docjojo** [cdnjs/cdnjs#6263]
**Library name: ** 
jatec

**Descripton**
jATEC is a fast and concise JavaScript Library that simplifies HTML DOM handling and Ajax interactions for rapid web development. You are free to use the jATEC framework in your own projects.

**Git repository url: **
https://github.com/docjojo/jatec

**License(s):**
public use

**Official homepage: **
http://jatec.atec-systems.com/

**Wanna say something? Leave message here:**
please host
https://raw.githubusercontent.com/docjojo/jatec/gh-pages/2.0/jatec-2.0.min.js

Best regards, Chris

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@docjojo this lib needs higher notable popularity to be added on the cdn.

**Comment by docjojo** [comment]
ok, thanks.

**Comment by PeterDaveHello** [comment]
@docjojo I think you can send a request to add this lib when it got the higher popularity, so let's close this one.
