### ISSUE TITLE
[Request] Add Faisca CSS

### ISSUE THREAD

**Issue by nandomoreirame** [cdnjs/cdnjs#6267]
**Library name:** Faisca CSS
**Git repository url:** https://github.com/nandomoreirame/faisca-css
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/nandomoreirame/faisca-css
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@nandomoreirame this lib needs higher notable popularity to be added on the cdn.

**Comment by maruilian11** [comment]
@nandomoreirame this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.
