### ISSUE TITLE
[Request] select2-bootstrap-theme

### ISSUE THREAD

**Issue by chipco** [cdnjs/cdnjs#6271]
**Library name:** select2-bootstrap-theme
**Git repository url:** https://github.com/select2/select2-bootstrap-theme
**License(s):** MIT
**Official homepage:** https://select2.github.io/select2-bootstrap-theme/

**Comment by Piicksarn** [comment]
@chipco, thanks for your suggestion!
The library would considered to be included when it is stable version.
Please remind us or send a pull request again as it release the stable version!

Piicksarn

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/cdnjs/cdnjs/issues/6271.

**Comment by PeterDaveHello** [comment]
@kevin-brown this is #6271

**Comment by PeterDaveHello** [comment]
oh but it's duplicated with #5984, so close this one.
