### ISSUE TITLE
[Request] crEl

### ISSUE THREAD

**Issue by xneek** [cdnjs/cdnjs#6280]
**Library name:crEl** 
**Git repository url:https://github.com/xneek/crEl.git**
**License(s):MIT**
**Official homepage:https://github.com/xneek/crEl/**
**Wanna say something? Leave message here:A small constructor for generated DOM elements**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@xneek  sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
because no respond, i close this issue
