### ISSUE TITLE
[Request] Add jQuery SliderAccess

### ISSUE THREAD

**Issue by aensley** [cdnjs/cdnjs#6286]
**Library name:** jQuery SliderAccess
**Git repository url:** https://github.com/trentrichardson/jQuery-SliderAccess
**npm package url(optional):** 
**License(s):** MIT, GPL
**Official homepage:** http://trentrichardson.com/examples/jQuery-SliderAccess/
**Wanna say something? Leave message here:**

@trentrichardson's [jQuery Timepicker Addon](https://github.com/trentrichardson/jQuery-Timepicker-Addon) is [already on CDNJS](https://cdnjs.com/libraries/jquery-ui-timepicker-addon). That plugin includes an option to use this plugin. Would be great to be able to load both from CDNJS.

**Comment by swapnil0545** [comment]
Yes it will be great to have this on cdn.

**Comment by aensley** [comment]
Indeed you do! Sorry I missed that. I was expecting to see it listed as a separate plugin since it was developed that way. SliderAccess's version isn't tied to Timepicker Addon's, so I didn't expect to see them together.

**Comment by PeterDaveHello** [comment]
@aensley jQuery SliderAccess its self doesn't have enough popularity to be hosted individually on cdnjs, but thanks @swapnil0545, I think you can access it via other libs.

**Comment by aensley** [comment]
@PeterDaveHello Yup. That works! I only wanted it for use with the other plugin I mentioned, so I'm just including it from there now. Thanks!

**Comment by PeterDaveHello** [comment]
:+1:
