### ISSUE TITLE
[Request] Add oneline.min.js

### ISSUE THREAD

**Issue by nadirhamid** [cdnjs/cdnjs#6287]
Oneline Client
http://github.com/nadirhamid/
**npm package url(optional):** 
**License(s):** MIT
**Official homepage: http://getoneline.com/
**Wanna say something? Leave message here:**
Hi, I'd like to submit my package to this CDN. I am unsure why however it may be better in the attempts of trying to get the releases hosted nicely, however a source. Currently I use my own domain

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@nadirhamid  sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
because no respond, i close this issue
