### ISSUE TITLE
moment-jdateformatparser

### ISSUE THREAD

**Issue by wilswong** [cdnjs/cdnjs#6299]
**Library name:moment-jdateformatparser
**Git repository url: https://github.com/MadMG/moment-jdateformatparser
**npm package url(optional):https://www.npmjs.com/package/moment-jdateformatparser
**License(s): MIT license
**Official homepage:https://github.com/MadMG/moment-jdateformatparser
**Wanna say something? Leave message here:

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @wilswong  ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
