### ISSUE TITLE
Update some out-dated repo info of libs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6312]
Some libs changed their owner or name, even deleted their repo, for the repo didn't been deleted, we need to update their repo url! 

I listed the lib can't be fetched properly and also wrote their lib name down.

 - github.com/subkit/angularsubkit.js (library name - angularSubkit)
 - github.com/projectBS/bsJS (library name - bsjs)
 - github.com/neteye/jquery-plugins (library name - jquery.activity-indicator)
 - github.com/rndme/download.js (library name - downloadjs)
 - github.com/j-l-n/noti.js (library name - noti.js)
 - github.com/n33/skel-layers (library name - skel-layers)
 - github.com/subkit/subkit.js (library name - subkit)
 - github.com/andyet/ICanHaz.js (library name - ICanHaz.js)
 - github.com/tybenz/legojs (library name - legojs)
 - github.com/720kb/radiobox (library name - radiobox.css)

**Comment by PeterDaveHello** [comment]
Related issue:
https://github.com/cdnjs/new-website/issues/69

**Comment by PeterDaveHello** [comment]
I did some:
* 7687b2c update repo url of react-redux
* f3849a0 update repo url of jQuery-linkify
* b6ab16d update repo url of jquerykeyframes
* c95a442 update npm/git repo name of custom-elements-builder
* bc88a0b update repo url of foundation

**Comment by LeaYeh** [comment]
@PeterDaveHello 
how could i find the new lib name? 
and how could i make sure the two lib are same after change author name?

**Comment by PeterDaveHello** [comment]
@LeaYeh We should review the library and author info in the repo, and discuss with author if it's need.

**Comment by NYCJacob** [comment]
@PeterDaveHello  is this still an issue, I'd be willing to work on this

**Comment by PeterDaveHello** [comment]
@NYCJacob I believe that we didn't solve it yet, welcome to join and feel free to ask for help!

**Comment by NYCJacob** [comment]
should I wait till you update, can you point me to where the listing code is

**Comment by PeterDaveHello** [comment]
@NYCJacob please give me few days to make sure we still have issue on it so that we'll not waste your time.

**Comment by PeterDaveHello** [comment]
@NYCJacob list updated!

**Comment by NYCJacob** [comment]
@PeterDaveHello ok I'm on it

**Comment by PeterDaveHello** [comment]
@NYCJacob Thanks!

**Comment by NYCJacob** [comment]
@PeterDaveHello I have checked all the links.  Most of them are not longer there but I have emailed the user it most cases.  Some have been renamed but I have email them also just to be sure.  I noticed that there are a couple of urgent flags to update the repo for new versions.  I thought maybe I could take care of that while I wait for these responses.

**Comment by PeterDaveHello** [comment]
@NYCJacob sounds really great! Thanks for your contribution!

**Comment by NYCJacob** [comment]
@PeterDaveHello couple of questions,  I have not been able to clone the repo to my machine because of disk space issues.  So I can't run the tests but I hope those are really only for new library additions.  Also, can I do one pull for all the update changes or should I do one pull for each?   Also, for the urgent flags to add a new library, isn't that the job of the library developer?  Sorry, for all the questions I am still new at this.

**Comment by PeterDaveHello** [comment]
@NYCJacob it's fine to send PR online on GitHub gui, it's both fine to send multi PR or a single one.

**Comment by PeterDaveHello** [comment]
the **urgent flags**, do you mean the "High Priority" label?
