### ISSUE TITLE
test2ccs.css

### ISSUE THREAD

**Issue by geoaetos** [cdnjs/cdnjs#6314]
mmmm

**Comment by PeterDaveHello** [comment]
What is this for?

**Comment by LeaYeh** [comment]
@geoaetos what is this issue mean? 
if no response we would close this issue after 3 days.

**Comment by LeaYeh** [comment]
because no respond i close it.

**Comment by geoaetos** [comment]
is rong :( sorry

2015-12-05 19:11 GMT+02:00 yehya <notifications@github.com>:
