### ISSUE TITLE
[Request] Add phina.js

### ISSUE THREAD

**Issue by phi-jp** [cdnjs/cdnjs#6315]
**Library name:** phina.js
**Git repository url:** https://github.com/phi-jp/phina.js/
**License(s):** MIT
**Official homepage:** http://phinajs.com

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@phi-jp,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
