### ISSUE TITLE
[Request] Add react-highcharts

### ISSUE THREAD

**Issue by kirjs** [cdnjs/cdnjs#6317]
**Library name:** react-highcharts
**Git repository url:** https://github.com/kirjs/react-highcharts
**npm package url(optional):** https://www.npmjs.com/package/react-highcharts
**License(s):** MIT
**Official homepage:** https://github.com/kirjs/react-highcharts
**Wanna say something? Leave message here:**
cdnjs is awesome, thanks a lot!

**Comment by PeterDaveHello** [comment]
What are the files should be hosted on the cdn?

**Comment by kirjs** [comment]
Hi peter, please see the paths below:
```bash
dist/highcharts.js
dist/highcharts.src.js
dist/highmaps.js
dist/highmaps.src.js
dist/highstock.js
dist/highstock.src.js
```

**Comment by PeterDaveHello** [comment]
Would you like to send a PR to add it?
