### ISSUE TITLE
openDiv

### ISSUE THREAD

**Issue by victorshkoda** [cdnjs/cdnjs#6319]
**Library name:*openDiv

* 
**Git repository url:**
**npm package url(optional):** 
**License(s):**

**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Is there any details about this lib?

**Comment by victorshkoda** [comment]
Simple JQuery plugin for opening units by pressing the button (link) with adjustable opening and closing speed blocks.

**Comment by PeterDaveHello** [comment]
@victorshkoda we need its source repository to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.
