### ISSUE TITLE
[Request] Add jQuery-CPF-CNPJ-Validator-plugin

### ISSUE THREAD

**Issue by ricardodantas** [cdnjs/cdnjs#6320]
**Library name:** /jQuery-CPF-CNPJ-Validator-plugin
**Git repository url:** https://github.com/gmgomess/jQuery-CPF-CNPJ-Validator-plugin
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://github.com/gmgomess/jQuery-CPF-CNPJ-Validator-plugin
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @ricardodantas 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

This issue will be closed if there is no any response in next 7 day.

**Comment by Amomo** [comment]
closed due to no response.
