### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.map

### ISSUE THREAD

**Issue by sanketgandhe** [cdnjs/cdnjs#6347]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hey what is this for @sanketgandhe ？

**Comment by Piicksarn** [comment]
@sanketgandhe,
**`This issue will be closed if there is no any response in next 7 day.`**

thank you!
Piicksarn

**Comment by PeterDaveHello** [comment]
Close due to no response for a long time.
