### ISSUE TITLE
[Request] JsRender

### ISSUE THREAD

**Issue by abdulhannanali** [cdnjs/cdnjs#6350]
**JsRender** 
**https://github.com/BorisMoore/jsrender**
**npm package url(optional):** 
**MIT**
**http://www.jsviews.com/**
**Please upload it and I love CdnJS**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mably** [comment]
+1

**Comment by abdulhannanali** [comment]
thanks everyone

**Comment by abdulhannanali** [comment]
@maruilian11 special thanks to you

**Comment by maruilian11** [comment]
@abdulhannanali :+1:

**Comment by BorisMoore** [comment]
I have just updated JsRender to v0.9.71. It should fix the autoupdate issue. (See https://github.com/BorisMoore/jsrender/issues/278#issuecomment-162769636). Thanks for your work on cdnjs!

**Comment by PeterDaveHello** [comment]
https://github.com/cdnjs/cdnjs/pull/6499#issuecomment-166228870
