### ISSUE TITLE
[Request] Add jsnetworkx

### ISSUE THREAD

**Issue by TakeshiTseng** [cdnjs/cdnjs#6354]
**Library name:** jsnetworkx
**Git repository url:** https://github.com/fkling/JSNetworkX.git
**npm package url(optional):** https://www.npmjs.com/package/jsnetworkx
**License(s):** BSD
**Official homepage:** jsnetworkx.org
**Wanna say something? Leave message here:**

- [x] Not found on cdnjs repo
- [x] No already exist issue and PR
- [x] Notable popularity (Star : 284, Fork : 65)
- [x] Project has public repository on famous online hosting platform (hosted on npm)
- [x] Has valid tags for each versions (for git auto-update)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What are the files will be needed to be hosted on cdn in this case?

**Comment by TakeshiTseng** [comment]
We need to include this file in the web page before use it:
https://github.com/fkling/JSNetworkX/blob/master/jsnetworkx.js

**Comment by PeterDaveHello** [comment]
Hey @Piicksarn please take a look at this, thanks.

**Comment by Piicksarn** [comment]
@PeterDaveHello, i got it!

**Comment by PeterDaveHello** [comment]
hmmm ... I used a wrong label, @Piicksarn please add it.
