### ISSUE TITLE
[Request] Add bootstrap-block-grid

### ISSUE THREAD

**Issue by JohnnyTheTank** [cdnjs/cdnjs#6357]
**Library name:** bootstrap-block-grid
**Git repository url:** https://github.com/JohnnyTheTank/bootstrap-block-grid.git
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/JohnnyTheTank/bootstrap-block-grid
**Wanna say something? Leave message here:** only the current version (v1.1.1) is ready for public usage

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @JohnnyTheTank ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.
