### ISSUE TITLE
[Request] Add  wColorPicker

### ISSUE THREAD

**Issue by swapnil0545** [cdnjs/cdnjs#6358]
**Library name:** wColorPicker
**Git repository url:**https://github.com/websanova/wColorPicker
**npm package url(optional):** 
**License(s):**MIT 
**Official homepage:**http://wcolorpicker.websanova.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @swapnil0545 ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
cause no respond, i closed this issue.
