### ISSUE TITLE
[Request] Add angular-clipboard

### ISSUE THREAD

**Issue by dyaa** [cdnjs/cdnjs#6360]
**Library name:** angular-clipboard
**Git repository url:** https://github.com/omichelsen/angular-clipboard
**npm package url(optional):** https://www.npmjs.com/package/angular-clipboard
**License(s):** MIT
**Official homepage:** https://rawgit.com/omichelsen/angular-clipboard/master/demo/demo.html

**Comment by PeterDaveHello** [comment]
Duplicated with #6166 to move to that issue, thanks @dyaa
