### ISSUE TITLE
[Request] Add Library Sidy.js

### ISSUE THREAD

**Issue by youcefhaouatis** [cdnjs/cdnjs#6365]
Library name: Multi-functional jQuery Off-canvas Navigation Plugin - Sidy.js
Git repository url: None
npm package url(optional): http://www.jqueryscript.net/download/Multi-functional-jQuery-Off-canvas-Navigation-Plugin-Sidy-js.zip
License(s): MIT
Official homepage: http://www.jqueryscript.net/menu/Multi-functional-jQuery-Off-canvas-Navigation-Plugin-Sidy-js.html
Wanna say something? Leave message here:
I'd like you to host these 2 files which located in the zipped file mentioned above as "npm package url"
/dist/sidy.css
/dist/sidy.js

Youcef.
Thanks.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by youcefhaouatis** [comment]
Hey Peter,

I did not understand your comment: added Library - Request to Add/Update and removed Library - Request to Add/Update.

Thanks.

Youcef.

**Comment by PeterDaveHello** [comment]
That's a mistake, the label is still there.

**Comment by youcefhaouatis** [comment]
Any updates about this lib?

**Comment by PeterDaveHello** [comment]
Is there a public repository for this lib?

**Comment by youcefhaouatis** [comment]
No, there is a package which is http://www.jqueryscript.net/download/Multi-functional-jQuery-Off-canvas-Navigation-Plugin-Sidy-js.zip

**Comment by youcefhaouatis** [comment]
Please check my first post.

**Comment by PeterDaveHello** [comment]
So how to conform its popularity?

**Comment by youcefhaouatis** [comment]
It's under the License: MIT

**Comment by PeterDaveHello** [comment]
I meant, how do we know it's popular enough to be hosted on a public cdn service?

**Comment by youcefhaouatis** [comment]
Sorry i can not confirm that, because i am not the founder of tha library. It is a library i use it usual. That's why i requested it to be hosted in cdnjs.

**Comment by PeterDaveHello** [comment]
Okay, give us more time to make sure its popularity.

**Comment by youcefhaouatis** [comment]
Ok, thanks!

**Comment by Amomo** [comment]
Hi @youcefhaouatis 
I found its GitHub repo [reactivestudio/Sidy.js](https://github.com/reactivestudio/Sidy.js) at package.json in zip.
Seems this library doesn't have enough popularity(only 10 watch and 11 star).

Currently, we won't add it.
We suggest you to open an issue when the library has more popularity.
Thank you. :-)
