### ISSUE TITLE
[Request] Imager.js

### ISSUE THREAD

**Issue by fiznool** [cdnjs/cdnjs#6373]
**Library name:** Imager.js
**Git repository url:** https://github.com/BBC-News/Imager.js/
**npm package url(optional):**  https://www.npmjs.com/package/imager.js
**License(s):** Apache 2.0
**Official homepage:** http://responsivenews.co.uk/post/58244240772/imagerjs
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by oncletom** [comment]
Thank you @PeterDaveHello and @fiznool :-)

**Comment by PeterDaveHello** [comment]
@oncletom Np
