### ISSUE TITLE
[Request] Add Mottie/tablesorter

### ISSUE THREAD

**Issue by al-sade** [cdnjs/cdnjs#6374]
**Library name: Mottie/tablesorter** 
**Git repository url: https://github.com/Mottie/tablesorter.git**
**npm package url(optional):** 
**License(s): Copyright (c) 2007 Christian Bach.Original examples and docs at: http://tablesorter.com.Dual licensed under the MIT and GPL licenses.**
**Official homepage: http://mottie.github.io/tablesorter/docs/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it here: https://cdnjs.com/libraries/jquery.tablesorter

**Comment by al-sade** [comment]
great thx


2015-12-02 18:02 GMT+02:00 Peter Dave Hello <notifications@github.com>:

**Comment by PeterDaveHello** [comment]
You can search it first next time if you wanna have a lib :+1:
