### ISSUE TITLE
https://raw.githubusercontent.com/mjnaderi/jquery-duration-picker/master/src/jquery-duration-picker.js

### ISSUE THREAD

**Issue by dinopasic** [cdnjs/cdnjs#6377]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@dinopasic, would you please make some detail?

**Comment by dinopasic** [comment]
sorry, this was posted by mistake!
