### ISSUE TITLE
[Request] jquery.placeholder.js v1.4.3

### ISSUE THREAD

**Issue by usmanspecial** [cdnjs/cdnjs#6379]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@usmanspecial please give some details.

**Comment by Amomo** [comment]
Hi @usmanspecial 
This issue will be closed if there is no any response in next 7 day.

**Comment by PeterDaveHello** [comment]
@usmanspecial do you mean the version v1.4.3 of this lib https://cdnjs.com/libraries/jquery-placeholder?

**Comment by PeterDaveHello** [comment]
Close due to no response.
