### ISSUE TITLE
[Request] Add jQuery-ui-Slider-Pips

### ISSUE THREAD

**Issue by LachauxRemi** [cdnjs/cdnjs#6382]
**Library name:** jquery-ui-slider-pips
**Git repository url:** https://github.com/simeydotme/jQuery-ui-Slider-Pips
**npm package url(optional):** 
**License(s):** http://opensource.org/licenses/MIT
**Official homepage:** http://simeydotme.github.io/jQuery-ui-Slider-Pips/
**Wanna say something? Leave message here:** is good library for input range slider

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by simeydotme** [comment]
thanks @maruilian11 and @Piicksarn ! :smile:  great to be part of CDNjs.

**Comment by PeterDaveHello** [comment]
:+1:
