### ISSUE TITLE
[Request] Add gifloopcoder 

### ISSUE THREAD

**Issue by msurguy** [cdnjs/cdnjs#6391]
**Library name:** gifloopcoder
**Git repository url:** https://github.com/msurguy/gifloopcoder
**npm package url(optional):** https://www.npmjs.com/package/gifloopcoder
**License(s):** MIT
**Official homepage:** https://github.com/msurguy/gifloopcoder
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hey @msurguy I just found that you are the author, would you like to send a PR to add it by yourself :smile: ?

**Comment by PeterDaveHello** [comment]
Ping @msurguy

**Comment by msurguy** [comment]
Hi! 

The plans have been changed by the original author of the tool, I have to close this PR for now unfortunately
