### ISSUE TITLE
[Request] Add Blueimp-Load-Image

### ISSUE THREAD

**Issue by samogot** [cdnjs/cdnjs#6401]
**Library name:** Blueimp-Load-Image
**Git repository url:** https://github.com/blueimp/JavaScript-Load-Image
**License(s):** MIT
**Official homepage:** https://blueimp.github.io/JavaScript-Load-Image/
**Wanna say something? Leave message here:** it is dependency for https://cdnjs.com/libraries/blueimp-file-upload

**Comment by Piicksarn** [comment]
Closed due to duplicate lib with #6076
