### ISSUE TITLE
[Request] Add Slider Pro - jQuery slider plugin

### ISSUE THREAD

**Issue by wakjoko** [cdnjs/cdnjs#6404]
**Library name:** 
Slider Pro - jQuery slider plugin
**Git repository url:**
https://github.com/bqworks/slider-pro
**npm package url(optional):** 
**License(s):**
http://opensource.org/licenses/MIT
**Official homepage:**
http://bqworks.com/slider-pro
**Wanna say something? Leave message here:**
this slider is just awesome n should be shared to the community
no need to do extra setup as its default is responsive, not just the slider but including its content
very smart n elegent 
thanks yo

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@wakjoko duplicated with #6387, we will add this lib asap :+1:
