### ISSUE TITLE
[Request] Add flexbox-grid

### ISSUE THREAD

**Issue by PetervMeijgaard** [cdnjs/cdnjs#6411]
**Library name:** flexbox-grid 
**Git repository url:** https://github.com/vivid-web/flexbox-grid-stylus
**npm package url(optional):** https://www.npmjs.com/package/flexbox-grid-stylus
**License(s):** MIT
**Official homepage:** http://flexboxgrid.vivid-websolutions.nl/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @PetervMeijgaard  ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
because no respond, i close this issue

**Comment by PetervMeijgaard** [comment]
Oh sorry, I forgot to react.
It is fine to close this issue.
Have a nice day!
