### ISSUE TITLE
[Request] Add cleverbot.io.js 

### ISSUE THREAD

**Issue by atomictissue** [cdnjs/cdnjs#6412]
**Library name: cleverbot.io.js** 
**Git repository url: https://github.com/CleverbotIO/cleverbot.io.js**
**License(s): MIT**
**Official homepage: http://cleverbotio.github.io/**

**Comment by Amomo** [comment]
Hi @atomictissue 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)

**Comment by Amomo** [comment]
@atomictissue 
This issue will be closed if there is no any response in next 7 day.
