### ISSUE TITLE
[Request]Add twbs-pagination

### ISSUE THREAD

**Issue by k2tzumi** [cdnjs/cdnjs#6414]
**Library name:** 
twbs-pagination
**Git repository url:**
https://github.com/esimakin/twbs-pagination
**npm package url(optional):** 
**License(s):**
http://www.apache.org/licenses/LICENSE-2.0
**Official homepage:**
http://esimakin.github.io/twbs-pagination/

**Comment by AngeIII** [comment]
Just noticed that version number in comment is still old.. Not a problem but will be fixed. https://github.com/esimakin/twbs-pagination/issues/62

**Comment by PeterDaveHello** [comment]
:+1:
