### ISSUE TITLE
[Request] Dummyjs

### ISSUE THREAD

**Issue by spyshiv** [cdnjs/cdnjs#6419]
**Library name: Dummyjs** 
**Git repository url: https://github.com/spyshiv/dummyjs**
**npm package url(optional):** 
**License(s):GNU GENERAL PUBLIC LICENSE Version 2, June 1991**
**Official homepage:http://spyshiv.github.io/dummyjs/**
**Wanna say something? Leave message here:**Dummyjs is js library to generate dummy words, dummy sentences and dummy paragraphs which are very useful while writing a webpage and instead of content you have to write some dummy text like...lorem ipsum dolor sit etc..using dummyjs can save the much time of web developer 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@spyshiv,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by spyshiv** [comment]
OK... I will reopen it when I will get 100 stars
