### ISSUE TITLE
[Request] Add net

### ISSUE THREAD

**Issue by AnthonyKalsatos** [cdnjs/cdnjs#6426]
**Library name:**  net 
**Git repository url:** https://github.com/sleeplessinc/net
**npm package url(optional):** https://www.npmjs.com/package/net
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@AnthonyKalsatos,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
