### ISSUE TITLE
[Request] Add Mikhus/jsurl

### ISSUE THREAD

**Issue by neersighted** [cdnjs/cdnjs#6428]
**Library name:** Mikhus/jsurl
**Git repository url:** https://github.com/Mikhus/jsurl
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/Mikhus/jsurl
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
The lib would be added as the tags used.

**Comment by neersighted** [comment]
Got it, thanks.

**Comment by neersighted** [comment]
It appears that tags have been created.

**Comment by Piicksarn** [comment]
#7024
