### ISSUE TITLE
[Request] Add Skeleton Framework

### ISSUE THREAD

**Issue by gld1982ltd** [cdnjs/cdnjs#6441]
**Library name:**  Skeleton Framework
**Git repository url:** https://github.com/skeleton-framework/skeleton-framework
**npm package url(optional):** https://www.npmjs.com/package/skeleton-framework
**License(s):** MIT
**Official homepage:** http://skeleton-framework.github.io/
**Wanna say something? Leave message here:**  Skeleton Framework is based on Skeleton, but is maintained and supported. New features will be added via a plugin system called bones.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
hi @gld1982ltd  ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by LeaYeh** [comment]
cause no respond, i closed this issue.

**Comment by gld1982ltd** [comment]
I believe we have met the requirements now?

**Comment by PeterDaveHello** [comment]
@gld1982ltd I will take a look at it later, let me off to sleep first :smile:

**Comment by gld1982ltd** [comment]
Awesome. Thanks!
