### ISSUE TITLE
[Request] Add react-f-ui-modal

### ISSUE THREAD

**Issue by hnq90** [cdnjs/cdnjs#6442]
**Library name:** react-f-ui-modal
**Git repository url:** https://github.com/fcomb/react-f-ui-modal
**npm package url:** https://www.npmjs.com/package/react-f-ui-modal
**License(s):** MIT
**Official homepage:** http://fcomb.github.io/react-f-ui-modal/
**Wanna say something? Leave message here:**

### Modal component for React

 __Features__
- full control of content
- outer click closes modal
- esc closes too!
- stateless: just pass active as prop
- animation with react-motion
- overflow scrolls content

**Comment by Piicksarn** [comment]
@hnq90,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by hnq90** [comment]
@Piicksarn Thanks. I will close this issue.
