### ISSUE TITLE
[Request] ng-focus-on

### ISSUE THREAD

**Issue by katsgeorgeek** [cdnjs/cdnjs#6443]
**Library name: ng-focus-on** 
**Git repository url: https://github.com/goodeggs/ng-focus-on**
**License(s): MIT**
**Official homepage: https://github.com/goodeggs/ng-focus-on**

**Comment by Piicksarn** [comment]
@katsgeorgeek,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
