### ISSUE TITLE
[Request] Add JavaScript-Load-Image

### ISSUE THREAD

**Issue by LyTranCong** [cdnjs/cdnjs#6451]
**Library name: JavaScript Load Image
**Git repository url: https://github.com/blueimp/JavaScript-Load-Image
**npm package url(optional): https://www.npmjs.com/package/blueimp-load-image 
**License(s): MIT
**Official homepage: https://blueimp.github.io/JavaScript-Load-Image/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
@LyTranCong 
It is duplicated with #6076, please wait for PR #6101.
Thanks for your suggestion!
