### ISSUE TITLE
[Request] Add angular-bootstrap-lightbox

### ISSUE THREAD

**Issue by rem99** [cdnjs/cdnjs#6452]
**Library name:** angular-bootstrap-lightbox
**Git repository url:** https://github.com/compact/angular-bootstrap-lightbox
**License(s):** MIT
**Official homepage:** http://compact.github.io/angular-bootstrap-lightbox/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
i
