### ISSUE TITLE
[Request] Add EQCSS 

### ISSUE THREAD

**Issue by tomhodgins** [cdnjs/cdnjs#6457]
**Library name:** EQCSS
**Git repository url:** https://github.com/eqcss/eqcss
**npm package url(optional):** https://www.npmjs.com/package/eqcss
**License(s):** MIT
**Official homepage:** http://elementqueries.com
**Wanna say something? Leave message here:**

Thanks for making CDNJS the best!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @tomhodgins, thanks for your request, we usually need a higher popularity to add a lib, but as you are the author of this lib and there this lib has a npm package, I wonder if you can just send a PR with npm auto-update and then I can just merge your PR, what do you think?

**Comment by tomhodgins** [comment]
Hi Peter, Thanks!

Reading the documentation it sounds like I would need to first [add the 'autoupdate' section to my package.json](https://github.com/cdnjs/cdnjs#enabling-npmrecommended-or-git-auto-update) and then [fork CDNJS and add my library](https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library)? Is that correct?

**Comment by PeterDaveHello** [comment]
Please use npm auto-update:
https://github.com/cdnjs/cdnjs#enabling-npmrecommended-or-git-auto-update

Cloning the whole history and checking out all the files may hurt, so please try shallow clone + sparse-checkout:
https://github.com/cdnjs/cdnjs/blob/master/sparseCheckout.md

Thanks.

**Comment by PeterDaveHello** [comment]
Any updates here?

**Comment by tomhodgins** [comment]
Hi Peter!

I've got [EQCSS in NPM](https://www.npmjs.com/package/eqcss), but I wasn't able to do a checkout, even a shallow one, of this repository to add these files to send you a pull request. I have a severe lack of GB and even the smallest checkout I tried made me run out of space :/

All that's required are the files:

-[EQCSS.js](http://elementqueries.com/)
-[EQCSS-polyfills.js](http://elementqueries.com/EQCSS-polyfills.js)

Which are hosted by Github. Hope this helps :)

**Comment by PeterDaveHello** [comment]
Thanks @tomhodgins, I'll take this.

**Comment by tomhodgins** [comment]
Thanks so much @PeterDaveHello <3 I just saw it show up on the live site

**Comment by PeterDaveHello** [comment]
@tomhodgins NP
