### ISSUE TITLE
jwplayer

### ISSUE THREAD

**Issue by glensc** [cdnjs/cdnjs#6458]
Homepage: http://www.jwplayer.com/
Licensing: http://www.jwplayer.com/pricing/
Source Repository: https://github.com/jwplayer/jwplayer
Open Source Releases: https://github.com/jwplayer/jwplayer/releases

would you accept this in your cdn? they do have free plan.
and the sourcecode is available in github

**Comment by PeterDaveHello** [comment]
Hello @glensc, do you know what are the files need to be hosted on cdnjs?

**Comment by glensc** [comment]
i think one needs to assemble (build) them themselves using source code. i can compare the result using commerical version.

**Comment by PeterDaveHello** [comment]
Okay, we need more time to confirm that.

**Comment by PeterDaveHello** [comment]
Sorry for the late reply, the build environment is a little bit complex, I wonder if there is pre-built releases lol ...

**Comment by glensc** [comment]
Pre-built versions exist, but i am not sure that you're allowed to redistribute them. Probably should contact their support and and ask! :)

**Comment by PeterDaveHello** [comment]
@glensc can you do that for us? Thanks.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
