### ISSUE TITLE
[Request] add i18next related libs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6467]
i18next (already on cdnjs):
- https://github.com/i18next/i18next  /  https://cdnjs.com/libraries/i18next

To be added:
- https://github.com/i18next/jquery-i18next
- https://github.com/i18next/i18next-browser-languageDetector

--

cc @jamuhl

**Comment by Amomo** [comment]
added via 5884afce75c73f0d82e8002de4d67061343943b9
