### ISSUE TITLE
add auto-update config for pegjs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6471]
https://cdnjs.com/libraries/pegjs

npm package: pegjs

PS: I'm not sure if it's suitable.

**Comment by Amomo** [comment]
I think we could use this as the source of auto-update.
https://github.com/pegjs/bower

**Comment by PeterDaveHello** [comment]
What about npm?

**Comment by Amomo** [comment]
Files on npm need to build.

**Comment by PeterDaveHello** [comment]
Should ask the author if the filename can be changed.
