### ISSUE TITLE
Update Parsley

### ISSUE THREAD

**Issue by rivets** [cdnjs/cdnjs#6473]
Current non-rc version is 2.1.3 - CDN version is 2.1.2

**Comment by PeterDaveHello** [comment]
Seems the upstream didn't been updated to v2.1.3 yet:
https://www.npmjs.com/package/parsleyjs

**Comment by maruilian11** [comment]
so, we need to open an issue to remind the author to update version to 2.1.3 on npm package, then we can close the issue?

**Comment by PeterDaveHello** [comment]
Yeah of course.

**Comment by maruilian11** [comment]
ok

**Comment by maruilian11** [comment]
@PeterDaveHello they seem to still not add v2.1.3 in npm package, but add v2.2.0, do we need to turn to git auto-update, or we can close this issue?

**Comment by PeterDaveHello** [comment]
Let's manually add v2.1.3, not transfer this time.

**Comment by maruilian11** [comment]
@PeterDaveHello since v2.1.3 has been added on github, can we close this issue?
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/parsley.js/2.1.3

**Comment by PeterDaveHello** [comment]
fine.
