### ISSUE TITLE
Changing package name

### ISSUE THREAD

**Issue by galambalazs** [cdnjs/cdnjs#6474]
Hi!

I'd like to ask if it's possible to change my package name inside `package.json`.

Currently it says "smoothscroll" and I'd like to add it to `npm` and there's already a package with that name so I need to change the name inside my package to "smoothscroll-for-websites"

How does it affect cdnjs which has my library? (and also uses the `package.json` as far as I know)

My repo: https://github.com/galambalazs/smoothscroll-for-websites
https://cdnjs.com/libraries/smoothscroll

Thanks

**Comment by PeterDaveHello** [comment]
Hi @galambalazs, we use `npmName` for the name on npm registry, so I think there is no need to change the `name` in package.json, they don't need to be the same, what do you think?

**Comment by galambalazs** [comment]
I'm not sure I understand. What is npmname?

My problem again:
- I'm currently listed inside CDNJS registry (package.json name:"smoothscroll")
- *Not* listed in NPM

I can't simply add my repo to NPM because "smoothscroll" name is taken. So I was thinking about changing the name to be "smoothscroll-for-websites"

- CDNJS registry (package.json name: "smoothscroll-for-websites")
- Listed in NPM (package.json name: "smoothscroll-for-websites")

I was wondering how that name change would affect cdnjs and my package which is already at this address: https://cdnjs.com/libraries/smoothscroll (with the "smoothscroll" name)

**Comment by PeterDaveHello** [comment]
We can change the name but it may cause some problems, e.g. the old link on cdnjs https://cdnjs.com/libraries/smoothscroll  will not work anymore, my idea is to use "smoothscroll-for-websites" on npm registry, and don't change the name on cdnjs, on cdnjs, the name be used to point to npm will be "npmName" like this:

https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery/package.json#L3-L11
```js
  "npmName": "jquery",
  "npmFileMap": [
    {
      "basePath": "/dist/",
      "files": [
        "jquery.*"
      ]
    }
  ],
```

They don't need to be the same.

**Comment by galambalazs** [comment]
I'm ok with that.

So if I understand it correctly:

1. I change the *name* to "smoothscroll-for-websites" inside my repo's `package.json`: https://github.com/galambalazs/smoothscroll-for-websites/blob/master/package.json

2. Create a PR for the  `package.json` on CDNJS to be (https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/smoothscroll/package.json):
```
"name": "smoothscroll",
"npmName": "smoothscroll-for-websites",
```

Is that correct?

**Comment by galambalazs** [comment]
Or does auto-updating take care of (2)?

**Comment by PeterDaveHello** [comment]
@galambalazs you should manually create the part of npm info, and then auto-update can work on it.
You only need to add npmName and npmFileMap, and jquery can be a good exanple of npm auto-update for you.

**Comment by galambalazs** [comment]
So I need to create a PR to CDNJS with npmName and npmFileMap fields added?
(https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/smoothscroll/package.json)

**Comment by PeterDaveHello** [comment]
@galambalazs Yes you are right!

**Comment by galambalazs** [comment]
ok https://github.com/cdnjs/cdnjs/pull/6476

**Comment by PeterDaveHello** [comment]
Close per #6476
