### ISSUE TITLE
[Request] Add Image Picker

### ISSUE THREAD

**Issue by hajekj** [cdnjs/cdnjs#6475]
**Library name:** Image Picker
**Git repository url:** https://github.com/rvera/image-picker
**npm package url(optional):** 
**License(s):** MIT / https://github.com/rvera/image-picker/blob/master/LICENSE
**Official homepage:** http://rvera.github.io/image-picker/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @hajekj [image-picker](https://cdnjs.com/libraries/image-picker) is already on cdnjs, enjoy it. :smile:
