### ISSUE TITLE
[Request] Add cytoscape-panzoom

### ISSUE THREAD

**Issue by ajmazurie** [cdnjs/cdnjs#6478]
**Library name:** cytoscape-panzoom
**Git repository url:** https://github.com/cytoscape/cytoscape.js-panzoom
**npm package url(optional):**
**License(s):** ?
**Official homepage:** https://github.com/cytoscape/cytoscape.js-panzoom
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@ajmazurie  sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
We can add this as it's an extention of the popular cytoscape.js

**Comment by maruilian11** [comment]
ok
