### ISSUE TITLE
[Request] Add Material Design Data Table

### ISSUE THREAD

**Issue by guanjinke** [cdnjs/cdnjs#6479]
**Library name: Material Design Data Table
**Git repository url: https://github.com/daniel-nagy/md-data-table
**npm package url(optional):** 
**License(s): MIT License
**Official homepage: https://github.com/daniel-nagy/md-data-table
**Wanna say something? Leave message here: I want the latest version 0.8.14.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@guanjinke,
The library had already been included in cdnjs.
https://cdnjs.com/libraries/angular-material-data-table
just enjoy! :smiley:
