### ISSUE TITLE
[Request] angular-slick-carousel

### ISSUE THREAD

**Issue by aszmyd** [cdnjs/cdnjs#6482]
**Library name:angular-slick-carousel** 
**Git repository url: https://github.com/devmark/angular-slick-carousel**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
@aszmyd 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by PeterDaveHello** [comment]
This lib looks okay to be added. So let's add it.

**Comment by Amomo** [comment]
ok~
