### ISSUE TITLE
[Request] Add sweet-scroll 

### ISSUE THREAD

**Issue by tsuyoshiwada** [cdnjs/cdnjs#6483]
**Library name: sweet-scroll** 
**Git repository url: https://github.com/tsuyoshiwada/sweet-scroll**
**npm package url(optional): https://www.npmjs.com/package/sweet-scroll** 
**License(s): MIT License**
**Official homepage: http://tsuyoshiwada.github.io/sweet-scroll/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @tsuyoshiwada 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by tsuyoshiwada** [comment]
Hi @Amomo
I was careless for not properly read a README.
If there is an opportunity also try to open an issue.

I'm rooting for you guys of activities. :-D

**Comment by Amomo** [comment]
close due to not enough popularity

**Comment by PeterDaveHello** [comment]
Hi @tsuyoshiwada I wonder if you would like to send a PR by yourself?
