### ISSUE TITLE
[Request] Add _short description to the existing libraries 

### ISSUE THREAD

**Issue by syntaxwork** [cdnjs/cdnjs#6485]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here: do you think it would be great to put a short description of what is the library is about, what is the main features, etc... It way easier for people to understand what each library is for beside include it into their testing workspace just to find out what it really is. Let me know if make sense**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail?

**Comment by Piicksarn** [comment]
@syntaxwork,
**`This issue will be closed if there isn't any response in next 7 day.`**
