### ISSUE TITLE
[Request] Add angular-rateit

### ISSUE THREAD

**Issue by dzbanek** [cdnjs/cdnjs#6488]
Library name: angular-rateit
Git repository url: https://github.com/akempes/angular-rateit
Official homepage: https://github.com/akempes/angular-rateit

**Comment by maruilian11** [comment]
Hi @dzbanek 
This library doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

This issue will be closed if there is no any response in next 7 day

**Comment by dzbanek** [comment]
I see, thank you for your time.
