### ISSUE TITLE
[Request] Add query-command-supported

### ISSUE THREAD

**Issue by CITguy** [cdnjs/cdnjs#6489]
**Library name:** query-command-supported
**Git repository url:** https://github.com/zenorocha/document.queryCommandSupported
**npm package url(optional):** query-command-supported
**License(s):** MIT
**Official homepage:**https://github.com/zenorocha/document.queryCommandSupported
**Wanna say something? Leave message here:** *n/a*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @CITguy 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by Amomo** [comment]
This issue will be closed if there is no any response in next 7 day.
