### ISSUE TITLE
extjs 6

### ISSUE THREAD

**Issue by colazo** [cdnjs/cdnjs#6492]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/extjs/6.0.0
