### ISSUE TITLE
webfont.js

### ISSUE THREAD

**Issue by DeveloperZone1** [cdnjs/cdnjs#6494]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hey what is this for?

**Comment by Piicksarn** [comment]
@DeveloperZone1,  :smiley: 
**`This issue will be closed if there is no any response in next 7 day.`**

Thanks
Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
