### ISSUE TITLE
[Request] Add egjs

### ISSUE THREAD

**Issue by sculove** [cdnjs/cdnjs#6495]
**Library name:** egjs
**Git repository url:** https://github.com/egjs/egjs
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://egjs.github.io/main/

**Comment by LeaYeh** [comment]
hi @sculove ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

**Comment by sculove** [comment]
We got a 100 stars.
Please, register egjs at cdnjs

**Comment by PeterDaveHello** [comment]
Hi @sculove, what are the files need to be hosted on our cdn? All the files under dist folder? Thanks.

**Comment by sculove** [comment]
@PeterDaveHello Yes, we need all the files under dist folder. Thank you

**Comment by PeterDaveHello** [comment]
@sculove Ok, thanks.
