### ISSUE TITLE
[Request] Add hammerjs-compatible

### ISSUE THREAD

**Issue by sculove** [cdnjs/cdnjs#6496]
**Library name:**  hammerjs-compatible
**Git repository url:** https://github.com/egjs/hammerjs-compatible
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/egjs/hammerjs-compatible

**Comment by Amomo** [comment]
Hi @sculove 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by Amomo** [comment]
This issue will be closed if there is no any response in next 7 day.

**Comment by sculove** [comment]
ok. I got it Thank you
