### ISSUE TITLE
[Request] Add Lightning Design System 

### ISSUE THREAD

**Issue by stenebenau** [cdnjs/cdnjs#6507]
Lightning Design System
https://github.com/salesforce-ux/design-system

Source code is licensed under BSD License Clause 2
All icons and images are licensed under Creative Commons Attribution-NoDerivatives 4.0
The font is licensed under our font license

https://www.lightningdesignsystem.com/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@stenebenau sorry for the late reply, do you know what are the files should be hosted on our CDN? Thanks.

**Comment by maruilian11** [comment]
we are trying to add this lib in https://github.com/cdnjs/cdnjs/issues/6573
thank you!
