### ISSUE TITLE
[Request] Flexslider2.js

### ISSUE THREAD

**Issue by vertisan** [cdnjs/cdnjs#6514]
**Library name: Flexslider2** 
**Git repository url: https://github.com/woothemes/FlexSlider**
**npm package url(optional):** 
**License(s): GPLv2**
**Official homepage: https://www.woothemes.com/flexslider/**
**Wanna say something? Leave message here:**

**Comment by LeaYeh** [comment]
@vertisan  sorry for my late reply, 
this library is already in [cdnjs](https://cdnjs.com/libraries/flexslider), if this lib is not witch you want just tell me. 
I will handle your asking as soon as possible :)
