### ISSUE TITLE
[Request] Add ng-scrollbars

### ISSUE THREAD

**Issue by AmitMY** [cdnjs/cdnjs#6522]
**Library name:**  ng-scrollbars
**Git repository url:** https://github.com/iominh/ng-scrollbars
**License(s):** MIT
**Official homepage:** http://iominh.github.io/ng-scrollbars/

**Comment by PeterDaveHello** [comment]
We need a higher popularity to host this lib.

**Comment by Amomo** [comment]
Hi @AmitMY 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

This issue will be closed if there is no any response in next 7 day.
