### ISSUE TITLE
[Request] Add mithril router 

### ISSUE THREAD

**Issue by altunyurt** [cdnjs/cdnjs#6525]
mithril-router
https://github.com/Nijikokun/mithril-router/
https://www.npmjs.com/package/mithril-router
MIT

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @altunyurt 
This library doesn't have enough popularity(100 watch or star is a good example).
Currently, we won't add it.
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by Amomo** [comment]
This issue will be closed if there is no any response in next 7 day.
