### ISSUE TITLE
[Request] Add simplePagination.js

### ISSUE THREAD

**Issue by LAKnoKAL** [cdnjs/cdnjs#6527]
**Library name:** simplePagination.js
**Git repository url:** https://github.com/flaviusmatis/simplePagination.js
**License(s):** http://flaviusmatis.github.com/license.html
**Official homepage:** http://flaviusmatis.github.com/simplePagination.js/

**Comment by Amomo** [comment]
Wait for the author add tags.
https://github.com/flaviusmatis/simplePagination.js/issues/120

**Comment by PeterDaveHello** [comment]
Should add a label for it.

**Comment by maruilian11** [comment]
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
@maruilian11 Tag me for what?

**Comment by maruilian11** [comment]
@PeterDaveHello the author seems recently not act on github. maybe we can consider closing this issue until the author reply.

**Comment by PeterDaveHello** [comment]
There is a v0.0.3 commit bumped its version, https://github.com/flaviusmatis/simplePagination.js/commit/71468116faf8106d653649ed2582ce6d49bb8013.

We can take it as the snapshot of v0.0.3 and manually add it.
