### ISSUE TITLE
[Request] Add jsviews

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6530]
**Library name:** jsviews
**Git repository url:** https://github.com/BorisMoore/jsviews

**Comment by BorisMoore** [comment]
Thanks for this.

FYI - JsViews is now published to npm: https://www.npmjs.com/package/jsviews - so I assume autoupdate using npm to deploy to cdnjs is an option...

**Comment by PeterDaveHello** [comment]
Nice :+1:

**Comment by BorisMoore** [comment]
BTW, JsViews builds on top of JsRender, and JsObservable, so the package includes the corresponding files: jsrender.js, jquery.observable.js and jquery.views.js. But usually it is more convenient to have a single composite file - which is the one called jsviews.js. 

That is why there are several different 'flavors' of js file in the jsviews package. See http://www.jsviews.com/#download.

**Comment by BorisMoore** [comment]
Let me know when you have an update on this. Looking forward to having JsViews available on cdnjs. When it is ready I will document it in the readme...

**Comment by PeterDaveHello** [comment]
@BorisMoore maybe you can send a PR to add it, or you want me to do it?

**Comment by BorisMoore** [comment]
To be honest, it would be really helpful if you could do it! I am very short on time - working hard on updating and completing the documentation for JsViews and JsRender at www.jsviews.com. 

But let me know if that is a problem, and I will have to try to find the time to do the PR. It will probably have to wait until after I have completed some high pri docs, though...

Either way, thanks for your help, and for cdnjs!

**Comment by PeterDaveHello** [comment]
@BorisMoore Ok so i will take this

**Comment by BorisMoore** [comment]
That's really great. Thanks very much!

**Comment by PeterDaveHello** [comment]
@BorisMoore No problem

**Comment by BorisMoore** [comment]
Excellent. Thanks again!

**Comment by PeterDaveHello** [comment]
@BorisMoore You are welcome.
