### ISSUE TITLE
[Request] Aragonite JS [author] Leo Javier

### ISSUE THREAD

**Issue by leojavier** [cdnjs/cdnjs#6533]
**Library name:**  Aragonite JS
**Git repository url:** https://github.com/leojavier/aragonite-validator
**npm package url(optional):** https://github.com/leojavier/aragonite-validator/blob/master/package.json
**License(s):** MIT
**Official homepage:** http://getaragonite.com

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We need a higher popularity to add this lib, as you are the author of this lib, I wonder if you can just send a PR with npm auto-update for this lib, I'll be happy to merge it if that PR can fit our conventions.

**Comment by leojavier** [comment]
sure, I will, Thank you Peter

**Comment by leojavier** [comment]
Hey Peter, what do you mean with the npm auto-update, can you be more specific please?

Thanks,

**Comment by PeterDaveHello** [comment]
@leojavier Oh I mean the autoupdate in readme.

**Comment by leojavier** [comment]
oh, it has it... is the third shield in the readme...

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
Ping @maruilian11, any updates?

**Comment by maruilian11** [comment]
@PeterDaveHello i thought this lib need higher popularity, so do i need to send a PR for it, or just ping the author and wait for seven days?
ps. i made a commit for it, but i have opened a PR.

**Comment by PeterDaveHello** [comment]
Looks okay with its npm stats, let's add this.
