### ISSUE TITLE
[Request] Add CKEDITOR base64image

### ISSUE THREAD

**Issue by ElimarGontijo** [cdnjs/cdnjs#6538]
**Library name: CKEDITOR base64image
**Git repository url:https://github.com/nmmf/base64image
**npm package url(optional):** 
**License(s):GPL
**Official homepage: none
**Wanna say something? Leave message here:This is a plugin for CKEDITOR to put images in base64 format.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@ElimarGontijo ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your suggestion. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response!
