### ISSUE TITLE
[Request] Add multiselect.js

### ISSUE THREAD

**Issue by montogeek** [cdnjs/cdnjs#6540]
**Library name:** multiselect.js
**Git repository url:** https://github.com/lou/multi-select
**License(s):** MIT
**Official homepage:** http://loudev.com/
**Wanna say something? Leave message here:** Thanks for this service!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Added in f9242bd
