### ISSUE TITLE
BUG: handled idle incorrect

### ISSUE THREAD

**Issue by sea-kg** [cdnjs/cdnjs#6554]
If switch between tabs, any time I get "idle"
if the time has not come: I expected get "focus" not "idle"

Example of code:
ifvisible.setIdleDuration(600); // 10 min == 600 sec
ifvisible.idle(function(){
  	console.log("ifvisible.idle handled");	
});

**Comment by PeterDaveHello** [comment]
Is this cdnjs issue? I didn't get it.

**Comment by sea-kg** [comment]
I come here from https://cdnjs.com/libraries/ifvisible
it's problem for ifvisible library.
I reported to another repository https://github.com/serkanyersen/ifvisible.js
Sorry.

**Comment by PeterDaveHello** [comment]
no problem
