### ISSUE TITLE
[Request] Add bootstrap-star-rating

### ISSUE THREAD

**Issue by vanduynslagerp** [cdnjs/cdnjs#6558]
**Library name:** bootstrap-star-rating
**Git repository url:** https://github.com/kartik-v/bootstrap-star-rating
**npm package url(optional):** N/A
**License(s):** BSD 3-Clause License
**Official homepage:** http://plugins.krajee.com/star-rating

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
lib has been added
https://cdnjs.com/libraries/bootstrap-star-rating
