### ISSUE TITLE
[Request] Add ajv (json-schema validator) [author]

### ISSUE THREAD

**Issue by epoberezkin** [cdnjs/cdnjs#6569]
Library name: Ajv 
Git repository url: https://github.com/epoberezkin/ajv
npm package url: https://www.npmjs.com/package/ajv
License: MIT
Official homepage: https://github.com/epoberezkin/ajv

I can make the PR
Thanks!

**Comment by PeterDaveHello** [comment]
Okay I'll wait for your PR!
