### ISSUE TITLE
[Request] Salesforce Lightning Design System

### ISSUE THREAD

**Issue by shankar-ray** [cdnjs/cdnjs#6573]
**Salesforce Lightning Design System:** 
**https://github.com/salesforce-ux/design-system:**
**npm package url(optional):** 
**BSD License Clause 2:**
**https://www.lightningdesignsystem.com:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@shankar-ray sorry for the late reply, do you know what are the files should be hosted on our CDN? Thanks.

**Comment by shankar-ray** [comment]
@PeterDaveHello Please find the link below for the assets.
https://www.lightningdesignsystem.com/downloads/

**Comment by PeterDaveHello** [comment]
hmmmm ... seems there is no pre-built files in the git repo, it'll be harder to apple auto-update config.

**Comment by maruilian11** [comment]
@PeterDaveHello there are pre-built files on npm package, do we support `@salesforce-ux/design-system` in npmName of auto-update config?

**Comment by PeterDaveHello** [comment]
Nope we do not, but you can work on it.

**Comment by PeterDaveHello** [comment]
Supported since: 759df7d245a6e37db7ef9227c523484853bc6b18

**Comment by kaelig** [comment]
@maruilian11 hi! Can you please remove my name from future commits? Thank you 🤗

**Comment by PeterDaveHello** [comment]
@kaelig sorry about that.
