### ISSUE TITLE
[Request] Add gown.js

### ISSUE THREAD

**Issue by SphinxC0re** [cdnjs/cdnjs#6574]
**Library name: gown.js** 
**Git repository url: https://github.com/brean/gown.js**
**License(s): Apache License 2.0**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@SphinxC0re ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your suggestion. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by SphinxC0re** [comment]
That seems reasonable to me

**Comment by PeterDaveHello** [comment]
Okay so close this, thanks.
