### ISSUE TITLE
[Request] jquery fast reader 

### ISSUE THREAD

**Issue by frikinside** [cdnjs/cdnjs#6577]
**Library name:jquery.fast-reader** 
**Git repository url:https://github.com/frikinside/jquery.fast-reader**
**npm package url(optional):npm install fast-reader** 
**License(s):MIT**
**Official homepage:http://frikinside.github.io/jquery.fast-reader/**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@frikinside sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by frikinside** [comment]
I overlook the popularity requisite while reading the readme! My bad!
I would follow your suggestion and if this repo ever gain enought popularity (I doubt it) I will post the request again.

Everything ready for closing the issue, thanks for the time to check this!

**Comment by PeterDaveHello** [comment]
Thanks.
