### ISSUE TITLE
[Request] Add react-container-query 

### ISSUE THREAD

**Issue by d6u** [cdnjs/cdnjs#6578]
**Library name:** react-container-query
**Git repository url:** https://github.com/d6u/react-container-query
**npm package url(optional):** https://www.npmjs.com/package/react-container-query
**License(s):** MIT
**Official homepage:** https://github.com/d6u/react-container-query
**Wanna say something? Leave message here:**
The bundled UMD build should be found in npm module `/node_modules/react-container-query/dist` directory.
I tried to create a PR, but due to https://github.com/cdnjs/cdnjs/issues/3941, it was so slow on my local. So I fallback to submit a issue.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Okay, but we a higher popularity to add this PR.

**Comment by maruilian11** [comment]
this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

thank you for your contribution!

**Comment by d6u** [comment]
Thanks for your reponse. I will seek to add this lib when appropriate.
