### ISSUE TITLE
[Request] Add Milligram 

### ISSUE THREAD

**Issue by cjpatoilo** [cdnjs/cdnjs#6579]
**Library name:** Milligram
**Git repository url:** https://github.com/milligram/milligram
**npm package url(optional):** https://www.npmjs.com/package/milligram 
**License(s):** Code under [MIT License](https://github.com/milligram/milligram#license).
**Official homepage:** http://milligram.github.io
**Wanna say something? Leave message here:** Milligram provides a minimal setup of styles for a fast and clean starting point. Just it! Only 2kb gzipped! It's not about a UI framework. Specially designed for better performance and higher productivity with fewer properties to reset resulting in cleaner code. Hope you enjoy!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@cjpatoilo,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by cjpatoilo** [comment]
@Piicksarn 
https://github.com/milligram/milligram/stargazers

**Comment by PeterDaveHello** [comment]
:+1:
