### ISSUE TITLE
[Request] Add Angular-easyModal-alert-confirm

### ISSUE THREAD

**Issue by regisluo** [cdnjs/cdnjs#6580]
**Library name:** Angular-easyModal 
**Git repository url:** https://github.com/regisluo/AngularJS-EasyModal-alert-confirm
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:** https://github.com/regisluo/AngularJS-EasyModal-alert-confirm
**Wanna say something? Leave message here:** An alternative of JS alert and confirm dialog with enhanced functionality(html template,css,callback,external controller), more flexible, better user experience.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@regisluo ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by regisluo** [comment]
Hi Piicksarn,
Thanks for your reply and I will reopen it when it has enough popularity :)

**Comment by PeterDaveHello** [comment]
Okay so close this, thanks.
