### ISSUE TITLE
[Request] Add angular-number-picker

### ISSUE THREAD

**Issue by andmau90** [cdnjs/cdnjs#6583]
**Library name: angular-number-picker** 
**Git repository url: https://github.com/leftstick/angular-number-picker.git**
**npm package url(optional): angular-number-picker** 
**License(s):MIT**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@andmau90 ,
This library doesn't have notable popularity either.
Would you mind to open an issue again when the library has more popularity?
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response.
