### ISSUE TITLE
[Request] Add HTML

### ISSUE THREAD

**Issue by thedunster** [cdnjs/cdnjs#6587]
**Library name:** HTML
**Git repository url:** https://github.com/nbubna/HTML
**npm package url(optional):** 
**License(s):** MIT (https://github.com/nbubna/HTML/blob/master/LICENSE-MIT)
**Official homepage:** http://nbubna.github.io/HTML/
**Wanna say something? Leave message here:** Thanks!

**Comment by PeterDaveHello** [comment]
@maruilian11 please add this lib ASAP, thanks.
