### ISSUE TITLE
Add utils in https://cdnjs.com/libraries/intl-tel-input

### ISSUE THREAD

**Issue by damiarita** [cdnjs/cdnjs#6589]
Hi,

I am collaborating to create a wordpress plugin for Intl-tel-input jquery plugin.

I found your CDN and loved it. I just found it is missing one important file for it to properly work. It's utils.js https://github.com/jackocnr/intl-tel-input/blob/master/lib/libphonenumber/build/utils.js

It would be great if you could serve it together with the rest of the files of this great library!

Thanks

**Comment by PeterDaveHello** [comment]
@damiarita Thanks for report, I will take a look at it.

**Comment by PeterDaveHello** [comment]
hmmmm ... there is a problem, current auto-update use `/build` as basePath, and git auto-update didn't support multiple filemap yet, give me more time to fix this.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
@damiarita I added them manually now, would you please try it? If now works, feel free to ping me, thanks.

**Comment by damiarita** [comment]
Let me tell the plugin's author. Maybe he could rearrange it.

Thanks

hmmmm ... there is a problem, current auto-update use /build as basePath,
and git auto-update didn't support multiple filemap yet, give me more time
to fix this.

—
Reply to this email directly or view it on GitHub
<https://github.com/cdnjs/cdnjs/issues/6589#issuecomment-167493147>.

**Comment by PeterDaveHello** [comment]
Okay, sure, thanks a lot :+1:

**Comment by PeterDaveHello** [comment]
@damiarita BTW now you can access it via: https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/7.0.1/lib/libphonenumber/build/utils.js

**Comment by damiarita** [comment]
Hi @PeterDaveHello The file looks very good.

I was just wondering whether it could be made visible in https://cdnjs.com/libraries/intl-tel-input and whether the new file is going to be there when a new version comes up. I am not quite sure what "adding manualy" actually implies

Thanks a lot for your help! You were very helpful and QUICK!

**Comment by PeterDaveHello** [comment]
@damiarita We hope every updates can be automatically added, because the filemap issue, I need to add them by myself, that's manually mean. 
I will clean up the cache on the website so it'll be visible soon.

**Comment by damiarita** [comment]
Thanks!
ᐧ

Damià Rita Espada

uniquecorners.com
(0034)652454694

**Comment by PeterDaveHello** [comment]
Hi @damiarita 

> Let me tell the plugin's author. Maybe he could rearrange it.

Is there any updates? Version 7.0.2  just been released.

**Comment by damiarita** [comment]
Hi Peter,

I just saw there are so many folders in the cdn. There is /img/, /css/,
/js/ and /build/. I wonder what folder do you prefere it to be in.

Thanks
ᐧ

Damià Rita Espada

uniquecorners.com
(0034)652454694

**Comment by PeterDaveHello** [comment]
Hi @damiarita,

https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/intl-tel-input/package.json#L23-L32
```js
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/jackocnr/intl-tel-input.git",
    "basePath": "build/",
    "files": [
      "js/intlTelInput*.js",
      "img/flags*.png",
      "css/intlTelInput.css"
    ]
  },
```

Currently we use `build` folder, so files under `build` will be good, thanks!

**Comment by jackocnr** [comment]
Hi guys, I'm the plugin author. Couldn't you just set the basePath to the root dir "./", and then specify the files array as "build/js/intlTelInput*.js" etc and then also "lib/libphonenumber/build/utils.js"?

**Comment by PeterDaveHello** [comment]
Hi @jackocnr, sorry for my late reply, we hope not to change the url/directory schema, so that user can easily upgrade the libs by changing the version number in the url.

**Comment by damiarita** [comment]
Hi @jackocnr,

Is it possible to move the file to the folder they need?

**Comment by jackocnr** [comment]
Ok I have moved it and pushed to master. It will be in the next release.

**Comment by PeterDaveHello** [comment]
Thank you both.

**Comment by jackocnr** [comment]
I have now released this change in v8.0.0. Will this update this page automatically? https://cdnjs.com/libraries/intl-tel-input

**Comment by PeterDaveHello** [comment]
@jackocnr Thanks,  I will take a look at it.

**Comment by PeterDaveHello** [comment]
@damiarita @jackocnr :
* a10f4e1 add intl-tel-input v8.0.0/8.0.1
* 06c9a55 update auto-update config of intl-tel-input
