### ISSUE TITLE
[Request] Add EasyAnim

### ISSUE THREAD

**Issue by fgRuslan** [cdnjs/cdnjs#6592]
**Library name:** EasyAnim
**Git repository url:** https://github.com/fgRuslan/easyAnim
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://fgruslan.github.io/easyAnim/
**Wanna say something? Leave message here:** Thanks

**Comment by Piicksarn** [comment]
@fgRuslan ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by Piicksarn** [comment]
Closed due to no response!
