### ISSUE TITLE
Morris v0.5.1 has wrong archive

### ISSUE THREAD

**Issue by efreibe** [cdnjs/cdnjs#6598]
It's pointing to version 0.5.0

**Comment by PeterDaveHello** [comment]
It's totally the same as upstream: https://github.com/morrisjs/morris.js/tree/0.5.1

**Comment by efreibe** [comment]
The code here: https://github.com/morrisjs/morris.js has the right version.
Above link points to the 0.5.0 version.

**Comment by PeterDaveHello** [comment]
the link you gave point to master branch, the link I gave poing to v0.5.1 tag, so that's not our problem, you should ping its author.

**Comment by PeterDaveHello** [comment]
Hello @oesmith, can you give your view or some other comments on this? Many thanks.

**Comment by maruilian11** [comment]
@PeterDaveHello what can we do for this issue?

**Comment by PeterDaveHello** [comment]
Nothing but report to upstream, that's not our problem.
