### ISSUE TITLE
[Request] Add Scalem

### ISSUE THREAD

**Issue by thdoan** [cdnjs/cdnjs#6603]
**Library name:** Scalem
**Git repository url:** https://github.com/thdoan/scalem
**npm package url(optional):** https://www.npmjs.com/package/scalem
**License(s):** https://github.com/thdoan/scalem/blob/master/LICENSE
**Official homepage:** http://thdoan.github.io/scalem/
**Wanna say something? Leave message here:**
Thanks for maintaining a great service! :+1: 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@thdoan,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by thdoan** [comment]
@Piicksarn Thanks for the heads up. This is chicken-or-the-egg problem: I was hoping by having the library available on CDNJS that would increase its popularity :)

**Comment by PeterDaveHello** [comment]
Yeah this is chicken-or-the-egg problem, so we setup a threshole, especially we don't have enough time to add all the libs.

**Comment by thdoan** [comment]
That's fine. Thank you for offering a great service.

**Comment by PeterDaveHello** [comment]
@thdoan can submit it again once you got 100 starts on GitHub, thank you for understanding.
