### ISSUE TITLE
[Request] Add Magnify

### ISSUE THREAD

**Issue by thdoan** [cdnjs/cdnjs#6604]
**Library name:** Magnify
**Git repository url:** https://github.com/thdoan/magnify
**npm package url(optional):** https://www.npmjs.com/package/magnify
**License(s):** https://github.com/thdoan/magnify/blob/master/LICENSE
**Official homepage:** http://thdoan.github.io/magnify/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@thdoan  sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by thdoan** [comment]
@maruilian11 I'm back with [another request to add](https://github.com/cdnjs/cdnjs/issues/11394) -- I hope you can reconsider since my lib has over 100 stars now ^_^.

**Comment by PeterDaveHello** [comment]
@thdoan we'll take a look soon, thanks.

**Comment by maruilian11** [comment]
@thdoan Great! Let's reopen this issue. Would you like to help send a PR to add your lib since we've got lots of works to do. Of course, if you don't have the time, I will help send the PR in few days.
