### ISSUE TITLE
irrelevant files

### ISSUE THREAD

**Issue by jossef** [cdnjs/cdnjs#6607]
https://cdnjs.com/libraries/material-design-icons

**Comment by PeterDaveHello** [comment]
You mean which one?

**Comment by jossef** [comment]
imho all of these png files are irrelevant

![image](https://cloud.githubusercontent.com/assets/1287098/12114233/dc65a5d6-b3b0-11e5-809c-96555c4d8d86.png)

**Comment by PeterDaveHello** [comment]
Those png imgaes are its files.

**Comment by PeterDaveHello** [comment]
Close due to no response.
