### ISSUE TITLE
[Request] Update prism

### ISSUE THREAD

**Issue by davidsarkany** [cdnjs/cdnjs#6612]
**Library name:** prism
**CNDJS url:** https://cdnjs.com/libraries/prism
**Git repository url:** https://github.com/PrismJS/prism
**Official homepage:** http://prismjs.com/
**Wanna say something? Leave message here:**

Please update latest version.
**Latest version:** 1.3.0
**Available version:** 0.0.1

**Comment by PeterDaveHello** [comment]
@davidsarkany @maruilian11 please take a look.
