### ISSUE TITLE
googbase_min.js

### ISSUE THREAD

**Issue by jackyhowe** [cdnjs/cdnjs#6619]
+function(){(window.goog=window.goog||{}).inherits=function(a,d){function b(){}b.prototype=d.prototype;a.b=d.prototype;a.prototype=new b;a.prototype.constructor=a;a.a=function(a,b,f){for(var e=Array(arguments.length-2),c=2;c<arguments.length;c++)e[c-2]=arguments[c];return d.prototype[b].apply(a,e)}};}()

**Comment by PeterDaveHello** [comment]
What's this for?

**Comment by Piicksarn** [comment]
@jackyhowe,
**`This issue will be closed if there is no any response in next 7 day.`**
