### ISSUE TITLE
[Request] Add Scrollspeed

### ISSUE THREAD

**Issue by afdallah** [cdnjs/cdnjs#6621]
**Library name: Scrollspeed** 
**Git repository url: https://github.com/nathco/jQuery.scrollSpeed**
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://code.nath.co/scrollSpeed
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Could you add git tag?
Thanks.

**Comment by PeterDaveHello** [comment]
@kennynaoh are you talking to issuer? I don't think he has the permission to do what do you want.

**Comment by kennynaoh** [comment]
@PeterDaveHello , right.

**Comment by kennynaoh** [comment]
Hello @nathco ,
We want to host [this library](https://github.com/nathco/jQuery.scrollSpeed) on [cndjs](https://github.com/cdnjs/cdnjs).
Please help us add git tag.
It's helpful for user to know the version and status.
Thanks very much!

**Comment by PeterDaveHello** [comment]
Maybe you can send an email to ask the author.

**Comment by kennynaoh** [comment]
Okay!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because it has no git tag and no response for a long time, but it has release notes https://github.com/nathco/jQuery.scrollSpeed#release-notes.
Could I add it by tracing commit log without git tag?
Thanks!

**Comment by PeterDaveHello** [comment]
Good idea @kennynaoh

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to add [this ](https://github.com/smb043/jQuery.scrollSpeed)forked version. What do U think?
