### ISSUE TITLE
[Request] Add MiIligram | A minimalist CSS framework

### ISSUE THREAD

**Issue by thompsonemerson** [cdnjs/cdnjs#6622]
**Library name: Milligram** 
**Git repository url: https://github.com/milligram/milligram**
**npm package url(optional): npm install milligram** 
**License(s): MIT License @ CJ Patoilo**
**Official homepage: http://milligram.github.io**
**Wanna say something? Leave message here: This is a new minimalist CSS framework developed with flexbox**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #6579
