### ISSUE TITLE
[Request] webrtc4all

### ISSUE THREAD

**Issue by iqbalalo** [cdnjs/cdnjs#6625]
Library name: webrtc4all
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
any detail?

**Comment by PeterDaveHello** [comment]
Close due to no response.
