### ISSUE TITLE
[Request] Add rocket.js

### ISSUE THREAD

**Issue by procek69** [cdnjs/cdnjs#6634]
**Library name:** rocket.js
**Git repository url:** https://github.com/ka-boom-game-studio/rocket.js/tree/master
**npm package url(optional):** 
**License(s):** MIT 
**Official homepage:** http://ka-boom-game-studio.github.io/rocket.js/
**Wanna say something? Leave message here:** min version in https://github.com/ka-boom-game-studio/rocket.js/blob/master/dist/rocket.min.js

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @procek69 

This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

This issue will be closed if there is no any response in next 7 day.
