### ISSUE TITLE
[Request] Add nice-validator

### ISSUE THREAD

**Issue by niceue** [cdnjs/cdnjs#6636]
**Library name:** 
nice-validator
**Git repository url:** 
https://github.com/niceue/nice-validator
**npm package url(optional):** 
https://www.npmjs.com/package/nice-validator
**License(s):** 
[MIT](http://niceue.com/licenses/MIT-LICENSE.txt)
**Official homepage:** 
http://validator.niceue.com/
**Wanna say something? Leave message here:**
Simple, smart and pleasant validation solution.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@niceue would you like to send a PR to add it?

**Comment by niceue** [comment]
@PeterDaveHello 
I was planning to add dist directory, so give me some time... :smile:

**Comment by PeterDaveHello** [comment]
Okay, that's nice.

**Comment by niceue** [comment]
@PeterDaveHello 
It's so hard so hard so hard for me to pull a big data, even had used "sparseCheckout". It was always break off. :cry::sob:
 I don't think it is a good idea to store all packages in libs.  :disappointed: 
Why not just store a package.json? aha.

**Comment by PeterDaveHello** [comment]
@niceue we need to change the structure but didn't have enough time and human resource on it yet, if you want we add it for you without your pr, that's fine, just need you to wait a little bit more, thanks!

**Comment by niceue** [comment]
that would be fine, many thanks! :+1:

**Comment by PeterDaveHello** [comment]
We will add it ASAP, maybe this weekend, thanks for waiting.
