### ISSUE TITLE
[Request] Add alertify-bootstrap-3 

### ISSUE THREAD

**Issue by CamiloBernal** [cdnjs/cdnjs#6638]
**Library name:**
alertify-bootstrap-3
**Git repository url:**
https://github.com/dbtek/alertify-bootstrap-3
**License(s):**
https://opensource.org/licenses/MIT
**Official homepage:**
http://dbtek.github.io/alertify-bootstrap-3/
**Wanna say something? Leave message here:**
Alertify Bootstrap 3 Theme

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@CamiloBernal sorry, but this lib doesn't have enough popularity(at least 100 watch or star). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.
