### ISSUE TITLE
[Request] microbejs

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [cdnjs/cdnjs#6640]
microbejs
https://github.com/sociomantic/microbe
https://www.npmjs.com/package/microbejs
License: MIT
http://m.icro.be
-----------
i added autoupdate to the package.json, but it's not added yet, so i figured i'd do it this way

**Comment by jason-braun-sociomantic-mouse** [comment]
bump

**Comment by PeterDaveHello** [comment]
Sorry for the delay, give us two more days.
@maruilian11 popularity of this lib looks fine by its npm stats, so please add this ASAP.

**Comment by jason-braun-sociomantic-mouse** [comment]
cool.  no hurry/worries.  just no updates here ^^

**Comment by PeterDaveHello** [comment]
@jason-braun-sociomantic-mouse Thanks for reminding.
