### ISSUE TITLE
[Request] Add DataTables Plugins

### ISSUE THREAD

**Issue by Dennis14e** [cdnjs/cdnjs#6646]
**Library name:** DataTables Plugins
**Git repository url:** https://github.com/DataTables/Plugins
**License(s):** See [License.txt](https://github.com/DataTables/Plugins/blob/master/License.txt)
**Official homepage:** https://datatables.net/plug-ins/index
Already requested in #5234.

**Comment by PeterDaveHello** [comment]
@DataTables would you be interested in helping us add this? Thanks.

**Comment by DataTables** [comment]
Sure - what is required from me?

**Comment by PeterDaveHello** [comment]
@DataTables I wonder if you would like to send a PR, cause I'm not sure what files should be included in.

**Comment by DataTables** [comment]
Sure. It might be a little bit of time before I can do that (serious back log of work to work through first!). I plan to rearrange the files a little in the plug-ins repo, so it might make sense for me to do that before sending the PR.

**Comment by PeterDaveHello** [comment]
@DataTables sounds good, thanks

**Comment by MattIPv4** [comment]
Dupe #5234
