### ISSUE TITLE
Selecting library version seems broken

### ISSUE THREAD

**Issue by epoberezkin** [cdnjs/cdnjs#6648]
When I select any old version of any library the dropdown switches back to the latest version (the page still shows the links for the old version).

That may be a desired behaviour (although a bit strange), but the only way to show the links for the latest version after this is to refresh a page.

**Comment by PeterDaveHello** [comment]
Thanks for report.

**Comment by PeterDaveHello** [comment]
`selected='selected'` should not be encoded here ...
```html
<option value="2.1.1" selected&#x3D;&quot;selected&quot;>2.1.1</option>
```

**Comment by PeterDaveHello** [comment]
too busy to trace ... cc @cdnjs/team-cdnjs @cdnjs/website for help ...
