### ISSUE TITLE
[Request] CDN link to "current version" 

### ISSUE THREAD

**Issue by Krindi** [cdnjs/cdnjs#6649]
It would be useful for me if there was an option to just link to the current version of font-awesome, without specifying a version number, via a link stable link name.  Yes I know that's on me if something changes, but it would be useful for when a brand name changes their icon (I'm looking at you Google+) and I have to go through all of my sites that are direct linking to the CDN to update the reference to 4.5.0.

existing:
https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css

requested:
https://maxcdn.bootstrapcdn.com/font-awesome/current/css/font-awesome.min.css

And then /current/ can just be a symlink (or whatever) to the newest version.

**Comment by PeterDaveHello** [comment]
hmmm ... related issues have been discussed several times ...

**Comment by PeterDaveHello** [comment]
#5674 #4396 cc @cdnjs/team-cdnjs

**Comment by Krindi** [comment]
Thanks for the speedy response.  I suppose I can always just pull down the current version and host it on my company's CDN under a "latest" link.

**Comment by PeterDaveHello** [comment]
Okay, and we will write a markdown doc about this issue in future, see #6650

**Comment by PeterDaveHello** [comment]
Close this one since we have #6650
