### ISSUE TITLE
Write a document about not to support `latest` in url as feature.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6650]
See:
#360 #5674 #4396 #3614 #987 #423 #6120

**Comment by MattCowley** [comment]
https://cdn.unreal-designs.co.uk/cont/cdnjsLatest/

**Comment by PeterDaveHello** [comment]
Oh, that's cool! :+1:

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 @cdnjs/intern everyone who is interested in this issue please just take it!

**Comment by PeterDaveHello** [comment]
b808981c7cf done
