### ISSUE TITLE
prism missing folder in npm package

### ISSUE THREAD

**Issue by maruilian11** [cdnjs/cdnjs#6653]
there is no `command-line` in their npm package but on github, i have opened an issue on their repo, they said maybe next release will add it, so we need to keep waiting the next release, then change the auto-update config or we turn to use git auto-update instead?
https://github.com/PrismJS/prism/issues/850#issuecomment-168493905
btw, jsdelivr uses github version

**Comment by PeterDaveHello** [comment]
Add tag for origin issue please.

#6617

**Comment by PeterDaveHello** [comment]
I have no idea why did you need to create another issue to discuss this. Close this.
