### ISSUE TITLE
[Request] jPut

### ISSUE THREAD

**Issue by pakornth** [cdnjs/cdnjs#6659]
**Library name: jPut** 
**Git repository url: https://github.com/shabeer-ali-m/jPut**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://github.com/shabeer-ali-m/jPut**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @pakornth 

This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

This issue will be closed if there is no any response in next 7 day.
