### ISSUE TITLE
[Request] Add bootstrap-html5sortable

### ISSUE THREAD

**Issue by CamiloBernal** [cdnjs/cdnjs#6660]
**Library name:** 
bootstrap-html5sortable
**Git repository url:**
https://github.com/psfpro/bootstrap-html5sortable.git
**npm package url(optional):** 
**License(s):**
https://opensource.org/licenses/MIT
**Official homepage:**
https://github.com/psfpro/bootstrap-html5sortable
**Wanna say something? Leave message here:**
Bootstrap HTML5 Sortable lightweight jQuery plugin to create sortable lists and grids using native HTML5 drag and drop API. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@CamiloBernal sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by Amomo** [comment]
closed due to no response.
