### ISSUE TITLE
[Request] Add jquery-carousel

### ISSUE THREAD

**Issue by CamiloBernal** [cdnjs/cdnjs#6663]
**Library name:** 
jquery-carousel
**Git repository url:**
https://github.com/ksylvest/jquery-carousel.git
**npm package url(optional):** 
**License(s):**
https://github.com/ksylvest/jquery-carousel/blob/master/LICENSE
**Official homepage:**
https://ksylvest.github.io/jquery-carousel/
**Wanna say something? Leave message here:**
A jQuery plugin for scrolling gallery

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @CamiloBernal 

This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
close due to no response.
