### ISSUE TITLE
[Request] Add Ionic Framework 2

### ISSUE THREAD

**Issue by wcustodio** [cdnjs/cdnjs#6665]
**Library name:** Ionic Framework 2.0
**Git repository url:** https://github.com/driftyco/ionic-code/tree/gh-pages/2.0.0
**npm package url(optional):** https://www.npmjs.com/package/ionic-framework
**License(s):**
**Official homepage:** http://ionicframework.com/docs/v2/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by wcustodio** [comment]
Its's now on beta 2!
https://github.com/driftyco/ionic/tree/2.0

**Comment by maruilian11** [comment]
@PeterDaveHello can we use `**/*.+(js|css|map|ttf|woff)` in auto-update config file map?

**Comment by PeterDaveHello** [comment]
@maruilian11 so what's the auto-update repo and basePath? You ask a strange question.

**Comment by maruilian11** [comment]
@PeterDaveHello hmmm... they use folder to separate versions, how do we handle this case?

**Comment by PeterDaveHello** [comment]
You didn't check its npm package, did you?

**Comment by maruilian11** [comment]
@PeterDaveHello oh! yes, i have checked it's npm package, so i asked
>>>
@PeterDaveHello can we use **/*.+(js|css|map|ttf|woff) in auto-update config file map?

i wanted to use npm package as auto-update source and set `"basePath": "",`.

**Comment by wcustodio** [comment]
it's possible to add this library? how can i help you?

**Comment by PeterDaveHello** [comment]
> @PeterDaveHello oh! yes, i have checked it's npm package, so i asked

So why not take `bundles/` as base path and use `**/*` as the rule to get the files?

> it's possible to add this library? how can i help you?

@wcustodio we are trying to confirm what are the files should be added, feel free to give us your comment, and sorry for the delay.

**Comment by wcustodio** [comment]
thanks @PeterDaveHello... this package is very awaited

**Comment by PeterDaveHello** [comment]
@maruilian11 let's add this ASAP.

**Comment by wcustodio** [comment]
Thanks a lot!

**Comment by PeterDaveHello** [comment]
:+1:
