### ISSUE TITLE
[Request] Add anchor.js

### ISSUE THREAD

**Issue by cbopp-art** [cdnjs/cdnjs#6667]
**Library name: anchor.js** 
**Git repository url: https://github.com/cbopp-art/anchor.git**
**npm package url(optional):** 
**License(s): GPL-2.0+**
**Official homepage: http://cbopp-art.github.io/anchor/**
**Wanna say something? Leave message here: Hi, thanks a lot for a fast include, have open issues asking for this ;)**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@cbopp-art would you like to send a PR to add it?
