### ISSUE TITLE
[Request] Themify-icons

### ISSUE THREAD

**Issue by sanathpathiraja** [cdnjs/cdnjs#6670]
**Library name:Themify-icons** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail?

**Comment by sanathpathiraja** [comment]
cdnjs have font awesome links. That like need themify -icons also.
https://themify.me/themify-icons

**Comment by PeterDaveHello** [comment]
Isn't there repository and license info? If you want this lib be hosted on cdnjs, please provide more detail info.

**Comment by maruilian11** [comment]
@sanathpathiraja sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 day. thank you for your contribution.
