### ISSUE TITLE
[Request] Add react-semantify

### ISSUE THREAD

**Issue by austinfox** [cdnjs/cdnjs#6671]
**Library name: react-semantify** 
**Git repository url: https://github.com/jessy1092/react-semantify**
**npm package url(optional): https://www.npmjs.com/package/react-semantify** 
**License(s): MIT**
**Official homepage: https://github.com/jessy1092/react-semantify**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LeaYeh** [comment]
@austinfox I am sorry for the late reply. I will handle your issue as soon as possible :(
