### ISSUE TITLE
[Request] Add videojs-youtube

### ISSUE THREAD

**Issue by devshark** [cdnjs/cdnjs#6674]
videojs-youtube
https://github.com/eXon/videojs-youtube

The MIT License (MIT)

I would appreciate if you add this to your CDN. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@devshark aha looks coolx thanks, we can add this.

**Comment by devshark** [comment]
Cool! Thank you very much!

**Comment by PeterDaveHello** [comment]
@devshark no problem, enjoy it 😄

**Comment by eXon** [comment]
Thanks for doing the PR, much appreciated :+1:

**Comment by PeterDaveHello** [comment]
I only do commit :smile:

**Comment by eXon** [comment]
Even better nobody needs to review your code! xD

**Comment by PeterDaveHello** [comment]
@eXon oh I review myself :smile:
