### ISSUE TITLE
[Request] Add Avalanche

### ISSUE THREAD

**Issue by grok** [cdnjs/cdnjs#6680]
**Library name:** Avalanche
**Git repository url:** https://github.com/colourgarden/avalanche
**npm package url(optional):** https://www.npmjs.com/package/avalanche-css
**License(s):** https://github.com/colourgarden/avalanche/blob/master/LICENSE.MD
**Official homepage:** http://colourgarden.net/avalanche/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@grok sorry, we only host  js, css, swf and library image files. please take a look at our [CONTRIBUTING-WIP.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md#1-policy-rules-and-guidelines) for details.

**Comment by PeterDaveHello** [comment]
Isn't it a css library?

**Comment by maruilian11** [comment]
@PeterDaveHello but there only is `_avalanche.scss` on its github.

**Comment by PeterDaveHello** [comment]
It just needs compilation, have you asked the author for pre-built file?

**Comment by colourgarden** [comment]
@maruilian11 I've now added a pre-compiled version of Avalanche which features a standard 12-column grid and all the layout variations. This is part of the new 1.1.0 release.

File (21kb) - https://github.com/colourgarden/avalanche/blob/1.1.0/avalanche.min.css

Please let me know if there's anything else you need and I look forward to seeing Avalanche on CDNJS soon!

@grok Thanks for suggesting Avalanche and supporting the project! If you're using it for any of your own projects then please get in touch on Twitter - I'd be very interested to see.

**Comment by PeterDaveHello** [comment]
Thanks @colourgarden, also see that in npm package.

**Comment by PeterDaveHello** [comment]
@colourgarden may I ask the command/parameters you used convert scss to css?

**Comment by colourgarden** [comment]
Hi @PeterDaveHello. The compiled file is a 'kitchen sink' version of Avalanche using a 12-column grid with all the layout options enabled. It is a copy of the compiled version from the gh-pages branch ( [settings file here](https://github.com/colourgarden/avalanche/blob/gh-pages/avalanche-grid.scss)) which powers the [project page](colourgarden.net/avalanche).

If you compile the stock [_avalanche.scss file](https://github.com/colourgarden/avalanche/blob/master/_avalanche.scss) then you're using the sensible default settings so less features enabled and a smaller file size.

**Comment by colourgarden** [comment]
Hi @PeterDaveHello. Anything else you need from me on this?

**Comment by PeterDaveHello** [comment]
@colourgarden Sorry for the late reply, I wonder if you can provide odd versions to be hosted? Or you only want the latest version been hosted? Thanks.

**Comment by colourgarden** [comment]
@PeterDaveHello I can provide different versions if you let me know what you'd like? However, a primary principal behind Avalanche is that the developer has a large degree of control over what finally gets compiled into CSS so there are a million different use cases. I think the [pre-compiled "kitchen sink" file](https://github.com/colourgarden/avalanche/blob/1.1.0/avalanche.min.css) is a good option for someone wishing to only deal with CSS (and not Sass).

**Comment by PeterDaveHello** [comment]
@colourgarden I meant the old versions that there is no pre built css file. Anyway, I've added this lib, let me know if you want to add `v1.0.0` and `v1.0.1`, thanks.

**Comment by colourgarden** [comment]
Perfect, thanks!
