### ISSUE TITLE
[Request] Add BVG.js

### ISSUE THREAD

**Issue by Spaxe** [cdnjs/cdnjs#6681]
**Library name:** BVG.js
**Git repository url:** https://github.com/Spaxe/BVG.js
**npm package url(optional):** https://www.npmjs.com/package/bvg
**License(s):** MIT
**Official homepage:** https://github.com/Spaxe/BVG.js
**Wanna say something? Leave message here:** 
Please let me know if there are any issues in adding this library. :]

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Spaxe** [comment]
Edited to add the NPM url.

**Comment by Piicksarn** [comment]
@Spaxe ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by PeterDaveHello** [comment]
Looks okay with its npm stats, @Spaxe would you like to send a PR by yourself?

**Comment by Spaxe** [comment]
No worries, I'll open the issue again when the library has popularity.

**Comment by PeterDaveHello** [comment]
Thank you.
