### ISSUE TITLE
[Request] Add animatr.js

### ISSUE THREAD

**Issue by struct78** [cdnjs/cdnjs#6689]
Animatr
https://github.com/sprawld/Animatr

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @struct78 

This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
close due to no response.
