### ISSUE TITLE
[Request] Add Plottable

### ISSUE THREAD

**Issue by prashcr** [cdnjs/cdnjs#6693]
**Library name:** Plottable
**Git repository url:** https://github.com/palantir/plottable
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://plottablejs.org/
**Wanna say something? Leave message here:** A light, D3-based charting library

**Comment by PeterDaveHello** [comment]
We have it. https://cdnjs.com/libraries/plottable.js/2.0.0
