### ISSUE TITLE
[Request] Add mangui/video-js-swf

### ISSUE THREAD

**Issue by emyller** [cdnjs/cdnjs#6700]
**Library name:** video-js-swf
**Git repository url:** https://github.com/mangui/video-js-swf
**npm package url(optional):** 
**License(s):** http://www.apache.org/licenses/LICENSE-2.0
**Official homepage:** http://flashls.org/

**Comment by emyller** [comment]
Linkable files are in `/dist`. Thanks!

**Comment by maruilian11** [comment]
@PeterDaveHello files under `dist` are `.swf`, `.swf.old`, `swf.orig`, we seem don't host these kinds of lib, could you give me some advice? thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 Of course we host .swf file, didn't you take a look at current repository?

**Comment by emyller** [comment]
The `.swf` files provided by this project are **not** standalone Flash libs. In fact, they are intended to replace the `video-js.swf` file provided by the video.js project, which is [already hosted in CDNJS][1], in order to provide better support for _HTTP Live Streaming_ on desktops, among other features already described at [their repository][2].


[1]: https://cdnjs.com/libraries/video.js 
[2]: https://github.com/videojs/video-js-swf/blob/master/README.md

**Comment by maruilian11** [comment]
@mangui could you please add tags for each version? because we use git auto update which depends on git tags.
thank you very much!

**Comment by emyller** [comment]
@maruilian11 Actually, there are tags [registered on Github][1].

[1]: https://github.com/videojs/video-js-swf/releases

**Comment by maruilian11** [comment]
@emyller  i thought you want to add `mangui/video-js-swf` originally.
 so we can add `videojs/video-js-swf` instead?

**Comment by emyller** [comment]
@maruilian11 Sorry, I though @mangui's version included the original tags -- since it's a fork. Now I just don't remember why I picked that instead of the original repo. But anyway, @videojs's version seems to be actively maintained. I think we can switch to it, yes. Thank you.

**Comment by gkatsev** [comment]
The only reason why you would want to use mangui/video-js-swf (or flashhls) is that you want to play back HLS but for whatever reason have to use flash and cannot use javascript (and contrib-hls) to load in the files (since it requires CORS headers on the content).
The official swf package for videojs is videojs/video-js-swf and is actively maintained. I do not know how active flashhls is.

**Comment by PeterDaveHello** [comment]
hmmmm ... we should add `videojs/video-js-swf`

**Comment by PeterDaveHello** [comment]
since `mangui/video-js-swf` is a fork of `videojs/video-js-swf`, but has no valid version tags and npm package, also not enough popularity, so add ``videojs/video-js-swf` instead.
