### ISSUE TITLE
Update for ChanceJS

### ISSUE THREAD

**Issue by Xarex** [cdnjs/cdnjs#6701]
https://cdnjs.com/libraries/chance 0.5.6

The latest version on chance.js website: Chance.js 0.8.0

http://chancejs.com/chance.js
http://chancejs.com/chance.min.js

Please update!

**Comment by maruilian11** [comment]
@PeterDaveHello chance has been updated, can we close this issue?
https://cdnjs.com/libraries/chance

**Comment by PeterDaveHello** [comment]
Sure.
