### ISSUE TITLE
[Request] CSS BROWSER SELECTOR

### ISSUE THREAD

**Issue by malikmalhan** [cdnjs/cdnjs#6704]
**Library name:Css browser selector
*_Git repository url:https://github.com/rafaelp/css_browser_selector
*_npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
close due to no response (https://github.com/rafaelp/css_browser_selector/issues/36)
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
That's not the way we close the issues.

**Comment by PeterDaveHello** [comment]
@kennynaoh you can still add this lib manually without autoupdate config since there is version number:
https://github.com/rafaelp/css_browser_selector/blob/master/css_browser_selector.js#L2

**Comment by PeterDaveHello** [comment]
Seems there are valid versions but just not tagged:
https://github.com/rafaelp/css_browser_selector/commits/master/css_browser_selector.js

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 @sufuf3  There is an updated [fork](https://github.com/verbatim/css_browser_selector). Maybe it is better to use it via [npm](https://www.npmjs.com/package/css-browser-selector) with auto update config?

**Comment by MattIPv4** [comment]
Library no longer maintained, closing.
