### ISSUE TITLE
[Request][Author] Add jpopup

### ISSUE THREAD

**Issue by seahorsepip** [cdnjs/cdnjs#6706]
**Library name: jPopup** 
**Git repository url: https://github.com/seahorsepip/jPopup**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://seapip.com/jpopup**
**Wanna say something? Leave message here: Homepage is wip.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@seahorsepip ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by seahorsepip** [comment]
I didn't knew about the notable popularity requirement, my bad.
Feel free to close this issue, I'll open a new issue when I pass above requirement.

**Comment by Piicksarn** [comment]
@seahorsepip, :+1:
