### ISSUE TITLE
[Request] babel-standalone

### ISSUE THREAD

**Issue by uniqname** [cdnjs/cdnjs#6708]
**Library name:** babel-standalone 
**Git repository url:** https://github.com/Daniel15/babel-standalone
**npm package url(optional):** https://www.npmjs.com/package/babel-standalone
**License(s):** MIT
**Official homepage:** https://github.com/Daniel15/babel-standalone
**Wanna say something? Leave message here:**
Gracias!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Would you please tell me what are the files should be hosted in this project?

**Comment by uniqname** [comment]
The comsumables are here: https://github.com/Daniel15/babel-standalone/releases
babel.js
babel.min.js

**Comment by PeterDaveHello** [comment]
Added in #6733
