### ISSUE TITLE
[Request] Add  rtMedia.backbone.js

### ISSUE THREAD

**Issue by navinachettri** [cdnjs/cdnjs#6713]
**Library name:** rtMedia.backbone.js
**Git repository url:**https://github.com/rtCamp/rtMedia/blob/master/app/assets/js/rtMedia.backbone.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**rtmedia.com
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@navinachettri,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by PeterDaveHello** [comment]
Sum of star/watch/fork looks fine, so let's add this lib @Piicksarn

**Comment by kennynaoh** [comment]
@PeterDaveHello 
I can't use git auto-update to get the files.
For example, I want to get the file `rtmedia.css` under `app/assets/css/`.
So the `basePath` field is `app/assets`, and the `files` field is `css/rtmedia*`
But I can't get it.
Please help me take a look at this library.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh Send a PR so that other people can fetch it and test.

**Comment by MattIPv4** [comment]
Library seems to have been removed from GitHub, closing.
