### ISSUE TITLE
[Request] bp-mentions

### ISSUE THREAD

**Issue by navinachettri** [cdnjs/cdnjs#6715]
**Library name:** mentions.min.js
**Git repository url:**https://github.com/buddypress/BuddyPress-build/blob/master/bp-activity/js/mentions.min.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**buddypress.org
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
#6714
