### ISSUE TITLE
[Request]jquery.caret.js

### ISSUE THREAD

**Issue by navinachettri** [cdnjs/cdnjs#6716]
**Library name:**jquery.caret.js
**Git repository url:*https://github.com/buddypress/BuddyPress-build/blob/master/bp-core/js/jquery.caret.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**buddypress.org
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@navinachettri 
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by maruilian11** [comment]
close due to no response.
