### ISSUE TITLE
[Request] Add jinqJS

### ISSUE THREAD

**Issue by amithegde** [cdnjs/cdnjs#6726]
**Library name: jinqJS** 
**Git repository url: https://github.com/fordth/jinqJs**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://www.jinqjs.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @amithegde 

This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by PeterDaveHello** [comment]
Looks ok from its npm stat. Maybe give it a lower priority on the libraries adding queue.
