### ISSUE TITLE
[Request] shortid

### ISSUE THREAD

**Issue by joonhyublee** [cdnjs/cdnjs#6736]
**Library name:** shortid
**Git repository url:** https://github.com/dylang/shortid
**npm package url(optional):** https://www.npmjs.com/package/shortid
**License(s):** MIT license
**Official homepage:** https://github.com/dylang/shortid
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @joonhyublee 
Could you point out which files should we host? Thank you.
