### ISSUE TITLE
[Request] Light7

### ISSUE THREAD

**Issue by lihongxun945** [cdnjs/cdnjs#6737]
**Library name:** Light7
**Git repository url:** https://github.com/lihongxun945/light7
**npm package url(optional):** https://www.npmjs.com/package/light7
**License(s):** MIT
**Official homepage:** http://light7.org/
**Wanna say something? Leave message here:** Light7 is a ui lib for build mobile web app
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by lihongxun945** [comment]
I will create a pull request today.

**Comment by PeterDaveHello** [comment]
Thank you @lihongxun945

**Comment by PeterDaveHello** [comment]
Didn't see your PR yet, let's reopen this before light7 been added, thanks.

**Comment by lihongxun945** [comment]
@PeterDaveHello  Sorry, I have tried to add my lib, but this repo is really huge.It's very hard to clone it.

**Comment by lihongxun945** [comment]
And I find that I can only publish one file, but I would like to publish both CSS and JS files. Is there any way to publish more than one file?

**Comment by PeterDaveHello** [comment]
You meant on GitHub GUI? I guess not, but maybe we can add this lib for you.

**Comment by lihongxun945** [comment]
I will be very appreciate.

**Comment by maruilian11** [comment]
hi @lihongxun945, could you please also create a `dist` folder in each tag because we use git auto-update which depended on git tags to update the lib's versions.
thank you very much!

**Comment by maruilian11** [comment]
@lihongxun945 do we also need to host `light7-swipeout.css` and `light7-swipeout.js`? i saw them not minified.

**Comment by lihongxun945** [comment]
Thank you very much for your help! 
I have moved to another UI lib, so there is no need to host this repo.
The new repo is here: https://github.com/lihongxun945/jquery-weui
 Maybe I will need your help when I release version `1.0.0` :)

**Comment by PeterDaveHello** [comment]
@lihongxun945 Why don't we host them both?

**Comment by lihongxun945** [comment]
I will be very appreciate if you can host them both.

**Comment by PeterDaveHello** [comment]
Sure we will.

**Comment by maruilian11** [comment]
>
|@lihongxun945 do we also need to host `light7-swipeout.css` and `light7-swipeout.js`? i saw them not minified.

@lihongxun945 :sweat_smile:

**Comment by lihongxun945** [comment]
Yes, thank you~

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Is this one already done?

**Comment by MattIPv4** [comment]
Hi there!

This library doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). Please take a look at our [pull request template, essentials checklist](https://github.com/cdnjs/cdnjs/blob/master/PULL_REQUEST_TEMPLATE.md#essential-checklist) for more information regarding this. 📖

Please open an issue again when the library has more popularity, so that we can process it properly and add the library to cdnjs! Thanks for your great work and contribution, sorry we couldn't add your request at this time. 😄
