### ISSUE TITLE
[Request] socket.io-client

### ISSUE THREAD

**Issue by joonhyublee** [cdnjs/cdnjs#6738]
**Library name:** socket.io-client
**Git repository url:** https://github.com/socketio/socket.io-client
**npm package url(optional):** https://www.npmjs.com/package/socket.io-client
**License(s):** MIT
**Official homepage:** http://socket.io
**Wanna say something? Leave message here:** This is the minimal version of socket.io intended for client-side usage

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it:
https://cdnjs.com/libraries/socket.io
