### ISSUE TITLE
[Request] Add ironwingjs

### ISSUE THREAD

**Issue by andrei-cacio** [cdnjs/cdnjs#6739]
**Library name:** ironwingjs
**Git repository url:** https://github.com/andrei-cacio/ironwing
**npm package url(optional):** https://www.npmjs.com/package/ironwing
**License(s):** MIT
**Official homepage:** http://andrei-cacio.github.io/ironwing/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@andrei-cacio ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn
