### ISSUE TITLE
[Request] AngularJS Slider

### ISSUE THREAD

**Issue by ValentinH** [cdnjs/cdnjs#6743]
**Library name: AngularJS Slider** 
**Git repository url: https://github.com/angular-slider/angularjs-slider**
**npm package url(optional): https://www.npmjs.com/package/angularjs-slider** 
**License(s): MIT**
**Official homepage: https://github.com/angular-slider/angularjs-slider**
**Wanna say something? Leave message here: As requested in https://github.com/angular-slider/angularjs-slider/issues/232**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by enric-sinh** [comment]
I recommend closing this, as there is a duplicate that has already been resolved: #6795 
(I duplicated it, sorry about that hehe).

**Comment by PeterDaveHello** [comment]
Okay, thanks.
