### ISSUE TITLE
add leafletjs related plugins

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6746]
Reference: http://leafletjs.com/plugins.html

**Comment by PeterDaveHello** [comment]
@kennynaoh hey let's try to close the issues from non-cdnjs member issued, thanks!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
You mean the issue which I opened before need to be closed, if the author is non-cdnjs member?
Thanks a lot!

**Comment by PeterDaveHello** [comment]
@kennynaoh Nope, I mean to solve other issues first.

**Comment by kennynaoh** [comment]
OK, thanks!
