### ISSUE TITLE
[Request] Add Bootstrap table context menu

### ISSUE THREAD

**Issue by Real-Gecko** [cdnjs/cdnjs#6757]
**Library name:*Bootstrap table context menu* 
**Git repository url:*https://github.com/prograhammer/bootstrap-table-contextmenu*
**npm package url(optional):** 
**License(s):*The MIT License*
**Official homepage:*https://github.com/prograhammer/bootstrap-table-contextmenu*
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@Real-Gecko sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by Real-Gecko** [comment]
OK, thank you :)
