### ISSUE TITLE
[Request] Add grid2flex

### ISSUE THREAD

**Issue by AlexisVK** [cdnjs/cdnjs#6759]
**grid2flex** 
**https://github.com/AlexisVK/grid2flex**
**https://www.npmjs.com/package/grid2flex** 
**MIT license**
**https://github.com/AlexisVK/grid2flex**
**grid2flex is configurable flexbox grid system**

**Comment by maruilian11** [comment]
@AlexisVK sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by Amomo** [comment]
closed due to no response.
