### ISSUE TITLE
[Request] Blob.js

### ISSUE THREAD

**Issue by oswinmurzello** [cdnjs/cdnjs#6782]
**Library name:** Blob.js
**Git repository url:**  https://github.com/andyinabox/Blob.js
**npm package url(optional):** 
**License(s):**  https://github.com/andyinabox/Blob.js/blob/master/LICENSE.md
**Official homepage:**  https://github.com/andyinabox/Blob.js
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello i'm not sure if this lib's popularity is enough.

**Comment by PeterDaveHello** [comment]
Not sure about 0 star and 1 watch?

**Comment by maruilian11** [comment]
but it has been forked 167 times.

**Comment by maruilian11** [comment]
@oswinmurzello sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
> but it has been forked 167 times.

it's the upstream stats ...
