### ISSUE TITLE
[Request] Add iframeActivationListener

### ISSUE THREAD

**Issue by SammySoft** [cdnjs/cdnjs#6783]
**Library name:**  iframeActivationListener
**Git repository url:** https://github.com/SammySoft/iframeActivationListener
**npm package url(optional):** 
**License(s):** MIT-Licence
**Official homepage:** I don't have one
**Wanna say something? Leave message here:**
This jquery plugin triggers an "activate" event, when an iframe gets the focus

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@SammySoft sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.
