### ISSUE TITLE
[Request] Add Bijou

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6786]
**Library name:** Bijou
**Git repository url:** https://github.com/andhart/bijou

**Comment by dannyxx001** [comment]
@PeterDaveHello there is no version and no autoupdate (it seems it won't be updated), so how should I handle it?

**Comment by PeterDaveHello** [comment]
@dannyxx001 you should open an issue to upstream, and discuss with its author, see if the author will be happy to add tags for releases, other members in @cdnjs/intern2 did this before, you can ask them for help if you still have problem.

**Comment by dannyxx001** [comment]
I can't open issue in [bijou](https://github.com/andhart/bijou).

**Comment by PeterDaveHello** [comment]
Maybe you can try to write an email, or use Trello as its readme says.

**Comment by dannyxx001** [comment]
I had sent email to the author, let's wait for respond.

**Comment by dannyxx001** [comment]
The email is failed. So I had trying the Trello. Let's wait for respond.

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close
