### ISSUE TITLE
[Request] Add color

### ISSUE THREAD

**Issue by aush** [cdnjs/cdnjs#6800]
**Library name:** color
**Git repository url:** https://github.com/Qix-/color
**npm package url(optional):** https://www.npmjs.com/package/color
**License(s):** MIT
**Official homepage:** https://github.com/Qix-/color

**Comment by maruilian11** [comment]
@aush could this lib be run on browser?

**Comment by aush** [comment]
Sorry, didn't check it first. No, this lib doesn't have a standalone build for browser and they reject to have it for whatever reason. Closing this.
