### ISSUE TITLE
[Request] Add mapglyphs

### ISSUE THREAD

**Issue by dtjones** [cdnjs/cdnjs#6801]
**Library name:** mapglyphs
**License(s):** http://mapglyphs.com/license
**Official homepage:**http://mapglyphs.com/

**Comment by maruilian11** [comment]
@dtjones please provide **git repo url** or **npm package url**, thanks.

**Comment by dtjones** [comment]
Its only available as a direct download from their website.
Hopefully this will change in the future.

https://www.npmjs.com/search?q=mapglyphs
https://github.com/search?utf8=%E2%9C%93&q=mapglyphs

**Comment by dtjones** [comment]
would this help 
https://github.com/dtjones/mapglyphs

**Comment by maruilian11** [comment]
@dtjones sorry, we only add libs from official git repo or npm package url.

**Comment by maruilian11** [comment]
@dtjones this issue will be closed if there is no any response in next 7 days.
thank you for your contribution.

**Comment by dtjones** [comment]
@maruilian11, yea no problem. i will add a new issue if an official repo or npm package are ever created.

**Comment by maruilian11** [comment]
:+1:  thank you!

**Comment by PeterDaveHello** [comment]
@dtjones I just tweeted them a msg: https://twitter.com/PeterDaveHello/status/699863354580439040
Maybe you can also email them see if they can help, thanks.
