### ISSUE TITLE
[Request] bootstrap-treeview

### ISSUE THREAD

**Issue by harmoniemand** [cdnjs/cdnjs#6802]
**Library name: bootstrap-treeview** 
**Git repository url:https://github.com/jonmiles/bootstrap-treeview.git**
**npm package url(optional):** 
**License(s):Apache License, Version 2.0**
**Official homepage: http://jonmiles.github.io/bootstrap-treeview/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@harmoniemand duplicated with #6872, sorry for not replying you first, we are trying to add this library.
