### ISSUE TITLE
[Request] Add ng2-bootstrap

### ISSUE THREAD

**Issue by valorkin** [cdnjs/cdnjs#6805]
**Library name:** ng2-bootstrap
**Git repository url:** https://github.com/valor-software/ng2-bootstrap
**npm package url(optional):** https://www.npmjs.com/package/ng2-bootstrap
**License(s):** MIT
**Official homepage:** http://valor-software.github.io/ng2-bootstrap/
**Wanna say something? Leave message here:** first angular2 module in cdnjs if accepted :)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Library was added via 5ec2abf13a696ab7fd30781b4cbe30a6da47d5cd
