### ISSUE TITLE
[Error] bootstrap-datetimepicker

### ISSUE THREAD

**Issue by AuspeXeu** [cdnjs/cdnjs#6806]
The library
https://cdnjs.com/libraries/smalot-bootstrap-datetimepicker
does not seem to be updated automatically.

**Comment by PeterDaveHello** [comment]
@AuspeXeu Thanks for report, I'll take a look.

**Comment by AuspeXeu** [comment]
Is this going to be updated automatically from now on?

**Comment by PeterDaveHello** [comment]
@AuspeXeu Yes
