### ISSUE TITLE
[Request] Add primeui

### ISSUE THREAD

**Issue by cagataycivici** [cdnjs/cdnjs#6812]
**Library name:** PrimeUI
**Git repository url:** https://github.com/primefaces/primeui-distribution/tree/v3.0.0
**npm package url(optional):** 
**License(s):** Apache V2
**Official homepage:** http://www.primefaces.org/primeui
**Wanna say something? Leave message here:**
PrimeUI is an open source UI library with over 50 jQuery UI widgets and WebComponents.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@cagataycivici sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it. 

**you can also send a PR yourself, we'll be glad to merge it, thanks
btw, you can regard https://github.com/maruilian11/cdnjs/commit/8992a41b850a7e8f65ac9c857a4ba66bc66f3e28 as an example which i sent carelessly without checking the popularity :sweat_smile:**

**Comment by cagataycivici** [comment]
No worries, we've bought a plan from maxcdn and created its own cdn. Thank you for the consideration anyway.

**Comment by PeterDaveHello** [comment]
Hey this repo is a distribution purpose repo, I just took at the organization and other repos, we should add this repo asap. @cagataycivici i believe that we can provide more fast and reliable cdn for this project, cdnjs support both spdy and http/2.0 at the same time, which and speed up on much more devices, and also cloudflare has more  datacenters around the world, so please wait few more hours, we will add this lib, or you can send a pull request, thanks :smile:

**Comment by maruilian11** [comment]
sorry, i'm late. 😓

**Comment by cagataycivici** [comment]
@PeterDaveHello @maruilian11 awesome, thank you very much. Do we need to anything now after we do a new release? Does cdnjs pull the releases from github whenever we do a release with a tag?

**Comment by PeterDaveHello** [comment]
@cagataycivici we will pull the new releases from the git tags of the repo, thanks.

**Comment by cagataycivici** [comment]
@PeterDaveHello, thank you.

**Comment by PeterDaveHello** [comment]
no problem
