### ISSUE TITLE
[Request] Add _ZTree

### ISSUE THREAD

**Issue by Basil1991** [cdnjs/cdnjs#6816]
**Library name:zTree** 
**Git repository url:https://github.com/zTree/zTree_v3**
**License(s):MIT**
**Official homepage:http://www.ztree.me/v3/main.php#_zTreeInfo**
**Wanna say something? Leave message here:Just add it.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Basil1991** [comment]
What can I do for this?

**Comment by PeterDaveHello** [comment]
@Basil1991 We are waiting for the response from its author, we need to confirm which hash of the commits is the exactly the latest version(v3.5.20).

**Comment by maruilian11** [comment]
@PeterDaveHello do we need to add this lib manually？ or there is another way？
https://github.com/zTree/zTree_v3/issues/130#issuecomment-184476311

**Comment by PeterDaveHello** [comment]
We can add it manually this time if the author doesn't like to change the filename.

**Comment by Stephan972** [comment]
Hello,

How can I use zTree from cdnjs?

TIA

**Comment by PeterDaveHello** [comment]
Hi @Stephan972, we are still confirming the detail, will add it ASAP, please wait for few more days, thanks.
