### ISSUE TITLE
Option to track the "latest" release of a library?

### ISSUE THREAD

**Issue by Xotic750** [cdnjs/cdnjs#6817]
Please excuse me if this has been asked before or is somewhere in the documentation, but I couldn't find it.

Is there a way to track the latest release of a library? Something like
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/latest/es5-shim.min.js"></script>
```

Thanks.

**Comment by PeterDaveHello** [comment]
@Xotic750 Nope, we do not have this feature.

**Comment by Xotic750** [comment]
@PeterDaveHello Thanks. Is this something that has or would be considered as a feature request? It would be nice to have. ;)

**Comment by PeterDaveHello** [comment]
@Xotic750 Nope, this feature been rejected many times, it may cause cache  purge and version upgrade breaking issue.

**Comment by Xotic750** [comment]
Ok, thanks for the info.

**Comment by PeterDaveHello** [comment]
NP, thanks for understanding, here are some references, just for your information:
#360 #5674 #4396 #3614 #987 #423 #6120

**Comment by Xotic750** [comment]
:+1:
