### ISSUE TITLE
Google web fonts mirror?

### ISSUE THREAD

**Issue by dandyhat** [cdnjs/cdnjs#682]
Would it make sense to mirror Google web fonts? 

It would be useful as some countries block/throttle connections to Google. _cough_ China _cough_

**Comment by seb-elico** [comment]
Hi there,

In case that could help, the ustclug.org website hosts a Chinese mirror of Google web fonts:
https://fonts-gstatic.proxy.ustclug.org

For instance:
https://fonts-gstatic.proxy.ustclug.org/s/raleway/v12/1Ptrg8zYS_SKggPNwJYtWqZPAA.woff2

They also hosts a mirror of the associated CSS:
https://fonts.proxy.ustclug.org

For instance:
https://fonts.proxy.ustclug.org/css?family=Arapey:400italic,400

**Comment by PeterDaveHello** [comment]
@seb-elico it there any license info?

**Comment by seb-elico** [comment]
@PeterDaveHello 
Not sure as all documentation is in Chinese. Based on my understanding, it's a simple reverse-proxy to the original Google servers, so I guess license should be the same.

FYI:

- [list](https://lug.ustc.edu.cn/wiki/mirrors/help/revproxy) of ustclug.org reverse-proxies
- [list](http://mirrors.ustc.edu.cn/) of ustclug.org mirrors

**Comment by dankohn** [comment]
Unfortunately, the Great Firewall of China seems to again be blocking http://fonts.googleapis.com. 

One workaround is to dynamically switch to a Chinese proxy using the technique mentioned in: https://www.hongkiat.com/blog/google-fonts-china/ but using https://fonts.proxy.ustclug.org/css?family=Arapey:400italic,400 as the proxy.

Another option is to host the fonts on your own site using https://www.npmjs.com/package/google-fonts-webpack-plugin which is what we do with https://landscape.cncf.io/ .
