### ISSUE TITLE
[Request] react-nvd3

### ISSUE THREAD

**Issue by royyeah** [cdnjs/cdnjs#6828]
**Library name:** react-nvd3
**Git repository url:** https://github.com/NuCivic/react-nvd3/
**npm package url(optional):** https://www.npmjs.com/package/react-nvd3/
**License(s):** None
**Official homepage:** None
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@royyeah sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Looks okay with its npm stats, please add this lib.

**Comment by royyeah** [comment]
Thanks @PeterDaveHello !

**Comment by PeterDaveHello** [comment]
@royyeah Np
