### ISSUE TITLE
[Request] Add messageformat

### ISSUE THREAD

**Issue by sylvainbx** [cdnjs/cdnjs#6829]
**Library name:** messageformat
**Git repository url:** https://github.com/SlexAxton/messageformat.js
**npm package url(optional):** messageformat
**License(s):** MIT
**Wanna say something? Leave message here:**

Hi, would you please add the messageformat library to CDNjs ? Especially versions <= 0.1.8 witch includes 'locales' files.

**Comment by sylvainbx** [comment]
Ok, I just see it was already requested in #5870. I close this as a duplicate.

**Comment by PeterDaveHello** [comment]
@sylvainbx Thanks.
