### ISSUE TITLE
[Request] Add cross-domain-ajax 

### ISSUE THREAD

**Issue by thdoan** [cdnjs/cdnjs#6845]
**Library name:**
cross-domain-ajax
**Git repository url:**
https://github.com/padolsey-archive/jquery.fn.git
**npm package url(optional):** 
**License(s):**
http://unlicense.org/UNLICENSE
**Official homepage:**
https://github.com/padolsey-archive/jquery.fn/tree/master/cross-domain-ajax
**Wanna say something? Leave message here:**
This plugin is in the `cross-domain-ajax` directory.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @maruilian11

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Suggest to close due to a lot of time passed since the issue was opened and request to add git tag to repo was sent
