### ISSUE TITLE
[Request] Add ngQuill

### ISSUE THREAD

**Issue by ghazalashahid** [cdnjs/cdnjs#6847]
**Library name:** ngQuill
**Git repository url:** https://github.com/killercodemonkey/ngQuill
**npm package url(optional):** 
**License(s):** The MIT License (MIT)
**Official homepage:** http://quilljs.com/docs/quickstart/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @ghazalashahid 
This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by maruilian11** [comment]
close due to no response.
