### ISSUE TITLE
[Request] Add wNumb

### ISSUE THREAD

**Issue by thib3113** [cdnjs/cdnjs#6850]
**Library name:** wNumb
**Git repository url:** https://github.com/leongersen/wnumb
**License(s):**  WTFPL
**Official homepage:** http://refreshless.com/wnumb/
**Wanna say something? Leave message here:** For formatting numbers

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @thib3113 
This library currently doesn't have enough popularity(100 watch or star is a good example).
Please take a look on our [README.md] (https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you to open an issue when the library has more popularity.
Thanks for your contribution. :-)

**Comment by thib3113** [comment]
Hum, yes sorry, I don't read, juste click add, and I come here :) . So no problem :)
