### ISSUE TITLE
[Request] Add jGravity

### ISSUE THREAD

**Issue by Dasky14** [cdnjs/cdnjs#6858]
**Library name:** jGravity
**Git repository url:** https://github.com/tinybigideas/jGravity
**License(s):** MIT
**Official homepage:** http://tinybigideas.com/plugins/jquery-gravity/
**Wanna say something? Leave message here:**
Something that is fun to play around with. Adds physics to page elements.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@Dasky14,
The lib would be considered to added in cdnjs as the tags be used.
We need tags for confirming the version.
Thank you! :smiley: 

Piicksarn

**Comment by Dasky14** [comment]
Thanks for asking about the tag for me, but the actual poster of the jGravity hasn't been active in years as far as I can see... Which is also why I'd like to have this hosted. Is it a big problem?

**Comment by PeterDaveHello** [comment]
Seems commit: https://github.com/tinybigideas/jGravity/commit/aa8ef26df92b21d5cfececf81764e00fca17a7ec can be v0.8

**Comment by Dasky14** [comment]
Okay, there haven't been any responses so... How to add tags? Is this something I need to do?

**Comment by PeterDaveHello** [comment]
No response from author side, @Piicksarn let's just manually add it as its version number in the minified js file.
