### ISSUE TITLE
[Request] Add ilikenwf-nestedSortable

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6863]
**Library name:** nestedSortable
**Git repository url:** https://github.com/ilikenwf/nestedSortable

**Comment by maruilian11** [comment]
already added. https://cdnjs.com/libraries/nestedSortable

**Comment by PeterDaveHello** [comment]
Mention related works before you close it.

**Comment by PeterDaveHello** [comment]
cc #6862 #7020

**Comment by maruilian11** [comment]
hmmm... so can we close this issue?
