### ISSUE TITLE
[Request] Add najaxjs

### ISSUE THREAD

**Issue by anyjser** [cdnjs/cdnjs#6868]
Library name: najaxjs
Git repository url: https://github.com/any-js/najaxjs
npm package url(optional): https://www.npmjs.com/package/najaxjs
License(s): MIT
Official homepage: http://any-js.github.io/

**Comment by kennynaoh** [comment]
Hello @anyjser ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.
Thanks!

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh we can add this lib :smile:

**Comment by kennynaoh** [comment]
OK, thanks!
