### ISSUE TITLE
[Request] Bulma

### ISSUE THREAD

**Issue by petercook** [cdnjs/cdnjs#6875]
**Library name: Bulma** 
**Git repository url: https://github.com/jgthms/bulma.git**
**npm package url(optional):** 
**License(s): MIT License**
**Official homepage: http://bulma.io**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #6837
