### ISSUE TITLE
[Request] Add Feather

### ISSUE THREAD

**Issue by KingPixil** [cdnjs/cdnjs#6876]
**Library name: Feather** 
**Git repository url: https://github.com/KingPixil/Feather.git**
**npm package url(optional):** 
**License(s): MIT License**
**Official homepage: http://kingpixil.github.io/Feather/**
**Wanna say something? Leave message here: Feather is a lightweight framework for making things as light as a feather**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@KingPixil sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**P.S. you can send the PR yourself, we'll be glad to merge it. please take a look at our [CONTRIBUTING.md](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md).**

**Comment by KingPixil** [comment]
Ok, I understand, but if I do not have enough popularity, I can still send a PR?

**Comment by maruilian11** [comment]
@PeterDaveHello can this lib be added by its author?

**Comment by PeterDaveHello** [comment]
Nope, it needs higher popularity.
