### ISSUE TITLE
[Request] Add Bulma CSS Framework

### ISSUE THREAD

**Issue by ahlee2326** [cdnjs/cdnjs#6879]
**Library name:** Bulma
**Git repository url:** https://github.com/jgthms/bulma
**npm package url(optional):** https://www.npmjs.com/package/bulma
**License(s):** MIT
**Official homepage:** http://bulma.io/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ahlee2326** [comment]
Same as #6875

**Comment by ahlee2326** [comment]
And #6837

**Comment by PeterDaveHello** [comment]
Duplicated with #6837
