### ISSUE TITLE
[Request] ng-sortable

### ISSUE THREAD

**Issue by AmitMY** [cdnjs/cdnjs#6884]
**Library name:** ng-sortable
**Git repository url:** https://github.com/a5hik/ng-sortable
**License(s):** MIT
**Wanna say something? Leave message here:**
Pretty popular library

**Comment by kennynaoh** [comment]
This library already exist.
https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ng-sortable
cc @PeterDaveHello 
Thanks

**Comment by PeterDaveHello** [comment]
Close per #7327
