### ISSUE TITLE
[Request] Add FeedEk

### ISSUE THREAD

**Issue by JacobLett** [cdnjs/cdnjs#6889]
http://jquery-plugins.net/FeedEk/FeedEk.html

https://github.com/enginkizil/FeedEk

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@JacobLett :smiley: 
the lib would be added in cdnjs when the package.json be used.

**Comment by PeterDaveHello** [comment]
@Piicksarn There is no need to wait for package.json

**Comment by PeterDaveHello** [comment]
Ping @Piicksarn
