### ISSUE TITLE
[Request] Add Louis Remy jquery.transform.js

### ISSUE THREAD

**Issue by mkormendy** [cdnjs/cdnjs#6891]
**Library name:** Louis Remy jquery.transform.js
**Git repository url:** https://github.com/louisremi/jquery.transform.js
**npm package url(optional):** 
**License(s):** Dual licensed under GPL and MIT licenses.
**Official homepage:** http://louisremi.github.com/jquery.transform.js/index.html

**Comment by PeterDaveHello** [comment]
@mkormendy there is no any version tag in its repository, so we can not confirm its version and add it right now, would you please help create an issue ticket to help us confirm its version? Thanks.

cc author @louisremi

**Comment by mkormendy** [comment]
I have requested to have a version tag added to the repo.

**Comment by PeterDaveHello** [comment]
@mkormendy Thanks man.

**Comment by PeterDaveHello** [comment]
Hi @mkormendy, is there any updates? Thanks.

**Comment by mkormendy** [comment]
It appears to have been abandoned. Suggestions?

**Comment by PeterDaveHello** [comment]
Yes, it appears to have been abandoned, are you still using this lib? Or there are some alternatives for you?

**Comment by mkormendy** [comment]
I am using this library .. Maybe I can fork it and add the version tag to my repo.

**Comment by PeterDaveHello** [comment]
Maybe you can try rawgit by MaxCDN:
https://cdn.rawgit.com/louisremi/jquery.transform.js/master/jquery.transform2d.js
https://cdn.rawgit.com/louisremi/jquery.transform.js/master/jquery.transform3d.js

**Comment by mkormendy** [comment]
Ideally a minified version would be the best. I'm not seeing that with rawgit.

**Comment by PeterDaveHello** [comment]
If you fork it, of course you can minify them, the lib seen to been abandoned and have no valid version, I have no idea to how to or why to add it.

**Comment by mkormendy** [comment]
Okay that's an alternative I'm willing to use.

I have placed them here:
https://cdn.rawgit.com/mkormendy/jquery.transform.js/master/jquery.transform2d.min.js
https://cdn.rawgit.com/mkormendy/jquery.transform.js/master/jquery.transform3d.min.js

Thanks for all your help.

**Comment by PeterDaveHello** [comment]
:+1:
