### ISSUE TITLE
[Request] Add apostle.js 

### ISSUE THREAD

**Issue by TrungRueta** [cdnjs/cdnjs#6893]
**Library name: apostle.js** 
**Git repository url: https://github.com/apostle/apostle.js**
**npm package url(optional):** 
**License(s): **
**Official homepage: apostle.io**
**Wanna say something? Leave message here: **

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@TrungRueta ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your contribution. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by TrungRueta** [comment]
Hi, 
Thank for explained detail our conditions! I just think will be great if we have it because this is offical library of apostle - email sevice  popular. But sure we have conditions for all sources and we need follow rules ;). I will make new request in future if library becomes more popular!

Thank cdnjs !!
