### ISSUE TITLE
[Request] Add triangles

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6897]
**Library name:** triangles
**Git repository url:** https://github.com/msurguy/triangles

**Comment by PeterDaveHello** [comment]
Can't you use bower.json as sample? https://github.com/msurguy/triangles/blob/master/bower.json

**Comment by maruilian11** [comment]
i open the issue because i want to confirm if the npm package url is their official package.
we prefer use npm auto-update than git.
