### ISSUE TITLE
[request] github-calendar

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#6898]
https://www.npmjs.com/package/github-calendar
https://github.com/ionicabizau/github-calendar

cc @IonicaBizau

**Comment by IonicaBizau** [comment]
Hey, @PeterDaveHello! That would be great! :four_leaf_clover:

**Comment by PeterDaveHello** [comment]
:smile: Feel free to send a PR if you would like to.

**Comment by IonicaBizau** [comment]
@PeterDaveHello Sure! I will probably will. :smile:
