### ISSUE TITLE
[Request] Clip Path Polygon

### ISSUE THREAD

**Issue by gilangpramudya** [cdnjs/cdnjs#6899]
**Clip Path Polygon:** 
**Git repository url:https://github.com/andrusieczko/clip-path-polygon**
**npm package url(optional):npm install clip-path-polygon** 
**License(s):MIT**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @gilangpramudya,

Thanks for your request, however, this lib didn't meet our requirement about the popularity yet, I'll respectfully suggest you to submit a new issue ticket when it has more than 100 stars on GitHub or has more than 300 downloads per month on npm stats, thanks.
