### ISSUE TITLE
[Request] Add APlayer

### ISSUE THREAD

**Issue by nyaatyan** [cdnjs/cdnjs#6900]
**Library name:** APlayer
**Git repository url:** https://github.com/DIYgod/APlayer
**npm package url(optional):** https://www.npmjs.com/package/aplayer
**License(s):** MIT
**Official homepage:** https://www.anotherhome.net/file/APlayer/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by DIYgod** [comment]
😆👍
