### ISSUE TITLE
[Request] Add min-dom

### ISSUE THREAD

**Issue by rjayasinghe** [cdnjs/cdnjs#6904]
**min-dom:** 
**Git repository url: https://github.com/bpmn-io/min-dom**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://github.com/bpmn-io/min-dom**
**Wanna say something? Leave message here: nothing special. would just be great to have that lib on cdnjs. thx! :-)**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @rjayasinghe 
Thanks for your request, however, this lib didn't meet our requirement about the popularity yet, I'll respectfully suggest you to submit a new issue ticket when it has more than 100 stars on GitHub or has more than 300 downloads per month on npm stats, thanks.

**Comment by rjayasinghe** [comment]
oh yes. just saw, that it has 0 (zero!) stars. ;-)
