### ISSUE TITLE
[Request] Aurora Grid

### ISSUE THREAD

**Issue by elrumordelaluz** [cdnjs/cdnjs#6905]
**Library name: Aurora Grid** 
**Git repository url: https://github.com/aurora-kit/aurora-grid**
**npm package url(optional): https://www.npmjs.com/package/aurora-grid** 
**License(s): http://www.pixeden.com/license**
**Official homepage: http://themes-pixeden.com/aurora-kit/grid**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Sorry for the delay, I'm now working on this issue.

**Comment by PeterDaveHello** [comment]
There is no pre-built files in the git repo and npm package, going to manually build it now.

**Comment by PeterDaveHello** [comment]
Okay, I cannot build it with success ...
```
[18:25:06] Using gulpfile /home/peter/node_modules/.store/aurora-grid@1.0.5/_/gulpfile.js
[18:25:06] Starting 'scss'...
[18:25:06] gulp-notify: [Scss error] Error: src/_functions.scss
Error: Undefined variable: "$min-val".
        on line 101 of src/_functions.scss
>>   $min-query: if($min-val and $min-val != 0, '(min-width: #{$min-val})', null)
   -----------------^

[18:25:06] gulp-notify: [Error running notifier] Could not send message: not found: notify-send
[18:25:06] Finished 'scss' after 202 ms
[18:25:06] Starting 'default'...
[18:25:06] Finished 'default' after 30 μs

```

**Comment by PeterDaveHello** [comment]
@elrumordelaluz seems you are the author of this lib, would you please send a PR or provide the files? Thanks.

**Comment by elrumordelaluz** [comment]
@PeterDaveHello I'm sorry for this, will give it a look on why you couldn't compile. In the meanwhile I [added](https://github.com/aurora-kit/aurora-grid/tree/dev/dist) the compiled files into the repo. 

Let me know if there's anything else I can do.

Thanks,

**Comment by PeterDaveHello** [comment]
@elrumordelaluz Could you please tell me the version you put there? Thanks.

**Comment by elrumordelaluz** [comment]
`1.0.6`

**Comment by PeterDaveHello** [comment]
@elrumordelaluz but it's in dev branch, what about just give it a `1.0.6` tag?

**Comment by elrumordelaluz** [comment]
@PeterDaveHello I'm sorry it [was there](https://github.com/aurora-kit/aurora-grid/releases/tag/v1.0.6) but missed tu push it.

**Comment by PeterDaveHello** [comment]
@elrumordelaluz added now, you can also add the old versions via sending a PR, thanks.
