### ISSUE TITLE
[Request] stickyfloat

### ISSUE THREAD

**Issue by SimonFricker** [cdnjs/cdnjs#6906]
**Library name:**  stickyfloat
**Git repository url:**https://github.com/yairEO/stickyfloat
**npm package url(optional):** 
**License(s):** none
**Official homepage:** none
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Sorry for the delay, I'm now working on this issue.
