### ISSUE TITLE
[Request] bootstrap-validator

### ISSUE THREAD

**Issue by SimonFricker** [cdnjs/cdnjs#6912]
**Library name:** Bootstrap Validator
**Git repository url:** https://github.com/1000hz/bootstrap-validator
**npm package url(optional):** 
**License(s):** MIT license.
**Official homepage:** https://1000hz.github.io/bootstrap-validator/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/1000hz-bootstrap-validator
