### ISSUE TITLE
[Request] swipebox.min.css

### ISSUE THREAD

**Issue by trevisanweb** [cdnjs/cdnjs#6913]
Library name: Swipebox
Git repository url: https://github.com/brutaldesign/swipebox
npm package url(optional): 
License(s): http://www.pixeden.com/license
Official homepage: http://brutaldesign.github.io/swipebox/

**Comment by PeterDaveHello** [comment]
Seems the minified file may not be up-to-date ... 

https://github.com/brutaldesign/swipebox/tree/1.4.1/src/css
