### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by danie92** [cdnjs/cdnjs#6917]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

Hye may i request a lib for my project

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@danie92 what's the detail? If the lib has enough notable popularity, we will be happy to host it.

**Comment by maruilian11** [comment]
@danie92 please provide your lib's gir repo url or npm package url, thanks.

**Comment by maruilian11** [comment]
@danie92 this issue will be closed if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
This kind of issues look no chance to discuss and the issuer didn't respond, let's close it  right now!
