### ISSUE TITLE
[Request] Add jquery-simple-websocket

### ISSUE THREAD

**Issue by jbloemendal** [cdnjs/cdnjs#6920]
**Library name:*jquery-simple-websocket* 
**Git repository url:*https://github.com/jbloemendal/jquery-simple-websocket
**npm package url(optional):*https://www.npmjs.com/package/jquery-simple-websocket
**License(s):*Apache License*
**Official homepage:*http://jbloemendal.github.io/jquery-simple-websocket/
**Wanna say something? Leave message here:*jQuery Simple WebSocket - a fluent, gracefull websocket*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @jbloemendal ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution. :-)
This issue will be closed if there is no any response in next 7 day.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Close due to no respsone.
