### ISSUE TITLE
[Request] Add ColorRotator.js

### ISSUE THREAD

**Issue by ykadosh** [cdnjs/cdnjs#6921]
**Library name:** ColorRotator.js
**Git repository url:** https://github.com/askupasoftware/color-rotator
**License(s):** GNU GENERAL PUBLIC LICENSE
**Official homepage:** http://products.askupasoftware.com/color-rotator/

**Comment by PeterDaveHello** [comment]
@ykadosh we need a higher popularity to add a new lib, please read our document first. Feel free to ping me if I miss anything.
