### ISSUE TITLE
[Request] Anchorific

### ISSUE THREAD

**Issue by joeldrapper** [cdnjs/cdnjs#6925]
**Library name:** Anchorific
**Git repository url:** https://github.com/renettarenula/anchorific.js/
**npm package url(optional):** 
**License(s):** MIT

**Comment by maruilian11** [comment]
@PeterDaveHello since the author has not acted on github for a long time, can we use commit log as version to add this lib?

**Comment by PeterDaveHello** [comment]
Yes, let's add it.
