### ISSUE TITLE
[Request] Add Selectivizr 2

### ISSUE THREAD

**Issue by corysimmons** [cdnjs/cdnjs#6935]
**Library name:** Selectivizr 2 
**Git repository url:** https://github.com/corysimmons/selectivizr2
**npm package url(optional):** https://www.npmjs.com/package/selectivizr2
**License(s):** MIT
**Official homepage:** http://selectivizr.com
**Wanna say something? Leave message here:** Hi mom!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@corysimmons sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by corysimmons** [comment]
Ah okay. Maybe you guys should add that to you Issue generator so I don't waste time trying to add libs?

**Comment by PeterDaveHello** [comment]
@corysimmons Sorry, but actually GitHub will remind you to read the contribution document when openning an issue, we will try to make things much more easier, thanks.

**Comment by corysimmons** [comment]
```
=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue.
We won't accept any lib with fewer than 100 stars or 500 downloads/mo on npmjs.com.
Please don't forget to read the guidelines for contributing, thanks!!
```

I don't think this extra line is crazy and I'm willing to bet maintainers have to close a lot of these "not enough stars" issues.

**Comment by PeterDaveHello** [comment]
@corysimmons Oh nope, sorry but I didn't mean this, there is a upper bar shows upon the issue title on the openning issue page.

**Comment by PeterDaveHello** [comment]
@corysimmons And yes you are correct, we need to close many issue, in fact we do not have enough human resource on the things, we may have our own issue tracker for the lib adding request in future, but not now.

**Comment by corysimmons** [comment]
Well, I can testify that I wouldn't have submitted 3 of my sub-100 libs if that message was in there. Might be worth asking about.

**Comment by PeterDaveHello** [comment]
@corysimmons Oh i am sure that GitHub says "Please review the guidelines for contributing to this repository." but I have to say sorry, in https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md, the popularity part is missimg, we only talk about it in https://github.com/cdnjs/cdnjs/blob/master/README.md

**Comment by corysimmons** [comment]
Even so, I don't have time to read every piece of docs people want me to read.

I'm just trying to save you guys time. I can imagine this is the most frequent issue you have to deal with. Implement the change or not. I don't care.

**Comment by PeterDaveHello** [comment]
@corysimmons Okay still thanks.

**Comment by PeterDaveHello** [comment]
@corysimmons I just found that you are the author of some popular libs, and you also have many followers on GitHub, I would like to host your libs as they have the potential to be popular, they also have some download stats on npm, as new libs, it looks great enough, hope you don't mind.

**Comment by corysimmons** [comment]
That'd be great! https://github.com/cdnjs/cdnjs/issues?q=is%3Aissue+author%3Acorysimmons+is%3Aclosed

I doubt selectivizr2 or ie-love will get too much attention because no one is supporting ie8 nowadays, but hopefully reeeset will garner some attention for people who are tired of un-doing normalize.css stuff all the time. :)

Thanks! :D

**Comment by PeterDaveHello** [comment]
@corysimmons Thanks for prompt reply, I just reopened all your issue tickets, but I'll need you wait for a while, we still have a lot of issues to be solved, sorry.

**Comment by corysimmons** [comment]
No problem. Thanks!

**Comment by PeterDaveHello** [comment]
@corysimmons Thank you.

**Comment by corysimmons** [comment]
:+1: Thanks everyone.
