### ISSUE TITLE
[Request] Add Angular SocialShare

### ISSUE THREAD

**Issue by stefankatic** [cdnjs/cdnjs#6941]
Angular SocialShare
https://github.com/720kb/angular-socialshare
http://ngmodules.org/modules/angular-socialshare
MIT
http://720kb.github.io/angular-socialshare/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by stefankatic** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
@stefankatic You are welcome.
