### ISSUE TITLE
[Request] Add reeeset

### ISSUE THREAD

**Issue by corysimmons** [cdnjs/cdnjs#6942]
**Library name:**  reeeset
**Git repository url:** https://github.com/corysimmons/reeeset
**npm package url(optional):** https://www.npmjs.com/package/reeeset
**License(s):** MIT
**Official homepage:** https://github.com/corysimmons/reeeset
**Wanna say something? Leave message here:** It's just a CSS reset. Here is the link to the minified dist: https://github.com/corysimmons/reeeset/blob/master/dist/reeeset.min.css

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by corysimmons** [comment]
Not enough stars.

**Comment by PeterDaveHello** [comment]
Let's add this lib.

**Comment by corysimmons** [comment]
Actually don't add this lib. I think I'm going to focus my efforts on https://github.com/10up/sanitize.css instead of maintaining a similar project.

That said, the current cdnjs.com sanitize.css **is not** the official sanitize.css (https://github.com/10up/sanitize.css).

Is there any way we can change it from the 24 star repo that hasn't been updated in several months to the 1000+ star repo?

**Comment by PeterDaveHello** [comment]
@corysimmons Nope, but we can add a new lib called 10up-sanitize.css, 10up-sanitize or what ever you think is better.

**Comment by corysimmons** [comment]
I've contacted the plugin author. Hopefully he'll just vacate his spot.

**Comment by PeterDaveHello** [comment]
@corysimmons so you want me close this issue?

**Comment by corysimmons** [comment]
Yes you can close this issue.

**Comment by PeterDaveHello** [comment]
@corysimmons Ok, thanks.

**Comment by corysimmons** [comment]
^
