### ISSUE TITLE
[Request] Add ie-love

### ISSUE THREAD

**Issue by corysimmons** [cdnjs/cdnjs#6943]
**Library name:** ie-love
**Git repository url:** https://github.com/corysimmons/ie-love
**npm package url(optional):** https://www.npmjs.com/package/ie-love
**License(s):** MIT
**Official homepage:** https://github.com/corysimmons/ie-love
**Wanna say something? Leave message here:** Combo polyfill for IE8. Here's the minified version https://github.com/corysimmons/ie-love/blob/master/dist/ie-love.min.js
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by corysimmons** [comment]
Not enough stars.

**Comment by PeterDaveHello** [comment]
Let's add this lib.
