### ISSUE TITLE
[Request] Add jquery.key.js

### ISSUE THREAD

**Issue by jdwuzhere** [cdnjs/cdnjs#6944]
**Library name: jquery.key.js** 
**Git repository url: https://github.com/yckart/jquery.key.js**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://github.com/yckart/jquery.key.js**
**Wanna say something? Leave message here: The certainly simpliest shortcut key event handler ever (c) 2013 Yannick Albert (http://yckart.com)**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@jdwuzhere we need a higher popularity to host add lib, please read our document first. If I missed anything, feel free to tell me, thanks.
