### ISSUE TITLE
[Request] angular-translate 2.9.0

### ISSUE THREAD

**Issue by izifortune** [cdnjs/cdnjs#6946]
**Library name: angular-translate** 
**Git repository url: https://github.com/angular-translate/bower-angular-translate**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://angular-translate.github.io/**
**Wanna say something? Leave message here:**
Hi, would be nice to update all the angular-translate libraries to 2.9.0 since its the last version of it.

The libraries can be found in here:

https://github.com/angular-translate

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@izifortune Thanks for report.
