### ISSUE TITLE
[Request] Cycle2 Main instead of just the parts

### ISSUE THREAD

**Issue by AdamHess** [cdnjs/cdnjs#6949]
Cycle 2:
https://github.com/malsup/cycle2
http://jquery.malsup.com/cycle2/

Cycle 2 is already supported and hosted **however** cdnjs only has the parts that make up the library and doesn't have the all in one this hurts **both** cdnjs and users accessing sites. 

cdnjs gets 5-6 requests for one library and our users will have to make those 5-6 requests.

Please consider adding the all-in-one built cycle2 library to cdnjs which can be found here

https://github.com/malsup/cycle2/blob/master/build/jquery.cycle2.min.js

this is not to be confused with the core library.  

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@AdamHess Thanks, I'll fix it.
