### ISSUE TITLE
[Request] Add infamous 

### ISSUE THREAD

**Issue by trusktr** [cdnjs/cdnjs#6950]
**Library name:** Infamous
**Git repository url:** http://github.com/infamous/infamous
**npm package url(optional):** 
**License(s):** MPL
**Official homepage:** http://infamous.io
**Wanna say something? Leave message here:** 3D rendering for the web with an HTML interface (alpha stage).

If you `npm install infamous`, the file to host would be the `infamous.js` file (or `global.js` file in more recent versions).

**Comment by PeterDaveHello** [comment]
@trusktr so we only need to host global.js?

**Comment by trusktr-goin** [comment]
Yep, just global.js. Maybe renamed to infamous.js?

**Comment by PeterDaveHello** [comment]
hmmm ... both fine, just make sure which one will be used in future, so that I can write auto-update config for it.

**Comment by trusktr-goin** [comment]
Hi Peter, if I were to choose `global.js`, for example, what would the URL be like? Would it be `https://cdnjs.cloudflare.com/ajax/libs/infamous/1.0.3/global.js`?

**Comment by PeterDaveHello** [comment]
@trusktr-goin Correct!

**Comment by PeterDaveHello** [comment]
Hi @trusktr-goin, so any updates here?

**Comment by trusktr** [comment]
Hi Peter! Let's go with `infamous.js`. Cheers! :smiley:

**Comment by PeterDaveHello** [comment]
@trusktr Thanks!

**Comment by PeterDaveHello** [comment]
@trusktr I found no `infamous.js` in the latest infamous npm package.

**Comment by trusktr** [comment]
@PeterDaveHello Oh, it's in `global.js`. Can the auto-update config convert global.js -> infamous.js?

**Comment by PeterDaveHello** [comment]
@trusktr Oh, can not, but i can manually do it at first import.

**Comment by trusktr** [comment]
Would it be automated after that?

**Comment by PeterDaveHello** [comment]
@trusktr nope, you need to change it's filename.

**Comment by trusktr** [comment]
@PeterDaveHello Thanks! That looks good. 😊🙂

**Comment by PeterDaveHello** [comment]
@trusktr You are welcome.

**Comment by trusktr** [comment]
Hello Peter, Infamous is up to `v8.0.1` now. How can we get it updated? Can it be automatic?

**Comment by PeterDaveHello** [comment]
@trusktr we have auto-update config here:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/infamous/package.json#L61-L69

seems the file/directory changed from v8.x, so that's the reason why it didn't been updated automatically.

**Comment by PeterDaveHello** [comment]
Opened an issue for it here: #8455

**Comment by trusktr** [comment]
Ah okay, gotcha. I'll keep that in mind for next time. I'm making some refactoring, so I'll be back...

**Comment by PeterDaveHello** [comment]
Okay, I tagged you in the new issue thread.
