### ISSUE TITLE
[Request] Add jQuery.scrollSpeed

### ISSUE THREAD

**Issue by DonMartin** [cdnjs/cdnjs#6951]
**Library name: jQuery.scrollSpeed** 
**Git repository url: https://github.com/nathco/jQuery.scrollSpeed**
**License(s):**
**Official homepage: http://code.nath.co/scrollSpeed**
**Wanna say something? Leave message here: 
Lightweight jQuery extension for modifying scrolling speed in modern web browsers. Supports vertical or horizontal scrolling direction, including user-defined easing.

Author: Nathan Rutzky**
#

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 
This lib has no tag and no issue tab to ask author for add git tag
Suggest to close

**Comment by sufuf3** [comment]
@sashberd Thanks.
I think we can add this lib as low priority. (because there is not a whole lot of stars.)
And maybe we can refer this link https://github.com/nathco/jQuery.scrollSpeed#release-notes and mapping to the commit logs.

Many thanks.

**Comment by sashberd** [comment]
@nathco Could you please add git tag to this library. Thanks

**Comment by sashberd** [comment]
@sufuf3 How about to use this [fork ](https://github.com/smb043/jQuery.scrollSpeed)instead of original one?

**Comment by sufuf3** [comment]
But this libraries doesn't have enough popularity (like more than 200 stars on GitHub or 800 downloads per month on npm). 
We can manually add https://github.com/nathco/jQuery.scrollSpeed#release-notes this lib.

How do you like?
Thanks.

**Comment by sashberd** [comment]
[Duplicate](https://github.com/cdnjs/cdnjs/issues/6621)
