### ISSUE TITLE
[Request] jquery.mb.bgndGallery

### ISSUE THREAD

**Issue by swpark8701** [cdnjs/cdnjs#6952]
**Library name:** jquery.mb.bgndGallery
**Git repository url:** https://github.com/pupunzi/jquery.mb.bgndGallery
**npm package url(optional):** 
**License(s):** GPL/MIT
**Official homepage:** http://pupunzi.com/#mb.components/mb.bgndGallery/bgndGallery.html
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@maruilian11 please add this lib, thanks.
