### ISSUE TITLE
[Request] Add Politespace 

### ISSUE THREAD

**Issue by MattSnowOregonGov** [cdnjs/cdnjs#6957]
**Library name: politespace** 
**Git repository url: https://github.com/filamentgroup/politespace**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://www.filamentgroup.com/lab/politespace.html**
**Wanna say something? Leave message here: This is a great solution for ADA-compliant masking, and is suggested by the 18F.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @Amomo

**Comment by MattSnowOregonGov** [comment]
@PeterDaveHello Any luck with this?

**Comment by PeterDaveHello** [comment]
@MattSnowOregonGov we'll add this TODAY :smile:

**Comment by PeterDaveHello** [comment]
hmmm ... need manually build, so can't not apply auto-update at the mean time.

**Comment by PeterDaveHello** [comment]
Added in 6b04816.
