### ISSUE TITLE
[Request] Add jquery.easypin

### ISSUE THREAD

**Issue by atayahmet** [cdnjs/cdnjs#6958]
**Library name: jQuery easypin** 
**Git repository url: https://github.com/atayahmet/jquery.easypin**
**npm package url(optional): https://www.npmjs.com/package/jquery.easypin** 
**License(s): MIT**
**Official homepage: http://atayahmet.github.io/jquery.easypin/**
**Wanna say something? Leave message here: Simply pinning objects on pictures**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @boogiewookie, thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can't not be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
