### ISSUE TITLE
[Request] OrnaJS

### ISSUE THREAD

**Issue by DimaPopov** [cdnjs/cdnjs#6959]
**Library name: *OrnaJS* 
**Git repository url:*https://github.com/OrnaOrg/OrnaJS
**npm package url(optional):*https://www.npmjs.com/package/orna* 
**License(s):*MIT*
**Official homepage:*http://ornaorg.github.io*
**Wanna say something? Leave message here:*OrnaJS - make extension for inline style, like : inheritance, event, abbreviation*

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by DimaPopov** [comment]
OrnaJS

**Comment by PeterDaveHello** [comment]
@DimaPopov would you please add tags for each versions? I can not recognize the versions easily, thanks.

**Comment by DimaPopov** [comment]
We added current release, thanks!

**Comment by PeterDaveHello** [comment]
@DimaPopov How many releases are there? Won't you like to add old versions?

**Comment by DimaPopov** [comment]
No, add only one, latest version

**Comment by PeterDaveHello** [comment]
@DimaPopov would you please remove the version number in the filename?

Reference:
https://github.com/cdnjs/cdnjs#conventions

**Comment by DimaPopov** [comment]
Ok

**Comment by PeterDaveHello** [comment]
@DimaPopov I need it in the tagged commit, thanks.

**Comment by DimaPopov** [comment]
it done!

**Comment by PeterDaveHello** [comment]
@Piicksarn Please add this lib.
