### ISSUE TITLE
[Request] Add knockout-jqAutocomplete

### ISSUE THREAD

**Issue by boogiewookie** [cdnjs/cdnjs#6960]
**Library name: knockout-jqAutocomplete** 
**Git repository url: https://github.com/rniemeyer/knockout-jqAutocomplete.git**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://github.com/rniemeyer/knockout-jqAutocomplete**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @boogiewookie, thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can't not be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
