### ISSUE TITLE
[Request] Add react-helmet

### ISSUE THREAD

**Issue by evanp** [cdnjs/cdnjs#6962]
**Library name: react-helmet *\* 
*_Git repository url: https://github.com/nfl/react-helmet *_
**npm package url(optional): https://www.npmjs.com/package/react-helmet** 
**License(s): MIT**
**Official homepage: NA**
**Wanna say something? Leave message here:**

This is a very useful React add-on for managing pages. Works well with React Router and other Reactive stuff.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@evanp would you please tell me what are the files I should add? Thanks.

**Comment by PeterDaveHello** [comment]
@Amomo please take a look what are the files we may need.

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 
We can host this lib only from 2.3.0 version. From this version that files inside src folder are supported by cdnjs
What do you think about this?

**Comment by sufuf3** [comment]
@sashberd Thank you for your suggestion.
But I think this lib is one of React component. (Back-end)
This library support `es` from npm.
But I'm not sure that this lib can be used in web front-end.

I'm sure that this lib from npm (under `es` folder) can't be minified via `web-minify-helper` because there are some errors as the followings:
```bash
Compressing Helmet.js ...
Parse error at Helmet.js:13,7
import React from "react";
       ^
ERROR: Unexpected token: name (React)
    at JS_Parse_Error.Object.defineProperty.get (eval at <anonymous> (/home/sufuf3149/web-minify-helper/node_$
odules/uglify-js/tools/node.js:21:1), <anonymous>:79:23)
    at fatal (/home/sufuf3149/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:268:52)
    at run (/home/sufuf3149/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:225:9)
    at Object.<anonymous> (/home/sufuf3149/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:155:5)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
```

Many thanks.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello So, should we close this issue?

**Comment by sufuf3** [comment]
I think this lib can't be used in web front-end.
Maybe we can close it.
Let's waiting for @PeterDaveHello decision.

@sashberd Many thanks. 👍

**Comment by PeterDaveHello** [comment]
Not sure what do you want me to answer, I tested the minifier with `react-helmet` the `es` folder and I didn't see any real problem here, those files are just minified successfully with `uglify-es` as below.

```
-rw-rw-r-- 1 peter peter 1.5K Aug 30 02:47 HelmetConstants.js
-rw-rw-r-- 1 peter peter 1.2K Nov 13 14:33 HelmetConstants.min.js
-rw-rw-r-- 1 peter peter 1.4K Nov 13 14:33 HelmetConstants.min.js.map
-rw-rw-r-- 1 peter peter  13K Aug 30 02:47 Helmet.js
-rw-rw-r-- 1 peter peter 5.7K Nov 13 14:33 Helmet.min.js
-rw-rw-r-- 1 peter peter 6.6K Nov 13 14:33 Helmet.min.js.map
-rw-rw-r-- 1 peter peter  21K Aug 30 02:47 HelmetUtils.js
-rw-rw-r-- 1 peter peter 9.9K Nov 13 14:33 HelmetUtils.min.js
-rw-rw-r-- 1 peter peter  13K Nov 13 14:33 HelmetUtils.min.js.map
```
