### ISSUE TITLE
[Request] Deputy CSS

### ISSUE THREAD

**Issue by npsantini** [cdnjs/cdnjs#6963]
Deputy CSS
https://github.com/ry4nolson/Deputy
http://ry4nolson.github.io/Deputy/

Please add this CSS liibrary. I use it on multiple projects and I know others do as well.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @npsantini , thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can't not be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
