### ISSUE TITLE
[Request] prettyCheckable

### ISSUE THREAD

**Issue by adrien-be** [cdnjs/cdnjs#6968]
**Library name:** prettyCheckable
**Git repository url:** https://github.com/arthurgouveia/prettyCheckable
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://arthurgouveia.com/prettyCheckable/
**Wanna say something? Leave message here:** This javascript library rocks, the only library doing a clean job at styling Checkboxes & Radio-buttons on many browser brands and versions. All the others are amateur work in comparison. Thx for adding it :)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by adrien-be** [comment]
Thanks for that. 

But an image is missing. And the plugin is unusable without it.

You can find that image under `https://github.com/arthurgouveia/prettyCheckable/tree/master/img/sprites-*.png`

**Comment by PeterDaveHello** [comment]
@adrien-be hope this can help.
* 21c589c prettyCheckable image issue workaround

**Comment by adrien-be** [comment]
Yeah, I think this does the job

**Comment by PeterDaveHello** [comment]
@adrien-be Nice
