### ISSUE TITLE
[Request] Add tota11y

### ISSUE THREAD

**Issue by mintao** [cdnjs/cdnjs#6970]
**Library name: tota11y** 
**Git repository url: https://github.com/Khan/tota11y**
**npm package url(optional): https://www.npmjs.com/package/tota11y** 
**License(s): MIT**
**Official homepage: http://khan.github.io/tota11y/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by jdan** [comment]
Thanks everyone :)

**Comment by PeterDaveHello** [comment]
:+1:

**Comment by PeterDaveHello** [comment]
@jdan not sure if you would like your "dynamo.js" been hosted on cdnjs, if so, pelase let me know, thanks.
