### ISSUE TITLE
[Request] Add Astro

### ISSUE THREAD

**Issue by Ting-y** [cdnjs/cdnjs#6971]
**Library name:** Astro
**Git repository url:** https://github.com/getastro/Astro
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://getastro.github.io/Astro/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @Ting-y , thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can not be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by Ting-y** [comment]
Thanks, and i will come back when my repos reach that limit :)

**Comment by PeterDaveHello** [comment]
Okay, thank you.
