### ISSUE TITLE
[request][new][author] Add jQuery TypeIt

### ISSUE THREAD

**Issue by alexmacarthur** [cdnjs/cdnjs#6972]
**Library name:** TypeIt: A jQuery Animated Typing Plugin
**Git repository url:** http://github.com/alexmacarthur/typeit
**npm package url(optional):** https://www.npmjs.com/package/typeit
**License(s):** GPL-2.0
**Official homepage:** http://macarthur.me/typeit
**Wanna say something? Leave message here:**

TypeIt is a lightweight jQuery animated typing plugin that types single or multiple strings (including HTML markup & entities) in the browser. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@alexmacarthur hey we can host this lib :+1:

**Comment by alexmacarthur** [comment]
@PeterDaveHello Definitely!

**Comment by PeterDaveHello** [comment]
@alexmacarthur all the new versions can be automatically added in future, would you please also add cdnjs in readme :smile: Thanks!

**Comment by PeterDaveHello** [comment]
@alexmacarthur is it possible to also mention cdnjs in the readme? Thanks.
