### ISSUE TITLE
[Request] bootstrap-languages

### ISSUE THREAD

**Issue by andryyy** [cdnjs/cdnjs#6975]
**Library name:** bootstrap-languages
**Git repository url:** https://github.com/usrz/bootstrap-languages
**License(s):** Apache License
**Official homepage:** http://usrz.github.io/bootstrap-languages/

:+1:

**Comment by PeterDaveHello** [comment]
Hi @andryyy , thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can't not be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
