### ISSUE TITLE
[Request] Add autotrack

### ISSUE THREAD

**Issue by TheSharpieOne** [cdnjs/cdnjs#6976]
**Library name:** autotrack
**Git repository url:** https://github.com/googleanalytics/autotrack
**npm package url(optional):** autotrack
**License(s):** [Apache License, Version 2.0](https://github.com/googleanalytics/autotrack/blob/master/LICENSE)
**Official homepage:** N/A
**Wanna say something? Leave message here:**

**Comment by philipwalton** [comment]
BTW, version 0.4.0 is the only publicly released version at this point, and the only version [tagged on Github](https://github.com/googleanalytics/autotrack/releases).
