### ISSUE TITLE
[Request] Add angular-read-more

### ISSUE THREAD

**Issue by ismarslomic** [cdnjs/cdnjs#6977]
**Library name:** angular-read-more 
**Git repository url:** https://github.com/ismarslomic/angular-read-more 
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/ismarslomic/angular-read-more
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @ismarslomic , thanks for your suggestion, however we need a higher popularity to host this lib, please re-submit this request when this lib has about 100 stars on GitHub, if I missed anything, maybe you think the lib is very popular but can't be proved on GitHub, please feel free to discuss with us. Thank you again.

Reference:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library

**Comment by ismarslomic** [comment]
Hi @PeterDaveHello, according to https://cdnjs.com/about, CDNJS is hosting all libraries, not only those most popular like Google CDN and Microsoft CDN.

"Everyone loves the Google CDN right? Even Microsoft runs their own CDN. 
The problem is, they only host the most popular libraries. 
We host it all - JavaScript, CSS, SWF, images, etc!"

Im confused what is actually correct here. Please elaborate.

**Comment by PeterDaveHello** [comment]
Hi @ismarslomic , sorry about that, due the the very high workload and the resource utilization, in fact we only the libraries with notable popularity, the words on the website was out-dated, and just been updated in https://github.com/cdnjs/new-website/commit/47a7f684839bacf8ac2883ec26b0397d40132b11. As you are the author, and the lib looks having good structure for our auto-updater, I wonder if you would like to send a pull request by yourself? I'll do my best to review it ASAP, many thanks!

**Comment by ismarslomic** [comment]
Thanks for quick reply, @PeterDaveHello! No problem, I can send PR.

**Comment by PeterDaveHello** [comment]
@ismarslomic Thank you.

**Comment by PeterDaveHello** [comment]
@ismarslomic BTW you may need [sparse-checkout](https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md) to help you speed up the process, and please don't forget to test your commit via `npm test`, thanks!

**Comment by ismarslomic** [comment]
Thanks, nice to know! :) :+1:

**Comment by PeterDaveHello** [comment]
Hi @ismarslomic, is there any updates? The good news is that you can add the lib by just adding its package.json with out specified version! See: #7149

**Comment by PeterDaveHello** [comment]
Close due to no response.
