### ISSUE TITLE
[Request] Stellar Base

### ISSUE THREAD

**Issue by cyberomin** [cdnjs/cdnjs#6979]
**Library name:** Stellar JS base 
**Git repository url:** https://github.com/stellar/js-stellar-base
**npm package url(optional):** https://www.npmjs.com/package/stellar-base
**License(s):** Apache-2.0
**Official homepage:** https://stellar.github.io/js-stellar-base/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by cyberomin** [comment]
Thanks @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@cyberomin no problem
