### ISSUE TITLE
[Request] cbpAnimatedHeader.js

### ISSUE THREAD

**Issue by mcallejas1** [cdnjs/cdnjs#6983]
**Library name:** Animated Header
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@mcallejas1 please provide git repo url or npm package url, thanks.

**Comment by maruilian11** [comment]
@mcallejas1 this issue will be closed **in 7 days** due to no response. thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Close due to no response.
