### ISSUE TITLE
[Request] easyModal.js

### ISSUE THREAD

**Issue by rjpedrosa** [cdnjs/cdnjs#6985]
**Library name: easyModal.js
*_Git repository url: http://flaviusmatis.github.io/easyModal.js/
*_npm package url(optional):** 
**License(s): https://github.com/flaviusmatis/easyModal.js/blob/master/LICENSE.txt
*_Official homepage: http://flaviusmatis.github.io/easyModal.js/
*_Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
As there is no any response from https://github.com/flaviusmatis/easyModal.js/issues/36, we can't add this right now, feel free to ping me to reopen it when it's available or submit other requests on familiar libraries, thanks.
