### ISSUE TITLE
[Request] Add vue-async-data 

### ISSUE THREAD

**Issue by Gomah** [cdnjs/cdnjs#6993]
**Library name:** vue-async-data
**Git repository url:** https://github.com/vuejs/vue-async-data
**npm package url(optional):** https://www.npmjs.com/package/vue-async-data
**License(s):** MIT
**Official homepage:** http://vuejs.org

Thanks :smile:

**Comment by PeterDaveHello** [comment]
@maruilian11 What's the reason why for https://github.com/vuejs/vue-async-data/issues/13 ? We can use npm auto-update.

**Comment by maruilian11** [comment]
sorry, not notice that.
