### ISSUE TITLE
angular-resource-min-js

### ISSUE THREAD

**Issue by mmhgarcia** [cdnjs/cdnjs#6995]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@mmhgarcia please provide the git repo url or npm package url, thanks.
