### ISSUE TITLE
[Request] Add vuex

### ISSUE THREAD

**Issue by Gomah** [cdnjs/cdnjs#6997]
**Library name:** vuex
**Git repository url:** https://github.com/vuejs/vuex
**npm package url(optional):**  https://www.npmjs.com/package/vuex
**License(s):** MIT
**Official homepage:** http://vuejs.org

Thanks :smile:

**Comment by PeterDaveHello** [comment]
@Gomah What are the files should be hosted on the CDN?

**Comment by Gomah** [comment]
@PeterDaveHello Apologize, there's no 'dist' build extension yet.

**Comment by PeterDaveHello** [comment]
@Gomah It's okay, will there be one dist soon?

**Comment by Gomah** [comment]
I hope so, I will re-open as soon as it's released :+1:

**Comment by PeterDaveHello** [comment]
@Gomah Okay, thanks.

**Comment by PeterDaveHello** [comment]
@Gomah would you like to open an issue at https://github.com/vuejs/vuex/ ?

**Comment by Gomah** [comment]
Sure, [https://github.com/vuejs/vuex/issues/59](https://github.com/vuejs/vuex/issues/59)

**Comment by PeterDaveHello** [comment]
@Gomah Thanks.

**Comment by Gomah** [comment]
@PeterDaveHello, done: https://github.com/vuejs/vuex/tree/master/dist

**Comment by PeterDaveHello** [comment]
Nice :+1:
