### ISSUE TITLE
[Request] Add eurocookie-js

### ISSUE THREAD

**Issue by AdrianArroyoCalle** [cdnjs/cdnjs#6999]
**Library name:** eurocookie-js
**Git repository url:** http://github.com/AdrianArroyoCalle/eurocookie-js
**npm package url(optional):** https://www.npmjs.com/package/eurocookie-js
**License(s):** Apache 2
**Official homepage:** http://github.com/AdrianArroyoCalle/eurocookie-js
**Wanna say something? Leave message here:**

**Comment by maruilian11** [comment]
@AdrianArroyoCalle  sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by AdrianArroyoCalle** [comment]
Ok, sorry for the inconvenience. I'll try to gain popularity first

**Comment by maruilian11** [comment]
thank you!
