### ISSUE TITLE
[Request] Add pure.js

### ISSUE THREAD

**Issue by avradul** [cdnjs/cdnjs#7000]
**Library name:** pure.js
**Git repository url:** https://github.com/pure/pure.git
**npm package url(optional):** 
**License(s):** no
**Official homepage:** http://beebole.com/pure/

**Comment by PeterDaveHello** [comment]
@avradul what are the files should be added? Thanks.

**Comment by avradul** [comment]
https://github.com/pure/pure/blob/master/libs/pure.js
https://github.com/pure/pure/blob/master/libs/pure.min.js

Thanks.

**Comment by PeterDaveHello** [comment]
Okay I'll take a look at it, thanks.
