### ISSUE TITLE
[Request] Add latest version of footable

### ISSUE THREAD

**Issue by boldmovecreative** [cdnjs/cdnjs#7003]
**Library name:** FooTable
**Git repository url:** https://github.com/fooplugins/FooTable.git
**License(s):** Unsure
**Official homepage:** http://fooplugins.github.io/FooTable/

**Comment by maruilian11** [comment]
FooTable has been updated to the latest version.

**Comment by PeterDaveHello** [comment]
Please mention the reference commit before you close next time.

**Comment by maruilian11** [comment]
ok.
