### ISSUE TITLE
[Request] Add foonav

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7006]
**Library name:** foonav
**Git repository url:** https://github.com/fooplugins/foonav

**Comment by PeterDaveHello** [comment]
@kennynaoh note that you need to use git auto-update here, not npm.

**Comment by kennynaoh** [comment]
there is a font directory and some files like foonav.min.js... in the dist directory, and there are some files in font directory like foonav.svg...
so the "files" in autoupdate config will be
"files":[
    "foonav.min.js",
    "foonav.svg"
]
right?
thanks
