### ISSUE TITLE
[Request] Add snap.svg.zpd.js 

### ISSUE THREAD

**Issue by wojciecheu** [cdnjs/cdnjs#7007]
snap.svg.zpd

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
https://github.com/huei90/snap.svg.zpd

**Comment by huei90** [comment]
Tq

**Comment by maruilian11** [comment]
@huei90 :+1:
