### ISSUE TITLE
[Request] css3-animate-it

### ISSUE THREAD

**Issue by leonirlopes** [cdnjs/cdnjs#7009]
**Library name:** css3-animate-it
**Git repository url:** https://github.com/Jack-McCourt/css3-animate-it
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://jackonthe.net/css3animateit
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@leonirlopes sorry, but this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
we suggest you open a issue again when the repo has notable popularity. 
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.
