### ISSUE TITLE
[Request] Add angular-confirm

### ISSUE THREAD

**Issue by deepakagrawal121** [cdnjs/cdnjs#7021]
angular-confirm
https://github.com/Schlogen/angular-confirm
https://github.com/Schlogen/angular-confirm/blob/master/LICENSE
http://schlogen.github.io/angular-confirm/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Looks okay to add.

**Comment by maruilian11** [comment]
ok.
