### ISSUE TITLE
dust-core-2.2.0.js

### ISSUE THREAD

**Issue by uzziellite** [cdnjs/cdnjs#7030]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
This one https://cdnjs.com/libraries/dustjs-linkedin/2.2.0 ?
