### ISSUE TITLE
[Request] Fallings

### ISSUE THREAD

**Issue by ikibiki** [cdnjs/cdnjs#7031]
**Library name: Fallings** 
**Git repository url: https://github.com/fuhton/fallings**
**npm package url(optional):** 
**License(s): **
**Official homepage: http://fuhton.github.io/fallings/**
**Wanna say something? Leave message here: Simple parallax engine**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@ikibiki ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your suggestion. :-)
**`This issue will be closed if there is no any response in next 7 day.`**

Piicksarn

**Comment by ikibiki** [comment]
okay. thanks! :+1:
