### ISSUE TITLE
[Request] Add layer

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7034]
**Library name:** layer
**Git repository url:** https://github.com/sentsin/layer
**Official homepage:** http://layer.layui.com/

**Comment by maruilian11** [comment]
@PeterDaveHello there is no issue page that i can open an issue to ask the author if he can add tags for each version. should i write an e-mail?

**Comment by PeterDaveHello** [comment]
Why not?

**Comment by maruilian11** [comment]
sent

**Comment by maruilian11** [comment]
@PeterDaveHello his email address(xu@sentsin.com) seems unavailable.
![image](https://cloud.githubusercontent.com/assets/10260008/14822728/4f858942-0c02-11e6-8655-b62e9140dd0e.png)

**Comment by PeterDaveHello** [comment]
Try to manually add:
http://res.layui.com/download/layer-v2.2.zip

**Comment by maruilian11** [comment]
i can't open the website, there is a 403 error.

**Comment by PeterDaveHello** [comment]
I have no problem with the website, you should try it again.

**Comment by maruilian11** [comment]
![image](https://cloud.githubusercontent.com/assets/10260008/15240559/2c8a4fc2-191d-11e6-9278-c6213c1ace1c.png)
still fail.

**Comment by PeterDaveHello** [comment]
Have you tried  http://layer.layui.com/?

**Comment by maruilian11** [comment]
i can view this website, but i only find v2.2 and v1.8.5 packages.

**Comment by PeterDaveHello** [comment]
So what's the problem? You can find it but you say it failed. You still failed to download from website?

**Comment by maruilian11** [comment]
hmmm... the version updated to v2.3, i can't remember if i could download v2.2.
i tried, i can download package by clicking the button, but i can't download it from url, even use `wget`.

**Comment by PeterDaveHello** [comment]
You can download package by clicking the button, so there is no any problem.

**Comment by maruilian11** [comment]
![image](https://cloud.githubusercontent.com/assets/10260008/15393917/7671ef52-1e02-11e6-9afd-5d51a4ce4d58.png)

**Comment by PeterDaveHello** [comment]
So why don't you just download package by clicking the button, is your button broken?

**Comment by maruilian11** [comment]
hi @sentsin,
we want to add each released version of your lib (layer) to cdnjs, could you please tell me where can i download all released version?
thank you very much!

**Comment by PeterDaveHello** [comment]
```
$ wget --referer=http://layer.layui.com/ http://res.layui.com/download/layer-v2.1.zip
--2016-05-19 20:52:23--  http://res.layui.com/download/layer-v2.1.zip
Resolving res.layui.com (res.layui.com)... 120.26.100.45
Connecting to res.layui.com (res.layui.com)|120.26.100.45|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 76793 (75K) [application/x-zip-compressed]
Saving to: ‘layer-v2.1.zip’

layer-v2.1.zip                    100%[============================================================>]  74.99K   125KB/s    in 0.6s

2016-05-19 20:52:24 (125 KB/s) - ‘layer-v2.1.zip’ saved [76793/76793]

$ wget --referer=http://layer.layui.com/ http://res.layui.com/download/layer-v2.2.zip
--2016-05-19 20:52:38--  http://res.layui.com/download/layer-v2.2.zip
Resolving res.layui.com (res.layui.com)... 120.26.100.45
Connecting to res.layui.com (res.layui.com)|120.26.100.45|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 77013 (75K) [application/x-zip-compressed]
Saving to: ‘layer-v2.2.zip’

layer-v2.2.zip                    100%[============================================================>]  75.21K   142KB/s    in 0.5s

2016-05-19 20:52:39 (142 KB/s) - ‘layer-v2.2.zip’ saved [77013/77013]

$ wget --referer=http://layer.layui.com/ http://res.layui.com/download/layer-v2.3.zip
--2016-05-19 20:52:46--  http://res.layui.com/download/layer-v2.3.zip
Resolving res.layui.com (res.layui.com)... 120.26.100.45
Connecting to res.layui.com (res.layui.com)|120.26.100.45|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75874 (74K) [application/x-zip-compressed]
Saving to: ‘layer-v2.3.zip’

layer-v2.3.zip                    100%[============================================================>]  74.10K   105KB/s    in 0.7s

2016-05-19 20:52:47 (105 KB/s) - ‘layer-v2.3.zip’ saved [75874/75874]

```

**Comment by maruilian11** [comment]
@PeterDaveHello ok, i got it, since i need to add it manually and i can't find version list, how many versions do i need to add?

**Comment by PeterDaveHello** [comment]
@maruilian11 Isn't there a list? 
https://github.com/sentsin/layer/blob/2.x/CHANGELOG.md

**Comment by maruilian11** [comment]
hmmm... i can't download 1.9.1~2.0, can i just add 1.8.5, 2.1, 2.2 and 2.3?

**Comment by PeterDaveHello** [comment]
@maruilian11 fine

**Comment by sentsin** [comment]
既然是台灣朋友，我直接用中文吧。這個地址（http://res.layui.com/download/layer-v2.2.zip）在外部是無法訪問的，因為我做了請求的限制，只能來自站內的Referer才能訪問，對此表示抱歉了。
你們可以用GitHub的下載鏈接：https://github.com/sentsin/layer/archive/2.x.zip。

**Comment by PeterDaveHello** [comment]
@sentsin thanks, it's not a real problem since we can use `wget` with `--referer=http://layer.layui.com/ `.

**Comment by sentsin** [comment]
ok, wandful!
