### ISSUE TITLE
[Request] Add deep-diff

### ISSUE THREAD

**Issue by Vishalashah** [cdnjs/cdnjs#7038]
**Library name:** Deep-Diff
**Git repository url:** https://github.com/flitbit/diff
**npm package url(optional):** https://www.npmjs.com/package/deep-diff
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
There is version numbers in release files, that's a problem for auto-updater, @flitbit is it possible to not use a version number in the distribution file so that we can apply auto-update on this lib? Thanks.
