### ISSUE TITLE
[Question] Does auto-update needs the build files to be versioned ?

### ISSUE THREAD

**Issue by lorem--ipsum** [cdnjs/cdnjs#7048]
I don't want to include the build files on my repo because it makes the PR diffs so messy...

**Comment by PeterDaveHello** [comment]
Which lib?

**Comment by lorem--ipsum** [comment]
https://github.com/n3-charts/line-chart

**Comment by PeterDaveHello** [comment]
@lorem--ipsum we are using npm auto-update, not git update here, see https://cdnjs.com/libraries/line-chart, so you don't need to put dist files in git repo, just in npm package :smile:

**Comment by lorem--ipsum** [comment]
Sooo nothing to do ? (thanks for adding the repo btw)

**Comment by PeterDaveHello** [comment]
yep, nothing to do, just make sure npm package is good

**Comment by lorem--ipsum** [comment]
Holy safari, that's terrific ! Thanks !
