### ISSUE TITLE
Bug: Library not updating: SmoothScroll [author]

### ISSUE THREAD

**Issue by galambalazs** [cdnjs/cdnjs#7049]
CDNJS shows v1.4.1
https://cdnjs.com/libraries/smoothscroll

But my library is already at v1.4.4
https://github.com/galambalazs/smoothscroll-for-websites

**Comment by galambalazs** [comment]
cc @PeterDaveHello @maruilian11

**Comment by PeterDaveHello** [comment]
@galambalazs you forgot to update the npm package, we use it as upstream.

**Comment by galambalazs** [comment]
Ah gotcha.

I think it was previously not available on npm sonI guess the way cdnjs works is that it updates from npm if available or directly from github if it isn't?

**Comment by PeterDaveHello** [comment]
@galambalazs hmmm ... it's static config in the package.json in cdnjs repo

**Comment by galambalazs** [comment]
Cool. Thanks for explaining.

**Comment by PeterDaveHello** [comment]
@galambalazs no probms, so are you going to release new versions on npm now?

**Comment by galambalazs** [comment]
Sure. ;)

**Comment by PeterDaveHello** [comment]
@galambalazs 🔨 1 new commits to cdnjs:master:

a0b74f7: add smoothscroll v1.4.4 by PeterBot

**Comment by galambalazs** [comment]
:+1:
