### ISSUE TITLE
[Request] BigVideo.js

### ISSUE THREAD

**Issue by simplylouis** [cdnjs/cdnjs#7050]
**Library name: BigVideo.js
**Git repository url: https://github.com/dfcb/BigVideo.js
**npm package url(optional):** 
**License(s):**
**Official homepage: http://dfcb.github.io/BigVideo.js/
**Wanna say something? Leave message here:**
I am not the owner. But I want to use the cdn service for this easy lib. Please add if you can 8). Thanks.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
close per #7149
