### ISSUE TITLE
[Request] jschardet

### ISSUE THREAD

**Issue by KOLANICH** [cdnjs/cdnjs#7056]
**Library name:jschardet** 
**Git repository url:https://github.com/aadsm/jschardet.git**
**npm package url(optional):https://raw.githubusercontent.com/aadsm/jschardet/master/package.json** 
**License(s):GNU LGPL v2.1**
**Official homepage:https://github.com/aadsm/jschardet**

**Comment by PeterDaveHello** [comment]
@KOLANICH what are the files need to be hosted on cdn?

**Comment by KOLANICH** [comment]
It is needed to be combined into a single file and then hosted. I wonder is there any js package manager which does it?

**Comment by PeterDaveHello** [comment]
We do not support using any package manager or task manager to build in the auto-updater, it's too complex, which means we need pre-built files, not sure if the author will like to have it.

**Comment by PeterDaveHello** [comment]
@Amomo p

**Comment by PeterDaveHello** [comment]
@KOLANICH I can manually build and add the latest version for this lib.

**Comment by PeterDaveHello** [comment]
hmmm ... seems no official build instructions there, I'll ask its author.

**Comment by KOLANICH** [comment]
>I can manually build and add the latest version for this lib.
Manual build is not a solution for the service meant to provide the latest versions of scripts.

**Comment by PeterDaveHello** [comment]
@aadsm would you like to give us your comment here? If you would like to have it on cdn, thanks!

**Comment by aadsm** [comment]
Hey, sure. Let me add a script that does this for me, I can just use browserify. Most people use it on node, so never felt the need for a single file.
Is it enough to have a single file in the repository and you'll add that path to your scripts?

**Comment by PeterDaveHello** [comment]
> Is it enough to have a single file in the repository and you'll add that path to your scripts?

:+1:
