### ISSUE TITLE
[Request] Add nvd3 v1.8.2

### ISSUE THREAD

**Issue by sbessah** [cdnjs/cdnjs#7058]
**Library name:nvd3 v1.8.2
**Git repository url:https://github.com/novus/nvd3
**npm package url(optional):** 
**License(s):https://github.com/novus/nvd3/blob/master/LICENSE.md
**Official homepage:http://nvd3.org/
**Wanna say something? Leave message here:
Hi,
Can you add 1.8.2 version of nvd3 library please?

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
* cecab8b add nvd3 v1.8.2
