### ISSUE TITLE
[Request] Add vega-embed

### ISSUE THREAD

**Issue by johanneskoester** [cdnjs/cdnjs#7062]
**Library name:** vega-embed
**Git repository url:** https://github.com/vega/vega-embed
**npm package url(optional):** https://www.npmjs.com/package/vega-embed
**License(s):** MIT
**Official homepage:** https://github.com/vega/vega-embed

**Comment by maruilian11** [comment]
@johanneskoester sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by johanneskoester** [comment]
Ok, thanks!

**Comment by maruilian11** [comment]
we will be glad to add this lib when it has enough popularity :smile:
