### ISSUE TITLE
[Request] Add vega-lite

### ISSUE THREAD

**Issue by johanneskoester** [cdnjs/cdnjs#7063]
**Library name:** vega-lite
**Git repository url:** https://github.com/vega/vega-lite
**npm package url(optional):** https://www.npmjs.com/package/vega-lite
**License(s):** MIT
**Official homepage:** http://vega.github.io/vega-lite/

**Comment by maruilian11** [comment]
@johanneskoester could you please tell us what files should be hosted? thank you!

**Comment by PeterDaveHello** [comment]
No need to host this anymore?

**Comment by johanneskoester** [comment]
I found another solution, but I still think this is a highly valuable library.
The relevant files would be //vega.github.io/vega-lite/vega-lite.js and //vega.github.io/vega-editor/vendor/vega-embed.js.

**Comment by PeterDaveHello** [comment]
@johanneskoester hmmmm... I will take a look at it, thanks.
