### ISSUE TITLE
[Website] «Something broke!» when trying to access any library page

### ISSUE THREAD

**Issue by soulchainer** [cdnjs/cdnjs#7064]
Just right now, when you try to access any **cdnjs** page about a library (https://cdnjs.com/libraries/anyLibraryName), the site only shows the error

> Something broke!

So, I guess that something is broken, right? (xD).
Just in case anyone hasn't notice it yet.

**Comment by PeterDaveHello** [comment]
Thanks @soulchainer, my fault.
