### ISSUE TITLE
[Request] Leaflet.ZoomBox

### ISSUE THREAD

**Issue by maerco** [cdnjs/cdnjs#7076]
**Library name:** 
Leaflet.ZoomBox
**Git repository url:**
https://github.com/consbio/Leaflet.ZoomBox
**npm package url(optional):** 

**License(s):**
https://github.com/consbio/Leaflet.ZoomBox/blob/master/LICENSE
**Official homepage:**
https://github.com/consbio/Leaflet.ZoomBox

**Comment by maruilian11** [comment]
@maerco sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·
we suggest you open a issue again when the repo has notable popularity.·

we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

**Comment by maruilian11** [comment]
close due to no response.
