### ISSUE TITLE
[Request] Add the Montserrat, the Roboto and the Ubuntu font

### ISSUE THREAD

**Issue by ghost** [cdnjs/cdnjs#7081]
Could you please host the [Montserrat](https://www.google.com/fonts/specimen/Montserrat), the [Roboto](https://www.google.com/fonts/specimen/Roboto) and the [Ubuntu](https://www.google.com/fonts/specimen/Ubuntu) font?

**Comment by sashberd** [comment]
@PeterDaveHello How to add this fonts. How is package json should look? Can you provide me an example?

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
