### ISSUE TITLE
theme-jsoneditor.js 404 error

### ISSUE THREAD

**Issue by jimmibond** [cdnjs/cdnjs#7085]
getting 404 error while retriving this file http://cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/theme-jsoneditor.js

**Comment by PeterDaveHello** [comment]
@jimmibond Yes there is no that file, see https://cdnjs.com/libraries/ace/1.1.3

**Comment by jimmibond** [comment]
do i need to change in code, or it's missing in cdn?

**Comment by PeterDaveHello** [comment]
There is no that file, see: https://github.com/ajaxorg/ace-builds/tree/v1.1.3/src-min
