### ISSUE TITLE
[Request] Add turbolinks 5.0.0.beta2

### ISSUE THREAD

**Issue by claudiob** [cdnjs/cdnjs#7088]
**Library name: Turbolinks (new repo)
**Git repository url: https://github.com/turbolinks/turbolinks
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/turbolinks/turbolinks
**Wanna say something? Leave message here:**

There is a new repo for turbolinks with version 5.0.0.beta2, whereas cdnjs is now hosting version 1.x.

The actual JS file is here: https://github.com/turbolinks/turbolinks/blob/v5.0.0.beta2/dist/turbolinks.js

**Comment by PeterDaveHello** [comment]
Any detail?

**Comment by claudiob** [comment]
Thanks!! :+1: :clap: :tada:

**Comment by PeterDaveHello** [comment]
You're welcome.
