### ISSUE TITLE
[Request] Add flot-spline

### ISSUE THREAD

**Issue by johnpozy** [cdnjs/cdnjs#7090]
**Library name: flot-spline** 
**Git repository url: https://github.com/johnpozy/flot-spline**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: https://github.com/johnpozy/flot-spline**
**Wanna say something? Leave message here:**

**Comment by PeterDaveHello** [comment]
@johnpozy I'm sorry but we need a higher and notable popularity to add a library, please read our readme document first, thank you.

**Comment by beruic** [comment]
Is it enough that I want to use it, and that it is bundled in [this bootstrap theme](https://wrapbootstrap.com/theme/inspinia-responsive-admin-theme-WB0R5L90S) and available on bower? :)

**Comment by PeterDaveHello** [comment]
There is not  usage stats on bower package, if there is some other methods to prove its popularity, we'll be happy to add it, otherwise, we may not add this.

**Comment by maruilian11** [comment]
hi, @johnpozy 
this issue will be closed if there is on response in next 7 days, we'll be glad to add the lib when it has enough popularity :smile:

**Comment by johnpozy** [comment]
@maruilian11 feel free to close it if this script don't have enough popularity :smile:

**Comment by PeterDaveHello** [comment]
Okay let's close this, @johnpozy I'll respectfully suggest you to make a homepage and demo page for your lib, and publish on npm, it'll help you spread your library!
