### ISSUE TITLE
[Request] Add _react-localstorage

### ISSUE THREAD

**Issue by acidin** [cdnjs/cdnjs#7093]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail?

**Comment by acidin** [comment]
https://github.com/STRML/react-localstorage
Please, add this library.

**Comment by PeterDaveHello** [comment]
What's the files should be hosted on CDNJS?

**Comment by acidin** [comment]
https://github.com/STRML/react-localstorage/blob/master/react-localstorage.js
