### ISSUE TITLE
[Request] Add Autobahn|JS

### ISSUE THREAD

**Issue by TRManderson** [cdnjs/cdnjs#7102]
**Library name:** Autobahn|JS
**Git repository url:** https://github.com/crossbario/autobahn-js
**npm package url(optional):** https://www.npmjs.com/package/autobahn
**License(s):** custom/permissive
**Official homepage:** https://autobahn.ws

**Comment by PeterDaveHello** [comment]
@TRManderson would you please tell me what are the files need to be hosted on CDN? Thanks.

**Comment by PeterDaveHello** [comment]
Ping @TRManderson

**Comment by Jichao** [comment]
@PeterDaveHello 
There is only one js file that need tto hosted on the CDN.
the minized and zipped version: https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz
the minized version:
https://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.js
according to the offical website: http://autobahn.ws/js/gettingstarted.html

**Comment by PeterDaveHello** [comment]
@Jichao Thanks

**Comment by Jichao** [comment]
Ping @kennynaoh @PeterDaveHello any news here?

**Comment by PeterDaveHello** [comment]
@Jichao sorry for the late update, we'll start to work on this ASAP.

**Comment by kennynaoh** [comment]
Hello @Jichao ,
I found that the file you offered on the website https://autobahn.s3.amazonaws.com/autobahnjs/0.10.1/autobahn.js is different from the git repo and npm. Could you please publish the minified and development version you offered above to git repo or npm. Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh is @Jichao the author? Have no idea what are you talking about ...

**Comment by kennynaoh** [comment]
OK, I will discuss with author.

**Comment by Jichao** [comment]
Hi @kennynaoh, I'm not the author.

**Comment by oberstet** [comment]
The latest AutobahnJS version is hosted (for dev purposes) here

```
Link: 	
https://s3-eu-west-1.amazonaws.com/autobahn/autobahnjs/latest/autobahn.min.jgz
Size: 	61842
Last Modified: 	Wed Nov 16 15:18:47 GMT+100 2016
ETag: 	fa6bcf33a30e7261eba65b8eabaa85c5
``` 

which is linked to a versioned release

```
Link: 	
https://s3-eu-west-1.amazonaws.com/autobahn/autobahnjs/0.11.1/autobahn.min.jgz
Size: 	61842
Last Modified: 	Wed Nov 16 15:18:55 GMT+100 2016
ETag: 	fa6bcf33a30e7261eba65b8eabaa85c5
```

The built versions are also available from GitHub, eg https://github.com/crossbario/autobahn-js-built/tree/v0.11.1

**Comment by PeterDaveHello** [comment]
@kennynaoh any updates now?

**Comment by kennynaoh** [comment]
Thanks @oberstet , I think it's better to add the files from the git repo you mention above, right?

**Comment by thanhngvpt** [comment]
What about it? I've tried to lookup on cdnjs.org site but Its  seem not there.

**Comment by oberstet** [comment]
On a sidenote, using CDNs exposes you to security risks, which we (Crossbar.io project) will take no responsibility for.

**Comment by PeterDaveHello** [comment]
@oberstet I don't think this is really an issue here and in fact we can provide better security for most cases as not all the developers know about best implement, including https, DNSSEC, SRI, etc. This issue is just like: using the Internet will have security and privacy issues :)

**Comment by oberstet** [comment]
No, I disagree: you cannot provide "upstream trust", as you can fiddle with the distributed code as you wish, while the JS runs in the security context of the users loading page. Whereas if a developer clones our upstream built repo and self-hosts, there is no such issue.

**Comment by PeterDaveHello** [comment]
@oberstet no offense but this is totally a [FUD](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt), I'll respectfully suggest you to take a look at what SRI is - https://www.w3.org/TR/SRI, https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity, and then tell me how can we and how should we fiddle the codes if SRI is enabled? If you wanna keep the security high, you can even provide its SRI hashes as an official developer, which is much more confidence, this will help improve the security, FUD won't.

**Comment by oberstet** [comment]
1. SRI would do away with security concerns, but http://caniuse.com/#feat=subresource-integrity
2. SRI does NOT help with privacy (you, as a CDN, can track the clients loading the resource)

So no FUD.

Anyway: I cannot stop you from distributing Autobahn on your CDN, but I can discourage our users from using any CDN, and encourage self-hosting.

**Comment by PeterDaveHello** [comment]
@oberstet I agree that SRI is not that widely supported yet but this will be improved in future, as modern Chrome + Firefox have more than 50% market sharing, I won't worry about this too much, especially this is already much more secure then even self-hosting in most case (I don't know who is calculating SRI by his/her own on his hosting yet), the hosting issue I can say that most of CDN providers' implement is much more reliable than many individual developers, so no worry please.

About the privacy, I totally agree that CDN can track that, AFAIK, we  don't and we won't violate any users' privacy, beside this, I more care about if the developers enabled https, SRI, DNSSEC on their side, if not, not only MITM attacks can easily be deployed to cause security issues, without good https implement, the ISP, the free wifi AP, etc, can do the tracking job much more easier than anyone, which will cause the real privacy issue. For the user side, I'll suggest to use security extensions on their web browser to help privacy control, if this is not acceptable, then they should be more worried about the other websites that have motivation to tracking them first, at least CDNJS doesn't and won't bid the service reputation with users' privacy.

If you do have concerns about security and privacy, maybe building your own CDN for the users could also be an option :)
