### ISSUE TITLE
[Request] Add  jquery.keyboard.js

### ISSUE THREAD

**Issue by TWUsers** [cdnjs/cdnjs#7106]
**Library name:**jquery.keyboard.js
**Git repository url:**https://github.com/TechnoWolof/js/blob/master/jquery.keyboard.js
**npm package url(optional):** 
**License(s):**MIT License
**Official homepage:**
this is an adaptation

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
@TWUsers sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our README.md for detail. We suggest you open a issue again when the repo has notable popularity. Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days.
If there is any other possibility to add this lib, we may discuss to add it.

**Comment by dannyxx001** [comment]
@PeterDaveHello please help me check again, thanks.

**Comment by PeterDaveHello** [comment]
Yeah, we need higher popularity on this lib.

**Comment by PeterDaveHello** [comment]
@dannyxx001 leave message to talk about the reason why to close it, do not directly do this.

**Comment by PeterDaveHello** [comment]
Now I'll close this due to no response from issuer.
