### ISSUE TITLE
[Request] jsdiff

### ISSUE THREAD

**Issue by paragonie-scott** [cdnjs/cdnjs#7127]
https://github.com/kpdecker/jsdiff

**Comment by sbrl** [comment]
**Library name:** jsdiff
**Git repository url:** https://github.com/kpdecker/jsdiff
**npm package url(optional):** https://www.npmjs.com/package/diff
**License(s):** BSD
**Official homepage:** http://kpdecker.github.io/jsdiff/
**Wanna say something? Leave message here:** This seems to be the best js-based unified diff utility out there at the moment that I can find. It would be seriously handy if cdnjs hosted this, as all the other CDNs have a terribly outdated copy of this library :(
