### ISSUE TITLE
[Request] Spellbook

### ISSUE THREAD

**Issue by warlock** [cdnjs/cdnjs#7136]
**Library name: Spellbook** 
**Git repository url: https://github.com/warlock/spellbook.git**
**npm package url(optional): https://www.npmjs.com/package/spellbook** 
**License(s): MIT**
**Official homepage: http://www.spellbook.io**
**Wanna say something? Leave message here: Library for extend the javascript habilities.**

**Comment by warlock** [comment]
Hi Peter. This is a minified file. Thank you.
https://github.com/warlock/spellbook/tree/minified

**Comment by PeterDaveHello** [comment]
Thanks @warlock, I'll take a look at it, but I have to tell you the that you may need to wait for 5 ~ 10 days because there are too many adding requests that I can not handle, it'll be good if you can send a PR.

**Comment by warlock** [comment]
Ok. No problem. Thank you.

**Comment by PeterDaveHello** [comment]
Oops, used a wrong ID to commit ... nevermind, I'm not lacking of commits, this lib will be available in 30 mins. @warlock maybe you can add the CDN info in readme :smile:

**Comment by warlock** [comment]
Perfect! Thank you. Readme updated!  :+1:

**Comment by PeterDaveHello** [comment]
@warlock Nic3
