### ISSUE TITLE
[Request] Colorify.js

### ISSUE THREAD

**Issue by KasperAndersson** [cdnjs/cdnjs#7147]
**Library name:** Colorify.js
**Git repository url:** https://github.com/LukyVj/Colorify.js
**npm package url(optional):** Not on NPM yet
**License(s):** This project is licensed under ISC
**Official homepage:** http://colorify.rocks/

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@KasperAndersson What are the files need to be hosted on CDNJS?

**Comment by PeterDaveHello** [comment]
cc @LukyVj

**Comment by LukyVj** [comment]
Hi, thanks for your support! 
The main js file : https://github.com/LukyVj/Colorify.js/blob/master/scripts/colorify.min.js
The main css file : https://github.com/LukyVj/Colorify.js/blob/master/styles/colorify.css

**Comment by LukyVj** [comment]
@PeterDaveHello

**Comment by PeterDaveHello** [comment]
Added 7 days ago.

* e73b88c add Colorify.js with npm auto-update

**Comment by KasperAndersson** [comment]
Nice on :+1:
