### ISSUE TITLE
[Request] Add react-keybinding

### ISSUE THREAD

**Issue by dcworldwide** [cdnjs/cdnjs#7148]
**Library name:** react-keybinding
**Git repository url:** https://github.com/mapbox/react-keybinding/
**npm package url(optional):** 
**License(s):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@dcworldwide what are the files need to be hosted on CDNJS? Thanks.

**Comment by PeterDaveHello** [comment]
cc auther @tmcw @scothis

**Comment by PeterDaveHello** [comment]
ping @dcworldwide

**Comment by dcworldwide** [comment]
Decided that I no longer need this. I was looking for a cdn for my codepen deps, but using cdnjs for every dep will never work, I figure i'm better off hosting my deps somewhere that i can ownership of. Sorry, thanks for looking into this.

**Comment by PeterDaveHello** [comment]
np
