### ISSUE TITLE
[Request] Add offline.js css files

### ISSUE THREAD

**Issue by jamesz** [cdnjs/cdnjs#7155]
LIbrary: Offline.JS
Git repository url: https://github.com/hubspot/offline
Official homepage: https://github.com/hubspot/offline

The javascript file is already there, but it would be good to have all the css files for theme and languages as well.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/offline-js

**Comment by PeterDaveHello** [comment]
@jamesz what's the files you meant here?

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by MattIPv4** [comment]
Library appears to unmaintained, closing.
