### ISSUE TITLE
[Request] Add Giphify

### ISSUE THREAD

**Issue by twaffl3s** [cdnjs/cdnjs#7161]
**Library name:**  Giphify
**Git repository url:** https://github.com/twaffl3s/giphify
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://acjanus.co
**Wanna say something? Leave message here:** A library that uses the GIPHY API to create tooltips with random images, based on the text that's in the wrapper. 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @twaffl3s, thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!
