### ISSUE TITLE
[Request] Add Mootools More v1.6.0

### ISSUE THREAD

**Issue by alphestdev** [cdnjs/cdnjs#7183]
**Library name:** Mootools More
**Git repository url:** http://github.com/mootools/mootools-more
**License(s):**
**Official homepage:** http://mootools.net/
**Wanna say something? Leave message here:** Core 1.6.0 is included on CDNJS but More 1.6.0 not. Please add.

**Comment by alphestdev** [comment]
Any progress?

**Comment by PeterDaveHello** [comment]
Sorry for the late reply, we now have it.
