### ISSUE TITLE
[Request] Add To Home Simple

### ISSUE THREAD

**Issue by iHackify** [cdnjs/cdnjs#7184]
**Library name: Add To Home Simple** 
**Git repository url: https://github.com/iHackify/addtohomesimple**
**npm package url(optional):** 
**License(s): MIT License**
**Official homepage: http://ihackify.github.io/addtohomesimple/**
**Wanna say something? Leave message here: Add To Home Simple Works Like A Charm It Works With Very Simple Javascript That Allows Your Website To Detect Whether Or Not the Website Is Opened Via iOS Safari Or Via A Web Clip**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by iHackify** [comment]
????

**Comment by PeterDaveHello** [comment]
@iHackify I can see to popularity on this lib, there is a popularity requirement to add a lib, please read our document first, thanks.

**Comment by maruilian11** [comment]
close due to no response.
