### ISSUE TITLE
[Request] Add jquery-sse 

### ISSUE THREAD

**Issue by byjg** [cdnjs/cdnjs#7185]
**Library name:** jquery-sse
**Git repository url:** https://github.com/byjg/jquery-sse
**npm package url(optional):** https://www.npmjs.com/package/jquery-sse
**License(s):** MIT
**Official homepage:** https://github.com/byjg/jquery-sse
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @byjg ,

Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Best,
Peter

**Comment by PeterDaveHello** [comment]
Close due to no response.
