### ISSUE TITLE
[Request] Add ramjet

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7191]
**Library name:** ramjet
**Git repository url:** https://github.com/Rich-Harris/ramjet
**npm package url(optional):** ramjet

**Comment by kennynaoh** [comment]
there is a syntax error problem when I do the minify about ramjet.js

**Comment by PeterDaveHello** [comment]
@kennynaoh What's the error message? What's the minifier you are using? You should provide info in detail.

**Comment by kennynaoh** [comment]
error message: 
/home/naoh/web-minify-helper/minify.sh: line 58: /home/naoh/web-minify-helper/node_modules/uglify-js/bin/uglifyjs: No such file or directory
local compressor failed, try javascript-/cssminifier.com
minifier:
I remove the web-minify-helper and clone again, so maybe it is the newest version.

thanks

**Comment by PeterDaveHello** [comment]
Seems you didn't run `npm install` ...
https://github.com/PeterDaveHello/web-minify-helper#how-to-use

**Comment by kennynaoh** [comment]
ok, I will check.
thanks.
