### ISSUE TITLE
[Request] Add Repaintless.css

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7192]
**Library name:** Repaintless.css
**Git repository url:** https://github.com/szynszyliszys/repaintless
**npm package url(optional):** repaintless
**Official homepage:** http://szynszyliszys.github.io/repaintless/

**Comment by pvnr0082t** [comment]
@PeterDaveHello Should I pick the ```repaintless-scss/``` directory including many .scss files?

**Comment by PeterDaveHello** [comment]
@pvnr0082t Nope, we don't host scss.
