### ISSUE TITLE
[Request] Add suncalc

### ISSUE THREAD

**Issue by avimar** [cdnjs/cdnjs#7199]
**Library name:** suncalc
**Git repository url:** https://github.com/mourner/suncalc
**npm package url(optional):** suncalc
**License(s):** must reatin copyright
**Official homepage:** github, but demo at: http://suncalc.net/

**Comment by avimar** [comment]
@PeterDaveHello Thanks! Now one of my projects loads all JS from cdnjs :smiley:

**Comment by PeterDaveHello** [comment]
Nice.
