### ISSUE TITLE
Update twitter/twemoji

### ISSUE THREAD

**Issue by markseu** [cdnjs/cdnjs#7213]
Hi, please update https://cdnjs.com/libraries/twemoji.
There are new files for [version 2](https://github.com/twitter/twemoji#breaking-changes-in-v2), for example [Swedish flag](https://github.com/twitter/twemoji/blob/gh-pages/2/svg/1f1f8-1f1ea.svg).

**Comment by PeterDaveHello** [comment]
Yeah, we have the latest v2.0.0~2.0.5

**Comment by markseu** [comment]
Thank you 👍

**Comment by PeterDaveHello** [comment]
@markseu np
