### ISSUE TITLE
[author][new] Add cloudinary-core 2.0.7

### ISSUE THREAD

**Issue by cloudinary** [cdnjs/cdnjs#7216]
**Library name**: `cloudinary-core`
**Git repository url**: https://github.com/cloudinary/pkg-cloudinary-core
**npm package url(optional)**: https://www.npmjs.com/package/cloudinary-core
**License(s)**: MIT
**Official homepage**: http://cloudinary.com/
**Wanna say something? Leave message here**: This is the JavaScript client library for the cloudinary service.
PR to follow shortly.

**Comment by PeterDaveHello** [comment]
Added in #7217
