### ISSUE TITLE
[Request] jQuery Datetimepicker Full

### ISSUE THREAD

**Issue by evromalarkey** [cdnjs/cdnjs#7222]
**Library name:** jquery-datetimepicker
**Git repository url:** https://github.com/xdan/datetimepicker
**npm package url(optional):** https://github.com/xdan/datetimepicker/blob/master/package.json
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
The library is already on cdnjs (https://cdnjs.com/libraries/jquery-datetimepicker), but that's no longer the full version. -  jquery.datetimepicker.full.min.js is missing there

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by evromalarkey** [comment]
unfortunately I still can't see the full version on cdnjs
http://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.1/jquery.datetimepicker.js still lacks the DateFormatter dependency, so it's not working - here is how it should be https://github.com/xdan/datetimepicker/blob/master/build/jquery.datetimepicker.full.js

**Comment by PeterDaveHello** [comment]
@evromalarkey I will take a look at it. Thanks for report.

**Comment by PeterDaveHello** [comment]
@evromalarkey have you tried this?
https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.3/build/jquery.datetimepicker.full.min.js
