### ISSUE TITLE
[Request] Add Jed

### ISSUE THREAD

**Issue by koorgoo** [cdnjs/cdnjs#7223]
**Library name:** Jed
**Git repository url:** https://github.com/SlexAxton/Jed
**npm package url(optional):** https://www.npmjs.com/package/jed
**License(s):** WTFPL
**Official homepage:** https://slexaxton.github.io/Jed/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by koorgoo** [comment]
Nice. Thank you.

**Comment by maruilian11** [comment]
:+1:
