### ISSUE TITLE
[Request] Add leaflet.spin

### ISSUE THREAD

**Issue by fallingrock** [cdnjs/cdnjs#7224]
**Library name:** Leaflet.Spin
**Git repository url:** https://github.com/makinacorpus/Leaflet.Spin
**npm package url(optional):** 
**License(s):** MIT 
**Official homepage:** https://github.com/makinacorpus/Leaflet.Spin
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@fallingrock sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·                 
we suggest you open an issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
We'll add this.
