### ISSUE TITLE
Valoraciones.js

### ISSUE THREAD

**Issue by lrocabuso** [cdnjs/cdnjs#7228]
**Library name**: valoraciones.js  
**Git repository url**: [https://github.com/lrocabuso/valoraciones](https://github.com/lrocabuso/valoraciones)  
**npm package url(optional)**:   
**License(s)**: MIT  
**Official homepage**: [http://www.minubeinformatica.com](http://www.minubeinformatica.com)
* * *
Control básico para el uso de marcadores de valoración utilizando estrellas como marcadores.

**Comment by maruilian11** [comment]
@lrocabuso  sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·                 
we suggest you open an issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.
