### ISSUE TITLE
[Request] audiojs

### ISSUE THREAD

**Issue by EndenDragon** [cdnjs/cdnjs#7229]
**Library name:** audiojs
**Git repository url:** https://github.com/kolber/audiojs
**License(s):** MIT license
**Official homepage:** http://kolber.github.io/audiojs/
**Wanna say something? Leave message here:**
Just add the following files should be fine (It all needs to be able to be called from the same folder/url, in order to have it work): audio.js, audio.min.js, audiojs.swf, and player-graphics.gif

**Comment by EndenDragon** [comment]
Would this be sufficient? https://github.com/cdnjs/cdnjs/pull/7230

**Comment by maruilian11** [comment]
close this because the PR was merged.
