### ISSUE TITLE
[Request] Genericons

### ISSUE THREAD

**Issue by solvemethod** [cdnjs/cdnjs#7231]
**Library name:Genericons** 
**Git repository url:https://github.com/Automattic/Genericons**
**License(s):GPL v2**
**Official homepage:http://genericons.com/**
**Wanna say something? Leave message here:Genericons is much needed for WordPress site.**

**Comment by georgestephanis** [comment]
cc: @jasmussen ^^ (iunno why I was tagged either, but it's more relevant to you than me)

**Comment by maruilian11** [comment]
@georgestephanis  thanks! 
@jasmussen sorry for not tagging you the first time!
