### ISSUE TITLE
fastclick.min.js

### ISSUE THREAD

**Issue by RambaliSingh** [cdnjs/cdnjs#7232]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@RambaliSingh what's this for?
this issue will be closed if there is no response next 7 days, thank you very much!
