### ISSUE TITLE
https://github.com/websanova/js-url

### ISSUE THREAD

**Issue by websanova** [cdnjs/cdnjs#7233]
**Library name:**  js-url
**Git repository url:** https://github.com/websanova/js-url
**npm package url(optional):** https://www.npmjs.com/package/wurl
**License(s):** MIT
**Official homepage:** http://websanova.com/plugins/url
**Wanna say something? Leave message here:** Please use this since it's the official library. Not that jillex or whatever you have there.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi, @websanova 
we already host [js-url](https://cdnjs.com/libraries/js-url)! :laughing: 
thank you!
