### ISSUE TITLE
[Request] Add Framico

### ISSUE THREAD

**Issue by TheBrooonS** [cdnjs/cdnjs#7236]
**Library name:** Framico
**Git repository url:** https://github.com/TheBrooonS/Framico.git
**npm package url(optional):** 
**License(s):** ISC
**Official homepage:** http://framico.thebrooons.ru
**Wanna say something? Leave message here:** I would be very grateful for adding :)

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @TheBrooonS , thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!
