### ISSUE TITLE
[Request] Jarallax

### ISSUE THREAD

**Issue by daniluski** [cdnjs/cdnjs#7243]
**Library name:Jarallax** 
**Git repository url: https://github.com/nk-o/jarallax**
**npm package url(optional):** 
**License(s): Copyright (c) 2015 _nK Licensed under the WTFPL license.**
**Official homepage: http://free.nkdev.info/jarallax/simple-parallax.html**
**Wanna say something? Leave message here:**
Just Another Parallax [Jarallax]
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @daniluski , thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!

**Comment by PeterDaveHello** [comment]
Added in #7283
