### ISSUE TITLE
[FIX] jquery-ujs 

### ISSUE THREAD

**Issue by nMado** [cdnjs/cdnjs#7249]
**Library name:** jquery-ujs
**Git repository url:** https://github.com/rails/jquery-ujs
**Wanna say something? Leave message here:**

I'm getting either `404 Not Found` or `403 Forbidden` error message when I try to open one of the urls listed for the `jquery-ujs` here https://cdnjs.com/libraries/jquery-ujs or more specifically this cdn url https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.1/rails.js

**Comment by PeterDaveHello** [comment]
cc @ryankirkman

**Comment by PeterDaveHello** [comment]
issue confirmed.

**Comment by thomasdavis** [comment]
Any other files on the network experiencing the same problem?

**Comment by PeterDaveHello** [comment]
@thomasdavis hard to test them all, but we got this serveral times in this week

**Comment by terinjokes** [comment]
Taking a look at why this came back.

**Comment by PeterDaveHello** [comment]
@terinjokes seems the latest angular.js has same problem

**Comment by terinjokes** [comment]
@PeterDaveHello they tend come all at once.
