### ISSUE TITLE
[Request] Add Lightense Images 

### ISSUE THREAD

**Issue by sparanoid** [cdnjs/cdnjs#7251]
**Library name:** Lightense Images 
**Git repository url:** https://github.com/sparanoid/lightense-images
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://sparanoid.com/work/lightense-images/
**Wanna say something? Leave message here:** A dependency-free pure JavaScript image lightbox library less than 2 KB (not gzipped!)

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @sparanoid , thanks for your suggestion, but for the lib wants to be hosted on the cdn, it'll need to have some notable popularity, for now, seems the star/watcher/fork count on GitHub is a little too few, we'll respectfully suggest you to send this request when the lib been more popular, or if you can show us something else like the lib's hosting page on sourceforge, bitbucket, npm, etc. Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.
