### ISSUE TITLE
[Request] Add angular-material-toasts

### ISSUE THREAD

**Issue by andreasonny83** [cdnjs/cdnjs#7262]
**Library name:angular-material-toasts** 
**Git repository url:https://github.com/andreasonny83/angular-material-toasts**
**npm package url(optional):** 
**License(s):MIT**
**Official homepage:https://github.com/andreasonny83/angular-material-toasts**
**Wanna say something? Leave message here:The library is already linked to a bower package**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Hi @andreasonny83 ,

Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Best,
Peter
