### ISSUE TITLE
Drop "requiredFiles" section in package.json

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7264]
With the new powerful hardware I bought and the tuning of the scripts, the bot is now stable enough, working hard day and night, as you can see below:

https://github.com/cdnjs/cdnjs/commits/master?author=PeterBot
![screenshot from 2016-03-12 23 06 43](https://cloud.githubusercontent.com/assets/3691490/13723671/1b816bb2-e8a7-11e5-820a-be4ebef46eea.png)

Though the bot is not powerful enough for us (*both the hardware and software, I need much more time to work on the codes, and also need some money to buy the powerful enough machine*), at least, it will always check the structure inconsistency and try to minify the css/js files, using zopflipng to recompress png images with zopfli's default 15 iterations, so I am happy to say, let's drop the `"requiredFiles"` section in `package.json`, which was used to check if there are some files should have a minified copy, we don't need it anymore, I will remove the codes about that part after 7 days!

`"requiredFiles"` example taken from [sco.js](https://cdnjs.com/libraries/sco.js)
```js
  "requiredFiles": [
    "css/sco.message.min.css",
    "js/sco.ajax.min.js",
    "js/sco.collapse.min.js",
    "js/sco.confirm.min.js",
    "js/sco.countdown.min.js",
    "js/sco.message.min.js",
    "js/sco.modal.min.js",
    "js/sco.panes.min.js",
    "js/sco.tab.min.js",
    "js/sco.tooltip.min.js",
    "js/sco.valid.min.js"
  ]
```

Will affect these libs:
 - Buttons
 - Dynatable
 - Radian
 - alchemyjs
 - angular-bootstrap-datetimepicker
 - angular-data-table
 - angular-timer
 - awesomplete
 - blueimp-load-image
 - bootstrap-fileinput
 - bootstrap-rating
 - circliful
 - classnames
 - coin-slider
 - collageplus
 - cytoscape-panzoom
 - datatables-colvis
 - dialog-polyfill
 - elemental
 - ember-data-model-fragments
 - fabric.js
 - fancyInput
 - flux
 - formatter.js
 - formvalidation
 - graphiql
 - gridforms
 - image-picker
 - ion-rangeslider
 - jBox
 - jReject
 - jqtree
 - jquery-countdown
 - jquery-lang-js
 - jquery-modal
 - jquery-treetable
 - jquery.cycle
 - jquery.scrollbar
 - jquery.smartmenus
 - js-data
 - jwerty
 - le_js
 - lightbox2
 - lightcase
 - limonte-sweetalert2
 - line-chart
 - loaders.css
 - multi-select
 - nice-validator
 - notify
 - nwmatcher
 - object-fit
 - onepage-scroll
 - pegasus
 - perfbar
 - photoswipe
 - pikaday
 - pqGrid
 - prettyPhoto
 - prism
 - remodal
 - require.js
 - scannerdetection
 - sco.js
 - sigma.js
 - spinkit
 - superfish
 - sweetalert
 - syn
 - tagmanager
 - timecircles
 - trix
 - unsemantic

cc @cdnjs/team-cdnjs @cdnjs/intern

**Comment by maruilian11** [comment]
:+1:
