### ISSUE TITLE
[Request] Add isomorphic-fetch

### ISSUE THREAD

**Issue by jacogr** [cdnjs/cdnjs#7266]
**Library name:** isomorphic-fetch
**Git repository url:** https://github.com/matthew-andrews/isomorphic-fetch
**npm package url(optional):** https://www.npmjs.com/package/isomorphic-fetch
**License(s):** MIT
**Official homepage:** https://github.com/matthew-andrews/isomorphic-fetch
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@jacogr would you please tell me what are the files I should add? Thanks.

**Comment by jacogr** [comment]
Been using this via bower & browserify for this locally, however digging through the bower.json - 

I think it probably would make sense for people to just use the "fetch" library instead in the browser, this is actually just a wrapper for it. (i.e. fetch-bower.js is the file to be included, but this requires browserify - not quite right for CDN)

Think it should probably be closed since it requires an extra step, and there are alternatives available.

**Comment by PeterDaveHello** [comment]
Okay, so close this, thanks.
