### ISSUE TITLE
[author][Request] Add pinf

### ISSUE THREAD

**Issue by cadorn** [cdnjs/cdnjs#7267]
**Library name:** pinf
**Git repository url:** https://github.com/pinf/pinf-loader-js
**npm package url(optional):** pinf-loader-js
**License(s):** https://opensource.org/licenses/FPL-1.0.0
**Official homepage:** http://pinf.js.org/
**Wanna say something? Leave message here:**

I am aware that this library is not yet popular enough to possibly be considered.

I wish to point out that since the library is a generic loader that is intended to be loaded by default by any site it does belong onto a cdn and highly shared namespace and is the approach I wish to promote to users.

Files:
- `loader.js`
- `loader.min.js`

**Comment by sashberd** [comment]
@PeterDaveHello Should we host this lib?

**Comment by cadorn** [comment]
The timing of this re-consideration is interesting. I hope to release a few projects that leverage this loader (like https://jsonrep.github.io/jsonrep/) in the coming months.

**Comment by PeterDaveHello** [comment]
hmmm if @cadorn you'd like to send a pull request, I can accept it, but we may not directly help add it as we still have many libraries with higher popularity to deal with.

**Comment by cadorn** [comment]
Sounds good! I'll send a PR when ready. Thanks!

**Comment by PeterDaveHello** [comment]
@cadorn I mean if you can send a PR from your side, I'll like to assume the popularity requirement is met this time :)

**Comment by sashberd** [comment]
Hi @cadorn 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
