### ISSUE TITLE
[Request] Add adactio/FitText.js

### ISSUE THREAD

**Issue by MDTech-us-MAN** [cdnjs/cdnjs#7274]
adactio/FitText.js
https://github.com/adactio/FitText.js

A non-jQuery version.

**Comment by PeterDaveHello** [comment]
There is no [git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) in that repository, **git tag** is what our git auto-updater relies on, is there is no any valid tag, the updater can not recognize what are the correct versions we can use, and also, you can not make sure the specific versions. So would you please discuss with its author about that, thanks.

References:
 - https://git-scm.com/book/en/v2/Git-Basics-Tagging
 - https://help.github.com/articles/creating-releases/
 - https://help.github.com/articles/working-with-tags/

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
