### ISSUE TITLE
[Request] Add switchy

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7277]
https://github.com/lou/switchy

**Comment by PeterDaveHello** [comment]
@pvnr0082t  note that you need to use git auto-update here, not npm.

**Comment by pvnr0082t** [comment]
Okay. I got it.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I found the ```switchy.jquery.json``` in this library.
Should I change the filename ```switchy.jquery.json``` to ```package.json```?

**Comment by PeterDaveHello** [comment]
@pvnr0082t If you can not find package.json, you can use it as reference.
