### ISSUE TITLE
[Request] Jarallax

### ISSUE THREAD

**Issue by rogervila** [cdnjs/cdnjs#7283]
**Library name:** Jarallax 
**Git repository url:** https://github.com/nk-o/jarallax.git
**License(s):** Copyright (c) 2016 _nK Licensed under the WTFPL license.
**Official homepage:** https://github.com/nk-o/jarallax

**Comment by maruilian11** [comment]
@rogervila sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·
we suggest you open an issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Looks good to promote this lib, I'll add it
