### ISSUE TITLE
[Request] Add ngAudio

### ISSUE THREAD

**Issue by AmitMY** [cdnjs/cdnjs#7291]
**Library name:** ngAudio
**Git repository url:** https://github.com/danielstern/ngAudio
**License(s):** MIT

**Wanna say something? Leave message here:**
A great library for audio with angularjs

**Comment by PeterDaveHello** [comment]
@AmitMY  would you please tell me what are the files I should add? Thanks.

**Comment by AmitMY** [comment]
The only one needed for using ngAudio is: https://github.com/danielstern/ngAudio/blob/master/app/angular.audio.js
Or path in the project:
app/angular.audio.js

They do not have a minified file as far as I can tell.

Thanks

**Comment by PeterDaveHello** [comment]
@danielstern would you please help us confirm that? Many thanks.

**Comment by AmitMY** [comment]
Yes, I have scanned the files, no minified version for ngAudio found.
So the only file required is the file above.

**Comment by danielstern** [comment]
@AmitMY  @PeterDaveHello 
Thank you for the inclusion of this library!
Yes, that is correct, the main file @ app/angular.audio.js is all that is required!

**Comment by PeterDaveHello** [comment]
Thanks @danielstern
