### ISSUE TITLE
[Request] Add jquery.backstretch

### ISSUE THREAD

**Issue by danielgindi** [cdnjs/cdnjs#7296]
**Library name:** jquery.backstretch
**Git repository url:** https://github.com/danielgindi/jquery-backstretch/
**npm package url(optional):** https://www.npmjs.com/package/jquery.backstretch
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**

The original jquery.backstretch repository is practically dead, and this is a fork that had much evolution.

Now there are requests to CDN it... https://github.com/danielgindi/jquery-backstretch/issues/19

**Comment by SakyaStelios** [comment]
:+1:
