### ISSUE TITLE
[Request] Add jQuery 2.2.2

### ISSUE THREAD

**Issue by t47io** [cdnjs/cdnjs#7300]
**Library name:**  jQuery
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Sorry for the delay.
* 5b4db93 add jquery v1.12.2/2.2.2
