### ISSUE TITLE
[Request] Add jblocks

### ISSUE THREAD

**Issue by vitkarpov** [cdnjs/cdnjs#7316]
**Library name:**  jblocks
**Git repository url:** https://github.com/vitkarpov/jblocks
**npm package url(optional):** https://www.npmjs.com/package/jblocks
**License(s):** MIT
**Official homepage:**  http://vitkarpov.com/jblocks/
**About the library:** jblocks is a tiny javascript library which helps to build UI components

**Comment by maruilian11** [comment]
@vitkarpov sorry, but this lib doesn't have enough popularity(100 watch or star on github, or 500 downloaded on npm package a month is a good example). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail. 
we suggest you open a issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
@maruilian11, looks good to promote this library, let's add it!
