### ISSUE TITLE
[Request] Add nestedSortable v.2

### ISSUE THREAD

**Issue by Krato** [cdnjs/cdnjs#7337]
**Library name:** nestedSortable
**Git repository url:** https://github.com/ilikenwf/nestedSortable
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**https://github.com/ilikenwf/nestedSortable
**Wanna say something? Leave message here:** Is a fork with version 2 of this plugin.

**Comment by maruilian11** [comment]
@Krato https://cdnjs.com/libraries/nestedSortable is from ilikenwf/nestedSortable

**Comment by PeterDaveHello** [comment]
Close since we have it.

**Comment by Krato** [comment]
@maruilian11 Is on it. But is discontinued and other user has the new version, 2.0. I think you must change git url of package. Thanks.

**Comment by maruilian11** [comment]
@Krato we use git tag to update this lib, i will open an issue to ask the author if he can update tags to the latest version, thank you!

**Comment by Krato** [comment]
@maruilian11 ok. Thanks.

**Comment by maruilian11** [comment]
@Krato the author has add tag v2.0.0, please wait for few hours, it would be see on cdnjs.com :smile:

**Comment by PeterDaveHello** [comment]
@maruilian11 v2.0.0 changed the filename, check it out before you saying it'll be there.
