### ISSUE TITLE
[Request] Add GoJS [author] [new]

### ISSUE THREAD

**Issue by simonsarris** [cdnjs/cdnjs#7341]
**Library name:** GoJS
**Git repository url:** https://github.com/NorthwoodsSoftware/GoJS
**npm package url(optional):** https://www.npmjs.com/package/gojs
**License(s):** http://gojs.net/latest/doc/license.html
**Official homepage:**  http://gojs.net
**Wanna say something? Leave message here:**

* GitHub / Bitbucket popularity (required):
  * Count of stars: 498
  * Count of watchers: 107
  * Count of forks: 356
* NPM download stats (optional):
  * Downloads in the last day: 14
  * Downloads in the last week: 93
  * Downloads in the last month: 511

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@simonsarris what are the files should be hosted?

**Comment by simonsarris** [comment]
> what are the files should be hosted?

@PeterDaveHello these two:

    "release/go.js",
    "release/go-debug.js",

aka:

https://github.com/NorthwoodsSoftware/GoJS/blob/master/release/go.js

https://github.com/NorthwoodsSoftware/GoJS/blob/master/release/go-debug.js

Should I be pointing to these in the `package.json`? I do have:

    "main": "release/go.js",

In the `package.json`

**Comment by PeterDaveHello** [comment]
@simonsarris Thanks, that's useful, no need to add to your own package.json
