### ISSUE TITLE
[Request] Add Grommet Index

### ISSUE THREAD

**Issue by eabay** [cdnjs/cdnjs#7344]
**Library name:** Grommet Index
**Git repository url:** https://github.com/grommet/grommet-index
**npm package url(optional):** https://www.npmjs.com/package/grommet-index
**License(s):** Apache-2.0
**Official homepage:** http://index.grommet.io/

**Comment by maruilian11** [comment]
@eabay sorry, but this lib doesn't have enough popularity(100 watch or star and 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·
we suggest you open an issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
@eabay what are the files should be added ?

**Comment by alansouzati** [comment]
Hi all, I'm part of the grommet team. We recently decided to split our project into separate modules.

Previously `grommet-index` was inside [grommet](https://github.com/grommet/grommet) which meets the 'popularity' requirements.

It would be great to have both `grommet-index` and `grommet` available at `cdnjs`.

`grommet` has a bower distribution available here: https://github.com/grommet/grommet-bower. I'm assuming that would be enough for you guys to track it in your end?

Unfortunately, `grommet-index` does not yet have a bower distribution. I'm going to work on that today and I will let you guys know as soon as I have it.

Alan

**Comment by eabay** [comment]
#7343 #7412

**Comment by PeterDaveHello** [comment]
Hi @alansouzati, the npm package also looks good for us, we'll use npm auto-update here.

**Comment by PeterDaveHello** [comment]
@eabay @alansouzati
Sorry for the late reply and update, I'm adding this lib now!

**Comment by alansouzati** [comment]
thanks for the update

**Comment by PeterDaveHello** [comment]
You're welcome @alansouzati, btw, would you be interested in adding CDNJS in the document? This can help your users use it easier, thanks.
