### ISSUE TITLE
[Request] Add ResponsiveFilemanager

### ISSUE THREAD

**Issue by zafranf** [cdnjs/cdnjs#7348]
**Library name:** ResponsiveFilemanager
**Git repository url:** https://github.com/trippo/ResponsiveFilemanager/
**npm package url(optional):** 
**License(s):** http://creativecommons.org/licenses/by-nc/3.0/
**Official homepage:** http://www.responsivefilemanager.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by zafranf** [comment]
oh, ok. thank you @kennynaoh :)

**Comment by PeterDaveHello** [comment]
Is this added?

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 The library still written on PHP. Should we still have this request opened?
