### ISSUE TITLE
[Request] Add bootstrap-drawer

### ISSUE THREAD

**Issue by Stephan972** [cdnjs/cdnjs#7350]
**Library name:** bootstrap-drawer
**Git repository url:** https://github.com/clineamb/bootstrap-drawer
**npm package url(optional):** https://www.npmjs.com/package/bootstrap-drawer
**License(s):** (See below)
**Official homepage:** https://github.com/clineamb/bootstrap-drawer
**Wanna say something? Leave message here:**
The package is published on npm: https://www.npmjs.com/package/bootstrap-drawer.

The licence is presented like this:

~ LICENCE START ~
Copyright (c) 2015, Caroline Amaba

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
~ LICENCE END ~

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks

**Comment by kennynaoh** [comment]
Hello @Stephan972  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our README.md for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.
Thanks!

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh we can add this.

**Comment by kennynaoh** [comment]
OK, thanks
