### ISSUE TITLE
[request] Add wordpress theme js

### ISSUE THREAD

**Issue by semaoip** [cdnjs/cdnjs#7351]
**Library name:** doim 
**Git repository url:** https://github.com/doim/doim.github.com
**doim npm package url(optional):**
**theme License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**semaoip@gmail.com

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any details here?

**Comment by dannyxx001** [comment]
Sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our README.md for detail. We suggest you open a issue again when the repo has notable popularity. Thank you for your contribution.

**Comment by PeterDaveHello** [comment]
@dannyxx001 please do not directly close issue duo to the popularity, you can close this is the issuer do not respond for more than 7 days since your comment.

**Comment by dannyxx001** [comment]
OK. if this issuer do not respond for more than 7 days, and I will close it at that time.

**Comment by dannyxx001** [comment]
Close it because of no response more than 7 days.
