### ISSUE TITLE
seamless-immutable.js

### ISSUE THREAD

**Issue by holly-juan** [cdnjs/cdnjs#7359]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @holly-juan ,
What's the detail?
Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
@kennynaoh please close your no-respond issues.
