### ISSUE TITLE
[Request] Add Maptable

### ISSUE THREAD

**Issue by melalj** [cdnjs/cdnjs#7363]
**Library name:** Maptable
**Git repository url:** https://github.com/Packet-Clearing-House/maptable
**npm package url(optional):** https://www.npmjs.com/package/maptable
**License(s):** MIT
**Official homepage:** http://packet-clearing-house.github.io/maptable/
**Wanna say something? Leave message here:** Convert any dataset to a customizable set of visual components (Map, Filters, Table). Using D3

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@melalj ,
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Yeah, we need a higher popularity on this lib.

**Comment by melalj** [comment]
Okay Thanks.
Will repost it when it would gain more popularity.

**Comment by PeterDaveHello** [comment]
Thanks.
