### ISSUE TITLE
[Request] Add url-query-builder

### ISSUE THREAD

**Issue by Thisman** [cdnjs/cdnjs#7367]
**Library name:url-query-builder** 
**Git repository url:https://github.com/Thisman/UrlQueryBuilder**
**npm package url(optional):https://www.npmjs.com/package/url-query-builder** 
**License(s):MIT**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@Thisman 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
Close due to no response.
