### ISSUE TITLE
[Request] Add Nodus

### ISSUE THREAD

**Issue by AdmajorMC** [cdnjs/cdnjs#7368]
**Library name:Nodus** 
**Git repository urlhttps://github.com/AdmajorMC/nodus-library:**
**npm package url(optional):** 
**License(s):none**
**Official homepagenone:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@AdmajorMC what can we do for you?

**Comment by PeterDaveHello** [comment]
This lib needs a higher popularity to be hosted on cdnjs.

**Comment by maruilian11** [comment]
@AdmajorMC this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
Close due to no response.
