### ISSUE TITLE
number-polyfill js

### ISSUE THREAD

**Issue by ranjankumarpatel** [cdnjs/cdnjs#7370]
Number Polyfill
https://github.com/jonstipe/number-polyfill

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
duplicated with https://github.com/cdnjs/cdnjs/issues/7282
