### ISSUE TITLE
[Request] Add pickout

### ISSUE THREAD

**Issue by ktquez** [cdnjs/cdnjs#7372]
**Library name:** pickout
**Git repository url:** https://github.com/ktquez/pickout
**npm package url(optional):** https://www.npmjs.com/package/pickout  
**License(s):** MIT
**Official homepage:** https://github.com/ktquez/pickout
**Wanna say something? Leave message here:**

**Comment by dannyxx001** [comment]
@ktquez 
This library doesn't have notable popularity(100 watch or star, or 500 downloads in npm package are good examples). Please take a look on our README.md for detail. Would you mind to open an issue again when the library has more popularity? Thanks for your suggestion. :-)
This issue will be closed if there is no any response in next 7 day.

dannyxx001

**Comment by dannyxx001** [comment]
@PeterDaveHello please help me for checking, thanks.

**Comment by PeterDaveHello** [comment]
Looks good to promote this lib, @dannyxx001 let's add this one.

**Comment by ktquez** [comment]
@PeterDaveHello 
I did yesterday, I'm entering more functionality today and the guys are really enjoying it. 
Thank you very much.
