### ISSUE TITLE
[Request] Add jQuery-ace

### ISSUE THREAD

**Issue by ramiy** [cdnjs/cdnjs#7392]
**Library name:** jQuery-ace
**Git repository url:** https://github.com/cheef/jquery-ace
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://cheef.github.io/jquery-ace/
**Wanna say something? Leave message here:** jQuery plugin for ACE Code Editor

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@ramiy I'm sorry, but we need a higher and notable popularity on this lib, please read our document for detail, thanks.

**Comment by PeterDaveHello** [comment]
Close due to no response.
