### ISSUE TITLE
[Request] Add LogosDistort

### ISSUE THREAD

**Issue by louis-lau** [cdnjs/cdnjs#7418]
**Library name:** LogosDistort
**Git repository url:** https://github.com/hellsan631/LogosDistort
**License:** MIT
**Official homepage:** https://github.com/hellsan631/LogosDistort
**Wanna say something? Leave message here:**
LogosDistort is a fancy jQuery plugin that helps you create unique 3D perspective distortions with mouse interaction using CSS matrix3d transforms.

**Comment by x09326** [comment]
@PeterDaveHello this lib not match More than 100 [Stars / Watchers / Forks].
Should I add this lib?

**Comment by PeterDaveHello** [comment]
Looks close to the minimun request, and with good structure to add, let's add it.
