### ISSUE TITLE
[Request] Add Jouele

### ISSUE THREAD

**Issue by zupsel** [cdnjs/cdnjs#7419]
**Library name: Jouele 
**Git repository url:https://github.com/ilyabirman/Jouele
**npm package url(optional):** 
**License(s):MIT License
**Official homepage:http://ilyabirman.net/projects/jouele/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
I ask the author to update some files in the version 2.1.2.
https://github.com/ilyabirman/Jouele/issues/19
