### ISSUE TITLE
[Request] angular-translate

### ISSUE THREAD

**Issue by ragnarekmix** [cdnjs/cdnjs#7423]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @ragnarekmix , is there any detail? This issue will be closed in 7 days if no response.

**Comment by PeterDaveHello** [comment]
Close due to no response.
