### ISSUE TITLE
[Request] Add bitzyCSS

### ISSUE THREAD

**Issue by joshbivens** [cdnjs/cdnjs#7428]
bitzyCSS
https://github.com/BitzyCSS/BitzyCSS
MIT
http://bitzycss.github.io/

**Comment by iheartkode** [comment]
has this been added?

**Comment by PeterDaveHello** [comment]
Not yet.

**Comment by pvnr0082t** [comment]
I'll do it.

**Comment by iheartkode** [comment]
Ok then, that's fine.

**Comment by PeterDaveHello** [comment]
hmmmm ... that's also true

**Comment by PeterDaveHello** [comment]
Hi @joshbivens & @iheartkode,

Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

To prevent I missed anything (e.g. It's a famous library, but only publish on GitHub or npm recently so it doesn't have a notable popularity on these platforms, or maybe it's a js library developed for a popular application), I will not close this issue in next 7 days, feel free to show some other references if you have something else want to discuss with us, if there is no any response in next 7 day, this issue will be closed.

Thanks for being interested in CDNJS.

Best,
Peter

**Comment by PeterDaveHello** [comment]
@pvnr0082t you should mention the reason to close a issue first.

**Comment by pvnr0082t** [comment]
Oh, sorry. I close this issue because this library doesn't have enough notable popularity.

**Comment by PeterDaveHello** [comment]
The reason should be no response from issuer.
