### ISSUE TITLE
[Request] Add photobox

### ISSUE THREAD

**Issue by J2TeaM** [cdnjs/cdnjs#7440]
**Library name:** photobox
**Git repository url:** https://github.com/yairEO/photobox
**npm package url(optional):** (none)
**License(s):** (none)
**Official homepage:** http://yaireo.github.io/photobox/

**Comment by J2TeaM** [comment]
Thank you, @PeterDaveHello! :+1:

**Comment by PeterDaveHello** [comment]
@J2TeaM no probs
