### ISSUE TITLE
[Request] Add shell.js

### ISSUE THREAD

**Issue by sun2rise** [cdnjs/cdnjs#7442]
shell.js
https://github.com/davidecaruso/shell.js
**npm package url(optional):** 
MIT
https://github.com/davidecaruso/shell.js

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Looks cool enough to host it.
