### ISSUE TITLE
[Request] jscolor

### ISSUE THREAD

**Issue by ajmas** [cdnjs/cdnjs#7444]
**Library name:** jscolor
**Git repository url:** https://github.com/EastDesire/jscolor
**npm package url(optional):** 
**License(s):** GPLv3
**Official homepage:** http://jscolor.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ajmas** [comment]
Just seen that there was an existing request from the project owner #6172, though was closed. I have responded on the other ticket, hoping the owner will feedback. Feel free to close this ticket if the conditions are still the same.

**Comment by PeterDaveHello** [comment]
Okay, let's discuss in #6172
