### ISSUE TITLE
[Request] Update cdnjs of egjs project

### ISSUE THREAD

**Issue by sculove** [cdnjs/cdnjs#7447]
we made a mistake when creating 1.1.0 tag.
so we did recreate 1.1.0 tag.

How to update egjs files on cdns?

https://github.com/naver/egjs
https://cdnjs.com/libraries/egjs

Please update this files on the CDN.

Thank you.

**Comment by PeterDaveHello** [comment]
@sculove I will take care of this issue.

**Comment by sculove** [comment]
@PeterDaveHello thank you

**Comment by sculove** [comment]
@PeterDaveHello egjs is not updated.
Could you check egjs agian?

https://cdnjs.com/libraries/egjs

**Comment by PeterDaveHello** [comment]
@sculove I don't think so, I didn't see any new version tags in the repo.

**Comment by sculove** [comment]
@PeterDaveHello you're right.
egjs 1.1.0 is lastest.
but, egjs cdnjs differ from egjs 1.1.0 tag

- egjs cdnjs : https://cdnjs.cloudflare.com/ajax/libs/egjs/1.1.0/eg.js (@SHA-1 c9acb90 (1.1.0-rc))
- egjs 1.1.0 tag : https://github.com/naver/egjs/blob/1.1.0/dist/eg.js (@SHA-1 fb4a69e (1.1.0-rc))

**Comment by PeterDaveHello** [comment]
@sculove Okay, I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@sculove strange, I got 0172ef297e1238aef23a71da8aa100405a9d0be4 for both. Would you please check it again?

**Comment by sculove** [comment]
@PeterDaveHello ok. I'll recreate my tag 1.1.0.
I'll keep in touch after work. thanks

**Comment by PeterDaveHello** [comment]
@sculove np

**Comment by sculove** [comment]
@PeterDaveHello I recreated 1.1.0 tag. Could you check 1.1.0 tag?

**Comment by PeterDaveHello** [comment]
I'll check it later.

**Comment by PeterDaveHello** [comment]
Okay, updated, hope we don't need to do this again ...

**Comment by sculove** [comment]
@PeterDaveHello Thank you very much.

**Comment by PeterDaveHello** [comment]
np
