### ISSUE TITLE
Wrong version of jQuery slim

### ISSUE THREAD

**Issue by henriklundahl** [cdnjs/cdnjs#7452]
When requesting https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.2/jquery.slim.min.js or https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.slim.min.js I get jQuery v3.0.0-beta1.

**Comment by PeterDaveHello** [comment]
Thanks for reporting this, I'll take a look at it.

**Comment by PeterDaveHello** [comment]
@henriklundahl they look the same as upstream, you can try `npm install jquery@2.2.2` and see what you got, so that's not our issue.

**Comment by henriklundahl** [comment]
Thanks and sorry for the noise. I didn't realize that they hadn't released the slim version yet, but I still find it strange that this 3 beta version is included along with the 2.2 version as well as the 1.12 version. Well well, not a cdnjs issue anyhow...

**Comment by PeterDaveHello** [comment]
Yep
