### ISSUE TITLE
[Request] headroom.js (update)

### ISSUE THREAD

**Issue by evromalarkey** [cdnjs/cdnjs#7453]
**Library name:** headroom.js
**Git repository url:** https://github.com/WickyNilliams/headroom.js
**npm package url(optional):** https://github.com/WickyNilliams/headroom.js/blob/master/package.json
**License(s):** MIT
**Official homepage:** http://wicky.nillia.ms/headroom.js/
**Wanna say something? Leave message here:** already on cdnjs, but only older version - 0.8.0 is missing

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Seems upstream removed the pre-built files, I'll manually update this and see if the pre-built files can be back.
