### ISSUE TITLE
[Request] Add jquery.wookmark 2.1.0

### ISSUE THREAD

**Issue by alexkleinubing** [cdnjs/cdnjs#7454]
**Library name:** jquery.wookmark
**Git repository url:** https://github.com/germanysbestkeptsecret/Wookmark-jQuery
**License(s):** https://spdx.org/licenses/MIT.html
**Official homepage:** http://www.wookmark.com/jquery-plugin
**Wanna say something? Leave message here:** Need **2.1.0** version. Actually cdn have a 1.3 only =/

**Comment by PeterDaveHello** [comment]
Close per #7570
