### ISSUE TITLE
html2canvas

### ISSUE THREAD

**Issue by udayjoshi** [cdnjs/cdnjs#7458]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@udayjoshi What's the detail?

**Comment by udayjoshi** [comment]
sorry but I needed HTML2canvas.min.js I need to use it offline

**Comment by PeterDaveHello** [comment]
You can just download it
