### ISSUE TITLE
[Request] Add Xonomy 

### ISSUE THREAD

**Issue by robert-denney** [cdnjs/cdnjs#7459]
Xonomy 
git:n/a
npm:n/a
CC4.0
http://www.lexiconista.com/xonomy/

Low barrier to entry browser-based xml editing tool. Despite the simplicity of the website, the product is polished and the manual is comprehensive.

[xonomy.zip](https://github.com/cdnjs/cdnjs/files/200781/xonomy.zip)
[xonomy.pdf](https://github.com/cdnjs/cdnjs/files/200782/xonomy.pdf)

**Comment by PeterDaveHello** [comment]
Is there any public repository?

**Comment by robert-denney** [comment]
Hi there, doesn't look like it. Looks like he just updates the dist on his
website. Seems frequent though, as recent as Jan/Feb

**Comment by PeterDaveHello** [comment]
@robert-denney We need that to verify its popularity, please read our document first.

**Comment by robert-denney** [comment]
No worries

**Comment by PeterDaveHello** [comment]
Sorry that I can't not verify that in the meantime, feel free to open a new issue once there is any updates.

**Comment by yakupgezdirici** [comment]
> Is there any public repository?

https://github.com/michmech/xonomy
