### ISSUE TITLE
Is the CDNJS API down?

### ISSUE THREAD

**Issue by mstenta** [cdnjs/cdnjs#7464]
https://api.cdnjs.com/libraries?search=jquery

Going there redirects me to:

https://cdnjs.com/libraries?search=jquery

Which does not return the expected JSON.

**Comment by mstenta** [comment]
Cross-posting the issue that originally prompted this from drupal.org: https://www.drupal.org/node/2699099

The Drupal Libraries CDN module was causing a fatal error because it wasn't handling bad API responses properly. So it's actually a combination of problems... the API isn't returning JSON, and the module isn't handling that gracefully. I've uploaded a patch to the Drupal module, so that part should be fixed.

Any ideas why the API isn't returning JSON like it should?

**Comment by PeterDaveHello** [comment]
@mstenta Sorry, my mistake.

**Comment by PeterDaveHello** [comment]
@mstenta Fixed.

**Comment by mstenta** [comment]
Thanks @PeterDaveHello - looks like it's working again.
