### ISSUE TITLE
[Request] Update LoadGo to newer version

### ISSUE THREAD

**Issue by franverona** [cdnjs/cdnjs#7466]
Library name: LoadGo
Git repository url: https://github.com/franverona/loadgo
License(s): https://github.com/franverona/loadgo/blob/master/LICENSE
Official homepage: http://franverona.com/loadgo
Wanna say something? Leave message here: Need 2.0 version. Actually cdnjs have an old version.

**Comment by PeterDaveHello** [comment]
Added in ca582c5
