### ISSUE TITLE
[Request] Add flot.tooltip

### ISSUE THREAD

**Issue by dziewonski** [cdnjs/cdnjs#7481]
**Library name:** flot.tooltip
**Git repository url:** https://github.com/krzysu/flot.tooltip
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/krzysu/flot.tooltip
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
We have it from a long time ago, see:
https://github.com/cdnjs/cdnjs/commits/master/ajax/libs/flot.tooltip
https://cdnjs.com/libraries/flot.tooltip
