### ISSUE TITLE
[Request] us-map

### ISSUE THREAD

**Issue by bespokeweb** [cdnjs/cdnjs#7484]
Library name: us-map
Git repository url: https://github.com/NewSignature/us-map
License(s): BSD Standard License
Official homepage: https://newsignature.github.io/us-map/

**Comment by PeterDaveHello** [comment]
@bespokeweb would you please tell me what are the files need to be hosted on cdn? Thanks.

**Comment by bespokeweb** [comment]
Absolutely:

https://github.com/NewSignature/us-map/blob/master/jquery.usmap.js
https://github.com/NewSignature/us-map/blob/master/svg/Blank_US_Map.svg
https://github.com/NewSignature/us-map/blob/master/svg/Blank_USA%2C_w_territories.svg
