### ISSUE TITLE
[Request] extjs 6.0.1 (new version)

### ISSUE THREAD

**Issue by tananaev** [cdnjs/cdnjs#7485]
Please add extjs version 6.0.1 to the repository.

https://www.sencha.com/forum/showthread.php?309973-Ext-JS-6.0.1-GPL-Version-is-Now-Available

**Comment by PeterDaveHello** [comment]
@tananaev I'll add it in few minutes, please take a look and see if it works for you.

**Comment by tananaev** [comment]
It seems to work. Thank you very much.

**Comment by PeterDaveHello** [comment]
@tananaev Thanks!
