### ISSUE TITLE
[Request] Add Susy

### ISSUE THREAD

**Issue by jxuereb** [cdnjs/cdnjs#7494]
Susy
https://github.com/oddbird/susy/
git://github.com/oddbird/susy.git
http://susy.oddbird.net/
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@jxuereb what are the files should we add?

**Comment by jxuereb** [comment]
Hi,

The files to be added can be found here: https://github.com/oddbird/susy/tree/master/sass. It's the entire contents of the "sass" folder.

**Comment by PeterDaveHello** [comment]
@jxuereb hmmm ... we need official pre-built files

**Comment by jxuereb** [comment]
No worries. In that case feel free to close this request.

**Comment by PeterDaveHello** [comment]
@jxuereb not really need to close this, maybe we can discuss with its author

**Comment by MattIPv4** [comment]
Closing, no further progress.
