### ISSUE TITLE
[Request] Add SmartClient

### ISSUE THREAD

**Issue by sOOrf** [cdnjs/cdnjs#7501]
**Library name:_SmartClient_ 
*_Git repository url:_http://www.smartclient.com*
**npm package url(optional):** 
**License(s):**
**Official homepage:_http://www.smartclient.com_
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@sOOrf Is there a public source code repository?

**Comment by sOOrf** [comment]
LGPL Edition: Free and open source
 Download SmartClient LGPL Edition <http://www.smartclient.com/product/download-bounce.jsp?product=smartclient&license=lgpl&version=11.0p&nightly=true>

**Comment by PeterDaveHello** [comment]
I mean a source code repository

**Comment by PeterDaveHello** [comment]
Any updates here?

**Comment by mandrachek** [comment]
They don't have a public git repo. It's LGPL, so I suppose someone could take it upon themselves to publish it.

**Comment by PeterDaveHello** [comment]
Maybe could asking for publish it officially, it'll be better than published by a someone else.

**Comment by sashberd** [comment]
@PeterDaveHello No new news here. Suggest to close
