### ISSUE TITLE
[Request] Add inexorabletash-polyfill

### ISSUE THREAD

**Issue by IncSW** [cdnjs/cdnjs#7508]
**Library name:** js-polyfills
**Git repository url:** https://github.com/inexorabletash/polyfill
**npm package url(optional):** https://www.npmjs.com/package/js-polyfills
**License(s):** https://github.com/inexorabletash/polyfill/blob/master/LICENSE.md
**Official homepage:** https://github.com/inexorabletash/polyfill
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t
