### ISSUE TITLE
[Request] Add chocolat.js

### ISSUE THREAD

**Issue by HarrisRobin** [cdnjs/cdnjs#7514]
**Library name:**Chocolat 
**Git repository url:**https://github.com/nicolas-t/Chocolat
**npm package url(optional):** https://www.npmjs.com/package/chocolat
**License(s):** Open source license
**Official homepage:** http://chocolat.insipi.de/

**Comment by x09326** [comment]
I asked the author to update the version in npm.
https://github.com/nicolas-t/Chocolat/issues/37#issuecomment-212868390
But the author meet some problem.
@PeterDaveHello can you help him?

**Comment by PeterDaveHello** [comment]
@x09326 I'll take a look at it.

**Comment by PeterDaveHello** [comment]
Seems the author forgot to publish new versino on npm, another problem is that there is only 2 versions on npm, but 14 on GitHub, I wonder if we should just use git auto-update in this case(as the author says he's new to npm, not sure if there will be problem to publish new versions again).
