### ISSUE TITLE
[Request] Update dexie to v1.3.6

### ISSUE THREAD

**Issue by dfahlander** [cdnjs/cdnjs#7520]
**Library name: dexie ** 
**Git repository url: https://github.com/dfahlander/Dexie.js**
**npm package url(optional): dexie** 
**License(s): Apache 2**
**Official homepage: http://dexie.org**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Sorry for the late reply, I'm working on it now.
