### ISSUE TITLE
[Request] Add Scrollspy 

### ISSUE THREAD

**Issue by haydenbleasel** [cdnjs/cdnjs#7527]
**Library name: Scrollspy** 
**Git repository url: https://github.com/r3plica/Scrollspy**
**npm package url(optional): (none)** 
**License(s): GNU GENERAL PUBLIC LICENSE**
**Official homepage: https://github.com/r3plica/Scrollspy**

**Comment by x09326** [comment]
@haydenbleasel 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
Yeah, we need a higher popularity on it.

**Comment by haydenbleasel** [comment]
No worries, that's all good.
