### ISSUE TITLE
[Request] Add paho.mqtt.javascript

### ISSUE THREAD

**Issue by TridentTD** [cdnjs/cdnjs#7532]
**Library name:** paho.mqtt.javascript
**Git repository url:** https://github.com/eclipse/paho.mqtt.javascript
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://www.eclipse.org/paho/
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@TridentTD 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by dannyxx001** [comment]
@TridentTD 
Hello, thanks for your request. However, maybe next time you can follow the format to open an issue. Then we can know all the information more clearly and quickly. I had modified it this time, and you can take a look at it. Thanks for your collaboration. : )

**Comment by PeterDaveHello** [comment]
We need a higher popularity on it.

**Comment by x09326** [comment]
Close because no response
