### ISSUE TITLE
[Request] Add load-awesome

### ISSUE THREAD

**Issue by Jbithell** [cdnjs/cdnjs#7536]
**Library name:** load-awesome
**Git repository url:** https://github.com/danielcardoso/load-awesome
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://github.danielcardoso.net/load-awesome/
**Wanna say something? Leave message here:**
# Not my project, I just think it would be good on CDNJS

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
The problem in https://github.com/danielcardoso/load-awesome/issues/10 should not be a problem to add this lib since [The official website](http://github.danielcardoso.net/load-awesome/) says " No JavaScript Required"
