### ISSUE TITLE
Font Awesome not working in Firefox (possible fix found)

### ISSUE THREAD

**Issue by homerjam** [cdnjs/cdnjs#755]
Hi, when using Font Awesome I've found that in Firefox the characters do not render as they should whilst they work fine in Chrome and Safari.

After some searching around this seems a common issue, I have found this suggestion:

http://blog.netdna.com/opensource/font-awesome-firefox-bug-fix/

Could you possibly add the absolute paths rather than relative paths to the css file?

Many thanks

**Comment by Subhojit1992** [comment]
In fonts folder please upload the following files

>FontAwesome.otf
>fontawesome-webfont.eot
>fontawesome-webfont.svg
>fontawesome-webfont.ttf
>fontawesome-webfont.woff
**------------------ Important glyphicons files----------------**
>glyphicons-halflings-regular.eot
>glyphicons-halflings-regular.svg
>glyphicons-halflings-regular.ttf
>glyphicons-halflings-regular.woff

Please upload the following files and after that you link your font-awesome.min.css in your header file. 

Here is the following link with proper files:
http://goo.gl/WICQAf

**Comment by blueror815** [comment]
Hi All.
I have found font awesome does not work in FF.
Could you please help me how I should do?

**Comment by PeterDaveHello** [comment]
@blueror815 if there is no any detail info, how can we help you?

**Comment by ajwaldrop** [comment]
Thanks all that contributed!!! This fixed it for me bay adding to the .hta file.

<FilesMatch ".(ttf|otf|woff)$">
    Header set Access-Control-Allow-Origin "*"
</FilesMatch>

**Comment by PeterDaveHello** [comment]
:+1: Nice

**Comment by akiladevi11** [comment]
Thanks Subhojit1992 , it worked. I have downloaded the css & fonts from the given link. It works fine now :+1:

**Comment by terinjokes** [comment]
CDNJS has served Font Awesome font files with Access-Control-Allow-Origin "*" for a while now. I can look into specific cases if more details are given.

**Comment by J3QQ4** [comment]
I am having the same bug with Firefox (works fine in all other browsers). FontAwesome icons display as rectangular boxes with unicode character code inside. 

**The bug is no longer related to CDNJS** and is now a problem in Firefox. Firefox does not display Unicode properly when an unusual unicode character such as &#xf067; is inserted directly into the markup. It works when you use a pseudo element and content, e.g.:

    yourelement::before {
        content: '\f067';
        font-family: FontAwesome;
    }

**Comment by PeterDaveHello** [comment]
@J3QQ4 Thanks for your report!

**Comment by jesuspreethi** [comment]
@Subhojit1992 Thank u so much.. with your solution i cleared this issue..

**Comment by thakurpunk** [comment]
Can anyone please tell me what to do because my custom fonts are not working in FF even on my local html, showing the same error "downloadable font: download failed (font-family: "gotham_lightregular" style:normal weight:normal stretch:normal src index:1): bad URI or cross-site access not allowed source:" I can not even apply .htaccess code here.

**Comment by PeterDaveHello** [comment]
@thakurpunk sorry for the late reply, would you please give us the url(s) you have problem (few examples)?

**Comment by ameerko2u** [comment]
Worked like a charm !
Problem Solved Many thanks :)
Adding  this to .htaccess  file solved it>
<FilesMatch ".(ttf|otf|woff)$">
    Header set Access-Control-Allow-Origin "*"
</FilesMatch>

**Comment by hesameto** [comment]
hi friends!
copy this link to your index.html:

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

goodluck ;) .

**Comment by hesameto** [comment]
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

**Comment by hesameto** [comment]
hi friends!
copy the HTML form on this page to your index.html :
https://www.bootstrapcdn.com/fontawesome/
goodluck :)
