### ISSUE TITLE
[Request] Add jquery-video-lightning

### ISSUE THREAD

**Issue by mikaoelitiana** [cdnjs/cdnjs#7550]
**Library name:** jquery-video-lightning
**Git repository url:** https://github.com/musocrat/jquery-video-lightning
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://musocrat.github.io/jquery-video-lightning/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello Still low popularity, suggest to close
