### ISSUE TITLE
[Request] Add latest chosen

### ISSUE THREAD

**Issue by ycecube** [cdnjs/cdnjs#7551]
**Name:** Chosen
**Git repository url:** https://github.com/harvesthq/chosen
**License(s):** https://github.com/harvesthq/chosen/blob/master/LICENSE.md
**Official homepage:** https://harvesthq.github.io/chosen/

**Comment by PeterDaveHello** [comment]
Since there is no pre-built files in the repo, so I can only manually add it, it'll be goo if you can open an issue to upstream and see if they can add the files in repo, thanks.

**Comment by holtkamp** [comment]
the compiled files can be fetched from a separate repo, for instance for the new ```1.6.1```: https://github.com/harvesthq/chosen-package/tree/v1.6.1

Is there a way to instruct the auto-update mechanism to use this repo to feed CDNJS?

**Comment by PeterDaveHello** [comment]
Thanks @holtkamp

**Comment by holtkamp** [comment]
Is there any way I can help to get this working?

**Comment by PeterDaveHello** [comment]
@holtkamp Since there are many requests, we need time to add this one, it'll be great if you can send a pull request to add it, thanks.

**Comment by PeterDaveHello** [comment]
BTW, our auto-update supports to fetch compiled files from another repo, so the repo you said will work.

**Comment by holtkamp** [comment]
ok, thanks for the headsup, next time will try to be pro-active and come up with a PR immediately 😄

**Comment by PeterDaveHello** [comment]
@holtkamp No problem.
