### ISSUE TITLE
[Request] visualsearch

### ISSUE THREAD

**Issue by sic2** [cdnjs/cdnjs#7575]
**Library name:** visualsearch
**Git repository url:** https://github.com/documentcloud/visualsearch
**npm package url(optional):** 
**License(s):** https://github.com/documentcloud/visualsearch/blob/master/LICENSE
**Official homepage:** http://documentcloud.github.com/visualsearch
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
