### ISSUE TITLE
[Request] Add TimeMe.js 

### ISSUE THREAD

**Issue by haydenbleasel** [cdnjs/cdnjs#7576]
**Library name: TimeMe.js** 
**Git repository url: https://github.com/jasonzissman/TimeMe.js**
**License(s): Apache License**
**Official homepage: http://jasonzissman.com/timeme/index.html**

**Comment by x09326** [comment]
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

@PeterDaveHello please help me review this issue, thanks.
This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
@haydenbleasel I think we are adding this lib, please hold on, thanks.

**Comment by PeterDaveHello** [comment]
@x09326 can you send a PR to add this?

**Comment by x09326** [comment]
Got it.
