### ISSUE TITLE
[Request] wnumb.js

### ISSUE THREAD

**Issue by DmonteiroD** [cdnjs/cdnjs#7579]
**Library name:**  wnumb.js
**Git repository url:** https://github.com/leongersen/wnumb
**Wanna say something? Leave message here:**
The author of this library is the same of noUiSlider (+- 2000 stars). 

Even without 100 stars, I think this library is relevant, because the official way of format numbers in noUiSlider is with wnumb.

https://refreshless.com/nouislider/slider-read-write/#section-formatting

**Comment by PeterDaveHello** [comment]
See #7607 #7649
