### ISSUE TITLE
Materialize 0.97.6 references incorrect directory

### ISSUE THREAD

**Issue by drewfreyling** [cdnjs/cdnjs#7580]
Currently https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.css refers fonts to `/fonts` but it looks like in the `package.json` we are only pulling in the `font` directory. It looks like things got moved recently on the materialize project - https://github.com/Dogfalo/materialize/issues/3024

**Comment by PeterDaveHello** [comment]
Does this help?
* ce199bf materialize v0.97.6 font path bug workaround Peter Dave Hello 22 hours ago

**Comment by drewfreyling** [comment]
No but i this fixes it - https://github.com/cdnjs/cdnjs/commit/a1d198c72204107de4814ce20ab41dcebb72835d

**Comment by PeterDaveHello** [comment]
Should be this one:
bf7051c
