### ISSUE TITLE
[Request] add flag-icon-css

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7587]
https://github.com/lipis/flag-icon-css/
https://lipis.github.io/flag-icon-css/

**Comment by pvnr0082t** [comment]
@PeterDaveHello https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/flag-icon-css. This library is already in ```cdnjs```.

**Comment by PeterDaveHello** [comment]
Thanks.
