### ISSUE TITLE
[Request] Add smoothState.js

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7588]
**Library name:** smoothState.js
**Git repository url:** https://github.com/miguel-perez/smoothState.js
**Official homepage:**  http://smoothstate.com/

**Comment by dannyxx001** [comment]
This lib is already in cdnjs.[see here](https://cdnjs.com/libraries/smoothState.js)

**Comment by PeterDaveHello** [comment]
Thanks.
