### ISSUE TITLE
[author] Angular.js: consider pulling releases from github / only after official announcement

### ISSUE THREAD

**Issue by Narretz** [cdnjs/cdnjs#7589]
Hi,
we noticed that you already have pulled in angular 1.5.4 into cdnjs.

Yesterday, we attempted to release angular.js 1.5.4, but an error caused the version not to be released completely  to npm / bower, and only to code.angularjs.org. We are currently investigating if we should skip 1.5.4 and go straight to 1.5.5 or to re-release it correctly (which could mean it would have different code).

So I would like you to consider only pulling angularjs releases from the associated bower-\* repositories (tagged) (https://github.com/angular/bower-angular et al), once all modules are available. 
Or, since we always do a twitter announcement, another option is to pull in the files only after the announcement (then you could still pull from code.angularjs.org)

We of course will try not to screw up our releases in the future ... ;)

**Comment by PeterDaveHello** [comment]
Hi @Narretz ,

Thanks for your report, in fact, I manually add new versions because there are not all the files in https://github.com/angular/bower-angular, so I'm not sure if it's possible to apply auto-update on angular, some users complaint about the missing files problem before, BTW, I can re-fetch v1.5.4 if you want :)

**Comment by Narretz** [comment]
Sorry I should have been more clear: There are repositories for every angular module, so bower-angular, bower-angular-animate, bower-angular-route and so forth.
We've also decided to go straight to 1.5.5 so you should probably remove 1.5.4 from the cdn completely.

**Comment by PeterDaveHello** [comment]
@Narretz usually we don't remove files from cdn, is it so dangerous so that we need to do that? I also wonder if it's possible to have a place to combine all the modules so that we can apply auto-update on it? Thanks.

**Comment by MattIPv4** [comment]
No further progress, closing.
