### ISSUE TITLE
CORS Header for SVGs? (Trumbowyg/2.0.5/ui/icons.svg)

### ISSUE THREAD

**Issue by jakejohns** [cdnjs/cdnjs#7609]
I'm not sure exactly how CORS headers are handled here, but I _think_ they need to be passed for this:
https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.0.5/ui/icons.svg
I appear to be getting an error.

**Comment by PeterDaveHello** [comment]
@terinjokes would you please take a look at this issue? Thanks.

**Comment by terinjokes** [comment]
@jakejohns How are you attempting to use the SVG? Just trying to understand what error you might be getting.

**Comment by jakejohns** [comment]
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Trumbowyg by Alex-D</title>
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.0.5/ui/trumbowyg.min.css">
    </head>
    <body>
        <div id="main" role="main">
            <div id="editor">
                <h2>This editor is the default build of Trumbowyg.</h2>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.0.5/trumbowyg.min.js"></script>
        <script>$('#editor').trumbowyg();</script>
    </body>
</html>

```

>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.0.5/ui/icons.svg. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

**Comment by terinjokes** [comment]
OK. Trumbowyg does an XHR to fetch the SVGs.

**Comment by jakejohns** [comment]
Any hope here?

**Comment by monad98** [comment]
same problem here.

**Comment by Alex-D** [comment]
Hello!

I'm the Trumbowyg creator and I want to switch from rawgit to cdnjs because people inspect the page and use the code that I use, so they use rawgit in prod. And that is not cool.

But... I can't because I use [an XHR to load SVG icons](https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L177), and I found this issue \o/

This header is just required, Trumbowyg 2+ cannot works without this header.

So, if you can add this header on the `icon.svg` file, it could be really great!

If I can help or anything, ping me :)

**Comment by terinjokes** [comment]
@Alex-D Is there a reason Trumbowyg uses an XHR to fetch the SVGs?

**Comment by Alex-D** [comment]
Some devs don't want SVG icons. So, I can't include it in JS file (and it's ugly).
I use SVG as sprite with `<use>` so I need to include SVG icons.svg content inline in each page where Trumbowyg is init.

All I can say is : I can't do other.

Idk if it's clear, it's hard to explain :/

**Comment by Alex-D** [comment]
Any update?

**Comment by PeterDaveHello** [comment]
I think @terinjokes is working on it now, please wait :)

**Comment by Alex-D** [comment]
What's up here?

**Comment by FizWork** [comment]
I play with your editor to cross-my-api-domain like this:

api/editor/ui/.htaccess
```
Options +FollowSymLinks
RewriteEngine On
RewriteRule ^icons.svg$ icons.php [L]
```

api/editor/ui/icons.svg
```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Max-Age: 999999');
header('Content-type: image/svg+xml');
echo'<svg xmlns="http://www.w3.org/2000/svg">
~~~~~~ALL SVG~~~~~~~~~~
';?>
```

This is working for me...

**Comment by FizWork** [comment]
Already test : https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.5.1/trumbowyg.min.js
this problem still not solved... If cdnjs can run .htaccess, you can do like I did...
It's works without any error... :100:

**Comment by Alex-D** [comment]
That's a CDN, not an Apache + PHP server ^^
This kind of configuration is to do in the CDN dashboard or something like that.

**Comment by brentkelly** [comment]
@Alex-D while waiting for this fix, why don't you create an icon.svg.js file & get that put on the CDN. That file could just write the SVG contents into the DOM in a `trumbowyg-icons` as per your docs.

A little bit messy I know, but not as messy as loading half of trumbowyg off a CDN and having to either have the SVG in our HTML, or load it locally.

The user would then have the option to drop into their html:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.5.1/trumbowyg.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.5.1/icons.svg.js"></script>
```

**Comment by jakejohns** [comment]
@Alex-D @terinjokes @PeterDaveHello 

Any word here?

**Comment by PeterDaveHello** [comment]
@jakejohns I have zero permission on the server, so I can only wait for help from Cloudflare just like you, sorry.

**Comment by biswajitpaul01** [comment]
Use cdn from jsdelivr.
Here it is: https://www.jsdelivr.com/package/npm/trumbowyg

**Comment by MattIPv4** [comment]
Cloudflare are now investigating this. I will post any updates here as I get them. :)

**Comment by MattIPv4** [comment]
Similar request in #13019 where PNG files are missing CORS headers and causing issues in some use cases.

**Comment by MattIPv4** [comment]
Similar thing once again in #4724 where .map files are missing CORS.

**Comment by MattIPv4** [comment]
Cloudflare have deployed a fix and these file extensions now come with a CORS header 🎉
