### ISSUE TITLE
Add "ol-debug.min.js" option for ol3 library

### ISSUE THREAD

**Issue by tananaev** [cdnjs/cdnjs#7610]
Older versions (up to 3.14.2) had `ol-debug.min.js` option. New versions starting from 3.15.0 don't have it. What is the reason? Is it possible to add it back?

**Comment by PeterDaveHello** [comment]
Currently, we can't not find a minifier support that file, that's the reason why we didn't add it.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs

**Comment by PeterDaveHello** [comment]
Even Google's clousure compiler doesn't work with it:
https://closure-compiler.appspot.com
```
12: URL cdnjs.cloudflare.com/ajax/libs/ol3/3.15.1/ol-debug.js is not formed properly.
Original Post Data: 
output_format=json&output_info=compiled_code&output_info=warnings&output_info=errors&output_info=statistics&compilation_level=ADVANCED_OPTIMIZATIONS&warning_level=verbose&output_file_name=default.js&code_url=cdnjs.cloudflare.com%2Fajax%2Flibs%2Fol3%2F3.15.1%2Fol-debug.js&js_code=
```

**Comment by drewfreyling** [comment]
@PeterDaveHello what minifiers have we tried (other than closure)?

**Comment by PeterDaveHello** [comment]
Yes, UglifyJS doesn't work either, I usually use UglifyJS and YUICompressor.

As I and @drewfreyling said, @tananaev what do you think?

cc ol3 authors @twpayne @tschaub @ahocevar @elemoine @fredj, not sure if you can give us some comments, sorry for bothering if you don't like it.

**Comment by tananaev** [comment]
I'm actually using debug version in production because I have some extension to ol3 library and it won't work with release version of ol3. The only other option for me is to build custom version of the whole ol3 library.

**Comment by ahocevar** [comment]
ol.js is the minified build, currently compiled with the Closure compiler. ol-debug.js the unminified version for debugging. I think this issue should be closed.

**Comment by PeterDaveHello** [comment]
Thanks @ahocevar. @tananaev are we good to close this issue now?

**Comment by tananaev** [comment]
Yes, I think we can close it.

**Comment by PeterDaveHello** [comment]
Thank you guys.
