### ISSUE TITLE
[Request] jquery.mark

### ISSUE THREAD

**Issue by maxpower9000** [cdnjs/cdnjs#7613]
**jquery.mark** 
**https://github.com/julmot/jquery.mark/**
**MIT**
**https://jquerymark.io/**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @maxpower9000 ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t please don't forget to add labels next time.

**Comment by PeterDaveHello** [comment]
I think we can add it now.

**Comment by PeterDaveHello** [comment]
@julmot do you want to send a PR to add it by yourself or leave it for cdnjs team to add it?

**Comment by julmot** [comment]
Added as of https://github.com/cdnjs/cdnjs/commit/0c6009a32c0867de2ae79fadef290593a7b6edab

**Comment by PeterDaveHello** [comment]
Close per #8098

**Comment by julmot** [comment]
@PeterDaveHello Thank you very much!

**Comment by PeterDaveHello** [comment]
@julmot You're welcome.
