### ISSUE TITLE
jQuery 2.2.3 slim is empty

### ISSUE THREAD

**Issue by beruic** [cdnjs/cdnjs#7617]
[https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js](https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js) has no content

**Comment by drewfreyling** [comment]
@PeterDaveHello looks like the following files are not not there for jquery 2.2.3:

- https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js
- https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.min.js (this one is actually empty and not a 404)
- https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.min.map
- https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.map

**Comment by PeterDaveHello** [comment]
Not sure the reason why, but the first fetch of jquery's new version seems to have problem for several times ... I'm not sure if they republish after that, I'll re-fetch it.

**Comment by beruic** [comment]
I still cannot get [https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js](https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js) (It's empty).

Oh, and this is probably an error on Jquery's end, but why are the map files and `jqyery.slim.min.js` version 3.0.0-beta1 instead of 2.2.3?

**Comment by PeterDaveHello** [comment]
@terinjokes would you please help flush the cache on this file?
@beruic the version problem came from jquery.

**Comment by beruic** [comment]
Files are listed correctly now, however:
- [https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.map](https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.map) is version 3.
- [https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js](https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.slim.js) has no content

**Comment by PeterDaveHello** [comment]
Ping @terinjokes

**Comment by PeterDaveHello** [comment]
@thomasdavis @ryankirkman can you help us ping Cloudflare? Thanks.

**Comment by terinjokes** [comment]
@beruic We purged the cache for both of those URLs.

**Comment by PeterDaveHello** [comment]
@terinjokes Thanks.

**Comment by beruic** [comment]
Slim seems fixed, The map is still version 3, so this is probably a jQuery issue.

**Comment by PeterDaveHello** [comment]
Yep.

**Comment by drewfreyling** [comment]
@beruic feel freel to report it upsteam to the jquery guys for https://code.jquery.com/jquery-1.12.3.min.map
