### ISSUE TITLE
[Request] Add recompose

### ISSUE THREAD

**Issue by henry40408** [cdnjs/cdnjs#7620]
**Library name:** recompose
**Git repository url:** https://github.com/acdlite/recompose
**npm package url(optional):** https://www.npmjs.com/package/recompose
**License(s):** MIT (according to [`package.json`](https://github.com/acdlite/recompose/blob/master/package.json))
**Official homepage:** https://github.com/acdlite/recompose
**Wanna say something? Leave message here:** I ❤️  React.js and functional programming, they works better if works together.

**Comment by dannyxx001** [comment]
Wait for ready files for cdnjs.
[recompose_response](https://github.com/acdlite/recompose/issues/131)

**Comment by PeterDaveHello** [comment]
@dannyxx001 the text of your link looks strange, please use acdlite/recompose#131 instead.
