### ISSUE TITLE
API application error

### ISSUE THREAD

**Issue by david-mohr** [cdnjs/cdnjs#7623]
I was attempting to update my library for `cdnjs-cdn-data` and it kept failing. Manually entering the URL into the browser yields an application error: http://api.cdnjs.com/libraries?fields=name,assets,filename

Let me know if there's any other information I can provide.

**Comment by thomasdavis** [comment]
@ryankirkman you still awake to give that a restart?

**Comment by thomasdavis** [comment]
@david-mohr I think you are trying to request too much at once, any chance you can scope it?

**Comment by PeterDaveHello** [comment]
@david-mohr Maybe you can setup a local api server, and get the latest artifacts from cdnjs.com

**Comment by PeterDaveHello** [comment]
@thomasdavis Did you mean restart instance on heroku or something?

**Comment by thomasdavis** [comment]
Yeah nevermind I thought the server went down, but it was just that request.

**Comment by PeterDaveHello** [comment]
I'll take a look at it, since there are several deploys during this period, the instance has been restarted not only once.

**Comment by PeterDaveHello** [comment]
I just manually restarted it, let's see if this help.

**Comment by PeterDaveHello** [comment]
Hmmmm ... seems it doesn't work.

**Comment by PeterDaveHello** [comment]
Okay, it's the memory usage issue again ...

@cdnjs/owners  we'll need to make time to rewrite this as website's problem ...

```
Apr 19 10:52:12 cdnjsapi heroku/web.1: Process running mem=817M(159.6%) 
Apr 19 10:52:12 cdnjsapi heroku/web.1: Error R14 (Memory quota exceeded) 
```
```
Apr 19 10:52:32 cdnjsapi heroku/web.1: Process running mem=1276M(249.4%) 
Apr 19 10:52:32 cdnjsapi heroku/web.1: Error R15 (Memory quota vastly exceeded) 
```

@david-mohr at the mean time, is it possible for you to just download the whole data from https://cdnjs.com/packages.min.json to your local then work with it? Sorry for the inconvenience caused.

**Comment by PeterDaveHello** [comment]
Not sure if it will help it increase the dyno size on heroku, from the experience of the same problem of website instance, it obviously doesn't work, and we still don't know the reason why, but the website and api server they both work properly in local.

**Comment by david-mohr** [comment]
Thanks for the quick response.  I'll grab the whole data as you suggested and work with it locally.  Good luck with the memory usage issue!

**Comment by PeterDaveHello** [comment]
@david-mohr sorry for the late update, I did some modifications to make the memory usage lower, would you please try it again? Hope this works for you, thanks!

**Comment by david-mohr** [comment]
Looks good! Thanks for the update.

```
npm install cdnjs-cdn-data
cd node_modules/cdnjs-cdn-data/
npm install
./update.sh
```

**Comment by PeterDaveHello** [comment]
Thanks @david-mohr !
