### ISSUE TITLE
[Request] Show latest stable by default

### ISSUE THREAD

**Issue by CupOfTea696** [cdnjs/cdnjs#7624]
When looking for libraries on cdnjs, by default it will show the latest release regardless of stability. For jQuery for example, this means it shows `v3.3.0-beta1` rather than the latest stable release `v2.2.3`. I think it'd be better if it would show the latest stable rather than the unstable release.

**Comment by PeterDaveHello** [comment]
Hi @CupOfTea696, sorry for the late reply, yes we do it usually, only for the most popular lib will show the non-stable version.
