### ISSUE TITLE
[Request] Add cash

### ISSUE THREAD

**Issue by shshaw** [cdnjs/cdnjs#7625]
**Library name:** cash
**Git repository url:** https://github.com/kenwheeler/cash/
**npm package url(optional):** https://www.npmjs.com/package/cash-dom
**License(s):** MIT
**Official homepage:** https://github.com/kenwheeler/cash
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by shshaw** [comment]
Thank you!

**Comment by PeterDaveHello** [comment]
Thanks @shshaw
