### ISSUE TITLE
[Request] Add flipcountdown

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7627]
https://github.com/xdan/flipcountdown

**Comment by PeterDaveHello** [comment]
There are 7 releases on GitHub, but only the latest on npm, should also add the other versions.

**Comment by sashberd** [comment]
@PeterDaveHello The latest version now is also on git. Should we change autoupdate to git?

**Comment by MattIPv4** [comment]
No progress, library seems unmaintained. Closing.
