### ISSUE TITLE
[Request] Add Chained

### ISSUE THREAD

**Issue by WilliamIsted** [cdnjs/cdnjs#7634]
**Library name:** jquery_chained
**Git repository url:** https://github.com/tuupola/jquery_chained
**npm package url(optional):** https://www.npmjs.com/package/jquery-chained
**License(s):** MIT
**Official homepage:** http://www.appelsiini.net/projects/chained
**Wanna say something? Leave message here:** Thanks

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
@WilliamIsted Hello, thanks for your request. However, maybe next time you can follow the format to open an issue. Then we can know all the information more clearly and quickly. I had modified it this time, and you can take a look at it. Thanks for your collaboration. : )
