### ISSUE TITLE
[Request] Add turbolinks-classic

### ISSUE THREAD

**Issue by linusramos** [cdnjs/cdnjs#7635]
**Library name:** Turbolinks-classic
**Git repository url:** https://github.com/turbolinks/turbolinks-classic
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/turbolinks/turbolinks-classic
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nateberkopec** [comment]
Hey @dannyxx001 - hopefully this isn't too late and your internship is still ongoing!

`turbolinks-classic` and `turbolinks` are two different versions of the same project, kinda like two different forks. `turbolinks-classic` is sort of a legacy project and no longer under active development, but it may still be beneficial for some to add it to CDNjs. It would be appropriate to add it as `turbolinks` version `2.5.3`. The main `turbolinks` repository contains releases 5.0.0 and up.

**Comment by PeterDaveHello** [comment]
@nateberkopec thanks for your help, we'll look into it.

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by sashberd** [comment]
@PeterDaveHello We cannot add turbolinks-classic, it is swift library. FYI and FYR. Suggest to close

**Comment by extend1994** [comment]
Reference: https://www.npmjs.com/package/turbolinks
