### ISSUE TITLE
Let's discuss about why only popular libraries

### ISSUE THREAD

**Issue by ricardopolo** [cdnjs/cdnjs#7647]
I had always preffer CDNJs over jsDelivr.  
I dont have a particular reason, but I can see they have two features that CDNJs currently dont.

First, SRI integration. I know you are working on it and thats ok :)
Second, they allow you to host every project, font, etc, you only allow the more popular. So, this can be a deal breaker for some. Why that policy? If sometime I found a dependency that one of our project uses and they approved there but not CDNJs I think I would change.

Regards

**Comment by PeterDaveHello** [comment]
Hi @ricardopolo,

Good to see someone join discussion, as you can see, we are working on SRI and some other issues, and we indeed didn't have enough human resource to work on all the works, SRI is a very important feature we should support, so how can we balance these things? The popularity requirement. The popularity requirement on cdnjs, personally I don't think it's a high requirement, instead, it makes sure that the lib has its valuable to be hosted, if we host a lib without users using it, it will a little bit make no sense, the resource is not unlimited, we don't want to make cdnjs larger without the corresponding effects, like Google and Yahoo only provide few libraries, CDNJS likes to provide more, everything valuable, but not **that everything**, so we sometimes push some libs with potential even it dosn't have the popularity, and we usually accepect the libraries don't reach the gap but close to it, there is still a scope we accept, not that strict, we also accept discussion, as you can see we usually don't close issue directly, but we want to hear from the issuer and author for more possible, as far as I know, there are already services like [rawgit](https://rawgit.com) and [npmcdn](https://npmcdn.com/) that allow everything been served via their services, if a small library really need a cdn service, maybe rawgit and npmcdn could be a start, and once the lib has about 100 stars or 500 downloads per month on npm, we'll be very happy to add it.

My English skill is not so good, I have not enough vocabulary to help me explain precisely, but hope you can understand there are difficulties ... cc @cdnjs/team-cdnjs

**Comment by drewfreyling** [comment]
There is also the upkeep aspect too. If we host all open source code everywhere we still have to maintain it and make sure it is up to date, so it is a quality thing too. I fully agree with @PeterDaveHello  here. Also, it isn't like the requirement is a high lofty goal, it is mainly just to weed out hosting anything that might only be valuable to one person.

**Comment by PeterDaveHello** [comment]
@drewfreyling Thanks :smile:

**Comment by drewfreyling** [comment]
The popularity requirement isn't a hard and fast rule either, if you submit a PR and can provide a damn good reason for adding it even though it might have the popularity yet, I'm sure the team would be willing to accept it.

**Comment by PeterDaveHello** [comment]
@ricardopolo BTW, though jsdelivr doesn't have a requirement about popularity, we still have mpre libraries, so that I really don't think that's that matter.

**Comment by ricardopolo** [comment]
Thanks for your kindness an willing to accept comments about how to manage the project.

I understand that manageability would be difficult and quality is more important. And understand the limited time resources.

So I would do this:

1. Allow request for adding a library with the name, license, etc, only for popular repos. This way only time resources are used in relevant things.
2. Allow all libraries if the creator (or interested) upload in a PR form. With bower and auto update. This way we enable the small developer who wants to offer his project to the world in the best way, and dont add overhead to the project. Just work for the auto update bot :)

**Comment by ricardopolo** [comment]
@PeterDaveHello any comment?

**Comment by PeterDaveHello** [comment]
> Allow all libraries if the creator (or interested) upload in a PR form. With bower and auto update.

I don't really like this, actually, you can take a simple trace of the requests from authors, we usually make the gap smaller/easier for the authors, we also try to push some small libs, we are not so hard or tough to ask for the 100 stars or 500 downloads per month on npm, my English is not so good to explain well ... I know that you want to push some small libs, but ... I believe a cool lib won't have only a hundred stars, even it'll need one more week, as we won't directly close the issues, but will wait for a week.
