### ISSUE TITLE
[Request]enzyme

### ISSUE THREAD

**Issue by BernardDoherty** [cdnjs/cdnjs#7651]
enzyme
https://github.com/airbnb/enzyme
https://www.npmjs.com/package/enzyme
http://airbnb.io/enzyme/
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
I think it needs Browserify, let's close it until it's officially supported by its authors.
