### ISSUE TITLE
[Request] update jquery.uniform

### ISSUE THREAD

**Issue by shehi** [cdnjs/cdnjs#7660]
**Library name:** jquery.uniform
**Git repository url:** https://github.com/AudithSoftworks/Uniform
**npm package url(optional):** https://www.npmjs.com/package/jquery.uniform
**License(s):** MIT
**Official homepage:** http://opensource.audith.org/uniform
**Wanna say something? Leave message here:** I am the owner and would like my package to be added to CDNjs.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by shehi** [comment]
Btw, https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Uniform.js is the same package as this one.

**Comment by PeterDaveHello** [comment]
@shehi Thanks. We should not duicated this lib if it is the same.

**Comment by PeterDaveHello** [comment]
@pvnr0082t can you take a look?

**Comment by pvnr0082t** [comment]
@PeterDaveHello Sure, I'll take a look.

**Comment by PeterDaveHello** [comment]
@pvnr0082t seems you should only add auto-update config on it, let's update this ASAP.
