### ISSUE TITLE
[Request] Add twemoji-awesome

### ISSUE THREAD

**Issue by abr4xas** [cdnjs/cdnjs#7663]
**Library name**: twemoji-awesome
**Git repository url**: https://github.com/abr4xas/twemoji-awesome
**npm package url(optional)**: https://www.npmjs.com/package/twemoji-awesome
**License(s)**: MIT
**Official homepage**:

**Comment by ajsb85** [comment]
+1

**Comment by JMEspiz** [comment]
+1

**Comment by pvnr0082t** [comment]
hi @abr4xas ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by abr4xas** [comment]
Hey @pvnr0082t Thank you. :+1:
