### ISSUE TITLE
[Request] Add Countable

### ISSUE THREAD

**Issue by johnsmeeth** [cdnjs/cdnjs#7667]
**Library name:** Countable
**Git repository url:** https://github.com/RadLikeWhoa/Countable
**npm package url(optional):** https://www.npmjs.com/package/countable
**License(s):** MIT
**Official homepage:** https://sacha.me/Countable/
**Wanna say something? Leave message here:** Please add this to your cdn

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by johnsmeeth** [comment]
@dannyxx001  @PeterDaveHello greate. many thanks

**Comment by PeterDaveHello** [comment]
@johnsmeeth You are welcome.
