### ISSUE TITLE
[Request] getmdl-select

### ISSUE THREAD

**Issue by pergamino** [cdnjs/cdnjs#7669]
getmdl-select
https://github.com/CreativeIT/getmdl-select

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @pergamino ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.
cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
Close issue because of not enough popularity.
