### ISSUE TITLE
[Request] Add Polymer

### ISSUE THREAD

**Issue by ghost** [cdnjs/cdnjs#7671]
*_Library name: Polymer 1.0 (from google)
*_Git repository url:https://github.com/Polymer/polymer
*_npm package url(optional): 
*_License(s):Open Source
*_Official homepage: https://www.polymer-project.org/1.0/
*_Wanna say something? Leave message here: THANK YOU !! :)
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t

**Comment by pvnr0082t** [comment]
@PeterDaveHello This library developed using `html` but cdnjs does not support html. Can this be added?

**Comment by PeterDaveHello** [comment]
Would you please confirm that what are the the files should be hosted first? Then we can discuss about how to deal with it, thanks.

**Comment by MattIPv4** [comment]
Dupe #4973
