### ISSUE TITLE
[Request] Add Minimality

### ISSUE THREAD

**Issue by davaakhuu** [cdnjs/cdnjs#7711]
**Library name:** Minimality
**Git repository url:** https://github.com/minimality/minimality
**npm package url(optional):** https://www.npmjs.com/package/minimality
**License(s):** ISC
**Official homepage:** minimality.github.io
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @davaakhuu , `https://github.com/minimality/minimality` does not exist. 

According to npm, this library doesn't have enough notable popularity(like more than 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
Close issue because of not enough popularity.
