### ISSUE TITLE
[Request] Add Minimality

### ISSUE THREAD

**Issue by davaakhuu** [cdnjs/cdnjs#7712]
**Library name: Minimality
**Git repository url: https://github.com/minimality/minimality
**npm package url(optional): https://www.npmjs.com/package/minimality
**License(s): 
**Official homepage: minimality.github.io
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
This is the same issue as #7711 . I think one issue is enough, so I close it.
