### ISSUE TITLE
[Request] Add gridster.js

### ISSUE THREAD

**Issue by rcastley** [cdnjs/cdnjs#7713]
**Library name:** jquery.gridster.min.css 
**Git repository url:** https://github.com/ducksboard/gridster.js/blob/master/dist/jquery.gridster.min.css
**npm package url(optional):** https://www.npmjs.com/package/gridster
**License(s):** MIT
**Official homepage:** http://gridster.net/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
I think this library is already in cdnjs. See [here](https://cdnjs.com/libraries/jquery.gridster).
@PeterDaveHello please help me review, thanks.

**Comment by PeterDaveHello** [comment]
Correct.

**Comment by rcastley** [comment]
Hi, Thank you for reviewing, however this was a request to add the CSS file for use with gridster.js. I am already using the JS from your site but it would be great if you could also host the CSS file. Would you be open to reconsidering my request?

Many thanks,
- Robert

**Comment by rcastley** [comment]
Actually, ignore that request. The CSS was not showing up in the search but manually typing in the URL finds it. Apologies for wasting your time :-(

**Comment by PeterDaveHello** [comment]
@rcastley no problem
