### ISSUE TITLE
[Request] Add jqvmap

### ISSUE THREAD

**Issue by huyannet** [cdnjs/cdnjs#7716]
**Library name:** jqvmap 
**Git repository url:** https://github.com/manifestinteractive/jqvmap/
**npm package url(optional):** https://www.npmjs.com/package/jqvmap
**Official homepage:** http://jqvmap.com/

**Comment by pvnr0082t** [comment]
@PeterDaveHello When I use ```npm install jqvmap```, NPM installation failed as the same problem as this [issue](https://github.com/manifestinteractive/jqvmap/issues/217). I need to install by using ```npm install --save github:manifestinteractive/jqvmap```. In this case, can we still use **npm auto-update config**? Or we need to use git auto-update?

**Comment by PeterDaveHello** [comment]
You can directly download the tar ball of this lib, in fact, we don't need to really "install" it, just need to extract it.
