### ISSUE TITLE
[Request] Add salesforce-lightning-design-system

### ISSUE THREAD

**Issue by 3den** [cdnjs/cdnjs#7719]
**Library name:** salesforce-lightning-design-system
**Git repository url:** https://github.com/salesforce-ux/design-system
**npm package url:**  @salesforce-ux/design-system

**Licenses:**
* Source code is licensed under [BSD License Clause 2](http://opensource.org/licenses/BSD-2-Clause)
* All icons and images are licensed under [Creative Commons Attribution-NoDerivatives 4.0](http://creativecommons.org/licenses/by-nd/4.0/)
* The font is licensed under our [font license](https://www.lightningdesignsystem.com/assets/licenses/License-for-font.txt)
**Official homepage:** https://www.lightningdesignsystem.com

**Comment by maruilian11** [comment]
duplicated with https://github.com/cdnjs/cdnjs/issues/6573
