### ISSUE TITLE
[Request] Add css3-animate-it

### ISSUE THREAD

**Issue by shinoamakusa** [cdnjs/cdnjs#7730]
**Library name:** css3-animate-it
**Git repository url:** https://github.com/Jack-McCourt/css3-animate-it
**npm package url(optional):**
**License(s):** MIT
**Official homepage:** http://css3-animate-it.jackonthe.net
**Wanna say something? Leave message here:**

**Comment by dannyxx001** [comment]
@shinoamakusa 
Sorry, this library doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our README.md for detail. We suggest you open a issue again when the repo has notable popularity. Thanks for your collaboration. : )

This issue will be closed if there is no any response in next 7 days.
If there is any other possibility to add this lib, we may discuss with adding it.

@PeterDaveHello please help me review this issue, thanks.

**Comment by PeterDaveHello** [comment]
hmmm ... looks close, and with valid version tags, ok, let's add this.

**Comment by shinoamakusa** [comment]
Even as it is not my p;ugin, but thank you for consideration. I want to add this plugin to my sites and having all my plugins on one cdn would help and it is no rush :smile:

**Comment by PeterDaveHello** [comment]
np
