### ISSUE TITLE
[Request] Add angular-gage

### ISSUE THREAD

**Issue by Grayda** [cdnjs/cdnjs#7738]
**Library name:** angular-gage
**Git repository url:** https://github.com/frapontillo/angular-gage
**npm package url(optional):** n/a
**License(s):** Apache 2.0
**Official homepage:** n/a
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @Grayda ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.
cc @PeterDaveHello

**Comment by sashberd** [comment]
Hi @Grayda 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
