### ISSUE TITLE
[Request] add angular-imgcache.js

### ISSUE THREAD

**Issue by ranjankumarpatel** [cdnjs/cdnjs#7742]
**Library name:** angular-imgcache.js
**Git repository url:** https://github.com/jBenes/angular-imgcache.js
**npm package url(optional):**
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message 
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
@PeterDaveHello
Would you please help me decide whether to add it or not? Because this library doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples).
If there is any other possibility to add this lib, we may discuss with adding it.

**Comment by Amomo** [comment]
Hi @ranjankumarpatel 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
Let's add this lib.

**Comment by Amomo** [comment]
ok!

**Comment by damrem** [comment]
https://github.com/jBenes/angular-imgcache.js is an angularjs wrapper for https://github.com/chrisben/imgcache.js/ so it seems necessary to cdnify it as well: https://github.com/cdnjs/cdnjs/issues/11309
