### ISSUE TITLE
[Request] jquery.cookieBar

### ISSUE THREAD

**Issue by bnomei** [cdnjs/cdnjs#7748]
**Library name:** 
jquery.cookieBar
**Git repository url:**
https://github.com/carlwoodhouse/jquery.cookieBar
**npm package url(optional):** 
**License(s):**
MIT
https://github.com/carlwoodhouse/jquery.cookieBar/blob/master/license.txt
**Official homepage:**
https://github.com/carlwoodhouse/jquery.cookieBar
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @bnomei ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
@bnomei Oh! I found this issue is the same as #7456. So I will close this issue.
