### ISSUE TITLE
[Request] Add jsdiff

### ISSUE THREAD

**Issue by sbrl** [cdnjs/cdnjs#7750]
**Library name:** jsdiff
**Git repository url:** https://github.com/kpdecker/jsdiff
**npm package url(optional):** https://www.npmjs.com/package/diff
**License(s):** BSD
**Official homepage:** http://kpdecker.github.io/jsdiff/
**Wanna say something? Leave message here:** This seems to be the best js-based unified diff utility out there at the moment that I can find. It would be seriously handy if cdnjs hosted this, as all the other CDNs have a terribly outdated copy of this library :(

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @sbrl , This issue duplicate with #7127.

**Comment by sbrl** [comment]
@pvnr0082t Oops! Since I've included more information here than has been added there, should I copy my description over there and close this one?

**Comment by pvnr0082t** [comment]
@sbrl  Yeah, I think it will be good to do that. Thank you. :+1:

**Comment by sbrl** [comment]
@pvnr0082t Done. For future reference, issue #7127 is the new issue tracking the addition of this library.
