### ISSUE TITLE
[Request] Add gifshot 

### ISSUE THREAD

**Issue by zherring** [cdnjs/cdnjs#7767]
**Library name:** gifshot
https://github.com/yahoo/gifshot#quick-start
https://github.com/yahoo/gifshot/blob/master/LICENSE.txt
https://yahoo.github.io/gifshot/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by haydenbleasel** [comment]
I was literally about to suggest this!
