### ISSUE TITLE
[Request] Add leaflet.toolbar.js 

### ISSUE THREAD

**Issue by ckhung** [cdnjs/cdnjs#7779]
**Library name:** leaflet.toolbar.js
**Git repository url:** https://github.com/Leaflet/Leaflet.toolbar
**npm package url(optional):** https://www.npmjs.com/package/leaflet-toolbar
**License(s):** MIT
**Official homepage:** https://github.com/Leaflet/Leaflet.toolbar
**Wanna say something? Leave message here:** Thank you!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @ckhung ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t we can add this.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Got it.

**Comment by ckhung** [comment]
Thanks!
