### ISSUE TITLE
[Request] Add kbdfun.css 

### ISSUE THREAD

**Issue by explor3r** [cdnjs/cdnjs#7782]
**Library name:** kbdfun.css
**Git repository url:** https://github.com/kremalicious/kbdfun
**npm package url(optional):**  N/A
**License(s):** MIT license
**Official homepage:** https://kremalicious.com/using-kbd-for-fun-and-profit/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dannyxx001** [comment]
@explor3r 
Sorry, this library doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our README.md for detail. We suggest you open a issue again when the repo has notable popularity. Thanks for your collaboration. : )

This issue will be closed if there is no any response in next 7 days.
If there is any other possibility to add this lib, we may discuss with adding it.

@PeterDaveHello please help me review this issue, thanks.

**Comment by explor3r** [comment]
@dannyxx001 
I was directed to the "New Issue" page from cdnjs website... so I didn't really know about the rules about popularity... 
Sorry about the inconvenience!

**Comment by PeterDaveHello** [comment]
@explor3r it's okay.
