### ISSUE TITLE
How fast the library is updated to newest version?

### ISSUE THREAD

**Issue by jcubic** [cdnjs/cdnjs#7786]
I've publish new version of jQuery Terminal and I want to include cdnjs in a readme but the cdnjs latest version of one behind. How fast it will be updated? Is this automatic from npm (like the tag "npm autoupdate enabled" says) or manual?

**Comment by PeterDaveHello** [comment]
@jcubic usually 15 mins,  jQuery Terminal  didn't been updated because the structure changed, so the bot won't automatically add it, as you can see, I manually commit it in aacf2f3, if the structure won't been changed, the next update can be very fast!
