### ISSUE TITLE
[Request] Add ichart.1.2.min.js 

### ISSUE THREAD

**Issue by chayanjana20** [cdnjs/cdnjs#7791]
**Library name:** ichart.1.2.min.js
**Git repository url:** https://github.com/wanghetommy/ichartjs
**npm package url(optional):** 
**License(s):**apache license 2.0
**Official homepage:** http://www.ichartjs.com
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@chayanjana20 
Any detail?

**Comment by PeterDaveHello** [comment]
@x09326 take a look at this: https://github.com/wanghetommy/ichartjs

**Comment by sashberd** [comment]
@PeterDaveHello Still no answer from author. maybe we could add [1.1](https://github.com/wanghetommy/ichartjs/tree/ichartjs1.1) and [1.2](https://github.com/wanghetommy/ichartjs/tree/ichartjs1.2) manually

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
