### ISSUE TITLE
Update the DOC about the easier way to add libs via single package.json only

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7793]
Since the repo is too fat, we actually support submit PR to add a lib with only one single package.json without real files, so the users don't need to clone the repo locally, just do the commit and PR on GitHub.

Example:
https://github.com/cdnjs/cdnjs/pull/7149 by @PeterDaveHello
https://github.com/cdnjs/cdnjs/pull/7725 by @pakastin 
cc #3941

**Comment by pakastin** [comment]
I actually started cloning the repo first, but canceled it and searched for a better way 😂

Using a single package.json was really simple. 👍

**Comment by pakastin** [comment]
..I ended up using just the Github's web interface — really straight forward.

**Comment by PeterDaveHello** [comment]
@pakastin I wonder if you would like to improve the document to talk about this part :smile:

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 @cdnjs/intern everyone who is interested in this issue please just take it!

**Comment by maruilian11** [comment]
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson
