### ISSUE TITLE
[Request] Add Firebase

### ISSUE THREAD

**Issue by jeffmicklos** [cdnjs/cdnjs#7795]
**Library name:** Firebase 
**Git repository url:** https://github.com/firebase/firebase-bower
**npm package url(optional):** https://www.npmjs.com/package/firebase
**License(s):** https://www.firebase.com/terms/terms-of-service.html
**Official homepage:** https://www.firebase.com/
**Wanna say something? Leave message here:** I can currently pull this via jsdelivr but I would, obviously, rather use cdnjs! See their usage [here](https://www.jsdelivr.com/projects/firebase).

❤️ ❤️

**Comment by pvnr0082t** [comment]
Hi @jeffmicklos  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t it's just a web client of a popular project, you can take a look at https://github.com/firebase, we should add this lib!

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay, I got it.

**Comment by joshreisner** [comment]
+1
