### ISSUE TITLE
[Request][Author] Add log4sure

### ISSUE THREAD

**Issue by bsurela** [cdnjs/cdnjs#7796]
**log4sure:** 
_https://github.com/bsurela/log4surejs.git:_*
**MIT**
**http://log4sure.com**
**Updating log4sure for relaunch, would be nice to have a cdn url for the js:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @bsurela  ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 
I suggest to close this issue. The lib popularity did not changed since the issue was opened
FYR

**Comment by sufuf3** [comment]
@sashberd Thanks.
Closed due to no response from the author in 7 days. cc @PeterDaveHello
