### ISSUE TITLE
[Request] Add scorocode

### ISSUE THREAD

**Issue by NikSmith** [cdnjs/cdnjs#7800]
**Library name: scorocode** 
**Git repository url: https://github.com/Scorocode/scorocode-SDK-JS**
**npm package url(optional): scorocode** 
**License(s): MIT**
**Official homepage: scorocode.ru**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
hi @NikSmith  ,
this lib doesn't have enough popularity(100 watch or star or 300 downloads in the last month on npm is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello
