### ISSUE TITLE
[Request] Add readremaining.js

### ISSUE THREAD

**Issue by J2TeaM** [cdnjs/cdnjs#7804]
**Library name:** readremaining.js
**Git repository url:** https://github.com/Aerolab/readremaining.js
**npm package url(optional):** (none)
**License(s):** MIT
**Official homepage:** http://aerolab.github.io/readremaining.js/

**Comment by dannyxx001** [comment]
duplicate issue [cdnjs/#7585](https://github.com/cdnjs/cdnjs/issues/7585)

**Comment by J2TeaM** [comment]
@dannyxx001 yes, this is a duplicate request!
