### ISSUE TITLE
[Request] Add sprint

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7814]
**Library name:** sprint
**Git repository url:** https://github.com/bendc/sprint

**Comment by pvnr0082t** [comment]
@PeterDaveHello This issue is duplicated with #7776.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Okay, thanks!

**Comment by PeterDaveHello** [comment]
@pvnr0082t you can directly close this kind of issues next time, so you can have new archive on [getbadges](https://cdnjs-cdnjs.getbadges.io/?ref=shield-game)
