### ISSUE TITLE
[Request] Add jszip-utils 

### ISSUE THREAD

**Issue by Gompels** [cdnjs/cdnjs#7819]
**Library name:** jszip-utils
**Git repository url:** https://github.com/Stuk/jszip-utils
**npm package url(optional):** 
**License(s):** JSZipUtils is dual-licensed. You may use it under the MIT license or the GPLv3 license. See LICENSE.markdown.
**Official homepage:** http://stuk.github.io/jszip-utils/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Gompels ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t we can add this.
