### ISSUE TITLE
[Request] Filterizr

### ISSUE THREAD

**Issue by lhvolso** [cdnjs/cdnjs#7820]
**Library name:** 
Filterizr
**Git repository url:**
https://github.com/giotiskl/Filterizr
**npm package url(optional):**  https://www.npmjs.com/package/filterizr
**License(s):**
Filterizr is licensed under the MIT License (i.e. you do whatever you want with it). Enjoy!
**Official homepage:**
http://yiotis.net/filterizr/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
hi @lhvolso  ,
this lib doesn't have enough popularity(100 watch or star is a good example).
Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.
Thanks.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks close to the requirement, we can wait for a while.
