### ISSUE TITLE
[Request] Add smooth-scrollbar 

### ISSUE THREAD

**Issue by brunowego** [cdnjs/cdnjs#7823]
**Library name:** smooth-scrollbar
**Git repository url:** https://github.com/idiotWu/smooth-scrollbar
**npm package url(optional):** https://www.npmjs.com/package/smooth-scrolling
**License(s):** MIT
**Official homepage:** http://idiotwu.github.io/smooth-scrollbar/
**Wanna say something? Leave message here:** This is a powerful plugin to add custom scroll.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@brunowego I think you give the wrong npm package url. The smooth-scrollbar correspond to https://www.npmjs.com/package/smooth-scrollbar

**Comment by idiotWu** [comment]
Oh thanks @brunowego ! Big hug for you!
