### ISSUE TITLE
[Request] Add colorfilter 

### ISSUE THREAD

**Issue by Raikhen** [cdnjs/cdnjs#7826]
**Library name:** colorfilter
**Git repository url:** https://github.com/LukyVj/colofilter.css
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://lukyvj.github.io/colofilter.css/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by LukyVj** [comment]
Should be good guys.
