### ISSUE TITLE
[Request] Add bootstrap-table-export.js 

### ISSUE THREAD

**Issue by suchitasalunkhe** [cdnjs/cdnjs#7830]
**Library name:** bootstrap-table-export.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
What's the detail?

**Comment by PeterDaveHello** [comment]
Close due to no response.
