### ISSUE TITLE
[Request] YUI CSS Reset

### ISSUE THREAD

**Issue by mantissefr** [cdnjs/cdnjs#7831]
**Library name:**  YUI CSS Reset
**Git repository url:** https://github.com/yui/yui3
**npm package url(optional):** 
**License(s):** https://raw.githubusercontent.com/yui/yui3/master/LICENSE.md
**Official homepage:** http://yuilibrary.com/yui/docs/cssreset/
**Wanna say something? Leave message here: YUI Library is in CDNJS repository, (of course), maybe, it is interesting to propose only this library to use apart from the rest of the web design framework. **

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @mantissefr , This library has already been hosted on cdnjs. https://cdnjs.com/libraries/yui

**Comment by PeterDaveHello** [comment]
@pvnr0082t : 
> YUI Library is in CDNJS repository, (of course), maybe, it is interesting to propose only this library to use apart from the rest of the web design framework

**Comment by PeterDaveHello** [comment]
@mantissefr I didn't really get your point, you want the cssreset part be hosted individually?

**Comment by pvnr0082t** [comment]
Oh, sorry. I didn't see that.

**Comment by mantissefr** [comment]
Hello cdnjs,

That is to say that when I was searching for a https link to the CSS reset css file, I found that only on github.

Here is the link https://raw.githubusercontent.com/yui/yui3/25264e3629b1c07fb779d203c4a25c0879ec862c/src/cssreset/css/cssreset.css

Of course there are a lot of components in the YUI library, but proposing them individually if they don't have any dependencies would be great up to me.

To be honest, I don't know much about this web framework yet but I am now ready to discover it using it in my web apps projects.

All the best,

mantissefr

**Comment by PeterDaveHello** [comment]
@mantissefr doesn't this help you? https://cdnjs.cloudflare.com/ajax/libs/yui/3.18.0/cssreset/cssreset-min.css

**Comment by mantissefr** [comment]
Hello,

Maybe the link exists now, I did not check.

What will help me is to work and learn with and from YUI.

Bye

-----Message d'origine-----
De : "Peter Dave Hello" <notifications@github.com>
Envoyé : ‎07/‎07/‎2016 07:11
À : "cdnjs/cdnjs" <cdnjs@noreply.github.com>
Cc : "mantissefr" <jose.desgris@gmail.com>; "Mention" <mention@noreply.github.com>
Objet : Re: [cdnjs/cdnjs] [Request] YUI CSS Reset (#7831)

@mantissefr doesn't this help you? https://cdnjs.cloudflare.com/ajax/libs/yui/3.18.0/cssreset/cssreset-min.css
