### ISSUE TITLE
[Request] Add wdtLoading 

### ISSUE THREAD

**Issue by microdesign** [cdnjs/cdnjs#7832]
**Library name:** wdtLoading
**Git repository url:**https://github.com/needim/wdtLoading
**npm package url(optional):** https://www.npmjs.com/package/wdt-loading
**License(s):**
**Official homepage:**http://ned.im/wdtLoading/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@microdesign 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by microdesign** [comment]
No problem thanks

**Comment by PeterDaveHello** [comment]
I think we can add this lib.

**Comment by x09326** [comment]
Got it.
