### ISSUE TITLE
What would happen if we add a Cname to CDNJS

### ISSUE THREAD

**Issue by ricardopolo** [cdnjs/cdnjs#7833]
If one time our app is locked by  a firewall, we would required to open our domain.
But now that we are using CDNjs, we would need to open the cloudflare domain too.

So... do you know about which classification the domain of CDNJs has?
If we add a DNS Cname to your domain, like cdn.ourdomain.com, we would still have all the advantages of CDNJS? (Understating that users wont benefit for pre fetch from another website).

Thanks

**Comment by PeterDaveHello** [comment]
@ricardopolo cdnjs.com, *.cdnjs.com, cdnjs.cloudflare.xom, I don't suggest you to use cname since it will have problem with the https certs, though you can use http instead of https, then you can not benefit from http/2.0 and you know https is secure but http is not.
