### ISSUE TITLE
[Request] Add Ajax-Bootstrap-Select

### ISSUE THREAD

**Issue by ImJustToNy** [cdnjs/cdnjs#7838]
**Library name:** Ajax-Bootstrap-Select
**Git repository url:** https://github.com/truckingsim/Ajax-Bootstrap-Select
**npm package url(optional):** https://www.npmjs.com/package/ajax-bootstrap-select
**License(s):** MIT
**Official homepage:** https://github.com/truckingsim/Ajax-Bootstrap-Select
**Wanna say something? Leave message here:** ---

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@ImJustToNy 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
Looks okay to add this, btw you can ask the author for the minified css file first.

**Comment by truckingsim** [comment]
@PeterDaveHello @x09326 auth of said package.  CSS has been minified starting with release/tag v1.3.5.

**Comment by PeterDaveHello** [comment]
Thanks @truckingsim
