### ISSUE TITLE
Google fonts in CDNJs

### ISSUE THREAD

**Issue by ricardopolo** [cdnjs/cdnjs#7845]
We love CDNJs and would love to have all of our resources here. Not using multiple CDNS. This way you relay only in Cloudflare and have HTTP/2 for download all external resources in one request.

Currently we are downloading fonts from Google from their CDN. Any way we can copy that fonts to CDNJ?

**Comment by PeterDaveHello** [comment]
Yes, it is possible, but we need a stable upsteam for the files, I am not sure if we have enough resource on maintain this by ourselves, do you have any suggestions?

cc @cdnjs/team-cdnjs

**Comment by ricardopolo** [comment]
https://github.com/google/fonts
https://google-fonts.azurewebsites.net/

**Comment by skibulk** [comment]
https://github.com/cdnjs/cdnjs/issues/682

**Comment by drewfreyling** [comment]
Sounds like there is alot of complexities here due to technical as well as possible legal aspects.

**Comment by ricardopolo** [comment]
:(... so it will be closed, i guess

**Comment by PeterDaveHello** [comment]
hmmmm ... I'll like to host it once the problems been solved ... closing this issue is the last option for me.

**Comment by drewfreyling** [comment]
There is no git tags or npm releases as far as I can tell so how do we know when to update?

**Comment by PeterDaveHello** [comment]
maybe just manually do it ... but we need to figure out how to add this lib first.

**Comment by terinjokes** [comment]
Right now we can't do the per-browser optimizations, so end users would lose a huge benefit from the Google CDN.

**Comment by skibulk** [comment]
There are several fonts on Font Squirrel that would benefit from a CDN
(Some are hosted by Google, others are not). All of these fonts are free
for commercial use, although I don't believe they have a centralized
repository... https://www.fontsquirrel.com/

**Comment by drewfreyling** [comment]
I'd consider this closed then @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@ryankirkman @thomasdavis do you guys have any comments?

**Comment by InnovativeInventor** [comment]
@PeterDaveHello @drewfreyling @skibulk @ricardopolo @terinjokes 
It seems like there aren't any legal issues. On [Google Font's README](https://github.com/google/fonts#user-content-self-host-fonts-available-from-google-fonts), it says:

Since all the fonts available here are licensed with permission to redistribute, subject to the license terms, you can self-host. 

I'm all for hosting Google Fonts on cdnjs in order to avoid using multiple cdns!

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
