### ISSUE TITLE
[Request] Add trimpath-template

### ISSUE THREAD

**Issue by curtkim** [cdnjs/cdnjs#7847]
**Library name:** trimpath-template
**Git repository url:** https://github.com/wankdanker/node-trimpath-template
**npm package url(optional):** https://www.npmjs.com/package/trimpath-template
**License(s):** GPL, Apache 2.0
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
hi @curtkim ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can wait for a while since the npm download stats looks close to the requirement.

**Comment by kennynaoh** [comment]
@PeterDaveHello ,
I think the popularity is not enough.
Should we close it?or keep waiting?
Thanks!

**Comment by PeterDaveHello** [comment]
It's been a while, so maybe it's time to close it.

**Comment by kennynaoh** [comment]
close due to not enough popularity.
Thanks @curtkim
