### ISSUE TITLE
Point out minimum stars/watchers/forks in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Thermisen75** [cdnjs/cdnjs#7849]
This will avoid issues or pull requests about libraries with low popularity

**Comment by PeterDaveHello** [comment]
I thought we have it, don't we?

https://github.com/cdnjs/cdnjs/commit/dc6a43201cfa6e3b7d85b687ddf603592953325c#diff-04c6e90faac2675aa89e2176d2eec7d8
https://github.com/cdnjs/cdnjs/commit/e777483ae63c711d4fbfaa0c95b25aa86b7835b3

**Comment by Thermisen75** [comment]
@PeterDaveHello From my point of view things that are related to issues or pull requests should be documented in CONTRIBUTING.md, not in README.md.  
Take this use case: I know cdnjs and would like to request a new library. Therefore I click the "Request a lib" button and can now start creating the issue. Before, I read the CONTRIBUTING.md and as there is no mention about minimum stars/watchers, I assume that my lib is ok. Now, you want me to read the README.md that is not in a relationship to it. Gotcha.

**Comment by PeterDaveHello** [comment]
@Thermisen75 You are right, thanks, will you like to send a PR to help us add it?

**Comment by sufuf3** [comment]
Here we were done.
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library
IMO, maybe we can open an issue at cdnjs/new-website and add this in the template.
Such as, 
```
**Library name:** 
**Library desctiption:** 
**Git repository url:** 
**npm package name or url** (if there is one): 
**License (List them all if it's multiple):** 
**Official homepage:** 
**Wanna say something? Leave message here:** 

=====================

Notes from cdnjs maintainer(please remove this section after you read it):
1. Please read the README.md and CONTRIBUTING.md document first.
2. For the new library request issue, please make sure it's not a personal project, we have a basic requirement for the popularity, like 200 stars on GitHub or 800 downloads/month on npm registry.

We encourage you to add a library via sending pull request,
it'll be faster than just opening a request issue,
since there are tons of issues, please wait with patience,
and please don't forget to read the guidelines for contributing, thanks!!
```

Because we solved this issue, I'll close this issue.
cc @PeterDaveHello
