### ISSUE TITLE
simple-line-icons (2.3.1) missing .woff2 file

### ISSUE THREAD

**Issue by mikesonnenberg** [cdnjs/cdnjs#7856]
NetworkError: 404 Not Found - https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.3.1/fonts/Simple-Line-Icons.woff2?v=2.3.1

It is referenced from the css file in the library.

**Comment by PeterDaveHello** [comment]
@mikesonnenberg thanks for report!
