### ISSUE TITLE
[Request] Add titatoggle 

### ISSUE THREAD

**Issue by truekasun** [cdnjs/cdnjs#7859]
**Library name:** titatoggle
**Git repository url:** https://github.com/kleinejan/titatoggle
**npm package url(optional):** 
**License(s):** BSD-2-Clause
**Official homepage:** http://kleinejan.github.io/titatoggle/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @truekasun ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
hmmm ... let's add this.

**Comment by pvnr0082t** [comment]
OK!

**Comment by truekasun** [comment]
Hi @pvnr0082t ,
I'm sorry for not reading the README.md of cdnjs. I was searching for the requested repository on cdnjs.com and when it wasn't found in the website, I saw a link called "Would you like to request it?" then I went through the link and came here. There was no mention about the README or the required stars and downloads. I'm really sorry for not reading your requirements and I suggest you to mention it in the request form.
Also there is no personal favor to add this repository to the cdnjs since I already have get catered my requirement with offline files. The idea behind this request was I thought it would be useful for someone else who use cdnjs.

@PeterDaveHello , Thank you for your consideration to add this repository.

**Comment by PeterDaveHello** [comment]
@truekasun we'll improve the process of reminding about the popularity, thanks.
