### ISSUE TITLE
[Request] Add browser-logos 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7865]
**Library name:** browser-logos
**Git repository url:** https://github.com/alrra/browser-logos

**Comment by maruilian11** [comment]
@PeterDaveHello the author said this is just a collection of images, it's not a JavaScript/CSS library.
do we still add this lib?
https://github.com/alrra/browser-logos/issues/83#issuecomment-219396973

**Comment by PeterDaveHello** [comment]
Yes we can host it.
