### ISSUE TITLE
[Request] wow.js (MIT forever free)

### ISSUE THREAD

**Issue by graingert** [cdnjs/cdnjs#7866]
**Library name:** wow.js
**Git repository url:** https://github.com/graingert/WOW.git
**npm package url(optional):** https://www.npmjs.com/package/wow.js
**License(s):** MIT
**Official homepage:** https://wow.js.org
**Wanna say something? Leave message here:** This replaces the existing https://cdnjs.com/libraries/wow that is now GPL/shareware.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@graingert
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by PeterDaveHello** [comment]
hmmm ... we can add it as `graingert-wow`

**Comment by graingert** [comment]
How about free-wow or wow-mit

**Comment by PeterDaveHello** [comment]
@graingert this lib seems to be named wow.js or WOW, the name conflict on cdnjs we using author name as namespace to handle it.

**Comment by graingert** [comment]
ok
