### ISSUE TITLE
[Request] Add Replacer

### ISSUE THREAD

**Issue by devlix1** [cdnjs/cdnjs#7868]
* Library name: Replacer * 
* Git repository url: https://github.com/devlix1/Replacer *
* npm package url(optional): * 
* License(s): MIT *
* Official homepage: samp.work *
* Wanna say something? Leave message here: *

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @devlix1  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t please close the old issues.
