### ISSUE TITLE
[Request] Add q-connection 

### ISSUE THREAD

**Issue by menixator** [cdnjs/cdnjs#7870]
**Library name:** q-connection
**Git repository url:** https://github.com/kriskowal/q-connection
**npm package url(optional):**  https://www.npmjs.com/package/q-connection
**License(s):** MIT
**Official homepage:**

**Comment by PeterDaveHello** [comment]
No response from https://github.com/kriskowal/q-connection/issues/43 for a long time, we won't host this until it's confirmed that it works in front-end.
