### ISSUE TITLE
[Request] Add vcardjs 

### ISSUE THREAD

**Issue by alejandrosierra** [cdnjs/cdnjs#7871]
**Library name:** vcardjs
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @alejandrosierra,
Could you please provide more detail? Thanks.

**Comment by pvnr0082t** [comment]
close issue due to no response.
