### ISSUE TITLE
[Request] Add ContentTools 

### ISSUE THREAD

**Issue by maya88r** [cdnjs/cdnjs#7874]
**Library name:** ContentTools
**Git repository url:** https://github.com/GetmeUK/ContentTools
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://getcontenttools.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @maya88r , `ContentTools` had been already hosted in cdnjs. https://cdnjs.com/libraries/ContentTools
This issue will be closed.
