### ISSUE TITLE
[Request] Add tacit 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#7879]
**Library name:** tacit
**Git repository url:** https://github.com/yegor256/tacit/

**Comment by pvnr0082t** [comment]
@PeterDaveHello All of the filename included version in [dist](https://github.com/yegor256/tacit/tree/0.6/dist) folder. Should I open an issue to ask that is it possible to rename files without version?

**Comment by PeterDaveHello** [comment]
Yes, and you can send a PR with correct naming for old versions. You should try to write shell sciprts to help you do the correction works, not manually, since we may make mistake for complex works.

**Comment by pvnr0082t** [comment]
@PeterDaveHello There are only `scss` files before `v0.5.5`. How to do for this case?

**Comment by PeterDaveHello** [comment]
Maybe take it as a practice to compile scss files to css by yourself? Just remember to record all the detail for auditing.
