### ISSUE TITLE
[Request] Add tv4.js 

### ISSUE THREAD

**Issue by jochouen** [cdnjs/cdnjs#7884]
**Library name:** tv4.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by janbrohl** [comment]
- Git repository url: https://github.com/geraintluff/tv4
- npm package url(optional): https://www.npmjs.com/package/tv4
- Licenses: MIT, public domain
- Official homepage: https://geraintluff.github.io/tv4/
