### ISSUE TITLE
[Request] Add select2-bootstrap-theme 

### ISSUE THREAD

**Issue by joehmchan** [cdnjs/cdnjs#7892]
Library name:select2-bootstrap-theme 
Git repository url: https://github.com/select2/select2-bootstrap-theme
npm package url(optional):select2-bootstrap-theme
License(s):MIT
Official homepage: http://select2.github.io/select2-bootstrap-theme/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Close per #5984
