### ISSUE TITLE
[Request] Add pavilion 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#7893]
**Library name:** pavilion
**Git repository url:** https://github.com/getpavilion/pavilion
**npm package url(optional):** https://www.npmjs.com/package/pavilion
**License(s):** MIT
**Official homepage:** http://www.pavilion.io/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by getpavilion** [comment]
Thanks for adding, guys!
