### ISSUE TITLE
[Request] Add jquery.simple.tree 

### ISSUE THREAD

**Issue by dmitriistrelok** [cdnjs/cdnjs#7899]
**Library name:** jquery.simple.tree
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @dmitriistrelok , any details?
Thanks!

**Comment by kennynaoh** [comment]
close due to no response.
cc @PeterDaveHello
