### ISSUE TITLE
[Request] Karkas.js

### ISSUE THREAD

**Issue by odin3** [cdnjs/cdnjs#7902]
Karkas.js
https://github.com/odin3/karkas
**npm package url(optional):** 
GNU GENERAL PUBLIC LICENSE
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @odin3 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our README.md for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.
Thanks!

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
@PeterDaveHello ,
I think the popularity is not enough.
Should we close it?or keep waiting?
Thanks!

**Comment by kennynaoh** [comment]
close due to not enough popularity.
Thanks @odin3
