### ISSUE TITLE
[Request] Add brand-colors

### ISSUE THREAD

**Issue by ulyan** [cdnjs/cdnjs#7906]
**Library name:**  Brand Colors
**Git repository url:** https://github.com/reimertz/brand-colors
**npm package url(optional):** brand-colors
**License(s):** ???
**Official homepage:** http://brand-colors.com/

**Comment by pvnr0082t** [comment]
@PeterDaveHello The dist folder contains all version files. How can I do to grab files of the latest version using auto-update?

**Comment by PeterDaveHello** [comment]
Can't we use `dist/latest` as base path?

**Comment by ulyan** [comment]
@PeterDaveHello It will be the best decision.

**Comment by PeterDaveHello** [comment]
Thanks @ulyan

**Comment by reimertz** [comment]
yeay, this is awesome. thanks guys!

**Comment by PeterDaveHello** [comment]
@reimertz no problem and please enjoy it! You can also add the CDN info in the readme and website :+1:
