### ISSUE TITLE
CDNJS Combo Loader

### ISSUE THREAD

**Issue by demoive** [cdnjs/cdnjs#791]
# CDNJS Combo Loader

A proposal for [CDNJS](http://cdnjs.com/) to support combined requests allowing their resources to be served in a reduced number of HTTP connections (inspiration by [YUI's combo loading](http://yuilibrary.com/yui/docs/yui/loader.html) service).
## Example

Instead of four separate requests:

``` html
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.7.0/mustache.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.3/underscore-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.9/backbone-min.js"></script>
```

... developers could do the following and utilise a single request:

``` html
<script src="//cdn1js.cloudflare.com
?ajax/libs/jquery/1.8.3/jquery.min.js
&ajax/libs/mustache.js/0.7.0/mustache.min.js
&ajax/libs/underscore.js/1.4.3/underscore-min.js
&ajax/libs/backbone.js/0.9.9/backbone-min.js"></script>
```
## Discussion

Indeed, this would diversify the number of "unique" resources, making it less likely for browsers to cache common requests. But since this would be an option in addition to the existing individual file serving, it doesn't really hurt to have it! In my personal opinion, the pros outweigh the cons:
### Pros
- Reduces latency by serving fewer, individual requests
- Strengthens CDNJS ability to used in production environments
### Cons
- Browsers are less likely to encounter cache collisions
- Could be more difficult to maintain source code (especially for novice developers)
## Specs
- Files are concatenated in the order they are listed. This can be used to manage dependencies.
- If any file fails to load, the entire request fails. The idea here being that the scripts you are loading onto your page is assumed to be required for it to run. If one isn't available, then tough luck. This also follows the idea of dependencies and developers could combine different groups of dependencies.
### Potential base URLs

```
//cdnjs1.cloudflare.com?
//cdn1js.cloudflare.com?
//cdnjs.cloudflare.com/1?
//cdnjs.cloudflare.com/combo?
```
### Psuedo-code-ish code for serving libraries

``` javascript
var MAX_URL_LENGTH = 1024,
  SEPARATOR = '&',
  resources = [],
  concat = '';

if (location.href.length > MAX_URL_LENGTH) {
  // return either nothing or an error
} else {
  resources = location.search.split(comboSep)

  resources.forEach(function (resource) {
    concat += read(location.origin + '/' + resource);
  });

  serve(concat);
}
```

**Comment by dcohenb** [comment]
Why is this amazing idea is closed? anything happened with this?

**Comment by PeterDaveHello** [comment]
hmmm ... something like #360

However that's not a good practice with http/2.0.

**Comment by PeterDaveHello** [comment]
cc @cdnjs/team-cdnjs

**Comment by dcohenb** [comment]
Fair enough.

**Comment by PeterDaveHello** [comment]
@dcohenb As more httpds and browsers are going to support http/2.0 (and many of them already support spdy, the pre-http2.0), maybe this feature won't be exist in in future anymore, it's more convenient for front-end developer, but increase the overhead of web servers and the complexsity to debug.

**Comment by dcohenb** [comment]
@PeterDaveHello So what is the best practice if I use 10-15 libs, should I concat them in my builder and serve as one file or is it better to serve them separately from cdnjs?

**Comment by PeterDaveHello** [comment]
@dcohenb No need to concat them in your  builder and serve as one file,  is it better to serve them separately from cdnjs,  by http/2.0,  they will be loaded in parallel,  the server will aitomatically push them to the clients.

**Comment by dcohenb** [comment]
@PeterDaveHello Awesome thanks for clearing that up for me

**Comment by PeterDaveHello** [comment]
@dcohenb No problem
