### ISSUE TITLE
[Request] Add ngCart

### ISSUE THREAD

**Issue by kenhui521** [cdnjs/cdnjs#7917]
**Library name:** ngCart
**Git repository url:** https://github.com/snapjay/ngCart
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://ngcart.snapjay.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @kenhui521 ,
The same issue was opened before. (#7881)

**Comment by PeterDaveHello** [comment]
Close per #7881
