### ISSUE TITLE
[Request] Add quantumui 

### ISSUE THREAD

**Issue by bugmenot2** [cdnjs/cdnjs#7935]
**Library name:** quantumui
**Git repository url:** https://github.com/quantumui/quantumui
**npm package url(optional):** 
**License(s):** MIT and CC-BY-3.0
**Official homepage:** https://github.com/quantumui/quantumui
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @bugmenot2 ,
There is an issue for `quantumui`. See #7896. Thanks for your contribution.
