### ISSUE TITLE
[Request] Add redux-thunk

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#7939]
**Library name:** redux-thunk
**Git repository url:** https://github.com/gaearon/redux-thunk
**npm package url(optional):** https://www.npmjs.com/package/redux-thunk
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any reason to close?

**Comment by pvnr0082t** [comment]
Because I found that the lib already exist. https://cdnjs.com/#q=redux-thunk

**Comment by PeterDaveHello** [comment]
Fine, please mention the reason when you are going to close an issue.

**Comment by PeterDaveHello** [comment]
@pvnr0082t BTW, should provide the url of the lib, not search page.
