### ISSUE TITLE
[Request] Add covjson-reader 

### ISSUE THREAD

**Issue by kennynaoh** [cdnjs/cdnjs#7942]
**Library name:** covjson-reader
**Git repository url:** https://github.com/Reading-eScience-Centre/covjson-reader
**npm package url(optional):** https://www.npmjs.com/package/covjson-reader
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by neothemachine** [comment]
@kennynaoh Any particular reason for putting this in cdnjs? It's already on http://www.jsdelivr.com/projects/covjson-reader Just wondering

**Comment by kennynaoh** [comment]
@neothemachine 
It provides more choices to users.
