### ISSUE TITLE
jslibrary

### ISSUE THREAD

**Issue by sofftechnologies** [cdnjs/cdnjs#7947]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@sofftechnologies 
Any details?

**Comment by PeterDaveHello** [comment]
@x09326 though I know the reason why you close this issue, but it'll be better to mention the reason when you are closing an issue.

**Comment by x09326** [comment]
okay, I will do it next time.
