### ISSUE TITLE
[Request] Add Swal

### ISSUE THREAD

**Issue by AmadeusDelfino** [cdnjs/cdnjs#7952]
**Library name:** Swal
**Git repository url:** https://github.com/lipis/bootstrap-sweetalert
**npm package url(optional):**  https://www.npmjs.com/package/bootstrap-sweetalert
**License(s): MIT**
**Official homepage: http://lipis.github.io/bootstrap-sweetalert/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @AmadeusDelfino ,
`bootstrap-sweetalert` already exists in cdnjs. Here is the reference https://cdnjs.com/libraries/bootstrap-sweetalert. Thanks for contribution.

**Comment by PeterDaveHello** [comment]
@pvnr0082t check the version.

**Comment by pvnr0082t** [comment]
@PeterDaveHello What version I need to check? NPM released version and GitHub released version? Or the versions in cdnjs and the repo?

**Comment by PeterDaveHello** [comment]
There is v1.0.0 on upstream, don't you notice that we don't have v1.0.0? Try to fix it.
