### ISSUE TITLE
[Request] Add xrmservicetoolkit 

### ISSUE THREAD

**Issue by Tharnadar** [cdnjs/cdnjs#7955]
**Library name:** xrmservicetoolkit
**Git repository url:** https://github.com/con-ssc/XrmServiceToolkit
**npm package url(optional):** 
**License(s):**
**Official homepage:**https://xrmservicetoolkit.codeplex.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Tharnadar ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by Tharnadar** [comment]
Thank you Daniel, sorry for my mistake.

**Comment by PeterDaveHello** [comment]
@Tharnadar It's okay, dont worry :)
