### ISSUE TITLE
[Request] Add pdfmake2

### ISSUE THREAD

**Issue by DataTables** [cdnjs/cdnjs#7957]
**Library name:** pdfmake2
**Git repository url:** https://github.com/miltador/pdfmake2
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://pdfmake.org/#/ (forked)
**Wanna say something? Leave message here:**

CDNJS currently [has pdfmake](https://cdnjs.com/libraries/pdfmake) available, but pdfmake hasn't been updated in a while and there haven't been any replies to [the community](https://github.com/bpampuch/pdfmake/issues/532) asking if that project is still active. It doesn't appear to be.

The proposed package contains a number of fixes to the pdfmake on cdnjs at the moment. Can this fork also be included on cdnjs?

**Comment by DataTables** [comment]
Apologies - I think I've jumped the gun a bit here. From [the discussion in the pdfmake repo](https://github.com/bpampuch/pdfmake/issues/532#issuecomment-219819634), the existing repo might be brought back to current. Rather than propagating fragmented libraries to cdnjs, I guess we should wait to see the out come of that discussion. Going to close this issue until then! Sorry for the noise :-)

**Comment by PeterDaveHello** [comment]
@DataTables No problem.
