### ISSUE TITLE
ng-table.js

### ISSUE THREAD

**Issue by chkramesh** [cdnjs/cdnjs#7959]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @chkramesh , is there any detail? If no response,this issue will be closed in 7 days.

**Comment by pvnr0082t** [comment]
closed due to no response.
