### ISSUE TITLE
[Request] Add backbone-fsm 

### ISSUE THREAD

**Issue by tarasovin** [cdnjs/cdnjs#7965]
**Library name:** backbone-fsm
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

https://github.com/pwlmaciejewski/backbone-fsm

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@tarasovin 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

@PeterDaveHello Please help me review it, thank you.

**Comment by x09326** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@x09326 you don't need to ping me for the popularity problem issue.

**Comment by x09326** [comment]
Close this issue because no response.
