### ISSUE TITLE
[Request] algebra.js

### ISSUE THREAD

**Issue by bigteejay** [cdnjs/cdnjs#7971]
**Library name:** algebra.js
**Git repository url:** https://github.com/nicolewhite/algebra.js
**npm package url(optional):** https://www.npmjs.com/package/algebra.js
**License(s):** MIT
**Official homepage:** http://algebra.js.org
**Wanna say something? Leave message here:** They dont appear to currently have a webpack/browserified version in github, but they do offer one [here](http://algebra.js.org/javascripts/algebra.min.js) as well as [make support to build one](https://github.com/nicolewhite/algebra.js#in-the-browser-1).
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by bigteejay** [comment]
@nicolewhite

**Comment by nicolewhite** [comment]
Can someone help me understand why `algebra.min.js` no longer works on its own? When I built this project a few months ago, I was simply able to refer to the minified .js in the HTML like so:

```html
<script src="algebra.min.js"></script>
```

Now this no longer works and I get undefined errors. Did Chrome or browsers in general change something regarding how loading JavaScript files works?
