### ISSUE TITLE
Font awesome on windows phone

### ISSUE THREAD

**Issue by wouter2203** [cdnjs/cdnjs#7977]
Hello,

Font awesome loaded through cdnjs on any Windows Phone I can test on (Lumia 930, Lumia 925, Lumia 630, Lumia 520) does not load.

However when I load the exact CSS on any of my own servers the fonts are downloaded and it works as intended, which made me think it's an issue on the cdnjs servers.
Everything seems to be fine when loaded through bootstrapcdn as well.

It also works when I just load font awesome locally, without any cdn.

Sincerely,

Wouter

**Comment by PeterDaveHello** [comment]
@wouter2203 do you have any error message or log on the client?

**Comment by wouter2203** [comment]
@PeterDaveHello there are no error or log messages in my console.

**Comment by PeterDaveHello** [comment]
Have you tried to manually enter the url of ther resources in the browser?

**Comment by wouter2203** [comment]
Here's a table explaining what font type I can load and which I can't load.

Font type | Success
------------ | ----------
EOT | Nope
WOFF2 | Nope
WOFF | Yes
TTF | Yes
SVG | Yes

When they fail loading I get the following (useless) notice:
> We're having trouble reaching this website

**Comment by PeterDaveHello** [comment]
@wouter2203 is there also a problem on accessing other libs with the same file type?
Like `https://cdnjs.cloudflare.com/ajax/libs/amazeui/2.6.0/fonts/fontawesome-webfont.woff2`

**Comment by mashedkeyboard** [comment]
Windows Phone user weighing in here - I use CDNJS for Font Awesome and it seems to work perfectly across all devices, including Windows Phone 8.1 and Windows 10 Mobile, with both UC Browser and Microsoft Edge/IE Mobile. :/

**Comment by PeterDaveHello** [comment]
Thanks @mashedkeyboard

**Comment by PeterDaveHello** [comment]
@wouter2203 do you have a "clean" phone to test it again? Maybe try if another ISP works for you?

**Comment by wouter2203** [comment]
I've tested it on a new Windows tablet, it seems to work fine on this tablet. However, it still isn't working on the phones, but I rather think this is an issue with the phones and not with cdnjs.

Thank you for your help!

**Comment by PeterDaveHello** [comment]
I wonder if you could provide more details so that we can help you fix it.
