### ISSUE TITLE
[Request] Add jquery.csv-0.71.min.js 

### ISSUE THREAD

**Issue by rockymenezes** [cdnjs/cdnjs#7980]
**Library name:** jquery.csv-0.71.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Any details?
Thanks!

**Comment by PeterDaveHello** [comment]
Close due to no response.

**Comment by PeterDaveHello** [comment]
And this may be something you want: https://cdnjs.com/libraries/jquery-csv
