### ISSUE TITLE
[Request] Add synaptic.js

### ISSUE THREAD

**Issue by bddatest** [cdnjs/cdnjs#7991]
**Library name:** synaptic 
**Git repository url: https://github.com/cazala/synaptic
**npm package url(optional):** https://www.npmjs.com/package/synaptic
**License(s):**
**Official homepage:http://synaptic.juancazala.com/
**Wanna say something? Leave message here:Excellent AI library in JS

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Jabher** [comment]
Hi. Synaptic minified version is partially not working. Is it possible to distribute a non-minified version as a minified one? (in order not to break urls)

See https://github.com/cazala/synaptic/issues/137

**Comment by PeterDaveHello** [comment]
A little bit hard since we now added SRI support, any modification will break the users worth.
