### ISSUE TITLE
[Request] Add js-nacl 

### ISSUE THREAD

**Issue by lovesh** [cdnjs/cdnjs#7995]
**Library name:** js-nacl
**Git repository url:** https://github.com/tonyg/js-nacl
**npm package url(optional):** https://www.npmjs.com/package/js-nacl
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by lovesh** [comment]
[nacl_factory.js ](https://github.com/tonyg/js-nacl/blob/master/lib/nacl_factory.js)

**Comment by kennynaoh** [comment]
Thanks!

**Comment by athanclark** [comment]
Can we get the latest version v1.2.1? Version 1.2.0 doesn't expose a (vital in my case) [API component](https://github.com/tonyg/js-nacl#changes) :)

**Comment by PeterDaveHello** [comment]
@athanclark you could ask its author to publish it on npm, so that our auto-updater will add it, thanks. cc @kennynaoh

**Comment by athanclark** [comment]
@joeyh has opted to specifically **not** upload to npm, due to this being a "browser-only" package; npm implies node.js, when anyone using node.js should use the bona-fide libsodium.so bindings.

**Comment by PeterDaveHello** [comment]
Okay, I'll transfer it to use git auto-update.

**Comment by PeterDaveHello** [comment]
v1.2.1 added here: bd27640

**Comment by athanclark** [comment]
Awesome!! Thank you!
