### ISSUE TITLE
[Request] Add wickedpicker 

### ISSUE THREAD

**Issue by mashedkeyboard** [cdnjs/cdnjs#7998]
**Library name:** wickedpicker
**Git repository url:** https://github.com/ericjgagnon/wickedpicker
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://ericjgagnon.github.io/wickedpicker/
**Wanna say something? Leave message here:**
Another awesome timepicker package.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @mashedkeyboard ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by mashedkeyboard** [comment]
Heya @pvnr0082t,

Thanks, I hadn't seen that. Might I suggest that that instruction is added to the "No results" page on the CDNJS website? I came here and added the request from that page, not through GitHub itself, so wouldn't have seen the readme.md.

Thanks!

**Comment by pvnr0082t** [comment]
@mashedkeyboard That's ok. Thanks for your contribution!
