### ISSUE TITLE
[Request] Add kraken 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8010]
**Library name:** kraken
**Git repository url:** https://github.com/cferdinandi/kraken

**Comment by cferdinandi** [comment]
@PeterDaveHello is not the author of this package. I am. Kraken should absolutely **not** be served from a CDN. It's intended to be a boilerplate that's modified by developers, and thus makes no sense as a CDN-served asset.

**Comment by PeterDaveHello** [comment]
@cferdinandi we know you are the author, don't worry. Since there are minified files in the `dist` folder, can't that be used directly from CDN? Or you mean that every developer must modified and compiled their own version?

**Comment by cferdinandi** [comment]
Per the docs, Kraken is NOT a framework or finished product. It's a boilerplate, a starting point for devs to modify and build on top of. As such, serving it from a CDN makes no sense. http://cferdinandi.github.io/kraken/#ugly-on-purpose

**Comment by PeterDaveHello** [comment]
Thanks for your explanation @cferdinandi , I wonder if we can just leave it for users/developers to decide using it or not, this hosting won't force them to use it via cdn, what do you think?

**Comment by cferdinandi** [comment]
I think it encourages bad development practices, and I would personally not submit this to a CDN. But, it's an open source project under MIT license, so it's not really up to me.
