### ISSUE TITLE
[Request] Add x18n series libs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8011]
~~https://github.com/florian/x18n~~
https://github.com/marco-a/react-x18n
https://github.com/florian/jQuery.x18n/
~~https://github.com/SBoudrias/handlebars-x18n~~

**Comment by sashberd** [comment]
@PeterDaveHello The link to https://github.com/SBoudrias/handlebars-x18n is not working any more. Is lib exists or we could remove it from the list to add?
