### ISSUE TITLE
[Request] Add palette.js

### ISSUE THREAD

**Issue by AbigailBuccaneer** [cdnjs/cdnjs#8013]
**Library name:** palette.js
**Git repository url:** https://github.com/google/palette.js
**npm package url(optional):** None
**License(s):** Apache 2 / MIT
**Official homepage:** https://github.com/google/palette.js

**Comment by PeterDaveHello** [comment]
Ping @x09326

**Comment by x09326** [comment]
@AbigailBuccaneer 
Could you provide the version of this libraray?

**Comment by AbigailBuccaneer** [comment]
It looks like it's not versioned under any sensible versioning scheme - so I guess `master` or `3ec568c9dd6d44996c8b045ed9dde28fc1744105` or `2015-12-10` would be the appropriate version string. If you'd like I can try and contact the developers to ask them about releasing a numbered version.

**Comment by PeterDaveHello** [comment]
@AbigailBuccaneer It'll be better to have a version :)
