### ISSUE TITLE
[Request] Add angular-daterangepicker

### ISSUE THREAD

**Issue by kenhui521** [cdnjs/cdnjs#8014]
**Library name:** angular-daterangepicker
**Git repository url:** https://github.com/fragaria/angular-daterangepicker
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**
bower install angular-daterangepicker --save
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Nicholaiii** [comment]
**npm package url(optional):** https://www.npmjs.com/package/angular-daterangepicker
**Official homepage:** http://fragaria.github.io/angular-daterangepicker/

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
