### ISSUE TITLE
[Request] Add JsBarcode 

### ISSUE THREAD

**Issue by kennynaoh** [cdnjs/cdnjs#8020]
**Library name:** JsBarcode
**Git repository url:** https://github.com/lindell/JsBarcode
**npm package url(optional):** https://www.npmjs.com/package/jsbarcode
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by bruceCzK** [comment]
+1

**Comment by lindell** [comment]
The npm cobfig should not be used for web. The files in `./dist` is built for Web use
