### ISSUE TITLE
[Request] Add add-to-homescreen

### ISSUE THREAD

**Issue by vitalragaz** [cdnjs/cdnjs#8025]
**Library name: add-to-homescreen** 
**Git repository url: https://github.com/cubiq/add-to-homescreen**
**npm package url(optional):** 
**License(s): MIT License**
**Official homepage:http://cubiq.org/add-to-home-screen**
**Wanna say something? Leave message here:
One of the famoust library for adding webapp to the homescreen**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
