### ISSUE TITLE
[Request] Add Plyr

### ISSUE THREAD

**Issue by MattSnowOregonGov** [cdnjs/cdnjs#8027]
**Library name: Plyr** 
**Git repository url: https://github.com/selz/plyr**
**npm package url: https://www.npmjs.com/package/plyr** 
**License(s): MIT**
**Official homepage: https://plyr.io**
**Wanna say something? Leave message here: A simple, accessible HTML5 media player.**

**Comment by drewfreyling** [comment]
Feel free to add a PR for this @MattSnowOregonGov

**Comment by SamPotts** [comment]
Awesome. Thanks for doing this 👍

**Comment by PeterDaveHello** [comment]
@SamPotts this lib will be available on cdnjs within 30 mins!

**Comment by SamPotts** [comment]
Epic! Thanks for sorting this out :-)

**Comment by PeterDaveHello** [comment]
@SamPotts No problem.
