### ISSUE TITLE
[Request] Add annotorious 

### ISSUE THREAD

**Issue by smashappz** [cdnjs/cdnjs#8031]
**Library name:** annotorious
**Git repository url:**https://github.com/annotorious/annotorious
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**https://annotorious.github.io/index.html
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
