### ISSUE TITLE
[Request] Add flex layout attribute 

### ISSUE THREAD

**Issue by mohitsadaria** [cdnjs/cdnjs#8038]
**Library name:** flex layout attribute
**Git repository url:** https://github.com/StefanKovac/flex-layout-attribute
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @mohitsadaria , this issue will be closed because duplicated with #8035. Thanks for your contribution.
