### ISSUE TITLE
[Request] Add leaflet.markercluster.freezable 

### ISSUE THREAD

**Issue by FunkyLoveCow** [cdnjs/cdnjs#8040]
**Library name:** leaflet.markercluster.freezable
**Git repository url:** https://github.com/ghybs/Leaflet.MarkerCluster.Freezable
**npm package url(optional):** 
**License(s):** MIT: https://github.com/ghybs/Leaflet.MarkerCluster.Freezable/blob/master/LICENSE
**Official homepage:** https://github.com/ghybs/Leaflet.MarkerCluster.Freezable
**Wanna say something? Leave message here:**
This is a subplugin for leaflet.markercluster and is useful for being about to freeze and unfreeze levels at which pins will show vs. cluster.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @FunkyLoveCow ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello
