### ISSUE TITLE
[Request] Add jPages

### ISSUE THREAD

**Issue by apumex** [cdnjs/cdnjs#8046]
**Library name: JPages
*_Git repository url:https://github.com/luis-almeida/jPages
*_npm package url(optional):** 
**License(s):**
**Official homepage: http://luis-almeida.github.io/jPages/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's trace its commit log to add this lib.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
