### ISSUE TITLE
[Request] Add Hyphenator

### ISSUE THREAD

**Issue by adamshaylor** [cdnjs/cdnjs#8050]
**Library name:** Hyphenator
**Git repository url:** https://github.com/mnater/hyphenator
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://mnater.github.io/Hyphenator/

**Comment by mnater** [comment]
Thanks for your awesome work.

I'd like to mention that IMHO it would be best for page-load performance to merge the Hyphenator.js-Script and the necessary hyphenation patterns in one file. My repo has a tool (http://mnater.github.io/Hyphenator/mergeAndPack.html) for exactly this task. Obviously it isn't possible for cdnjs to provide all possible combinations. So your approach will work.

**Comment by adamshaylor** [comment]
Thanks for the tip, @mnater. I think it should be sufficient for most use cases to link directly to `Hyphenator.js` and one or two of the pattern files on cdnjs.com. Anyone who needs more patterns than that can bundle them and self-host.

Bear in mind that there are significant cross-site caching advantages to linking to a common CDN such as this and that multiple requests are mitigated by HTTP/2—or at least they will be for those who haven’t upgraded yet.
