### ISSUE TITLE
[Request] Add Bootstrap-Iconpicker 

### ISSUE THREAD

**Issue by jmurphy45** [cdnjs/cdnjs#8052]
**Library name:** Bootstrap-Iconpicker
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @jmurphy45 , is there any detail? This issue will be closed if there is no any response in next 7 days.

**Comment by pvnr0082t** [comment]
close issue due to no response.

**Comment by PeterDaveHello** [comment]
@pvnr0082t we could also just google it and see if there is a famous lib that we can add.
https://github.com/victor-valencia/bootstrap-iconpicker

**Comment by andersmmg** [comment]
bootstrap-iconpicker.min.js
iconset-fontawesome-4.2.0.min.js
bootstrap-iconpicker.min.css
iconset-glyphicon.min.js
iconset-ionicon-1.5.2.min.js
iconset-weathericon-1.2.0.min.js
iconset-mapicon-2.1.0.min.js
iconset-octicon-2.1.2.min.js
iconset-typicon-2.0.6.min.js
iconset-elusiveicon-2.0.0.min.js
iconset-materialdesign-1.1.1.min.js
