### ISSUE TITLE
[Request] Add gasparesganga/jquery-loading-overlay 

### ISSUE THREAD

**Issue by kaz0636** [cdnjs/cdnjs#8053]
**Library name:** gasparesganga/jquery-loading-overlay
*_Git repository url:https://github.com/gasparesganga/jquery-loading-overlay
*_npm package url(optional):
*_License(s):MIT
*_Official homepage:http://gasparesganga.com/labs/jquery-loading-overlay/
**Wanna say something? Leave message here:
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @kaz0636 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello
