### ISSUE TITLE
[Request] Add jquery.ajaxify 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#8054]
**Library name:** jquery.ajaxify
**Git repository url:**https://github.com/arvgta/ajaxify/tree/6.2.1
**npm package url(optional):** https://www.npmjs.com/package/ajaxify
**License(s):**MIT
**Official homepage:**http://4nf.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Added in #7941
