### ISSUE TITLE
[Request] Add utemplate

### ISSUE THREAD

**Issue by Announcement** [cdnjs/cdnjs#8056]
**Library name:** 
**Git repository url: https://github.com/Announcement/utemplate**
**npm package url(optional): https://www.npmjs.com/package/utemplate** 
**License(s): MIT**
**Official homepage: https://github.com/Announcement/utemplate**
**Wanna say something? Leave message here:**
just need the utemplate.js pls, thank you.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
hi @Announcement ,
this lib doesn't have enough popularity(100 watch or star is a good example). Please take a look at our README.md for detail.
we suggest you open a issue again when the repo has notable popularity.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
@PeterDaveHello ,
I think the popularity is not enough.
Should we close it?or keep waiting?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh For the issues waiting more then a month and didn't reach the minimun popularity requirement, you can just close them.

**Comment by kennynaoh** [comment]
@PeterDaveHello ok,
close due to not enough popularity.
Thanks @Announcement
