### ISSUE TITLE
[Request] Add clappr-chromecast-plugin

### ISSUE THREAD

**Issue by Sarabveer** [cdnjs/cdnjs#8061]
**Library name:** clappr-chromecast-plugin
**Git repository url:** https://github.com/clappr/clappr-chromecast-plugin
**npm package url(optional):** https://www.npmjs.com/package/clappr-chromecast-plugin
**License(s):** BSD-3-Clause 
**Official homepage:** N/A
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Sarabveer** [comment]
Plugin was Finalized and added to the JSDelivr CDN

**Comment by pvnr0082t** [comment]
Hi @Sarabveer ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We should add this since it's a plugin of a popular lib.
