### ISSUE TITLE
[Request] Add sisyphus 

### ISSUE THREAD

**Issue by tobsn** [cdnjs/cdnjs#8069]
**Library name:** Sisyphus
**Git repository url:** https://github.com/simsalabim/sisyphus
**npm package url(optional):** https://www.npmjs.com/package/sisyphus.js
**License(s):** https://github.com/simsalabim/sisyphus/blob/master/MIT-LICENSE
**Official homepage:** http://sisyphus-js.herokuapp.com

**Comment by simsalabim** [comment]
Synchronized versions on GitHub and [npm](https://www.npmjs.com/package/sisyphus.js) to a sane degree. Current version is v1.1.3.
