### ISSUE TITLE
Add missing keywords field in libs' package.json 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#8073]
Here are the libs without `keywords` :

  * [x] acorn
  * [x] agility
  * [x] alertify.js
  * [x] algoliasearch-helper-js
  * [x] anchor-js
  * [x] angucomplete-alt
  * [ ] angular-autofields
  * [ ] angular-bootstrap-slider
  * [ ] angular-cache
  * [ ] angular-carousel
  * [ ] angular-chart.js
  * [ ] angular-data
  * [ ] angular-datatables
  * [ ] angular-dragula
  * [ ] angular-formly-templates-bootstrap
  * [ ] angular-material
  * [ ] angular-materialize
  * [ ] angular-pusher
  * [ ] angular-truncate
  * [ ] angular-ui-calendar
  * [ ] angular-ui-date
  * [ ] angular-ui-select
  * [ ] angular-ui-sortable
  * [ ] angularLocalStorage
  * [ ] animo.js
  * [ ] antimoderate
  * [ ] attrchange
  * [ ] aurora.js
  * [ ] awesome-bootstrap-checkbox
  * [ ] babel-standalone
  * [ ] backbone.modal
  * [ ] balance-text
  * [ ] balloon-css
  * [ ] Base64
  * [ ] booking-js
  * [ ] bootbox.js
  * [ ] bootstrap-daterangepicker
  * [ ] bootstrap-sweetalert
  * [ ] chaplin
  * [ ] circliful
  * [ ] clappr
  * [ ] ContentTools
  * [ ] cookieconsent2
  * [ ] depot
  * [ ] device.js
  * [ ] Director
  * [ ] django.js
  * [ ] documentup
  * [ ] dragdealer
  * [ ] dragula
  * [ ] eve.js
  * [ ] eventable
  * [ ] expect.js
  * [ ] Faker
  * [ ] flag-icon-css
  * [ ] fluidvids.js
  * [ ] formstone
  * [ ] fpsmeter
  * [ ] FrozenUI
  * [ ] github-repo-widget
  * [ ] gmap3
  * [ ] graphiql
  * [ ] gulp
  * [ ] gumshoe
  * [ ] hls.js
  * [ ] instafeed.js
  * [ ] instantsearch.js
  * [ ] interpolate.js
  * [ ] is_js
  * [ ] iviewer
  * [ ] jmpress
  * [ ] joyride
  * [ ] jquery-fracs
  * [ ] jquery-mobile-datebox
  * [ ] jquery-overscroll
  * [ ] jquery-scrollpanel
  * [ ] jquery-twinkle
  * [ ] jquery.html5loader
  * [ ] jquery.photocols
  * [ ] jquery.turbolinks
  * [ ] jquery.waitforimages
  * [ ] js-data-angular
  * [ ] jshint
  * [ ] jstat
  * [ ] knockout-postbox
  * [ ] label.css
  * [ ] Ladda
  * [ ] Leaflet.awesome-markers
  * [ ] leaflet.fullscreen
  * [ ] legojs
  * [ ] line-chart
  * [ ] linkurious.js
  * [ ] localStorage
  * [ ] lrsjng.jquery-qrcode
  * [ ] materialize
  * [ ] mhayes-twentytwenty
  * [ ] midi.js
  * [ ] motion.js
  * [ ] ng-img-crop
  * [ ] ng-tasty
  * [ ] offline-js
  * [ ] oppia
  * [ ] outdated-browser
  * [ ] page.js
  * [ ] papier
  * [ ] plupload
  * [ ] r2d3
  * [ ] ramjet.js
  * [ ] range.js
  * [ ] repo.js
  * [ ] requirejs-plugins
  * [ ] resumable.js
  * [ ] sbt
  * [ ] scaleapp
  * [ ] scrollpoints
  * [ ] scrollReveal.js
  * [ ] shaka-player
  * [ ] shepherd
  * [ ] shopify-cartjs
  * [ ] side-comments
  * [ ] sigma.js
  * [ ] signature_pad
  * [ ] slidebars
  * [ ] snabbt.js
  * [ ] social-sharing
  * [ ] space
  * [ ] spf
  * [ ] systemjs
  * [ ] templatebinding
  * [ ] tether-drop
  * [ ] tether-select
  * [ ] timezone-js
  * [ ] TinyNav.js
  * [ ] Trumbowyg
  * [ ] uswds
  * [ ] vex-js
  * [ ] videojs-contrib-ads
  * [ ] vivus
  * [ ] vue-google-maps
  * [ ] wavesurfer.js
  * [ ] winjs

**Comment by PeterDaveHello** [comment]
Duplicated with #5422
