### ISSUE TITLE
[Request] Add vimeo.ga.js

### ISSUE THREAD

**Issue by joycegrace** [cdnjs/cdnjs#8085]
**Library name:** vimeo.ga.js
**Git repository url:**https://github.com/sanderheilbron/vimeo.ga.js
**npm package url(optional):** 
**License(s):**MIT
Copyright © 2015 Sander Heilbron.
**Official homepage:**https://www.sanderheilbron.nl/vimeo.ga.js/

**Wanna say something? Leave message here:**

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@joycegrace 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
@x09326 look close to the minimum requirement, let's just add it, thanks.
