### ISSUE TITLE
[Request] Add angular-cookies 

### ISSUE THREAD

**Issue by horiuchi** [cdnjs/cdnjs#8091]
**Library name:** angular-cookies
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@horiuchi 
Can you give me the git repository url or npm package url?
If you do not respond for more than 7 days, and I will close it at that time.

**Comment by horiuchi** [comment]
@x09326 Sorry, I forget this pull request.
I had knew that the `angular-cookies` is equal to `ngCookie`. And this library is hosted by google cdn.
So I will close this pull request.

**Comment by PeterDaveHello** [comment]
@x09326 https://www.npmjs.com/package/angular-cookies

**Comment by PeterDaveHello** [comment]
Seems we already have them here: https://cdnjs.com/libraries/angular.js/1.5.7, it's part of angular.js
