### ISSUE TITLE
[Request][author] Add mark.js

### ISSUE THREAD

**Issue by julmot** [cdnjs/cdnjs#8096]
**Library name:** mark.js
**Git repository url:** https://github.com/julmot/mark.js/
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://markjs.io/
**Wanna say something? Leave message here:** Would add it myself, but didn't find a documentation that describes how to add auto-update packages that are _not_ on npm. 

This will close #7613

**Comment by PeterDaveHello** [comment]
Try this, https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

and we should move to #7613

**Comment by PeterDaveHello** [comment]
@julmot we can add it for you, but it's also fine with adding by yourself, it depends on you.

**Comment by julmot** [comment]
@PeterDaveHello I'm currently planning the new architecture of mark.js v9.0.0. As JSDelivr switched to a different CDN architecture I'm having one question specifically for cdnjs: Is there any way to automatically files in this repository automatically, without the need to store them on the vendor repository itself?

**Comment by PeterDaveHello** [comment]
@julmot I saw your commit `Initial publishing as mark.js package on npm`, we also support to fetch files from npm, just need to switch its auto-update config to use npm auto-update :)
