### ISSUE TITLE
[Request] Add jquery.tcm.monthpicker

### ISSUE THREAD

**Issue by Krato** [cdnjs/cdnjs#8099]
**Library name**: jquery-tcm-month.js
**Git repository url:** https://github.com/thecodingmachine/jquery.tcm.monthpicker
**License(s):** MIT
**Wanna say something? Leave message here:** Very useful MonthPicker addon.

**Comment by pvnr0082t** [comment]
Hi @Krato ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
Close issue because of not enough popularity.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Because of no reponse, not the popularity.

**Comment by pvnr0082t** [comment]
@PeterDaveHello OK!
