### ISSUE TITLE
[Request] Add countUp.js 

### ISSUE THREAD

**Issue by DavidLemayian** [cdnjs/cdnjs#8100]
**Library name:** CountUp.js
**Git repository url:** https://github.com/inorganik/countUp.js
**npm package url(optional):** https://www.npmjs.com/package/countup.js
**License(s):** MIT
**Official homepage:** http://inorganik.github.io/countUp.js

**Comment by pvnr0082t** [comment]
Hi @DavidLemayian , CountUp.js had been added in cdnjs. (#8345) Thanks for your contribution.
