### ISSUE TITLE
[Request] Add angular 2.0.0-rc.1 (angular2)

### ISSUE THREAD

**Issue by Ofer-Gal** [cdnjs/cdnjs#8102]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Waiting for rc1 been release on https://code.angularjs.org/
