### ISSUE TITLE
[Request] Add timedropper 

### ISSUE THREAD

**Issue by montgoss** [cdnjs/cdnjs#8103]
**Library name:** timedropper
**Git repository url:** https://github.com/felicegattuso/timedropper/
**npm package url(optional):** 
**License(s):** MIT License, CC BY 4.0
**Official homepage:**  http://felicegattuso.com/projects/timedropper/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Because it has no git tag and no response for a long time, but it has version `v1.0` https://github.com/felicegattuso/timedropper/commit/0234d20d7c6ba8136c7b6fb35bf91c31f3e58947
Could I add it without git tag?
Thanks!

**Comment by PeterDaveHello** [comment]
Yes, it's a godo idea!
