### ISSUE TITLE
[Request] Add angular-animate.min.js.map 

### ISSUE THREAD

**Issue by ChaitanyaGadhavajjula** [cdnjs/cdnjs#8109]
**Library name:** angular-animate.min.js.map
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @ChaitanyaGadhavajjula 

We have received your request, I think that you are referring to [angular/bower-angular-animate](https://github.com/angular/bower-angular-animate), right?
Please wait a few days, we will add this library as soon as possible.

**Comment by sashberd** [comment]
Duplicate #8418
