### ISSUE TITLE
[Request] Add PushBullet.js

### ISSUE THREAD

**Issue by BubonicPestilence** [cdnjs/cdnjs#8112]
**Library name:** pushbullet.js
**Git repository url:** https://github.com/alexschneider/pushbullet-js
**npm package url(optional):** 
**License(s):** https://github.com/alexschneider/pushbullet-js/blob/master/LICENSE
**Official homepage:** https://github.com/alexschneider/pushbullet-js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@BubonicPestilence sorry, but this lib doesn't have enough popularity(100 watch or star, 500 downloads in npm package are good examples). Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.·
we suggest you open an issue again when the repo has notable popularity.·
thank you for your contribution.

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by BubonicPestilence** [comment]
It's ok, sry for not reading all rules.
Wish they will become more popular ;)

**Comment by maruilian11** [comment]
thank you!

**Comment by PeterDaveHello** [comment]
I'll be happy to host it if it has a valid version.

**Comment by PeterDaveHello** [comment]
Close due to no response from upstream.
