### ISSUE TITLE
[Request] Add Sexy 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8121]
**Library name:** Sexy
**Git repository url:** https://github.com/furf/Sexy

**Comment by Amomo** [comment]
@PeterDaveHello this lib seems not have enough popularity, should we add it?

**Comment by PeterDaveHello** [comment]
It's very close to the minimum.

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 Still low popularity. Suggest to close

**Comment by PeterDaveHello** [comment]
Let's close it.
