### ISSUE TITLE
[Request] Add responsive.gs

### ISSUE THREAD

**Issue by polyskalov** [cdnjs/cdnjs#8124]
**Library name:** responsive.gs
**Git repository url:** https://github.com/DenisLeblanc/responsive.gs
**Official homepage:** http://responsive.gs

**Comment by Amomo** [comment]
Hi @polyskalov 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.
