### ISSUE TITLE
[Request] Add angular-datatables 0.5.5

### ISSUE THREAD

**Issue by RatchapongT** [cdnjs/cdnjs#8127]
**Library name: angular-datatables
**Git repository url:https://github.com/l-lin/angular-datatables
**npm package url(optional):** https://www.npmjs.com/package/angular-datatables
**License(s):https://en.wikipedia.org/wiki/MIT_License
**Official homepage:https://l-lin.github.io/angular-datatables/#/welcome
**Wanna say something? Leave message here: 0.5.5 is out, cdn has up to 0.5.4

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
close due to existing on [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/angular-datatables).
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh you should read the whole issue again.

**Comment by PeterDaveHello** [comment]
@RatchapongT there is no v0.5.5 git tag or npm package so that's the reason why we don't have that, maybe you can confirm with the author of this lib.

**Comment by kennynaoh** [comment]
@PeterDaveHello 
Sorry for late added this library manually.
The version 0.5.5 of angular-datatables is already added automatically few days ago.
Should we can close it?
Thanks!

**Comment by PeterDaveHello** [comment]
Yes.
