### ISSUE TITLE
[Request] Add tingle.js 

### ISSUE THREAD

**Issue by ckaiser** [cdnjs/cdnjs#8128]
**Library name:** tingle.js
**Git repository url:** https://github.com/robinparisi/tingle
**npm package url(optional):** https://www.npmjs.com/package/tingle.js
**License(s):** MIT
**Official homepage:** http://robinparisi.github.io/tingle/

**Comment by Amomo** [comment]
Hi @ckaiser 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.

**Comment by Amomo** [comment]
closed due to no response.

**Comment by PeterDaveHello** [comment]
Looks fine to add now.
