### ISSUE TITLE
[Request] Add simplePagination.js

### ISSUE THREAD

**Issue by bguilz** [cdnjs/cdnjs#8134]
**Library name:** simplePagination.js
**Git repository url:** https://github.com/flaviusmatis/simplePagination.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
duplicated [issue](https://github.com/cdnjs/cdnjs/issues/6527)
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh mention the issue number in comment next time.

**Comment by PeterDaveHello** [comment]
Close per #6527

**Comment by kennynaoh** [comment]
OK
