### ISSUE TITLE
[Request] Add typeahead.min.js 

### ISSUE THREAD

**Issue by RahulNandi** [cdnjs/cdnjs#8136]
**Library name:** typeahead.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @RahulNandi 
Could you give us more detail about this issue?

If you are referring to [`twitter/typeahead.js`](https://github.com/twitter/typeahead.js), it is already on cdnjs!
https://cdnjs.com/libraries/typeahead.js

**Comment by VimalanBonito** [comment]
There is a well-known bug in the latest version of typeahead.js
https://github.com/twitter/typeahead.js/issues/1218

Is it possible to add this patched version?
https://github.com/getyourguide/typeahead.js/commit/6fc8051fec273d0fa0c8a9340446aad07923c34c

**Comment by sashberd** [comment]
@PeterDaveHello @sufuf3 Suggest to close
