### ISSUE TITLE
[Request] Add Angular2.0.0.rc1

### ISSUE THREAD

**Issue by ArchangelCommunity** [cdnjs/cdnjs#8138]
**Library name:** Angular2.0.0.rc1
**Git repository url:** https://github.com/angular/angular
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://angular.io/
**Wanna say something? Leave message here:** No

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #8102
