### ISSUE TITLE
[Request] Add most.js

### ISSUE THREAD

**Issue by electrichead** [cdnjs/cdnjs#8143]
**Library name:** most.js
**Git repository url:** https://github.com/cujojs/most
**npm package url(optional):** https://www.npmjs.com/package/most
**License(s):** MIT
**Official homepage:** https://github.com/cujojs/most
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
According to author already hosted with name [most](https://cdnjs.com/libraries/most). Closed
