### ISSUE TITLE
[Request] responsive-headings.css

### ISSUE THREAD

**Issue by adrielcafe** [cdnjs/cdnjs#8145]
**Library name:** responsive-headings.css
**Git repository url:** https://github.com/adrielcafe/responsive-headings.css
**npm package url(optional):** https://npmjs.com/package/responsive-headings
**License(s):** MIT
**Official homepage:** https://github.com/adrielcafe/responsive-headings.css
**Wanna say something? Leave message here:** Bring responsiveness to HTML headings

**Comment by x09326** [comment]
@adrielcafe 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by adrielcafe** [comment]
Ok @x09326, currently it have 174 downloads on npm. I'll come back when reach more than 300 :)
Thanks!

**Comment by sashberd** [comment]
@PeterDaveHello Still low popularity. suggest to close

**Comment by PeterDaveHello** [comment]
Let's close it first, we can create a new issue for it once it reaches the popularity requirement.
