### ISSUE TITLE
[Request] Add mkg-up

### ISSUE THREAD

**Issue by mkg0** [cdnjs/cdnjs#8151]
**Library name: mkg-up** 
**Git repository url: https://github.com/mkg0/mkg-up**
**npm package url(optional): https://www.npmjs.com/package/mkg-up** 
**License(s): MIT**
**Official homepage: https://github.com/mkg0/mkg-up**

thanks ^^

**Comment by x09326** [comment]
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.
