### ISSUE TITLE
[Request] Add Jquery-Theme-Switcher

### ISSUE THREAD

**Issue by Archin-modi** [cdnjs/cdnjs#8156]
**JeTLine UI** 
**https://github.com/Archin-modi/Jquery-Theme-Switcher**
**npm package url(optional):** 
**License(s):**
**http://www.jetline-ui.somee.com/Default/Theme_Switcher**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @Archin-modi 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.

**Comment by Amomo** [comment]
closed due to no response.
