### ISSUE TITLE
[Request] Add rateit 

### ISSUE THREAD

**Issue by maavuz** [cdnjs/cdnjs#8158]
**Library name:** rateit
**Git repository url:** https://github.com/gjunge/rateit.js
**npm package url(optional):**  https://www.npmjs.com/package/jquery.rateit

**Comment by Amomo** [comment]
Hi @maavuz 

We have received your request, but sorry this lib __doesn't have enough popularity.__ 
(for example,100 stars/watchers on GitHub or 500 times download per month on npm)
You can take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.

We suggest you opening an issue again when the repo has enough popularity.
Or, if there is any other proof of popularity, we may discuss to add it.

Thank you for your contribution. 

> This issue will be closed if there is no any response in next 7 days.

**Comment by Amomo** [comment]
closed due to no response.
