### ISSUE TITLE
[Request] Add voice command 

### ISSUE THREAD

**Issue by Tanvir18** [cdnjs/cdnjs#8177]
**Library name:** voice command
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Any details?

**Comment by kennynaoh** [comment]
close due to no response.
cc @PeterDaveHello
