### ISSUE TITLE
Custom builds via URL parameters

### ISSUE THREAD

**Issue by LeaVerou** [cdnjs/cdnjs#8179]
CDNJS is fantastic. One thing that would make it even more awesome would be the possibility for custom builds via URL params. These could be defined in a manifest in the library's repo.

For example, in [Prism](https://github.com/PrismJS/prism), we have a bunch of languages and plugins that people can check and uncheck in the [downloads page](http://prismjs.com/download.html) to create their own build. However, for its [CDNJS version](https://cdnjs.com/libraries/prism) people have to either link to a pre-baked version of Prism with some languages and no plugins, and then include anything additional as a separate file, manually.

I was thinking something like the URL parameters of polyfill.io would be very useful, with aliases for common sets of components too. Thoughts?

**Comment by thomasdavis** [comment]
Hi @LeaVerou,

Thanks for the kind words! We don't actually support this at the moment, the reason being, that it does demand a lot more resources to serve an exponential amount of combinations of scripts. 

We are meeting this week to talk about future plans and we will definitely revisit this idea.

In the mean time, there is an awesome alternative called Jsdelivr(http://www.jsdelivr.com/) that should do what you need.

Keep up the good work at Prism, I've been using it on and off for years!

**Comment by MattIPv4** [comment]
This doesn't seem very practical + no further progress. Closing.
