### ISSUE TITLE
[Request] Add angular-parse 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8180]
**Library name:** angular-parse
**Git repository url:** https://github.com/ivnivnch/angular-parse

**Comment by Amomo** [comment]
@PeterDaveHello this lib seems not have enough popularity, should we add it?

**Comment by PeterDaveHello** [comment]
Yes.

**Comment by sashberd** [comment]
@MattIPv4 Please review this one. Thanks
