### ISSUE TITLE
[Request] Add Noctua Art

### ISSUE THREAD

**Issue by Noctuaart** [cdnjs/cdnjs#8186]
Noctua Art
Git repository url: https://github.com/Noctuaart/cdn

http://www.noctuaart.com.br/sem/dist/css/styles.min.css
http://www.noctuaart.com.br/js/waypoints.min.js
http://www.noctuaart.com.br/sem/dist/js/all.min.js
http://www.noctuaart.com.br/_imgs/_sem/servico1_googlelogo.jpg
http://www.noctuaart.com.br/_imgs/_sem/caminhoes.gif
http://www.noctuaart.com.br/_imgs/_sem/caminhoes_sm.gif
http://www.noctuaart.com.br/_imgs/_sem/grafico_beneficios_xs.gif
http://www.noctuaart.com.br/_imgs/_sem/grafico_beneficios_sm.gif
http://www.noctuaart.com.br/_imgs/_sem/grafico-_beneficios.png
http://www.noctuaart.com.br/_imgs/_sem/bg.jpg
http://www.noctuaart.com.br/_imgs/_sem/grafico_flut1.png
http://www.noctuaart.com.br/_imgs/_sem/grafico_flut2.png
http://www.noctuaart.com.br/_imgs/_sem/grafico_flut3.png
http://www.noctuaart.com.br/_imgs/_sem/monitor1.png
http://www.noctuaart.com.br/_imgs/_sem/cafe.png
http://www.noctuaart.com.br/_imgs/_sem/livro.png
http://www.noctuaart.com.br/_imgs/_sem/monitor2.png
http://www.noctuaart.com.br/_imgs/_sem/luminaria.png
http://www.noctuaart.com.br/_imgs/_sem/tablet.png
http://www.noctuaart.com.br/_imgs/_sem/ulitem.png
http://www.noctuaart.com.br/_imgs/_sem/relatorios_personalizados_md.jpg
http://www.noctuaart.com.br/_imgs/_sem/transicao01.gif
http://www.noctuaart.com.br/_imgs/_sem/transicao02.gif

**http://www.noctuaart.com.br:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Amomo** [comment]
Hi @Noctuaart 
All new libraries hosted on CDNJS should have an official public repository or npm package, and the officially pre-built distribution file(s) should also be there, so that we can apply the auto-update mechanism on that lib.

I am sorry, we can't host these files for you.

> This issue will be closed if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
Close due to no response.
