### ISSUE TITLE
[Request] Add data-layer-helper 

### ISSUE THREAD

**Issue by SergeAx** [cdnjs/cdnjs#8188]
**Library name:** data-layer-helper
**Git repository url:** https://github.com/google/data-layer-helper
**npm package url(optional):** https://libraries.io/npm/data-layer-helper
**License(s):** Apache 2.0
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello As I saw you closed PR because of no response from the author fro git tags. Should we also close the issue?

**Comment by PeterDaveHello** [comment]
@sashberd the old PR is stale so close it and everyone can send a new one.
