### ISSUE TITLE
[Request] Add qs 

### ISSUE THREAD

**Issue by natesilva** [cdnjs/cdnjs#8190]
**Library name:** qs
**Git repository url:** https://github.com/ljharb/qs
**npm package url(optional):** https://www.npmjs.com/package/qs
**License(s):** BSD-3-Clause
**Official homepage:** https://github.com/ljharb/qs
**Wanna say something? Leave message here:**

A minimalist library for building query strings. Originally created by the prolific TJ Holowaychuk.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by natesilva** [comment]
Thank you! 🚀

**Comment by PeterDaveHello** [comment]
@natesilva You're welcome.
