### ISSUE TITLE
[Request] Add alloyeditor 

### ISSUE THREAD

**Issue by NetanelBasal** [cdnjs/cdnjs#8199]
**Library name:** alloyeditor
**Git repository url:** https://github.com/liferay/alloy-editor
**npm package url(optional):** https://www.npmjs.com/package/alloyeditor
**License(s):**LGPL-3.0
**Official homepage:** http://alloyeditor.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by SylwesterZarebski** [comment]
Is there any progress lately?

**Comment by sufuf3** [comment]
5,256 downloads in the last month from npm (over 5000+)

**Comment by SylwesterZarebski** [comment]
Better later than never, thanks :-)
