### ISSUE TITLE
[Request] Add stripe/jquery.mobilePhoneNumber

### ISSUE THREAD

**Issue by judicapo** [cdnjs/cdnjs#8209]
**Library name:** jquery.mobilePhoneNumber
**Git repository url:** https://github.com/stripe/jquery.mobilePhoneNumber
**npm package url(optional):** 
**License(s):** https://github.com/stripe/jquery.mobilePhoneNumber/blob/master/LICENSE
**Official homepage:** not listed
**Wanna say something? Leave message here:** It is a popular js that Stripe uses to validate phone number inputs, it is really useful for both users and developers in order to fill forms that includes phone numbers, actually have 265 stars "https://github.com/stripe/jquery.mobilePhoneNumber/stargazers".

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ricardopolo** [comment]
:+1:

**Comment by judicapo** [comment]
Hello, is it any requirement missing? Do I have to help with something? I would like to thank you of been attending this issue.

**Comment by PeterDaveHello** [comment]
@judicapo There are many request issues, please wait with patient, thanks.

**Comment by ricardopolo** [comment]
Hi, I understand there are lots of request but please don't forget this one :)

Thank you so so much!

**Comment by PeterDaveHello** [comment]
Duplicated with #8070
