### ISSUE TITLE
[Request] accursoft/caret

### ISSUE THREAD

**Issue by judicapo** [cdnjs/cdnjs#8210]
**Library name:** accursoft/caret
**Git repository url:** https://github.com/accursoft/caret
**npm package url(optional):** 
**License(s):** https://github.com/accursoft/caret/blob/master/license.txt
**Official homepage:** http://plugins.jquery.com/caret/
**Wanna say something? Leave message here:** the issue #8209 has dependency of this library. 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@judicapo 
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity, it seems it won't take much time :smiley: 
you can suggest the author to add a version number for it, that will help us add this lib more quickly. 
thanks!

this issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by ricardopolo** [comment]
Hi @maruilian11 can you review this again please?

Altought this library is not very popular a very popular library by Stripe depends on it, so maybe thats a good reason to include it. I am talking about this library https://github.com/cdnjs/cdnjs/issues/8209

Please also reffer to this thread https://github.com/cdnjs/cdnjs/issues/7647 where we discuss about only including popular libraries.  Over there people said if a library doesnt have popularity but have a good reason to include it it can be included.

I think this time is that the case :)

Thank you so much for your answer @maruilian11

**Comment by maruilian11** [comment]
@PeterDaveHello since a popular lib depends on this lib, i think we can add this lib.

**Comment by PeterDaveHello** [comment]
Looks like this lib doesn't even have a valid version, should fix that first.

**Comment by maruilian11** [comment]
@accursoft could you please consider adding version number for **caret**, or can we regard the current files as v1.0.0?
thank you!

**Comment by accursoft** [comment]
I used to maintain a version number, but it was just adding noise without actually adding anything useful.

The latest/supported version is always `master`. If you want to pin a specific version use the commit hash.

**Comment by ricardopolo** [comment]
@accursoft having a version number is really important when your project is going to be published in a CDN or a package manager like NPM. 

Its very important when you are going to integrate a external package in your project. So, please, if you re think that our team will really appreciate it and the people at Cdnjs would help us publishing Caret in their CDN :)

Thanks in advance

**Comment by accursoft** [comment]
OK, I've tagged `v1.0.0`.
