### ISSUE TITLE
[Request] loadjs

### ISSUE THREAD

**Issue by amorey** [cdnjs/cdnjs#8212]
Library name: loadjs
Git repository url: https://github.com/muicss/loadjs
npm package url(optional): https://www.npmjs.com/package/loadjs
License(s): MIT
Official homepage: https://github.com/muicss/loadjs

A loadjs user asked us to add it to cdnjs:
https://github.com/muicss/loadjs/issues/19

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by amorey** [comment]
Thanks!!

**Comment by PeterDaveHello** [comment]
@amorey you're welcome.
