### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/fonts/fontawesome-webfont.svg 

### ISSUE THREAD

**Issue by Abdurraheem** [cdnjs/cdnjs#8219]
**Library name:** https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/fonts/fontawesome-webfont.svg
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @Abdurraheem ,
More detail about this library?
Like **Git repository url** or **npm package url**.
Thanks!

**Comment by kennynaoh** [comment]
close due to exiting on [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/font-awesome/4.4.0)
cc @PeterDaveHello
