### ISSUE TITLE
[Request] Add chrono 

### ISSUE THREAD

**Issue by kennynaoh** [cdnjs/cdnjs#8222]
**Library name:** chrono
**Git repository url:** https://github.com/wanasit/chrono
**npm package url(optional):** https://www.npmjs.com/package/chrono-node
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@kennynaoh why don't you label it?

**Comment by kennynaoh** [comment]
Sorry, I forgot it.
I will be more careful next time.

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh, there is another issue #8762 may want this lib.
