### ISSUE TITLE
[Request] Barba.js

### ISSUE THREAD

**Issue by fabianhick** [cdnjs/cdnjs#8223]
**Library name:** Barba.js
**Git repository url:** https://github.com/luruke/barba.js
**npm package url(optional):** 
**License(s):** Barba.js is created in the spare time by Luigi De Rosa and released under MIT licence.
**Official homepage:**http://barbajs.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by fabianhick** [comment]
Thanks :)

**Comment by PeterDaveHello** [comment]
@kennynaoh note that this is duplicated with an old issue, should close that in the same commit, or just close one of them before sending new PR.
