### ISSUE TITLE
[Request] Add jsgif

### ISSUE THREAD

**Issue by patrickroberts** [cdnjs/cdnjs#8225]
**Library name:** jsgif
**Git repository url:** https://github.com/antimatter15/jsgif/
**License(s):** MIT
**Official homepage:** https://antimatter15.com/project/jsgif/

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello  Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by patrickroberts** [comment]
Unfortunate... oh well.
