### ISSUE TITLE
[Request] deep-freeze

### ISSUE THREAD

**Issue by aymans** [cdnjs/cdnjs#8231]
**Library name:** deep-freeze
**Git repository url:** https://github.com/substack/deep-freeze
**npm package url(optional):** 
**License(s):** [public domain](https://github.com/substack/deep-freeze/blob/master/LICENSE)
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by patrickgaskill** [comment]
@gaearon 's Redux courses on egghead use a CDN version of deep-freeze, would be great to have on here. The links in the videos now seem to be broken.

**Comment by PeterDaveHello** [comment]
Its author haven't decided to provide a host-able version yet, see
https://github.com/substack/deep-freeze/issues/14

Feel free to open a new issue once we can host it, thanks.
