### ISSUE TITLE
[Request] Add qad 

### ISSUE THREAD

**Issue by alex2844** [cdnjs/cdnjs#8237]
**Library name:** qad
**Git repository url:** https://github.com/alex2844/qad
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://www.pcmasters.ml/docs/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @alex2844 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
