### ISSUE TITLE
[Request] Add cytoscape-cola 

### ISSUE THREAD

**Issue by Jargon64** [cdnjs/cdnjs#8240]
**Library name:** cytoscape-cola
**Git repository url:** https://github.com/cytoscape/cytoscape.js-cola
**npm package url(optional):** https://www.npmjs.com/package/cytoscape-cola
**License(s):** MIT
**Official homepage:** https://github.com/cytoscape/cytoscape.js-cola
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Jargon64 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
a
