### ISSUE TITLE
[Request] Add Holmes 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8244]
**Library name:** Holmes
**Git repository url:** https://github.com/Haroenv/holmes/
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by dakshshah96** [comment]
@PeterDaveHello If I want to add this library without using single package.json, do I need to create folders for all versions manually? There are a total of [46 releases](https://github.com/Haroenv/holmes/releases) for this library.

**Comment by PeterDaveHello** [comment]
@dakshshah96 For the versions can fit the auto-update config, you don't need to manually add them, just add the latest version!

**Comment by PeterDaveHello** [comment]
@dakshshah96 btw, I think you can try to use the auto-updater to test if the config works in the meantime!

**Comment by dakshshah96** [comment]
@PeterDaveHello Are these all the files that we should include for the holmes library?

```
js/holmes.js
css/style.css
```

**Comment by PeterDaveHello** [comment]
I'm not sure about main.js, wanna open an issue to discuss with its author?

**Comment by dakshshah96** [comment]
@PeterDaveHello Done 👍 https://github.com/Haroenv/holmes/issues/91

Awaiting authors response.

**Comment by PeterDaveHello** [comment]
@dakshshah96 nice!
