### ISSUE TITLE
[Request] Add js-scrypt

### ISSUE THREAD

**Issue by athanclark** [cdnjs/cdnjs#8253]
**Library name:** js-scrypt 
**Git repository url:** https://github.com/tonyg/js-scrypt
**npm package url(optional):** https://www.npmjs.com/package/js-scrypt
**License(s):** BSD-2
**Official homepage:** https://github.com/tonyg/js-scrypt
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
https://github.com/tonyg/js-scrypt#using-the-library
>>>
Note that the file browser/scrypt_raw.js.mem must also be retrievable alongside scrypt.js

@PeterDaveHello can we also host `.mem` files? the author said he has been trying to use rawgit.com as an alternative for this, but for some reason the `.mem` file isn't reachable.
https://github.com/tonyg/js-scrypt/issues/20#issuecomment-238072527

**Comment by PeterDaveHello** [comment]
@maruilian11 This is a strange case, what is that for?

**Comment by maruilian11** [comment]
@PeterDaveHello `.mem` file is a memory variable file and it seems to not directly readable.
i think it's unsuitable to host it on cdnjs, but it seems a necessary file for this lib.

**Comment by PeterDaveHello** [comment]
@maruilian11 Is there any way to manually load it from user specified source? I dont think we will host this kind of file.

**Comment by athanclark** [comment]
It's precompiled output from [emscripten](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#memory-initialization)

**Comment by tonyg** [comment]
From js-scrypt v1.2.0 the .mem file is no longer required.

**Comment by PeterDaveHello** [comment]
@tonyg Nice.

**Comment by maruilian11** [comment]
@tonyg would you please also put released versions to npm pacakge so that we turn to use npm auto-update which is more recommended. :smiley:

**Comment by tonyg** [comment]
@maruilian11: If it can work without being uploaded to npm, I think I'd prefer that. The code is intended for use in the browser, where the "real" scrypt library is unavailable. There are many, many options for using the actual scrypt machine-code for people who are using node. None of the npm packages incorporating js-scrypt code were created by me or are under my control, and I don't have any node.js support in the js-scrypt package at the moment.

**Comment by maruilian11** [comment]
@tonyg thanks, we will keep using git auto-update.
