### ISSUE TITLE
[Request] ionicons

### ISSUE THREAD

**Issue by yuye3248** [cdnjs/cdnjs#8270]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @yuye3248 , could you please provide the git repo url or npm package url? thank you!

**Comment by maruilian11** [comment]
close due to no response.
