### ISSUE TITLE
[Request] Add Algolia Places

### ISSUE THREAD

**Issue by xtheonexuk** [cdnjs/cdnjs#8277]
Algolia Places 
https://github.com/algolia/places
**npm package url(optional):** 
https://github.com/algolia/places/blob/master/LICENSE
http://community.algolia.com/places/

I notice you're already using Algolias realtime search but you don't have places in your repos. Please fix this ;)

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
I don't think there is something should be "fixed", but we'll host this lib :+1:
