### ISSUE TITLE
[Request] Add recorderjs

### ISSUE THREAD

**Issue by giladaya** [cdnjs/cdnjs#8284]
**Library name:** recorderjs
**Git repository url:** https://github.com/mattdiamond/Recorderjs
**npm package url(optional):** https://www.npmjs.com/package/recorderjs
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by joe-tom** [comment]
+1
