### ISSUE TITLE
[Request] Add zip.js 

### ISSUE THREAD

**Issue by JamesWClark** [cdnjs/cdnjs#8290]
**Library name:** zip.js
**Git repository url:https://github.com/gildas-lormeau/zip.js
**npm package url(optional):** 
**License(s):**
**Official homepage:https://gildas-lormeau.github.io/zip.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by JamesWClark** [comment]
nevermind -

**Comment by PeterDaveHello** [comment]
@JamesWClark maybe you can try this one: https://cdnjs.com/libraries/jszip
