### ISSUE TITLE
[Request] Add jetline 

### ISSUE THREAD

**Issue by Archin-modi** [cdnjs/cdnjs#8293]
**Library name:** jetlineui
**Git repository url: https://github.com/Archin-modi/Jquery-Theme-Switcher**
**npm package url(optional):** 
**License(s):MIT License **
**Official homepage: http://www.jetline-ui.somee.com/Theme_Switcher/Get_Start **
**Wanna say something? Leave message here: i want add this js and css file in cdn**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Archin-modi ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
