### ISSUE TITLE
[Request] Add docsearch.js 

### ISSUE THREAD

**Issue by kennynaoh** [cdnjs/cdnjs#8297]
**Library name:** docsearch.js
**Git repository url:** https://github.com/algolia/docsearch
**npm package url(optional):** https://www.npmjs.com/package/docsearch.js
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by redox** [comment]
Awesome, thank you guys 👍

**Comment by PeterDaveHello** [comment]
@redox maybe you can ping me when Algolia has a new lib, we'll definitely add it immediately.

**Comment by redox** [comment]
> @redox maybe you can ping me when Algolia has a new lib, we'll definitely add it immediately.

Ah cool :) Will do!

**Comment by PeterDaveHello** [comment]
@redox Thanks :)
