### ISSUE TITLE
[Request] Add console-polyfill

### ISSUE THREAD

**Issue by ifelsee** [cdnjs/cdnjs#8308]
**Library name:** 
**Git repository url:** https://github.com/paulmillr/console-polyfill
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @ifelsee , is there any detail? This issue will be closed if no response in 7 days.

**Comment by pvnr0082t** [comment]
Maybe we can add this https://github.com/paulmillr/console-polyfill

**Comment by ifelsee** [comment]
thanks very much!

**Comment by PeterDaveHello** [comment]
@ifelsee NP
