### ISSUE TITLE
[author] jQuery.Lazy missing update

### ISSUE THREAD

**Issue by eisbehr-** [cdnjs/cdnjs#8310]
Hello,

I've updated my project [jquery.lazy](https://github.com/eisbehr-/jquery.lazy) and I'm missing the auto-update from cdnjs. Are there any problems? I ask because I'll changed the package.json some days before in PR #8147. Just to be sure nothing went wrong ...

Thanks.

**Comment by PeterDaveHello** [comment]
Didn't see any problem here, is there anything wrong?

**Comment by eisbehr-** [comment]
Ahh. No. Not anymore. :sweat_smile:
Last time I looked there was no new version in the folder. But it seems to be my fault. Sorry for the trouble.

**Comment by PeterDaveHello** [comment]
@eisbehr- I don't think there is any problem, this lib didn't been updated immediately just because the structure changed, and the bot can not handle the structure changes yet, so I need to review the update.

**Comment by eisbehr-** [comment]
@PeterDaveHello Yes, I was thinking something about the change went wrong. Thanks for your explanation.
But the files are still not reachable over cdn. Is this a problem with the changes too, or did it just need some more time?

**Comment by PeterDaveHello** [comment]
@eisbehr- Hmmmm ... I will take a look at it asap.

**Comment by eisbehr-** [comment]
Okay, I'll open the issue again then. :wink:

**Comment by PeterDaveHello** [comment]
Fixed.
