### ISSUE TITLE
How to publish my own JS through CDNJS

### ISSUE THREAD

**Issue by dipankar08** [cdnjs/cdnjs#8314]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by ricardopolo** [comment]
Please read the contributing guides
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md

If your JS is only used by you, dont have some popularity you cannot upload it to CDNJs. Please go to Jsdelivr.

**Comment by PeterDaveHello** [comment]
Thanks @ricardopolo
