### ISSUE TITLE
[Request] Add zip2addr 

### ISSUE THREAD

**Issue by golorih** [cdnjs/cdnjs#8321]
**Library name:** zip2addr
**Git repository url:** https://github.com/kotarok/jQuery.zip2addr
**npm package url(optional):** 
**License(s):** Dual licensed under the MIT or GPL Version 2 licenses.
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello The library still has low popularity and also there is no answer from author on request add git tag and time passed from current request was opened. Suggest to close

**Comment by PeterDaveHello** [comment]
@sashberd I see there is still update recently in that repo, maybe you'd like to ping its author in the issue in case it's missed?
