### ISSUE TITLE
[Request] Add hyphenator 

### ISSUE THREAD

**Issue by sebwas** [cdnjs/cdnjs#8324]
**Library name:** hyphenator
**Git repository url:** https://github.com/mnater/hyphenator
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://mnater.github.io/Hyphenator/

@mnater FYI

**Comment by mnater** [comment]
https://github.com/cdnjs/cdnjs/issues/8050

**Comment by sebwas** [comment]
![Herp derp](http://i2.kym-cdn.com/photos/images/original/000/270/676/83b.png)
Thanks.
