### ISSUE TITLE
[Request] Add selectordie 

### ISSUE THREAD

**Issue by stevieg83** [cdnjs/cdnjs#8325]
**Library name:** selectordie
**Git repository url:** https://github.com/vestman/Select-or-Die
**npm package url(optional):** https://www.npmjs.com/package/select-or-die-mt
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@PeterDaveHello 

The github page in the npm is not same as the github page here.
Which do I need to add?

**Comment by PeterDaveHello** [comment]
@x09326 they seem to be two libs.

**Comment by x09326** [comment]
The github page in the npm is forked from the github page here.

**Comment by PeterDaveHello** [comment]
@x09326 but the forked one is not popular enough
