### ISSUE TITLE
[Request] Add amplitude 

### ISSUE THREAD

**Issue by cdll** [cdnjs/cdnjs#8338]
**Library name:** amplitude
**Git repository url:** https://github.com/amplitude/Amplitude-Javascript
**npm package url(optional):** https://www.npmjs.com/package/node-amplitude
**License(s):**MIT
**Official homepage:**https://amplitude.com/
**Wanna say something? Leave message here:** a common js library that most webber will use, hope for supported~

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @cdll ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our README.md for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.
Thanks!

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to not enough popularity.
Thanks @cdll
