### ISSUE TITLE
cdnjs seems down.

### ISSUE THREAD

**Issue by vjnathe-webonise** [cdnjs/cdnjs#8341]
cdnjs seems down from long time. not able to access any of library.How you can assure 100% uptime ?

**Comment by thomasdavis** [comment]
Everything working for me, do you have an example url?

**Comment by vjnathe-webonise** [comment]
https://cdnjs.cloudflare.com/ajax/libs/react-router/2.4.0/ReactRouter.min.js

**Comment by vjnathe-webonise** [comment]
even https://cdnjs.com/ not opening

**Comment by PeterDaveHello** [comment]
@vjnathe-webonise Yoir netwrok might been blocked by CloudFlare.

**Comment by vjnathe-webonise** [comment]
how i get to know the reason behind it ?

**Comment by PeterDaveHello** [comment]
@vjnathe-webonise Can you access other sites behind CloudFlare? Like feedly.com or digitalocean.com and their own cloudflare.com

**Comment by vjnathe-webonise** [comment]
@PeterDaveHello  yes i am able to access both

**Comment by PeterDaveHello** [comment]
@vjnathe-webonise Okay I got it, would you please open a support ticket on CloudFlare? @terinjokes would you please take a look at this issue? Thanks.

**Comment by thomasdavis** [comment]
@vjnathe-webonise Which country are you accessing from?

**Comment by vjnathe-webonise** [comment]
INDIA. Its seems up now.. i am able to access it. what was the issue ?

**Comment by PeterDaveHello** [comment]
Only CloudFlare knows the problem.

**Comment by vjnathe-webonise** [comment]
@PeterDaveHello @thomasdavis  Thanx for the help
