### ISSUE TITLE
[Request] Add angular-ui-notification.min.css   

### ISSUE THREAD

**Issue by Tengale** [cdnjs/cdnjs#8347]
**Library name:** angular-ui-notification.min.css
**Git repository url:** https://github.com/alexcrack/angular-ui-notification
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Tengale , is there any detail? This issue will be closed if no response in 7 days.

**Comment by pvnr0082t** [comment]
Maybe we can add https://github.com/alexcrack/angular-ui-notification.
