### ISSUE TITLE
[Request] Add selftype 

### ISSUE THREAD

**Issue by lmenus** [cdnjs/cdnjs#8348]
**Library name:** selftype
**Git repository url:** https://github.com/lmenus/selftype
**npm package url(optional):** https://www.npmjs.com/package/selftype
**License(s):** MIT
**Official homepage:** http://lmen.us
**Wanna say something? Leave message here:** Please include this :D Thank you!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @lmenus ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by lmenus** [comment]
Hi Daniel,

OK will do, thanks! Sorry I'm still new to open source so didn't get to grips with how it all works :/

Lubos

**Comment by PeterDaveHello** [comment]
No mind, feel free to open an new issue or pull request when you got a higher popularity, we'll be happy to host then.
