### ISSUE TITLE
Dropify

### ISSUE THREAD

**Issue by selvavalluvan** [cdnjs/cdnjs#8349]
**Library name:**Dropify 
**Git repository url:**https://github.com/JeremyFagis/dropify
**npm package url(optional):** https://www.npmjs.com/package/dropify
**License(s):**
**Official homepage:**http://jeremyfagis.github.io/dropify
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
close due to it had been merged. #8382
