### ISSUE TITLE
[Request] Add https://github.com/j3k0/cordova-non-renewing-subscription 

### ISSUE THREAD

**Issue by wmworia** [cdnjs/cdnjs#8359]
**Library name:** https://github.com/j3k0/cordova-non-renewing-subscription
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @wmworia ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our README.md for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.
Thanks!

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to no response.
Thanks @wmworia 

cc @PeterDaveHello
