### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css

### ISSUE THREAD

**Issue by dralkoud** [cdnjs/cdnjs#8366]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Why to request a exist lib?

**Comment by pvnr0082t** [comment]
close due to no response.
