### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/ionicons 

### ISSUE THREAD

**Issue by treaconsultium** [cdnjs/cdnjs#8376]
**Library name:** https://cdnjs.cloudflare.com/ajax/libs/ionicons
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Why to request a exist lib?

**Comment by pvnr0082t** [comment]
close due to no response.
