### ISSUE TITLE
[Request] Add animatedModal

### ISSUE THREAD

**Issue by robanhl** [cdnjs/cdnjs#8385]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @robanhl , I found that there is https://github.com/joaopereirawd/animatedModal.js/. Is this what you request?

**Comment by PeterDaveHello** [comment]
move to #9494
