### ISSUE TITLE
[Request] Add cbpAnimatedHeader 

### ISSUE THREAD

**Issue by dev-yosh1** [cdnjs/cdnjs#8387]
**Library name:** cbpAnimatedHeader
**Git repository url:** https://github.com/codrops/AnimatedHeader/tree/master/js
**Official homepage:** http://tympanus.net/codrops/
**Wanna say something? Leave message here:** please add this to cdn.

cbpAnimatedHeader.js    Fix AnimatedHeader on reload.   8 months ago
cbpAnimatedHeader.min.js    Updated -min version.   8 months ago
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@dev-yosh1 thanks for your request, but it seems that this repository has already existed in [cdnjs](https://cdnjs.com/libraries/animated-header)

cc @PeterDaveHello
