### ISSUE TITLE
[Request] Add suncream.min.css

### ISSUE THREAD

**Issue by naruas** [cdnjs/cdnjs#8403]
**Library name: Suncream** 
**Git repository url: https://github.com/naruas/Suncream.git**
**npm package url(optional):readying** 
**License(s): MIT License**
**Official homepage:https://github.com/naruas/Suncream**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @naruas ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by naruas** [comment]
Hello @pvnr0082t 

I just understood that.
Thank you for your advice :)

**Comment by PeterDaveHello** [comment]
@naruas feel free to send the request again once you got a notable popularity, thanks for your contribution!
