### ISSUE TITLE
ui-bootstrap-tpls.js

### ISSUE THREAD

**Issue by padmashreeudupi** [cdnjs/cdnjs#8408]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@padmashreeudupi Please provide the details about the library information,such as ```Git repository url```, thanks!

**Comment by nolsherry** [comment]
Closed due to no response.
