### ISSUE TITLE
[Request][Author] Add AvatarJS

### ISSUE THREAD

**Issue by IPENGR** [cdnjs/cdnjs#8409]
**Library name:** AvatarJS
**Git repository url:**https://github.com/IPENGR/AvatarJS
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**https://github.com/IPENGR/AvatarJS
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello According to author there is only 1 version 0.2. Maybe we could add it manually? What do you think?

**Comment by sashberd** [comment]
Hi @IPENGR 
The library doesn't have enough popularity(200 stars/watchers on GitHub and 800 downloads/month on npm registry are good examples). You can take a look at our issue rule for more details 😄

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

Thank you for your request!
