### ISSUE TITLE
[Request] Add route-recognizer

### ISSUE THREAD

**Issue by x09326** [cdnjs/cdnjs#8410]
**Library name:** route-recognizer
**Git repository url:**https://github.com/tildeio/route-recognizer
**npm package url(optional):** https://www.npmjs.com/package/route-recognizer
**License(s):**MIT
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by rafegoldberg** [comment]
pretty please?
