### ISSUE TITLE
[Request] Add stickyNavbar.js 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#8413]
**Library name:** stickyNavbar.js
**Git repository url:** https://github.com/jbutko/stickyNavbar.js
**npm package url(optional):** https://www.npmjs.com/package/stickyNavbar.js
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by jbutko** [comment]
Versions mismatch fixed. Can be closed. Thank you.

**Comment by pvnr0082t** [comment]
@jbutko Thanks for your help.
