### ISSUE TITLE
[Request] Update Dojo to the newest version 1.11.2

### ISSUE THREAD

**Issue by ArminMueller** [cdnjs/cdnjs#8414]
Note: If you'd like to request a new library, please follow this link: https://cdnjs.com/request-new-lib

**Comment by ArminMueller** [comment]
I have seen that up to now there is only dojo itself included without dijit, dojox and themes. Are there any plans to add the full dojo library?

**Comment by ArminMueller** [comment]
sorry do not want close

**Comment by dylans** [comment]
This will be redundant with #10349 when that is addressed.

**Comment by PeterDaveHello** [comment]
Since  #10349 has more details, move to  #10349, thanks
