### ISSUE TITLE
[Request] Add jPanelMenu

### ISSUE THREAD

**Issue by austinbiggs** [cdnjs/cdnjs#8417]
jPanelMenu
https://github.com/acolangelo/jPanelMenu
MIT License
http://jpanelmenu.com/
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by AustinTBiggs** [comment]
bump 😄  - @qwe19272375  @PeterDaveHello

**Comment by sufuf3** [comment]
@AustinTBiggs Thanks for reminder.

The lib on npm is not officially. (Someone fork this lib from git repo and publish by other.)
Just add the lib from GitHub repo is fine.
@maruilian11 Would you mind adding this lib in your own time? Because this issue is assigned to you.

Many thanks.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
