### ISSUE TITLE
[Request] Add angular-animate 

### ISSUE THREAD

**Issue by julianonunes** [cdnjs/cdnjs#8418]
**Library name:** angular-animate
**Git repository url:** https://github.com/angular/bower-angular-animate
**npm package url(optional):** https://www.npmjs.com/package/angular-animate
**License(s):** The MIT License
**Official homepage:** http://docs.angularjs.org/api/ngAnimate
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
Hello @NgDashboard,
I am the member of cdnjs project.
We want to host this library.
I found the latest version is ```v1.5.8-build.4928+sha.e8c2e11``` on github, but the latest version on npm is v1.5.7. Could you update the latest version on npm?
Thank you very much!

cdnjs/cdnjs#8418

**Comment by MattIPv4** [comment]
Available on cdnjs: https://cdnjs.com/libraries/angular-animate
