### ISSUE TITLE
[Request] Add microevent.js

### ISSUE THREAD

**Issue by x09326** [cdnjs/cdnjs#8426]
**Library name:** microevent.js
**Git repository url:**https://github.com/jeromeetienne/microevent.js
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**http://notes.jetienne.com/2011/03/22/microeventjs.html
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@x09326 don't forget the label.
