### ISSUE TITLE
[Request] extjs 3.3.1 (3.4 has a problem for some of us)

### ISSUE THREAD

**Issue by oualidfouad** [cdnjs/cdnjs#8430]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @tripleatube , is there any detail? This issue will be closed if no response in 7 days.

**Comment by PeterDaveHello** [comment]
What do you mean "3.4 has a problem for some of us" actually?

**Comment by tripleatube** [comment]
I solved it, thank you for your response.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please take a look if it's possible to add extjs v3.3.1, thanks.
