### ISSUE TITLE
[Request] Add antiscroll 

### ISSUE THREAD

**Issue by nikitakiselev** [cdnjs/cdnjs#8434]
**Library name:** antiscroll
**Git repository url:** https://github.com/Automattic/antiscroll
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://automattic.github.io/antiscroll/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nylen** [comment]
I've tagged the latest version of `antiscroll` as v0.9:

![image](https://cloud.githubusercontent.com/assets/227022/18602587/46872b4c-7c1f-11e6-8028-f8a2e6b818fc.png)

**Comment by PeterDaveHello** [comment]
@nylen Thanks.
