### ISSUE TITLE
[Request] Add DoubleTapToGo 

### ISSUE THREAD

**Issue by jmburnz** [cdnjs/cdnjs#8439]
**Library name:** DoubleTapToGo
**Git repository url:** https://github.com/zenopopovici/DoubleTapToGo
**npm package url(optional):** 
**License(s):** MIT https://github.com/zenopopovici/DoubleTapToGo/blob/master/LICENSE
**Official homepage:**
**Wanna say something? Leave message here:** Due to MIT licence it's not always possible to include this in distributions (where all included code must be GPL, e.g. Drupal contrib projects). The best alternative is cdnjs.com.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @jmburnz ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to no response.
