### ISSUE TITLE
[Request] Add RiTa

### ISSUE THREAD

**Issue by CyrusSUEN** [cdnjs/cdnjs#8442]
**Library name:** RiTa
**Git repository url:** https://github.com/dhowe/RiTaJS
**npm package url(optional):** https://www.npmjs.com/package/rita
**License(s):** GPL 3.0
**Official homepage:** http://rednoise.org/rita/
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
close due to the PR had been merged.
