### ISSUE TITLE
[Request] Add font-awesome

### ISSUE THREAD

**Issue by bababa358** [cdnjs/cdnjs#8448]
**Library name:** https://www.addgame-cheatz.xyz/bootstrap/css/font-awesome.css
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @bababa358 , I cannot access https://www.addgame-cheatz.xyz/bootstrap/css/font-awesome.css. Could you please provide more information? Thank you. This issue will be closed if no response in 7 days.

**Comment by pvnr0082t** [comment]
close due to no response.
