### ISSUE TITLE
[Request] Add Enllax.js

### ISSUE THREAD

**Issue by danieloliveira117** [cdnjs/cdnjs#8450]
**Library name:** Enllax.js
**Git repository url:** https://github.com/mmkjony/enllax.js
**License(s):** MIT (https://github.com/mmkjony/enllax.js/blob/master/LICENSE)
**Official homepage:** http://mmkjony.github.io/enllax.js/

**Comment by PeterDaveHello** [comment]
We can add this.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
