### ISSUE TITLE
[Request] Add fbbk-json 

### ISSUE THREAD

**Issue by XadillaX** [cdnjs/cdnjs#8452]
**Library name:** fbbk-json
**Git repository url:** https://github.com/XadillaX/fbibik-json
**npm package url(optional):** https://www.npmjs.com/package/fbbk-json
**License(s):** MIT
**Official homepage:** https://github.com/XadillaX/fbibik-json
**Wanna say something? Leave message here:**

Parse JSON-Object string (not normalized JSON string) into JSON object.

Something like:

```javascript
'{foo: \'bar\',baz: true,c:[]}'
```

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @XadillaX ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello
