### ISSUE TITLE
Update auto-update filemap of pileup 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8454]
pileup v0.6.7 changed the structure and caused the auto-updater fetched something we can not use directly.

**Comment by pvnr0082t** [comment]
@PeterDaveHello I don't know what we cannot use directly. Are the files fetched from `dist/main` and `dist/test`?

**Comment by PeterDaveHello** [comment]
@pvnr0082t It contains test files'

**Comment by pvnr0082t** [comment]
@PeterDaveHello I'd like to know why there is no test file before v0.6.7 because auto-updater will start to fetch `pileuputils-test.js` under `test` folder from v0.6.1. Is it because you manually added those files?

**Comment by PeterDaveHello** [comment]
@pvnr0082t You should use git log to check the history then you'll know who committed the updates, the problem is the new main and test folder.
