### ISSUE TITLE
Update auto-update filemap of infamous

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8455]
infamous v8 changed the structure and caused the auto-updater fetched something we can not use directly.

**Comment by PeterDaveHello** [comment]
Wait for @trusktr

**Comment by kennynaoh** [comment]
Hello @trusktr
So, will you change the filename to `infamous.js`?
That will be easy to us for helping you host this library and we can add the auto-update config to add file automatically when you publish the new version.
Thanks for your contribution.

cc @PeterDaveHello

**Comment by trusktr** [comment]
Hey guys, got your message. I am currently publishing the `global.js` in the root of the package as of `v11.0.2`. Would that work? Or does it have to be specifically `infamous.js`?

**Comment by trusktr** [comment]
And for example, I can use it from the github repo using rawgit like this: https://cdn.rawgit.com/infamous/infamous/v11.0.2/global.js

**Comment by PeterDaveHello** [comment]
@trusktr it'll be better not to change the name, so that users can easily switch between different versions by changing version number only, agree?

**Comment by trusktr** [comment]
I agree, plus the name "global" makes it clear that it's the file to use
with the global patterns rather than with `require()` or `import`; it
provides a hint for the programmers just getting started with JS for the
first time.

**Comment by sashberd** [comment]
@PeterDaveHello @trusktr The version now is 19.0.4 and the name of file is still global.js
@PeterDaveHello Should we update auto-update pattern?
