### ISSUE TITLE
403 error accessing multiple common files

### ISSUE THREAD

**Issue by erikmartinessanches** [cdnjs/cdnjs#8467]
I'm getting 403 responses (server recognized but wouldn't process) while trying to access common files such as jquery, bootstrap, respondjs, modernizr, font awesome, etc on cdnjs. I copy and pasted the tags provided by cdnjs into the head section of my site. I'm running an ASP.NET MVC project, this happens locally and while on Azure (hosting). (I'm presently using http, is it fine to use the https resources from cdnjs?)

**Comment by PeterDaveHello** [comment]
Can you show be the result of using curl or wget to fetch the file with verbose output?

**Comment by erikmartinessanches** [comment]
It works now and I can't replicate the problem. I've changed to using ASP.NET MVC's build in facility for getting scripts and styles from a CDN using the instructions [here](https://www.asp.net/mvc/overview/performance/bundling-and-minification) rather than pasting links into the layout view itself.
