### ISSUE TITLE
[Request] Add lambci 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#8470]
**Library name:** lambci
**Git repository url:**https://github.com/lambci/lambci
**npm package url(optional):** https://www.npmjs.com/package/lambci
**License(s):**MIT
**Official homepage:**https://medium.com/@hichaelmart/lambci-4c3e29d6599b#.o8h77094q
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Not really sure why we would add CI projects to a primarily browser-based CDN service. Closing.
