### ISSUE TITLE
[Request] Add ec.js 

### ISSUE THREAD

**Issue by Justin-Maxwell** [cdnjs/cdnjs#8471]
**Library name:** 
jsbn / Tom Wu's jsbn library
(including rsa/ec/rng etc)

**Git repository url:** 
https://github.com/kjur/jsrsasign/tree/master/ext
(most, but not all of Tom Wu's bits are incorporated into jrsasign, including minified)

https://github.com/hoangductho/jsbn 
(appears to be a simple upload of http://www-cs-students.stanford.edu/~tjw/jsbn/)

**npm package url(optional):** 
https://www.npmjs.com/package/jsbn
(via the hoangductho/jsbn github repo above

**License(s):** 
http://www-cs-students.stanford.edu/~tjw/jsbn/LICENSE

**Official homepage:** 
http://www-cs-students.stanford.edu/~tjw/jsbn/

**Wanna say something? Leave message here:**

There doesn't seem to be an 'official github' for these, but they are widely used at the core of many/most symmetric encryption javascript libraries (including jsrsasign).  Very stable, and probably worth adding 'manually' if necessary since the full set at hoangductho/jsbn doesn't have minified versions, and kjur/jsrsasign is incomplete <sigh>

Files from jsrsasign/tree/master/ext:
- jsbn.js jsbn-min.js 
- jsbn2.js jsbn2-min.js
- rsa.js rsa-min.js
- rsa2.js rsa2-min.js
- ec.js ec-min.js 
- sec.js NOT INCLUDED AT jrsasign
- rng.js rng-min.js
- prng4.js prng4-min.js
- base64.js base64-min.js
- sha1.js NOT INCLUDED AT jrsasign

Some of these are at https://cdnjs.com/libraries/cryptico
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by smileytechguy** [comment]
any update?
