### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.1/js/formValidation.min.js 

### ISSUE THREAD

**Issue by djadhav16692** [cdnjs/cdnjs#8476]
**Library name:** https://cdnjs.cloudflare.com/ajax/libs/formvalidation/0.6.1/js/formValidation.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail? What's the problem here?

**Comment by pvnr0082t** [comment]
close due to no response.
