### ISSUE TITLE
[Request] Add jLouvain 

### ISSUE THREAD

**Issue by morkrispil** [cdnjs/cdnjs#8485]
**Library name:** jLouvain
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @morkrispil 
Could you provide more detail information about the library?
Like `Git repository url` or `npm package url`.
Thanks!

**Comment by morkrispil** [comment]
https://github.com/upphiminn/jLouvain/blob/master/jLouvain.js

Thank you

On Mon, Jul 11, 2016 at 8:11 AM, naoh <notifications@github.com> wrote:

> Hello @morkrispil <https://github.com/morkrispil>
> Could you provide more detail information about the library?
> Like Git repository url or npm package url.
> Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cdnjs/cdnjs/issues/8485#issuecomment-231643487>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEaFkW84afSrM5Qut3ADP823VYm7q8Z7ks5qUdB2gaJpZM4JIkiH>
> .
>



-- 
Thanks,

Mor

**Comment by PeterDaveHello** [comment]
@morkrispil Thanks.

**Comment by kennynaoh** [comment]
close due to not enough popularity.
Thanks @morkrispil 

cc @PeterDaveHello
