### ISSUE TITLE
[Request] Add locutus 

### ISSUE THREAD

**Issue by ryvkin** [cdnjs/cdnjs#8494]
**Library name:** locutus
**Git repository url:** https://github.com/kvz/locutus
**npm package url(optional):** https://www.npmjs.com/package/locutus
**License(s):** MIT
**Official homepage:** http://locutus.io
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello Author [said ](https://github.com/kvz/locutus/issues/307)that the library can not be hosted on cdnjs. Suggest to close

**Comment by PeterDaveHello** [comment]
Okay, cool!
