### ISSUE TITLE
[Request] Add social-share-kit 

### ISSUE THREAD

**Issue by nasa8x** [cdnjs/cdnjs#8505]
**Library name:** social-share-kit
**Git repository url:**https://github.com/darklow/social-share-kit
**npm package url(optional):** https://www.npmjs.com/package/social-share-kit
**License(s):**http://creativecommons.org/licenses/by-nc/3.0/
**Official homepage:**http://socialsharekit.com
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by darklow** [comment]
Social Share Kit is officially maintained on npm and always up to date.
Would it be possible to proceed with this issue?
Thank you.

**Comment by kennynaoh** [comment]
Thanks @darklow ,
I will handle this ASAP.
Thanks!
