### ISSUE TITLE
[Request] Add playcanvas 

### ISSUE THREAD

**Issue by Javier-Romario** [cdnjs/cdnjs#8508]
**Library name:** playcanvas
**Git repository url:** https://github.com/playcanvas/engine.git
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://playcanvas.com/
**Wanna say something? Leave message here:**
Really cool 3d engine for Javascript Developers, produces webGL and works on multiple platforms, even has an ios exporter for quick ios building and publish features to help you get your game/app out there.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@PeterDaveHello 
It seems the author said we need to generate the main files by ourselves.
How do I add git auto-update config?
Please take a look.

**Comment by PeterDaveHello** [comment]
https://github.com/playcanvas/engine/issues/736 we could start working now
