### ISSUE TITLE
[Request] Add tag-it 

### ISSUE THREAD

**Issue by TheVukasLt** [cdnjs/cdnjs#8510]
**Library name:** tag-it
**Git repository url:** https://github.com/aehlke/tag-it
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://aehlke.github.io/tag-it/
**Wanna say something? Leave message here:** 
It's simple yet powerful plugin. Would be awesome to see in backpack of Cloudflare. :)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by TheVukasLt** [comment]
+https://github.com/PeterDaveHello How long does it take for it to be added?

**Comment by PeterDaveHello** [comment]
Usually within 2 weeks.

**Comment by TheVukasLt** [comment]
@PeterDaveHello Thanks!

**Comment by PeterDaveHello** [comment]
@TheVukasLt No problem.
