### ISSUE TITLE
Can't not update some libs from npm

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8512]
The error message:
```
Found version 2.1.1 of cloudinary-jquery-file-upload, now try to import it.
cloudinary-jquery-file-upload contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-jquery-file-upload/2.1.1/package
Found version 2.0.9 of cloudinary-jquery-file-upload, now try to import it.
cloudinary-jquery-file-upload contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-jquery-file-upload/2.0.9/package
Found version 2.1.0 of cloudinary-jquery-file-upload, now try to import it.
cloudinary-jquery-file-upload contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-jquery-file-upload/2.1.0/package
Library "cloudinary-jquery-file-upload" update finished
Found version 2.0.9 of cloudinary-core, now try to import it.
cloudinary-core contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-core/2.0.9/package
Found version 2.1.0 of cloudinary-core, now try to import it.
cloudinary-core contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-core/2.1.0/package
Found version 2.1.1 of cloudinary-core, now try to import it.
cloudinary-core contains a malicious file path: /run/shm/cdnjs_NPM_temp/cloudinary-core/2.1.1/package
```

**Comment by PeterDaveHello** [comment]
@pvnr0082t @kennynaoh would you please take a look?

**Comment by holtkamp** [comment]
@PeterDaveHello it seems updates to these repositories are still not detected. The CDNJS versions are 'stuck' on ```2.1.2``` while the ones on GitHub have tags up to ```2.1.5```.

- https://cdnjs.com/libraries/cloudinary-core
- https://github.com/cloudinary/pkg-cloudinary-core/tags

And

- https://cdnjs.com/libraries/cloudinary-jquery-file-upload
- https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload/tags

**Comment by PeterDaveHello** [comment]
@holtkamp I'll take a look at it, thanks!

**Comment by PeterDaveHello** [comment]
Okay, since @pvnr0082t took care on this originally, I'll let him take a look first.

**Comment by PeterDaveHello** [comment]
@holtkamp that two libs are using "npm" auto-update, the upstream didn't update their npm package, would you mind to open issues to them? Once the missing versions been published on npm, we'll grab it, thanks!

**Comment by holtkamp** [comment]
@PeterDaveHello NPM was updated and CDNJS picked it up, also at ```2.1.5``` now, thanks for the pointer! Also see https://github.com/cloudinary/cloudinary_js/issues/59#issuecomment-255671689, this issue can be closed!

**Comment by PeterDaveHello** [comment]
Thanks.
