### ISSUE TITLE
[Request] Add datatables buttons extension

### ISSUE THREAD

**Issue by drees** [cdnjs/cdnjs#8516]
datatables buttons extension
https://github.com/DataTables/Buttons
MIT License
https://datatables.net/extensions/buttons/

**Comment by PeterDaveHello** [comment]
@drees thanks, @pvnr0082t please take a look as a higher priority issue, thanks.

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by pvnr0082t** [comment]
@PeterDaveHello They distributed `js` and `css` files to [datatables.net-buttons](https://www.npmjs.com/package/datatables.net-buttons) and [datatables.net-buttons-dt](https://www.npmjs.com/package/datatables.net-buttons-dt) on NPM, but all `js` and `css` files are on github repo. Is it better to fetch files from git repo in this case?

**Comment by PeterDaveHello** [comment]
@pvnr0082t yes, git auto-update will be better in this case.

**Comment by pvnr0082t** [comment]
ask for official compiled `css` files. https://datatables.net/forums/discussion/37976/provide-compiled-css-file-on-github-repo#latest

**Comment by PeterDaveHello** [comment]
Any updates here?
