### ISSUE TITLE
[Request] Add formsy-react 

### ISSUE THREAD

**Issue by okvic77** [cdnjs/cdnjs#8517]
**Library name:** formsy-react
**Git repository url:** https://github.com/christianalfoni/formsy-react
**npm package url(optional):** https://www.npmjs.com/package/formsy-react
**License(s):** MIT
**Official homepage:** https://github.com/christianalfoni/formsy-react
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
close due to existing on [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/formsy-react)
Thanks @okvic77 

cc @PeterDaveHello
