### ISSUE TITLE
[Request] Add js-beautify

### ISSUE THREAD

**Issue by zxqfox** [cdnjs/cdnjs#8518]
**Library name:** js-beautify
**Git repository url:** https://github.com/beautify-web/js-beautify/
**npm package url(optional):** https://www.npmjs.com/package/js-beautify
**License(s):** MIT
**Official homepage:** http://jsbeautifier.org/
**Wanna say something? Leave message here:** 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by bitwiseman** [comment]
@pvnr0082t 
The files need to be added in cdnjs as following:

js/lib/beautify.js
js/lib/beautify-css.js
js/lib/beautify-html.js

Thanks!
