### ISSUE TITLE
[Request] jQuery_ScrollSpy

### ISSUE THREAD

**Issue by vivekkupadhyay** [cdnjs/cdnjs#8520]
**jquery-scrollspy** 
**https://github.com/thesmart/jquery-scrollspy**
**npm package url(optional):** 
**https://github.com/thesmart/jquery-scrollspy/blob/master/LICENSE**
**https://github.com/thesmart/jquery-scrollspy**
**A very useful plugin and it should be included in CDN JS library**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Mithgol** [comment]
The awaited response seems to appear at thesmart/jquery-scrollspy#23.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
