### ISSUE TITLE
[Request] update viz.js

### ISSUE THREAD

**Issue by bfly2000** [cdnjs/cdnjs#8527]
viz.js
https://github.com/mdaines/viz.js/
BSD

**Comment by BigBlueHat** [comment]
Looks like it's [The Unlicense](http://unlicense.org)--see https://github.com/mdaines/viz.js/issues/67#issuecomment-255104265 for more.

**Comment by pvnr0082t** [comment]
@PeterDaveHello So we can add this with `"license": "Unlicense"`?

**Comment by PeterDaveHello** [comment]
@pvnr0082t See tools/license-list.json
