### ISSUE TITLE
[Request] Add color 

### ISSUE THREAD

**Issue by mahmoudhossam** [cdnjs/cdnjs#8531]
**Library name:** color
**Git repository url:** https://github.com/Qix-/color
**npm package url(optional):** https://www.npmjs.com/package/color
**License(s):** MIT
**Official homepage:** https://github.com/Qix-/color

**Comment by Qix-** [comment]
Apologies - I should definitely be on top of this. I will be in the future! Thanks for PR-ing this.

**Comment by maruilian11** [comment]
hi @Qix-,
this lib seems not for browser, right?
we only host files for browser, sorry for checking it carelessly...

**Comment by Qix-** [comment]
Using requireJS or something similar, yes -- to my knowledge none of the dependencies requires anything Node.js specific.

**Comment by maruilian11** [comment]
hi @Qix-,
thank you for your reply, could you please provide the bundled js on npm package because the `index.js` can't directly run under browser. thank you.

**Comment by maruilian11** [comment]
ping @Qix- , thanks.

**Comment by Qix-** [comment]
Hi @maruilian11 - I'm not sure what you mean. Could you explain why `index.js` doesn't run in the browser?

**Comment by maruilian11** [comment]
@Qix- Because the users will directly include the cdn link in their html.
like
``` 
<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
```
We need bundled `index.js` so that the user can directly include the link. 
Thank you.

**Comment by maruilian11** [comment]
Hi @Qix-, Could we turn to this conversation to continue the discussion?
https://github.com/cdnjs/cdnjs/pull/8873#r77371749

**Comment by Qix-** [comment]
I still don't know what you mean by "bundled". If users are going to use modules in the browser that are traditionally included via `require()` they should be webpacking them (or equivalent).

**Comment by maruilian11** [comment]
@PeterDaveHello Does it mean we can't host this kind of lib needed to be webpacked?

**Comment by PeterDaveHello** [comment]
I think the webpacking is kind of bundling.

**Comment by Qix-** [comment]
Ultimately it comes down to two issues:

1. I write ES6 code, which isn't supported by a lot of browsers. As a maintainer of many javascript libraries, it would be painful to maintain a build system that babelified all of my libraries _just_ for a CDN to distribute them. On the other hand, these libraries won't be back-ported to ES5. It's just not happening.

2. I write all of my code using the `module.exports` mechanism, which is quickly becoming _the_ standard way to export modules for both Node and the browser alike (in the future, there will be the `export` and `export default` mechanisms, but that's TBD). This isn't natively supported by the browser (it should be, but it isn't) and thus tools like Webpack stub this functionality for you for use in the browser.

As a service, cdnjs will probably have to start doing these things to keep up with the evolving javascript community. I don't think it's fair to expect package maintainers to distribute (or even worse, commit into the repository) a 'web-ready' version of the script.

Likewise, requiring that packages be back-ported to ES5 or babelified by the maintainer just won't happen.

---

I've used cdnjs before, and it appears you guys _do_ have a step for minification and even provide sourcemaps. This is great as-is, but you might consider having a few extra entries for babelified (back to ES5) and webpacked versions of scripts.

In the case that either babel or webpack fail (non-zero exit code), just omit the entries (maybe with a message on why they haven't been included in the listing).

**Comment by PeterDaveHello** [comment]
@Qix- thanks for your reply in detail, really appreciate it. We don't have plan to implement the new feature right now, but it's open to accept pull requests if you'd like to contribute, thanks!

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Should this one be closed?

**Comment by PeterDaveHello** [comment]
Okay, let's close it. We can re-open once anything related changed.
