### ISSUE TITLE
[Request] Add Loadie.js 

### ISSUE THREAD

**Issue by ipankajthakur** [cdnjs/cdnjs#8540]
**Library name:** Loadie.js
**Git repository url:_https://github.com/9elements/loadie.js_
**npm package url(optional):** 
**License(s):**
**Official homepage:_http://9elements.github.io/loadie.js/_
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 It seems that this lobrary has only 1 version [v1.0](https://github.com/9elements/loadie.js#options), maybe we could add it manually? What do you think?

**Comment by PeterDaveHello** [comment]
The problem is that we can't identify/locate the v1.0, so we can't manually add it.

**Comment by sashberd** [comment]
@PeterDaveHello Why? Here, in the link above, it is clearly said that: "At this moment Loadie.js (**v1.0**) doesn't support extensive options... ". So we could add it from master as v1.0

**Comment by PeterDaveHello** [comment]
@sashberd That's not acceptable at all, v1.0 should be a static reference, a branch is NOT.

**Comment by sashberd** [comment]
@PeterDaveHello Well, I suggest to close this one
