### ISSUE TITLE
[Request] Add ssi-modal 

### ISSUE THREAD

**Issue by ssbeefeater** [cdnjs/cdnjs#8541]
Library name: ssi-modal
Git repository url: [https://github.com/ssbeefeater/ssi-modal](https://github.com/ssbeefeater/ssi-modal)
npm package url: [https://www.npmjs.com/package/ssi-modal](https://www.npmjs.com/package/ssi-modal)
License(s): MIT
Official homepage: [http://ssbeefeater.github.io/](http://ssbeefeater.github.io/)

**Comment by x09326** [comment]
@ssbeefeater 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by PeterDaveHello** [comment]
@x09326 We can host this!
