### ISSUE TITLE
[Request] Add Zebra_DatePicker 1.8.9

### ISSUE THREAD

**Issue by jhenrygv** [cdnjs/cdnjs#8552]
**Library name:** Zebra_DatePicker
**Git repository url:** https://github.com/stefangabos/Zebra_Datepicker
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@NiniHsu Please take this.

**Comment by sashberd** [comment]
Duplicate #7443
