### ISSUE TITLE
[Request] Add highlightjs-line-numbers 

### ISSUE THREAD

**Issue by imgarylai** [cdnjs/cdnjs#8553]
**Library name:** highlightjs-line-numbers
**Git repository url:** git@github.com:wcoder/highlightjs-line-numbers.js.git
**npm package url(optional):** 
**License(s):** MIT 
**Official homepage:** https://github.com/wcoder/highlightjs-line-numbers.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @imgarylai ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks good to have this.
