### ISSUE TITLE
[Request] Add axe-core 

### ISSUE THREAD

**Issue by marcysutton** [cdnjs/cdnjs#8556]
**Library name:** axe-core
**Git repository url:** https://github.com/dequelabs/axe-core
**npm package url(optional):**  https://www.npmjs.com/package/axe-core
**License(s):** MPL-2.0
**Official homepage:** http://www.deque.com/products/axe/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Close per #8558
