### ISSUE TITLE
[Request] Please add KUTE.js

### ISSUE THREAD

**Issue by thednp** [cdnjs/cdnjs#8559]
**Library name:** kute.js
**Git repository url:** https://github.com/thednp/kute.js/
**npm package url(optional):** https://www.npmjs.com/package/kute.js
**License(s):** https://github.com/thednp/kute.js/blob/master/LICENSE
**Official homepage:** http://thednp.github.io/kute.js/
**Wanna say something? Leave message here:**
Have fun animating.

**Comment by pvnr0082t** [comment]
Hi @thednp ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by thednp** [comment]
OK, sorry I didn't know about that criteria, but still my other script got into the game and it's not so popular https://github.com/cdnjs/cdnjs/pull/8549

check this out
http://codepen.io/thednp/pens/popular/

**Comment by PeterDaveHello** [comment]
Cool, let's add this lib.

**Comment by thednp** [comment]
I thank you :)

**Comment by PeterDaveHello** [comment]
@thednp NP, BTW, would you like to add cdnjs to the readme or document? Or even give itba tweet, so that more users can know about the info, thanks.

**Comment by thednp** [comment]
Of course, as soon as CDN links are available, the demo, readme and all social goes into this.

**Comment by PeterDaveHello** [comment]
@thednp It'a already there for a while :) see https://cdnjs.com/libraries/kute.js

**Comment by thednp** [comment]
As we speak I'm sending my commit with new doc page linking the newly added repository
http://thednp.github.io/kute.js/start.html

also updated [README](https://github.com/thednp/kute.js/blob/master/README.md).
Thank you and have an excellent week.

**Comment by PeterDaveHello** [comment]
@thednp Thanks.

**Comment by thednp** [comment]
@pvnr0082t and @PeterDaveHello it's [100+ stars now](https://github.com/thednp/kute.js).

**Comment by thednp** [comment]
It's already added, no need to reopen, just to let you guys know :)
