### ISSUE TITLE
[Request] bytes.js

### ISSUE THREAD

**Issue by hairyhenderson** [cdnjs/cdnjs#8560]
**Library name:** bytes.js
**Git repository url:** https://github.com/visionmedia/bytes.js
**npm package url(optional):** https://www.npmjs.com/package/bytes
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
As they're not going to provide browser build, we can't add this right now, feel free to ping me to reopen it when it's available or submit other requests on familiar libraries, thanks.
