### ISSUE TITLE
[Request] Add sql.js

### ISSUE THREAD

**Issue by clicpilot** [cdnjs/cdnjs#8561]
**Library name:** sql.js
**Git repository url:**https://github.com/kripken/sql.js/
**npm package url(optional):** 
**License(s):**MIT licensed.
**Official homepage:**https://github.com/kripken/sql.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @clicpilot , this issue is the same as #8449, so I will close this issue. Thank you for your contribution.
