### ISSUE TITLE
[Request] Add mockJSON

### ISSUE THREAD

**Issue by ovuncgursoy** [cdnjs/cdnjs#8563]
**Library name:** mockJSON
**Git repository url:** https://github.com/mennovanslooten/mockJSON
**npm package url(optional):** 
**License(s):** GPL, MIT
**Official homepage:** http://experiments.mennovanslooten.nl/2010/mockjson/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@maruilian11  @PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
Okay, let's close it.
