### ISSUE TITLE
Issues requesting toastr from cdnjs/Australia.

### ISSUE THREAD

**Issue by Groombro** [cdnjs/cdnjs#8565]
we are having issue with an application that reference https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css 
we can access it in the uk and America but not in Australia. 
the exact path requested is https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css?v=201607141512

in Uk it loads  Australia it gives a file not found.

**Comment by PeterDaveHello** [comment]
@Groombro What is the IP address and ISP you are using in Australia? Have you tried with another ISP?

cc @terinjokes

**Comment by Groombro** [comment]
we have tried from multiple offices and i.p's the problem seems to move (Monday all our offices worked but home users didn't Tuesday New Zealand office didn't work, Australia did ) my guess is cloud flare have an issue with one of there nodes and a load shifts or ISP's change peers there the issue effects different people.

**Comment by PeterDaveHello** [comment]
@Groombro Thanks for your info.

**Comment by dschuermans** [comment]
@PeterDaveHello, @Groombro 
I too have a client in Australia, Melbourne which is unable to load the toastr library from cdnjs. The issue still persists today.
I have resolved it temporarily by serving the toastr files from my own server.

Glad to know it's not just my client which is having the issue :)

No idea which ISP they use, i'd have to ask them.

**Comment by PeterDaveHello** [comment]
Thanks @dschuermans , I've pinged CloudFlare (@terinjokes), please also let us know the response from your ISP, many thanks!

**Comment by dschuermans** [comment]
@PeterDaveHello - Thanks.
I've asked my client what the name is of their ISP. Due to the large timezone difference (they're 8 hours ahead) it's always a working day between responses.
I'll have more information tomorrow.

Weird thing is, it was happening on their company network but also through their mobile data connection and their connection at home.

**Comment by terinjokes** [comment]
@dschuermans A few pieces of information to help us identify these problems and come up with resolutions:

- The error message from the browser/network panel in DevTools, if any.
- The name of the ISP.
- A traceroute (or preferably, an mtr) to cdnjs.cloudflare.com

**Comment by dschuermans** [comment]
@terinjokes The error message in the devtools is a classic 404 not found. Their IT dept verified by trying to open the JS file directly.  
They have Telstra & Virgin as their mobile operators and TPG at home. All had the same issue.

I'll ask them to do a tracert from home since they use a proxy at work and the tracert from there was useless.

**Comment by PeterDaveHello** [comment]
Thanks @dschuermans, looks like we may have problem with some edges.

**Comment by mxalfrod** [comment]
here is my trace same issue in Mexico
Tracing route to cdnjs.cloudflare.com [198.41.215.67]
over a maximum of 30 hops:

  1    <1 ms    <1 ms    <1 ms  172.16.6.1
  2     1 ms     1 ms     1 ms  mmredes-207-248-55-113.multimedios.net [207.248.
55.113]
  3     1 ms     1 ms     1 ms  mmredes-207-248-50-42.multimedios.net [207.248.5
0.42]
  4     7 ms     7 ms     7 ms  cablelink-200-239-52-57.hosts.cablevision.com.mx
 [200.239.52.57]
  5     3 ms     7 ms     7 ms  cablelink-200-239-52-53.hosts.cablevision.com.mx
 [200.239.52.53]
  6     4 ms     4 ms     4 ms  be4352.rcr21.mfe01.atlas.cogentco.com [38.104.17
6.69]
  7     4 ms     4 ms     4 ms  be2979.rcr22.mfe02.atlas.cogentco.com [154.24.41
.65]
  8    12 ms    12 ms    12 ms  be2888.ccr22.iah01.atlas.cogentco.com [154.54.47
.45]
  9    17 ms    17 ms    17 ms  be2443.ccr22.dfw01.atlas.cogentco.com [154.54.44
.230]
 10    17 ms    17 ms    18 ms  be2764.ccr41.dfw03.atlas.cogentco.com [154.54.47
.214]
 11    17 ms    17 ms    17 ms  38.140.104.98
 12    26 ms    18 ms    17 ms  198.41.215.67

**Comment by mxalfrod** [comment]
Here is the response header 
<html>
<head><title>404 Not Found</title><script type="text/javascript">
//<![CDATA[
try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:0,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"cbdb49bad1c99cf025b77c43e4cd9fd3",petok:"2b74dfd5c173e33a59f671e6346ec56b0f62453e-1469825680-1800",adblock:1,betok:"878885c8eb158f582e2c0aca0ca6bb76ce028a79-1469825680-120",zone:"cloudflare.com",rocket:"0",apps:{},sha2test:0}];!function(a,b){a=document.createElement("script"),b=document.getElementsByTagName("script")[0],a.async=!0,a.src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=0489c402f5/cloudflare.min.js",b.parentNode.insertBefore(a,b)}()}}catch(e){};
//]]>
</script>
</head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by terinjokes** [comment]
Per https://cdnjs.com/libraries/toastr.js/latest, the correct URL is https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js

**Comment by dschuermans** [comment]
@terinjokes I see. Stupid thing to do imho.

Anyhow, that still doesn't explain why I can load v2.1.0 just fine but my client in Australia can't?
Or did you find issues with the edges as @PeterDaveHello mentioned earlier?

In any case, i'll ask my client to verify if https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js is working for them.

**Comment by mxalfrod** [comment]
@terinjokes I knew that using specific version will fix the issues, and is actually what i'm doing to keep developing but whoever started the app set that as the URL and is now in production, that means I will need to request somebody to change that URL there but it will be hard for me to show them the reason for switching if it is working for them but just not for me, will you ever drop support of the mentioned URL in the future?, because if the answer is yes then they will listen.

**Comment by terinjokes** [comment]
@dschuermans Files from CDNJS are cached at the edge "indefinitely", but for various reasons they may get purged from cache. There's currently no magic for updating "latest" URL or purge them when they change (though we're considering making the neccessary infrustructure changes to support that).

You're hitting an edge location that has it in cache, some of your users are hitting edge locations that don't, and are requesting it from CDNJS's origin, where the file (correctly) no longer exists

I can manually trigger a cache purge, but it won't fix your problem. Supporting the automatic purge would have simply made this break sooner. You shouldn't be relying on "latest" URLs in production.

---

@mxalfrod It sucks, but unfortunately you're going to have to deploy an update. Versioned URLs are here to stay, and are immutable (with narrowly defined exceptions), so relying on them would be safe.
