### ISSUE TITLE
[Request] Add markdown-it-emoji 

### ISSUE THREAD

**Issue by tchoulihan** [cdnjs/cdnjs#8566]
**Library name:** markdown-it-emoji
**Git repository url:*https://github.com/markdown-it/markdown-it-emoji*
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@tchoulihan You are welcome.
