### ISSUE TITLE
[Request] Add highlightjs-line-numbers.min.js 

### ISSUE THREAD

**Issue by as535364** [cdnjs/cdnjs#8571]
**Library name:** highlightjs-line-numbers.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #8553
