### ISSUE TITLE
[Request] Add PHPFileExplorer

### ISSUE THREAD

**Issue by zenncoder** [cdnjs/cdnjs#8576]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@zenncoder 
Any details?

**Comment by zenncoder** [comment]
This is under development. Will take some more time.

**Comment by NYCJacob** [comment]
is this still being worked on or should this be closed?

**Comment by zenncoder** [comment]
I'm busy with my work so I'll close this.

**Comment by PeterDaveHello** [comment]
Feel free to open a new one when you have time.
