### ISSUE TITLE
[Request] Add aurelia 

### ISSUE THREAD

**Issue by hyrmedia** [cdnjs/cdnjs#8577]
**Library name:** aurelia
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
http://aurelia.io/hub.html#/doc/persona/developer

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any detail here?

**Comment by pvnr0082t** [comment]
close due to no response.
