### ISSUE TITLE
[Request] Add particleground 

### ISSUE THREAD

**Issue by kilinkis** [cdnjs/cdnjs#8592]
**Library name:** particleground
**Git repository url:** https://github.com/jnicol/particleground
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://jnicol.github.io/particleground/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Billy4195** [comment]
@qwe19272375 Do you still work on this issue? or I'd like to finish this.

**Comment by sashberd** [comment]
@Billy4195 Go on it!

**Comment by sashberd** [comment]
@MattIPv4 There is no git tag on lib or npm. The lib has 2.1k, but there is no way to get it.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
