### ISSUE TITLE
[Author] [Request] Add simpleGallery.js

### ISSUE THREAD

**Issue by fccoelho7** [cdnjs/cdnjs#8593]
**Library name:** simpleGallery.js
**Git repository url:** https://github.com/fccoelho7/simpleGallery.js
**npm package url(optional):** https://www.npmjs.com/package/simple-gallery-js
**License(s):** MIT
**Official homepage:** In progress.
**Wanna say something? Leave message here:**
# Upload, surely, is a hard part in programming, probably you have had problems with that. Why not simplify? No frameworks, just 2kb gzipped!

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @fccoelho7 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
Looks good to add this one.

**Comment by pvnr0082t** [comment]
@dada0423 You can take this.
