### ISSUE TITLE
[Request] Add jQuery Tag-it!

### ISSUE THREAD

**Issue by Zhastreaus** [cdnjs/cdnjs#8597]
jQuery Tag-it!
https://github.com/aehlke/tag-it
MIT license.
http://aehlke.github.io/tag-it/
Thanks in advance!

**Comment by TheVukasLt** [comment]
Hey, it's a duplicate: :)
https://github.com/cdnjs/cdnjs/issues/8510

**Comment by PeterDaveHello** [comment]
Move to #8510

**Comment by TheVukasLt** [comment]
@Zhastreaus Good news! It's already published.

**Comment by Zhastreaus** [comment]
@TheVukasLt Thanks
