### ISSUE TITLE
[Request] [author] Add hack

### ISSUE THREAD

**Issue by egoist** [cdnjs/cdnjs#8605]
**Library name:** hack
**Git repository url:** https://github.com/egoist/hack
**npm package url(optional):** https://npmjs.com/package/hack
**License(s):** MIT
**Official homepage:** http://hackcss.com

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@egoist would you like to send a PR to add it?
