### ISSUE TITLE
[Request] Add alpaca 

### ISSUE THREAD

**Issue by qhix-antony** [cdnjs/cdnjs#8618]
**Library name:** alpaca
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @qhix-antony ,
What's the detail?
Like the **Git repository url** or **npm package url**.
Thanks!

**Comment by x09326** [comment]
close due to no response
