### ISSUE TITLE
[Request] Add jQuery Timer plugin

### ISSUE THREAD

**Issue by asifq** [cdnjs/cdnjs#8626]
**Library name:** timer.jquery
**Git repository url:** https://github.com/walmik/timer.jquery
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://jquerytimer.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@dada0423 You can take this.
