### ISSUE TITLE
Toastr Latest url not working in Mexico

### ISSUE THREAD

**Issue by mxalfrod** [cdnjs/cdnjs#8636]
We make reference to the following URL in a project:

https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js

the url works fine for my team mates in the US but for me in Mexico it throws a 404 (I.P. 189.210.98.245)
tested from my cell phone and have the same result
![2016-07-29 13_00_35-404 not found](https://cloud.githubusercontent.com/assets/3709457/17258445/841b7c56-558c-11e6-81ba-49e9ecdde8fc.png)

**Comment by PeterDaveHello** [comment]
Same as #8565, @mxalfrod would you please move to #8565 and give us these info:
  -  The name of the ISP.
  -  A traceroute (or preferably, an mtr) to cdnjs.cloudflare.com

I think it'll be even better if you could also provide the response header of the url, thanks!

**Comment by terinjokes** [comment]
The current "latest" URL is https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.1/toastr.min.js, but please use a specific version rather than "latest".
