### ISSUE TITLE
[Request] Add allineed 

### ISSUE THREAD

**Issue by misterhtmlcss** [cdnjs/cdnjs#8644]
**Library name:** allineed
**Git repository url:** https://github.com/elenatorro/allineed
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://elenatorro.github.io/allineed/
**Wanna say something? Leave message here:** 

I think another good and simple CSS framework is always a good thing to have. I'm using this one and I enjoy your service, so I thought why not ask for it's inclusion.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @misterhtmlcss ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by misterhtmlcss** [comment]
@pvnr0082t sorry man. When I submitted it, it was from the website and so mentally I was on a regular support page in my mind despite noticing now that it was GH repo and therefore the instructions  below. I didn't even take note the first time, I'll try be more alert in the future when I see I'm being sent to a GH repo and I'll of course shoot over to your Readme now too. Thank you for your patience; just a non-coder oversight on my part. Have a great weekend!!

**Comment by pvnr0082t** [comment]
@misterhtmlcss It's okay. Feel free to request/reopen an issue if it has enough popularity. Thanks for your contribution. I'm going to close this issue.

cc @PeterDaveHello
