### ISSUE TITLE
[Request] Add mosaicflow 

### ISSUE THREAD

**Issue by thakurpunk** [cdnjs/cdnjs#8648]
**Library name:** mosaicflow
**Git repository url:_https://github.com/sapegin/jquery.mosaicflow_
**npm package url(optional):** 
**License(s):**
**Official homepage:_http://sapegin.github.io/jquery.mosaicflow/_
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@NiniHsu Please take this.
