### ISSUE TITLE
[Request] Add angular-growl 

### ISSUE THREAD

**Issue by saranrajrasu** [cdnjs/cdnjs#8649]
**Library name:** angular-growl
**Git repository url:**https://github.com/marcorinck/angular-growl
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@NiniHsu Please take this.
