### ISSUE TITLE
[Request] Update Leaflet.draw

### ISSUE THREAD

**Issue by devdattat-webonise** [cdnjs/cdnjs#8650]
**Library name:Leaflet.draw** 
**Git repository url: [https://github.com/Leaflet/Leaflet.draw](https://github.com/Leaflet/Leaflet.draw)**
**npm package url(optional):** 
**License(s):MIT License**
**Official homepage: [https://github.com/Leaflet/Leaflet.draw](https://github.com/Leaflet/Leaflet.draw)**
**Wanna say something? Leave message here:**

Older versions of this Library are available at [https://cdnjs.com/libraries/leaflet.draw](https://cdnjs.com/libraries/leaflet.draw); This library has been updated last year, and v0.3.0 has some new functionality which would be very useful to me. Please update the page with v0.3.0 of the leaflet.draw library

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Auto-update config added, the bot should add the other versions if the structure is not changed in the new version.

**Comment by PeterDaveHello** [comment]
See https://github.com/cdnjs/cdnjs/commit/9120451f0158dd41d6383bd8ba0466db3815db35
