### ISSUE TITLE
[Request] Add NicEdit

### ISSUE THREAD

**Issue by afuous** [cdnjs/cdnjs#8653]
**Library name:** NicEdit
**Git repository url:** https://github.com/danishkhan/NicEdit
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://nicedit.com/
**Wanna say something? Leave message here:** It is already available at http://js.nicedit.com/nicEdit-latest.js, but this does not support https.

**Comment by PeterDaveHello** [comment]
@pvnr0082t any updates here?

**Comment by pvnr0082t** [comment]
@sajochiu Author answered. You can start to add this library. :+1:

**Comment by pvnr0082t** [comment]
@NiniHsu Please take this.
