### ISSUE TITLE
[Request] Add jquery.bootstrap-autohidingnavbar 

### ISSUE THREAD

**Issue by isudox** [cdnjs/cdnjs#8654]
**Library name:** jquery.bootstrap-autohidingnavbar
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

Github link: https://github.com/istvan-ujjmeszaros/bootstrap-autohidingnavbar
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@NiniHsu Please take this.
