### ISSUE TITLE
[Request] Add recorderjs 

### ISSUE THREAD

**Issue by joe-tom** [cdnjs/cdnjs#8656]
**Library name:** recorderjs
**Git repository url:**https://github.com/mattdiamond/Recorderjs
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
duplicated with #8284
