### ISSUE TITLE
[Request] Add https://code.jquery.com/jquery-1.12.4.js 

### ISSUE THREAD

**Issue by pamlazada** [cdnjs/cdnjs#8657]
**Library name:** https://code.jquery.com/jquery-1.12.4.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@pamlazada We have jquery v1.12.4, can't you use it?

**Comment by kennynaoh** [comment]
close due to no response
Thanks @pamlazada 

cc @PeterDaveHello
