### ISSUE TITLE
[Request] Add _library_name_ <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

### ISSUE THREAD

**Issue by angelveena** [cdnjs/cdnjs#8660]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What's the problem here?

**Comment by InternalSequence** [comment]
This request was clearly posted by someone who did not know what they were doing.

They just pasted an already-hosted version of jQuery onto an issue. I suggest this be closed.

**Comment by PeterDaveHello** [comment]
Close due to no response.
