### ISSUE TITLE
[Request] Add lawnchair

### ISSUE THREAD

**Issue by x09326** [cdnjs/cdnjs#8673]
**Library name:** lawnchair
**Git repository url:**https://github.com/brianleroux/lawnchair
**npm package url(optional):** https://www.npmjs.com/package/lawnchair
**License(s):**MIT
**Official homepage:**http://brian.io/lawnchair/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@x09326 This issue duplicated with #8058. Please check if the library has already been requested before open an issue. Thanks.
