### ISSUE TITLE
[Request] Add Sketch.js

### ISSUE THREAD

**Issue by derpierre65** [cdnjs/cdnjs#8675]
**Library name:** Sketch.js
**Git repository url:** https://github.com/intridea/sketch.js
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://intridea.github.io/sketch.js/
**Wanna say something? Leave message here:** https://cdnjs.com/libraries/sketch.js is not the same
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
