### ISSUE TITLE
[Request] Add Mozilla PopcornJS

### ISSUE THREAD

**Issue by jazrak** [cdnjs/cdnjs#8690]
**Library name: Popcorn.js** 
**Git repository url: https://github.com/mozilla/popcorn-js**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://popcornjs.org/**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
