### ISSUE TITLE
[Request] Add timedropper 

### ISSUE THREAD

**Issue by louis-l** [cdnjs/cdnjs#8692]
**Library name:** timedropper
**Git repository url:** https://github.com/felicegattuso/timedropper
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://felicegattuso.com/projects/timedropper/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
This issue will be closed due to duplicating with #8103.
