### ISSUE TITLE
[Request] Leaflet.SvgShapeMarkers

### ISSUE THREAD

**Issue by alvincyh** [cdnjs/cdnjs#8696]
Library name:Leaflet.SvgShapeMarkers
Git repository url:https://github.com/rowanwins/Leaflet.SvgShapeMarkers
**npm package url(optional):** 
License(s):MIT
**Official homepage:https://github.com/rowanwins/Leaflet.SvgShapeMarkers
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @alvincyh  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by alvincyh** [comment]
Terribly sorry about that. I'll be sure to pay attention the next time round 👍

**Comment by PeterDaveHello** [comment]
Thanks @alvincyh
