### ISSUE TITLE
[Request] Add tAutocomplete

### ISSUE THREAD

**Issue by alien3d** [cdnjs/cdnjs#8697]
**Library name:** vyasrao
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @alien3d , is there any detail? This issue will be closed if no response in 7 days.

**Comment by alien3d** [comment]
I just click  suggestion because not found in cdnjs. Unsure it was other
meaning ?

**Comment by pvnr0082t** [comment]
@alien3d Could you please provide more information about the library? Like GitHub repository or npm url. Thank you.

**Comment by alien3d** [comment]
Https://github.com/vyasrao/tAutocomplete

Description : An autocomplete in the form of table

** this is not my repo

**Comment by pvnr0082t** [comment]
Thanks @alien3d ,

But this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by alien3d** [comment]
Thanks . For information.  Because at first im kinda quite confuse with the
flow. Suggest ->github login->issue ? .  Okay i just include manually   the
library.

**Comment by PeterDaveHello** [comment]
I think we could add this.
