### ISSUE TITLE
web-animations has source maps but the files are missing

### ISSUE THREAD

**Issue by chris-morgan** [cdnjs/cdnjs#8698]
The existence of the source maps makes for errors in the console in some browsers when it fails to download them.

The source maps should either be removed (including the annotation at the bottom of the source file) or made to work in some way (providing the `src` directory, or changing the paths to fully-qualified paths to somewhere else that hosts the `src` directory).

This probably applies to other libraries as well.

**Comment by PeterDaveHello** [comment]
@chris-morgan please tell me the exactly url you have the error, so that I can look into the problem, thanks.

**Comment by chris-morgan** [comment]
@PeterDaveHello `data:text/html,%3Cscript%2520src%3Dhttps://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js%3E%3C/script%3E` (alas, GitHub doesn’t seem to allow `data:` URIs to be made links).

Just open that in Firefox and go to the Debugger panel in the Web Developer Tools, or presumably something like it in Chrome, or put that script tag into a document and open it in Edge (which apparently doesn’t allow you to open `data:` URIs!) and open the F12 tools.

Note how https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js includes at the end `//# sourceMappingURL=web-animations.min.js.map`.

**Comment by PeterDaveHello** [comment]
I don't have a problem with this code:
```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js"></script>
```

and I can reach the mapfile: 
https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js.map

Did I miss anything?

**Comment by chris-morgan** [comment]
@PeterDaveHello The problem is that the source files referred to in the map file are missing.

**Comment by PeterDaveHello** [comment]
The file is not missing, that's a relative path.
cc @cdnjs/owners

**Comment by MattIPv4** [comment]
No progress, closing.

**Comment by chris-morgan** [comment]
This was persistently misunderstood. I’ll try one last time.

The source map file is present.

But the original source files which are referred to in the map file, such as `src/scope.js`, are missing, so that the source map file is worse than useless.

It should be reopened.

**Comment by MattIPv4** [comment]
We have no plans to include all the source files for libraries. The maps are still useful to include for those that wish to fetch the source files themselves and understand how the file on cdnjs was composed.

**Comment by MattIPv4** [comment]
It's also worth noting that in a lot of cases, the map for a minified file on cdnjs will correctly map it to the unminified file that is also present on cdnjs. Those maps are definitely worth having.

**Comment by chris-morgan** [comment]
No no no no no no no that’s *not* how it works. The presence of source maps where the source files are missing is *actively harmful*: it makes browser dev tools request all the files, get a large number of 404 responses (clogging network traffic, which is a nuisance at best and a performance drain in general) and emit console warnings for each one.

The source maps should either be written so that they go to URLs that *will* work (e.g. on GitHub if it can be swung, if it’s not on cdnjs), or removed.

**Comment by MattIPv4** [comment]
Source map requests won't be made unless a user opens developer tools, so it is harmless for the vast majority of users on cdnjs.

These source maps are provided by the libraries themselves, so there is no way for us to easily filter out those that map to files we aren't including in cdnjs.

**Comment by chris-morgan** [comment]
*The source maps are broken.* At present they are worse than useless. It would be straightforward by parsing them to mechanically check whether they’re broken and remove them.

**Comment by MattIPv4** [comment]
You are welcome to create a PR on our assorted auto-update tools if you believe you have a simple solution to check every new source map being added to verify if it is valid or not. :)

**Comment by chris-morgan** [comment]
I intend to engage no further here. I don’t use cdnjs any more, so this doesn’t affect me any more. I seem to have failed to convince you that this should be reopened. Fare well!
