### ISSUE TITLE
[Request] Update SignalR

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [cdnjs/cdnjs#8702]
**SignalR 2.2.1** was [released](https://github.com/SignalR/SignalR/releases/tag/2.2.1).
https://github.com/SignalR/SignalR

@RohithKumbharkar / https://github.com/cdnjs/cdnjs/pull/6128

**Comment by PeterDaveHello** [comment]
We'll need help from them, it's impossible to build the libs by ourselves, there are too many libs, and official build will be better.

**Comment by PeterDaveHello** [comment]
@moozzyk is it possible to provide official build in the repo or the release page? Thanks.

**Comment by moozzyk** [comment]
I assume you are asking about JS client. If you don't want to build yourself you can get it from here: https://www.nuget.org/packages/Microsoft.AspNet.SignalR.JS/ (nupkg is just a zip)

**Comment by PeterDaveHello** [comment]
@moozzyk thanks!

**Comment by PeterDaveHello** [comment]
@moozzyk I manually added it, but it'll be great if the pre-built files can be released on git repo(on the git tag) or npm package, so that we can automatically, thanks.

**Comment by moozzyk** [comment]
In that case I think you should look at this repo: https://github.com/SignalR/bower-signalr

**Comment by PeterDaveHello** [comment]
@moozzyk Oh, that's nice, didn't notice this before, thanks!
