### ISSUE TITLE
[Request] Add icheck-bootstrap 

### ISSUE THREAD

**Issue by bantikyan** [cdnjs/cdnjs#8708]
**Library name:** icheck-bootstrap
**Git repository url:** https://github.com/bantikyan/icheck-bootstrap
**License(s):** https://github.com/bantikyan/icheck-bootstrap/blob/master/LICENSE

**Comment by pvnr0082t** [comment]
Hi @bantikyan ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by bantikyan** [comment]
Ok sorry for that, I just wont to use in the project by cdn. I will close this new.

**Comment by PeterDaveHello** [comment]
@bantikyan I'll suggest you start from rawgit.com, and publish this lib on npm, once it got notable popularity, we can host it here, thanks.

**Comment by bantikyan** [comment]
Thanks for suggestion.
