### ISSUE TITLE
Update vex

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8710]
v3 beta1 was released : https://github.com/HubSpot/vex/tree/v3.0.0-beta.1

May need to update the auto-update config.

**Comment by bbatliner** [comment]
Hi again,

We've switched fully to the `/dist/{css,js}/*.{css,js}` structure in all our releases past 3.0.0. I checked the [vex-js folder](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/vex-js) here in the cdnjs repo and it seems to be pulling the right files.

Let me know if anything needs to change.

**Comment by pvnr0082t** [comment]
@bbatliner Thanks!

**Comment by pvnr0082t** [comment]
vex-js in cdnjs is the latest version(https://cdnjs.com/libraries/vex-js). I'm going to close this issue.
