### ISSUE TITLE
wmd.css

### ISSUE THREAD

**Issue by Narender1990** [cdnjs/cdnjs#8713]
body 
{ 
	background-color: White
}

.wmd-panel
{
    text-align:center;
	/*margin-left: 25%;
	margin-right: 25%;*/
	width: 100%;
	/*min-width: 500px;*/
    word-wrap:break-word;
    font:13.3333px Arial;
    font-size:25px;
    color:gray;
}

#wmd-editor
{
	/*background-color: Aquamarine;*/
}

#wmd-button-bar 
{
	width: 100.5%;
	/*background-color: Silver;*/ 
    border:1px solid DarkGray;
}

#wmd-input 
{ 
	height: 400px;
	width: 100%;
	/*background-color: Gainsboro;*/
	border: 1px solid DarkGray;
}

#wmd-preview 
{ 
	background-color: #eff0f1; 
}

#wmd-output 
{ 
	background-color: Pink;
}

#wmd-button-row 
{
	position: relative; 
	margin-left: 0px;
	margin-right: 5px;
	margin-bottom: 5px;
	margin-top: 10px;
	padding: 0px;  
	height: 20px;
}

.wmd-spacer
{
	width: 1px; 
	height: 20px; 
	margin-left: 14px;
	
	position: absolute;
	background-color: Silver;
	display: inline-block; 
	list-style: none;
}

.wmd-button
{
	width: 20px; 
	height: 20px; 
	margin-left: 1px;
	margin-right: 5px;
	
	position: absolute;
	background-image: url(wmd-buttons.png);
	background-repeat: no-repeat;
	background-position: 0px 0px;
	display: inline-block; 
	list-style: none;
}

.wmd-button > a
{
	width: 0px; 
	height: 20px; 
	margin-left: 5px;
	margin-right: 5px;
	
	position: absolute;
	display: inline-block; 
}

/* sprite button slicing style information */
#wmd-button-bar #wmd-bold-button    {left: 0px;   background-position: 0px 0;}
#wmd-button-bar #wmd-italic-button  {left: 25px;  background-position: -20px 0;}
#wmd-button-bar #wmd-spacer1        {left: 35px;}
#wmd-button-bar #wmd-link-button    {left: 50px;  background-position: -40px 0;}
#wmd-button-bar #wmd-quote-button   {left: 75px;  background-position: -60px 0;}
#wmd-button-bar #wmd-code-button    {left: 100px;  background-position: -80px 0;}
#wmd-button-bar #wmd-image-button   {left: 125px;  background-position: -100px 0;}
#wmd-button-bar #wmd-spacer2        {left: 135px;}
#wmd-button-bar #wmd-olist-button   {left: 150px;  background-position: -120px 0;}
#wmd-button-bar #wmd-ulist-button   {left: 175px; background-position: -140px 0;}
#wmd-button-bar #wmd-heading-button {left: 200px; background-position: -160px 0;}
#wmd-button-bar #wmd-hr-button      {left: 225px; background-position: -180px 0;}
#wmd-button-bar #wmd-spacer3        {left: 235px;}
#wmd-button-bar #wmd-undo-button    {left: 250px; background-position: -200px 0;}
#wmd-button-bar #wmd-redo-button    {left: 270px; background-position: -220px 0;}
#wmd-button-bar #wmd-help-button    {right: 0px; background-position: -240px 0;}

.wmd-prompt-background
{
	background-color: Black;
}

.wmd-prompt-dialog
{
	border: 1px solid #999999;
	background-color: #F5F5F5;
}

.wmd-prompt-dialog > div {
	font-size: 0.8em;
	font-family: arial, helvetica, sans-serif;
}

.wmd-prompt-dialog > form > input[type="text"] {
	border: 1px solid #999999;
	color: black;
}

.wmd-prompt-dialog > form > input[type="button"]{
	border: 1px solid #888888;
	font-family: trebuchet MS, helvetica, sans-serif;
	font-size: 0.8em;
	font-weight: bold;
}

**Comment by PeterDaveHello** [comment]
@Narender1990 Please follow the request format to provide more detail.

**Comment by Narender1990** [comment]
I would like to upload my js and css file to cdnjs. Above is the css file.

How to do that?

**Comment by PeterDaveHello** [comment]
@Narender1990 please read our readme first, thanks.

**Comment by PeterDaveHello** [comment]
Close due to no response.
