### ISSUE TITLE
Need old stable release of Semantic UI 2.1.8

### ISSUE THREAD

**Issue by skumarrana** [cdnjs/cdnjs#8716]
**Semantic UI 2.1.8** 
**https://github.com/Semantic-Org/Semantic-UI**
**http://semantic-ui.com/:**
**Thanks you **

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by iwdmb** [comment]
[https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/semantic-ui/2.1.8](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/semantic-ui/2.1.8)

**Comment by PeterDaveHello** [comment]
@iwdmb Thanks.

**Comment by skumarrana** [comment]
Thanks Peter.

________________________________

**Comment by PeterDaveHello** [comment]
@skumarrana So do we still have problem here? Or we can close this issue now? Thanks.

**Comment by skumarrana** [comment]
One small doubt,

I see 2.1.7 mentioned inside semantic UI  java script file. Does it mean that , there was no update in the file from 2.1.7 to 2.1.8 ?


Thanks,

________________________________

**Comment by PeterDaveHello** [comment]
Yes, you can take a look from upstream, they should be the same.
