### ISSUE TITLE
[Request] Add scrolltofixed 

### ISSUE THREAD

**Issue by angelovaudo** [cdnjs/cdnjs#8718]
**Library name:** scrolltofixed
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @, is there any detail? This issue will be closed if no response in 7 days.

**Comment by PeterDaveHello** [comment]
@pvnr0082t missing tag.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Thanks!

**Comment by extend1994** [comment]
Close this issue because the library had been added. https://cdnjs.com/libraries/ScrollToFixed. cc @PeterDaveHello
