### ISSUE TITLE
[Request] Add https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js 

### ISSUE THREAD

**Issue by bhawnpandey** [cdnjs/cdnjs#8722]
**Library name:** https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @bhawnpandey ,
Close due to existing library on [cdnjs](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/jquery/2.1.3/jquery.min.js).
Thanks!
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh you didn't close it and we usually don't close an issue immediately.
@bhawnpandey do you have a problem with the jQuery v2.1.3?

**Comment by extend1994** [comment]
Hi @bhawnpandey If there is still response in next 7 days, I will close this issue. Thanks.

**Comment by extend1994** [comment]
Close due to no response, cc @PeterDaveHello
