### ISSUE TITLE
arcticModal

### ISSUE THREAD

**Issue by dreit-p** [cdnjs/cdnjs#8724]
arcticModal
https://github.com/vjik/arcticModal
http://arcticlab.ru/

**Comment by Piicksarn** [comment]
https://github.com/vjik/arcticModal/issues/16

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2
The last time author responded to the library is 4 years ago.
And the lib is lack of tags and package.json.

What's your opinions for this library?
Is there exist standard operating procedure for this situation?

**Comment by pvnr0082t** [comment]
I think you can add it  by tracing commit log. Like these PRs: https://github.com/cdnjs/cdnjs/pull/9122 https://github.com/cdnjs/cdnjs/pull/9130

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
