### ISSUE TITLE
[Request] Add jcf

### ISSUE THREAD

**Issue by erikeliasson** [cdnjs/cdnjs#8725]
**Library name:** _JCF_
**Git repository url:** _https://github.com/w3co/jcf_
**npm package url(optional):** 
**License(s):**
**Official homepage:** _https://www.psd2html.com/js-custom-forms/_
**Wanna say something? Leave message here:** An awesome js lib for 100% form customizations.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@kennynaoh please also label other issues before you are going to assign yourself.

**Comment by kennynaoh** [comment]
copy
