### ISSUE TITLE
[Request] Add jquery.iframe-transport.js 

### ISSUE THREAD

**Issue by Error203** [cdnjs/cdnjs#8731]
**Library name:** jquery.iframe-transport.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@Error203 do you mean [this lib](https://github.com/cmlenz/jquery-iframe-transport)?

**Comment by maruilian11** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
@maruilian11 you should add it.
