### ISSUE TITLE
[Request] Add kissui.scrollanim

### ISSUE THREAD

**Issue by afshinm** [cdnjs/cdnjs#8735]
**Library name: kissui.scrollanim** 
**Git repository url: https://github.com/usablica/kissui.scrollanim**
**npm package url(optional): https://www.npmjs.com/package/kissui.scrollanim** 
**License(s): MIT**
**Official homepage: scrollanim.kissui.io**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by afshinm** [comment]
Sorry, I didn't get what happened.

**Comment by PeterDaveHello** [comment]
@afshinm this lib is now added on CDNJS, see https://cdnjs.com/libraries/kissui.scrollanim
