### ISSUE TITLE
animated-jquery.js

### ISSUE THREAD

**Issue by Awadheshfgi** [cdnjs/cdnjs#8740]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @Awadheshfgi,
could you please provide git repo url or npm package url? thanks!

**Comment by maruilian11** [comment]
this issue will be closed if there is no any response in next 7 days.

**Comment by Piicksarn** [comment]
Closed due to no response
