### ISSUE TITLE
Update datatables-fixedheader

### ISSUE THREAD

**Issue by anand-bhat** [cdnjs/cdnjs#8742]
https://cdnjs.com/libraries/datatables-fixedheader needs to be updated to link to the latest version of the DataTables FixedHeader plugin (v3.1.2). I'm sorry but I do not know enough to create a PR to change the auto-update config.

**Comment by PeterDaveHello** [comment]
ping @kennynaoh @pvnr0082t

**Comment by PeterDaveHello** [comment]
ping  @kennynaoh

**Comment by PeterDaveHello** [comment]
ping @kennynaoh @pvnr0082t , any updates?

**Comment by anand-bhat** [comment]
Hello, The maintainer of the report has added their comments to https://github.com/DataTables/FixedHeader/issues/83

**Comment by PeterDaveHello** [comment]
@anand-bhat thanks
