### ISSUE TITLE
[Request] Add prebidjs 

### ISSUE THREAD

**Issue by pravintandale** [cdnjs/cdnjs#8744]
**Library name: Prebid.js** 
**Git repository url: https://github.com/prebid/Prebid.js**
**npm package url(optional):** 
**License(s): https://github.com/prebid/Prebid.js/blob/master/LICENSE**
**Official homepage: prebid.org**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
No prebuilt version is available for this, so we cannot add it, closing.
