### ISSUE TITLE
[Request] Add cPlayer

### ISSUE THREAD

**Issue by Copay** [cdnjs/cdnjs#8745]
**Library name:** cPlayer
**Git repository url:** https://github.com/Copay/cPlayer
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://cplayer.js.org
**Wanna say something? Leave message here:** It's a beautiful WEB HTML5 ECMAScript6 Player.

```javascript
  "autoupdate":{
    "source":"git",
    "target":"git://github.com/Copay/cPlayer.git",
    "basePath":"dist/",
    "files":["**/*"]
  }
```

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Added in #8760
