### ISSUE TITLE
[Request] Add ie-emulation-modes-warning 

### ISSUE THREAD

**Issue by spencerdcarlson** [cdnjs/cdnjs#8753]
**Library name:** ie-emulation-modes-warning
**Git repository url:** 
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@spencerdcarlson could you please provide the git repo url or npm package url?

**Comment by maruilian11** [comment]
close due to no response.
