### ISSUE TITLE
[Request] CollectionsJS

### ISSUE THREAD

**Issue by masterx2** [cdnjs/cdnjs#8759]
CollectionsJS
https://github.com/montagejs/collections

3-clause BSD license
http://www.collectionsjs.com/
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
https://github.com/montagejs/collections/issues/159
