### ISSUE TITLE
[Request] Updated versions for CreateJS libs

### ISSUE THREAD

**Issue by sebastianderossi** [cdnjs/cdnjs#8766]
**Library name:** 
CreateJS libs include (EaselJS, TweenJS, TweenJS, SoundJS, PreloadJS)
**Git repository url:**
CreateJS
- [EaselJS 0.8.2](https://github.com/CreateJS/EaselJS)
- [TweenJS 0.6.2](https://github.com/CreateJS/TweenJS)
- [SoundJS 0.6.2](https://github.com/CreateJS/SoundJS)
- [PreloadJS 0.6.2](https://github.com/CreateJS/PreloadJS)

**npm package url(optional):** 
**License(s):**
MIT
**Official homepage:**
[CreateJS.com](http://createjs.com/)
**Wanna say something? Leave message here:**

Currently **cdnjs** is hosting older versions of each library, it would great if we could get them updated to their latest versions.

If you have any questions or concerns please let me know :)

Thanks!
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sebastianderossi** [comment]
**Library name:** 
New CreateJS libs include (EaselJS, TweenJS, TweenJS, SoundJS, PreloadJS) for Version 1.0
**Git repository url:**
CreateJS
- [EaselJS 1.0.2](https://github.com/CreateJS/EaselJS/releases)
- [TweenJS 1.0.2](https://github.com/CreateJS/TweenJS/releases)
- [SoundJS 1.0.2](https://github.com/CreateJS/SoundJS/releases
- [PreloadJS 1.0.2](https://github.com/CreateJS/PreloadJS/releases)

cdnjs is hosting older versions of each library, it would great if we could get them updated to their latest versions.

Currently, this issue is marked as `waiting for response`/`in progress` is there _anything_ we can do/provide to help speed up this process? 

Thanks in advance!

**Comment by PeterDaveHello** [comment]
@sebastianderossi we can't fetch the updates from release page automatically, can you provide the dist files in the git tagged commits?

**Comment by PeterDaveHello** [comment]
@sebastianderossi see #11851 #11852 #11853 #11854

**Comment by PeterDaveHello** [comment]
All merged!
