### ISSUE TITLE
TaffyDB minified file raises an exception

### ISSUE THREAD

**Issue by Alsciende** [cdnjs/cdnjs#8778]
See http://jsbin.com/karoroveqa/1/edit?html,console for a demo of the issue. An exception is raised when creating a database if an element with id `q` exists in the DOM.

This issue doesn't appear with the original minified file provided by the author at https://github.com/typicaljoe/taffydb

Please update the CDN file with the one from the author.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @kennynaoh would you please take a look?

**Comment by MattIPv4** [comment]
We are pulling down the minified files directly from the npm package: https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/taffydb/package.json
