### ISSUE TITLE
[Request] Add mergely 

### ISSUE THREAD

**Issue by cikasfm** [cdnjs/cdnjs#8781]
**Library name:** mergely
**Git repository url:** https://github.com/wickedest/Mergely
**npm package url(optional):** mergely
**License(s):** GPL, LGPL and MPL
**Official homepage:** http://mergely.com
**Wanna say something? Leave message here:** It's a great lib for comparing content on a website, it should be made available!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
**[The confirmation of licenses version](https://github.com/wickedest/Mergely/issues/47)**

**Comment by PeterDaveHello** [comment]
@Piicksarn You should just use wickedest/Mergel#47 to mention an issue, easier to read directly.

**Comment by Piicksarn** [comment]
@PeterDaveHello, okay!
[Mergely #47] (https://github.com/wickedest/Mergely/issues/47)

**Comment by PeterDaveHello** [comment]
@Piicksarn Not correct, just use the 100% same syntax, GitHub will add the link for you.

**Comment by PeterDaveHello** [comment]
wickedest/Mergel#47

**Comment by cikasfm** [comment]
@Piicksarn anything else is needed for this?

**Comment by PeterDaveHello** [comment]
Looks like there is no response from wickedest/Mergely#47, maybe need to try some other method to confirm with its author, @cikasfm would you like to help us confirm its license? Thanks.

**Comment by Piicksarn** [comment]
@maruilian11, @cdnjs/intern2,
Would you mind to help me add the lib?
The library uses multiple licenses : **LGPL-3.0, MPL-2.0, GPL-3.0+**, which are confirmed from the author.
Thank you a lot!!!

**Comment by maruilian11** [comment]
@cdnjs/intern2
