### ISSUE TITLE
[Request] Add jQuery Countdown

### ISSUE THREAD

**Issue by claudiosw** [cdnjs/cdnjs#8783]
**Library name:** jQuery Countdown
**Git repository url:** https://github.com/Reflejo/jquery-countdown
**npm package url(optional):** 
**License(s):** 
**Official homepage:** https://github.com/Reflejo/jquery-countdown
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@PeterDaveHello No answer from author, no git tag. Suggest to close

**Comment by extend1994** [comment]
Also, there is no version/release, close it now.
If it's necessary, we may reopen it, cc @PeterDaveHello
