### ISSUE TITLE
[Request] Add jquery-scrolltofixed-min.js 

### ISSUE THREAD

**Issue by divyamayurmohite** [cdnjs/cdnjs#8787]
**Library name:** jquery-scrolltofixed-min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @divyamayurmohite , is there any detail? Because I think this issue duplicate with #8718. This issue will be closed if no response in 7 days.
