### ISSUE TITLE
[Request] Add angular2-polyfills.js 

### ISSUE THREAD

**Issue by sfn96** [cdnjs/cdnjs#8789]
**Library name:** angular2-polyfills.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @sfn96, do you mean https://github.com/SamVerschueren/angular2-polyfill? or could you please provide git repo url or npm package url? thanks!

**Comment by maruilian11** [comment]
this issue will be closed in 7 days if there is no response.
