### ISSUE TITLE
[Request] Add jsrsasign 

### ISSUE THREAD

**Issue by alxnegrila** [cdnjs/cdnjs#8792]
**Library name:** jsrsasign
**Git repository url:** https://github.com/kjur/jsrsasign
**License(s):**
**Official homepage:** https://kjur.github.io/jsrsasign/

**Comment by maruilian11** [comment]
hi @alxnegrila, I'm going to add files under `min` folder, are they enough for you? or are there any other files should be hosted? thanks.
