### ISSUE TITLE
[Request] Add multiscroll 

### ISSUE THREAD

**Issue by Vizerdrixx** [cdnjs/cdnjs#8795]
**Library name:** multiscroll
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

https://github.com/alvarotrigo/multiscroll.js

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by alvarotrigo** [comment]
Thanks!
