### ISSUE TITLE
[Request] Add jstree-actions 

### ISSUE THREAD

**Issue by shinze** [cdnjs/cdnjs#8797]
**Library name:** jstree-actions
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @shinze ,
do you mean https://github.com/alexandernst/jstree-actions / https://www.npmjs.com/package/jstree-actions?
this lib's popularity is not enough, 100 stars for github or 500 downloads per month is an goog example.
sorry, we may not add this lib now, you can open a new issue when its popularity is enough.

thank you very much. this issue will be closed in next 7 days if there is no any response.

**Comment by PeterDaveHello** [comment]
Close due to no response.
