### ISSUE TITLE
[Request] Add ng.ckeditor

### ISSUE THREAD

**Issue by miamarti** [cdnjs/cdnjs#8798]
**Library name:** 
ng.ckeditor

**Git repository url:**
https://github.com/miamarti/ng.ckeditor

**npm package url(optional):** 

**License(s):**
GNU GENERAL PUBLIC LICENSE

**Official homepage:**
http://miamarti.github.io/ng.ckeditor/

**Wanna say something? Leave message here:**
AngularJS component that implements the module ckeditor

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @miamarti ,
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by maruilian11** [comment]
btw, you can add your lib yourself by sending a PR. we will be happy to help you if you have any question.

**Comment by PeterDaveHello** [comment]
We can host this.

**Comment by miamarti** [comment]
Sure, no problem.
I am grateful for contact, rss
Thank you @maruilian11  and @PeterDaveHello :smiley:

**Comment by PeterDaveHello** [comment]
@miamarti Thank you.
