### ISSUE TITLE
jquery.inputmask: phone-codes.js is missing when using cdnjs

### ISSUE THREAD

**Issue by avradul** [cdnjs/cdnjs#8802]
https://jsfiddle.net/aradul/xabgtt47/
GET [XHR]
https://fiddle.jshell.net/_display/phone-codes/phone-codes.js [HTTP/1.1 404 Not Found 124мс]

**Comment by PeterDaveHello** [comment]
This is not a CDNJS problem since they didn't put the files under `dist` folder but `extra` folder, especially, in the `min` folder, the `phone-codes.js` is also been referenced. I'll add a workaround hotfix for it but can't guarantee it'll work in future releases.
