### ISSUE TITLE
[Request] Add OpenSeadragon 

### ISSUE THREAD

**Issue by danielsmink** [cdnjs/cdnjs#8811]
**Library name:** OpenSeadragon
**Git repository url:_https://github.com/openseadragon/openseadragon_
**npm package url(optional):** https://www.npmjs.com/package/openseadragon
**License(s):_New BSD license https://github.com/openseadragon/openseadragon/blob/master/LICENSE.txt_
*_Official homepage:_https://openseadragon.github.io/openseadragon/*
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by iangilman** [comment]
I hope I provided all of the necessary information in https://github.com/openseadragon/openseadragon/issues/1012 … Please let me know if there's anything else you need!

**Comment by PeterDaveHello** [comment]
Thanks @iangilman

**Comment by iangilman** [comment]
Is this still in progress?

**Comment by maruilian11** [comment]
Hi @iangilman, sorry for the late reply. We are going to add version before `v1.1.1` manually, it may take some time. I will send a PR for this lib ASAP.
