### ISSUE TITLE
Update Twemoji

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [cdnjs/cdnjs#8813]
Twemoji needs to be updated to 2.1.2. 

The highest version now on cdnjs is 2.1.0.

**Comment by PeterDaveHello** [comment]
Please ask the authors to add a v2.1.2 git tag for it, then it will be added, thanks.

See: https://github.com/twitter/twemoji/releases

**Comment by vijayaraghavanramanan** [comment]
Done. https://github.com/twitter/twemoji/issues/166

**Comment by PeterDaveHello** [comment]
See https://github.com/cdnjs/cdnjs/commit/470e2a5bf8f3339a776ba71d63725f0c9e214204
