### ISSUE TITLE
[Request] Add fractal_trading

### ISSUE THREAD

**Issue by giovanihgo** [cdnjs/cdnjs#8814]
![imagen1](https://cloud.githubusercontent.com/assets/8739964/17901350/a328e1ba-6928-11e6-8141-6692e184f7ef.png)
![imagen2](https://cloud.githubusercontent.com/assets/8739964/17901351/a32b3f00-6928-11e6-901f-f08f435d4e8c.png)
![imagen3](https://cloud.githubusercontent.com/assets/8739964/17901352/a32c9bf2-6928-11e6-8103-33efe0e1b64b.png)
![imagen4](https://cloud.githubusercontent.com/assets/8739964/17901353/a32f65b2-6928-11e6-8f43-e1f868051e78.png)

**Library name:** fractal_trading
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@giovanihgo 
Any details about github repo of this lib?

**Comment by x09326** [comment]
Close due to no response.
