### ISSUE TITLE
[Request] Add Quick search plugin for Bootstrap

### ISSUE THREAD

**Issue by jamesw72** [cdnjs/cdnjs#8817]
**Library name:** 
Quick search plugin for Bootstrap
**Git repository url:** 
https://github.com/skywalkapps/bootstrap-quick-search.git

**npm package url(optional):** 

**License(s):** 
MIT License (MIT)

**Official homepage:** 
http://skywalkapps.github.io/bootstrap-quick-search/

**Wanna say something? Leave message here:**
Quick Search for Bootstrap is a simple library for searching any collection of elements. Useful when you require ultra simple searching solution.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @jamesw72,
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by maruilian11** [comment]
close due to no response and lib still doesn't have enough popularity.
