### ISSUE TITLE
[Request] Add jquery.printarea.js 

### ISSUE THREAD

**Issue by Forge0100** [cdnjs/cdnjs#8826]
**Library name:** jquery.printarea.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@Forge0100 I found https://github.com/RitsC/PrintArea. Is this what you want to request?

**Comment by pvnr0082t** [comment]
@qwe19272375 Please take this.
