### ISSUE TITLE
[Request] Add jQuery Datepicker

### ISSUE THREAD

**Issue by johndoefromhere** [cdnjs/cdnjs#8832]
**Library name:** jQuery Datepicker
**Git repository url:** https://github.com/kbwood/datepick
**npm package url(optional):** -
**License(s):** MIT
**Official homepage:** http://keith-wood.name/datepick.HTML
**Wanna say something? Leave message here:**

Author promotes his own website instead of GitHub repo so it does not have a lot of stars, but:
- this lib has **2nd place in Google** for _jQuery Datepicker_
- it's the most advanced datepicker out there
- you already host another lib of this author: https://cdnjs.com/libraries/jquery-countdown

**Comment by x09326** [comment]
@johndoefromhere 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by johndoefromhere** [comment]
@x09326 This lib has enough popularity, just not on GitHub or npm. Its author promotes his own website instead of GitHub repo.

Note this lib has **2nd place in Google for jQuery Datepicker**

Also, you already host another lib of this author: https://cdnjs.com/libraries/jquery-countdown

**Comment by x09326** [comment]
@johndoefromhere 
Okay, thank you for your response.
We will host this lib ASAP.

**Comment by johndoefromhere** [comment]
@x09326 Hi, any updates on this?

**Comment by x09326** [comment]
@johndoefromhere 
We have finished it.
Thanks for your concern.
:+1:
