### ISSUE TITLE
[Request] Add godlike.css

### ISSUE THREAD

**Issue by Vadizar** [cdnjs/cdnjs#8836]
"name": "godlike.css",
  "version": "2.0.1",
  "description": "CSS for layout standardization and to improve the usability of web applications from 1000.tech",
  "author": "1000.tech <info@1000.tech>",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/1000tech/godlike.css.git"
  },
  "license": "WTFPL",

**Comment by pvnr0082t** [comment]
Hi @Vadizar ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by Vadizar** [comment]
Hey @pvnr0082t and @PeterDaveHello. Over the last 4 days the library downloaded more than 344 times:
https://www.npmjs.com/package/godlike.css

**Comment by PeterDaveHello** [comment]
We'll keep eyes on it :+1:

**Comment by Vadizar** [comment]
Hey @pvnr0082t and @PeterDaveHello. Over the last 4 days the library downloaded more than 513 times:
https://www.npmjs.com/package/godlike.css
