### ISSUE TITLE
[Request] Add jump.js

### ISSUE THREAD

**Issue by controversial** [cdnjs/cdnjs#8838]
**Library name:** Jump.js
**Git repository url:** https://github.com/callmecavs/jump.js
**npm package url(optional):** https://www.npmjs.com/package/jump.js
**License(s):** MIT
**Official homepage:** http://callmecavs.com/jump.js/
**Wanna say something? Leave message here:** This library has more than 2000 GitHub stars

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by controversial** [comment]
That was fast, thanks!

**Comment by PeterDaveHello** [comment]
@controversial You're welcome.

**Comment by callmecavs** [comment]
@PeterDaveHello @controversial thanks guys

**Comment by PeterDaveHello** [comment]
@callmecavs no problems, actually the guy sent the PR for this lib is our team member @pvnr0082t
