### ISSUE TITLE
[Request] MeanMenu

### ISSUE THREAD

**Issue by Toweb-Noel** [cdnjs/cdnjs#8842]
**MeanMenu** 
**https://github.com/meanthemes/meanMenu.git**
**-** 
**-**
**http://www.meanthemes.com/**
**Its fast and simple to make your menu responsive**

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
