### ISSUE TITLE
[Request] tocbot

### ISSUE THREAD

**Issue by honeo** [cdnjs/cdnjs#8844]
**Library name: tocbot** 
**Git repository url: https://github.com/tscanlin/tocbot**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: http://tscanlin.github.io/tocbot/**
**Wanna say something? Leave message here: Easy and convenient TOC library**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello the author asked if the files we grab by git auto-update must be put on master branch. I try to find git auto-update code on cdnjs repo to realize how it works, but I only find [npm auto-update code](https://github.com/cdnjs/cdnjs/blob/master/auto-update.js).

**Comment by PeterDaveHello** [comment]
We grab from the tagged commit, it's not about the branch.

**Comment by maruilian11** [comment]
does it means the tagged commit need to be pushed to the branch where the files on.

**Comment by PeterDaveHello** [comment]
tag is not about branch.

**Comment by maruilian11** [comment]
@PeterDaveHello the author will delete pre-version `.css` and `.js` files on the other branch when new file release, I think that is why he didn't git tag the commit with those files. And I can't catch the file with git auto-update.js, maybe it's commit time problem I guess.
how can we suggest the author to do?

**Comment by PeterDaveHello** [comment]
let @cdnjs/intern help

**Comment by Piicksarn** [comment]
@PeterDaveHello, @maruilian11,
how about add without auto-update first?

**Comment by PeterDaveHello** [comment]
@Piicksarn it can be an option
