### ISSUE TITLE
[Request] update dynamics.js to v1.7.1

### ISSUE THREAD

**Issue by carloslongen** [cdnjs/cdnjs#8845]
**Library name:** dynamics.js 1.7.1
**Git repository url:** https://github.com/michaelvillar/dynamics.js
**npm package url(optional):** https://www.npmjs.com/package/dynamics.js
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Close due to the duplicated [issue](https://github.com/cdnjs/cdnjs/issues/5243).
Thanks!
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh did you see "1.7.1" ?

**Comment by kennynaoh** [comment]
Sorry about that!

**Comment by kennynaoh** [comment]
Hello @carloslongen ,
The latest release on [github](https://github.com/michaelvillar/dynamics.js) and [npm](https://www.npmjs.com/package/dynamics.js) is `v1.1.5`, and it is update on [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/dynamics.js).
Please help me confirm that.
Thanks!

**Comment by carloslongen** [comment]
Hi!

Sorry, I guess i'm wrong. Version in cdnjs is current.

Regards!

​Carlos Longen​

**Comment by PeterDaveHello** [comment]
Thanks @carloslongen, so I think we can close this issue now? Thanks.

**Comment by carloslongen** [comment]
Ya! Thanks!

**Comment by grayghostvisuals** [comment]
Not seeing this lib on CDNJS any longer. Any reason why?
