### ISSUE TITLE
lib angular-morris-chart has changed

### ISSUE THREAD

**Issue by st1s** [cdnjs/cdnjs#8846]
**Library name:** Angular Morris
**Git repository url:** https://github.com/st1s/angular-morris
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** angular-morris.io
**Wanna say something? Leave message here:**

Hey! **angular-morris-chart** has changed and rebranded to [angular-morris](https://github.com/st1s/angular-morris). Please update the entries. Thx!

**Comment by maruilian11** [comment]
@PeterDaveHello in this case, do we add `angular-morris` as a new lib? or we can just change `angular-morris-chart`'s package info?

**Comment by PeterDaveHello** [comment]
@st1s which one you will prefer?

**Comment by st1s** [comment]
i guess change is better
Ty

**Comment by st1s** [comment]
But changing is only if cdnjs work with redirects, If dont would better have the two versions to don't break applications using the old version

**Comment by maruilian11** [comment]
@PeterDaveHello I think change package.json won't break old version used?

**Comment by PeterDaveHello** [comment]
@st1s we don't support redirect, do you mind to use the original name on CDNJS?

**Comment by st1s** [comment]
Ok. No, but If you just changes the name will break the apps using the old version, right? 

So this case I guess is better just register the new package

**Comment by PeterDaveHello** [comment]
No offense, but I'm wondering, if they are two different libs that can't use the same name, why don't you create a new repository for it? The new lib even start with v1.3.0 just lib the update to v1.2.0, isn't it? The tricky thing is that the old versions are still there in the release page on GitHub.

**Comment by st1s** [comment]
The problem is that a lot of people are using cdnjs   with old version name. That is the only reason for it still there.

**Comment by PeterDaveHello** [comment]
@st1s Sorry, I didn't get your point here, I don't think it's a problem that people using the old name one is a problem, as you now have a new one and they are different, aren't they?

**Comment by st1s** [comment]
In other words, I just want to change

`https://cdnjs.cloudflare.com/ajax/libs/angular-morris-chart/1.2.0/angular-morris-chart.min.js`

For 

`https://cdnjs.cloudflare.com/ajax/libs/angular-morris/1.3.0/angular-morris.min.js`

With no breaking for who are using the first option.

**Comment by PeterDaveHello** [comment]
@st1s They are different lib with different filename, so I didn't see a breaking problem here.

**Comment by st1s** [comment]
just because they are different , their application must stop ?

**Comment by PeterDaveHello** [comment]
@st1s but we won't force user to move on the version, there won't be a problem. I still didn't understand ...

**Comment by st1s** [comment]
I'm just trying to say to keep the first option and register the 2nd as new lib

**Comment by PeterDaveHello** [comment]
@st1s Okay that's fine, my point is if you think it's a new lib, why not just create a new repo and start version from v1.0.0 or v0.0.1 but v1.3.0 and inherit from another lib? The new regiested lib will still hosted the old versions and files since they are just there and been grabbed by the bot ...

**Comment by st1s** [comment]
Isnt a new lib. is the same lib rebranded with minor changes. So I will transfer old releases to new repo

**Comment by st1s** [comment]
Oops. This (old versions) is already there. 
now I do not understand your point

**Comment by PeterDaveHello** [comment]
@st1s I mean the new one

**Comment by st1s** [comment]
@PeterDaveHello 

I didnt get your point yet.

>  Okay that's fine, my point is if you think it's a new lib, why not just create a new repo and start version from v1.0.0 or v0.0.1 but v1.3.0 and inherit from another lib?

just to clarify, I am the owner of this project. why if i am releasing a new better version of same software, i have to start the semver again?

The new one repository (st1s/angular-morris) isnt a new lib, is just an evolution of old (st1s/angular-morris-chart)

> The new regiested lib will still hosted the old versions and files since they are just there and been grabbed by the bot 

Yes, I see no problem with that.

-

I believe the big question here is, why you renamed the repository of old version?
I tried to explain all this into [releases page](https://github.com/st1s/angular-morris/releases)

but it is basically to make the lib name more 'memorable'. as some people have pronounced the name without the 'chart ' at the end, i decided to change.

**Comment by maruilian11** [comment]
create a new lib `angular-morris`
`https://cdnjs.cloudflare.com/ajax/libs/angular-morris/1.3.0/angular-morris.min.js` will work
and
`https://cdnjs.cloudflare.com/ajax/libs/angular-morris-chart/1.2.0/angular-morris-chart.min.js` still work too.
because we won't delete `angular-morris-chart`.

@st1s Does it help?

**Comment by PeterDaveHello** [comment]
@maruilian11 That's not we're going to do, I'll handle this issue.

**Comment by maruilian11** [comment]
ok

**Comment by st1s** [comment]
@maruilian11 
this is the point. for me would be great

**Comment by PeterDaveHello** [comment]
@st1s I'm going to write the redirect feature, before that, that's my idea:

1. move `angular-morris-chart` directory to `angular-morris`
2. add a symbolic link `angular-morris-chart` to point to `angular-morris`

This will make `angular-morris-chart` invisible on cdnjs.com, instead, `angular-morris` will be visible there, the origin link/page to `angular-morris-chart` will be redirected to the search result, and `angular-morris` may be the top result, but both `angular-morris-chart` and `angular-morris` will work on the actual CDN service, e.g. :  
- https://cdnjs.cloudflare.com/ajax/libs/angular-morris/1.2.0/angular-morris-chart.min.js
- https://cdnjs.cloudflare.com/ajax/libs/angular-morris-chart/1.2.0/angular-morris-chart.min.js
- https://cdnjs.cloudflare.com/ajax/libs/angular-morris/1.3.0/angular-morris.min.js
- https://cdnjs.cloudflare.com/ajax/libs/angular-morris-chart/1.3.0/angular-morris.min.js

After I finished the redirect feature, the origin link/page to `angular-morris-chart` will be redirected to the new `angular-morris`, not the search result any more, and both `angular-morris-chart` and `angular-morris` will still work on the actual CDN service as origin.

What do you think?

**Comment by st1s** [comment]
@PeterDaveHello 

Perfect!!!
