### ISSUE TITLE
[Request] Add thrift 

### ISSUE THREAD

**Issue by odedhb** [cdnjs/cdnjs#8848]
**Library name:** thrift
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @odedhb , is there any detail? This issue will be closed if no response in 7 days.

**Comment by odedhb** [comment]
sorry: https://github.com/apache/thrift/tree/master/lib/js

**Comment by PeterDaveHello** [comment]
@odedhb Thanks

**Comment by pvnr0082t** [comment]
@qwe19272375 Please take this.
