### ISSUE TITLE
[Request] Add Facebook Embed Post Plugin

### ISSUE THREAD

**Issue by otari** [cdnjs/cdnjs#8849]
**Facebook Embed Post:** 
**https://github.com/otari/Tinymce-facebook-embed-post**
**MIT**
**Not Available:**

**Comment by x09326** [comment]
@otari 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by x09326** [comment]
Close due to no response.
