### ISSUE TITLE
[Feature request] Use Brotli compression

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [cdnjs/cdnjs#8854]
Is cdnjs planning to use brotli compression?

Also, a few more requests: use static gzip files for better speed and compression (at level 9). And static brotli compressed file too.

**Comment by Daniel15** [comment]
Somewhat related to #1120, which was looking at Zopfli.

**Comment by PeterDaveHello** [comment]
As CloudFlare is currently our only CDN provider and they have their own brotli module for nginx:
https://github.com/cloudflare/ngx_brotli_module

I believe it may be possible, but I'll respectfully suggest @terinjokes as the guy inside CloudFlare to answer this.

**Comment by drewfreyling** [comment]
This would be a great idea and give us a point of difference over other CDNs.

**Comment by drewfreyling** [comment]
any luck on this one @terinjokes ?

**Comment by MattIPv4** [comment]
@PeterDaveHello @drewfreyling @terinjokes It appears assets are now being sent using Brotli, can someone confirm this for me?

**Comment by drewfreyling** [comment]
I can confirm this is returning brotli compression for cdnjs assets.
