### ISSUE TITLE
[Request] Add material-ui

### ISSUE THREAD

**Issue by alexisllamas** [cdnjs/cdnjs#8855]
**Library name:** material-u
**Git repository url:_https://github.com/callemall/material-ui_
*_npm package url(optional):_npm install material-ui\* 
**License(s):**
*_Official homepage:_http://www.material-ui.com/#/*
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
Close because it duplicated with #10908
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@sufuf3 close the new ones next time ... not the old one.

**Comment by sufuf3** [comment]
OK sorry~
