### ISSUE TITLE
[Request] Add mobx-react

### ISSUE THREAD

**Issue by agent3bood** [cdnjs/cdnjs#8864]
**Library name: mobx-react 
**Git repository url: https://github.com/mobxjs/mobx-react
 
**License(s):MIT https://github.com/mobxjs/mobx-react/blob/master/LICENSE

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
This issue duplicate with #8309. I closed it. Thanks for your contribution.
