### ISSUE TITLE
Feature request: Make cdnjs.cloudflare.com cookie-free

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [cdnjs/cdnjs#8868]
Currently, although files loaded from cdnjs.clouflare.com don't have cookies, there is a complication. 

If someone visits cloudflare.com, then his/her browser will have cookies in files loaded from cdnjs.cloudflare.com even if they are requested by another website. 

This can be avoided. 

Possible to do this?

**Comment by terinjokes** [comment]
Accessing cdnjs.cloudflare.com sets no cookies, but navigating to www.cloudflare.com will set `__cfcuid` as is the standard for CloudFlare network.

Unfortunately, there is little we can do about this, user agents don't have the ability to exclude certain subdomains from apex cookies.
