### ISSUE TITLE
[Request update] emojify.js

### ISSUE THREAD

**Issue by J2TeaM** [cdnjs/cdnjs#8870]
This library has been updated to version 1.1.0: https://github.com/Ranks/emojify.js/releases

But it has not been updated on [cdnjs.com](https://cdnjs.com/libraries/emojify.js) (version 0.9.5).

**Comment by PeterDaveHello** [comment]
@J2TeaM thanks for your report!

**Comment by PeterDaveHello** [comment]
Looks like the auto-update config is out-dated, I'll handle this.
