### ISSUE TITLE
[Request] Add Butns

### ISSUE THREAD

**Issue by ahmedtarek2134** [cdnjs/cdnjs#8871]
**Library name:**Butns 
**Git repository url:**https://github.com/ahmedtarek2134/Butns
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**https://ahmedtarek2134.github.io/butns-demo/
**Wanna say something? Leave message here:**Hey guys! I have made my first library and it would be incredible if you would make a cdn for it, I am active on free code camp and some people want to use it on codepen for there projects

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @ahmedtarek2134 ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
