### ISSUE TITLE
[Request] Add jQuery Repeater

### ISSUE THREAD

**Issue by sofyansitorus** [cdnjs/cdnjs#8877]
**Library name: jQuery Repeater**
**Git repository url:https://github.com/DubFriend/jquery.repeater**
**npm package url(optional):** https://www.npmjs.com/package/jquery.repeater
**License(s): MIT**
**Official homepage:http://briandetering.net/repeater**
**Wanna say something? An interface to add and remove a repeatable group of input elements.**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @sofyansitorus ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
@pvnr0082t this can be added
