### ISSUE TITLE
[Request] Add ngmodeloptions 

### ISSUE THREAD

**Issue by phuongnh3012** [cdnjs/cdnjs#8878]
**Library name:** ngmodeloptions
**Git repository url:* https://github.com/fergaldoyle/modelOptions/
**npm package url(optional):** https://www.npmjs.com/package/ngmodeloptions
**License(s):** MIT
**Official homepage:** https://github.com/fergaldoyle/modelOptions/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @phuongnh3012 ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
npm stats 499 downloads in the last month, don't need to be so tough.
