### ISSUE TITLE
[Request] https://modules.ceylon-lang.org/repo/1/ceylon/language/1.2.2/ceylon.language-1.2.2.js

### ISSUE THREAD

**Issue by f47k9L** [cdnjs/cdnjs#8882]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @f47k9L,
does this lib has git repo or npm package?

**Comment by maruilian11** [comment]
seems duplicated with #8881
