### ISSUE TITLE
ionicons.css

### ISSUE THREAD

**Issue by DivyaKMurthy** [cdnjs/cdnjs#8890]
**Library name:ionicons.css
*_Git repository url:https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.css
*_npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:Can you please send me the ionicons.css file. Thanks.

**Comment by kennynaoh** [comment]
Hello @DivyaKMurthy ,
The git repository is [this](https://github.com/driftyco/ionicons), right?
If yes, this library is already hosted on [cdnjs](https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/ionicons).
Please confirm that.
Thanks!

**Comment by maruilian11** [comment]
hi @DivyaKMurthy, we only provide CDN service of libs, if you need the real file, you can use `wget` command or clone the repo and get the file.
let me know if you need other help, thanks!
