### ISSUE TITLE
[Request] Add RateIt

### ISSUE THREAD

**Issue by satalways** [cdnjs/cdnjs#8902]
**RateIt:** 
**https://github.com/gjunge/rateit.js:**
https://www.npmjs.com/package/jquery.rateit
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @satalways ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
Popularity looks good no nuget: https://www.nuget.org/packages/jQuery.RateIt/, let's add it.
