### ISSUE TITLE
Redirect old lib to the new one.

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#8904]
For the name changed libs, we use symbolic link to make them actually the same files to avoid maintain two libs with duplicate at the same some, however, currently, the CDN intra will work on both the old and the new lib name, but the webpage **will not**, should have a method to **redirect** the old lib to the new one.

These are the libs with symbolic link right now:
- bower-angular-translate -> angular-translate
- bower-angular-translate-loader-partial -> angular-translate-loader-partial
- bower-angular-translate-loader-static-files -> angular-translate-loader-static-files
- bower-angular-translate-loader-url -> angular-translate-loader-url
- nicescroll -> jquery.nicescroll
- pie -> css3pie
- zocial -> css-social-buttons

cc #8846 #8786

**Comment by PeterDaveHello** [comment]
cc @st1s (Feel free to ping me if I forgot this)

**Comment by MattIPv4** [comment]
We've decided the best process for this in the future, if other rename requests come in, will be to simply disable auto-update on the old library name, and then add the new library name, as if it were a new library, to cdnjs.

**Comment by MattIPv4** [comment]
The existing symlinks can stay as legacy items, but it isn't worth our time to work on a custom solution for the website for these.
