### ISSUE TITLE
[Request] Add MDBootstrap

### ISSUE THREAD

**Issue by mattonit** [cdnjs/cdnjs#8906]
**Library name: MDBoostrap
**Git repository url: https://github.com/mdbootstrap/bootstrap-material-design
**npm package url(optional): mdbootstrap
**License(s): MIT
**Official homepage: http://mdbootstrap.com
**Wanna say something? Leave message here: Material Design for Bootstrap (MDB) is a powerful Material Design UI KIT for most popular HTML, CSS, and JS framework - Bootstrap.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mattonit** [comment]
@PeterDaveHello any progress?

**Comment by PeterDaveHello** [comment]
@mattonit sorry but we have hundreds of requests, please be patient and waiting for the audit. If you are in hurry, I'll respectfully suggest you to send a Pull Request instead of Request Issue, we'll help you review the PR to add this lib, thanks.
