### ISSUE TITLE
[Request] Add teasim.js

### ISSUE THREAD

**Issue by billgo** [cdnjs/cdnjs#8912]
Library name: teasim
Git repository url:https://github.com/teasim/teasim
_npm package url(optional):https://www.npmjs.com/package/teasim
*_License(s):MIT
*Official homepage:http://www.teasim.com

**Comment by kennynaoh** [comment]
Hello @billgo ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by billgo** [comment]
@PeterDaveHello Brother, These days I have improved my library and changing the structure of this project. I think it's better than before, So I want CDNJS to help me host the new files. 

My project [repository](https://github.com/teasim/teasim)  in here . I have 15 npm packages in this project, but i just need to host 7 npm packages. I'm not sure whether to send five requests to you. The structure of the project is as follows.

1. npm package [teasim](https://www.npmjs.com/package/teasim), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-ui/library

2. npm package [teasim-icon](https://www.npmjs.com/package/teasim-icon), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-icon/library

3. npm package [teasim-animations](https://www.npmjs.com/package/teasim-animations), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-animations/library

4. npm package [teasim-middlewares](https://www.npmjs.com/package/teasim-middlewares), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-middlewares/library

5. npm package [teasim-plugins](https://www.npmjs.com/package/teasim-plugins), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-plugins/library

6. npm package [teasim-samples](https://www.npmjs.com/package/teasim-samples), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-samples/library

7. npm package [teasim-widgets](https://www.npmjs.com/package/teasim-widgets), The library files in [repository](https://github.com/teasim/teasim) packages/teasim-widgets/library

We just need to host from version 2.0.0.
Thank you all brothers.

**Comment by PeterDaveHello** [comment]
@pvnr0082t please take a look, thanks!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t

**Comment by PeterDaveHello** [comment]
I just merged #9176, the new *teasim* series can be added individually.
