### ISSUE TITLE
[Request] Add ng-bootstrap

### ISSUE THREAD

**Issue by vahidk** [cdnjs/cdnjs#8913]
**Library name:** ng-bootstrap
**Git repository url:** https://github.com/ng-bootstrap/ng-bootstrap.git
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://ng-bootstrap.github.io/#/home
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @vahidk, what files should we host?

**Comment by vahidk** [comment]
I'm going to close this since I noticed there's another similar library already hosted.

**Comment by PeterDaveHello** [comment]
This lib looks good to be hosted here!

**Comment by PeterDaveHello** [comment]
Looks like `bundles` is the directory we need.
