### ISSUE TITLE
[Request] Add NumJs

### ISSUE THREAD

**Issue by chausies** [cdnjs/cdnjs#8917]
**Library name:** NumJs
**Git repository url:** https://github.com/nicolaspanel/numjs
**npm package url(optional):** https://www.npmjs.com/package/numjs
**License(s):** MIT license
**Official homepage:** https://github.com/nicolaspanel/numjs
**Wanna say something? Leave message here:**
NumJs is a fantastic numpy-like library for javascript that supports an ndarray type that's missing from packages like numeric.js.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @chausies 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to not enough popularity
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@kennynaoh due to no response then not enough popularity in this casse

**Comment by PeterDaveHello** [comment]
BTW I'll like to add this one.

**Comment by kennynaoh** [comment]
OK

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh
