### ISSUE TITLE
[Request] Add timeago.js

### ISSUE THREAD

**Issue by hustcc** [cdnjs/cdnjs#8930]
Library name: `timeago.js`
Git repository url: [https://github.com/hustcc/timeago.js](https://github.com/hustcc/timeago.js)
npm package url(optional): [https://www.npmjs.com/package/timeago.js](https://www.npmjs.com/package/timeago.js)
License(s): MIT
Official homepage: [http://timeago.org/](http://timeago.org/)
Wanna say something? Leave message here: A very tiny javascript library to format date to *** time ago. Only 2 kb after uglify.

I want to pull a request. but I'm in **`China`**, clone the repo is **so so so slowly...**

**Comment by hustcc** [comment]
Thank you for your works, but `timeago.js` has updated to v2.x.x, and add one [timeago.locales.min.js](https://github.com/hustcc/timeago.js/tree/master/dist) file, all locales packaged into it.

The file was added in timeago.js@2.0.0, it is needed to cdn too. Sorry to trouble you. ^_^

**Comment by PeterDaveHello** [comment]
@hustcc Thanks

**Comment by PeterDaveHello** [comment]
@hustcc I think you added it since v2.0.1 not v2.0.0, and it has been added in f8cf97f about 8 hours ago, enjoy it.

**Comment by hustcc** [comment]
Yes, since v2.0.1 ^_^
