### ISSUE TITLE
[Request] Add yaml-js

### ISSUE THREAD

**Issue by Hirse** [cdnjs/cdnjs#8932]
**Library name:** yaml-js
**Git repository url:** https://github.com/connec/yaml-js
**npm package url(optional):** https://www.npmjs.com/package/yaml-js
**License(s):** WTFPL
**Official homepage:** https://github.com/connec/yaml-js

**Comment by kennynaoh** [comment]
@PeterDaveHello 
The npm auto-update can't get some of old versions(`v0.0.1`~`v0.0.2`), but I can use `npm install` to get them.
So, should I also add old versions manually?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh please try to figure out the reason that they can't been fetched, thanks!

**Comment by pvnr0082t** [comment]
@qwe19272375 Please take this.

**Comment by qwe19272375** [comment]
@pvnr0082t I have the same problem.
Tried using `**/*` in filemap, but npm auto-update some how only get `index.js` in `v0.0.1`~`v0.0.4`.

**Comment by pvnr0082t** [comment]
@qwe19272375 I think we could ignore v0.0.1-v0.0.4.
