### ISSUE TITLE
Hi how to call customise icon 

### ISSUE THREAD

**Issue by rajeshtbabu** [cdnjs/cdnjs#8940]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What the problem is?

**Comment by Piicksarn** [comment]
@rajeshtbabu, would you please make some detail for the issue?

**Comment by Piicksarn** [comment]
@rajeshtbabu, the issue will be closed due to no response, thanks.

**Comment by Piicksarn** [comment]
Closed due to no response.
