### ISSUE TITLE
[Request] Add psl 

### ISSUE THREAD

**Issue by xlsdg** [cdnjs/cdnjs#8942]
**Library name:** psl
**Git repository url:** https://github.com/wrangr/psl
**npm package url(optional):** https://www.npmjs.com/package/psl
**License(s):** MIT
**Official homepage:** https://github.com/wrangr/psl
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by lupomontero** [comment]
https://github.com/wrangr/psl/issues/2 has now been addressed

**Comment by PeterDaveHello** [comment]
@lupomontero Thanks
