### ISSUE TITLE
[Request] Add tldjs 

### ISSUE THREAD

**Issue by xlsdg** [cdnjs/cdnjs#8943]
**Library name:** tldjs
**Git repository url:** https://github.com/oncletom/tld.js.git
**npm package url(optional):** https://npmjs.com/tldjs
**License(s):** 
**Official homepage:** https://github.com/oncletom/tld.js
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@sufuf3 @extend1994 please work together to manually build the dist file and host this library. Don't forget to mention the whole process so that I can review if you do it correctly.

**Comment by oncletom** [comment]
Any help needed on this one?
