### ISSUE TITLE
[Request] Add grade.js 

### ISSUE THREAD

**Issue by Cat5TV** [cdnjs/cdnjs#8948]
**Library name:** grade.js
**Git repository url:** http://github.com/benhowdle89/grade
**npm package url(optional):**  https://www.npmjs.com/package/grade-js
**License(s):* *MIT
**Official homepage:** http://benhowdle.im/grade/
**Wanna say something? Leave message here:** This is a really cool library which creates nice color-matching gradients to accent your images. It chooses the top 2 colors from the image and builds the gradient around that automatically and instantly.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #8948

**Comment by Cat5TV** [comment]
Ha, guess the library got real popular all of a sudden.  :) Looks like the duplicate was added just before mine. Thanks for committing it. The library looks really great!
