### ISSUE TITLE
[Request] Add Whitestorm.js

### ISSUE THREAD

**Issue by sasha240100** [cdnjs/cdnjs#8951]
**Framework name:** Whitestorm.js
**Git repository url:** https://github.com/WhitestormJS/whitestorm.js
**npm package url(optional):** https://www.npmjs.com/package/whs
**License(s):** MIT
**Official homepage:** http://whsjs.io/

**Comment by sasha240100** [comment]
@kennynaoh Can you please add it?

**Comment by sufuf3** [comment]
close because duplicated with #10616
And CDNJS host this lib #10868
cc @PeterDaveHello
