### ISSUE TITLE
[Request] Add ckd-css

### ISSUE THREAD

**Issue by equinusocio** [cdnjs/cdnjs#8958]
**Library name:** ckd-css
**Git repository url:** https://github.com/equinusocio/ckdcss
**npm package url(optional):** https://www.npmjs.com/package/ckd-css
**License(s):** MIT
**Official homepage:** http://equinsuocha.io/ckdcss/
**Wanna say something?**
The main file is `dist/ckd-css.min.css`

**Comment by kennynaoh** [comment]
Hello @equinusocio ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by equinusocio** [comment]
Ok thanks!

**Comment by kennynaoh** [comment]
Close due to not enough popularity
Thanks @equinusocio 

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Hi @equinusocio ! You are the author, right? I think we can help push lib!

**Comment by equinusocio** [comment]
Yes i'm the author!

**Comment by PeterDaveHello** [comment]
@equinusocio would you like to send a PR to add your lib? As we have so many requests, this can help us add your library earlier!

**Comment by equinusocio** [comment]
I don't know what i have to do..

**Comment by PeterDaveHello** [comment]
@equinusocio have you cloned the CDNJS repo?

@cdnjs/intern2 please help @equinusocio to send his lib here.

**Comment by equinusocio** [comment]
> equinusocio have you cloned the CDNJS repo?
@PeterDaveHello yes.

```
git clone git@github.com:cdnjs/cdnjs.git ~/cdnjs  
cdnjs-importer -g git@github.com:equinusocio/ckdcss.git
```

**Comment by PeterDaveHello** [comment]
@equinusocio would you please should me the result of `git status` command inside `~/cdnjs` ? Thanks.

**Comment by equinusocio** [comment]
```
~/cdnjs ❯❯❯ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ajax/libs/Sortable/package.json
	typechange: ajax/libs/history/3.0.0-0/History.js
	typechange: ajax/libs/history/3.0.0-0/History.min.js
	typechange: ajax/libs/history/3.0.0-1/History.js
	typechange: ajax/libs/history/3.0.0-1/History.min.js
	typechange: ajax/libs/history/3.0.0-2/History.js
	typechange: ajax/libs/history/3.0.0-2/History.min.js
	typechange: ajax/libs/history/3.0.0/History.js
	typechange: ajax/libs/history/3.0.0/History.min.js
	modified:   ajax/libs/jquery-scrollTo/package.json


It took 39.91 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by PeterDaveHello** [comment]
@equinusocio thanks!

I think you need sparse checkout:
https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md

inside ~/cdnjs:
$ git config core.sparseCheckout true

put this content in `.git/info/sparse-checkout`

```
/build
/test
/tools
/scratch
/MIT-LICENSE
/hooks
/*.yml
/*.md
/*.json
/*.sh
/*.js
/ajax/libs/jquery/*
```

Then `git reset --hard`, this will help you!

**Comment by equinusocio** [comment]
over 3.000.000 files...

**Comment by equinusocio** [comment]
Nono, i still have to do it, but now, with a normal clone, there is over 3.000.000 files... :D My MBP need a lot of time to delete the repo

**Comment by PeterDaveHello** [comment]
@equinusocio You know what? I think you can just do it on GitHub without cloning it, what do you think?

**Comment by equinusocio** [comment]
Do you mean adding my library? I can't understand how to do it, what files/folders i have to add. I also use npmjs, so i think i need something that auto-update the library form npm.

**Comment by PeterDaveHello** [comment]
@equinusocio No worry, we'll help you, will you like to try? Maybe can also learn something!

**Comment by equinusocio** [comment]
Yes, ok. I'm here :)

PS:

```
~/cdnjs ❯❯❯ git config core.sparsecheckout true
~/cdnjs ❯❯❯ echo /build >> .git/info/sparse-checkout
```

**Comment by PeterDaveHello** [comment]
@equinusocio I note that the case is different : git config sparseCheckout true

**Comment by pvnr0082t** [comment]
@equinusocio I think you can create `sparse-checkout` by yourself if `echo /build >> .git/info/sparse-checkout` cannot work.

**Comment by PeterDaveHello** [comment]
@pvnr0082t I think the problem is the case of 'C' in the config/command.

**Comment by PeterDaveHello** [comment]
@equinusocio do you still want to add this lib on CDNJS? Thanks.

**Comment by equinusocio** [comment]
Nope, i used another service with a bit more easy process to add libraries.
