### ISSUE TITLE
[Request] Add Load Awesome

### ISSUE THREAD

**Issue by vertisan** [cdnjs/cdnjs#8978]
**Library name:** Load Awesome
**Git repository url:** https://github.com/danielcardoso/load-awesome
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://github.danielcardoso.net/load-awesome/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
close issue due to the issue duplicate with #7536.
