### ISSUE TITLE
[Request] Add Pannellum

### ISSUE THREAD

**Issue by rdenubila** [cdnjs/cdnjs#8992]
**Library name: Pannellum
**Git repository url: https://github.com/mpetroff/pannellum
**npm package url(optional):** https://www.npmjs.com/package/pannellum
**License(s): MIT License
**Official homepage: https://pannellum.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@PeterDaveHello I found that there have pre-built files been published on NPM but no pre-built files on github repo. In this case, I need to add old versions from github repo. Should I ask author provide official compiled files for previous versions or just compiled by myself?

**Comment by PeterDaveHello** [comment]
Files under `build`? I can see `pannellum.css`, `pannellum.js` & `pannellum.htm`

**Comment by pvnr0082t** [comment]
I can see `pannellum.css, pannellum.js & pannellum.htm` on NPM also but I need to add old versions from git repo. Should I need to run `utils/build/build.sh` to build them or ask author provide official compiled files?

**Comment by PeterDaveHello** [comment]
Maybe we could just leave the old versions alone, how many are there? I don't like to build dist file by our own.

**Comment by pvnr0082t** [comment]
There are 2 releases on NPM but 10 on GitHub.

**Comment by PeterDaveHello** [comment]
I meant the versions without pre-built dist files.

**Comment by pvnr0082t** [comment]
It seems like all releases without pre-built dist files on github.

**Comment by PeterDaveHello** [comment]
Any other method to get it? If not, just grab from npm, that's fine, I don't want to build our own dist files unless it's a very popular lib without any pre-built versions.
