### ISSUE TITLE
annyang 

### ISSUE THREAD

**Issue by fothert** [cdnjs/cdnjs#8996]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@fothert, would you please mention details about the lib?
Thanks.

The issue will be closed due to no response after 7 days.

**Comment by Piicksarn** [comment]
**Closed due to no response**
