### ISSUE TITLE
[Request] Add react-dom 

### ISSUE THREAD

**Issue by CTDevRic** [cdnjs/cdnjs#9004]
**Library name:** react-dom
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@CTDevRic , would you please mention details about the lib?
Thanks.

The issue will be closed due to no response after 7 days.

**Comment by Piicksarn** [comment]
@CTDevRic,
This one? :point_right:  https://www.npmjs.com/package/react-dom

**Comment by Piicksarn** [comment]
closed due to no response

**Comment by PeterDaveHello** [comment]
@Piicksarn can't we host  https://www.npmjs.com/package/react-dom ?

**Comment by bsyk** [comment]
Isn't this already available under react?
https://cdnjs.com/libraries/react

**Comment by PeterDaveHello** [comment]
@bsyk seems so, so just close this one, thanks.

**Comment by svenanders** [comment]
react-dom is a separate package from react and is not available under https://cdnjs.com/libraries/react

**Comment by bsyk** [comment]
It was at v15.6.0 https://cdnjs.com/libraries/react/15.6.0, seems not so since then.
