### ISSUE TITLE
[Request] Add jquery.vide

### ISSUE THREAD

**Issue by koryp** [cdnjs/cdnjs#9005]
**Library name:** Vide
**Git repository url:** https://github.com/VodkaBears/Vide
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** vodkabears.github.io/vide/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Closed due to duplicate request.
#8994
