### ISSUE TITLE
[Request] Add jquery-simple-datetimepicker 

### ISSUE THREAD

**Issue by hay-wire** [cdnjs/cdnjs#9010]
**Library name:** jquery-simple-datetimepicker
**Git repository url:** https://github.com/mugifly/jquery-simple-datetimepicker
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://mugifly.github.io/jquery-simple-datetimepicker/jquery.simple-dtpicker.html
**Wanna say something? Leave message here:**
This is way more intutive than other date time pickers on the net where date and time are in separate views. 
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
