### ISSUE TITLE
cdnjs.cloudflare.com/ajax

### ISSUE THREAD

**Issue by Jovial242** [cdnjs/cdnjs#9011]
**Library name:** animate.css/3.4.0/
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@Jovial242, do you mean [animaye.css](https://cdnjs.com/libraries/animate.css) library?
There is [animate.css/3.4.0](https://cdnjs.com/libraries/animate.css/3.4.0) in [cdnjs website](https://cdnjs.com/), if not, please provide the detail of library information such as git repository url, thanks!

**Comment by nolsherry** [comment]
Closed due to no response.
