### ISSUE TITLE
[Request] Add jquery.placepicker.js 

### ISSUE THREAD

**Issue by akriot** [cdnjs/cdnjs#9013]
``
**Library name:** jquery.placepicker.js
**Git repository url:_https://github.com/benignware/jquery-placepicker_
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
Hello @akriot,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by maruilian11** [comment]
close due to no response.
