### ISSUE TITLE
[Request] Add jquery-confirm v2.5.1 

### ISSUE THREAD

**Issue by ThomasC3** [cdnjs/cdnjs#9021]
**Library name:** jquery-confirm v2.5.1
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@ThomasC3 jquery-confirm v2.5.1 had already been added in d6ee4603b9903eaab1376ff0ad126732cace7479. This issue will be closed. Thanks for your contribution.
