### ISSUE TITLE
[Request] Add icodeforlove/Console.js 

### ISSUE THREAD

**Issue by elpic** [cdnjs/cdnjs#9022]
**Library name:** icodeforlove/Console.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@elpic,
we need more detail about the library, thanks!

**Comment by Piicksarn** [comment]
**Closed due to no response**

**Comment by PeterDaveHello** [comment]
We can try to add this one.

**Comment by Piicksarn** [comment]
https://github.com/icodeforlove/Console.js/issues/9
