### ISSUE TITLE
[Issue] Ember-Data 2.8.0 (final release) not available on the CDN

### ISSUE THREAD

**Issue by piotrpalek** [cdnjs/cdnjs#9023]
For some reason the CDN skipped the final release of ember-data, while every version (including previous and next betas) are present. 

This breaks https://ember-twiddle.com because we try to download the 2.8.0 version from `https://cdnjs.cloudflare.com/ajax/libs/ember-data.js/2.8.0/ember-data.js` but this obviously fails.

Confirmed by going to the website (https://cdnjs.com/libraries/ember-data.js) and checking which version are available.

**Comment by PeterDaveHello** [comment]
v2.8.0 is not tagged from upsteam: https://github.com/components/ember-data/tree/v2.8.0, I don't even see history of the version v2.8.0 in package.json, that's not a problem.

**Comment by piotrpalek** [comment]
@PeterDaveHello thanks!
