### ISSUE TITLE
[Request]ngSweetAlert

### ISSUE THREAD

**Issue by 1194420729** [cdnjs/cdnjs#9028]
**Library name:** ngSweetAlert
**Git repository url:**https://github.com/oitozero/ngSweetAlert
**npm package url(optional):** 
**License(s):**The MIT License (MIT)
**Official homepage:**https://github.com/oitozero/ngSweetAlert
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by oitozero** [comment]
@pvnr0082t 
Published latest version to npm.
https://www.npmjs.com/package/angular-sweetalert

Thanks.

**Comment by PeterDaveHello** [comment]
@oitozero thanks
