### ISSUE TITLE
[Request] Add angular pdf viewer 

### ISSUE THREAD

**Issue by sudheer-ranga** [cdnjs/cdnjs#9033]
**Library name:** angular pdf viewer
**Git repository url:** https://github.com/winkerVSbecks/angular-pdf-viewer
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @sudheer-ranga ,
Any details?
Like **Git repository url** or **npm package url**
Thanks!

**Comment by sudheer-ranga** [comment]
Hello,

Thanks for getting back. Here is the git url.

`https://github.com/winkerVSbecks/angular-pdf-viewer`

I found just now that this project is no longer maintained. So, I think it would not be worth adding.

**Comment by kennynaoh** [comment]
Thanks!
