### ISSUE TITLE
[Request] Add mobi.css

### ISSUE THREAD

**Issue by brentybh** [cdnjs/cdnjs#9035]
**Library name:** mobi.css
**Git repository url:** https://github.com/xcatliu/mobi.css.git
**npm package url(optional):** https://www.npmjs.com/package/mobi.css
**License(s):** MIT
**Official homepage:** http://getmobicss.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by xcatliu** [comment]
@Piicksarn Thanks! But please note the latest version of Mobi.css is v1.0.0-alpha.4
https://github.com/xcatliu/mobi.css/releases

Plus, I'll publish v1.0.0 by the end of September.
