### ISSUE TITLE
[Request] Add mobi.css 

### ISSUE THREAD

**Issue by zhuqling** [cdnjs/cdnjs#9041]
**Library name:mobi.css** 
**Git repository url:https://github.com/xcatliu/mobi.css**
**npm package url(optional):** 
**License(s):open-source MIT license**
**Official homepage:http://getmobicss.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #9035 and been added, see https://cdnjs.com/libraries/mobi.css
