### ISSUE TITLE
[Request] Add inuit.css 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9043]
**Library name:** inuit.css
**Git repository url:** https://github.com/csswizardry/inuit.css/

**Comment by pvnr0082t** [comment]
@PeterDaveHello I seems like no compiled `css` file in the repo. Should I manually compile `scss` into `css` or need to ask author if it's possible to provide official compiled `css` file?

**Comment by PeterDaveHello** [comment]
@pvnr0082t Always ask for official release first, thanks.

**Comment by sashberd** [comment]
The lib is use only *.scss files that cdnjs can not host today. Also current git is not maintained according to https://github.com/csswizardry/inuit.css/issues/340#issuecomment-248536678
Closed
