### ISSUE TITLE
[Request] Add inuitcss 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9044]
**Library name:** inuitcss
**Git repository url:** https://github.com/inuitcss/inuitcss

https://www.npmjs.com/package/inuitcss

**Comment by kennynaoh** [comment]
@PeterDaveHello 
What should I do in this case?
Because all the releases are beta version on both github and npm.
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh This lib is popular enough to be added, no problem.

**Comment by kennynaoh** [comment]
OK

**Comment by PeterDaveHello** [comment]
ping

**Comment by PeterDaveHello** [comment]
@kennynaoh any updates?
