### ISSUE TITLE
[Request] Add inobounce 

### ISSUE THREAD

**Issue by n9ti** [cdnjs/cdnjs#9047]
**Library name:** inobounce
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@n9ti, we need more detail about the library, thanks! :sweat_smile:

**Comment by n9ti** [comment]
inobounce is a script for stop iOS webapp from bouncing around when scrolling.

https://github.com/lazd/iNoBounce

**Comment by PeterDaveHello** [comment]
@n9ti Thanks

**Comment by Piicksarn** [comment]
Would add the lib after author update the min.js file to the latest version

https://github.com/lazd/iNoBounce/pull/31 - add license version
https://github.com/lazd/iNoBounce/pull/32 - update the min.js file

**Comment by lazd** [comment]
@Piicksarn is the minified file required for CDN deployment? If so, let's get it updated.

**Comment by PeterDaveHello** [comment]
@lazd it not requirement but it's better to have official minified release.

**Comment by lazd** [comment]
@PeterDaveHello @Piicksarn 0.1.3 has been properly released with the updated minified file and is ready for cdnjs!

**Comment by PeterDaveHello** [comment]
@lazd Thank you so much, we'll add this lib soon, feel free if you'll like to send a PR directly!
