### ISSUE TITLE
[Request] Add list.js fuzzy search

### ISSUE THREAD

**Issue by mocxd** [cdnjs/cdnjs#9049]
**Library name: list.js fuzzy search plugin** 
**Git repository url: https://github.com/javve/list.fuzzysearch.js**
**npm package url(optional): not available** 
**License(s): Apache License 2.0 http://www.apache.org/licenses/LICENSE-2.0**
**Official homepage: http://www.listjs.com/docs/plugins/fuzzysearch**
**Wanna say something? Leave message here: would be great to have this available in addition to the main list.js library**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @mocxd ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's add this lib.
