### ISSUE TITLE
[Request] Add markdeep 

### ISSUE THREAD

**Issue by alexzorin** [cdnjs/cdnjs#9052]
**Library name:** markdeep
**Git repository url:** N/A (no official repo)
**npm package url(optional):**  N/A
**License(s):** BSD
**Official homepage:** https://casual-effects.com/markdeep/

**Comment by Piicksarn** [comment]
@PeterDaveHello,
This library doesn't be hosted on famous public online platform.
Should we include it?

**Comment by PeterDaveHello** [comment]
Looks good to add it, but maybe you can ask the author if it's possible to have a repo for it.

**Comment by alexzorin** [comment]
I have done so already, I think the author is amenable to creating a GH mirror.

**Comment by alexzorin** [comment]
Author has created an official mirror on GH - https://github.com/morgan3d/markdeep

**Comment by PeterDaveHello** [comment]
Thanks @alexzorin

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
