### ISSUE TITLE
[Request] Add jquery-alertable 

### ISSUE THREAD

**Issue by Cat5TV** [cdnjs/cdnjs#9058]
**Library name:** jquery-alertable
**Git repository url:** https://github.com/claviska/jquery-alertable
**npm package url(optional):** https://www.npmjs.com/package/@claviska/jquery-alertable
**License(s):** MIT
**Official homepage:** https://www.abeautifulsite.net/minimal-jquery-alert-and-confirm-replacements
**Wanna say something? Leave message here:**
Nice, clean alert dialogue replacement using jquery.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @Cat5TV ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@Cat5TV Sorry for that, please ping us if it got about 60 or 70 stars, before that, I'll respectfully suggest you give rawgit.com a try, thank you for being interested in CDNJS, hope other hosted libs can also help your works!

**Comment by maruilian11** [comment]
@Cat5TV we will reopen this issue when the lib get enough popularity, thank you!
