### ISSUE TITLE
[Request] Add SCM Music Player

### ISSUE THREAD

**Issue by J2TEAM** [cdnjs/cdnjs#9059]
**Library name:** SCM Music Player
**Git repository url:** https://github.com/cshum/SCM-Music-Player/
**License(s):** GPL
**Official homepage:** http://scmplayer.net/

**Comment by Piicksarn** [comment]
Hi @cshum, 
There's a library request in cdnjs, and we desire to contain **[SCM Music Player](https://github.com/cshum/SCM-Music-Player/)** .
However, i must to make a check for the files that we need to added.

The files i would like to added are:

 - lib/scm*.js
 - css/scm*.css

Is that complete for the user?

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
