### ISSUE TITLE
[Request] origamijs 

### ISSUE THREAD

**Issue by raphamorim** [cdnjs/cdnjs#9060]
**Library name:** Origamijs
**Git repository url:** http://github.com/raphamorim/origami.js
**npm package url(optional):**  https://www.npmjs.com/package/origamijs
**License(s):** GPL-3.0
**Official homepage:** http://origamijs.com
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by raphamorim** [comment]
Done: https://github.com/raphamorim/origami.js/issues/39

**Comment by PeterDaveHello** [comment]
@raphamorim Thanks.
