### ISSUE TITLE
[Request] Add EventSource 

### ISSUE THREAD

**Issue by christianesperar** [cdnjs/cdnjs#9064]
**Library name:** EventSource
**Git repository url:** https://github.com/Yaffle/EventSource
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@christianesperar Is https://github.com/Yaffle/EventSource what you request?

**Comment by christianesperar** [comment]
Yup :D
