### ISSUE TITLE
[Request] Add react-data-grid 

### ISSUE THREAD

**Issue by joyinsky** [cdnjs/cdnjs#9066]
**Library name:** react-data-grid
**Git repository url:**
https://github.com/adazzle/react-data-grid
**npm package url(optional):** https://www.npmjs.com/package/react-data-grid
react-data-grid
**License(s):**
MIT
**Official homepage:**
http://adazzle.github.io/react-data-grid/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh
