### ISSUE TITLE
bootstrap-combined.min.css

### ISSUE THREAD

**Issue by bontower** [cdnjs/cdnjs#9068]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @bontower ,
Any details?
Like **Git repository url** or **npm package url**.
Thanks!

**Comment by kennynaoh** [comment]
close due to no reponse

cc @PeterDaveHello
