### ISSUE TITLE
Firefox 49 update broke insertRule. Fixed

### ISSUE THREAD

**Issue by what5150** [cdnjs/cdnjs#9069]
Change line 151:
`document.styleSheets[0].insertRule(rule);`

To:
`document.styleSheets[0].insertRule(rule, "index-max");`

**Comment by PeterDaveHello** [comment]
Sorry but I don't get your point, what is this for?

**Comment by what5150** [comment]
Firefox 49 now requires index. my windows and linux machines were stuck showing the indicator until I added the index to insertRule. I thought it might be helpful to others. [CSSStyleSheet.insertRule()](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule)

**Comment by PeterDaveHello** [comment]
@what5150 I believe that https://gitter.im/cdnjs/cdnjs is a better place to share this! Since this is not a CDNJS issue, so I'm sorry that I have to close this issue now, thanks for your sharing!
