### ISSUE TITLE
[Request] Add videojs-fairplay

### ISSUE THREAD

**Issue by LeonidasEsteban** [cdnjs/cdnjs#9070]
**Library name: videojs-fairplay** 
**Git repository url: https://github.com/chemoish/videojs-fairplay**
**npm package url: https://www.npmjs.com/package/videojs-fairplay** 
**License(s): MIT**
**Official homepage: no**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @LeonidasEsteban ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to no response
cc @PeterDaveHello
