### ISSUE TITLE
[Request] Add simditor 

### ISSUE THREAD

**Issue by nodeman777** [cdnjs/cdnjs#9073]
**Library name:** simditor
**Git repository url:**https://github.com/mycolorway/simditor
**npm package url(optional):** npm install simditor
**License(s):**https://github.com/mycolorway/simditor/blob/master/LICENSE
**Official homepage:**http://simditor.tower.im/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
I'm going to close this issue because there already exist issue and PR. See #7371 #8224
