### ISSUE TITLE
[Request] Add http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js 

### ISSUE THREAD

**Issue by amunalawade25593** [cdnjs/cdnjs#9086]
**Library name:** http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@amunalawade25593 Do you have a problem with jquery v2.1.3 on CDNJS?

**Comment by maruilian11** [comment]
this issue will be closed if there is no any response in next 7 days.

**Comment by PeterDaveHello** [comment]
Close due to no response.
