### ISSUE TITLE
Add the sub-libraries for the Light Gallery library.  

### ISSUE THREAD

**Issue by HamzaAbdullahMoh** [cdnjs/cdnjs#9087]
**Light Gallery** 
**https://github.com/sachinchoolur/lightGallery**
**npm package url(optional):** https://www.npmjs.com/package/lightgallery
**GNU AGPLv3**
**http://sachinchoolur.github.io/lightGallery/**
*_lg-autoplay.min.js, lg-autoplay.min.js, lg-fullscreen.min.js, lg-hash.min.js, lg-pager.min.js, lg-share.min.js, lg-thumbnail.min.js, lg-video.min.js, lg-zoom.min.js, *_
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by evromalarkey** [comment]
Any update on this? Lightgallery itself is up to date on cdnjs, but the modules are still not present (it's 8 months now).

GitHub links to each module - https://github.com/sachinchoolur/lightGallery#built-in-modules

**Comment by maruilian11** [comment]
@evromalarkey Sorry to keep you waiting.
We will add these modules ASAP.
@cdnjs/intern2 @cdnjs/intern3 Please help to add these modules if you have free time, I will send PR to add them in a week since I'll be busy next week. Thanks!

**Comment by evromalarkey** [comment]
It's been almost 2 months again without no update, so what's the hold-up here? :/

I would add pull request myself, but I don't know what it involves and honestly I don't have the time to deal with that now.

I'm using the modules from jsdelivr for a while now, but obviously I would prefer cdnjs 😄

**Comment by maruilian11** [comment]
@evromalarkey Sorry for my mistake. I have sent PRs to add all sub-libraries. Please wait for few days for our reviewers to check them, and they will be merged individually.

**Comment by PeterDaveHello** [comment]
@evromalarkey feel free to send a pull request if you really need it, it's obviously that we are happy to add it but we can't guarantee the time line as we all have our stuffs to do just like you, you can also donate to the issues which is valuable to you when you have time, then some passengers may pick it up.

**Comment by maruilian11** [comment]
Hi @sachinchoolur, Could you please help us confirm the license of your libs, thank you!
like https://github.com/sachinchoolur/lg-video/issues/1

**Comment by sachinchoolur** [comment]
Hi @maruilian11,
Thank you for considering hosting lightGallery on cdnjs. lightGallery and its submodules are licensed under  GPLv3 license.

**Comment by maruilian11** [comment]
All sub-libraries have been added.

**Comment by evromalarkey** [comment]
thanks a lot!

**Comment by hamzaabdullah90** [comment]
Thank you!
