### ISSUE TITLE
[author] Taggd 3.x

### ISSUE THREAD

**Issue by timseverien** [cdnjs/cdnjs#9100]
So Taggd 2.x was added in July 2016 (#8524), which is great. Unfortunately, it doesn’t (automatically) update to 3.x which was released only several days later.

Can Taggd 3.x be added to cdnjs? Can I help in any way?

**Comment by PeterDaveHello** [comment]
@timseverien yes, the tag for v3 will help, thanks!

**Comment by PeterDaveHello** [comment]
@PeterDaveHello Looks like the directory/file structure changed, let me take a look.

**Comment by PeterDaveHello** [comment]
@timseverien Okay, looks like both the filename and file path changed, I'll update them right now, next time you can send a PR to update it on CDNJS first, thanks!

**Comment by PeterDaveHello** [comment]
@timseverien I updated the config and manually added v3 files, it'll be available on CDNJS within 15 mins (since both CDNJS infrastructure and the website needs time to update!), feel free to ping me if there is still a problem then, thanks for being interested in CDNJS!

**Comment by timseverien** [comment]
@PeterDaveHello Thank you _so_ much for the practically instant response. Unfortunately, I had to go AFK for a moment. Hence the “late” reply ;)

The changes were made about an hour ago, and 3.x still isn’t live. I’m not bothered that my library isn’t updated yet, but you may want to check the infrastructure :)

Again, thanks a lot.

**Comment by PeterDaveHello** [comment]
@timseverien I think you mean website, the CDN works fine, see: https://cdnjs.cloudflare.com/ajax/libs/taggd/3.0.7/taggd.min.js, website sometimes delay the updates due to the cache issue, please try to purge your cache, and then try again, thanks for your report! If CDNJS looks good for you, maybe you can also consider to add the link into your readme and website, thank you!

**Comment by timseverien** [comment]
@PeterDaveHello Ah, yes, perfect.

Yeah, I’ll be sure to do that. Thanks again :)

**Comment by PeterDaveHello** [comment]
@timseverien No problem! Feel free if you can not get the updated website after you purged the cache! I can see them on website right now from my side.
