### ISSUE TITLE
[Request] Add SurveyJS

### ISSUE THREAD

**Issue by rap2hpoutre** [cdnjs/cdnjs#9101]
**Library name:** Survey JS
**Git repository url:** https://github.com/andrewtelnov/surveyjs
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** surveyjs.org
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Duplicate with #9771, and pull request is #10153

**Comment by extend1994** [comment]
@PeterDaveHello should we close this issue?

**Comment by PeterDaveHello** [comment]
@extend1994 sure, nice catch!
