### ISSUE TITLE
[Request] Add dialog-polif

### ISSUE THREAD

**Issue by murilobd** [cdnjs/cdnjs#9104]
**Library name:** dialog-polyfill css
**Git repository url:** https://github.com/GoogleChrome/dialog-polyfill
**npm package url(optional):** https://www.npmjs.com/package/dialog-polyfill
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @murilobd 
This lib has been added on [cdnjs](https://cdnjs.com/libraries/dialog-polyfill).
Anything I can help?
Thanks!

**Comment by murilobd** [comment]
Great!! Thanks =)
