### ISSUE TITLE
[Request][author] Add webmo-client

### ISSUE THREAD

**Issue by mactkg** [cdnjs/cdnjs#9118]
**Library name:**  webmo
**Git repository url:** https://github.com/cidreixd/webmo-library-javascript
**npm package url(optional):** https://www.npmjs.com/package/webmo-client
**License(s):** MIT
**Official homepage:** http://webmo.io/
**Wanna say something? Leave message here:** This is a motor which have a HTTP/WebSocket API.  You can rotate motor easily like an out of the box product.  However, we sale it for only Japan because of quality of supporting and responsibility.

**Comment by pvnr0082t** [comment]
Hi @mactkg ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by mactkg** [comment]
@pvnr0082t Sorry, I missed the popularity point.  I'll use https://unpkg.com/ to deliver my module.  Thanks!
