### ISSUE TITLE
[Request] Add table2excel.min.js 

### ISSUE THREAD

**Issue by Avinash489** [cdnjs/cdnjs#9127]
**Library name:** table2excel.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@Avinash489 
Any details about this?
Could you offer the github repo?

**Comment by x09326** [comment]
Close due to no response.
