### ISSUE TITLE
[Request] Add jsPanel 

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#9131]
**Library name:** jsPanel
**Git repository url:** https://github.com/Flyer53/jsPanel
**npm package url(optional):**  https://www.npmjs.com/package/jspanel
**License(s):** MIT
**Official homepage:** http://jspanel.de/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Move to #10658
