### ISSUE TITLE
[author] Wrong library version shipped for jsPDF 1.3.0

### ISSUE THREAD

**Issue by MrRio** [cdnjs/cdnjs#9136]
A user reported this to me, but have verified, this appears to be 1.2.x rather than the latest.

https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.0/jspdf.debug.js

The release version and tagged version on github looks correct though?

Thanks very much,
James

See: https://github.com/MrRio/jsPDF/issues/868

**Comment by PeterDaveHello** [comment]
This was added in commit bc90070 by our bot about 3 days ago, it was fetched from the tagged commit, I wonder if you ever re-tagged v1.3.0?

**Comment by MattIPv4** [comment]
Looks like newer versions are being picked up correctly: https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js

Due to the incorrect asset being live for a long time, replacing it is not something that would be viable due to users that may be relying on that version already.
