### ISSUE TITLE
Typo correction.

### ISSUE THREAD

**Issue by Cat5TV** [cdnjs/cdnjs#9137]
Hey team,
I'm not sure how CDNJS is laid out on github, so not sure where I could make this change myself to submit a pull request. So instead, I'll just report it and then watch for the patch so I can see the diff for next time.

[https://cdnjs.com/libraries/bootstrap-formhelpers](https://cdnjs.com/libraries/bootstrap-formhelpers)

The project's URL is spelled incorrectly (boostrap instead of bootstrap). So clicking for documentation is a dead link. Site exists and is up, just that it's spelled wrong on CDNJS.

Regards,
Robbie Ferguson

**Comment by PeterDaveHello** [comment]
@Cat5TV thanks for your report, if you'll like to send a PR, please just edit this file:
https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/bootstrap-formhelpers/package.json

**Comment by Cat5TV** [comment]
Thanks for the info on how to make these types of pull requests. I'll be sure to look around and if I spot anything else in future, I'll see if I can find the files to do the PR.  :)
