### ISSUE TITLE
[Request] Add tree-model-js 

### ISSUE THREAD

**Issue by malhotraa** [cdnjs/cdnjs#9138]
**Library name: tree-model-js** 
**Git repository url: https://github.com/joaonuno/tree-model-js**
**npm package url(optional):** 
**License(s):**
**Official homepage: http://jnuno.com/tree-model-js/**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by joaonuno** [comment]
Hi,

Just updated the [issue](https://github.com/joaonuno/tree-model-js/issues/40) open by @maruilian11 with some questions regarding the process of adding support for [cdnjs](http://cdnjs.com). Waiting for your answers.

**Comment by PeterDaveHello** [comment]
@joaonuno Thanks
