### ISSUE TITLE
[Request] Add pseudocode.js

### ISSUE THREAD

**Issue by seba-1511** [cdnjs/cdnjs#9142]
**Library name:** pseudocode.js
**Git repository url:** https://github.com/tatetian/pseudocode.js
**npm package url(optional):** n/a
**License(s):** MIT
**Official homepage:** http://www.tatetian.io/pseudocode.js/
**Wanna say something? Leave message here:** Thanks a lot for considering adding it to cdnjs.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
Hi @seba-1511 ,
Thanks for suggestion, however, this library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

this issue will be closed if there is no any response in next 7 days, if there is any other good reason to add this lib, we may discuss to add it.

**Comment by seba-1511** [comment]
Thanks for the answer. 

I was redirected here directly from your website, and since I think this library is doing something quite useful it would have been interesting to add it to cdnjs. I'll come back when it's popularity will have grown.

**Comment by maruilian11** [comment]
thank you!

**Comment by maruilian11** [comment]
@PeterDaveHello maybe we can mention the popularity request in website when users click `Request a lib`.
