### ISSUE TITLE
[Request] Add EaselJS 0.8.2

### ISSUE THREAD

**Issue by kwatch** [cdnjs/cdnjs#9145]
**Library name:** 
EaselJS

**Git repository url:**
https://github.com/CreateJS/EaselJS.git

**npm package url(optional):** 

**License(s):**
MIT License

**Official homepage:**
http://www.createjs.com/easeljs

**Wanna say something? Leave message here:**
EaselJS 0.8.0 is already hosted on CDNJS, but 0.8.2 is not.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping

**Comment by kwatch** [comment]
Thank you for your progress and I'm sorry for late response.

I found EaselJS 0.8.0 on CDNJS, but couldn't find 0.8.2.
https://cdnjs.com/libraries/EaselJS

I can't find EaselJS 0.8.2 on CNDJS git repository.

Please let me know what I should do.

**Comment by PeterDaveHello** [comment]
@kwatch oops, I should ping #9265 not this one :)

cc @x09326

**Comment by kwatch** [comment]
I see. thanks.

**Comment by PeterDaveHello** [comment]
@kwatch thank you

**Comment by x09326** [comment]
They are considering to build files without version number.
I'm waiting for their response.
https://github.com/CreateJS/EaselJS/issues/807
https://github.com/CreateJS/EaselJS/issues/785

**Comment by PeterDaveHello** [comment]
@x09326 besides waiting, you could also ping them to understand if things are going, they may even forgot it.

**Comment by sebastianderossi** [comment]
Hi @x09326 + @PeterDaveHello 
EaselJS (along with PreloadJS, SoundJS, TweenJS) is now in `version 1.0.2` what is the best way to get it them on CDNJS?

Thanks!

**Comment by sebastianderossi** [comment]
Hi @PeterDaveHello,

Thanks for the quick response! Hopefully, these issues can be resolved shortly :D 
Thanks again!

**Comment by PeterDaveHello** [comment]
@sebastianderossi 👍

**Comment by extend1994** [comment]
@PeterDaveHello Can this issue move to #12231? There are more missing versions than 0.8.2.

**Comment by PeterDaveHello** [comment]
Fine 👍
