### ISSUE TITLE
[Request] Add tweenjs 0.6.2

### ISSUE THREAD

**Issue by kwatch** [cdnjs/cdnjs#9146]
**Library name:** 
tweenjs

**Git repository url:**
https://github.com/CreateJS/TweenJS.git

**npm package url(optional):** 

**License(s):**
MIT License

**Official homepage:**
http://www.createjs.com/tweenjs

**Wanna say something? Leave message here:**
tweenjs 0.6.0 is already hosted, but 0.6.2 (latest version) is not.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping

**Comment by pvnr0082t** [comment]
@PeterDaveHello There is no any response from https://github.com/CreateJS/TweenJS/issues/74. Should we continue working on #9157?

**Comment by PeterDaveHello** [comment]
@pvnr0082t try our best to continue

**Comment by kwatch** [comment]
I'm sorry for late response, but what should I do as next action?

(what I did)

* I confirmed that tweenjs 0.6.1 is hosted on CDNJS but 0.6.2 (= what I expected) is not yet.
  https://cdnjs.com/libraries/tweenjs
  
* I checked out git repository of cdnjs but I can't find tweenjs 0.6.2 in the repository.

**Comment by PeterDaveHello** [comment]
@kwatch no you don't need to worry about this, we'll take care of it, thanks.

**Comment by kwatch** [comment]
@PeterDaveHello  I see. Thanks.

**Comment by PeterDaveHello** [comment]
Any updates @pvnr0082t ?

**Comment by pvnr0082t** [comment]
@PeterDaveHello No any new response in https://github.com/CreateJS/TweenJS/issues/74. I'm gonna continue working on https://github.com/cdnjs/cdnjs/pull/9157.

**Comment by PeterDaveHello** [comment]
@pvnr0082t Great, we can try our best to get it hosted first.
