### ISSUE TITLE
[Request] bootstrap-dropdown-hover

### ISSUE THREAD

**Issue by rush27** [cdnjs/cdnjs#9151]
Library name: bootstrap-dropdown-hover  
Git repository url: https://github.com/istvan-ujjmeszaros/bootstrap-dropdown-hover
Official homepage: http://www.virtuosoft.eu/code/bootstrap-dropdown-hover/
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @rush27 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's add this lib.

**Comment by istvan-ujjmeszaros** [comment]
Hi guys, sorry, it is just up on npm.
