### ISSUE TITLE
Multi-filemap support in `autoupdate` field

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9155]
Currently, the `autoupdate` field in `package.json` only support single base path with single file list like this:

``` js
  "autoupdate": {
     "source": "git",
     "target": "git://github.com/cdnjs/cdnjs.git",
     "basePath": "",
     "files": [
       "*.json"
     ]
  }
```

We did support multi-filemap in npm auto-update like this (take `waterfall.js` as example):

``` js
  "npmName": "waterfall.js",
  "npmFileMap": [
    {
      "basePath": "",
      "files": [
        "waterfall*"
      ]
    },
    {
      "basePath": "src",
      "files": [
        "waterfall*"
      ]
    }
  ]
```

We should also support the same feature in `autoupdate` field though it is used for git auto-update only, once multi-filemap support added, we can migrate `npmName` and `npmFileMap` to `autoupdate` format.

The multi-filemap should looks like this in `package.json` once it's implemented:

``` js
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/cdnjs/cdnjs.git",
    "fileMap": [
      {
        "basePath": "",
        "files": [
          "*.json"
        ]
      },
      {
         "basePath": "",
         "files": [
           "*.js"
        ]
      }
    ]
  }
```

PS: the auto-updater is in [cdnjs/autoupdate](https://github.com/cdnjs/autoupdate) repo, the corresponding issue there is cdnjs/autoupdate#13

The test cases for `package.json` and example should also be updated at the same time.

**Comment by IonicaBizau** [comment]
I'm on it. :rocket:

**Comment by PeterDaveHello** [comment]
@IonicaBizau Thanks!

**Comment by IonicaBizau** [comment]
@PeterDaveHello If I don't solve it today or tomorrow, remind me. 😂

**Comment by PeterDaveHello** [comment]
@IonicaBizau Sure !
