### ISSUE TITLE
[Request] Add paste.js 

### ISSUE THREAD

**Issue by mkmoisen** [cdnjs/cdnjs#9156]
**Library name:** paste.js
**Git repository url:** https://github.com/layerssss/paste.js.git
**npm package url(optional):** 
**License(s):** MIT 
**Official homepage:** https://github.com/layerssss/paste.js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by mkmoisen** [comment]
Thanks everyone!

**Comment by PeterDaveHello** [comment]
@mkmoisen you're welcome
