### ISSUE TITLE
[Request] blogger-core

### ISSUE THREAD

**Issue by zkreations** [cdnjs/cdnjs#9158]
**Library name: blogger.core.min.css** 
**Git repository url: https://github.com/zkreations/blogger-core**
**npm package url(optional):** 
**License(s): GNU GENERAL PUBLIC LICENSE**
**Official homepage: https://github.com/zkreations/blogger-core**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @zkreations ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
I'm going to close this issue. @zkreations Thanks for your contribution. Feel free to open a new issue again when the library has some notable popularity.
