### ISSUE TITLE
[Request] Add Material Icons 

### ISSUE THREAD

**Issue by luoixie** [cdnjs/cdnjs#9160]
**Library name:** Material Icons
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

Does this link `http://fonts.googleapis.com/icon?family=Material+Icons` has cdn?
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@luoixie Currently no if I didn't remember it wrong, if there is a repo of that, we can easily host it.

**Comment by PeterDaveHello** [comment]
Close d

**Comment by maruilian11** [comment]
hi @luoixie, do you mean this lib? https://cdnjs.com/libraries/material-design-icons
