### ISSUE TITLE
[Request] Add radialIndicator 

### ISSUE THREAD

**Issue by hitechbeijing** [cdnjs/cdnjs#9161]
**Library name:** radialIndicator
**Git repository url:**https://github.com/s-yadav/radialIndicator.git
**npm package url(optional):** 
**License(s):**MIT
**Official homepage:**http://ignitersworld.com/lab/radialIndicator.html
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @hitechbeijing ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We can host this one.

**Comment by pvnr0082t** [comment]
@qwe19272375 You can take this.
