### ISSUE TITLE
[Request] Add Aurelia

### ISSUE THREAD

**Issue by xperiandri** [cdnjs/cdnjs#9166]
**Official homepage:** http://aurelia.io/

**Library name:** Aurelia framework
**Git repository url:** https://github.com/aurelia/framework
**npm package url(optional):** https://www.npmjs.com/package/aurelia-framework

**Library name:** Aurelia bootstrapper
**Git repository url:** https://github.com/aurelia/bootstrapper
**npm package url(optional):** https://www.npmjs.com/package/aurelia-bootstrapper

**Library name:** Aurelia bootstrapper
**Git repository url:** https://github.com/aurelia/bootstrapper-webpack
**npm package url(optional):** https://www.npmjs.com/package/aurelia-bootstrapper-webpack

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by PeterDaveHello** [comment]
@kennynaoh please take this

**Comment by paolocarrasco** [comment]
Hi, is there any news about this?

**Comment by PeterDaveHello** [comment]
@dakshshah96 can you help take this?

**Comment by dakshshah96** [comment]
@PeterDaveHello My pleasure!

**Comment by paolocarrasco** [comment]
Thanks guys. Look forward to it.
