### ISSUE TITLE
[Request] Add ng-device-detector 

### ISSUE THREAD

**Issue by luije87** [cdnjs/cdnjs#9167]
**Library name:** ng-device-detector
**Git repository url:https://github.com/srfrnk/ng-device-detector
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@luije87 , please provide the details of the repository, thanks!

**Comment by luije87** [comment]
https://github.com/srfrnk/ng-device-detector

**Comment by nolsherry** [comment]
@luije87 , thanks for your response, we will add this repository to [cdnjs](https://cdnjs.com/) ASAP!
