### ISSUE TITLE
[Request] Add Twitter Post Fetcher 

### ISSUE THREAD

**Issue by stagfoo** [cdnjs/cdnjs#9169]
**Library name:** Twitter Post Fetcher
**Git repository url:** https://github.com/jasonmayes/Twitter-Post-Fetcher
**npm package url(optional):** https://www.npmjs.com/package/twitter-fetcher
**License(s):**
**Official homepage:** http://www.jasonmayes.com/projects/twitterApi/#sthash.gB3HsLRT.dpbs
**Wanna say something? Leave message here:** this is a really handy twitter api library to let you get tweets and style them.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
close due to duplicated issue
https://github.com/cdnjs/cdnjs/issues/9103

cc @PeterDaveHello
