### ISSUE TITLE
[Request] Add fonts.css

### ISSUE THREAD

**Issue by brentybh** [cdnjs/cdnjs#9171]
**Library name:** fonts.css
**Git repository url:** https://github.com/zenozeng/fonts.css
**npm package url(optional):** https://www.npmjs.com/package/fonts.css
**License(s):** MIT
**Official homepage:** http://zenozeng.github.io/fonts.css/
**Wanna say something? Leave message here:** It's a cross-platform Chinese characters font solution.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
