### ISSUE TITLE
[Request] Add http://ksylvest.github.io/jquery-spin/ 

### ISSUE THREAD

**Issue by ashish-padakannaya** [cdnjs/cdnjs#9172]
**Library name:** http://ksylvest.github.io/jquery-spin/
**Git repository url:** https://github.com/ksylvest/jquery-spin
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @ashish-padakannaya 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to no response

cc @PeterDaveHello
