### ISSUE TITLE
[Request] Add tufte-css 

### ISSUE THREAD

**Issue by DTrejo** [cdnjs/cdnjs#9181]
- [x] Before opening a issue ticket, please check if there is/was already an issue on the same topic.
- [x] @edwardtufte @daveliepmann

---

**Library name:** tufte-css 
**Git repository url:** https://github.com/edwardtufte/tufte-css
**npm package url(optional):**  
**License(s):** MIT
**Official homepage:** https://edwardtufte.github.io/tufte-css/
**Wanna say something? Leave message here:** I hope this suggestion is appropriate. Might need to include the css as well as the font files. Thanks!
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@x09326 do we have any updates here?

**Comment by x09326** [comment]
@PeterDaveHello 
Yes, they reply recently.
