### ISSUE TITLE
[Request] Add angular-ckeditor 

### ISSUE THREAD

**Issue by jacek-pulit** [cdnjs/cdnjs#9184]
**Library name:** angular-ckeditor
**Git repository url:** https://github.com/lemonde/angular-ckeditor
**npm package url(optional):**  https://www.npmjs.com/package/angular-ckeditor
**License(s):** MIT
**Official homepage:** 
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping

**Comment by pvnr0082t** [comment]
@PeterDaveHello I will set git auto-update config for this because there is no any response.
