### ISSUE TITLE
[Request] Add rye 

### ISSUE THREAD

**Issue by micahscopes** [cdnjs/cdnjs#9185]
**Library name:** rye
**Git repository url:** https://github.com/ryejs/rye
**npm package url(optional):** https://www.npmjs.com/package/ryejs
**License(s):** [ISC](https://github.com/ryejs/rye/blob/master/LICENSE)
**Official homepage:** http://ryejs.com
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@PeterDaveHello should I add this library? It seemed to be handled by Piicksarn.

**Comment by PeterDaveHello** [comment]
@extend1994 let's use a new PR to close that PR and this issue, #9429 seem to be dead.
