### ISSUE TITLE
[Request] Add z-grid 

### ISSUE THREAD

**Issue by hefler** [cdnjs/cdnjs#9194]
**Library name:**  z-grid
**Git repository url:** https://github.com/zoopit/z-grid
**License(s):** GPL-3.0
**Official homepage:**  https://zoopit.github.io/z-grid/
**Author:** Felipe Hefler @hefler

**Comment by kennynaoh** [comment]
Hello @hefler ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Close due to no response.
