### ISSUE TITLE
[Request] responsive-carousel

### ISSUE THREAD

**Issue by adrien-be** [cdnjs/cdnjs#9200]
**Library name:** responsive-carousel
**Git repository url:** https://github.com/filamentgroup/responsive-carousel
**npm package url(optional):** https://www.npmjs.com/package/responsive-carousel
**License(s):** MIT, GPL licenses
**Official homepage:** https://www.filamentgroup.com/lab/responsive-carousel.html
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@pvnr0082t any updates here? Should take more care with the "High Priority" issues.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Okay. There is still no response.

**Comment by PeterDaveHello** [comment]
@adrien-be do you have any suggestions? Thanks.
