### ISSUE TITLE
[Request] Add iphone-inline-video 

### ISSUE THREAD

**Issue by gergelypap** [cdnjs/cdnjs#9202]
**Library name:**  iphone-inline-video
**Git repository url:** https://github.com/bfred-it/iphone-inline-video
**npm package url(optional):** https://www.npmjs.com/package/iphone-inline-video
**License(s):** MIT
**Official homepage:** http://bfred-it.github.io/iphone-inline-video/

**Comment by kennynaoh** [comment]
@NiniHsu Please take this.
