### ISSUE TITLE
[Request] Add livequery 

### ISSUE THREAD

**Issue by calete** [cdnjs/cdnjs#9208]
**Library name:** livequery
**Git repository url:** https://github.com/hazzik/livequery
**npm package url(optional):** 
**License(s):** The Live Query plugin is dual licensed (just like jQuery) under the MIT (MIT_LICENSE.txt) and GPL Version 2 (GPL_LICENSE.txt) licenses.
**Official homepage:** https://github.com/hazzik/livequery
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @pvnr0082t
