### ISSUE TITLE
Prepare for the missing license list for intern3

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9211]
@x09326 please create a confirmed libraries list like #6324, including 15 libraries who don't have license info in CDNJS but already been confirmed that the license info is clear and will be easier to be added. cc #5500

**Comment by x09326** [comment]
[ ] camanjs
[ ] clientside-haml-js
[ ] cubism
[ ] cufon
[ ] davis.js
[ ] dd-belatedpng
[ ] diff-match-patch
[ ] dragdealer
[ ] deagonbones
[ ] easeyXDM
[ ] feedback.js
[ ] flexie
[ ] flot
[ ] galleria
[ ] geo-location-javascript

**Comment by PeterDaveHello** [comment]
> @x09326 please create a confirmed libraries list like #6324

Please create another issue and then close this one, thanks!

**Comment by x09326** [comment]
Got it.

**Comment by PeterDaveHello** [comment]
@x09326 please put the issue number here for tracking, thanks.

**Comment by x09326** [comment]
cc #9248
