### ISSUE TITLE
[Request] Add font-linux 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9217]
**Library name:** font-linux
**Git repository url:** https://github.com/Lukas-W/font-linux

**Comment by leoherzog** [comment]
This library has been renamed and moved to
https://github.com/Lukas-W/font-logos
so it is currently no longer getting updates.

**Comment by leoherzog** [comment]
Also, this project uses the public domain Unlicense:
https://raw.githubusercontent.com/Lukas-W/font-logos/v0.11/LICENSE
which isn't specified on [the cdnjs page for the project](https://cdnjs.com/libraries/font-linux).

**Comment by leoherzog** [comment]
This still needs to be re-opened.

**Comment by leoherzog** [comment]
@MattIPv4

**Comment by MattIPv4** [comment]
Please create a new issue if a library needs its auto-update config changed.

**Comment by leoherzog** [comment]
Will do! Thanks!
