### ISSUE TITLE
[Request] Add androidicons 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9218]
**Library name:** androidicons
**Git repository url:** https://github.com/opoloo/androidicons

**Comment by Piicksarn** [comment]
@cdnjs/intern @cdnjs/intern2,
It seems too many files to add (17,602 files).
We must to choose the size of png to include.
The lib use different size shown below :
 - hdpi
 - ldpi
 - mdpi
 - xhdpi
 - xxhdpi

Which ones should we include?

**Comment by PeterDaveHello** [comment]
It's not about the resolution, have you excluded `*.ai` & `*.eps`?

**Comment by Piicksarn** [comment]
@PeterDaveHello, i excluded the those files in package.json and now still have the problem i mentioned above.
Still trying to find the solution :disappointed:

**Comment by PeterDaveHello** [comment]
@x09326 please join us on this issue :smile:

**Comment by maruilian11** [comment]
why not we add all size of file? just exclude `*.ai` and `*.eps`.
why we must choose the size?

**Comment by Piicksarn** [comment]
The problem is that in my actual files number push on GH comes to 17,602.
However, i could see only 17,508 files be pushed on GH.

**Comment by maruilian11** [comment]
can you show me how can you sure you push to GH 17,602 files?
I clone your br, there are only 17,508 modified files.

**Comment by x09326** [comment]
I fetch the branch and see 17508 files.

**Comment by PeterDaveHello** [comment]
```
 17508 files changed, 558 insertions(+)
```

What's the problem?

**Comment by maruilian11** [comment]
@Piicksarn have you tried to fetch all file type? maybe some type of file will be ignored by `.gitignore`.

**Comment by Piicksarn** [comment]
@PeterDaveHello, although it shows 558 insertions(+) in terminal, it shows 0 addition(+) on [code compare page](https://github.com/cdnjs/cdnjs/pull/9283/commits/30d1f9fc979613bd8e7d1c98ad69b2417c153227), and can not jump to package.json.😞 
So that, i can not confirm whether the commit's content be pushed completely and successfully.

**Comment by PeterDaveHello** [comment]
why don't you just confirm the hash? much more easier ...

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 
Why we need all data from assets?
inside iconsfont there is the description of ow to install this package. All needs are: 1 css and font files. Am I right?

**Comment by sashberd** [comment]
@PeterDaveHello Waiting for your approval. Thanks

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 @sufuf3 @extend1994 Ping

**Comment by sufuf3** [comment]
@sashberd Sorry for late reply.
IMO, I think you're right.
The files under `assets` looks be used in website.

Thanks.
