### ISSUE TITLE
[Request] Add morphext 

### ISSUE THREAD

**Issue by filipsedivy** [cdnjs/cdnjs#9219]
**Library name:** morphext
**Git repository url:** https://github.com/MrSaints/Morphext
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://morphext.fyianlai.com/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Niko9911** [comment]
@maruilian11 
This tickets seems to been a long time open. Is there possibility to get this done in a month?

**Comment by PeterDaveHello** [comment]
@sufuf3 please add this one ASAP.

**Comment by maruilian11** [comment]
Sorry for late reply, our project members will help add this soon.
