### ISSUE TITLE
[Request] Add better-dateinput-polyfill 

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [cdnjs/cdnjs#9220]
**Library name:** better-dateinput-polyfill
**Git repository url:** https://github.com/chemerisuk/better-dateinput-polyfill
**npm package url(optional):** https://www.npmjs.com/package/moo-dateinput-polyfill
**License(s):** MIT
**Official homepage:** https://chemerisuk.github.io/better-dateinput-polyfill/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by 0xFEEDC0DE64** [comment]
Is there something wrong with my request?

Nobody answers here and I dont want it to be abandoned.

**Comment by PeterDaveHello** [comment]
@0xFEEDC0DE64 sorry for the delay, since we have a lots of requests, please give us more time on handling this, if you are in hurry, please also consider to send a PR, thanks.
