### ISSUE TITLE
[Request] Add mfglabs-iconset 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9225]
**Library name:** mfglabs-iconset
**Git repository url:** https://github.com/MfgLabs/mfglabs-iconset

**Comment by sashberd** [comment]
@PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
@sashberd as no anyone tagged in the issue, sometimes busy maintainers won't notice that issue, wanna help ping its authors for discussion?
