### ISSUE TITLE
[Request] responsivevoice.js

### ISSUE THREAD

**Issue by vitaoloureiro** [cdnjs/cdnjs#9228]
**Library name:** Responsive Voice
**Git repository url:** https://github.com/ResponsiveVoice/ResponsiveVoice
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://www.responsivevoice.org
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@vitaoloureiro 
Could you provide the Git repository url?
Thanks.

**Comment by vitaoloureiro** [comment]
@x09326 sure
[Git Repsotirory url:](https://github.com/ResponsiveVoice/ResponsiveVoice)

**Comment by sashberd** [comment]
@PeterDaveHello I suggest to close this issue. The lib did not get enough popularity since the issue was opened
FYI
