### ISSUE TITLE
[Request] Add _library_name_ cloud

### ISSUE THREAD

**Issue by aungkyawhtay** [cdnjs/cdnjs#9240]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@aungkyawhtay, we need more detail, thanks.

**`The issue will be closed after 7 days due to no response.`**

**Comment by Piicksarn** [comment]
Closed due to no response.
