### ISSUE TITLE
[Request] Add OpenUI5

### ISSUE THREAD

**Issue by dvorpahl** [cdnjs/cdnjs#9244]
**Library name:** OpenUI5
**Git repository url:** https://github.com/SAP/openui5
**npm package url(optional):**  none
**License(s):** https://github.com/SAP/openui5/blob/master/LICENSE.txt
**Official homepage:** http://openui5.org/
**Wanna say something? Leave message here:**
would be nice to have this framework available

**Comment by sufuf3** [comment]
@PeterDaveHello as the author said https://github.com/SAP/openui5/issues/1237#issuecomment-264413013 they already provide a CDN hosting and they don't see a need for cdnjs: 
- a specific UI5 version like https://openui5.hana.ondemand.com/1.38.21/resources/sap-ui-core.js to manage updates on my own
- the "latest stable" version https://openui5.hana.ondemand.com/resources/sap-ui-core.js, which is updated without prior notice, so it is not recommended for productive apps
(from http://openui5.org/download.html)

And I can't find the minified `sap-ui-core.js` in GitHub repo. 
The `sap-ui-core.js`(non-minify) in GitHub is under `src/sap.ui.core/src/` but it's different from https://openui5.hana.ondemand.com/resources/sap-ui-core.js (this is minified).

What can we do?

**Comment by PeterDaveHello** [comment]
I replied there.

**Comment by PeterDaveHello** [comment]
@sufuf3 the author replied few days ago, see the issue in their repo.

**Comment by sufuf3** [comment]
Thanks, found the file https://github.com/openui5/packaged-sap.ui.core/blob/rel-1.44/resources/sap-ui-core.js
I'll add it.

**Comment by MattIPv4** [comment]
Please see #11789 for why we won't be adding this.
