### ISSUE TITLE
[Request] Add minecraft emoji

### ISSUE THREAD

**Issue by viet** [cdnjs/cdnjs#9245]
**Library name:** minecraft emoji
**Git repository url:** https://github.com/minecraftly/emoji
**npm package url(optional):** 
**License(s):** GNU GPLv3
**Official homepage:** http://mc.ly/emoji
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@viet 
Sorry, but this lib doesn't have enough popularity(100 watch/star or npm package downloaded 300 times per month is a good example). Please take a look at our README.md for detail.
We suggest you open a issue again when the repo has notable popularity.
Thank you for your contribution.

This issue will be closed if there is no any response in next 7 days, if there is any other possibility to add this lib, we may discuss to add it.

**Comment by extend1994** [comment]
Close due to no response over 7 days and insufficient popularity. cc @PeterDaveHello

**Comment by extend1994** [comment]
Close due to no response over 7 days and insufficient popularity. cc @PeterDaveHello
