### ISSUE TITLE
[intern3] Add missing license info of some libs

### ISSUE THREAD

**Issue by x09326** [cdnjs/cdnjs#9248]
This issue is for **intern3**, cc #5500 

**Please ref to this issue in your PR comment! and commit message**

These libs don't have `license` field, please add the missing license in their **package.json** to help us maintain these libs. You can find the license information in the **GitHub repo** or **homepage** of these libs.

SPDX: [license-list](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json)

special case : #9318 

Remaining libs:
- [x] dd_belatedpng
- [x] diff_match_patch

**Comment by yangwanting** [comment]
hashgrid

**Comment by clairetsai818** [comment]
tweet

**Comment by extend1994** [comment]
html5-history-api

**Comment by NiniHsu** [comment]
qwery

**Comment by jj528s35** [comment]
flot

**Comment by jingwei95** [comment]
ng-clip

**Comment by ko19951231** [comment]
noisy

**Comment by emmy41124** [comment]
ng-csv

**Comment by x112358** [comment]
screenfull.js

**Comment by sajochiu** [comment]
ie8

**Comment by dada0423** [comment]
swipe

**Comment by lcd78706** [comment]
galleria

**Comment by dada0423** [comment]
swiper

**Comment by clairetsai818** [comment]
ie8

**Comment by extend1994** [comment]
progress.js

**Comment by clairetsai818** [comment]
ng-clip

**Comment by jingwei95** [comment]
hiw-api

**Comment by jingwei95** [comment]
easeyXDM

**Comment by extend1994** [comment]
wysihtml5

**Comment by dada0423** [comment]
taggd

**Comment by dada0423** [comment]
cufon

**Comment by clairetsai818** [comment]
cubism

**Comment by kiwi89** [comment]
knockout-postbox

**Comment by lcd78706** [comment]
geo-location-javascript

**Comment by yangwanting** [comment]
dragdealer

**Comment by jj528s35** [comment]
ng-csv

**Comment by yangwanting** [comment]
heatmap.js

**Comment by yangwanting** [comment]
vue-smart-table

**Comment by NiniHsu** [comment]
owl-carousel

**Comment by sajochiu** [comment]
taggd

**Comment by PeterDaveHello** [comment]
@x09326 please update the checklist for the added license.

**Comment by nolsherry** [comment]
@PeterDaveHello , I have updated the checklist for the added license.

**Comment by PeterDaveHello** [comment]
@nolsherry Thanks

**Comment by qwe19272375** [comment]
localStorage

**Comment by hare1039** [comment]
knockout.mapping

**Comment by sufuf3** [comment]
requirejs-plugins

**Comment by kiwi89** [comment]
requirejs-plugins

**Comment by honestree** [comment]
tablesort

**Comment by sufuf3** [comment]
jquery.tipsy

**Comment by honestree** [comment]
deagonbones

**Comment by hare1039** [comment]
Timedropper

**Comment by kennynaoh** [comment]
string_score

**Comment by kiwi89** [comment]
jquery.tipsy

**Comment by jj528s35** [comment]
hinclude

**Comment by NiniHsu** [comment]
impress.js

**Comment by clairetsai818** [comment]
timedropper

**Comment by clairetsai818** [comment]
html5-history-api

**Comment by PeterDaveHello** [comment]
@x09326 please confirm if this issue is done and can be closed, I think we moved to the old #5500.

**Comment by x09326** [comment]
Close due to being finished
