### ISSUE TITLE
Make the repo size smaller

### ISSUE THREAD

**Issue by IonicaBizau** [cdnjs/cdnjs#9250]
Currently this repository is really big and hard to work with.

Would it be better to store here only the `package.json` files and ignore the downloaded files by `auto-update`?

Second, I'd propose removing the libraries' code from the history as well, so we reduce the size of the repo. I will be a painful process, but it's not impossible.

**Comment by PeterDaveHello** [comment]
@IonicaBizau yes I'm pushing harder to solve this, let's move to #3941 #3616, thanks.
