### ISSUE TITLE
[Request] Ikki

### ISSUE THREAD

**Issue by michaelnagy** [cdnjs/cdnjs#9263]
**Library name:** Ikki 
**Git repository url:** https://github.com/cognitom/ikki
**npm package url(optional):** https://www.npmjs.com/package/ikki
**License(s):** MIT
**Official homepage:** http://cognitom.github.io/ikki/
**Wanna say something? Leave message here:**

**Comment by pvnr0082t** [comment]
Hi @michaelnagy ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We'll host this one.
