### ISSUE TITLE
[Request] Add scrollintoview 

### ISSUE THREAD

**Issue by beneficialmedia** [cdnjs/cdnjs#9264]
**Library name:** scrollintoview
https://github.com/litera/jquery-scrollintoview
**npm package url(optional):** 
MIT
http://erraticdev.blogspot.com/2011/02/jquery-scroll-into-view-plugin-with.html
This is a great cross-browser jquery extension to https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@qwe19272375 You can take this.
