### ISSUE TITLE
[Request] Add ng-prettyjson

### ISSUE THREAD

**Issue by yintaosong** [cdnjs/cdnjs#9266]
**Library name:** ng-prettyjson
**Git repository url:** https://github.com/darul75/ng-prettyjson
**npm package url(optional):** https://www.npmjs.com/package/ng-prettyjson
**License(s):** MIT
**Official homepage:** http://darul75.github.io/ng-prettyjson/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @yintaosong ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Close enough, give it more time or a lower priority.
