### ISSUE TITLE
[Request] Add Marzipano

### ISSUE THREAD

**Issue by austinbiggs** [cdnjs/cdnjs#9280]
Marzipano (on Google's Github)
https://github.com/google/marzipano
Apache License
http://www.marzipano.net/
Please check this out, this one is a no brainer, seriously!
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Ping @x09326
