### ISSUE TITLE
[Request] Add SCEditor

### ISSUE THREAD

**Issue by taichunmin** [cdnjs/cdnjs#9296]
**Library name:** SCEditor
**Git repository url:** https://github.com/samclarke/SCEditor
**npm package url(optional):** https://www.npmjs.com/package/sceditor
**License(s):** MIT License
**Official homepage:** http://www.sceditor.com/
**Wanna say something? Leave message here:** Please add this library. Thanks!

**Comment by PeterDaveHello** [comment]
@taichunmin would you like to send a PR?

**Comment by taichunmin** [comment]
我研究一下要怎麼加 :)
