### ISSUE TITLE
add elementui

### ISSUE THREAD

**Issue by liutao0532** [cdnjs/cdnjs#9298]
Note: If you'd like to request a new library, please follow this link: https://cdnjs.com/request-new-lib
https://github.com/ElemeFE/element

thank s

**Comment by sashberd** [comment]
@PeterDaveHello What is this issue about?

**Comment by sufuf3** [comment]
@sashberd this is an adding library request.
CDNJS host this lib https://cdnjs.com/libraries/element-ui
Let's close this issue. :)
cc @PeterDaveHello
