### ISSUE TITLE
[Request] Update flux to 3.0.0

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [cdnjs/cdnjs#9301]
**Library name:** flux
**Git repository url:** https://github.com/facebook/flux
**npm package url(optional):** https://www.npmjs.com/package/flux
**Files:** https://github.com/facebook/flux/tree/master/dist

**Comment by PeterDaveHello** [comment]
They forgot to publish v3.0.0 on GitHub but only on npm ... I'll transfer flux to use npm auto-update, but you can consider to report this problem to upstream, thanks.

**Comment by PeterDaveHello** [comment]
Fixed.
