### ISSUE TITLE
[Request] Add jquery-2.2.4.js 

### ISSUE THREAD

**Issue by ambonium** [cdnjs/cdnjs#9302]
**Library name:** jquery-2.2.4.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
https://cdnjs.com/libraries/jquery/2.2.4
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js
https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js
