### ISSUE TITLE
[Request] shapecss

### ISSUE THREAD

**Issue by MicroDreamIT** [cdnjs/cdnjs#9303]
**Library name: Shapecss** 
**Git repository url: https://github.com/MicroDreamIT/ShapeCss**
**npm package url(optional):** 
**License(s): MIT**
**Official homepage: www.shapecss.com**
**Wanna say something? Leave message here: I wish this repository help people for drawing geometrical shapes**

=====================
Notes from cdnjs maintainer: We will very much glad if you accept our request.
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MicroDreamIT** [comment]
I did not understand, what it mean?

**Comment by pvnr0082t** [comment]
Hi @MicroDreamIT ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
