### ISSUE TITLE
[Request] Add angular-notification 

### ISSUE THREAD

**Issue by mrova** [cdnjs/cdnjs#9307]
**Library name:** angular-notification
**Git repository url:** https://github.com/neoziro/angular-notification
**npm package url(optional):** https://www.npmjs.com/package/angular-notification
**License(s):** MIT
**Official homepage:** https://github.com/neoziro/angular-notification
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@PeterDaveHello The popularity of this lib looks close to threshold. Can this be added?

**Comment by PeterDaveHello** [comment]
Sure!
