### ISSUE TITLE
[Request] Add vuikit 

### ISSUE THREAD

**Issue by miljan-aleksic** [cdnjs/cdnjs#9308]
**Library name:** Vuikit
**Git repository url:** https://github.com/vuikit/vuikit
**npm package url(optional):** https://www.npmjs.com/package/vuikit
**License(s):** MIT
**Official homepage:** https://vuikit.github.io/vuikit

**Comment by kytwb** [comment]
I'm taking this one, will come back with a PR within 24 hours.

**Comment by PeterDaveHello** [comment]
Added in #9355, thanks @kytwb!
