### ISSUE TITLE
[Request] Add bvalidator 

### ISSUE THREAD

**Issue by cronos916** [cdnjs/cdnjs#9312]
**Library name:** bvalidator
**Git repository url:** https://github.com/bmauser/bvalidator
**npm package url(optional):** https://www.npmjs.com/package/bvalidator
**License(s):** MIT
**Official homepage:** http://bmauser.github.io/bvalidator/#licence

**Comment by pvnr0082t** [comment]
Hi @cronos916 ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
