### ISSUE TITLE
[Request] Update zabuto_calendar to 1.3

### ISSUE THREAD

**Issue by dearsina** [cdnjs/cdnjs#9316]
Library name: zabuto_calendar
Git repository url: https://github.com/zabuto/calendar
License(s): MIT Licence
Official homepage: http://zabuto.com/dev/calendar/examples/index.html

Currently only versions up to 1.2.1 are found. Please add 1.3.

Thank you!

**Comment by pvnr0082t** [comment]
@dearsina The version 1.3 haven't been released yet. Ref: https://github.com/zabuto/calendar/releases
Once the version 1.3 released, I think the auto-updater in cdnjs will update it. Thanks for your contribution.
