### ISSUE TITLE
[Request] Add antlr4 

### ISSUE THREAD

**Issue by jdl-mit-alum** [cdnjs/cdnjs#9325]
**Library name:** antlr4
**Git repository url: https://github.com/antlr/antlr4
*_npm package url(optional): https://www.npmjs.com/package/antlr4
*_License(s): BSD
*_Official homepage: http://www.antlr.org/
*_Wanna say something? Leave message here:**

It is the runtime library that is needed for cdnjs:

https://github.com/antlr/antlr4/tree/master/runtime/JavaScript/src
-  This is not my repository, but I expect it would be popular.
-  I am writing client-side DSL lexers/parsers using ANTLR4.
-  Having the runtime available for <links> or requires would
-  enable me to make my offerings lighter-weight since
-  duplicating active well-managed existing repos is typically
-  less productive than fetching it live as I do with
-  jquery, underscore, and other important libraries.
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
This NPM package does not include a bundled version, so we cannot add this. Please reach out to the library maintainers and ask them to include a bundled version in their package, then create a new cdnjs issue once this is available.
