### ISSUE TITLE
[Request] Add swiftclick

### ISSUE THREAD

**Issue by huhgawz** [cdnjs/cdnjs#9327]
**Library name:** swiftclick
**Git repository url:** https://github.com/munkychop/swiftclick
**npm package url(optional):** https://www.npmjs.com/package/swiftclick
**License(s):** MIT
**Official homepage:** https://github.com/munkychop/swiftclick
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @huhgawz 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
Close due to no response.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
We should host this one.

**Comment by huhgawz** [comment]
swiftclick has been added through Pull Request #[9329](https://github.com/cdnjs/cdnjs/pull/9329). This issue can be closed.

**Comment by PeterDaveHello** [comment]
Oh cool, thanks @huhgawz
