### ISSUE TITLE
[Request] Add custom-elements 

### ISSUE THREAD

**Issue by richardkazuomiller** [cdnjs/cdnjs#9331]
**Library name:** custom-elements
**Git repository url:** https://github.com/webcomponents/custom-elements
**npm package url(optional):** 
**License(s):** BSD
**Official homepage:** http://webcomponents.org
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @richardkazuomiller 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by richardkazuomiller** [comment]
I know it has few stars because it's quite new, but it is the successor to the custom element polyfills in [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs), which is quite popular, I think it's worth adding. `custom-elements` polyfills the Custom Elements v1 API, whereas `webcomponentsjs` polyfills v0 which will not be supported in the future.

**Comment by PeterDaveHello** [comment]
Fair enough.
