### ISSUE TITLE
avalon.js auto-update not working

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9332]
The structure on upstream seems to be not suitable for auto-update anymore, @x09326 please take care of this issue, thanks.

**Comment by x09326** [comment]
@PeterDaveHello 
Do you mean the old versions can't be added?

**Comment by PeterDaveHello** [comment]
Should be the new versions. If you trace the commit log you may see I manually added the recent versions.

**Comment by x09326** [comment]
@PeterDaveHello 
I test the auto-update for this library and it is okay.

**Comment by PeterDaveHello** [comment]
No, it's not, or I won't add them by myself.

**Comment by x09326** [comment]
This is my auto-update result, I just grep the latest 4 version information.
```
All files for avalon.js v2.1.7 - 11
11 true
All files for avalon.js v2.1.8 - 9
9 true
All files for avalon.js v2.1.16 - 11
11 true
All files for avalon.js v2.1.16ee - 9
9 true
avalon.js updated from Git
```

**Comment by PeterDaveHello** [comment]
@x09326 Checkout the content.

**Comment by x09326** [comment]
Take 2.1.16 as a example.
The files downloaded by auto-update are same as in the git repo.

**Comment by PeterDaveHello** [comment]
You should take a look at the files been committed.
