### ISSUE TITLE
Merge / migrate tools/fix* programs

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9333]
Should merge them into a single `fixFormat.js`

**Comment by petrgazarov** [comment]
Hey @PeterDaveHello! I'm new to the codebase and would like to contribute to this. This task sounds clear to me and looks like a good first-PR.

**Comment by PeterDaveHello** [comment]
@petrgazarov That's nice! Please ping me when you send the PR!

**Comment by petrgazarov** [comment]
@PeterDaveHello I'm trying to clone the repo, but looks like its too big for the amount of memory I have, ~17GB not enough. How large is the repo and is there a way to reduce the clone memory?

**Comment by PeterDaveHello** [comment]
@petrgazarov https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md
SparseCheckout and shallow clone will help, thanks!

**Comment by petrgazarov** [comment]
Awesome, I knew there must be a way!

**Comment by PeterDaveHello** [comment]
Done in #9346 but forgot to close issue in commit message, manually close it now. Thanks @petrgazarov
