### ISSUE TITLE
[Request] CanvasXpress

### ISSUE THREAD

**Issue by neuhausi** [cdnjs/cdnjs#9334]
**Library name: canvasXpress** 
**Git repository url: https://github.com/neuhausi/canvasXpress**
**npm package url(optional):** 
**License(s): GLP3**
**Official homepage: http://canvasxpress.org/html/index.html**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
please help me check git tag issue neuhausi/canvasXpress#8
