### ISSUE TITLE
[Request] Add versify

### ISSUE THREAD

**Issue by sammoorhouse** [cdnjs/cdnjs#9335]
**Library name:** versify
**Git repository url:** https://github.com/sammoorhouse/versify
**npm package url(optional):** n/a
**License(s):** MIT
**Official homepage:** sammoorhouse.github.io/versify
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @sammoorhouse ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by sammoorhouse** [comment]
Okay, thanks! Closing for now.

**Comment by PeterDaveHello** [comment]
@sammoorhouse feel free to ping us once you got a notable popularity, sorry for the inconvenience!
