### ISSUE TITLE
[Request] ngprogress 1.1.2

### ISSUE THREAD

**Issue by ezetojo** [cdnjs/cdnjs#9336]
**Library name: ngprogress 1.1.2** 
**Git repository url: https://github.com/VictorBjelkholm/ngProgress**
**npm package url(optional):** 
**License(s):**
**Official homepage: https://github.com/VictorBjelkholm/ngProgress**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@x09326 let's import the missing versions from git repo.
