### ISSUE TITLE
[Request] Add two events,js 

### ISSUE THREAD

**Issue by Salvodif** [cdnjs/cdnjs#9337]
**Library name:** two events,js
**Git repository url:** https://github.com/jonobr1/two.js/blob/master/third-party/events.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @Salvodif 
Could you tell me which files do you want us to hold?
Just `events.js` or the [files](https://github.com/jonobr1/two.js/tree/master/build) under `builds`? 
Thank you!

**Comment by PeterDaveHello** [comment]
@extend1994 `events.js` is under third-party dir, so of course you should add files under `builds`, if `events.js` can't be added as a library individually, then we add it together.

**Comment by extend1994** [comment]
@PeterDaveHello So what I need to add are all files under `build` and `event.js`, and I don't need to add other files under `third-party`? Or I should ask the author what should I add to confirm if adding `event.js` is suitable?

**Comment by PeterDaveHello** [comment]
@extend1994 as I mentioned, you'll need to check if the third-party libs already hosted on cdnjs, if not, can we host it individually? (meets enough popularity and other requirements?) If we can not host it individually, then we'll consider to add them.

**Comment by MattIPv4** [comment]
Appears to no longer exist, closing.
