### ISSUE TITLE
[Request] Add typeis

### ISSUE THREAD

**Issue by salihsagdilek** [cdnjs/cdnjs#9339]
**Library name:** typeis
**Git repository url:** https://github.com/typeis/typeisjs
**npm package url(optional):** https://www.npmjs.com/package/typeis
**License(s):** MIT
**Official homepage:** https://typeis.github.io/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @salihsagdilek ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by kennynaoh** [comment]
close due to no response

**Comment by PeterDaveHello** [comment]
We might host this, just give it a lower priority.

**Comment by salihsagdilek** [comment]
ahh sorry @kennynaoh i dont see question, i dont know yet but i think it's a usable and yea by and by the library has more popularity.

and @PeterDaveHello thank you for faith.
