### ISSUE TITLE
[Request] react-json-tree

### ISSUE THREAD

**Issue by gwestwater** [cdnjs/cdnjs#9343]
React Json Tree
https://github.com/alexkuz/react-json-tree
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Add it after [issue](https://github.com/alexkuz/react-json-tree/issues/64) solved.
