### ISSUE TITLE
[Request] Add _angulartics2 

### ISSUE THREAD

**Issue by kimaina** [cdnjs/cdnjs#9346]
**Library name:angulartics2** 
**Git repository url:https://github.com/angulartics/angulartics2**
**npm package url(optional):angulartics2** 
**License(s):The MIT License (MIT)**
**Official homepage: http://angulartics.github.io/**
**please try to add asap**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by drewfreyling** [comment]
@PeterDaveHello are we able to host typescript files?

**Comment by PeterDaveHello** [comment]
@drewfreyling Not yet, need support from @terinjokes / Cloudflare
