### ISSUE TITLE
[Request] Add chatbot

### ISSUE THREAD

**Issue by ddsky** [cdnjs/cdnjs#9356]
**Library name: chatbot** 
**Git repository url:https://github.com/ddsky/chatbot**
**License(s): Apache 2.0**
**Official homepage:https://github.com/ddsky/chatbot**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @ddsky   :
There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for more detail.
Would you mind to open a new issue again when it comes to be notable popularity? :grinning: 
Thanks for your request! 

***`The issue will be closed if it has no response in 7 days.`***

Piicksarn.

**Comment by maruilian11** [comment]
close due to no response.
