### ISSUE TITLE
[Request] reacthttp 

### ISSUE THREAD

**Issue by tinpee** [cdnjs/cdnjs#9359]
**Library name:** reacthttp
**Git repository url:** https://github.com/tinpee/reacthttp.git
**npm package url(optional):** https://www.npmjs.com/package/reacthttp
**License(s):** MIT
**Official homepage:** http://tinpee.github.io/reacthttp
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @tinpee ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks close, we may host this.

**Comment by tinpee** [comment]
@PeterDaveHello Thank you!

**Comment by PeterDaveHello** [comment]
@tinpee No problem.
