### ISSUE TITLE
[Request] Add egg.js

### ISSUE THREAD

**Issue by J2TeaM** [cdnjs/cdnjs#9363]
**Library name:** egg.js
**Git repository url:** https://github.com/mikeflynn/egg.js
**Official homepage:** http://thatmikeflynn.com/egg.js/

**Comment by J2TeaM** [comment]
Ping @PeterDaveHello , @maruilian11 😁

**Comment by maruilian11** [comment]
@J2TeaM Ｓorry to keep you waiting so long. I am going to send a PR for this issue.
