### ISSUE TITLE
[Request] Add treant js

### ISSUE THREAD

**Issue by pradeepsixer** [cdnjs/cdnjs#9365]
**Library name:** treant
**Git repository url:** https://github.com/fperucic/treant-js
**npm package url(optional):** https://www.npmjs.com/package/treant-js
**License(s):** MIT
**Official homepage:** http://fperucic.github.io/treant-js/
**Wanna say something? Leave message here:**
This library is for visualization of tree structures.

**Comment by kennynaoh** [comment]
Hello @pradeepsixer 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks close, we may add this.
