### ISSUE TITLE
[test] check unexpected leading slash with filename in package.json

### ISSUE THREAD

**Issue by nolsherry** [cdnjs/cdnjs#9367]
There should not be the leading slash  with filename in auto-update config file map 
We need to check unexpected leading slash with filename in auto-update config,
and add this check item in `fixFormat.js`.

cc @PeterDaveHello , cc  #9355

**Comment by PeterDaveHello** [comment]
@nolsherry hmmm ... since we'll test the file, I think the trailing slash will be detected by that, so we'll deal with the leading one here.

**Comment by nolsherry** [comment]
@PeterDaveHello , OK, I will correct the description of issue, thanks!

**Comment by PeterDaveHello** [comment]
#9422
