### ISSUE TITLE
node auto-update.js run always errs with "malicious npmFileMap" on Windows

### ISSUE THREAD

**Issue by alexdima** [cdnjs/cdnjs#9368]
There is a large number of packages already checked in to this repository that suffer from this issue.

Have a package.json without a `basePath`:

```
  "npmName": "monaco-editor",
  "npmFileMap": [
    {
      "files": [
        "min/**/*",
        "min-maps/**/*"
      ]
    }
  ]
```

The following function always returns false:
- `isValidPath` is called with `"/"` because there is no `fileSpec.basePath`
- `return p === path.normalize(p);` returns false because `path.normalize('/')` is `"\"` on windows
- I suggest changing the check to something like `return p === path.normalize(p).replace(/\\/g, '/');`

``` js
/**
 * Check if an npmFileMap object contains any path which are not normalized, and thus could allow access to parent dirs
 * @param pkg
 * @returns {*}
 */
var isValidFileMap = function(pkg) {
  var isValidPath = function(p) {
    if (p !== null) { // don't allow parent dir access, or tricky paths
      p = p.replace(/\/+/g, '/'); // don't penalize for consequtive path seperators
      return p === path.normalize(p);
    }
    return false;
  };

  if (pkg && pkg.npmFileMap) {
    return _.every(pkg.npmFileMap, function(fileSpec) {
      if (isValidPath(fileSpec.basePath || "/")) {
        return _.every(fileSpec.files, isValidPath);
      }
      return false;
    });
  }
  return false;
};
```

**Comment by PeterDaveHello** [comment]
@alexandrudima thanks for your report! 
@pvnr0082t would you like to take a first look at this issue?
