### ISSUE TITLE
[Request] Add Social Icons

### ISSUE THREAD

**Issue by erictansh** [cdnjs/cdnjs#9372]
**Library name:** Social Icons
**Git repository url:** https://github.com/jivinivan/soc.js
**License(s):** MIT License
**Official homepage:** http://ivansugerman.com/soc.js/

**Comment by erictansh** [comment]
please help to add.. thanks!

**Comment by PeterDaveHello** [comment]
@erictansh thanks for suggestion, we'll take a look at it.
