### ISSUE TITLE
[Request] Add angular-storage 

### ISSUE THREAD

**Issue by rafaelgom3s** [cdnjs/cdnjs#9380]
**Library name:** angular-storage
**Git repository url:** https://github.com/auth0/angular-storage
**npm package url(optional):** https://www.npmjs.com/package/angular-storage
**License(s):** MIT
**Official homepage:** https://github.com/auth0/angular-storage
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@NiniHsu Please take this.
