### ISSUE TITLE
[Request] Add jquery.ui.datepicker.mobile.css 

### ISSUE THREAD

**Issue by adamz01h** [cdnjs/cdnjs#9381]
**Library name:** jquery.ui.datepicker.mobile.css
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by nolsherry** [comment]
@adamz01h, please provide the details of the library, thanks!

**Comment by nolsherry** [comment]
Closed due to no response in 7 days.
