### ISSUE TITLE
[Request] Add sticky-kit 

### ISSUE THREAD

**Issue by arbet** [cdnjs/cdnjs#9384]
**Library name:** sticky-kit
**Git repository url:** https://github.com/leafo/sticky-kit
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://leafo.net/sticky-kit/
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
duplicated with #7522

**Comment by PeterDaveHello** [comment]
Let's move to #7522
