### ISSUE TITLE
[Request] Add material-scrolltop 

### ISSUE THREAD

**Issue by amulecregg** [cdnjs/cdnjs#9387]
**Library name:** material-scrolltop
**Git repository url:** https://github.com/bartholomej/material-scrolltop
**npm package url(optional):** 
**License(s):** MIT Licence
**Official homepage:** http://bartholomej.github.io/material-scrolltop
**Wanna say something? Leave message here:** Lightweight, Material Design inspired button for scroll-to-top of the page (jQuery plugin).
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @amulecregg 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Looks close, we can wait for it, just give it a lower priority.
