### ISSUE TITLE
[Request] Add Poshytip

### ISSUE THREAD

**Issue by bunnymatic** [cdnjs/cdnjs#9388]
**Library name:** Poshytip
**Git repository url:** https://github.com/vadikom/poshytip.git
**npm package url(optional):** 
**License(s):** GPL, MIT
**Official homepage:** http://vadikom.com/tools/poshy-tip-jquery-plugin-for-stylish-tooltips/
**Wanna say something? Leave message here:**  Part of the reason I'd like to see this is because you have `x-editable` (https://cdnjs.com/libraries/x-editable) in the library and that repo needs poshytip for part of it.  It'd be nice to pull them both from cdnjs.

I'll see if i can figure out how to add it myself as a PR.
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by bunnymatic** [comment]
I did some looking around and trying to add this to my own project.  It seems that project is a bit stale and depends on another old jquery extension ($.browser).  So I think it's best not to add this.  And I should move on to something more modern than `x-editable`.

I'm closing this request.

Thanks

**Comment by PeterDaveHello** [comment]
We can still host this :)

**Comment by bunnymatic** [comment]
Cool.
