### ISSUE TITLE
[intern3] Add new libraries

### ISSUE THREAD

**Issue by kennynaoh** [cdnjs/cdnjs#9414]
First library add for intern 3
- [x] boba.js https://github.com/cdnjs/cdnjs/issues/8891
- [ ] lawnchair https://github.com/cdnjs/cdnjs/issues/8058
- [x] ZingChart-React https://github.com/cdnjs/cdnjs/issues/9796
- [x] ZingChart-AngularJS https://github.com/cdnjs/cdnjs/issues/9797
- [ ] gitbook-plugin-code-editor https://github.com/cdnjs/cdnjs/issues/9798
- [x] leaflet.pm https://github.com/cdnjs/cdnjs/issues/9799
- [x] Template7 https://github.com/cdnjs/cdnjs/issues/9480
- [x] javascript-astar https://github.com/cdnjs/cdnjs/issues/9540
- [x] jquery-localize https://github.com/cdnjs/cdnjs/issues/9563
- [x] NoSleep.js https://github.com/cdnjs/cdnjs/issues/9517
- [x] angular-formly-templates-material https://github.com/cdnjs/cdnjs/issues/9596
- [x] cropit https://github.com/cdnjs/cdnjs/issues/9647
- [x] kotojs https://github.com/cdnjs/cdnjs/issues/9746
- [x] vee-validate https://github.com/cdnjs/cdnjs/issues/9646
- [x] flexMenu https://github.com/cdnjs/cdnjs/issues/9740
- [x] clarinet https://github.com/cdnjs/cdnjs/issues/9761
- [x] MinPubSub https://github.com/cdnjs/cdnjs/issues/8658
- [x] snabbdom https://github.com/cdnjs/cdnjs/issues/9785
---
- [x] pagination.js https://github.com/cdnjs/cdnjs/issues/9483

**Comment by clairetsai818** [comment]
NoSleep.js

**Comment by lcd78706** [comment]
leaflet.pm

**Comment by PeterDaveHello** [comment]
@dada0423 Duplicated

**Comment by clairetsai818** [comment]
＠PeterDaveHello I've changed the library.

**Comment by dada0423** [comment]
NoSleep.js

**Comment by qwe19272375** [comment]
clarinet

**Comment by hare1039** [comment]
snabbdom

**Comment by honestree** [comment]
angular-formly-templates-material

**Comment by sufuf3** [comment]
kotojs

**Comment by lcd78706** [comment]
boba.js

**Comment by qwe19272375** [comment]
Template7

**Comment by clairetsai818** [comment]
MinPubSub

**Comment by clairetsai818** [comment]
lawnchair

**Comment by PeterDaveHello** [comment]
Hey guys, anyone would like to take #9483? This one should be solved with higher prioroty, thanks.

**Comment by hare1039** [comment]
I'll take the #9483

**Comment by lcd78706** [comment]
vee-validate

**Comment by NiniHsu** [comment]
jquery-localize

**Comment by sajochiu** [comment]
gitbook-plugin-code-editor

**Comment by PeterDaveHello** [comment]
Awesome 👍 
I'll like to give two more choices here: #9289 #9263 🚀

**Comment by hare1039** [comment]
Griddle #9289

**Comment by qwe19272375** [comment]
Ikki #9263

**Comment by lcd78706** [comment]
javascript-astar

**Comment by NiniHsu** [comment]
ZingChart-AngularJS

**Comment by dada0423** [comment]
boba.js

**Comment by PeterDaveHello** [comment]
Are we done here?

**Comment by PeterDaveHello** [comment]
Ping @kennynaoh

**Comment by PeterDaveHello** [comment]
@cdnjs/intern3 please help update the checklist and see how many remains can be reused by intern4, thanks.

**Comment by qwe19272375** [comment]
- lawnchair #8058
- gitbook-plugin-code-editor #9798
- javascript-astar #9540
- jquery-localize #9563

These issues are left open, mostly waiting for response.

**Comment by extend1994** [comment]
@qwe19272375 #9540 seems closed?

**Comment by qwe19272375** [comment]
Yes, thank you.

**Comment by MattIPv4** [comment]
We no longer have interns working on this project, closing.
