### ISSUE TITLE
[Request] Update foundation-datepicker

### ISSUE THREAD

**Issue by XmlmXmlmX** [cdnjs/cdnjs#9427]
**Library name:** foundation-datepicker
**Git repository url:** https://github.com/najlepsiwebdesigner/foundation-datepicker
**npm package url(optional):** https://www.npmjs.com/package/foundation-datepicker
**License(s):**  Apache License Version 2.0
**Official homepage:** http://foundation-datepicker.peterbeno.com
**Wanna say something? Leave message here:** The library is already available at cdnjs, but some files are missing (all in [locales](https://github.com/najlepsiwebdesigner/foundation-datepicker/tree/master/js/locales)).

**Comment by pvnr0082t** [comment]
A little complicated in this case. @PeterDaveHello will take over it.

**Comment by PeterDaveHello** [comment]
@XmlmXmlmX thanks for your report, the files are all online now, however, the updates to the website will have a short delay, you can just directly access the files via modifying the URLs, thanks and sorry for the inconvenience caused.

**Comment by XmlmXmlmX** [comment]
Wow, this was fast. Thank you 👍
