### ISSUE TITLE
BLOCKED

### ISSUE THREAD

**Issue by sefatunckanat** [cdnjs/cdnjs#9430]

**Comment by pvnr0082t** [comment]
Hi @sefatunckanat ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
close due to information had been deleted. @sefatunckanat Thanks for your contribution.
