### ISSUE TITLE
[Request] font-awesome/4.6.3/css/font-awesome.min.css

### ISSUE THREAD

**Issue by anurag899** [cdnjs/cdnjs#9438]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What's the problem here please?

**Comment by PeterDaveHello** [comment]
Close due to no response.
