### ISSUE TITLE
cdnjs_mirror

### ISSUE THREAD

**Issue by akzoe** [cdnjs/cdnjs#9442]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
What's this for please?

**Comment by PeterDaveHello** [comment]
Close due to no response.
