### ISSUE TITLE
[Request] Add chosen-bootstrap 

### ISSUE THREAD

**Issue by wallace-eduardo** [cdnjs/cdnjs#9444]
**Library name:** chosen-bootstrap
**Git repository url:**https://github.com/dbtek/chosen-bootstrap
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
# 

Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @wallace-eduardo 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by wallace-eduardo** [comment]
Ok, works for me

**Comment by kennynaoh** [comment]
close due to not enough popularity
