### ISSUE TITLE
[Request] Add chartjs-plugin-zoom

### ISSUE THREAD

**Issue by g-liu** [cdnjs/cdnjs#9445]
**Library name:** chartjs-plugin-zoom
**Git repository url:** https://github.com/chartjs/chartjs-plugin-zoom
**npm package url(optional):** https://www.npmjs.com/package/chartjs-plugin-zoom
**License(s):** MIT
**Official homepage:** (none)
**Wanna say something? Leave message here:**
There's a couple of nice plugins for ChartJS that could be added to the CDN. [Here's a list](http://www.chartjs.org/docs/#notes-popular-plugins).

**Comment by kennynaoh** [comment]
Hello @g-liu 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
@x112358 Please take this
