### ISSUE TITLE
material-design-lite: add color variants

### ISSUE THREAD

**Issue by ishitatsuyuki** [cdnjs/cdnjs#9446]
According to the [official page](https://getmdl.io/started/index.html), they have color variant and they *only* have it.

> These colors are specified in the CSS file name by following this pattern: `material.{primary}-{accent}.min.css`

This is a request to add all the variant so I can replace their crappy CDN with cdnjs.

**Comment by PeterDaveHello** [comment]
Already there: https://cdnjs.com/libraries/material-design-lite

**Comment by ishitatsuyuki** [comment]
@PeterDaveHello hey, **read again**
I'm requesting for color variants.
