### ISSUE TITLE
[Request] Add Silk Icons

### ISSUE THREAD

**Issue by sweepyoface** [cdnjs/cdnjs#9451]
**Library name:**  Silk Icons
**Git repository url:** https://github.com/legacy-icons/famfamfam-silk
**npm package url(optional):** https://www.npmjs.com/package/famfamfam-silk
**License(s):** N/A
**Official homepage:** http://www.famfamfam.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @sweepyoface ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
close due to no response.
