### ISSUE TITLE
[Request] Add _library_name_ 

### ISSUE THREAD

**Issue by qumorm** [cdnjs/cdnjs#9456]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, `thanks!!`/*!

Theme Name: Decode

Theme URI: http://www.machothemes.com/themes/decode/

Version: 3.15.3

Author: Macho Themes

Author URI: http://www.machothemes.com/

Description: A minimal, modern theme, designed to be mobile first and fully responsive. Decode features the ability to change all the colors in the theme and an elegant sidebar conveniently accessed by tapping on the menu icon. The sidebar can fit all of your widgets and its position can be customized. You can also choose to keep the sidebar always visible on larger screens for a smooth two-column experience. You can even disable the sidebar and comment links if you choose. Decode supports link posts, where the title can be hyperlinked. Decode includes custom social icons in the header that you can easily link to your choice of 55 different social profiles from Twitter and Instagram, to Pinterest and LinkedIn, you will be sure to find support for the network you want alongside a bevy of customizations to make your site unique. Decode has been translated into Chinese, Dutch, French, German, Polish, Russian, and Spanish. <a href="http://www.machothemes.com/themes/decode/">More info here</a>

Tags: responsive-layout, one-column, two-columns, left-sidebar, right-sidebar, custom-background, custom-colors, custom-header, editor-style, featured-images, microformats, post-formats, rtl-language-support, sticky-post, theme-options, threaded-comments, translation-ready

License: GNU General Public License v3.0

License URI: http://www.gnu.org/licenses/gpl-3.0-standalone.html

Domain Path: /languages/

Text Domain: decode

Decode is based on Underscores http://underscores.me/, (C) 2012-2015 Automattic, Inc.

/*--------------------------------------------------------------

>>> TABLE OF CONTENTS:

----------------------------------------------------------------

1.0  - Reset

	1.1 - Normalize

	1.2 - Elements

	1.3 - Typography

	1.4 - Forms

2.0  - Utilities

	2.1 - Accessibility

	2.2 - Clearing

3.0  - Media

	3.1 - Captions

	3.2 - Galleries

	3.3 - Alignment

4.0  - Header

	4.1 - Site Branding

	4.2 - Social Links

	4.3 - Menus

	4.4 - Breadcrumbs

5.0  - Content

6.0  - Post Formats

	6.1 - Link Posts

	6.2 - Quote Posts

	6.3 - Asides

	6.4 - Audio Posts

7.0  - Author Profiles

	7.1 - Author Cards

	7.2 - Author Pages

8.0  - Comments

9.0  - Navigation

10.0 - Search

11.0 - Sidebar

12.0 - Widgets

13.0 - Explore Page

14.0 - Infinite Scroll

15.0 - Media Queries

	15.1 - Tablets (<35ems)

	15.2 - Desktops (<50ems)

	15.3 - Large Screens (<68.5ems)

	15.4 - Print

--------------------------------------------------------------*/

`/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background-color:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:1px dotted}dfn{font-style:italic}h1{font-size:2em;margin:.67em 0}mark{background:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sup{top:-.5em}sub{bottom:-.25em}img{border:0}svg:not(:root){overflow:hidden}figure{margin:1em 40px}hr{box-sizing:content-box;height:0}pre{overflow:auto}code,kbd,pre,samp{font-family:monospace,monospace;font-size:1em}button,input,optgroup,select,textarea{color:inherit;font:inherit;margin:0}button{overflow:visible}button,select{text-transform:none}button,html input[type=button],input[type=reset],input[type=submit]{-webkit-appearance:button;cursor:pointer}button[disabled],html input[disabled]{cursor:default}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0}input{line-height:normal}input[type=checkbox],input[type=radio]{box-sizing:border-box;padding:0}input[type=number]::-webkit-inner-spin-button,input[type=number]::-webkit-outer-spin-button{height:auto}input[type=search]{-webkit-appearance:textfield;box-sizing:content-box}input[type=search]::-webkit-search-cancel-button,input[type=search]::-webkit-search-decoration{-webkit-appearance:none}fieldset{border:1px solid silver;margin:0 2px;padding:.35em .625em .75em}legend{border:0;padding:0}textarea{overflow:auto}optgroup{font-weight:700}table{border-collapse:collapse;border-spacing:0}td,th{padding:0}html{box-sizing:border-box}*,:after,:before{box-sizing:inherit}body{background:#e9ebed}hr{height:1px;border:0;margin-bottom:1.5em;background-color:#ccc}ol,ul{margin:0 0 1.5em 1em}ul{list-style:disc}ol{list-style:decimal}li>ol,li>ul{margin-bottom:0;margin-left:1em}dt{font-weight:700}dd{margin:0 1.5em 1.5em}table{width:100%;margin:0 0 1.5em}body,button,input,select,textarea{color:#444;font-family:Oxygen,Helvetica Neue,Arial,sans-serif;font-weight:300;line-height:1.5}body{-webkit-overflow-scrolling:touch;text-align:left;margin:0;background-color:#e9ebed}h1,h2,h3,h4,h5,h6{font-weight:inherit;clear:both;margin:0}a{-webkit-transition:color .4s ease;transition:color .4s ease;text-decoration:none;border-bottom:0 solid rgba(69,69,69,0);background-color:transparent}.no-touch a:hover,a{color:#00b0cc}.no-touch a:active{color:#008094}.no-touch .author-site a,.no-touch .categories a,.no-touch .comments-link a,.no-touch .edit-link a,.no-touch .entry-content a,.no-touch .site-colophon a,.no-touch .site-description a,.no-touch .tags a,.no-touch .theme-info a{-webkit-transition:color .4s ease-in-out,border-bottom .4s ease-in-out;transition:color .4s ease-in-out,border-bottom .4s ease-in-out}.no-touch .author-site a:hover,.no-touch .categories a:hover,.no-touch .comments-link a:hover,.no-touch .edit-link a:hover,.no-touch .entry-content a:hover,.no-touch .site-colophon a:hover,.no-touch .site-description a:hover,.no-touch .tags a:hover,.no-touch .theme-info a:hover{border-bottom:1px solid #00b0cc}.no-touch .author-site a:active,.no-touch .categories a:active,.no-touch .comments-link a:active,.no-touch .edit-link a:active,.no-touch .entry-content a:active,.no-touch .site-colophon a:active,.no-touch .site-description a:active,.no-touch .tags a:active,.no-touch .theme-info a:active{border-bottom:1px solid #008094}b,strong{font-weight:700}cite,dfn,em,i{font-style:italic}blockquote{margin:0 1.5em}blockquote:after,blockquote:before,q:after,q:before{content:""}blockquote,q{quotes:"" ""}address{margin:0 0 1.5em}pre{overflow:auto;font-family:Courier\ 10 Pitch,Courier,monospace;line-height:1.6;max-width:100%;padding:1.6em;margin-bottom:1.6em;background:#eee}code,kbd,tt,var{font-family:Monaco,Consolas,Andale Mono,DejaVu Sans Mono,monospace}abbr,acronym{border-bottom:1px dotted #666;cursor:help}ins,mark{text-decoration:none;background:#fff9c0}small{font-size:75%}big{font-size:125%}button,input[type=button],input[type=reset],input[type=submit]{-webkit-transition:border .25s ease-out,color .25s ease-out;transition:border .25s ease-out,color .25s ease-out;color:#00b0cc;min-height:22px;min-height:2rem;padding:0 .7em;border:1px solid silver;border-radius:3px;background:transparent}.no-touch button:hover,.no-touch input[type=button]:hover,.no-touch input[type=reset]:hover,.no-touch input[type=submit]:hover{border:1px solid #00b0cc}.no-touch button:active,.no-touch button:focus,.no-touch input[type=button]:active,.no-touch input[type=button]:focus,.no-touch input[type=reset]:active,.no-touch input[type=reset]:focus,.no-touch input[type=submit]:active,.no-touch input[type=submit]:focus,.touch button:active,.touch button:focus,.touch input[type=button]:active,.touch input[type=button]:focus,.touch input[type=reset]:active,.touch input[type=reset]:focus,.touch input[type=submit]:active,.touch input[type=submit]:focus{color:#008094;border-color:#008094}input[type=email],input[type=password],input[type=search],input[type=tel],input[type=text],input[type=url],textarea{-webkit-transition:border .25s ease-out,color .25s ease-out,background .25s ease-out;transition:border .25s ease-out,color .25s ease-out,background .25s ease-out;color:silver;width:100%;padding:.3em;border:1px solid silver;border-radius:3px;background:hsla(0,0%,100%,0)}input[type=email],input[type=password],input[type=search],input[type=tel],input[type=text],input[type=url]{min-height:22px;min-height:2rem}.no-touch input[type=email]:hover,.no-touch input[type=password]:hover,.no-touch input[type=search]:hover,.no-touch input[type=tel]:hover,.no-touch input[type=text]:hover,.no-touch input[type=url]:hover,.no-touch textarea:hover{color:gray;border-color:gray}.no-touch input[type=email]:focus,.no-touch input[type=password]:focus,.no-touch input[type=search]:focus,.no-touch input[type=tel]:focus,.no-touch input[type=text]:focus,.no-touch input[type=url]:focus,.no-touch textarea:focus,.touch input[type=email]:focus,.touch input[type=password]:focus,.touch input[type=search]:focus,.touch input[type=tel]:focus,.touch input[type=text]:focus,.touch input[type=url]:focus,.touch textarea:focus{color:#444;border-color:#00b0cc;outline:none}input[type=search]{-webkit-appearance:none;box-sizing:border-box}body .screen-reader-text{overflow:hidden;clip:rect(0 0 0 0);position:absolute;width:1px;height:1px;padding:0;border:0;margin:-1px}body .screen-reader-text:active,body .screen-reader-text:focus,body .screen-reader-text:hover{overflow:visible;clip:auto;position:static;z-index:5;width:auto;height:auto;margin:0}.cf:after,.cf:before{display:table;content:''}.cf:after{clear:both}.comment-content:after,.comment-content:before,.entry-content:after,.entry-content:before,.site-content:after,.site-content:before,.site-footer:after,.site-footer:before,.site-header:after,.site-header:before{display:table;content:''}.comment-content:after,.entry-content:after,.site-content:after,.site-footer:after,.site-header:after{clear:both}.wp-caption{max-width:100%;margin-bottom:1.5em}.wp-caption…```

**Comment by nolsherry** [comment]
@qumorm , please provide the details of the library, such as git repository url or npm package url.

**Comment by nolsherry** [comment]
Closed due to no response in 7 days.
