### ISSUE TITLE
Customize error message from JSV

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9460]
To make the error message much more human readable

**Comment by petrgazarov** [comment]
If this becomes up for grabs, I'd love to work on this 👍

**Comment by PeterDaveHello** [comment]
@petrgazarov I'm good with it if you would like to help :)

**Comment by petrgazarov** [comment]
Cool, I'll let you know if I have any questions!

**Comment by PeterDaveHello** [comment]
@petrgazarov Thank you.

**Comment by petrgazarov** [comment]
Hey @PeterDaveHello, I ran the test against an example file, and it looks pretty readable to me:

```
    jquery
      ✗ jquery package.json is valid
        » jquery is not a valid cdnjs package.json format:
  	  » NPM package.json
  		Array can only contain unique items ([object Object]): /properties/keywords
  		Instance is not a required type (string,object): /properties/author // valid-packages-test.js:86

      ✗ jquery: filename from package.json exists
        » ./ajax/libs/jquery/311/jquery.js does not exist but is referenced in package.json!

      ✗ jquery: must have auto-update config if it has no version specified
        » jquery: must have a valid auto-update config // valid-packages-test.js:134

      ✗ jquery: npmName and npmFileMap should be a pair
        » jquery: npmName and npmFileMap should be a pair // valid-packages-test.js:142
```

Can you please provide an example of what you are looking to achieve? I'm out of ideas. Thanks!

**Comment by PeterDaveHello** [comment]
@petrgazarov I think this part may not be clear enough for guys not familiar with cdnjs:
>  Array can only contain unique items ([object Object]): /properties/keywords
> Instance is not a required type (string,object): /properties/author // valid-packages-test.js:86

The others are not from JSV, we write them in the code.

@ChiWeiHsiao do you remember the error message you got here?

**Comment by ChiWeiHsiao** [comment]
@PeterDaveHello Sorry, I forget. QQ
