### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.5.1/socket.io.js

### ISSUE THREAD

**Issue by EdwardThawne** [cdnjs/cdnjs#9466]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@EdwardThawne , please provide the details of the repository, thanks!

**Comment by kennynaoh** [comment]
Is there any problems here?
Thanks!

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello @extend1994 
What about this issue? What should be done here?

**Comment by PeterDaveHello** [comment]
We should close it as it's meaningless and lack of response :)
