### ISSUE TITLE
[Request] Add capty

### ISSUE THREAD

**Issue by DerayGa** [cdnjs/cdnjs#9474]
**Library name:** 
capty

**Git repository url:**
https://github.com/wbotelhos/capty

**npm package url(optional):** 
N/A

**License(s):**
MIT

**Official homepage:**
https://github.com/wbotelhos/capty

**Wanna say something? Leave message here:**
Love you~

**Comment by pvnr0082t** [comment]
Hi @DerayGa ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

cc @PeterDaveHello

**Comment by pvnr0082t** [comment]
close due to no response.
