### ISSUE TITLE
[Request] jqPuzzle

### ISSUE THREAD

**Issue by markat1** [cdnjs/cdnjs#9475]
jqPuzzle 
jqPuzzle is dual-licensed under the GPL and MIT license
http://www.2meter3.de/jqPuzzle/index.html
Hi - I really need this package ASAP 👍 

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@markat1 please provide the repository info so that we can make sure its popularity

**Comment by maruilian11** [comment]
@markat1 this issue will be closed if there is no response in next 7 days.

**Comment by extend1994** [comment]
the repository seems https://github.com/2m3/jqPuzzle.
Close this issue cause no response and insufficient popularity, cc @PeterDaveHello
