### ISSUE TITLE
[Request] Add tree-grid-directive

### ISSUE THREAD

**Issue by pherng** [cdnjs/cdnjs#9478]
**Library name:** tree-grid-directive
**Git repository url:** https://github.com/khan4019/tree-grid-directive
**npm package url(optional):** $ https://www.npmjs.com/package/angular-bootstrap-grid-tree
**License(s):** MIT license
**Official homepage:** http://khan4019.github.io/tree-grid-directive/test/treeGrid.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@emmy41124 Please take this.
