### ISSUE TITLE
[Request] Add numeral js languages

### ISSUE THREAD

**Issue by oliviermattei** [cdnjs/cdnjs#9479]
**Library name: numeral js languages** 
**Git repository url: https://github.com/adamwdraper/Numeral-js **
**npm package url(optional): numeral** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

Library is on cdnjs, no locales files.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @oliviermattei 
This library is already exist on cdnjs https://cdnjs.com/libraries/numeral.js
Any problems here?
Thanks!

**Comment by PeterDaveHello** [comment]
@kennynaoh  ...
> Library is on cdnjs, no locales files.

**Comment by PeterDaveHello** [comment]
@kennynaoh any schedule to fix this? As title said, just need to add numeral js language files.

**Comment by kennynaoh** [comment]
@PeterDaveHello I got it, thank you!

**Comment by oliviermattei** [comment]
Nice, thank you ;)
