### ISSUE TITLE
[Request] Add angular-numeric-directive

### ISSUE THREAD

**Issue by kkorus** [cdnjs/cdnjs#9481]
**angular-numeric-directive** 
**https://github.com/epeschier/angular-numeric-directive**
**https://www.npmjs.com/package/angular-numeric-directive** 
**MIT**
**https://github.com/epeschier/angular-numeric-directive**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @kkorus ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
close due to no response
cc @PeterDaveHello
