### ISSUE TITLE
[Request] Add recentpostswiththumbnailsv3

### ISSUE THREAD

**Issue by phuein** [cdnjs/cdnjs#9482]
**Library name:** recentpostswiththumbnailsv3
**Git repository url:** http://tavristasos.googlecode.com/svn-history/r100/trunk/recentpostswiththumbnailsv3.js (original address - now defunct and neglected.)
**npm package url(optional):** 
**License(s):** Was posted publicly without license, so assume public.
**Official homepage:** http://tavristasos.googlecode.com (dead)
**Wanna say something? Leave message here:** As evident, the creator has neglected this project. The script is very useful for Blogger.com users, so it makes sense to share it publicly. It works well, and I've used it for years. The two files of the library, working together, are on my github:
https://github.com/phuein/assafkoss-com/blob/master/recentpostswiththumbnailsv3.js
https://github.com/phuein/assafkoss-com/blob/master/recentpostticker.js

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
