### ISSUE TITLE
[Request] pagination.js

### ISSUE THREAD

**Issue by pmwalsh** [cdnjs/cdnjs#9483]
**Library name: pagination.js**
**Git repository url: https://github.com/superRaytin/paginationjs**
**npm package url(optional):** 
**License(s):**
**Official homepage: http://paginationjs.com/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pmwalsh** [comment]
Hello, I'm curious what to expect in terms of process for the requested library getting added to CDNJS? 1 month? 6 months? more? Thanks!

**Comment by PeterDaveHello** [comment]
@pmwalsh we'll host this before the end of 2016, there are too many requests lol ...

**Comment by pmwalsh** [comment]
Thank you, I appreciate your help. Your site is amazing.

**Comment by PeterDaveHello** [comment]
@pmwalsh you're welcome, feel free to share with others :)
