### ISSUE TITLE
[Request] Add jquery-validation localization

### ISSUE THREAD

**Issue by ctj1731** [cdnjs/cdnjs#9491]
Library name:  jquery-validation
Git repository url: https://github.com/jzaefferer/jquery-validation/tree/master/src/localization

The jquery-validate library has already in cdnjs, but the localization is not.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@ctj1731 thanks for your report, we'll take a look at it!
