### ISSUE TITLE
[Request] Add NumScroller 

### ISSUE THREAD

**Issue by Igcorreia** [cdnjs/cdnjs#9492]
**Library name:** NumScroller
**Git repository url:** https://github.com/tinywall/numscroller
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

http://demo.tinywall.net/numscroller/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @Igcorreia 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by Piicksarn** [comment]
**The issue will be closed if it has no response in 7 days.**

**Comment by kennynaoh** [comment]
close due to no response.
