### ISSUE TITLE
[Request] Add angular-numeraljs

### ISSUE THREAD

**Issue by isopov** [cdnjs/cdnjs#9493]
**Library name:** angular-numeraljs
**Git repository url:** https://github.com/baumandm/angular-numeraljs
**npm package url(optional):**  https://www.npmjs.com/package/angular-numeraljs
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

"3,053 downloads in the last month" - I think only two were from me :-)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@emmy41124 Please take this.
