### ISSUE TITLE
[Request] Add animatedModal.js 

### ISSUE THREAD

**Issue by vertisan** [cdnjs/cdnjs#9494]
**Library name:** animatedModal.js
**Git repository url:** https://github.com/joaopereirawd/animatedModal.js
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** http://joaopereirawd.github.io/animatedModal.js/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
close due to duplicate issue with https://github.com/cdnjs/cdnjs/issues/8385, thanks!

cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
This one is much more clear.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
