### ISSUE TITLE
Update autotrack.js to 1.1.0

### ISSUE THREAD

**Issue by kmplngj** [cdnjs/cdnjs#9495]
My headline says it all.

Thanks a lot

**Comment by PeterDaveHello** [comment]
@kmplngj I think its author forget to publish on npm, I'll transfer to use git auto-update on this lib, thanks for your report!

**Comment by PeterDaveHello** [comment]
@kmplngj this update will be available on cdnjs.com & cdnjs.cloudflare.com about 10 later, thanks!
