### ISSUE TITLE
[Request] Flagstrap

### ISSUE THREAD

**Issue by DmonteiroD** [cdnjs/cdnjs#9497]
**Library name:**  flagstrap
**Git repository url:** https://github.com/blazeworx/flagstrap
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://blazeworx.github.io/flagstrap/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @DmonteiroD 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by Piicksarn** [comment]
**The issue will be closed if it has no response in 7 days.**

**Comment by kennynaoh** [comment]
close due to no response.

**Comment by PeterDaveHello** [comment]
Let's try to contact the author and see if we could have correct version tag, then we could add this.

**Comment by kennynaoh** [comment]
I have sent a PR to add this library because it has correct version tag on git repo.
