### ISSUE TITLE
antd use a iconfont and it's font file is not on cdnjs 

### ISSUE THREAD

**Issue by ian4hu** [cdnjs/cdnjs#9500]
As [antd's document said](https://github.com/ant-design/antd-init/tree/7c1a33cadb98f2fd8688fe527dd7f98215b9bced/examples/local-iconfont), it use a iconfont but the iconfont is hosted as `https://at.alicdn.com/t/font_pldm8phsjkathuxr.woff`, could it be hosted on cdnjs?

**Comment by PeterDaveHello** [comment]
@ian4hu if it's free and open source, with a public repo, and valid version number, we could host it.

**Comment by ian4hu** [comment]
Yes, the document mentioned how to host its' iconfont

**Comment by PeterDaveHello** [comment]
@ian4hu Thanks, we'll take a look at it later.

**Comment by PeterDaveHello** [comment]
@cdnjs/intern2 please take a look at this issue, thanks.
