### ISSUE TITLE
[Request] Add angular-countup

### ISSUE THREAD

**Issue by dmitriy-borisov** [cdnjs/cdnjs#9526]
**Library name:** angular-countup
**Git repository url:** https://github.com/dmitriy-borisov/angular-countup
**npm package url(optional):** https://www.npmjs.com/package/angular-countup
**License(s):** MIT

**Comment by kennynaoh** [comment]
Hello @dmitriy-borisov 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by Piicksarn** [comment]
**The issue will be closed due to no response after 7 days.**

**Comment by kennynaoh** [comment]
close due to no response.
