### ISSUE TITLE
[Request] Add mobx-react 

### ISSUE THREAD

**Issue by mohsen1** [cdnjs/cdnjs#9527]
**Library name:** mobx-react
**Git repository url:** https://github.com/mobxjs/mobx-react/
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** https://github.com/mobxjs/mobx-react
**Wanna say something? Leave message here:** We're using it in production. Would be nice to have it on CDN

**Comment by kennynaoh** [comment]
close due to duplicate issue with https://github.com/cdnjs/cdnjs/issues/8309
It's in progress now https://github.com/cdnjs/cdnjs/pull/9550
Thanks for your contribution.
