### ISSUE TITLE
[Request] baffle.js

### ISSUE THREAD

**Issue by k9t9** [cdnjs/cdnjs#9529]
**Library name:**  baffle.js
**Git repository url:** https://github.com/camwiegert/baffle
**npm package url(optional):**  https://www.npmjs.com/package/baffle
**License(s):**  MIT
**Official homepage:** https://camwiegert.github.io/baffle/

A tiny (~1.8kb) javascript library for obfuscating and revealing text in DOM elements.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
@PeterDaveHello @cdnjs/intern2 could you assign this request to me? thanks!
