### ISSUE TITLE
Update MDBootstrap to 4.2.0

### ISSUE THREAD

**Issue by mattonit** [cdnjs/cdnjs#9531]
Recently, we released MDBootstrap 4.2.0. Our customers ask for MDB 4.2.0 on cdnjs. Could you please update MDBootstrap to 4.2.0?

Github repo: https://github.com/mdbootstrap/bootstrap-material-design

**Comment by PeterDaveHello** [comment]
@pvnr0082t could you take a look at the possibility to transfer to git auto-update? Thanks.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Of course.

**Comment by PeterDaveHello** [comment]
added in 0350979 by bot since npm package released.
