### ISSUE TITLE
[Request] Add Map Icons

### ISSUE THREAD

**Issue by kevindb** [cdnjs/cdnjs#9539]
**Library name:** Map Icons
**Library desctiption:** An icon font for use with Google Maps API and Google Places API using SVG markers and icon labels
**Git repository url:** https://github.com/scottdejonge/map-icons
**License(s):** Code: [MIT](http://opensource.org/licenses/mit-license.html), Fonts: [SIL OFL 1.1](http://scripts.sil.org/OFL)
**Official homepage:** http://map-icons.com/

**Comment by sashberd** [comment]
@sufuf3 This library is deprecated and not in use any more. I suggest not to host it

**Comment by sufuf3** [comment]
@sashberd I think this lib is still good to host.
Because the good file structure, release versions and enough popularity.
Also the latest commit is on 3 Jul.

What do you think?
Thanks for your great work and contribution.

**Comment by sashberd** [comment]
@sufuf3 
I disagree. As developer I will never use deprecated library in my work. So why we need to host something that download rates of it will be zeroed and spent place for it on hosting
@PeterDaveHello However, for your consideration.

**Comment by sufuf3** [comment]
I think many developers as the same with your mind would like to use useful library not to use the deprecated library.
But sometimes, some people maybe meet some problem which be depended on the situation.
In that circumstances, they have to choose the deprecated library.
This is a bad news, but this can be occurred.

Any way, let's wait for @PeterDaveHello decision.

Thank you @sashberd

**Comment by MattIPv4** [comment]
Library no longer maintained, no further requests here for it. Closing.
