### ISSUE TITLE
[Request] Add redux-promise-middleware 

### ISSUE THREAD

**Issue by notgiorgi** [cdnjs/cdnjs#9544]
**Library name:** redux-promise-middleware
**Git repository url:https://github.com/pburtchaell/redux-promise-middleware**
**npm package url(optional):https://www.npmjs.com/package/redux-promise-middleware** 
**License(s):https://github.com/pburtchaell/redux-promise-middleware/blob/master/LICENSE**
**Official homepage: https://github.com/pburtchaell/redux-promise-middleware**

**Comment by PeterDaveHello** [comment]
Not good to add anymore?

**Comment by PeterDaveHello** [comment]
Here we go: https://cdnjs.com/libraries/redux-promise-middleware
