### ISSUE TITLE
[Request] Add noopener.js

### ISSUE THREAD

**Issue by XmlmXmlmX** [cdnjs/cdnjs#9545]
**Library name:** noopener.js
**Git repository url:** https://github.com/XmlmXmlmX/noopener.js
**npm package url(optional):** https://www.npmjs.com/package/noopener-js
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @XmlmXmlmX 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by XmlmXmlmX** [comment]
Ok, understand.

**Comment by Piicksarn** [comment]
**The issue will be closed due to if it has no progress in 7 days.**
Thanks.

**Comment by kennynaoh** [comment]
close due to not enough popularity.
cc @PeterDaveHello
