### ISSUE TITLE
[Request] Add vue-count-up

### ISSUE THREAD

**Issue by mimani** [cdnjs/cdnjs#9554]
**Library name:** 
vue-count-up

**Git repository url:**
https://github.com/samcrosoft/vue-countup

**npm package url(optional):** 
https://www.npmjs.com/package/vue-countup

**License(s):**
MIT

**Official homepage:**
https://www.npmjs.com/package/vue-countup

**Comment by Piicksarn** [comment]
Hi @mimani  :
There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for more detail.
Would you mind to open a new issue again when it comes to be notable popularity? :grinning: 
Thanks for your request! 

***`The issue will be closed if it has no response in 7 days.`***

Piicksarn.

**Comment by Piicksarn** [comment]
**Closed due to no response.**
