### ISSUE TITLE
[Request] Add jquery.interactive_bg.js 

### ISSUE THREAD

**Issue by LukeXF** [cdnjs/cdnjs#9555]
**Library name:** jquery.interactive_bg.js
**Git repository url:** https://github.com/peachananr/interactive_bg
**npm package url(optional):** 
**License(s):** GNU GENERAL PUBLIC LICENSE
**Official homepage:** http://www.thepetedesign.com/demos/interactive_bg_demo.html
**Wanna say something? Leave message here:** Would be awesome to see the min and standard js file added. It provides interactive backgrounds for websites.

**Comment by LukeXF** [comment]
Any progress?

**Comment by maruilian11** [comment]
@LukeXF Sorry for keeping you waiting for a long time. I will send a PR to add it later.

**Comment by maruilian11** [comment]
We need to confirm the current version number first, let's wait for one week first. And we can consider move on. 😃

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
