### ISSUE TITLE
[Request] Add Event Control Library

### ISSUE THREAD

**Issue by civcastillo** [cdnjs/cdnjs#9561]
**Library name: Event Control** 
**Git repository url: https://github.com/krig/eventcontrol**
**npm package url(optional):** 
**License(s):**
**Official homepage: https://github.com/krig/eventcontrol**
**Wanna say something? Leave message here: Slim and smart javascript library to handle and display time events**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @civcastillo 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
close due to no response
cc @PeterDaveHello
