### ISSUE TITLE
[Request] jquery.localize.js

### ISSUE THREAD

**Issue by air720boarder** [cdnjs/cdnjs#9563]
**Library name: Jquery Localize
**Git repository url: https://github.com/coderifous/jquery-localize
**npm package url(optional):** https://www.npmjs.com/package/jquery-localize
**License(s): **GPL** and **MIT**
**Official homepage: https://github.com/coderifous/jquery-localize
**Wanna say something? Leave message here: It's amazing, please add it!

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by NiniHsu** [comment]
coderifous/jquery-localize#91
