### ISSUE TITLE
[Request] Add react-flip-move 

### ISSUE THREAD

**Issue by zuhair-naqvi** [cdnjs/cdnjs#9564]
**Library name:** react-flip-move
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @zuhair-naqvi 
What you mean is this https://github.com/joshwcomeau/react-flip-move?
