### ISSUE TITLE
[Request] jquery-mosaic

### ISSUE THREAD

**Issue by manfuku** [cdnjs/cdnjs#9569]
**Library name:** jquery-mosaic
**Git repository url:** https://github.com/tin-cat/jquery-mosaic
**npm package url(optional):** 
**License(s):** MIT License
**Official homepage:** https://jquery-mosaic.tin.cat/
**Wanna say something? Leave message here:** not the owner but this script is very useful :)

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @manfuku ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by manfuku** [comment]
Hi @pvnr0082t,

Sorry about that. I was able to read it after submission. Thanks for putting it on wait though!

**Comment by pvnr0082t** [comment]
I'm going to close this issue. If you get enough popularity, feel free to reopen it. @manfuku Thanks for your contribution.
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Hi @manfuku @pvnr0082t 

I just took a look at this lib, I think it's worth to host it :)

**Comment by manfuku** [comment]
that's great news!!
