### ISSUE TITLE
Update auto-update document about how to exclude file type in glob

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9570]
`"**/*"` in auto-update example is for all the files recursively, should add more examples about how to exclude file type like `*.flow`, `*.scss`

**Comment by PeterDaveHello** [comment]
@cdnjs/intern @cdnjs/intern2 you can take a look and do something on it

**Comment by maruilian11** [comment]
how about `**/*.!(flow|scss)`?
