### ISSUE TITLE
[Request] Heatmap: Yandex.Maps API plugin

### ISSUE THREAD

**Issue by alt-j** [cdnjs/cdnjs#9573]
**Library name: Heatmap: Yandex.Maps API plugin for data visualization** 
**Git repository url: https://github.com/yandex/mapsapi-heatmap**
**npm package url(optional):** 
**License(s): BSD-2-Clause**
**Official homepage: https://github.com/yandex/mapsapi-heatmap/blob/master/README.md**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @alt-j ,
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our README.md for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by kennynaoh** [comment]
close due to no response
cc @PeterDaveHello
