### ISSUE TITLE
[Request] Add mocha.css 

### ISSUE THREAD

**Issue by Anomnimel** [cdnjs/cdnjs#9578]
**Library name:** mocha.css
**Git repository url:** https://github.com/mochajs/mocha/blob/master/mocha.css
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@Anomnimel 
This library has been added in cdnjs.
Thanks for your suggestion.
