### ISSUE TITLE
[Request] Add nano scr 

### ISSUE THREAD

**Issue by ksp9241** [cdnjs/cdnjs#9586]
**Library name:** nano scr
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@ksp9241 any detail here? thanks

**Comment by pvnr0082t** [comment]
close due to no response.
