### ISSUE TITLE
[Request] Add Stackable.js 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9589]
**Library name:** Stackable.js
**Git repository url:** https://github.com/johnpolacek/stacktable.js/
**npm package url(optional):** 
**License(s):** MIT+GPL
**Official homepage:** https://johnpolacek.github.io/stacktable.js/

**Comment by sufuf3** [comment]
Duplicate with #9486
PR: #11472

**Comment by PeterDaveHello** [comment]
Close pr #9486
