### ISSUE TITLE
[Request] Add jquery-nice-select 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9592]
**Library name:** jquery-nice-select
**Git repository url:** https://github.com/hernansartorio/jquery-nice-select
**Official homepage:** http://hernansartorio.com/jquery-nice-select/

Need to confirm its license before going to host it.

**Comment by extend1994** [comment]
License contradiction issue: https://github.com/hernansartorio/jquery-nice-select/issues/31

**Comment by PeterDaveHello** [comment]
Moved back to #9988
