### ISSUE TITLE
[Request] Add gibberish-aes

### ISSUE THREAD

**Issue by Nickitee** [cdnjs/cdnjs#9603]
**Library name:** Gibberish AES
**Git repository url:** https://github.com/mdp/gibberish-aes
**npm package url(optional):**  https://www.npmjs.com/package/gibberish-aes
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
duplicated with #8741. I'm going to close this issue. @Nickitee Thanks for your contribution.
