### ISSUE TITLE
[Request] Add palette.js 

### ISSUE THREAD

**Issue by dado0583** [cdnjs/cdnjs#9605]
**Library name:** palette.js
**Git repository url:** https://github.com/google/palette.js/tree/master
**npm package url(optional):** 
**License(s):** Apache License, Version 2.0
**Official homepage:** https://github.com/google/palette.js
**Wanna say something? Leave message here:** JS for producing colour schemes (e.g. colour-blind friendly palettes)

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Added in https://github.com/cdnjs/cdnjs/pull/13777
