### ISSUE TITLE
[Request] redux-undo

### ISSUE THREAD

**Issue by ghost** [cdnjs/cdnjs#9611]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by x09326** [comment]
@sebastianlee20 
Any details like Git url?

**Comment by pvnr0082t** [comment]
I think we can add https://github.com/omnidan/redux-undo.

**Comment by sashberd** [comment]
@PeterDaveHello I think this library can not be used via WEB. Suggest to close

**Comment by PeterDaveHello** [comment]
Thanks @sashberd
