### ISSUE TITLE
Update auto-update config of flatpickr

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9629]
The structure changed since v2.0.9, `src` and `dist` almost contain the files with same structure, but the files under `dist` may be even larger than the same one in `src`, we need to figure it out.

**Comment by x09326** [comment]
@PeterDaveHello 
So do we just use `dist` as a `basepath` and remove the `src`?

**Comment by PeterDaveHello** [comment]
@x09326 The content need to be confirmed as I said.

**Comment by x09326** [comment]
How do I confirm that?

**Comment by PeterDaveHello** [comment]
Confirm with author?

**Comment by x09326** [comment]
@PeterDaveHello 
The author say that we can just host the files in `dist` and abandon the files in `src`.

**Comment by PeterDaveHello** [comment]
@x09326 nice, PR on the way?
