### ISSUE TITLE
[Request] Balloon.css (version update)

### ISSUE THREAD

**Issue by kazzkiq** [cdnjs/cdnjs#9633]
**Library name:** Balloon.css
**Git repository url:** https://github.com/kazzkiq/balloon.css
**npm package url(optional):** https://www.npmjs.com/package/balloon-css
**License(s):** MIT
**Official homepage:** https://kazzkiq.github.io/balloon.css/
**Wanna say something? Leave message here:** Just update version (from `0.3.0` to `0.4.0`).

**Comment by Piicksarn** [comment]
@kazzkiq ✨ 
Would you mind to add git tags for the lib?
We're able to use git tags for git autoupdate.

**Comment by kazzkiq** [comment]
@Piicksarn Sure! Just issued a new Tag, from now on will be creating them on version changes.

You can access them **[here](https://github.com/kazzkiq/balloon.css/releases/tag/v0.4.0)**.

If you need any other configuration to make the autoupdate happen for Balloon.css, please let me know. 👍

**Comment by PeterDaveHello** [comment]
Didn't the bot add it ?

> * 58dd011 Add balloon-css v0.4.0 PeterBot 7 hours ago

**Comment by PeterDaveHello** [comment]
We are using npm auto-update here but not git, any the version seem to be added on time.

**Comment by kazzkiq** [comment]
@PeterDaveHello It worked!

So just to clarify to prevent further Issues opened without need, every time I update the npm version, CDNJS will update the package automatically?

**Comment by PeterDaveHello** [comment]
@kazzkiq correct, the delay usually be within 15 mins.

**Comment by kazzkiq** [comment]
Perfect. Thanks!
