### ISSUE TITLE
amcharts, ammaps, amstockchart - upgrade to v3.20.17

### ISSUE THREAD

**Issue by zdm** [cdnjs/cdnjs#9644]
Please, upgrade libs in the subject to the latest versions.
https://www.amcharts.com/download/

**Comment by PeterDaveHello** [comment]
@pvnr0082t looks like there is an existing PR #5747 for the lib, we need to help solve that first before sending new one unless there is no any more response.

**Comment by PeterDaveHello** [comment]
move to #5337
