### ISSUE TITLE
[Request] Add icomoon 

### ISSUE THREAD

**Issue by way2rach** [cdnjs/cdnjs#9649]
**Library name:** icomoon
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage: https://icomoon.io/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@pvnr0082t let's spend some time on reviewing issues.

**Comment by sashberd** [comment]
@PeterDaveHello Looks like there is no official git for this specific lib. Suggest to close it
