### ISSUE TITLE
[Request] Add nuka-carousel React Carousel Component

### ISSUE THREAD

**Issue by danielattig** [cdnjs/cdnjs#9662]
**Library name:** nuka-carousel
**Git repository url:** https://github.com/FormidableLabs/nuka-carousel
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://kenwheeler.github.io/nuka-carousel/#/
**Wanna say something? Leave message here:** Thank you for your consideration. You guys are awesome!

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
According to https://github.com/FormidableLabs/nuka-carousel/issues/295 and https://github.com/FormidableLabs/nuka-carousel/issues/268  can not be hosted on cdnjs
Suggest to close
