### ISSUE TITLE
[Request] Add karpathy/convnetjs

### ISSUE THREAD

**Issue by maramal** [cdnjs/cdnjs#9664]
**Library name:** karpathy/convnetjs
**Git repository url:** https://github.com/karpathy/convnetjs
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://cs.stanford.edu/people/karpathy/convnetjs
**Wanna say something? Leave message here:** Neural Networks for browser / nodejs

**Comment by sufuf3** [comment]
Duplicated with #9165
