### ISSUE TITLE
[Request] @blueprintjs/core

### ISSUE THREAD

**Issue by larshp** [cdnjs/cdnjs#9667]
**Library name:** Blueprint
**Git repository url:** https://github.com/palantir/blueprint
**npm package url(optional):**  @blueprintjs/core
**License(s):** Apache-2.0
**Official homepage:** http://blueprintjs.com/
**Wanna say something? Leave message here:**
also consider adding @blueprintjs/datetime + @blueprintjs/table

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@larshp I am going to add files under `docs`, do I miss any file you need? Thanks!

**Comment by larshp** [comment]
I think it is okay, I'll create a new issue if I find anything missing

**Comment by PeterDaveHello** [comment]
Why to add docs? We don't need docs.

**Comment by PeterDaveHello** [comment]
@giladgray @llorca would you guys like help confirm what are the files should be hosted on the CDN? All the files under `dist` folder in the npm package? Many thanks!

**Comment by giladgray** [comment]
`dist` and `resources` should do it. the css file references an icon font that lives in `resources`.

**Comment by PeterDaveHello** [comment]
@giladgray, thanks, btw, is it possible to provide minified files or bundled files? I can see `blueprint.css` but no `blueprint.js`, just wonder if we could bundle the js files? Thanks.

**Comment by PeterDaveHello** [comment]
@maruilian11 I don't even finished the confirmation works, why are you so hurry to send a PR to close this issue which is not assigned to you?

**Comment by maruilian11** [comment]
sorry, I will wait for the confirmation work finishing.
