### ISSUE TITLE
[Request] Add isotope-layout

### ISSUE THREAD

**Issue by qpongo** [cdnjs/cdnjs#9672]
**Library name:** isotope-layout
**Git repository url:** https://github.com/metafizzy/isotope
**npm package url(optional):** https://www.npmjs.com/package/isotope-layout
**License(s):** GNU GPL license v3
**Official homepage:** http://isotope.metafizzy.co/
**Wanna say something? Leave message here:**
Here's the link to the developer's latest on another CDN (https://unpkg.com/isotope-layout@3.0.1/dist/isotope.pkgd.min.js) but YSlow complains that my page is not referencing from a cookie-free CDN...  10k dls per month on this one so it's fairly popular.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by desandro** [comment]
The npm module `isotope-layout` is already available as [jquery.isotope](https://cdnjs.com/libraries/jquery.isotope)

**Comment by PeterDaveHello** [comment]
As @desandro says, it's already on there but just different name :)
