### ISSUE TITLE
[Request] confront

### ISSUE THREAD

**Issue by zorzysty** [cdnjs/cdnjs#9674]
Note: If you'd like to request a new library, please follow this link: https://cdnjs.com/request-new-lib

**Comment by Piicksarn** [comment]
@zorzysty, u mean this library? 👉 [confront](https://www.npmjs.com/package/confront)

**Comment by zorzysty** [comment]
Yes, exactly

**Comment by pvnr0082t** [comment]
Hi @zorzysty  ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by sufuf3** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days. cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@zorzysty if you'd like to send a pull request to add it, we can help you to do that.

**Comment by zorzysty** [comment]
@PeterDaveHello Thx. I'll get back to you if and when I get the required popularity.

**Comment by PeterDaveHello** [comment]
@zorzysty I mean if can send it now, no worry about the popularity :)
