### ISSUE TITLE
drecss

### ISSUE THREAD

**Issue by andrebc52** [cdnjs/cdnjs#9690]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Any details here? Thanks.

**Comment by Piicksarn** [comment]
@andrebc52, we need more detail about the library!
ex: Git repository url or npm package url

**Comment by Piicksarn** [comment]
***`The issue will be closed if it has no response in 7 days.`***

**Comment by maruilian11** [comment]
close due to no reponse.
