### ISSUE TITLE
Pixi.js not updated

### ISSUE THREAD

**Issue by Yennick** [cdnjs/cdnjs#9699]
The library pixi.js isn't auto-updated anymore/yet. The cdnjs version is stuck at 4.1.1 while pixi.js 4.2.1 and 4.2.2 are released 4 days ago.

I could make a custom pull request, or could i help in another way?

@PeterDaveHello  ( @PeterBot )

**Comment by PeterDaveHello** [comment]
@Yennick Let me take a quick check first, thanks for your report!

**Comment by PeterDaveHello** [comment]
@Yennick I think they may changed the file structure on npm package, would you like to help us update it? Thanks.
