### ISSUE TITLE
[Request] Add dflow

### ISSUE THREAD

**Issue by fibo** [cdnjs/cdnjs#9706]
**Library name:** dflow
**Git repository url:** https://github.com/fibo/dflow.git
**npm package url(optional):** dflow
**License(s):** MIT
**Official homepage:** http://g14n.info/dflow
**Wanna say something? Leave message here:** is a minimal Dataflow programming engine

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by fibo** [comment]
Hope the following is written correctly

多謝

means "thank you", right?

**Comment by PeterDaveHello** [comment]
@fibo Perfect

**Comment by fibo** [comment]
Gteat, cause I added It to dflow readme to thank you, but I cannot read It. Ciaooo

**Comment by PeterDaveHello** [comment]
@fibo no worry and thanks for your kindness, I think English is good enough, amazed to see you use Chinese 💯

**Comment by PeterDaveHello** [comment]
@fibo btw, would you like to have a CDNJS badge like https://github.com/selectize/selectize.js/blob/master/README.md to help you track the latest version on CDNJS? No pressure at all.

**Comment by fibo** [comment]
It Is already in the Readme
