### ISSUE TITLE
[Request] Add woocommerce

### ISSUE THREAD

**Issue by crafterno1** [cdnjs/cdnjs#9709]
Library name:woocommerce/woocommerce 
Git repository url:https://github.com/woocommerce/woocommerce
npm package url(optional): 
License(s):
Official homepage:https://woocommerce.com/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @crafterno1, I want to confirm what files should be hosted on cdnjs? Thank you!

**Comment by crafterno1** [comment]
Hello @maruilian11 
I'm very sorry for late reply.
It would be nice if all files and folders under woocommerce/assets/ were hosted.
However, if I have to choose some of them, these files are my suggestion.

woocommerce/assets/js/frontend/add-payment-method.min.js
woocommerce/assets/js/frontend/add-to-cart-variation.min.js
woocommerce/assets/js/frontend/add-to-cart.min.js
woocommerce/assets/js/frontend/address-i18n.min.js
woocommerce/assets/js/frontend/cart-fragments.min.js
woocommerce/assets/js/frontend/cart.min.js
woocommerce/assets/js/frontend/checkout.min.js
woocommerce/assets/js/frontend/country-select.min.js
woocommerce/assets/js/frontend/credit-card-form.min.js
woocommerce/assets/js/frontend/geolocation.min.js
woocommerce/assets/js/frontend/lost-password.min.js
woocommerce/assets/js/frontend/password-strength-meter.min.js
woocommerce/assets/js/frontend/price-slider.min.js
woocommerce/assets/js/frontend/single-product.min.js
woocommerce/assets/js/frontend/tokenization-form.min.js
woocommerce/assets/js/frontend/woocommerce.min.js
woocommerce/assets/js/select2/select2.min.js
woocommerce/assets/js/jquery-cookie/jquery.cookie.min.js
woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js

woocommerce/assets/fonts/WooCommerce.woff
woocommerce/assets/fonts/star.woff

woocommerce/assets/css/woocommerce-layout.css
woocommerce/assets/css/woocommerce.css
woocommerce/assets/css/woocommerce-smallscreen.css
woocommerce/assets/css/select2.css

Thank you.

**Comment by maruilian11** [comment]
@crafterno1 Thank you for your detailed and helpful reply! I will add it asap!

**Comment by maruilian11** [comment]
@PeterDaveHello since woocommerce is a tool to build online platform, can we host all its assets, rather than not adding the assets belong to other lib.

**Comment by maruilian11** [comment]
ping @PeterDaveHello

**Comment by PeterDaveHello** [comment]
Unless woocommerce guys are happy with this and would like to help, we'll not host this one as it's a frontend library.

**Comment by dakshshah96** [comment]
@PeterDaveHello Close this issue maybe?

**Comment by PeterDaveHello** [comment]
Close due to no response.
