### ISSUE TITLE
[Request] Add ng-inline-edit 

### ISSUE THREAD

**Issue by robdefeo** [cdnjs/cdnjs#9710]
**Library name:** ng-inline-edit
**Git repository url:**
https://github.com/tameraydin/ng-inline-edit
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @rdefeo  :

There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for more detail.

Would you mind to open a new issue again when it comes to be notable popularity? :grinning: 
Thanks for your request! 

***`The issue will be closed if it has no response in 7 days.`***

Piicksarn.

**Comment by maruilian11** [comment]
I think this lib popularity is close to our request.
