### ISSUE TITLE
[Request] Add purejs-onepage-scroll

### ISSUE THREAD

**Issue by FabianGabor** [cdnjs/cdnjs#9714]
**Library name:**purejs-onepage-scroll
**Git repository url:**https://github.com/peachananr/purejs-onepage-scroll.git
**npm package url(optional):** 
**License(s):**Attribution-ShareAlike 4.0 International
**Official homepage:**http://www.thepetedesign.com/demos/purejs_onepage_scroll_demo.html
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@extend1994  @PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
Since it's popular enough, I suggest take this commit: https://github.com/peachananr/purejs-onepage-scroll/commit/3c6cde24a67aa4df1fff5d45c681f27f9b43f0ea as v1.2.2 (as its code mentions) to manually add this version with additional auto-update config.

**Comment by MattIPv4** [comment]
Hi there,

We are no longer accepting requests for libraries that do not have a way to be automatically updated by our automation.

Our auto-update mechanism requires that either there exists a source repository with versions tagged that contain the required files for the CDN, or a package released on NPM that contains the files needed for the CDN.

You can find out more about our auto-update config structure in the [CONTRIBUTING](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) and [CONTRIBUTING-WIP](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md) documents.
