### ISSUE TITLE
[Request] Add wp-embed.min.js

### ISSUE THREAD

**Issue by extremehex** [cdnjs/cdnjs#9715]
**Library name:** wp-embed.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @extremehex :sparkles: ,
There are some detail in [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) show that : `All new libraries hosted on CDNJS should have an official public repository or npm package`.

Would you please provide official public repository or npm package url?
Thank you!

**Comment by maruilian11** [comment]
hi @extremehex, do you mean this lib?
https://github.com/WordPress/WordPress/blob/master/wp-includes/js/wp-embed.min.js

**Comment by sashberd** [comment]
@maruilian11 The link you provided is not working any more too

**Comment by sufuf3** [comment]
@sashberd Thanks.

Closed due to no response in 7 days. Also I can't find the repo from GitHub and npm.
cc @PeterDaveHello
