### ISSUE TITLE
[Request] Add jquery-endless-scroll 

### ISSUE THREAD

**Issue by Immortalin** [cdnjs/cdnjs#9719]
**Library name:** jquery-endless-scroll
**Git repository url:** https://github.com/fredwu/jquery-endless-scroll/tree/2.0-rewrite/js
**npm package url(optional):** 
**License(s):** MIT/GPL Dual
**Official homepage:** https://fredwu.github.io/jquery-endless-scroll/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
For the dual licenses, is
`"license": [
  "MIT",
  "GPL"
],`
in  `package.json` correct?

**Comment by PeterDaveHello** [comment]
@extend1994 we use "licenses" by now.
