### ISSUE TITLE
[Request] Add amazon-cognito-identity 

### ISSUE THREAD

**Issue by menego** [cdnjs/cdnjs#9725]
**Library name: amazon-cognito-identity-js (amazon-cognito-identity.min.js)** 
**Git repository url: https://github.com/aws/amazon-cognito-identity-js/**
**npm package url(optional):** 
**License(s): Amazon Software License**
**Official homepage: https://aws.amazon.com/cognito/**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @menego, could you please tell me that whether amazon software license is a kind of open source license or give me some suggestion about it?

Thank you :)

**Comment by PeterDaveHello** [comment]
As it's not open source software, and aws should have their own cdn service to host it, we may not host this one.

**Comment by prem911** [comment]
However, jsDelivr is hosting the same
https://cdn.jsdelivr.net/npm/amazon-cognito-identity-js@1.19.0/dist/amazon-cognito-identity.min.js
