### ISSUE TITLE
[Request] Add aws_cognito_sdk

### ISSUE THREAD

**Issue by menego** [cdnjs/cdnjs#9727]
**Library name:amazon-cognito-identity-js (aws-cognito-sdk.min.js)** 
**Git repository url: https://github.com/aws/amazon-cognito-identity-js/**
**npm package url(optional):** 
**License(s):Amazon Software License**
**Official homepage: https://aws.amazon.com/cognito/**
**Wanna say something? Leave message here:**
this library is composed by aws-cognito-sdk.min.js and amazon-cognito-identity.min.js bith in the 'dist' directory.
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@menego, you mean this library? :point_right: https://www.npmjs.com/package/amazon-cognito-js
Or it just duplicate with https://github.com/cdnjs/cdnjs/issues/9726 ?

**Comment by menego** [comment]
Hi @Piicksarn the library you mentioned is for the cognito sync features (offline synchronization), the two library requests I made (#9725 and #9727) are for the 2 files that together create the cognito sdk for javascript (node but most importantly web browsers). Probably I should have done one single Request for both files since it is the same library.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained, closing.
