### ISSUE TITLE
blueimp-load-image 2.9.0 missing file

### ISSUE THREAD

**Issue by tyrex1975** [cdnjs/cdnjs#9728]
Hi - the latest version of blueimp's load-image library is missing the following file: load-image.all.min.js

https://cdnjs.com/libraries/blueimp-load-image/2.9.0

It was present in most previous versions.

Thank you.

**Comment by maruilian11** [comment]
Hi @blueimp,
could you please also consider adding `load-image.all.min.js` on npm package? Thank you very much!

**Comment by blueimp** [comment]
@tyrex1975 @maruilian11 
I've re-added the combined and minified file in version 2.10.0.

**Comment by maruilian11** [comment]
@blueimp thanks a lot!
@tyrex1975 I will manually add  `load-image.all.min.js` and `load-image.all.min.js.map` for old versions on cdnjs.

**Comment by maruilian11** [comment]
2.10.0 is available https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.10.0/load-image.all.min.js

**Comment by tyrex1975** [comment]
Thank you @blueimp & @maruilian11 :-)
