### ISSUE TITLE
[Request] Add tosrus 

### ISSUE THREAD

**Issue by ifightcode** [cdnjs/cdnjs#9730]
**Library name:** tosrus
**Git repository url:** https://github.com/FrDH/jQuery.TosRUs
**Official homepage:** http://tosrus.frebsite.nl/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by MattIPv4** [comment]
Request links to a 4040, closing.
