### ISSUE TITLE
[Request] Add bootstrap-datetimepicker

### ISSUE THREAD

**Issue by ivanhalen** [cdnjs/cdnjs#9736]
**Library name:** bootstrap-datetimepicker
**Git repository url:** https://github.com/smalot/bootstrap-datetimepicker
**npm package url(optional):** 
**License(s):** https://github.com/smalot/bootstrap-datetimepicker/blob/master/LICENSE
**Official homepage:** http://www.malot.fr/bootstrap-datetimepicker/index.php
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @ivanhalen , it seems like that this library has existed in [cdnjs](https://cdnjs.com/libraries/smalot-bootstrap-datetimepicker). Is that you request to add?

**Comment by ivanhalen** [comment]
Oh my, sorry! I totally missed this :-(

**Comment by extend1994** [comment]
Close the issue because the request library has existed in cdnjs.

**Comment by PeterDaveHello** [comment]
@extend1994 just reminder, make sure everything especially version, license, homepage info is up-to-date before closing this kind of request :+1:
