### ISSUE TITLE
[Request] Add check-browsers

### ISSUE THREAD

**Issue by perfectacle** [cdnjs/cdnjs#9737]
**Library name: check-browsers
**Git repository url: https://github.com/perfectacle/check-browsers
**npm package url(optional): https://www.npmjs.com/package/check-browsers
**License(s): MIT
**Official homepage: none.
**Wanna say something? Leave message here:**
Check Browsers helps your page styling for each browser.
It is stand alone library.
Thanks.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @perfectacle ,
This library doesn't have notable popularity (100 stars/watchers on GitHub, or more than 500 times download per month on npm stats are both good examples).
You can take a look on our [README](https://github.com/cdnjs/cdnjs/blob/master/README.md) for details :)
The issue will be closed if it has no response in 7 days.

Thanks for your request.

**Comment by extend1994** [comment]
Close the issue because the request library does not have notable popularity and there is no response in 7 days.
