### ISSUE TITLE
[Request] Add expr-eval

### ISSUE THREAD

**Issue by johndoefromhere** [cdnjs/cdnjs#9741]
**Library name:** expr-eval
**Git repository url:** https://github.com/silentmatt/expr-eval
**npm package url(optional):** https://www.npmjs.com/package/expr-eval
**License(s):** MIT
**Official homepage:** https://silentmatt.com/javascript-expression-evaluator/

**Comment by johndoefromhere** [comment]
@PeterDaveHello @pvnr0082t @extend1994 Any updates on this?

**Comment by PeterDaveHello** [comment]
@johndoefromhere will update soon, there are too many issues, if you're in hurry, please consider to send a pull request, thanks.
