### ISSUE TITLE
[Request] Add Themify Icons

### ISSUE THREAD

**Issue by ThanhKhoaIT** [cdnjs/cdnjs#9756]
**Library name:**  Themify Icons
**Git repository url:** https://github.com/lykmapipo/themify-icons 
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://themify.me/themify-icons
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @ThanhKhoaIT,
this library doesn't have notable popularity (100 stars/watchers on GitHub is a  good examples).
You can take a look on our [README](https://github.com/cdnjs/cdnjs/blob/master/README.md) for more details :)
The issue will be closed if it has no response in 7 days.

Thanks for your request.

**Comment by ThanhKhoaIT** [comment]
@extend1994 thank for your comment.
