### ISSUE TITLE
[Request] Add docsify 

### ISSUE THREAD

**Issue by QingWei-Li** [cdnjs/cdnjs#9757]
**Library name:** docsify
**Git repository url:** https://github.com/QingWei-Li/docsify
**npm package url(optional):** https://www.npmjs.com/package/docsify
**License(s):** MIT
**Official homepage:** https://qingwei-li.github.io/docsify/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@Piicksarn did you just label it wrong?

**Comment by Piicksarn** [comment]
@PeterDaveHello, yes, sorry!

**Comment by QingWei-Li** [comment]
Thanks @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@QingWei-Li you are welcome
