### ISSUE TITLE
[Request] Add slatecss 

### ISSUE THREAD

**Issue by thomashare** [cdnjs/cdnjs#9758]
**Library name:** slatecss
**Git repository url:*https://github.com/thomashare/slate.css*
**npm package url(optional):*slatecss* 
**License(s):*MIT*
**Official homepage:*slatecss.com*
**Wanna say something? It's a pretty nice css framework.**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
Hi @thomashare :
There isn't enough notable popularity of the library.
 `(ex: more than 100 stars on GitHub or 500 downloads per month on npm)`
please take a look on our **[README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md)** for more detail.
Would you mind to open a new issue again when it comes to be notable popularity? :grinning: 
Thanks for your request! 

***`The issue will be closed if it has no response in 7 days.`***

Piicksarn.

**Comment by thomashare** [comment]
Yes, I'm sure it will get popular. If you could reopen at that time, that would be great. Thank you

Tommy Hare




On Mon, Nov 28, 2016 at 7:12 AM -0700, "Piicksarn" <notifications@github.com> wrote:












Hi @thomashare :

There isn't enough notable popularity of the library.

(ex: more than 100 stars on GitHub or 500 downloads per month on npm)

please take a look on our README.md for more detail.

Would you mind to open a new issue again when it comes to be notable popularity? 😀

Thanks for your request!


The issue will be closed if it has no response in 7 days.


Piicksarn.

**Comment by PeterDaveHello** [comment]
@Piicksarn you should tag me before close it.

**Comment by PeterDaveHello** [comment]
We'll see if it growth.

**Comment by sashberd** [comment]
@PeterDaveHello The library did not grown since the issue was opened. Suggest to close
