### ISSUE TITLE
[Request] Add survey.js

### ISSUE THREAD

**Issue by klvbdmh** [cdnjs/cdnjs#9771]
**Library name:** survey.js
**Git repository url:** http://github.com/andrewtelnov/surveyjs
**npm package url(optional):** survey-knockout, survey-react
**License(s):** MIT
**Official homepage:** http://surveyjs.org/
**Wanna say something? Leave message here:** Very useful in creating client-side surveys. Although the repo has only 80 stars, combined npm packages downloads per month are well over 500 (295  + 308). There are two npm packages, as survey.js supports two frameworks.

**Comment by kennynaoh** [comment]
@sufuf3 Please take this.

**Comment by qwe19272375** [comment]
@sufuf3 is this issue done? Not sure should label it `in progress` or not.

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello What about this one? Why it is still opened? The lib was added as I understood.

**Comment by PeterDaveHello** [comment]
@sashberd @qwe19272375 nice catch!

@sufuf3 any reason no response here?

**Comment by sufuf3** [comment]
That's my bad. I'm apologize.
The reason maybe that I was learning how to be a member of intern 3, before. 
The PR was be merged on Mar 8. 
I was a new member in that time.

In any case, it's still my fault. I'm sorry.
