### ISSUE TITLE
[Request] Add Aldrich 

### ISSUE THREAD

**Issue by SnorlaxYum** [cdnjs/cdnjs#9774]
I want to use that, thanks!
The font css: https://fonts.googleapis.com/css?family=Aldrich

**Comment by SnorlaxYum** [comment]
The font css: https://fonts.googleapis.com/css?family=Aldrich
The font files r in it.

**Comment by sashberd** [comment]
@PeterDaveHello What is this issue for?

**Comment by PeterDaveHello** [comment]
Seems to ask for Google web font hosting?

**Comment by PeterDaveHello** [comment]
Moved to #7845
