### ISSUE TITLE
[Request] Add Superslides v.0.6.3-wip

### ISSUE THREAD

**Issue by ixlipixli** [cdnjs/cdnjs#9775]
**Library name: Superslides** 
**Git repository url: https://github.com/nicinabox/superslides** 
**npm package url(optional):** 
**License(s):MIT**
**Official homepage: http://archive.nicinabox.com/superslides/#1**
**Wanna say something? Leave message here: Latest version is not online.**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@ixlipixli , the last tag of this library is v.0.6.2.
where is the v.0.6.3-wip tag? 
And we add the last tag of this library is v.0.6.2 which link is https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/superslides 
Thank you.

**Comment by PeterDaveHello** [comment]
wip means working in progress not released version, we don't host that, and also close due to no response.

**Comment by PeterDaveHello** [comment]
@sufuf3 use the url on cdnjs.com instead of GitHub repo next time.
