### ISSUE TITLE
[Request] Add p5.sound.js 

### ISSUE THREAD

**Issue by g4ztop** [cdnjs/cdnjs#9790]
**Library name:** p5.sound.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@g4ztop Is https://github.com/processing/p5.js-sound what you request?

**Comment by g4ztop** [comment]
I'm actually looking for a place that hosts the script online, similarly to
this http://newhive.com/abram/css-pos

**Comment by pvnr0082t** [comment]
@g4ztop So, what do you mean? Could you please give the detail about what you want to request?

**Comment by g4ztop** [comment]
Well my problem is that i cant get AudioIn() to work on chrome while it
works on firefox and internet explorer. And after reading up on why that is
i found that i need an https server and not an http one for it to work, so
i guess i was wondering if it would work when i ran the script off of a
different server and not my own. Similar to what the newhive site seems to
be offering.

**Comment by pvnr0082t** [comment]
@PeterDaveHello Could you please help me take a look at this issue? Thank you.

**Comment by PeterDaveHello** [comment]
No matter https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.4/addons/p5.sound.min.js or https://github.com/processing/p5.js-sound, I didn't see any relation between your problem and CDNJS, if you have problem with a library, please contact with its author, thanks.
