### ISSUE TITLE
[Request] Add videojs-Background

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9815]
**Library name:** videojs-Background
**Git repository url:** https://github.com/matthojo/videojs-Background
**License(s):** MIT

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by abdulamite** [comment]
So I noticed that the link with the url: 

https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library 

is broken, and the other link:

[https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
](url)

simply takes me back to the code page of the github. I was wondering if there are any resources that I can look at in terms of understanding the first steps to contributing a library to the site. I apologize for all the questions, but I am really excited to to be a part of this product, and I want to make sure that I am doing this correctly.

**Comment by sufuf3** [comment]
@abdulamite you could refer to this link -> https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md as well.

If you want to add a new library by a single package.json, the link is https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

Thank you for your contribution.

**Comment by PeterDaveHello** [comment]
Link updated, thanks.
