### ISSUE TITLE
[Request] Add vjs-video 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9829]
**Library name:** vjs-video
**Git repository url:** https://github.com/LonnyGomes/vjs-video
**npm package url(optional):** vjs-video
**License(s):** MIT
**Official homepage:** https://lonnygomes.github.io/vjs-video/

In this issue, we are going to host a new web front-end library on cdnjs, so that web developer can easily use it on our free CDN without additional download/upload process.

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks.

**Comment by nagrawal3** [comment]
@PeterDaveHello I will work on this issue, if no one else is working on this

**Comment by PeterDaveHello** [comment]
@nagrawal3 great! 👍
