### ISSUE TITLE
[Request] Add videojs-record 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9831]
**Library name:** videojs-record
**Git repository url:** https://github.com/collab-project/videojs-record
**npm package url(optional):** videojs-record
**License(s):** MIT 

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by nagrawal3** [comment]
Hi @PeterDaveHello I am interested in working on this issue. I was reading the description and was trying to go to URL mentioned above about the docs for how to add a library, but I didn't find any doc guiding through the process in the first URL, and the second URL is not working. I would really appreciate if you help me find the relevant documents.

**Comment by PeterDaveHello** [comment]
@nagrawal3 sorry that we moved the doc and i now updated the urls, thanks for your report, would you like to take a look again to see if that help? Thanks!

**Comment by nagrawal3** [comment]
@PeterDaveHello thanks for updating the links, that helped in knowing how to proceed.

**Comment by PeterDaveHello** [comment]
@nagrawal3 any news here please? Thanks.

**Comment by nagrawal3** [comment]
@PeterDaveHello I had worked on the other issue, so as it is for the beginner I didn't work on this.

**Comment by sufuf3** [comment]
duplicated with #9827 
move to #9827
cc @PeterDaveHello

**Comment by PeterDaveHello** [comment]
@sufuf3 this is not a normal issue, you should close another one.

**Comment by sufuf3** [comment]
Sorry I will pay more attention next time.
I thought that we should keep earlier issue, and close latest one.
So maybe I have to keep the issue with `beginner` label in this case.
Am I right?
Thank you.

**Comment by PeterDaveHello** [comment]
@sufuf3 not really, we can discuss later, let's focus on the pending PRs first.
