### ISSUE TITLE
[Request] Add _Oimo.js_ 

### ISSUE THREAD

**Issue by codeartisticninja** [cdnjs/cdnjs#9833]
**Library name:** Oimo.js
**Git repository url:** https://github.com/lo-th/Oimo.js
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://lo-th.github.io/Oimo.js/
**Wanna say something? Leave message here:** This seems to be the preferred physics engine for Babylon.js, which you already have in your CDN..

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
related to #5709.

**Comment by maruilian11** [comment]
duplicate with #5709
