### ISSUE TITLE
[Request] Add HumanInput 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9837]
**Library name:** HumanInput
**Git repository url:** https://github.com/liftoff/HumanInput
**License(s):** Apache-2.0

**Comment by nolsherry** [comment]
@emmy41124, please take this.

**Comment by liftoff** [comment]
I have corrected this issue on the HumanInput repo side of things as well as in the NPM repositories.  Let me know if there's anything else holding this up.  Thanks!

**Comment by PeterDaveHello** [comment]
Thanks a lot @liftoff
