### ISSUE TITLE
[Request] Add parametric-svg 

### ISSUE THREAD

**Issue by dicoy** [cdnjs/cdnjs#9841]
**Library name:** parametric-svg
**Git repository url:** https://github.com/parametric-svg/parametric-svg
**npm package url(optional):** https://www.npmjs.com/package/@parametric-svg/element
**License(s):** MIT https://github.com/parametric-svg/parametric-svg/blob/master/packages/spec/License.md
**Official homepage:** http://parametric-svg.js.org/
**Wanna say something? Leave message here:** 
they have it here, but this page is weird and not always loads correctly
https://wzrd.in/standalone/parametric-svg@latest

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @dicoy,
We can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

**Comment by hare1039** [comment]
Feel free to show some other references if you want to discuss more with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response in 7 days. cc @PeterDaveHello
