### ISSUE TITLE
[Request] Add sw-toolbox 

### ISSUE THREAD

**Issue by leonmak** [cdnjs/cdnjs#9843]
**Library name:** sw-toolbox
**Git repository url:** https://github.com/GoogleChrome/sw-toolbox
**npm package url(optional):** 
**License(s):** 
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by extend1994** [comment]
Hi @leonmak !
Could you please tell me which files should be contained in the cdnjs which contains files running on browsers?
For more details, you can check CDNJS [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md).
Thank you!
