### ISSUE TITLE
[Request] Add glUtils.js

### ISSUE THREAD

**Issue by cendechen** [cdnjs/cdnjs#9845]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@cendechen, did you mean 👉 https://www.npmjs.com/package/glutils  ??

**Comment by clairetsai818** [comment]
Hi @cendechen  !
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by clairetsai818** [comment]
close due to no response, cc @PeterDaveHello
