### ISSUE TITLE
[Request] Add google-calendar-events

### ISSUE THREAD

**Issue by Shmasya** [cdnjs/cdnjs#9846]
**Library name:** google-calendar-events
**Git repository url:** https://github.com/mcopley08/google-calendar-events
**npm package url(optional):** https://www.npmjs.com/package/google-calendar-events
**License(s):**
**Official homepage:** https://github.com/mcopley08/google-calendar-events
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
Hi @Shmasya ,

This library doesn't have enough notable popularity(like more than 100 stars on GitHub or 500 downloads per month on npm). please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail, it's always good to read the document before open an issue, I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by pvnr0082t** [comment]
closed and wait for notable popularity. @Shmasya Thanks for your contribution. :+1:
