### ISSUE TITLE
[Request] Add floating.js 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9848]
**Library name:** floating.js
**Git repository url:** https://github.com/Haroenv/floating.js/
**npm package url(optional):** floating.js
**License(s):** Apache-2.0
**Official homepage:** https://haroen.me/floating.js/

In this issue, we are going to host a new web front-end library on cdnjs, so that web developer can easily use it on our free CDN without additional download/upload process, if you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks.

**Comment by hd719** [comment]
Hello I am new to open source can I work on this?

**Comment by PeterDaveHello** [comment]
@hd719 I think @dakshshah96 is working on this right now as you can see above, I think you can pick another BEGINNER issue from here: https://github.com/cdnjs/cdnjs/issues?q=is%3Aopen+label%3ABEGINNER+sort%3Acreated-asc, feel free to ask for help!
