### ISSUE TITLE
[Request] Add Distri.js

### ISSUE THREAD

**Issue by Flarp** [cdnjs/cdnjs#9858]
**Library name:** Distri.js
**Git repository url:** https://github.com/Flarp/Distri-JS
**npm package url(optional):** 
**License(s):** BSD 3 Clause
**Official homepage:** [distri.js.org](https://distri.js.org)
**Wanna say something? Leave message here:** It's `distri.min.js` in the build folder.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Flarp** [comment]
Just realized libraries must be popular. My bad.

**Comment by clairetsai818** [comment]
@Flarp  I recommend you to open a new issue when this library has more popularity. Thanks for your contribution!
cc @PeterDaveHello
