### ISSUE TITLE
[Request] https://github.com/ergec/jQuery-for-PhotoSwipe 

### ISSUE THREAD

**Issue by intermedion** [cdnjs/cdnjs#9862]
**Library name:** 
jQuery-for-PhotoSwipe

**Git repository url:**
https://github.com/ergec/jQuery-for-PhotoSwipe

**npm package url(optional):** 
-

**License(s):**
MIT License

**Official homepage:**
https://ergec.github.io/jQuery-for-PhotoSwipe/

**Wanna say something? Leave message here:**
Easy to use jQuery wrapper for PhotoSwipe. Unlike the original photoSwipe, it does not need image dimensions.

**Comment by sufuf3** [comment]
Hi @intermedion!
This library doesn't have enough popularity (like more than 100 stars on GitHub or 500 downloads per month on npm). Please take a look at our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md). Would you mind to open an issue again when the library has more popularity? If there are no response in 7 days, I will close this issue. Thanks for your great work and contribution.

**Comment by sufuf3** [comment]
Close due to no response. 
cc @PeterDaveHello
