### ISSUE TITLE
[Request] Add Angular Elastic Input  

### ISSUE THREAD

**Issue by viktorzavadil** [cdnjs/cdnjs#9867]
**Library name:** Angular Elastic Input 
**Git repository url:** https://github.com/jacek-pulit/angular-elastic-input
**NPM package url:** https://www.npmjs.com/package/angular-elastic-input
**License(s):** MIT license
**Official homepage:** http://jacek-pulit.github.io/angular-elastic-input/

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by pvnr0082t** [comment]
@hare1039 You can take this.

**Comment by hare1039** [comment]
@pvnr0082t Okey. And I created a PR(#10126) for this. Would you like to review it?

**Comment by PeterDaveHello** [comment]
@hare1039 s/Would you like/Would you please/
