### ISSUE TITLE
[Request] Add v-mask

### ISSUE THREAD

**Issue by PedroFelipe** [cdnjs/cdnjs#9870]
**Library name:** v-mask
**Git repository url:** https://github.com/probil/v-mask
**npm package url:** https://www.npmjs.com/package/v-mask
**License(s):** MIT License
**Official homepage:** https://github.com/probil/v-mask

**Comment by hare1039** [comment]
Hi @PedroFelipe,
This library seems not used as a front-end library. Can you tell us how you want to use the library?

**Comment by trevorhreed** [comment]
I can show you how I intent to use it: https://rawgit.com/probil/v-mask--demo/master/dist/index.html
