### ISSUE TITLE
[Request] Add react-datagrid 

### ISSUE THREAD

**Issue by jeremypocket** [cdnjs/cdnjs#9873]
**Library name:** react-datagrid
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@jeremypocket do you mean this lib?
https://github.com/zippyui/react-datagrid
https://www.npmjs.com/package/react-datagrid

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.

**Comment by MattIPv4** [comment]
Library appears to be unmaintained & requires a paid license, closing.
