### ISSUE TITLE
summernote

### ISSUE THREAD

**Issue by YUER1127** [cdnjs/cdnjs#9875]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@YUER1127 Any detail?

**Comment by maruilian11** [comment]
@YUER1127 do you mean this lib? https://cdnjs.com/libraries/summernote

**Comment by maruilian11** [comment]
close due to no response.
