### ISSUE TITLE
[Request] Add css-to-pdf

### ISSUE THREAD

**Issue by devshark** [cdnjs/cdnjs#9876]
**Library name:** css-to-pdf
**Git repository url:** https://github.com/Xportability/css-to-pdf
**npm package url(optional):** 
**License(s):** 
**Official homepage:** http://www.cloudformatter.com/css2pdf
**Wanna say something? Leave message here:**
I do not own this repository, I just came across of this and thought it would be nice if this was available on cdn.js 

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@sufuf3 @PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
Close due to no response from upstream.
