### ISSUE TITLE
[Request] Add qrcode 

### ISSUE THREAD

**Issue by fmgoncalves** [cdnjs/cdnjs#9878]
**Library name:** qrcodejs
**Git repository url:** https://github.com/davidshimjs/qrcodejs
**License(s):** MIT License
**Official homepage:** https://davidshimjs.github.io/qrcodejs/

**Comment by PeterDaveHello** [comment]
ping @pvnr0082t

**Comment by pvnr0082t** [comment]
Waiting for response from https://github.com/davidshimjs/qrcodejs/issues/96. cc @PeterDaveHello

**Comment by ryh** [comment]
Looks @davidshimjs did not update his repo at all, any forker to maintain?

**Comment by PeterDaveHello** [comment]
Don't know yet, I'll take care of it later.

**Comment by sashberd** [comment]
@PeterDaveHello How about to use https://github.com/CatTail/qrcodejs?
