### ISSUE TITLE
[Request] Add html5gallery 

### ISSUE THREAD

**Issue by PaoloFalomo** [cdnjs/cdnjs#9883]
**Library name:** html5gallery
**Git repository url:** 
**npm package url(optional):** 
**License(s):**
**Official homepage:** 
https://html5box.com/html5gallery/#quickinstallation

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t I cannot find this library on neither github nor npm. How can we host this library?

**Comment by PeterDaveHello** [comment]
@hare1039 So you should ask if the issuer can provide the details.

**Comment by hare1039** [comment]
@PeterDaveHello Okey.
@PaoloFalomo Can you give us more detail about this library?

**Comment by PaoloFalomo** [comment]
Hi @hare1039 ,

sure:
## jQuery Image and Video Gallery Plugin 

- Fully responsive and supports desktop, iPhone, iPad, Andorid and all modern web browsers.
- A perfect combination of HTML5, CSS3, Flash and jQuery, easy to install and easy to configure
- The first Gallery that supports images, YouTube, Vimeo, mp4, m4v, flv, ogg, ogv and webm videos in one gallery and works on mobile, tablets and all web browsers

- The only Gallery that supports Google Analytics Logging, LightBox effect and social media integration

This library is not available on github. NOTE this is not a full open-source library: https://html5box.com/order.php

i might be wrong on suggest to post it on cdnjs 😿  but it's a good library that has the free version.

**Comment by PeterDaveHello** [comment]
So what's its license for non-comercial usage?

**Comment by hare1039** [comment]
@PeterDaveHello I think we can't host it without written permission of Magic Hills Pty Ltd.
https://html5box.com/terms.php#eula
(c) You may not redistribute, modify or resell the PRODUCTS in any way without the written permission of Magic Hills Pty Ltd.

**Comment by PeterDaveHello** [comment]
@PaoloFalomo as you can see, that's not what we can host.

**Comment by maruilian11** [comment]
@PaoloFalomo this issue will be closed if there is no response in next 7 days. thanks.

**Comment by PaoloFalomo** [comment]
@maruilian11 ok! I think there's no reply. This library might not be addable. @hare1039 is right.

**Comment by maruilian11** [comment]
thanks!
