### ISSUE TITLE
[Request] Add cheerio 

### ISSUE THREAD

**Issue by JorgeCapillo** [cdnjs/cdnjs#9884]
**Library name:** cheerio
**Git repository url:** https://github.com/cheeriojs/cheerio
**npm package url(optional):**  https://www.npmjs.com/package/cheerio
**License(s):** MIT
**Official homepage:** https://cheerio.js.org/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping @kennynaoh
