### ISSUE TITLE
[Request] Add object-fit-images 

### ISSUE THREAD

**Issue by blashstar** [cdnjs/cdnjs#9885]
**Library name:** object-fit-images
**Git repository url:** https://github.com/bfred-it/object-fit-images/
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
ping @extend1994

**Comment by bfred-it** [comment]
This is a 1KB library, do you really want to load this in a separate request?

**Comment by PeterDaveHello** [comment]
@bfred-it I think it's cool since we support http/2.0 and spdy 😄
