### ISSUE TITLE
[Request] Add angular-moment-picker 

### ISSUE THREAD

**Issue by PavelTyk** [cdnjs/cdnjs#9886]
**Library name:** angular-moment-picker
**Git repository url:** https://github.com/indrimuska/angular-moment-picker
**npm package url(optional):** 
**License(s):**
**Official homepage:** https://indrimuska.github.io/angular-moment-picker/
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@qwe19272375 Please take this.
