### ISSUE TITLE
[Request] Add livequery

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9889]
**Library name:** livequery
**Git repository url:** https://github.com/brandonaaron/livequery
**License(s):** MIT

**Comment by pvnr0082t** [comment]
@hare1039 You can take this.

**Comment by hare1039** [comment]
@pvnr0082t Hi, I wasn't sure which version string should I put into the `package.json` file.
Should it be `"version": "2.0.0-pre"` [ref](https://github.com/brandonaaron/livequery/blob/master/package.json#L3) or `"2.0.0"` or even the older version `"1.1.1"`?
Please help.

**Comment by pvnr0082t** [comment]
@hare1039 You should follow git tag. Use tag `1.1.1`.

**Comment by hare1039** [comment]
@pvnr0082t I've created a PR(#10146) for this library@1.1.1. Would you please to review it?
