### ISSUE TITLE
[Request] Add jquery-ui-1.8.13.slider.min.js 

### ISSUE THREAD

**Issue by yeswanthchowdary** [cdnjs/cdnjs#9893]
**Library name:** jquery-ui-1.8.13.slider.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@yeswanthchowdary What's the detail?

**Comment by yeswanthchowdary** [comment]
I need cdn link or file for this "jquery-ui-1.8.13.slider.min.js"

**Comment by PeterDaveHello** [comment]
@yeswanthchowdary I'll take a look at it, thanks
