### ISSUE TITLE
[Request] Add Mousetrap latest version

### ISSUE THREAD

**Issue by jd987** [cdnjs/cdnjs#9896]
**Library name: Mousetrap
**Git repository url: https://github.com/ccampbell/mousetrap

Project is up to 1.6.0 but the latest available here is 1.4.6

**Comment by pvnr0082t** [comment]
@PeterDaveHello v1.4.6 in cdnjs contain the files under plugin folder. ref: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/mousetrap/1.4.6
Should we get files under `plugin` folder or just fetch `mousetrap.js` and `mousetrap.min.js` for other versions?

**Comment by PeterDaveHello** [comment]
Looks like we should grab `plugins/**/mousetrap*`, even manually add the structure for v1.4.6
