### ISSUE TITLE
[Request] Add bootstrap-waitingfor.js 

### ISSUE THREAD

**Issue by yerram1990** [cdnjs/cdnjs#9899]
**Library name:** bootstrap-waitingfor.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@yerram1990 do you mean this lib? https://github.com/ehpc/bootstrap-waitingfor/tree/master/build

**Comment by pvnr0082t** [comment]
@dada0423 Please take this.

**Comment by PeterDaveHello** [comment]
Move to #10403
