### ISSUE TITLE
[Request] updete animejs

### ISSUE THREAD

**Issue by zizyzhang** [cdnjs/cdnjs#9905]
**Library name:**  animejs
**Git repository url:** https://github.com/juliangarnier/anime
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://anime-js.com
**Wanna say something? Leave message here:**
Thank you!
=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
hi @zizyzhang, this lib is already on cdnjs.
https://cdnjs.com/libraries/animejs

**Comment by zizyzhang** [comment]
Hi,


The library on cdnjs is outdated.


I hope it can be updated soon.


Thx!



Zizy
Ming - Chuan University
Department of Information Management
tel：(+886)0909231428


________________________________
发件人: Una Ma <notifications@github.com>
发送时间: 2016年12月8日 14:19
收件人: cdnjs/cdnjs
抄送: Zizy; Mention
主题: Re: [cdnjs/cdnjs] [Request] updete animejs (#9905)


hi @zizyzhang<https://github.com/zizyzhang>, this lib is already on cdnjs.
https://cdnjs.com/libraries/animejs

―

**Comment by PeterDaveHello** [comment]
@zizyzhang We'll update it ASAP, thanks.
