### ISSUE TITLE
ColumnFilterWidgetsTracking.js

### ISSUE THREAD

**Issue by kishangandhi** [cdnjs/cdnjs#9907]
**Library name:** 
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by Piicksarn** [comment]
@kishangandhi, we need more detail, thanks.

**Comment by maruilian11** [comment]
Hi @kishangandhi, Do you mean this lib? https://github.com/cyberhobo/ColumnFilterWidgets/tree/master/media/js

**Comment by MattIPv4** [comment]
Unclear what this request is for, didn't follow template. Cloisng.
