### ISSUE TITLE
[Request] Add simplebar 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9917]
**Library name:** simplebar
**Git repository url:** https://github.com/Grsmto/simplebar 
**License(s):** MIT
**Official homepage:** https://grsmto.github.io/simplebar/

For beginners who is interested in picking up this issue:

In this issue, we are going to host a new web front-end library on CDNJS, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start pulling cdnjs repository with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are so many files in this repo, without sparseCheckout, the whole process will be slow and will use more than 80GB disk space, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#d-adding-a-new-library-with-its-assets
 - https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#e-adding-a-new-library-by-a-single-packagejson

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄

**Comment by gmanideep1991** [comment]
Hello @PeterDaveHello , this is first time working with open source projects i would like to help you guys and also learn myself. Thanks.

**Comment by PeterDaveHello** [comment]
@gmanideep1991 Thank you, feel free to ask for help when you need it.

**Comment by gmanideep1991** [comment]
Hey @PeterDaveHello , if i am not wrong we need to add all the version from 1.0 to latest right?

**Comment by PeterDaveHello** [comment]
@gmanideep1991 Actually we will just add the latest one manually, with auto update config, and our bot or I will pick the old versions via autoupdater, unless the config is not suit to the old versions, you can takr a look at the closed PRs as example!

**Comment by gmanideep1991** [comment]
@PeterDaveHello i added all the files as per the doc minified and everything but for some reason it would not show up in github. And does the package.json should be same as the one as main repo ones right? i could not figure out how to modify package.json and also does autoupdate needs to be added or not?

**Comment by PeterDaveHello** [comment]
`package.json` don't need to be the same one, can be tuned as what we need, auto-update config need to be added, thanks.

**Comment by PeterDaveHello** [comment]
@pvnr0082t @kennynaoh will also help you if you need any instructions :smile:
