### ISSUE TITLE
[Request] Add currency-flags

### ISSUE THREAD

**Issue by HLFH** [cdnjs/cdnjs#9920]
**Library name:** currency-flags.min.css
**Git repository url:*https://github.com/transferwise/currency-flags*
**License(s):*MIT https://github.com/transferwise/currency-flags/blob/master/LICENSE*
**Official homepage:*https://github.com/transferwise/currency-flags*
**Wanna say something? Leave message here:**
It would be cool to support this library. I need it to play with Cloudflare and WordPress.

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
@sufuf3 don't forget to clean up the title.

**Comment by sufuf3** [comment]
OK, Thanks.
Close issue because this PR is merged.  cc @PeterDaveHello
