### ISSUE TITLE
[Request] Add chartjs-plugin-annotation 

### ISSUE THREAD

**Issue by compwright** [cdnjs/cdnjs#9921]
**Library name:** chartjs-plugin-annotation
**Git repository url:** https://github.com/chartjs/chartjs-plugin-annotation
**npm package url(optional):** https://www.npmjs.com/package/chartjs-plugin-annotation
**License(s):** MIT
**Official homepage:** https://github.com/chartjs/chartjs-plugin-annotation
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by clairetsai818** [comment]
@PeterDaveHello I found that this library doesn't have enough popularity.

**Comment by PeterDaveHello** [comment]
Looks fine as it's plugin of https://github.com/chartjs/Chart.js, but if you have concerns, should send the PR after confirmation, not ask after sent it.
