### ISSUE TITLE
[Request] Other asynquence files need to be exposed

### ISSUE THREAD

**Issue by getify** [cdnjs/cdnjs#9925]
**Library name:** asynquence-contrib 
**Git repository url:** https://github.com/getify/asynquence/tree/master/contrib
**npm package url(optional):** https://www.npmjs.com/package/asynquence-contrib 
**License(s):** MIT
**Official homepage:** https://github.com/getify/asynquence/tree/master/contrib
**Wanna say something? Leave message here:** This is the companion package (optional plugins) for *asynquence* which is already in this CDN.

This package actually needs two files to be exposed via the CDN (`main` is transpiled for ES<=5, but there's also an ES6 version). I couldn't figure out from the README how to specify both files, or if this is even supported. The two files are:

contrib.js   (ES<=5)
contrib-es6.src.js   (ES6+)

As a matter of fact, there's a third file that would be nice to expose, too. It's a common subset of the contrib plugins, as a matter of convenience for some users.

contrib-common.js

All 3 of these files are in the npm package, and are auto-built on each new version. None of them are in the github repo.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@PeterDaveHello 
There are two npm packages point to the same git repo([getify/asynquence](https://github.com/getify/asynquence)).
Both npm packages are launched by the author(getify). 
https://www.npmjs.com/package/asynquence
https://www.npmjs.com/package/asynquence-contrib

How about we solve this problem by adding `asynquence-contrib` as a new library with npm auto-update?

**Comment by PeterDaveHello** [comment]
Let's just add `asynquence-contrib`

**Comment by getify** [comment]
I still have the request that the asynquence-contrib be able to expose multiple files. Is that possible?

**Comment by PeterDaveHello** [comment]
@getify I didn't get your point here, can't adding `asynquence-contrib` meet your request?

**Comment by getify** [comment]
The `asynquence-contrib` package has 3 files in it that need to be exposed. As I was reading the documentation, it seems like only the file specified in a `main` property of `package.json` can be made available from a package. Am I wrong on that?

**Comment by PeterDaveHello** [comment]
There are many files in `asynquence-contrib`, I don't think we'll only add the file mentioned by `main`

**Comment by maruilian11** [comment]
@getify I'm going to add `asynquence-contrib`, I want to confirm that do we only need to add `contrib.js`, `contrib-es6.src.js` and `contrib-common.js` to cdnjs? Or there are other files could be put on cdnjs, like `contrib-wrapper.js` or `plugin.after.js`. 
We can add multiple files as many as you want, if there are available for CDN.

**Comment by getify** [comment]
Just the three (`contrib.js`, `contrib-common.js`, and `contrib-es6.src.js`) should be made available. Thanks!

--------

As a separate note, `contrib.js` has some functionality in it that, if used, requires users to have the **regenerator** lib (for the transpiled generators) loaded. I noticed that regenerator is not on cdnjs, but it'd be great to have, because lots of libs that are babel-transpiled and use generators end up relying on it.

**Comment by maruilian11** [comment]
@getify do you mean this [`regenerator`](https://www.npmjs.com/package/regenerator)? 
we can also add this lib to cdnjs. could you please tell us what file you need in this lib, I want to confirm this to avoid not adding them.

btw, could you also consider generating `contrib-es6.src.js`'s minified file?
because we usually generate minified files for user if the lib author doesn't provide.
but our bot can only generate minified files for files in the same folder/path.

**Comment by getify** [comment]
Sorry for my delay in responding.

> do you mean this regenerator?

Actually, this one: https://www.npmjs.com/package/regenerator-runtime

> could you please tell us what file you need in this lib

I'm fairly sure it's just "runtime.js" from that package. The other .js files look to only be related to node usage.

> could you also consider generating contrib-es6.src.js's minified file in every version?

I would love to, and it's certainly my plan. The problem is that uglify's stable release doesn't yet support ES6 syntax.

> if you don't have time to do that, we can choose:
>
> 1. not provide contrib-es6.src.js's minified file.
> 2. add its minified file manually for every version on cdnjs.

I would prefer (1) for now, until stable uglify supports ES6 at which point I will begin generating the minified version myself on npm publish.

> which means contrib.src.js and contrib-common.src.js will be minified again by the bot.

That's OK, but I do provide those minified files, so I guess I'd prefer if you just made those available rather than re-minifying. I test against my minified files, and I'd rather not distribute different files just in the off case there was some bug introduced by one minification that wasn't what I tested. :)

**Comment by maruilian11** [comment]
I add asynquence-contrib first, and I will add regenerator-runtime in another PR.

**Comment by getify** [comment]
Thanks!!
