### ISSUE TITLE
[Request] Add shave 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9927]
**Library name:** shave
**Git repository url:** https://github.com/dollarshaveclub/shave
**npm package url(optional):** shave 
**License(s):** MIT
**Official homepage:** https://dollarshaveclub.github.io/shave/

**Comment by mercyg** [comment]
Hi @PeterDaveHello  I would like to help on this issue. Could you please guide me on where I would start?

**Comment by PeterDaveHello** [comment]
@mercyg sure! @pvnr0082t & @kennynaoh will also help you here.

In this issue, we are going to host a new library on cdnjs, may I know how do you know about git and GitHub flow? If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, instead, you can also just do it on GitHub, but it may be a little bit hard to fix problems on GitHub gui.

Here are the docs about how to add a library:
https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

Tell me what kind of help you'll need, thanks.

**Comment by mercyg** [comment]
@PeterDaveHello I am a beginner for contributing to open source projects and also I have been working with git for a few months now.

**Comment by PeterDaveHello** [comment]
@mercyg So which one you prefer to use to solve this issue? git command line or GitHub gui?

**Comment by mercyg** [comment]
I prefer working on git command line.

**Comment by PeterDaveHello** [comment]
@mercyg Awesome, then we can start from the sparseCheckout (and also shallow clone, in the same doc), but please make sure you have good internet connection and enough disk space since you'll need to download about 2.7 GB content!

**Comment by mercyg** [comment]
@PeterDaveHello  Ok , thank you.

**Comment by PeterDaveHello** [comment]
@mercyg No problem, feel free to ask for help, if the doc is not clear enough, feel free to ask for help, since I'm not native in English, so maybe you can even help us improve the doc :D

**Comment by mercyg** [comment]
@PeterDaveHello cool, English is not my first language either but I will try :)

**Comment by PeterDaveHello** [comment]
@mercyg looks like @JamesHealdUK already sent a PR - #9998, not sure if you have started it, just remind you to prevent you guys send duplicated PR.

**Comment by mercyg** [comment]
@PeterDaveHello I haven't started working on it. I will try to work on another issue :)

**Comment by PeterDaveHello** [comment]
@mercyg Great, let's do it!
