### ISSUE TITLE
[Request] Add d3kit-timeline 

### ISSUE THREAD

**Issue by RafaelDeJongh** [cdnjs/cdnjs#9929]
**Library name:** d3kit-timeline
**Git repository url:** https://raw.githubusercontent.com/kristw/d3kit-timeline/master/dist/d3kit-timeline.min.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t Can I add this library?

**Comment by PeterDaveHello** [comment]
@hare1039 go ahead
