### ISSUE TITLE
[Request] Add modernizr-2.6.1-respond-1.1.0.min.js

### ISSUE THREAD

**Issue by zanteweb** [cdnjs/cdnjs#9930]
**Library name:** modernizr-2.6.1-respond-1.1.0.min.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
@zanteweb `modernizr-2.6.1-respond-1.1.0.min.js` seems like a custom build file, if this file is not on git repo or npm package, we can't get them with our auto-update config.
@PeterDaveHello please take a look, thanks!

**Comment by qwe19272375** [comment]
@PeterDaveHello I think this issue can be closed as it is a custom build file. The following url is what I found.

https://gist.github.com/Eomerx/9934758#file-modernizr-2-6-2-respond-1-1-0-min-js-L1

**Comment by PeterDaveHello** [comment]
Thank you both!
