### ISSUE TITLE
[Request] Add materialize.min.js 

### ISSUE THREAD

**Issue by bradgillap** [cdnjs/cdnjs#9932]
**Library name:** materialize.min.js
**Git repository url:** https://github.com/Dogfalo/materialize/blob/master/dist/js/materialize.min.js
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://materializecss.com/
**Wanna say something? Leave message here:**

You have the materialize.min.css but not the .js

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@bradgillap Are you looking for this `https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js` ?

**Comment by hare1039** [comment]
@bradgillap We now have the latest version `0.98.0` `https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js`, what else can we help you?
This issue will close if no response in next 7 days.

**Comment by maruilian11** [comment]
close due to no response.
