### ISSUE TITLE
[Request] Add jQuery ScrollUp

### ISSUE THREAD

**Issue by glowworms** [cdnjs/cdnjs#9934]
**Library name:**  jQuery ScrollUp
**Git repository url:** https://github.com/markgoodyear/scrollup
**npm package url(optional):** 
**License(s):**
**Official homepage:** http://markgoodyear.com/labs/scrollup/
**Wanna say something? Leave message here:** This library is used by many templates.

JSDelivr is hosting it here: http://www.jsdelivr.com/projects/jquery.scrollup

Thank you.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
@pvnr0082t Can I add this library?
