### ISSUE TITLE
[Request] vertx-eventbus.js

### ISSUE THREAD

**Issue by nielsbaloe** [cdnjs/cdnjs#9935]
Library name:  vertx-eventbus.js
npm package: https://registry.npmjs.org/vertx3-eventbus-client/-/vertx3-eventbus-client-3.3.3.tgz
Official homepage: http://vertx.io/docs/vertx-sockjs-service-proxy/java/
Super thanks, it has not been updated on the CND since version 2.0.

**Comment by maruilian11** [comment]
git repo https://github.com/vert-x3/vertx-bus-bower

**Comment by nielsbaloe** [comment]
thanks for the notification!


________________________________
