### ISSUE TITLE
[Request] Materialize-Autocomplete

### ISSUE THREAD

**Issue by striff** [cdnjs/cdnjs#9940]
**Library name: materialize-autocomplete
**Git repository url: https://github.com/icefox0801/materialize-autocomplete
**npm package url(optional): https://www.npmjs.com/package/materialize-autocomplete
**License(s): http://spdx.org/licenses/MIT
**Official homepage: https://icefox0801.github.io/materialize-autocomplete/

**Comment by kennynaoh** [comment]
@sufuf3 Please take this
