### ISSUE TITLE
[Request] Add infobubble 

### ISSUE THREAD

**Issue by gsknbabu** [cdnjs/cdnjs#9941]
**Library name:** infobubble
**Git repository url:**https://github.com/googlemaps/v3-utility-library/blob/master/infobubble/src/infobubble-compiled.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sashberd** [comment]
@sufuf3  @PeterDaveHello Suggest to close sine there is no answer from author on request add git tag and time passed from current request was opened

**Comment by PeterDaveHello** [comment]
Let's close due to no response from https://github.com/googlemaps/v3-utility-library/issues/366, we can reopen once that issue got fixed.
