### ISSUE TITLE
[Request] r-script

### ISSUE THREAD

**Issue by hemans** [cdnjs/cdnjs#9946]
**Library name:r-script 
**Git repository url: https://github.com/joshkatz/r-script
**npm package url(optional):r-script
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
Hello @hemans 
This library doesn't have notable popularity(100 watch or star is a good example).
Please take a look on our [README.md](https://github.com/cdnjs/cdnjs/blob/master/README.md) for detail.
Would you mind to open an issue again when the library has more popularity?
Thanks for your great work and contribution.

**Comment by sashberd** [comment]
@PeterDaveHello @maruilian11 Still low popularity. Suggest to close

**Comment by PeterDaveHello** [comment]
My concern is it looks not suitable for the browsers to run. Anyway, close due to no response.
