### ISSUE TITLE
[Request] Add readingTime 

### ISSUE THREAD

**Issue by hdiwan** [cdnjs/cdnjs#9950]
**Library name:** readingTime
**Git repository url:** https://github.com/michael-lynch/reading-time.git
**npm package url(optional):**  
**License(s):** MIT
**Official homepage:** https://github.com/michael-lynch/reading-time
**Wanna say something? Leave message here:** n/a

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@lcd78706 Please take this.
