### ISSUE TITLE
[intern3] Add badges

### ISSUE THREAD

**Issue by pvnr0082t** [cdnjs/cdnjs#9953]
Add badge for the intern3 practice

- [x] 10up-sanitize.css https://github.com/jonathantneal/sanitize.css
- [x] 16pixels https://github.com/englishextra/16pixels
- [x] 3Dmol.js https://github.com/3dmol/3Dmol.js
- [x] 960gs https://github.com/nathansmith/960-Grid-System
- [x] Allofthelights.js https://github.com/Pierrinho/Allofthelights.js
- [x] AniJS https://github.com/anijs/anijs
- [x] Backbone.dualStorage https://github.com/nilbus/Backbone.dualStorage
- [x] Base64 https://github.com/davidchambers/Base64.js
- [x] BigVideo.js https://github.com/dfcb/BigVideo.js

**Comment by dada0423** [comment]
10up-sanitize.css

**Comment by sajochiu** [comment]
AniJS

**Comment by x112358** [comment]
16pixels

**Comment by NiniHsu** [comment]
BigVideo.js

**Comment by emmy41124** [comment]
Base64

**Comment by lcd78706** [comment]
babel

**Comment by qwe19272375** [comment]
3Dmol.js

**Comment by sufuf3** [comment]
960gs

**Comment by lcd78706** [comment]
Allofthelights.js

**Comment by dada0423** [comment]
Backbone.dualStorage

**Comment by PeterDaveHello** [comment]
Are we done here?

**Comment by sashberd** [comment]
@PeterDaveHello I checked infront of cdnjs website... All libraries are hosted. Close this issue
