### ISSUE TITLE
[Request] Add jquery.loadingModal.js 

### ISSUE THREAD

**Issue by Sensiblemnd** [cdnjs/cdnjs#9955]
**Library name:** jquery.loadingModal.js
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by maruilian11** [comment]
do you mean this lib?
https://github.com/do-web/jquery-loadingModal/tree/master/js

if you do, the lib doesn't get enough popularity yet. (like more than 100 stars on GitHub or 500 downloads per month on npm).I'll respectfully suggest you to open a new issue again when the library has some notable popularity.

**Comment by Sensiblemnd** [comment]
Thanks for the comment

**Comment by maruilian11** [comment]
@Sensiblemnd thank you, then I close this issue now.
