### ISSUE TITLE
[Request] Add responsive-tabs 

### ISSUE THREAD

**Issue by sfacets** [cdnjs/cdnjs#9957]
**Library name:** responsive-tabs
**Git repository url:** https://github.com/callmenick/responsive-tabs
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by hare1039** [comment]
Hi @sfacets,
We're sorry that we can't host this library since it doesn't have enough notable popularity(100 stars on github / npm 500 downloads per month). If you think we really need to host it, please contact PeterDaveHello, the maintainer of cdnjs.

**Comment by hare1039** [comment]
Feel free to show some other references if you want to discuss more with us. If there is no response in next 7 days, this issue will be closed.

Thanks for being interested in CDNJS.

**Comment by hare1039** [comment]
Close due to no response in 7 days. cc @PeterDaveHello
