### ISSUE TITLE
[Request] Add crypto-js 

### ISSUE THREAD

**Issue by evanvosberg** [cdnjs/cdnjs#9958]
**Library name:** CryptoJS
**Git repository url:** https://github.com/brix/crypto-js
**npm package url(optional):** https://www.npmjs.com/packages/crypto-js
**License(s):** MIT
**Official homepage:** https://github.com/brix/crypto-js
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@evanvosberg is it based on cdnjs's crypto-js?  
I saw the brix/crypto-js library initialized repository based on CryptoJS 3.1.2.  
And cdnjs has CryptoJS v3.1.2 from https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/crypto-js , it's homepage is http://code.google.com/p/crypto-js
