### ISSUE TITLE
[Request] Add libphonenumber-js

### ISSUE THREAD

**Issue by aloisdg** [cdnjs/cdnjs#9962]
**Library name:** libphonenumber-js
**Git repository url:** https://github.com/halt-hammerzeit/libphonenumber-js
**npm package url(optional):** https://www.npmjs.com/package/libphonenumber-js
**License(s):** MIT
**Official homepage:** https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/README.md
**Wanna say something? Leave message here:** libphonenumber-js is a port of an Android library made by Google. The original library is quite popular. There are [others](https://github.com/cdnjs/cdnjs/issues?utf8=%E2%9C%93&q=libphonenumber) so it may not be that needed.

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
@PeterDaveHello This lib has added. ref: https://github.com/cdnjs/cdnjs/pull/10201

**Comment by aloisdg** [comment]
Thank you
