### ISSUE TITLE
[Request] Add microplugin.js 

### ISSUE THREAD

**Issue by PeterDaveHello** [cdnjs/cdnjs#9973]
**Library name:** microplugin.js
**Git repository url:** https://github.com/brianreavis/microplugin.js
**npm package url(optional):** microplugin
**License(s):** Apache-2.0

In this issue, we are going to host a new web front-end library on cdnjs, so that web developer can easily use it on our free CDN without additional download/upload process 🚀 .

If you'll like to work locally, I'll suggest you start with sparseCheckout: https://github.com/cdnjs/cdnjs/blob/master/documents/sparseCheckout.md, since there are too many files in this repo, without sparseCheckout, the whole process will be super slow, using git command line can learn more skills and experience, if you don't like that, instead, you can also just do it on GitHub, it's more convenient, but it may be a little bit harder to fix problems on GitHub gui.

Here are the docs about how to add a library:
 - https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library
 - https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md#d-adding-a-new-library

We'll also ask to setup auto-update config so that the added libraries can be updated to the latest version easily:
 - https://github.com/cdnjs/cdnjs/blob/master/documents/autoupdate.md

For beginners who is interested in join and help add this library, please feel free to tell me what kind of help you'll need, we'll help you send the valid pull request, thanks 😄 .

**Comment by mercyg** [comment]
@PeterDaveHello I want to help on this issue

**Comment by mercyg** [comment]
@PeterDaveHello I was trying to work locally and on the third instruction it says that set what you want to checkout only. I am confused on what I have to checkout for this issue?

**Comment by PeterDaveHello** [comment]
@mercyg Just use the xonfig as example will be fine.

**Comment by mercyg** [comment]
@PeterDaveHello Do I have to clone the microplugin library to add it to the cdnjs? If not, how do I add the library locally?

**Comment by PeterDaveHello** [comment]
@mercyg Sorry, I mean can, not car, just typo.

**Comment by mercyg** [comment]
@PeterDaveHello No problem, I did clone the cdnjs but I am confused on how to add the library

**Comment by PeterDaveHello** [comment]
@mercyg Read the doc yet?

**Comment by mercyg** [comment]
@PeterDaveHello Yes I did :)

**Comment by mercyg** [comment]
What I am confused about is how to get the microplugin library and add it to the cdnjs

**Comment by mercyg** [comment]
@PeterDaveHello I figured how to add the file and made my pull request please check it and let me know what you think :)

**Comment by PeterDaveHello** [comment]
cc #10576
