### ISSUE TITLE
[Request] Add post-robot

### ISSUE THREAD

**Issue by maxali** [cdnjs/cdnjs#9977]
post-robot
https://github.com/krakenjs/post-robot
https://www.npmjs.com/package/post-robot

**Comment by dakshshah96** [comment]
Hey @bluepnume, Can this library be used directly in the browser?

**Comment by bluepnume** [comment]
@dakshshah96 Yes, absolutely, it creates a `postRobot` global via UMD.

**Comment by dakshshah96** [comment]
@bluepnume Great! 😄
