### ISSUE TITLE
[Request] Add sankey.js

### ISSUE THREAD

**Issue by tmthyjames** [cdnjs/cdnjs#9983]
**Library name:** sankey.js
**Git repository url:** https://github.com/d3/d3-plugins/tree/master/sankey
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by sufuf3** [comment]
The library moved to https://github.com/d3/d3-sankey! ( https://github.com/d3/d3-plugins/blob/master/sankey/README.md )
So named the library to d3-sankey.
