### ISSUE TITLE
[Request] Split.js

### ISSUE THREAD

**Issue by ihsinhw** [cdnjs/cdnjs#9986]
**Library name:** Split.js
**Git repository url:**https://github.com/nathancahill/Split.js
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**
plz, thank you.

**Comment by nolsherry** [comment]
@x112358, please take this, thanks!

**Comment by x112358** [comment]
i will take it after finishing another PR

**Comment by PeterDaveHello** [comment]
@x112358 Cool!

**Comment by maruilian11** [comment]
Has been added in aba39a73780eab24a7d3f6355de0b6db55d63076
