### ISSUE TITLE
[Request] Add hernansartorio/jquery-nice-select 

### ISSUE THREAD

**Issue by mashuble** [cdnjs/cdnjs#9988]
**Library name:** hernansartorio/jquery-nice-select
**Git repository url:**
**npm package url(optional):** 
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #9592
