### ISSUE TITLE
[Request] Add MixItUp

### ISSUE THREAD

**Issue by patrickkunka** [cdnjs/cdnjs#9989]
**Library name: MixItUp** 
**Git repository url: https://github.com/patrickkunka/mixitup**
**npm package url(optional): https://www.npmjs.com/package/mixitup** 
**License(s): proprietary**
**Official homepage: https://www.kunkalabs.com/mixitup**
**Wanna say something? Leave message here:**

Hi guys,

MixItUp already exists on CDNJS, but the latest major version v3 does not seem to have been picked up – perhaps because v3 is now the default branch, not master. As we've dropped jQuery the description of the package is a little different now too.

Thanks

=====================
Notes from cdnjs maintainer:
Please read the README.md and CONTRIBUTING.md document first.

You are welcome to add a library via sending pull request,
it'll be faster than just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@lcd78706 Please take this.

**Comment by sashberd** [comment]
@maruilian11 @PeterDaveHello I think this one is already [exists](https://cdnjs.com/libraries/mixitup). Suggest to close

**Comment by PeterDaveHello** [comment]
The problem is this lib is dated.
