### ISSUE TITLE
[Request] Add jquery-animateNumber

### ISSUE THREAD

**Issue by vinch** [cdnjs/cdnjs#9990]
**Library name:** jquery-animateNumber
**Git repository url:** https://github.com/aishek/jquery-animateNumber
**npm package url(optional):** 
**License(s):** MIT
**Official homepage:** http://aishek.github.io/jquery-animateNumber
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by kennynaoh** [comment]
@x112358 Please take this.
