### ISSUE TITLE
[Request] Add Vue Material

### ISSUE THREAD

**Issue by marcosmoura** [cdnjs/cdnjs#9992]
**Library name:** Vue Material
**Git repository url:** https://github.com/marcosmoura/vue-material
**npm package url(optional):** https://www.npmjs.com/package/vue-material
**License(s):** MIT
**Official homepage:** https://vuematerial.github.io

**Comment by ChuanfengZhang** [comment]
@marcosmoura It's official homepage has been changed into https://vuematerial.io/
