### ISSUE TITLE
[Request] Add algebra.js

### ISSUE THREAD

**Issue by xadamxk** [cdnjs/cdnjs#9993]
**Library name:** algebra
**Git repository url:**https://github.com/nicolewhite/algebra.js
**npm package url(optional):** https://badge.fury.io/js/algebra.js
**License(s):**
**Official homepage:**
**Wanna say something? Leave message here:**

=====================
Notes from cdnjs maintainer:
You are welcome to add a library via sending pull request,
it'll be faster then just opening a request issue,
and please don't forget to read the guidelines for contributing, thanks!!

**Comment by PeterDaveHello** [comment]
Duplicated with #7971
